rootProject.name = "TAPAS"
include("tapas-daemon")
include("tapas")
include("io")
include("tapas-environment")
include("converter")
include("tapas-matrixtool")
include("tapas-environment-gui")
include("tapas-parameter")
include("tapas-util")
include("tapas-logger")
include("tapas-tools")
include("tapas-model")
include("tapas-analyzer")
