rootProject.name = "TAPAS"
include("tapas-server")
include("tapas")
include("configuration")
include("io")
include("service")
include("tapas-environment")
include("converter")
include("tapas-matrixtool")
include("tapas-environment-gui")
include("tapas-parameter")
include("tapas-util")
include("tapas-logger")
include("tapas-tools")
include("tapas-model")
include("tapas-analyzer")
include("tapas-installer")
include("service")
