package de.dlr.ivf.api.io.crud.write;

import de.dlr.ivf.api.io.configuration.model.DataSource;
import de.dlr.ivf.api.io.conversion.JavaToSqlTypeConverter;
import de.dlr.ivf.api.io.crud.write.implementation.IdReturningSimpleJdbcWriter;
import de.dlr.ivf.api.io.crud.write.implementation.JdbcBatchWriter;
import de.dlr.ivf.api.io.crud.write.implementation.SimpleJdbcWriter;
import de.dlr.ivf.api.io.util.PreparedStatementContext;
import de.dlr.ivf.api.io.util.PreparedStatementContextFactory;
import de.dlr.ivf.api.io.util.PreparedStatementParameterSetter;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.*;
import java.util.stream.Collectors;

public class DataWriterFactory {

    public static <S> DataWriter<S,Void> newJdbcBatchWriter(DataSource dataSource, Connection  connection, Class<S> objectType) {

        PreparedStatementContext psContext = PreparedStatementContextFactory.newPreparedStatementContext(objectType);

        PreparedStatement preparedStatement;
        try {
             preparedStatement = connection.prepareStatement(generateInsertQuery(psContext.getUpdatableColumnNames(),dataSource));
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
        return JdbcBatchWriter.<S>builder()
                .batchSize(1000)
                .connection(connection)
                .preparedStatement(preparedStatement)
                .statementParameterSetter(new PreparedStatementParameterSetter<>(psContext.getIndexedInvocableMethods(), new JavaToSqlTypeConverter()))
                .build();
    }

    public static <S> DataWriter<S,Void> newJdbcWriter(DataSource dataSource, Connection  connection, Class<S> objectType){

        PreparedStatementContext psContext = PreparedStatementContextFactory.newPreparedStatementContext(objectType);

        return SimpleJdbcWriter.<S>builder()
                .connection(connection)
                .statementParameterSetter(new PreparedStatementParameterSetter<>(psContext.getIndexedInvocableMethods(), new JavaToSqlTypeConverter()))
                .query(generateInsertQuery(psContext.getUpdatableColumnNames(), dataSource))
                .build();
    }

    public static <S> DataWriter<S, Integer> newIdReturningSimpleJdbcWriter(DataSource dataSource, Connection connectionSupplier, Class<S> objectType){

        PreparedStatementContext preparedStatementContext = PreparedStatementContextFactory.newPreparedStatementContext(objectType);
        if(preparedStatementContext.getFilterColumns().size() != 1){
            throw new IllegalArgumentException("the provided bean: '"+objectType.getName()+"' contains multiple non-ignorable fields. Can't derive the autogenerated id");
        }

        return IdReturningSimpleJdbcWriter.<S>builder()
                .connection(connectionSupplier)
                .idColumn(preparedStatementContext.getFilterColumns().toArray(String[]::new))
                .query(generateInsertQuery(preparedStatementContext.getUpdatableColumnNames(), dataSource))
                .psParameterSetter(new PreparedStatementParameterSetter<>(preparedStatementContext.getIndexedInvocableMethods(), new JavaToSqlTypeConverter()))
                .build();
    }

    private static String generateInsertQuery(List<String> columnNames, DataSource dataSource){
        //create column definition part: (col1, col2, ...)
        String sqlInsertColumnDefinition = columnNames.stream().collect(Collectors.joining(",","(",")"));
        //create parameterizable part: (?, ?, ...)
        String sqlParameterPart = columnNames.stream().map(c -> "?").collect(Collectors.joining(",","(",")"));

        return "INSERT INTO "+dataSource.getUri()+" "+sqlInsertColumnDefinition+" VALUES "+sqlParameterPart;
    }
}
