TAPAS: de.dlr.ivf.tapas.runtime.client.TextPopupEditor.TextAreaDialog Class Reference
de.dlr.ivf.tapas.runtime.client.TextPopupEditor.TextAreaDialog Class Reference
Public Member Functions
TextAreaDialog ()
String getText ()
void hide (boolean save)
void show (String oldText, Point position)
Private Attributes
final JTextArea textArea
String oldText
Static Private Attributes
static final long serialVersionUID = -704484231321328670L
static final String LEAVE_SAVE = "leave_save"
static final String LEAVE_DISCARD = "leave_discard"
static final String ENTER = "enter"
Detailed Description
Definition at line 62 of file TextPopupEditor.java.
Constructor & Destructor Documentation
TextAreaDialog()
de.dlr.ivf.tapas.runtime.client.TextPopupEditor.TextAreaDialog.TextAreaDialog ()
Definition at line 74 of file TextPopupEditor.java.
References de.dlr.ivf.tapas.runtime.client.TextPopupEditor.actionPerformed(), de.dlr.ivf.tapas.runtime.client.TextPopupEditor.TextAreaDialog.ENTER, de.dlr.ivf.tapas.runtime.client.TextPopupEditor.TextAreaDialog.hide(), de.dlr.ivf.tapas.runtime.client.TextPopupEditor.TextAreaDialog.LEAVE_DISCARD, de.dlr.ivf.tapas.runtime.client.TextPopupEditor.TextAreaDialog.LEAVE_SAVE, de.dlr.ivf.tapas.runtime.client.TextPopupEditor.TextAreaDialog.serialVersionUID, and de.dlr.ivf.tapas.runtime.client.TextPopupEditor.TextAreaDialog.textArea.
Member Function Documentation
getText()
String de.dlr.ivf.tapas.runtime.client.TextPopupEditor.TextAreaDialog.getText ()
Definition at line 143 of file TextPopupEditor.java.
References de.dlr.ivf.tapas.runtime.client.TextPopupEditor.TextAreaDialog.textArea.
Referenced by de.dlr.ivf.tapas.runtime.client.TextPopupEditor.getCellEditorValue().
hide()
void de.dlr.ivf.tapas.runtime.client.TextPopupEditor.TextAreaDialog.hide (boolean save)
Definition at line 147 of file TextPopupEditor.java.
References de.dlr.ivf.tapas.runtime.client.TextPopupEditor.TextAreaDialog.oldText, and de.dlr.ivf.tapas.runtime.client.TextPopupEditor.TextAreaDialog.textArea.
Referenced by de.dlr.ivf.tapas.runtime.client.TextPopupEditor.TextAreaDialog.TextAreaDialog().
show()
void de.dlr.ivf.tapas.runtime.client.TextPopupEditor.TextAreaDialog.show (String oldText, Point position)
Definition at line 159 of file TextPopupEditor.java.
References de.dlr.ivf.tapas.runtime.client.TextPopupEditor.TextAreaDialog.oldText, de.dlr.ivf.tapas.runtime.client.TextPopupEditor.table, and de.dlr.ivf.tapas.runtime.client.TextPopupEditor.TextAreaDialog.textArea.
Referenced by de.dlr.ivf.tapas.runtime.client.TextPopupEditor.actionPerformed().
Member Data Documentation
ENTER
final String de.dlr.ivf.tapas.runtime.client.TextPopupEditor.TextAreaDialog.ENTER = "enter" static private
Definition at line 69 of file TextPopupEditor.java.
Referenced by de.dlr.ivf.tapas.runtime.client.TextPopupEditor.TextAreaDialog.TextAreaDialog().
LEAVE_DISCARD
final String de.dlr.ivf.tapas.runtime.client.TextPopupEditor.TextAreaDialog.LEAVE_DISCARD = "leave_discard" static private
Definition at line 68 of file TextPopupEditor.java.
Referenced by de.dlr.ivf.tapas.runtime.client.TextPopupEditor.TextAreaDialog.TextAreaDialog().
LEAVE_SAVE
final String de.dlr.ivf.tapas.runtime.client.TextPopupEditor.TextAreaDialog.LEAVE_SAVE = "leave_save" static private
Definition at line 67 of file TextPopupEditor.java.
Referenced by de.dlr.ivf.tapas.runtime.client.TextPopupEditor.TextAreaDialog.TextAreaDialog().
oldText
String de.dlr.ivf.tapas.runtime.client.TextPopupEditor.TextAreaDialog.oldText private
Definition at line 72 of file TextPopupEditor.java.
Referenced by de.dlr.ivf.tapas.runtime.client.TextPopupEditor.TextAreaDialog.hide(), and de.dlr.ivf.tapas.runtime.client.TextPopupEditor.TextAreaDialog.show().
serialVersionUID
final long de.dlr.ivf.tapas.runtime.client.TextPopupEditor.TextAreaDialog.serialVersionUID = -704484231321328670L static private
Definition at line 66 of file TextPopupEditor.java.
Referenced by de.dlr.ivf.tapas.runtime.client.TextPopupEditor.TextAreaDialog.TextAreaDialog().
textArea
final JTextArea de.dlr.ivf.tapas.runtime.client.TextPopupEditor.TextAreaDialog.textArea private
Definition at line 71 of file TextPopupEditor.java.
Referenced by de.dlr.ivf.tapas.runtime.client.TextPopupEditor.TextAreaDialog.getText(), de.dlr.ivf.tapas.runtime.client.TextPopupEditor.TextAreaDialog.hide(), de.dlr.ivf.tapas.runtime.client.TextPopupEditor.TextAreaDialog.show(), and de.dlr.ivf.tapas.runtime.client.TextPopupEditor.TextAreaDialog.TextAreaDialog().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/runtime/client/TextPopupEditor.java