TAPAS: de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter Class Reference
de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter Class Reference
Static Public Member Functions
static void main (String[] args) throws IOException, DOMException
static DefaultMutableTreeNode readTree (String filename) throws IOException
static boolean writeTree (DefaultMutableTreeNode root, String filename) throws FileNotFoundException
Static Private Member Functions
static int getLevel (TreeWalker walker, Node currentNode)
static void printTree (DefaultMutableTreeNode root)
Static Private Attributes
static final String ELEMENT_ROOT = "general_analyzer"
static final String ELEMENT_FILE = "file"
static final String ELEMENT_TAB = "tab"
static final String ELEMENT_SPLIT = "split"
static final String ELEMENT_ANALYZER = "analyzer"
static final String ATTRIBUTE_NAME = "name"
static final String ATTRIBUTE_VERSION = "version"
static final String VERSION = "1.0"
Detailed Description
Definition at line 41 of file GeneralAnalyzerTreeExporter.java.
Member Function Documentation
getLevel()
static int de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.getLevel (TreeWalker walker, Node currentNode) static private
Definition at line 52 of file GeneralAnalyzerTreeExporter.java.
References de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.ELEMENT_ANALYZER, de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.ELEMENT_FILE, de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.ELEMENT_ROOT, de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.ELEMENT_SPLIT, and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.ELEMENT_TAB.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.readTree().
main()
static void de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.main (String[] args) throws IOException, DOMException static
For testing purposes only
Exceptions
IOException
DOMException
Definition at line 75 of file GeneralAnalyzerTreeExporter.java.
References de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.DistanceCategoryDefault, de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.Mode, de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.PersonGroup, de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.printTree(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.readTree(), de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.RegionCode, de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.TripIntention, and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.writeTree().
printTree()
static void de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.printTree (DefaultMutableTreeNode root) static private
for debugging only
Parameters
root
Definition at line 133 of file GeneralAnalyzerTreeExporter.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.main().
readTree()
static DefaultMutableTreeNode de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.readTree (String filename) throws IOException static
Reads an XML-file written by this class and converts it into a tree readable by TUMControlGeneral.
Parameters
filename
Returns
the root node of the created tree. May be null if the tree could not be parsed correctly.
Exceptions
IOException if the file can't be accessed.
Definition at line 155 of file GeneralAnalyzerTreeExporter.java.
References de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.ATTRIBUTE_NAME, de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.ATTRIBUTE_VERSION, de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.ELEMENT_ANALYZER, de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.getLevel(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.VERSION.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.loadTree(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.main().
writeTree()
static boolean de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.writeTree (DefaultMutableTreeNode root, String filename) throws FileNotFoundException static
Exports a tree used by TUMControlGeneral to an XML-file that can be imported again by this class.
Parameters
root
filename
Returns
true if the export is successful.
Exceptions
FileNotFoundException if there is any problem writing the file.
Definition at line 251 of file GeneralAnalyzerTreeExporter.java.
References de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.ATTRIBUTE_NAME, de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.ATTRIBUTE_VERSION, de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.ELEMENT_ANALYZER, de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.ELEMENT_FILE, de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.ELEMENT_ROOT, de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.ELEMENT_SPLIT, de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.ELEMENT_TAB, de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.AnalyzerCollection.getAnalyzers(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.AnalyzerCollection.getName(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.VERSION.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.main(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.saveTree().
Member Data Documentation
ATTRIBUTE_NAME
final String de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.ATTRIBUTE_NAME = "name" static private
Definition at line 48 of file GeneralAnalyzerTreeExporter.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.readTree(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.writeTree().
ATTRIBUTE_VERSION
final String de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.ATTRIBUTE_VERSION = "version" static private
Definition at line 49 of file GeneralAnalyzerTreeExporter.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.readTree(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.writeTree().
ELEMENT_ANALYZER
final String de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.ELEMENT_ANALYZER = "analyzer" static private
Definition at line 47 of file GeneralAnalyzerTreeExporter.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.getLevel(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.readTree(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.writeTree().
ELEMENT_FILE
final String de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.ELEMENT_FILE = "file" static private
Definition at line 44 of file GeneralAnalyzerTreeExporter.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.getLevel(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.writeTree().
ELEMENT_ROOT
final String de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.ELEMENT_ROOT = "general_analyzer" static private
Definition at line 43 of file GeneralAnalyzerTreeExporter.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.getLevel(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.writeTree().
ELEMENT_SPLIT
final String de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.ELEMENT_SPLIT = "split" static private
Definition at line 46 of file GeneralAnalyzerTreeExporter.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.getLevel(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.writeTree().
ELEMENT_TAB
final String de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.ELEMENT_TAB = "tab" static private
Definition at line 45 of file GeneralAnalyzerTreeExporter.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.getLevel(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.writeTree().
VERSION
final String de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.VERSION = "1.0" static private
Definition at line 50 of file GeneralAnalyzerTreeExporter.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.readTree(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.writeTree().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/tum/regionanalyzer/general/GeneralAnalyzerTreeExporter.java