TAPAS: de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.TripStats Class Reference
de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.TripStats Class Reference
Public Member Functions
TripStats (double dist, long cntTrips, double duration)
TripStats (TapasTrip trip)
void add (double dist, long cnt, double dur)
void add (TripStats ts)
void add (TapasTrip trip)
long getCntTrips ()
double getDist ()
double getDur ()
String toString ()
Private Attributes
double dist
long cntTrips
double duration
Detailed Description
This mutable class encapsulates distance, number of trips and total duration and offers several ways to add and create them.
Author
boec_pa
Definition at line 19 of file TripStats.java.
Constructor & Destructor Documentation
TripStats() [1/2]
de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.TripStats.TripStats (double dist, long cntTrips, double duration)
Definition at line 24 of file TripStats.java.
References de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.TripStats.cntTrips, de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.TripStats.dist, and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.TripStats.duration.
TripStats() [2/2]
de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.TripStats.TripStats (TapasTrip trip)
Definition at line 31 of file TripStats.java.
References de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTrip.getDistNet(), and de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTrip.getTT().
Member Function Documentation
add() [1/3]
void de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.TripStats.add (double dist, long cnt, double dur)
Definition at line 35 of file TripStats.java.
References de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.TripStats.dist.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.TripStats.add(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.Analyzer.getSplit().
add() [2/3]
void de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.TripStats.add (TapasTrip trip)
Definition at line 45 of file TripStats.java.
References de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.TripStats.add(), de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTrip.getDistNet(), and de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTrip.getTT().
add() [3/3]
void de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.TripStats.add (TripStats ts)
Definition at line 41 of file TripStats.java.
References de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.TripStats.add(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.TripStats.duration, de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.TripStats.getCntTrips(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.TripStats.getDist().
getCntTrips()
long de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.TripStats.getCntTrips ()
Definition at line 49 of file TripStats.java.
References de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.TripStats.cntTrips.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.TripStats.add(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getAvgDistByTrip(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.Analyzer.getSplit(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.Analyzer.getTripCnt().
getDist()
double de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.TripStats.getDist ()
Definition at line 53 of file TripStats.java.
References de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.TripStats.dist.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.TripStats.add(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getAvgDistByTrip(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.Analyzer.getDistance().
getDur()
double de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.TripStats.getDur ()
Definition at line 57 of file TripStats.java.
References de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.TripStats.duration.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.Analyzer.getDuration().
toString()
String de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.TripStats.toString ()
Definition at line 62 of file TripStats.java.
References de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.TripStats.cntTrips, de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.TripStats.dist, and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.TripStats.duration.
Member Data Documentation
cntTrips
long de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.TripStats.cntTrips private
Definition at line 21 of file TripStats.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.TripStats.getCntTrips(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.TripStats.toString(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.TripStats.TripStats().
dist
double de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.TripStats.dist private
Definition at line 20 of file TripStats.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.TripStats.add(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.TripStats.getDist(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.TripStats.toString(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.TripStats.TripStats().
duration
double de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.TripStats.duration private
Definition at line 22 of file TripStats.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.TripStats.add(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.TripStats.getDur(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.TripStats.toString(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.TripStats.TripStats().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/tum/regionanalyzer/TripStats.java