TAPAS: de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData Class Reference
de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData Class Reference
Classes
class TravelTimeParameter
Public Member Functions
CruisingSpeedCalcData ()
boolean[] getCalculation ()
void setCalculation (boolean[] calculation)
String getMatricesTable ()
void setMatricesTable (String matricesTable)
String getTazTable ()
void setTazTable (String tazTable)
String getTerrain ()
void setTerrain (String terrain)
TravelTimeParameter[] getTravelTimeParameter ()
void setTravelTimeParameter (TravelTimeParameter[] travelTimeParameter)
boolean isIndirectWayFactor ()
void setIndirectWayFactor (boolean indirectWayFactor)
boolean isTop3 ()
void setTop3 (boolean top3)
boolean iszValues ()
void setzValues (boolean zValues)
Private Attributes
String terrain = null
boolean top3 = true
String tazTable = null
String matricesTable = null
boolean indirectWayFactor = true
boolean zValues = false
boolean[] calculation = null
TravelTimeParameter[] travelTimeParameter = null
Detailed Description
Definition at line 11 of file CruisingSpeedCalcData.java.
Constructor & Destructor Documentation
CruisingSpeedCalcData()
de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.CruisingSpeedCalcData ()
Definition at line 22 of file CruisingSpeedCalcData.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.calculation, de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.setCalculation(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.setTravelTimeParameter(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.travelTimeParameter.
Member Function Documentation
getCalculation()
boolean [] de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.getCalculation ()
Definition at line 33 of file CruisingSpeedCalcData.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.calculation.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.readProperties().
getMatricesTable()
String de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.getMatricesTable ()
Definition at line 41 of file CruisingSpeedCalcData.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.matricesTable.
getTazTable()
String de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.getTazTable ()
Definition at line 49 of file CruisingSpeedCalcData.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.tazTable.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.calcDistance().
getTerrain()
String de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.getTerrain ()
Definition at line 57 of file CruisingSpeedCalcData.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.terrain.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.calcDistance().
getTravelTimeParameter()
TravelTimeParameter [] de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.getTravelTimeParameter ()
Definition at line 65 of file CruisingSpeedCalcData.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.travelTimeParameter.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.getTravelTime(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.readProperties().
isIndirectWayFactor()
boolean de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.isIndirectWayFactor ()
Definition at line 73 of file CruisingSpeedCalcData.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.indirectWayFactor.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.calcDistance().
isTop3()
boolean de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.isTop3 ()
Definition at line 81 of file CruisingSpeedCalcData.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.top3.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.start().
iszValues()
boolean de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.iszValues ()
Definition at line 89 of file CruisingSpeedCalcData.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.zValues.
setCalculation()
void de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.setCalculation (boolean[] calculation)
Definition at line 37 of file CruisingSpeedCalcData.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.calculation.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.CruisingSpeedCalcData().
setIndirectWayFactor()
void de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.setIndirectWayFactor (boolean indirectWayFactor)
Definition at line 77 of file CruisingSpeedCalcData.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.indirectWayFactor.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.calcDistance(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.readProperties().
setMatricesTable()
void de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.setMatricesTable (String matricesTable)
Definition at line 45 of file CruisingSpeedCalcData.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.matricesTable.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.calcDistance(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.readProperties().
setTazTable()
void de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.setTazTable (String tazTable)
Definition at line 53 of file CruisingSpeedCalcData.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.tazTable.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.calcDistance(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.readProperties().
setTerrain()
void de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.setTerrain (String terrain)
Definition at line 61 of file CruisingSpeedCalcData.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.terrain.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.calcDistance(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.readProperties().
setTop3()
void de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.setTop3 (boolean top3)
Definition at line 85 of file CruisingSpeedCalcData.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.top3.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.readProperties().
setTravelTimeParameter()
void de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.setTravelTimeParameter (TravelTimeParameter[] travelTimeParameter)
Definition at line 69 of file CruisingSpeedCalcData.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.travelTimeParameter.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.CruisingSpeedCalcData().
setzValues()
void de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.setzValues (boolean zValues)
Definition at line 93 of file CruisingSpeedCalcData.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.zValues.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.readProperties().
Member Data Documentation
calculation
boolean [] de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.calculation = null private
Definition at line 19 of file CruisingSpeedCalcData.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.CruisingSpeedCalcData(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.getCalculation(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.setCalculation().
indirectWayFactor
boolean de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.indirectWayFactor = true private
Definition at line 16 of file CruisingSpeedCalcData.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.isIndirectWayFactor(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.setIndirectWayFactor().
matricesTable
String de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.matricesTable = null private
Definition at line 15 of file CruisingSpeedCalcData.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.getMatricesTable(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.setMatricesTable().
tazTable
String de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.tazTable = null private
Definition at line 14 of file CruisingSpeedCalcData.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.getTazTable(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.setTazTable().
terrain
String de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.terrain = null private
Definition at line 12 of file CruisingSpeedCalcData.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.getTerrain(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.setTerrain().
top3
boolean de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.top3 = true private
Definition at line 13 of file CruisingSpeedCalcData.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.isTop3(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.setTop3().
travelTimeParameter
TravelTimeParameter [] de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.travelTimeParameter = null private
Definition at line 20 of file CruisingSpeedCalcData.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.CruisingSpeedCalcData(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.getTravelTimeParameter(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.setTravelTimeParameter().
zValues
boolean de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.zValues = false private
Definition at line 17 of file CruisingSpeedCalcData.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.iszValues(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.setzValues().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/matrixMap/CruisingSpeedCalcData.java