TAPAS: de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator Class Reference
de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator Class Reference
Classes
class ECommerceTrip
class MinimalLocation
Public Member Functions
void addActivity (int activity)
void addBRZInfos2EComHouseholds (String bzrTable)
void appendBZRInfo (String bzrTable, MinimalLocation loc)
double calcDiffDist (ECommerceTrip trip)
double calcDiffTT (ECommerceTrip trip, int mode)
void collectEComTrips (String table)
double getCorrectedMatrixVal (MinimalLocation start, MinimalLocation end, double[][] matrix)
boolean isECommerceTrip ()
boolean isShopping (int activity)
void loadMatrices (String dist, String[] tts, String table)
double[][] loadMatrix (String table, String name)
void loadTAZ (String table)
void updateEComTripsInDB (String tablename)
void writeEComHouseholds (String filename)
void writeEComTripsToDB (String tablename)
void writeEComTripsToFile (String filename)
Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_BasicConnectionClass ()
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass)
TPS_BasicConnectionClass (String loginFile)
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass, String loginFile)
boolean checkMatrixName (String matrixName)
TPS_ParameterClass getParameters ()
String readParameter (String simKey, String paramKey)
void storeInDB (String matrixName, double[][] matrix, int decimalPlaces)
Static Public Member Functions
static void main (String[] args)
Static Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
static double[][] array1Dto2D (Integer[] matrixVal)
static double[][] array1Dto2D (int[] matrixVal)
static File getRuntimeFile (boolean forceNewFile)
static File getRuntimeFile (String propertyFile, boolean forceNewFile)
static File getRuntimeFile ()
static File getRuntimeFile (String propertyFile)
static int[][] intArray1Dto2D (int[] matrixVal)
static String matrixToSQLArray (double[][] array, int decimalPlaces)
static StringWriter matrixToStringWriterSQL (double[][] array, int decimalPlaces)
Additional Inherited Members
Protected Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
void finalize ()
Protected Attributes inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_DB_Connector dbCon = null
TPS_ParameterClass parameterClass
Detailed Description
Definition at line 27 of file TPS_ECommerceEstimator.java.
Member Function Documentation
addActivity()
void de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.addActivity (int activity)
Definition at line 137 of file TPS_ECommerceEstimator.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.main().
addBRZInfos2EComHouseholds()
void de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.addBRZInfos2EComHouseholds (String bzrTable)
Definition at line 142 of file TPS_ECommerceEstimator.java.
References de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.appendBZRInfo().
appendBZRInfo()
void de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.appendBZRInfo (String bzrTable, MinimalLocation loc)
Definition at line 155 of file TPS_ECommerceEstimator.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery().
Referenced by de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.addBRZInfos2EComHouseholds().
calcDiffDist()
double de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.calcDiffDist (ECommerceTrip trip)
Definition at line 189 of file TPS_ECommerceEstimator.java.
References de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.getCorrectedMatrixVal().
Referenced by de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.collectEComTrips().
calcDiffTT()
double de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.calcDiffTT (ECommerceTrip trip, int mode)
Definition at line 194 of file TPS_ECommerceEstimator.java.
References de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.getCorrectedMatrixVal().
Referenced by de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.collectEComTrips().
collectEComTrips()
void de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.collectEComTrips (String table)
Definition at line 200 of file TPS_ECommerceEstimator.java.
References de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.calcDiffDist(), de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.calcDiffTT(), de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.getCorrectedMatrixVal(), de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.isECommerceTrip(), and de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.isShopping().
Referenced by de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.main().
getCorrectedMatrixVal()
double de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.getCorrectedMatrixVal (MinimalLocation start, MinimalLocation end, double matrix[][])
Definition at line 320 of file TPS_ECommerceEstimator.java.
References de.dlr.ivf.tapas.util.TPS_Geometrics.getDistance(), de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.getParameters(), and de.dlr.ivf.tapas.util.parameters.ParamValue.MIN_DIST.
Referenced by de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.calcDiffDist(), de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.calcDiffTT(), de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.collectEComTrips(), and de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.updateEComTripsInDB().
isECommerceTrip()
boolean de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.isECommerceTrip ()
Definition at line 335 of file TPS_ECommerceEstimator.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.collectEComTrips().
isShopping()
boolean de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.isShopping (int activity)
Definition at line 339 of file TPS_ECommerceEstimator.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.collectEComTrips().
loadMatrices()
void de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.loadMatrices (String dist, String[] tts, String table)
Definition at line 343 of file TPS_ECommerceEstimator.java.
References de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.loadMatrix().
Referenced by de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.main().
loadMatrix()
double [][] de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.loadMatrix (String table, String name)
Definition at line 353 of file TPS_ECommerceEstimator.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.array1Dto2D(), de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.extractIntArray(), and name.
Referenced by de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.loadMatrices().
loadTAZ()
void de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.loadTAZ (String table)
Definition at line 372 of file TPS_ECommerceEstimator.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), de.dlr.ivf.tapas.util.TPS_Geometrics.getDistance(), and de.dlr.ivf.tapas.util.parameters.ParamValue.MIN_DIST.
Referenced by de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.main().
main()
static void de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.main (String[] args) static
Definition at line 44 of file TPS_ECommerceEstimator.java.
References de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.addActivity(), de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.collectEComTrips(), de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.getParameters(), de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.loadMatrices(), de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.loadTAZ(), de.dlr.ivf.tapas.util.parameters.ParamValue.MIN_DIST, and de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.setValue().
updateEComTripsInDB()
void de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.updateEComTripsInDB (String tablename)
Definition at line 400 of file TPS_ECommerceEstimator.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection(), de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.getCorrectedMatrixVal(), de.dlr.ivf.tapas.util.TPS_Geometrics.getDistance(), and de.dlr.ivf.tapas.util.parameters.ParamValue.MIN_DIST.
writeEComHouseholds()
void de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.writeEComHouseholds (String filename)
Definition at line 472 of file TPS_ECommerceEstimator.java.
writeEComTripsToDB()
void de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.writeEComTripsToDB (String tablename)
Definition at line 489 of file TPS_ECommerceEstimator.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection().
writeEComTripsToFile()
void de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.writeEComTripsToFile (String filename)
Definition at line 527 of file TPS_ECommerceEstimator.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/TPS_ECommerceEstimator.java