TAPAS: de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.TypedWeightedLocationDistribution Class Reference
de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.TypedWeightedLocationDistribution Class Reference
Public Member Functions
TypedWeightedLocationDistribution ()
void addLocation (TPS_Location loc)
double getWeightSum ()
TPS_Location select ()
ArrayList< TPS_Location > selectActivityLocations (int number)
void updateOccupancy (double priorWeight, double postWeight)
Public Attributes
Vector< TPS_Location > locations = new Vector<>()
The list of locations with the same activity.
Private Member Functions
TPS_Location select (double weightSum, List< TPS_Location > from)
Private Attributes
double freeWeightSum = 0
The sum of all the weights of all locations that are within this TAZ and allow the according activity.
Detailed Description
A container for locations of the same activity type that are located in this TAZ
Definition at line 918 of file TPS_TrafficAnalysisZone.java.
Constructor & Destructor Documentation
TypedWeightedLocationDistribution()
de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.TypedWeightedLocationDistribution.TypedWeightedLocationDistribution ()
Constructor
Definition at line 928 of file TPS_TrafficAnalysisZone.java.
Member Function Documentation
addLocation()
void de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.TypedWeightedLocationDistribution.addLocation (TPS_Location loc)
Adds a location
Parameters
loc The location to add
Definition at line 936 of file TPS_TrafficAnalysisZone.java.
References de.dlr.ivf.tapas.loc.TPS_Location.getData(), and de.dlr.ivf.tapas.loc.TPS_Location.TPS_LocationData.getWeight().
getWeightSum()
double de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.TypedWeightedLocationDistribution.getWeightSum ()
Returns the sum of the stored locations weights
Returns
The sum of the locations weights
Definition at line 946 of file TPS_TrafficAnalysisZone.java.
select() [1/2]
TPS_Location de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.TypedWeightedLocationDistribution.select ()
Chooses a random location, weighted by the locations' weights
Returns
A randomly selected weighted location
Definition at line 955 of file TPS_TrafficAnalysisZone.java.
select() [2/2]
TPS_Location de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.TypedWeightedLocationDistribution.select (double weightSum, List< TPS_Location > from) private
Selects locations from the given list randomly, taking into account their weight
Parameters
weightSum The sum of the location's weights
from The list of locations to choose from
Returns
A single selected location
Definition at line 966 of file TPS_TrafficAnalysisZone.java.
References de.dlr.ivf.tapas.util.Randomizer.random().
selectActivityLocations()
ArrayList<TPS_Location> de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.TypedWeightedLocationDistribution.selectActivityLocations (int number)
Chooses the given number of locations randomly, taking their weights into account
Parameters
number The number of locations to choose
Returns
List of selected locations
Definition at line 1004 of file TPS_TrafficAnalysisZone.java.
References de.dlr.ivf.tapas.loc.TPS_Location.getData(), and de.dlr.ivf.tapas.loc.TPS_Location.TPS_LocationData.getWeight().
updateOccupancy()
void de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.TypedWeightedLocationDistribution.updateOccupancy (double priorWeight, double postWeight)
Updates the weights after changing the weight of a location given by the prior and current weights
Parameters
priorWeight The prior weight of the location
postWeight The new weight of the location
Definition at line 1030 of file TPS_TrafficAnalysisZone.java.
Member Data Documentation
freeWeightSum
double de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.TypedWeightedLocationDistribution.freeWeightSum = 0 private
The sum of all the weights of all locations that are within this TAZ and allow the according activity.
Definition at line 922 of file TPS_TrafficAnalysisZone.java.
locations
Vector<TPS_Location> de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.TypedWeightedLocationDistribution.locations = new Vector<>()
The list of locations with the same activity.
Definition at line 920 of file TPS_TrafficAnalysisZone.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/loc/TPS_TrafficAnalysisZone.java