TAPAS: de.dlr.ivf.tapas.runtime.util.MultilanguageSupport Class Reference
de.dlr.ivf.tapas.runtime.util.MultilanguageSupport Class Reference
Static Public Member Functions
static Locale getLocale ()
static void setLocale (Locale loc)
static String getString (String key)
static JMenu init (final Class<?> guiClass)
Static Private Member Functions
static void change (Locale locale)
static File getUsersPropertiesFile (Class<?> guiClass)
static Properties load (Class<?> guiClass) throws IOException
static void store (Locale locale) throws IOException
Static Private Attributes
static ResourceBundle RB
static Locale locale
Detailed Description
This class provides multiple language support for any GUI. The language settings are stored for each user of the software so everybody can choose his own language. For the multiple languages the Java ResourceBundle is used.
The class provides also a menu for the GUI to change the current language settings. These changes only take place when the program is restarted.
To use this language support you have to create a subfolder called 'resource' into the folder where the main GUI class is located. In this subfolder you have to put on file called '$guiClass.getSimpleName()$.properties' where you define which languages you provide for this GUI. You enter the line 'languages = ...', where the dots can be 'de', 'en' and so on. Then you have to create a label file called '$guiClass.getSimpleName()$Labels_$language$.properties' for each language you defined. These files have to be created how it is explained in ResourceBundle. For each key and for each language you define a label text.
Author
mark_ma
See also
ResourceBundle
Definition at line 39 of file MultilanguageSupport.java.
Member Function Documentation
change()
static void de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.change (Locale locale) static private
The method changes the current settings and stores them in the properties file.
Parameters
locale new local settings
Definition at line 56 of file MultilanguageSupport.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.locale, de.dlr.ivf.tapas.log.TPS_Logger.log(), and de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.store().
Referenced by de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.init().
getLocale()
static Locale de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.getLocale () static
Returns current global locale setting
Returns
current global locale setting
Definition at line 72 of file MultilanguageSupport.java.
References de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.locale.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.createAndShowGUI(), and de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.initialize().
getString()
static String de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.getString (String key) static
Parameters
key key for the string to show in the current language
Returns
string to this key in the current language
Definition at line 84 of file MultilanguageSupport.java.
References de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.RB.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationControl.chooseRunFile(), de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.createToolTips(), de.dlr.ivf.tapas.tools.TUM.IntegratedTUM.doInBackground(), de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.getColumnNames(), de.dlr.ivf.tapas.runtime.client.SimulationControl.getServerHash(), de.dlr.ivf.tapas.runtime.client.SimulationMonitor.HashRenderer.getTableCellRendererComponent(), de.dlr.ivf.tapas.runtime.client.SimulationMonitor.initTables(), de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.ModalSplitChart(), de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartFrame.ModalSplitChartFrame(), de.dlr.ivf.tapas.tools.TUM.IntegratedTUM.process(), de.dlr.ivf.tapas.runtime.client.SimulationMonitor.SimulationMonitor(), de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.SimulationTableModel.SimulationTableModel(), de.dlr.ivf.tapas.tools.TUM.IntegratedTUM.summary(), and de.dlr.ivf.tapas.tools.TUM.IntegratedTUM.totalSummary().
getUsersPropertiesFile()
static File de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.getUsersPropertiesFile (Class<?> guiClass) static private
Parameters
guiClass the main class of the GUI
Returns
file for the current users language properties for the given GUI
Definition at line 92 of file MultilanguageSupport.java.
Referenced by de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.load(), and de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.store().
init()
static JMenu de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.init (final Class<?> guiClass) static
This method loads the language settings to this GUI for the current user and returns a menu for the gui where the settings can be changed.
Parameters
guiClass the main class of the GUI
Returns
menu with language options
Definition at line 103 of file MultilanguageSupport.java.
References de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.change(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.load(), de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.locale, de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.RB, de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.setLocale(), and de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.store().
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.getColumnNames(), de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.ModalSplitChart(), de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartFrame.ModalSplitChartFrame(), de.dlr.ivf.tapas.runtime.client.SimulationMonitor.SimulationMonitor(), and de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.SimulationTableModel.SimulationTableModel().
load()
static Properties de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.load (Class<?> guiClass) throws IOException static private
This method loads the user properties from the user properties file corresponding to the given GUI
Parameters
guiClass the main class of the GUI
Returns
user properties to this GUI
Exceptions
IOException This exception is thrown if the user properties wasn't loaded
Definition at line 150 of file MultilanguageSupport.java.
References de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.getUsersPropertiesFile().
Referenced by de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.init(), and de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.store().
setLocale()
static void de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.setLocale (Locale loc) static
Definition at line 76 of file MultilanguageSupport.java.
References de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.locale.
Referenced by de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.init(), and de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.store().
store()
static void de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.store (Locale locale) throws IOException static private
This method stores the current local settings for a specific user.
Parameters
locale current local language
Exceptions
IOException This exception is thrown if the local settings wasn't stored
Definition at line 163 of file MultilanguageSupport.java.
References de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.getUsersPropertiesFile(), de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.load(), de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.locale, de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.setLocale(), and de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.store().
Referenced by de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.change(), de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.init(), and de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.store().
Member Data Documentation
locale
Locale de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.locale static private
Locale setting
Definition at line 49 of file MultilanguageSupport.java.
Referenced by de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.change(), de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.getLocale(), de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.init(), de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.setLocale(), and de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.store().
RB
ResourceBundle de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.RB static private
Resource Bundle with the strings in the current language.
Definition at line 44 of file MultilanguageSupport.java.
Referenced by de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.getString(), and de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.init().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/runtime/util/MultilanguageSupport.java