TAPAS: de.dlr.ivf.tapas.tools.TPS_CapacityScale Class Reference
de.dlr.ivf.tapas.tools.TPS_CapacityScale Class Reference
Classes
class DistrictInfo
Public Member Functions
void createDistricts ()
void fillNewLocations (String schema, String oldLoc, String newLoc)
void getLocationInfo (String locTable, String tazTable)
void loadPersons (String table, String keyRef, String keyScen)
void loadTaz2DistrictMapping (String table)
Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_BasicConnectionClass ()
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass)
TPS_BasicConnectionClass (String loginFile)
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass, String loginFile)
boolean checkMatrixName (String matrixName)
TPS_ParameterClass getParameters ()
String readParameter (String simKey, String paramKey)
void storeInDB (String matrixName, double[][] matrix, int decimalPlaces)
Static Public Member Functions
static void main (String[] args)
Static Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
static double[][] array1Dto2D (Integer[] matrixVal)
static double[][] array1Dto2D (int[] matrixVal)
static File getRuntimeFile (boolean forceNewFile)
static File getRuntimeFile (String propertyFile, boolean forceNewFile)
static File getRuntimeFile ()
static File getRuntimeFile (String propertyFile)
static int[][] intArray1Dto2D (int[] matrixVal)
static String matrixToSQLArray (double[][] array, int decimalPlaces)
static StringWriter matrixToStringWriterSQL (double[][] array, int decimalPlaces)
Additional Inherited Members
Protected Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
void finalize ()
Protected Attributes inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_DB_Connector dbCon = null
TPS_ParameterClass parameterClass
Detailed Description
This tool adjusts the capacity of given locations to a new population.
Definition at line 24 of file TPS_CapacityScale.java.
Member Function Documentation
createDistricts()
void de.dlr.ivf.tapas.tools.TPS_CapacityScale.createDistricts ()
Definition at line 39 of file TPS_CapacityScale.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_CapacityScale.main().
fillNewLocations()
void de.dlr.ivf.tapas.tools.TPS_CapacityScale.fillNewLocations (String schema, String oldLoc, String newLoc)
Definition at line 48 of file TPS_CapacityScale.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute().
Referenced by de.dlr.ivf.tapas.tools.TPS_CapacityScale.main().
getLocationInfo()
void de.dlr.ivf.tapas.tools.TPS_CapacityScale.getLocationInfo (String locTable, String tazTable)
Definition at line 79 of file TPS_CapacityScale.java.
References code, de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery().
Referenced by de.dlr.ivf.tapas.tools.TPS_CapacityScale.main().
loadPersons()
void de.dlr.ivf.tapas.tools.TPS_CapacityScale.loadPersons (String table, String keyRef, String keyScen)
Definition at line 100 of file TPS_CapacityScale.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery().
Referenced by de.dlr.ivf.tapas.tools.TPS_CapacityScale.main().
loadTaz2DistrictMapping()
void de.dlr.ivf.tapas.tools.TPS_CapacityScale.loadTaz2DistrictMapping (String table)
Load the mapping form the tazes to the districts. This information is hidden in the "no" column of the table
Parameters
table
Definition at line 135 of file TPS_CapacityScale.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery().
Referenced by de.dlr.ivf.tapas.tools.TPS_CapacityScale.main().
main()
static void de.dlr.ivf.tapas.tools.TPS_CapacityScale.main (String[] args) static
Definition at line 29 of file TPS_CapacityScale.java.
References de.dlr.ivf.tapas.tools.TPS_CapacityScale.createDistricts(), de.dlr.ivf.tapas.tools.TPS_CapacityScale.fillNewLocations(), de.dlr.ivf.tapas.tools.TPS_CapacityScale.getLocationInfo(), de.dlr.ivf.tapas.tools.TPS_CapacityScale.loadPersons(), and de.dlr.ivf.tapas.tools.TPS_CapacityScale.loadTaz2DistrictMapping().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/TPS_CapacityScale.java