TAPAS: de.dlr.ivf.tapas.loc.TPS_Region Class Reference
de.dlr.ivf.tapas.loc.TPS_Region Class Reference
Public Member Functions
TPS_Region (TPS_PersistenceManager pm)
void addLocation (TPS_Location location)
boolean containsTrafficAnalysisZone (int id)
TPS_TrafficAnalysisZone createTrafficAnalysisZone (int id)
TPS_Block getBlock (int blockId)
TPS_CFN getCfn ()
TPS_CFN getPotential ()
void setCfn (TPS_CFN cfn)
void setPotential (TPS_CFN pot)
TPS_Location getLocation (int id)
TPS_LocationChoiceSet getLocationChoiceSet ()
TPS_LocationSelectModel getLocationSelectModel ()
int getSmallestId ()
TPS_TrafficAnalysisZone getTrafficAnalysisZone (int id)
Collection< Integer > getTrafficAnalysisZoneKeys ()
Collection< TPS_TrafficAnalysisZone > getTrafficAnalysisZones ()
TPS_VariableMap getValuesOfTime ()
void setValuesOfTime (TPS_VariableMap valuesOfTime)
void initLocationChoiceSet ()
void initLocationSelectModel ()
Iterator< TPS_TrafficAnalysisZone > iterator ()
TPS_Location selectLocation (TPS_Plan plan, TPS_PlanningContext pc, TPS_LocatedStay locatedStay)
int size ()
String toString ()
String toString (String prefix)
Private Member Functions
boolean addTrafficAnalysisZone (TPS_TrafficAnalysisZone taz)
double calculateVOTadds (double costs, TPS_Plan plan)
double manipulateCNF4ByPersongroup (TPS_ActivityConstant confSel, TPS_PersonGroup personGroup, double cfn4, TPS_ActivityConstant actCode)
Private Attributes
TPS_PersistenceManager PM = null
The reference to the persistence manager.
TPS_CFN cfn
All CFN values for this region.
TPS_CFN potential
All Potential values for this region.
final SortedMap< Integer, TPS_TrafficAnalysisZone > TAZ_Map
The map for all traffic analysis zones sorted by their id.
TPS_VariableMap valuesOfTime
The map of the differentiated values of time.
final HashMap< Integer, TPS_Location > locations = new HashMap<>()
TPS_LocationSelectModel LOCATION_SELECT_MODEL = null
TPS_LocationChoiceSet LOCATION_CHOICE_SET = null
Detailed Description
This class represents a complete region for a TAPAS simulation. A region can be Berlin. The region contains all traffic analysis zones. Furthermore the values of time and the cfn values are connected to this class.
The class provides a basic method selectLocation in which for a specific stay a location from the region is selected.
Definition at line 43 of file TPS_Region.java.
Constructor & Destructor Documentation
TPS_Region()
de.dlr.ivf.tapas.loc.TPS_Region.TPS_Region (TPS_PersistenceManager pm)
Initialises the map for the traffic analysis zones
Definition at line 73 of file TPS_Region.java.
Member Function Documentation
addLocation()
void de.dlr.ivf.tapas.loc.TPS_Region.addLocation (TPS_Location location)
Adds the given location to this region;
Parameters
location The location to add
Definition at line 83 of file TPS_Region.java.
References de.dlr.ivf.tapas.loc.TPS_Location.getId().
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readRegion().
addTrafficAnalysisZone()
boolean de.dlr.ivf.tapas.loc.TPS_Region.addTrafficAnalysisZone (TPS_TrafficAnalysisZone taz) private
This method adds the given traffic analysis zone when the id doesn't exist yet as a key in the traffic analysis zone map
Parameters
taz the traffic analysis zone to add
Returns
true if added, false otherwise
Definition at line 94 of file TPS_Region.java.
References de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.getTAZId(), and de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.setRegion().
calculateVOTadds()
double de.dlr.ivf.tapas.loc.TPS_Region.calculateVOTadds (double costs, TPS_Plan plan) private
Calculates the increase in travel time resulting from the transformation of the general costs into time usage; amount of time being added depends on the value of time as a function of the costs specified and the appropriate vot
Parameters
plan the plan for holding the attributes
costs travel costs / general costs
Returns
travel time increase in seconds
Definition at line 112 of file TPS_Region.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.FINE, de.dlr.ivf.tapas.plan.TPS_Plan.getAttributes(), de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), and de.dlr.ivf.tapas.log.TPS_Logger.log().
containsTrafficAnalysisZone()
boolean de.dlr.ivf.tapas.loc.TPS_Region.containsTrafficAnalysisZone (int id)
Flag determining if the traffic analysis zone, specified via the id, is a known element of the region
Parameters
id of the traffic analysis zone
Returns
true if the id is a key in the traffic analysis zone map
Definition at line 128 of file TPS_Region.java.
createTrafficAnalysisZone()
TPS_TrafficAnalysisZone de.dlr.ivf.tapas.loc.TPS_Region.createTrafficAnalysisZone (int id)
Creates a new traffic analysis zone specified by the id in the region ad returns it. If the taz exists it returns the existing taz.
Parameters
id the new id for this taz
Returns
the created taz
Definition at line 139 of file TPS_Region.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readRegion().
getBlock()
TPS_Block de.dlr.ivf.tapas.loc.TPS_Region.getBlock (int blockId)
Retruns the block for the given id
Parameters
blockId the block id to look for
Returns
the block or null if nothing was found
Definition at line 153 of file TPS_Region.java.
References de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.containsBlock(), and de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.getBlock().
getCfn()
TPS_CFN de.dlr.ivf.tapas.loc.TPS_Region.getCfn ()
Returns
the cfn
Definition at line 165 of file TPS_Region.java.
Referenced by de.dlr.ivf.tapas.loc.TPS_SelectLocationWeightBased.selectLocationFromChoiceSet(), and de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.selectLocationFromChoiceSet().
getLocation()
TPS_Location de.dlr.ivf.tapas.loc.TPS_Region.getLocation (int id)
Gets the specified location from this region
Parameters
id the location id to retrieve
Returns
the location or null if no location was found
Definition at line 199 of file TPS_Region.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.getTrafficAnalysisZonesAround(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.updateOccupancyTable().
getLocationChoiceSet()
TPS_LocationChoiceSet de.dlr.ivf.tapas.loc.TPS_Region.getLocationChoiceSet ()
Definition at line 203 of file TPS_Region.java.
getLocationSelectModel()
TPS_LocationSelectModel de.dlr.ivf.tapas.loc.TPS_Region.getLocationSelectModel ()
Definition at line 210 of file TPS_Region.java.
getPotential()
TPS_CFN de.dlr.ivf.tapas.loc.TPS_Region.getPotential ()
Returns
the cfn
Definition at line 172 of file TPS_Region.java.
Referenced by de.dlr.ivf.tapas.loc.TPS_SelectLocationWeightBased.selectLocationFromChoiceSet(), and de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.selectLocationFromChoiceSet().
getSmallestId()
int de.dlr.ivf.tapas.loc.TPS_Region.getSmallestId ()
Returns the smallest id of all traffic zones in the region
Returns
the smallest id
Definition at line 222 of file TPS_Region.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readMatrices().
getTrafficAnalysisZone()
TPS_TrafficAnalysisZone de.dlr.ivf.tapas.loc.TPS_Region.getTrafficAnalysisZone (int id)
Returns the traffic analysis zone specified by the id provides
Parameters
id id of the traffic analysis zone asked for
Returns
the traffic analysis zone or null if non existant
Definition at line 232 of file TPS_Region.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.getTrafficAnalysisZonesAround(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.loadHouseholds(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readRegion(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readTAZInfos().
getTrafficAnalysisZoneKeys()
Collection<Integer> de.dlr.ivf.tapas.loc.TPS_Region.getTrafficAnalysisZoneKeys ()
gets the key-set for the TAZ map
Returns
Definition at line 241 of file TPS_Region.java.
getTrafficAnalysisZones()
Collection<TPS_TrafficAnalysisZone> de.dlr.ivf.tapas.loc.TPS_Region.getTrafficAnalysisZones ()
gets the value set for the TAZ map
Returns
Definition at line 250 of file TPS_Region.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readMatrices().
getValuesOfTime()
TPS_VariableMap de.dlr.ivf.tapas.loc.TPS_Region.getValuesOfTime ()
Returns a map with all differentiated values of time
Returns
the values of time
Definition at line 259 of file TPS_Region.java.
initLocationChoiceSet()
void de.dlr.ivf.tapas.loc.TPS_Region.initLocationChoiceSet ()
This method initializes the location select model.
Definition at line 275 of file TPS_Region.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.HierarchyLogLevel.APPLICATION, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.FATAL, de.dlr.ivf.tapas.persistence.TPS_PersistenceManager.getParameters(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.util.parameters.ParamString.LOCATION_CHOICE_SET_CLASS, de.dlr.ivf.tapas.log.TPS_Logger.log(), and de.dlr.ivf.tapas.loc.TPS_LocationChoiceSet.setClassReferences().
initLocationSelectModel()
void de.dlr.ivf.tapas.loc.TPS_Region.initLocationSelectModel ()
This method initializes the location select model.
Definition at line 292 of file TPS_Region.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.HierarchyLogLevel.APPLICATION, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.FATAL, de.dlr.ivf.tapas.persistence.TPS_PersistenceManager.getParameters(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.util.parameters.ParamString.LOCATION_SELECT_MODEL_CLASS, de.dlr.ivf.tapas.log.TPS_Logger.log(), and de.dlr.ivf.tapas.loc.TPS_LocationSelectModel.setClassReferences().
iterator()
Iterator<TPS_TrafficAnalysisZone> de.dlr.ivf.tapas.loc.TPS_Region.iterator ()
Definition at line 313 of file TPS_Region.java.
manipulateCNF4ByPersongroup()
double de.dlr.ivf.tapas.loc.TPS_Region.manipulateCNF4ByPersongroup (TPS_ActivityConstant confSel, TPS_PersonGroup personGroup, double cfn4, TPS_ActivityConstant actCode) private
Manipulates the cfn4-values depending on the person group --> non used / stub
Parameters
confSel
personGroup
cfn4
actCode
Returns
modifizierten CFN4-Wert fr die Personengruppe und den Wegezweck
Definition at line 328 of file TPS_Region.java.
selectLocation()
TPS_Location de.dlr.ivf.tapas.loc.TPS_Region.selectLocation (TPS_Plan plan, TPS_PlanningContext pc, TPS_LocatedStay locatedStay)
TODO Rita translate
Wenn in der Zone eine Location zu dieser Aktivitt gefunden wurde, werden im Folgenden pModeArr und pModeDep der Map weightModes hinzugefgt, wenn sie noch nicht dort enthalten sind. Sind sie bereits enthalten, wird lediglich der entsprechende weight-Wert zu diesem Mode in weightModes der aktuelle weight-Wert dieser Zone weightC addiert. Am Ende beinhaltet die Map weightModes alle fr diese act in allen Zonen angebotenen Modes und deren aufaddierten Gewichte.
Nun werden die Gewichte im Vektor weightMode skaliert, in dem sie fr alle Elemente der Map zu sumWeights aufsummiert und anschlieend durch sumWeights dividiert werden.
pLocC wird nun die oben gesetzte repr. Location fr eine Zone, mit der als erstes die sog. Beeline-Entfernung vom comingFrom und zum GoingTo ermittelt wird. Nun wird fr alle Mode-Elemente der Map weightModes die Reisezeit vom comingFrom und zum goingTo errechnet und mit dem entsprechenden Gewicht multipliziert. Abschlieend wir das Paar (isBez92C, ttArr + ttDep) dem Vektor seqZoneQ hinzugefgt.
Zuletzt wird mit draeGeometric idBez92C gesetzt. Die myPLocationRepr der idBez92C entsprechenden Zone wird returned - oder null.
Parameters
plan The plan to use
pc planning context
locatedStay the located stay we are coming from
Returns
the selected location
Definition at line 472 of file TPS_Region.java.
References de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ACTIVITY2LOCATIONS_MAP, de.dlr.ivf.tapas.scheme.TPS_Episode.getActCode(), de.dlr.ivf.tapas.constants.TPS_ActivityConstant.getCode(), de.dlr.ivf.tapas.constants.TPS_ActivityConstant.getId(), de.dlr.ivf.tapas.persistence.TPS_PersistenceManager.getParameters(), de.dlr.ivf.tapas.plan.TPS_Plan.getPerson(), de.dlr.ivf.tapas.plan.TPS_LocatedStay.getStay(), de.dlr.ivf.tapas.person.TPS_Person.getWorkLocationID(), de.dlr.ivf.tapas.constants.TPS_ActivityConstant.isFix, de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.SEVERE, and de.dlr.ivf.tapas.constants.TPS_ActivityConstant.TPS_ActivityCodeType.ZBE.
Referenced by de.dlr.ivf.tapas.plan.TPS_LocatedStay.selectLocation().
setCfn()
void de.dlr.ivf.tapas.loc.TPS_Region.setCfn (TPS_CFN cfn)
Sets the reference of all cfn values
Parameters
cfn all cfn values for this region
Definition at line 181 of file TPS_Region.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readRegion().
setPotential()
void de.dlr.ivf.tapas.loc.TPS_Region.setPotential (TPS_CFN pot)
Sets the reference of all potential values
Parameters
pot all potential values for this region
Definition at line 190 of file TPS_Region.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readRegion().
setValuesOfTime()
void de.dlr.ivf.tapas.loc.TPS_Region.setValuesOfTime (TPS_VariableMap valuesOfTime)
Sets the reference of the values of time
Parameters
valuesOfTime
Definition at line 268 of file TPS_Region.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readRegion().
size()
int de.dlr.ivf.tapas.loc.TPS_Region.size ()
Returns the number of traffic analysis zones in this region
Returns
number of traffic analysis zones
Definition at line 511 of file TPS_Region.java.
toString() [1/2]
String de.dlr.ivf.tapas.loc.TPS_Region.toString ()
Definition at line 521 of file TPS_Region.java.
toString() [2/2]
String de.dlr.ivf.tapas.loc.TPS_Region.toString (String prefix)
This method should print the object naturally with the given prefix.
Parameters
prefix
Returns
prefix + toString();
Implements de.dlr.ivf.tapas.util.ExtendedWritable.
Definition at line 530 of file TPS_Region.java.
Member Data Documentation
cfn
TPS_CFN de.dlr.ivf.tapas.loc.TPS_Region.cfn private
All CFN values for this region.
Definition at line 48 of file TPS_Region.java.
LOCATION_CHOICE_SET
TPS_LocationChoiceSet de.dlr.ivf.tapas.loc.TPS_Region.LOCATION_CHOICE_SET = null private
Instance to the location select model
Definition at line 68 of file TPS_Region.java.
LOCATION_SELECT_MODEL
TPS_LocationSelectModel de.dlr.ivf.tapas.loc.TPS_Region.LOCATION_SELECT_MODEL = null private
Instance to the location select model
Definition at line 64 of file TPS_Region.java.
locations
final HashMap<Integer, TPS_Location> de.dlr.ivf.tapas.loc.TPS_Region.locations = new HashMap<>() private
Definition at line 60 of file TPS_Region.java.
PM
TPS_PersistenceManager de.dlr.ivf.tapas.loc.TPS_Region.PM = null private
The reference to the persistence manager.
Definition at line 45 of file TPS_Region.java.
potential
TPS_CFN de.dlr.ivf.tapas.loc.TPS_Region.potential private
All Potential values for this region.
Definition at line 51 of file TPS_Region.java.
TAZ_Map
final SortedMap<Integer, TPS_TrafficAnalysisZone> de.dlr.ivf.tapas.loc.TPS_Region.TAZ_Map private
The map for all traffic analysis zones sorted by their id.
Definition at line 54 of file TPS_Region.java.
valuesOfTime
TPS_VariableMap de.dlr.ivf.tapas.loc.TPS_Region.valuesOfTime private
The map of the differentiated values of time.
Definition at line 57 of file TPS_Region.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/loc/TPS_Region.java