TAPAS: de.dlr.ivf.tapas.util.Matrix Class Reference
de.dlr.ivf.tapas.util.Matrix Class Reference
Classes
enum MatrixPrint
Public Member Functions
Matrix (int n)
Matrix (int n, boolean diagonal)
Matrix (int n, boolean diagonal, int startIndex)
Matrix (int m, int n)
Matrix (int m, int n, int startIndex)
Matrix clone ()
double getAverageValue (boolean skipDiagonal, boolean skipNegative)
int getNumberOfColums ()
int getNumberOfElements ()
int getNumberOfRows ()
double getValue (int row, int column)
void setRawValue (int index, double value)
void setValue (int row, int column, double value)
void setValue (int index, double value)
void setValues (double value)
String toString ()
String toString (MatrixPrint print)
Static Public Member Functions
static void main (String[] args)
Public Attributes
double[][] vals
final int sIndex
Private Member Functions
Matrix (int m, int n, boolean diagonal, int startIndex)
Private Attributes
final boolean diagonal
final int m
final int n
Detailed Description
A matrix is a special value distribution. Here you can create line or column vectors, m*n (diagonal) matrices.
Author
mark_ma
Definition at line 20 of file Matrix.java.
Constructor & Destructor Documentation
Matrix() [1/6]
de.dlr.ivf.tapas.util.Matrix.Matrix (int n)
Builds a n*n matrix.
Parameters
n number of rows/columns -> n*n
Definition at line 50 of file Matrix.java.
References de.dlr.ivf.tapas.util.Matrix.n.
Referenced by de.dlr.ivf.tapas.util.Matrix.clone(), and de.dlr.ivf.tapas.util.Matrix.main().
Matrix() [2/6]
de.dlr.ivf.tapas.util.Matrix.Matrix (int n, boolean diagonal)
Builds a (diagonal) n*n matrix.
Parameters
n number of rows/columns -> n*n
diagonal flag if you want to create a diagonal matrix
Definition at line 60 of file Matrix.java.
References de.dlr.ivf.tapas.util.Matrix.diagonal, and de.dlr.ivf.tapas.util.Matrix.n.
Matrix() [3/6]
de.dlr.ivf.tapas.util.Matrix.Matrix (int n, boolean diagonal, int startIndex)
Builds a (diagonal) n*n matrix starting at the given index.
Parameters
n number of rows/columns -> n*n
diagonal flag if you want to create a diagonal matrix
startIndex start index of the first element
Definition at line 71 of file Matrix.java.
References de.dlr.ivf.tapas.util.Matrix.diagonal, and de.dlr.ivf.tapas.util.Matrix.n.
Matrix() [4/6]
de.dlr.ivf.tapas.util.Matrix.Matrix (int m, int n)
Builds a m*n matrix.
Parameters
m number of rows
n number of columns
Definition at line 81 of file Matrix.java.
References de.dlr.ivf.tapas.util.Matrix.m, and de.dlr.ivf.tapas.util.Matrix.n.
Matrix() [5/6]
de.dlr.ivf.tapas.util.Matrix.Matrix (int m, int n, boolean diagonal, int startIndex) private
Builds a (diagonal) m*n matrix starting at the given index.
Parameters
m number of rows
n number of columns
diagonal flag if you want to create a diagonal matrix
startIndex start index of the first element
Definition at line 93 of file Matrix.java.
References de.dlr.ivf.tapas.util.Matrix.diagonal, de.dlr.ivf.tapas.util.Matrix.m, de.dlr.ivf.tapas.util.Matrix.n, de.dlr.ivf.tapas.util.Matrix.setValues(), and de.dlr.ivf.tapas.util.Matrix.sIndex.
Matrix() [6/6]
de.dlr.ivf.tapas.util.Matrix.Matrix (int m, int n, int startIndex)
Builds a m*n matrix starting at the given index.
Parameters
m number of rows
n number of columns
startIndex start index of the first element
Definition at line 109 of file Matrix.java.
References de.dlr.ivf.tapas.util.Matrix.m, and de.dlr.ivf.tapas.util.Matrix.n.
Member Function Documentation
clone()
Matrix de.dlr.ivf.tapas.util.Matrix.clone ()
This method generates a clone from this matrix.
Definition at line 139 of file Matrix.java.
References de.dlr.ivf.tapas.util.Matrix.m, de.dlr.ivf.tapas.util.Matrix.Matrix(), de.dlr.ivf.tapas.util.Matrix.n, de.dlr.ivf.tapas.util.Matrix.sIndex, and de.dlr.ivf.tapas.util.Matrix.vals.
Referenced by de.dlr.ivf.tapas.util.MatrixMap.clone(), and de.dlr.ivf.tapas.tools.TPS_SubnetMatrixIntegrator.updateValues().
getAverageValue()
double de.dlr.ivf.tapas.util.Matrix.getAverageValue (boolean skipDiagonal, boolean skipNegative)
Returns the average value of this matrix
Parameters
skipDiagonal flag if the diagonal values should be included or not
skipNegative flag if negative values should be included or not
Returns
the average value of all relevant values
Definition at line 154 of file Matrix.java.
References de.dlr.ivf.tapas.util.Matrix.m, and de.dlr.ivf.tapas.util.Matrix.n.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.readMatrixMap().
getNumberOfColums()
int de.dlr.ivf.tapas.util.Matrix.getNumberOfColums ()
get number of columns
Definition at line 174 of file Matrix.java.
References de.dlr.ivf.tapas.util.Matrix.n.
Referenced by de.dlr.ivf.tapas.tools.TPS_ParkAndRideAnalysator.analyzeTrips(), de.dlr.ivf.tapas.tools.TPS_FeederCellManipulator.loadAndInitMatrices(), de.dlr.ivf.tapas.tools.TPS_PTBikeInterchangeMatrix.loadAndInitMatrices(), de.dlr.ivf.tapas.tools.TPS_PTCarInterchangeMatrix.loadMatrices(), de.dlr.ivf.tapas.tools.TPS_ParkAndRideRouter.loadTAZRestriction(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.matrixToSQLArray(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.mergeMatrixPair(), de.dlr.ivf.tapas.tools.TPS_ParkAndRideRouter.routePnR(), and de.dlr.ivf.tapas.tools.TPS_ParkAndRideRouter.storeMatrixInDB().
getNumberOfElements()
int de.dlr.ivf.tapas.util.Matrix.getNumberOfElements ()
get number of elements
Definition at line 181 of file Matrix.java.
References de.dlr.ivf.tapas.util.Matrix.m, and de.dlr.ivf.tapas.util.Matrix.n.
getNumberOfRows()
int de.dlr.ivf.tapas.util.Matrix.getNumberOfRows ()
get number of rows
Definition at line 188 of file Matrix.java.
References de.dlr.ivf.tapas.util.Matrix.m.
Referenced by de.dlr.ivf.tapas.tools.TPS_ParkAndRideAnalysator.analyzeTrips(), de.dlr.ivf.tapas.tools.TPS_FeederCellManipulator.loadAndInitMatrices(), and de.dlr.ivf.tapas.tools.TPS_ParkAndRideRouter.storeMatrixInDB().
getValue()
double de.dlr.ivf.tapas.util.Matrix.getValue (int row, int column)
Returns the value at the given position of the matrix (row / column)
Parameters
row row index
column column index
Returns
value at this position
Definition at line 199 of file Matrix.java.
References de.dlr.ivf.tapas.util.Matrix.sIndex.
Referenced by de.dlr.ivf.tapas.tools.TPS_ParkAndRideAnalysator.analyzeTrips(), de.dlr.ivf.tapas.tools.TPS_MainDiagonalLengthEstimator.calcBeeLineFactors(), de.dlr.ivf.tapas.tools.TPS_MainDiagonalLengthEstimator.calcBeelineTAZDist(), de.dlr.ivf.tapas.tools.TPS_ParkAndRideRouter.createPandRMatrix(), de.dlr.ivf.tapas.util.parameters.ParamMatrixClass.getValue(), de.dlr.ivf.tapas.util.parameters.ParamMatrixMapClass.getValue(), de.dlr.ivf.tapas.tools.TPS_FeederCellManipulator.loadAndInitMatrices(), de.dlr.ivf.tapas.tools.TPS_PTBikeInterchangeMatrix.loadAndInitMatrices(), de.dlr.ivf.tapas.tools.TPS_PTCarInterchangeMatrix.loadMatrices(), de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.loadSumoValues(), de.dlr.ivf.tapas.util.Matrix.main(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.matrixToSQLArray(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.mergeMatrixPair(), de.dlr.ivf.tapas.tools.TPS_MainDiagonalLengthEstimator.printStats(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.readCSVFile(), de.dlr.ivf.tapas.runtime.sumoDaemon.SumoMatrixImporter.readSumoValues(), de.dlr.ivf.tapas.tools.TPS_ParkAndRideRouter.routePnR(), de.dlr.ivf.tapas.tools.TPS_ParkAndRideRouter.storeMatrixInDB(), and de.dlr.ivf.tapas.tools.TPS_SubnetMatrixIntegrator.updateValues().
main()
static void de.dlr.ivf.tapas.util.Matrix.main (String[] args) static
Demo main
Parameters
args
Definition at line 118 of file Matrix.java.
References de.dlr.ivf.tapas.util.Matrix.getValue(), de.dlr.ivf.tapas.util.Matrix.MatrixPrint.LINE, de.dlr.ivf.tapas.util.Matrix.Matrix(), de.dlr.ivf.tapas.util.Matrix.setValue(), and de.dlr.ivf.tapas.util.Matrix.toString().
setRawValue()
void de.dlr.ivf.tapas.util.Matrix.setRawValue (int index, double value)
This method sets the value at position index. It ignores the sIndex member to access arrays which start counting e.g. by 1;
Parameters
index index in matrix
value new value at this position
Definition at line 210 of file Matrix.java.
References de.dlr.ivf.tapas.util.Matrix.n.
Referenced by de.dlr.ivf.tapas.tools.TPS_MainDiagonalLengthEstimator.loadDistMatrix(), de.dlr.ivf.tapas.iteration.TPS_VisumConverter.readMatrix(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.readMatrix(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readMatrix(), de.dlr.ivf.tapas.tools.TPS_FeederCellManipulator.readMatrix(), de.dlr.ivf.tapas.tools.TPS_ParkAndRideRouter.readMatrix(), de.dlr.ivf.tapas.tools.TPS_PTBikeInterchangeMatrix.readMatrix(), de.dlr.ivf.tapas.tools.TPS_PTCarInterchangeMatrix.readMatrix(), and de.dlr.ivf.tapas.iteration.TPS_SumoConverter.readMatrixMap().
setValue() [1/2]
void de.dlr.ivf.tapas.util.Matrix.setValue (int index, double value)
This method sets the value at position index. It also uses the sIndex member to access arrays which start counting e.g. by 1;
Parameters
index index in matrix
value new value at this position
Definition at line 235 of file Matrix.java.
References de.dlr.ivf.tapas.util.Matrix.n, and de.dlr.ivf.tapas.util.Matrix.sIndex.
setValue() [2/2]
void de.dlr.ivf.tapas.util.Matrix.setValue (int row, int column, double value)
This method sets the value at position (row,column). It also uses the sIndex member to access arrays which start counting e.g. by 1;
Parameters
row row index
column column index
value new value at this position
Definition at line 224 of file Matrix.java.
References de.dlr.ivf.tapas.util.Matrix.sIndex.
Referenced by de.dlr.ivf.tapas.tools.TPS_ParkAndRideRouter.createPandRMatrix(), de.dlr.ivf.tapas.tools.TPS_SubnetMatrixIntegrator.extractSubmatrix(), de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.loadSumoValues(), de.dlr.ivf.tapas.util.Matrix.main(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.mergeMatrixPair(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.readAllParis(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.readCSVFile(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readMatrices(), de.dlr.ivf.tapas.runtime.sumoDaemon.SumoMatrixImporter.readSumoValues(), de.dlr.ivf.tapas.tools.TPS_MainDiagonalLengthEstimator.readTAZ(), de.dlr.ivf.tapas.tools.TPS_MainDiagonalLengthEstimator.saveNewMatrix(), de.dlr.ivf.tapas.tools.TPS_ParkingSpaceAproximator.storeSQLMatrix(), and de.dlr.ivf.tapas.tools.TPS_SubnetMatrixIntegrator.updateValues().
setValues()
void de.dlr.ivf.tapas.util.Matrix.setValues (double value)
Sets all values of the matrix to the given value
Parameters
value
Definition at line 247 of file Matrix.java.
Referenced by de.dlr.ivf.tapas.util.Matrix.Matrix().
toString() [1/2]
String de.dlr.ivf.tapas.util.Matrix.toString ()
Definition at line 259 of file Matrix.java.
References de.dlr.ivf.tapas.util.Matrix.MatrixPrint.LINE.
Referenced by de.dlr.ivf.tapas.util.Matrix.main(), and de.dlr.ivf.tapas.util.MatrixMap.main().
toString() [2/2]
String de.dlr.ivf.tapas.util.Matrix.toString (MatrixPrint print)
Returns a matrix as string representation; format of the string depends on the type of printing specified: either as single line or as matrix
Parameters
print type of printing
Returns
printed matrix
Definition at line 270 of file Matrix.java.
References de.dlr.ivf.tapas.util.Matrix.m, de.dlr.ivf.tapas.util.Matrix.n, and de.dlr.ivf.tapas.util.Matrix.sIndex.
Member Data Documentation
diagonal
final boolean de.dlr.ivf.tapas.util.Matrix.diagonal private
Flag if the matrix is a diagonal matrix
Definition at line 30 of file Matrix.java.
Referenced by de.dlr.ivf.tapas.util.Matrix.Matrix().
m
final int de.dlr.ivf.tapas.util.Matrix.m private
Number of rows
Definition at line 34 of file Matrix.java.
Referenced by de.dlr.ivf.tapas.util.Matrix.clone(), de.dlr.ivf.tapas.util.Matrix.getAverageValue(), de.dlr.ivf.tapas.util.Matrix.getNumberOfElements(), de.dlr.ivf.tapas.util.Matrix.getNumberOfRows(), de.dlr.ivf.tapas.util.Matrix.Matrix(), and de.dlr.ivf.tapas.util.Matrix.toString().
n
final int de.dlr.ivf.tapas.util.Matrix.n private
Number of columns
Definition at line 38 of file Matrix.java.
Referenced by de.dlr.ivf.tapas.util.Matrix.clone(), de.dlr.ivf.tapas.util.Matrix.getAverageValue(), de.dlr.ivf.tapas.util.Matrix.getNumberOfColums(), de.dlr.ivf.tapas.util.Matrix.getNumberOfElements(), de.dlr.ivf.tapas.util.Matrix.Matrix(), de.dlr.ivf.tapas.util.Matrix.setRawValue(), de.dlr.ivf.tapas.util.Matrix.setValue(), and de.dlr.ivf.tapas.util.Matrix.toString().
sIndex
final int de.dlr.ivf.tapas.util.Matrix.sIndex
The start index of the matrix. Normally an Array starts a 0. Here you can define the start index, e.g. 1.
Definition at line 42 of file Matrix.java.
Referenced by de.dlr.ivf.tapas.util.Matrix.clone(), de.dlr.ivf.tapas.util.Matrix.getValue(), de.dlr.ivf.tapas.util.Matrix.Matrix(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.matrixToSQLArray(), de.dlr.ivf.tapas.util.Matrix.setValue(), and de.dlr.ivf.tapas.util.Matrix.toString().
vals
double [][] de.dlr.ivf.tapas.util.Matrix.vals
The matrix is stored in this value distribution.
Definition at line 25 of file Matrix.java.
Referenced by de.dlr.ivf.tapas.util.Matrix.clone(), and de.dlr.ivf.tapas.tools.TPS_MainDiagonalLengthEstimator.saveNewMatrix().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/util/Matrix.java