TAPAS: de.dlr.ivf.tapas.person.TPS_Person Class Reference
de.dlr.ivf.tapas.person.TPS_Person Class Reference
Public Member Functions
TPS_Person (int id, TPS_Sex sex, TPS_PersonGroup personGroup, int age, boolean abo, boolean hasBike, double budget, double isWorking, boolean isTeleworker, int workLocationID, int eduactionLevel, boolean use_shopping_motives)
void estimateAccessibilityPreference (TPS_Stay stay, boolean use_shopping_motives)
int getAge ()
TPS_AgeClass getAgeClass ()
double getBudget ()
TPS_DrivingLicenseInformation getDrivingLicenseInformation ()
void setDrivingLicenseInformation (TPS_DrivingLicenseInformation drivingLicenseInformation)
int getEducationLevel ()
TPS_Household getHousehold ()
void setHousehold (TPS_Household household)
int getId ()
TPS_PersonGroup getPersGroup ()
TPS_Sex getSex ()
int getWorkLocationID ()
double getWorkingAmount ()
boolean hasAbo ()
boolean hasBike ()
boolean hasDrivingLicenseInformation ()
boolean isAgeAdapted ()
boolean isCarPooler ()
void setCarPooler (boolean carPooler)
boolean isChild ()
boolean isPupil ()
boolean isStudent ()
boolean isTeleworker ()
boolean isWorking ()
boolean mayDriveACar ()
double primaryDriver ()
void setAgeAdaption (boolean ageAdaption, int rejuvenate_by_nb_years)
String toString ()
String toString (String prefix)
Public Attributes
ShoppingPreferenceAccessibility currentAccessibilityPreference = ShoppingPreferenceAccessibility.Sonstige
ShoppingPreferenceSupply currentSupplyPreference = ShoppingPreferenceSupply.Sonstige
TPS_Preference preferenceValues
Private Member Functions
boolean hasDrivingLicense ()
ShoppingPreferenceAccessibility selectPreferenceAccessibility (ShoppingClass s)
ShoppingPreferenceSupply selectPreferenceSupply (ShoppingClass s)
Private Attributes
final int id
id of the person
TPS_PersonGroup persGroup
the person group
final TPS_Sex sex
sex of the person
final boolean abo
Flag if person holds a long term ticket (season / month...)for the public transport.
int age
age of the person
boolean ageAdaption
flag if the age has been adapted (artificial rejuvenation of retirees)
TPS_AgeClass ageClass
class of the age of the person
final double budget
monthly financial budget for travel expenditures in Euro, includes car usage and pt usage but no fix budget
boolean carPooler
flag if the person is prone to be a car pooler
TPS_DrivingLicenseInformation drivingLicenseInformation
information if person holds a driving license and when applicable the type of licence
TPS_Household household
the household the person belongs to
boolean teleworker
flag if the person is prone to be a teleworker
final double working
flag if the person is working
final boolean hasBike
flag if this person has a bike
int workLocationID = -1
Id to the fixed work location.
double driverScore = -1
int educationLevel = 0
Detailed Description
This class represents a person.
Author
mark_ma
Definition at line 35 of file TPS_Person.java.
Constructor & Destructor Documentation
TPS_Person()
de.dlr.ivf.tapas.person.TPS_Person.TPS_Person (int id, TPS_Sex sex, TPS_PersonGroup personGroup, int age, boolean abo, boolean hasBike, double budget, double isWorking, boolean isTeleworker, int workLocationID, int eduactionLevel, boolean use_shopping_motives)
This constructor just calls the init() method.
Parameters
id The id of this person
sex The sex of this person
personGroup The person group this person matches
age The age of this person
abo Whether this person has a public transport abo
hasBike Whether this person has a bike
budget This person's budget
isWorking Whether this person is working
isTeleworker Whether this person is a teleworker
workLocationID The id of this person's work location (negative if not valid)
eduactionLevel
use_shopping_motives
Definition at line 93 of file TPS_Person.java.
References de.dlr.ivf.tapas.constants.TPS_AgeClass.getAgeClass(), de.dlr.ivf.tapas.util.Randomizer.random(), de.dlr.ivf.tapas.util.Randomizer.randomGumbelDistribution(), and de.dlr.ivf.tapas.constants.TPS_DrivingLicenseInformation.UNKNOWN.
Member Function Documentation
estimateAccessibilityPreference()
void de.dlr.ivf.tapas.person.TPS_Person.estimateAccessibilityPreference (TPS_Stay stay, boolean use_shopping_motives)
Definition at line 117 of file TPS_Person.java.
References de.dlr.ivf.tapas.scheme.TPS_Stay.getTypeOfShoppingGoods(), de.dlr.ivf.tapas.scheme.TPS_Stay.locationChoiceMotive, de.dlr.ivf.tapas.scheme.TPS_Stay.locationChoiceMotiveSupply, de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingPreferenceSupply.Sonstige, and de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingPreferenceAccessibility.Sonstige.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes().
getAge()
int de.dlr.ivf.tapas.person.TPS_Person.getAge ()
Returns the age of the person
Returns
the age
Definition at line 144 of file TPS_Person.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.addPersonToHousehold(), de.dlr.ivf.tapas.person.TPS_Preference.calcUtility(), and de.dlr.ivf.tapas.plan.TPS_Plan.TPS_Plan().
getAgeClass()
TPS_AgeClass de.dlr.ivf.tapas.person.TPS_Person.getAgeClass ()
Returns the age category of the person
Returns
the age category
Definition at line 153 of file TPS_Person.java.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.createOutput(), de.dlr.ivf.tapas.constants.TPS_PersonGroup.fits(), de.dlr.ivf.tapas.plan.TPS_Plan.TPS_Plan(), and de.dlr.ivf.tapas.plan.TPS_Plan.writeOutputStream().
getBudget()
double de.dlr.ivf.tapas.person.TPS_Person.getBudget ()
Returns the monthly variable budget for travel expenditures in Euro
Returns
the budget
Definition at line 162 of file TPS_Person.java.
Referenced by de.dlr.ivf.tapas.plan.acceptance.TPS_PlanEVA1Acceptance.calculateAcceptanceProbBudgetConstraints().
getDrivingLicenseInformation()
TPS_DrivingLicenseInformation de.dlr.ivf.tapas.person.TPS_Person.getDrivingLicenseInformation ()
Returns information about driving license availability of the person
Returns
driving license status
Definition at line 171 of file TPS_Person.java.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.TPS_Plan().
getEducationLevel()
int de.dlr.ivf.tapas.person.TPS_Person.getEducationLevel ()
Coding: 0 = none 1 = school 2 = college/Abitur 3 = professional training/ Ausbildung 4 = university 5 = other';
Returns
the education level of this person
Definition at line 195 of file TPS_Person.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Preference.calcUtility().
getHousehold()
TPS_Household de.dlr.ivf.tapas.person.TPS_Person.getHousehold ()
Returns the household the person belongs to
Returns
the household
Definition at line 204 of file TPS_Person.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.batchStoreTrips(), de.dlr.ivf.tapas.person.TPS_Preference.calcUtility(), de.dlr.ivf.tapas.plan.TPS_Plan.createOutput(), de.dlr.ivf.tapas.constants.TPS_PersonGroup.fits(), de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixedBS.getDistributionSet(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessMode.getTravelTime(), de.dlr.ivf.tapas.person.TPS_Car.selectCar(), de.dlr.ivf.tapas.plan.TPS_LocatedStay.selectLocation(), de.dlr.ivf.tapas.loc.TPS_SelectLocationWeightBased.selectLocationFromChoiceSet(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.selectLocationFromChoiceSet(), de.dlr.ivf.tapas.plan.TPS_Plan.TPS_Plan(), and de.dlr.ivf.tapas.plan.TPS_Plan.writeOutputStream().
getId()
int de.dlr.ivf.tapas.person.TPS_Person.getId ()
Returns the id of the person
Returns
id
Definition at line 222 of file TPS_Person.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Household.addMember(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.batchStoreTrips(), de.dlr.ivf.tapas.plan.TPS_Plan.createOutput(), and de.dlr.ivf.tapas.plan.TPS_Plan.writeOutputStream().
getPersGroup()
TPS_PersonGroup de.dlr.ivf.tapas.person.TPS_Person.getPersGroup ()
Returns the person group of the person, indication work status, sex, age and car ownership
Returns
the person group
Definition at line 231 of file TPS_Person.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.batchStoreTrips(), de.dlr.ivf.tapas.person.TPS_Preference.calcUtility(), de.dlr.ivf.tapas.plan.TPS_Plan.createOutput(), de.dlr.ivf.tapas.mode.TPS_MassTransportMode.getTravelTime(), de.dlr.ivf.tapas.scheme.TPS_SchemeSet.selectScheme(), de.dlr.ivf.tapas.plan.TPS_Plan.TPS_Plan(), and de.dlr.ivf.tapas.plan.TPS_Plan.writeOutputStream().
getSex()
TPS_Sex de.dlr.ivf.tapas.person.TPS_Person.getSex ()
Returns the sex of the person
Returns
the sex
Definition at line 240 of file TPS_Person.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Preference.calcUtility(), de.dlr.ivf.tapas.plan.TPS_Plan.createOutput(), de.dlr.ivf.tapas.constants.TPS_PersonGroup.fits(), de.dlr.ivf.tapas.plan.TPS_Plan.TPS_Plan(), and de.dlr.ivf.tapas.plan.TPS_Plan.writeOutputStream().
getWorkingAmount()
double de.dlr.ivf.tapas.person.TPS_Person.getWorkingAmount ()
Returns the work amount
Returns
The work amount
Definition at line 256 of file TPS_Person.java.
getWorkLocationID()
int de.dlr.ivf.tapas.person.TPS_Person.getWorkLocationID ()
Returns
the workLocationID
Definition at line 247 of file TPS_Person.java.
Referenced by de.dlr.ivf.tapas.loc.TPS_FocusPointModel.getFocusPoint(), and de.dlr.ivf.tapas.loc.TPS_Region.selectLocation().
hasAbo()
boolean de.dlr.ivf.tapas.person.TPS_Person.hasAbo ()
Returns whether the person holds an season ticket for public transport
Returns
true if an season ticket is present, false else
Definition at line 265 of file TPS_Person.java.
hasBike()
boolean de.dlr.ivf.tapas.person.TPS_Person.hasBike ()
Returns
Returns true if this person has a usable bike.
Definition at line 272 of file TPS_Person.java.
hasDrivingLicense()
boolean de.dlr.ivf.tapas.person.TPS_Person.hasDrivingLicense () private
Returns whether the person holds a driving license
Returns
true if the person holds a license; false else
Definition at line 281 of file TPS_Person.java.
References de.dlr.ivf.tapas.constants.TPS_DrivingLicenseInformation.CAR.
hasDrivingLicenseInformation()
boolean de.dlr.ivf.tapas.person.TPS_Person.hasDrivingLicenseInformation ()
Returns whether the information about the driving license of the person is available
Returns
true if the information is available; false else
Definition at line 290 of file TPS_Person.java.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.TPS_Plan().
isAgeAdapted()
boolean de.dlr.ivf.tapas.person.TPS_Person.isAgeAdapted ()
Returns whether the age of the person was adapted to account for younger behavior of the elderly
Returns
true if the age was adapted; false else
Definition at line 301 of file TPS_Person.java.
isCarPooler()
boolean de.dlr.ivf.tapas.person.TPS_Person.isCarPooler ()
Returns whether the person is prone to car pooling
Returns
true if applicable; false else
Definition at line 311 of file TPS_Person.java.
isChild()
boolean de.dlr.ivf.tapas.person.TPS_Person.isChild ()
Returns whether the person is a child and is too young to go to school according to age
Returns
true if child; false else
Definition at line 329 of file TPS_Person.java.
isPupil()
boolean de.dlr.ivf.tapas.person.TPS_Person.isPupil ()
Returns whether the person is a pupil and goes to school
Returns
true if child; false else
Definition at line 338 of file TPS_Person.java.
isStudent()
boolean de.dlr.ivf.tapas.person.TPS_Person.isStudent ()
Returns whether the person is a university student
Returns
true if the person is a university student; false else
Definition at line 347 of file TPS_Person.java.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.createOutput(), and de.dlr.ivf.tapas.plan.TPS_Plan.writeOutputStream().
isTeleworker()
boolean de.dlr.ivf.tapas.person.TPS_Person.isTeleworker ()
Returns whether the person is prone to teleworking
Returns
true if teleworking; false else
Definition at line 356 of file TPS_Person.java.
isWorking()
boolean de.dlr.ivf.tapas.person.TPS_Person.isWorking ()
Returns whether the person is working
Returns
if working; false else
Definition at line 365 of file TPS_Person.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Preference.calcUtility().
mayDriveACar()
boolean de.dlr.ivf.tapas.person.TPS_Person.mayDriveACar ()
Returns whether the person may drive a car
Combines driving information if available and age to determine whether the person may drive a car.
Returns
true if the person may drive a car; false else
Definition at line 376 of file TPS_Person.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.addPersonToHousehold().
primaryDriver()
double de.dlr.ivf.tapas.person.TPS_Person.primaryDriver ()
This is a hard coded linear regression model to see if the person is the primary driver of a car.
Returns
a probability of being the primary driver
Definition at line 386 of file TPS_Person.java.
References de.dlr.ivf.tapas.constants.TPS_Sex.MALE, and de.dlr.ivf.tapas.person.TPS_Household.Sorting.NONE.
selectPreferenceAccessibility()
ShoppingPreferenceAccessibility de.dlr.ivf.tapas.person.TPS_Person.selectPreferenceAccessibility (ShoppingClass s) private
Definition at line 471 of file TPS_Person.java.
References de.dlr.ivf.tapas.util.TPS_FastMath.exp(), de.dlr.ivf.tapas.util.Randomizer.random(), de.dlr.ivf.tapas.util.Randomizer.randomGaussian(), de.dlr.ivf.tapas.util.Randomizer.randomGaussianDistribution(), de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingPreferenceAccessibility.Sonstige, de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingClass.UEL, and de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingPreferenceAccessibility.valueArray.
selectPreferenceSupply()
ShoppingPreferenceSupply de.dlr.ivf.tapas.person.TPS_Person.selectPreferenceSupply (ShoppingClass s) private
Definition at line 528 of file TPS_Person.java.
References de.dlr.ivf.tapas.util.TPS_FastMath.exp(), de.dlr.ivf.tapas.util.Randomizer.random(), de.dlr.ivf.tapas.util.Randomizer.randomGaussian(), de.dlr.ivf.tapas.util.Randomizer.randomGaussianDistribution(), de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingPreferenceSupply.Sonstige, and de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingPreferenceSupply.valueArray.
setAgeAdaption()
void de.dlr.ivf.tapas.person.TPS_Person.setAgeAdaption (boolean ageAdaption, int rejuvenate_by_nb_years)
This method sets the person's age to a new value. this is used in scenario versions. The prediction is that people are more mobile in higher ages in future. So in these scenarios they get younger. This leads to a new selection of the person group that these values are consistent
Parameters
ageAdaption flag if an age adaption should be performed
rejuvenate_by_nb_years
Definition at line 593 of file TPS_Person.java.
References de.dlr.ivf.tapas.constants.TPS_PersonGroup.fits(), de.dlr.ivf.tapas.constants.TPS_AgeClass.getAgeClass(), and de.dlr.ivf.tapas.constants.TPS_PersonGroup.getConstants().
setCarPooler()
void de.dlr.ivf.tapas.person.TPS_Person.setCarPooler (boolean carPooler)
Sets whether the person is prone to car pooling
Parameters
carPooler
Definition at line 320 of file TPS_Person.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.addPersonToHousehold().
setDrivingLicenseInformation()
void de.dlr.ivf.tapas.person.TPS_Person.setDrivingLicenseInformation (TPS_DrivingLicenseInformation drivingLicenseInformation)
Sets the driving license information of the person
Parameters
drivingLicenseInformation
Definition at line 180 of file TPS_Person.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.addPersonToHousehold().
setHousehold()
void de.dlr.ivf.tapas.person.TPS_Person.setHousehold (TPS_Household household)
Sets the household of the person
Parameters
household
Definition at line 213 of file TPS_Person.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Household.addMember().
toString() [1/2]
String de.dlr.ivf.tapas.person.TPS_Person.toString ()
Definition at line 619 of file TPS_Person.java.
toString() [2/2]
String de.dlr.ivf.tapas.person.TPS_Person.toString (String prefix)
This method should print the object naturally with the given prefix.
Parameters
prefix
Returns
prefix + toString();
Implements de.dlr.ivf.tapas.util.ExtendedWritable.
Definition at line 628 of file TPS_Person.java.
References de.dlr.ivf.tapas.constants.TPS_PersonGroup.getCode(), and de.dlr.ivf.tapas.constants.TPS_AgeClass.TPS_AgeCodeType.STBA.
Member Data Documentation
abo
final boolean de.dlr.ivf.tapas.person.TPS_Person.abo private
Flag if person holds a long term ticket (season / month...)for the public transport.
Definition at line 51 of file TPS_Person.java.
age
int de.dlr.ivf.tapas.person.TPS_Person.age private
age of the person
Definition at line 53 of file TPS_Person.java.
ageAdaption
boolean de.dlr.ivf.tapas.person.TPS_Person.ageAdaption private
flag if the age has been adapted (artificial rejuvenation of retirees)
Definition at line 55 of file TPS_Person.java.
ageClass
TPS_AgeClass de.dlr.ivf.tapas.person.TPS_Person.ageClass private
class of the age of the person
Definition at line 57 of file TPS_Person.java.
budget
final double de.dlr.ivf.tapas.person.TPS_Person.budget private
monthly financial budget for travel expenditures in Euro, includes car usage and pt usage but no fix budget
Definition at line 59 of file TPS_Person.java.
carPooler
boolean de.dlr.ivf.tapas.person.TPS_Person.carPooler private
flag if the person is prone to be a car pooler
Definition at line 61 of file TPS_Person.java.
currentAccessibilityPreference
ShoppingPreferenceAccessibility de.dlr.ivf.tapas.person.TPS_Person.currentAccessibilityPreference = ShoppingPreferenceAccessibility.Sonstige
Definition at line 36 of file TPS_Person.java.
Referenced by de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessMode.getTravelTime().
currentSupplyPreference
ShoppingPreferenceSupply de.dlr.ivf.tapas.person.TPS_Person.currentSupplyPreference = ShoppingPreferenceSupply.Sonstige
Definition at line 37 of file TPS_Person.java.
driverScore
double de.dlr.ivf.tapas.person.TPS_Person.driverScore = -1 private
Definition at line 74 of file TPS_Person.java.
drivingLicenseInformation
TPS_DrivingLicenseInformation de.dlr.ivf.tapas.person.TPS_Person.drivingLicenseInformation private
information if person holds a driving license and when applicable the type of licence
Definition at line 63 of file TPS_Person.java.
educationLevel
int de.dlr.ivf.tapas.person.TPS_Person.educationLevel = 0 private
Definition at line 75 of file TPS_Person.java.
hasBike
final boolean de.dlr.ivf.tapas.person.TPS_Person.hasBike private
flag if this person has a bike
Definition at line 71 of file TPS_Person.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Worker.createPersonPlans(), and de.dlr.ivf.tapas.plan.TPS_Plan.TPS_Plan().
household
TPS_Household de.dlr.ivf.tapas.person.TPS_Person.household private
the household the person belongs to
Definition at line 65 of file TPS_Person.java.
id
final int de.dlr.ivf.tapas.person.TPS_Person.id private
id of the person
Definition at line 45 of file TPS_Person.java.
persGroup
TPS_PersonGroup de.dlr.ivf.tapas.person.TPS_Person.persGroup private
the person group
Definition at line 47 of file TPS_Person.java.
preferenceValues
TPS_Preference de.dlr.ivf.tapas.person.TPS_Person.preferenceValues
This is the local reference to the preference model. It must be set before we touch it and the instance must be thread save (either one per thread or synchronized). I decided for one instance per thread. Thus the reference must be set in the TPS_Worker-thread.
Definition at line 42 of file TPS_Person.java.
sex
final TPS_Sex de.dlr.ivf.tapas.person.TPS_Person.sex private
sex of the person
Definition at line 49 of file TPS_Person.java.
teleworker
boolean de.dlr.ivf.tapas.person.TPS_Person.teleworker private
flag if the person is prone to be a teleworker
Definition at line 67 of file TPS_Person.java.
working
final double de.dlr.ivf.tapas.person.TPS_Person.working private
flag if the person is working
Definition at line 69 of file TPS_Person.java.
workLocationID
int de.dlr.ivf.tapas.person.TPS_Person.workLocationID = -1 private
Id to the fixed work location.
Definition at line 73 of file TPS_Person.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/person/TPS_Person.java