TAPAS: de.dlr.ivf.tapas.util.TPS_TripDeleter Class Reference
de.dlr.ivf.tapas.util.TPS_TripDeleter Class Reference
Public Member Functions
TPS_TripDeleter (TPS_ParameterClass parameterClass)
void clearHHID ()
StringBuffer createStringBuffer (ResultSet rs) throws SQLException
int deleteHouseholdsFromTriptable (Connection connection)
ArrayList< Integer > getHh_id ()
void setHh_id (ArrayList< Integer > hhId)
String getKey ()
void setKey (String key)
void putHHID (int id)
void resetConnection (Connection connection, boolean autoCommit, int isolationLevel, Statement statement) throws SQLException
Static Public Member Functions
static void main (String[] args) throws IOException, ClassNotFoundException, SQLException
Detailed Description
Definition at line 34 of file TPS_TripDeleter.java.
Constructor & Destructor Documentation
TPS_TripDeleter()
de.dlr.ivf.tapas.util.TPS_TripDeleter.TPS_TripDeleter (TPS_ParameterClass parameterClass)
Definition at line 41 of file TPS_TripDeleter.java.
Member Function Documentation
clearHHID()
void de.dlr.ivf.tapas.util.TPS_TripDeleter.clearHHID ()
Clears the HHID-resetlist
Definition at line 89 of file TPS_TripDeleter.java.
Referenced by de.dlr.ivf.tapas.iteration.TPS_IterationManagement.resetPlansForRecalculation().
createStringBuffer()
StringBuffer de.dlr.ivf.tapas.util.TPS_TripDeleter.createStringBuffer (ResultSet rs) throws SQLException
This method creates a StringBuffer which contains a SQL-conform Array with all integers above 0 in the ResultSet column 1
Parameters
rs The ResultSet to scan
Returns
A StringBuffer containing a SQL-Array-String
Exceptions
SQLException
Definition at line 101 of file TPS_TripDeleter.java.
deleteHouseholdsFromTriptable()
int de.dlr.ivf.tapas.util.TPS_TripDeleter.deleteHouseholdsFromTriptable (Connection connection)
Method to delete all trips from the trip table which belong to the selected household ids:
diese Funktion soll folgendes tun: 0: hole die sim parameter aus public.simulations (FALSE für den Aufruf-Behaviour...) check 1: sammle alle locations der trips zu den Personen diesen hh_id 2: dekrementiere die locations in temp.locations_<key> 3: lösche diese hh_id aus der trip-table 4: setze alle hh_id in temp.households_<key> auf started= false, finished = false, serverip=null 5: dekrementiere sim_progress aus public.simulations um count(hh_id) 6: setze flags "sim_finished" und "sim_started" in public.simulations auf false
Parameters
connection The connection to use.
Returns
the number of households deleted
Exceptions
SQLException
Definition at line 131 of file TPS_TripDeleter.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.BEHAVIOUR, de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.buildQuery(), de.dlr.ivf.tapas.util.parameters.ParamString.DB_HOUSEHOLD_AND_PERSON_KEY, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_HOUSEHOLD_TMP, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_LOCATION_TMP, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_PERSON, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_TRIPS, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.Behaviour.FAT, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.INFO, de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), de.dlr.ivf.tapas.log.TPS_Logger.log(), and de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.WARN.
Referenced by de.dlr.ivf.tapas.util.TPS_TripDeleter.main(), and de.dlr.ivf.tapas.iteration.TPS_IterationManagement.resetPlansForRecalculation().
getHh_id()
ArrayList<Integer> de.dlr.ivf.tapas.util.TPS_TripDeleter.getHh_id ()
Get the ArrayList of selected household ids
Returns
Definition at line 315 of file TPS_TripDeleter.java.
getKey()
String de.dlr.ivf.tapas.util.TPS_TripDeleter.getKey ()
Returns the key for the simulation
Returns
Definition at line 333 of file TPS_TripDeleter.java.
main()
static void de.dlr.ivf.tapas.util.TPS_TripDeleter.main (String[] args) throws IOException, ClassNotFoundException, SQLException static
Main to test this function
Parameters
args
Exceptions
IOException
ClassNotFoundException
SQLException
Definition at line 53 of file TPS_TripDeleter.java.
References de.dlr.ivf.tapas.util.TPS_TripDeleter.deleteHouseholdsFromTriptable(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.loadRuntimeParameters(), de.dlr.ivf.tapas.util.TPS_TripDeleter.putHHID(), de.dlr.ivf.tapas.util.parameters.ParamString.RUN_IDENTIFIER, de.dlr.ivf.tapas.util.TPS_TripDeleter.setKey(), and de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.setString().
putHHID()
void de.dlr.ivf.tapas.util.TPS_TripDeleter.putHHID (int id)
Adds one household to the set list
Parameters
id the id to reset
Definition at line 351 of file TPS_TripDeleter.java.
References de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), de.dlr.ivf.tapas.log.TPS_Logger.log(), and de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.WARN.
Referenced by de.dlr.ivf.tapas.util.TPS_TripDeleter.main(), and de.dlr.ivf.tapas.iteration.TPS_IterationManagement.resetPlansForRecalculation().
resetConnection()
void de.dlr.ivf.tapas.util.TPS_TripDeleter.resetConnection (Connection connection, boolean autoCommit, int isolationLevel, Statement statement) throws SQLException
Method to roll back all transactions and reset the connection to its initial state
Parameters
connection The Connection to reset
autoCommit should autocommit be enabled? false = transaction mode
isolationLevel The isolation level for the connection
statement The statement to close.
Exceptions
SQLException
Definition at line 371 of file TPS_TripDeleter.java.
setHh_id()
void de.dlr.ivf.tapas.util.TPS_TripDeleter.setHh_id (ArrayList< Integer > hhId)
Set an ArrayList containing the selected household ids
Parameters
hhId
Definition at line 324 of file TPS_TripDeleter.java.
setKey()
void de.dlr.ivf.tapas.util.TPS_TripDeleter.setKey (String key)
Sets the key for the simulation
Parameters
key
Definition at line 342 of file TPS_TripDeleter.java.
Referenced by de.dlr.ivf.tapas.util.TPS_TripDeleter.main(), and de.dlr.ivf.tapas.iteration.TPS_IterationManagement.resetPlansForRecalculation().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/util/TPS_TripDeleter.java