TAPAS: de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer_Zeitreihendatensatz Class Reference
de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer_Zeitreihendatensatz Class Reference
Classes
class Diary
class DiaryElement
Public Member Functions
void calcDiaryStatistics ()
void cleanUpDB (String table)
void clearEverything ()
void printDiariesSQLInserts (String table_episode, String table_schemes, boolean print)
void printDistributionVectorSQLInserts (String tablename, String name, boolean print)
void printDistributionVectors ()
void printSchemeClassSQLInserts (String table, boolean print)
void printStatistics ()
void readMIDDiary (String table, String filter)
Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_BasicConnectionClass ()
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass)
TPS_BasicConnectionClass (String loginFile)
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass, String loginFile)
boolean checkMatrixName (String matrixName)
TPS_ParameterClass getParameters ()
String readParameter (String simKey, String paramKey)
void storeInDB (String matrixName, double[][] matrix, int decimalPlaces)
Static Public Member Functions
static void main (String[] args)
static String makeDiaryKey (long hhID, int pID, int erhebung)
Static Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
static double[][] array1Dto2D (Integer[] matrixVal)
static double[][] array1Dto2D (int[] matrixVal)
static File getRuntimeFile (boolean forceNewFile)
static File getRuntimeFile (String propertyFile, boolean forceNewFile)
static File getRuntimeFile ()
static File getRuntimeFile (String propertyFile)
static int[][] intArray1Dto2D (int[] matrixVal)
static String matrixToSQLArray (double[][] array, int decimalPlaces)
static StringWriter matrixToStringWriterSQL (double[][] array, int decimalPlaces)
Additional Inherited Members
Protected Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
void finalize ()
Protected Attributes inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_DB_Connector dbCon = null
TPS_ParameterClass parameterClass
Detailed Description
Definition at line 21 of file TPS_MiD_Diary_Analyzer_Zeitreihendatensatz.java.
Member Function Documentation
calcDiaryStatistics()
void de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer_Zeitreihendatensatz.calcDiaryStatistics ()
Definition at line 110 of file TPS_MiD_Diary_Analyzer_Zeitreihendatensatz.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer_Zeitreihendatensatz.main().
cleanUpDB()
void de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer_Zeitreihendatensatz.cleanUpDB (String table)
Definition at line 159 of file TPS_MiD_Diary_Analyzer_Zeitreihendatensatz.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute().
Referenced by de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer_Zeitreihendatensatz.main().
clearEverything()
void de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer_Zeitreihendatensatz.clearEverything ()
Definition at line 164 of file TPS_MiD_Diary_Analyzer_Zeitreihendatensatz.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer_Zeitreihendatensatz.main().
main()
static void de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer_Zeitreihendatensatz.main (String[] args) static
Definition at line 51 of file TPS_MiD_Diary_Analyzer_Zeitreihendatensatz.java.
References de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer_Zeitreihendatensatz.calcDiaryStatistics(), de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer_Zeitreihendatensatz.cleanUpDB(), de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer_Zeitreihendatensatz.clearEverything(), de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer_Zeitreihendatensatz.printDistributionVectorSQLInserts(), and de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer_Zeitreihendatensatz.readMIDDiary().
makeDiaryKey()
static String de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer_Zeitreihendatensatz.makeDiaryKey (long hhID, int pID, int erhebung) static
Definition at line 547 of file TPS_MiD_Diary_Analyzer_Zeitreihendatensatz.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer_Zeitreihendatensatz.readMIDDiary().
printDiariesSQLInserts()
void de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer_Zeitreihendatensatz.printDiariesSQLInserts (String table_episode, String table_schemes, boolean print)
Definition at line 184 of file TPS_MiD_Diary_Analyzer_Zeitreihendatensatz.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection().
printDistributionVectors()
void de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer_Zeitreihendatensatz.printDistributionVectors ()
Definition at line 366 of file TPS_MiD_Diary_Analyzer_Zeitreihendatensatz.java.
printDistributionVectorSQLInserts()
void de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer_Zeitreihendatensatz.printDistributionVectorSQLInserts (String tablename, String name, boolean print)
Definition at line 325 of file TPS_MiD_Diary_Analyzer_Zeitreihendatensatz.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute(), and name.
Referenced by de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer_Zeitreihendatensatz.main().
printSchemeClassSQLInserts()
void de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer_Zeitreihendatensatz.printSchemeClassSQLInserts (String table, boolean print)
Definition at line 392 of file TPS_MiD_Diary_Analyzer_Zeitreihendatensatz.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute().
printStatistics()
void de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer_Zeitreihendatensatz.printStatistics ()
Definition at line 518 of file TPS_MiD_Diary_Analyzer_Zeitreihendatensatz.java.
readMIDDiary()
void de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer_Zeitreihendatensatz.readMIDDiary (String table, String filter)
Definition at line 551 of file TPS_MiD_Diary_Analyzer_Zeitreihendatensatz.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), and de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer_Zeitreihendatensatz.makeDiaryKey().
Referenced by de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer_Zeitreihendatensatz.main().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/TPS_MiD_Diary_Analyzer_Zeitreihendatensatz.java