TAPAS: de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.ModalSplitRenderer Class Reference
de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.ModalSplitRenderer Class Reference
Public Member Functions
ModalSplitRenderer (ModalSplitChartDataset dataset)
Paint getItemOutlinePaint (int row, int column)
Paint getItemPaint (int row, int column)
Shape getItemShape (int row, int column)
Private Attributes
final ModalSplitChartDataset dataset
Static Private Attributes
static final long serialVersionUID = 1600719877317415532L
Detailed Description
This class plots boxes the options for plotting the scatter plot and additional lines.
Definition at line 246 of file ModalSplitChart.java.
Constructor & Destructor Documentation
ModalSplitRenderer()
de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.ModalSplitRenderer.ModalSplitRenderer (ModalSplitChartDataset dataset)
Definition at line 251 of file ModalSplitChart.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.ModalSplitRenderer.dataset, de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.getSeriesCount(), and de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.isDataSeries().
Member Function Documentation
getItemOutlinePaint()
Paint de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.ModalSplitRenderer.getItemOutlinePaint (int row, int column)
Definition at line 272 of file ModalSplitChart.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.ModalSplitRenderer.dataset, de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.ModalSplitRenderer.getItemPaint(), de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.isDataSeries(), and de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.selected.
getItemPaint()
Paint de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.ModalSplitRenderer.getItemPaint (int row, int column)
Definition at line 281 of file ModalSplitChart.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.ModalSplitRenderer.dataset, de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.Quality.getColor(), de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.getQuality(), and de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.isDataSeries().
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.ModalSplitRenderer.getItemOutlinePaint().
getItemShape()
Shape de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.ModalSplitRenderer.getItemShape (int row, int column)
Definition at line 287 of file ModalSplitChart.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.ModalSplitRenderer.dataset, de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.getMode(), de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.isDataSeries(), and de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.shapeMap.
Member Data Documentation
dataset
final ModalSplitChartDataset de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.ModalSplitRenderer.dataset private
Definition at line 249 of file ModalSplitChart.java.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.ModalSplitRenderer.getItemOutlinePaint(), de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.ModalSplitRenderer.getItemPaint(), de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.ModalSplitRenderer.getItemShape(), and de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.ModalSplitRenderer.ModalSplitRenderer().
serialVersionUID
final long de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.ModalSplitRenderer.serialVersionUID = 1600719877317415532L static private
Definition at line 248 of file ModalSplitChart.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/runtime/client/Graphics/ModalSplitChart/ModalSplitChart.java