TAPAS: de.dlr.ivf.tapas.runtime.server.SimulationDaemon Class Reference
de.dlr.ivf.tapas.runtime.server.SimulationDaemon Class Reference
Classes
class ServerProcessChecker
class ShutDownProcedure
Public Member Functions
void startServer ()
Static Public Member Functions
static void main (String[] args)
Private Member Functions
SimulationDaemon (String[] args)
Private Attributes
String hostname
final String[] arguments
Timer timer
Static Private Attributes
static final String sysoutPrefix = "-- Daemon -- "
static final SimpleDateFormat SDF = new SimpleDateFormat("dd.MM.yyyy kk:mm:ss")
static Process p
static SimulationDaemon daemon = null
static TPS_DB_Connector con = null
static final List< Process > processes = new ArrayList<>()
static final TPS_ArgumentType<?>[] PARAMETERS
Detailed Description
Author
mark_ma
Definition at line 32 of file SimulationDaemon.java.
Constructor & Destructor Documentation
SimulationDaemon()
de.dlr.ivf.tapas.runtime.server.SimulationDaemon.SimulationDaemon (String[] args) private
This main method starts the SimulationServer and catches each exception which is thrown and stores it in a file with the current timestamp. After 2.5 seconds the simulation server is restarted.
Parameters
args
Definition at line 59 of file SimulationDaemon.java.
References de.dlr.ivf.tapas.util.TPS_Argument.checkArguments(), de.dlr.ivf.tapas.runtime.server.SimulationDaemon.con, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_SERVERS, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeUpdate(), de.dlr.ivf.tapas.util.parameters.ParamString.FILE_WORKING_DIRECTORY, de.dlr.ivf.tapas.runtime.util.DaemonControlProperties.get(), de.dlr.ivf.tapas.runtime.util.IPInfo.getHostname(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.runtime.server.SimulationDaemon.hostname, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.loadRuntimeParameters(), de.dlr.ivf.tapas.runtime.util.DaemonControlProperties.DaemonControlPropKey.LOGIN_CONFIG, de.dlr.ivf.tapas.runtime.server.SimulationDaemon.PARAMETERS, de.dlr.ivf.tapas.runtime.util.DaemonControlProperties.set(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.setString(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.SIM_DIR, and de.dlr.ivf.tapas.runtime.server.SimulationDaemon.timer.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationDaemon.main().
Member Function Documentation
main()
static void de.dlr.ivf.tapas.runtime.server.SimulationDaemon.main (String[] args) static
Definition at line 94 of file SimulationDaemon.java.
References de.dlr.ivf.tapas.runtime.server.SimulationDaemon.daemon, de.dlr.ivf.tapas.runtime.server.SimulationServer.main(), de.dlr.ivf.tapas.runtime.server.SimulationDaemon.p, de.dlr.ivf.tapas.runtime.server.SimulationDaemon.processes, de.dlr.ivf.tapas.runtime.server.SimulationDaemon.SDF, and de.dlr.ivf.tapas.runtime.server.SimulationDaemon.SimulationDaemon().
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationDaemon.startServer().
startServer()
void de.dlr.ivf.tapas.runtime.server.SimulationDaemon.startServer ()
Definition at line 134 of file SimulationDaemon.java.
References de.dlr.ivf.tapas.runtime.server.SimulationDaemon.arguments, de.dlr.ivf.tapas.runtime.server.SimulationDaemon.main(), de.dlr.ivf.tapas.runtime.server.SimulationDaemon.p, and de.dlr.ivf.tapas.runtime.server.SimulationDaemon.sysoutPrefix.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationDaemon.ServerProcessChecker.run().
Member Data Documentation
arguments
final String [] de.dlr.ivf.tapas.runtime.server.SimulationDaemon.arguments private
Definition at line 50 of file SimulationDaemon.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationDaemon.startServer().
con
TPS_DB_Connector de.dlr.ivf.tapas.runtime.server.SimulationDaemon.con = null static private
Definition at line 41 of file SimulationDaemon.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationDaemon.ShutDownProcedure.run(), de.dlr.ivf.tapas.runtime.server.SimulationDaemon.ServerProcessChecker.run(), and de.dlr.ivf.tapas.runtime.server.SimulationDaemon.SimulationDaemon().
daemon
SimulationDaemon de.dlr.ivf.tapas.runtime.server.SimulationDaemon.daemon = null static private
Definition at line 40 of file SimulationDaemon.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationDaemon.main().
hostname
String de.dlr.ivf.tapas.runtime.server.SimulationDaemon.hostname private
Definition at line 49 of file SimulationDaemon.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationDaemon.ShutDownProcedure.run(), de.dlr.ivf.tapas.runtime.server.SimulationDaemon.ServerProcessChecker.run(), and de.dlr.ivf.tapas.runtime.server.SimulationDaemon.SimulationDaemon().
p
Process de.dlr.ivf.tapas.runtime.server.SimulationDaemon.p static private
Definition at line 39 of file SimulationDaemon.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationDaemon.main(), de.dlr.ivf.tapas.runtime.server.SimulationDaemon.ShutDownProcedure.run(), and de.dlr.ivf.tapas.runtime.server.SimulationDaemon.startServer().
PARAMETERS
final TPS_ArgumentType<?> [] de.dlr.ivf.tapas.runtime.server.SimulationDaemon.PARAMETERS static private
Initial value:
= {new TPS_ArgumentType<>("tapas network directory path",
            File.class)}
Parameter array with all parameters for this main method.
PARAMETERS[0] = tapas network directory path
Definition at line 47 of file SimulationDaemon.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationDaemon.SimulationDaemon().
processes
final List<Process> de.dlr.ivf.tapas.runtime.server.SimulationDaemon.processes = new ArrayList<>() static private
Definition at line 42 of file SimulationDaemon.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationDaemon.main().
SDF
final SimpleDateFormat de.dlr.ivf.tapas.runtime.server.SimulationDaemon.SDF = new SimpleDateFormat("dd.MM.yyyy kk:mm:ss") static private
Date format for the exception file appendix
Definition at line 38 of file SimulationDaemon.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationDaemon.main().
sysoutPrefix
final String de.dlr.ivf.tapas.runtime.server.SimulationDaemon.sysoutPrefix = "-- Daemon -- " static private
Definition at line 34 of file SimulationDaemon.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationDaemon.ShutDownProcedure.run(), and de.dlr.ivf.tapas.runtime.server.SimulationDaemon.startServer().
timer
Timer de.dlr.ivf.tapas.runtime.server.SimulationDaemon.timer private
Definition at line 51 of file SimulationDaemon.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationDaemon.SimulationDaemon().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/runtime/server/SimulationDaemon.java