TAPAS: de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer Class Reference
de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer Class Reference
Public Member Functions
RegionAnalyzer (boolean[] distanceCategoryFilter, boolean differentiateRegion)
boolean finish () throws BadLocationException
boolean finish (File exportfile)
double getAvgDistByTrip (Categories category, Enum instance)
double getAvgDistByTrip (Categories[] categories, Enum[] instances)
Set< EnumSet< Categories > > getCategories ()
int getCntPersons (RegionCode region)
int getCntPersons (PersonGroup pg, RegionCode region)
int getCntPersons ()
int getCntPersons (PersonGroup pg)
long getCntTrips (RegionCode region)
long getCntTrips ()
long getCntTrips (Categories category, Enum instance)
long getCntTrips (Categories[] categories, Enum[] instances)
double getDist (Categories category, Enum instance)
double getDist (Categories[] categories, Enum[] instances)
ArrayList< DistanceCategory > getDistanceCategories ()
String getDistanceCategoryDescription (DistanceCategory dc)
double getDur (Categories category, Enum instance)
double getDur (Categories[] categories, Enum[] instances)
double getMaxDuration (RegionCode region)
double getMaxDuration ()
double getMaxTripLength (RegionCode region)
double getMaxTripLength ()
double getMinDuration (RegionCode region)
double getMinDuration ()
double getMinTripLength (RegionCode region)
double getMinTripLength ()
String getSource ()
double getTotalDuration (RegionCode region)
double getTotalDuration ()
double getTotalTripLength (RegionCode region)
double getTotalTripLength ()
boolean init (String outputPath, StyledDocument console, boolean clearSources) throws BadLocationException
boolean init (boolean clearSources)
boolean isRegionDifferentiated ()
boolean prepare (String source, TapasTrip trip, TPS_ParameterClass parameterClass) throws BadLocationException
Public Member Functions inherited from de.dlr.ivf.tapas.analyzer.gui.AbstractCoreProcess
AbstractCoreProcess ()
final boolean cancelFinish ()
void doCancel ()
boolean isCancelled ()
final void run ()
Public Attributes
ArrayList< EnumSet< Categories > > allCategoryCombinations
Private Member Functions
boolean addSource (String source)
ArrayList< EnumSet< Categories > > createAllCombinations ()
TripStats getTripStats (Categories[] cat, Enum[] c)
double saveDiv (double n, double d)
void updateGlobalStatistics (TapasTrip tt)
Private Attributes
StyledDocument console
String outputPath
String source = ""
final EnumMap< Categories, AnalyzerBase > baseAnalyzers
final HashMap< EnumSet< Categories >, Analyzer > analyzers
final boolean differentiateRegion
final EnumMap< RegionCode, GlobalAnalysis > globalAnalysis = new EnumMap<>(RegionCode.class)
Additional Inherited Members
Protected Attributes inherited from de.dlr.ivf.tapas.analyzer.gui.AbstractCoreProcess
boolean isProcessing
Detailed Description
This module analyzes a number of TapasTrips according to the distribution within different Categories.
After adding all trips it is used as a data module for different exports like LegacyExcelWriter.
It extends the AbstractCoreProcess to be used as a module in the TapasAnalyzer.
Author
boec_pa
Definition at line 38 of file RegionAnalyzer.java.
Constructor & Destructor Documentation
RegionAnalyzer()
de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.RegionAnalyzer (boolean[] distanceCategoryFilter, boolean differentiateRegion)
Parameters
distanceCategoryFilter must have the same length as DistanceCategory. true means, that the category is handled separately.
differentiateRegion true if all occurring regions should be treated separately.
Definition at line 58 of file RegionAnalyzer.java.
References de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategory.createFilteredDistances(), de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.DistanceCategory, de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.Job, de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.Mode, de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.PersonGroup, de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.RegionCode.REGION_0, de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.RegionCode, and de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.TripIntention.
Member Function Documentation
addSource()
boolean de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.addSource (String source) private
Returns
true if the source is updated.
Definition at line 109 of file RegionAnalyzer.java.
createAllCombinations()
ArrayList<EnumSet<Categories> > de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.createAllCombinations () private
Creates a list of all Analyzers for easy use and readability.
Returns
Definition at line 127 of file RegionAnalyzer.java.
References de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.DistanceCategory, de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.Job, de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.Mode, de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.PersonGroup, de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.RegionCode, and de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.TripIntention.
finish() [1/2]
boolean de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.finish () throws BadLocationException
Muss aufgerufen werden, wenn der Prozess beendet wird
Returns
Implements de.dlr.ivf.tapas.analyzer.core.CoreProcessInterface.
Definition at line 163 of file RegionAnalyzer.java.
References de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyTextWriter.process(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyExcelWriter.writeStatistics(), and de.dlr.ivf.tapas.analyzer.tum.results.DatabaseSummaryExport.writeSummary().
finish() [2/2]
boolean de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.finish (File exportfile)
Reimplemented from de.dlr.ivf.tapas.analyzer.gui.AbstractCoreProcess.
Definition at line 206 of file RegionAnalyzer.java.
getAvgDistByTrip() [1/2]
double de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getAvgDistByTrip (Categories category, Enum instance)
Get the average distance for a specific instance (e.g. bike) of a category (e.g. mode)
Parameters
category
instance must be from the category given as parameter
Exceptions
IllegalArgumentException if there is no Analyzer considering cat.
Definition at line 219 of file RegionAnalyzer.java.
References categories.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyExcelWriter.writeFurtherValuesData(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyExcelWriter.writeWegelaengenData().
getAvgDistByTrip() [2/2]
double de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getAvgDistByTrip (Categories[] categories, Enum[] instances)
Get the average distance for a specific combination of instances (e.g. [bike, shopping]) of categories (e.g. [mode, trip intention])
Parameters
categories
instances must be the same length as categories and every element must be from the according category.
Exceptions
IllegalArgumentException if the combination of categories is not found.
Definition at line 234 of file RegionAnalyzer.java.
References categories, de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.TripStats.getCntTrips(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.TripStats.getDist().
getCategories()
Set<EnumSet<Categories> > de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getCategories ()
Definition at line 239 of file RegionAnalyzer.java.
getCntPersons() [1/4]
int de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getCntPersons ()
Definition at line 253 of file RegionAnalyzer.java.
References de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.RegionCode.REGION_0.
getCntPersons() [2/4]
int de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getCntPersons (PersonGroup pg)
Definition at line 257 of file RegionAnalyzer.java.
References de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.RegionCode.REGION_0.
getCntPersons() [3/4]
int de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getCntPersons (PersonGroup pg, RegionCode region)
Definition at line 249 of file RegionAnalyzer.java.
getCntPersons() [4/4]
int de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getCntPersons (RegionCode region)
Definition at line 245 of file RegionAnalyzer.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.results.DatabaseSummaryExport.fillBatch(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyExcelWriter.writeFurtherValuesData(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyExcelWriter.writePersongroupData(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyExcelWriter.writeWegelaengenData().
getCntTrips() [1/4]
long de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getCntTrips ()
Definition at line 265 of file RegionAnalyzer.java.
References de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.RegionCode.REGION_0.
getCntTrips() [2/4]
long de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getCntTrips (Categories category, Enum instance)
Get the number of trips for a specific instance (e.g. bike) of a category (e.g. mode)
Parameters
category
instance must be from the category given as parameter
Returns
Exceptions
IllegalArgumentException if there is no Analyzer considering cat.
Definition at line 278 of file RegionAnalyzer.java.
getCntTrips() [3/4]
long de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getCntTrips (Categories[] categories, Enum[] instances)
Get the number of trips for a specific combination of instances (e.g. [bike, shopping]) of categories (e.g. [mode, trip intention])
Parameters
categories
instances must be the same length as categories and every element must be from the according category.
Exceptions
IllegalArgumentException if the combination of categories is not found.
Definition at line 293 of file RegionAnalyzer.java.
References categories.
getCntTrips() [4/4]
long de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getCntTrips (RegionCode region)
Definition at line 261 of file RegionAnalyzer.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.results.DatabaseSummaryExport.fillBatch(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyExcelWriter.writeFurtherValuesData(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyExcelWriter.writeModalsplitData(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyExcelWriter.writePersongroupData(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyExcelWriter.writeStatistics(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyExcelWriter.writeWegelaengenData().
getDist() [1/2]
double de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getDist (Categories category, Enum instance)
Get the accumulated distance for a specific instance (e.g. bike) of a category (e.g. mode)
Parameters
category
instance must be from the category given as parameter
Exceptions
IllegalArgumentException if there is no Analyzer considering cat.
Definition at line 305 of file RegionAnalyzer.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.results.DatabaseSummaryExport.fillBatch(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyExcelWriter.writePersongroupData().
getDist() [2/2]
double de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getDist (Categories[] categories, Enum[] instances)
Get the accumulated distance for a specific combination of instances (e.g. [bike, shopping]) of categories (e.g. [mode, trip intention])
Parameters
categories
instances must be the same length as categories and every element must be from the according category.
Exceptions
IllegalArgumentException if the combination of categories is not found.
Definition at line 320 of file RegionAnalyzer.java.
References categories.
getDistanceCategories()
ArrayList<DistanceCategory> de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getDistanceCategories ()
Returns
all active distance categories (after filtering).
Definition at line 327 of file RegionAnalyzer.java.
References de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.DistanceCategory.
getDistanceCategoryDescription()
String de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getDistanceCategoryDescription (DistanceCategory dc)
Returns
the description of a distance category after filtering, e.g. 1-10km.
Definition at line 335 of file RegionAnalyzer.java.
References de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.DistanceCategory.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyExcelWriter.initModalsplitSheet().
getDur() [1/2]
double de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getDur (Categories category, Enum instance)
Get the accumulated duration for a specific instance (e.g. bike) of a category (e.g. mode)
Parameters
category
instance must be from the category given as parameter
Exceptions
IllegalArgumentException if there is no Analyzer considering cat.
Definition at line 347 of file RegionAnalyzer.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.results.DatabaseSummaryExport.fillBatch().
getDur() [2/2]
double de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getDur (Categories[] categories, Enum[] instances)
Get the accumulated duration for a specific combination of instances (e.g. [bike, shopping]) of categories (e.g. [mode, trip intention])
Parameters
categories
instances must be the same length as categories and every element must be from the according category.
Exceptions
IllegalArgumentException if the combination of categories is not found.
Definition at line 362 of file RegionAnalyzer.java.
References categories.
getMaxDuration() [1/2]
double de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getMaxDuration ()
Definition at line 370 of file RegionAnalyzer.java.
References de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.RegionCode.REGION_0.
getMaxDuration() [2/2]
double de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getMaxDuration (RegionCode region)
Definition at line 366 of file RegionAnalyzer.java.
getMaxTripLength() [1/2]
double de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getMaxTripLength ()
Definition at line 378 of file RegionAnalyzer.java.
References de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.RegionCode.REGION_0.
getMaxTripLength() [2/2]
double de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getMaxTripLength (RegionCode region)
Definition at line 374 of file RegionAnalyzer.java.
getMinDuration() [1/2]
double de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getMinDuration ()
Definition at line 386 of file RegionAnalyzer.java.
References de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.RegionCode.REGION_0.
getMinDuration() [2/2]
double de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getMinDuration (RegionCode region)
Definition at line 382 of file RegionAnalyzer.java.
getMinTripLength() [1/2]
double de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getMinTripLength ()
Definition at line 394 of file RegionAnalyzer.java.
References de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.RegionCode.REGION_0.
getMinTripLength() [2/2]
double de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getMinTripLength (RegionCode region)
Definition at line 390 of file RegionAnalyzer.java.
getSource()
String de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getSource ()
Definition at line 398 of file RegionAnalyzer.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.results.DatabaseSummaryExport.DatabaseSummaryExport(), and de.dlr.ivf.tapas.analyzer.tum.results.DatabaseSummaryExport.fillBatch().
getTotalDuration() [1/2]
double de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getTotalDuration ()
Definition at line 406 of file RegionAnalyzer.java.
References de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.RegionCode.REGION_0.
getTotalDuration() [2/2]
double de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getTotalDuration (RegionCode region)
Definition at line 402 of file RegionAnalyzer.java.
getTotalTripLength() [1/2]
double de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getTotalTripLength ()
Definition at line 415 of file RegionAnalyzer.java.
References de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.RegionCode.REGION_0.
getTotalTripLength() [2/2]
double de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getTotalTripLength (RegionCode region)
Definition at line 410 of file RegionAnalyzer.java.
getTripStats()
TripStats de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getTripStats (Categories[] cat, Enum[] c) private
Main access method to get information from Analyzer.
Parameters
cat e.g. [Categories.RegionCode, Categories.TripIntention]
c e.g. [RegionCode.REGION_0, TripIntention.TRIP_31]
Returns
TripStats
Definition at line 426 of file RegionAnalyzer.java.
References de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.Analyzer.getTripStats().
init() [1/2]
boolean de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.init (boolean clearSources)
Must be called once before executing the de.dlr.ivf.tapas.tools.TUM.IntegratedTUM
Parameters
clearSources Flag to omit previous results
Returns
Reimplemented from de.dlr.ivf.tapas.analyzer.gui.AbstractCoreProcess.
Definition at line 449 of file RegionAnalyzer.java.
init() [2/2]
boolean de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.init (String outputPath, StyledDocument console, boolean clearSources) throws BadLocationException
Parameters
console my be null. Then, only error messages will be printed in the error stream.
Exceptions
BadLocationException
Implements de.dlr.ivf.tapas.analyzer.core.CoreProcessInterface.
Definition at line 439 of file RegionAnalyzer.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.doInBackground().
isRegionDifferentiated()
boolean de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.isRegionDifferentiated ()
Definition at line 454 of file RegionAnalyzer.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.results.DatabaseSummaryExport.fillBatch().
prepare()
boolean de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.prepare (String filePath, TapasTrip trip, TPS_ParameterClass parameterClass) throws BadLocationException
Muss vor dem Start des Prozesses fr jeden zu behandelnden Trip aufgerufen werden.
Parameters
filePath Der Pfad zum Trip
trip der Trip
Returns
Implements de.dlr.ivf.tapas.analyzer.core.CoreProcessInterface.
Definition at line 459 of file RegionAnalyzer.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.doInBackground().
saveDiv()
double de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.saveDiv (double n, double d) private
Returns
0.0 if d == 0 and n/d else
Definition at line 476 of file RegionAnalyzer.java.
updateGlobalStatistics()
void de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.updateGlobalStatistics (TapasTrip tt) private
Covers all statistics that are not specifically for one Analyzer like total trip length or the number of unique persons.
Parameters
tt
Definition at line 487 of file RegionAnalyzer.java.
References de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.PersonGroup, de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.RegionCode.REGION_0, and de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.RegionCode.
Member Data Documentation
allCategoryCombinations
ArrayList<EnumSet<Categories> > de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.allCategoryCombinations
Definition at line 40 of file RegionAnalyzer.java.
analyzers
final HashMap<EnumSet<Categories>, Analyzer> de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.analyzers private
Definition at line 46 of file RegionAnalyzer.java.
baseAnalyzers
final EnumMap<Categories, AnalyzerBase> de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.baseAnalyzers private
Definition at line 45 of file RegionAnalyzer.java.
console
StyledDocument de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.console private
Definition at line 42 of file RegionAnalyzer.java.
differentiateRegion
final boolean de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.differentiateRegion private
Definition at line 47 of file RegionAnalyzer.java.
globalAnalysis
final EnumMap<RegionCode, GlobalAnalysis> de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.globalAnalysis = new EnumMap<>(RegionCode.class) private
Definition at line 48 of file RegionAnalyzer.java.
outputPath
String de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.outputPath private
Definition at line 43 of file RegionAnalyzer.java.
source
String de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.source = "" private
Definition at line 44 of file RegionAnalyzer.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/tum/regionanalyzer/RegionAnalyzer.java