TAPAS: de.dlr.ivf.tapas.tools.TPS_CapacityCalculator Class Reference
de.dlr.ivf.tapas.tools.TPS_CapacityCalculator Class Reference
Classes
class CapacityInfo
class CapacityType
class TargetLocation
Public Member Functions
void addHouseHoldsForVisit (String hhTable, String hhKey, String tazTable)
void aggregateValues (Map< String, CapacityType > map)
void catMatchingCSVImport (String filename, String tablename)
void emptyLocations (String destination)
void generateCodeMap ()
void loadLocations (String origin)
void loadNexigaLocations (String origin)
void printCodeMap ()
void printLocations ()
void printMappingValues (Map< String, CapacityType > map)
void readBosserhofMapingValues ()
void readBosserhofValues ()
void storeCodeMap (String table)
void storeLocations (String destination, boolean updateTAZ, String tazMultiline, boolean updateBlocks, String blockMultiline)
void updateLocCodesInBosserhofMapingValues ()
void updateLocationCapacity (String tableName)
Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_BasicConnectionClass ()
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass)
TPS_BasicConnectionClass (String loginFile)
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass, String loginFile)
boolean checkMatrixName (String matrixName)
TPS_ParameterClass getParameters ()
String readParameter (String simKey, String paramKey)
void storeInDB (String matrixName, double[][] matrix, int decimalPlaces)
Static Public Member Functions
static String getCombinedCategory (String cat1, String cat2, String cat3)
static void main (String[] args)
Static Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
static double[][] array1Dto2D (Integer[] matrixVal)
static double[][] array1Dto2D (int[] matrixVal)
static File getRuntimeFile (boolean forceNewFile)
static File getRuntimeFile (String propertyFile, boolean forceNewFile)
static File getRuntimeFile ()
static File getRuntimeFile (String propertyFile)
static int[][] intArray1Dto2D (int[] matrixVal)
static String matrixToSQLArray (double[][] array, int decimalPlaces)
static StringWriter matrixToStringWriterSQL (double[][] array, int decimalPlaces)
Private Member Functions
void aggregateCat (String[] array, Map< String, CapacityType > catMap, Map< String, CapacityType > sourceMap, int catLevel)
String makeSQLArray (String separatedArrary, String separator)
Additional Inherited Members
Protected Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
void finalize ()
Protected Attributes inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_DB_Connector dbCon = null
TPS_ParameterClass parameterClass
Detailed Description
Definition at line 25 of file TPS_CapacityCalculator.java.
Member Function Documentation
addHouseHoldsForVisit()
void de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.addHouseHoldsForVisit (String hhTable, String hhKey, String tazTable)
Definition at line 90 of file TPS_CapacityCalculator.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery().
aggregateCat()
void de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.aggregateCat (String[] array, Map< String, CapacityType > catMap, Map< String, CapacityType > sourceMap, int catLevel) private
Definition at line 130 of file TPS_CapacityCalculator.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.aggregateValues().
aggregateValues()
void de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.aggregateValues (Map< String, CapacityType > map)
Definition at line 198 of file TPS_CapacityCalculator.java.
References de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.aggregateCat().
Referenced by de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.main().
catMatchingCSVImport()
void de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.catMatchingCSVImport (String filename, String tablename)
Definition at line 228 of file TPS_CapacityCalculator.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute(), de.dlr.ivf.tapas.log.TPS_Logger.log(), and de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.makeSQLArray().
emptyLocations()
void de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.emptyLocations (String destination)
Definition at line 275 of file TPS_CapacityCalculator.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute().
generateCodeMap()
void de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.generateCodeMap ()
Definition at line 281 of file TPS_CapacityCalculator.java.
References code, de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), and de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.getCombinedCategory().
Referenced by de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.main().
getCombinedCategory()
static String de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.getCombinedCategory (String cat1, String cat2, String cat3) static
Definition at line 48 of file TPS_CapacityCalculator.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.generateCodeMap().
loadLocations()
void de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.loadLocations (String origin)
Definition at line 325 of file TPS_CapacityCalculator.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery().
loadNexigaLocations()
void de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.loadNexigaLocations (String origin)
Definition at line 424 of file TPS_CapacityCalculator.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery().
main()
static void de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.main (String[] args) static
Definition at line 60 of file TPS_CapacityCalculator.java.
References de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.aggregateValues(), de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.generateCodeMap(), de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.printCodeMap(), and de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.readBosserhofMapingValues().
makeSQLArray()
String de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.makeSQLArray (String separatedArrary, String separator) private
Definition at line 492 of file TPS_CapacityCalculator.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.catMatchingCSVImport().
printCodeMap()
void de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.printCodeMap ()
Definition at line 510 of file TPS_CapacityCalculator.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.main().
printLocations()
void de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.printLocations ()
Definition at line 516 of file TPS_CapacityCalculator.java.
printMappingValues()
void de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.printMappingValues (Map< String, CapacityType > map)
Definition at line 525 of file TPS_CapacityCalculator.java.
readBosserhofMapingValues()
void de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.readBosserhofMapingValues ()
Definition at line 535 of file TPS_CapacityCalculator.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery().
Referenced by de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.main().
readBosserhofValues()
void de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.readBosserhofValues ()
Definition at line 581 of file TPS_CapacityCalculator.java.
References code, de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery().
storeCodeMap()
void de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.storeCodeMap (String table)
Definition at line 625 of file TPS_CapacityCalculator.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection().
storeLocations()
void de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.storeLocations (String destination, boolean updateTAZ, String tazMultiline, boolean updateBlocks, String blockMultiline)
Definition at line 658 of file TPS_CapacityCalculator.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeUpdate(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection().
updateLocationCapacity()
void de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.updateLocationCapacity (String tableName)
Definition at line 739 of file TPS_CapacityCalculator.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeUpdate().
updateLocCodesInBosserhofMapingValues()
void de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.updateLocCodesInBosserhofMapingValues ()
Definition at line 717 of file TPS_CapacityCalculator.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeUpdate().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/TPS_CapacityCalculator.java