TAPAS: de.dlr.ivf.tapas.loc.TPS_Block Class Reference
de.dlr.ivf.tapas.loc.TPS_Block Class Reference
Public Member Functions
TPS_Block (int id)
boolean addLocation (TPS_Location location)
int compareTo (TPS_Block o)
boolean containsLocation (TPS_Location loc)
TPS_Coordinate getCenter ()
void setCenter (TPS_Coordinate center)
int getId ()
double getNearestPubTransStop ()
void setNearestPubTransStop (double nearestPubTransStop)
double getScore ()
void setScore (double score)
int getScoreCat ()
void setScoreCat (int scoreCat)
TPS_TrafficAnalysisZone getTrafficAnalysisZone ()
void setTrafficAnalysisZone (TPS_TrafficAnalysisZone taz)
void setCenter (double x, double y)
String toString ()
Private Attributes
final int id
final List< TPS_Location > locations
double nearestPubTransStop
TPS_TrafficAnalysisZone taz
double score
int scoreCat
TPS_Coordinate center
Detailed Description
A traffic analysis zone is territorially subdivided in blocks. Each traffic analysis zone contains of at least one block which fills the whole traffic analysis zone. The amount of blocks is not limited.
Author
mark_ma
Definition at line 24 of file TPS_Block.java.
Constructor & Destructor Documentation
TPS_Block()
de.dlr.ivf.tapas.loc.TPS_Block.TPS_Block (int id)
Constructs a block with the given id and an empty location list.
Parameters
id id of the block
Definition at line 66 of file TPS_Block.java.
Member Function Documentation
addLocation()
boolean de.dlr.ivf.tapas.loc.TPS_Block.addLocation (TPS_Location location)
This method adds the given location to the block's list and sets the reference of the location to this block, i.e. the mutual connection is built up.
Parameters
location Location the reference should be set for
Returns
true if the location was added, false otherwise
Definition at line 79 of file TPS_Block.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readRegion().
compareTo()
int de.dlr.ivf.tapas.loc.TPS_Block.compareTo (TPS_Block o)
Definition at line 84 of file TPS_Block.java.
References de.dlr.ivf.tapas.loc.TPS_Block.id.
containsLocation()
boolean de.dlr.ivf.tapas.loc.TPS_Block.containsLocation (TPS_Location loc)
Checks if the block has a reference to the location provided
Parameters
loc location a reference should be checked for
Returns
true if the block has a reference to the location, false otherwise
Definition at line 94 of file TPS_Block.java.
getCenter()
TPS_Coordinate de.dlr.ivf.tapas.loc.TPS_Block.getCenter ()
Gets the center of this block
Returns
A TPS_Coordinate containing the block center
Definition at line 103 of file TPS_Block.java.
getId()
int de.dlr.ivf.tapas.loc.TPS_Block.getId ()
Returns the ID of the block
Returns
id
Definition at line 121 of file TPS_Block.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.batchStoreTrips(), and de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes().
getNearestPubTransStop()
double de.dlr.ivf.tapas.loc.TPS_Block.getNearestPubTransStop ()
Returns the distance to the next public transport stop in this block in meters
Returns
distance to the nearest public transport stop
Definition at line 130 of file TPS_Block.java.
Referenced by de.dlr.ivf.tapas.mode.TPS_MassTransportMode.getTravelTime().
getScore()
double de.dlr.ivf.tapas.loc.TPS_Block.getScore ()
Returns the score of the public transport quality for the block
Returns
score
Definition at line 148 of file TPS_Block.java.
getScoreCat()
int de.dlr.ivf.tapas.loc.TPS_Block.getScoreCat ()
Returns the score category of the public transport quality for the block
Returns
score category
Definition at line 166 of file TPS_Block.java.
Referenced by de.dlr.ivf.tapas.mode.TPS_MassTransportMode.getScore().
getTrafficAnalysisZone()
TPS_TrafficAnalysisZone de.dlr.ivf.tapas.loc.TPS_Block.getTrafficAnalysisZone ()
Returns the traffic analysis zone of the block
Returns
traffic analysis zone
Definition at line 184 of file TPS_Block.java.
setCenter() [1/2]
void de.dlr.ivf.tapas.loc.TPS_Block.setCenter (double x, double y)
Sets the center according to the given coordinates
Parameters
x x-value
y y-value
Definition at line 203 of file TPS_Block.java.
References de.dlr.ivf.tapas.loc.TPS_Coordinate.setValues().
setCenter() [2/2]
void de.dlr.ivf.tapas.loc.TPS_Block.setCenter (TPS_Coordinate center)
Sets the center of this block
Parameters
center The bölock center
Definition at line 112 of file TPS_Block.java.
References de.dlr.ivf.tapas.loc.TPS_Coordinate.getValue().
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readRegion().
setNearestPubTransStop()
void de.dlr.ivf.tapas.loc.TPS_Block.setNearestPubTransStop (double nearestPubTransStop)
Sets the distance in meters to the nearest public transport stop in this block
Parameters
nearestPubTransStop
Definition at line 139 of file TPS_Block.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readRegion().
setScore()
void de.dlr.ivf.tapas.loc.TPS_Block.setScore (double score)
Sets the score of the public transport quality for the block
Parameters
score
Definition at line 157 of file TPS_Block.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readRegion().
setScoreCat()
void de.dlr.ivf.tapas.loc.TPS_Block.setScoreCat (int scoreCat)
Sets score category of the public transport quality for the block
Parameters
scoreCat
Definition at line 175 of file TPS_Block.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readRegion().
setTrafficAnalysisZone()
void de.dlr.ivf.tapas.loc.TPS_Block.setTrafficAnalysisZone (TPS_TrafficAnalysisZone taz)
Sets reference to the traffic analysis zone.
Parameters
taz the traffic analysis zone (tvz)
Definition at line 193 of file TPS_Block.java.
Referenced by de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.getBlock().
toString()
String de.dlr.ivf.tapas.loc.TPS_Block.toString ()
Definition at line 217 of file TPS_Block.java.
Member Data Documentation
center
TPS_Coordinate de.dlr.ivf.tapas.loc.TPS_Block.center private
Center coordinate of this block
Definition at line 59 of file TPS_Block.java.
id
final int de.dlr.ivf.tapas.loc.TPS_Block.id private
Block id
Definition at line 29 of file TPS_Block.java.
Referenced by de.dlr.ivf.tapas.loc.TPS_Block.compareTo().
locations
final List<TPS_Location> de.dlr.ivf.tapas.loc.TPS_Block.locations private
List of all locations in this block
Definition at line 34 of file TPS_Block.java.
nearestPubTransStop
double de.dlr.ivf.tapas.loc.TPS_Block.nearestPubTransStop private
Distance to the nearest public transport stop in this block in meters
Definition at line 39 of file TPS_Block.java.
score
double de.dlr.ivf.tapas.loc.TPS_Block.score private
score value
Definition at line 49 of file TPS_Block.java.
scoreCat
int de.dlr.ivf.tapas.loc.TPS_Block.scoreCat private
Category of score for the public transport quality
Definition at line 54 of file TPS_Block.java.
taz
TPS_TrafficAnalysisZone de.dlr.ivf.tapas.loc.TPS_Block.taz private
Reference to the traffic analysis zone this block is inside
Definition at line 44 of file TPS_Block.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/loc/TPS_Block.java