TAPAS: de.dlr.ivf.tapas.scheme.TPS_Scheme Class Reference
de.dlr.ivf.tapas.scheme.TPS_Scheme Class Reference
Classes
class TourPartIterator
Public Member Functions
TPS_Scheme (int id, TPS_ParameterClass parameterClass)
boolean addEpisode (TPS_Episode episode)
TPS_Scheme clone ()
Iterable< TPS_Episode > getEpisodeIterator ()
int getId ()
double getOriginalTravelDuration ()
TPS_SchemePart getSchemePart (TPS_Episode episode)
List< TPS_SchemePart > getSchemeParts ()
double getTimeUsageAVG ()
double getTimeUsageSTD ()
Iterable< TPS_TourPart > getTourPartIterator ()
int hashCode ()
void init ()
Iterator< TPS_SchemePart > iterator ()
int size ()
String toString ()
String toString (String prefix)
Private Attributes
final int id
double originalTravelDuration
TPS_SchemeClass schemeClass
final List< TPS_SchemePart > schemeParts
final TPS_ParameterClass parameterClass
Detailed Description
This class provides a scheme. All schemes are singleton instances, so that the plans have just a reference to the scheme but doesn't manipulate it. A scheme is divided into tour and home parts. Tour parts consists of stays and trips and home parts does only contain of stays which are located at home.
Definition at line 30 of file TPS_Scheme.java.
Constructor & Destructor Documentation
TPS_Scheme()
de.dlr.ivf.tapas.scheme.TPS_Scheme.TPS_Scheme (int id, TPS_ParameterClass parameterClass)
New scheme for a given id and a parameter class reference
Parameters
id scheme id
parameterClass parameter class reference
Definition at line 60 of file TPS_Scheme.java.
Member Function Documentation
addEpisode()
boolean de.dlr.ivf.tapas.scheme.TPS_Scheme.addEpisode (TPS_Episode episode)
This method adds the given episode to the last scheme part of the scheme. When there is no scheme part a home part is created (a scheme starts at home). When the last scheme past does not fit to the tour number or the fact that it is a home part a new part is created. At last the episode is added to the last scheme part.
Parameters
episode the episode to add
Returns
true if the episode was added successful, false otherwise
Definition at line 75 of file TPS_Scheme.java.
References de.dlr.ivf.tapas.scheme.TPS_SchemePart.addStay(), de.dlr.ivf.tapas.constants.TPS_ActivityConstant.getActivityCodeByTypeAndCode(), de.dlr.ivf.tapas.scheme.TPS_Scheme.getId(), de.dlr.ivf.tapas.scheme.TPS_SchemePart.getId(), de.dlr.ivf.tapas.scheme.TPS_SchemePart.getLastEpisode(), de.dlr.ivf.tapas.scheme.TPS_Episode.getOriginalDuration(), de.dlr.ivf.tapas.scheme.TPS_Episode.getOriginalEnd(), de.dlr.ivf.tapas.scheme.TPS_SchemePart.getScheme(), de.dlr.ivf.tapas.scheme.TPS_Episode.isHomePart, de.dlr.ivf.tapas.scheme.TPS_SchemePart.isHomePart(), de.dlr.ivf.tapas.scheme.TPS_Episode.isStay(), de.dlr.ivf.tapas.scheme.TPS_SchemePart.isTourPart(), de.dlr.ivf.tapas.util.parameters.ParamValue.SEC_TIME_SLOT, de.dlr.ivf.tapas.scheme.TPS_Episode.setOriginalDuration(), de.dlr.ivf.tapas.scheme.TPS_Episode.toString(), de.dlr.ivf.tapas.scheme.TPS_Episode.tourNumber, and de.dlr.ivf.tapas.constants.TPS_ActivityConstant.TPS_ActivityCodeType.ZBE.
Referenced by de.dlr.ivf.tapas.scheme.TPS_Scheme.clone(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readSchemeSet().
clone()
TPS_Scheme de.dlr.ivf.tapas.scheme.TPS_Scheme.clone ()
Definition at line 121 of file TPS_Scheme.java.
References de.dlr.ivf.tapas.scheme.TPS_Scheme.addEpisode(), de.dlr.ivf.tapas.scheme.TPS_Episode.clone(), de.dlr.ivf.tapas.scheme.TPS_Scheme.init(), and de.dlr.ivf.tapas.scheme.TPS_Scheme.schemeClass.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.TPS_Plan().
getEpisodeIterator()
Iterable<TPS_Episode> de.dlr.ivf.tapas.scheme.TPS_Scheme.getEpisodeIterator ()
Returns
An instance of EpisodeIterator
Definition at line 139 of file TPS_Scheme.java.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.calcPlanFeasiblity(), de.dlr.ivf.tapas.plan.TPS_Plan.reset(), de.dlr.ivf.tapas.plan.TPS_Plan.toString(), and de.dlr.ivf.tapas.plan.TPS_Plan.TPS_Plan().
getId()
int de.dlr.ivf.tapas.scheme.TPS_Scheme.getId ()
Returns the id of the scheme
Returns
id
Definition at line 148 of file TPS_Scheme.java.
Referenced by de.dlr.ivf.tapas.scheme.TPS_Scheme.addEpisode(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.batchStoreTrips(), de.dlr.ivf.tapas.plan.TPS_Plan.createOutput(), de.dlr.ivf.tapas.scheme.TPS_SchemeSet.findScheme(), de.dlr.ivf.tapas.scheme.TPS_SchemeClass.getScheme(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readSchemeSet(), and de.dlr.ivf.tapas.plan.TPS_Plan.writeOutputStream().
getOriginalTravelDuration()
double de.dlr.ivf.tapas.scheme.TPS_Scheme.getOriginalTravelDuration ()
Returns
complete travel duration of all trips of the scheme
Definition at line 170 of file TPS_Scheme.java.
getSchemePart()
TPS_SchemePart de.dlr.ivf.tapas.scheme.TPS_Scheme.getSchemePart (TPS_Episode episode)
Method to get the according scheme part for a given episode. Returns null if this episode is not part of this scheme
Parameters
episode the episode to look for
Returns
the scheme part, which contains the episode or null, if the episode is not part of this scheme
Definition at line 213 of file TPS_Scheme.java.
getSchemeParts()
List<TPS_SchemePart> de.dlr.ivf.tapas.scheme.TPS_Scheme.getSchemeParts ()
Definition at line 222 of file TPS_Scheme.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Worker.processHousehold().
getTimeUsageAVG()
double de.dlr.ivf.tapas.scheme.TPS_Scheme.getTimeUsageAVG ()
Returns the average travel time expenditure in the diary class the scheme belongs to
Returns
average travel time expenditures in minutes
Definition at line 231 of file TPS_Scheme.java.
getTimeUsageSTD()
double de.dlr.ivf.tapas.scheme.TPS_Scheme.getTimeUsageSTD ()
Returns the standard deviance of the travel time in the diary class the scheme belongs to
Returns
the standard deviance of the average as ratio of the average travel time expenditure
Definition at line 240 of file TPS_Scheme.java.
getTourPartIterator()
Iterable<TPS_TourPart> de.dlr.ivf.tapas.scheme.TPS_Scheme.getTourPartIterator ()
This method returns an iterator over all trips in this scheme.
Returns
an instance of TourPartIterator
Definition at line 249 of file TPS_Scheme.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.batchStoreTrips(), de.dlr.ivf.tapas.plan.TPS_Plan.createOutput(), de.dlr.ivf.tapas.plan.TPS_Plan.reset(), and de.dlr.ivf.tapas.plan.TPS_Plan.writeOutputStream().
hashCode()
int de.dlr.ivf.tapas.scheme.TPS_Scheme.hashCode ()
Definition at line 259 of file TPS_Scheme.java.
init()
void de.dlr.ivf.tapas.scheme.TPS_Scheme.init ()
Initialises the hierarchies in the tours and calculates the complete travel duration.
Definition at line 266 of file TPS_Scheme.java.
Referenced by de.dlr.ivf.tapas.scheme.TPS_Scheme.clone(), and de.dlr.ivf.tapas.scheme.TPS_SchemeSet.init().
iterator()
Iterator<TPS_SchemePart> de.dlr.ivf.tapas.scheme.TPS_Scheme.iterator ()
Definition at line 286 of file TPS_Scheme.java.
size()
int de.dlr.ivf.tapas.scheme.TPS_Scheme.size ()
Returns the number of episodes the scheme consists of
Returns
the number of episodes
Definition at line 295 of file TPS_Scheme.java.
References de.dlr.ivf.tapas.scheme.TPS_SchemePart.size().
toString() [1/2]
String de.dlr.ivf.tapas.scheme.TPS_Scheme.toString ()
Definition at line 309 of file TPS_Scheme.java.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.toString().
toString() [2/2]
String de.dlr.ivf.tapas.scheme.TPS_Scheme.toString (String prefix)
This method should print the object naturally with the given prefix.
Parameters
prefix
Returns
prefix + toString();
Implements de.dlr.ivf.tapas.util.ExtendedWritable.
Definition at line 318 of file TPS_Scheme.java.
References de.dlr.ivf.tapas.scheme.TPS_SchemePart.toString().
Member Data Documentation
id
final int de.dlr.ivf.tapas.scheme.TPS_Scheme.id private
id of the scheme
Definition at line 35 of file TPS_Scheme.java.
originalTravelDuration
double de.dlr.ivf.tapas.scheme.TPS_Scheme.originalTravelDuration private
original travel duration of this scheme in seconds
Definition at line 39 of file TPS_Scheme.java.
parameterClass
final TPS_ParameterClass de.dlr.ivf.tapas.scheme.TPS_Scheme.parameterClass private
this method returns the number of scheme parts in this scheme
Definition at line 52 of file TPS_Scheme.java.
schemeClass
TPS_SchemeClass de.dlr.ivf.tapas.scheme.TPS_Scheme.schemeClass private
Reference to the corresponding scheme class
Definition at line 43 of file TPS_Scheme.java.
Referenced by de.dlr.ivf.tapas.scheme.TPS_Scheme.clone().
schemeParts
final List<TPS_SchemePart> de.dlr.ivf.tapas.scheme.TPS_Scheme.schemeParts private
List of all scheme parts
Definition at line 47 of file TPS_Scheme.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/scheme/TPS_Scheme.java