TAPAS: de.dlr.ivf.tapas.scheme.TPS_TourPart.TravelDurations Class Reference
de.dlr.ivf.tapas.scheme.TPS_TourPart.TravelDurations Class Reference
Public Member Functions
double getArrivalDuration (TPS_ParameterClass parameterClass)
double getDepartureDuration (TPS_ParameterClass parameterClass)
void setArrivalDuration (double arrivalDuration)
void setDepartureDuration (double departureDuration)
String toString ()
Private Attributes
double arrivalDuration
double departureDuration
Detailed Description
Structure to store the complete arrival and departure duration for one stay in the tour part.
Example:
episodes t s t s t s t s t
durations 10 12 16 90 20 16 10 50 20
the complete arrival duration for the second stay is 10 + 16 = 26
and the complete departure duration is 20 + 10 + 20 = 50
Author
mark_ma
Definition at line 557 of file TPS_TourPart.java.
Member Function Documentation
getArrivalDuration()
double de.dlr.ivf.tapas.scheme.TPS_TourPart.TravelDurations.getArrivalDuration (TPS_ParameterClass parameterClass)
Returns
the arrivalDuration
Definition at line 572 of file TPS_TourPart.java.
References de.dlr.ivf.tapas.mode.TPS_Mode.get(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getDoubleValue(), de.dlr.ivf.tapas.mode.TPS_Mode.getVelocity(), de.dlr.ivf.tapas.util.parameters.ParamValue.MIN_DIST, and de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.WALK.
Referenced by de.dlr.ivf.tapas.loc.TPS_MultipleTAZRepresentant.getLocationRepresentatives().
getDepartureDuration()
double de.dlr.ivf.tapas.scheme.TPS_TourPart.TravelDurations.getDepartureDuration (TPS_ParameterClass parameterClass)
Returns
the departureDuration
Definition at line 580 of file TPS_TourPart.java.
References de.dlr.ivf.tapas.mode.TPS_Mode.get(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getDoubleValue(), de.dlr.ivf.tapas.mode.TPS_Mode.getVelocity(), de.dlr.ivf.tapas.util.parameters.ParamValue.MIN_DIST, and de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.WALK.
Referenced by de.dlr.ivf.tapas.loc.TPS_MultipleTAZRepresentant.getLocationRepresentatives().
setArrivalDuration()
void de.dlr.ivf.tapas.scheme.TPS_TourPart.TravelDurations.setArrivalDuration (double arrivalDuration)
Parameters
arrivalDuration the arrivalDuration to set
Definition at line 588 of file TPS_TourPart.java.
setDepartureDuration()
void de.dlr.ivf.tapas.scheme.TPS_TourPart.TravelDurations.setDepartureDuration (double departureDuration)
Parameters
departureDuration the departureDuration to set
Definition at line 595 of file TPS_TourPart.java.
toString()
String de.dlr.ivf.tapas.scheme.TPS_TourPart.TravelDurations.toString ()
Definition at line 606 of file TPS_TourPart.java.
Member Data Documentation
arrivalDuration
double de.dlr.ivf.tapas.scheme.TPS_TourPart.TravelDurations.arrivalDuration private
complete arrival duration
Definition at line 561 of file TPS_TourPart.java.
Referenced by de.dlr.ivf.tapas.scheme.TPS_TourPart.addStay().
departureDuration
double de.dlr.ivf.tapas.scheme.TPS_TourPart.TravelDurations.departureDuration private
complete departure duration
Definition at line 566 of file TPS_TourPart.java.
Referenced by de.dlr.ivf.tapas.scheme.TPS_TourPart.addStay(), and de.dlr.ivf.tapas.scheme.TPS_TourPart.addTrip().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/scheme/TPS_TourPart.java