TAPAS: de.dlr.ivf.tapas.constants.TPS_Income Class Reference
de.dlr.ivf.tapas.constants.TPS_Income Class Reference
Public Member Functions
TPS_Income (int id, String name, int code, int max)
void addToIncomeMap ()
int getCode ()
Static Public Member Functions
static void clearIncomeMap ()
static int getCode (double income)
Public Attributes
String name
Private Attributes
final int max
final int id
final int code
Static Private Attributes
static final HashMap< Integer, TPS_Income > INCOME_MAP = new HashMap<>()
static final TreeMap< Integer, Integer > MAX_VALUES = new TreeMap<>()
Detailed Description
This class represents the income codes. There is also an ascending distribution of the values stored, to find the fitting code for any income value.
Definition at line 18 of file TPS_Income.java.
Constructor & Destructor Documentation
TPS_Income()
de.dlr.ivf.tapas.constants.TPS_Income.TPS_Income (int id, String name, int code, int max)
Basic constructor of the income constant object
Parameters
id corresponding to the db entry
name description of the income category
code of the income category
max maximum value of a distance category
Definition at line 54 of file TPS_Income.java.
References de.dlr.ivf.tapas.constants.TPS_Income.code, de.dlr.ivf.tapas.constants.TPS_Income.id, de.dlr.ivf.tapas.constants.TPS_Income.max, and de.dlr.ivf.tapas.constants.TPS_Income.name.
Member Function Documentation
addToIncomeMap()
void de.dlr.ivf.tapas.constants.TPS_Income.addToIncomeMap ()
Associates an id with a TPS_Income object. Additionally maps a max_value to an id to conveniently return a TPS_Income object or its code
Definition at line 84 of file TPS_Income.java.
References de.dlr.ivf.tapas.constants.TPS_Income.INCOME_MAP, de.dlr.ivf.tapas.constants.TPS_Income.max, and de.dlr.ivf.tapas.constants.TPS_Income.MAX_VALUES.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readIncomeCodes().
clearIncomeMap()
static void de.dlr.ivf.tapas.constants.TPS_Income.clearIncomeMap () static
Empties the global static income map and the max values map
Definition at line 64 of file TPS_Income.java.
References de.dlr.ivf.tapas.constants.TPS_Income.INCOME_MAP, and de.dlr.ivf.tapas.constants.TPS_Income.MAX_VALUES.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.clearConstants().
getCode() [1/2]
int de.dlr.ivf.tapas.constants.TPS_Income.getCode ()
Returns
income code
Definition at line 92 of file TPS_Income.java.
References de.dlr.ivf.tapas.constants.TPS_Income.code.
getCode() [2/2]
static int de.dlr.ivf.tapas.constants.TPS_Income.getCode (double income) static
This method searches the income value which is the next greater (or equal) than the given value. To this constant the code is returned.
Parameters
income determines the corresponding income category, e.g. income=1320 corresponds to category 'under 1500'
Returns
fitting income code
Definition at line 76 of file TPS_Income.java.
References de.dlr.ivf.tapas.constants.TPS_Income.INCOME_MAP, and de.dlr.ivf.tapas.constants.TPS_Income.MAX_VALUES.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.createOutput(), de.dlr.ivf.tapas.plan.TPS_Plan.TPS_Plan(), and de.dlr.ivf.tapas.plan.TPS_Plan.writeOutputStream().
Member Data Documentation
code
final int de.dlr.ivf.tapas.constants.TPS_Income.code private
code of the income category
Definition at line 43 of file TPS_Income.java.
Referenced by de.dlr.ivf.tapas.constants.TPS_Income.getCode(), and de.dlr.ivf.tapas.constants.TPS_Income.TPS_Income().
id
final int de.dlr.ivf.tapas.constants.TPS_Income.id private
id corresponding to the db entry
Definition at line 39 of file TPS_Income.java.
Referenced by de.dlr.ivf.tapas.constants.TPS_Income.TPS_Income().
INCOME_MAP
final HashMap<Integer, TPS_Income> de.dlr.ivf.tapas.constants.TPS_Income.INCOME_MAP = new HashMap<>() static private
INCOME_MAP maps id to income objects
Definition at line 23 of file TPS_Income.java.
Referenced by de.dlr.ivf.tapas.constants.TPS_Income.addToIncomeMap(), de.dlr.ivf.tapas.constants.TPS_Income.clearIncomeMap(), and de.dlr.ivf.tapas.constants.TPS_Income.getCode().
max
final int de.dlr.ivf.tapas.constants.TPS_Income.max private
maximum value of a distance category
Definition at line 35 of file TPS_Income.java.
Referenced by de.dlr.ivf.tapas.constants.TPS_Income.addToIncomeMap(), and de.dlr.ivf.tapas.constants.TPS_Income.TPS_Income().
MAX_VALUES
final TreeMap<Integer, Integer> de.dlr.ivf.tapas.constants.TPS_Income.MAX_VALUES = new TreeMap<>() static private
MAX_VALUES maps max values of income to ids (=keys in INCOME_MAP)
Definition at line 27 of file TPS_Income.java.
Referenced by de.dlr.ivf.tapas.constants.TPS_Income.addToIncomeMap(), de.dlr.ivf.tapas.constants.TPS_Income.clearIncomeMap(), and de.dlr.ivf.tapas.constants.TPS_Income.getCode().
name
String de.dlr.ivf.tapas.constants.TPS_Income.name
name/description of the income category
Definition at line 31 of file TPS_Income.java.
Referenced by de.dlr.ivf.tapas.constants.TPS_Income.TPS_Income().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/constants/TPS_Income.java