TAPAS: de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution Class Reference
de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution Class Reference
Classes
class DistributionException
Public Member Functions
HouseholdDistribution ()
ArrayList< Integer > getEmptyBlocks ()
long getHouseholdCnt ()
void updateHouseholds (boolean verbose)
Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_BasicConnectionClass ()
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass)
TPS_BasicConnectionClass (String loginFile)
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass, String loginFile)
boolean checkMatrixName (String matrixName)
TPS_ParameterClass getParameters ()
String readParameter (String simKey, String paramKey)
void storeInDB (String matrixName, double[][] matrix, int decimalPlaces)
Static Public Member Functions
static void main (String[] args)
Static Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
static double[][] array1Dto2D (Integer[] matrixVal)
static double[][] array1Dto2D (int[] matrixVal)
static File getRuntimeFile (boolean forceNewFile)
static File getRuntimeFile (String propertyFile, boolean forceNewFile)
static File getRuntimeFile ()
static File getRuntimeFile (String propertyFile)
static int[][] intArray1Dto2D (int[] matrixVal)
static String matrixToSQLArray (double[][] array, int decimalPlaces)
static StringWriter matrixToStringWriterSQL (double[][] array, int decimalPlaces)
Private Member Functions
void addNoBuildingUpdate (int block)
void addRegularUpdate (int building, int household, String key, boolean verbose)
double[] getDistribution (HashMap< Integer, ArrayList< Integer >> buildings) throws DistributionException
int getLanduse (double[] locDist)
HashMap< Integer, ArrayList< Integer > > retrieveBuildingsByLanduse (int block)
ArrayList< Integer > retrieveBuildingsSimple (int block)
ArrayList< Integer > retrieveHouseholds (String key, int block)
Static Private Member Functions
static int getLanduseFromCode (int landuseCode)
Private Attributes
final int BATCH_SIZE = 10000
final ArrayList< Integer > blocks = new ArrayList<>()
final ArrayList< String > keys = new ArrayList<>()
long cntHouseholdsUpdated = 0
long cntHouseholdsNoBuilding = 0
final ArrayList< Integer > emptyBlocks = new ArrayList<>()
PreparedStatement updateHouseholds
PreparedStatement updateHouseholdsNoBuilding
PreparedStatement fetchHouseholds
PreparedStatement fetchBuildings
PreparedStatement fetchBuildingsSimple
Additional Inherited Members
Protected Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
void finalize ()
Protected Attributes inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_DB_Connector dbCon = null
TPS_ParameterClass parameterClass
Detailed Description
Updates all household positions from block centroid to actual buildings. The households are distributed mainly on residential buildings.
Author
boec_pa
Definition at line 30 of file HouseholdDistribution.java.
Constructor & Destructor Documentation
HouseholdDistribution()
de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.HouseholdDistribution ()
Fetches all blocks (15k) and fetches household keys (4) Prepared all sql statements
Definition at line 57 of file HouseholdDistribution.java.
References de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.blocks, de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.fetchBuildings, de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.fetchBuildingsSimple, de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.fetchHouseholds, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection(), de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.keys, de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.updateHouseholds, and de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.updateHouseholdsNoBuilding.
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.main().
Member Function Documentation
addNoBuildingUpdate()
void de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.addNoBuildingUpdate (int block) private
Definition at line 160 of file HouseholdDistribution.java.
References de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.BATCH_SIZE, de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.cntHouseholdsNoBuilding, and de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.updateHouseholdsNoBuilding.
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.updateHouseholds().
addRegularUpdate()
void de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.addRegularUpdate (int building, int household, String key, boolean verbose) private
Definition at line 192 of file HouseholdDistribution.java.
References de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.BATCH_SIZE, de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.cntHouseholdsUpdated, and de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.updateHouseholds.
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.updateHouseholds().
getDistribution()
double [] de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.getDistribution (HashMap< Integer, ArrayList< Integer >> buildings) throws DistributionException private
Example: There are no MIXED buildings Default is [0.6,0.39,0.01,0.0] Result is (roughly) [0.98,0.0, 0.2,0.0] After that, we weight the distribution with the number of buildings in each category
Parameters
buildings
Returns
Exceptions
DistributionException
Definition at line 244 of file HouseholdDistribution.java.
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.updateHouseholds().
getEmptyBlocks()
ArrayList<Integer> de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.getEmptyBlocks ()
Definition at line 280 of file HouseholdDistribution.java.
References de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.emptyBlocks.
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.main().
getHouseholdCnt()
long de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.getHouseholdCnt ()
Definition at line 284 of file HouseholdDistribution.java.
References de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.cntHouseholdsUpdated.
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.main().
getLanduse()
int de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.getLanduse (double[] locDist) private
Definition at line 288 of file HouseholdDistribution.java.
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.updateHouseholds().
getLanduseFromCode()
static int de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.getLanduseFromCode (int landuseCode) static private
Definition at line 124 of file HouseholdDistribution.java.
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.retrieveBuildingsByLanduse().
main()
static void de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.main (String[] args) static
Definition at line 137 of file HouseholdDistribution.java.
References de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.getEmptyBlocks(), de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.getHouseholdCnt(), de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.HouseholdDistribution(), and de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.updateHouseholds.
retrieveBuildingsByLanduse()
HashMap<Integer, ArrayList<Integer> > de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.retrieveBuildingsByLanduse (int block) private
Retrieves 4 lists of buildings in the given block organised in a Map with the landuse as key.
Parameters
block
Returns
Definition at line 303 of file HouseholdDistribution.java.
References de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.fetchBuildings, de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.getLanduseFromCode(), and type.
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.updateHouseholds().
retrieveBuildingsSimple()
ArrayList<Integer> de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.retrieveBuildingsSimple (int block) private
Definition at line 333 of file HouseholdDistribution.java.
References de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.fetchBuildingsSimple.
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.updateHouseholds().
retrieveHouseholds()
ArrayList<Integer> de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.retrieveHouseholds (String key, int block) private
Retrieves a list of all households in the given block with the given key.
Parameters
key
block
Returns
null on SQL exceptions.
Definition at line 360 of file HouseholdDistribution.java.
References de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.fetchHouseholds.
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.updateHouseholds().
updateHouseholds()
void de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.updateHouseholds (boolean verbose)
Updates all household positions from block centroid to actual buildings. The households are distributed mainly on residential buildings. 3 stage algorithm:
Try to match dlm blocks to blocks and find buildings in there
If that fails, try find buildings just in blocks
If that fails as well, update households to block centroid instead
Parameters
verbose If true, a status report for every block is given to track progress.
Definition at line 394 of file HouseholdDistribution.java.
References de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.addNoBuildingUpdate(), de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.addRegularUpdate(), de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.blocks, de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.emptyBlocks, de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.getDistribution(), de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.getLanduse(), de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.keys, de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.retrieveBuildingsByLanduse(), de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.retrieveBuildingsSimple(), de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.retrieveHouseholds(), and type.
Member Data Documentation
BATCH_SIZE
final int de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.BATCH_SIZE = 10000 private
Definition at line 38 of file HouseholdDistribution.java.
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.addNoBuildingUpdate(), and de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.addRegularUpdate().
blocks
final ArrayList<Integer> de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.blocks = new ArrayList<>() private
Definition at line 39 of file HouseholdDistribution.java.
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.HouseholdDistribution(), and de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.updateHouseholds().
cntHouseholdsNoBuilding
long de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.cntHouseholdsNoBuilding = 0 private
Definition at line 43 of file HouseholdDistribution.java.
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.addNoBuildingUpdate().
cntHouseholdsUpdated
long de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.cntHouseholdsUpdated = 0 private
Definition at line 42 of file HouseholdDistribution.java.
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.addRegularUpdate(), and de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.getHouseholdCnt().
emptyBlocks
final ArrayList<Integer> de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.emptyBlocks = new ArrayList<>() private
Definition at line 45 of file HouseholdDistribution.java.
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.getEmptyBlocks(), and de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.updateHouseholds().
fetchBuildings
PreparedStatement de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.fetchBuildings private
Definition at line 50 of file HouseholdDistribution.java.
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.HouseholdDistribution(), and de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.retrieveBuildingsByLanduse().
fetchBuildingsSimple
PreparedStatement de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.fetchBuildingsSimple private
Definition at line 51 of file HouseholdDistribution.java.
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.HouseholdDistribution(), and de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.retrieveBuildingsSimple().
fetchHouseholds
PreparedStatement de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.fetchHouseholds private
Definition at line 49 of file HouseholdDistribution.java.
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.HouseholdDistribution(), and de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.retrieveHouseholds().
keys
final ArrayList<String> de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.keys = new ArrayList<>() private
Definition at line 40 of file HouseholdDistribution.java.
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.HouseholdDistribution(), and de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.updateHouseholds().
updateHouseholds
PreparedStatement de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.updateHouseholds private
Definition at line 47 of file HouseholdDistribution.java.
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.addRegularUpdate(), de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.HouseholdDistribution(), and de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.main().
updateHouseholdsNoBuilding
PreparedStatement de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.updateHouseholdsNoBuilding private
Definition at line 48 of file HouseholdDistribution.java.
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.addNoBuildingUpdate(), and de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.HouseholdDistribution().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/OpportunityDistribution/HouseholdDistribution.java