TAPAS: de.dlr.ivf.tapas.persistence.TPS_RegionResultSet Class Reference
de.dlr.ivf.tapas.persistence.TPS_RegionResultSet Class Reference
Classes
class InternalResultIterable
class Result
Public Member Functions
TPS_RegionResultSet ()
void add (TPS_TrafficAnalysisZone taz, TPS_Location loc, Double sumWeight)
void clear ()
Iterable< Result > getResultIterable ()
boolean isEmpty ()
int size ()
Static Public Attributes
static Map< ParamValue, Integer > VELOCITY_2_INDEX_MAP
Private Attributes
final List< TPS_Location > locList
final List< Double > sumWeightList
final List< TPS_TrafficAnalysisZone > tazList
Detailed Description
Class which represents the ResultSet of possible TPS_Location
Author
hein_mh
Definition at line 24 of file TPS_RegionResultSet.java.
Constructor & Destructor Documentation
TPS_RegionResultSet()
de.dlr.ivf.tapas.persistence.TPS_RegionResultSet.TPS_RegionResultSet ()
Constructor
Definition at line 48 of file TPS_RegionResultSet.java.
Member Function Documentation
add()
void de.dlr.ivf.tapas.persistence.TPS_RegionResultSet.add (TPS_TrafficAnalysisZone taz, TPS_Location loc, Double sumWeight)
This method adds one element to the lists.
Parameters
taz The taz of this location
loc The location
sumWeight The weight of this location
Definition at line 61 of file TPS_RegionResultSet.java.
Referenced by de.dlr.ivf.tapas.loc.TPS_MultipleTAZRepresentant.getLocationRepresentatives(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.getTrafficAnalysisZonesAround().
clear()
void de.dlr.ivf.tapas.persistence.TPS_RegionResultSet.clear ()
Method to clear all results.
Definition at line 70 of file TPS_RegionResultSet.java.
Referenced by de.dlr.ivf.tapas.loc.TPS_MultipleTAZRepresentant.getLocationRepresentatives(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.getTrafficAnalysisZonesAround().
getResultIterable()
Iterable<Result> de.dlr.ivf.tapas.persistence.TPS_RegionResultSet.getResultIterable ()
This Method gets a iterator which provides a Result with the correct aligned taz, location and weights
Returns
The iterator
Definition at line 81 of file TPS_RegionResultSet.java.
Referenced by de.dlr.ivf.tapas.loc.TPS_SelectLocationWeightBased.selectLocationFromChoiceSet(), and de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.selectLocationFromChoiceSet().
isEmpty()
boolean de.dlr.ivf.tapas.persistence.TPS_RegionResultSet.isEmpty ()
Method to check if the result set is empty
Returns
true if no valid data is attached
Definition at line 90 of file TPS_RegionResultSet.java.
size()
int de.dlr.ivf.tapas.persistence.TPS_RegionResultSet.size ()
Returns the amount of added data to this TPS_RegionResultSet.
Returns
The number of locations attached.
Definition at line 99 of file TPS_RegionResultSet.java.
Referenced by de.dlr.ivf.tapas.loc.TPS_MultipleTAZRepresentant.getLocationRepresentatives(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.getTrafficAnalysisZonesAround().
Member Data Documentation
locList
final List<TPS_Location> de.dlr.ivf.tapas.persistence.TPS_RegionResultSet.locList private
Definition at line 41 of file TPS_RegionResultSet.java.
sumWeightList
final List<Double> de.dlr.ivf.tapas.persistence.TPS_RegionResultSet.sumWeightList private
Definition at line 42 of file TPS_RegionResultSet.java.
tazList
final List<TPS_TrafficAnalysisZone> de.dlr.ivf.tapas.persistence.TPS_RegionResultSet.tazList private
Definition at line 43 of file TPS_RegionResultSet.java.
VELOCITY_2_INDEX_MAP
Map<ParamValue, Integer> de.dlr.ivf.tapas.persistence.TPS_RegionResultSet.VELOCITY_2_INDEX_MAP static
Definition at line 26 of file TPS_RegionResultSet.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/persistence/TPS_RegionResultSet.java