TAPAS: de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer2017 Class Reference
de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer2017 Class Reference
Classes
class Diary
class DiaryElement
Public Member Functions
void calcDiaryStatistics ()
void cleanUpDB (String table)
void clearEverything ()
void printDiariesSQLInserts (String table_episode, String table_schemes, boolean print)
void printDistributionVectorSQLInserts (String tablename, String name, boolean print)
void printDistributionVectors ()
void printSchemeClassSQLInserts (String table, boolean print)
void printStatistics ()
void readMIDDiary (String table, String filter)
Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_BasicConnectionClass ()
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass)
TPS_BasicConnectionClass (String loginFile)
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass, String loginFile)
boolean checkMatrixName (String matrixName)
TPS_ParameterClass getParameters ()
String readParameter (String simKey, String paramKey)
void storeInDB (String matrixName, double[][] matrix, int decimalPlaces)
Static Public Member Functions
static void main (String[] args)
Static Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
static double[][] array1Dto2D (Integer[] matrixVal)
static double[][] array1Dto2D (int[] matrixVal)
static File getRuntimeFile (boolean forceNewFile)
static File getRuntimeFile (String propertyFile, boolean forceNewFile)
static File getRuntimeFile ()
static File getRuntimeFile (String propertyFile)
static int[][] intArray1Dto2D (int[] matrixVal)
static String matrixToSQLArray (double[][] array, int decimalPlaces)
static StringWriter matrixToStringWriterSQL (double[][] array, int decimalPlaces)
Private Member Functions
void recodeAcompanyTrip (DiaryElement trip, DiaryElement theOtherOne)
Additional Inherited Members
Protected Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
void finalize ()
Protected Attributes inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_DB_Connector dbCon = null
TPS_ParameterClass parameterClass
Detailed Description
Definition at line 21 of file TPS_MiD_Diary_Analyzer2017.java.
Member Function Documentation
calcDiaryStatistics()
void de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer2017.calcDiaryStatistics ()
Definition at line 111 of file TPS_MiD_Diary_Analyzer2017.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer2017.main().
cleanUpDB()
void de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer2017.cleanUpDB (String table)
Definition at line 160 of file TPS_MiD_Diary_Analyzer2017.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute().
Referenced by de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer2017.main().
clearEverything()
void de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer2017.clearEverything ()
Definition at line 165 of file TPS_MiD_Diary_Analyzer2017.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer2017.main().
main()
static void de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer2017.main (String[] args) static
Definition at line 53 of file TPS_MiD_Diary_Analyzer2017.java.
References de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer2017.calcDiaryStatistics(), de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer2017.cleanUpDB(), de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer2017.clearEverything(), de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer2017.printDiariesSQLInserts(), de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer2017.printDistributionVectorSQLInserts(), de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer2017.printSchemeClassSQLInserts(), and de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer2017.readMIDDiary().
printDiariesSQLInserts()
void de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer2017.printDiariesSQLInserts (String table_episode, String table_schemes, boolean print)
Definition at line 185 of file TPS_MiD_Diary_Analyzer2017.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection().
Referenced by de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer2017.main().
printDistributionVectors()
void de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer2017.printDistributionVectors ()
Definition at line 430 of file TPS_MiD_Diary_Analyzer2017.java.
printDistributionVectorSQLInserts()
void de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer2017.printDistributionVectorSQLInserts (String tablename, String name, boolean print)
Definition at line 389 of file TPS_MiD_Diary_Analyzer2017.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute(), and name.
Referenced by de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer2017.main().
printSchemeClassSQLInserts()
void de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer2017.printSchemeClassSQLInserts (String table, boolean print)
Definition at line 456 of file TPS_MiD_Diary_Analyzer2017.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute().
Referenced by de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer2017.main().
printStatistics()
void de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer2017.printStatistics ()
Definition at line 582 of file TPS_MiD_Diary_Analyzer2017.java.
readMIDDiary()
void de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer2017.readMIDDiary (String table, String filter)
Definition at line 611 of file TPS_MiD_Diary_Analyzer2017.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), and de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer2017.recodeAcompanyTrip().
Referenced by de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer2017.main().
recodeAcompanyTrip()
void de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer2017.recodeAcompanyTrip (DiaryElement trip, DiaryElement theOtherOne) private
Definition at line 775 of file TPS_MiD_Diary_Analyzer2017.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer2017.readMIDDiary().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/TPS_MiD_Diary_Analyzer2017.java