TAPAS: de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralExcelExport Class Reference
de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralExcelExport Class Reference
Public Member Functions
GeneralExcelExport (GeneralAnalyzer analyzer)
boolean writeAnalysis (File file)
void writeAnalysis (String baseName) throws IOException, WriteException
Private Member Functions
void createFormats ()
boolean writeFile (WritableWorkbook workbook, DefaultMutableTreeNode fileNode, Enum[] fixedSheetValues) throws RowsExceededException, WriteException
int writeSplit (WritableSheet sheet, Analyzer a, Enum[] fixedSplitValues, Enum[] splitValues, int x, int y) throws WriteException
boolean writeTab (WritableSheet sheet, DefaultMutableTreeNode tabNode, Enum[] fixedSheetValues) throws RowsExceededException, WriteException
void writeTabHeader (WritableSheet sheet) throws WriteException
Private Attributes
WritableCellFormat percentageFormat
WritableCellFormat floatFormat
WritableCellFormat intFormat
final GeneralAnalyzer analyzer
Static Private Attributes
static int HEADER_HEIGHT = 0
Detailed Description
This class uses a GeneralAnalyzer and exports it to (multiple) excel files using its tree structure.
Author
boec_pa
Definition at line 36 of file GeneralExcelExport.java.
Constructor & Destructor Documentation
GeneralExcelExport()
de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralExcelExport.GeneralExcelExport (GeneralAnalyzer analyzer)
Definition at line 44 of file GeneralExcelExport.java.
References de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzer.getNumberTrips().
Member Function Documentation
createFormats()
void de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralExcelExport.createFormats () private
Definition at line 49 of file GeneralExcelExport.java.
writeAnalysis() [1/2]
boolean de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralExcelExport.writeAnalysis (File file)
Used by the IntegratedTUM
Parameters
file
Definition at line 61 of file GeneralExcelExport.java.
References de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzer.getRoot().
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzer.finish().
writeAnalysis() [2/2]
void de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralExcelExport.writeAnalysis (String baseName) throws IOException, WriteException
Definition at line 85 of file GeneralExcelExport.java.
References de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.AnalyzerCollection.getCategories(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.AnalyzerCollection.getName(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzer.getRoot(), and de.dlr.ivf.tapas.analyzer.tum.constants.CategoryCombination.listAllCombinations().
writeFile()
boolean de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralExcelExport.writeFile (WritableWorkbook workbook, DefaultMutableTreeNode fileNode, Enum[] fixedSheetValues) throws RowsExceededException, WriteException private
Parameters
workbook
fileNode
fixedSheetValues are the categories that are fixed for the whole file (usually, this would be a zero-length-array.
Returns
true if empty.
Exceptions
RowsExceededException
WriteException
Definition at line 140 of file GeneralExcelExport.java.
References de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.AnalyzerCollection.getCategories(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.AnalyzerCollection.getName(), de.dlr.ivf.tapas.analyzer.tum.constants.CategoryCombination.listAllCombinations(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.AnalyzerCollection.toString().
writeSplit()
int de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralExcelExport.writeSplit (WritableSheet sheet, Analyzer a, Enum[] fixedSplitValues, Enum[] splitValues, int x, int y) throws WriteException private
Returns
new y
Definition at line 184 of file GeneralExcelExport.java.
writeTab()
boolean de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralExcelExport.writeTab (WritableSheet sheet, DefaultMutableTreeNode tabNode, Enum[] fixedSheetValues) throws RowsExceededException, WriteException private
Parameters
sheet
tabNode
fixedSheetValues are the categories fixed in the sheet to write (in the default version, that is RegionCode).
Exceptions
WriteException
RowsExceededException
Definition at line 210 of file GeneralExcelExport.java.
References de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzer.getAnalyzers(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.Analyzer.getCategories(), de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.getEnumeration(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.Analyzer.getNumberOfAnalyzers(), de.dlr.ivf.tapas.analyzer.tum.constants.CategoryCombination.listAllCombinations(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.Analyzer.toString().
writeTabHeader()
void de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralExcelExport.writeTabHeader (WritableSheet sheet) throws WriteException private
Definition at line 281 of file GeneralExcelExport.java.
References de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzer.getNumberTrips(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzer.getRegion(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzer.getSource().
Member Data Documentation
analyzer
final GeneralAnalyzer de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralExcelExport.analyzer private
Definition at line 42 of file GeneralExcelExport.java.
floatFormat
WritableCellFormat de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralExcelExport.floatFormat private
Definition at line 40 of file GeneralExcelExport.java.
HEADER_HEIGHT
int de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralExcelExport.HEADER_HEIGHT = 0 static private
Definition at line 38 of file GeneralExcelExport.java.
intFormat
WritableCellFormat de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralExcelExport.intFormat private
Definition at line 41 of file GeneralExcelExport.java.
percentageFormat
WritableCellFormat de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralExcelExport.percentageFormat private
Definition at line 39 of file GeneralExcelExport.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/tum/regionanalyzer/general/GeneralExcelExport.java