TAPAS: de.dlr.ivf.tapas.iteration.TPS_IterationManagement Class Reference
de.dlr.ivf.tapas.iteration.TPS_IterationManagement Class Reference abstract
Classes
class PlanDeviation
Public Member Functions
HashMap< Long, PlanDeviation > calculatePlanDerivation (int iteration)
MatrixMap[] getNewTravelTimeMatrix ()
int hashToHHID (long hash)
int hashToPersonID (long hash)
long hhAndPersonIDToHash (int hh_id, int p_id)
void resetPlansForRecalculation (ArrayList< Long > plans)
abstract ArrayList< Long > selectPlansForRecalculation (HashMap< Long, PlanDeviation > derivationMap, int actIter, int maxIter)
void setDBConnector (TPS_DB_Connector dbManager)
Private Attributes
final TPS_ParameterClass parameterClass
final MatrixMap[] newTT = new MatrixMap[TPS_Mode.MODE_TYPE_ARRAY.length]
Detailed Description
Definition at line 28 of file TPS_IterationManagement.java.
Member Function Documentation
calculatePlanDerivation()
HashMap<Long, PlanDeviation> de.dlr.ivf.tapas.iteration.TPS_IterationManagement.calculatePlanDerivation (int iteration)
Function to calculate the derivation of the day plans according to the new matrices
Parameters
iteration The iteration index to calculate
Returns
The HashMap, which stores the travel time derivation for every persons plan.
Definition at line 54 of file TPS_IterationManagement.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_REGION, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.iteration.TPS_IterationManagement.hhAndPersonIDToHash(), de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.iteration.TPS_IterationManagement.PlanDeviation.newTime, de.dlr.ivf.tapas.iteration.TPS_IterationManagement.PlanDeviation.oldTime, and de.dlr.ivf.tapas.util.parameters.ParamString.RUN_IDENTIFIER.
getNewTravelTimeMatrix()
MatrixMap [] de.dlr.ivf.tapas.iteration.TPS_IterationManagement.getNewTravelTimeMatrix ()
Returns
the newTT
Definition at line 133 of file TPS_IterationManagement.java.
References de.dlr.ivf.tapas.iteration.TPS_IterationManagement.newTT.
hashToHHID()
int de.dlr.ivf.tapas.iteration.TPS_IterationManagement.hashToHHID (long hash)
Method to extract the household id from a hash key.
Parameters
hash the key value form a entry returned by calculatePlanDerivation
Returns
the household id
Definition at line 143 of file TPS_IterationManagement.java.
Referenced by de.dlr.ivf.tapas.iteration.TPS_IterationManagement.resetPlansForRecalculation().
hashToPersonID()
int de.dlr.ivf.tapas.iteration.TPS_IterationManagement.hashToPersonID (long hash)
Method to extract the person id from a hash key.
Parameters
hash the key value form a entry returned by calculatePlanDerivation
Returns
the person id
Definition at line 154 of file TPS_IterationManagement.java.
hhAndPersonIDToHash()
long de.dlr.ivf.tapas.iteration.TPS_IterationManagement.hhAndPersonIDToHash (int hh_id, int p_id)
Method to map the household id and person id to a unique long-value
Parameters
hh_id the id of the household
p_id the id of the person in this household
Returns
a long value for the hashmap used in calculatePlanDerivation
Definition at line 165 of file TPS_IterationManagement.java.
Referenced by de.dlr.ivf.tapas.iteration.TPS_IterationManagement.calculatePlanDerivation().
resetPlansForRecalculation()
void de.dlr.ivf.tapas.iteration.TPS_IterationManagement.resetPlansForRecalculation (ArrayList< Long > plans)
Method to prepare the given plans for recalculation. This automatically triggers a recalculation.
Parameters
plans A map of plans to recalculate.
Definition at line 178 of file TPS_IterationManagement.java.
References de.dlr.ivf.tapas.util.TPS_TripDeleter.clearHHID(), de.dlr.ivf.tapas.util.TPS_TripDeleter.deleteHouseholdsFromTriptable(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.iteration.TPS_IterationManagement.hashToHHID(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.INFO, de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.util.TPS_TripDeleter.putHHID(), de.dlr.ivf.tapas.util.parameters.ParamString.RUN_IDENTIFIER, and de.dlr.ivf.tapas.util.TPS_TripDeleter.setKey().
selectPlansForRecalculation()
abstract ArrayList<Long> de.dlr.ivf.tapas.iteration.TPS_IterationManagement.selectPlansForRecalculation (HashMap< Long, PlanDeviation > derivationMap, int actIter, int maxIter) abstract
Method to select persons and plans, which should be recalculated.
Parameters
derivationMap The derivation map of the plans
actIter the actual iteration
maxIter the maximum value actIter can reach
Returns
A map of plans for recalculation
Reimplemented in de.dlr.ivf.tapas.iteration.TPS_BasicIterationManager, and de.dlr.ivf.tapas.iteration.TPS_AcceptanceIterationManager.
setDBConnector()
void de.dlr.ivf.tapas.iteration.TPS_IterationManagement.setDBConnector (TPS_DB_Connector dbManager)
Parameters
dbManager the dbManager to set
Definition at line 229 of file TPS_IterationManagement.java.
Member Data Documentation
newTT
final MatrixMap [] de.dlr.ivf.tapas.iteration.TPS_IterationManagement.newTT = new MatrixMap[TPS_Mode.MODE_TYPE_ARRAY.length] private
An array of MatrixMap for the new travel times
Definition at line 37 of file TPS_IterationManagement.java.
Referenced by de.dlr.ivf.tapas.iteration.TPS_IterationManagement.getNewTravelTimeMatrix().
parameterClass
final TPS_ParameterClass de.dlr.ivf.tapas.iteration.TPS_IterationManagement.parameterClass private
parameter class reference
Definition at line 33 of file TPS_IterationManagement.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/iteration/TPS_IterationManagement.java