TAPAS: de.dlr.ivf.tapas.util.parameters.ParamStringClass Class Reference
de.dlr.ivf.tapas.util.parameters.ParamStringClass Class Reference
Public Member Functions
void add (ParamString param, String appendix)
void add (ParamString param, String prefix, String suffix)
void add (ParamString param, ParamString appendix)
void add (ParamString param, ParamString prefix, ParamString suffix)
void add (ParamString param, ParamString prefix, String suffix)
void clear (ParamString param)
String getPreset (ParamString param)
String getString (ParamString param) throws RuntimeException
ParamType getType (ParamString param)
boolean isDefined (ParamString param)
void setString (ParamString param, String string)
Private Attributes
final EnumMap< ParamString, MutablePair< ParamType, String > > paramStrings
Detailed Description
Definition at line 15 of file ParamStringClass.java.
Member Function Documentation
add() [1/5]
void de.dlr.ivf.tapas.util.parameters.ParamStringClass.add (ParamString param, ParamString appendix)
Appends the value of a ParamString object to this one
Parameters
param string parameter enum
appendix The ParamString to add
Definition at line 217 of file ParamStringClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamStringClass.add(), de.dlr.ivf.tapas.util.parameters.ParamStringClass.getString(), and de.dlr.ivf.tapas.util.parameters.ParamStringClass.isDefined().
add() [2/5]
void de.dlr.ivf.tapas.util.parameters.ParamStringClass.add (ParamString param, ParamString prefix, ParamString suffix)
Adds a prefix and suffix to the existing String
Parameters
param string parameter enum as a ParamString
prefix The prefix to add
suffix The suffix to add
Definition at line 230 of file ParamStringClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamStringClass.add(), de.dlr.ivf.tapas.util.parameters.ParamStringClass.getString(), and de.dlr.ivf.tapas.util.parameters.ParamStringClass.isDefined().
add() [3/5]
void de.dlr.ivf.tapas.util.parameters.ParamStringClass.add (ParamString param, ParamString prefix, String suffix)
Adds a prefix and suffix to the existing String
Parameters
param string parameter enum as a ParamString
prefix The prefix to add as a ParamString
suffix The suffix to add as a string
Definition at line 243 of file ParamStringClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamStringClass.add(), de.dlr.ivf.tapas.util.parameters.ParamStringClass.getString(), and de.dlr.ivf.tapas.util.parameters.ParamStringClass.isDefined().
add() [4/5]
void de.dlr.ivf.tapas.util.parameters.ParamStringClass.add (ParamString param, String appendix)
Append a given string to this String
Parameters
param string parameter enum
appendix the String to append to this one
Definition at line 190 of file ParamStringClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamStringClass.getString(), de.dlr.ivf.tapas.util.parameters.ParamStringClass.isDefined(), and de.dlr.ivf.tapas.util.parameters.ParamStringClass.setString().
Referenced by de.dlr.ivf.tapas.util.parameters.ParamStringClass.add(), and de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.generateTemporaryParameters().
add() [5/5]
void de.dlr.ivf.tapas.util.parameters.ParamStringClass.add (ParamString param, String prefix, String suffix)
Adds a prefix and suffix to the existing String
Parameters
param string parameter enum
prefix The prefix to add
suffix The suffix to add
Definition at line 204 of file ParamStringClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamStringClass.getString(), de.dlr.ivf.tapas.util.parameters.ParamStringClass.isDefined(), and de.dlr.ivf.tapas.util.parameters.ParamStringClass.setString().
clear()
void de.dlr.ivf.tapas.util.parameters.ParamStringClass.clear (ParamString param)
clears the attached String value to the default value
Definition at line 252 of file ParamStringClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamStringClass.getString(), and de.dlr.ivf.tapas.util.parameters.ParamStringClass.setString().
getPreset()
String de.dlr.ivf.tapas.util.parameters.ParamStringClass.getPreset (ParamString param)
TODO ugly hack maybe improve
Parameters
param string parameter enum
Returns
the default string value of the enum
Definition at line 262 of file ParamStringClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamStringClass.getString().
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.getDefaultParams().
getString()
String de.dlr.ivf.tapas.util.parameters.ParamStringClass.getString (ParamString param) throws RuntimeException
Parameters
param string parameter enum
Returns
constant string
Exceptions
RuntimeException if the constant was not defined
Definition at line 275 of file ParamStringClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamStringClass.isDefined().
Referenced by de.dlr.ivf.tapas.util.parameters.ParamStringClass.add(), de.dlr.ivf.tapas.util.parameters.ParamStringClass.clear(), de.dlr.ivf.tapas.util.parameters.ParamStringClass.getPreset(), and de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString().
getType()
ParamType de.dlr.ivf.tapas.util.parameters.ParamStringClass.getType (ParamString param)
Parameters
param string parameter enum
Returns
parameter type
Definition at line 286 of file ParamStringClass.java.
Referenced by de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getType().
isDefined()
boolean de.dlr.ivf.tapas.util.parameters.ParamStringClass.isDefined (ParamString param)
Parameters
param string parameter enum
Returns
true if the string is defined (not null), false otherwise
Definition at line 294 of file ParamStringClass.java.
Referenced by de.dlr.ivf.tapas.util.parameters.ParamStringClass.add(), de.dlr.ivf.tapas.util.parameters.ParamStringClass.getString(), and de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isDefined().
setString()
void de.dlr.ivf.tapas.util.parameters.ParamStringClass.setString (ParamString param, String string)
Sets the string value
Parameters
param string parameter enum
string string value to be set to the parameter
Definition at line 304 of file ParamStringClass.java.
Referenced by de.dlr.ivf.tapas.util.parameters.ParamStringClass.add(), de.dlr.ivf.tapas.util.parameters.ParamStringClass.clear(), de.dlr.ivf.tapas.tools.TPS_MainDiagonalLengthEstimator.main(), and de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.setString().
Member Data Documentation
paramStrings
final EnumMap<ParamString, MutablePair<ParamType, String> > de.dlr.ivf.tapas.util.parameters.ParamStringClass.paramStrings private
Definition at line 16 of file ParamStringClass.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/util/parameters/ParamStringClass.java