TAPAS: de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler Class Reference
de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler Class Reference
Public Member Functions
JFrame createAndShowGUI ()
Static Public Member Functions
static void main (String[] args) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException
static GridBagConstraints newGridBag (int gridX, int padX, int gridY, int padY)
Protected Member Functions
void renameMatrices ()
Private Member Functions
void addMatrix ()
void addMatrixMap ()
void cloneSelectedMatrices ()
void cloneSelectedMatrixMaps ()
void closeConnection ()
JFrame createGui ()
void deleteLists ()
void deleteMatrixList ()
void deleteMatrixMapList ()
void deleteSelectedMatrices ()
void deleteSelectedMatrixMaps ()
void editMatrix ()
void editMatrixMap ()
void fillLists ()
void fillLoginData (boolean forceNewFile)
JButton getConfigFileButton ()
JButton getConnectButton ()
JTextField getDbNameText ()
JButton getDisconnectButton ()
JPanel getJConnectionPane ()
JPanel getJMatrixMapPane ()
JPanel getJMatrixPane ()
JPanel getMainPanel ()
JPanel getMapListPane ()
JPanel getMatrixActionPanel ()
JButton getMatrixAddButton ()
JPanel getMatrixButtonPanel ()
JButton getMatrixCloneButton ()
JComboBox< String > getMatrixDBNameComboBox ()
JPanel getMatrixDBNamePanel ()
JButton getMatrixDeleteButton ()
JButton getMatrixEditButton ()
JButton getMatrixImportButton ()
JScrollPane getMatrixList ()
JPanel getMatrixListPanel ()
JButton getMatrixLoadButton ()
JPanel getMatrixMapActionPane ()
JButton getMatrixMapAddButton ()
JPanel getMatrixMapButtonPane ()
JButton getMatrixMapCloneButton ()
JComboBox< String > getMatrixMapDBNameComboBox ()
JPanel getMatrixMapDBNamePane ()
JButton getMatrixMapDeleteButton ()
JButton getMatrixMapEditButton ()
JScrollPane getMatrixMapList ()
JButton getMatrixMapLoadButton ()
JSplitPane getMatrixMapSplitPane ()
JButton getMatrixRenameButton ()
JSplitPane getMatrixSplitPane ()
JPasswordField getPasswordField ()
JTextField getPortText ()
JButton getRenameMatrixMapButton ()
JTextField getServerText ()
JTextField getUserText ()
boolean isMatrixExisting (String s) throws SQLException
boolean isMatrixMapExisting (String s) throws SQLException
void loadMatrixList ()
void loadMatrixMapList ()
void manipulateTop3 ()
JButton matrixEditTop3Button ()
void openConnection ()
void renameMatrixMaps ()
void set2ndLevelMatrixButtonEnabled (boolean val)
void set2ndLevelMatrixMapEnabled (boolean val)
void setConnectionEnabled (boolean connected)
Private Attributes
ResourceBundle rb
JFrame controlInstance
JPanel mainPanel = null
JPanel jConnectionPane = null
JPanel jMatrixMapPane = null
JPanel jMatrixPane = null
JTextField serverText = null
JTextField portText = null
JTextField userText = null
JPasswordField passwordField = null
JButton connectButton = null
JButton disconnectButton = null
JButton configFileButton = null
JSplitPane MatrixMapSplitPane = null
JPanel MapListPane = null
JPanel matrixMapButtonPane = null
JPanel matrixMapDBNamePane = null
JComboBox< String > matrixMapDBNameComboBox = null
JPanel matrixMapActionPane = null
JButton matrixMapLoadButton = null
JButton matrixMapEditButton = null
JButton matrixMapAddButton = null
JButton matrixMapDeleteButton = null
JScrollPane matrixMapListScrollPane = null
JList< String > matrixMapList = null
JSplitPane MatrixSplitPane = null
JPanel matrixListPanel = null
JPanel matrixDBNamePanel = null
JScrollPane matrixListScrollPane = null
JList< String > matrixList = null
JPanel matrixButtonPanel = null
JPanel matrixActionPanel = null
JButton matrixLoadButton = null
JComboBox< String > matrixDBNameComboBox = null
JButton matrixEditButton = null
JButton matrixEditTop3Button = null
JButton matrixAddButton = null
JButton matrixDeleteButton = null
JButton matrixImportButton = null
Connection connection = null
Statement statement = null
JTextField dbNameText = null
JButton matrixCloneButton = null
JButton matrixMapCloneButton = null
JButton renameMatrixMapButton = null
JButton matrixRenameButton = null
Static Private Attributes
static final int arrayChunk = 10000
Detailed Description
main class for handling matrix maps and matrices in the db
Definition at line 36 of file MatrixMapHandler.java.
Member Function Documentation
addMatrix()
void de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.addMatrix () private
method to add a new entry in the matrix table
Definition at line 111 of file MatrixMapHandler.java.
References de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.arrayChunk, de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.controlInstance, de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.editMatrix(), de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.loadMatrixList(), de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.rb, and de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.statement.
addMatrixMap()
void de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.addMatrixMap () private
method to add a new entry in the matrixMap table
Definition at line 175 of file MatrixMapHandler.java.
References de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.controlInstance, de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.editMatrixMap(), de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.loadMatrixMapList(), de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.rb, and de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.statement.
cloneSelectedMatrices()
void de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.cloneSelectedMatrices () private
method to clone db entries in the matrix table
Definition at line 217 of file MatrixMapHandler.java.
References de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.arrayChunk, de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.controlInstance, de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.isMatrixExisting(), de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.loadMatrixList(), de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.rb, and de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.statement.
cloneSelectedMatrixMaps()
void de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.cloneSelectedMatrixMaps () private
method to clone db entries in the matrixMap table
Definition at line 296 of file MatrixMapHandler.java.
References de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.controlInstance, de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.isMatrixMapExisting(), de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.loadMatrixMapList(), de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.rb, and de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.statement.
closeConnection()
void de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.closeConnection () private
method to close the db connection and statement
Definition at line 376 of file MatrixMapHandler.java.
References de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.connection, and de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.statement.
createAndShowGUI()
JFrame de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.createAndShowGUI ()
This function generates the gui and fills it with default values
Returns
jFrame gui element
Definition at line 396 of file MatrixMapHandler.java.
References de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.controlInstance, de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.createGui(), de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.fillLoginData(), de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.getLocale(), and de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.rb.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.main(), and de.dlr.ivf.tapas.runtime.client.SimulationMonitor.SimulationMonitor().
createGui()
JFrame de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.createGui () private
method to initialise the gui elements and returns the main panel
Returns
jFrame gui element
Definition at line 410 of file MatrixMapHandler.java.
References de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.getMainPanel(), and de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.rb.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.createAndShowGUI().
deleteLists()
void de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.deleteLists () private
method to clear the lists and combo boxes
Definition at line 431 of file MatrixMapHandler.java.
deleteMatrixList()
void de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.deleteMatrixList () private
method to clear the matrix map list
Definition at line 441 of file MatrixMapHandler.java.
deleteMatrixMapList()
void de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.deleteMatrixMapList () private
method to clear the matrix map list
Definition at line 453 of file MatrixMapHandler.java.
deleteSelectedMatrices()
void de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.deleteSelectedMatrices () private
method to delete the selected Matrices from the db, each entry must be confirmed!
Definition at line 465 of file MatrixMapHandler.java.
deleteSelectedMatrixMaps()
void de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.deleteSelectedMatrixMaps () private
method to delete the selected matrix maps from the db, each entry must be confirmed!
Definition at line 493 of file MatrixMapHandler.java.
editMatrix()
void de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.editMatrix () private
method to edit a matrix entry
Definition at line 521 of file MatrixMapHandler.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.addMatrix().
editMatrixMap()
void de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.editMatrixMap () private
method to edit a matrixMap entry
Definition at line 579 of file MatrixMapHandler.java.
References de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.showDialog().
Referenced by de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.addMatrixMap().
fillLists()
void de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.fillLists () private
method to fill the combo boxes
Definition at line 612 of file MatrixMapHandler.java.
fillLoginData()
void de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.fillLoginData (boolean forceNewFile) private
Definition at line 631 of file MatrixMapHandler.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_DBNAME, de.dlr.ivf.tapas.util.parameters.ParamString.DB_HOST, de.dlr.ivf.tapas.util.parameters.ParamString.DB_PASSWORD, de.dlr.ivf.tapas.util.parameters.ParamValue.DB_PORT, de.dlr.ivf.tapas.util.parameters.ParamString.DB_USER, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getIntValue(), de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.getRuntimeFile(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), and de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.loadRuntimeParameters().
Referenced by de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.createAndShowGUI().
getConfigFileButton()
JButton de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.getConfigFileButton () private
This method initializes configFileButton
Returns
javax.swing.JButton
Definition at line 667 of file MatrixMapHandler.java.
getConnectButton()
JButton de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.getConnectButton () private
This method initializes connectButton
Returns
javax.swing.JButton
Definition at line 681 of file MatrixMapHandler.java.
getDbNameText()
JTextField de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.getDbNameText () private
This method initializes dbNameText
Returns
javax.swing.JTextField
Definition at line 701 of file MatrixMapHandler.java.
getDisconnectButton()
JButton de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.getDisconnectButton () private
This method initializes disconnectButton
Returns
javax.swing.JButton
Definition at line 713 of file MatrixMapHandler.java.
getJConnectionPane()
JPanel de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.getJConnectionPane () private
This method initializes jConnectionPane
Returns
javax.swing.JPanel
Definition at line 733 of file MatrixMapHandler.java.
getJMatrixMapPane()
JPanel de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.getJMatrixMapPane () private
This method initializes jMatrixMapPane
Returns
javax.swing.JPanel
Definition at line 794 of file MatrixMapHandler.java.
getJMatrixPane()
JPanel de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.getJMatrixPane () private
This method initializes jMatrixPane
Returns
javax.swing.JPanel
Definition at line 808 of file MatrixMapHandler.java.
getMainPanel()
JPanel de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.getMainPanel () private
This method initializes mainPanel
Returns
javax.swing.JPanel
Definition at line 822 of file MatrixMapHandler.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.createGui().
getMapListPane()
JPanel de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.getMapListPane () private
This method initializes MapListPane
Returns
javax.swing.JPanel
Definition at line 841 of file MatrixMapHandler.java.
getMatrixActionPanel()
JPanel de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.getMatrixActionPanel () private
This method initializes matrixActionPanel
Returns
javax.swing.JPanel
Definition at line 861 of file MatrixMapHandler.java.
getMatrixAddButton()
JButton de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.getMatrixAddButton () private
This method initializes matrixAddButton
Returns
javax.swing.JButton
Definition at line 890 of file MatrixMapHandler.java.
getMatrixButtonPanel()
JPanel de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.getMatrixButtonPanel () private
This method initializes matrixButtonPanel
Returns
javax.swing.JPanel
Definition at line 904 of file MatrixMapHandler.java.
getMatrixCloneButton()
JButton de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.getMatrixCloneButton () private
This method initializes matrixCloneButton
Returns
javax.swing.JButton
Definition at line 918 of file MatrixMapHandler.java.
getMatrixDBNameComboBox()
JComboBox<String> de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.getMatrixDBNameComboBox () private
This method initializes matrixDBNameComboBox
Returns
javax.swing.JComboBox
Definition at line 932 of file MatrixMapHandler.java.
getMatrixDBNamePanel()
JPanel de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.getMatrixDBNamePanel () private
This method initializes matrixDBNamePanel
Returns
javax.swing.JPanel
Definition at line 947 of file MatrixMapHandler.java.
getMatrixDeleteButton()
JButton de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.getMatrixDeleteButton () private
This method initializes matrixDeleteButton
Returns
javax.swing.JButton
Definition at line 966 of file MatrixMapHandler.java.
getMatrixEditButton()
JButton de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.getMatrixEditButton () private
This method initializes matrixEditButton
Returns
javax.swing.JButton
Definition at line 980 of file MatrixMapHandler.java.
getMatrixImportButton()
JButton de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.getMatrixImportButton () private
This method initializes matrixImportButton
Returns
javax.swing.JButton
Definition at line 994 of file MatrixMapHandler.java.
getMatrixList()
JScrollPane de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.getMatrixList () private
This method initializes matrixList
Returns
javax.swing.JScrollPane
Definition at line 1010 of file MatrixMapHandler.java.
getMatrixListPanel()
JPanel de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.getMatrixListPanel () private
This method initializes matrixListPanel
Returns
javax.swing.JPanel
Definition at line 1022 of file MatrixMapHandler.java.
getMatrixLoadButton()
JButton de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.getMatrixLoadButton () private
This method initializes matrixLoadButton
Returns
javax.swing.JButton
Definition at line 1042 of file MatrixMapHandler.java.
getMatrixMapActionPane()
JPanel de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.getMatrixMapActionPane () private
This method initializes matrixMapActionPane
Returns
javax.swing.JPanel
Definition at line 1056 of file MatrixMapHandler.java.
getMatrixMapAddButton()
JButton de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.getMatrixMapAddButton () private
This method initializes matrixMapAddButton
Returns
javax.swing.JButton
Definition at line 1081 of file MatrixMapHandler.java.
getMatrixMapButtonPane()
JPanel de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.getMatrixMapButtonPane () private
This method initializes matrixMapButtonPane
Returns
javax.swing.JPanel
Definition at line 1095 of file MatrixMapHandler.java.
getMatrixMapCloneButton()
JButton de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.getMatrixMapCloneButton () private
This method initializes matrixMapCloneButton
Returns
javax.swing.JButton
Definition at line 1109 of file MatrixMapHandler.java.
getMatrixMapDBNameComboBox()
JComboBox<String> de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.getMatrixMapDBNameComboBox () private
This method initializes matrixMapDBNameComboBox
Returns
javax.swing.JComboBox
Definition at line 1123 of file MatrixMapHandler.java.
getMatrixMapDBNamePane()
JPanel de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.getMatrixMapDBNamePane () private
This method initializes matrixMapDBNamePane
Returns
javax.swing.JPanel
Definition at line 1138 of file MatrixMapHandler.java.
getMatrixMapDeleteButton()
JButton de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.getMatrixMapDeleteButton () private
This method initializes matrixMapDeleteButton
Returns
javax.swing.JButton
Definition at line 1157 of file MatrixMapHandler.java.
getMatrixMapEditButton()
JButton de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.getMatrixMapEditButton () private
This method initializes matrixMapEditButton
Returns
javax.swing.JButton
Definition at line 1171 of file MatrixMapHandler.java.
getMatrixMapList()
JScrollPane de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.getMatrixMapList () private
This method initializes matrixMapList
Returns
javax.swing.JScrollPane
Definition at line 1185 of file MatrixMapHandler.java.
getMatrixMapLoadButton()
JButton de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.getMatrixMapLoadButton () private
This method initializes matrixMapLoadButton
Returns
javax.swing.JButton
Definition at line 1197 of file MatrixMapHandler.java.
getMatrixMapSplitPane()
JSplitPane de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.getMatrixMapSplitPane () private
This method initializes MatrixMapSplitPane
Returns
javax.swing.JSplitPane
Definition at line 1211 of file MatrixMapHandler.java.
getMatrixRenameButton()
JButton de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.getMatrixRenameButton () private
This method initializes matrixRenameButton
Returns
javax.swing.JButton
Definition at line 1226 of file MatrixMapHandler.java.
getMatrixSplitPane()
JSplitPane de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.getMatrixSplitPane () private
This method initializes MatrixSplitPane
Returns
javax.swing.JSplitPane
Definition at line 1240 of file MatrixMapHandler.java.
getPasswordField()
JPasswordField de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.getPasswordField () private
This method initializes passwordField
Returns
javax.swing.JPasswordField
Definition at line 1254 of file MatrixMapHandler.java.
getPortText()
JTextField de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.getPortText () private
This method initializes portText
Returns
javax.swing.JTextField
Definition at line 1267 of file MatrixMapHandler.java.
getRenameMatrixMapButton()
JButton de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.getRenameMatrixMapButton () private
This method initializes renameMatrixMapButton
Returns
javax.swing.JButton
Definition at line 1280 of file MatrixMapHandler.java.
getServerText()
JTextField de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.getServerText () private
This method initializes serverText
Returns
javax.swing.JTextField
Definition at line 1294 of file MatrixMapHandler.java.
getUserText()
JTextField de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.getUserText () private
This method initializes userText
Returns
javax.swing.JTextField
Definition at line 1307 of file MatrixMapHandler.java.
isMatrixExisting()
boolean de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.isMatrixExisting (String s) throws SQLException private
method to check if a given matrix name already exists
Returns
true if name exists
Definition at line 1321 of file MatrixMapHandler.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.cloneSelectedMatrices().
isMatrixMapExisting()
boolean de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.isMatrixMapExisting (String s) throws SQLException private
method to check if a given MatrixMapName is existing in the database
Returns
true if name exists
Definition at line 1334 of file MatrixMapHandler.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.cloneSelectedMatrixMaps().
loadMatrixList()
void de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.loadMatrixList () private
method to fill the matrix list with the entries from the db
Definition at line 1347 of file MatrixMapHandler.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.addMatrix(), and de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.cloneSelectedMatrices().
loadMatrixMapList()
void de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.loadMatrixMapList () private
method to fill the matrix map list with the entries from the db
Definition at line 1368 of file MatrixMapHandler.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.addMatrixMap(), and de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.cloneSelectedMatrixMaps().
main()
static void de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.main (String[] args) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException static
main method to start
Parameters
args parameters
Definition at line 91 of file MatrixMapHandler.java.
References de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.controlInstance, and de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.createAndShowGUI().
manipulateTop3()
void de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.manipulateTop3 () private
method to manipulate a matrix entry
Definition at line 1390 of file MatrixMapHandler.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.array1Dto2D(), de.dlr.ivf.tapas.util.TPS_Geometrics.calcTop3(), de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.matrixToSQLArray(), and name.
matrixEditTop3Button()
JButton de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.matrixEditTop3Button () private
This method initializes matrixEditTop3Button
Returns
javax.swing.JButton
Definition at line 1463 of file MatrixMapHandler.java.
newGridBag()
static GridBagConstraints de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.newGridBag (int gridX, int padX, int gridY, int padY) static
Definition at line 99 of file MatrixMapHandler.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.getAvailableMatrixPanel(), de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.getCurrentMatrixMapSetPanel(), and de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.getMainPanel1().
openConnection()
void de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.openConnection () private
method to open the db connection and to create the sqlStatement
Definition at line 1475 of file MatrixMapHandler.java.
renameMatrices()
void de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.renameMatrices () protected
method to change a matrix name in the database
Definition at line 1497 of file MatrixMapHandler.java.
renameMatrixMaps()
void de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.renameMatrixMaps () private
method to rename the selected matrix maps
Definition at line 1538 of file MatrixMapHandler.java.
set2ndLevelMatrixButtonEnabled()
void de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.set2ndLevelMatrixButtonEnabled (boolean val) private
method to enable and disable 2nd level matrix actions
Definition at line 1580 of file MatrixMapHandler.java.
set2ndLevelMatrixMapEnabled()
void de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.set2ndLevelMatrixMapEnabled (boolean val) private
method to enable and disable 2nd level matrix map actions
Definition at line 1593 of file MatrixMapHandler.java.
setConnectionEnabled()
void de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.setConnectionEnabled (boolean connected) private
This function enables and disables gui-elements according to the connection status
Parameters
connected indicates if db connection exists or not
Definition at line 1606 of file MatrixMapHandler.java.
Member Data Documentation
arrayChunk
final int de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.arrayChunk = 10000 static private
Definition at line 37 of file MatrixMapHandler.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.addMatrix(), and de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.cloneSelectedMatrices().
configFileButton
JButton de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.configFileButton = null private
Definition at line 51 of file MatrixMapHandler.java.
connectButton
JButton de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.connectButton = null private
Definition at line 49 of file MatrixMapHandler.java.
connection
Connection de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.connection = null private
Definition at line 78 of file MatrixMapHandler.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.closeConnection().
controlInstance
JFrame de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.controlInstance private
Definition at line 40 of file MatrixMapHandler.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.addMatrix(), de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.addMatrixMap(), de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.cloneSelectedMatrices(), de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.cloneSelectedMatrixMaps(), de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.createAndShowGUI(), and de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.main().
dbNameText
JTextField de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.dbNameText = null private
Definition at line 80 of file MatrixMapHandler.java.
disconnectButton
JButton de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.disconnectButton = null private
Definition at line 50 of file MatrixMapHandler.java.
jConnectionPane
JPanel de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.jConnectionPane = null private
Definition at line 42 of file MatrixMapHandler.java.
jMatrixMapPane
JPanel de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.jMatrixMapPane = null private
Definition at line 43 of file MatrixMapHandler.java.
jMatrixPane
JPanel de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.jMatrixPane = null private
Definition at line 44 of file MatrixMapHandler.java.
mainPanel
JPanel de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.mainPanel = null private
Definition at line 41 of file MatrixMapHandler.java.
MapListPane
JPanel de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.MapListPane = null private
Definition at line 53 of file MatrixMapHandler.java.
matrixActionPanel
JPanel de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.matrixActionPanel = null private
Definition at line 70 of file MatrixMapHandler.java.
matrixAddButton
JButton de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.matrixAddButton = null private
Definition at line 75 of file MatrixMapHandler.java.
matrixButtonPanel
JPanel de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.matrixButtonPanel = null private
Definition at line 69 of file MatrixMapHandler.java.
matrixCloneButton
JButton de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.matrixCloneButton = null private
Definition at line 81 of file MatrixMapHandler.java.
matrixDBNameComboBox
JComboBox<String> de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.matrixDBNameComboBox = null private
Definition at line 72 of file MatrixMapHandler.java.
matrixDBNamePanel
JPanel de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.matrixDBNamePanel = null private
Definition at line 66 of file MatrixMapHandler.java.
matrixDeleteButton
JButton de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.matrixDeleteButton = null private
Definition at line 76 of file MatrixMapHandler.java.
matrixEditButton
JButton de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.matrixEditButton = null private
Definition at line 73 of file MatrixMapHandler.java.
matrixEditTop3Button
JButton de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.matrixEditTop3Button = null private
Definition at line 74 of file MatrixMapHandler.java.
matrixImportButton
JButton de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.matrixImportButton = null private
Definition at line 77 of file MatrixMapHandler.java.
matrixList
JList<String> de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.matrixList = null private
Definition at line 68 of file MatrixMapHandler.java.
matrixListPanel
JPanel de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.matrixListPanel = null private
Definition at line 65 of file MatrixMapHandler.java.
matrixListScrollPane
JScrollPane de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.matrixListScrollPane = null private
Definition at line 67 of file MatrixMapHandler.java.
matrixLoadButton
JButton de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.matrixLoadButton = null private
Definition at line 71 of file MatrixMapHandler.java.
matrixMapActionPane
JPanel de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.matrixMapActionPane = null private
Definition at line 57 of file MatrixMapHandler.java.
matrixMapAddButton
JButton de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.matrixMapAddButton = null private
Definition at line 60 of file MatrixMapHandler.java.
matrixMapButtonPane
JPanel de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.matrixMapButtonPane = null private
Definition at line 54 of file MatrixMapHandler.java.
matrixMapCloneButton
JButton de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.matrixMapCloneButton = null private
Definition at line 82 of file MatrixMapHandler.java.
matrixMapDBNameComboBox
JComboBox<String> de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.matrixMapDBNameComboBox = null private
Definition at line 56 of file MatrixMapHandler.java.
matrixMapDBNamePane
JPanel de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.matrixMapDBNamePane = null private
Definition at line 55 of file MatrixMapHandler.java.
matrixMapDeleteButton
JButton de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.matrixMapDeleteButton = null private
Definition at line 61 of file MatrixMapHandler.java.
matrixMapEditButton
JButton de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.matrixMapEditButton = null private
Definition at line 59 of file MatrixMapHandler.java.
matrixMapList
JList<String> de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.matrixMapList = null private
Definition at line 63 of file MatrixMapHandler.java.
matrixMapListScrollPane
JScrollPane de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.matrixMapListScrollPane = null private
Definition at line 62 of file MatrixMapHandler.java.
matrixMapLoadButton
JButton de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.matrixMapLoadButton = null private
Definition at line 58 of file MatrixMapHandler.java.
MatrixMapSplitPane
JSplitPane de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.MatrixMapSplitPane = null private
Definition at line 52 of file MatrixMapHandler.java.
matrixRenameButton
JButton de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.matrixRenameButton = null private
Definition at line 84 of file MatrixMapHandler.java.
MatrixSplitPane
JSplitPane de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.MatrixSplitPane = null private
Definition at line 64 of file MatrixMapHandler.java.
passwordField
JPasswordField de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.passwordField = null private
Definition at line 48 of file MatrixMapHandler.java.
portText
JTextField de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.portText = null private
Definition at line 46 of file MatrixMapHandler.java.
rb
ResourceBundle de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.rb private
Definition at line 39 of file MatrixMapHandler.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.addMatrix(), de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.addMatrixMap(), de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.cloneSelectedMatrices(), de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.cloneSelectedMatrixMaps(), de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.createAndShowGUI(), and de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.createGui().
renameMatrixMapButton
JButton de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.renameMatrixMapButton = null private
Definition at line 83 of file MatrixMapHandler.java.
serverText
JTextField de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.serverText = null private
Definition at line 45 of file MatrixMapHandler.java.
statement
Statement de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.statement = null private
Definition at line 79 of file MatrixMapHandler.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.addMatrix(), de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.addMatrixMap(), de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.cloneSelectedMatrices(), de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.cloneSelectedMatrixMaps(), and de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.closeConnection().
userText
JTextField de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.userText = null private
Definition at line 47 of file MatrixMapHandler.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/matrixMap/MatrixMapHandler.java