TAPAS: de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport Class Reference
de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport Class Reference
Public Member Functions
GeneralDatabaseSummaryExport (Analyzer analyzer, String source) throws IOException, ClassNotFoundException
boolean writeSummary ()
Static Public Member Functions
static void main (String[] args) throws ClassNotFoundException, IOException, SQLException
Private Member Functions
void fillBatch (PreparedStatement ps)
Private Attributes
final TPS_DB_Connector dbCon
final Analyzer analyzer
final String source
boolean update = false
Detailed Description
Definition at line 27 of file GeneralDatabaseSummaryExport.java.
Constructor & Destructor Documentation
GeneralDatabaseSummaryExport()
de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.GeneralDatabaseSummaryExport (Analyzer analyzer, String source) throws IOException, ClassNotFoundException
Parameters
analyzer This Analyzer must have the following analyzers: [ModeAnalyzer, PersonGroupAnalyzer, TripIntentionAnalyzer, DefaultDistanceCategoryAnalyzer] . The order is important. The PersonGroupAnalyzer must have person statistics.
source
Exceptions
SQLException when the connection to the database fails.
IOException if the loginInfo is not found
ClassNotFoundException if the TPS_DB_Connector could not login.
IllegalArgumentException if any of the mentioned
Definition at line 46 of file GeneralDatabaseSummaryExport.java.
References de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.analyzer, de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.dbCon, de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.DistanceCategoryDefault, de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.Analyzer.getCategories(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection(), de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.getRuntimeFile(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.Analyzer.hasPersonGroupStatistics(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.loadRuntimeParameters(), de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.Mode, de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.PersonGroup, de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.source, de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.TripIntention, and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.update.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.main().
Member Function Documentation
fillBatch()
void de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.fillBatch (PreparedStatement ps) private
Definition at line 130 of file GeneralDatabaseSummaryExport.java.
References de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.analyzer, de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.DistanceCategoryDefault, de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.Analyzer.getCntPersons(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.Analyzer.getDistance(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.Analyzer.getDuration(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.Analyzer.getTripCnt(), de.dlr.ivf.tapas.analyzer.tum.constants.CategoryCombination.listAllCombinations(), de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.Mode, de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.PersonGroup, de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.PersonGroup.PG_1, de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.source, de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.TripIntention.TRIP_31, and de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.TripIntention.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.writeSummary().
main()
static void de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.main (String[] args) throws ClassNotFoundException, IOException, SQLException static
Parameters
args
Exceptions
IOException
ClassNotFoundException
SQLException
Definition at line 98 of file GeneralDatabaseSummaryExport.java.
References de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.Analyzer.addTrip(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.analyzer, de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.close(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.dbCon, de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.GeneralDatabaseSummaryExport(), de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.getIterator(), de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.getRuntimeFile(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.loadRuntimeParameters(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.writeSummary().
writeSummary()
boolean de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.writeSummary ()
Inserts or updates the summary in the database.
Returns
false if the database access failed or the region was differentiated.
Definition at line 173 of file GeneralDatabaseSummaryExport.java.
References de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.dbCon, de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.fillBatch(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.update.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzer.finish(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.main().
Member Data Documentation
analyzer
final Analyzer de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.analyzer private
Definition at line 30 of file GeneralDatabaseSummaryExport.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.fillBatch(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.GeneralDatabaseSummaryExport(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.main().
dbCon
final TPS_DB_Connector de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.dbCon private
Definition at line 29 of file GeneralDatabaseSummaryExport.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.GeneralDatabaseSummaryExport(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.main(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.writeSummary().
source
final String de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.source private
Definition at line 31 of file GeneralDatabaseSummaryExport.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.fillBatch(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.GeneralDatabaseSummaryExport().
update
boolean de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.update = false private
Definition at line 33 of file GeneralDatabaseSummaryExport.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.GeneralDatabaseSummaryExport(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.writeSummary().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/tum/regionanalyzer/general/GeneralDatabaseSummaryExport.java