TAPAS: de.dlr.ivf.tapas.scheme.TPS_SchemeSet Class Reference
de.dlr.ivf.tapas.scheme.TPS_SchemeSet Class Reference
Public Member Functions
TPS_SchemeSet ()
void addDistribution (TPS_PersonGroup persGroup, TPS_DiscreteDistribution< Integer > distribution)
boolean containsDistribution (TPS_PersonGroup key)
boolean containsSchemeClass (int schemeClassId)
TPS_Scheme findScheme (TPS_Person person)
TPS_SchemeClass getSchemeClass (int schemeClassId)
Integer[] getSchemeClassIdArray ()
Iterable< TPS_SchemeClass > getSchemeClassIterable ()
void init ()
Iterator< TPS_Scheme > iterator ()
TPS_Scheme selectScheme (TPS_Person person)
String toString ()
String toString (String prefix)
Private Attributes
final SortedMap< TPS_PersonGroup, TPS_DiscreteDistribution< Integer > > distributionMap
Collection of scheme class distributions mapped by the person group.
final Map< Integer, TPS_SchemeClass > schemeClasses
Collection of scheme classes mapped by their own id.
Detailed Description
This class is a collection of all schemes collected by several scheme classes. Furthermore the scheme classes are weighted by distributions created for different person groups.
Definition at line 28 of file TPS_SchemeSet.java.
Constructor & Destructor Documentation
TPS_SchemeSet()
de.dlr.ivf.tapas.scheme.TPS_SchemeSet.TPS_SchemeSet ()
Constructor
Definition at line 39 of file TPS_SchemeSet.java.
Member Function Documentation
addDistribution()
void de.dlr.ivf.tapas.scheme.TPS_SchemeSet.addDistribution (TPS_PersonGroup persGroup, TPS_DiscreteDistribution< Integer > distribution)
This method adds a scheme class distribution for the given person group
Parameters
persGroup person group
distribution probability distribution of scheme class ids
Definition at line 51 of file TPS_SchemeSet.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readSchemeSet().
containsDistribution()
boolean de.dlr.ivf.tapas.scheme.TPS_SchemeSet.containsDistribution (TPS_PersonGroup key)
Parameters
key person group to search a distribution for
Returns
true if the scheme set contains a distribution for the given person group, false otherwise
Definition at line 60 of file TPS_SchemeSet.java.
containsSchemeClass()
boolean de.dlr.ivf.tapas.scheme.TPS_SchemeSet.containsSchemeClass (int schemeClassId)
Checks whether the scheme class identified by the id given is contained in the scheme set
Parameters
schemeClassId scheme class id corresponding to a scheme class
Returns
true if the scheme class is contained, false otherwise
Definition at line 71 of file TPS_SchemeSet.java.
findScheme()
TPS_Scheme de.dlr.ivf.tapas.scheme.TPS_SchemeSet.findScheme (TPS_Person person)
Function determines the scheme to be used by the person specified. In case a specific type of scheme is to be preferred, the selection probabilities are adopted.
Parameters
person person the scheme is to be selected for
Returns
the scheme which was found, null is also possible
Definition at line 82 of file TPS_SchemeSet.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.DEBUG, de.dlr.ivf.tapas.scheme.TPS_Scheme.getId(), de.dlr.ivf.tapas.scheme.TPS_SchemeClass.getId(), de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), de.dlr.ivf.tapas.log.TPS_Logger.log(), and de.dlr.ivf.tapas.log.TPS_LoggingInterface.HierarchyLogLevel.PERSON.
Referenced by de.dlr.ivf.tapas.person.TPS_Worker.createPersonPlans().
getSchemeClass()
TPS_SchemeClass de.dlr.ivf.tapas.scheme.TPS_SchemeSet.getSchemeClass (int schemeClassId)
This method returns the scheme class corresponding to the given id. If the scheme class does not exist yet it is created.
Parameters
schemeClassId scheme class id corresponding to a scheme class
Returns
scheme class to the given id
Definition at line 100 of file TPS_SchemeSet.java.
References de.dlr.ivf.tapas.scheme.TPS_SchemeClass.getId().
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readSchemeSet().
getSchemeClassIdArray()
Integer [] de.dlr.ivf.tapas.scheme.TPS_SchemeSet.getSchemeClassIdArray ()
Definition at line 112 of file TPS_SchemeSet.java.
getSchemeClassIterable()
Iterable<TPS_SchemeClass> de.dlr.ivf.tapas.scheme.TPS_SchemeSet.getSchemeClassIterable ()
Returns
Iterable over all scheme classes
Definition at line 120 of file TPS_SchemeSet.java.
init()
void de.dlr.ivf.tapas.scheme.TPS_SchemeSet.init ()
This method calls the init method of every scheme
Definition at line 127 of file TPS_SchemeSet.java.
References de.dlr.ivf.tapas.scheme.TPS_Scheme.init().
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readSchemeSet().
iterator()
Iterator<TPS_Scheme> de.dlr.ivf.tapas.scheme.TPS_SchemeSet.iterator ()
Definition at line 138 of file TPS_SchemeSet.java.
selectScheme()
TPS_Scheme de.dlr.ivf.tapas.scheme.TPS_SchemeSet.selectScheme (TPS_Person person)
First of all the distribution of the scheme classes for the given person is searched by the person group. Then there is one scheme class drawn out of the distribution. At last, there is a scheme out of the scheme class drawn.
Parameters
person person
Returns
the drawn scheme
Definition at line 150 of file TPS_SchemeSet.java.
References de.dlr.ivf.tapas.scheme.TPS_SchemeClass.draw(), de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.drawKey(), and de.dlr.ivf.tapas.person.TPS_Person.getPersGroup().
toString() [1/2]
String de.dlr.ivf.tapas.scheme.TPS_SchemeSet.toString ()
Definition at line 163 of file TPS_SchemeSet.java.
toString() [2/2]
String de.dlr.ivf.tapas.scheme.TPS_SchemeSet.toString (String prefix)
This method should print the object naturally with the given prefix.
Parameters
prefix
Returns
prefix + toString();
Implements de.dlr.ivf.tapas.util.ExtendedWritable.
Definition at line 172 of file TPS_SchemeSet.java.
Member Data Documentation
distributionMap
final SortedMap<TPS_PersonGroup, TPS_DiscreteDistribution<Integer> > de.dlr.ivf.tapas.scheme.TPS_SchemeSet.distributionMap private
Collection of scheme class distributions mapped by the person group.
Definition at line 30 of file TPS_SchemeSet.java.
schemeClasses
final Map<Integer, TPS_SchemeClass> de.dlr.ivf.tapas.scheme.TPS_SchemeSet.schemeClasses private
Collection of scheme classes mapped by their own id.
Definition at line 33 of file TPS_SchemeSet.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/scheme/TPS_SchemeSet.java