TAPAS: de.dlr.ivf.tapas.person.TPS_Preference Class Reference
de.dlr.ivf.tapas.person.TPS_Preference Class Reference
Classes
class PreferenceSet
Public Member Functions
TPS_Preference ()
void computePreferences (TPS_PreferenceParameters parameters, TPS_Person person)
Private Member Functions
double calcUtility (ChoiceParams param, TPS_Person person)
Detailed Description
This class holdts the specific preference parameters for this person.
Author
hein_mh
Definition at line 23 of file TPS_Preference.java.
Constructor & Destructor Documentation
TPS_Preference()
de.dlr.ivf.tapas.person.TPS_Preference.TPS_Preference ()
standard constructor, which needs a reference to the person it is attached to
Definition at line 33 of file TPS_Preference.java.
References de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingPreferenceSupply.Sonstige, de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingPreferenceAccessibility.Sonstige, de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingPreferenceSupply.valueArray, and de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingPreferenceAccessibility.valueArray.
Member Function Documentation
calcUtility()
double de.dlr.ivf.tapas.person.TPS_Preference.calcUtility (ChoiceParams param, TPS_Person person) private
Definition at line 76 of file TPS_Preference.java.
References de.dlr.ivf.tapas.constants.TPS_Sex.FEMALE, de.dlr.ivf.tapas.person.TPS_Person.getAge(), de.dlr.ivf.tapas.person.TPS_Household.getCarNumber(), de.dlr.ivf.tapas.person.TPS_Person.getEducationLevel(), de.dlr.ivf.tapas.person.TPS_Person.getHousehold(), de.dlr.ivf.tapas.person.TPS_Household.getIncome(), de.dlr.ivf.tapas.person.TPS_Household.getMembers(), de.dlr.ivf.tapas.person.TPS_Person.getPersGroup(), de.dlr.ivf.tapas.person.TPS_Person.getSex(), de.dlr.ivf.tapas.person.TPS_Person.isWorking(), de.dlr.ivf.tapas.person.TPS_Household.Sorting.NONE, and de.dlr.ivf.tapas.constants.TPS_PersonGroup.TPS_PersonType.RETIREE.
Referenced by de.dlr.ivf.tapas.person.TPS_Preference.computePreferences().
computePreferences()
void de.dlr.ivf.tapas.person.TPS_Preference.computePreferences (TPS_PreferenceParameters parameters, TPS_Person person)
Method to precompute the preference values
Parameters
parameters
Definition at line 143 of file TPS_Preference.java.
References de.dlr.ivf.tapas.person.TPS_Preference.calcUtility(), de.dlr.ivf.tapas.person.TPS_PreferenceParameters.paramsAccess, and de.dlr.ivf.tapas.person.TPS_PreferenceParameters.paramsSupply.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/person/TPS_Preference.java