TAPAS: de.dlr.ivf.tapas.analyzer.tum.StatisticPOJO Class Reference
de.dlr.ivf.tapas.analyzer.tum.StatisticPOJO Class Reference
Public Member Functions
StatisticPOJO ()
void addRegion (RegionPOJO analysis)
List< RegionPOJO > getAnalyses ()
int getCntIgnored ()
void setCntIgnored (int cntIgnored)
int getNrTrips ()
void setNrTrips (int size)
boolean isRegionalDifferentiation ()
void setRegionalDifferentiation (boolean regionalDifferentiation)
void setTripsIgnored (int cntIgnored)
Private Attributes
final List< RegionPOJO > analyses = new ArrayList<>()
int cntIgnored
int nrTrips
boolean regionalDifferentiation
Detailed Description
Definition at line 15 of file StatisticPOJO.java.
Constructor & Destructor Documentation
StatisticPOJO()
de.dlr.ivf.tapas.analyzer.tum.StatisticPOJO.StatisticPOJO ()
Definition at line 22 of file StatisticPOJO.java.
Member Function Documentation
addRegion()
void de.dlr.ivf.tapas.analyzer.tum.StatisticPOJO.addRegion (RegionPOJO analysis)
Definition at line 26 of file StatisticPOJO.java.
References de.dlr.ivf.tapas.analyzer.tum.StatisticPOJO.analyses.
getAnalyses()
List<RegionPOJO> de.dlr.ivf.tapas.analyzer.tum.StatisticPOJO.getAnalyses ()
Definition at line 31 of file StatisticPOJO.java.
References de.dlr.ivf.tapas.analyzer.tum.StatisticPOJO.analyses.
Referenced by de.dlr.ivf.tapas.analyzer.core.TapasChartFactory.createModalSplit(), de.dlr.ivf.tapas.analyzer.core.TapasChartFactory.createModalSplitDistanceCategorySeparated(), de.dlr.ivf.tapas.analyzer.core.TapasChartFactory.createModalSplitTripIntentionDistanceCategorySeparated(), de.dlr.ivf.tapas.analyzer.core.TapasChartFactory.createModalSplitTripIntentionSeparated(), de.dlr.ivf.tapas.analyzer.core.TapasChartFactory.createModalSplitTripIntentionTapasPersonGroupSeparated(), de.dlr.ivf.tapas.analyzer.core.TapasChartFactory.createModalSplitTripIntentionVisevaPersonGroupSeparated(), de.dlr.ivf.tapas.analyzer.core.TapasChartFactory.createTripLength(), de.dlr.ivf.tapas.analyzer.core.TapasChartFactory.createTripLengthModeSeparated(), and de.dlr.ivf.tapas.analyzer.core.TapasChartFactory.createTripLengthTripIntentionSeparated().
getCntIgnored()
int de.dlr.ivf.tapas.analyzer.tum.StatisticPOJO.getCntIgnored ()
Definition at line 35 of file StatisticPOJO.java.
References de.dlr.ivf.tapas.analyzer.tum.StatisticPOJO.cntIgnored.
getNrTrips()
int de.dlr.ivf.tapas.analyzer.tum.StatisticPOJO.getNrTrips ()
Definition at line 43 of file StatisticPOJO.java.
References de.dlr.ivf.tapas.analyzer.tum.StatisticPOJO.nrTrips.
isRegionalDifferentiation()
boolean de.dlr.ivf.tapas.analyzer.tum.StatisticPOJO.isRegionalDifferentiation ()
Definition at line 51 of file StatisticPOJO.java.
References de.dlr.ivf.tapas.analyzer.tum.StatisticPOJO.regionalDifferentiation.
setCntIgnored()
void de.dlr.ivf.tapas.analyzer.tum.StatisticPOJO.setCntIgnored (int cntIgnored)
Definition at line 39 of file StatisticPOJO.java.
References de.dlr.ivf.tapas.analyzer.tum.StatisticPOJO.cntIgnored.
setNrTrips()
void de.dlr.ivf.tapas.analyzer.tum.StatisticPOJO.setNrTrips (int size)
Definition at line 47 of file StatisticPOJO.java.
setRegionalDifferentiation()
void de.dlr.ivf.tapas.analyzer.tum.StatisticPOJO.setRegionalDifferentiation (boolean regionalDifferentiation)
Definition at line 55 of file StatisticPOJO.java.
References de.dlr.ivf.tapas.analyzer.tum.StatisticPOJO.regionalDifferentiation.
setTripsIgnored()
void de.dlr.ivf.tapas.analyzer.tum.StatisticPOJO.setTripsIgnored (int cntIgnored)
Definition at line 59 of file StatisticPOJO.java.
References de.dlr.ivf.tapas.analyzer.tum.StatisticPOJO.cntIgnored.
Member Data Documentation
analyses
final List<RegionPOJO> de.dlr.ivf.tapas.analyzer.tum.StatisticPOJO.analyses = new ArrayList<>() private
Definition at line 17 of file StatisticPOJO.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.StatisticPOJO.addRegion(), and de.dlr.ivf.tapas.analyzer.tum.StatisticPOJO.getAnalyses().
cntIgnored
int de.dlr.ivf.tapas.analyzer.tum.StatisticPOJO.cntIgnored private
Definition at line 18 of file StatisticPOJO.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.StatisticPOJO.getCntIgnored(), de.dlr.ivf.tapas.analyzer.tum.StatisticPOJO.setCntIgnored(), and de.dlr.ivf.tapas.analyzer.tum.StatisticPOJO.setTripsIgnored().
nrTrips
int de.dlr.ivf.tapas.analyzer.tum.StatisticPOJO.nrTrips private
Definition at line 19 of file StatisticPOJO.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.StatisticPOJO.getNrTrips().
regionalDifferentiation
boolean de.dlr.ivf.tapas.analyzer.tum.StatisticPOJO.regionalDifferentiation private
Definition at line 20 of file StatisticPOJO.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.StatisticPOJO.isRegionalDifferentiation(), and de.dlr.ivf.tapas.analyzer.tum.StatisticPOJO.setRegionalDifferentiation().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/tum/StatisticPOJO.java