TAPAS: de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.ModalSplitForDistanceCategory.ModalSplitForDistanceCategoryElement Class Reference
de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.ModalSplitForDistanceCategory.ModalSplitForDistanceCategoryElement Class Reference
Public Member Functions
List< DistanceCategory > getDistanceCategories ()
double getModalSplit ()
long getModalSplitAbs ()
Private Attributes
double modalSplit
long modalSplitAbs
List< DistanceCategory > distanceCategories
Detailed Description
Ein Element des Modalsplits. Abhängig davon welche Distanzkategorien selektiert wurden, enthält dieses Element die Distanzkategorien die zusammengefasst wurden.
Author
Marco
Definition at line 719 of file RegionPOJO.java.
Member Function Documentation
getDistanceCategories()
List<DistanceCategory> de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.ModalSplitForDistanceCategory.ModalSplitForDistanceCategoryElement.getDistanceCategories ()
Definition at line 724 of file RegionPOJO.java.
Referenced by de.dlr.ivf.tapas.analyzer.core.TapasChartFactory.createModalSplitDistanceCategorySeparated(), and de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getModalSplitForDistanceCategory().
getModalSplit()
double de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.ModalSplitForDistanceCategory.ModalSplitForDistanceCategoryElement.getModalSplit ()
Definition at line 729 of file RegionPOJO.java.
Referenced by de.dlr.ivf.tapas.analyzer.core.TapasChartFactory.createModalSplitDistanceCategorySeparated().
getModalSplitAbs()
long de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.ModalSplitForDistanceCategory.ModalSplitForDistanceCategoryElement.getModalSplitAbs ()
Definition at line 733 of file RegionPOJO.java.
Member Data Documentation
distanceCategories
List<DistanceCategory> de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.ModalSplitForDistanceCategory.ModalSplitForDistanceCategoryElement.distanceCategories private
Definition at line 722 of file RegionPOJO.java.
modalSplit
double de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.ModalSplitForDistanceCategory.ModalSplitForDistanceCategoryElement.modalSplit private
Definition at line 720 of file RegionPOJO.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getModalSplitForDistanceCategory().
modalSplitAbs
long de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.ModalSplitForDistanceCategory.ModalSplitForDistanceCategoryElement.modalSplitAbs private
Definition at line 721 of file RegionPOJO.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getModalSplitForDistanceCategory().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/tum/RegionPOJO.java