TAPAS: de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.Analyzer Class Reference
de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.Analyzer Class Reference
Public Member Functions
Analyzer (AnalyzerBase... analyzers)
void addTrip (TapasTrip trip)
Categories[] getCategories ()
int getCntPersons (Enum[] e)
double getDistance (Enum[] e)
double getDuration (Enum[] e)
int getNumberOfAnalyzers ()
ArrayList< TASplitData > getSplit (Enum... c)
long getTripCnt (Enum[] e)
TripStats getTripStats (Enum[] e)
boolean hasPersonGroupStatistics ()
String toString ()
Private Member Functions
CategoryCombination assignTrip (TapasTrip trip)
Private Attributes
final AnalyzerBase[] analyzers
final int numberOfAnalyzers
int idxPersonGroup = -1
final HashMap< CategoryCombination, TripStats > statsMap = new HashMap<>()
Detailed Description
This class combines a number of AnalyzerBase instances. The split will by made by applying every AnalyzerBase to the trips.
Author
boec_pa
Definition at line 26 of file Analyzer.java.
Constructor & Destructor Documentation
Analyzer()
de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.Analyzer.Analyzer (AnalyzerBase... analyzers)
The order of the AnalyzerBase matters if you use Analyzer#getSplit(Enum...).
Parameters
analyzers
Definition at line 40 of file Analyzer.java.
Member Function Documentation
addTrip()
void de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.Analyzer.addTrip (TapasTrip trip)
Adds the TapasTrip to the statistics.
Parameters
trip
Definition at line 59 of file Analyzer.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.main().
assignTrip()
CategoryCombination de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.Analyzer.assignTrip (TapasTrip trip) private
Definition at line 67 of file Analyzer.java.
getCategories()
Categories [] de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.Analyzer.getCategories ()
Returns the Categories of this Analyzer.
Definition at line 78 of file Analyzer.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.GeneralDatabaseSummaryExport(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralExcelExport.writeTab().
getCntPersons()
int de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.Analyzer.getCntPersons (Enum[] e)
Returns
-1 if no information is available
Definition at line 89 of file Analyzer.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.fillBatch().
getDistance()
double de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.Analyzer.getDistance (Enum[] e)
Gets the accumulated distance for a combination of categories. An example would be [RegionCode#REGION_0, PersonGroup#PG_6]. The order has to be the same as the order at construction of this Analyzer.
Definition at line 106 of file Analyzer.java.
References de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.TripStats.getDist().
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.fillBatch().
getDuration()
double de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.Analyzer.getDuration (Enum[] e)
Gets the total of trips for a combination of categories. An example would be [RegionCode#REGION_0, PersonGroup#PG_6]. The order has to be the same as the order at construction of this Analyzer.
Definition at line 119 of file Analyzer.java.
References de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.TripStats.getDur().
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.fillBatch().
getNumberOfAnalyzers()
int de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.Analyzer.getNumberOfAnalyzers ()
Definition at line 126 of file Analyzer.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralExcelExport.writeTab().
getSplit()
ArrayList<TASplitData> de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.Analyzer.getSplit (Enum... c)
Calculates the split along the last Categories of the analyzer for the given categories.
Example: The analyzer is [Pg, Ti, Mo]. A call could be c={ PersonGroup#PG_1, TripIntention#TRIP_35 } which gives a modal split for these categories.
Parameters
c the categories for all but the last category.
Definition at line 143 of file Analyzer.java.
References de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.TripStats.add(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.TripStats.getCntTrips(), de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.getEnumeration(), and de.dlr.ivf.tapas.analyzer.tum.constants.CategoryCombination.listAllCombinations().
getTripCnt()
long de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.Analyzer.getTripCnt (Enum[] e)
Gets the number of trips for a combination of categories. An example would be [RegionCode#REGION_0, PersonGroup#PG_6]. The order has to be the same as the order at construction of this Analyzer.
Definition at line 199 of file Analyzer.java.
References de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.TripStats.getCntTrips().
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.fillBatch().
getTripStats()
TripStats de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.Analyzer.getTripStats (Enum[] e)
Gets the TripStats for a combination of categories. An example would be [RegionCode#REGION_0, PersonGroup#PG_6]. The order has to be the same as the order at construction of this Analyzer.
Definition at line 213 of file Analyzer.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getTripStats().
hasPersonGroupStatistics()
boolean de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.Analyzer.hasPersonGroupStatistics ()
Definition at line 221 of file Analyzer.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.GeneralDatabaseSummaryExport().
toString()
String de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.Analyzer.toString ()
Definition at line 226 of file Analyzer.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralExcelExport.writeTab().
Member Data Documentation
analyzers
final AnalyzerBase [] de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.Analyzer.analyzers private
Definition at line 28 of file Analyzer.java.
idxPersonGroup
int de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.Analyzer.idxPersonGroup = -1 private
Definition at line 30 of file Analyzer.java.
numberOfAnalyzers
final int de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.Analyzer.numberOfAnalyzers private
Definition at line 29 of file Analyzer.java.
statsMap
final HashMap<CategoryCombination, TripStats> de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.Analyzer.statsMap = new HashMap<>() private
Definition at line 32 of file Analyzer.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/tum/regionanalyzer/Analyzer.java