TAPAS: de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI Class Reference
de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI Class Reference
Public Member Functions
void activateStart ()
void handleException (String job, Exception ex)
void print (String message)
void repaint ()
void resetCursor ()
void setCursor (Cursor cursor)
Static Public Member Functions
static void main (String[] args) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException
Static Public Attributes
static final String ABS_PATH = "T:/TAPAS/Inputdateien/"
Private Member Functions
File chooseConfigFile (String title, JFrame f)
void createAndShowGui ()
void define (File file)
JTable getFileTable ()
void load (File file)
void loadConfig (File file)
Private Attributes
final TPS_ParameterClass parameterClass
File configFile
JFrame control
DBImportController core
JTable fileTable
DBImportTableModel model
JTextField regionField
JTextField schemaField
JButton btnStart
JTextArea textPane
Cursor cursor
Static Private Attributes
static final boolean DEBUG = false
Detailed Description
Definition at line 29 of file DBImportGUI.java.
Member Function Documentation
activateStart()
void de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.activateStart ()
Definition at line 64 of file DBImportGUI.java.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportController.dbimport().
chooseConfigFile()
File de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.chooseConfigFile (String title, JFrame f) private
Definition at line 68 of file DBImportGUI.java.
References de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.ABS_PATH.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.createAndShowGui(), and de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.loadConfig().
createAndShowGui()
void de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.createAndShowGui () private
Definition at line 86 of file DBImportGUI.java.
References de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.btnStart, de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.chooseConfigFile(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.configFile, de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.control, de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.core, de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportController.dbimport(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.DEBUG, de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.define(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.fileTable, de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.getFileTable(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.handleException(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.load(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.loadConfig(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.model, de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.print(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.regionField, and de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.schemaField.
define()
void de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.define (File file) private
Definition at line 322 of file DBImportGUI.java.
References de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.control, de.dlr.ivf.tapas.util.parameters.ParamString.DB_REGION, de.dlr.ivf.tapas.util.parameters.ParamString.DB_SCHEMA_CORE, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.handleException(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.loadConfig(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.loadRuntimeParameters(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.regionField, and de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.schemaField.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.createAndShowGui(), and de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.load().
getFileTable()
JTable de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.getFileTable () private
Definition at line 341 of file DBImportGUI.java.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.createAndShowGui().
handleException()
void de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.handleException (String job, Exception ex)
Definition at line 371 of file DBImportGUI.java.
References de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.print().
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.createAndShowGui(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportController.dbimport(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.define(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.load(), and de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.loadConfig().
load()
void de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.load (File file) private
Definition at line 379 of file DBImportGUI.java.
References de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.control, de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.define(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.fileTable, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.handleException(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isDefined(), and de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.model.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.createAndShowGui().
loadConfig()
void de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.loadConfig (File file) private
Definition at line 417 of file DBImportGUI.java.
References de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.chooseConfigFile(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.control, de.dlr.ivf.tapas.util.parameters.ParamString.DB_DBNAME, de.dlr.ivf.tapas.util.parameters.ParamString.DB_HOST, de.dlr.ivf.tapas.util.parameters.ParamString.DB_PASSWORD, de.dlr.ivf.tapas.util.parameters.ParamValue.DB_PORT, de.dlr.ivf.tapas.util.parameters.ParamString.DB_USER, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getIntValue(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.handleException(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.loadSingleParameterFile(), and de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.print().
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.createAndShowGui(), and de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.define().
main()
static void de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.main (String[] args) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException static
Definition at line 55 of file DBImportGUI.java.
References de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.control.
print()
void de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.print (String message)
Definition at line 438 of file DBImportGUI.java.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.createAndShowGui(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportController.dbimport(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.handleException(), and de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.loadConfig().
repaint()
void de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.repaint ()
Definition at line 444 of file DBImportGUI.java.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportController.dbimport().
resetCursor()
void de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.resetCursor ()
Definition at line 448 of file DBImportGUI.java.
References de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.cursor.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportController.dbimport().
setCursor()
void de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.setCursor (Cursor cursor)
Definition at line 452 of file DBImportGUI.java.
References de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.cursor.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportController.dbimport().
Member Data Documentation
ABS_PATH
final String de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.ABS_PATH = "T:/TAPAS/Inputdateien/" static
Definition at line 31 of file DBImportGUI.java.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.chooseConfigFile(), and de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportTableModel.FileOpenEditor.getTableCellEditorComponent().
btnStart
JButton de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.btnStart private
Definition at line 47 of file DBImportGUI.java.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.createAndShowGui().
configFile
File de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.configFile private
Definition at line 40 of file DBImportGUI.java.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.createAndShowGui().
control
JFrame de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.control private
Definition at line 41 of file DBImportGUI.java.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.createAndShowGui(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.define(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.load(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.loadConfig(), and de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.main().
core
DBImportController de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.core private
Definition at line 42 of file DBImportGUI.java.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.createAndShowGui().
cursor
Cursor de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.cursor private
Definition at line 49 of file DBImportGUI.java.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.resetCursor(), and de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.setCursor().
DEBUG
final boolean de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.DEBUG = false static private
Definition at line 33 of file DBImportGUI.java.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.createAndShowGui().
fileTable
JTable de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.fileTable private
Definition at line 43 of file DBImportGUI.java.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.createAndShowGui(), and de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.load().
model
DBImportTableModel de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.model private
Definition at line 44 of file DBImportGUI.java.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.createAndShowGui(), and de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.load().
parameterClass
final TPS_ParameterClass de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.parameterClass private
Definition at line 39 of file DBImportGUI.java.
regionField
JTextField de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.regionField private
Definition at line 45 of file DBImportGUI.java.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.createAndShowGui(), and de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.define().
schemaField
JTextField de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.schemaField private
Definition at line 46 of file DBImportGUI.java.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.createAndShowGui(), and de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.define().
textPane
JTextArea de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.textPane private
Definition at line 48 of file DBImportGUI.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/persitence/db/dbImport/DBImportGUI.java