TAPAS: de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripConverter Class Reference
de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripConverter Class Reference
Public Member Functions
TapasTripConverter (List< File > tripFiles)
boolean convertNextTrip (StyledDocument console) throws BadLocationException
TapasTrip getTrip ()
void setTrip (TapasTrip trip)
String getTripFile ()
Private Attributes
File currentTripFile = null
TPS_FileReader reader = null
TapasTrip trip = null
int tripFileCounter
final List< File > tripFiles
Detailed Description
Definition at line 18 of file TapasTripConverter.java.
Constructor & Destructor Documentation
TapasTripConverter()
de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripConverter.TapasTripConverter (List< File > tripFiles)
Definition at line 26 of file TapasTripConverter.java.
References de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripConverter.currentTripFile, de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTrip.generateKeyMap(), de.dlr.ivf.tapas.analyzer.inputfileconverter.TPS_FileReader.getHeaders(), de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripConverter.reader, de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripConverter.trip, de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripConverter.tripFileCounter, and de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripConverter.tripFiles.
Member Function Documentation
convertNextTrip()
boolean de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripConverter.convertNextTrip (StyledDocument console) throws BadLocationException
Wird vom core aufgerufen. bekommt die tripFiles Liste übergeben und holt sich daraus die Zeilen der Tripfiles gibt diese dann an TapasTrip weiter
Parameters
console
Exceptions
BadLocationException
Definition at line 54 of file TapasTripConverter.java.
References de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripConverter.currentTripFile, de.dlr.ivf.tapas.analyzer.inputfileconverter.TPS_FileReader.getFileName(), de.dlr.ivf.tapas.analyzer.inputfileconverter.TPS_FileReader.getRecord(), de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripConverter.reader, de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTrip.setValues(), de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripConverter.trip, de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripConverter.tripFileCounter, and de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripConverter.tripFiles.
Referenced by de.dlr.ivf.tapas.analyzer.inputfileconverter.FileTripReader.TripFileIterator.hasNext().
getTrip()
TapasTrip de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripConverter.getTrip ()
Definition at line 103 of file TapasTripConverter.java.
References de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripConverter.trip.
Referenced by de.dlr.ivf.tapas.analyzer.inputfileconverter.FileTripReader.TripFileIterator.next().
getTripFile()
String de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripConverter.getTripFile ()
Definition at line 111 of file TapasTripConverter.java.
References de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripConverter.currentTripFile.
Referenced by de.dlr.ivf.tapas.analyzer.inputfileconverter.FileTripReader.getSource().
setTrip()
void de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripConverter.setTrip (TapasTrip trip)
Definition at line 107 of file TapasTripConverter.java.
References de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripConverter.trip.
Member Data Documentation
currentTripFile
File de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripConverter.currentTripFile = null private
Definition at line 20 of file TapasTripConverter.java.
Referenced by de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripConverter.convertNextTrip(), de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripConverter.getTripFile(), and de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripConverter.TapasTripConverter().
reader
TPS_FileReader de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripConverter.reader = null private
Definition at line 21 of file TapasTripConverter.java.
Referenced by de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripConverter.convertNextTrip(), and de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripConverter.TapasTripConverter().
trip
TapasTrip de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripConverter.trip = null private
Definition at line 22 of file TapasTripConverter.java.
Referenced by de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripConverter.convertNextTrip(), de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripConverter.getTrip(), de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripConverter.setTrip(), and de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripConverter.TapasTripConverter().
tripFileCounter
int de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripConverter.tripFileCounter private
Definition at line 23 of file TapasTripConverter.java.
Referenced by de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripConverter.convertNextTrip(), and de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripConverter.TapasTripConverter().
tripFiles
final List<File> de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripConverter.tripFiles private
Definition at line 24 of file TapasTripConverter.java.
Referenced by de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripConverter.convertNextTrip(), and de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripConverter.TapasTripConverter().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/inputfileconverter/TapasTripConverter.java