TAPAS: de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.TripIterator Class Reference
de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.TripIterator Class Reference
Public Member Functions
TripIterator (String simulation, String hhkey, String schema, String region, Set< Integer > acceptedTAZs, String trip_table, TPS_DB_Connector connection, boolean verbose) throws SQLException, ClassNotFoundException, IOException
String getSource ()
boolean hasNext ()
TapasTrip next ()
void remove ()
void run ()
Private Member Functions
void close ()
Private Attributes
final BlockingQueue< TapasTrip > q = new ArrayBlockingQueue<>(QUEUE_SIZE)
final Thread fetcherThread
final DBTripFetcher tripFetcher
final Set< Integer > acceptedTAZs
TapasTrip nextItem = null
Detailed Description
Definition at line 612 of file DBTripReader.java.
Constructor & Destructor Documentation
TripIterator()
de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.TripIterator.TripIterator (String simulation, String hhkey, String schema, String region, Set< Integer > acceptedTAZs, String trip_table, TPS_DB_Connector connection, boolean verbose) throws SQLException, ClassNotFoundException, IOException
Definition at line 623 of file DBTripReader.java.
References de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.TripIterator.acceptedTAZs, de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.TripIterator.fetcherThread, de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.TripIterator.q, de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.region, and de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.TripIterator.tripFetcher.
Member Function Documentation
close()
void de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.TripIterator.close () private
Definition at line 636 of file DBTripReader.java.
References de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.close(), and de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.TripIterator.tripFetcher.
Referenced by de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.close(), de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.TripIterator.hasNext(), and de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.TripIterator.next().
getSource()
String de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.TripIterator.getSource ()
Definition at line 640 of file DBTripReader.java.
References de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.getSource(), and de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.TripIterator.tripFetcher.
Referenced by de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.getSource().
hasNext()
boolean de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.TripIterator.hasNext ()
Definition at line 644 of file DBTripReader.java.
References de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.TripIterator.acceptedTAZs, de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.TripIterator.close(), de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.cntTrips, de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTrip.getBez92Arr(), de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTrip.getBez92Dep(), de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.TripIterator.nextItem, de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.POISON_INSTANCE, and de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.TripIterator.q.
next()
TapasTrip de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.TripIterator.next ()
Definition at line 665 of file DBTripReader.java.
References de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.TripIterator.close(), de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.cntTrips, de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.TripIterator.nextItem, and de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.TripIterator.q.
remove()
void de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.TripIterator.remove ()
Definition at line 682 of file DBTripReader.java.
run()
void de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.TripIterator.run ()
Definition at line 698 of file DBTripReader.java.
References de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.TripIterator.fetcherThread.
Member Data Documentation
acceptedTAZs
final Set<Integer> de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.TripIterator.acceptedTAZs private
Definition at line 619 of file DBTripReader.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.TripIterator.hasNext(), and de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.TripIterator.TripIterator().
fetcherThread
final Thread de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.TripIterator.fetcherThread private
Definition at line 616 of file DBTripReader.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.TripIterator.run(), and de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.TripIterator.TripIterator().
nextItem
TapasTrip de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.TripIterator.nextItem = null private
Definition at line 621 of file DBTripReader.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.TripIterator.hasNext(), and de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.TripIterator.next().
q
final BlockingQueue<TapasTrip> de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.TripIterator.q = new ArrayBlockingQueue<>(QUEUE_SIZE) private
Definition at line 614 of file DBTripReader.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.TripIterator.hasNext(), de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.TripIterator.next(), and de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.TripIterator.TripIterator().
tripFetcher
final DBTripFetcher de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.TripIterator.tripFetcher private
Definition at line 617 of file DBTripReader.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.TripIterator.close(), de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.TripIterator.getSource(), and de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.TripIterator.TripIterator().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/tum/databaseConnector/DBTripReader.java