TAPAS: de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset Class Reference
de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset Class Reference
Classes
enum Series
Public Member Functions
ModalSplitChartDataset (ArrayList< ModalSplitData > data)
int getDataSeries ()
DomainOrder getDomainOrder ()
int getItemCount (int series)
String getLabel (int item)
Mode getMode (int item)
Quality getQuality (int item)
int getSeriesCount ()
Comparable getSeriesKey (int series)
Number getX (int series, int item)
double getXValue (int series, int item)
Number getY (int series, int item)
double getYValue (int series, int item)
boolean isDataSeries (int series)
Private Member Functions
void addGEH (ArrayList< ModalSplitData > data)
void addOptimal (ArrayList< ModalSplitData > data)
Private Attributes
final CategoryCombination ccDummy = new CategoryCombination(Mode.BIKE)
final EnumMap< Series, ArrayList< ModalSplitData > > seriesCollection = new EnumMap<>(Series.class)
Static Private Attributes
static final long serialVersionUID = 7190643396627027541L
Detailed Description
Definition at line 21 of file ModalSplitChartDataset.java.
Constructor & Destructor Documentation
ModalSplitChartDataset()
de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.ModalSplitChartDataset (ArrayList< ModalSplitData > data)
Definition at line 28 of file ModalSplitChartDataset.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.addGEH(), de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.addOptimal(), de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.Series.DATA, de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitData.getReference(), and de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.seriesCollection.
Member Function Documentation
addGEH()
void de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.addGEH (ArrayList< ModalSplitData > data) private
Definition at line 36 of file ModalSplitChartDataset.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.ccDummy, de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.Series.GEH5_HIGH, de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.Series.GEH5_LOW, and de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.seriesCollection.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.ModalSplitChartDataset().
addOptimal()
void de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.addOptimal (ArrayList< ModalSplitData > data) private
Definition at line 51 of file ModalSplitChartDataset.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.ccDummy, de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.Series.OPTIMAL, and de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.seriesCollection.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.ModalSplitChartDataset().
getDataSeries()
int de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.getDataSeries ()
Definition at line 58 of file ModalSplitChartDataset.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.Series.DATA.
getDomainOrder()
DomainOrder de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.getDomainOrder ()
Definition at line 63 of file ModalSplitChartDataset.java.
getItemCount()
int de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.getItemCount (int series)
Definition at line 68 of file ModalSplitChartDataset.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.Series.getById(), and de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.seriesCollection.
getLabel()
String de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.getLabel (int item)
Definition at line 72 of file ModalSplitChartDataset.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.Series.DATA, and de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.seriesCollection.
getMode()
Mode de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.getMode (int item)
Definition at line 76 of file ModalSplitChartDataset.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.Series.DATA, and de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.seriesCollection.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.ModalSplitRenderer.getItemShape().
getQuality()
Quality de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.getQuality (int item)
Definition at line 80 of file ModalSplitChartDataset.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.Series.DATA, and de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.seriesCollection.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.ModalSplitRenderer.getItemPaint().
getSeriesCount()
int de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.getSeriesCount ()
Definition at line 85 of file ModalSplitChartDataset.java.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.ModalSplitRenderer.ModalSplitRenderer().
getSeriesKey()
Comparable de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.getSeriesKey (int series)
Definition at line 91 of file ModalSplitChartDataset.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.Series.getById().
getX()
Number de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.getX (int series, int item)
Definition at line 96 of file ModalSplitChartDataset.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.getXValue().
getXValue()
double de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.getXValue (int series, int item)
Definition at line 101 of file ModalSplitChartDataset.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.Series.getById(), and de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.seriesCollection.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.getX().
getY()
Number de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.getY (int series, int item)
Definition at line 106 of file ModalSplitChartDataset.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.getYValue().
getYValue()
double de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.getYValue (int series, int item)
Definition at line 111 of file ModalSplitChartDataset.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.Series.getById(), and de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.seriesCollection.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.getY().
isDataSeries()
boolean de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.isDataSeries (int series)
Definition at line 115 of file ModalSplitChartDataset.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.Series.DATA.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.ModalSplitToolTipGenerator.generateToolTip(), de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.ModalSplitRenderer.getItemOutlinePaint(), de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.ModalSplitRenderer.getItemPaint(), de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.ModalSplitRenderer.getItemShape(), and de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.ModalSplitRenderer.ModalSplitRenderer().
Member Data Documentation
ccDummy
final CategoryCombination de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.ccDummy = new CategoryCombination(Mode.BIKE) private
Definition at line 25 of file ModalSplitChartDataset.java.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.addGEH(), and de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.addOptimal().
serialVersionUID
final long de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.serialVersionUID = 7190643396627027541L static private
Definition at line 23 of file ModalSplitChartDataset.java.
seriesCollection
final EnumMap<Series, ArrayList<ModalSplitData> > de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.seriesCollection = new EnumMap<>(Series.class) private
Definition at line 26 of file ModalSplitChartDataset.java.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.addGEH(), de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.addOptimal(), de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.getItemCount(), de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.getLabel(), de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.getMode(), de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.getQuality(), de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.getXValue(), de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.getYValue(), and de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.ModalSplitChartDataset().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/runtime/client/Graphics/ModalSplitChart/ModalSplitChartDataset.java