TAPAS: de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyTextWriter Class Reference
de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyTextWriter Class Reference
Public Member Functions
LegacyTextWriter (String file)
void process (RegionAnalyzer ra)
Private Member Functions
void processTUM (RegionAnalyzer results, PrintStream ps)
Static Private Member Functions
static String perc (double p, double n)
static double saveDiv (double n, double d)
Private Attributes
final String file
Detailed Description
Definition at line 17 of file LegacyTextWriter.java.
Constructor & Destructor Documentation
LegacyTextWriter()
de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyTextWriter.LegacyTextWriter (String file)
Definition at line 21 of file LegacyTextWriter.java.
References de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyTextWriter.file.
Member Function Documentation
perc()
static String de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyTextWriter.perc (double p, double n) static private
Returns
p/n*100 as a String with 4 decimal places
Definition at line 28 of file LegacyTextWriter.java.
References de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyTextWriter.saveDiv().
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyTextWriter.processTUM().
process()
void de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyTextWriter.process (RegionAnalyzer ra)
Definition at line 41 of file LegacyTextWriter.java.
References de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyTextWriter.file, and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyTextWriter.processTUM().
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.finish().
processTUM()
void de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyTextWriter.processTUM (RegionAnalyzer results, PrintStream ps) private
Definition at line 59 of file LegacyTextWriter.java.
References de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategory.CAT_1, de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.DistanceCategory, de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.Job, de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.Mode, de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyTextWriter.perc(), de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.PersonGroup, de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.PersonGroup.PG_1, de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.PersonGroup.PG_12, de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.RegionCode.REGION_0, de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.RegionCode, de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyTextWriter.saveDiv(), de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.TripIntention.TRIP_31, and de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.TripIntention.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyTextWriter.process().
saveDiv()
static double de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyTextWriter.saveDiv (double n, double d) static private
Parameters
n
d
Returns
0.0 if d == 0 and n/d else
Definition at line 37 of file LegacyTextWriter.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyTextWriter.perc(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyTextWriter.processTUM().
Member Data Documentation
file
final String de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyTextWriter.file private
Definition at line 19 of file LegacyTextWriter.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyTextWriter.LegacyTextWriter(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyTextWriter.process().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/tum/regionanalyzer/LegacyTextWriter.java