TAPAS: de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI Class Reference
de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI Class Reference
Classes
class ConfigurationTable
class ConfigurationTableRenderer
class FileTargetListener
class JRadioButtonEditor
class JRadioButtonRenderer
Public Member Functions
TPS_ParameterFileConverterGUI (TPS_ParameterClass parameterClass)
void show ()
String showModal (final JFrame parent, String simKey)
Static Public Member Functions
static void main (String[] args)
Private Member Functions
String checkSchema (Map< String, String > configMap, String param)
String chooseSimulation (Connection con) throws SQLException
void fill (SortedMap< String, String > map)
void generateTemporaryParametersInMap (Map< String, String > configMap2)
SortedMap< String, String > getDefaultParams ()
String getNewSimKey ()
void init ()
int insert (String key, ParamType type, int row)
boolean isSimulationStartedAlready (Connection con) throws SQLException
void load (File file, SortedMap< String, String > map, int column, boolean loadParents) throws IOException
void loadConfigFromDatabase ()
void readClientProperties ()
void revertTemporaryParametersInMap (Map< String, String > configMap2)
void saveConfigInDatabase ()
void setFilename (File file, JTextField field, boolean xls)
void updateConfigParamsInEnum ()
void updateTable (Map< String, String > map, int column)
Private Attributes
final SortedMap< String, String > configMap = new TreeMap<>()
final SortedMap< String, String > defaultMap = new TreeMap<>()
final JFrame frame
final String[] header = new String[]{"Key", "Default Value", "", "Config Value", ""}
final ConfigurationTable table
String mSimKey
ClientControlProperties mClientControlProperties
final TPS_ParameterClass parameterClass
File tapasNetworkDirectory
Detailed Description
Definition at line 41 of file TPS_ParameterFileConverterGUI.java.
Constructor & Destructor Documentation
TPS_ParameterFileConverterGUI()
de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.TPS_ParameterFileConverterGUI (TPS_ParameterClass parameterClass)
Definition at line 56 of file TPS_ParameterFileConverterGUI.java.
References de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.header, de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.init(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.parameterClass, and de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.readClientProperties().
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.main().
Member Function Documentation
checkSchema()
String de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.checkSchema (Map< String, String > configMap, String param) private
Checks if the given ParamString has the correct db-schema format, which means, it should end with a dot.
Parameters
param The parameter to check
Definition at line 89 of file TPS_ParameterFileConverterGUI.java.
References de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.configMap.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.generateTemporaryParametersInMap().
chooseSimulation()
String de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.chooseSimulation (Connection con) throws SQLException private
Definition at line 98 of file TPS_ParameterFileConverterGUI.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_SIMULATION_PARAMETERS, de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.frame, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), and de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.mSimKey.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.loadConfigFromDatabase().
fill()
void de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.fill (SortedMap< String, String > map) private
Definition at line 118 of file TPS_ParameterFileConverterGUI.java.
References de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isDefined().
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.load().
generateTemporaryParametersInMap()
void de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.generateTemporaryParametersInMap (Map< String, String > configMap2) private
Definition at line 140 of file TPS_ParameterFileConverterGUI.java.
References de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.checkSchema().
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.loadConfigFromDatabase().
getDefaultParams()
SortedMap<String, String> de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.getDefaultParams () private
Definition at line 154 of file TPS_ParameterFileConverterGUI.java.
References de.dlr.ivf.tapas.util.parameters.ParamFlagClass.getPreset(), de.dlr.ivf.tapas.util.parameters.ParamStringClass.getPreset(), de.dlr.ivf.tapas.util.parameters.ParamValueClass.getPreset(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.paramFlagClass, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.paramStringClass, and de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.paramValueClass.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.loadConfigFromDatabase().
getNewSimKey()
String de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.getNewSimKey () private
Definition at line 174 of file TPS_ParameterFileConverterGUI.java.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.saveConfigInDatabase().
init()
void de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.init () private
Definition at line 186 of file TPS_ParameterFileConverterGUI.java.
References de.dlr.ivf.tapas.tools.fileModifier.persistence.AbstractTPS_ParameterDAO.addAdditionalParameter(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.configMap, de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.defaultMap, de.dlr.ivf.tapas.util.parameters.ParamString.FILE_PARENT_PROPERTIES, de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.frame, de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.ConfigurationTable.initTableColum(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.insert(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.load(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.loadConfigFromDatabase(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.parameterClass, de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.saveConfigInDatabase(), de.dlr.ivf.tapas.tools.fileModifier.persistence.AbstractTPS_ParameterDAO.setFile(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.setFilename(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.setValue(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.table, de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.updateConfigParamsInEnum(), de.dlr.ivf.tapas.tools.fileModifier.persistence.TPS_ParameterCSVDAO.writeParameter(), and de.dlr.ivf.tapas.tools.fileModifier.persistence.TPS_ParameterXLSDAO.writeParameter().
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.TPS_ParameterFileConverterGUI().
insert()
int de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.insert (String key, ParamType type, int row) private
Definition at line 433 of file TPS_ParameterFileConverterGUI.java.
References de.dlr.ivf.tapas.util.parameters.ParamType.EXEC, de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.header, de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.table, de.dlr.ivf.tapas.util.parameters.ParamType.TMP, and type.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.init().
isSimulationStartedAlready()
boolean de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.isSimulationStartedAlready (Connection con) throws SQLException private
Definition at line 446 of file TPS_ParameterFileConverterGUI.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_SIMULATIONS, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), and de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.mSimKey.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.saveConfigInDatabase().
load()
void de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.load (File file, SortedMap< String, String > map, int column, boolean loadParents) throws IOException private
Definition at line 466 of file TPS_ParameterFileConverterGUI.java.
References de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.fill(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.loadRuntimeParameters(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.loadSingleParameterFile(), de.dlr.ivf.tapas.tools.fileModifier.persistence.TPS_ParameterPropertiesDAO.readParameter(), de.dlr.ivf.tapas.tools.fileModifier.persistence.AbstractTPS_ParameterDAO.setFile(), and de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.updateTable().
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.FileTargetListener.drop(), and de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.init().
loadConfigFromDatabase()
void de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.loadConfigFromDatabase () private
Definition at line 487 of file TPS_ParameterFileConverterGUI.java.
References de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.chooseSimulation(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.configMap, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_SIMULATION_PARAMETERS, de.dlr.ivf.tapas.util.parameters.ParamString.FILE_WORKING_DIRECTORY, de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.frame, de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.generateTemporaryParametersInMap(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.getDefaultParams(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.mSimKey, de.dlr.ivf.tapas.util.parameters.ParamString.RUN_IDENTIFIER, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.setString(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.tapasNetworkDirectory, and de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.updateTable().
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.init(), and de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.showModal().
main()
static void de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.main (String[] args) static
Definition at line 71 of file TPS_ParameterFileConverterGUI.java.
References de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.TPS_ParameterFileConverterGUI().
readClientProperties()
void de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.readClientProperties () private
Definition at line 539 of file TPS_ParameterFileConverterGUI.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_PASSWORD, de.dlr.ivf.tapas.util.parameters.ParamString.DB_USER, de.dlr.ivf.tapas.util.parameters.ParamString.FILE_WORKING_DIRECTORY, de.dlr.ivf.tapas.runtime.util.ClientControlProperties.get(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isDefined(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.loadRuntimeParameters(), de.dlr.ivf.tapas.runtime.util.ClientControlProperties.ClientControlPropKey.LOGIN_CONFIG, de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.mClientControlProperties, de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.parameterClass, de.dlr.ivf.tapas.runtime.util.ClientControlProperties.set(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.setString(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.SIM_DIR, de.dlr.ivf.tapas.runtime.util.ClientControlProperties.ClientControlPropKey.TAPAS_DIR_LINUX, de.dlr.ivf.tapas.runtime.util.ClientControlProperties.ClientControlPropKey.TAPAS_DIR_WIN, and de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.tapasNetworkDirectory.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.TPS_ParameterFileConverterGUI().
revertTemporaryParametersInMap()
void de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.revertTemporaryParametersInMap (Map< String, String > configMap2) private
Definition at line 568 of file TPS_ParameterFileConverterGUI.java.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.saveConfigInDatabase().
saveConfigInDatabase()
void de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.saveConfigInDatabase () private
Definition at line 579 of file TPS_ParameterFileConverterGUI.java.
References de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.frame, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.getNewSimKey(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.isSimulationStartedAlready(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.mSimKey, de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.revertTemporaryParametersInMap(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.updateConfigParamsInEnum(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.updateInDB(), and de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.writeToDB().
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.init().
setFilename()
void de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.setFilename (File file, JTextField field, boolean xls) private
Definition at line 610 of file TPS_ParameterFileConverterGUI.java.
References name.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.FileTargetListener.drop(), and de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.init().
show()
void de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.show ()
Definition at line 620 of file TPS_ParameterFileConverterGUI.java.
showModal()
String de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.showModal (final JFrame parent, String simKey)
Zeigt ein Fenster zum Anzeigen der Config fr den bergebenen Simulationskey. Zurckgegeben wird der Simulationskey, der zuletzt bearbeitet wurde, so dass diese Config in dem Parent-Frame angezeigt werden kann. Die nderungen die an der Config vorgenommen wurden sind in den Enums ParamFlag, ParamValue und ParamString gespeichert. Sollte ein Simulationskey zurckgegeben werden, der vorher noch nicht vorhanden war, sollte daraus eine neue Simulation gestartet werden.
Parameters
parent
simKey
Returns
Definition at line 634 of file TPS_ParameterFileConverterGUI.java.
References de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.frame, de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.loadConfigFromDatabase(), and de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.mSimKey.
updateConfigParamsInEnum()
void de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.updateConfigParamsInEnum () private
Definition at line 659 of file TPS_ParameterFileConverterGUI.java.
References de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.table.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.init(), and de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.saveConfigInDatabase().
updateTable()
void de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.updateTable (Map< String, String > map, int column) private
Definition at line 669 of file TPS_ParameterFileConverterGUI.java.
References de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.ConfigurationTable.setValueAt(), and de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.table.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.load(), and de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.loadConfigFromDatabase().
Member Data Documentation
configMap
final SortedMap<String, String> de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.configMap = new TreeMap<>() private
Definition at line 46 of file TPS_ParameterFileConverterGUI.java.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.checkSchema(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.FileTargetListener.drop(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.init(), and de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.loadConfigFromDatabase().
defaultMap
final SortedMap<String, String> de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.defaultMap = new TreeMap<>() private
Definition at line 47 of file TPS_ParameterFileConverterGUI.java.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.FileTargetListener.drop(), and de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.init().
frame
final JFrame de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.frame private
Definition at line 48 of file TPS_ParameterFileConverterGUI.java.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.chooseSimulation(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.FileTargetListener.drop(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.init(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.loadConfigFromDatabase(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.saveConfigInDatabase(), and de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.showModal().
header
final String [] de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.header = new String[]{"Key", "Default Value", "", "Config Value", ""} private
Definition at line 49 of file TPS_ParameterFileConverterGUI.java.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.insert(), and de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.TPS_ParameterFileConverterGUI().
mClientControlProperties
ClientControlProperties de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.mClientControlProperties private
Definition at line 52 of file TPS_ParameterFileConverterGUI.java.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.readClientProperties().
mSimKey
String de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.mSimKey private
Definition at line 51 of file TPS_ParameterFileConverterGUI.java.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.chooseSimulation(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.isSimulationStartedAlready(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.loadConfigFromDatabase(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.saveConfigInDatabase(), and de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.showModal().
parameterClass
final TPS_ParameterClass de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.parameterClass private
Definition at line 53 of file TPS_ParameterFileConverterGUI.java.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.init(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.readClientProperties(), and de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.TPS_ParameterFileConverterGUI().
table
final ConfigurationTable de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.table private
Definition at line 50 of file TPS_ParameterFileConverterGUI.java.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.FileTargetListener.drop(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.ConfigurationTableRenderer.getTableCellRendererComponent(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.JRadioButtonRenderer.getTableCellRendererComponent(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.init(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.ConfigurationTable.initTableColum(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.insert(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.updateConfigParamsInEnum(), and de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.updateTable().
tapasNetworkDirectory
File de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.tapasNetworkDirectory private
Definition at line 54 of file TPS_ParameterFileConverterGUI.java.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.loadConfigFromDatabase(), and de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.readClientProperties().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/fileModifier/TPS_ParameterFileConverterGUI.java