TAPAS: de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader Class Reference
de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader Class Reference
Public Member Functions
CalibrationResultsReader (String simkey) throws IOException, ClassNotFoundException
HashMap< CategoryCombination, Double > getAbsoluteSplit (Categories... categories)
long getCntTrips (Enum... categories)
long getCntTrips ()
HashMap< Mode, Double > getModalSplit (Enum... categories)
HashMap< Mode, Double > getModalSplit ()
Static Public Member Functions
static void main (String[] args) throws ClassNotFoundException, IOException
static void validate (Enum... categories)
Private Member Functions
String buildGroupClause (Categories... categories)
String buildWhereClause (Enum... categories)
Private Attributes
final TPS_DB_Connector dbCon
final String simkey
Detailed Description
This class provides an interface to the public table 'calibration_results'. It provides simple methods to retrieve modal splits.
Author
boec_pa
Definition at line 30 of file CalibrationResultsReader.java.
Constructor & Destructor Documentation
CalibrationResultsReader()
de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader.CalibrationResultsReader (String simkey) throws IOException, ClassNotFoundException
The constructor tries to connect to the database.
Parameters
simkey
Exceptions
IOException if the connection could not be established.
ClassNotFoundException
Definition at line 42 of file CalibrationResultsReader.java.
References de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader.dbCon, de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.getRuntimeFile(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.loadRuntimeParameters(), and de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader.simkey.
Referenced by de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader.main().
Member Function Documentation
buildGroupClause()
String de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader.buildGroupClause (Categories... categories) private
Definition at line 79 of file CalibrationResultsReader.java.
References categories.
Referenced by de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader.getAbsoluteSplit().
buildWhereClause()
String de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader.buildWhereClause (Enum... categories) private
Definition at line 92 of file CalibrationResultsReader.java.
References categories.
Referenced by de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader.getCntTrips(), and de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader.getModalSplit().
getAbsoluteSplit()
HashMap<CategoryCombination, Double> de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader.getAbsoluteSplit (Categories... categories)
Returns the number of counts for all combinations in the given category combination.
Parameters
categories
Returns
Definition at line 114 of file CalibrationResultsReader.java.
References de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader.buildGroupClause(), categories, de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection(), and de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader.simkey.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDBFetcher.getModalSplitData(), de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader.main(), and de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDatasetDBFetcher.makeQSChart().
getCntTrips() [1/2]
long de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader.getCntTrips ()
Returns the total number of trips in the given run.
Returns
-1 if the connection to database fails.
Definition at line 175 of file CalibrationResultsReader.java.
References de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection(), and de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader.simkey.
getCntTrips() [2/2]
long de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader.getCntTrips (Enum... categories)
Returns the number of trips within the given category combination.
Parameters
categories
Returns
-1 if the connection to database fails.
Definition at line 151 of file CalibrationResultsReader.java.
References de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader.buildWhereClause(), categories, de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection(), and de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader.simkey.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDBFetcher.getModalSplitData(), and de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDatasetDBFetcher.makeQSChart().
getModalSplit() [1/2]
HashMap<Mode, Double> de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader.getModalSplit ()
Returns the modal split for the given run.
Definition at line 245 of file CalibrationResultsReader.java.
getModalSplit() [2/2]
HashMap<Mode, Double> de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader.getModalSplit (Enum... categories)
This method creates a modal split along some categories (or none). An example would be the modal split of shopping in 3-5 km. It returns the percentage of all trips (count) in the given category for each mode.
Parameters
categories may be a combination of elements of PersonGroup, TripIntention and DistanceCategory (or DistanceCategoryDefault). Contradictory elements will result in empty maps.
Returns
null if the connection to the database went wrong.
Exceptions
IllegalArgumentException if at least one of the categories are not valid or not suitable for modal splits.
Definition at line 206 of file CalibrationResultsReader.java.
References de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader.buildWhereClause(), categories, de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection(), de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader.simkey, and de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader.validate().
Referenced by de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader.main().
main()
static void de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader.main (String[] args) throws ClassNotFoundException, IOException static
For testing purposes only
Definition at line 56 of file CalibrationResultsReader.java.
References de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader.CalibrationResultsReader(), de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader.getAbsoluteSplit(), and de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader.getModalSplit().
validate()
static void de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader.validate (Enum... categories) static
Checks if categories are valid.
Returns
Exceptions
IllegalArgumentException if the are not.
Definition at line 73 of file CalibrationResultsReader.java.
References categories.
Referenced by de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader.getModalSplit().
Member Data Documentation
dbCon
final TPS_DB_Connector de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader.dbCon private
Definition at line 32 of file CalibrationResultsReader.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader.CalibrationResultsReader(), de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader.getAbsoluteSplit(), de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader.getCntTrips(), and de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader.getModalSplit().
simkey
final String de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader.simkey private
Definition at line 33 of file CalibrationResultsReader.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader.CalibrationResultsReader(), de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader.getAbsoluteSplit(), de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader.getCntTrips(), and de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader.getModalSplit().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/tum/results/CalibrationResultsReader.java