TAPAS: de.dlr.ivf.tapas.persistence.io.TPS_FileConsumer Class Reference
de.dlr.ivf.tapas.persistence.io.TPS_FileConsumer Class Reference abstract
Public Member Functions
TPS_FileConsumer (String fileName)
TPS_FileConsumer (String fileName, boolean hasHeader)
TPS_FileConsumer (String fileName, boolean hasHeader, int recordLength)
TPS_FileConsumer (String fileName, int recordLength)
int getRecordLength ()
void setRecordLength (int recordLength)
void start ()
Protected Member Functions
abstract void consume (String[] record, int lineCount)
void finish (int lineCount)
String getFileName ()
String getShortFileName ()
void init (String[] headers)
Private Member Functions
void consumeFile (boolean hasHeader) throws Exception
String createException (SortedMap< Integer, Exception > exMap)
Private Attributes
final boolean hasHeader
final TPS_FileReader reader
int recordLength
Detailed Description
This class provides basic behaviour for reading a file. It can open the file, read the header and all lines and close the file automatically. There are three main methods you can override. The init() and finish() methods are called at the beginning respectively at the end of the reading process. The abstract method consume you have to implement. It is called for each line read from the file.
Author
mark_ma
Definition at line 33 of file TPS_FileConsumer.java.
Constructor & Destructor Documentation
TPS_FileConsumer() [1/4]
de.dlr.ivf.tapas.persistence.io.TPS_FileConsumer.TPS_FileConsumer (String fileName)
Calls this(fileName, true);
Parameters
fileName name of the file to read
Definition at line 56 of file TPS_FileConsumer.java.
TPS_FileConsumer() [2/4]
de.dlr.ivf.tapas.persistence.io.TPS_FileConsumer.TPS_FileConsumer (String fileName, boolean hasHeader)
Calls this (fileName, hasHeader, -1);
Parameters
fileName name of the file to read
hasHeader flag if the file has a header
Definition at line 66 of file TPS_FileConsumer.java.
TPS_FileConsumer() [3/4]
de.dlr.ivf.tapas.persistence.io.TPS_FileConsumer.TPS_FileConsumer (String fileName, boolean hasHeader, int recordLength)
The constructor builds a TPS_FileReader and initaliases the member variables.
Parameters
fileName name of the file to read
hasHeader flag if the file has a header
recordLength length of the record, values smaller than zero determines that the length is not specified
Definition at line 77 of file TPS_FileConsumer.java.
TPS_FileConsumer() [4/4]
de.dlr.ivf.tapas.persistence.io.TPS_FileConsumer.TPS_FileConsumer (String fileName, int recordLength)
Calls this(fileName, true, recordLength);
Parameters
fileName name of the file to read
recordLength length of the record, values smaller than zero determines that the length is not specified
Definition at line 93 of file TPS_FileConsumer.java.
Member Function Documentation
consume()
abstract void de.dlr.ivf.tapas.persistence.io.TPS_FileConsumer.consume (String[] record, int lineCount) abstract protected
This method is called for each line of the file. It should consume the line and store all information in memory.
Parameters
record the current line (record) of the file
lineCount the current line number
consumeFile()
void de.dlr.ivf.tapas.persistence.io.TPS_FileConsumer.consumeFile (boolean hasHeader) throws Exception private
This method consumes the complete file. At the beginning it calls the init() method. For each line the consume() method is called. At least the finish() method is called. If there occur exceptions they are stored until an amuont of ten and then they are thrown as one single exception.
Parameters
hasHeader flag if there exsits a header
Exceptions
Exception This method can throw any Exception
Definition at line 113 of file TPS_FileConsumer.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.FINE, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.INFO, de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), de.dlr.ivf.tapas.log.TPS_Logger.log(), and de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.WARN.
createException()
String de.dlr.ivf.tapas.persistence.io.TPS_FileConsumer.createException (SortedMap< Integer, Exception > exMap) private
All stored exceptions are combined to one single exception
Parameters
exMap all stored exceptions
Returns
one single exception
Definition at line 181 of file TPS_FileConsumer.java.
finish()
void de.dlr.ivf.tapas.persistence.io.TPS_FileConsumer.finish (int lineCount) protected
This method is called after the last line of the file is consumed
Parameters
lineCount count of all read lines
Definition at line 199 of file TPS_FileConsumer.java.
getFileName()
String de.dlr.ivf.tapas.persistence.io.TPS_FileConsumer.getFileName () protected
Returns
filename
Definition at line 206 of file TPS_FileConsumer.java.
References de.dlr.ivf.tapas.persistence.io.TPS_FileReader.getFileName().
getRecordLength()
int de.dlr.ivf.tapas.persistence.io.TPS_FileConsumer.getRecordLength ()
Returns
length of a record, values smaller than zero determines that the length is not specified
Definition at line 213 of file TPS_FileConsumer.java.
getShortFileName()
String de.dlr.ivf.tapas.persistence.io.TPS_FileConsumer.getShortFileName () protected
Returns
local filename without path
Definition at line 229 of file TPS_FileConsumer.java.
References de.dlr.ivf.tapas.persistence.io.TPS_FileReader.getFileName().
init()
void de.dlr.ivf.tapas.persistence.io.TPS_FileConsumer.init (String[] headers) protected
This method is called before the first line of the file is read. When there exists a header it is the first argument otherwise it is null.
Parameters
headers the header of the file
Definition at line 239 of file TPS_FileConsumer.java.
setRecordLength()
void de.dlr.ivf.tapas.persistence.io.TPS_FileConsumer.setRecordLength (int recordLength)
Sets the record length.
Parameters
recordLength record length, values smaller than zero determines that the length is not specified
Definition at line 222 of file TPS_FileConsumer.java.
start()
void de.dlr.ivf.tapas.persistence.io.TPS_FileConsumer.start ()
Starts the reading of the file. This method catches all exceptions and log them.
Definition at line 246 of file TPS_FileConsumer.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, and de.dlr.ivf.tapas.log.TPS_Logger.log().
Member Data Documentation
hasHeader
final boolean de.dlr.ivf.tapas.persistence.io.TPS_FileConsumer.hasHeader private
Flag determines whether the file has a header or not
Definition at line 38 of file TPS_FileConsumer.java.
reader
final TPS_FileReader de.dlr.ivf.tapas.persistence.io.TPS_FileConsumer.reader private
The internal file reader
Definition at line 43 of file TPS_FileConsumer.java.
recordLength
int de.dlr.ivf.tapas.persistence.io.TPS_FileConsumer.recordLength private
The length one record in this file should have. If the record is too short an exception is thrown. If the record is too long a warning is printed
Definition at line 49 of file TPS_FileConsumer.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/persistence/io/TPS_FileConsumer.java