TAPAS: de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.Trip Class Reference
de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.Trip Class Reference
Public Member Functions
Trip (String start, String stop)
String getHeader ()
int getNum ()
void setNum (int num)
String getStart ()
String getStop ()
void incNum ()
String toCSVString ()
Detailed Description
Definition at line 313 of file PTTripProcessorBraunschweig.java.
Constructor & Destructor Documentation
Trip()
de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.Trip.Trip (String start, String stop)
Definition at line 318 of file PTTripProcessorBraunschweig.java.
Member Function Documentation
getHeader()
String de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.Trip.getHeader ()
Definition at line 324 of file PTTripProcessorBraunschweig.java.
References de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.DELIMITER.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.main().
getNum()
int de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.Trip.getNum ()
Returns
the num
Definition at line 333 of file PTTripProcessorBraunschweig.java.
getStart()
String de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.Trip.getStart ()
Returns
the start
Definition at line 351 of file PTTripProcessorBraunschweig.java.
getStop()
String de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.Trip.getStop ()
Returns
the stop
Definition at line 359 of file PTTripProcessorBraunschweig.java.
incNum()
void de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.Trip.incNum ()
Definition at line 363 of file PTTripProcessorBraunschweig.java.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.processTrip().
setNum()
void de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.Trip.setNum (int num)
Parameters
num the num to set
Definition at line 342 of file PTTripProcessorBraunschweig.java.
toCSVString()
String de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.Trip.toCSVString ()
Definition at line 367 of file PTTripProcessorBraunschweig.java.
References de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.DELIMITER, de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.PTStop.getX(), de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.PTStop.getY(), and de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.stopMap.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.main().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/locationallocation/PTTripProcessorBraunschweig.java