TAPAS: de.dlr.ivf.tapas.scheme.TPS_TourPart.TPS_StayHierarchy Class Reference
de.dlr.ivf.tapas.scheme.TPS_TourPart.TPS_StayHierarchy Class Reference
Public Member Functions
TPS_StayHierarchy (TPS_Stay prev, TPS_Stay next)
TPS_Stay getNextStay ()
TPS_Stay getPrevStay ()
String toString (TPS_Stay stay)
Private Attributes
final TPS_Stay nextStay
final TPS_Stay prevStay
Detailed Description
This class provides a stay hierarchy in this tour part. They are sorted by their duration. Each stay has a link to a stay which is the longest one of all stays which are earlier respectively later.
Author
mark_ma
Definition at line 617 of file TPS_TourPart.java.
Constructor & Destructor Documentation
TPS_StayHierarchy()
de.dlr.ivf.tapas.scheme.TPS_TourPart.TPS_StayHierarchy.TPS_StayHierarchy (TPS_Stay prev, TPS_Stay next)
Builds an instance and sets both references.
Parameters
prev
next
Definition at line 637 of file TPS_TourPart.java.
Member Function Documentation
getNextStay()
TPS_Stay de.dlr.ivf.tapas.scheme.TPS_TourPart.TPS_StayHierarchy.getNextStay ()
Returns the next longer stay in this tour part or the first stay at home in the next home part
Returns
the next stay
Definition at line 647 of file TPS_TourPart.java.
Referenced by de.dlr.ivf.tapas.loc.TPS_MultipleTAZRepresentant.getLocationRepresentatives(), de.dlr.ivf.tapas.plan.TPS_LocatedStay.selectLocation(), de.dlr.ivf.tapas.loc.TPS_SelectLocationWeightBased.selectLocationFromChoiceSet(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.selectLocationFromChoiceSet(), and de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes().
getPrevStay()
TPS_Stay de.dlr.ivf.tapas.scheme.TPS_TourPart.TPS_StayHierarchy.getPrevStay ()
Returns the previous longer stay in this tour part or the last stay at home in the next home part
Returns
the previous stay
Definition at line 656 of file TPS_TourPart.java.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.getHierarchizedPreviousStay(), de.dlr.ivf.tapas.loc.TPS_MultipleTAZRepresentant.getLocationRepresentatives(), de.dlr.ivf.tapas.plan.TPS_LocatedStay.selectLocation(), de.dlr.ivf.tapas.loc.TPS_SelectLocationWeightBased.selectLocationFromChoiceSet(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.selectLocationFromChoiceSet(), and de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes().
toString()
String de.dlr.ivf.tapas.scheme.TPS_TourPart.TPS_StayHierarchy.toString (TPS_Stay stay)
Builds a String of this hierarchy element
Parameters
stay the corresponding stay to this hierarchy element
Returns
string of this hierarchy element
Definition at line 666 of file TPS_TourPart.java.
References de.dlr.ivf.tapas.scheme.TPS_Episode.getId().
Member Data Documentation
nextStay
final TPS_Stay de.dlr.ivf.tapas.scheme.TPS_TourPart.TPS_StayHierarchy.nextStay private
This stay indicates the longest stay of all later stays in this tour part or the first stay at home in the next home part if there exist no later stay in the tour part.
Definition at line 623 of file TPS_TourPart.java.
prevStay
final TPS_Stay de.dlr.ivf.tapas.scheme.TPS_TourPart.TPS_StayHierarchy.prevStay private
This stay indicates the longest stay of all previous stays in this tour part or the last stay at home in the previous home part if no earlier stay exist in the tour part.
Definition at line 629 of file TPS_TourPart.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/scheme/TPS_TourPart.java