TAPAS: de.dlr.ivf.tapas.tools.TUM.IntegratedTUM Class Reference
de.dlr.ivf.tapas.tools.TUM.IntegratedTUM Class Reference abstract
Public Member Functions
IntegratedTUM ()
abstract void buildAnalyzerList ()
long getCurrentTripCnt ()
long getTotalTrips ()
boolean setInput (ITumInterface input)
Protected Member Functions
Void doInBackground () throws Exception
void done ()
AnalyzerBase getAnalyzer (Categories c)
void process (List< String > chunks)
Protected Attributes
DefaultMutableTreeNode root = new DefaultMutableTreeNode(new AnalyzerCollection("ROOT"))
Private Member Functions
void defaultAnalyzerList ()
String summary ()
String totalSummary ()
Static Private Member Functions
static String getTime ()
Private Attributes
final String fail = "FAIL"
final String success = "SUCCESS"
final String abort = "ABORTED"
final String time = "TIME"
final String nextsim = "CONTINUE"
final String summary = "SUMMARY"
final String totalsummary = "TOTALSUMMARY"
final String header = "TUM Export started..."
long starttime
long absstarttime
long elapsedtime
long currenttripcnt
long totaltrips
StyledDocument console
TPS_DB_Connector connection
File[] exportfiles
String[] simulations
DBTripReader tripReader
ArrayList< AnalyzerBase > baseAnalyzerList
boolean triptablesuccess = false
Detailed Description
This class handles the integrated TUM-export. Additionally it extends SwingWorker
Input: since the constructor doesn't take any arguments this class gets its input through an ITumInterface interface that must be passed by the setInput(ITumInterface) method.
Work flow:
first a trip table will be created after DBTripReader constructor's call.
then you can access every TapasTrip by its implemented Iterator calling DBTripReader#getIterator().
every single trip can be passed as argument to GeneralAnalyzer#prepare(String, TapasTrip, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass) for evaluation.
finally an excel-export will be done by invoking GeneralAnalyzer#finish(File)
Note: file handling is done outside of this class for example in a customized JFileChooser like SimulationMonitor::tumFileChooser(int).
Thrown exceptions
PSQLException: thrown if IntegratedTUM#cancel(boolean) is invoked during the trip table creation statement and sometimes occurs during cancellation in a GeneralAnalyzer#prepare(String, TapasTrip, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass) call.
IllegalArgumentException: manually thrown by getAnalyzer(Categories) if no AnalyzerBase object that matched the Categories argument was found.
Author
sche_ai
Definition at line 65 of file IntegratedTUM.java.
Constructor & Destructor Documentation
IntegratedTUM()
de.dlr.ivf.tapas.tools.TUM.IntegratedTUM.IntegratedTUM ()
fill a list with all available analyzers
build a collection containing AnalyzerCollections and its AnalyzerBase objects
Definition at line 115 of file IntegratedTUM.java.
Member Function Documentation
buildAnalyzerList()
abstract void de.dlr.ivf.tapas.tools.TUM.IntegratedTUM.buildAnalyzerList () abstract
implementing this method will allow you to set up your own AnalyzerBase combinations wrapped into AnalyzerCollections.
Note: this method doesn't take any parameters, instead IntegratedTUM#root will be filled and can be passed to GeneralAnalyzer#GeneralAnalyzer(DefaultMutableTreeNode, boolean, String)
As an example check StandardTUM that extends this class.
Reimplemented in de.dlr.ivf.tapas.tools.TUM.StandardTUM.
defaultAnalyzerList()
void de.dlr.ivf.tapas.tools.TUM.IntegratedTUM.defaultAnalyzerList () private
fills up baseAnalyzerList
Definition at line 139 of file IntegratedTUM.java.
doInBackground()
Void de.dlr.ivf.tapas.tools.TUM.IntegratedTUM.doInBackground () throws Exception protected
Definition at line 154 of file IntegratedTUM.java.
References de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.addPropertyChangeListener(), de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.close(), de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.description, de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzer.finish(), de.dlr.ivf.tapas.constants.TPS_SettlementSystem.TPS_SettlementSystemType.FORDCP, de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.getIterator(), de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.getString(), de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.getTotal(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzer.init(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzer.prepare(), de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.region, and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzer.setDescription().
done()
void de.dlr.ivf.tapas.tools.TUM.IntegratedTUM.done () protected
Definition at line 277 of file IntegratedTUM.java.
References de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.cancel().
getAnalyzer()
AnalyzerBase de.dlr.ivf.tapas.tools.TUM.IntegratedTUM.getAnalyzer (Categories c) protected
Parameters
c
Returns
AnalyzerBase object belonging to Categories
Exceptions
{
Definition at line 290 of file IntegratedTUM.java.
Referenced by de.dlr.ivf.tapas.tools.TUM.StandardTUM.buildAnalyzerList().
getCurrentTripCnt()
long de.dlr.ivf.tapas.tools.TUM.IntegratedTUM.getCurrentTripCnt ()
Returns
the current trip count that already has been processed
Definition at line 299 of file IntegratedTUM.java.
getTime()
static String de.dlr.ivf.tapas.tools.TUM.IntegratedTUM.getTime () static private
Definition at line 120 of file IntegratedTUM.java.
getTotalTrips()
long de.dlr.ivf.tapas.tools.TUM.IntegratedTUM.getTotalTrips ()
Returns
total trip count
Definition at line 306 of file IntegratedTUM.java.
process()
void de.dlr.ivf.tapas.tools.TUM.IntegratedTUM.process (List< String > chunks) protected
Definition at line 312 of file IntegratedTUM.java.
References de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.getString().
setInput()
boolean de.dlr.ivf.tapas.tools.TUM.IntegratedTUM.setInput (ITumInterface input)
Parameters
input transfer
Definition at line 368 of file IntegratedTUM.java.
References de.dlr.ivf.tapas.tools.TUM.ITumInterface.getConnection(), de.dlr.ivf.tapas.tools.TUM.ITumInterface.getConsole(), de.dlr.ivf.tapas.tools.TUM.ITumInterface.getExportFiles(), and de.dlr.ivf.tapas.tools.TUM.ITumInterface.getSimKeys().
summary()
String de.dlr.ivf.tapas.tools.TUM.IntegratedTUM.summary () private
Returns
string containing information about elapsed time and processed trips of an analyzed simulation
Definition at line 386 of file IntegratedTUM.java.
References de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.getString().
totalSummary()
String de.dlr.ivf.tapas.tools.TUM.IntegratedTUM.totalSummary () private
Returns
string containing information about overall elapsed time
Definition at line 399 of file IntegratedTUM.java.
References de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.getString().
Member Data Documentation
abort
final String de.dlr.ivf.tapas.tools.TUM.IntegratedTUM.abort = "ABORTED" private
Definition at line 72 of file IntegratedTUM.java.
absstarttime
long de.dlr.ivf.tapas.tools.TUM.IntegratedTUM.absstarttime private
Definition at line 86 of file IntegratedTUM.java.
baseAnalyzerList
ArrayList<AnalyzerBase> de.dlr.ivf.tapas.tools.TUM.IntegratedTUM.baseAnalyzerList private
contains all Analyzers
Definition at line 104 of file IntegratedTUM.java.
connection
TPS_DB_Connector de.dlr.ivf.tapas.tools.TUM.IntegratedTUM.connection private
Definition at line 94 of file IntegratedTUM.java.
console
StyledDocument de.dlr.ivf.tapas.tools.TUM.IntegratedTUM.console private
mandatory information from SimulationMonitor passed by setInput(ITumInterface)
Definition at line 93 of file IntegratedTUM.java.
currenttripcnt
long de.dlr.ivf.tapas.tools.TUM.IntegratedTUM.currenttripcnt private
Definition at line 88 of file IntegratedTUM.java.
elapsedtime
long de.dlr.ivf.tapas.tools.TUM.IntegratedTUM.elapsedtime private
Definition at line 87 of file IntegratedTUM.java.
exportfiles
File [] de.dlr.ivf.tapas.tools.TUM.IntegratedTUM.exportfiles private
Definition at line 95 of file IntegratedTUM.java.
fail
final String de.dlr.ivf.tapas.tools.TUM.IntegratedTUM.fail = "FAIL" private
constant strings that influence console behavior and styles in process(List)
Definition at line 70 of file IntegratedTUM.java.
header
final String de.dlr.ivf.tapas.tools.TUM.IntegratedTUM.header = "TUM Export started..." private
Definition at line 77 of file IntegratedTUM.java.
nextsim
final String de.dlr.ivf.tapas.tools.TUM.IntegratedTUM.nextsim = "CONTINUE" private
Definition at line 74 of file IntegratedTUM.java.
root
DefaultMutableTreeNode de.dlr.ivf.tapas.tools.TUM.IntegratedTUM.root = new DefaultMutableTreeNode(new AnalyzerCollection("ROOT")) protected
input parameter for the GeneralAnalyzer
Definition at line 81 of file IntegratedTUM.java.
Referenced by de.dlr.ivf.tapas.tools.TUM.StandardTUM.buildAnalyzerList().
simulations
String [] de.dlr.ivf.tapas.tools.TUM.IntegratedTUM.simulations private
Definition at line 96 of file IntegratedTUM.java.
starttime
long de.dlr.ivf.tapas.tools.TUM.IntegratedTUM.starttime private
these variables will hold values to represent intermediate results
Definition at line 85 of file IntegratedTUM.java.
success
final String de.dlr.ivf.tapas.tools.TUM.IntegratedTUM.success = "SUCCESS" private
Definition at line 71 of file IntegratedTUM.java.
summary
final String de.dlr.ivf.tapas.tools.TUM.IntegratedTUM.summary = "SUMMARY" private
Definition at line 75 of file IntegratedTUM.java.
time
final String de.dlr.ivf.tapas.tools.TUM.IntegratedTUM.time = "TIME" private
Definition at line 73 of file IntegratedTUM.java.
totalsummary
final String de.dlr.ivf.tapas.tools.TUM.IntegratedTUM.totalsummary = "TOTALSUMMARY" private
Definition at line 76 of file IntegratedTUM.java.
totaltrips
long de.dlr.ivf.tapas.tools.TUM.IntegratedTUM.totaltrips private
Definition at line 89 of file IntegratedTUM.java.
tripReader
DBTripReader de.dlr.ivf.tapas.tools.TUM.IntegratedTUM.tripReader private
instance variable for trip reader
Definition at line 100 of file IntegratedTUM.java.
triptablesuccess
boolean de.dlr.ivf.tapas.tools.TUM.IntegratedTUM.triptablesuccess = false private
getting set by IntegratedTUM#tripReader's PropertyChangeListener
Definition at line 108 of file IntegratedTUM.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/TUM/IntegratedTUM.java