TAPAS: de.dlr.ivf.tapas.analyzer.gui.TripChooserPanel Class Reference
de.dlr.ivf.tapas.analyzer.gui.TripChooserPanel Class Reference
Public Member Functions
TripChooserPanel (String title, String initSimulation, StyledDocument console)
TapasTripReader getTripReader ()
boolean isReady ()
Private Attributes
final String title
final StyledDocument console
final DBSimulationChooserPanel dbChooser
final FilesChooser filesChooser
Static Private Attributes
static final long serialVersionUID = 7301753761411077441L
Detailed Description
Definition at line 17 of file TripChooserPanel.java.
Constructor & Destructor Documentation
TripChooserPanel()
de.dlr.ivf.tapas.analyzer.gui.TripChooserPanel.TripChooserPanel (String title, String initSimulation, StyledDocument console)
Definition at line 30 of file TripChooserPanel.java.
References de.dlr.ivf.tapas.analyzer.gui.TripChooserPanel.console, de.dlr.ivf.tapas.analyzer.gui.TripChooserPanel.dbChooser, de.dlr.ivf.tapas.analyzer.gui.TripChooserPanel.filesChooser, and de.dlr.ivf.tapas.analyzer.gui.TripChooserPanel.title.
Member Function Documentation
getTripReader()
TapasTripReader de.dlr.ivf.tapas.analyzer.gui.TripChooserPanel.getTripReader ()
Definition at line 42 of file TripChooserPanel.java.
References de.dlr.ivf.tapas.analyzer.gui.TripChooserPanel.console, de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.createDBTripReader(), de.dlr.ivf.tapas.analyzer.gui.FilesChooser.createFileTripReader(), de.dlr.ivf.tapas.analyzer.gui.TripChooserPanel.dbChooser, de.dlr.ivf.tapas.analyzer.gui.TripChooserPanel.filesChooser, de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.isReady(), and de.dlr.ivf.tapas.analyzer.gui.FilesChooser.isReady().
Referenced by de.dlr.ivf.tapas.analyzer.gui.Control.getTripReader().
isReady()
boolean de.dlr.ivf.tapas.analyzer.gui.TripChooserPanel.isReady ()
Definition at line 56 of file TripChooserPanel.java.
References de.dlr.ivf.tapas.analyzer.gui.TripChooserPanel.dbChooser, de.dlr.ivf.tapas.analyzer.gui.TripChooserPanel.filesChooser, de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.isReady(), and de.dlr.ivf.tapas.analyzer.gui.FilesChooser.isReady().
Referenced by de.dlr.ivf.tapas.analyzer.gui.Control.createAndShowGUI().
Member Data Documentation
console
final StyledDocument de.dlr.ivf.tapas.analyzer.gui.TripChooserPanel.console private
Definition at line 25 of file TripChooserPanel.java.
Referenced by de.dlr.ivf.tapas.analyzer.gui.TripChooserPanel.getTripReader(), and de.dlr.ivf.tapas.analyzer.gui.TripChooserPanel.TripChooserPanel().
dbChooser
final DBSimulationChooserPanel de.dlr.ivf.tapas.analyzer.gui.TripChooserPanel.dbChooser private
Definition at line 27 of file TripChooserPanel.java.
Referenced by de.dlr.ivf.tapas.analyzer.gui.TripChooserPanel.getTripReader(), de.dlr.ivf.tapas.analyzer.gui.TripChooserPanel.isReady(), and de.dlr.ivf.tapas.analyzer.gui.TripChooserPanel.TripChooserPanel().
filesChooser
final FilesChooser de.dlr.ivf.tapas.analyzer.gui.TripChooserPanel.filesChooser private
Definition at line 28 of file TripChooserPanel.java.
Referenced by de.dlr.ivf.tapas.analyzer.gui.TripChooserPanel.getTripReader(), de.dlr.ivf.tapas.analyzer.gui.TripChooserPanel.isReady(), and de.dlr.ivf.tapas.analyzer.gui.TripChooserPanel.TripChooserPanel().
serialVersionUID
final long de.dlr.ivf.tapas.analyzer.gui.TripChooserPanel.serialVersionUID = 7301753761411077441L static private
Definition at line 21 of file TripChooserPanel.java.
title
final String de.dlr.ivf.tapas.analyzer.gui.TripChooserPanel.title private
Definition at line 24 of file TripChooserPanel.java.
Referenced by de.dlr.ivf.tapas.analyzer.gui.TripChooserPanel.TripChooserPanel().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/gui/TripChooserPanel.java