TAPAS: de.dlr.ivf.scripts.PTAnalyzer Class Reference
de.dlr.ivf.scripts.PTAnalyzer Class Reference
Classes
class TAZCounter
Public Member Functions
int numberOfLongDistanceWalkingConnections (double maxWalk)
int numberOfWalkingConnections ()
void printMinMaxAvg (PTNodeField field)
void printMinMaxAvgSpeed (PTNodeField dist, PTNodeField time, double maxSpeed, double minSpeed)
void writeCSVXY (PTNodeField dist, PTNodeField time, double sample, String filename)
Public Member Functions inherited from de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB
TPS_VisumOeVToDB (String loginFile)
TPS_VisumOeVToDB ()
void calcBeelines ()
void calcSumOfTT ()
void calcTTWithoutWaiting (int secPerTransit)
void calcTop3 (double factor)
void clearPTNodes ()
void constantInitialWaiting (int lengthOfWaiting)
void findMissingValues ()
double[][] getMatrixForField (PTNodeField field)
void initTAZIDs (String filename)
void initTAZIDsOMFormat (String filename)
void initTAZIDsVFormat (String filename)
boolean loadTAZ (String table)
void readValues (String filename, PTNodeField field, int maxValue, int minValue)
void readValuesOMFormat (String filename, PTNodeField field, int maxValue, int minValue)
void readValuesVFormat (String filename, PTNodeField field, int maxValue, int minValue)
void removeACTandEGTfromPJT ()
void transformNumOfConnectionToInitialWaiting (int lengthOfSimulation, double A, double E)
void transformUnits ()
Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_BasicConnectionClass ()
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass)
TPS_BasicConnectionClass (String loginFile)
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass, String loginFile)
boolean checkMatrixName (String matrixName)
TPS_ParameterClass getParameters ()
String readParameter (String simKey, String paramKey)
void storeInDB (String matrixName, double[][] matrix, int decimalPlaces)
Static Public Member Functions
static void main (String[] args)
Static Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
static double[][] array1Dto2D (Integer[] matrixVal)
static double[][] array1Dto2D (int[] matrixVal)
static File getRuntimeFile (boolean forceNewFile)
static File getRuntimeFile (String propertyFile, boolean forceNewFile)
static File getRuntimeFile ()
static File getRuntimeFile (String propertyFile)
static int[][] intArray1Dto2D (int[] matrixVal)
static String matrixToSQLArray (double[][] array, int decimalPlaces)
static StringWriter matrixToStringWriterSQL (double[][] array, int decimalPlaces)
Additional Inherited Members
Public Attributes inherited from de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB
HashMap< Integer, TAZ > TAZes = new HashMap<>()
PTNode[][] nodes = null
Protected Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
void finalize ()
Protected Attributes inherited from de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB
HashMap< Integer, Integer > reverseTAZIDMap = new HashMap<>()
Protected Attributes inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_DB_Connector dbCon = null
TPS_ParameterClass parameterClass
Detailed Description
Definition at line 22 of file PTAnalyzer.java.
Member Function Documentation
main()
static void de.dlr.ivf.scripts.PTAnalyzer.main (String[] args) static
Parameters
args
Reimplemented from de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.
Definition at line 28 of file PTAnalyzer.java.
References de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNodeField.ACT, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNodeField.BDH, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.calcBeelines(), de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.calcSumOfTT(), de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.calcTop3(), de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNodeField.EGT, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.initTAZIDs(), de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNodeField.IVT, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNodeField.JRD, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.loadTAZ(), de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNodeField.NTR, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.readValues(), de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNodeField.SUMTT, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNodeField.SWT, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.transformNumOfConnectionToInitialWaiting(), de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.transformUnits(), de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNodeField.TWT, and de.dlr.ivf.scripts.PTAnalyzer.writeCSVXY().
numberOfLongDistanceWalkingConnections()
int de.dlr.ivf.scripts.PTAnalyzer.numberOfLongDistanceWalkingConnections (double maxWalk)
Definition at line 82 of file PTAnalyzer.java.
References de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNode.bld, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNode.idEnd, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNode.idStart, and de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.nodes.
numberOfWalkingConnections()
int de.dlr.ivf.scripts.PTAnalyzer.numberOfWalkingConnections ()
Definition at line 109 of file PTAnalyzer.java.
References de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.nodes.
printMinMaxAvg()
void de.dlr.ivf.scripts.PTAnalyzer.printMinMaxAvg (PTNodeField field)
Definition at line 124 of file PTAnalyzer.java.
References de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.getMatrixForField().
printMinMaxAvgSpeed()
void de.dlr.ivf.scripts.PTAnalyzer.printMinMaxAvgSpeed (PTNodeField dist, PTNodeField time, double maxSpeed, double minSpeed)
Definition at line 142 of file PTAnalyzer.java.
References de.dlr.ivf.scripts.SrVCalculator.TAZ.description, de.dlr.ivf.scripts.SrVCalculator.TAZ.getDistance(), de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.getMatrixForField(), de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.reverseTAZIDMap, de.dlr.ivf.scripts.SrVCalculator.TAZ.taz_id, and de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.TAZes.
writeCSVXY()
void de.dlr.ivf.scripts.PTAnalyzer.writeCSVXY (PTNodeField dist, PTNodeField time, double sample, String filename)
Definition at line 195 of file PTAnalyzer.java.
References de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.getMatrixForField().
Referenced by de.dlr.ivf.scripts.PTAnalyzer.main().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/scripts/PTAnalyzer.java