TAPAS: de.dlr.ivf.tapas.modechoice.TPS_ModeChoiceTree Class Reference
de.dlr.ivf.tapas.modechoice.TPS_ModeChoiceTree Class Reference
Public Member Functions
TPS_ModeChoiceTree ()
TPS_ModeChoiceTree (TPS_Node root)
TPS_Node getDistributionSet (TPS_Plan plan)
TPS_Node getNode (int id)
TPS_Node getRoot ()
void setRoot (TPS_Node root)
String toString ()
String toString (String prefix)
Protected Member Functions
TPS_Node descend (TPS_Plan plan, TPS_Node node)
TPS_Node find (TPS_Node node, int id)
Protected Attributes
TPS_Node root = null
Detailed Description
This tree describes the different specialisations of the mode distributions. At each node there is a different mode distribution stored
Author
mark_ma
Definition at line 23 of file TPS_ModeChoiceTree.java.
Constructor & Destructor Documentation
TPS_ModeChoiceTree() [1/2]
de.dlr.ivf.tapas.modechoice.TPS_ModeChoiceTree.TPS_ModeChoiceTree ()
This constructor builds a mode choice tree without a root
Definition at line 33 of file TPS_ModeChoiceTree.java.
TPS_ModeChoiceTree() [2/2]
de.dlr.ivf.tapas.modechoice.TPS_ModeChoiceTree.TPS_ModeChoiceTree (TPS_Node root)
Builds the encapsulating object and sets the root
Parameters
root
Definition at line 42 of file TPS_ModeChoiceTree.java.
Member Function Documentation
descend()
TPS_Node de.dlr.ivf.tapas.modechoice.TPS_ModeChoiceTree.descend (TPS_Plan plan, TPS_Node node) protected
Recursively searches the mode choice tree, normally starting at the root node. Returns either the node it is called with or the leave associated with the attributes of the person or the day plan a mode should be chosen for
Parameters
plan day plan
node node of the tree to start searching at
Returns
the corresponding leave of the mode choice tree or the root node
Definition at line 54 of file TPS_ModeChoiceTree.java.
References de.dlr.ivf.tapas.plan.TPS_Plan.getAttributeValue(), de.dlr.ivf.tapas.modechoice.TPS_Node.getChildren(), de.dlr.ivf.tapas.modechoice.TPS_Node.getSplitVariable(), and de.dlr.ivf.tapas.modechoice.TPS_Node.isLeaf().
find()
TPS_Node de.dlr.ivf.tapas.modechoice.TPS_ModeChoiceTree.find (TPS_Node node, int id) protected
Searches recursively for the node with the specified id; starting at the node specified
Parameters
node node to start searching at
id id of the node to find
Returns
the node if found; null else
Reimplemented in de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree.
Definition at line 83 of file TPS_ModeChoiceTree.java.
References de.dlr.ivf.tapas.modechoice.TPS_Node.getChildren(), and de.dlr.ivf.tapas.modechoice.TPS_Node.getId().
getDistributionSet()
TPS_Node de.dlr.ivf.tapas.modechoice.TPS_ModeChoiceTree.getDistributionSet (TPS_Plan plan)
Returns the node containing the mode choice distribution for the combination of the personal and trip based attributes
Parameters
plan day plan
Returns
a node containing the mode choice distribution
Reimplemented in de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree.
Definition at line 100 of file TPS_ModeChoiceTree.java.
Referenced by de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixed.getDistributionSet(), and de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixedBS.getDistributionSet().
getNode()
TPS_Node de.dlr.ivf.tapas.modechoice.TPS_ModeChoiceTree.getNode (int id)
Returns the corresponding node to the id specified
Parameters
id node id
Returns
node
Reimplemented in de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree.
Definition at line 117 of file TPS_ModeChoiceTree.java.
getRoot()
TPS_Node de.dlr.ivf.tapas.modechoice.TPS_ModeChoiceTree.getRoot ()
Returns the root of the mode choice tree
Returns
root node
Reimplemented in de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree.
Definition at line 126 of file TPS_ModeChoiceTree.java.
setRoot()
void de.dlr.ivf.tapas.modechoice.TPS_ModeChoiceTree.setRoot (TPS_Node root)
Sets the node specified as root node of the mode choice tree
Parameters
root root node to set
Definition at line 135 of file TPS_ModeChoiceTree.java.
toString() [1/2]
String de.dlr.ivf.tapas.modechoice.TPS_ModeChoiceTree.toString ()
Reimplemented in de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree.
Definition at line 145 of file TPS_ModeChoiceTree.java.
Referenced by de.dlr.ivf.tapas.mode.TPS_ModeSet.toString().
toString() [2/2]
String de.dlr.ivf.tapas.modechoice.TPS_ModeChoiceTree.toString (String prefix)
This method should print the object naturally with the given prefix.
Parameters
prefix
Returns
prefix + toString();
Implements de.dlr.ivf.tapas.util.ExtendedWritable.
Reimplemented in de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree.
Definition at line 154 of file TPS_ModeChoiceTree.java.
References de.dlr.ivf.tapas.modechoice.TPS_Node.toString().
Member Data Documentation
root
TPS_Node de.dlr.ivf.tapas.modechoice.TPS_ModeChoiceTree.root = null protected
Root node
Definition at line 28 of file TPS_ModeChoiceTree.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/modechoice/TPS_ModeChoiceTree.java