TAPAS: de.dlr.ivf.tapas.util.TPS_GX Class Reference
de.dlr.ivf.tapas.util.TPS_GX Class Reference
Static Public Member Functions
static double calculateEVA1Acceptance (double value, double EBottom, double FTop, double TurningPoint)
static int deltaSign (double delta)
static Vector< Double > tridiag (Vector< Double > a, Vector< Double > b, Vector< Double > c, Vector< Double > rhs, Vector< Double > sol)
Detailed Description
Class provides helper function for random selection
Definition at line 16 of file TPS_GX.java.
Member Function Documentation
calculateEVA1Acceptance()
static double de.dlr.ivf.tapas.util.TPS_GX.calculateEVA1Acceptance (double value, double EBottom, double FTop, double TurningPoint) static
Calculates the acceptance probability of the value provided (resistance term) according to a EVA1-Curve (Lohse), who's calibration parameter have to be provided I I---— F I \ I -\ I \ G I \
I -\ ___________ E
Parameters
value value to determine the acceptance for
EBottom parameter determining the curve in the lower part (snuggle at the bottom)
FTop parameter determining the curve in the upper part (acceptance drop for small discrepancies)
TurningPoint turning point of the function
Returns
acceptance probability between 0.0 and 1.0
Definition at line 36 of file TPS_GX.java.
References de.dlr.ivf.tapas.util.TPS_FastMath.exp().
Referenced by de.dlr.ivf.tapas.plan.acceptance.TPS_PlanEVA1Acceptance.calculateAcceptanceProbBudgetConstraints(), de.dlr.ivf.tapas.plan.acceptance.TPS_PlanEVA1Acceptance.calculateAcceptanceProbTimeConstraints(), de.dlr.ivf.tapas.plan.acceptance.TPS_PlanEVA1Acceptance.isPlanAcceptedByOverallTravelTime(), and de.dlr.ivf.tapas.iteration.TPS_AcceptanceIterationManager.selectPlansForRecalculation().
deltaSign()
static int de.dlr.ivf.tapas.util.TPS_GX.deltaSign (double delta) static
Method to identify the sign of the given double with a epsilon around zero
Parameters
delta
Returns
-1 if delta is below -eps, 0 if delta is between -eps and eps and 1 if delta is greater than eps
Definition at line 49 of file TPS_GX.java.
tridiag()
static Vector<Double> de.dlr.ivf.tapas.util.TPS_GX.tridiag (Vector< Double > a, Vector< Double > b, Vector< Double > c, Vector< Double > rhs, Vector< Double > sol) static
tridiag solves the system of linear equations, legacy import from old c files, not used for a long time!
Attention: input vectors are references and thus eventually changed!
Parameters
a Vector
b Vector
c Vector
rhs Vector
sol Vector
Returns
sol Vector<Double>
Definition at line 73 of file TPS_GX.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/util/TPS_GX.java