TAPAS: de.dlr.ivf.tapas.loc.TPS_CFN Class Reference
de.dlr.ivf.tapas.loc.TPS_CFN Class Reference
Public Member Functions
TPS_CFN (TPS_SettlementSystemType regType, TPS_ActivityCodeType actType)
void addToCFN4Map (int regionNumber, int activity, double value)
void addToCFNXMap (int regionNumber, double value)
double getCFN4Value (TPS_SettlementSystem regionType, TPS_ActivityConstant act)
double getParamValue (TPS_SettlementSystem regionType, TPS_ActivityConstant act)
double getCFNXValue (TPS_SettlementSystem regionType)
String toString ()
Private Attributes
final Map< TPS_SettlementSystem, Map< TPS_ActivityConstant, Double > > cfn4Map = new HashMap<>()
final Map< TPS_SettlementSystem, Double > defaultCFNXMap = new HashMap<>()
TPS_VariableMap specialCFN4Map
final TPS_SettlementSystemType regType
final TPS_ActivityCodeType actType
Detailed Description
Encapsulates all tables for cfn* values.
Author
mark_ma
Definition at line 30 of file TPS_CFN.java.
Constructor & Destructor Documentation
TPS_CFN()
de.dlr.ivf.tapas.loc.TPS_CFN.TPS_CFN (TPS_SettlementSystemType regType, TPS_ActivityCodeType actType)
Definition at line 59 of file TPS_CFN.java.
Member Function Documentation
addToCFN4Map()
void de.dlr.ivf.tapas.loc.TPS_CFN.addToCFN4Map (int regionNumber, int activity, double value)
Adds a value for the regional and activity based cnf-map
Parameters
regionNumber the number of the region
activity the activity number
value the value for this set
Definition at line 71 of file TPS_CFN.java.
References de.dlr.ivf.tapas.constants.TPS_ActivityConstant.getActivityCodeByTypeAndCode(), and de.dlr.ivf.tapas.constants.TPS_SettlementSystem.getSettlementSystem().
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readRegion().
addToCFNXMap()
void de.dlr.ivf.tapas.loc.TPS_CFN.addToCFNXMap (int regionNumber, double value)
Adds a value for the (general) region based cnf-map
Parameters
regionNumber the number of the region
value the value for this set
Definition at line 84 of file TPS_CFN.java.
References de.dlr.ivf.tapas.constants.TPS_SettlementSystem.getSettlementSystem().
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readRegion().
getCFN4Value()
double de.dlr.ivf.tapas.loc.TPS_CFN.getCFN4Value (TPS_SettlementSystem regionType, TPS_ActivityConstant act)
Returns
default current cfn value
Definition at line 92 of file TPS_CFN.java.
References de.dlr.ivf.tapas.constants.TPS_ActivityConstant.getActivityCodeByTypeAndCode(), de.dlr.ivf.tapas.constants.TPS_ActivityConstant.getCode(), de.dlr.ivf.tapas.constants.TPS_SettlementSystem.getCode(), de.dlr.ivf.tapas.constants.TPS_SettlementSystem.getSettlementSystem(), de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.WARN, and de.dlr.ivf.tapas.constants.TPS_ActivityConstant.TPS_ActivityCodeType.ZBE.
Referenced by de.dlr.ivf.tapas.loc.TPS_SelectLocationWeightBased.selectLocationFromChoiceSet(), and de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.selectLocationFromChoiceSet().
getCFNXValue()
double de.dlr.ivf.tapas.loc.TPS_CFN.getCFNXValue (TPS_SettlementSystem regionType)
Returns
current cfnx value
Definition at line 125 of file TPS_CFN.java.
References de.dlr.ivf.tapas.constants.TPS_SettlementSystem.getCode(), and de.dlr.ivf.tapas.constants.TPS_SettlementSystem.getSettlementSystem().
Referenced by de.dlr.ivf.tapas.loc.TPS_SelectLocationWeightBased.selectLocationFromChoiceSet(), and de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.selectLocationFromChoiceSet().
getParamValue()
double de.dlr.ivf.tapas.loc.TPS_CFN.getParamValue (TPS_SettlementSystem regionType, TPS_ActivityConstant act)
Returns
default current cfn value
Definition at line 109 of file TPS_CFN.java.
References de.dlr.ivf.tapas.constants.TPS_ActivityConstant.getActivityCodeByTypeAndCode(), de.dlr.ivf.tapas.constants.TPS_ActivityConstant.getCode(), de.dlr.ivf.tapas.constants.TPS_SettlementSystem.getCode(), and de.dlr.ivf.tapas.constants.TPS_SettlementSystem.getSettlementSystem().
Referenced by de.dlr.ivf.tapas.loc.TPS_SelectLocationWeightBased.selectLocationFromChoiceSet(), and de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.selectLocationFromChoiceSet().
toString()
String de.dlr.ivf.tapas.loc.TPS_CFN.toString ()
Definition at line 137 of file TPS_CFN.java.
Member Data Documentation
actType
final TPS_ActivityCodeType de.dlr.ivf.tapas.loc.TPS_CFN.actType private
Activity type
Definition at line 57 of file TPS_CFN.java.
cfn4Map
final Map<TPS_SettlementSystem, Map<TPS_ActivityConstant, Double> > de.dlr.ivf.tapas.loc.TPS_CFN.cfn4Map = new HashMap<>() private
cfn4 values depending on settlement system and activity code
Definition at line 35 of file TPS_CFN.java.
defaultCFNXMap
final Map<TPS_SettlementSystem, Double> de.dlr.ivf.tapas.loc.TPS_CFN.defaultCFNXMap = new HashMap<>() private
cfnX values depending on settlement system
Definition at line 41 of file TPS_CFN.java.
regType
final TPS_SettlementSystemType de.dlr.ivf.tapas.loc.TPS_CFN.regType private
Settlement type
Definition at line 52 of file TPS_CFN.java.
specialCFN4Map
TPS_VariableMap de.dlr.ivf.tapas.loc.TPS_CFN.specialCFN4Map private
cfn4 values depending on settlement system, time and work
Definition at line 47 of file TPS_CFN.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/loc/TPS_CFN.java