TAPAS: de.dlr.ivf.tapas.tools.TPS_SpeedAndDistanceValidator Class Reference
de.dlr.ivf.tapas.tools.TPS_SpeedAndDistanceValidator Class Reference
Classes
class OutlierEntry
class ScatterData
enum STATVAL
class TAZ
class TravelData
Public Member Functions
void addMatrix (double[][] a, double[][] b)
double[] calcStatistics (boolean speed)
double[] calcStatistics (boolean speed, double distMin, double distMax)
Collection< ScatterData > calchAVGSpeedScatterPlotData (double distBin)
Collection< ScatterData > calchScatterPlotData (double speedBin, double distBin, boolean speed)
List< OutlierEntry > findOutliers (double maxThreshold)
List< TravelData > findStrangePairs (boolean speed, double maxThreshold, double minThreshold)
double[][] loadMatrix (String table, String name)
double[][] loadMatrixFromFile (String name)
void loadTAZ (String table)
void loadTAZInfos (String tazTable, String matrixTable, String distName, String ttName, String accessName, String egressName)
void writeScatterData (String filename, Collection< ScatterData > data)
Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_BasicConnectionClass ()
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass)
TPS_BasicConnectionClass (String loginFile)
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass, String loginFile)
boolean checkMatrixName (String matrixName)
TPS_ParameterClass getParameters ()
String readParameter (String simKey, String paramKey)
void storeInDB (String matrixName, double[][] matrix, int decimalPlaces)
Static Public Member Functions
static void main (String[] args)
Static Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
static double[][] array1Dto2D (Integer[] matrixVal)
static double[][] array1Dto2D (int[] matrixVal)
static File getRuntimeFile (boolean forceNewFile)
static File getRuntimeFile (String propertyFile, boolean forceNewFile)
static File getRuntimeFile ()
static File getRuntimeFile (String propertyFile)
static int[][] intArray1Dto2D (int[] matrixVal)
static String matrixToSQLArray (double[][] array, int decimalPlaces)
static StringWriter matrixToStringWriterSQL (double[][] array, int decimalPlaces)
Additional Inherited Members
Protected Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
void finalize ()
Protected Attributes inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_DB_Connector dbCon = null
TPS_ParameterClass parameterClass
Detailed Description
Definition at line 20 of file TPS_SpeedAndDistanceValidator.java.
Member Function Documentation
addMatrix()
void de.dlr.ivf.tapas.tools.TPS_SpeedAndDistanceValidator.addMatrix (double a[][], double b[][])
Definition at line 97 of file TPS_SpeedAndDistanceValidator.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_SpeedAndDistanceValidator.loadTAZInfos().
calchAVGSpeedScatterPlotData()
Collection<ScatterData> de.dlr.ivf.tapas.tools.TPS_SpeedAndDistanceValidator.calchAVGSpeedScatterPlotData (double distBin)
Calc the average speed per distance bin.
Parameters
distBin
Returns
Definition at line 152 of file TPS_SpeedAndDistanceValidator.java.
calchScatterPlotData()
Collection<ScatterData> de.dlr.ivf.tapas.tools.TPS_SpeedAndDistanceValidator.calchScatterPlotData (double speedBin, double distBin, boolean speed)
Definition at line 184 of file TPS_SpeedAndDistanceValidator.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_SpeedAndDistanceValidator.main().
calcStatistics() [1/2]
double [] de.dlr.ivf.tapas.tools.TPS_SpeedAndDistanceValidator.calcStatistics (boolean speed)
Definition at line 105 of file TPS_SpeedAndDistanceValidator.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_SpeedAndDistanceValidator.main().
calcStatistics() [2/2]
double [] de.dlr.ivf.tapas.tools.TPS_SpeedAndDistanceValidator.calcStatistics (boolean speed, double distMin, double distMax)
Definition at line 110 of file TPS_SpeedAndDistanceValidator.java.
findOutliers()
List<OutlierEntry> de.dlr.ivf.tapas.tools.TPS_SpeedAndDistanceValidator.findOutliers (double maxThreshold)
Method to build an ordered list of outliers. An outlier deviates by a given Threshold between the x and y values.
Parameters
maxThreshold
Returns
Definition at line 231 of file TPS_SpeedAndDistanceValidator.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_SpeedAndDistanceValidator.main().
findStrangePairs()
List<TravelData> de.dlr.ivf.tapas.tools.TPS_SpeedAndDistanceValidator.findStrangePairs (boolean speed, double maxThreshold, double minThreshold)
Definition at line 268 of file TPS_SpeedAndDistanceValidator.java.
loadMatrix()
double [][] de.dlr.ivf.tapas.tools.TPS_SpeedAndDistanceValidator.loadMatrix (String table, String name)
Definition at line 284 of file TPS_SpeedAndDistanceValidator.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.array1Dto2D(), de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.extractIntArray(), and name.
Referenced by de.dlr.ivf.tapas.tools.TPS_SpeedAndDistanceValidator.loadTAZInfos().
loadMatrixFromFile()
double [][] de.dlr.ivf.tapas.tools.TPS_SpeedAndDistanceValidator.loadMatrixFromFile (String name)
Definition at line 303 of file TPS_SpeedAndDistanceValidator.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.array1Dto2D(), and name.
loadTAZ()
void de.dlr.ivf.tapas.tools.TPS_SpeedAndDistanceValidator.loadTAZ (String table)
Definition at line 330 of file TPS_SpeedAndDistanceValidator.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery().
Referenced by de.dlr.ivf.tapas.tools.TPS_SpeedAndDistanceValidator.loadTAZInfos().
loadTAZInfos()
void de.dlr.ivf.tapas.tools.TPS_SpeedAndDistanceValidator.loadTAZInfos (String tazTable, String matrixTable, String distName, String ttName, String accessName, String egressName)
Definition at line 352 of file TPS_SpeedAndDistanceValidator.java.
References de.dlr.ivf.tapas.tools.TPS_SpeedAndDistanceValidator.addMatrix(), de.dlr.ivf.tapas.util.TPS_Geometrics.getDistance(), de.dlr.ivf.tapas.tools.TPS_SpeedAndDistanceValidator.loadMatrix(), and de.dlr.ivf.tapas.tools.TPS_SpeedAndDistanceValidator.loadTAZ().
Referenced by de.dlr.ivf.tapas.tools.TPS_SpeedAndDistanceValidator.main().
main()
static void de.dlr.ivf.tapas.tools.TPS_SpeedAndDistanceValidator.main (String[] args) static
Definition at line 25 of file TPS_SpeedAndDistanceValidator.java.
References de.dlr.ivf.tapas.tools.TPS_SpeedAndDistanceValidator.calchScatterPlotData(), de.dlr.ivf.tapas.tools.TPS_SpeedAndDistanceValidator.calcStatistics(), de.dlr.ivf.tapas.tools.TPS_SpeedAndDistanceValidator.findOutliers(), de.dlr.ivf.tapas.tools.TPS_SpeedAndDistanceValidator.loadTAZInfos(), and de.dlr.ivf.tapas.tools.TPS_SpeedAndDistanceValidator.writeScatterData().
writeScatterData()
void de.dlr.ivf.tapas.tools.TPS_SpeedAndDistanceValidator.writeScatterData (String filename, Collection< ScatterData > data)
Definition at line 382 of file TPS_SpeedAndDistanceValidator.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_SpeedAndDistanceValidator.main().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/TPS_SpeedAndDistanceValidator.java