TAPAS: de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.AnalyzerCollection Class Reference
de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.AnalyzerCollection Class Reference
Public Member Functions
AnalyzerCollection (String name, AnalyzerBase... analyzers)
AnalyzerCollection (AnalyzerBase... analyzers)
AnalyzerCollection (String name)
int addAnalyzer (AnalyzerBase analyzer)
AnalyzerBase[] getAnalyzers ()
Categories[] getCategories ()
String getName ()
void setName (String name)
int size ()
String toString ()
Private Attributes
AnalyzerBase[] analyzers
String name
Static Private Attributes
static final String SEPARATOR = " - "
Detailed Description
This class groups AnalyzerBase objects and works as a wrapper for javax.swing.tree.DefaultMutableTreeNode that form the tree in TUMControlGeneral.
Author
boec_pa
Definition at line 23 of file AnalyzerCollection.java.
Constructor & Destructor Documentation
AnalyzerCollection() [1/3]
de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.AnalyzerCollection.AnalyzerCollection (String name, AnalyzerBase... analyzers)
Definition at line 30 of file AnalyzerCollection.java.
References name.
AnalyzerCollection() [2/3]
de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.AnalyzerCollection.AnalyzerCollection (AnalyzerBase... analyzers)
Definition at line 35 of file AnalyzerCollection.java.
AnalyzerCollection() [3/3]
de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.AnalyzerCollection.AnalyzerCollection (String name)
Definition at line 39 of file AnalyzerCollection.java.
References name.
Member Function Documentation
addAnalyzer()
int de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.AnalyzerCollection.addAnalyzer (AnalyzerBase analyzer)
adds an AnalyzerBase to the collection and returns the index where it is inserted.
Definition at line 47 of file AnalyzerCollection.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.AnalyzerTreeTransferHandler.importData().
getAnalyzers()
AnalyzerBase [] de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.AnalyzerCollection.getAnalyzers ()
Definition at line 56 of file AnalyzerCollection.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.loadSelectedNodeInfo(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.writeTree().
getCategories()
Categories [] de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.AnalyzerCollection.getCategories ()
Definition at line 60 of file AnalyzerCollection.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralExcelExport.writeAnalysis(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralExcelExport.writeFile().
getName()
String de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.AnalyzerCollection.getName ()
Definition at line 69 of file AnalyzerCollection.java.
References name.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.loadSelectedNodeInfo(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralExcelExport.writeAnalysis(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralExcelExport.writeFile(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.writeTree().
setName()
void de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.AnalyzerCollection.setName (String name)
Definition at line 73 of file AnalyzerCollection.java.
References name.
size()
int de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.AnalyzerCollection.size ()
Definition at line 77 of file AnalyzerCollection.java.
toString()
String de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.AnalyzerCollection.toString ()
Definition at line 82 of file AnalyzerCollection.java.
References name.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralExcelExport.writeFile().
Member Data Documentation
analyzers
AnalyzerBase [] de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.AnalyzerCollection.analyzers private
Definition at line 27 of file AnalyzerCollection.java.
name
String de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.AnalyzerCollection.name private
Definition at line 28 of file AnalyzerCollection.java.
SEPARATOR
final String de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.AnalyzerCollection.SEPARATOR = " - " static private
Definition at line 25 of file AnalyzerCollection.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/tum/regionanalyzer/general/AnalyzerCollection.java