TAPAS: de.dlr.ivf.tapas.loc.TPS_Location.TPS_LocationData Class Reference
de.dlr.ivf.tapas.loc.TPS_Location.TPS_LocationData Class Reference
Public Member Functions
void calculateWeight ()
int getCapacity ()
int getOccupancy ()
double getWeight ()
boolean hasFixCapacity ()
void init (int capacity, boolean fixCapacity)
boolean setOccupancy (int newValue)
String toString ()
Private Attributes
int capacity
Capacity of the location.
boolean fixCapacity
int occupancy = 0
number of persons that chose that location
double weight = 0
Weight represents the amount of free capacities.
final TPS_ParameterClass parameterClass
Detailed Description
Definition at line 231 of file TPS_Location.java.
Member Function Documentation
calculateWeight()
void de.dlr.ivf.tapas.loc.TPS_Location.TPS_LocationData.calculateWeight ()
This method calculates the weight of the location by a decreasing exponential function, so the weight is always greater than 0.
Since very small weights produce nasty cast errors in sql an overloadfactor is introduced: Locations with an overload of 10 get a weight of 0!
Definition at line 263 of file TPS_Location.java.
References de.dlr.ivf.tapas.util.TPS_FastMath.exp(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getDoubleValue(), and de.dlr.ivf.tapas.util.parameters.ParamValue.WEIGHT_OCCUPANCY.
getCapacity()
int de.dlr.ivf.tapas.loc.TPS_Location.TPS_LocationData.getCapacity ()
Returns the capacity of a location
Returns
capacity
Definition at line 289 of file TPS_Location.java.
getOccupancy()
int de.dlr.ivf.tapas.loc.TPS_Location.TPS_LocationData.getOccupancy ()
Returns the occupancy of the location
Returns
occupancy
Definition at line 298 of file TPS_Location.java.
getWeight()
double de.dlr.ivf.tapas.loc.TPS_Location.TPS_LocationData.getWeight ()
Returns the weight of the location
Returns
weight (always greater than 0)
Definition at line 307 of file TPS_Location.java.
Referenced by de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.TypedWeightedLocationDistribution.addLocation(), de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.TypedWeightedLocationDistribution.selectActivityLocations(), and de.dlr.ivf.tapas.loc.TPS_Location.updateOccupancy().
hasFixCapacity()
boolean de.dlr.ivf.tapas.loc.TPS_Location.TPS_LocationData.hasFixCapacity ()
Flag if the capacity of the location is fix
Returns
true if fix, false else
Definition at line 316 of file TPS_Location.java.
init()
void de.dlr.ivf.tapas.loc.TPS_Location.TPS_LocationData.init (int capacity, boolean fixCapacity)
Initialises this location's capacity and occupancy and computes the respective weight
Parameters
capacity The capacity of this location
fixCapacity Whether the capacity shall be fix
Definition at line 326 of file TPS_Location.java.
Referenced by de.dlr.ivf.tapas.loc.TPS_Location.initCapacity().
setOccupancy()
boolean de.dlr.ivf.tapas.loc.TPS_Location.TPS_LocationData.setOccupancy (int newValue)
Sets a new occupancy
Parameters
newValue The new occupancy
Returns
Whether the occupancy has changed
Definition at line 339 of file TPS_Location.java.
References de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_UPDATE_LOCATION_WEIGHTS, and de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isTrue().
Referenced by de.dlr.ivf.tapas.loc.TPS_Location.updateOccupancy().
toString()
String de.dlr.ivf.tapas.loc.TPS_Location.TPS_LocationData.toString ()
Returns this object's string representation
See also
java.lang.Object::toString()
Definition at line 360 of file TPS_Location.java.
Referenced by de.dlr.ivf.tapas.loc.TPS_Location.toString().
Member Data Documentation
capacity
int de.dlr.ivf.tapas.loc.TPS_Location.TPS_LocationData.capacity private
Capacity of the location.
Definition at line 233 of file TPS_Location.java.
fixCapacity
boolean de.dlr.ivf.tapas.loc.TPS_Location.TPS_LocationData.fixCapacity private
This flag indicates if the location has a fixed capacity, i.e. occupancy <= capacity (e.g. theatres, enterprises, etc). If the flag is false more people can choose this location than its capacity provides (e.g. parks, museums, shops, etc.).
Definition at line 241 of file TPS_Location.java.
occupancy
int de.dlr.ivf.tapas.loc.TPS_Location.TPS_LocationData.occupancy = 0 private
number of persons that chose that location
Definition at line 244 of file TPS_Location.java.
parameterClass
final TPS_ParameterClass de.dlr.ivf.tapas.loc.TPS_Location.TPS_LocationData.parameterClass private
Definition at line 249 of file TPS_Location.java.
weight
double de.dlr.ivf.tapas.loc.TPS_Location.TPS_LocationData.weight = 0 private
Weight represents the amount of free capacities.
Definition at line 247 of file TPS_Location.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/loc/TPS_Location.java