TAPAS: de.dlr.ivf.tapas.tools.TPS_SchemeClassCalculator Class Reference
de.dlr.ivf.tapas.tools.TPS_SchemeClassCalculator Class Reference
Static Public Member Functions
static void main (String[] args) throws IOException, SQLException, ClassNotFoundException
Protected Member Functions
void finalize () throws Throwable
Private Member Functions
void readData () throws SQLException
void writeSchemeClassValues () throws SQLException
Private Attributes
final Connection con
final Statement st
final int minSchemeClass
final int maxSchemeClass
final HashMap< Integer, double[]> SchemeClassEntries
Static Private Attributes
static final double slotFactor = 5.0
Detailed Description
Definition at line 23 of file TPS_SchemeClassCalculator.java.
Member Function Documentation
finalize()
void de.dlr.ivf.tapas.tools.TPS_SchemeClassCalculator.finalize () throws Throwable protected
Definition at line 75 of file TPS_SchemeClassCalculator.java.
main()
static void de.dlr.ivf.tapas.tools.TPS_SchemeClassCalculator.main (String[] args) throws IOException, SQLException, ClassNotFoundException static
Definition at line 63 of file TPS_SchemeClassCalculator.java.
References de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.loadRuntimeParameters(), de.dlr.ivf.tapas.tools.TPS_SchemeClassCalculator.readData(), and de.dlr.ivf.tapas.tools.TPS_SchemeClassCalculator.writeSchemeClassValues().
readData()
void de.dlr.ivf.tapas.tools.TPS_SchemeClassCalculator.readData () throws SQLException private
Definition at line 81 of file TPS_SchemeClassCalculator.java.
References de.dlr.ivf.tapas.tools.TPS_SchemeClassCalculator.maxSchemeClass, and de.dlr.ivf.tapas.tools.TPS_SchemeClassCalculator.slotFactor.
Referenced by de.dlr.ivf.tapas.tools.TPS_SchemeClassCalculator.main().
writeSchemeClassValues()
void de.dlr.ivf.tapas.tools.TPS_SchemeClassCalculator.writeSchemeClassValues () throws SQLException private
Definition at line 148 of file TPS_SchemeClassCalculator.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_SchemeClassCalculator.main().
Member Data Documentation
con
final Connection de.dlr.ivf.tapas.tools.TPS_SchemeClassCalculator.con private
Connection to the database
Definition at line 28 of file TPS_SchemeClassCalculator.java.
maxSchemeClass
final int de.dlr.ivf.tapas.tools.TPS_SchemeClassCalculator.maxSchemeClass private
Definition at line 31 of file TPS_SchemeClassCalculator.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_SchemeClassCalculator.readData().
minSchemeClass
final int de.dlr.ivf.tapas.tools.TPS_SchemeClassCalculator.minSchemeClass private
Definition at line 30 of file TPS_SchemeClassCalculator.java.
SchemeClassEntries
final HashMap<Integer, double[]> de.dlr.ivf.tapas.tools.TPS_SchemeClassCalculator.SchemeClassEntries private
Definition at line 32 of file TPS_SchemeClassCalculator.java.
slotFactor
final double de.dlr.ivf.tapas.tools.TPS_SchemeClassCalculator.slotFactor = 5.0 static private
Definition at line 24 of file TPS_SchemeClassCalculator.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_SchemeClassCalculator.readData().
st
final Statement de.dlr.ivf.tapas.tools.TPS_SchemeClassCalculator.st private
Definition at line 29 of file TPS_SchemeClassCalculator.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/TPS_SchemeClassCalculator.java