TAPAS: de.dlr.ivf.tapas.plan.TPS_LocatedStay Class Reference
de.dlr.ivf.tapas.plan.TPS_LocatedStay Class Reference
Public Member Functions
TPS_LocatedStay (TPS_Plan plan, TPS_Stay stay)
TPS_LocatedStay (TPS_LocatedStay locatedStayIn)
void deleteModes ()
TPS_Episode getEpisode ()
TPS_Location getLocation ()
void setLocation (TPS_Location location)
TPS_ExtMode getModeArr ()
void setModeArr (TPS_ExtMode modeArr)
TPS_ExtMode getModeDep ()
void setModeDep (TPS_ExtMode modeDep)
TPS_Stay getStay ()
void setStay (TPS_Stay stay)
void init ()
boolean isLocated ()
boolean isLocatedStay ()
void selectLocation (TPS_Plan plan, TPS_PlanningContext pc)
String toString ()
String toString (String prefix)
Public Member Functions inherited from de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode
TPS_AdaptedEpisode (TPS_Plan plan, TPS_Episode episode)
double getDistance ()
void setDistance (double distance)
double getDistanceBeeline ()
void setDistanceBeeline (double distanceBeeline)
double getDistanceEmptyNet ()
void setDistanceEmptyNet (double distanceEmptyNet)
int getDuration ()
void setDuration (int duration)
int getEnd ()
int getStart ()
void setStart (int start)
boolean isPlannedTrip ()
Private Attributes
TPS_Location location
TPS_ExtMode modeArr = null
TPS_ExtMode modeDep = null
TPS_Stay stay
final TPS_PersistenceManager PM
Additional Inherited Members
Protected Member Functions inherited from de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode
void init (TPS_Episode episode)
Protected Attributes inherited from de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode
TPS_Plan plan
Detailed Description
Author
cyga_ri
Definition at line 35 of file TPS_LocatedStay.java.
Constructor & Destructor Documentation
TPS_LocatedStay() [1/2]
de.dlr.ivf.tapas.plan.TPS_LocatedStay.TPS_LocatedStay (TPS_Plan plan, TPS_Stay stay)
Constructor for a located stay.
Parameters
plan reference to the whole plan
stay reference to the current stay
Definition at line 54 of file TPS_LocatedStay.java.
References de.dlr.ivf.tapas.plan.TPS_Plan.getPM().
TPS_LocatedStay() [2/2]
de.dlr.ivf.tapas.plan.TPS_LocatedStay.TPS_LocatedStay (TPS_LocatedStay locatedStayIn)
Definition at line 62 of file TPS_LocatedStay.java.
References de.dlr.ivf.tapas.plan.TPS_Plan.getPM(), de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.plan, and de.dlr.ivf.tapas.plan.TPS_LocatedStay.stay.
Member Function Documentation
deleteModes()
void de.dlr.ivf.tapas.plan.TPS_LocatedStay.deleteModes ()
Deletes the arrival and departure mode of the stay
Definition at line 73 of file TPS_LocatedStay.java.
getEpisode()
TPS_Episode de.dlr.ivf.tapas.plan.TPS_LocatedStay.getEpisode ()
getter method for the stay-instance as an episode
Reimplemented from de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.
Definition at line 83 of file TPS_LocatedStay.java.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes().
getLocation()
TPS_Location de.dlr.ivf.tapas.plan.TPS_LocatedStay.getLocation ()
Returns the location of the stay
Returns
the location
Definition at line 93 of file TPS_LocatedStay.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.batchStoreTrips(), de.dlr.ivf.tapas.loc.TPS_FocusPointModel.getFocusPoint(), de.dlr.ivf.tapas.loc.TPS_MultipleTAZRepresentant.getLocationRepresentatives(), de.dlr.ivf.tapas.plan.TPS_LocatedStay.selectLocation(), de.dlr.ivf.tapas.loc.TPS_SelectLocationWeightBased.selectLocationFromChoiceSet(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.selectLocationFromChoiceSet(), de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes(), and de.dlr.ivf.tapas.mode.TPS_ModeSet.selectMode().
getModeArr()
TPS_ExtMode de.dlr.ivf.tapas.plan.TPS_LocatedStay.getModeArr ()
Returns the arrival mode of the stay
Returns
arrival mode
Definition at line 111 of file TPS_LocatedStay.java.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes(), and de.dlr.ivf.tapas.mode.TPS_ModeSet.selectMode().
getModeDep()
TPS_ExtMode de.dlr.ivf.tapas.plan.TPS_LocatedStay.getModeDep ()
Returns the departure mode of the stay
Returns
departure mode
Definition at line 129 of file TPS_LocatedStay.java.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes(), and de.dlr.ivf.tapas.mode.TPS_ModeSet.selectMode().
getStay()
TPS_Stay de.dlr.ivf.tapas.plan.TPS_LocatedStay.getStay ()
getter method for the basic stay
Returns
Definition at line 147 of file TPS_LocatedStay.java.
Referenced by de.dlr.ivf.tapas.loc.TPS_MultipleTAZRepresentant.getLocationRepresentatives(), de.dlr.ivf.tapas.loc.TPS_Region.selectLocation(), de.dlr.ivf.tapas.loc.TPS_SelectLocationWeightBased.selectLocationFromChoiceSet(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.selectLocationFromChoiceSet(), and de.dlr.ivf.tapas.mode.TPS_ModeSet.selectMode().
init()
void de.dlr.ivf.tapas.plan.TPS_LocatedStay.init ()
Definition at line 163 of file TPS_LocatedStay.java.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.reset().
isLocated()
boolean de.dlr.ivf.tapas.plan.TPS_LocatedStay.isLocated ()
Definition at line 169 of file TPS_LocatedStay.java.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes().
isLocatedStay()
boolean de.dlr.ivf.tapas.plan.TPS_LocatedStay.isLocatedStay ()
Returns
true if it is a located stay false otherwise
Reimplemented from de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.
Definition at line 174 of file TPS_LocatedStay.java.
selectLocation()
void de.dlr.ivf.tapas.plan.TPS_LocatedStay.selectLocation (TPS_Plan plan, TPS_PlanningContext pc)
Selects a location for the stay
Parameters
plan day plan to be executed
pc
Definition at line 184 of file TPS_LocatedStay.java.
References de.dlr.ivf.tapas.util.TPS_AttributeReader.TPS_Attribute.CURRENT_EPISODE_ACTIVITY_CODE_MCT, de.dlr.ivf.tapas.util.TPS_AttributeReader.TPS_Attribute.CURRENT_EPISODE_ACTIVITY_CODE_TAPAS, de.dlr.ivf.tapas.util.TPS_AttributeReader.TPS_Attribute.CURRENT_EPISODE_ACTIVITY_CODE_VOT, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.DEBUG, de.dlr.ivf.tapas.constants.TPS_ActivityConstant.TPS_ActivityConstantAttribute.E_COMMERCE_OUT_OF_HOME, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.mode.TPS_Mode.get(), de.dlr.ivf.tapas.scheme.TPS_Episode.getActCode(), de.dlr.ivf.tapas.constants.TPS_ActivityConstant.getCode(), de.dlr.ivf.tapas.mode.TPS_Mode.getDistance(), de.dlr.ivf.tapas.person.TPS_Person.getHousehold(), de.dlr.ivf.tapas.plan.TPS_Plan.getLocatedStay(), de.dlr.ivf.tapas.person.TPS_Household.getLocation(), de.dlr.ivf.tapas.plan.TPS_LocatedStay.getLocation(), de.dlr.ivf.tapas.scheme.TPS_TourPart.TPS_StayHierarchy.getNextStay(), de.dlr.ivf.tapas.plan.TPS_Plan.getPerson(), de.dlr.ivf.tapas.scheme.TPS_TourPart.TPS_StayHierarchy.getPrevStay(), de.dlr.ivf.tapas.persistence.TPS_PersistenceManager.getRegion(), de.dlr.ivf.tapas.scheme.TPS_Episode.getSchemePart(), de.dlr.ivf.tapas.scheme.TPS_TourPart.getStayHierarchy(), de.dlr.ivf.tapas.constants.TPS_ActivityConstant.hasAttribute(), de.dlr.ivf.tapas.scheme.TPS_Stay.isAtHome(), de.dlr.ivf.tapas.plan.TPS_Plan.isLocated(), de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.constants.TPS_ActivityConstant.TPS_ActivityCodeType.MCT, de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.MIT, de.dlr.ivf.tapas.util.parameters.SimulationType.SCENARIO, de.dlr.ivf.tapas.loc.TPS_Region.selectLocation(), de.dlr.ivf.tapas.plan.TPS_Plan.setAttributeValue(), de.dlr.ivf.tapas.constants.TPS_ActivityConstant.TPS_ActivityCodeType.TAPAS, and de.dlr.ivf.tapas.constants.TPS_ActivityConstant.TPS_ActivityCodeType.VOT.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes().
setLocation()
void de.dlr.ivf.tapas.plan.TPS_LocatedStay.setLocation (TPS_Location location)
Sets the location for the stay
Parameters
location the location for the stay
Definition at line 102 of file TPS_LocatedStay.java.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.reset(), de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes(), and de.dlr.ivf.tapas.plan.TPS_Plan.TPS_Plan().
setModeArr()
void de.dlr.ivf.tapas.plan.TPS_LocatedStay.setModeArr (TPS_ExtMode modeArr)
Sets the arrival mode of the stay
Parameters
modeArr mode to set
Definition at line 120 of file TPS_LocatedStay.java.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes(), and de.dlr.ivf.tapas.mode.TPS_ModeSet.selectMode().
setModeDep()
void de.dlr.ivf.tapas.plan.TPS_LocatedStay.setModeDep (TPS_ExtMode modeDep)
Sets the departure mode of the stay
Parameters
modeDep mode to set
Definition at line 138 of file TPS_LocatedStay.java.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes(), and de.dlr.ivf.tapas.mode.TPS_ModeSet.selectMode().
setStay()
void de.dlr.ivf.tapas.plan.TPS_LocatedStay.setStay (TPS_Stay stay)
Sets the Stay for this class
Parameters
stay
Definition at line 156 of file TPS_LocatedStay.java.
toString() [1/2]
String de.dlr.ivf.tapas.plan.TPS_LocatedStay.toString ()
Override for standard toString: return with empty string as prefix
Definition at line 251 of file TPS_LocatedStay.java.
toString() [2/2]
String de.dlr.ivf.tapas.plan.TPS_LocatedStay.toString (String prefix)
to String Method with a given prefix, right now prefix is ignored
Implements de.dlr.ivf.tapas.util.ExtendedWritable.
Definition at line 259 of file TPS_LocatedStay.java.
Member Data Documentation
location
TPS_Location de.dlr.ivf.tapas.plan.TPS_LocatedStay.location private
Definition at line 37 of file TPS_LocatedStay.java.
modeArr
TPS_ExtMode de.dlr.ivf.tapas.plan.TPS_LocatedStay.modeArr = null private
Definition at line 39 of file TPS_LocatedStay.java.
modeDep
TPS_ExtMode de.dlr.ivf.tapas.plan.TPS_LocatedStay.modeDep = null private
Definition at line 41 of file TPS_LocatedStay.java.
PM
final TPS_PersistenceManager de.dlr.ivf.tapas.plan.TPS_LocatedStay.PM private
Definition at line 45 of file TPS_LocatedStay.java.
stay
TPS_Stay de.dlr.ivf.tapas.plan.TPS_LocatedStay.stay private
Definition at line 43 of file TPS_LocatedStay.java.
Referenced by de.dlr.ivf.tapas.plan.TPS_LocatedStay.TPS_LocatedStay().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/plan/TPS_LocatedStay.java