TAPAS: de.dlr.ivf.tapas.scheme.TPS_SchemeClass Class Reference
de.dlr.ivf.tapas.scheme.TPS_SchemeClass Class Reference
Public Member Functions
TPS_SchemeClass (int id)
boolean containsScheme (int schemeId)
TPS_Scheme draw ()
int getId ()
TPS_Scheme getScheme (int schemeId, TPS_ParameterClass parameterClass)
TPS_SchemeSet getSchemeSet ()
boolean isEmpty ()
Iterator< TPS_Scheme > iterator ()
void setTimeDistribution (double mean, double dev)
int size ()
String toString ()
String toString (String prefix)
Private Member Functions
void setDeviation (double deviation)
void setMean (double mean)
Private Attributes
final int id
final SortedMap< Integer, TPS_Scheme > schemes
TPS_DiscreteDistribution< TPS_Scheme > schemeDis
TPS_SchemeSet schemeSet
double mean
double deviation
Detailed Description
A scheme class collects similar schemes into one class. Furthermore it provide a time distribution for travel time acceptance
Definition at line 25 of file TPS_SchemeClass.java.
Constructor & Destructor Documentation
TPS_SchemeClass()
de.dlr.ivf.tapas.scheme.TPS_SchemeClass.TPS_SchemeClass (int id)
Constructor
Parameters
id The id of this scheme class
Definition at line 56 of file TPS_SchemeClass.java.
Member Function Documentation
containsScheme()
boolean de.dlr.ivf.tapas.scheme.TPS_SchemeClass.containsScheme (int schemeId)
Checks if a scheme with the given id exists in the scheme class
Parameters
schemeId corresponding to a scheme
Returns
true if there exists a scheme corresponding to the given id
Definition at line 67 of file TPS_SchemeClass.java.
draw()
TPS_Scheme de.dlr.ivf.tapas.scheme.TPS_SchemeClass.draw ()
When the scheme distribution is not created yet it gets created. Then a scheme is drawn out of the distribution.
Returns
the drawn scheme
Definition at line 76 of file TPS_SchemeClass.java.
References de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.drawKey(), and de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.normalize().
Referenced by de.dlr.ivf.tapas.scheme.TPS_SchemeSet.selectScheme().
getId()
int de.dlr.ivf.tapas.scheme.TPS_SchemeClass.getId ()
Returns the id of the scheme class
Returns
id
Definition at line 100 of file TPS_SchemeClass.java.
Referenced by de.dlr.ivf.tapas.scheme.TPS_SchemeSet.findScheme(), and de.dlr.ivf.tapas.scheme.TPS_SchemeSet.getSchemeClass().
getScheme()
TPS_Scheme de.dlr.ivf.tapas.scheme.TPS_SchemeClass.getScheme (int schemeId, TPS_ParameterClass parameterClass)
This method returns the scheme corresponding to the given scheme id. If the scheme doesn't exist it is created.
Parameters
schemeId corresponding to the desired scheme
parameterClass parameter class reference
Returns
scheme with the given id
Definition at line 119 of file TPS_SchemeClass.java.
References de.dlr.ivf.tapas.scheme.TPS_Scheme.getId().
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readSchemeSet().
getSchemeSet()
TPS_SchemeSet de.dlr.ivf.tapas.scheme.TPS_SchemeClass.getSchemeSet ()
Returns
reference to the complete scheme set
Definition at line 134 of file TPS_SchemeClass.java.
isEmpty()
boolean de.dlr.ivf.tapas.scheme.TPS_SchemeClass.isEmpty ()
Method to check if this TPS_SchemeClass is empty.
Returns
true if no TPS_Scheme is attached to this object
Definition at line 152 of file TPS_SchemeClass.java.
iterator()
Iterator<TPS_Scheme> de.dlr.ivf.tapas.scheme.TPS_SchemeClass.iterator ()
Definition at line 161 of file TPS_SchemeClass.java.
setDeviation()
void de.dlr.ivf.tapas.scheme.TPS_SchemeClass.setDeviation (double deviation) private
Definition at line 91 of file TPS_SchemeClass.java.
setMean()
void de.dlr.ivf.tapas.scheme.TPS_SchemeClass.setMean (double mean) private
Definition at line 108 of file TPS_SchemeClass.java.
setTimeDistribution()
void de.dlr.ivf.tapas.scheme.TPS_SchemeClass.setTimeDistribution (double mean, double dev)
Sets the time distribution, i.e. mean and deviation
Parameters
mean mean
dev deviation
Definition at line 171 of file TPS_SchemeClass.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readSchemeSet().
size()
int de.dlr.ivf.tapas.scheme.TPS_SchemeClass.size ()
Returns the size of the scheme class: e.g. the number of schemes contained
Returns
number of schemes in the scheme class
Definition at line 181 of file TPS_SchemeClass.java.
toString() [1/2]
String de.dlr.ivf.tapas.scheme.TPS_SchemeClass.toString ()
Definition at line 191 of file TPS_SchemeClass.java.
toString() [2/2]
String de.dlr.ivf.tapas.scheme.TPS_SchemeClass.toString (String prefix)
This method should print the object naturally with the given prefix.
Parameters
prefix
Returns
prefix + toString();
Implements de.dlr.ivf.tapas.util.ExtendedWritable.
Definition at line 200 of file TPS_SchemeClass.java.
Member Data Documentation
deviation
double de.dlr.ivf.tapas.scheme.TPS_SchemeClass.deviation private
deviation of a gaussian distribution
Definition at line 49 of file TPS_SchemeClass.java.
id
final int de.dlr.ivf.tapas.scheme.TPS_SchemeClass.id private
Definition at line 27 of file TPS_SchemeClass.java.
mean
double de.dlr.ivf.tapas.scheme.TPS_SchemeClass.mean private
mean or expected value of a Gaussian distribution of this scheme class
Definition at line 44 of file TPS_SchemeClass.java.
schemeDis
TPS_DiscreteDistribution<TPS_Scheme> de.dlr.ivf.tapas.scheme.TPS_SchemeClass.schemeDis private
Definition at line 33 of file TPS_SchemeClass.java.
schemes
final SortedMap<Integer, TPS_Scheme> de.dlr.ivf.tapas.scheme.TPS_SchemeClass.schemes private
Definition at line 30 of file TPS_SchemeClass.java.
schemeSet
TPS_SchemeSet de.dlr.ivf.tapas.scheme.TPS_SchemeClass.schemeSet private
Reference to the scheme set
Definition at line 38 of file TPS_SchemeClass.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/scheme/TPS_SchemeClass.java