TAPAS: de.dlr.ivf.tapas.analyzer.gui.FilesChooser.FilesListModel Class Reference
de.dlr.ivf.tapas.analyzer.gui.FilesChooser.FilesListModel Class Reference
Public Member Functions
void addListDataListener (ListDataListener l)
void changed ()
File getElementAt (int index)
int getSize ()
void removeListDataListener (ListDataListener l)
Private Attributes
final List< ListDataListener > listeners = new ArrayList<>()
Detailed Description
Model which get all Files from FilesChooser#files
Author
mbrehme
Definition at line 181 of file FilesChooser.java.
Member Function Documentation
addListDataListener()
void de.dlr.ivf.tapas.analyzer.gui.FilesChooser.FilesListModel.addListDataListener (ListDataListener l)
Definition at line 185 of file FilesChooser.java.
References de.dlr.ivf.tapas.analyzer.gui.FilesChooser.FilesListModel.listeners.
changed()
void de.dlr.ivf.tapas.analyzer.gui.FilesChooser.FilesListModel.changed ()
Definition at line 189 of file FilesChooser.java.
References de.dlr.ivf.tapas.analyzer.gui.FilesChooser.files, and de.dlr.ivf.tapas.analyzer.gui.FilesChooser.FilesListModel.listeners.
Referenced by de.dlr.ivf.tapas.analyzer.gui.FilesChooser.addFiles(), and de.dlr.ivf.tapas.analyzer.gui.FilesChooser.do_lstFiles_mouseClicked().
getElementAt()
File de.dlr.ivf.tapas.analyzer.gui.FilesChooser.FilesListModel.getElementAt (int index)
Definition at line 194 of file FilesChooser.java.
References de.dlr.ivf.tapas.analyzer.gui.FilesChooser.files.
getSize()
int de.dlr.ivf.tapas.analyzer.gui.FilesChooser.FilesListModel.getSize ()
Definition at line 198 of file FilesChooser.java.
References de.dlr.ivf.tapas.analyzer.gui.FilesChooser.files.
removeListDataListener()
void de.dlr.ivf.tapas.analyzer.gui.FilesChooser.FilesListModel.removeListDataListener (ListDataListener l)
Definition at line 202 of file FilesChooser.java.
References de.dlr.ivf.tapas.analyzer.gui.FilesChooser.FilesListModel.listeners.
Member Data Documentation
listeners
final List<ListDataListener> de.dlr.ivf.tapas.analyzer.gui.FilesChooser.FilesListModel.listeners = new ArrayList<>() private
Definition at line 183 of file FilesChooser.java.
Referenced by de.dlr.ivf.tapas.analyzer.gui.FilesChooser.FilesListModel.addListDataListener(), de.dlr.ivf.tapas.analyzer.gui.FilesChooser.FilesListModel.changed(), and de.dlr.ivf.tapas.analyzer.gui.FilesChooser.FilesListModel.removeListDataListener().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/gui/FilesChooser.java