TAPAS: de.dlr.ivf.tapas.person.TPS_Household Class Reference
de.dlr.ivf.tapas.person.TPS_Household Class Reference
Classes
enum Sorting
Public Member Functions
TPS_Household (int id)
TPS_Household (int id, int income, int type, TPS_Location loc, TPS_Car[] cars)
void addMember (TPS_Person p)
TPS_Car[] getAllCars ()
TPS_Car[] getAvailableCars (double start, double end)
TPS_Car[] getAvailableCars (int start, int end)
TPS_Car getCar (int index)
int getCarNumber ()
int getId ()
double getIncome ()
TPS_Car getLeastRestrictedCar ()
TPS_Location getLocation ()
Collection< TPS_Person > getMembers (Sorting e)
int getNumCarDrivers ()
int getNumChildren ()
int getNumGrownups ()
int getNumHalfEmployed ()
int getNumMalePersons ()
int getNumberOfMembers ()
int getType ()
int hashCode ()
String toString ()
String toString (String prefix)
Private Attributes
final int id
household id
double income
household income
int type
household type
final TPS_Location location
household location
final SortedMap< Integer, TPS_Person > members
household member list
TPS_Car[] cars
number of cars in household
boolean leastRestrictedCarInitialized = false
TPS_Car leastRestrictedCar = null
Detailed Description
This class represents a household.
Author
mark_ma
Definition at line 25 of file TPS_Household.java.
Constructor & Destructor Documentation
TPS_Household() [1/2]
de.dlr.ivf.tapas.person.TPS_Household.TPS_Household (int id)
Constructor TODO: remove, this won't work - it is used by HouseholdSet only, which is not used
Parameters
id The id of the household
Definition at line 55 of file TPS_Household.java.
TPS_Household() [2/2]
de.dlr.ivf.tapas.person.TPS_Household.TPS_Household (int id, int income, int type, TPS_Location loc, TPS_Car[] cars)
Constructor
Parameters
id The id of the household
income The income of the household
type The type of the household
loc The location of the household
cars The cars that this household has
Definition at line 71 of file TPS_Household.java.
References type.
Member Function Documentation
addMember()
void de.dlr.ivf.tapas.person.TPS_Household.addMember (TPS_Person p)
Adds this person to the household
Parameters
p person to be added
Definition at line 87 of file TPS_Household.java.
References de.dlr.ivf.tapas.person.TPS_Person.getId(), and de.dlr.ivf.tapas.person.TPS_Person.setHousehold().
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.addPersonToHousehold().
getAllCars()
TPS_Car [] de.dlr.ivf.tapas.person.TPS_Household.getAllCars ()
Returns all cars in the household
Returns
an array of cars, null if no cars are present
Definition at line 97 of file TPS_Household.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Worker.processHousehold().
getAvailableCars() [1/2]
TPS_Car [] de.dlr.ivf.tapas.person.TPS_Household.getAvailableCars (double start, double end)
Returns the number of cars available in the household for the time period specified
Parameters
start time period start
end time period end
Returns
an array of available cars, null if no cars are available
Definition at line 108 of file TPS_Household.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Car.selectCar().
getAvailableCars() [2/2]
TPS_Car [] de.dlr.ivf.tapas.person.TPS_Household.getAvailableCars (int start, int end)
Returns the number of cars available in the household for the time period specified
Parameters
start time period start
end time period end
Returns
an array of available cars, null if no cars are available
Definition at line 119 of file TPS_Household.java.
getCar()
TPS_Car de.dlr.ivf.tapas.person.TPS_Household.getCar (int index)
Retrieves the car on the specified index or null otherwise
Parameters
index the index of the car
Returns
the car
Definition at line 143 of file TPS_Household.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Worker.processHousehold().
getCarNumber()
int de.dlr.ivf.tapas.person.TPS_Household.getCarNumber ()
Returns the number of cars in the household
Returns
number of cars
Definition at line 158 of file TPS_Household.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Preference.calcUtility(), de.dlr.ivf.tapas.constants.TPS_PersonGroup.fits(), de.dlr.ivf.tapas.person.TPS_Worker.processHousehold(), and de.dlr.ivf.tapas.plan.TPS_Plan.TPS_Plan().
getId()
int de.dlr.ivf.tapas.person.TPS_Household.getId ()
Returns the id of the household
Returns
household id
Definition at line 171 of file TPS_Household.java.
Referenced by de.dlr.ivf.tapas.person.TPS_HouseholdSet.addHousehold(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.batchStoreTrips(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.returnHousehold(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.returnHousehold().
getIncome()
double de.dlr.ivf.tapas.person.TPS_Household.getIncome ()
Returns the household income
Returns
household income
Definition at line 180 of file TPS_Household.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Preference.calcUtility(), de.dlr.ivf.tapas.plan.TPS_Plan.createOutput(), de.dlr.ivf.tapas.plan.TPS_Plan.TPS_Plan(), and de.dlr.ivf.tapas.plan.TPS_Plan.writeOutputStream().
getLeastRestrictedCar()
TPS_Car de.dlr.ivf.tapas.person.TPS_Household.getLeastRestrictedCar ()
Returns the least restricted car for this household or null, if no car is available.
Returns
the car
Definition at line 189 of file TPS_Household.java.
getLocation()
TPS_Location de.dlr.ivf.tapas.person.TPS_Household.getLocation ()
Returns the location of the household
Returns
household location
Definition at line 214 of file TPS_Household.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.batchStoreTrips(), de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixedBS.getDistributionSet(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessMode.getTravelTime(), de.dlr.ivf.tapas.plan.TPS_LocatedStay.selectLocation(), de.dlr.ivf.tapas.loc.TPS_SelectLocationWeightBased.selectLocationFromChoiceSet(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.selectLocationFromChoiceSet(), and de.dlr.ivf.tapas.plan.TPS_Plan.TPS_Plan().
getMembers()
Collection<TPS_Person> de.dlr.ivf.tapas.person.TPS_Household.getMembers (Sorting e)
Returns all members of a household sorted by age
Returns
all household members
Definition at line 223 of file TPS_Household.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Preference.calcUtility(), and de.dlr.ivf.tapas.person.TPS_Worker.processHousehold().
getNumberOfMembers()
int de.dlr.ivf.tapas.person.TPS_Household.getNumberOfMembers ()
Returns the number of members in this household
Returns
Definition at line 313 of file TPS_Household.java.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.createOutput(), de.dlr.ivf.tapas.person.TPS_Worker.processHousehold(), and de.dlr.ivf.tapas.plan.TPS_Plan.writeOutputStream().
getNumCarDrivers()
int de.dlr.ivf.tapas.person.TPS_Household.getNumCarDrivers ()
Definition at line 255 of file TPS_Household.java.
getNumChildren()
int de.dlr.ivf.tapas.person.TPS_Household.getNumChildren ()
Definition at line 265 of file TPS_Household.java.
getNumGrownups()
int de.dlr.ivf.tapas.person.TPS_Household.getNumGrownups ()
Definition at line 275 of file TPS_Household.java.
getNumHalfEmployed()
int de.dlr.ivf.tapas.person.TPS_Household.getNumHalfEmployed ()
Definition at line 285 of file TPS_Household.java.
getNumMalePersons()
int de.dlr.ivf.tapas.person.TPS_Household.getNumMalePersons ()
Definition at line 295 of file TPS_Household.java.
References de.dlr.ivf.tapas.constants.TPS_Sex.MALE, and de.dlr.ivf.tapas.constants.TPS_Sex.NON_RELEVANT.
getType()
int de.dlr.ivf.tapas.person.TPS_Household.getType ()
Returns the type of the household
Returns
household type
Definition at line 322 of file TPS_Household.java.
References type.
hashCode()
int de.dlr.ivf.tapas.person.TPS_Household.hashCode ()
Definition at line 332 of file TPS_Household.java.
toString() [1/2]
String de.dlr.ivf.tapas.person.TPS_Household.toString ()
Definition at line 342 of file TPS_Household.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Worker.call().
toString() [2/2]
String de.dlr.ivf.tapas.person.TPS_Household.toString (String prefix)
This method should print the object naturally with the given prefix.
Parameters
prefix
Returns
prefix + toString();
Implements de.dlr.ivf.tapas.util.ExtendedWritable.
Definition at line 351 of file TPS_Household.java.
Member Data Documentation
cars
TPS_Car [] de.dlr.ivf.tapas.person.TPS_Household.cars private
number of cars in household
Definition at line 42 of file TPS_Household.java.
id
final int de.dlr.ivf.tapas.person.TPS_Household.id private
household id
Definition at line 27 of file TPS_Household.java.
income
double de.dlr.ivf.tapas.person.TPS_Household.income private
household income
Definition at line 30 of file TPS_Household.java.
leastRestrictedCar
TPS_Car de.dlr.ivf.tapas.person.TPS_Household.leastRestrictedCar = null private
Definition at line 46 of file TPS_Household.java.
leastRestrictedCarInitialized
boolean de.dlr.ivf.tapas.person.TPS_Household.leastRestrictedCarInitialized = false private
Definition at line 44 of file TPS_Household.java.
location
final TPS_Location de.dlr.ivf.tapas.person.TPS_Household.location private
household location
Definition at line 36 of file TPS_Household.java.
members
final SortedMap<Integer, TPS_Person> de.dlr.ivf.tapas.person.TPS_Household.members private
household member list
Definition at line 39 of file TPS_Household.java.
type
int de.dlr.ivf.tapas.person.TPS_Household.type private
household type
Definition at line 33 of file TPS_Household.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/person/TPS_Household.java