TAPAS: de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.TripIntentionAnalyzer Class Reference
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.TripIntentionAnalyzer Class Reference
Public Member Functions
TripIntention assignTrip (TapasTrip trip)
Detailed Description
Definition at line 1084 of file TuMEnums.java.
Member Function Documentation
assignTrip()
TripIntention de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.TripIntentionAnalyzer.assignTrip (TapasTrip trip)
Definition at line 1086 of file TuMEnums.java.
References de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTrip.getActCode(), de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.TripIntention.getByActivity(), de.dlr.ivf.tapas.analyzer.inputfileconverter.Activity.getById(), de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTrip.isBackHome, and de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.TripIntention.TRIP_37.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/tum/constants/TuMEnums.java