TAPAS: de.dlr.ivf.tapas.tools.fileModifier.TPS_ModeChoiceTreeConverter Class Reference
de.dlr.ivf.tapas.tools.fileModifier.TPS_ModeChoiceTreeConverter Class Reference
Public Member Functions
TPS_ModeChoiceTreeConverter (String input, String output, String identifier)
void load ()
Static Public Member Functions
static void main (String[] args)
Public Attributes
Map< String, String > map
Private Member Functions
void save ()
Detailed Description
Class for converting the former mode choice tree files resulting from the analysis of datasets with the spss package "answer tree" and the subsequent transformation of the xml-files with the converter "CHAIDfromXML" into an sql-file to store in the db
Definition at line 21 of file TPS_ModeChoiceTreeConverter.java.
Constructor & Destructor Documentation
TPS_ModeChoiceTreeConverter()
de.dlr.ivf.tapas.tools.fileModifier.TPS_ModeChoiceTreeConverter.TPS_ModeChoiceTreeConverter (String input, String output, String identifier)
Definition at line 37 of file TPS_ModeChoiceTreeConverter.java.
References de.dlr.ivf.tapas.tools.fileModifier.TPS_ModeChoiceTreeConverter.map.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ModeChoiceTreeConverter.main().
Member Function Documentation
load()
void de.dlr.ivf.tapas.tools.fileModifier.TPS_ModeChoiceTreeConverter.load ()
This method imports the mode choice tree. The tree's root is in the first line after the header.
Definition at line 75 of file TPS_ModeChoiceTreeConverter.java.
References de.dlr.ivf.tapas.tools.fileModifier.TPS_ModeChoiceTreeConverter.map.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ModeChoiceTreeConverter.main().
main()
static void de.dlr.ivf.tapas.tools.fileModifier.TPS_ModeChoiceTreeConverter.main (String[] args) static
Definition at line 56 of file TPS_ModeChoiceTreeConverter.java.
References de.dlr.ivf.tapas.tools.fileModifier.TPS_ModeChoiceTreeConverter.load(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ModeChoiceTreeConverter.save(), and de.dlr.ivf.tapas.tools.fileModifier.TPS_ModeChoiceTreeConverter.TPS_ModeChoiceTreeConverter().
save()
void de.dlr.ivf.tapas.tools.fileModifier.TPS_ModeChoiceTreeConverter.save () private
Save the tree to a sql-file, whch can be imported via psql
Definition at line 153 of file TPS_ModeChoiceTreeConverter.java.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ModeChoiceTreeConverter.main().
Member Data Documentation
map
Map<String, String> de.dlr.ivf.tapas.tools.fileModifier.TPS_ModeChoiceTreeConverter.map
map for the conversion of the initial split parameter names into the new constants
Definition at line 26 of file TPS_ModeChoiceTreeConverter.java.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.importModeChoice(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ModeChoiceTreeConverter.load(), and de.dlr.ivf.tapas.tools.fileModifier.TPS_ModeChoiceTreeConverter.TPS_ModeChoiceTreeConverter().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/fileModifier/TPS_ModeChoiceTreeConverter.java