TAPAS: de.dlr.ivf.tapas.analyzer.gui.Control Class Reference
de.dlr.ivf.tapas.analyzer.gui.Control Class Reference
Public Member Functions
Control (TPS_ParameterClass parameterClass)
Control (String initialSimulation, TPS_ParameterClass parameterClass)
void actionPerformed (ActionEvent e)
StyledDocument getConsole ()
ControlInputInterface getInterface (Module module)
String getOutputPath ()
JPanel getPanel ()
List< File > getTripFiles ()
TapasTripReader getTripReader ()
boolean isActive (Module module)
Static Public Member Functions
static Control getInstance ()
Private Member Functions
void addProgressBar ()
File chooseDirectory (String type, JFrame f)
void createAndShowGUI (Map< Module, ControlInputInterface > col)
Private Attributes
String initSimulation
TripChooserPanel tripChooser
TapasTripReader tripReader
final TPS_ParameterClass parameterClass
final List< Core > threadList = new LinkedList<>()
FilesChooser tripFilesChooser
final String version = "0.9.0.0"
Static Private Attributes
static final Logger LOG = LogManager.getLogger(Control.class)
static String initOutputPath
static Control instance
Detailed Description
Einstiegsklasse des TapasAnalyzer. Zeitgleich ist Control ein CoreInputInterface, dadurch können andere Objekte die Zugriff auf diese Instanz haben unter anderem die selektierten Module abfragen.
Author
Marco
Definition at line 42 of file Control.java.
Constructor & Destructor Documentation
Control() [1/2]
de.dlr.ivf.tapas.analyzer.gui.Control.Control (TPS_ParameterClass parameterClass)
Parameters
parameterClass parameter container class
Definition at line 93 of file Control.java.
References de.dlr.ivf.tapas.analyzer.gui.Control.createAndShowGUI(), de.dlr.ivf.tapas.analyzer.gui.FileChooserHistoryManager.getLastDirectory(), de.dlr.ivf.tapas.analyzer.core.CoreInputInterface.Module.TUM, and de.dlr.ivf.tapas.analyzer.gui.FileChooserHistoryManager.updateLastDirectory().
Control() [2/2]
de.dlr.ivf.tapas.analyzer.gui.Control.Control (String initialSimulation, TPS_ParameterClass parameterClass)
Parameters
initialSimulation is the simulation that is selected on startup (if it is found in the database)
parameterClass parameter container class
Definition at line 155 of file Control.java.
Member Function Documentation
actionPerformed()
void de.dlr.ivf.tapas.analyzer.gui.Control.actionPerformed (ActionEvent e)
The timer check for progress
Definition at line 168 of file Control.java.
References de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripReader.getProgress().
addProgressBar()
void de.dlr.ivf.tapas.analyzer.gui.Control.addProgressBar () private
Definition at line 187 of file Control.java.
chooseDirectory()
File de.dlr.ivf.tapas.analyzer.gui.Control.chooseDirectory (String type, JFrame f) private
Definition at line 194 of file Control.java.
References de.dlr.ivf.tapas.analyzer.gui.FileChooserHistoryManager.updateLastDirectory().
createAndShowGUI()
void de.dlr.ivf.tapas.analyzer.gui.Control.createAndShowGUI (Map< Module, ControlInputInterface > col) private
set the outputpath
Definition at line 219 of file Control.java.
References de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripReader.close(), de.dlr.ivf.tapas.analyzer.gui.ControlInputInterface.getIndex(), de.dlr.ivf.tapas.analyzer.gui.TripChooserPanel.isReady(), de.dlr.ivf.tapas.analyzer.gui.Control.parameterClass, and de.dlr.ivf.tapas.analyzer.core.Core.setCoreInput().
Referenced by de.dlr.ivf.tapas.analyzer.gui.Control.Control().
getConsole()
StyledDocument de.dlr.ivf.tapas.analyzer.gui.Control.getConsole ()
Returns
UI component of status bar
Implements de.dlr.ivf.tapas.analyzer.core.CoreInputInterface.
Definition at line 401 of file Control.java.
getInstance()
static Control de.dlr.ivf.tapas.analyzer.gui.Control.getInstance () static
Definition at line 160 of file Control.java.
getInterface()
ControlInputInterface de.dlr.ivf.tapas.analyzer.gui.Control.getInterface (Module module)
Parameters
module
Returns
corresponding ControlInputInterface or null if not existent
Implements de.dlr.ivf.tapas.analyzer.core.CoreInputInterface.
Definition at line 405 of file Control.java.
getOutputPath()
String de.dlr.ivf.tapas.analyzer.gui.Control.getOutputPath ()
Returns
path of output files
Implements de.dlr.ivf.tapas.analyzer.core.CoreInputInterface.
Definition at line 409 of file Control.java.
getPanel()
JPanel de.dlr.ivf.tapas.analyzer.gui.Control.getPanel ()
Definition at line 413 of file Control.java.
getTripFiles()
List<File> de.dlr.ivf.tapas.analyzer.gui.Control.getTripFiles ()
Returns
paths of selected trip files
Implements de.dlr.ivf.tapas.analyzer.core.CoreInputInterface.
Definition at line 417 of file Control.java.
References de.dlr.ivf.tapas.analyzer.gui.FilesChooser.getFiles().
getTripReader()
TapasTripReader de.dlr.ivf.tapas.analyzer.gui.Control.getTripReader ()
Implements de.dlr.ivf.tapas.analyzer.core.CoreInputInterface.
Definition at line 422 of file Control.java.
References de.dlr.ivf.tapas.analyzer.gui.TripChooserPanel.getTripReader().
isActive()
boolean de.dlr.ivf.tapas.analyzer.gui.Control.isActive (Module module)
Parameters
module
Returns
returns true if the corresponding ControlInputInterface is currently in process
Implements de.dlr.ivf.tapas.analyzer.core.CoreInputInterface.
Definition at line 427 of file Control.java.
Member Data Documentation
initOutputPath
String de.dlr.ivf.tapas.analyzer.gui.Control.initOutputPath static private
Definition at line 50 of file Control.java.
initSimulation
String de.dlr.ivf.tapas.analyzer.gui.Control.initSimulation private
Definition at line 76 of file Control.java.
instance
Control de.dlr.ivf.tapas.analyzer.gui.Control.instance static private
Definition at line 51 of file Control.java.
LOG
final Logger de.dlr.ivf.tapas.analyzer.gui.Control.LOG = LogManager.getLogger(Control.class) static private
Logging object
Definition at line 49 of file Control.java.
parameterClass
final TPS_ParameterClass de.dlr.ivf.tapas.analyzer.gui.Control.parameterClass private
Definition at line 81 of file Control.java.
Referenced by de.dlr.ivf.tapas.analyzer.gui.Control.createAndShowGUI().
threadList
final List<Core> de.dlr.ivf.tapas.analyzer.gui.Control.threadList = new LinkedList<>() private
Definition at line 86 of file Control.java.
tripChooser
TripChooserPanel de.dlr.ivf.tapas.analyzer.gui.Control.tripChooser private
Definition at line 78 of file Control.java.
tripFilesChooser
FilesChooser de.dlr.ivf.tapas.analyzer.gui.Control.tripFilesChooser private
Definition at line 87 of file Control.java.
tripReader
TapasTripReader de.dlr.ivf.tapas.analyzer.gui.Control.tripReader private
Definition at line 79 of file Control.java.
version
final String de.dlr.ivf.tapas.analyzer.gui.Control.version = "0.9.0.0" private
Definition at line 88 of file Control.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/gui/Control.java