TAPAS: de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset Class Reference
de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset Class Reference
Classes
enum Key
Public Member Functions
QualityChartDataset (ArrayList< QualityChartData > data, EnumSet< Key > seriesKeys)
QualityChartDataset (ArrayList< QualityChartData > data)
DomainOrder getDomainOrder ()
int getItemCount (int series)
String getLabel (int series, int item)
int getSeriesCount ()
Comparable getSeriesKey (int series)
Number getX (int series, int item)
double getXValue (int series, int item)
Number getY (int series, int item)
double getYValue (int series, int item)
int indexOf (Comparable seriesKey)
String toString ()
Static Public Attributes
static final EnumSet< Key > DATASERIES = EnumSet.of(Key.DATA_HIGH, Key.DATA_MED, Key.DATA_LOW)
Private Member Functions
double setConfidenceInterval (ArrayList< QualityChartData > data)
void setGEH5 (ArrayList< QualityChartData > data)
Private Attributes
final EnumMap< Key, ArrayList< QualityChartData > > seriesCollection = new EnumMap<>(Key.class)
double max
Static Private Attributes
static final long serialVersionUID = 1105064554090557394L
Detailed Description
Definition at line 16 of file QualityChartDataset.java.
Constructor & Destructor Documentation
QualityChartDataset() [1/2]
de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.QualityChartDataset (ArrayList< QualityChartData > data, EnumSet< Key > seriesKeys)
Definition at line 26 of file QualityChartDataset.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.Key.getByQuality(), de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.Key.LOWER_CONFIDENCE, de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.Key.LOWER_GEH5, de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.max, de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.Key.OPTIMAL, de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.seriesCollection, de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.setConfidenceInterval(), and de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.setGEH5().
QualityChartDataset() [2/2]
de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.QualityChartDataset (ArrayList< QualityChartData > data)
Definition at line 55 of file QualityChartDataset.java.
Member Function Documentation
getDomainOrder()
DomainOrder de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.getDomainOrder ()
Definition at line 60 of file QualityChartDataset.java.
getItemCount()
int de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.getItemCount (int series)
Definition at line 65 of file QualityChartDataset.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.getSeriesKey(), and de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.seriesCollection.
getLabel()
String de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.getLabel (int series, int item)
Parameters
series
Returns
the label for data series and null otherwise.
Definition at line 77 of file QualityChartDataset.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.DATASERIES, de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.getSeriesKey(), and de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.seriesCollection.
getSeriesCount()
int de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.getSeriesCount ()
Definition at line 85 of file QualityChartDataset.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.seriesCollection.
getSeriesKey()
Comparable de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.getSeriesKey (int series)
Definition at line 91 of file QualityChartDataset.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.seriesCollection.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartFactory.QualityChartLegendGerator.generateLabel(), de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.getItemCount(), de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.getLabel(), de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.getXValue(), and de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.getYValue().
getX()
Number de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.getX (int series, int item)
Definition at line 96 of file QualityChartDataset.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.getXValue().
getXValue()
double de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.getXValue (int series, int item)
Definition at line 101 of file QualityChartDataset.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.getSeriesKey(), and de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.seriesCollection.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartFactory.createChart(), and de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.getX().
getY()
Number de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.getY (int series, int item)
Definition at line 112 of file QualityChartDataset.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.getYValue().
getYValue()
double de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.getYValue (int series, int item)
Definition at line 117 of file QualityChartDataset.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.getSeriesKey(), and de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.seriesCollection.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartFactory.createChart(), and de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.getY().
indexOf()
int de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.indexOf (Comparable seriesKey)
Parameters
seriesKey must be of type Key.
Exceptions
IllegalArgumentException if seriesKey is not of the right type.
Definition at line 133 of file QualityChartDataset.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.seriesCollection.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartFactory.createChart().
setConfidenceInterval()
double de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.setConfidenceInterval (ArrayList< QualityChartData > data) private
Confidence interval calculated using formulas from
Qualitätssicherung für die Anwendung von Verkehrsnachfragemodellen und Verkehrsprognosen, Merkblatt, BMVIT
Parameters
data
Returns
Definition at line 154 of file QualityChartDataset.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.Key.LOWER_CONFIDENCE, de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.max, de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.seriesCollection, and de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.Key.UPPER_CONFIDENCE.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.QualityChartDataset().
setGEH5()
void de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.setGEH5 (ArrayList< QualityChartData > data) private
Definition at line 176 of file QualityChartDataset.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.Key.LOWER_GEH5, de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.seriesCollection, and de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.Key.UPPER_GEH5.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.QualityChartDataset().
toString()
String de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.toString ()
Definition at line 189 of file QualityChartDataset.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.seriesCollection.
Member Data Documentation
DATASERIES
final EnumSet<Key> de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.DATASERIES = EnumSet.of(Key.DATA_HIGH, Key.DATA_MED, Key.DATA_LOW) static
Definition at line 18 of file QualityChartDataset.java.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartFactory.QualityChartLegendGerator.generateLabel(), and de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.getLabel().
max
double de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.max private
Definition at line 24 of file QualityChartDataset.java.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.QualityChartDataset(), and de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.setConfidenceInterval().
serialVersionUID
final long de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.serialVersionUID = 1105064554090557394L static private
Definition at line 22 of file QualityChartDataset.java.
seriesCollection
final EnumMap<Key, ArrayList<QualityChartData> > de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.seriesCollection = new EnumMap<>(Key.class) private
Definition at line 23 of file QualityChartDataset.java.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.getItemCount(), de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.getLabel(), de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.getSeriesCount(), de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.getSeriesKey(), de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.getXValue(), de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.getYValue(), de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.indexOf(), de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.QualityChartDataset(), de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.setConfidenceInterval(), de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.setGEH5(), and de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.toString().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/runtime/client/Graphics/QualityChart/QualityChartDataset.java