TAPAS: de.dlr.ivf.tapas.modechoice.TPS_UtilityMNL Class Reference
de.dlr.ivf.tapas.modechoice.TPS_UtilityMNL Class Reference abstract
Public Member Functions
double calculateDelta (TPS_Mode mode, TPS_Plan plan, double distanceNet, TPS_ModeChoiceContext mcc)
abstract double getCostOfMode (TPS_Mode mode, TPS_Plan plan, double travelTime, TPS_ModeChoiceContext mcc, SimulationType simType)
TPS_DiscreteDistribution< TPS_Mode > getDistributionSet (TPS_ModeSet modeSet, TPS_Plan plan, double distanceNet, TPS_ModeChoiceContext mcc)
void setParameterSet (TPS_Mode mode, double[] parameters)
Protected Attributes
HashMap< TPS_Mode, double[]> parameterMap = new HashMap<>()
Additional Inherited Members
Public Attributes inherited from de.dlr.ivf.tapas.modechoice.TPS_UtilityFunction
double walkDistanceBarrier = 3000
double walkDistanceShareAfterBarrier = 0.02
double walkDistanceBarrierStrong = 5000
double walkDistanceShareAfterBarrierStrong = 0.00
double minModeProbability = 0
Detailed Description
Utility function, which implements the pivot-point modifications according to the simple linear model in König/Axhausen 2001: "Verkehrsentscheidungen in Mobidrive"
Author
hein_mh
Definition at line 33 of file TPS_UtilityMNL.java.
Member Function Documentation
calculateDelta()
double de.dlr.ivf.tapas.modechoice.TPS_UtilityMNL.calculateDelta (TPS_Mode mode, TPS_Plan plan, double distanceNet, TPS_ModeChoiceContext mcc)
This function calculates the deltafactor in the utility values for the given parameters
Parameters
mode The mode to check
distanceNet The net distance
plan The plan we are working on
mcc
Returns
the delta factor of the utility
Implements de.dlr.ivf.tapas.modechoice.TPS_UtilityFunction.
Reimplemented in de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixedBS.
Definition at line 40 of file TPS_UtilityMNL.java.
References de.dlr.ivf.tapas.util.parameters.SimulationType.BASE, de.dlr.ivf.tapas.mode.TPS_ModeChoiceContext.carForThisPlan, de.dlr.ivf.tapas.constants.TPS_ActivityConstant.DUMMY, de.dlr.ivf.tapas.mode.TPS_ModeChoiceContext.fromStayLocation, de.dlr.ivf.tapas.modechoice.TPS_UtilityMNL.getCostOfMode(), de.dlr.ivf.tapas.plan.TPS_Plan.getPerson(), de.dlr.ivf.tapas.mode.TPS_Mode.getTravelTime(), de.dlr.ivf.tapas.mode.TPS_Mode.isUseBase(), de.dlr.ivf.tapas.util.parameters.SimulationType.SCENARIO, and de.dlr.ivf.tapas.mode.TPS_ModeChoiceContext.startTime.
getCostOfMode()
abstract double de.dlr.ivf.tapas.modechoice.TPS_UtilityMNL.getCostOfMode (TPS_Mode mode, TPS_Plan plan, double travelTime, TPS_ModeChoiceContext mcc, SimulationType simType) abstract
This method calculates the costs of the given mode.
Parameters
mode The mode to calculate
simType The simulation type (BASE or SCENARIO)
Returns
The cost for the mode
Reimplemented in de.dlr.ivf.tapas.modechoice.TPS_UtilityMNLFullComplexIntermodal, de.dlr.ivf.tapas.modechoice.TPS_UtilityMNLFullComplex, and de.dlr.ivf.tapas.modechoice.TPS_UtilityMNLAutomover.
Referenced by de.dlr.ivf.tapas.modechoice.TPS_UtilityMNL.calculateDelta(), and de.dlr.ivf.tapas.modechoice.TPS_UtilityMNL.getDistributionSet().
getDistributionSet()
TPS_DiscreteDistribution<TPS_Mode> de.dlr.ivf.tapas.modechoice.TPS_UtilityMNL.getDistributionSet (TPS_ModeSet modeSet, TPS_Plan plan, double distanceNet, TPS_ModeChoiceContext mcc)
This function gets the distribution set for the utilities of the modes
Parameters
modeSet A link to the calling class to access some data
plan the plan we are looking at
distanceNet the net distance in meters between the locations the
mcc
Returns
a distributionset, which holds the distribuion of the utilities of the modes
Implements de.dlr.ivf.tapas.modechoice.TPS_UtilityFunction.
Reimplemented in de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixedBS, and de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixed.
Definition at line 72 of file TPS_UtilityMNL.java.
References de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree.applyExpertKnowledge(), de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.BIKE, de.dlr.ivf.tapas.mode.TPS_ModeChoiceContext.carForThisPlan, de.dlr.ivf.tapas.constants.TPS_ActivityConstant.DUMMY, de.dlr.ivf.tapas.log.TPS_LoggingInterface.HierarchyLogLevel.EPISODE, de.dlr.ivf.tapas.util.TPS_FastMath.exp(), de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_USE_TAXI, de.dlr.ivf.tapas.mode.TPS_ModeChoiceContext.fromStayLocation, de.dlr.ivf.tapas.mode.TPS_Mode.get(), de.dlr.ivf.tapas.modechoice.TPS_UtilityMNL.getCostOfMode(), de.dlr.ivf.tapas.mode.TPS_ModeDistribution.getDistribution(), de.dlr.ivf.tapas.mode.TPS_Mode.getParameters(), de.dlr.ivf.tapas.plan.TPS_Plan.getPerson(), de.dlr.ivf.tapas.mode.TPS_Mode.getTravelTime(), de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.getValues(), de.dlr.ivf.tapas.mode.TPS_ModeChoiceContext.isBikeAvailable, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isFalse(), de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), de.dlr.ivf.tapas.mode.TPS_Mode.isType(), de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.modechoice.TPS_UtilityFunction.minModeProbability, de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.MIT, de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.MIT_PASS, de.dlr.ivf.tapas.mode.TPS_Mode.MODE_TYPE_ARRAY, de.dlr.ivf.tapas.mode.TPS_Mode.noConnection(), de.dlr.ivf.tapas.util.parameters.SimulationType.SCENARIO, de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.setValueByKey(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.SEVERE, de.dlr.ivf.tapas.mode.TPS_ModeChoiceContext.startTime, and de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.TAXI.
setParameterSet()
void de.dlr.ivf.tapas.modechoice.TPS_UtilityMNL.setParameterSet (TPS_Mode mode, double[] parameters)
Function to set the parameters for the utility function
Parameters
mode the mode we are parametrizing
parameters the parameters for the mode
Implements de.dlr.ivf.tapas.modechoice.TPS_UtilityFunction.
Definition at line 143 of file TPS_UtilityMNL.java.
Member Data Documentation
parameterMap
HashMap<TPS_Mode, double[]> de.dlr.ivf.tapas.modechoice.TPS_UtilityMNL.parameterMap = new HashMap<>() protected
A Hashmap for the mode depending parameters
Definition at line 38 of file TPS_UtilityMNL.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/modechoice/TPS_UtilityMNL.java