TAPAS: de.dlr.ivf.tapas.util.TPS_Argument Class Reference
de.dlr.ivf.tapas.util.TPS_Argument Class Reference
Classes
class TPS_ArgumentType
Static Public Member Functions
static Object[] checkArguments (String[] args, Collection< TPS_ArgumentType<?>> types)
static Object[] checkArguments (String[] args, TPS_ArgumentType<?>... types) throws IllegalArgumentException
Detailed Description
Class for runtime arguments pasted via the command line
Author
hein_mh
Definition at line 20 of file TPS_Argument.java.
Member Function Documentation
checkArguments() [1/2]
static Object [] de.dlr.ivf.tapas.util.TPS_Argument.checkArguments (String[] args, Collection< TPS_ArgumentType<?>> types) static
Method to check a set of arguments pated by a String array for values and a Collection of expected TPS_ArgumentType
Parameters
args the command line parameters provided
types the types needed
Returns
An array of correctly initialised arguments with values
Definition at line 29 of file TPS_Argument.java.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationControl.main(), de.dlr.ivf.tapas.runtime.server.SimulationServer.main(), de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.main(), de.dlr.ivf.tapas.TPS_Main.main(), and de.dlr.ivf.tapas.runtime.server.SimulationDaemon.SimulationDaemon().
checkArguments() [2/2]
static Object [] de.dlr.ivf.tapas.util.TPS_Argument.checkArguments (String[] args, TPS_ArgumentType<?>... types) throws IllegalArgumentException static
Method to check a set of arguments pasted by a String array for values and an array of expected TPS_ArgumentType
Parameters
args the command line parameters provided
types the types needed
Returns
An array of correctly initialised arguments with values
Exceptions
IllegalArgumentException if given and necessary arguments does not match
Definition at line 43 of file TPS_Argument.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/util/TPS_Argument.java