TAPAS: de.dlr.ivf.tapas.persistence.db.TPS_DB_IO Class Reference
de.dlr.ivf.tapas.persistence.db.TPS_DB_IO Class Reference
Public Member Functions
TPS_DB_IO (TPS_DB_IOManager pm) throws IOException
void clearConstants ()
TPS_RegionResultSet getTrafficAnalysisZonesAround (TPS_Region region, Locatable comingFrom, double arrivalDuration, Locatable goingTo, double departureDuration, TPS_ActivityConstant activityCode) throws SQLException
void initStart ()
TPS_ExpertKnowledgeTree readExpertKnowledgeTree () throws SQLException
void readMatrices (TPS_Region region) throws SQLException
TPS_ModeChoiceTree readModeChoiceTree () throws SQLException
TPS_Region readRegion () throws SQLException
TPS_SchemeSet readSchemeSet () throws SQLException
void readSettlementSystemCodes (String simulation)
void readUtilityFunction () throws SQLException
Static Public Member Functions
static double[] extractDoubleArray (ResultSet rs, String index) throws SQLException
static int[] extractIntArray (ResultSet rs, String index) throws SQLException
static String[] extractStringArray (ResultSet rs, String index) throws SQLException
static String matrixToSQLArray (Matrix array, int decimalPlaces)
Static Public Attributes
static final double INTERCHANGE_FACTOR = 0.01
Private Member Functions
TPS_Person addPersonToHousehold (ResultSet pRs) throws SQLException
int fetchNextSetOfHouseholds (TPS_Region region)
List< TPS_Household > loadHouseholds (TPS_Region region, List< Integer > hIDs)
void readActivity2LocationCodes ()
void readActivityConstantCodes ()
void readAgeClassCodes ()
void readCarCodes ()
void readDistanceCodes ()
void readDrivingLicenseCodes ()
void readIncomeCodes ()
void readLocationConstantCodes ()
void readMatrix (ParamString matrixName, ParamMatrix matrix, SimulationType simType, int sIndex) throws SQLException
void readMatrix (String matrixName, ParamMatrix matrix, SimulationType simType, int sIndex) throws SQLException
void readMatrix (ParamString matrixName, ParamMatrixMap matrix, SimulationType type, int sIndex)
void readModes ()
void readPersonGroupCodes ()
void readSexCodes ()
void readTAZInfos (ResultSet set, TPS_Region region, SimulationType type) throws SQLException
TPS_VariableMap readVariableMap (ResultSet set, int offset, int comment, double defaultValue) throws SQLException
void returnHousehold (TPS_Household hh)
void updateOccupancyTable (TPS_Region region)
void vacuumTempTables ()
Private Attributes
final int numberToFetch
The number of households to fetch per cpu.
final TPS_DB_IOManager PM
The reference to the persistence manager.
final Queue< TPS_Household > prefetchedHouseholds = new LinkedList<>()
A queue for prefetched households. Filled by getNextHouseholds .
int numberOfFetchedHouseholds
The number of households fetched for this chunk. should be cpu*numberToFetch or the remainders in db for the.
int lastCleanUp = -1
Static Private Attributes
static final int fetchSizePerProcessor = 256
static final int fetchSizePerProcessorPrefetchHouseholds = 256
static InetAddress ADDRESS = null
The ip address of this machine.
Detailed Description
Definition at line 53 of file TPS_DB_IO.java.
Constructor & Destructor Documentation
TPS_DB_IO()
de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.TPS_DB_IO (TPS_DB_IOManager pm) throws IOException
Constructor
Parameters
pm the managing class for sql-commands
Exceptions
IOException if the machine has no IP address, an exception is thrown.
Definition at line 79 of file TPS_DB_IO.java.
References de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_PREFETCH_ALL_HOUSEHOLDS, de.dlr.ivf.tapas.runtime.util.IPInfo.getEthernetInetAddress(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.getParameters(), and de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isTrue().
Member Function Documentation
addPersonToHousehold()
TPS_Person de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.addPersonToHousehold (ResultSet pRs) throws SQLException private
Here we create a person for a given SQL-ResultSet to add it to a household.
Parameters
pRs
Returns
Exceptions
SQLException
Definition at line 179 of file TPS_DB_IO.java.
References de.dlr.ivf.tapas.person.TPS_Household.addMember(), de.dlr.ivf.tapas.util.parameters.ParamValue.AVAILABILITY_FACTOR_BIKE, de.dlr.ivf.tapas.util.parameters.ParamValue.AVAILABILITY_FACTOR_CARSHARING, de.dlr.ivf.tapas.constants.TPS_DrivingLicenseInformation.CAR, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_USE_DRIVING_LICENCE, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_USE_ROBOTAXI, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_USE_SHOPPING_MOTIVES, de.dlr.ivf.tapas.person.TPS_Person.getAge(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getDoubleValue(), de.dlr.ivf.tapas.constants.TPS_Sex.getEnum(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getIntValue(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.getParameters(), de.dlr.ivf.tapas.constants.TPS_PersonGroup.getPersonGroupByTypeAndCode(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isFalse(), de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isTrue(), de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.person.TPS_Person.mayDriveACar(), de.dlr.ivf.tapas.util.parameters.ParamValue.MIN_AGE_CARSHARING, de.dlr.ivf.tapas.constants.TPS_DrivingLicenseInformation.NO_DRIVING_LICENSE, de.dlr.ivf.tapas.util.Randomizer.random(), de.dlr.ivf.tapas.person.TPS_Person.setCarPooler(), de.dlr.ivf.tapas.person.TPS_Person.setDrivingLicenseInformation(), de.dlr.ivf.tapas.constants.TPS_PersonGroup.TPS_PersonGroupType.TAPAS, de.dlr.ivf.tapas.log.TPS_LoggingInterface.HierarchyLogLevel.THREAD, de.dlr.ivf.tapas.constants.TPS_DrivingLicenseInformation.UNKNOWN, and de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.WARN.
clearConstants()
void de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.clearConstants ()
Empty all global static constants maps
Definition at line 230 of file TPS_DB_IO.java.
References de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ACTIVITY2LOCATIONS_MAP, de.dlr.ivf.tapas.constants.TPS_ActivityConstant.clearActivityConstantMap(), de.dlr.ivf.tapas.constants.TPS_AgeClass.clearAgeClassMap(), de.dlr.ivf.tapas.constants.TPS_Distance.clearDistanceMap(), de.dlr.ivf.tapas.constants.TPS_Income.clearIncomeMap(), de.dlr.ivf.tapas.constants.TPS_LocationConstant.clearLocationConstantMap(), de.dlr.ivf.tapas.mode.TPS_Mode.clearModeMap(), de.dlr.ivf.tapas.constants.TPS_PersonGroup.clearPersonGroupMap(), de.dlr.ivf.tapas.constants.TPS_SettlementSystem.clearSettlementSystemMap(), and de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.LOCATION2ACTIVITIES_MAP.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.init().
extractDoubleArray()
static double [] de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.extractDoubleArray (ResultSet rs, String index) throws SQLException static
Helper function to extract an sql-array to a Java double array
Parameters
rs The ResultSet containing a sql-Array
index The index position of the SQL-Array
Returns
A double array
Exceptions
SQLException
Definition at line 101 of file TPS_DB_IO.java.
Referenced by de.dlr.ivf.tapas.iteration.TPS_VisumConverter.readMatrix(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.readMatrixMap(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.readMatrixMap().
extractIntArray()
static int [] de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.extractIntArray (ResultSet rs, String index) throws SQLException static
Helper function to extract an sql-array to a Java int array
Parameters
rs The ResultSet containing a sql-Array
index The index position of the SQL-Array
Returns
A int array
Exceptions
SQLException
Definition at line 120 of file TPS_DB_IO.java.
Referenced by de.dlr.ivf.scripts.OTP2SQLMatrix.checkDBMatrix(), de.dlr.ivf.tapas.tools.TPS_MainDiagonalLengthEstimator.loadDistMatrix(), de.dlr.ivf.tapas.tools.TPS_CarRedistributor.loadHouseHolds(), de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ.loadMapping(), de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.loadMatrix(), de.dlr.ivf.tapas.tools.TPS_MatrixComparison.loadMatrix(), de.dlr.ivf.tapas.tools.TPS_SpeedAndDistanceValidator.loadMatrix(), de.dlr.ivf.scripts.SrVCalculator.loadTAZToMapping(), de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.processOpportunities(), de.dlr.ivf.tapas.iteration.TPS_VisumConverter.readMatrix(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.readMatrix(), de.dlr.ivf.tapas.tools.TPS_FeederCellManipulator.readMatrix(), de.dlr.ivf.tapas.tools.TPS_ParkAndRideRouter.readMatrix(), de.dlr.ivf.tapas.tools.TPS_PTBikeInterchangeMatrix.readMatrix(), de.dlr.ivf.tapas.tools.TPS_PTCarInterchangeMatrix.readMatrix(), de.dlr.ivf.scripts.SrVCalculator.readMatrixFromDB(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.readMatrixMap(), de.dlr.ivf.tapas.tools.TPS_CarRedistributor.recodeAllCars(), and de.dlr.ivf.tapas.tools.TPS_CarRedistributor.transformAllCars().
extractStringArray()
static String [] de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.extractStringArray (ResultSet rs, String index) throws SQLException static
Helper function to extract an sql-array to a Java String array
Parameters
rs The ResultSet containing a sql-Array
index The index position of the SQL-Array
Returns
A String array
Exceptions
SQLException
Definition at line 139 of file TPS_DB_IO.java.
Referenced by de.dlr.ivf.tapas.iteration.TPS_VisumConverter.readMatrix(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.readMatrixMap(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.readMatrixMap().
fetchNextSetOfHouseholds()
int de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.fetchNextSetOfHouseholds (TPS_Region region) private
Here we load a new set of households and return the number of fetched ones. We have to check if the simulation is running and still existent. Someone might have deleted it! Then we fetch the unfinished households from any previous simulation (crashed sim pick up). Then we mark new households in the temporary household table (job table), that we will pick them. Here we have to check for race conditions with other computers! Next we load the household IDs Then we load the persons and finally we store them in the household-pool and return.
Parameters
region with households to fetch
Returns
the number of fetched households
Definition at line 269 of file TPS_DB_IO.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_HOUSEHOLD_TMP, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_SIMULATIONS, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.executeQuery(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.getDbConnector(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.getParameters(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.INFO, de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.util.parameters.ParamString.RUN_IDENTIFIER, and de.dlr.ivf.tapas.log.TPS_LoggingInterface.HierarchyLogLevel.THREAD.
getTrafficAnalysisZonesAround()
TPS_RegionResultSet de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.getTrafficAnalysisZonesAround (TPS_Region region, Locatable comingFrom, double arrivalDuration, Locatable goingTo, double departureDuration, TPS_ActivityConstant activityCode) throws SQLException
Method to return the locations, which are possible to use for the given activity.
Parameters
region The region to look in
comingFrom The location where the person is currently present
arrivalDuration the duration of getting to comingFrom
goingTo the location the person wants to visit afterwards
departureDuration the time he has to reach goingTo
activityCode The activity code for this query
Returns
A TPS_RegionResultSet of appropriate locations
Exceptions
SQLException Exceptions during sql-queries
Definition at line 411 of file TPS_DB_IO.java.
References de.dlr.ivf.tapas.persistence.TPS_RegionResultSet.add(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.BEHAVIOUR, de.dlr.ivf.tapas.persistence.TPS_RegionResultSet.clear(), de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_LOCATION_TMP, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_TAZ, de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.executeQuery(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.Behaviour.FAT, de.dlr.ivf.tapas.loc.TPS_Location.getData(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getDoubleValue(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getIntValue(), de.dlr.ivf.tapas.loc.TPS_Region.getLocation(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.getParameters(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.loc.TPS_Region.getTrafficAnalysisZone(), de.dlr.ivf.tapas.util.TPS_Geometrics.isBetweenLine(), de.dlr.ivf.tapas.util.TPS_Geometrics.isWithin(), de.dlr.ivf.tapas.util.parameters.ParamValue.MAX_SYSTEM_SPEED, de.dlr.ivf.tapas.util.parameters.ParamValue.MAX_TRIES_LOCATION_SELECTION, de.dlr.ivf.tapas.util.parameters.ParamValue.MIN_DIST, de.dlr.ivf.tapas.util.Randomizer.random(), de.dlr.ivf.tapas.persistence.TPS_RegionResultSet.size(), and de.dlr.ivf.tapas.constants.TPS_ActivityConstant.TPS_ActivityCodeType.ZBE.
initStart()
void de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.initStart ()
Method to initializes some variables for starting the new simulation
Definition at line 533 of file TPS_DB_IO.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.DBTripFetcher(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.init().
loadHouseholds()
List<TPS_Household> de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.loadHouseholds (TPS_Region region, List< Integer > hIDs) private
Here we load the households, persons and car data from the DB for a given list of household ids! First we look at our household-map if the house hold is already loaded (prefetched). If we do not find it, we load it with all attributes, cars and persons. Finally we store the households in a list and return this list.
Parameters
region in which the households are
hIDs list of household ids
Returns
list of loaded households
Definition at line 548 of file TPS_DB_IO.java.
References de.dlr.ivf.tapas.person.TPS_Car.cloneCar(), de.dlr.ivf.tapas.util.parameters.ParamString.DB_CAR_FLEET_KEY, de.dlr.ivf.tapas.util.parameters.ParamString.DB_HOUSEHOLD_AND_PERSON_KEY, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_CARS, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_HOUSEHOLD, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_PERSON, de.dlr.ivf.tapas.person.TPS_Car.EMISSION_TYPE_ARRAY, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.executeQuery(), de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_PREFETCH_ALL_HOUSEHOLDS, de.dlr.ivf.tapas.person.TPS_Car.FUEL_TYPE_ARRAY, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getDoubleValue(), de.dlr.ivf.tapas.person.TPS_Car.getId(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getIntValue(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.getParameters(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.loc.TPS_Region.getTrafficAnalysisZone(), de.dlr.ivf.tapas.util.parameters.ParamValue.GLOBAL_AUTOMATION_LEVEL, de.dlr.ivf.tapas.util.parameters.ParamValue.GLOBAL_AUTOMATION_PROBABILITY, de.dlr.ivf.tapas.constants.TPS_LocationConstant.HOME, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.INFO, de.dlr.ivf.tapas.person.TPS_Car.init(), de.dlr.ivf.tapas.loc.TPS_Location.initCapacity(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isFalse(), de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isTrue(), de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.person.TPS_Household.Sorting.NONE, de.dlr.ivf.tapas.person.TPS_Car.setAutomation(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.HierarchyLogLevel.THREAD, type, and de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.WARN.
matrixToSQLArray()
static String de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.matrixToSQLArray (Matrix array, int decimalPlaces) static
Method to convert matrixelements to a sql-parsable array
Parameters
array the array
decimalPlaces number of decimal places for the string
Returns
Definition at line 155 of file TPS_DB_IO.java.
References de.dlr.ivf.tapas.util.Matrix.getNumberOfColums(), de.dlr.ivf.tapas.util.Matrix.getValue(), and de.dlr.ivf.tapas.util.Matrix.sIndex.
Referenced by de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.saveMatrices(), de.dlr.ivf.tapas.tools.TPS_SubnetMatrixIntegrator.saveMatrix(), de.dlr.ivf.scripts.InterCellTrafficImporter.saveMatrix(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.storeInDB(), de.dlr.ivf.tapas.tools.TPS_ParkingSpaceAproximator.storeSQLMatrix(), and de.dlr.ivf.tapas.runtime.sumoDaemon.SumoMatrixImporter.writeMatrix().
readActivity2LocationCodes()
void de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readActivity2LocationCodes () private
Reads and assigns activities to locations and vice versa
Note: First the activity and locations must be read, i.e. readActivityConstantCodes and readLocationConstantCodes must be called beforehand
Definition at line 783 of file TPS_DB_IO.java.
References de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ACTIVITY2LOCATIONS_MAP, de.dlr.ivf.tapas.util.parameters.ParamString.DB_ACTIVITY_2_LOCATION_KEY, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_CONSTANT_ACTIVITY_2_LOCATION, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.executeQuery(), de.dlr.ivf.tapas.constants.TPS_ActivityConstant.getActivityCodeByTypeAndCode(), de.dlr.ivf.tapas.constants.TPS_LocationConstant.getLocationCodeByTypeAndCode(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.getParameters(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.LOCATION2ACTIVITIES_MAP, de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.constants.TPS_LocationConstant.TPS_LocationCodeType.TAPAS, and de.dlr.ivf.tapas.constants.TPS_ActivityConstant.TPS_ActivityCodeType.ZBE.
readActivityConstantCodes()
void de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readActivityConstantCodes () private
Reads all activity constants codes from the database and stores them in to a global static map An ActivityConstant has the form (id, 3-tuples of (name, code, type), istrip, isfix, attr) Example: (5, ("school", "2", "TAPAS"), ("SCHOOL", "410", "MCT"), True, False, "SCHOOL")
Definition at line 817 of file TPS_DB_IO.java.
References de.dlr.ivf.tapas.constants.TPS_ActivityConstant.addActivityConstantToMap(), de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_CONSTANT_ACTIVITY, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.executeQuery(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.getParameters(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), and de.dlr.ivf.tapas.log.TPS_Logger.log().
readAgeClassCodes()
void de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readAgeClassCodes () private
Reads all age classes codes from the database and stores them in to a global static map An AgeClass has the form (id, 3-tuples of (name, code, type), min, max) Example: (5, (under 35, 7, STBA), (under 45, 4, PersGroup), 30, 34)
Definition at line 851 of file TPS_DB_IO.java.
References de.dlr.ivf.tapas.constants.TPS_AgeClass.addAgeClassToMap(), de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_CONSTANT_AGE, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.executeQuery(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.getParameters(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), and de.dlr.ivf.tapas.log.TPS_Logger.log().
readCarCodes()
void de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readCarCodes () private
Reads all car codes from the database and stores them through enums A CarCode has the form (name_cars, code_cars) Example: (YES, 1)
Definition at line 882 of file TPS_DB_IO.java.
References de.dlr.ivf.tapas.constants.TPS_CarCode.code, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_CONSTANT_CARS, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.executeQuery(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.getParameters(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.log.TPS_Logger.log(), and de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.WARN.
readDistanceCodes()
void de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readDistanceCodes () private
Reads all distance codes from the database and stores them in to a global static map A Distance has the form (id, 3-tuples of (name, code, type), max) Example: (5, (under 5k, 1, VOT), (under 2k, 2000, MCT), 2000)
Definition at line 931 of file TPS_DB_IO.java.
References de.dlr.ivf.tapas.constants.TPS_Distance.addDistanceToMap(), de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_CONSTANT_DISTANCE, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.executeQuery(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.getParameters(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), and de.dlr.ivf.tapas.log.TPS_Logger.log().
readDrivingLicenseCodes()
void de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readDrivingLicenseCodes () private
Reads all driving license codes from the database and stores them through enums A DrivingLicenseCodes has the form (name_dli, code_dli) Example: (no, 2)
Definition at line 956 of file TPS_DB_IO.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_CONSTANT_DRIVING_LICENSE_INFORMATION, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.executeQuery(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.getParameters(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.constants.TPS_DrivingLicenseInformation.setCode(), and de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.WARN.
readExpertKnowledgeTree()
TPS_ExpertKnowledgeTree de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readExpertKnowledgeTree () throws SQLException
This method reads the mode choice tree used for the pivot-point model.
Returns
The tree read from the db.
Exceptions
SQLException
Definition at line 985 of file TPS_DB_IO.java.
References de.dlr.ivf.tapas.modechoice.TPS_Node.addChild(), de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_EKT, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_EKT, de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.executeQuery(), de.dlr.ivf.tapas.modechoice.TPS_Node.getChild(), de.dlr.ivf.tapas.mode.TPS_Mode.getConstants(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.getParameters(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isDefined(), de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.setValueByPosition(), and de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.size().
readIncomeCodes()
void de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readIncomeCodes () private
Reads all income codes from the database and stores them in to a global static map An Income has the form (id, name, code, max) Example: (5, under 2600, 4, 2600)
Definition at line 1069 of file TPS_DB_IO.java.
References de.dlr.ivf.tapas.constants.TPS_Income.addToIncomeMap(), de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_CONSTANT_INCOME, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.executeQuery(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.getParameters(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), and de.dlr.ivf.tapas.log.TPS_Logger.log().
readLocationConstantCodes()
void de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readLocationConstantCodes () private
Reads all location constant codes from the database and stores them in to a global static map A LocationConstant has the form (id, 3-tuples of (name, code, type)) Example: (5, (club, 7, GENERAL), (club, 7, TAPAS))
Definition at line 1090 of file TPS_DB_IO.java.
References de.dlr.ivf.tapas.constants.TPS_LocationConstant.addLocationCodeToMap(), de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_CONSTANT_LOCATION, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.executeQuery(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.getParameters(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), and de.dlr.ivf.tapas.log.TPS_Logger.log().
readMatrices()
void de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readMatrices (TPS_Region region) throws SQLException
Method to read all matrices for the given region (travel times, distances etc.)
Parameters
region The region to look for.
Exceptions
SQLException
Definition at line 1118 of file TPS_DB_IO.java.
References de.dlr.ivf.tapas.util.parameters.ParamMatrixMap.ARRIVAL_BIKE, de.dlr.ivf.tapas.util.parameters.ParamMatrixMap.ARRIVAL_MIT, de.dlr.ivf.tapas.util.parameters.ParamMatrixMap.ARRIVAL_PT, de.dlr.ivf.tapas.util.parameters.ParamMatrixMap.ARRIVAL_WALK, de.dlr.ivf.tapas.util.parameters.ParamValue.AVERAGE_DISTANCE_PT_STOP, de.dlr.ivf.tapas.util.parameters.SimulationType.BASE, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_BLOCK_NEXT_PT_STOP, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_ACCESS_BIKE, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_ACCESS_BIKE_BASE, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_ACCESS_MIT, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_ACCESS_MIT_BASE, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_ACCESS_PT, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_ACCESS_PT_BASE, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_ACCESS_WALK, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_ACCESS_WALK_BASE, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_DISTANCES_BIKE, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_DISTANCES_PT, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_DISTANCES_STREET, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_DISTANCES_WALK, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_EGRESS_BIKE, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_EGRESS_BIKE_BASE, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_EGRESS_MIT, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_EGRESS_MIT_BASE, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_EGRESS_PT, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_EGRESS_PT_BASE, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_EGRESS_WALK, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_EGRESS_WALK_BASE, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_INTERCHANGE_PT, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_INTERCHANGE_PT_BASE, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_TT_BIKE, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_TT_BIKE_BASE, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_TT_MIT, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_TT_MIT_BASE, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_TT_PT, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_TT_PT_BASE, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_TT_WALK, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_TT_WALK_BASE, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_PTBIKE_ACCESS_TAZ, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_PTBIKE_EGRESS_TAZ, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_PTBIKE_INTERCHANGES, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_PTCAR_ACCESS_TAZ, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_PTCAR_INTERCHANGES, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_BLOCK_NEXT_PT_STOP, de.dlr.ivf.tapas.util.parameters.ParamMatrix.DISTANCES_BIKE, de.dlr.ivf.tapas.util.parameters.ParamMatrix.DISTANCES_BL, de.dlr.ivf.tapas.util.parameters.ParamMatrix.DISTANCES_PT, de.dlr.ivf.tapas.util.parameters.ParamMatrix.DISTANCES_STREET, de.dlr.ivf.tapas.util.parameters.ParamMatrix.DISTANCES_WALK, de.dlr.ivf.tapas.util.parameters.ParamMatrixMap.EGRESS_BIKE, de.dlr.ivf.tapas.util.parameters.ParamMatrixMap.EGRESS_MIT, de.dlr.ivf.tapas.util.parameters.ParamMatrixMap.EGRESS_PT, de.dlr.ivf.tapas.util.parameters.ParamMatrixMap.EGRESS_WALK, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_RUN_SZENARIO, de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.functionExecuteQuery(), de.dlr.ivf.tapas.util.TPS_Geometrics.getDistance(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.getParameters(), de.dlr.ivf.tapas.loc.TPS_Region.getSmallestId(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.loc.TPS_Region.getTrafficAnalysisZones(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.INFO, de.dlr.ivf.tapas.util.parameters.ParamMatrixMap.INTERCHANGES_PT, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isDefined(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isTrue(), de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.util.parameters.ParamValue.MIN_DIST, de.dlr.ivf.tapas.util.parameters.ParamMatrixMap.PTBIKE_ACCESS_TAZ, de.dlr.ivf.tapas.util.parameters.ParamMatrixMap.PTBIKE_EGRESS_TAZ, de.dlr.ivf.tapas.util.parameters.ParamMatrixMap.PTBIKE_INTERCHANGES, de.dlr.ivf.tapas.util.parameters.ParamMatrixMap.PTCAR_ACCESS_TAZ, de.dlr.ivf.tapas.util.parameters.ParamMatrixMap.PTCAR_INTERCHANGES, de.dlr.ivf.tapas.util.parameters.SimulationType.SCENARIO, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.setMatrix(), de.dlr.ivf.tapas.util.Matrix.setValue(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.setValue(), de.dlr.ivf.tapas.util.parameters.ParamMatrixMap.TRAVEL_TIME_BIKE, de.dlr.ivf.tapas.util.parameters.ParamMatrixMap.TRAVEL_TIME_MIT, de.dlr.ivf.tapas.util.parameters.ParamMatrixMap.TRAVEL_TIME_PT, and de.dlr.ivf.tapas.util.parameters.ParamMatrixMap.TRAVEL_TIME_WALK.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.init().
readMatrix() [1/3]
void de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readMatrix (ParamString matrixName, ParamMatrix matrix, SimulationType simType, int sIndex) throws SQLException private
Method to read a single specified matrix
Parameters
matrixName The name for this matrix as a String
matrix the matrix to store in
simType the simulation type
sIndex the index for reading in the db. Should be zero.
Exceptions
SQLException
Definition at line 1332 of file TPS_DB_IO.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.getParameters(), and de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString().
readMatrix() [2/3]
void de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readMatrix (ParamString matrixName, ParamMatrixMap matrix, SimulationType type, int sIndex) private
Method to read a single specified matrix map
Parameters
matrixName The name for this matrix map
matrix the matrixmap to store in
type The Simulation type to store to
sIndex the index for reading in the db. Should be zero.
Definition at line 1375 of file TPS_DB_IO.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.getDbConnector(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.getParameters(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.INFO, de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.paramMatrixMapClass, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.readMatrixMap(), de.dlr.ivf.tapas.util.parameters.ParamMatrixMapClass.setMatrixMap(), and type.
readMatrix() [3/3]
void de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readMatrix (String matrixName, ParamMatrix matrix, SimulationType simType, int sIndex) throws SQLException private
Method to read a single specified matrix
Parameters
matrixName The name for this matrix
matrix the matrix to store in
simType the simulation type
sIndex the index for reading in the db. Should be zero.
Exceptions
SQLException
Definition at line 1345 of file TPS_DB_IO.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.HierarchyLogLevel.CLIENT, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_MATRICES, de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.executeQuery(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.getParameters(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.INFO, de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.setMatrix(), de.dlr.ivf.tapas.util.Matrix.setRawValue(), and de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.WARN.
readModeChoiceTree()
TPS_ModeChoiceTree de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readModeChoiceTree () throws SQLException
This method reads the mode choice tree used for the pivot-point model.
Returns
The tree read from the db.
Exceptions
SQLException
Definition at line 1389 of file TPS_DB_IO.java.
References de.dlr.ivf.tapas.modechoice.TPS_Node.addChild(), de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MCT, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_MCT, de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.executeQuery(), de.dlr.ivf.tapas.modechoice.TPS_Node.getChild(), de.dlr.ivf.tapas.mode.TPS_Mode.getConstants(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.getParameters(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), and de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.setValueByPosition().
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.init().
readModes()
void de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readModes () private
Reads all mode constant codes from the database and stores them in to a global static map A Mode has the form (id, 3-tuples of (name, code, type), isfix) Example: (3, (MIT, 2, MCT), (MIT, 1, VOT), true)
Definition at line 1435 of file TPS_DB_IO.java.
References de.dlr.ivf.tapas.mode.TPS_Mode.addModeToMap(), de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_CONSTANT_MODE, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.executeQuery(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.getParameters(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.log.TPS_Logger.log(), and name.
readPersonGroupCodes()
void de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readPersonGroupCodes () private
Reads all person group codes from the database and stores them in to a global static map A PersGroup has the form (id, 3-tuples of (name, code, type), code_ageclass, code_sex, code_cars, persType) Example: (3, (RoP65-74, 12, VISEVA_R), 6, ,1, 2, RETIREE)
Definition at line 1484 of file TPS_DB_IO.java.
References de.dlr.ivf.tapas.constants.TPS_PersonGroup.addPersonGroupToMap(), de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_CONSTANT_PERSON, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.executeQuery(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.getParameters(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), and de.dlr.ivf.tapas.log.TPS_Logger.log().
readRegion()
TPS_Region de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readRegion () throws SQLException
Reads all region specific parameters from the DB
Returns
The region, specified in the Parameter set
Exceptions
SQLException Error during SQL-processing
Definition at line 1512 of file TPS_DB_IO.java.
References de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.addLocation(), de.dlr.ivf.tapas.loc.TPS_Block.addLocation(), de.dlr.ivf.tapas.loc.TPS_Region.addLocation(), de.dlr.ivf.tapas.loc.TPS_CFN.addToCFN4Map(), de.dlr.ivf.tapas.loc.TPS_CFN.addToCFNXMap(), de.dlr.ivf.tapas.util.parameters.SimulationType.BASE, de.dlr.ivf.tapas.log.TPS_LoggingInterface.HierarchyLogLevel.CLIENT, de.dlr.ivf.tapas.loc.TPS_Region.createTrafficAnalysisZone(), de.dlr.ivf.tapas.util.parameters.ParamString.DB_ACTIVITY_CNF_KEY, de.dlr.ivf.tapas.util.parameters.ParamString.DB_ACTIVITY_POTENTIAL_KEY, de.dlr.ivf.tapas.util.parameters.ParamValue.DB_HH_SAMPLE_SIZE, de.dlr.ivf.tapas.util.parameters.ParamString.DB_LOCATION_KEY, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_BLOCK_NEXT_PT_STOP, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_BLOCK_SCORES, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_FEES_TOLLS, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_TAZ_INTRA_MIT_INFOS, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_TAZ_INTRA_MIT_INFOS_BASE, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_TAZ_INTRA_PT_INFOS, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_TAZ_INTRA_PT_INFOS_BASE, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_TAZ_SCORES, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_VOT, de.dlr.ivf.tapas.util.parameters.ParamString.DB_REGION_CNF_KEY, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_BLOCK, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_BLOCK_NEXT_PT_STOP, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_BLOCK_SCORES, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_CFN4, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_CFNX, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_LOCATION, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_TAZ, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_TAZ_FEES_TOLLS, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_TAZ_INTRA_MIT_INFOS, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_TAZ_INTRA_PT_INFOS, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_TAZ_SCORES, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_VOT, de.dlr.ivf.tapas.util.parameters.ParamValue.DEFAULT_VOT, de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.executeQuery(), de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_RUN_SZENARIO, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_USE_LOCATION_GROUPS, de.dlr.ivf.tapas.constants.TPS_SettlementSystem.TPS_SettlementSystemType.FORDCP, de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.getBlock(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getDoubleValue(), de.dlr.ivf.tapas.constants.TPS_LocationConstant.getLocationCodeByTypeAndCode(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.getParameters(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.loc.TPS_Region.getTrafficAnalysisZone(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.INFO, de.dlr.ivf.tapas.loc.TPS_Location.initCapacity(), de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.initFeesTolls(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isDefined(), de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isTrue(), de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.util.parameters.SimulationType.SCENARIO, de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.setBbrType(), de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.setCenter(), de.dlr.ivf.tapas.loc.TPS_Block.setCenter(), de.dlr.ivf.tapas.loc.TPS_Region.setCfn(), de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.setExternalId(), de.dlr.ivf.tapas.loc.TPS_Block.setNearestPubTransStop(), de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.setPNR(), de.dlr.ivf.tapas.loc.TPS_Region.setPotential(), de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.setRestricted(), de.dlr.ivf.tapas.loc.TPS_Block.setScore(), de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.setScore(), de.dlr.ivf.tapas.loc.TPS_Block.setScoreCat(), de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.setScoreCat(), de.dlr.ivf.tapas.loc.TPS_Region.setValuesOfTime(), de.dlr.ivf.tapas.constants.TPS_ActivityConstant.TPS_ActivityCodeType.TAPAS, de.dlr.ivf.tapas.constants.TPS_LocationConstant.TPS_LocationCodeType.TAPAS, and de.dlr.ivf.tapas.constants.TPS_SettlementSystem.TPS_SettlementSystemType.TAPAS.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.init().
readSchemeSet()
TPS_SchemeSet de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readSchemeSet () throws SQLException
This method reads the scheme set, scheme class distribution values and all episodes from the db.
Returns
The TPS_SchemeSet containing all episodes.
Exceptions
SQLException
Definition at line 1753 of file TPS_DB_IO.java.
References de.dlr.ivf.tapas.scheme.TPS_SchemeSet.addDistribution(), de.dlr.ivf.tapas.scheme.TPS_Scheme.addEpisode(), de.dlr.ivf.tapas.util.parameters.ParamString.DB_EPISODE_KEY, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_SCHEME_CLASS_DISTRIBUTION, de.dlr.ivf.tapas.util.parameters.ParamString.DB_SCHEME_CLASS_DISTRIBUTION_KEY, de.dlr.ivf.tapas.util.parameters.ParamString.DB_SCHEME_CLASS_KEY, de.dlr.ivf.tapas.util.parameters.ParamString.DB_SCHEME_KEY, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_EPISODE, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_SCHEME, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_SCHEME_CLASS, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_SCHEME_CLASS_DISTRIBUTION, de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.executeQuery(), de.dlr.ivf.tapas.constants.TPS_ActivityConstant.getActivityCodeByTypeAndCode(), de.dlr.ivf.tapas.constants.TPS_ActivityConstant.getCode(), de.dlr.ivf.tapas.scheme.TPS_Scheme.getId(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getIntValue(), de.dlr.ivf.tapas.scheme.TPS_Episode.getOriginalDuration(), de.dlr.ivf.tapas.scheme.TPS_Episode.getOriginalStart(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.getParameters(), de.dlr.ivf.tapas.constants.TPS_PersonGroup.getPersonGroupByTypeAndCode(), de.dlr.ivf.tapas.scheme.TPS_Stay.getPriority(), de.dlr.ivf.tapas.scheme.TPS_SchemeClass.getScheme(), de.dlr.ivf.tapas.scheme.TPS_SchemeSet.getSchemeClass(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.scheme.TPS_SchemeSet.init(), de.dlr.ivf.tapas.scheme.TPS_Episode.isHomePart, de.dlr.ivf.tapas.scheme.TPS_Episode.isStay(), de.dlr.ivf.tapas.constants.TPS_ActivityConstant.isTrip, de.dlr.ivf.tapas.constants.TPS_ActivityConstant.TPS_ActivityCodeType.PRIORITY, de.dlr.ivf.tapas.util.parameters.ParamValue.SEC_TIME_SLOT, de.dlr.ivf.tapas.scheme.TPS_Stay.setActCode(), de.dlr.ivf.tapas.scheme.TPS_Episode.setOriginalDuration(), de.dlr.ivf.tapas.scheme.TPS_Episode.setOriginalStart(), de.dlr.ivf.tapas.scheme.TPS_SchemeClass.setTimeDistribution(), de.dlr.ivf.tapas.constants.TPS_PersonGroup.TPS_PersonGroupType.TAPAS, de.dlr.ivf.tapas.scheme.TPS_Episode.tourNumber, and de.dlr.ivf.tapas.constants.TPS_ActivityConstant.TPS_ActivityCodeType.ZBE.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.init().
readSettlementSystemCodes()
void de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readSettlementSystemCodes (String simulation)
Reads all settlement system codes from the database and stores them in to a global static map A SettlementSystem has the form (id, 3-tuples of (name, code, type)) Example: (7, ("R1, K1, Kernstadt > 500000", "1", "FORDCP"))
Definition at line 1864 of file TPS_DB_IO.java.
References de.dlr.ivf.tapas.constants.TPS_SettlementSystem.addSettlementSystemToMap(), de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_CONSTANT_SETTLEMENT, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.executeQuery(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.getDbConnector(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.getParameters(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.log.TPS_Logger.log(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.readSingleParameter().
Referenced by de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.DBTripFetcher().
readSexCodes()
void de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readSexCodes () private
Reads all sex codes from the database and stores them through enums A SexCodes has the form (name_sex, code_sex) Example: (FEMALE, 2)
Definition at line 1901 of file TPS_DB_IO.java.
References de.dlr.ivf.tapas.constants.TPS_Sex.code, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_CONSTANT_SEX, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.executeQuery(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.getParameters(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.log.TPS_Logger.log(), and de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.WARN.
readTAZInfos()
void de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readTAZInfos (ResultSet set, TPS_Region region, SimulationType type) throws SQLException private
This method processes the ResultSet for the intra cell-infos like travel speed or pt zone
Parameters
set The ResultSet from a appropriate sql-query. Must contain: info_taz_id, beeline_factor_mit, average_speed_mit, average_speed_pt, has_intra_traffic_mit, has_intra_traffic_pt, pt_zone
region The region, where the infos are stored in
type theSimulationType (BASE/SCENARIO)
Exceptions
SQLException
Definition at line 1930 of file TPS_DB_IO.java.
References de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.getSimulationTypeValues(), de.dlr.ivf.tapas.loc.TPS_Region.getTrafficAnalysisZone(), de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.setAverageSpeedMIT(), de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.setAverageSpeedPT(), de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.setBeelineFactorMIT(), de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.setIntraMITTrafficAllowed(), de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.setIntraPTTrafficAllowed(), de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.setPtZone(), and type.
readUtilityFunction()
void de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readUtilityFunction () throws SQLException
Method to read the parameters of the utility function
Exceptions
SQLException
Definition at line 1950 of file TPS_DB_IO.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MODEL_PARAMETERS, de.dlr.ivf.tapas.util.parameters.ParamString.DB_SCHEMA_CORE, de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.executeQuery(), de.dlr.ivf.tapas.mode.TPS_Mode.get(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.getParameters(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.mode.TPS_Mode.getUtilityFunction(), de.dlr.ivf.tapas.modechoice.TPS_UtilityFunction.setParameterSet(), de.dlr.ivf.tapas.util.parameters.ParamString.UTILITY_FUNCTION_CLASS, and de.dlr.ivf.tapas.util.parameters.ParamString.UTILITY_FUNCTION_KEY.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.init().
readVariableMap()
TPS_VariableMap de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readVariableMap (ResultSet set, int offset, int comment, double defaultValue) throws SQLException private
Method to read variable maps, like value of time.
Parameters
set The SQL- ResultSet
offset an offset for the storing positin in one atribute element
comment specifies the number of comments included in the ResultSet
defaultValue defines a default value in case of null-columns
Returns
The initialized TPS_VariableMap
Exceptions
SQLException
Definition at line 1980 of file TPS_DB_IO.java.
References de.dlr.ivf.tapas.util.TPS_VariableMap.addValue(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.FATAL, and de.dlr.ivf.tapas.log.TPS_Logger.log().
returnHousehold()
void de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.returnHousehold (TPS_Household hh) private
This method returns one household back to the database, e.g. if there where no members in this household found. Usually this indicates an error in the data set
Parameters
hh The household to return
Exceptions
SQLException
Definition at line 2009 of file TPS_DB_IO.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.BEHAVIOUR, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_HOUSEHOLD_TMP, de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.Behaviour.FAT, de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.functionExecute(), de.dlr.ivf.tapas.person.TPS_Household.getId(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.getParameters(), and de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString().
updateOccupancyTable()
void de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.updateOccupancyTable (TPS_Region region) private
In this method we update the occupancies of the locations. We have to work with increments, because other threads might have updated the occupancies in between. I call this "sloppy synchronization", because this is a classical shared resource for a multi-machine setup. However, a little overbooking is not so bad! After that we update our occupancies with the values stored in db.
Parameters
region with locations where the occupancy gets updated
Definition at line 2030 of file TPS_DB_IO.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_LOCATION_TMP, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.DEBUG, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.executeQuery(), de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_UPDATE_LOCATION_WEIGHTS, de.dlr.ivf.tapas.loc.TPS_Region.getLocation(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.getParameters(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.INFO, de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isTrue(), de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.HierarchyLogLevel.THREAD, and de.dlr.ivf.tapas.loc.TPS_Location.updateOccupancy().
vacuumTempTables()
void de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.vacuumTempTables () private
Method to vacuum the heavily used temp tables. It determines the type of clean up needed, looks if someone else is cleaning up and starts cleaning if no other tread is busy doing this job. This is a classic task for a job-scheduling manager and not for the worker threads :(
Definition at line 2066 of file TPS_DB_IO.java.
References de.dlr.ivf.tapas.util.parameters.ParamValue.DB_HH_SAMPLE_SIZE, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_HOUSEHOLD_TMP, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_SIMULATIONS, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_SUMO_STATUS, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.DEBUG, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.execute(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.executeQuery(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.functionExecute(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.getDbConnector(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getIntValue(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.getParameters(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.INFO, de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), de.dlr.ivf.tapas.util.parameters.ParamValue.ITERATION, de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.util.parameters.ParamValue.MAX_SUMO_ITERATION, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.readSingleParameter(), de.dlr.ivf.tapas.util.parameters.ParamString.RUN_IDENTIFIER, de.dlr.ivf.tapas.log.TPS_LoggingInterface.HierarchyLogLevel.THREAD, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.updateSingleParameter().
Member Data Documentation
ADDRESS
InetAddress de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.ADDRESS = null static private
The ip address of this machine.
Definition at line 59 of file TPS_DB_IO.java.
fetchSizePerProcessor
final int de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.fetchSizePerProcessor = 256 static private
Definition at line 56 of file TPS_DB_IO.java.
fetchSizePerProcessorPrefetchHouseholds
final int de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.fetchSizePerProcessorPrefetchHouseholds = 256 static private
Definition at line 57 of file TPS_DB_IO.java.
INTERCHANGE_FACTOR
final double de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.INTERCHANGE_FACTOR = 0.01 static
Definition at line 55 of file TPS_DB_IO.java.
lastCleanUp
int de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.lastCleanUp = -1 private
Definition at line 71 of file TPS_DB_IO.java.
numberOfFetchedHouseholds
int de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.numberOfFetchedHouseholds private
The number of households fetched for this chunk. should be cpu*numberToFetch or the remainders in db for the.
Definition at line 70 of file TPS_DB_IO.java.
numberToFetch
final int de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.numberToFetch private
The number of households to fetch per cpu.
Definition at line 61 of file TPS_DB_IO.java.
PM
final TPS_DB_IOManager de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.PM private
The reference to the persistence manager.
Definition at line 65 of file TPS_DB_IO.java.
prefetchedHouseholds
final Queue<TPS_Household> de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.prefetchedHouseholds = new LinkedList<>() private
A queue for prefetched households. Filled by getNextHouseholds .
Definition at line 67 of file TPS_DB_IO.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/persistence/db/TPS_DB_IO.java