TAPAS: de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer Class Reference
de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer Class Reference
Classes
class Diary
class DiaryElement
Public Member Functions
void calcDiaryStatistics ()
void cleanUpDB (String table)
void clearEverything ()
void printDiariesSQLInserts (String table_episode, String table_schemes, boolean print)
void printDistributionVectorSQLInserts (String tablename, String name, boolean print)
void printDistributionVectors ()
void printSchemeClassSQLInserts (String table, boolean print)
void printStatistics ()
void readMIDDiary (String table, String filter)
Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_BasicConnectionClass ()
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass)
TPS_BasicConnectionClass (String loginFile)
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass, String loginFile)
boolean checkMatrixName (String matrixName)
TPS_ParameterClass getParameters ()
String readParameter (String simKey, String paramKey)
void storeInDB (String matrixName, double[][] matrix, int decimalPlaces)
Static Public Member Functions
static void main (String[] args)
static String makeDiaryKey (int hhID, int pID)
Static Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
static double[][] array1Dto2D (Integer[] matrixVal)
static double[][] array1Dto2D (int[] matrixVal)
static File getRuntimeFile (boolean forceNewFile)
static File getRuntimeFile (String propertyFile, boolean forceNewFile)
static File getRuntimeFile ()
static File getRuntimeFile (String propertyFile)
static int[][] intArray1Dto2D (int[] matrixVal)
static String matrixToSQLArray (double[][] array, int decimalPlaces)
static StringWriter matrixToStringWriterSQL (double[][] array, int decimalPlaces)
Private Member Functions
int getMappingKey (int purpose, int purposeDetailed, int personStatus)
int recodeAcompanyTrip (DiaryElement trip, DiaryElement theOtherOne)
Additional Inherited Members
Protected Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
void finalize ()
Protected Attributes inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_DB_Connector dbCon = null
TPS_ParameterClass parameterClass
Detailed Description
Definition at line 20 of file TPS_MiD_Diary_Analyzer.java.
Member Function Documentation
calcDiaryStatistics()
void de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer.calcDiaryStatistics ()
Definition at line 101 of file TPS_MiD_Diary_Analyzer.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer.main().
cleanUpDB()
void de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer.cleanUpDB (String table)
Definition at line 150 of file TPS_MiD_Diary_Analyzer.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute().
Referenced by de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer.main().
clearEverything()
void de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer.clearEverything ()
Definition at line 155 of file TPS_MiD_Diary_Analyzer.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer.main().
getMappingKey()
int de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer.getMappingKey (int purpose, int purposeDetailed, int personStatus) private
Definition at line 175 of file TPS_MiD_Diary_Analyzer.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer.printDiariesSQLInserts().
main()
static void de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer.main (String[] args) static
Definition at line 45 of file TPS_MiD_Diary_Analyzer.java.
References de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer.calcDiaryStatistics(), de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer.cleanUpDB(), de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer.clearEverything(), de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer.printDistributionVectors(), de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer.printDistributionVectorSQLInserts(), and de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer.readMIDDiary().
makeDiaryKey()
static String de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer.makeDiaryKey (int hhID, int pID) static
Definition at line 97 of file TPS_MiD_Diary_Analyzer.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer.readMIDDiary().
printDiariesSQLInserts()
void de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer.printDiariesSQLInserts (String table_episode, String table_schemes, boolean print)
Definition at line 179 of file TPS_MiD_Diary_Analyzer.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection(), and de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer.getMappingKey().
printDistributionVectors()
void de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer.printDistributionVectors ()
Definition at line 415 of file TPS_MiD_Diary_Analyzer.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer.main().
printDistributionVectorSQLInserts()
void de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer.printDistributionVectorSQLInserts (String tablename, String name, boolean print)
Definition at line 374 of file TPS_MiD_Diary_Analyzer.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute(), and name.
Referenced by de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer.main().
printSchemeClassSQLInserts()
void de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer.printSchemeClassSQLInserts (String table, boolean print)
Definition at line 441 of file TPS_MiD_Diary_Analyzer.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute().
printStatistics()
void de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer.printStatistics ()
Definition at line 556 of file TPS_MiD_Diary_Analyzer.java.
readMIDDiary()
void de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer.readMIDDiary (String table, String filter)
Definition at line 585 of file TPS_MiD_Diary_Analyzer.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer.makeDiaryKey(), and de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer.recodeAcompanyTrip().
Referenced by de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer.main().
recodeAcompanyTrip()
int de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer.recodeAcompanyTrip (DiaryElement trip, DiaryElement theOtherOne) private
Definition at line 741 of file TPS_MiD_Diary_Analyzer.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer.readMIDDiary().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/TPS_MiD_Diary_Analyzer.java