TAPAS: de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeNode Class Reference
de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeNode Class Reference
Public Member Functions
TPS_ExpertKnowledgeNode (int id, TPS_Attribute splitVariable, Collection< Integer > attributeValues, TPS_DiscreteDistribution< TPS_Mode > summand, TPS_DiscreteDistribution< TPS_Mode > factor, TPS_Node parent)
TPS_DiscreteDistribution< TPS_Mode > modifyDistribution (TPS_DiscreteDistribution< TPS_Mode > input)
Public Member Functions inherited from de.dlr.ivf.tapas.modechoice.TPS_Node
TPS_Node (int id, TPS_Attribute splitVariable, Collection< Integer > attributeValues, TPS_DiscreteDistribution< TPS_Mode > distribution, TPS_Node parent)
void addChild (TPS_Node pChild)
int compareTo (TPS_Node o)
boolean find (int val)
TPS_Node getChild (int childId)
List< TPS_Node > getChildren ()
TPS_DiscreteDistribution< TPS_Mode > getCopyOfValueDistribution ()
int getId ()
List< Integer > getMyAttValues ()
TPS_Node getParent ()
TPS_Attribute getSplitVariable ()
boolean isLeaf ()
void setDistribution (double[] distribution)
String toString ()
String toString (String prefix)
String toString (String prefix, boolean recursive)
Private Attributes
final TPS_DiscreteDistribution< TPS_Mode > modificationFactor
Additional Inherited Members
Protected Attributes inherited from de.dlr.ivf.tapas.modechoice.TPS_Node
TPS_DiscreteDistribution< TPS_Mode > distribution
Detailed Description
Definition at line 17 of file TPS_ExpertKnowledgeNode.java.
Constructor & Destructor Documentation
TPS_ExpertKnowledgeNode()
de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeNode.TPS_ExpertKnowledgeNode (int id, TPS_Attribute splitVariable, Collection< Integer > attributeValues, TPS_DiscreteDistribution< TPS_Mode > summand, TPS_DiscreteDistribution< TPS_Mode > factor, TPS_Node parent)
Constructor for a TPS_ExpertKnowledge node. It stores the factor and the summand for modifying a given modal split: new = summand+original*factor
Parameters
id The id for this node
splitVariable the current split variable
attributeValues the attribute values of this node
summand the summands of this distribution modification
factor the factors of this distribution modification
parent a link to the parent node
Definition at line 34 of file TPS_ExpertKnowledgeNode.java.
References de.dlr.ivf.tapas.modechoice.TPS_Node.parent, and de.dlr.ivf.tapas.modechoice.TPS_Node.splitVariable.
Member Function Documentation
modifyDistribution()
TPS_DiscreteDistribution<TPS_Mode> de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeNode.modifyDistribution (TPS_DiscreteDistribution< TPS_Mode > input)
Function to generate a new ProbabilityDistribution. The input will be cloned. The out put suffices: output[mode] = input[mode]*factor[mode]+summand[mode]
Parameters
input The reference probability distribution
Returns
a new instance of probability distribution according to the factors and summands.
Definition at line 47 of file TPS_ExpertKnowledgeNode.java.
References de.dlr.ivf.tapas.mode.TPS_Mode.getConstants(), de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.getValueByKey(), and de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.setValueByKey().
Referenced by de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree.applyExpertKnowledge().
Member Data Documentation
modificationFactor
final TPS_DiscreteDistribution<TPS_Mode> de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeNode.modificationFactor private
mode distribution
Definition at line 22 of file TPS_ExpertKnowledgeNode.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/modechoice/TPS_ExpertKnowledgeNode.java