TAPAS: de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB Class Reference
de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB Class Reference
Classes
class PTNode
enum PTNodeField
Public Member Functions
TPS_VisumOeVToDB (String loginFile)
TPS_VisumOeVToDB ()
void calcBeelines ()
void calcSumOfTT ()
void calcTTWithoutWaiting (int secPerTransit)
void calcTop3 (double factor)
void clearPTNodes ()
void constantInitialWaiting (int lengthOfWaiting)
void findMissingValues ()
double[][] getMatrixForField (PTNodeField field)
void initTAZIDs (String filename)
void initTAZIDsOMFormat (String filename)
void initTAZIDsVFormat (String filename)
boolean loadTAZ (String table)
void readValues (String filename, PTNodeField field, int maxValue, int minValue)
void readValuesOMFormat (String filename, PTNodeField field, int maxValue, int minValue)
void readValuesVFormat (String filename, PTNodeField field, int maxValue, int minValue)
void removeACTandEGTfromPJT ()
void transformNumOfConnectionToInitialWaiting (int lengthOfSimulation, double A, double E)
void transformUnits ()
Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_BasicConnectionClass ()
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass)
TPS_BasicConnectionClass (String loginFile)
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass, String loginFile)
boolean checkMatrixName (String matrixName)
TPS_ParameterClass getParameters ()
String readParameter (String simKey, String paramKey)
void storeInDB (String matrixName, double[][] matrix, int decimalPlaces)
Static Public Member Functions
static void main (String[] args)
Static Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
static double[][] array1Dto2D (Integer[] matrixVal)
static double[][] array1Dto2D (int[] matrixVal)
static File getRuntimeFile (boolean forceNewFile)
static File getRuntimeFile (String propertyFile, boolean forceNewFile)
static File getRuntimeFile ()
static File getRuntimeFile (String propertyFile)
static int[][] intArray1Dto2D (int[] matrixVal)
static String matrixToSQLArray (double[][] array, int decimalPlaces)
static StringWriter matrixToStringWriterSQL (double[][] array, int decimalPlaces)
Public Attributes
HashMap< Integer, TAZ > TAZes = new HashMap<>()
PTNode[][] nodes = null
Protected Attributes
HashMap< Integer, Integer > reverseTAZIDMap = new HashMap<>()
Protected Attributes inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_DB_Connector dbCon = null
TPS_ParameterClass parameterClass
Private Member Functions
double checkValue (double dValue, int maxValue, int minValue)
double getTop3FromRow (List< Double > row, double factor)
String unifyFormat (String in)
Additional Inherited Members
Protected Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
void finalize ()
Detailed Description
Class to store a result from the VISUM PT Module in the TAPAS DB. It reads Visum output from the "O-Format", converts it and stores the result in the DB
Author
hein_mh
Definition at line 30 of file TPS_VisumOeVToDB.java.
Constructor & Destructor Documentation
TPS_VisumOeVToDB() [1/2]
de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.TPS_VisumOeVToDB (String loginFile)
Definition at line 49 of file TPS_VisumOeVToDB.java.
TPS_VisumOeVToDB() [2/2]
de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.TPS_VisumOeVToDB ()
Definition at line 53 of file TPS_VisumOeVToDB.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.main().
Member Function Documentation
calcBeelines()
void de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.calcBeelines ()
Function to calculate all beelinedistances for all taz-pairs
Definition at line 171 of file TPS_VisumOeVToDB.java.
References de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNode.bld, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNode.idEnd, and de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNode.idStart.
Referenced by de.dlr.ivf.scripts.PTAnalyzer.main(), and de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.main().
calcSumOfTT()
void de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.calcSumOfTT ()
Method to calculate the sum of all travel times, except access and egress
Definition at line 197 of file TPS_VisumOeVToDB.java.
Referenced by de.dlr.ivf.scripts.PTAnalyzer.main(), and de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.main().
calcTop3()
void de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.calcTop3 (double factor)
Method to use the top3-technique to fill the diagonal
Definition at line 247 of file TPS_VisumOeVToDB.java.
References de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNode.act, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNode.egt, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.getTop3FromRow(), de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNode.ivt, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNode.jrd, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNode.sumTT, and de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNode.twt.
Referenced by de.dlr.ivf.scripts.PTAnalyzer.main(), and de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.main().
calcTTWithoutWaiting()
void de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.calcTTWithoutWaiting (int secPerTransit)
Method to remove waitingtime from the traveltime
Definition at line 212 of file TPS_VisumOeVToDB.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.main().
checkValue()
double de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.checkValue (double dValue, int maxValue, int minValue) private
Function to check if a value is OK. It converts the double to a integer and do some checks: If the value is the VISUM-"No Connection tag" (999999) or diagonal (888888) it returns -1 If the value is the VISUM-"No value tag" (777777) it returns -2 If the value is higher tahn max or smaler than min it returns -3
Parameters
dValue the value to check
maxValue the maximum plausible int value
minValue the minimum plausible int value
Returns
the adjusted value
Definition at line 308 of file TPS_VisumOeVToDB.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.readValuesOMFormat(), and de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.readValuesVFormat().
clearPTNodes()
void de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.clearPTNodes ()
Definition at line 325 of file TPS_VisumOeVToDB.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.main().
constantInitialWaiting()
void de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.constantInitialWaiting (int lengthOfWaiting)
Method to set the initial waiting time to a constant
Definition at line 346 of file TPS_VisumOeVToDB.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.main().
findMissingValues()
void de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.findMissingValues ()
Method to find all missing values
Definition at line 357 of file TPS_VisumOeVToDB.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.main().
getMatrixForField()
double [][] de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.getMatrixForField (PTNodeField field)
Method to parse all values from a given field to a double[][]-array
Parameters
field The field to process
Returns
A double[][]-array containing all values
Definition at line 383 of file TPS_VisumOeVToDB.java.
References de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNode.act, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNode.bdh, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNode.bld, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNode.egt, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNode.ivt, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNode.jrd, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNode.nrt, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNode.sumTT, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNode.swt, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNode.twt, and de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNode.wkt.
Referenced by de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.main(), de.dlr.ivf.scripts.PTAnalyzer.printMinMaxAvg(), de.dlr.ivf.scripts.PTAnalyzer.printMinMaxAvgSpeed(), and de.dlr.ivf.scripts.PTAnalyzer.writeCSVXY().
getTop3FromRow()
double de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.getTop3FromRow (List< Double > row, double factor) private
Definition at line 435 of file TPS_VisumOeVToDB.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.calcTop3().
initTAZIDs()
void de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.initTAZIDs (String filename)
Function to initialize the TAZIDs from a VISUM File.
Parameters
filename Any VISUM-Output containing a matrix with the used TAZ-IDs
Definition at line 453 of file TPS_VisumOeVToDB.java.
References de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.initTAZIDsOMFormat(), and de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.initTAZIDsVFormat().
Referenced by de.dlr.ivf.scripts.PTAnalyzer.main(), and de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.main().
initTAZIDsOMFormat()
void de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.initTAZIDsOMFormat (String filename)
Definition at line 473 of file TPS_VisumOeVToDB.java.
References de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.reverseTAZIDMap, and de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.unifyFormat().
Referenced by de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.initTAZIDs().
initTAZIDsVFormat()
void de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.initTAZIDsVFormat (String filename)
Function to initialize the TAZIDs from a VISUM File.
Parameters
filename Any VISUM-Output containing a matrix with the used TAZ-IDs
Definition at line 532 of file TPS_VisumOeVToDB.java.
References de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.reverseTAZIDMap, and de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.unifyFormat().
Referenced by de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.initTAZIDs().
loadTAZ()
boolean de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.loadTAZ (String table)
Function to fetch all TAZ infoirmation from the DB, containing TAZID TAZ index, coordinates and statistical area
Returns
Definition at line 587 of file TPS_VisumOeVToDB.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, de.dlr.ivf.scripts.SrVCalculator.TAZ.description, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), de.dlr.ivf.scripts.SrVCalculator.TAZ.ignore, de.dlr.ivf.scripts.SrVCalculator.TAZ.lat, de.dlr.ivf.scripts.SrVCalculator.TAZ.lon, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.nodes, de.dlr.ivf.scripts.SrVCalculator.TAZ.stat_area, and de.dlr.ivf.scripts.SrVCalculator.TAZ.taz_id.
Referenced by de.dlr.ivf.scripts.PTAnalyzer.main(), and de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.main().
main()
static void de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.main (String[] args) static
Parameters
args
Reimplemented in de.dlr.ivf.scripts.PTAnalyzer.
Definition at line 60 of file TPS_VisumOeVToDB.java.
References de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNodeField.ACT, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNodeField.BDH, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.calcBeelines(), de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.calcSumOfTT(), de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.calcTop3(), de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.calcTTWithoutWaiting(), de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.clearPTNodes(), de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.constantInitialWaiting(), de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_MATRICES, de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNodeField.EGT, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.findMissingValues(), de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.getMatrixForField(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getParameters(), de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.initTAZIDs(), de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNodeField.IVT, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNodeField.JRD, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.loadTAZ(), de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNodeField.NTR, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.readValues(), de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.removeACTandEGTfromPJT(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.setString(), de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.storeInDB(), de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNodeField.SUMTT, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNodeField.SWT, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.TPS_VisumOeVToDB(), de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.transformNumOfConnectionToInitialWaiting(), de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.transformUnits(), and de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNodeField.TWT.
readValues()
void de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.readValues (String filename, PTNodeField field, int maxValue, int minValue)
Definition at line 633 of file TPS_VisumOeVToDB.java.
References de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.readValuesOMFormat(), and de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.readValuesVFormat().
Referenced by de.dlr.ivf.scripts.PTAnalyzer.main(), and de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.main().
readValuesOMFormat()
void de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.readValuesOMFormat (String filename, PTNodeField field, int maxValue, int minValue)
Main method to parse a VISUM-File to a given PTNode-Field
Parameters
filename THe File to read
field The target field, eg egress time
Definition at line 660 of file TPS_VisumOeVToDB.java.
References de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNode.act, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNode.bdh, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.checkValue(), de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNode.egt, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNode.idEnd, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNode.idStart, de.dlr.ivf.scripts.SrVCalculator.TAZ.ignore, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNode.isDefined, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNode.ivt, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNode.jrd, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNode.nrt, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNode.sumTT, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNode.swt, de.dlr.ivf.scripts.SrVCalculator.TAZ.taz_id, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNode.twt, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.unifyFormat(), and de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNode.wkt.
Referenced by de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.readValues().
readValuesVFormat()
void de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.readValuesVFormat (String filename, PTNodeField field, int maxValue, int minValue)
Main method to parse a VISUM-File to a given PTNode-Field
Parameters
filename THe File to read
field The target field, eg egress time
Definition at line 778 of file TPS_VisumOeVToDB.java.
References de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNode.act, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNode.bdh, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.checkValue(), de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNode.egt, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNode.idEnd, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNode.idStart, de.dlr.ivf.scripts.SrVCalculator.TAZ.ignore, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNode.isDefined, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNode.ivt, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNode.jrd, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNode.nrt, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.reverseTAZIDMap, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNode.sumTT, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNode.swt, de.dlr.ivf.scripts.SrVCalculator.TAZ.taz_id, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNode.twt, de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.unifyFormat(), and de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.PTNode.wkt.
Referenced by de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.readValues().
removeACTandEGTfromPJT()
void de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.removeACTandEGTfromPJT ()
Definition at line 888 of file TPS_VisumOeVToDB.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.main().
transformNumOfConnectionToInitialWaiting()
void de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.transformNumOfConnectionToInitialWaiting (int lengthOfSimulation, double A, double E)
Method to transform the number of connections per day to a initial waiting time. This is done by VISUM-technique: waiting = a*(Period/num)^E
Parameters
lengthOfSimulation the length of the simulation in minutes
A the weigth
E the exponent
Definition at line 909 of file TPS_VisumOeVToDB.java.
Referenced by de.dlr.ivf.scripts.PTAnalyzer.main(), and de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.main().
transformUnits()
void de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.transformUnits ()
Method to convert all minutes to seconds and all km to meter
Definition at line 925 of file TPS_VisumOeVToDB.java.
Referenced by de.dlr.ivf.scripts.PTAnalyzer.main(), and de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.main().
unifyFormat()
String de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.unifyFormat (String in) private
Helper function to unify various string formats. The input is cleaned for double spaces ands all spaces are transformed to tabs All commas are transformed to dots for stupid German number formats!
Parameters
in the ugly input string
Returns
out: the beauty output string
Definition at line 950 of file TPS_VisumOeVToDB.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.initTAZIDsOMFormat(), de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.initTAZIDsVFormat(), de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.readValuesOMFormat(), and de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.readValuesVFormat().
Member Data Documentation
nodes
PTNode [][] de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.nodes = null
The array for all pTNOdes
Definition at line 39 of file TPS_VisumOeVToDB.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.loadTAZ(), de.dlr.ivf.scripts.PTAnalyzer.numberOfLongDistanceWalkingConnections(), and de.dlr.ivf.scripts.PTAnalyzer.numberOfWalkingConnections().
reverseTAZIDMap
HashMap<Integer, Integer> de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.reverseTAZIDMap = new HashMap<>() protected
Map from taz index to TAZ-ID
Definition at line 43 of file TPS_VisumOeVToDB.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.initTAZIDsOMFormat(), de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.initTAZIDsVFormat(), de.dlr.ivf.scripts.PTAnalyzer.printMinMaxAvgSpeed(), and de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.readValuesVFormat().
TAZes
HashMap<Integer, TAZ> de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.TAZes = new HashMap<>()
Map for Taz-id to TAZ-Class form SrVCalculator
Definition at line 35 of file TPS_VisumOeVToDB.java.
Referenced by de.dlr.ivf.scripts.PTAnalyzer.printMinMaxAvgSpeed().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/TPS_VisumOeVToDB.java