TAPAS: de.dlr.ivf.tapas.scheme.TPS_TourPart Class Reference
de.dlr.ivf.tapas.scheme.TPS_TourPart Class Reference
Classes
class TPS_StayHierarchy
class TravelDurations
class TripIterator
Public Member Functions
TPS_TourPart (int id)
boolean addStay (TPS_Stay stay, TPS_ParameterClass parameterClass)
boolean addTrip (TPS_Trip trip)
TPS_Car getCar ()
void setCar (TPS_Car car)
TPS_Trip getNextTrip (TPS_Episode episode)
double getOriginalTripDuration ()
TPS_Trip getPreviousTrip (TPS_Episode episode)
Iterable< TPS_Stay > getPriorisedStayIterable ()
TPS_StayHierarchy getStayHierarchy (TPS_Stay stay)
double getTourpartDistance ()
TravelDurations getTravelDurations (TPS_Stay key)
Iterable< TPS_Trip > getTripIterator ()
TPS_ExtMode getUsedMode ()
void initHierarchy ()
boolean isBikeUsed ()
boolean isCarUsed ()
boolean isFixedModeUsed ()
boolean isHomePart ()
boolean isTourPart ()
void releaseCar ()
void setInitialTravelDurations (TPS_ParameterClass parameterClass)
void setUsedMode (TPS_ExtMode mode, TPS_Car car)
String toString (String prefix)
void updateActualTravelDistances (TPS_Plan plan)
void updateActualTravelDurations (TPS_Plan plan)
Public Member Functions inherited from de.dlr.ivf.tapas.scheme.TPS_SchemePart
TPS_SchemePart (int id)
TPS_Episode getFirstEpisode ()
int getId ()
TPS_Episode getLastEpisode ()
TPS_Episode getNextEpisode (TPS_Episode episode)
TPS_Episode getNextEpisodeFromThisPart (TPS_Episode episode)
TPS_Stay getNextStay (TPS_Episode episode)
double getOriginalSchemePartEnd ()
double getOriginalSchemePartStart ()
TPS_Episode getPreviousEpisode (TPS_Episode episode)
TPS_Episode getPreviousEpisodeFromThisPart (TPS_Episode episode)
TPS_Stay getPreviousStay (TPS_Episode episode)
TPS_Scheme getScheme ()
Iterable< TPS_Stay > getStayIterator ()
boolean isFirst (TPS_Episode episode)
boolean isLast (TPS_Episode episode)
Iterator< TPS_Episode > iterator ()
int size ()
String toString ()
Public Attributes
boolean hasWorkActivity = false
boolean hasEducationActivity = false
boolean hasShoppingActivity = false
boolean hasLeisureActivity = false
boolean hasErrantActivity = false
Private Attributes
final Map< TPS_Stay, TravelDurations > travelDurationsMap
final Map< TPS_Stay, TPS_StayHierarchy > hierachyMap
final SortedSet< TPS_Stay > prioritySet
TPS_Car car = null
TPS_ExtMode lastMode = null
double tourPartDistance
Additional Inherited Members
Protected Member Functions inherited from de.dlr.ivf.tapas.scheme.TPS_SchemePart
boolean addEpisode (TPS_Episode episode)
Protected Attributes inherited from de.dlr.ivf.tapas.scheme.TPS_SchemePart
List< TPS_Episode > episodes
double originalSchemePartStart = 24 * 60 * 60
double originalSchemePartEnd = 0.0
Detailed Description
This class represents a tour part. It is characterised by one trip at the beginning and at the end and all stays between are out of home. The shortest tour consists of one trip (e.g. go with the dog). All stays in a tour are prioritised and connected by their priorities.
Author
mark_ma
Definition at line 34 of file TPS_TourPart.java.
Constructor & Destructor Documentation
TPS_TourPart()
de.dlr.ivf.tapas.scheme.TPS_TourPart.TPS_TourPart (int id)
This constructor builds a new tourpart with the given id. It instantiates all Collections which are used in this instance.
Parameters
id
Definition at line 70 of file TPS_TourPart.java.
Member Function Documentation
addStay()
boolean de.dlr.ivf.tapas.scheme.TPS_TourPart.addStay (TPS_Stay stay, TPS_ParameterClass parameterClass)
This method adds a stay to the list and sets its reference to a scheme part to this.
Parameters
stay
parameterClass reference - which is not used in here, only in the subclass
Returns
true if added, false otherwise
Reimplemented from de.dlr.ivf.tapas.scheme.TPS_SchemePart.
Definition at line 83 of file TPS_TourPart.java.
References de.dlr.ivf.tapas.scheme.TPS_TourPart.TravelDurations.arrivalDuration, de.dlr.ivf.tapas.scheme.TPS_TourPart.TravelDurations.departureDuration, de.dlr.ivf.tapas.scheme.TPS_Episode.getActCode(), de.dlr.ivf.tapas.constants.TPS_ActivityConstant.getCode(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getIntValue(), de.dlr.ivf.tapas.scheme.TPS_Episode.getOriginalEnd(), de.dlr.ivf.tapas.scheme.TPS_Episode.getOriginalStart(), de.dlr.ivf.tapas.util.parameters.ParamValue.PT_MINIMUM_TT, and de.dlr.ivf.tapas.constants.TPS_ActivityConstant.TPS_ActivityCodeType.TAPAS.
addTrip()
boolean de.dlr.ivf.tapas.scheme.TPS_TourPart.addTrip (TPS_Trip trip)
This method adds a trip and increments the temporary complete arrival duration.
Parameters
trip trip to add
Returns
true if the trip was added, false otherwise
Definition at line 154 of file TPS_TourPart.java.
References de.dlr.ivf.tapas.scheme.TPS_TourPart.TravelDurations.departureDuration, and de.dlr.ivf.tapas.scheme.TPS_Episode.getOriginalDuration().
getCar()
TPS_Car de.dlr.ivf.tapas.scheme.TPS_TourPart.getCar ()
gets the reference to a car attached to this plan environment
Returns
the car
Definition at line 173 of file TPS_TourPart.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Worker.assignCarToPlan(), de.dlr.ivf.tapas.loc.TPS_MultipleTAZRepresentant.getLocationRepresentatives(), de.dlr.ivf.tapas.person.TPS_Car.selectCar(), de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes(), and de.dlr.ivf.tapas.mode.TPS_ModeSet.selectMode().
getNextTrip()
TPS_Trip de.dlr.ivf.tapas.scheme.TPS_TourPart.getNextTrip (TPS_Episode episode)
Returns the next trip to the episode provided
Parameters
episode
Returns
next trip to this episode
Definition at line 194 of file TPS_TourPart.java.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes().
getOriginalTripDuration()
double de.dlr.ivf.tapas.scheme.TPS_TourPart.getOriginalTripDuration ()
Returns the sum of all original durations of all trip episodes of this tour part.
Returns
sum of all original durations of all trips of this tour part
Definition at line 209 of file TPS_TourPart.java.
getPreviousTrip()
TPS_Trip de.dlr.ivf.tapas.scheme.TPS_TourPart.getPreviousTrip (TPS_Episode episode)
Returns the previous trip to the episode provided
Parameters
episode
Returns
previous trip to this episode
Definition at line 225 of file TPS_TourPart.java.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes().
getPriorisedStayIterable()
Iterable<TPS_Stay> de.dlr.ivf.tapas.scheme.TPS_TourPart.getPriorisedStayIterable ()
Returns
Iterator over all stays in this tour part in a priorised order
Definition at line 238 of file TPS_TourPart.java.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.balanceStarts(), and de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes().
getStayHierarchy()
TPS_StayHierarchy de.dlr.ivf.tapas.scheme.TPS_TourPart.getStayHierarchy (TPS_Stay stay)
Parameters
stay stay to get the hierarchy element
Returns
the previous and next stay to the given one
Definition at line 246 of file TPS_TourPart.java.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.getHierarchizedPreviousStay(), de.dlr.ivf.tapas.loc.TPS_MultipleTAZRepresentant.getLocationRepresentatives(), de.dlr.ivf.tapas.plan.TPS_LocatedStay.selectLocation(), de.dlr.ivf.tapas.loc.TPS_SelectLocationWeightBased.selectLocationFromChoiceSet(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.selectLocationFromChoiceSet(), and de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes().
getTourpartDistance()
double de.dlr.ivf.tapas.scheme.TPS_TourPart.getTourpartDistance ()
Method to get the distance traveled in this tour part
Returns
the distance traveled in meters
Definition at line 255 of file TPS_TourPart.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Worker.assignCarToPlan().
getTravelDurations()
TravelDurations de.dlr.ivf.tapas.scheme.TPS_TourPart.getTravelDurations (TPS_Stay key)
Parameters
key stay for which the travel durations are retrieved
Returns
travel durations corresponding to the given stay
Definition at line 263 of file TPS_TourPart.java.
Referenced by de.dlr.ivf.tapas.loc.TPS_MultipleTAZRepresentant.getLocationRepresentatives().
getTripIterator()
Iterable<TPS_Trip> de.dlr.ivf.tapas.scheme.TPS_TourPart.getTripIterator ()
This method returns an iterator over all trips of this tour part.
Returns
an instance of TripIterator
Definition at line 272 of file TPS_TourPart.java.
getUsedMode()
TPS_ExtMode de.dlr.ivf.tapas.scheme.TPS_TourPart.getUsedMode ()
returns the mode, which was used for the last stay
Returns
the mode
Definition at line 281 of file TPS_TourPart.java.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes().
initHierarchy()
void de.dlr.ivf.tapas.scheme.TPS_TourPart.initHierarchy ()
This method is quite simple, because all of the nasty work, like stay-merging has been done in {link TPS_DB_IO.readSchemeSet()}. This method simply puts the hierarchical previous and next stay in a [} structure. If this stay is the first or the last of the scheme its precessor resp. successor is null
The method is divided into two parts. The first part sets the priorities of all stays of the tour. The second part uses the priorities to build the connection hierarchy of the stays.
Definition at line 290 of file TPS_TourPart.java.
References de.dlr.ivf.tapas.scheme.TPS_Episode.getOriginalStart().
isBikeUsed()
boolean de.dlr.ivf.tapas.scheme.TPS_TourPart.isBikeUsed ()
Returns
the bikeUsed
Definition at line 365 of file TPS_TourPart.java.
References de.dlr.ivf.tapas.mode.TPS_ExtMode.isBikeUsed().
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes(), and de.dlr.ivf.tapas.mode.TPS_ModeSet.selectMode().
isCarUsed()
boolean de.dlr.ivf.tapas.scheme.TPS_TourPart.isCarUsed ()
checks if a car is attached to this plan environment
Returns
true if a car is attached
Definition at line 374 of file TPS_TourPart.java.
References de.dlr.ivf.tapas.mode.TPS_ExtMode.isCarUsed().
Referenced by de.dlr.ivf.tapas.loc.TPS_MultipleTAZRepresentant.getLocationRepresentatives(), de.dlr.ivf.tapas.person.TPS_Car.selectCar(), and de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes().
isFixedModeUsed()
boolean de.dlr.ivf.tapas.scheme.TPS_TourPart.isFixedModeUsed ()
Method to determine if this tourpart has to be done with a fixed mode, e.g. bike or car
Returns
true if a fixed mode is used previously
Definition at line 383 of file TPS_TourPart.java.
References de.dlr.ivf.tapas.mode.TPS_ExtMode.isFix().
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes().
isHomePart()
boolean de.dlr.ivf.tapas.scheme.TPS_TourPart.isHomePart ()
Flag indicating whether this scheme part is a home part, i.e. all stays are at home and the scheme part does not contain a trip.
Returns
true if the scheme part is a home part
Reimplemented from de.dlr.ivf.tapas.scheme.TPS_SchemePart.
Definition at line 397 of file TPS_TourPart.java.
isTourPart()
boolean de.dlr.ivf.tapas.scheme.TPS_TourPart.isTourPart ()
Flag indicating whether the scheme part is a tour part, i.e. the scheme part contains trips, in detail it has to start and end with a trip. Every change of a location in the stays in the scheme part is separated by a further trip.
Returns
true if the scheme part is a tour part, false otherwise
Reimplemented from de.dlr.ivf.tapas.scheme.TPS_SchemePart.
Definition at line 407 of file TPS_TourPart.java.
releaseCar()
void de.dlr.ivf.tapas.scheme.TPS_TourPart.releaseCar ()
releases the used car, e.g. if the plan is not accepted
Returns
success of this action
Definition at line 416 of file TPS_TourPart.java.
setCar()
void de.dlr.ivf.tapas.scheme.TPS_TourPart.setCar (TPS_Car car)
sets an reference to the used car for this plan environment
Parameters
car the reference to an car of this household
Definition at line 182 of file TPS_TourPart.java.
References de.dlr.ivf.tapas.mode.TPS_ExtMode.simpleMIT.
setInitialTravelDurations()
void de.dlr.ivf.tapas.scheme.TPS_TourPart.setInitialTravelDurations (TPS_ParameterClass parameterClass)
method to set the initial travel durations to their original values
Parameters
parameterClass parameter class reference
Definition at line 426 of file TPS_TourPart.java.
References de.dlr.ivf.tapas.mode.TPS_Mode.get(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getDoubleValue(), de.dlr.ivf.tapas.mode.TPS_Mode.getVelocity(), de.dlr.ivf.tapas.util.parameters.ParamValue.MIN_DIST, and de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.WALK.
setUsedMode()
void de.dlr.ivf.tapas.scheme.TPS_TourPart.setUsedMode (TPS_ExtMode mode, TPS_Car car)
This method stores the last used departure mode from a stay
Parameters
mode The used departure mode
car A car, if available. If the mode is not, "MIT" this information is discarded and the internal reference is still a null pointer.
Definition at line 450 of file TPS_TourPart.java.
References de.dlr.ivf.tapas.mode.TPS_ExtMode.isCarUsed().
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes().
toString()
String de.dlr.ivf.tapas.scheme.TPS_TourPart.toString (String prefix)
This method should print the object naturally with the given prefix.
Parameters
prefix
Returns
prefix + toString();
Reimplemented from de.dlr.ivf.tapas.scheme.TPS_SchemePart.
Definition at line 476 of file TPS_TourPart.java.
References de.dlr.ivf.tapas.scheme.TPS_Episode.toString().
updateActualTravelDistances()
void de.dlr.ivf.tapas.scheme.TPS_TourPart.updateActualTravelDistances (TPS_Plan plan)
Method to update the travel distances for this plan up to this point
Definition at line 504 of file TPS_TourPart.java.
References de.dlr.ivf.tapas.mode.TPS_Mode.get(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getDoubleValue(), de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.getDuration(), de.dlr.ivf.tapas.plan.TPS_PlannedTrip.getMode(), de.dlr.ivf.tapas.persistence.TPS_PersistenceManager.getParameters(), de.dlr.ivf.tapas.plan.TPS_Plan.getPlannedTrip(), de.dlr.ivf.tapas.plan.TPS_Plan.getPM(), de.dlr.ivf.tapas.mode.TPS_Mode.getVelocity(), de.dlr.ivf.tapas.util.parameters.ParamValue.MIN_DIST, and de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.WALK.
updateActualTravelDurations()
void de.dlr.ivf.tapas.scheme.TPS_TourPart.updateActualTravelDurations (TPS_Plan plan)
Method to update the travel durations for this plan up to this point
Parameters
plan
Definition at line 532 of file TPS_TourPart.java.
References de.dlr.ivf.tapas.plan.TPS_Plan.getAdaptedEpisode(), and de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.getDistance().
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes().
Member Data Documentation
car
TPS_Car de.dlr.ivf.tapas.scheme.TPS_TourPart.car = null private
The car used with this plan
Definition at line 56 of file TPS_TourPart.java.
hasEducationActivity
boolean de.dlr.ivf.tapas.scheme.TPS_TourPart.hasEducationActivity = false
Definition at line 37 of file TPS_TourPart.java.
hasErrantActivity
boolean de.dlr.ivf.tapas.scheme.TPS_TourPart.hasErrantActivity = false
Definition at line 40 of file TPS_TourPart.java.
hasLeisureActivity
boolean de.dlr.ivf.tapas.scheme.TPS_TourPart.hasLeisureActivity = false
Definition at line 39 of file TPS_TourPart.java.
hasShoppingActivity
boolean de.dlr.ivf.tapas.scheme.TPS_TourPart.hasShoppingActivity = false
Definition at line 38 of file TPS_TourPart.java.
hasWorkActivity
boolean de.dlr.ivf.tapas.scheme.TPS_TourPart.hasWorkActivity = false
Definition at line 36 of file TPS_TourPart.java.
hierachyMap
final Map<TPS_Stay, TPS_StayHierarchy> de.dlr.ivf.tapas.scheme.TPS_TourPart.hierachyMap private
Map with all connections of the stays to a previous and a next stay
Definition at line 48 of file TPS_TourPart.java.
lastMode
TPS_ExtMode de.dlr.ivf.tapas.scheme.TPS_TourPart.lastMode = null private
Definition at line 58 of file TPS_TourPart.java.
prioritySet
final SortedSet<TPS_Stay> de.dlr.ivf.tapas.scheme.TPS_TourPart.prioritySet private
Automatically sorted set with all stays by their priority
Definition at line 52 of file TPS_TourPart.java.
tourPartDistance
double de.dlr.ivf.tapas.scheme.TPS_TourPart.tourPartDistance private
Definition at line 62 of file TPS_TourPart.java.
travelDurationsMap
final Map<TPS_Stay, TravelDurations> de.dlr.ivf.tapas.scheme.TPS_TourPart.travelDurationsMap private
In this map are all complete travel durations for each stay in this tour part stored
Definition at line 44 of file TPS_TourPart.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/scheme/TPS_TourPart.java