TAPAS: de.dlr.ivf.tapas.TPS_Main Class Reference
de.dlr.ivf.tapas.TPS_Main Class Reference
Classes
enum RunType
class TPS_State
Public Member Functions
TPS_Main (File file, String simKey)
TPS_Main (String filename, String sim_key)
void finish ()
TPS_PersistenceManager getPersistenceManager ()
void init ()
void run (int threads)
Static Public Member Functions
static String getDefaultSimKey ()
static void main (String[] args)
Static Public Attributes
static Map< Integer, Integer[]> actStats = new HashMap<>()
static TPS_State STATE = new TPS_State()
static boolean waitForMe = false
Private Member Functions
void updateCosts ()
Private Attributes
final TPS_PersistenceManager PM
final TPS_ParameterClass parameterClass
Static Private Attributes
static final boolean DEBUG = false
Flag for DEBUG-Modus.
Detailed Description
This class is the main entry point into a TAPAS simulation. It provides a main method which can start in different modes indicated by the RunType of the simulation.
Author
mark_ma
Definition at line 42 of file TPS_Main.java.
Constructor & Destructor Documentation
TPS_Main() [1/2]
de.dlr.ivf.tapas.TPS_Main.TPS_Main (File file, String simKey)
This constructor reads all parameters and tries to initialise all data which is available via the TPS_PersistenceManager . If any Exception is thrown it is logged and the application stops.
Parameters
file filename of the parameter file with all run information. This file leads to all other files with e.g. logging, database, etc. information.
simKey key of the simulation
Definition at line 70 of file TPS_Main.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.CLASS_DATA_SCOURCE_ORIGIN, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.closeConnection(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.FATAL, de.dlr.ivf.tapas.util.parameters.ParamString.FILE_WORKING_DIRECTORY, de.dlr.ivf.tapas.TPS_Main.getDefaultSimKey(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.INFO, de.dlr.ivf.tapas.util.parameters.ParamValue.ITERATION, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.loadRuntimeParameters(), de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.readRuntimeParametersFromDB(), de.dlr.ivf.tapas.util.parameters.ParamString.RUN_IDENTIFIER, and de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.setString().
TPS_Main() [2/2]
de.dlr.ivf.tapas.TPS_Main.TPS_Main (String filename, String sim_key)
The constructor builds a File from the given filename and calls TPS_Main(File, String).
Parameters
filename filename of the run properties file
sim_key key of the simulation
Definition at line 117 of file TPS_Main.java.
Member Function Documentation
finish()
void de.dlr.ivf.tapas.TPS_Main.finish ()
This method drops the temporary tables from the database if necessary.
Definition at line 181 of file TPS_Main.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.dropTemporaryTables(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.FATAL, and de.dlr.ivf.tapas.log.TPS_Logger.log().
Referenced by de.dlr.ivf.tapas.TPS_Main.main().
getDefaultSimKey()
static String de.dlr.ivf.tapas.TPS_Main.getDefaultSimKey () static
sim_key
Returns
default simulation key generated by the current timestamp
Definition at line 126 of file TPS_Main.java.
Referenced by de.dlr.ivf.tapas.TPS_Main.TPS_Main(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.TPS_SumoConverter(), and de.dlr.ivf.tapas.iteration.TPS_VisumConverter.TPS_VisumConverter().
getPersistenceManager()
TPS_PersistenceManager de.dlr.ivf.tapas.TPS_Main.getPersistenceManager ()
Returns
persistence manager of the whole simulation run
Definition at line 196 of file TPS_Main.java.
init()
void de.dlr.ivf.tapas.TPS_Main.init ()
This method initialises all temporary tables in the database if necessary. This method sets the
Definition at line 204 of file TPS_Main.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.createTemporaryAndOutputTables().
Referenced by de.dlr.ivf.tapas.TPS_Main.main().
main()
static void de.dlr.ivf.tapas.TPS_Main.main (String[] args) static
Main method initialises a TPS_Main and starts the simulation via the run method.
Parameters
args Arguments with a R are necessary, these with an O are optional
R args[0] absolute filename of the run configuration file
O args[1] constant for run type [ALL, SIMULATE]
O args[2] simulation key
O args[3] amount of parallel threads
Definition at line 145 of file TPS_Main.java.
References de.dlr.ivf.tapas.TPS_Main.RunType.ALL, de.dlr.ivf.tapas.util.TPS_Argument.checkArguments(), de.dlr.ivf.tapas.persistence.TPS_PersistenceManager.close(), de.dlr.ivf.tapas.TPS_Main.finish(), de.dlr.ivf.tapas.TPS_Main.init(), de.dlr.ivf.tapas.TPS_Main.PM, de.dlr.ivf.tapas.TPS_Main.run(), and de.dlr.ivf.tapas.TPS_Main.TPS_State.setFinished().
run()
void de.dlr.ivf.tapas.TPS_Main.run (int threads)
This method initialises the persistence manager and builds all worker threads. The method blocks until all workers have finished the simulation.
Parameters
threads amount of parallel threads.
Definition at line 217 of file TPS_Main.java.
References de.dlr.ivf.tapas.log.TPS_Logger.closeLoggers(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.FATAL, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.INFO, de.dlr.ivf.tapas.persistence.TPS_PersistenceManager.init(), de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), and de.dlr.ivf.tapas.log.TPS_Logger.log().
Referenced by de.dlr.ivf.tapas.TPS_Main.main().
updateCosts()
void de.dlr.ivf.tapas.TPS_Main.updateCosts () private
Definition at line 271 of file TPS_Main.java.
References de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.BIKE, de.dlr.ivf.tapas.util.parameters.ParamValue.BIKE_COST_PER_KM, de.dlr.ivf.tapas.util.parameters.ParamValue.BIKE_COST_PER_KM_BASE, de.dlr.ivf.tapas.mode.TPS_Mode.cost_per_km, de.dlr.ivf.tapas.mode.TPS_Mode.cost_per_km_base, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_TT_BIKE_BASE, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_TT_MIT_BASE, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_TT_PT_BASE, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_TT_WALK_BASE, de.dlr.ivf.tapas.mode.TPS_Mode.get(), de.dlr.ivf.tapas.util.parameters.ParamValueClass.getDoubleValue(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isDefined(), de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.MIT, de.dlr.ivf.tapas.util.parameters.ParamValue.MIT_GASOLINE_COST_PER_KM, de.dlr.ivf.tapas.util.parameters.ParamValue.MIT_GASOLINE_COST_PER_KM_BASE, de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.MIT_PASS, de.dlr.ivf.tapas.util.parameters.ParamValue.MIT_VARIABLE_COST_PER_KM, de.dlr.ivf.tapas.util.parameters.ParamValue.MIT_VARIABLE_COST_PER_KM_BASE, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.paramValueClass, de.dlr.ivf.tapas.util.parameters.ParamValue.PASS_COST_PER_KM, de.dlr.ivf.tapas.util.parameters.ParamValue.PASS_COST_PER_KM_BASE, de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.PT, de.dlr.ivf.tapas.util.parameters.ParamValue.PT_COST_PER_KM, de.dlr.ivf.tapas.util.parameters.ParamValue.PT_COST_PER_KM_BASE, de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.TAXI, de.dlr.ivf.tapas.util.parameters.ParamValue.TAXI_COST_PER_KM, de.dlr.ivf.tapas.util.parameters.ParamValue.TAXI_COST_PER_KM_BASE, de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.TRAIN, de.dlr.ivf.tapas.util.parameters.ParamValue.TRAIN_COST_PER_KM, de.dlr.ivf.tapas.util.parameters.ParamValue.TRAIN_COST_PER_KM_BASE, de.dlr.ivf.tapas.mode.TPS_Mode.useBase, de.dlr.ivf.tapas.mode.TPS_Mode.variable_cost_per_km, de.dlr.ivf.tapas.mode.TPS_Mode.variable_cost_per_km_base, de.dlr.ivf.tapas.mode.TPS_Mode.velocity, de.dlr.ivf.tapas.util.parameters.ParamValue.VELOCITY_BIKE, de.dlr.ivf.tapas.util.parameters.ParamValue.VELOCITY_CAR, de.dlr.ivf.tapas.util.parameters.ParamValue.VELOCITY_FOOT, de.dlr.ivf.tapas.util.parameters.ParamValue.VELOCITY_TRAIN, de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.WALK, de.dlr.ivf.tapas.util.parameters.ParamValue.WALK_COST_PER_KM, and de.dlr.ivf.tapas.util.parameters.ParamValue.WALK_COST_PER_KM_BASE.
Member Data Documentation
actStats
Map<Integer, Integer[]> de.dlr.ivf.tapas.TPS_Main.actStats = new HashMap<>() static
Definition at line 44 of file TPS_Main.java.
Referenced by de.dlr.ivf.tapas.loc.TPS_MultipleTAZRepresentant.getLocationRepresentatives().
DEBUG
final boolean de.dlr.ivf.tapas.TPS_Main.DEBUG = false static private
Flag for DEBUG-Modus.
Definition at line 51 of file TPS_Main.java.
parameterClass
final TPS_ParameterClass de.dlr.ivf.tapas.TPS_Main.parameterClass private
container which holds all parameter values
Definition at line 59 of file TPS_Main.java.
PM
final TPS_PersistenceManager de.dlr.ivf.tapas.TPS_Main.PM private
persistence manager of the whole simulation run
Definition at line 55 of file TPS_Main.java.
Referenced by de.dlr.ivf.tapas.TPS_Main.main().
STATE
TPS_State de.dlr.ivf.tapas.TPS_Main.STATE = new TPS_State() static
state of the simulation
Definition at line 48 of file TPS_Main.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Worker.call(), de.dlr.ivf.tapas.runtime.TPS_Launch.main(), de.dlr.ivf.tapas.runtime.server.SimulationServer.run(), and de.dlr.ivf.tapas.runtime.server.SimulationServer.RunWhenShuttingDown.run().
waitForMe
boolean de.dlr.ivf.tapas.TPS_Main.waitForMe = false static
Definition at line 49 of file TPS_Main.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationServer.RunWhenShuttingDown.run().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/TPS_Main.java