TAPAS: de.dlr.ivf.tapas.mode.TPS_NonMotorisedMode Class Reference
de.dlr.ivf.tapas.mode.TPS_NonMotorisedMode Class Reference
Public Member Functions
TPS_NonMotorisedMode (String name, String[] attributes, boolean isFix, TPS_ParameterClass parameterClass)
double getDistance (Locatable start, Locatable end, SimulationType simType, TPS_Car car)
double getTravelTime (Locatable start, Locatable end, int time, SimulationType simType, TPS_ActivityConstant actCodeFrom, TPS_ActivityConstant actCodeTo, TPS_Person person, TPS_Car car)
Public Member Functions inherited from de.dlr.ivf.tapas.mode.TPS_Mode
void addModeToMap ()
ModeType getAttribute ()
int getCode (TPS_ModeCodeType type)
double getCost_per_km (SimulationType simType)
ModeType getModeType ()
String getName ()
TPS_ParameterClass getParameters ()
void setParameters (TPS_ParameterClass param)
double getVariableCost_per_km (SimulationType simType)
ParamValue getVelocity ()
boolean isFix ()
boolean isType (ModeType... type)
boolean isType (ModeType type)
boolean isUseBase ()
String toString (String prefix)
Additional Inherited Members
Static Public Member Functions inherited from de.dlr.ivf.tapas.mode.TPS_Mode
static void clearModeMap ()
static TPS_Mode get (ModeType key)
static Collection< TPS_Mode > getConstants ()
static TPS_UtilityFunction getUtilityFunction (TPS_ParameterClass parameterClass)
static boolean hasConnection (double val)
static void initUtilityFunction (TPS_ParameterClass parameterClass)
static boolean noConnection (double val)
Public Attributes inherited from de.dlr.ivf.tapas.mode.TPS_Mode
ParamValue velocity = null
double cost_per_km = 0
double cost_per_km_base = 0
double variable_cost_per_km = 0
double variable_cost_per_km_base = 0
boolean useBase = false
Static Public Attributes inherited from de.dlr.ivf.tapas.mode.TPS_Mode
static ModeType[] MODE_TYPE_ARRAY = new ModeType[]{ModeType.WALK, ModeType.BIKE, ModeType.MIT, ModeType.MIT_PASS, ModeType.TAXI, ModeType.PT, ModeType.TRAIN}
static double NO_CONNECTION = -1
static double VISUM_NO_CONNECTION = 99999.0
Protected Member Functions inherited from de.dlr.ivf.tapas.mode.TPS_Mode
TPS_Mode (String name, String[] attributes, boolean isFix, TPS_ParameterClass parameterClass)
Detailed Description
This class represents the modes 'walk' and 'bike'.
Author
mark_ma
Definition at line 23 of file TPS_NonMotorisedMode.java.
Constructor & Destructor Documentation
TPS_NonMotorisedMode()
de.dlr.ivf.tapas.mode.TPS_NonMotorisedMode.TPS_NonMotorisedMode (String name, String[] attributes, boolean isFix, TPS_ParameterClass parameterClass)
Calls super constructor with name
Parameters
name
parameterClass parameter class reference
Definition at line 31 of file TPS_NonMotorisedMode.java.
References de.dlr.ivf.tapas.mode.TPS_Mode.isFix, de.dlr.ivf.tapas.mode.TPS_Mode.name, and de.dlr.ivf.tapas.mode.TPS_Mode.parameterClass.
Member Function Documentation
getDistance()
double de.dlr.ivf.tapas.mode.TPS_NonMotorisedMode.getDistance (Locatable start, Locatable end, SimulationType simType, TPS_Car car)
This method calculates the real distance between two locations.
Parameters
start location, where this trip starts
end location, where this trip ends
simType Type of simulation (Base/Scenario)
car The car for this trip, if available. Set it to null, if no car is used
Returns
calculated distance in meter
Reimplemented from de.dlr.ivf.tapas.mode.TPS_Mode.
Definition at line 43 of file TPS_NonMotorisedMode.java.
References de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.BIKE, de.dlr.ivf.tapas.util.parameters.ParamMatrix.DISTANCES_BIKE, de.dlr.ivf.tapas.util.parameters.ParamMatrix.DISTANCES_WALK, de.dlr.ivf.tapas.util.TPS_Geometrics.getDistance(), de.dlr.ivf.tapas.mode.TPS_Mode.getParameters(), de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.getTAZId(), de.dlr.ivf.tapas.loc.Locatable.getTrafficAnalysisZone(), de.dlr.ivf.tapas.util.parameters.ParamMatrixClass.getValue(), de.dlr.ivf.tapas.util.parameters.ParamValue.MIN_DIST, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.paramMatrixClass, and de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.WALK.
getTravelTime()
double de.dlr.ivf.tapas.mode.TPS_NonMotorisedMode.getTravelTime (Locatable start, Locatable end, int time, SimulationType simType, TPS_ActivityConstant actCodeFrom, TPS_ActivityConstant actCodeTo, TPS_Person person, TPS_Car car)
This method calculates the travel time between two locations.
Parameters
start location, where this trip starts
end location, where this trip ends
time departure time of the trip in seconds after midnight
simType simulation type
actCodeFrom activity code of the earlier episode
actCodeTo activity code of the later episode
person reference to the person on this trip
Returns
travel time in seconds
Reimplemented from de.dlr.ivf.tapas.mode.TPS_Mode.
Definition at line 65 of file TPS_NonMotorisedMode.java.
References de.dlr.ivf.tapas.util.parameters.ParamMatrixMap.ARRIVAL_BIKE, de.dlr.ivf.tapas.util.parameters.ParamMatrixMap.ARRIVAL_WALK, de.dlr.ivf.tapas.util.parameters.SimulationType.BASE, de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.BIKE, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_ACCESS_BIKE, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_ACCESS_BIKE_BASE, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_ACCESS_WALK, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_ACCESS_WALK_BASE, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_EGRESS_BIKE, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_EGRESS_BIKE_BASE, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_EGRESS_WALK, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_EGRESS_WALK_BASE, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_TT_BIKE, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_TT_BIKE_BASE, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_TT_WALK, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_TT_WALK_BASE, de.dlr.ivf.tapas.util.parameters.ParamMatrix.DISTANCES_BL, de.dlr.ivf.tapas.util.parameters.ParamMatrixMap.EGRESS_BIKE, de.dlr.ivf.tapas.util.parameters.ParamMatrixMap.EGRESS_WALK, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_INTRA_INFOS_MATRIX, de.dlr.ivf.tapas.util.TPS_Geometrics.getDistance(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getDoubleValue(), de.dlr.ivf.tapas.mode.TPS_Mode.getParameters(), de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.getTAZId(), de.dlr.ivf.tapas.loc.Locatable.getTrafficAnalysisZone(), de.dlr.ivf.tapas.util.parameters.ParamMatrixClass.getValue(), de.dlr.ivf.tapas.util.parameters.ParamMatrixMapClass.getValue(), de.dlr.ivf.tapas.mode.TPS_Mode.getVelocity(), de.dlr.ivf.tapas.mode.TPS_Mode.isType(), de.dlr.ivf.tapas.util.parameters.ParamValue.MIN_DIST, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.paramMatrixClass, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.paramMatrixMapClass, de.dlr.ivf.tapas.util.parameters.SimulationType.SCENARIO, de.dlr.ivf.tapas.util.parameters.ParamMatrixMap.TRAVEL_TIME_BIKE, de.dlr.ivf.tapas.util.parameters.ParamMatrixMap.TRAVEL_TIME_WALK, and de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.WALK.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/mode/TPS_NonMotorisedMode.java