TAPAS: de.dlr.ivf.tapas.analyzer.gui.FilesChooser Class Reference
de.dlr.ivf.tapas.analyzer.gui.FilesChooser Class Reference
Classes
class FilesListModel
Public Member Functions
FilesChooser (String name, String title)
FilesChooser (String name)
FileTripReader createFileTripReader (StyledDocument console)
List< File > getFiles ()
String getTitle ()
void setTitle (String title)
boolean isReady ()
Protected Member Functions
List< File > chooseFile ()
void do_btnAdd_actionPerformed (ActionEvent e)
void do_lstFiles_mouseClicked (MouseEvent e)
Private Member Functions
void addFiles (List< File > files)
void createContents (String title)
Private Attributes
final List< File > files = new ArrayList<>()
final String name
JList< File > lstFiles
FilesListModel dataModel
TitledBorder border
Static Private Attributes
static final long serialVersionUID = -8388208545993125633L
Detailed Description
Eine UI-Komponente die das Auswählen mehrerer Dateien ermöglicht. Die ausgewählten Dateien werden in einer Liste angezeigt.
Author
Marco
Definition at line 33 of file FilesChooser.java.
Constructor & Destructor Documentation
FilesChooser() [1/2]
de.dlr.ivf.tapas.analyzer.gui.FilesChooser.FilesChooser (String name, String title)
Create the panel.
Definition at line 48 of file FilesChooser.java.
References de.dlr.ivf.tapas.analyzer.gui.FilesChooser.createContents(), and de.dlr.ivf.tapas.analyzer.gui.FilesChooser.name.
FilesChooser() [2/2]
de.dlr.ivf.tapas.analyzer.gui.FilesChooser.FilesChooser (String name)
Create the panel.
Definition at line 59 of file FilesChooser.java.
References de.dlr.ivf.tapas.analyzer.gui.FilesChooser.createContents(), and de.dlr.ivf.tapas.analyzer.gui.FilesChooser.name.
Member Function Documentation
addFiles()
void de.dlr.ivf.tapas.analyzer.gui.FilesChooser.addFiles (List< File > files) private
Definition at line 66 of file FilesChooser.java.
References de.dlr.ivf.tapas.analyzer.gui.FilesChooser.FilesListModel.changed(), de.dlr.ivf.tapas.analyzer.gui.FilesChooser.dataModel, and de.dlr.ivf.tapas.analyzer.gui.FilesChooser.files.
Referenced by de.dlr.ivf.tapas.analyzer.gui.FilesChooser.do_btnAdd_actionPerformed().
chooseFile()
List<File> de.dlr.ivf.tapas.analyzer.gui.FilesChooser.chooseFile () protected
Definition at line 74 of file FilesChooser.java.
References de.dlr.ivf.tapas.analyzer.gui.FileChooserHistoryManager.getLastDirectory(), de.dlr.ivf.tapas.analyzer.gui.FilesChooser.name, and de.dlr.ivf.tapas.analyzer.gui.FileChooserHistoryManager.updateLastDirectory().
Referenced by de.dlr.ivf.tapas.analyzer.gui.FilesChooser.do_btnAdd_actionPerformed().
createContents()
void de.dlr.ivf.tapas.analyzer.gui.FilesChooser.createContents (String title) private
Definition at line 94 of file FilesChooser.java.
References de.dlr.ivf.tapas.analyzer.gui.FilesChooser.border, de.dlr.ivf.tapas.analyzer.gui.FilesChooser.dataModel, de.dlr.ivf.tapas.analyzer.gui.FilesChooser.do_lstFiles_mouseClicked(), and de.dlr.ivf.tapas.analyzer.gui.FilesChooser.lstFiles.
Referenced by de.dlr.ivf.tapas.analyzer.gui.FilesChooser.FilesChooser().
createFileTripReader()
FileTripReader de.dlr.ivf.tapas.analyzer.gui.FilesChooser.createFileTripReader (StyledDocument console)
Definition at line 135 of file FilesChooser.java.
References de.dlr.ivf.tapas.analyzer.gui.FilesChooser.files.
Referenced by de.dlr.ivf.tapas.analyzer.gui.TripChooserPanel.getTripReader().
do_btnAdd_actionPerformed()
void de.dlr.ivf.tapas.analyzer.gui.FilesChooser.do_btnAdd_actionPerformed (ActionEvent e) protected
Definition at line 143 of file FilesChooser.java.
References de.dlr.ivf.tapas.analyzer.gui.FilesChooser.addFiles(), de.dlr.ivf.tapas.analyzer.gui.FilesChooser.chooseFile(), and de.dlr.ivf.tapas.analyzer.gui.FilesChooser.lstFiles.
do_lstFiles_mouseClicked()
void de.dlr.ivf.tapas.analyzer.gui.FilesChooser.do_lstFiles_mouseClicked (MouseEvent e) protected
Definition at line 148 of file FilesChooser.java.
References de.dlr.ivf.tapas.analyzer.gui.FilesChooser.FilesListModel.changed(), de.dlr.ivf.tapas.analyzer.gui.FilesChooser.dataModel, de.dlr.ivf.tapas.analyzer.gui.FilesChooser.getFiles(), and de.dlr.ivf.tapas.analyzer.gui.FilesChooser.lstFiles.
Referenced by de.dlr.ivf.tapas.analyzer.gui.FilesChooser.createContents().
getFiles()
List<File> de.dlr.ivf.tapas.analyzer.gui.FilesChooser.getFiles ()
Definition at line 160 of file FilesChooser.java.
References de.dlr.ivf.tapas.analyzer.gui.FilesChooser.files.
Referenced by de.dlr.ivf.tapas.analyzer.gui.FilesChooser.do_lstFiles_mouseClicked(), and de.dlr.ivf.tapas.analyzer.gui.Control.getTripFiles().
getTitle()
String de.dlr.ivf.tapas.analyzer.gui.FilesChooser.getTitle ()
Definition at line 164 of file FilesChooser.java.
References de.dlr.ivf.tapas.analyzer.gui.FilesChooser.border.
isReady()
boolean de.dlr.ivf.tapas.analyzer.gui.FilesChooser.isReady ()
Definition at line 172 of file FilesChooser.java.
References de.dlr.ivf.tapas.analyzer.gui.FilesChooser.files.
Referenced by de.dlr.ivf.tapas.analyzer.gui.TripChooserPanel.getTripReader(), and de.dlr.ivf.tapas.analyzer.gui.TripChooserPanel.isReady().
setTitle()
void de.dlr.ivf.tapas.analyzer.gui.FilesChooser.setTitle (String title)
Definition at line 168 of file FilesChooser.java.
References de.dlr.ivf.tapas.analyzer.gui.FilesChooser.border.
Member Data Documentation
border
TitledBorder de.dlr.ivf.tapas.analyzer.gui.FilesChooser.border private
Definition at line 43 of file FilesChooser.java.
Referenced by de.dlr.ivf.tapas.analyzer.gui.FilesChooser.createContents(), de.dlr.ivf.tapas.analyzer.gui.FilesChooser.getTitle(), and de.dlr.ivf.tapas.analyzer.gui.FilesChooser.setTitle().
dataModel
FilesListModel de.dlr.ivf.tapas.analyzer.gui.FilesChooser.dataModel private
Definition at line 42 of file FilesChooser.java.
Referenced by de.dlr.ivf.tapas.analyzer.gui.FilesChooser.addFiles(), de.dlr.ivf.tapas.analyzer.gui.FilesChooser.createContents(), and de.dlr.ivf.tapas.analyzer.gui.FilesChooser.do_lstFiles_mouseClicked().
files
final List<File> de.dlr.ivf.tapas.analyzer.gui.FilesChooser.files = new ArrayList<>() private
Definition at line 39 of file FilesChooser.java.
Referenced by de.dlr.ivf.tapas.analyzer.gui.FilesChooser.addFiles(), de.dlr.ivf.tapas.analyzer.gui.FilesChooser.FilesListModel.changed(), de.dlr.ivf.tapas.analyzer.gui.FilesChooser.createFileTripReader(), de.dlr.ivf.tapas.analyzer.gui.FilesChooser.FilesListModel.getElementAt(), de.dlr.ivf.tapas.analyzer.gui.FilesChooser.getFiles(), de.dlr.ivf.tapas.analyzer.gui.FilesChooser.FilesListModel.getSize(), and de.dlr.ivf.tapas.analyzer.gui.FilesChooser.isReady().
lstFiles
JList<File> de.dlr.ivf.tapas.analyzer.gui.FilesChooser.lstFiles private
Definition at line 41 of file FilesChooser.java.
Referenced by de.dlr.ivf.tapas.analyzer.gui.FilesChooser.createContents(), de.dlr.ivf.tapas.analyzer.gui.FilesChooser.do_btnAdd_actionPerformed(), and de.dlr.ivf.tapas.analyzer.gui.FilesChooser.do_lstFiles_mouseClicked().
name
final String de.dlr.ivf.tapas.analyzer.gui.FilesChooser.name private
Definition at line 40 of file FilesChooser.java.
Referenced by de.dlr.ivf.tapas.analyzer.gui.FilesChooser.chooseFile(), and de.dlr.ivf.tapas.analyzer.gui.FilesChooser.FilesChooser().
serialVersionUID
final long de.dlr.ivf.tapas.analyzer.gui.FilesChooser.serialVersionUID = -8388208545993125633L static private
Definition at line 38 of file FilesChooser.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/gui/FilesChooser.java