TAPAS: de.dlr.ivf.tapas.runtime.util.CPUUsage Class Reference
de.dlr.ivf.tapas.runtime.util.CPUUsage Class Reference
Classes
enum CPUUsageRetrieveType
Public Member Functions
CPUUsage ()
double getCPUUsage () throws IOException, InterruptedException
Private Member Functions
double getPROC () throws IOException
double getWMIC () throws IOException
void init ()
Private Attributes
CPUUsageRetrieveType cpuURT
double lastProcTime = 0
double lastTotalTime = 0
boolean firstRun = true
Detailed Description
This class can be used to determine the CPU usage of a Linux or a Windows System. For Linux the /proc/stat file and for Windows the WMICprocess is used.
Author
mark_ma
Definition at line 26 of file CPUUsage.java.
Constructor & Destructor Documentation
CPUUsage()
de.dlr.ivf.tapas.runtime.util.CPUUsage.CPUUsage ()
The constructor calls the init() method.
Definition at line 39 of file CPUUsage.java.
References de.dlr.ivf.tapas.runtime.util.CPUUsage.init().
Member Function Documentation
getCPUUsage()
double de.dlr.ivf.tapas.runtime.util.CPUUsage.getCPUUsage () throws IOException, InterruptedException
Returns
CPU usage
Exceptions
IOException This exception is thrown if detecting the CPU usage failed
InterruptedException
Definition at line 48 of file CPUUsage.java.
References de.dlr.ivf.tapas.runtime.util.CPUUsage.getPROC(), and de.dlr.ivf.tapas.runtime.util.CPUUsage.getWMIC().
Referenced by de.dlr.ivf.tapas.runtime.util.CPUUsage.init(), and de.dlr.ivf.tapas.runtime.server.SimulationServer.SimulationServerUpdateTask.run().
getPROC()
double de.dlr.ivf.tapas.runtime.util.CPUUsage.getPROC () throws IOException private
Returns
CPU usage from Linux using top
Exceptions
IOException if reading file failed
InterruptedException
Definition at line 68 of file CPUUsage.java.
References de.dlr.ivf.tapas.runtime.util.CPUUsage.lastProcTime.
Referenced by de.dlr.ivf.tapas.runtime.util.CPUUsage.getCPUUsage().
getWMIC()
double de.dlr.ivf.tapas.runtime.util.CPUUsage.getWMIC () throws IOException private
Returns
CPU usage from Windows WMIC process
Exceptions
IOException This exception is thrown if the communication with the Windows WMIC process failed
Definition at line 114 of file CPUUsage.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, and de.dlr.ivf.tapas.log.TPS_Logger.log().
Referenced by de.dlr.ivf.tapas.runtime.util.CPUUsage.getCPUUsage().
init()
void de.dlr.ivf.tapas.runtime.util.CPUUsage.init () private
This method tries to find a method to retrieve the CPU usage from the system.
Exceptions
RuntimeException This exception is throw if not method was found
Definition at line 164 of file CPUUsage.java.
References de.dlr.ivf.tapas.runtime.util.CPUUsage.cpuURT, de.dlr.ivf.tapas.runtime.util.CPUUsage.getCPUUsage(), de.dlr.ivf.tapas.runtime.util.CPUUsage.CPUUsageRetrieveType.PROC, and de.dlr.ivf.tapas.runtime.util.CPUUsage.CPUUsageRetrieveType.WMIC.
Referenced by de.dlr.ivf.tapas.runtime.util.CPUUsage.CPUUsage().
Member Data Documentation
cpuURT
CPUUsageRetrieveType de.dlr.ivf.tapas.runtime.util.CPUUsage.cpuURT private
Method to retrieve the CPU usage
Definition at line 31 of file CPUUsage.java.
Referenced by de.dlr.ivf.tapas.runtime.util.CPUUsage.init().
firstRun
boolean de.dlr.ivf.tapas.runtime.util.CPUUsage.firstRun = true private
Definition at line 34 of file CPUUsage.java.
lastProcTime
double de.dlr.ivf.tapas.runtime.util.CPUUsage.lastProcTime = 0 private
Definition at line 32 of file CPUUsage.java.
Referenced by de.dlr.ivf.tapas.runtime.util.CPUUsage.getPROC().
lastTotalTime
double de.dlr.ivf.tapas.runtime.util.CPUUsage.lastTotalTime = 0 private
Definition at line 33 of file CPUUsage.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/runtime/util/CPUUsage.java