TAPAS: de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution Class Reference
de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution Class Reference
Classes
class DModellKreisMapping
class DVZMappingElement
class ODPair
class TAZ
class Vehicle
Public Member Functions
TPS_ExternalTrafficDistribution ()
void clearTrafficDistribution ()
void distributeOverDay ()
void distributeOverLocations (double calib)
void fillBusDistribution2010 ()
void fillCarDistribution2010 ()
void fillHDVDistribution2010 ()
void fillPTDistribution2010 ()
void fillTrailerDistribution2010 ()
void fillTruck12Distribution2010 ()
void fillTruck35Distribution2010 ()
void fillTruck75Distribution2010 ()
void loadCordonDistricts (String tableName, String dmod, int berlinId)
void loadCordonDistrictsKoFIF (String tableName, String dmod, int berlinId)
void loadDayDistribution ()
void loadExternalPositions (String tableName, String mappingTable)
void loadODPairs (String fileName, boolean useInternalTraffic)
void loadTAPASDeutschlandmodellMapping (int minCapacity, String locName, String zonierungsName)
void saveToDB (String tablename, int modeNumber, boolean is_resticted, boolean createTable)
Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_BasicConnectionClass ()
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass)
TPS_BasicConnectionClass (String loginFile)
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass, String loginFile)
boolean checkMatrixName (String matrixName)
TPS_ParameterClass getParameters ()
String readParameter (String simKey, String paramKey)
void storeInDB (String matrixName, double[][] matrix, int decimalPlaces)
Static Public Member Functions
static void main (String[] args)
Static Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
static double[][] array1Dto2D (Integer[] matrixVal)
static double[][] array1Dto2D (int[] matrixVal)
static File getRuntimeFile (boolean forceNewFile)
static File getRuntimeFile (String propertyFile, boolean forceNewFile)
static File getRuntimeFile ()
static File getRuntimeFile (String propertyFile)
static int[][] intArray1Dto2D (int[] matrixVal)
static String matrixToSQLArray (double[][] array, int decimalPlaces)
static StringWriter matrixToStringWriterSQL (double[][] array, int decimalPlaces)
Additional Inherited Members
Protected Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
void finalize ()
Protected Attributes inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_DB_Connector dbCon = null
TPS_ParameterClass parameterClass
Detailed Description
Definition at line 25 of file TPS_ExternalTrafficDistribution.java.
Constructor & Destructor Documentation
TPS_ExternalTrafficDistribution()
de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.TPS_ExternalTrafficDistribution ()
Definition at line 43 of file TPS_ExternalTrafficDistribution.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.main().
Member Function Documentation
clearTrafficDistribution()
void de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.clearTrafficDistribution ()
Definition at line 207 of file TPS_ExternalTrafficDistribution.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.main().
distributeOverDay()
void de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.distributeOverDay ()
Definition at line 217 of file TPS_ExternalTrafficDistribution.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.main().
distributeOverLocations()
void de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.distributeOverLocations (double calib)
Definition at line 260 of file TPS_ExternalTrafficDistribution.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.main().
fillBusDistribution2010()
void de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.fillBusDistribution2010 ()
Definition at line 369 of file TPS_ExternalTrafficDistribution.java.
fillCarDistribution2010()
void de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.fillCarDistribution2010 ()
Definition at line 375 of file TPS_ExternalTrafficDistribution.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.main().
fillHDVDistribution2010()
void de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.fillHDVDistribution2010 ()
Definition at line 387 of file TPS_ExternalTrafficDistribution.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.main().
fillPTDistribution2010()
void de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.fillPTDistribution2010 ()
Definition at line 393 of file TPS_ExternalTrafficDistribution.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.main().
fillTrailerDistribution2010()
void de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.fillTrailerDistribution2010 ()
Definition at line 399 of file TPS_ExternalTrafficDistribution.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.main().
fillTruck12Distribution2010()
void de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.fillTruck12Distribution2010 ()
Definition at line 405 of file TPS_ExternalTrafficDistribution.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.main().
fillTruck35Distribution2010()
void de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.fillTruck35Distribution2010 ()
Definition at line 411 of file TPS_ExternalTrafficDistribution.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.main().
fillTruck75Distribution2010()
void de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.fillTruck75Distribution2010 ()
Definition at line 417 of file TPS_ExternalTrafficDistribution.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.main().
loadCordonDistricts()
void de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.loadCordonDistricts (String tableName, String dmod, int berlinId)
Definition at line 423 of file TPS_ExternalTrafficDistribution.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery().
Referenced by de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.main().
loadCordonDistrictsKoFIF()
void de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.loadCordonDistrictsKoFIF (String tableName, String dmod, int berlinId)
Definition at line 470 of file TPS_ExternalTrafficDistribution.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery().
loadDayDistribution()
void de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.loadDayDistribution ()
Definition at line 519 of file TPS_ExternalTrafficDistribution.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.main().
loadExternalPositions()
void de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.loadExternalPositions (String tableName, String mappingTable)
Definition at line 670 of file TPS_ExternalTrafficDistribution.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery().
Referenced by de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.main().
loadODPairs()
void de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.loadODPairs (String fileName, boolean useInternalTraffic)
Definition at line 827 of file TPS_ExternalTrafficDistribution.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.main().
loadTAPASDeutschlandmodellMapping()
void de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.loadTAPASDeutschlandmodellMapping (int minCapacity, String locName, String zonierungsName)
Definition at line 981 of file TPS_ExternalTrafficDistribution.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery().
Referenced by de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.main().
main()
static void de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.main (String[] args) static
Definition at line 60 of file TPS_ExternalTrafficDistribution.java.
References de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.clearTrafficDistribution(), de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.distributeOverDay(), de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.distributeOverLocations(), de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.fillCarDistribution2010(), de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.fillHDVDistribution2010(), de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.fillPTDistribution2010(), de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.fillTrailerDistribution2010(), de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.fillTruck12Distribution2010(), de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.fillTruck35Distribution2010(), de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.fillTruck75Distribution2010(), de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.loadCordonDistricts(), de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.loadDayDistribution(), de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.loadExternalPositions(), de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.loadODPairs(), de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.loadTAPASDeutschlandmodellMapping(), de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.saveToDB(), and de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.TPS_ExternalTrafficDistribution().
saveToDB()
void de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.saveToDB (String tablename, int modeNumber, boolean is_resticted, boolean createTable)
Definition at line 1027 of file TPS_ExternalTrafficDistribution.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection(), and de.dlr.ivf.tapas.util.TPS_Geometrics.getDistance().
Referenced by de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.main().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/TPS_ExternalTrafficDistribution.java