TAPAS: de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode Class Reference
de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode Class Reference abstract
Public Member Functions
TPS_AdaptedEpisode (TPS_Plan plan, TPS_Episode episode)
double getDistance ()
void setDistance (double distance)
double getDistanceBeeline ()
void setDistanceBeeline (double distanceBeeline)
double getDistanceEmptyNet ()
void setDistanceEmptyNet (double distanceEmptyNet)
int getDuration ()
void setDuration (int duration)
int getEnd ()
abstract TPS_Episode getEpisode ()
int getStart ()
void setStart (int start)
abstract boolean isLocatedStay ()
boolean isPlannedTrip ()
Protected Member Functions
void init (TPS_Episode episode)
Protected Attributes
TPS_Plan plan
Private Attributes
double distance
double distanceBeeline
double distanceEmptyNet
int duration
int start
Detailed Description
This is the basic class for an adapted episode. It stores all modified values of an episode in a scheme.
Author
mark_ma
Definition at line 21 of file TPS_AdaptedEpisode.java.
Constructor & Destructor Documentation
TPS_AdaptedEpisode()
de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.TPS_AdaptedEpisode (TPS_Plan plan, TPS_Episode episode)
Builds this instance and calls the TPS_AdaptedEpisode::init Method.
Parameters
plan Reference to the whole plan
episode Reference to this episode of the plan
Definition at line 51 of file TPS_AdaptedEpisode.java.
Member Function Documentation
getDistance()
double de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.getDistance ()
Returns
real distance in meters
Definition at line 59 of file TPS_AdaptedEpisode.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.batchStoreTrips(), de.dlr.ivf.tapas.plan.TPS_Plan.calcPlanFeasiblity(), de.dlr.ivf.tapas.plan.TPS_Plan.createOutput(), de.dlr.ivf.tapas.scheme.TPS_TourPart.updateActualTravelDurations(), and de.dlr.ivf.tapas.plan.TPS_Plan.writeOutputStream().
getDistanceBeeline()
double de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.getDistanceBeeline ()
Returns
beeline distance
Definition at line 75 of file TPS_AdaptedEpisode.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.batchStoreTrips(), de.dlr.ivf.tapas.plan.TPS_Plan.createOutput(), and de.dlr.ivf.tapas.plan.TPS_Plan.writeOutputStream().
getDistanceEmptyNet()
double de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.getDistanceEmptyNet ()
Returns
net distance
Definition at line 91 of file TPS_AdaptedEpisode.java.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.createOutput(), and de.dlr.ivf.tapas.plan.TPS_Plan.writeOutputStream().
getDuration()
int de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.getDuration ()
Returns
duration
Definition at line 107 of file TPS_AdaptedEpisode.java.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.balanceStarts(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.batchStoreTrips(), de.dlr.ivf.tapas.plan.TPS_Plan.calcPlanFeasiblity(), de.dlr.ivf.tapas.plan.TPS_Plan.createOutput(), de.dlr.ivf.tapas.scheme.TPS_TourPart.updateActualTravelDistances(), and de.dlr.ivf.tapas.plan.TPS_Plan.writeOutputStream().
getEnd()
int de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.getEnd ()
Returns
end time
Definition at line 123 of file TPS_AdaptedEpisode.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Worker.assignCarToPlan(), and de.dlr.ivf.tapas.plan.TPS_Plan.balanceStarts().
getEpisode()
abstract TPS_Episode de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.getEpisode () abstract
Returns
episode
Reimplemented in de.dlr.ivf.tapas.plan.TPS_PlannedTrip, and de.dlr.ivf.tapas.plan.TPS_LocatedStay.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.getHierarchizedPreviousStay(), and de.dlr.ivf.tapas.plan.TPS_Plan.getPreviousLocatedStay().
getStart()
int de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.getStart ()
Returns
start time
Definition at line 135 of file TPS_AdaptedEpisode.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Worker.assignCarToPlan(), de.dlr.ivf.tapas.plan.TPS_Plan.balanceStarts(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.batchStoreTrips(), de.dlr.ivf.tapas.plan.TPS_Plan.calcPlanFeasiblity(), de.dlr.ivf.tapas.plan.TPS_Plan.createOutput(), and de.dlr.ivf.tapas.plan.TPS_Plan.writeOutputStream().
init()
void de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.init (TPS_Episode episode) protected
This method initialises the member values by reading the start and duration from the episode.
Parameters
episode
Definition at line 153 of file TPS_AdaptedEpisode.java.
References de.dlr.ivf.tapas.scheme.TPS_Episode.getOriginalDuration(), and de.dlr.ivf.tapas.scheme.TPS_Episode.getOriginalStart().
isLocatedStay()
abstract boolean de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.isLocatedStay () abstract
Returns
true if it is a located stay false otherwise
Reimplemented in de.dlr.ivf.tapas.plan.TPS_PlannedTrip, and de.dlr.ivf.tapas.plan.TPS_LocatedStay.
isPlannedTrip()
boolean de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.isPlannedTrip ()
Returns
true if it is a planned trip false otherwise
Definition at line 169 of file TPS_AdaptedEpisode.java.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.calcPlanFeasiblity().
setDistance()
void de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.setDistance (double distance)
Sets the distance
Parameters
distance
Definition at line 68 of file TPS_AdaptedEpisode.java.
setDistanceBeeline()
void de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.setDistanceBeeline (double distanceBeeline)
Sets the beeline distance
Parameters
distanceBeeline
Definition at line 84 of file TPS_AdaptedEpisode.java.
setDistanceEmptyNet()
void de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.setDistanceEmptyNet (double distanceEmptyNet)
Sets the net distance
Parameters
distanceEmptyNet
Definition at line 100 of file TPS_AdaptedEpisode.java.
setDuration()
void de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.setDuration (int duration)
Sets the duration
Parameters
duration
Definition at line 116 of file TPS_AdaptedEpisode.java.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.calcPlanFeasiblity().
setStart()
void de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.setStart (int start)
Sets the start
Parameters
start
Definition at line 144 of file TPS_AdaptedEpisode.java.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.balanceStarts().
Member Data Documentation
distance
double de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.distance private
real distance
Definition at line 27 of file TPS_AdaptedEpisode.java.
distanceBeeline
double de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.distanceBeeline private
beeline distance
Definition at line 31 of file TPS_AdaptedEpisode.java.
distanceEmptyNet
double de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.distanceEmptyNet private
net distance
Definition at line 35 of file TPS_AdaptedEpisode.java.
duration
int de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.duration private
duration of the episode
Definition at line 39 of file TPS_AdaptedEpisode.java.
plan
TPS_Plan de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.plan protected
Definition at line 23 of file TPS_AdaptedEpisode.java.
Referenced by de.dlr.ivf.tapas.plan.TPS_LocatedStay.TPS_LocatedStay().
start
int de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.start private
starting time of the episode in minutes
Definition at line 43 of file TPS_AdaptedEpisode.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/plan/TPS_AdaptedEpisode.java