TAPAS: de.dlr.ivf.tapas.tools.tazcalculator.TAZSRVAggregator Class Reference
de.dlr.ivf.tapas.tools.tazcalculator.TAZSRVAggregator Class Reference
Classes
class Point
Static Public Member Functions
static void main (String[] args)
Private Member Functions
double[][] calculateAggegation (double[][] source, boolean useMedian)
double[][] calculateBeeline ()
double[][] readMatrices (String name)
void readStatisticalAreasMappingf (String name)
void readTAZCentroids (String string)
void writeMatrix (double[][] matrix, String file)
void writeODValueFile (double[][] matrix, String file)
Detailed Description
This class reads a mapping file for tvz to a more aggregate level. Then it loads some source/dest-matrices and calculates the mean or median of the aggregated values. Please see main routine for filepaths (hard coded fro simplicity...)
Author
hein_mh
Definition at line 27 of file TAZSRVAggregator.java.
Member Function Documentation
calculateAggegation()
double [][] de.dlr.ivf.tapas.tools.tazcalculator.TAZSRVAggregator.calculateAggegation (double source[][], boolean useMedian) private
Calculates the aggregated s/d-matrix. The flag useMedian determines, if the resulting correspondences should be outlierfiltered: Largest and smallest values are removed from the aggregation set.
Parameters
source source matrix
useMedian flag for median filtering
Returns
aggregated matrix
Definition at line 96 of file TAZSRVAggregator.java.
Referenced by de.dlr.ivf.tapas.tools.tazcalculator.TAZSRVAggregator.main().
calculateBeeline()
double [][] de.dlr.ivf.tapas.tools.tazcalculator.TAZSRVAggregator.calculateBeeline () private
Internal method to calculate the beeline matrix of the tvz-centroids
Returns
Definition at line 155 of file TAZSRVAggregator.java.
Referenced by de.dlr.ivf.tapas.tools.tazcalculator.TAZSRVAggregator.main().
main()
static void de.dlr.ivf.tapas.tools.tazcalculator.TAZSRVAggregator.main (String[] args) static
Parameters
args
Definition at line 38 of file TAZSRVAggregator.java.
References de.dlr.ivf.tapas.util.TPS_Geometrics.calcTop3(), de.dlr.ivf.tapas.tools.tazcalculator.TAZSRVAggregator.calculateAggegation(), de.dlr.ivf.tapas.tools.tazcalculator.TAZSRVAggregator.calculateBeeline(), de.dlr.ivf.tapas.tools.tazcalculator.TAZSRVAggregator.readMatrices(), de.dlr.ivf.tapas.tools.tazcalculator.TAZSRVAggregator.readStatisticalAreasMappingf(), de.dlr.ivf.tapas.tools.tazcalculator.TAZSRVAggregator.readTAZCentroids(), de.dlr.ivf.tapas.tools.tazcalculator.TAZSRVAggregator.writeMatrix(), and de.dlr.ivf.tapas.tools.tazcalculator.TAZSRVAggregator.writeODValueFile().
readMatrices()
double [][] de.dlr.ivf.tapas.tools.tazcalculator.TAZSRVAggregator.readMatrices (String name) private
Function to read a specified o/d-matrix. Tab or space delimited row-wise matrix
Parameters
name Input
Returns
matrix or null
Definition at line 181 of file TAZSRVAggregator.java.
References name.
Referenced by de.dlr.ivf.tapas.tools.tazcalculator.TAZSRVAggregator.main().
readStatisticalAreasMappingf()
void de.dlr.ivf.tapas.tools.tazcalculator.TAZSRVAggregator.readStatisticalAreasMappingf (String name) private
Function to read a mapping file (semicolon separated with header): source id;destinantion id
Parameters
name The filename
Definition at line 231 of file TAZSRVAggregator.java.
References name.
Referenced by de.dlr.ivf.tapas.tools.tazcalculator.TAZSRVAggregator.main().
readTAZCentroids()
void de.dlr.ivf.tapas.tools.tazcalculator.TAZSRVAggregator.readTAZCentroids (String string) private
Function to read taz-coordinates from a csv-file tab-separated without header: id x y
Parameters
string input file
Definition at line 279 of file TAZSRVAggregator.java.
Referenced by de.dlr.ivf.tapas.tools.tazcalculator.TAZSRVAggregator.main().
writeMatrix()
void de.dlr.ivf.tapas.tools.tazcalculator.TAZSRVAggregator.writeMatrix (double matrix[][], String file) private
Writes a tab separated matrix
Parameters
matrix input
file outpu
Definition at line 324 of file TAZSRVAggregator.java.
Referenced by de.dlr.ivf.tapas.tools.tazcalculator.TAZSRVAggregator.main().
writeODValueFile()
void de.dlr.ivf.tapas.tools.tazcalculator.TAZSRVAggregator.writeODValueFile (double matrix[][], String file) private
Definition at line 344 of file TAZSRVAggregator.java.
Referenced by de.dlr.ivf.tapas.tools.tazcalculator.TAZSRVAggregator.main().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/tazcalculator/TAZSRVAggregator.java