TAPAS: de.dlr.ivf.tapas.person.TPS_Car Class Reference
de.dlr.ivf.tapas.person.TPS_Car Class Reference
Classes
enum CarSize
enum EmissionClass
enum FuelType
Public Member Functions
TPS_Car (int id)
void cloneCar (TPS_Car original)
int getAutomation ()
void setAutomation (int automation)
CarSize getCarSize ()
double getCostPerKilometer (SimulationType simType)
EmissionClass getEmissionClass ()
double getFixCosts ()
void setFixCosts (double newCosts)
FuelType getFuelType ()
int getId ()
void setId (int id)
int getKBANumber ()
double getRangeLeft ()
int getSumoHBEFACode (boolean use7Code)
int getSumoVehicleClass ()
double getVariableCostPerKilometer (SimulationType simType)
void init (FuelType type, int kba, EmissionClass emissionClass, double fixCosts, boolean companyCar, boolean isRestricted, TPS_ParameterClass parameterClass, int index)
boolean isAvailable (double start, double end)
boolean isAvailable (int start, int end)
boolean isCompanyCar ()
void setCompanyCar (boolean companyCar)
boolean isRestricted ()
void setRestricted (boolean restricted)
boolean pickCar (double start, double end, double distance, boolean payToll)
boolean pickCar (int start, int end, boolean payToll)
void reduceRange (double tripLength)
void refuelCar ()
void setEngineClass (EmissionClass emissionClass)
boolean unPickCar (double start, double end)
boolean unPickCar (int start, int end)
Static Public Member Functions
static CarSize getCarSize (int kba_no)
static int getSumoVehicleClass (CarSize size, FuelType type, boolean isRestricted)
static TPS_Car selectCar (TPS_Plan plan, TPS_TourPart tourpart)
Public Attributes
boolean hasPaidToll = false
int index = -1
Static Public Attributes
static FuelType[] FUEL_TYPE_ARRAY = new FuelType[]{FuelType.BENZINE, FuelType.DIESEL, FuelType.GAS, FuelType.EMOBILE, FuelType.PLUGIN, FuelType.FUELCELL, FuelType.LPG}
static EmissionClass[] EMISSION_TYPE_ARRAY = new EmissionClass[]{EmissionClass.EURO_0, EmissionClass.EURO_1, EmissionClass.EURO_2, EmissionClass.EURO_3, EmissionClass.EURO_4, EmissionClass.EURO_5, EmissionClass.EURO_6}
Private Member Functions
double getKBAFuelCostPerKilometerFactor (SimulationType type)
double getKBAVariableCostPerKilometerFactor ()
Private Attributes
Timeline availability
FuelType type
int kbaNo
int id
EmissionClass emissionClass
boolean restricted = false
int automationLevel = 0
double rangeLeft = 0.0
boolean companyCar = false
double fixCosts = 0.0
TPS_ParameterClass parameterClass
Detailed Description
Class for different car types# Size Attributes: Large, Medium, Small, Transporter Fuel Attributes: Benzine, Diesel, Plugin (hybrid), EMobil (Range limited) Internal attributes: available, costPerKilometer, variableCostsPerKilometer, range
Author
hein_mh
Definition at line 30 of file TPS_Car.java.
Constructor & Destructor Documentation
TPS_Car()
de.dlr.ivf.tapas.person.TPS_Car.TPS_Car (int id)
Constructor class for a new car.
Parameters
id of this car
Definition at line 84 of file TPS_Car.java.
Member Function Documentation
cloneCar()
void de.dlr.ivf.tapas.person.TPS_Car.cloneCar (TPS_Car original)
Method to clone the parameters from a given car type to this instance. DO NOT COPY THE INDEX!
Parameters
original the car which holds the desired values.
Definition at line 334 of file TPS_Car.java.
References de.dlr.ivf.tapas.person.TPS_Car.automationLevel, de.dlr.ivf.tapas.person.TPS_Car.companyCar, de.dlr.ivf.tapas.person.TPS_Car.emissionClass, de.dlr.ivf.tapas.person.TPS_Car.fixCosts, de.dlr.ivf.tapas.person.TPS_Car.kbaNo, de.dlr.ivf.tapas.person.TPS_Car.restricted, and de.dlr.ivf.tapas.person.TPS_Car.type.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.loadHouseholds().
getAutomation()
int de.dlr.ivf.tapas.person.TPS_Car.getAutomation ()
Returns
the automation
Definition at line 347 of file TPS_Car.java.
Referenced by de.dlr.ivf.tapas.mode.TPS_IndividualTransportMode.getTravelTime().
getCarSize() [1/2]
CarSize de.dlr.ivf.tapas.person.TPS_Car.getCarSize ()
This method converts the internal kba number to a size
Returns
the car size
Definition at line 363 of file TPS_Car.java.
References de.dlr.ivf.tapas.person.TPS_Car.getCarSize().
getCarSize() [2/2]
static CarSize de.dlr.ivf.tapas.person.TPS_Car.getCarSize (int kba_no) static
This method converts the given kba number to a size
Parameters
kba_no the kba number to convert
Returns
the car size
Definition at line 94 of file TPS_Car.java.
References de.dlr.ivf.tapas.person.TPS_Car.CarSize.LARGE, de.dlr.ivf.tapas.person.TPS_Car.CarSize.MEDIUM, de.dlr.ivf.tapas.person.TPS_Car.CarSize.SMALL, and de.dlr.ivf.tapas.person.TPS_Car.CarSize.TRANSPORTER.
Referenced by de.dlr.ivf.scripts.FleetAnalyzer.analyzeSegments(), and de.dlr.ivf.tapas.person.TPS_Car.getCarSize().
getCostPerKilometer()
double de.dlr.ivf.tapas.person.TPS_Car.getCostPerKilometer (SimulationType simType)
Method to get the cost per kilometre, depending on fueltype
Definition at line 370 of file TPS_Car.java.
References de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getDoubleValue(), and type.
getEmissionClass()
EmissionClass de.dlr.ivf.tapas.person.TPS_Car.getEmissionClass ()
Returns
the engineClass
Definition at line 383 of file TPS_Car.java.
getFixCosts()
double de.dlr.ivf.tapas.person.TPS_Car.getFixCosts ()
Method to get the fixed costs of this car
Returns
the actual fix costs
Definition at line 392 of file TPS_Car.java.
getFuelType()
FuelType de.dlr.ivf.tapas.person.TPS_Car.getFuelType ()
Method to get the fuel type of this car
Returns
the reference of the fueltype, which is a singelton
Definition at line 410 of file TPS_Car.java.
References type.
getId()
int de.dlr.ivf.tapas.person.TPS_Car.getId ()
GEts the id of this car
Returns
the car id
Definition at line 419 of file TPS_Car.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.loadHouseholds().
getKBAFuelCostPerKilometerFactor()
double de.dlr.ivf.tapas.person.TPS_Car.getKBAFuelCostPerKilometerFactor (SimulationType type) private
This method gives the fuel factor derived from internal variables.
These factors come from the KBA and MID flre analysis from the ecoMove Project
Parameters
type
Returns
the fuel factor
Definition at line 441 of file TPS_Car.java.
References de.dlr.ivf.tapas.util.parameters.SimulationType.BASE, de.dlr.ivf.tapas.person.TPS_Car.FuelType.DIESEL, and type.
getKBANumber()
int de.dlr.ivf.tapas.person.TPS_Car.getKBANumber ()
Method to get the kba-number of this car
Returns
the kba number
Definition at line 480 of file TPS_Car.java.
getKBAVariableCostPerKilometerFactor()
double de.dlr.ivf.tapas.person.TPS_Car.getKBAVariableCostPerKilometerFactor () private
This method gives the variable cost factor derived from internal variables. Guessed by Matthias Heinrichs
Returns
the variable cost factor
Definition at line 489 of file TPS_Car.java.
getRangeLeft()
double de.dlr.ivf.tapas.person.TPS_Car.getRangeLeft ()
Method to get the actual range, which can be driven by this car today
Returns
the left range
Definition at line 516 of file TPS_Car.java.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.allowsCar().
getSumoHBEFACode()
int de.dlr.ivf.tapas.person.TPS_Car.getSumoHBEFACode (boolean use7Code)
Returns the SUMO cade for the HBEFA-class of this car
Parameters
use7Code use 7 or 14 classes?
Returns
the sumo HBEFA-code
Definition at line 526 of file TPS_Car.java.
References de.dlr.ivf.tapas.person.TPS_Car.FuelType.BENZINE.
getSumoVehicleClass() [1/2]
int de.dlr.ivf.tapas.person.TPS_Car.getSumoVehicleClass ()
Returns the SUMO cade for the vehilce-class of this car
Returns
the sumo vclass-code
Definition at line 608 of file TPS_Car.java.
getSumoVehicleClass() [2/2]
static int de.dlr.ivf.tapas.person.TPS_Car.getSumoVehicleClass (CarSize size, FuelType type, boolean isRestricted) static
Returns the SUMO cade for the vehilce-class of thet given car size
Parameters
size the size of this car
type the engine-type of this car
isRestricted Has this car access restrictions?
Returns
the sumo vclass-code
Definition at line 130 of file TPS_Car.java.
References type.
getVariableCostPerKilometer()
double de.dlr.ivf.tapas.person.TPS_Car.getVariableCostPerKilometer (SimulationType simType)
Method to get the cost per kilometre, depending on fueltype
Definition at line 615 of file TPS_Car.java.
References de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getDoubleValue(), and type.
init()
void de.dlr.ivf.tapas.person.TPS_Car.init (FuelType type, int kba, EmissionClass emissionClass, double fixCosts, boolean companyCar, boolean isRestricted, TPS_ParameterClass parameterClass, int index)
Initialisies this instance
Parameters
type fuel type of this car
kba the kba type of this car
emissionClass the emission class of this car (Euro0-6)
fixCosts the fix costs for this car, e.g. taxes, insurance
companyCar flag if this is a company car or not. Company cars do not produce individual costs
isRestricted flag to indicate that this car is restricted for entering certain areas
parameterClass parameter class reference
Definition at line 632 of file TPS_Car.java.
References de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getDoubleValue(), de.dlr.ivf.tapas.person.TPS_Car.FuelType.getRange(), de.dlr.ivf.tapas.util.parameters.SimulationType.SCENARIO, and type.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.loadHouseholds().
isAvailable() [1/2]
boolean de.dlr.ivf.tapas.person.TPS_Car.isAvailable (double start, double end)
checks if this car is available and standing at home
Returns
returns the availability status
Definition at line 650 of file TPS_Car.java.
References de.dlr.ivf.tapas.util.Timeline.clash().
isAvailable() [2/2]
boolean de.dlr.ivf.tapas.person.TPS_Car.isAvailable (int start, int end)
checks if this car is available and standing at home
Returns
returns the availability status
Definition at line 659 of file TPS_Car.java.
References de.dlr.ivf.tapas.util.Timeline.clash().
isCompanyCar()
boolean de.dlr.ivf.tapas.person.TPS_Car.isCompanyCar ()
Definition at line 663 of file TPS_Car.java.
isRestricted()
boolean de.dlr.ivf.tapas.person.TPS_Car.isRestricted ()
Returns
the restricted
Definition at line 674 of file TPS_Car.java.
Referenced by de.dlr.ivf.tapas.loc.TPS_MultipleTAZRepresentant.getLocationRepresentatives(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.getModeLogSum(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessMode.getTravelTime(), de.dlr.ivf.tapas.loc.TPS_SelectWithSingleAccessMode.getTravelTime(), and de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes().
pickCar() [1/2]
boolean de.dlr.ivf.tapas.person.TPS_Car.pickCar (double start, double end, double distance, boolean payToll)
Picks the car for the time period specified
Parameters
start time period start
end time period end
Returns
success of this action
Definition at line 692 of file TPS_Car.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Worker.assignCarToPlan().
pickCar() [2/2]
boolean de.dlr.ivf.tapas.person.TPS_Car.pickCar (int start, int end, boolean payToll)
Picks the car for the time period specified
Parameters
start time period start
end time period end
payToll flag to indicate that this car pays a entry/exit toll
Returns
success of this action
Definition at line 710 of file TPS_Car.java.
References de.dlr.ivf.tapas.util.Timeline.add().
reduceRange()
void de.dlr.ivf.tapas.person.TPS_Car.reduceRange (double tripLength)
reduces the actual range for this car after a return to home
Parameters
tripLength
Definition at line 725 of file TPS_Car.java.
refuelCar()
void de.dlr.ivf.tapas.person.TPS_Car.refuelCar ()
Method to trigger, that the car is refuelled, e.g. long stay at home
Definition at line 732 of file TPS_Car.java.
References de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getDoubleValue(), de.dlr.ivf.tapas.person.TPS_Car.FuelType.getRange(), and de.dlr.ivf.tapas.util.parameters.SimulationType.SCENARIO.
selectCar()
static TPS_Car de.dlr.ivf.tapas.person.TPS_Car.selectCar (TPS_Plan plan, TPS_TourPart tourpart) static
Method to select a car from the household for the tourpart
Parameters
plan The plan which is processed.
tourpart The tourpart for this query
Returns
null if no car is a available, otherwise a car, which can be used.
Definition at line 303 of file TPS_Car.java.
References de.dlr.ivf.tapas.person.TPS_Household.getAvailableCars(), de.dlr.ivf.tapas.scheme.TPS_TourPart.getCar(), de.dlr.ivf.tapas.person.TPS_Person.getHousehold(), de.dlr.ivf.tapas.scheme.TPS_SchemePart.getOriginalSchemePartEnd(), de.dlr.ivf.tapas.scheme.TPS_SchemePart.getOriginalSchemePartStart(), de.dlr.ivf.tapas.plan.TPS_Plan.getPerson(), and de.dlr.ivf.tapas.scheme.TPS_TourPart.isCarUsed().
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes().
setAutomation()
void de.dlr.ivf.tapas.person.TPS_Car.setAutomation (int automation)
Parameters
automation the automation to set
Definition at line 354 of file TPS_Car.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.loadHouseholds().
setCompanyCar()
void de.dlr.ivf.tapas.person.TPS_Car.setCompanyCar (boolean companyCar)
Definition at line 667 of file TPS_Car.java.
setEngineClass()
void de.dlr.ivf.tapas.person.TPS_Car.setEngineClass (EmissionClass emissionClass)
Parameters
emissionClass the EmissionClass to set
Definition at line 739 of file TPS_Car.java.
setFixCosts()
void de.dlr.ivf.tapas.person.TPS_Car.setFixCosts (double newCosts)
Method to set the fixed costs of this car
Parameters
newCosts the new fixed costs for this car
Definition at line 401 of file TPS_Car.java.
setId()
void de.dlr.ivf.tapas.person.TPS_Car.setId (int id)
sets the id for this car.
Parameters
id the id to set
Definition at line 428 of file TPS_Car.java.
setRestricted()
void de.dlr.ivf.tapas.person.TPS_Car.setRestricted (boolean restricted)
Parameters
restricted the restricted to set
Definition at line 681 of file TPS_Car.java.
unPickCar() [1/2]
boolean de.dlr.ivf.tapas.person.TPS_Car.unPickCar (double start, double end)
Unpicks the car for the time period specified
Parameters
start time period start
end time period end
Returns
success of this action
Definition at line 750 of file TPS_Car.java.
unPickCar() [2/2]
boolean de.dlr.ivf.tapas.person.TPS_Car.unPickCar (int start, int end)
Unpicks the car for the time period specified
Parameters
start time period start
end time period end
Returns
success of this action
Definition at line 761 of file TPS_Car.java.
References de.dlr.ivf.tapas.util.Timeline.remove().
Member Data Documentation
automationLevel
int de.dlr.ivf.tapas.person.TPS_Car.automationLevel = 0 private
Level of automation for this car
Definition at line 64 of file TPS_Car.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Car.cloneCar().
availability
Timeline de.dlr.ivf.tapas.person.TPS_Car.availability private
indicates if this car is available (standing in front of the home)
Definition at line 39 of file TPS_Car.java.
companyCar
boolean de.dlr.ivf.tapas.person.TPS_Car.companyCar = false private
is this car a company car?
Definition at line 72 of file TPS_Car.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Car.cloneCar().
EMISSION_TYPE_ARRAY
EmissionClass [] de.dlr.ivf.tapas.person.TPS_Car.EMISSION_TYPE_ARRAY = new EmissionClass[]{EmissionClass.EURO_0, EmissionClass.EURO_1, EmissionClass.EURO_2, EmissionClass.EURO_3, EmissionClass.EURO_4, EmissionClass.EURO_5, EmissionClass.EURO_6} static
Definition at line 33 of file TPS_Car.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.loadHouseholds().
emissionClass
EmissionClass de.dlr.ivf.tapas.person.TPS_Car.emissionClass private
Enum for the engine emissions class
Definition at line 55 of file TPS_Car.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Car.cloneCar().
fixCosts
double de.dlr.ivf.tapas.person.TPS_Car.fixCosts = 0.0 private
fix costs, eg. insurance, tax, parking-zone in Euro
Definition at line 76 of file TPS_Car.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Car.cloneCar().
FUEL_TYPE_ARRAY
FuelType [] de.dlr.ivf.tapas.person.TPS_Car.FUEL_TYPE_ARRAY = new FuelType[]{FuelType.BENZINE, FuelType.DIESEL, FuelType.GAS, FuelType.EMOBILE, FuelType.PLUGIN, FuelType.FUELCELL, FuelType.LPG} static
Definition at line 32 of file TPS_Car.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.loadHouseholds(), and de.dlr.ivf.scripts.FleetAnalyzer.readTrips().
hasPaidToll
boolean de.dlr.ivf.tapas.person.TPS_Car.hasPaidToll = false
Definition at line 34 of file TPS_Car.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Worker.assignCarToPlan(), and de.dlr.ivf.tapas.mode.TPS_ModeSet.selectMode0().
id
int de.dlr.ivf.tapas.person.TPS_Car.id private
this car id
Definition at line 51 of file TPS_Car.java.
index
int de.dlr.ivf.tapas.person.TPS_Car.index = -1
Definition at line 35 of file TPS_Car.java.
kbaNo
int de.dlr.ivf.tapas.person.TPS_Car.kbaNo private
this car size
Definition at line 47 of file TPS_Car.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Car.cloneCar().
parameterClass
TPS_ParameterClass de.dlr.ivf.tapas.person.TPS_Car.parameterClass private
Definition at line 77 of file TPS_Car.java.
rangeLeft
double de.dlr.ivf.tapas.person.TPS_Car.rangeLeft = 0.0 private
this range left
Definition at line 68 of file TPS_Car.java.
restricted
boolean de.dlr.ivf.tapas.person.TPS_Car.restricted = false private
Flag if this car is restricted in access of certain areas
Definition at line 60 of file TPS_Car.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Car.cloneCar().
type
FuelType de.dlr.ivf.tapas.person.TPS_Car.type private
this fuel type
Definition at line 43 of file TPS_Car.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Car.cloneCar().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/person/TPS_Car.java