TAPAS: de.dlr.ivf.tapas.tools.TPS_VisumOD2DB Class Reference
de.dlr.ivf.tapas.tools.TPS_VisumOD2DB Class Reference
Public Member Functions
void generateIntraCellInfos (double weight)
double[][] getMatrix ()
void readCSVFile (String fileName, Double factor) throws IOException
void readIDMap (String table) throws SQLException
Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_BasicConnectionClass ()
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass)
TPS_BasicConnectionClass (String loginFile)
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass, String loginFile)
boolean checkMatrixName (String matrixName)
TPS_ParameterClass getParameters ()
String readParameter (String simKey, String paramKey)
void storeInDB (String matrixName, double[][] matrix, int decimalPlaces)
Static Public Member Functions
static void main (String[] args) throws IOException, SQLException
Static Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
static double[][] array1Dto2D (Integer[] matrixVal)
static double[][] array1Dto2D (int[] matrixVal)
static File getRuntimeFile (boolean forceNewFile)
static File getRuntimeFile (String propertyFile, boolean forceNewFile)
static File getRuntimeFile ()
static File getRuntimeFile (String propertyFile)
static int[][] intArray1Dto2D (int[] matrixVal)
static String matrixToSQLArray (double[][] array, int decimalPlaces)
static StringWriter matrixToStringWriterSQL (double[][] array, int decimalPlaces)
Private Member Functions
int checkMultiMin (double val, double[] array)
void insertMinAt (double val, double[] array, int position)
Private Attributes
final HashMap< Integer, Integer > idToIndex = new HashMap<>()
final HashMap< Integer, Integer > indexToId = new HashMap<>()
double[][] matrix = null
Additional Inherited Members
Protected Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
void finalize ()
Protected Attributes inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_DB_Connector dbCon = null
TPS_ParameterClass parameterClass
Detailed Description
Class to convert a visum file containing speeds, traveltimes, distances and beelines to TAPAS-Input.
This Class provides all necessary functions to read the visum-file, process the intra-infos and write the output back to the db
Author
hein_mh
Definition at line 30 of file TPS_VisumOD2DB.java.
Member Function Documentation
checkMultiMin()
int de.dlr.ivf.tapas.tools.TPS_VisumOD2DB.checkMultiMin (double val, double[] array) private
Internal Method to check for multiple mins.
Parameters
val the value to test
array an array, which holds the array.length minimum values
Returns
the position, where the value was inserted or -1 if "val" is bigger than every value in "array"
Definition at line 78 of file TPS_VisumOD2DB.java.
References de.dlr.ivf.tapas.tools.TPS_VisumOD2DB.insertMinAt().
Referenced by de.dlr.ivf.tapas.tools.TPS_VisumOD2DB.generateIntraCellInfos().
generateIntraCellInfos()
void de.dlr.ivf.tapas.tools.TPS_VisumOD2DB.generateIntraCellInfos (double weight)
Definition at line 88 of file TPS_VisumOD2DB.java.
References de.dlr.ivf.tapas.tools.TPS_VisumOD2DB.checkMultiMin().
Referenced by de.dlr.ivf.tapas.tools.TPS_VisumOD2DB.main().
getMatrix()
double [][] de.dlr.ivf.tapas.tools.TPS_VisumOD2DB.getMatrix ()
Returns
the matrix
Definition at line 124 of file TPS_VisumOD2DB.java.
References de.dlr.ivf.tapas.tools.TPS_VisumOD2DB.matrix.
Referenced by de.dlr.ivf.tapas.tools.TPS_VisumOD2DB.main().
insertMinAt()
void de.dlr.ivf.tapas.tools.TPS_VisumOD2DB.insertMinAt (double val, double[] array, int position) private
Internal method to insert a value at a specific position in the array. All succedion values are shifted one to the left. In C I would use the shift command ;)
Parameters
val the new value
array the array to insert into
position the position
Definition at line 135 of file TPS_VisumOD2DB.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_VisumOD2DB.checkMultiMin().
main()
static void de.dlr.ivf.tapas.tools.TPS_VisumOD2DB.main (String[] args) throws IOException, SQLException static
Parameters
args
Definition at line 49 of file TPS_VisumOD2DB.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_MATRICES, de.dlr.ivf.tapas.tools.TPS_VisumOD2DB.generateIntraCellInfos(), de.dlr.ivf.tapas.tools.TPS_VisumOD2DB.getMatrix(), de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.getParameters(), de.dlr.ivf.tapas.tools.TPS_VisumOD2DB.readCSVFile(), de.dlr.ivf.tapas.tools.TPS_VisumOD2DB.readIDMap(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.setString(), and de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.storeInDB().
readCSVFile()
void de.dlr.ivf.tapas.tools.TPS_VisumOD2DB.readCSVFile (String fileName, Double factor) throws IOException
Definition at line 144 of file TPS_VisumOD2DB.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.tools.TPS_VisumOD2DB.idToIndex, de.dlr.ivf.tapas.tools.TPS_VisumOD2DB.indexToId, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.INFO, de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), and de.dlr.ivf.tapas.log.TPS_Logger.log().
Referenced by de.dlr.ivf.tapas.tools.TPS_VisumOD2DB.main().
readIDMap()
void de.dlr.ivf.tapas.tools.TPS_VisumOD2DB.readIDMap (String table) throws SQLException
Definition at line 237 of file TPS_VisumOD2DB.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), de.dlr.ivf.tapas.tools.TPS_VisumOD2DB.idToIndex, de.dlr.ivf.tapas.tools.TPS_VisumOD2DB.indexToId, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.INFO, de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), and de.dlr.ivf.tapas.log.TPS_Logger.log().
Referenced by de.dlr.ivf.tapas.tools.TPS_VisumOD2DB.main().
Member Data Documentation
idToIndex
final HashMap<Integer, Integer> de.dlr.ivf.tapas.tools.TPS_VisumOD2DB.idToIndex = new HashMap<>() private
hashmap for id conversion
Definition at line 35 of file TPS_VisumOD2DB.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_VisumOD2DB.readCSVFile(), and de.dlr.ivf.tapas.tools.TPS_VisumOD2DB.readIDMap().
indexToId
final HashMap<Integer, Integer> de.dlr.ivf.tapas.tools.TPS_VisumOD2DB.indexToId = new HashMap<>() private
hashmap for id conversion
Definition at line 39 of file TPS_VisumOD2DB.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_VisumOD2DB.readCSVFile(), and de.dlr.ivf.tapas.tools.TPS_VisumOD2DB.readIDMap().
matrix
double [][] de.dlr.ivf.tapas.tools.TPS_VisumOD2DB.matrix = null private
array for the values
Definition at line 44 of file TPS_VisumOD2DB.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_VisumOD2DB.getMatrix().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/TPS_VisumOD2DB.java