TAPAS: de.dlr.ivf.tapas.mode.TPS_ModeDistribution Class Reference
de.dlr.ivf.tapas.mode.TPS_ModeDistribution Class Reference
Static Public Member Functions
static TPS_DiscreteDistribution< TPS_Mode > calculateDistribution (TPS_DiscreteDistribution< TPS_Mode > srcDis, TPS_Plan plan, double distanceNet, TPS_ModeChoiceContext mcc)
static void clearDistributions ()
static TPS_DiscreteDistribution< TPS_Mode > getDistribution (TPS_DiscreteDistribution< TPS_Mode > srcDis)
Static Public Attributes
static Map< Thread, TPS_DiscreteDistribution< TPS_Mode > > MAP = new HashMap<>()
Detailed Description
Class for calculating the modal distributions in the case of a scenario. Based on the empirical modal splits as pivot point, the new distributions are calculated determining the differences in utility for the different modes available. Therefore, the changes in costs (financial and time-based) associated with the choice of a mode in the scenario and the base scenario are calculated.
Definition at line 30 of file TPS_ModeDistribution.java.
Member Function Documentation
calculateDistribution()
static TPS_DiscreteDistribution<TPS_Mode> de.dlr.ivf.tapas.mode.TPS_ModeDistribution.calculateDistribution (TPS_DiscreteDistribution< TPS_Mode > srcDis, TPS_Plan plan, double distanceNet, TPS_ModeChoiceContext mcc) static
/** Calculates and stores the differences in modal split between the base and the scenario resulting from the changes in costs and the initial modal split values
Parameters
srcDis initial modal split distribution
plan day plan
distanceNet distance on the street net
mcc modecontext, like , bike, car ... flag if a bike is available
Returns
resulting probability distribution for the modes
Definition at line 45 of file TPS_ModeDistribution.java.
References de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.BIKE, de.dlr.ivf.tapas.mode.TPS_ModeChoiceContext.carForThisPlan, de.dlr.ivf.tapas.util.TPS_FastMath.exp(), de.dlr.ivf.tapas.mode.TPS_Mode.get(), de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.getValueByKey(), de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.getValues(), de.dlr.ivf.tapas.mode.TPS_ModeChoiceContext.isBikeAvailable, de.dlr.ivf.tapas.modechoice.TPS_UtilityFunction.minModeProbability, de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.MIT, de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.normalize(), de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.setValueByKey(), and de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.setValues().
Referenced by de.dlr.ivf.tapas.mode.TPS_ModeSet.getModeDistribution().
clearDistributions()
static void de.dlr.ivf.tapas.mode.TPS_ModeDistribution.clearDistributions () static
Definition at line 99 of file TPS_ModeDistribution.java.
getDistribution()
static TPS_DiscreteDistribution<TPS_Mode> de.dlr.ivf.tapas.mode.TPS_ModeDistribution.getDistribution (TPS_DiscreteDistribution< TPS_Mode > srcDis) static
Gets a new distribution object with zero values.
Parameters
srcDis If specified the result will have the same indices like srcDis, if null a standard distribution is returned
Returns
A new object of TPS_ArrayIndexProbabilityDistribution
Definition at line 111 of file TPS_ModeDistribution.java.
References de.dlr.ivf.tapas.mode.TPS_Mode.getConstants(), de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.getSingletons(), de.dlr.ivf.tapas.mode.TPS_Mode.MODE_TYPE_ARRAY, and de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.setValueByPosition().
Referenced by de.dlr.ivf.tapas.modechoice.TPS_UtilityMNL.getDistributionSet(), and de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.getModeLogSum().
Member Data Documentation
MAP
Map<Thread, TPS_DiscreteDistribution<TPS_Mode> > de.dlr.ivf.tapas.mode.TPS_ModeDistribution.MAP = new HashMap<>() static
Definition at line 32 of file TPS_ModeDistribution.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/mode/TPS_ModeDistribution.java