TAPAS: de.dlr.ivf.tapas.tools.TPS_CSV2SQLMatrix Class Reference
de.dlr.ivf.tapas.tools.TPS_CSV2SQLMatrix Class Reference
Public Member Functions
void readCSVFile (String fileName)
void writeSQLScript (String output, String name)
Static Public Member Functions
static void main (String[] args)
Detailed Description
Definition at line 19 of file TPS_CSV2SQLMatrix.java.
Member Function Documentation
main()
static void de.dlr.ivf.tapas.tools.TPS_CSV2SQLMatrix.main (String[] args) static
Parameters
args
Definition at line 27 of file TPS_CSV2SQLMatrix.java.
References name, de.dlr.ivf.tapas.tools.TPS_CSV2SQLMatrix.readCSVFile(), and de.dlr.ivf.tapas.tools.TPS_CSV2SQLMatrix.writeSQLScript().
readCSVFile()
void de.dlr.ivf.tapas.tools.TPS_CSV2SQLMatrix.readCSVFile (String fileName)
Definition at line 41 of file TPS_CSV2SQLMatrix.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_CSV2SQLMatrix.main().
writeSQLScript()
void de.dlr.ivf.tapas.tools.TPS_CSV2SQLMatrix.writeSQLScript (String output, String name)
Definition at line 105 of file TPS_CSV2SQLMatrix.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.matrixToSQLArray(), and name.
Referenced by de.dlr.ivf.tapas.tools.TPS_CSV2SQLMatrix.main().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/TPS_CSV2SQLMatrix.java