TAPAS: de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree Class Reference
de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree Class Reference
Public Member Functions
TPS_ExpertKnowledgeTree ()
TPS_ExpertKnowledgeTree (TPS_ExpertKnowledgeNode root)
TPS_ExpertKnowledgeNode getDistributionSet (TPS_Plan plan)
TPS_ExpertKnowledgeNode getNode (int id)
TPS_ExpertKnowledgeNode getRoot ()
void setRoot (TPS_ExpertKnowledgeNode root)
String toString ()
String toString (String prefix)
Public Member Functions inherited from de.dlr.ivf.tapas.modechoice.TPS_ModeChoiceTree
TPS_ModeChoiceTree ()
TPS_ModeChoiceTree (TPS_Node root)
void setRoot (TPS_Node root)
Static Public Member Functions
static boolean applyExpertKnowledge (TPS_ModeSet modeSet, TPS_Plan plan, double distanceNet, TPS_ModeChoiceContext mcc, boolean checkForbiddenModes, TPS_DiscreteDistribution< TPS_Mode > dist)
Protected Member Functions
TPS_ExpertKnowledgeNode find (TPS_Node node, int id)
Protected Member Functions inherited from de.dlr.ivf.tapas.modechoice.TPS_ModeChoiceTree
TPS_Node descend (TPS_Plan plan, TPS_Node node)
Additional Inherited Members
Protected Attributes inherited from de.dlr.ivf.tapas.modechoice.TPS_ModeChoiceTree
TPS_Node root = null
Detailed Description
This tree describes the different specialisations of the mode distributions. At each node there is a different mode distribution stored
Author
mark_ma
Definition at line 32 of file TPS_ExpertKnowledgeTree.java.
Constructor & Destructor Documentation
TPS_ExpertKnowledgeTree() [1/2]
de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree.TPS_ExpertKnowledgeTree ()
This constructor builds a mode choice tree without a root
Definition at line 37 of file TPS_ExpertKnowledgeTree.java.
TPS_ExpertKnowledgeTree() [2/2]
de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree.TPS_ExpertKnowledgeTree (TPS_ExpertKnowledgeNode root)
Builds the encapsulating object and sets the root
Parameters
root
Definition at line 46 of file TPS_ExpertKnowledgeTree.java.
Member Function Documentation
applyExpertKnowledge()
static boolean de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree.applyExpertKnowledge (TPS_ModeSet modeSet, TPS_Plan plan, double distanceNet, TPS_ModeChoiceContext mcc, boolean checkForbiddenModes, TPS_DiscreteDistribution< TPS_Mode > dist) static
This method looks for expert knowledge data and applies them for the given distribution set
Parameters
modeSet The used set of mode
plan THe actual plan
distanceNet the actual net distance
checkForbiddenModes flag to enable check for forbidden modes
dist The distribution to adopt
Definition at line 59 of file TPS_ExpertKnowledgeTree.java.
References de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.BIKE, de.dlr.ivf.tapas.mode.TPS_ModeChoiceContext.carForThisPlan, de.dlr.ivf.tapas.constants.TPS_ActivityConstant.DUMMY, de.dlr.ivf.tapas.log.TPS_LoggingInterface.HierarchyLogLevel.EPISODE, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_USE_TAXI, de.dlr.ivf.tapas.mode.TPS_ModeChoiceContext.fromStayLocation, de.dlr.ivf.tapas.mode.TPS_Mode.get(), de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree.getDistributionSet(), de.dlr.ivf.tapas.mode.TPS_ModeSet.getExpertKnowledgeTree(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getIntValue(), de.dlr.ivf.tapas.mode.TPS_Mode.getParameters(), de.dlr.ivf.tapas.mode.TPS_ModeSet.getParameters(), de.dlr.ivf.tapas.plan.TPS_Plan.getPerson(), de.dlr.ivf.tapas.mode.TPS_Mode.getTravelTime(), de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.getValueByKey(), de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.getValueByPosition(), de.dlr.ivf.tapas.mode.TPS_ModeChoiceContext.isBikeAvailable, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isFalse(), de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), de.dlr.ivf.tapas.mode.TPS_Mode.isType(), de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.util.parameters.ParamValue.MAX_WALK_DIST, de.dlr.ivf.tapas.modechoice.TPS_UtilityFunction.minModeProbability, de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.MIT, de.dlr.ivf.tapas.mode.TPS_Mode.MODE_TYPE_ARRAY, de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeNode.modifyDistribution(), de.dlr.ivf.tapas.mode.TPS_Mode.noConnection(), de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.normalize(), de.dlr.ivf.tapas.util.parameters.SimulationType.SCENARIO, de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.setValueByKey(), de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.setValueByPosition(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.SEVERE, de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.size(), de.dlr.ivf.tapas.mode.TPS_ModeChoiceContext.startTime, de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.TAXI, and de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.WALK.
Referenced by de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixed.getDistributionSet(), de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixedBS.getDistributionSet(), and de.dlr.ivf.tapas.modechoice.TPS_UtilityMNL.getDistributionSet().
find()
TPS_ExpertKnowledgeNode de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree.find (TPS_Node node, int id) protected
Searches recursively for the node with the specified id; starting at the node specified
Parameters
node node to start searching at
id id of the node to find
Returns
the node if found; null else
Reimplemented from de.dlr.ivf.tapas.modechoice.TPS_ModeChoiceTree.
Definition at line 120 of file TPS_ExpertKnowledgeTree.java.
References de.dlr.ivf.tapas.modechoice.TPS_Node.find().
getDistributionSet()
TPS_ExpertKnowledgeNode de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree.getDistributionSet (TPS_Plan plan)
Returns the node containing the mode choice distribution for the combination of the personal and trip based attributes
Parameters
plan day plan
Returns
a node containing the mode choice distribution
Reimplemented from de.dlr.ivf.tapas.modechoice.TPS_ModeChoiceTree.
Definition at line 130 of file TPS_ExpertKnowledgeTree.java.
Referenced by de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree.applyExpertKnowledge().
getNode()
TPS_ExpertKnowledgeNode de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree.getNode (int id)
Returns the corresponding node to the id specified
Parameters
id node id
Returns
node
Reimplemented from de.dlr.ivf.tapas.modechoice.TPS_ModeChoiceTree.
Definition at line 140 of file TPS_ExpertKnowledgeTree.java.
References de.dlr.ivf.tapas.modechoice.TPS_Node.find().
getRoot()
TPS_ExpertKnowledgeNode de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree.getRoot ()
Returns the root of the mode choice tree
Returns
root node
Reimplemented from de.dlr.ivf.tapas.modechoice.TPS_ModeChoiceTree.
Definition at line 149 of file TPS_ExpertKnowledgeTree.java.
setRoot()
void de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree.setRoot (TPS_ExpertKnowledgeNode root)
Sets the node specified as root node of the mode choice tree
Parameters
root root node to set
Definition at line 158 of file TPS_ExpertKnowledgeTree.java.
toString() [1/2]
String de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree.toString ()
Reimplemented from de.dlr.ivf.tapas.modechoice.TPS_ModeChoiceTree.
Definition at line 168 of file TPS_ExpertKnowledgeTree.java.
toString() [2/2]
String de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree.toString (String prefix)
This method should print the object naturally with the given prefix.
Parameters
prefix
Returns
prefix + toString();
Reimplemented from de.dlr.ivf.tapas.modechoice.TPS_ModeChoiceTree.
Definition at line 177 of file TPS_ExpertKnowledgeTree.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/modechoice/TPS_ExpertKnowledgeTree.java