TAPAS: de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment Class Reference
de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment Class Reference
Classes
class Location
class Person
Public Member Functions
TPS_PrimaryActivityAssignment ()
void createTable (String table)
int getRandomElement (List< Integer > list)
void insertPersonsIntoTable (String table)
List< String > pKeyList (String table)
void readLocationsTable (String table)
void readPersonsTable (String p_table, String hh_table, String key)
void selectBestLocation ()
Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_BasicConnectionClass ()
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass)
TPS_BasicConnectionClass (String loginFile)
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass, String loginFile)
boolean checkMatrixName (String matrixName)
TPS_ParameterClass getParameters ()
String readParameter (String simKey, String paramKey)
void storeInDB (String matrixName, double[][] matrix, int decimalPlaces)
Static Public Member Functions
static void main (String[] args)
Static Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
static double[][] array1Dto2D (Integer[] matrixVal)
static double[][] array1Dto2D (int[] matrixVal)
static File getRuntimeFile (boolean forceNewFile)
static File getRuntimeFile (String propertyFile, boolean forceNewFile)
static File getRuntimeFile ()
static File getRuntimeFile (String propertyFile)
static int[][] intArray1Dto2D (int[] matrixVal)
static String matrixToSQLArray (double[][] array, int decimalPlaces)
static StringWriter matrixToStringWriterSQL (double[][] array, int decimalPlaces)
Private Member Functions
void assignPrimarySchoolLocation (Person p)
void assignSecondarySchoolLocation (Person p)
void assignTertiaryEduLocation (Person p)
void assignWorkplaceLocation (Person p, TPS_DiscreteDistribution< Integer > probDistribution)
void completeWorkplaceMap ()
void matrixConversion ()
void prepareDistanceCategories ()
void prepareSecondarySchoolLocations ()
void prepareTertiaryEduLocations ()
TPS_DiscreteDistribution< Integer > probDistributionWorkplace ()
int whichClass (int a)
Additional Inherited Members
Protected Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
void finalize ()
Protected Attributes inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_DB_Connector dbCon = null
TPS_ParameterClass parameterClass
Detailed Description
This class creates a new table in the database based on the table with the individuals living in the area under investigation. The new table adds to the existing one a fixed location to individuals whose main activity is work, school, university or vocational training. People from other groups are not assigned a fixed location.
Definition at line 25 of file TPS_PrimaryActivityAssignment.java.
Constructor & Destructor Documentation
TPS_PrimaryActivityAssignment()
de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.TPS_PrimaryActivityAssignment ()
This constructor overrides the file the with login information and also initializes the distance of the bins for the length distribution for workers
Definition at line 53 of file TPS_PrimaryActivityAssignment.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.main().
Member Function Documentation
assignPrimarySchoolLocation()
void de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.assignPrimarySchoolLocation (Person p) private
This method assigns the next school from their home with available places to pupils in primary school
Parameters
p
Definition at line 80 of file TPS_PrimaryActivityAssignment.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.selectBestLocation().
assignSecondarySchoolLocation()
void de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.assignSecondarySchoolLocation (Person p) private
This method assigns a random school from a set of the next five schools to students in secondary school
Parameters
p
Definition at line 110 of file TPS_PrimaryActivityAssignment.java.
References de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.draw(), and de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.getRandomElement().
Referenced by de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.selectBestLocation().
assignTertiaryEduLocation()
void de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.assignTertiaryEduLocation (Person p) private
This method assigns a totally random location to students or trainees in tertiary education
Parameters
p
Definition at line 153 of file TPS_PrimaryActivityAssignment.java.
References de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.draw().
Referenced by de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.selectBestLocation().
assignWorkplaceLocation()
void de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.assignWorkplaceLocation (Person p, TPS_DiscreteDistribution< Integer > probDistribution) private
A work location is assigned to each worker drawing a taz_id from the discrete probability distribution and then choosing a random location from the set of locations within that TAZ. This process is repeated until a location is assigned to a worker, always taking into account the capacities. In addition, the number of people in each distance category is counted and stored as value in workplaceModelTest
Parameters
p
probDistribution
Definition at line 172 of file TPS_PrimaryActivityAssignment.java.
References de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.draw(), and de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.getRandomElement().
Referenced by de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.selectBestLocation().
completeWorkplaceMap()
void de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.completeWorkplaceMap () private
Pre-step to the assignation of a work location
Definition at line 215 of file TPS_PrimaryActivityAssignment.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.main().
createTable()
void de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.createTable (String table)
This method creates a new empty table
Parameters
table
Definition at line 236 of file TPS_PrimaryActivityAssignment.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute().
Referenced by de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.main().
getRandomElement()
int de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.getRandomElement (List< Integer > list)
This method returns a random integer from a list
Parameters
list
Returns
Definition at line 265 of file TPS_PrimaryActivityAssignment.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.assignSecondarySchoolLocation(), and de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.assignWorkplaceLocation().
insertPersonsIntoTable()
void de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.insertPersonsIntoTable (String table)
The table created in the last step has to be filled with all the individuals, like in the original table, plus a fixed location for workers, pupils, students and trainees
Parameters
table
Definition at line 280 of file TPS_PrimaryActivityAssignment.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection().
Referenced by de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.main().
main()
static void de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.main (String[] args) static
Definition at line 58 of file TPS_PrimaryActivityAssignment.java.
References de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.completeWorkplaceMap(), de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.createTable(), de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.insertPersonsIntoTable(), de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.matrixConversion(), de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.pKeyList(), de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.readLocationsTable(), de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.readPersonsTable(), de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.selectBestLocation(), and de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.TPS_PrimaryActivityAssignment().
matrixConversion()
void de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.matrixConversion () private
Definition at line 326 of file TPS_PrimaryActivityAssignment.java.
References de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.whichClass().
Referenced by de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.main().
pKeyList()
List<String> de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.pKeyList (String table)
Since we have keys in our tables to differentiate projects or data sources, we want to do the process for each key separately
Definition at line 338 of file TPS_PrimaryActivityAssignment.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery().
Referenced by de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.main().
prepareDistanceCategories()
void de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.prepareDistanceCategories () private
This method creates a TreeMap (distanceCategories) with the mean value of distance categories as keys and null as values (for now). First of all, the maximum distance between TAZs (Traffic Analysis Zones) is calculated. This is going to be the maximum value used for the categories. To test the workplace choice model another map is created (workplaceModelTest). The keys are the same as in the TreeMap and the values are (for now) set to 0.
Definition at line 360 of file TPS_PrimaryActivityAssignment.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.readLocationsTable().
prepareSecondarySchoolLocations()
void de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.prepareSecondarySchoolLocations () private
This method creates a discrete probability distribution based on the capacities of the different types of secondary schools (according to the German system)
Definition at line 386 of file TPS_PrimaryActivityAssignment.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.readLocationsTable().
prepareTertiaryEduLocations()
void de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.prepareTertiaryEduLocations () private
This method creates a discrete probability distribution based on the capacities of the different locations for tertiary education
Definition at line 394 of file TPS_PrimaryActivityAssignment.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.readLocationsTable().
probDistributionWorkplace()
TPS_DiscreteDistribution<Integer> de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.probDistributionWorkplace () private
This method creates a discrete probability distribution based on the workplace choice model
Returns
Definition at line 403 of file TPS_PrimaryActivityAssignment.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.selectBestLocation().
readLocationsTable()
void de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.readLocationsTable (String table)
This method implies different actions in relation to the locations of activities (e.g., workplaces, shops, schools). First of all, the table with the locations is read from the database. Every location is stored in a map (locations) where the key is the type of location (loc_code) and the value is a list of locations of the corresponding type. workplaceMap is a TreeMap with the taz_id as key and a map with the distance categories (mean value) as key and a list (for now) set to null as value. In addition, the capacities of the locations are stored in different maps. There is a map for all the locations together and maps for schools, for workplaces and for tertiary education. workplaceTazIds is a map with lists of locations according to the TAZ where they are located
Parameters
table this is the table with the locations of activities
Definition at line 431 of file TPS_PrimaryActivityAssignment.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.prepareDistanceCategories(), de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.prepareSecondarySchoolLocations(), and de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.prepareTertiaryEduLocations().
Referenced by de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.main().
readPersonsTable()
void de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.readPersonsTable (String p_table, String hh_table, String key)
This method reads the table with the individuals along with the table with the households (needed to get the coordinates of the household) from the database. Everyone is stored in a list of the type Person (persons)
Parameters
p_table
hh_table
key
Definition at line 530 of file TPS_PrimaryActivityAssignment.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery().
Referenced by de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.main().
selectBestLocation()
void de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.selectBestLocation ()
This method sums up all the methods used to select a proper location, considering the status (worker, student,...) of the individual
Definition at line 604 of file TPS_PrimaryActivityAssignment.java.
References de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.assignPrimarySchoolLocation(), de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.assignSecondarySchoolLocation(), de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.assignTertiaryEduLocation(), de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.assignWorkplaceLocation(), and de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.probDistributionWorkplace().
Referenced by de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.main().
whichClass()
int de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.whichClass (int a) private
This two methods convert the values in meters of the distance matrix (matrix with distances between TAZs) to categories; this means, mean values of the distance classes
Definition at line 638 of file TPS_PrimaryActivityAssignment.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.matrixConversion().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/TPS_PrimaryActivityAssignment.java