TAPAS: de.dlr.ivf.tapas.runtime.client.SimulationControl Class Reference
de.dlr.ivf.tapas.runtime.client.SimulationControl Class Reference
Classes
class ServerControlUpdateTask
class ServerOnlineTester
class SimulationDataUpdateTask
class SimulationServerDataUpdateTask
class TimeUpdateTask
Public Member Functions
SimulationControl (File tapasNetworkDirectory)
void addSimulation (String sim_key, String filename, boolean addConfigToDB) throws IOException, SQLException
void addSimulation (String sim_key, String filename) throws IOException, SQLException
void changeSimulationDataState (String sim_key)
boolean checkConnection () throws SQLException
File[] chooseRunFile (Component parent)
void close ()
boolean configChanged ()
TPS_DB_Connector getConnection ()
Timestamp getCurrentDatabaseTimestamp ()
TPS_ParameterClass getParameters ()
String getServerHash (String hostname)
void removeServer (InetAddress ip)
void removeSimulation (String sim_key, boolean withDialog)
void updateProperties ()
Static Public Member Functions
static void main (String[] args)
Static Public Attributes
static final String BUILD_NUMBER = ".*"
Protected Member Functions
String getBuilddate ()
String getBuildnumber ()
ClientControlProperties getProperties ()
String getVersion ()
void shutServerDown (String hostname)
void startServer (String hostname)
Private Member Functions
int loadParameters (File name, HashMap< String, String > parameters) throws IOException
Private Attributes
final Stack< File > parameterFiles = new Stack<>()
TPS_DB_Connector dbConnection
Timestamp currentDatabaseTimestamp
final SimulationMonitor gui
final Map< String, SimulationServerData > simulationServerDataMap
final ExecutorService executorpool = Executors.newCachedThreadPool()
final ServerOnlineTester serverOnlineTester = new ServerOnlineTester()
final Map< String, SimulationData > simulationDataMap
boolean skipUpdate
final File tapasNetworkDirectory
final Timer timer
ClientControlProperties props
String version
String builddate
String buildnumber
Static Private Attributes
static final TPS_ArgumentType<?>[] PARAMETERS
static SimulationControl control
Detailed Description
The SimulationControl represents the controller for the simulation client. The controller has three active tasks and provides methods to change the simulation entries in the database.
The active tasks are:
SimulationDataUpdateTask
This task updates the simulation values in the memory of the client from the database
SimulationServerDataUpdateTask
This task updates the simulation server data values in the memory of the client from the database
TimeUpdateTask
This task retrieves the current timestamp of the database
Furthermore the client provides methods to add or remove simulations from the database and to change the state of a simulation, e.g. it is possible the stop or restart a simulation.
Author
mark_ma
Definition at line 67 of file SimulationControl.java.
Constructor & Destructor Documentation
SimulationControl()
de.dlr.ivf.tapas.runtime.client.SimulationControl.SimulationControl (File tapasNetworkDirectory)
The constructor consists of five parts:
initialising member variables
loading runtime file
The constructor loads the 'runtime.csv' file from the given parameter 'tapasNetworkDirectory'. The file can look like this:
name,value,comment
FILE_PARENT_PROPERTIES,db_connect_1_achilles.csv,
FILE_PARENT_PROPERTIES,db_user_0_admin.csv,
FILE_PARENT_PROPERTIES,db_schema_table_0.csv,
connecting to database
With the information of the runtime file there is a connection to the database built.
setting up the GUI
initialising the timer and all tasks
Parameters
tapasNetworkDirectory absolute path to the tapas network directory
Definition at line 154 of file SimulationControl.java.
References de.dlr.ivf.tapas.runtime.client.SimulationControl.builddate, de.dlr.ivf.tapas.runtime.client.SimulationControl.buildnumber, de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.getRuntimeFile(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.loadRuntimeParameters(), de.dlr.ivf.tapas.runtime.util.ClientControlProperties.ClientControlPropKey.LOGIN_CONFIG, de.dlr.ivf.tapas.runtime.client.SimulationControl.tapasNetworkDirectory, and de.dlr.ivf.tapas.runtime.client.SimulationControl.version.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationControl.main().
Member Function Documentation
addSimulation() [1/2]
void de.dlr.ivf.tapas.runtime.client.SimulationControl.addSimulation (String sim_key, String filename) throws IOException, SQLException
This method loads all values from the run properties file by the parameter 'filename' and stores a simulation in the database. The simulation is added to the internal map and the GUI via the SimulationDataUpdateTask.
Parameters
sim_key key for the simulation in the database
filename filename of the run properties file
Exceptions
IOException This exception is thrown if there occurred an error while reading the run properties file
SQLException This exception is thrown if there occurs an error while inserting the simulation into the database
Definition at line 322 of file SimulationControl.java.
References de.dlr.ivf.tapas.runtime.client.SimulationControl.addSimulation().
addSimulation() [2/2]
void de.dlr.ivf.tapas.runtime.client.SimulationControl.addSimulation (String sim_key, String filename, boolean addConfigToDB) throws IOException, SQLException
This method loads all values from the run properties file by the parameter 'filename' and stores a simulation in the database. The simulation is added to the internal map and the GUI via the SimulationDataUpdateTask.
Parameters
sim_key key for the simulation in the database
filename filename of the run properties file
addConfigToDB true if the config stored in filename should be stored in the database. false if it is stored already.
Exceptions
IOException This exception is thrown if there occurred an error while reading the run properties file
SQLException This exception is thrown if there occurs an error while inserting the simulation into the database
Definition at line 275 of file SimulationControl.java.
References de.dlr.ivf.tapas.runtime.client.SimulationControl.dbConnection, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection(), de.dlr.ivf.tapas.runtime.client.SimulationControl.getParameters(), de.dlr.ivf.tapas.runtime.client.SimulationControl.loadParameters(), de.dlr.ivf.tapas.runtime.client.SimulationControl.parameterFiles, and de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.writeToDB().
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationControl.addSimulation(), and de.dlr.ivf.tapas.runtime.client.SimulationMonitor.insertAction().
changeSimulationDataState()
void de.dlr.ivf.tapas.runtime.client.SimulationControl.changeSimulationDataState (String sim_key)
This method changes the state of the simulation corresponding to the parameter sim_key.
The changes are:
INSERTED -> STARTED
STOPPED -> STARTED
STARTED -> STOPPED
FINISHED -> Remove simulation completely from the database
The changes are done via a SQl statement and the skipUpdate flag is set to true after the statement was committed.
Parameters
sim_key key for the simulation in the database
Definition at line 342 of file SimulationControl.java.
References de.dlr.ivf.tapas.runtime.client.SimulationControl.dbConnection, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute(), de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState.getState(), de.dlr.ivf.tapas.runtime.client.SimulationControl.removeSimulation(), de.dlr.ivf.tapas.runtime.client.SimulationControl.simulationDataMap, and de.dlr.ivf.tapas.runtime.client.SimulationControl.skipUpdate.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitor.pauseSelected(), de.dlr.ivf.tapas.runtime.client.SimulationMonitor.SimTableButtonEditor.SimTableButtonEditor(), and de.dlr.ivf.tapas.runtime.client.SimulationMonitor.startSelected().
checkConnection()
boolean de.dlr.ivf.tapas.runtime.client.SimulationControl.checkConnection () throws SQLException
Definition at line 375 of file SimulationControl.java.
References de.dlr.ivf.tapas.runtime.client.SimulationControl.dbConnection, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection().
chooseRunFile()
File [] de.dlr.ivf.tapas.runtime.client.SimulationControl.chooseRunFile (Component parent)
This method opens a file dialog in which you can choose a run properties file, which have a name like 'run_*.csv' where * can be any string.
Parameters
parent parent component for the dialog which is opened in this method
Returns
the chosen run properties file
Definition at line 386 of file SimulationControl.java.
References de.dlr.ivf.tapas.runtime.util.ClientControlProperties.get(), de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.getString(), de.dlr.ivf.tapas.runtime.util.ClientControlProperties.ClientControlPropKey.LAST_SIMULATION, de.dlr.ivf.tapas.runtime.util.ClientControlProperties.ClientControlPropKey.LAST_SIMULATION_DIR, de.dlr.ivf.tapas.runtime.client.SimulationControl.props, and de.dlr.ivf.tapas.runtime.util.ClientControlProperties.set().
close()
void de.dlr.ivf.tapas.runtime.client.SimulationControl.close ()
This method stops the timer with all scheduled tasks and closes the connection to the database.
Definition at line 429 of file SimulationControl.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.closeConnection(), de.dlr.ivf.tapas.runtime.client.SimulationControl.dbConnection, and de.dlr.ivf.tapas.runtime.client.SimulationControl.timer.
configChanged()
boolean de.dlr.ivf.tapas.runtime.client.SimulationControl.configChanged ()
check if changes are made
Definition at line 449 of file SimulationControl.java.
References de.dlr.ivf.tapas.runtime.client.SimulationControl.props.
getBuilddate()
String de.dlr.ivf.tapas.runtime.client.SimulationControl.getBuilddate () protected
Definition at line 453 of file SimulationControl.java.
References de.dlr.ivf.tapas.runtime.client.SimulationControl.builddate.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitor.SimulationMonitor().
getBuildnumber()
String de.dlr.ivf.tapas.runtime.client.SimulationControl.getBuildnumber () protected
Definition at line 457 of file SimulationControl.java.
References de.dlr.ivf.tapas.runtime.client.SimulationControl.buildnumber.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitor.SimulationMonitor().
getConnection()
TPS_DB_Connector de.dlr.ivf.tapas.runtime.client.SimulationControl.getConnection ()
Definition at line 461 of file SimulationControl.java.
References de.dlr.ivf.tapas.runtime.client.SimulationControl.dbConnection.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitor.exportSelected(), de.dlr.ivf.tapas.runtime.client.SimulationMonitor.getConnection(), and de.dlr.ivf.tapas.runtime.client.SimulationMonitor.updateSimulationDescription().
getCurrentDatabaseTimestamp()
Timestamp de.dlr.ivf.tapas.runtime.client.SimulationControl.getCurrentDatabaseTimestamp ()
Returns
current database timestamp
Definition at line 468 of file SimulationControl.java.
References de.dlr.ivf.tapas.runtime.client.SimulationControl.currentDatabaseTimestamp.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitor.updateSimulationData().
getParameters()
TPS_ParameterClass de.dlr.ivf.tapas.runtime.client.SimulationControl.getParameters ()
Returns
parameter class reference
Definition at line 475 of file SimulationControl.java.
References de.dlr.ivf.tapas.runtime.client.SimulationControl.dbConnection, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getParameters().
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationControl.addSimulation(), de.dlr.ivf.tapas.runtime.client.SimulationControl.removeServer(), de.dlr.ivf.tapas.runtime.client.SimulationControl.removeSimulation(), and de.dlr.ivf.tapas.runtime.client.SimulationMonitor.startAnalyzer().
getProperties()
ClientControlProperties de.dlr.ivf.tapas.runtime.client.SimulationControl.getProperties () protected
Definition at line 479 of file SimulationControl.java.
References de.dlr.ivf.tapas.runtime.client.SimulationControl.props.
getServerHash()
String de.dlr.ivf.tapas.runtime.client.SimulationControl.getServerHash (String hostname)
Retrieves the ServerHash-String from the internal servers map
Parameters
hostname the host from which the Hash is retrieved
Returns
- empty String if server is offline or no Hash is defined
the hash string if server is online and the Hash has been set inside the database
Definition at line 490 of file SimulationControl.java.
References de.dlr.ivf.tapas.runtime.server.SimulationServerData.getHashString(), de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.getString(), de.dlr.ivf.tapas.runtime.server.SimulationServerData.isOnline(), and de.dlr.ivf.tapas.runtime.client.SimulationControl.simulationServerDataMap.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitor.HashRenderer.getTableCellRendererComponent().
getVersion()
String de.dlr.ivf.tapas.runtime.client.SimulationControl.getVersion () protected
Definition at line 501 of file SimulationControl.java.
References de.dlr.ivf.tapas.runtime.client.SimulationControl.version.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitor.SimulationMonitor().
loadParameters()
int de.dlr.ivf.tapas.runtime.client.SimulationControl.loadParameters (File name, HashMap< String, String > parameters) throws IOException private
This method loads all given parameter entries and stores them in a hashmap: (key,value). This hashmap is used to put the parameters into the database.
Definition at line 510 of file SimulationControl.java.
References name, and de.dlr.ivf.tapas.runtime.client.SimulationControl.parameterFiles.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationControl.addSimulation().
main()
static void de.dlr.ivf.tapas.runtime.client.SimulationControl.main (String[] args) static
This main method checks all parameters and then setup a client with a graphical user interface for TAPAS simulations
Parameters
args args[0]: tapas network directory path
Definition at line 229 of file SimulationControl.java.
References de.dlr.ivf.tapas.util.TPS_Argument.checkArguments(), de.dlr.ivf.tapas.runtime.client.SimulationControl.control, de.dlr.ivf.tapas.runtime.client.SimulationControl.PARAMETERS, de.dlr.ivf.tapas.runtime.util.ClientControlProperties.set(), de.dlr.ivf.tapas.runtime.client.SimulationControl.SimulationControl(), de.dlr.ivf.tapas.runtime.util.ClientControlProperties.ClientControlPropKey.TAPAS_DIR_LINUX, and de.dlr.ivf.tapas.runtime.util.ClientControlProperties.ClientControlPropKey.TAPAS_DIR_WIN.
removeServer()
void de.dlr.ivf.tapas.runtime.client.SimulationControl.removeServer (InetAddress ip)
Remove a TAPAS SimulationServer from DB
Parameters
ip
Definition at line 548 of file SimulationControl.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_SERVERS, de.dlr.ivf.tapas.runtime.client.SimulationControl.dbConnection, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute(), de.dlr.ivf.tapas.runtime.client.SimulationControl.getParameters(), and de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString().
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitor.removeServerData().
removeSimulation()
void de.dlr.ivf.tapas.runtime.client.SimulationControl.removeSimulation (String sim_key, boolean withDialog)
This method completely removes a simulation from the database. The changes take place in the internal map and the GUI when the SimulationDataUpdateTask works the next time.
Parameters
sim_key key for the simulation in the database
withDialog flag if a "are you sure?" dialog should be presented
Definition at line 562 of file SimulationControl.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_PROCESSES, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_SIMULATIONS, de.dlr.ivf.tapas.runtime.client.SimulationControl.dbConnection, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute(), and de.dlr.ivf.tapas.runtime.client.SimulationControl.getParameters().
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationControl.changeSimulationDataState(), and de.dlr.ivf.tapas.runtime.client.SimulationMonitor.deleteSelected().
shutServerDown()
void de.dlr.ivf.tapas.runtime.client.SimulationControl.shutServerDown (String hostname) protected
This method initiates a remote shutdown of a SimulationServer. This task runs asynchronously and is being handled as a CompletableFuture chain by an ExecutorService. Exceptions occurring inside the chain will be handled at the end
Parameters
hostname the host name of the remote computer where a SimulationServer needs to be shut down.
Definition at line 588 of file SimulationControl.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_PROCESSES, de.dlr.ivf.tapas.runtime.client.SimulationControl.dbConnection, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeUpdate(), de.dlr.ivf.tapas.runtime.client.SimulationControl.executorpool, de.dlr.ivf.tapas.runtime.client.SimulationControl.gui, de.dlr.ivf.tapas.runtime.server.SimulationServerData.setServerState(), de.dlr.ivf.tapas.runtime.client.SimulationControl.simulationServerDataMap, de.dlr.ivf.tapas.runtime.util.ServerControlState.STOP, and de.dlr.ivf.tapas.runtime.client.SimulationMonitor.updateServerControl().
startServer()
void de.dlr.ivf.tapas.runtime.client.SimulationControl.startServer (String hostname) protected
Launches remotely a SimulationServer from the SimlationDaemon. This task runs asynchronously and is being handled as a CompletableFuture chain by an ExecutorService. Checked exceptions will be re-thrown as unchecked ones so that the "exceptionally" block will be executed
Parameters
hostname the host name of the remote computer where a SimulationServer needs to be started up.
Exceptions
RemoteException
Definition at line 609 of file SimulationControl.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_SERVERS, de.dlr.ivf.tapas.runtime.client.SimulationControl.dbConnection, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeUpdate(), and de.dlr.ivf.tapas.runtime.client.SimulationControl.executorpool.
updateProperties()
void de.dlr.ivf.tapas.runtime.client.SimulationControl.updateProperties ()
writes all properties to the property file
Definition at line 623 of file SimulationControl.java.
References de.dlr.ivf.tapas.runtime.client.SimulationControl.props.
Member Data Documentation
BUILD_NUMBER
final String de.dlr.ivf.tapas.runtime.client.SimulationControl.BUILD_NUMBER = ".*" static
Definition at line 69 of file SimulationControl.java.
builddate
String de.dlr.ivf.tapas.runtime.client.SimulationControl.builddate private
Definition at line 127 of file SimulationControl.java.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationControl.getBuilddate(), and de.dlr.ivf.tapas.runtime.client.SimulationControl.SimulationControl().
buildnumber
String de.dlr.ivf.tapas.runtime.client.SimulationControl.buildnumber private
Definition at line 128 of file SimulationControl.java.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationControl.getBuildnumber(), and de.dlr.ivf.tapas.runtime.client.SimulationControl.SimulationControl().
control
SimulationControl de.dlr.ivf.tapas.runtime.client.SimulationControl.control static private
Definition at line 77 of file SimulationControl.java.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationControl.main().
currentDatabaseTimestamp
Timestamp de.dlr.ivf.tapas.runtime.client.SimulationControl.currentDatabaseTimestamp private
Current timestamp of database
Definition at line 90 of file SimulationControl.java.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationControl.getCurrentDatabaseTimestamp(), and de.dlr.ivf.tapas.runtime.client.SimulationControl.TimeUpdateTask.run().
dbConnection
TPS_DB_Connector de.dlr.ivf.tapas.runtime.client.SimulationControl.dbConnection private
Connection to the database
Definition at line 86 of file SimulationControl.java.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationControl.addSimulation(), de.dlr.ivf.tapas.runtime.client.SimulationControl.changeSimulationDataState(), de.dlr.ivf.tapas.runtime.client.SimulationControl.checkConnection(), de.dlr.ivf.tapas.runtime.client.SimulationControl.close(), de.dlr.ivf.tapas.runtime.client.SimulationControl.getConnection(), de.dlr.ivf.tapas.runtime.client.SimulationControl.getParameters(), de.dlr.ivf.tapas.runtime.client.SimulationControl.removeServer(), de.dlr.ivf.tapas.runtime.client.SimulationControl.removeSimulation(), de.dlr.ivf.tapas.runtime.client.SimulationControl.ServerOnlineTester.SimulationServerOnlineTestThread.resetDatabaseEntryOfSimulationServer(), de.dlr.ivf.tapas.runtime.client.SimulationControl.SimulationServerDataUpdateTask.run(), de.dlr.ivf.tapas.runtime.client.SimulationControl.SimulationDataUpdateTask.run(), de.dlr.ivf.tapas.runtime.client.SimulationControl.TimeUpdateTask.run(), de.dlr.ivf.tapas.runtime.client.SimulationControl.shutServerDown(), de.dlr.ivf.tapas.runtime.client.SimulationControl.SimulationDataUpdateTask.SimulationDataUpdateTask(), de.dlr.ivf.tapas.runtime.client.SimulationControl.SimulationServerDataUpdateTask.SimulationServerDataUpdateTask(), and de.dlr.ivf.tapas.runtime.client.SimulationControl.startServer().
executorpool
final ExecutorService de.dlr.ivf.tapas.runtime.client.SimulationControl.executorpool = Executors.newCachedThreadPool() private
Definition at line 99 of file SimulationControl.java.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationControl.shutServerDown(), and de.dlr.ivf.tapas.runtime.client.SimulationControl.startServer().
gui
final SimulationMonitor de.dlr.ivf.tapas.runtime.client.SimulationControl.gui private
the client graphical user interface
Definition at line 94 of file SimulationControl.java.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationControl.ServerControlUpdateTask.run(), de.dlr.ivf.tapas.runtime.client.SimulationControl.SimulationServerDataUpdateTask.run(), de.dlr.ivf.tapas.runtime.client.SimulationControl.SimulationDataUpdateTask.run(), and de.dlr.ivf.tapas.runtime.client.SimulationControl.shutServerDown().
parameterFiles
final Stack<File> de.dlr.ivf.tapas.runtime.client.SimulationControl.parameterFiles = new Stack<>() private
Stack to store the parents of the parameter files. Needed to descent in the correct order.
Definition at line 82 of file SimulationControl.java.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationControl.addSimulation(), and de.dlr.ivf.tapas.runtime.client.SimulationControl.loadParameters().
PARAMETERS
final TPS_ArgumentType<?> [] de.dlr.ivf.tapas.runtime.client.SimulationControl.PARAMETERS static private
Initial value:
= {new TPS_ArgumentType<>("tapas network directory path",
            File.class)}
Parameter array with all parameters for this main method.
PARAMETERS[0] = tapas network directory path
Definition at line 74 of file SimulationControl.java.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationControl.main().
props
ClientControlProperties de.dlr.ivf.tapas.runtime.client.SimulationControl.props private
The Client control properties
Definition at line 125 of file SimulationControl.java.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationControl.chooseRunFile(), de.dlr.ivf.tapas.runtime.client.SimulationControl.configChanged(), de.dlr.ivf.tapas.runtime.client.SimulationControl.getProperties(), and de.dlr.ivf.tapas.runtime.client.SimulationControl.updateProperties().
serverOnlineTester
final ServerOnlineTester de.dlr.ivf.tapas.runtime.client.SimulationControl.serverOnlineTester = new ServerOnlineTester() private
This instance can test if a SimulationServer is online
Definition at line 104 of file SimulationControl.java.
simulationDataMap
final Map<String, SimulationData> de.dlr.ivf.tapas.runtime.client.SimulationControl.simulationDataMap private
Map with all available simulations from the database
Definition at line 108 of file SimulationControl.java.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationControl.changeSimulationDataState(), and de.dlr.ivf.tapas.runtime.client.SimulationControl.SimulationDataUpdateTask.run().
simulationServerDataMap
final Map<String, SimulationServerData> de.dlr.ivf.tapas.runtime.client.SimulationControl.simulationServerDataMap private
All available servers
Definition at line 98 of file SimulationControl.java.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationControl.getServerHash(), de.dlr.ivf.tapas.runtime.client.SimulationControl.ServerControlUpdateTask.run(), de.dlr.ivf.tapas.runtime.client.SimulationControl.SimulationServerDataUpdateTask.run(), and de.dlr.ivf.tapas.runtime.client.SimulationControl.shutServerDown().
skipUpdate
boolean de.dlr.ivf.tapas.runtime.client.SimulationControl.skipUpdate private
This flag indicates if one update step of the SimulationData in SimulationDataUpdateTask has to be skipped
Definition at line 113 of file SimulationControl.java.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationControl.changeSimulationDataState(), and de.dlr.ivf.tapas.runtime.client.SimulationControl.SimulationDataUpdateTask.run().
tapasNetworkDirectory
final File de.dlr.ivf.tapas.runtime.client.SimulationControl.tapasNetworkDirectory private
Complete local path to the TAPAS directory
Definition at line 117 of file SimulationControl.java.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationControl.SimulationControl().
timer
final Timer de.dlr.ivf.tapas.runtime.client.SimulationControl.timer private
Timer for all internal tasks
Definition at line 121 of file SimulationControl.java.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationControl.close().
version
String de.dlr.ivf.tapas.runtime.client.SimulationControl.version private
Definition at line 126 of file SimulationControl.java.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationControl.getVersion(), and de.dlr.ivf.tapas.runtime.client.SimulationControl.SimulationControl().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/runtime/client/SimulationControl.java