TAPAS: de.dlr.ivf.tapas.analyzer.tum.results.DatabaseSummaryExport Class Reference
de.dlr.ivf.tapas.analyzer.tum.results.DatabaseSummaryExport Class Reference
Public Member Functions
DatabaseSummaryExport (RegionAnalyzer regionAnalyzer) throws IOException, ClassNotFoundException
boolean writeSummary ()
Private Member Functions
void fillBatch (PreparedStatement ps)
Private Attributes
final TPS_DB_Connector dbCon
final RegionAnalyzer regionAnalyzer
boolean update = false
Detailed Description
Writes the results of a RegionAnalyzer into the database table calibration_results.
More specifically, it writes a full split of Mode x PersonGroup x TripIntention x DistanceCategory
Author
boec_pa
Definition at line 31 of file DatabaseSummaryExport.java.
Constructor & Destructor Documentation
DatabaseSummaryExport()
de.dlr.ivf.tapas.analyzer.tum.results.DatabaseSummaryExport.DatabaseSummaryExport (RegionAnalyzer regionAnalyzer) throws IOException, ClassNotFoundException
Parameters
regionAnalyzer
Exceptions
IOException if the loginInfo file is not found.
ClassNotFoundException if class TPS_DB_Connector is not found.
Definition at line 45 of file DatabaseSummaryExport.java.
References de.dlr.ivf.tapas.analyzer.tum.results.DatabaseSummaryExport.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.getRuntimeFile(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getSource(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.loadRuntimeParameters(), de.dlr.ivf.tapas.analyzer.tum.results.DatabaseSummaryExport.regionAnalyzer, and de.dlr.ivf.tapas.analyzer.tum.results.DatabaseSummaryExport.update.
Member Function Documentation
fillBatch()
void de.dlr.ivf.tapas.analyzer.tum.results.DatabaseSummaryExport.fillBatch (PreparedStatement ps) private
Definition at line 73 of file DatabaseSummaryExport.java.
References de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategory.CAT_1, de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getCntPersons(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getCntTrips(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getDist(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getDur(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getSource(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.isRegionDifferentiated(), de.dlr.ivf.tapas.analyzer.tum.constants.CategoryCombination.listAllCombinations(), and de.dlr.ivf.tapas.analyzer.tum.results.DatabaseSummaryExport.regionAnalyzer.
Referenced by de.dlr.ivf.tapas.analyzer.tum.results.DatabaseSummaryExport.writeSummary().
writeSummary()
boolean de.dlr.ivf.tapas.analyzer.tum.results.DatabaseSummaryExport.writeSummary ()
Inserts or updates the summary in the database.
Returns
false if the database access failed or the region was differentiated.
Definition at line 122 of file DatabaseSummaryExport.java.
References de.dlr.ivf.tapas.analyzer.tum.results.DatabaseSummaryExport.dbCon, de.dlr.ivf.tapas.analyzer.tum.results.DatabaseSummaryExport.fillBatch(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection(), and de.dlr.ivf.tapas.analyzer.tum.results.DatabaseSummaryExport.update.
Referenced by de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.doInBackground(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.finish().
Member Data Documentation
dbCon
final TPS_DB_Connector de.dlr.ivf.tapas.analyzer.tum.results.DatabaseSummaryExport.dbCon private
Definition at line 36 of file DatabaseSummaryExport.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.results.DatabaseSummaryExport.DatabaseSummaryExport(), and de.dlr.ivf.tapas.analyzer.tum.results.DatabaseSummaryExport.writeSummary().
regionAnalyzer
final RegionAnalyzer de.dlr.ivf.tapas.analyzer.tum.results.DatabaseSummaryExport.regionAnalyzer private
Definition at line 37 of file DatabaseSummaryExport.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.results.DatabaseSummaryExport.DatabaseSummaryExport(), and de.dlr.ivf.tapas.analyzer.tum.results.DatabaseSummaryExport.fillBatch().
update
boolean de.dlr.ivf.tapas.analyzer.tum.results.DatabaseSummaryExport.update = false private
Definition at line 38 of file DatabaseSummaryExport.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.results.DatabaseSummaryExport.DatabaseSummaryExport(), and de.dlr.ivf.tapas.analyzer.tum.results.DatabaseSummaryExport.writeSummary().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/tum/results/DatabaseSummaryExport.java