TAPAS: de.dlr.ivf.tapas.runtime.server.SimulationServerData Class Reference
de.dlr.ivf.tapas.runtime.server.SimulationServerData Class Reference
Classes
enum HashStatus
enum ServerInfo
Public Member Functions
SimulationServerData (ResultSet rs) throws SQLException, UnknownHostException
SimulationServerData (InetAddress ip, String name)
int getCores ()
double getCpu ()
String getFormattedTimestamp ()
HashStatus getHashStatus ()
void setHashStatus (HashStatus status)
String getHashString ()
InetAddress getIp ()
String getName ()
Map< ServerInfo, String > getServerProcessInfo ()
void setServerProcessInfo (ResultSet serverinfo) throws SQLException
ServerControlState getServerState ()
void setServerState (ServerControlState state)
Timestamp getTimestamp ()
boolean isOnline ()
boolean isRemotelyControllable ()
boolean setName (String name, Connection connection, String db_table_servers)
String toString ()
void update (ResultSet rs) throws SQLException
Private Attributes
int cores
double cpu
final InetAddress ip
String name
boolean online
boolean shuttingdown
Timestamp timestamp
boolean remote_control = false
HashStatus hashstatus
volatile ServerControlState serverstate
String hashstring
final Map< ServerInfo, String > serverprocessdefaultinfo
Map< ServerInfo, String > serverprocessinfo
Static Private Attributes
static final SimpleDateFormat SDF = new SimpleDateFormat("dd.MM.yyyy kk:mm:ss")
Detailed Description
Storage class for all server data. These are the same as in the database.
Author
mark_ma
Definition at line 28 of file SimulationServerData.java.
Constructor & Destructor Documentation
SimulationServerData() [1/2]
de.dlr.ivf.tapas.runtime.server.SimulationServerData.SimulationServerData (ResultSet rs) throws SQLException, UnknownHostException
This constructor sets all member values.
Parameters
rs ResultSet of a database select statement
Exceptions
SQLException This exception is thrown if anything with the ResultSet is wrong, e.g. closed or too few values
UnknownHostException This exception is thrown if the host can't be found
Definition at line 87 of file SimulationServerData.java.
References de.dlr.ivf.tapas.runtime.server.SimulationServerData.ip, de.dlr.ivf.tapas.runtime.server.SimulationServerData.HashStatus.UNKNOWN, and de.dlr.ivf.tapas.runtime.server.SimulationServerData.update().
SimulationServerData() [2/2]
de.dlr.ivf.tapas.runtime.server.SimulationServerData.SimulationServerData (InetAddress ip, String name)
Definition at line 92 of file SimulationServerData.java.
References de.dlr.ivf.tapas.runtime.server.SimulationServerData.ip, and de.dlr.ivf.tapas.runtime.server.SimulationServerData.name.
Member Function Documentation
getCores()
int de.dlr.ivf.tapas.runtime.server.SimulationServerData.getCores ()
Returns
number of processors
Definition at line 100 of file SimulationServerData.java.
References de.dlr.ivf.tapas.runtime.server.SimulationServerData.cores.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitor.addServerData(), and de.dlr.ivf.tapas.runtime.client.SimulationMonitor.updateServerData().
getCpu()
double de.dlr.ivf.tapas.runtime.server.SimulationServerData.getCpu ()
Returns
cpu usage
Definition at line 107 of file SimulationServerData.java.
References de.dlr.ivf.tapas.runtime.server.SimulationServerData.cpu.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitor.addServerData(), and de.dlr.ivf.tapas.runtime.client.SimulationMonitor.updateServerData().
getFormattedTimestamp()
String de.dlr.ivf.tapas.runtime.server.SimulationServerData.getFormattedTimestamp ()
Returns
formatted timestamp of the last server update
Definition at line 114 of file SimulationServerData.java.
References de.dlr.ivf.tapas.runtime.server.SimulationServerData.SDF, and de.dlr.ivf.tapas.runtime.server.SimulationServerData.timestamp.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitor.addServerData(), and de.dlr.ivf.tapas.runtime.client.SimulationMonitor.updateServerData().
getHashStatus()
HashStatus de.dlr.ivf.tapas.runtime.server.SimulationServerData.getHashStatus ()
Definition at line 119 of file SimulationServerData.java.
References de.dlr.ivf.tapas.runtime.server.SimulationServerData.hashstatus.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitor.addServerData(), and de.dlr.ivf.tapas.runtime.client.SimulationMonitor.updateServerData().
getHashString()
String de.dlr.ivf.tapas.runtime.server.SimulationServerData.getHashString ()
Definition at line 128 of file SimulationServerData.java.
References de.dlr.ivf.tapas.runtime.server.SimulationServerData.hashstring.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationControl.getServerHash().
getIp()
InetAddress de.dlr.ivf.tapas.runtime.server.SimulationServerData.getIp ()
Returns
ip address
Definition at line 136 of file SimulationServerData.java.
References de.dlr.ivf.tapas.runtime.server.SimulationServerData.ip.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitor.addServerData(), de.dlr.ivf.tapas.runtime.client.SimulationMonitor.containsServerData(), and de.dlr.ivf.tapas.runtime.client.SimulationMonitor.updateServerData().
getName()
String de.dlr.ivf.tapas.runtime.server.SimulationServerData.getName ()
Returns
server name
Definition at line 143 of file SimulationServerData.java.
References de.dlr.ivf.tapas.runtime.server.SimulationServerData.name.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitor.addServerData(), and de.dlr.ivf.tapas.runtime.client.SimulationMonitor.updateServerData().
getServerProcessInfo()
Map<ServerInfo, String> de.dlr.ivf.tapas.runtime.server.SimulationServerData.getServerProcessInfo ()
Definition at line 150 of file SimulationServerData.java.
References de.dlr.ivf.tapas.runtime.server.SimulationServerData.serverprocessdefaultinfo, and de.dlr.ivf.tapas.runtime.server.SimulationServerData.serverprocessinfo.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitor.updateServerControl().
getServerState()
ServerControlState de.dlr.ivf.tapas.runtime.server.SimulationServerData.getServerState ()
Definition at line 190 of file SimulationServerData.java.
References de.dlr.ivf.tapas.runtime.server.SimulationServerData.serverstate.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitor.addServerData(), and de.dlr.ivf.tapas.runtime.client.SimulationMonitor.updateServerData().
getTimestamp()
Timestamp de.dlr.ivf.tapas.runtime.server.SimulationServerData.getTimestamp ()
Returns
timestamp of the last server update
Definition at line 203 of file SimulationServerData.java.
References de.dlr.ivf.tapas.runtime.server.SimulationServerData.timestamp.
isOnline()
boolean de.dlr.ivf.tapas.runtime.server.SimulationServerData.isOnline ()
Returns
online flag
Definition at line 210 of file SimulationServerData.java.
References de.dlr.ivf.tapas.runtime.server.SimulationServerData.online.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitor.addServerData(), de.dlr.ivf.tapas.runtime.client.SimulationControl.getServerHash(), de.dlr.ivf.tapas.runtime.client.SimulationMonitor.updateServerControl(), and de.dlr.ivf.tapas.runtime.client.SimulationMonitor.updateServerData().
isRemotelyControllable()
boolean de.dlr.ivf.tapas.runtime.server.SimulationServerData.isRemotelyControllable ()
Definition at line 214 of file SimulationServerData.java.
References de.dlr.ivf.tapas.runtime.server.SimulationServerData.remote_control.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitor.updateServerControl().
setHashStatus()
void de.dlr.ivf.tapas.runtime.server.SimulationServerData.setHashStatus (HashStatus status)
Definition at line 123 of file SimulationServerData.java.
setName()
boolean de.dlr.ivf.tapas.runtime.server.SimulationServerData.setName (String name, Connection connection, String db_table_servers)
tries to update the name of the server data.
Parameters
name
connection
db_table_servers
Returns
true if the update was successful.
Definition at line 226 of file SimulationServerData.java.
References de.dlr.ivf.tapas.runtime.server.SimulationServerData.ip, and de.dlr.ivf.tapas.runtime.server.SimulationServerData.name.
setServerProcessInfo()
void de.dlr.ivf.tapas.runtime.server.SimulationServerData.setServerProcessInfo (ResultSet serverinfo) throws SQLException
Definition at line 156 of file SimulationServerData.java.
References de.dlr.ivf.tapas.runtime.server.SimulationServerData.HashStatus.DEBUG, de.dlr.ivf.tapas.runtime.server.SimulationServerData.HashStatus.DOMINANT, de.dlr.ivf.tapas.runtime.server.SimulationServerData.hashstatus, de.dlr.ivf.tapas.runtime.server.SimulationServerData.ServerInfo.IDENTIFIER, de.dlr.ivf.tapas.runtime.server.SimulationServerData.HashStatus.INVALID, de.dlr.ivf.tapas.runtime.server.SimulationServerData.HashStatus.NON_DOMINANT, de.dlr.ivf.tapas.runtime.server.SimulationServerData.ServerInfo.PID, de.dlr.ivf.tapas.runtime.server.SimulationServerData.ServerInfo.RUNSINCE, de.dlr.ivf.tapas.runtime.server.SimulationServerData.HashStatus.UNKNOWN, and de.dlr.ivf.tapas.runtime.server.SimulationServerData.ServerInfo.WORKON.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationControl.SimulationServerDataUpdateTask.run().
setServerState()
void de.dlr.ivf.tapas.runtime.server.SimulationServerData.setServerState (ServerControlState state)
Definition at line 196 of file SimulationServerData.java.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationControl.SimulationServerDataUpdateTask.run(), and de.dlr.ivf.tapas.runtime.client.SimulationControl.shutServerDown().
toString()
String de.dlr.ivf.tapas.runtime.server.SimulationServerData.toString ()
Definition at line 248 of file SimulationServerData.java.
References de.dlr.ivf.tapas.runtime.server.SimulationServerData.ip, de.dlr.ivf.tapas.runtime.server.SimulationServerData.name, and de.dlr.ivf.tapas.runtime.server.SimulationServerData.online.
update()
void de.dlr.ivf.tapas.runtime.server.SimulationServerData.update (ResultSet rs) throws SQLException
Updates all member values.
Parameters
rs ResultSet of a database select statement
Exceptions
SQLException This exception is thrown if anything with the ResultSet is wrong, e.g. closed or too few values
Definition at line 259 of file SimulationServerData.java.
References de.dlr.ivf.tapas.runtime.util.ServerControlState.BOOT, de.dlr.ivf.tapas.runtime.server.SimulationServerData.cores, de.dlr.ivf.tapas.runtime.server.SimulationServerData.cpu, de.dlr.ivf.tapas.runtime.server.SimulationServerData.name, de.dlr.ivf.tapas.runtime.server.SimulationServerData.online, de.dlr.ivf.tapas.runtime.server.SimulationServerData.remote_control, de.dlr.ivf.tapas.runtime.server.SimulationServerData.serverprocessinfo, de.dlr.ivf.tapas.runtime.server.SimulationServerData.ServerInfo.SHUTDOWN, de.dlr.ivf.tapas.runtime.server.SimulationServerData.timestamp, and de.dlr.ivf.tapas.runtime.server.SimulationServerData.HashStatus.UNKNOWN.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationControl.SimulationServerDataUpdateTask.run(), and de.dlr.ivf.tapas.runtime.server.SimulationServerData.SimulationServerData().
Member Data Documentation
cores
int de.dlr.ivf.tapas.runtime.server.SimulationServerData.cores private
number of processors of the server
Definition at line 38 of file SimulationServerData.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationServerData.getCores(), and de.dlr.ivf.tapas.runtime.server.SimulationServerData.update().
cpu
double de.dlr.ivf.tapas.runtime.server.SimulationServerData.cpu private
CPU usage
Definition at line 42 of file SimulationServerData.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationServerData.getCpu(), and de.dlr.ivf.tapas.runtime.server.SimulationServerData.update().
hashstatus
HashStatus de.dlr.ivf.tapas.runtime.server.SimulationServerData.hashstatus private
Definition at line 64 of file SimulationServerData.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationServerData.getHashStatus(), and de.dlr.ivf.tapas.runtime.server.SimulationServerData.setServerProcessInfo().
hashstring
String de.dlr.ivf.tapas.runtime.server.SimulationServerData.hashstring private
Definition at line 66 of file SimulationServerData.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationServerData.getHashString().
ip
final InetAddress de.dlr.ivf.tapas.runtime.server.SimulationServerData.ip private
IP address
Definition at line 46 of file SimulationServerData.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationServerData.getIp(), de.dlr.ivf.tapas.runtime.server.SimulationServerData.setName(), de.dlr.ivf.tapas.runtime.server.SimulationServerData.SimulationServerData(), and de.dlr.ivf.tapas.runtime.server.SimulationServerData.toString().
name
String de.dlr.ivf.tapas.runtime.server.SimulationServerData.name private
name of the server
Definition at line 50 of file SimulationServerData.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationServerData.getName(), de.dlr.ivf.tapas.runtime.server.SimulationServerData.setName(), de.dlr.ivf.tapas.runtime.server.SimulationServerData.SimulationServerData(), de.dlr.ivf.tapas.runtime.server.SimulationServerData.toString(), and de.dlr.ivf.tapas.runtime.server.SimulationServerData.update().
online
boolean de.dlr.ivf.tapas.runtime.server.SimulationServerData.online private
is the server online (reachable)
Definition at line 54 of file SimulationServerData.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationServerData.isOnline(), de.dlr.ivf.tapas.runtime.server.SimulationServerData.toString(), and de.dlr.ivf.tapas.runtime.server.SimulationServerData.update().
remote_control
boolean de.dlr.ivf.tapas.runtime.server.SimulationServerData.remote_control = false private
Definition at line 63 of file SimulationServerData.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationServerData.isRemotelyControllable(), and de.dlr.ivf.tapas.runtime.server.SimulationServerData.update().
SDF
final SimpleDateFormat de.dlr.ivf.tapas.runtime.server.SimulationServerData.SDF = new SimpleDateFormat("dd.MM.yyyy kk:mm:ss") static private
This format is used to format the date into dd.MM.yyyy kk:mm:ss.
Definition at line 34 of file SimulationServerData.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationServerData.getFormattedTimestamp().
serverprocessdefaultinfo
final Map<ServerInfo, String> de.dlr.ivf.tapas.runtime.server.SimulationServerData.serverprocessdefaultinfo private
Initial value:
= new HashMap<ServerInfo, String>() {
        {
            put(ServerInfo.IDENTIFIER, "NA");
            put(ServerInfo.RUNSINCE, "NA");
            put(ServerInfo.PID, "NA");
            put(ServerInfo.WORKON, "NA");
            put(ServerInfo.SHUTDOWN, "NA");
        }
    }
Definition at line 68 of file SimulationServerData.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationServerData.getServerProcessInfo().
serverprocessinfo
Map<ServerInfo, String> de.dlr.ivf.tapas.runtime.server.SimulationServerData.serverprocessinfo private
Definition at line 77 of file SimulationServerData.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationServerData.getServerProcessInfo(), and de.dlr.ivf.tapas.runtime.server.SimulationServerData.update().
serverstate
volatile ServerControlState de.dlr.ivf.tapas.runtime.server.SimulationServerData.serverstate private
Definition at line 65 of file SimulationServerData.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationServerData.getServerState().
shuttingdown
boolean de.dlr.ivf.tapas.runtime.server.SimulationServerData.shuttingdown private
flag that indicates that this server is currently shutting down
Definition at line 58 of file SimulationServerData.java.
timestamp
Timestamp de.dlr.ivf.tapas.runtime.server.SimulationServerData.timestamp private
Timestamp of the last update of the server
Definition at line 62 of file SimulationServerData.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationServerData.getFormattedTimestamp(), de.dlr.ivf.tapas.runtime.server.SimulationServerData.getTimestamp(), and de.dlr.ivf.tapas.runtime.server.SimulationServerData.update().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/runtime/server/SimulationServerData.java