TAPAS: de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed Class Reference
de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed Class Reference
Public Member Functions
CruisingSpeed ()
CruisingSpeedCalcData getCalcData ()
CruisingSpeedValData getValData ()
void start (String[] args)
Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_BasicConnectionClass ()
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass)
TPS_BasicConnectionClass (String loginFile)
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass, String loginFile)
boolean checkMatrixName (String matrixName)
TPS_ParameterClass getParameters ()
String readParameter (String simKey, String paramKey)
void storeInDB (String matrixName, double[][] matrix, int decimalPlaces)
Static Public Member Functions
static String generateRecordName (String modus, int type)
static Properties getProperties ()
static void setProperties (Properties properties)
static void main (String[] args)
Static Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
static double[][] array1Dto2D (Integer[] matrixVal)
static double[][] array1Dto2D (int[] matrixVal)
static File getRuntimeFile (boolean forceNewFile)
static File getRuntimeFile (String propertyFile, boolean forceNewFile)
static File getRuntimeFile ()
static File getRuntimeFile (String propertyFile)
static int[][] intArray1Dto2D (int[] matrixVal)
static String matrixToSQLArray (double[][] array, int decimalPlaces)
static StringWriter matrixToStringWriterSQL (double[][] array, int decimalPlaces)
Static Public Attributes
static final String propertyFileName = "crusingspeed.properties"
static final int DISTANCE = 0
static final int TRAVELTIME = 1
Private Member Functions
void readProperties () throws IllegalArgumentException
void writeMatrix (StringWriter sqlVektor, String modus, int type)
void writeNewPropertyFile ()
void writePropertyFile (CommandLine lvCmd, boolean temp)
void writePropertyFile (CommandLine lvCmd)
Private Attributes
CruisingSpeedCalcData calcData = null
CruisingSpeedValData valData = null
final boolean[] val
boolean validation = false
final boolean indirectWayFactor = true
Static Private Attributes
static Properties properties = null
Additional Inherited Members
Protected Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
void finalize ()
Protected Attributes inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_DB_Connector dbCon = null
TPS_ParameterClass parameterClass
Detailed Description
Definition at line 20 of file CruisingSpeed.java.
Constructor & Destructor Documentation
CruisingSpeed()
de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.CruisingSpeed ()
Definition at line 44 of file CruisingSpeed.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.val.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.main().
Member Function Documentation
generateRecordName()
static String de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.generateRecordName (String modus, int type) static
Definition at line 48 of file CruisingSpeed.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.DISTANCE, de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.properties, and type.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.start(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.writeMatrix().
getCalcData()
CruisingSpeedCalcData de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.getCalcData ()
Definition at line 248 of file CruisingSpeed.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.calcData.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.readProperties(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.start().
getProperties()
static Properties de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.getProperties () static
Definition at line 52 of file CruisingSpeed.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.properties.
getValData()
CruisingSpeedValData de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.getValData ()
Definition at line 252 of file CruisingSpeed.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.valData.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.readProperties().
main()
static void de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.main (String[] args) static
Definition at line 74 of file CruisingSpeed.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.CruisingSpeed(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.start().
readProperties()
void de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.readProperties () throws IllegalArgumentException private
Definition at line 256 of file CruisingSpeed.java.
References de.dlr.ivf.tapas.tools.matrixMap.Modus.BIKE, de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.getCalcData(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.getCalculation(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.getReferenceDist(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.getReferenceTT(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.getTravelTimeParameter(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.getValData(), de.dlr.ivf.tapas.tools.matrixMap.Modus.MIV, de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.properties, de.dlr.ivf.tapas.tools.matrixMap.Modus.PT, de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.setIndirectWayFactor(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.setMatricesTable(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.setMatricesTable(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.setPath(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.setRecordName(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.setTazTable(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.setTazTable(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.setTerrain(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.setTerrain(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.setTop3(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.setzValues(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.val, de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.validation, and de.dlr.ivf.tapas.tools.matrixMap.Modus.WALK.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.start().
setProperties()
static void de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.setProperties (Properties properties) static
Definition at line 56 of file CruisingSpeed.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.properties.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedGUI.bStartActionPerformed().
start()
void de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.start (String[] args)
Definition at line 377 of file CruisingSpeed.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.calcData, de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.calcDistance(), de.dlr.ivf.tapas.util.TPS_Geometrics.calcTop3(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.DISTANCE, de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.getCalcData(), de.dlr.ivf.tapas.tools.matrixMap.Modus.getName(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.getTravelTime(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.isTop3(), de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.matrixToStringWriterSQL(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.properties, de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.readProperties(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.start(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.TRAVELTIME, de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.valData, de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.validation, de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.writeMatrix(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.writeNewPropertyFile(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.writePropertyFile().
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedGUI.bStartActionPerformed(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.main().
writeMatrix()
void de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.writeMatrix (StringWriter sqlVektor, String modus, int type) private
Definition at line 449 of file CruisingSpeed.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.generateRecordName(), name, de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.properties, and type.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.start().
writeNewPropertyFile()
void de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.writeNewPropertyFile () private
Definition at line 466 of file CruisingSpeed.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.properties, and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.propertyFileName.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.start().
writePropertyFile() [1/2]
void de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.writePropertyFile (CommandLine lvCmd) private
Definition at line 663 of file CruisingSpeed.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.writePropertyFile().
writePropertyFile() [2/2]
void de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.writePropertyFile (CommandLine lvCmd, boolean temp) private
Definition at line 547 of file CruisingSpeed.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.properties, and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.propertyFileName.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.start(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.writePropertyFile().
Member Data Documentation
calcData
CruisingSpeedCalcData de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.calcData = null private
Definition at line 36 of file CruisingSpeed.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.getCalcData(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.start().
DISTANCE
final int de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.DISTANCE = 0 static
Definition at line 23 of file CruisingSpeed.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.generateRecordName(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.start(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.start().
indirectWayFactor
final boolean de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.indirectWayFactor = true private
Definition at line 41 of file CruisingSpeed.java.
properties
Properties de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.properties = null static private
Definition at line 26 of file CruisingSpeed.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.generateRecordName(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.getProperties(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.readProperties(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.setProperties(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.start(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.writeMatrix(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.writeNewPropertyFile(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.writePropertyFile().
propertyFileName
final String de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.propertyFileName = "crusingspeed.properties" static
Definition at line 21 of file CruisingSpeed.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedGUI.CruisingSpeedGUI(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.readProperties(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedGUI.savePropertieFile(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedGUI.start(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.writeNewPropertyFile(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.writePropertyFile().
TRAVELTIME
final int de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.TRAVELTIME = 1 static
Definition at line 24 of file CruisingSpeed.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.start(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.start().
val
final boolean [] de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.val private
Definition at line 38 of file CruisingSpeed.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.CruisingSpeed(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.readProperties().
valData
CruisingSpeedValData de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.valData = null private
Definition at line 37 of file CruisingSpeed.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.getValData(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.start().
validation
boolean de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.validation = false private
Definition at line 39 of file CruisingSpeed.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.readProperties(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.start().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/matrixMap/CruisingSpeed.java