TAPAS: de.dlr.ivf.scripts.SrVCalculator Class Reference
de.dlr.ivf.scripts.SrVCalculator Class Reference
Classes
class PTTAZInfo
class TAZ
Public Member Functions
SrVCalculator (TPS_DB_Connector connection)
void aggregateAndWriteCSVFile (String fileName)
void initAreasWithDefaultTimes ()
boolean loadTAZToArea (String tazTable)
boolean loadTAZToMapping (String mappingCode, String tazTable, String mappingTable)
void readMatrixFromDB (String tableentry, double[][] matrix, String matrixTable)
void readMatrixFromDB (String tableentry, double[][] matrix, double factor, String matrixTable)
void readPTMatricesFromDB (String baseName)
void readPTMatrix (String filename)
boolean readTrips (String key)
void topxPTTAZInfo (int num, double weight)
Static Public Member Functions
static void main (String[] args) throws IOException, ClassNotFoundException
Private Member Functions
void closeConnection ()
Private Attributes
final HashMap< Integer, Integer > tazToStatisticArea = new HashMap<>()
final HashMap< Integer, List< Integer > > statisticAreaToTAZ = new HashMap<>()
final List< Integer > statisticArea = new ArrayList<>()
double[][][] ttArray = null
double[][][] distArray = null
int[][][] odArray = null
TAZ[] tazWeight = null
PTTAZInfo[][] ptTaz = null
Detailed Description
This class was originally designed to calculate some traveltimes of working trips for statistical areas for the SrV-Dataset. Now it converts a lot of matrices including MiV and PT to an appropriate format for mode estimation.
Author
hein_mh
Definition at line 29 of file SrVCalculator.java.
Constructor & Destructor Documentation
SrVCalculator()
de.dlr.ivf.scripts.SrVCalculator.SrVCalculator (TPS_DB_Connector connection)
the one and only standard-constructor
Parameters
connection reference to the db-connection-manager
Definition at line 85 of file SrVCalculator.java.
Referenced by de.dlr.ivf.scripts.SrVCalculator.main().
Member Function Documentation
aggregateAndWriteCSVFile()
void de.dlr.ivf.scripts.SrVCalculator.aggregateAndWriteCSVFile (String fileName)
Method to aggregate the taz to statistical areas and write them to a given csv-file
Parameters
fileName the file to write
Definition at line 148 of file SrVCalculator.java.
References de.dlr.ivf.scripts.SrVCalculator.TAZ.getDistance(), and de.dlr.ivf.scripts.SrVCalculator.odArray.
Referenced by de.dlr.ivf.scripts.SrVCalculator.main().
closeConnection()
void de.dlr.ivf.scripts.SrVCalculator.closeConnection () private
private function to close the connection. Do not call this, when using this in the main tapas programm.
Definition at line 255 of file SrVCalculator.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.closeConnection().
Referenced by de.dlr.ivf.scripts.SrVCalculator.main().
initAreasWithDefaultTimes()
void de.dlr.ivf.scripts.SrVCalculator.initAreasWithDefaultTimes ()
Method to calculate some default times. These are usually aggregated times for walk/bike
Definition at line 266 of file SrVCalculator.java.
References de.dlr.ivf.tapas.util.TPS_Geometrics.calcTop3(), de.dlr.ivf.scripts.SrVCalculator.odArray, and de.dlr.ivf.scripts.SrVCalculator.TAZ.weight.
Referenced by de.dlr.ivf.scripts.SrVCalculator.main().
loadTAZToArea()
boolean de.dlr.ivf.scripts.SrVCalculator.loadTAZToArea (String tazTable)
Method to load all TAZ for the region and create a mapping for the statistical areas
Returns
true for success
Definition at line 309 of file SrVCalculator.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), de.dlr.ivf.scripts.SrVCalculator.TAZ.lat, de.dlr.ivf.scripts.SrVCalculator.TAZ.lon, de.dlr.ivf.scripts.SrVCalculator.TAZ.stat_area, and de.dlr.ivf.scripts.SrVCalculator.TAZ.taz_id.
loadTAZToMapping()
boolean de.dlr.ivf.scripts.SrVCalculator.loadTAZToMapping (String mappingCode, String tazTable, String mappingTable)
Method to load all TAZ for the region and create a mapping for the statistical areas
Returns
true for success
Definition at line 384 of file SrVCalculator.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.extractIntArray(), de.dlr.ivf.scripts.SrVCalculator.TAZ.lat, de.dlr.ivf.scripts.SrVCalculator.TAZ.lon, de.dlr.ivf.scripts.SrVCalculator.TAZ.stat_area, and de.dlr.ivf.scripts.SrVCalculator.TAZ.taz_id.
Referenced by de.dlr.ivf.scripts.SrVCalculator.main().
main()
static void de.dlr.ivf.scripts.SrVCalculator.main (String[] args) throws IOException, ClassNotFoundException static
Parameters
args
Exceptions
IOException
ClassNotFoundException
Definition at line 94 of file SrVCalculator.java.
References de.dlr.ivf.scripts.SrVCalculator.aggregateAndWriteCSVFile(), de.dlr.ivf.scripts.SrVCalculator.closeConnection(), de.dlr.ivf.scripts.SrVCalculator.initAreasWithDefaultTimes(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.loadRuntimeParameters(), de.dlr.ivf.scripts.SrVCalculator.loadTAZToMapping(), de.dlr.ivf.scripts.SrVCalculator.odArray, de.dlr.ivf.scripts.SrVCalculator.ptTaz, de.dlr.ivf.scripts.SrVCalculator.readMatrixFromDB(), de.dlr.ivf.scripts.SrVCalculator.readPTMatricesFromDB(), de.dlr.ivf.scripts.SrVCalculator.SrVCalculator(), and de.dlr.ivf.scripts.SrVCalculator.tazToStatisticArea.
readMatrixFromDB() [1/2]
void de.dlr.ivf.scripts.SrVCalculator.readMatrixFromDB (String tableentry, double matrix[][], double factor, String matrixTable)
Reads a single matrix from the db, multiplys the values with the given factor and stores them into the given array
Parameters
tableentry The name of the matrix
matrix a reference to an array to put the values
factor the modification factor
Definition at line 470 of file SrVCalculator.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.extractIntArray().
readMatrixFromDB() [2/2]
void de.dlr.ivf.scripts.SrVCalculator.readMatrixFromDB (String tableentry, double matrix[][], String matrixTable)
Reads a single matrix from the db and stores them into the given array
Parameters
tableentry The name of the matrix
matrix a reference to an array to put the values
Definition at line 459 of file SrVCalculator.java.
Referenced by de.dlr.ivf.scripts.SrVCalculator.main(), and de.dlr.ivf.scripts.SrVCalculator.readPTMatricesFromDB().
readPTMatricesFromDB()
void de.dlr.ivf.scripts.SrVCalculator.readPTMatricesFromDB (String baseName)
Method to read a set of PT-Marices from the db. The matices must follow a certain name scheme: basename+EGT Egress time basename+ACT access time basename+TT travel time in vecicle basename+DIS pt-distance basename+IWT initial waiting time basename+TWT trip waiting time basename+NTR number of interchanges (times 100!)
Parameters
baseName the basename for the name scheme
Definition at line 511 of file SrVCalculator.java.
References de.dlr.ivf.scripts.SrVCalculator.readMatrixFromDB().
Referenced by de.dlr.ivf.scripts.SrVCalculator.main().
readPTMatrix()
void de.dlr.ivf.scripts.SrVCalculator.readPTMatrix (String filename)
Method to read the old pt-files from Dresden
Parameters
filename the file to read
Definition at line 548 of file SrVCalculator.java.
readTrips()
boolean de.dlr.ivf.scripts.SrVCalculator.readTrips (String key)
Old (obsolete?!?) methodd to read parameters for working trips
Parameters
key the simulation key
Returns
true for success
Definition at line 637 of file SrVCalculator.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), and de.dlr.ivf.scripts.SrVCalculator.TAZ.weight.
topxPTTAZInfo()
void de.dlr.ivf.scripts.SrVCalculator.topxPTTAZInfo (int num, double weight)
TOPx-calculation for the diagonal values for the following matrices: travel time interchanges maxWaiting (inital Waiting) sumWaiting access egress distance
Parameters
num the number of neighbours to considder
weight the weight for the average - should be between 0.2 and 0.8
Definition at line 708 of file SrVCalculator.java.
References de.dlr.ivf.scripts.SrVCalculator.ptTaz.
Member Data Documentation
distArray
double [][][] de.dlr.ivf.scripts.SrVCalculator.distArray = null private
sum of dist-array for each mode
Definition at line 71 of file SrVCalculator.java.
odArray
int [][][] de.dlr.ivf.scripts.SrVCalculator.odArray = null private
num of O/D-array for each mode
Definition at line 76 of file SrVCalculator.java.
Referenced by de.dlr.ivf.scripts.SrVCalculator.aggregateAndWriteCSVFile(), de.dlr.ivf.scripts.SrVCalculator.initAreasWithDefaultTimes(), and de.dlr.ivf.scripts.SrVCalculator.main().
ptTaz
PTTAZInfo [][] de.dlr.ivf.scripts.SrVCalculator.ptTaz = null private
Definition at line 78 of file SrVCalculator.java.
Referenced by de.dlr.ivf.scripts.SrVCalculator.main(), and de.dlr.ivf.scripts.SrVCalculator.topxPTTAZInfo().
statisticArea
final List<Integer> de.dlr.ivf.scripts.SrVCalculator.statisticArea = new ArrayList<>() private
Definition at line 61 of file SrVCalculator.java.
statisticAreaToTAZ
final HashMap<Integer, List<Integer> > de.dlr.ivf.scripts.SrVCalculator.statisticAreaToTAZ = new HashMap<>() private
Definition at line 60 of file SrVCalculator.java.
tazToStatisticArea
final HashMap<Integer, Integer> de.dlr.ivf.scripts.SrVCalculator.tazToStatisticArea = new HashMap<>() private
hashmap for id conversion
Definition at line 59 of file SrVCalculator.java.
Referenced by de.dlr.ivf.scripts.SrVCalculator.main().
tazWeight
TAZ [] de.dlr.ivf.scripts.SrVCalculator.tazWeight = null private
Definition at line 77 of file SrVCalculator.java.
ttArray
double [][][] de.dlr.ivf.scripts.SrVCalculator.ttArray = null private
sum of tt-array for each mode
Definition at line 66 of file SrVCalculator.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/scripts/SrVCalculator.java