TAPAS: de.dlr.ivf.tapas.tools.TPS_SubnetMatrixIntegrator Class Reference
de.dlr.ivf.tapas.tools.TPS_SubnetMatrixIntegrator Class Reference
Public Member Functions
void loadMatricesAndMappings (String subnet, String outernet, String subnetTAZ)
Matrix updateValues ()
void saveMatrix (String name, Matrix m)
boolean extractSubmatrix (String submatrixName)
Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_BasicConnectionClass ()
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass)
TPS_BasicConnectionClass (String loginFile)
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass, String loginFile)
boolean checkMatrixName (String matrixName)
TPS_ParameterClass getParameters ()
String readParameter (String simKey, String paramKey)
void storeInDB (String matrixName, double[][] matrix, int decimalPlaces)
Static Public Member Functions
static void main (String[] args)
Static Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
static double[][] array1Dto2D (Integer[] matrixVal)
static double[][] array1Dto2D (int[] matrixVal)
static File getRuntimeFile (boolean forceNewFile)
static File getRuntimeFile (String propertyFile, boolean forceNewFile)
static File getRuntimeFile ()
static File getRuntimeFile (String propertyFile)
static int[][] intArray1Dto2D (int[] matrixVal)
static String matrixToSQLArray (double[][] array, int decimalPlaces)
static StringWriter matrixToStringWriterSQL (double[][] array, int decimalPlaces)
Additional Inherited Members
Protected Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
void finalize ()
Protected Attributes inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_DB_Connector dbCon = null
TPS_ParameterClass parameterClass
Detailed Description
This method tries to integrate the changes of a subnet matrix to the whole matrix. Steps to do so: Load subnet matrix and original outer matrix Load mapping of the different cells Define cordon points: For a given connection between A in the subnet and B in the outer net do: Search over all points in the sub net the cell C with a minimum value of: (AC+CB)-AB Update the Value AB with the difference of AC between the original net and the subnet Update all connections in the original matrix, which lie within the subnet Save the new matrix
Definition at line 27 of file TPS_SubnetMatrixIntegrator.java.
Member Function Documentation
extractSubmatrix()
boolean de.dlr.ivf.tapas.tools.TPS_SubnetMatrixIntegrator.extractSubmatrix (String submatrixName)
Method to extract a submatrix from the "outernet" for a given list if tazes.
Parameters
submatrixName the name to store the Matrix in the db
Definition at line 182 of file TPS_SubnetMatrixIntegrator.java.
References de.dlr.ivf.tapas.tools.TPS_SubnetMatrixIntegrator.saveMatrix(), and de.dlr.ivf.tapas.util.Matrix.setValue().
loadMatricesAndMappings()
void de.dlr.ivf.tapas.tools.TPS_SubnetMatrixIntegrator.loadMatricesAndMappings (String subnet, String outernet, String subnetTAZ)
Reads the input. Needs DB_TABLE_MATRICES and DB_TABLE_TAZ to be set. The column taz_num_id from DB_TABLE_TAZ and subnetTAZ is used for mapping between the subnet and the outer net. First it reads all outer TAZ Ids from DB_TABLE_TAZ and fill the mappingOuternet-map. Second read the same for the subnet Third create a mapping between sdubnet and outernet Fourth load the matrices
Parameters
subnet The subnetmatrix to load
outernet the outer matrix to load
subnetTAZ the information about the subnetTAZ
Definition at line 53 of file TPS_SubnetMatrixIntegrator.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_TAZ, de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.parameterClass, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.readMatrix().
Referenced by de.dlr.ivf.tapas.tools.TPS_SubnetMatrixIntegrator.main().
main()
static void de.dlr.ivf.tapas.tools.TPS_SubnetMatrixIntegrator.main (String[] args) static
The main entry point.
Parameters
args
Definition at line 206 of file TPS_SubnetMatrixIntegrator.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_MATRICES, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_TAZ, de.dlr.ivf.tapas.tools.TPS_SubnetMatrixIntegrator.loadMatricesAndMappings(), de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.parameterClass, de.dlr.ivf.tapas.tools.TPS_SubnetMatrixIntegrator.saveMatrix(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.setString(), and de.dlr.ivf.tapas.tools.TPS_SubnetMatrixIntegrator.updateValues().
saveMatrix()
void de.dlr.ivf.tapas.tools.TPS_SubnetMatrixIntegrator.saveMatrix (String name, Matrix m)
Definition at line 168 of file TPS_SubnetMatrixIntegrator.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_MATRICES, de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.matrixToSQLArray(), name, and de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.parameterClass.
Referenced by de.dlr.ivf.tapas.tools.TPS_SubnetMatrixIntegrator.extractSubmatrix(), and de.dlr.ivf.tapas.tools.TPS_SubnetMatrixIntegrator.main().
updateValues()
Matrix de.dlr.ivf.tapas.tools.TPS_SubnetMatrixIntegrator.updateValues ()
Definition at line 121 of file TPS_SubnetMatrixIntegrator.java.
References de.dlr.ivf.tapas.util.Matrix.clone(), de.dlr.ivf.tapas.util.Matrix.getValue(), and de.dlr.ivf.tapas.util.Matrix.setValue().
Referenced by de.dlr.ivf.tapas.tools.TPS_SubnetMatrixIntegrator.main().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/TPS_SubnetMatrixIntegrator.java