TAPAS: de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategoryAnalyzer Class Reference
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategoryAnalyzer Class Reference
Public Member Functions
DistanceCategoryAnalyzer (double[] distances)
DistanceCategory assignTrip (TapasTrip trip)
String getCategoryName (DistanceCategory dc)
ArrayList< DistanceCategory > getDistanceCategories ()
Private Member Functions
void buildNameMap ()
Private Attributes
final double[] distances
Detailed Description
Definition at line 1003 of file TuMEnums.java.
Constructor & Destructor Documentation
DistanceCategoryAnalyzer()
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategoryAnalyzer.DistanceCategoryAnalyzer (double[] distances)
Parameters
distances in meters. Must be in strict ascending order.
Exceptions
IllegalArgumentException if the length of distances does not coincide with the number of categories or if there is no distance different from Double.MaxValue.
Definition at line 1015 of file TuMEnums.java.
References de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategoryAnalyzer.buildNameMap(), and de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategoryAnalyzer.distances.
Member Function Documentation
assignTrip()
DistanceCategory de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategoryAnalyzer.assignTrip (TapasTrip trip)
Definition at line 1027 of file TuMEnums.java.
References de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategory.CAT_1, de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategory.CAT_8, de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategoryAnalyzer.distances, and de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTrip.getDistNet().
buildNameMap()
void de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategoryAnalyzer.buildNameMap () private
Definition at line 1041 of file TuMEnums.java.
References de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategory.CAT_1, de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategory.CAT_8, de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategoryAnalyzer.distances, and de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategory.NOT_USED.
Referenced by de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategoryAnalyzer.DistanceCategoryAnalyzer().
getCategoryName()
String de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategoryAnalyzer.getCategoryName (DistanceCategory dc)
Definition at line 1065 of file TuMEnums.java.
getDistanceCategories()
ArrayList<DistanceCategory> de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategoryAnalyzer.getDistanceCategories ()
Returns all active DistanceCategories.
Definition at line 1072 of file TuMEnums.java.
References de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategory.NOT_USED.
Member Data Documentation
distances
final double [] de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategoryAnalyzer.distances private
Definition at line 1005 of file TuMEnums.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategoryAnalyzer.assignTrip(), de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategoryAnalyzer.buildNameMap(), and de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategoryAnalyzer.DistanceCategoryAnalyzer().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/tum/constants/TuMEnums.java