TAPAS: de.dlr.ivf.tapas.iteration.TPS_BasicIterationManager Class Reference
de.dlr.ivf.tapas.iteration.TPS_BasicIterationManager Class Reference
Public Member Functions
TPS_BasicIterationManager (TPS_ParameterClass parameterClass)
ArrayList< Long > selectPlansForRecalculation (HashMap< Long, PlanDeviation > derivationMap, int actIter, int maxIter)
Public Member Functions inherited from de.dlr.ivf.tapas.iteration.TPS_IterationManagement
HashMap< Long, PlanDeviation > calculatePlanDerivation (int iteration)
MatrixMap[] getNewTravelTimeMatrix ()
int hashToHHID (long hash)
int hashToPersonID (long hash)
long hhAndPersonIDToHash (int hh_id, int p_id)
void resetPlansForRecalculation (ArrayList< Long > plans)
void setDBConnector (TPS_DB_Connector dbManager)
Private Attributes
final TPS_ParameterClass parameterClass
Detailed Description
This Class provides some basic functionality which are used by more than one iteration method.
Author
hein_mh
Definition at line 31 of file TPS_BasicIterationManager.java.
Constructor & Destructor Documentation
TPS_BasicIterationManager()
de.dlr.ivf.tapas.iteration.TPS_BasicIterationManager.TPS_BasicIterationManager (TPS_ParameterClass parameterClass)
Definition at line 35 of file TPS_BasicIterationManager.java.
Member Function Documentation
selectPlansForRecalculation()
ArrayList<Long> de.dlr.ivf.tapas.iteration.TPS_BasicIterationManager.selectPlansForRecalculation (HashMap< Long, PlanDeviation > derivationMap, int actIter, int maxIter)
Method to select persons and plans, which should be recalculated.
Parameters
derivationMap The derivation map of the plans
actIter the actual iteration
maxIter the maximum value actIter can reach
Returns
A map of plans for recalculation
Reimplemented from de.dlr.ivf.tapas.iteration.TPS_IterationManagement.
Definition at line 40 of file TPS_BasicIterationManager.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_TRIPS, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.INFO, de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), de.dlr.ivf.tapas.log.TPS_Logger.log(), and de.dlr.ivf.tapas.util.Randomizer.random().
Member Data Documentation
parameterClass
final TPS_ParameterClass de.dlr.ivf.tapas.iteration.TPS_BasicIterationManager.parameterClass private
Definition at line 33 of file TPS_BasicIterationManager.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/iteration/TPS_BasicIterationManager.java