TAPAS: de.dlr.ivf.tapas.tools.fileModifier.persistence.TPS_ParameterXLSDAO Class Reference
de.dlr.ivf.tapas.tools.fileModifier.persistence.TPS_ParameterXLSDAO Class Reference
Public Member Functions
TPS_ParameterXLSDAO ()
void convert (File oldFile, File newPath, TPS_ParameterClass parameterClass)
void writeParameter (TPS_ParameterClass parameterClass)
Public Member Functions inherited from de.dlr.ivf.tapas.tools.fileModifier.persistence.AbstractTPS_ParameterDAO
AbstractTPS_ParameterDAO ()
void addAdditionalParameter (String name, String value, String comment)
File getFile ()
void setFile (File file)
void readParameter ()
void writeParameter ()
Private Attributes
final Map< String, Enum<?> > map
final IndexedColors[] indexedColors = new IndexedColors[]{IndexedColors.LIGHT_CORNFLOWER_BLUE, IndexedColors.LIGHT_GREEN, IndexedColors.WHITE}
final String[] prefixes = new String[]{"run_", "file_", "db_", "par_", "log_"}
Additional Inherited Members
Public Attributes inherited from de.dlr.ivf.tapas.tools.fileModifier.persistence.ITPS_ParameterDAO
String[] header = new String[]{"name", "value", "comment"}
Detailed Description
Definition at line 23 of file TPS_ParameterXLSDAO.java.
Constructor & Destructor Documentation
TPS_ParameterXLSDAO()
de.dlr.ivf.tapas.tools.fileModifier.persistence.TPS_ParameterXLSDAO.TPS_ParameterXLSDAO ()
Definition at line 32 of file TPS_ParameterXLSDAO.java.
References de.dlr.ivf.tapas.util.parameters.ParamValue.AVERAGE_DISTANCE_PT_STOP, de.dlr.ivf.tapas.util.parameters.ParamString.DB_DBNAME, de.dlr.ivf.tapas.util.parameters.ParamValue.DEFAULT_VOT, de.dlr.ivf.tapas.util.parameters.ParamValue.FINANCE_BUDGET_E, de.dlr.ivf.tapas.util.parameters.ParamValue.FINANCE_BUDGET_F, de.dlr.ivf.tapas.util.parameters.ParamValue.FINANCE_BUDGET_WP, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_CHECK_BUDGET_CONSTRAINTS, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_INFLUENCE_RANDOM_NUMBER, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_INTRA_INFOS_MATRIX, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_LOCATION_POCKET_COSTS, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_REJUVENATE_RETIREE, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_RUN_SZENARIO, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_SCHEMES_MANIPULATE_BY_WORK_AT_HOME, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_SCHEMES_MANIPULATE_BY_WORKINGCHAINS, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_SCHEMES_MANIPULATE_SELECTION_PROBS, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_SELECT_LOCATIONS_DIFF_PERSON_GROUP, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_USE_BLOCK_LEVEL, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_USE_DRIVING_LICENCE, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_USE_EXIT_MAUT, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_USE_FIXED_LOCS_ON_BASE, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_USE_SCHOOLBUS, de.dlr.ivf.tapas.util.parameters.ParamValue.GAMMA_LOCATION_WEIGHT, de.dlr.ivf.tapas.util.parameters.ParamValue.LOC_CHOICE_MOD_CFN4, de.dlr.ivf.tapas.util.parameters.ParamValue.MAX_TIME_DIFFERENCE, de.dlr.ivf.tapas.util.parameters.ParamValue.MAX_TRIES_PERSON, de.dlr.ivf.tapas.util.parameters.ParamValue.MIT_FUEL_COST_PER_KM_COMMUTE, de.dlr.ivf.tapas.util.parameters.ParamValue.MIT_FUEL_COST_PER_KM_COMMUTE_BASE, de.dlr.ivf.tapas.util.parameters.ParamValue.MIT_GASOLINE_COST_PER_KM, de.dlr.ivf.tapas.util.parameters.ParamValue.MIT_GASOLINE_COST_PER_KM_BASE, de.dlr.ivf.tapas.util.parameters.ParamValue.MIT_VARIABLE_COST_PER_KM, de.dlr.ivf.tapas.util.parameters.ParamValue.MIT_VARIABLE_COST_PER_KM_BASE, de.dlr.ivf.tapas.util.parameters.ParamValue.PARKING_FEE_CAT_1, de.dlr.ivf.tapas.util.parameters.ParamValue.PARKING_FEE_CAT_1_BASE, de.dlr.ivf.tapas.util.parameters.ParamValue.PARKING_FEE_CAT_2, de.dlr.ivf.tapas.util.parameters.ParamValue.PARKING_FEE_CAT_2_BASE, de.dlr.ivf.tapas.util.parameters.ParamValue.PARKING_FEE_CAT_3, de.dlr.ivf.tapas.util.parameters.ParamValue.PARKING_FEE_CAT_3_BASE, de.dlr.ivf.tapas.util.parameters.ParamString.PATH_ABS_INPUT, de.dlr.ivf.tapas.util.parameters.ParamString.PATH_ABS_OUTPUT, de.dlr.ivf.tapas.util.parameters.ParamValue.PT_COST_PER_KM, de.dlr.ivf.tapas.util.parameters.ParamValue.PT_COST_PER_KM_BASE, de.dlr.ivf.tapas.util.parameters.ParamValue.RANDOM_SEED_NUMBER, de.dlr.ivf.tapas.util.parameters.ParamValue.REJUVENATE_BY_NB_YEARS, de.dlr.ivf.tapas.util.parameters.ParamValue.TAXI_COST_PER_KM, de.dlr.ivf.tapas.util.parameters.ParamValue.TAXI_COST_PER_KM_BASE, de.dlr.ivf.tapas.util.parameters.ParamValue.TIME_BUDGET_E, de.dlr.ivf.tapas.util.parameters.ParamValue.TIME_BUDGET_F, de.dlr.ivf.tapas.util.parameters.ParamValue.TIME_BUDGET_WP, de.dlr.ivf.tapas.util.parameters.ParamValue.TOLL_CAT_1, de.dlr.ivf.tapas.util.parameters.ParamValue.TOLL_CAT_1_BASE, de.dlr.ivf.tapas.util.parameters.ParamValue.TOLL_CAT_2, de.dlr.ivf.tapas.util.parameters.ParamValue.TOLL_CAT_2_BASE, de.dlr.ivf.tapas.util.parameters.ParamValue.TOLL_CAT_3, de.dlr.ivf.tapas.util.parameters.ParamValue.TOLL_CAT_3_BASE, de.dlr.ivf.tapas.util.parameters.ParamValue.TRAIN_COST_PER_KM, de.dlr.ivf.tapas.util.parameters.ParamValue.TRAIN_COST_PER_KM_BASE, de.dlr.ivf.tapas.util.parameters.ParamString.UTILITY_FUNCTION_CLASS, de.dlr.ivf.tapas.util.parameters.ParamValue.VELOCITY_BIKE, de.dlr.ivf.tapas.util.parameters.ParamValue.VELOCITY_FOOT, de.dlr.ivf.tapas.util.parameters.ParamValue.WEIGHT_WORKING_AT_HOME, and de.dlr.ivf.tapas.util.parameters.ParamValue.WEIGHT_WORKING_CHAINS.
Member Function Documentation
convert()
void de.dlr.ivf.tapas.tools.fileModifier.persistence.TPS_ParameterXLSDAO.convert (File oldFile, File newPath, TPS_ParameterClass parameterClass)
File converter (obsolete?!)
Parameters
oldFile
newPath
Definition at line 136 of file TPS_ParameterXLSDAO.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.CLASS_DATA_SCOURCE_ORIGIN, de.dlr.ivf.tapas.util.parameters.ParamString.FILE_DATABASE_PROPERTIES, de.dlr.ivf.tapas.util.parameters.ParamString.FILE_LOGGING_PROPERTIES, de.dlr.ivf.tapas.util.parameters.ParamString.FILE_PARAMETER_PROPERTIES, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getDoubleValue(), de.dlr.ivf.tapas.util.parameters.ParamType.getIndex(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getType(), de.dlr.ivf.tapas.tools.fileModifier.persistence.ITPS_ParameterDAO.header, de.dlr.ivf.tapas.tools.fileModifier.persistence.TPS_ParameterXLSDAO.indexedColors, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isDefined(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isTrue(), name, and de.dlr.ivf.tapas.tools.fileModifier.persistence.TPS_ParameterXLSDAO.prefixes.
writeParameter()
void de.dlr.ivf.tapas.tools.fileModifier.persistence.TPS_ParameterXLSDAO.writeParameter (TPS_ParameterClass parameterClass)
Definition at line 286 of file TPS_ParameterXLSDAO.java.
References de.dlr.ivf.tapas.util.parameters.ParamType.DB, de.dlr.ivf.tapas.util.parameters.ParamType.DEFAULT, de.dlr.ivf.tapas.util.parameters.ParamType.FILE, de.dlr.ivf.tapas.util.parameters.ParamString.FILE_DATABASE_PROPERTIES, de.dlr.ivf.tapas.util.parameters.ParamString.FILE_LOGGING_PROPERTIES, de.dlr.ivf.tapas.util.parameters.ParamString.FILE_PARAMETER_PROPERTIES, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getDoubleValue(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getType(), de.dlr.ivf.tapas.tools.fileModifier.persistence.ITPS_ParameterDAO.header, de.dlr.ivf.tapas.tools.fileModifier.persistence.TPS_ParameterXLSDAO.indexedColors, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isDefined(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isTrue(), de.dlr.ivf.tapas.util.parameters.ParamType.LOG, name, de.dlr.ivf.tapas.tools.fileModifier.persistence.TPS_ParameterXLSDAO.prefixes, and de.dlr.ivf.tapas.util.parameters.ParamType.RUN.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.init().
Member Data Documentation
indexedColors
final IndexedColors [] de.dlr.ivf.tapas.tools.fileModifier.persistence.TPS_ParameterXLSDAO.indexedColors = new IndexedColors[]{IndexedColors.LIGHT_CORNFLOWER_BLUE, IndexedColors.LIGHT_GREEN, IndexedColors.WHITE} private
Definition at line 29 of file TPS_ParameterXLSDAO.java.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.persistence.TPS_ParameterXLSDAO.convert(), and de.dlr.ivf.tapas.tools.fileModifier.persistence.TPS_ParameterXLSDAO.writeParameter().
map
final Map<String, Enum<?> > de.dlr.ivf.tapas.tools.fileModifier.persistence.TPS_ParameterXLSDAO.map private
Mapping for String to enums
Definition at line 28 of file TPS_ParameterXLSDAO.java.
prefixes
final String [] de.dlr.ivf.tapas.tools.fileModifier.persistence.TPS_ParameterXLSDAO.prefixes = new String[]{"run_", "file_", "db_", "par_", "log_"} private
Definition at line 30 of file TPS_ParameterXLSDAO.java.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.persistence.TPS_ParameterXLSDAO.convert(), and de.dlr.ivf.tapas.tools.fileModifier.persistence.TPS_ParameterXLSDAO.writeParameter().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/fileModifier/persistence/TPS_ParameterXLSDAO.java