TAPAS: de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler Class Reference
de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler Class Reference
Public Member Functions
void addRules ()
JFrame createAndShowGUI ()
Static Public Member Functions
static void main (String[] args) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException
Private Member Functions
JFrame createGui ()
JList< String > getJActionsList ()
JButton getJAddButton ()
JList< String > getJBBRCatList ()
JTextField getJBikeTextFieldF ()
JTextField getJBikeTextFieldS ()
JList< String > getJDistancesList ()
JTextField getJFilenameTextField ()
JTextField getJMIVTextFieldF ()
JTextField getJMIVTextFieldS ()
JPanel getJMainContentPane ()
JTextField getJMiscTextFieldF ()
JTextField getJMiscTextFieldS ()
JTextField getJOeVTextFieldF ()
JTextField getJOeVTextFieldS ()
JPanel getJOutputPanel ()
JTextField getJPassTextFieldF ()
JTextField getJPassTextFieldS ()
JList< String > getJPersonsList ()
JPanel getJTargetPanel ()
JTextField getJTaxiTextFieldF ()
JTextField getJTaxiTextFieldS ()
JPanel getJValuesPanel ()
JTextField getJWalkTextFieldF ()
JTextField getJWalkTextFieldS ()
Private Attributes
JFrame controlInstance
JPanel jMainContentPane = null
JPanel jTargetPanel = null
JList< String > jPersonsList = null
JList< String > jActionsList = null
JList< String > jDistancesList = null
JPanel jValuesPanel = null
JTextField jMIVTextFieldF = null
JTextField jMIVTextFieldS = null
JTextField jPassTextFieldF = null
JTextField jPassTextFieldS = null
JTextField jOeVTextFieldF = null
JTextField jOeVTextFieldS = null
JTextField jBikeTextFieldF = null
JTextField jBikeTextFieldS = null
JTextField jWalkTextFieldF = null
JTextField jWalkTextFieldS = null
JTextField jMiscTextFieldF = null
JTextField jMiscTextFieldS = null
JTextField jTaxiTextFieldF = null
JTextField jTaxiTextFieldS = null
JPanel jOutputPanel = null
JTextField jFilenameTextField = null
JButton jAddButton = null
final HashMap< Integer, Integer > distanceConverter = new HashMap<>()
final HashMap< Integer, Integer[]> actionConverter = new HashMap<>()
JList< String > jBBRCatList = null
Detailed Description
Definition at line 25 of file ExpertKnowledgeHandler.java.
Member Function Documentation
addRules()
void de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.addRules ()
Definition at line 66 of file ExpertKnowledgeHandler.java.
createAndShowGUI()
JFrame de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.createAndShowGUI ()
Definition at line 187 of file ExpertKnowledgeHandler.java.
References de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.controlInstance, and de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.createGui().
Referenced by de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.main(), and de.dlr.ivf.tapas.runtime.client.SimulationMonitor.SimulationMonitor().
createGui()
JFrame de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.createGui () private
Definition at line 192 of file ExpertKnowledgeHandler.java.
References de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.getJMainContentPane().
Referenced by de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.createAndShowGUI().
getJActionsList()
JList<String> de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.getJActionsList () private
This method initializes jActionsList
Returns
javax.swing.JList
Definition at line 216 of file ExpertKnowledgeHandler.java.
References de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.actionConverter, and de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.jActionsList.
getJAddButton()
JButton de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.getJAddButton () private
This method initializes jAddButton
Returns
javax.swing.JButton
Definition at line 262 of file ExpertKnowledgeHandler.java.
References de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.jAddButton.
getJBBRCatList()
JList<String> de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.getJBBRCatList () private
This method initializes jBBRCatList
Returns
javax.swing.JList
Definition at line 279 of file ExpertKnowledgeHandler.java.
getJBikeTextFieldF()
JTextField de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.getJBikeTextFieldF () private
This method initializes jBikeTextField
Returns
javax.swing.JTextField
Definition at line 294 of file ExpertKnowledgeHandler.java.
getJBikeTextFieldS()
JTextField de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.getJBikeTextFieldS () private
This method initializes jBikeTextField
Returns
javax.swing.JTextField
Definition at line 306 of file ExpertKnowledgeHandler.java.
getJDistancesList()
JList<String> de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.getJDistancesList () private
This method initializes jDistancesList
Returns
javax.swing.JList
Definition at line 318 of file ExpertKnowledgeHandler.java.
getJFilenameTextField()
JTextField de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.getJFilenameTextField () private
This method initializes jFilenameTextField
Returns
javax.swing.JTextField
Definition at line 342 of file ExpertKnowledgeHandler.java.
getJMainContentPane()
JPanel de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.getJMainContentPane () private
This method initializes jMainContentPane
Returns
javax.swing.JPanel
Definition at line 378 of file ExpertKnowledgeHandler.java.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.createGui().
getJMiscTextFieldF()
JTextField de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.getJMiscTextFieldF () private
This method initializes jMiscTextField
Returns
javax.swing.JTextField
Definition at line 394 of file ExpertKnowledgeHandler.java.
getJMiscTextFieldS()
JTextField de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.getJMiscTextFieldS () private
This method initializes jMiscTextField
Returns
javax.swing.JTextField
Definition at line 406 of file ExpertKnowledgeHandler.java.
getJMIVTextFieldF()
JTextField de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.getJMIVTextFieldF () private
This method initializes jMIVTextField
Returns
javax.swing.JTextField
Definition at line 354 of file ExpertKnowledgeHandler.java.
getJMIVTextFieldS()
JTextField de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.getJMIVTextFieldS () private
This method initializes jMIVTextField
Returns
javax.swing.JTextField
Definition at line 366 of file ExpertKnowledgeHandler.java.
getJOeVTextFieldF()
JTextField de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.getJOeVTextFieldF () private
This method initializes jOeVTextField
Returns
javax.swing.JTextField
Definition at line 418 of file ExpertKnowledgeHandler.java.
getJOeVTextFieldS()
JTextField de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.getJOeVTextFieldS () private
This method initializes jOeVTextField
Returns
javax.swing.JTextField
Definition at line 430 of file ExpertKnowledgeHandler.java.
getJOutputPanel()
JPanel de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.getJOutputPanel () private
This method initializes jOutputPanel
Returns
javax.swing.JPanel
Definition at line 442 of file ExpertKnowledgeHandler.java.
getJPassTextFieldF()
JTextField de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.getJPassTextFieldF () private
This method initializes jPassTextField
Returns
javax.swing.JTextField
Definition at line 465 of file ExpertKnowledgeHandler.java.
getJPassTextFieldS()
JTextField de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.getJPassTextFieldS () private
This method initializes jPassTextField
Returns
javax.swing.JTextField
Definition at line 477 of file ExpertKnowledgeHandler.java.
getJPersonsList()
JList<String> de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.getJPersonsList () private
This method initializes jPersonsList
Returns
javax.swing.JList
Definition at line 489 of file ExpertKnowledgeHandler.java.
getJTargetPanel()
JPanel de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.getJTargetPanel () private
This method initializes jTargetPanel
Returns
javax.swing.JPanel
Definition at line 502 of file ExpertKnowledgeHandler.java.
getJTaxiTextFieldF()
JTextField de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.getJTaxiTextFieldF () private
This method initializes jTaxiTextField
Returns
javax.swing.JTextField
Definition at line 544 of file ExpertKnowledgeHandler.java.
getJTaxiTextFieldS()
JTextField de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.getJTaxiTextFieldS () private
This method initializes jTaxiTextField
Returns
javax.swing.JTextField
Definition at line 556 of file ExpertKnowledgeHandler.java.
getJValuesPanel()
JPanel de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.getJValuesPanel () private
This method initializes jValuesPanel
Returns
javax.swing.JPanel
Definition at line 568 of file ExpertKnowledgeHandler.java.
getJWalkTextFieldF()
JTextField de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.getJWalkTextFieldF () private
This method initializes jWalkTextField
Returns
javax.swing.JTextField
Definition at line 648 of file ExpertKnowledgeHandler.java.
getJWalkTextFieldS()
JTextField de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.getJWalkTextFieldS () private
This method initializes jWalkTextField
Returns
javax.swing.JTextField
Definition at line 660 of file ExpertKnowledgeHandler.java.
main()
static void de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.main (String[] args) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException static
Parameters
args
Definition at line 59 of file ExpertKnowledgeHandler.java.
References de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.controlInstance, and de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.createAndShowGUI().
Member Data Documentation
actionConverter
final HashMap<Integer, Integer[]> de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.actionConverter = new HashMap<>() private
Definition at line 53 of file ExpertKnowledgeHandler.java.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.getJActionsList().
controlInstance
JFrame de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.controlInstance private
Definition at line 28 of file ExpertKnowledgeHandler.java.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.createAndShowGUI(), and de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.main().
distanceConverter
final HashMap<Integer, Integer> de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.distanceConverter = new HashMap<>() private
Definition at line 52 of file ExpertKnowledgeHandler.java.
jActionsList
JList<String> de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.jActionsList = null private
Definition at line 32 of file ExpertKnowledgeHandler.java.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.getJActionsList().
jAddButton
JButton de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.jAddButton = null private
Definition at line 51 of file ExpertKnowledgeHandler.java.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.getJAddButton().
jBBRCatList
JList<String> de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.jBBRCatList = null private
Definition at line 54 of file ExpertKnowledgeHandler.java.
jBikeTextFieldF
JTextField de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.jBikeTextFieldF = null private
Definition at line 41 of file ExpertKnowledgeHandler.java.
jBikeTextFieldS
JTextField de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.jBikeTextFieldS = null private
Definition at line 42 of file ExpertKnowledgeHandler.java.
jDistancesList
JList<String> de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.jDistancesList = null private
Definition at line 33 of file ExpertKnowledgeHandler.java.
jFilenameTextField
JTextField de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.jFilenameTextField = null private
Definition at line 50 of file ExpertKnowledgeHandler.java.
jMainContentPane
JPanel de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.jMainContentPane = null private
Definition at line 29 of file ExpertKnowledgeHandler.java.
jMiscTextFieldF
JTextField de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.jMiscTextFieldF = null private
Definition at line 45 of file ExpertKnowledgeHandler.java.
jMiscTextFieldS
JTextField de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.jMiscTextFieldS = null private
Definition at line 46 of file ExpertKnowledgeHandler.java.
jMIVTextFieldF
JTextField de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.jMIVTextFieldF = null private
Definition at line 35 of file ExpertKnowledgeHandler.java.
jMIVTextFieldS
JTextField de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.jMIVTextFieldS = null private
Definition at line 36 of file ExpertKnowledgeHandler.java.
jOeVTextFieldF
JTextField de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.jOeVTextFieldF = null private
Definition at line 39 of file ExpertKnowledgeHandler.java.
jOeVTextFieldS
JTextField de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.jOeVTextFieldS = null private
Definition at line 40 of file ExpertKnowledgeHandler.java.
jOutputPanel
JPanel de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.jOutputPanel = null private
Definition at line 49 of file ExpertKnowledgeHandler.java.
jPassTextFieldF
JTextField de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.jPassTextFieldF = null private
Definition at line 37 of file ExpertKnowledgeHandler.java.
jPassTextFieldS
JTextField de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.jPassTextFieldS = null private
Definition at line 38 of file ExpertKnowledgeHandler.java.
jPersonsList
JList<String> de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.jPersonsList = null private
Definition at line 31 of file ExpertKnowledgeHandler.java.
jTargetPanel
JPanel de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.jTargetPanel = null private
Definition at line 30 of file ExpertKnowledgeHandler.java.
jTaxiTextFieldF
JTextField de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.jTaxiTextFieldF = null private
Definition at line 47 of file ExpertKnowledgeHandler.java.
jTaxiTextFieldS
JTextField de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.jTaxiTextFieldS = null private
Definition at line 48 of file ExpertKnowledgeHandler.java.
jValuesPanel
JPanel de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.jValuesPanel = null private
Definition at line 34 of file ExpertKnowledgeHandler.java.
jWalkTextFieldF
JTextField de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.jWalkTextFieldF = null private
Definition at line 43 of file ExpertKnowledgeHandler.java.
jWalkTextFieldS
JTextField de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.jWalkTextFieldS = null private
Definition at line 44 of file ExpertKnowledgeHandler.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/fileModifier/ExpertKnowledgeHandler.java