TAPAS: de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.PersonGroupAnalyzer Class Reference
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.PersonGroupAnalyzer Class Reference
Public Member Functions
PersonGroupAnalyzer ()
PersonGroupAnalyzer (AnalyzerBase... analyzers)
PersonGroup assignTrip (TapasTrip trip)
int getCntPersons (CategoryCombination cc)
boolean keepsCnt ()
Private Attributes
final HashMap< CategoryCombination, HashSet< Integer > > personSets
final AnalyzerBase[] analyzers
boolean keepsPersonCnt = false
Detailed Description
When created with reference to other analyzers, the PersonGroupAnalyzer keeps the number of persons for each CategoryCombination.
Definition at line 907 of file TuMEnums.java.
Constructor & Destructor Documentation
PersonGroupAnalyzer() [1/2]
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.PersonGroupAnalyzer.PersonGroupAnalyzer ()
Definition at line 913 of file TuMEnums.java.
PersonGroupAnalyzer() [2/2]
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.PersonGroupAnalyzer.PersonGroupAnalyzer (AnalyzerBase... analyzers)
Definition at line 917 of file TuMEnums.java.
Member Function Documentation
assignTrip()
PersonGroup de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.PersonGroupAnalyzer.assignTrip (TapasTrip trip)
Definition at line 929 of file TuMEnums.java.
References de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.getById(), de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.PersonGroup.getByJob(), de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTrip.getIdPers(), and de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTrip.getJob().
getCntPersons()
int de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.PersonGroupAnalyzer.getCntPersons (CategoryCombination cc)
Returns
-1 if the information is not available.
Definition at line 953 of file TuMEnums.java.
keepsCnt()
boolean de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.PersonGroupAnalyzer.keepsCnt ()
Definition at line 963 of file TuMEnums.java.
Member Data Documentation
analyzers
final AnalyzerBase [] de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.PersonGroupAnalyzer.analyzers private
Definition at line 910 of file TuMEnums.java.
keepsPersonCnt
boolean de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.PersonGroupAnalyzer.keepsPersonCnt = false private
Definition at line 911 of file TuMEnums.java.
personSets
final HashMap<CategoryCombination, HashSet<Integer> > de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.PersonGroupAnalyzer.personSets private
Definition at line 909 of file TuMEnums.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/tum/constants/TuMEnums.java