TAPAS: de.dlr.ivf.tapas.loc.TPS_Location Class Reference
de.dlr.ivf.tapas.loc.TPS_Location Class Reference
Classes
class TPS_LocationData
Public Member Functions
TPS_Location (int id, int groupId, TPS_LocationConstant locType, double x, double y, TPS_TrafficAnalysisZone taz, TPS_Block block, TPS_ParameterClass parameterClass)
TPS_Block getBlock ()
TPS_Coordinate getCoordinate ()
TPS_LocationData getData ()
int getGroupId ()
int getId ()
TPS_LocationConstant getLocType ()
int getTAZId ()
TPS_TrafficAnalysisZone getTrafficAnalysisZone ()
boolean hasBlock ()
boolean hasData ()
void initCapacity (int capacity, boolean fixCapacity)
boolean isSameLocationGroup (TPS_Location ref)
String toString ()
void updateOccupancy (int occupancy)
Private Attributes
final TPS_Block block
Reference to the block if this information is available.
final TPS_Coordinate coordinate
Coordinate of the location.
final TPS_LocationConstant locType
The location code of the location.
Set< TPS_ActivityConstant > activities = null
The list of possible activities (determined from the location code at initialisation)
TPS_LocationData data = null
This location's data.
final int id
The id of the location.
final TPS_ParameterClass parameterClass
final int groupId
final TPS_TrafficAnalysisZone taz
The traffic analysis zone this location is located in.
Detailed Description
This class represents a location within a region. It is characterized by a capacity, weight and an occupancy. Furthermore it is located at a coordinate. There exist two references to higher regions: the location set and the block. The block level is not known in all regions so this reference may be null.
Author
mark_ma
Definition at line 35 of file TPS_Location.java.
Constructor & Destructor Documentation
TPS_Location()
de.dlr.ivf.tapas.loc.TPS_Location.TPS_Location (int id, int groupId, TPS_LocationConstant locType, double x, double y, TPS_TrafficAnalysisZone taz, TPS_Block block, TPS_ParameterClass parameterClass)
The constructor sets the id of the location. The occupancy is set to 0 and the weight is calculated.
Parameters
id The id of the location
groupId The id of the locations group this location belongs to
locType The type of this location
x The x-coordinate of this location
y The y-coordinate of this location
parameterClass parameter container reference
Definition at line 70 of file TPS_Location.java.
References de.dlr.ivf.tapas.constants.TPS_LocationConstant.HOME, de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.LOCATION2ACTIVITIES_MAP, and de.dlr.ivf.tapas.loc.TPS_Coordinate.setValues().
Member Function Documentation
getBlock()
TPS_Block de.dlr.ivf.tapas.loc.TPS_Location.getBlock ()
Returns the block of the location
Returns
The block this location is located in; may be null
Implements de.dlr.ivf.tapas.loc.Locatable.
Definition at line 90 of file TPS_Location.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.batchStoreTrips(), and de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes().
getCoordinate()
TPS_Coordinate de.dlr.ivf.tapas.loc.TPS_Location.getCoordinate ()
Returns the coordinate of the location
Returns
The coordinates of this location
Implements de.dlr.ivf.tapas.loc.Locatable.
Definition at line 99 of file TPS_Location.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.batchStoreTrips().
getData()
TPS_LocationData de.dlr.ivf.tapas.loc.TPS_Location.getData ()
Returns this location's data
Returns
Data of this location
Definition at line 108 of file TPS_Location.java.
Referenced by de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.TypedWeightedLocationDistribution.addLocation(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.getTrafficAnalysisZonesAround(), and de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.TypedWeightedLocationDistribution.selectActivityLocations().
getGroupId()
int de.dlr.ivf.tapas.loc.TPS_Location.getGroupId ()
Returns the id of the group this location belongs to
Returns
The id of this location's group (may be -1 if not given)
Definition at line 117 of file TPS_Location.java.
Referenced by de.dlr.ivf.tapas.loc.TPS_Location.isSameLocationGroup().
getId()
int de.dlr.ivf.tapas.loc.TPS_Location.getId ()
Returns the id of this location
Returns
The id of this location
Definition at line 126 of file TPS_Location.java.
Referenced by de.dlr.ivf.tapas.loc.TPS_Region.addLocation(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.batchStoreTrips(), de.dlr.ivf.tapas.loc.TPS_FocusPointModel.getFocusPoint(), and de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes().
getLocType()
TPS_LocationConstant de.dlr.ivf.tapas.loc.TPS_Location.getLocType ()
Returns the location type
Returns
The type of this location
Definition at line 135 of file TPS_Location.java.
Referenced by de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.addLocation().
getTAZId()
int de.dlr.ivf.tapas.loc.TPS_Location.getTAZId ()
Returns the id of the traffic assignment zone this location belongs to
Returns
The id of the traffic assignment zone this location belongs to
Implements de.dlr.ivf.tapas.loc.Locatable.
Definition at line 145 of file TPS_Location.java.
getTrafficAnalysisZone()
TPS_TrafficAnalysisZone de.dlr.ivf.tapas.loc.TPS_Location.getTrafficAnalysisZone ()
Returns the traffic analysis zone this location belongs to
Returns
The traffic analysis zone this location belongs to
Implements de.dlr.ivf.tapas.loc.Locatable.
Definition at line 154 of file TPS_Location.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.batchStoreTrips(), de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixedBS.getDistributionSet(), de.dlr.ivf.tapas.loc.TPS_SelectLocationWeightBased.selectLocationFromChoiceSet(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.selectLocationFromChoiceSet(), de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes(), de.dlr.ivf.tapas.mode.TPS_ModeSet.selectMode0(), and de.dlr.ivf.tapas.plan.TPS_Plan.TPS_Plan().
hasBlock()
boolean de.dlr.ivf.tapas.loc.TPS_Location.hasBlock ()
Flag if the block of the location is known and set as reference
Returns
true if the reference to the block is not null, false otherwise
Implements de.dlr.ivf.tapas.loc.Locatable.
Definition at line 163 of file TPS_Location.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.batchStoreTrips(), and de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes().
hasData()
boolean de.dlr.ivf.tapas.loc.TPS_Location.hasData ()
Flag if data is attached to this location
Returns
true if getData returns not null
Definition at line 172 of file TPS_Location.java.
Referenced by de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.addLocation().
initCapacity()
void de.dlr.ivf.tapas.loc.TPS_Location.initCapacity (int capacity, boolean fixCapacity)
Inits this location's capacity
Parameters
capacity the capacity
fixCapacity true if the capacity is fixed
Definition at line 182 of file TPS_Location.java.
References de.dlr.ivf.tapas.loc.TPS_Location.TPS_LocationData.init().
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.loadHouseholds(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readRegion().
isSameLocationGroup()
boolean de.dlr.ivf.tapas.loc.TPS_Location.isSameLocationGroup (TPS_Location ref)
Method to determine if two locations are within the same group.
Parameters
ref The location to check
Returns
true if both locations are in the same location group
Definition at line 193 of file TPS_Location.java.
References de.dlr.ivf.tapas.loc.TPS_Location.getGroupId().
toString()
String de.dlr.ivf.tapas.loc.TPS_Location.toString ()
Returns this object's string representation
See also
java.lang.Object::toString()
Definition at line 203 of file TPS_Location.java.
References de.dlr.ivf.tapas.constants.TPS_LocationConstant.TPS_LocationCodeType.TAPAS, and de.dlr.ivf.tapas.loc.TPS_Location.TPS_LocationData.toString().
updateOccupancy()
void de.dlr.ivf.tapas.loc.TPS_Location.updateOccupancy (int occupancy)
Updates the occupancy of this location
A location may allow different activities. The location's weight has therefore to be adapted for all supported activity types.
Parameters
occupancy This location's new occupancy
Definition at line 217 of file TPS_Location.java.
References de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.allowsActivity(), de.dlr.ivf.tapas.loc.TPS_Location.TPS_LocationData.getWeight(), de.dlr.ivf.tapas.loc.TPS_Location.TPS_LocationData.setOccupancy(), and de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.updateActivityOccupancy().
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.updateOccupancyTable().
Member Data Documentation
activities
Set<TPS_ActivityConstant> de.dlr.ivf.tapas.loc.TPS_Location.activities = null private
The list of possible activities (determined from the location code at initialisation)
Definition at line 44 of file TPS_Location.java.
block
final TPS_Block de.dlr.ivf.tapas.loc.TPS_Location.block private
Reference to the block if this information is available.
Definition at line 38 of file TPS_Location.java.
coordinate
final TPS_Coordinate de.dlr.ivf.tapas.loc.TPS_Location.coordinate private
Coordinate of the location.
Definition at line 40 of file TPS_Location.java.
data
TPS_LocationData de.dlr.ivf.tapas.loc.TPS_Location.data = null private
This location's data.
Definition at line 46 of file TPS_Location.java.
groupId
final int de.dlr.ivf.tapas.loc.TPS_Location.groupId private
Group Id of the location, which associates this location to a group, e.g. shopping mall, where you can shop, eat and work. Should be set to -1, if no information is available.
Definition at line 55 of file TPS_Location.java.
id
final int de.dlr.ivf.tapas.loc.TPS_Location.id private
The id of the location.
Definition at line 48 of file TPS_Location.java.
locType
final TPS_LocationConstant de.dlr.ivf.tapas.loc.TPS_Location.locType private
The location code of the location.
Definition at line 42 of file TPS_Location.java.
parameterClass
final TPS_ParameterClass de.dlr.ivf.tapas.loc.TPS_Location.parameterClass private
Definition at line 49 of file TPS_Location.java.
taz
final TPS_TrafficAnalysisZone de.dlr.ivf.tapas.loc.TPS_Location.taz private
The traffic analysis zone this location is located in.
Definition at line 57 of file TPS_Location.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/loc/TPS_Location.java