TAPAS: de.dlr.ivf.tapas.loc.TPS_MultipleTAZRepresentant Class Reference
de.dlr.ivf.tapas.loc.TPS_MultipleTAZRepresentant Class Reference
Public Member Functions
List< TPS_Location > generateLocationRepr (TPS_ActivityConstant actCode, TPS_TrafficAnalysisZone taz)
TPS_RegionResultSet getLocationRepresentatives (TPS_Plan plan, TPS_PlanningContext pc, TPS_LocatedStay locatedStay, TPS_ParameterClass parameterClass)
Public Member Functions inherited from de.dlr.ivf.tapas.loc.TPS_LocationChoiceSet
void setClassReferences (TPS_Region region, TPS_DB_IOManager pm)
Detailed Description
Definition at line 33 of file TPS_MultipleTAZRepresentant.java.
Member Function Documentation
generateLocationRepr()
List<TPS_Location> de.dlr.ivf.tapas.loc.TPS_MultipleTAZRepresentant.generateLocationRepr (TPS_ActivityConstant actCode, TPS_TrafficAnalysisZone taz)
Definition at line 37 of file TPS_MultipleTAZRepresentant.java.
References de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.allowsActivity(), and de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.selectActivityLocations().
Referenced by de.dlr.ivf.tapas.loc.TPS_MultipleTAZRepresentant.getLocationRepresentatives().
getLocationRepresentatives()
TPS_RegionResultSet de.dlr.ivf.tapas.loc.TPS_MultipleTAZRepresentant.getLocationRepresentatives (TPS_Plan plan, TPS_PlanningContext pc, TPS_LocatedStay locatedStay, TPS_ParameterClass parameterClass)
Method to return the locations, which are possible to use for the given activity.
Parameters
plan the plan to use
pc planning context
locatedStay the located stay we are coming from
parameterClass parameter container reference
Returns
A TPS_RegionResultSet of appropriate locations
Reimplemented from de.dlr.ivf.tapas.loc.TPS_LocationChoiceSet.
Definition at line 54 of file TPS_MultipleTAZRepresentant.java.
References de.dlr.ivf.tapas.TPS_Main.actStats, de.dlr.ivf.tapas.persistence.TPS_RegionResultSet.add(), de.dlr.ivf.tapas.persistence.TPS_RegionResultSet.clear(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.DEBUG, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_FILTER_SHOPPING_CHOICE_SET, de.dlr.ivf.tapas.loc.TPS_MultipleTAZRepresentant.generateLocationRepr(), de.dlr.ivf.tapas.mode.TPS_Mode.get(), de.dlr.ivf.tapas.scheme.TPS_Episode.getActCode(), de.dlr.ivf.tapas.scheme.TPS_TourPart.TravelDurations.getArrivalDuration(), de.dlr.ivf.tapas.scheme.TPS_TourPart.getCar(), de.dlr.ivf.tapas.constants.TPS_ActivityConstant.getCode(), de.dlr.ivf.tapas.scheme.TPS_TourPart.TravelDurations.getDepartureDuration(), de.dlr.ivf.tapas.mode.TPS_Mode.getDistance(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getDoubleValue(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getIntValue(), de.dlr.ivf.tapas.plan.TPS_Plan.getLocatedStay(), de.dlr.ivf.tapas.plan.TPS_LocatedStay.getLocation(), de.dlr.ivf.tapas.scheme.TPS_TourPart.TPS_StayHierarchy.getNextStay(), de.dlr.ivf.tapas.persistence.TPS_PersistenceManager.getParameters(), de.dlr.ivf.tapas.plan.TPS_Plan.getPM(), de.dlr.ivf.tapas.scheme.TPS_TourPart.TPS_StayHierarchy.getPrevStay(), de.dlr.ivf.tapas.scheme.TPS_Episode.getSchemePart(), de.dlr.ivf.tapas.plan.TPS_LocatedStay.getStay(), de.dlr.ivf.tapas.scheme.TPS_TourPart.getStayHierarchy(), de.dlr.ivf.tapas.scheme.TPS_TourPart.getTravelDurations(), de.dlr.ivf.tapas.scheme.TPS_TourPart.isCarUsed(), de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), de.dlr.ivf.tapas.person.TPS_Car.isRestricted(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isTrue(), de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.util.parameters.ParamValue.MAX_SYSTEM_SPEED, de.dlr.ivf.tapas.util.parameters.ParamValue.MAX_TRIES_LOCATION_SELECTION, de.dlr.ivf.tapas.util.parameters.SimulationType.SCENARIO, de.dlr.ivf.tapas.persistence.TPS_RegionResultSet.size(), de.dlr.ivf.tapas.constants.TPS_ActivityConstant.TPS_ActivityCodeType.TAPAS, de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.WALK, and de.dlr.ivf.tapas.constants.TPS_ActivityConstant.TPS_ActivityCodeType.ZBE.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/loc/TPS_MultipleTAZRepresentant.java