TAPAS: de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator Class Reference
de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator Class Reference
Classes
class Household
class PTLine
enum PTLineType
class PTStop
Public Member Functions
void calcWeights (PTLineType minLine)
void loadHouseholds (String table, String key)
void loadPTStops (String stopsTable, String tazTable, int bufferSize)
void printPTStatisticsPerTAZ ()
void printPTStopsPerTAZ ()
void printTAZPerPTStop ()
void savePTStopsPerTAZToFile (String filename, double detourFactor, int maxStops)
void updateWeights (String table)
Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_BasicConnectionClass ()
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass)
TPS_BasicConnectionClass (String loginFile)
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass, String loginFile)
boolean checkMatrixName (String matrixName)
TPS_ParameterClass getParameters ()
String readParameter (String simKey, String paramKey)
void storeInDB (String matrixName, double[][] matrix, int decimalPlaces)
Static Public Member Functions
static void main (String[] args)
Static Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
static double[][] array1Dto2D (Integer[] matrixVal)
static double[][] array1Dto2D (int[] matrixVal)
static File getRuntimeFile (boolean forceNewFile)
static File getRuntimeFile (String propertyFile, boolean forceNewFile)
static File getRuntimeFile ()
static File getRuntimeFile (String propertyFile)
static int[][] intArray1Dto2D (int[] matrixVal)
static String matrixToSQLArray (double[][] array, int decimalPlaces)
static StringWriter matrixToStringWriterSQL (double[][] array, int decimalPlaces)
Public Attributes
Map< Integer, List< PTStop > > taz2StopMap = new HashMap<>()
Map< Integer, List< Household > > taz2HouseholdMap = new HashMap<>()
Map< String, List< Integer > > stops2TAZMap = new HashMap<>()
Additional Inherited Members
Protected Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
void finalize ()
Protected Attributes inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_DB_Connector dbCon = null
TPS_ParameterClass parameterClass
Detailed Description
Definition at line 22 of file TPS_PTStopWeightCalculator.java.
Member Function Documentation
calcWeights()
void de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.calcWeights (PTLineType minLine)
This method takes all households and searches for the closest pt stop in the same taz. Then it adds the number of persons to this pt stop.
Definition at line 52 of file TPS_PTStopWeightCalculator.java.
References de.dlr.ivf.tapas.util.TPS_Geometrics.getDistance().
Referenced by de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.main().
loadHouseholds()
void de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.loadHouseholds (String table, String key)
This methods loads the households from the given table with the given key and groups them into tazes.
Parameters
table
key
Definition at line 91 of file TPS_PTStopWeightCalculator.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), and de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.taz2HouseholdMap.
Referenced by de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.main().
loadPTStops()
void de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.loadPTStops (String stopsTable, String tazTable, int bufferSize)
Load the pt stops from the visum export. This method loads the data from the given table. It converts the coordinates and prepares the lines stopping at this stop. Finally, it adds all stops to a list of pt stops for each taz in the taz2StopMap membervariable.
Parameters
stopsTable
Definition at line 129 of file TPS_PTStopWeightCalculator.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.stops2TAZMap, and de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.taz2StopMap.
Referenced by de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.main().
main()
static void de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.main (String[] args) static
Definition at line 27 of file TPS_PTStopWeightCalculator.java.
References de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.PTLineType.BRT, de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.calcWeights(), de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.loadHouseholds(), de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.loadPTStops(), de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.printPTStatisticsPerTAZ(), de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.savePTStopsPerTAZToFile(), de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.PTLineType.Unknown, and de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.updateWeights().
printPTStatisticsPerTAZ()
void de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.printPTStatisticsPerTAZ ()
Definition at line 195 of file TPS_PTStopWeightCalculator.java.
References de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.PTLineType.BRT, de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.PTLineType.S, de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.PTLineType.Train, de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.PTLineType.Tram, and de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.PTLineType.U.
Referenced by de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.main().
printPTStopsPerTAZ()
void de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.printPTStopsPerTAZ ()
Prints all stops per TAZ on screen
Definition at line 293 of file TPS_PTStopWeightCalculator.java.
printTAZPerPTStop()
void de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.printTAZPerPTStop ()
Definition at line 312 of file TPS_PTStopWeightCalculator.java.
savePTStopsPerTAZToFile()
void de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.savePTStopsPerTAZToFile (String filename, double detourFactor, int maxStops)
Prints all stops per TAZ on screen
Definition at line 327 of file TPS_PTStopWeightCalculator.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.main().
updateWeights()
void de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.updateWeights (String table)
Definition at line 359 of file TPS_PTStopWeightCalculator.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection().
Referenced by de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.main().
Member Data Documentation
stops2TAZMap
Map<String, List<Integer> > de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.stops2TAZMap = new HashMap<>()
Definition at line 25 of file TPS_PTStopWeightCalculator.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.loadPTStops().
taz2HouseholdMap
Map<Integer, List<Household> > de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.taz2HouseholdMap = new HashMap<>()
Definition at line 24 of file TPS_PTStopWeightCalculator.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.loadHouseholds().
taz2StopMap
Map<Integer, List<PTStop> > de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.taz2StopMap = new HashMap<>()
Definition at line 23 of file TPS_PTStopWeightCalculator.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.loadPTStops().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/TPS_PTStopWeightCalculator.java