TAPAS: de.dlr.ivf.tapas.util.Pool< T > Class Template Reference
de.dlr.ivf.tapas.util.Pool< T > Class Template Reference
Classes
interface Instantiator
Public Member Functions
Pool (int initialSize, final Class< T > clazz)
Pool (int initialSize, Instantiator< T > clazz)
synchronized T pop ()
synchronized void push (T object)
synchronized void setMaxInitialSizeFactor (int factor)
Private Member Functions
void decrease ()
void increase ()
Private Attributes
final Stack< T > stack
final int initialSize
final Instantiator< T > clazz
int factor
Detailed Description
This class represents a pool, where you can push and pop items without regarding the instantiation or deletion of instances.
Parameters
<T> instance type of the pool
Author
mark_ma
Definition at line 21 of file Pool.java.
Constructor & Destructor Documentation
Pool() [1/2]
de.dlr.ivf.tapas.util.Pool< T >.Pool (int initialSize, final Class< T > clazz)
The constructor initialises the pool with the initial size of instances of T. The class of T is used to instaniate new instances. This constructor can be used if there exists a default constructor of T. Otherwise you have to build a Instantiator for the instances of T.
Parameters
initialSize initial pool size
clazz class of the instances in the pool
Definition at line 48 of file Pool.java.
References de.dlr.ivf.tapas.util.Pool< T >.clazz, and de.dlr.ivf.tapas.util.Pool< T >.initialSize.
Pool() [2/2]
de.dlr.ivf.tapas.util.Pool< T >.Pool (int initialSize, Instantiator< T > clazz)
Definition at line 56 of file Pool.java.
References de.dlr.ivf.tapas.util.Pool< T >.clazz, de.dlr.ivf.tapas.util.Pool< T >.increase(), and de.dlr.ivf.tapas.util.Pool< T >.initialSize.
Member Function Documentation
decrease()
void de.dlr.ivf.tapas.util.Pool< T >.decrease () private
Decreases the pool size about the initial size if possible
Definition at line 67 of file Pool.java.
References de.dlr.ivf.tapas.util.Pool< T >.stack.
Referenced by de.dlr.ivf.tapas.util.Pool< T >.push().
increase()
void de.dlr.ivf.tapas.util.Pool< T >.increase () private
Increases the pool about the initial size. It uses the default constructor to build instances of T by using the newInstance() method of the given Instantiator.
Definition at line 77 of file Pool.java.
References de.dlr.ivf.tapas.util.Pool< T >.initialSize, and de.dlr.ivf.tapas.util.Pool< T >.Instantiator< T >.newInstance().
Referenced by de.dlr.ivf.tapas.util.Pool< T >.Pool(), and de.dlr.ivf.tapas.util.Pool< T >.pop().
pop()
synchronized T de.dlr.ivf.tapas.util.Pool< T >.pop ()
Removes and returns one instance of T. If the pool is empty it is increased about the initial size.
Returns
instance of T
Definition at line 92 of file Pool.java.
References de.dlr.ivf.tapas.util.Pool< T >.increase().
push()
synchronized void de.dlr.ivf.tapas.util.Pool< T >.push (T object)
Adds one instance of T. If the pool size is too big it is decreased automatically. The border is the initial size multiplied with the max initial size factor.
Parameters
object instance of T
Definition at line 105 of file Pool.java.
References de.dlr.ivf.tapas.util.Pool< T >.decrease(), de.dlr.ivf.tapas.util.Pool< T >.factor, de.dlr.ivf.tapas.util.Pool< T >.initialSize, and de.dlr.ivf.tapas.util.Pool< T >.stack.
setMaxInitialSizeFactor()
synchronized void de.dlr.ivf.tapas.util.Pool< T >.setMaxInitialSizeFactor (int factor)
Sets the maximum initial size factor of the pool.
initial size = 12;
max initial size factor = 3;
max pool size = 3 * 12 = 36
Parameters
factor maximum initial size factor
Definition at line 121 of file Pool.java.
References de.dlr.ivf.tapas.util.Pool< T >.factor.
Member Data Documentation
clazz
final Instantiator<T> de.dlr.ivf.tapas.util.Pool< T >.clazz private
Instantiator of the instances of T
Definition at line 34 of file Pool.java.
Referenced by de.dlr.ivf.tapas.util.Pool< T >.Pool().
factor
int de.dlr.ivf.tapas.util.Pool< T >.factor private
maximum initial size factor
Definition at line 38 of file Pool.java.
Referenced by de.dlr.ivf.tapas.util.Pool< T >.push(), and de.dlr.ivf.tapas.util.Pool< T >.setMaxInitialSizeFactor().
initialSize
final int de.dlr.ivf.tapas.util.Pool< T >.initialSize private
initial pool size
Definition at line 30 of file Pool.java.
Referenced by de.dlr.ivf.tapas.util.Pool< T >.increase(), de.dlr.ivf.tapas.util.Pool< T >.Pool(), and de.dlr.ivf.tapas.util.Pool< T >.push().
stack
final Stack<T> de.dlr.ivf.tapas.util.Pool< T >.stack private
Internal collection to store the instances of T.
Definition at line 26 of file Pool.java.
Referenced by de.dlr.ivf.tapas.util.Pool< T >.decrease(), and de.dlr.ivf.tapas.util.Pool< T >.push().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/util/Pool.java