TAPAS: de.dlr.ivf.tapas.runtime.util.DaemonControlProperties Class Reference
de.dlr.ivf.tapas.runtime.util.DaemonControlProperties Class Reference
Inherits de.dlr.ivf.tapas.runtime.util.ControlProperties.
Classes
enum DaemonControlPropKey
Public Member Functions
DaemonControlProperties (File file)
String get (DaemonControlPropKey key)
void set (DaemonControlPropKey key, String value)
Detailed Description
Definition at line 19 of file DaemonControlProperties.java.
Constructor & Destructor Documentation
DaemonControlProperties()
de.dlr.ivf.tapas.runtime.util.DaemonControlProperties.DaemonControlProperties (File file)
The constructor builds the properties object and fills it with the key value pairs from the file.
Parameters
file the daemon.properties file
Definition at line 25 of file DaemonControlProperties.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, and de.dlr.ivf.tapas.log.TPS_Logger.log().
Member Function Documentation
get()
String de.dlr.ivf.tapas.runtime.util.DaemonControlProperties.get (DaemonControlPropKey key)
Parameters
key simulation property key
Returns
value corresponding to the given key
Definition at line 55 of file DaemonControlProperties.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationDaemon.SimulationDaemon(), de.dlr.ivf.tapas.runtime.server.SimulationServer.SimulationServer(), and de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.SumoDaemon().
set()
void de.dlr.ivf.tapas.runtime.util.DaemonControlProperties.set (DaemonControlPropKey key, String value)
Sets a key value pair for this property.
Parameters
key simulation property key
value simulation property value
Definition at line 65 of file DaemonControlProperties.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationDaemon.SimulationDaemon(), and de.dlr.ivf.tapas.runtime.server.SimulationServer.SimulationServer().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/runtime/util/DaemonControlProperties.java