TAPAS: de.dlr.ivf.tapas.plan.TPS_PlanEnvironment Class Reference
de.dlr.ivf.tapas.plan.TPS_PlanEnvironment Class Reference
Public Member Functions
TPS_PlanEnvironment (TPS_Person person)
void addPlan (TPS_Plan plan)
void dismissScheme ()
TPS_Plan getBestPlan ()
TPS_Plan getLastPlan ()
int getNumberOfFeasiblePlans ()
int getNumberOfRejectedPlans ()
TPS_Person getPerson ()
List< TPS_Plan > getPlans ()
boolean isPlanAccepted (TPS_Plan plan)
Private Attributes
final TPS_Person person
The person with this plan environment.
final List< TPS_Plan > plans
All plans which were generated for this person.
TPS_PlanAcceptance acceptance = null
Detailed Description
This class provides the plan environment for the simulation of one person. It stores all fix locations which were selected for this person. Also there are all plans stored and after generating some of them you can choose the best plan you have generated.
Author
mark_ma
Definition at line 28 of file TPS_PlanEnvironment.java.
Constructor & Destructor Documentation
TPS_PlanEnvironment()
de.dlr.ivf.tapas.plan.TPS_PlanEnvironment.TPS_PlanEnvironment (TPS_Person person)
Constructor
Parameters
person The person that gets this plan environment
Definition at line 45 of file TPS_PlanEnvironment.java.
Member Function Documentation
addPlan()
void de.dlr.ivf.tapas.plan.TPS_PlanEnvironment.addPlan (TPS_Plan plan)
This method adds a plan to all stored plans in this environment
Parameters
plan The plan to add
Definition at line 57 of file TPS_PlanEnvironment.java.
References de.dlr.ivf.tapas.plan.TPS_Plan.isPlanAccepted().
Referenced by de.dlr.ivf.tapas.person.TPS_Worker.createPersonPlans().
dismissScheme()
void de.dlr.ivf.tapas.plan.TPS_PlanEnvironment.dismissScheme ()
Definition at line 66 of file TPS_PlanEnvironment.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Worker.createPersonPlans().
getBestPlan()
TPS_Plan de.dlr.ivf.tapas.plan.TPS_PlanEnvironment.getBestPlan ()
Returns
best plan of all stored
Definition at line 73 of file TPS_PlanEnvironment.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Worker.processHousehold().
getLastPlan()
TPS_Plan de.dlr.ivf.tapas.plan.TPS_PlanEnvironment.getLastPlan ()
Returns
last added plan
Definition at line 127 of file TPS_PlanEnvironment.java.
getNumberOfFeasiblePlans()
int de.dlr.ivf.tapas.plan.TPS_PlanEnvironment.getNumberOfFeasiblePlans ()
Definition at line 131 of file TPS_PlanEnvironment.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Worker.createPersonPlans().
getNumberOfRejectedPlans()
int de.dlr.ivf.tapas.plan.TPS_PlanEnvironment.getNumberOfRejectedPlans ()
Definition at line 135 of file TPS_PlanEnvironment.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Worker.createPersonPlans(), and de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes().
getPerson()
TPS_Person de.dlr.ivf.tapas.plan.TPS_PlanEnvironment.getPerson ()
Returns
the person corresponding to this plan environment
Definition at line 142 of file TPS_PlanEnvironment.java.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.createOutput(), de.dlr.ivf.tapas.person.TPS_Worker.createPersonPlans(), de.dlr.ivf.tapas.plan.TPS_Plan.getPerson(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessMode.getTravelTime(), de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes(), and de.dlr.ivf.tapas.plan.TPS_Plan.writeOutputStream().
getPlans()
List<TPS_Plan> de.dlr.ivf.tapas.plan.TPS_PlanEnvironment.getPlans ()
Returns
all plans which were generated for this person
Definition at line 149 of file TPS_PlanEnvironment.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Worker.processHousehold().
isPlanAccepted()
boolean de.dlr.ivf.tapas.plan.TPS_PlanEnvironment.isPlanAccepted (TPS_Plan plan)
Definition at line 153 of file TPS_PlanEnvironment.java.
References de.dlr.ivf.tapas.plan.acceptance.TPS_PlanAcceptance.isPlanAccepted().
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.isPlanAccepted().
Member Data Documentation
acceptance
TPS_PlanAcceptance de.dlr.ivf.tapas.plan.TPS_PlanEnvironment.acceptance = null private
Definition at line 37 of file TPS_PlanEnvironment.java.
person
final TPS_Person de.dlr.ivf.tapas.plan.TPS_PlanEnvironment.person private
The person with this plan environment.
Definition at line 33 of file TPS_PlanEnvironment.java.
plans
final List<TPS_Plan> de.dlr.ivf.tapas.plan.TPS_PlanEnvironment.plans private
All plans which were generated for this person.
Definition at line 35 of file TPS_PlanEnvironment.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/plan/TPS_PlanEnvironment.java