TAPAS: de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate Class Reference
de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate Class Reference
Public Member Functions
CruisingSpeedCalculate (CruisingSpeedCalcData calcData)
double[][] calcDistance (String tazTable, String matricesTable, String modus, String terrain, boolean indirectWayFactor)
double[][] calcDistance (String modus)
double[] getFactors ()
void setFactors (double[] factors)
double getIndirectWayFactor (String modus, String terrain, double distance)
double[][] getTravelTime (String modus)
void setFactors (double factor0, double factor1, double factor2, double factor3, double factor4)
Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_BasicConnectionClass ()
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass)
TPS_BasicConnectionClass (String loginFile)
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass, String loginFile)
boolean checkMatrixName (String matrixName)
TPS_ParameterClass getParameters ()
String readParameter (String simKey, String paramKey)
void storeInDB (String matrixName, double[][] matrix, int decimalPlaces)
Private Member Functions
void init ()
Private Attributes
final Map< String, Double > correctionFactorModus = new HashMap<>()
final Map< String, Double > correctionFactorTerrain = new HashMap<>()
final CruisingSpeedCalcData calcData
double[][] travelTime = null
double[][] beeLine = null
double[][] indirectWayFactor = null
double[] factors = {1.0, 50.0, 2.0, 1.0, 0.60}
Additional Inherited Members
Static Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
static double[][] array1Dto2D (Integer[] matrixVal)
static double[][] array1Dto2D (int[] matrixVal)
static File getRuntimeFile (boolean forceNewFile)
static File getRuntimeFile (String propertyFile, boolean forceNewFile)
static File getRuntimeFile ()
static File getRuntimeFile (String propertyFile)
static int[][] intArray1Dto2D (int[] matrixVal)
static String matrixToSQLArray (double[][] array, int decimalPlaces)
static StringWriter matrixToStringWriterSQL (double[][] array, int decimalPlaces)
Protected Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
void finalize ()
Protected Attributes inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_DB_Connector dbCon = null
TPS_ParameterClass parameterClass
Detailed Description
Definition at line 19 of file CruisingSpeedCalculate.java.
Constructor & Destructor Documentation
CruisingSpeedCalculate()
de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.CruisingSpeedCalculate (CruisingSpeedCalcData calcData)
Definition at line 37 of file CruisingSpeedCalculate.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.calcData, and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.init().
Member Function Documentation
calcDistance() [1/2]
double [][] de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.calcDistance (String modus)
Definition at line 61 of file CruisingSpeedCalculate.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.beeLine, de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), de.dlr.ivf.tapas.util.TPS_Geometrics.getDistance(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.getIndirectWayFactor(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.getTazTable(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.getTerrain(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.indirectWayFactor, de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.isIndirectWayFactor(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.travelTime.
calcDistance() [2/2]
double [][] de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.calcDistance (String tazTable, String matricesTable, String modus, String terrain, boolean indirectWayFactor)
needed for validate
Parameters
tazTable
matricesTable
modus
terrain
indirectWayFactor
Returns
Definition at line 52 of file CruisingSpeedCalculate.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.indirectWayFactor, de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.setIndirectWayFactor(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.setMatricesTable(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.setTazTable(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.setTerrain().
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.readData(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.start().
getFactors()
double [] de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.getFactors ()
Definition at line 116 of file CruisingSpeedCalculate.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.factors.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.readData().
getIndirectWayFactor()
double de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.getIndirectWayFactor (String modus, String terrain, double distance)
Parameters
modus PT, MIV, BIKE, WALK
Returns
Definition at line 128 of file CruisingSpeedCalculate.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.factors.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.calcDistance().
getTravelTime()
double [][] de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.getTravelTime (String modus)
Definition at line 136 of file CruisingSpeedCalculate.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.beeLine, de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalcData.getTravelTimeParameter(), de.dlr.ivf.tapas.tools.matrixMap.Modus.getValue(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.travelTime.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.start().
init()
void de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.init () private
Definition at line 161 of file CruisingSpeedCalculate.java.
References de.dlr.ivf.tapas.tools.matrixMap.Modus.BIKE, de.dlr.ivf.tapas.tools.matrixMap.Terrain.CITY, de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.correctionFactorModus, de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.correctionFactorTerrain, de.dlr.ivf.tapas.tools.matrixMap.Terrain.DOWNS, de.dlr.ivf.tapas.tools.matrixMap.Modus.MIV, de.dlr.ivf.tapas.tools.matrixMap.Terrain.MOUNTAINOUS, de.dlr.ivf.tapas.tools.matrixMap.Terrain.PLAIN, de.dlr.ivf.tapas.tools.matrixMap.Modus.PT, de.dlr.ivf.tapas.tools.matrixMap.Terrain.STOPS, and de.dlr.ivf.tapas.tools.matrixMap.Modus.WALK.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.CruisingSpeedCalculate().
setFactors() [1/2]
void de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.setFactors (double factor0, double factor1, double factor2, double factor3, double factor4)
Definition at line 176 of file CruisingSpeedCalculate.java.
setFactors() [2/2]
void de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.setFactors (double[] factors)
Definition at line 120 of file CruisingSpeedCalculate.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.factors.
Member Data Documentation
beeLine
double [][] de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.beeLine = null private
Definition at line 25 of file CruisingSpeedCalculate.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.calcDistance(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.getTravelTime().
calcData
final CruisingSpeedCalcData de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.calcData private
Definition at line 23 of file CruisingSpeedCalculate.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.CruisingSpeedCalculate().
correctionFactorModus
final Map<String, Double> de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.correctionFactorModus = new HashMap<>() private
Definition at line 20 of file CruisingSpeedCalculate.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.init().
correctionFactorTerrain
final Map<String, Double> de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.correctionFactorTerrain = new HashMap<>() private
Definition at line 21 of file CruisingSpeedCalculate.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.init().
factors
double [] de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.factors = {1.0, 50.0, 2.0, 1.0, 0.60} private
(factors[0]/log10(factors[1]*(x^factors[2])+factors[3]))+factors4+1,1
Definition at line 35 of file CruisingSpeedCalculate.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.getFactors(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.getIndirectWayFactor(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.setFactors().
indirectWayFactor
double [][] de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.indirectWayFactor = null private
Definition at line 26 of file CruisingSpeedCalculate.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.calcDistance().
travelTime
double [][] de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.travelTime = null private
Definition at line 24 of file CruisingSpeedCalculate.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.calcDistance(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.getTravelTime().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/matrixMap/CruisingSpeedCalculate.java