TAPAS: de.dlr.ivf.tapas.scheme.TPS_Episode Class Reference
de.dlr.ivf.tapas.scheme.TPS_Episode Class Reference abstract
Public Member Functions
TPS_Episode (int id, TPS_ActivityConstant actCode, int start, int duration, double startEarlier, double startLater, double shorterDuration, double longerDuration, TPS_ParameterClass parameterClass)
TPS_Episode clone ()
TPS_ActivityConstant getActCode ()
void setActCode (TPS_ActivityConstant actCode)
double getAlphaEarlier ()
void setAlphaEarlier (double alphaEarlier)
double getAlphaLater ()
void setAlphaLater (double alphaLater)
double getBetaLonger ()
void setBetaLonger (double betaLonger)
double getBetaShorter ()
void setBetaShorter (double betaShorter)
int getId ()
double getLongerDuration ()
void setLongerDuration (double longerDuration)
int getOriginalDuration ()
void setOriginalDuration (int originalDuration)
double getOriginalEnd ()
int getOriginalStart ()
void setOriginalStart (int originalStart)
TPS_SchemePart getSchemePart ()
double getShorterDuration ()
void setShorterDuration (double shorterDuration)
double getStartEarlier ()
void setStartEarlier (double startEarlier)
double getStartLater ()
void setStartLater (double startLater)
int hashCode ()
boolean isLonger (TPS_Episode episode)
abstract boolean isStay ()
boolean isTrip ()
String toString ()
String toString (String prefix)
Public Attributes
boolean isHomePart
Variable which determines, if this part is a HomePart.
int tourNumber
tour number
Private Attributes
final int id
id of the episode
TPS_ActivityConstant actCode
activity code of the episode
double alphaEarlier
shift parameter for balancing episode starts: earlier
double alphaLater
shift parameter for balancing episode starts: later
double betaLonger
stretch parameter for balancing episode durations: longer
double betaShorter
stretch parameter for balancing episode durations: shorter
double longerDuration
allowed longer duration of the episode in seconds
int originalDuration
original reported duration of the episode in seconds
int originalStart
original reported start time of the episode in minutes
TPS_SchemePart schemePart
Each episode is part of a scheme part, this member is the link to the corresponding scheme part.
double shorterDuration
allowed shorter duration of the episode in seconds
double startEarlier
allowed earlier start of the episode in seconds
double startLater
allowed later start of the episode in seconds
final TPS_ParameterClass parameterClass
Detailed Description
This is the basic class for stays and trips. It stores the common member variables of both types of episodes and is extended by TPS_Stay and TPS_Trip
Author
mark_ma
Definition at line 25 of file TPS_Episode.java.
Constructor & Destructor Documentation
TPS_Episode()
de.dlr.ivf.tapas.scheme.TPS_Episode.TPS_Episode (int id, TPS_ActivityConstant actCode, int start, int duration, double startEarlier, double startLater, double shorterDuration, double longerDuration, TPS_ParameterClass parameterClass)
Constructor
Parameters
id the id for this episode
actCode the activity code according to the documentation
start the original start for this episode in seconds
duration the original duration for this episode in seconds
startEarlier the allowed earlier start for this episode in seconds
startLater the allowed later start for this episode in seconds
shorterDuration the allowed shorter duration of this episode in seconds
longerDuration the allowed longer duration of this episode in seconds
parameterClass parameter class reference
Definition at line 71 of file TPS_Episode.java.
References de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getDoubleValue(), de.dlr.ivf.tapas.util.parameters.ParamValue.SCALE_SHIFT, and de.dlr.ivf.tapas.util.parameters.ParamValue.SCALE_STRETCH.
Member Function Documentation
clone()
TPS_Episode de.dlr.ivf.tapas.scheme.TPS_Episode.clone ()
Definition at line 120 of file TPS_Episode.java.
References de.dlr.ivf.tapas.scheme.TPS_Episode.isHomePart, and de.dlr.ivf.tapas.scheme.TPS_Episode.tourNumber.
Referenced by de.dlr.ivf.tapas.scheme.TPS_Scheme.clone().
getActCode()
TPS_ActivityConstant de.dlr.ivf.tapas.scheme.TPS_Episode.getActCode ()
Returns the activity code of the episode
Returns
activity code
Definition at line 140 of file TPS_Episode.java.
Referenced by de.dlr.ivf.tapas.scheme.TPS_TourPart.addStay(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.batchStoreTrips(), de.dlr.ivf.tapas.plan.TPS_Plan.createOutput(), de.dlr.ivf.tapas.loc.TPS_FocusPointModel.getFocusPoint(), de.dlr.ivf.tapas.loc.TPS_MultipleTAZRepresentant.getLocationRepresentatives(), de.dlr.ivf.tapas.mode.TPS_ModeSet.getModeDistribution(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.getModeLogSum(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessMode.getTravelTime(), de.dlr.ivf.tapas.loc.TPS_SelectWithSingleAccessMode.getTravelTime(), de.dlr.ivf.tapas.plan.TPS_LocatedStay.selectLocation(), de.dlr.ivf.tapas.loc.TPS_Region.selectLocation(), de.dlr.ivf.tapas.loc.TPS_SelectLocationWeightBased.selectLocationFromChoiceSet(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.selectLocationFromChoiceSet(), and de.dlr.ivf.tapas.plan.TPS_Plan.writeOutputStream().
getAlphaEarlier()
double de.dlr.ivf.tapas.scheme.TPS_Episode.getAlphaEarlier ()
Returns
alpha earlier
Definition at line 157 of file TPS_Episode.java.
getAlphaLater()
double de.dlr.ivf.tapas.scheme.TPS_Episode.getAlphaLater ()
Returns
alpha later
Definition at line 175 of file TPS_Episode.java.
getBetaLonger()
double de.dlr.ivf.tapas.scheme.TPS_Episode.getBetaLonger ()
Returns
beta longer
Definition at line 188 of file TPS_Episode.java.
getBetaShorter()
double de.dlr.ivf.tapas.scheme.TPS_Episode.getBetaShorter ()
Returns
beta shorter
Definition at line 201 of file TPS_Episode.java.
getId()
int de.dlr.ivf.tapas.scheme.TPS_Episode.getId ()
Returns the id of the episode
Returns
the episodes' id
Definition at line 215 of file TPS_Episode.java.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes(), and de.dlr.ivf.tapas.scheme.TPS_TourPart.TPS_StayHierarchy.toString().
getLongerDuration()
double de.dlr.ivf.tapas.scheme.TPS_Episode.getLongerDuration ()
Returns
Get the longer allowed duration
Definition at line 223 of file TPS_Episode.java.
getOriginalDuration()
int de.dlr.ivf.tapas.scheme.TPS_Episode.getOriginalDuration ()
Returns
Get the original duration in minutes after midnight
Definition at line 235 of file TPS_Episode.java.
Referenced by de.dlr.ivf.tapas.scheme.TPS_Scheme.addEpisode(), de.dlr.ivf.tapas.scheme.TPS_TourPart.addTrip(), de.dlr.ivf.tapas.scheme.TPS_Stay.compareTo(), de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.init(), de.dlr.ivf.tapas.scheme.TPS_Episode.isLonger(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readSchemeSet(), de.dlr.ivf.tapas.plan.TPS_Plan.reset(), de.dlr.ivf.tapas.loc.TPS_SelectLocationWeightBased.selectLocationFromChoiceSet(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.selectLocationFromChoiceSet(), and de.dlr.ivf.tapas.mode.TPS_ModeSet.selectMode().
getOriginalEnd()
double de.dlr.ivf.tapas.scheme.TPS_Episode.getOriginalEnd ()
Returns
Get the original end in minutes after midnight
Definition at line 251 of file TPS_Episode.java.
Referenced by de.dlr.ivf.tapas.scheme.TPS_Scheme.addEpisode(), de.dlr.ivf.tapas.scheme.TPS_SchemePart.addEpisode(), de.dlr.ivf.tapas.scheme.TPS_TourPart.addStay(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessMode.getTravelTime(), and de.dlr.ivf.tapas.loc.TPS_SelectWithSingleAccessMode.getTravelTime().
getOriginalStart()
int de.dlr.ivf.tapas.scheme.TPS_Episode.getOriginalStart ()
Returns
Get the original start in minutes after midnight
Definition at line 258 of file TPS_Episode.java.
Referenced by de.dlr.ivf.tapas.scheme.TPS_SchemePart.addEpisode(), de.dlr.ivf.tapas.scheme.TPS_TourPart.addStay(), de.dlr.ivf.tapas.plan.TPS_Plan.calcPlanFeasiblity(), de.dlr.ivf.tapas.scheme.TPS_Stay.compareTo(), de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.init(), de.dlr.ivf.tapas.scheme.TPS_TourPart.initHierarchy(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readSchemeSet(), de.dlr.ivf.tapas.loc.TPS_SelectLocationWeightBased.selectLocationFromChoiceSet(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.selectLocationFromChoiceSet(), de.dlr.ivf.tapas.mode.TPS_ModeSet.selectMode(), and de.dlr.ivf.tapas.plan.TPS_Plan.TPS_Plan().
getSchemePart()
TPS_SchemePart de.dlr.ivf.tapas.scheme.TPS_Episode.getSchemePart ()
Returns
Get the associated TPS_SchemePart
Definition at line 274 of file TPS_Episode.java.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.createOutput(), de.dlr.ivf.tapas.plan.TPS_Plan.getHierarchizedPreviousStay(), de.dlr.ivf.tapas.loc.TPS_MultipleTAZRepresentant.getLocationRepresentatives(), de.dlr.ivf.tapas.plan.TPS_Plan.getPreviousLocatedStay(), de.dlr.ivf.tapas.plan.TPS_LocatedStay.selectLocation(), de.dlr.ivf.tapas.loc.TPS_SelectLocationWeightBased.selectLocationFromChoiceSet(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.selectLocationFromChoiceSet(), de.dlr.ivf.tapas.mode.TPS_ModeSet.selectMode(), and de.dlr.ivf.tapas.plan.TPS_Plan.writeOutputStream().
getShorterDuration()
double de.dlr.ivf.tapas.scheme.TPS_Episode.getShorterDuration ()
Returns
Get the shortest allowed duration
Definition at line 291 of file TPS_Episode.java.
getStartEarlier()
double de.dlr.ivf.tapas.scheme.TPS_Episode.getStartEarlier ()
Returns
Get the earliest possible start
Definition at line 304 of file TPS_Episode.java.
getStartLater()
double de.dlr.ivf.tapas.scheme.TPS_Episode.getStartLater ()
Returns
Get the latest possible start
Definition at line 317 of file TPS_Episode.java.
hashCode()
int de.dlr.ivf.tapas.scheme.TPS_Episode.hashCode ()
Definition at line 332 of file TPS_Episode.java.
isLonger()
boolean de.dlr.ivf.tapas.scheme.TPS_Episode.isLonger (TPS_Episode episode)
Comparing two episodes
Parameters
episode The episode to compare
Returns
true if this original duration is longer than the episode's one
Definition at line 342 of file TPS_Episode.java.
References de.dlr.ivf.tapas.scheme.TPS_Episode.getOriginalDuration().
isStay()
abstract boolean de.dlr.ivf.tapas.scheme.TPS_Episode.isStay () abstract
Returns
true if this is a TPS_Stay
Reimplemented in de.dlr.ivf.tapas.scheme.TPS_Trip, and de.dlr.ivf.tapas.scheme.TPS_Stay.
Referenced by de.dlr.ivf.tapas.scheme.TPS_Scheme.addEpisode(), de.dlr.ivf.tapas.plan.TPS_Plan.getAdaptedEpisode(), de.dlr.ivf.tapas.scheme.TPS_SchemePart.getNextStay(), de.dlr.ivf.tapas.scheme.TPS_SchemePart.getPreviousStay(), de.dlr.ivf.tapas.scheme.TPS_SchemePart.StayIterator.next(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readSchemeSet().
isTrip()
boolean de.dlr.ivf.tapas.scheme.TPS_Episode.isTrip ()
Returns
true if this is a TPS_Trip
Definition at line 354 of file TPS_Episode.java.
Referenced by de.dlr.ivf.tapas.scheme.TPS_TourPart.TripIterator.next().
setActCode()
void de.dlr.ivf.tapas.scheme.TPS_Episode.setActCode (TPS_ActivityConstant actCode)
Setter for the activity code
Parameters
actCode The activity code
Reimplemented in de.dlr.ivf.tapas.scheme.TPS_Stay.
Definition at line 149 of file TPS_Episode.java.
setAlphaEarlier()
void de.dlr.ivf.tapas.scheme.TPS_Episode.setAlphaEarlier (double alphaEarlier)
Set the alpha earlier factor. Not used anymore
Parameters
alphaEarlier
Definition at line 167 of file TPS_Episode.java.
setAlphaLater()
void de.dlr.ivf.tapas.scheme.TPS_Episode.setAlphaLater (double alphaLater)
Definition at line 180 of file TPS_Episode.java.
setBetaLonger()
void de.dlr.ivf.tapas.scheme.TPS_Episode.setBetaLonger (double betaLonger)
Definition at line 193 of file TPS_Episode.java.
setBetaShorter()
void de.dlr.ivf.tapas.scheme.TPS_Episode.setBetaShorter (double betaShorter)
Definition at line 206 of file TPS_Episode.java.
setLongerDuration()
void de.dlr.ivf.tapas.scheme.TPS_Episode.setLongerDuration (double longerDuration)
Definition at line 228 of file TPS_Episode.java.
setOriginalDuration()
void de.dlr.ivf.tapas.scheme.TPS_Episode.setOriginalDuration (int originalDuration)
Method to set the original duration in minutes after midnight
Parameters
originalDuration
Definition at line 244 of file TPS_Episode.java.
Referenced by de.dlr.ivf.tapas.scheme.TPS_Scheme.addEpisode(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readSchemeSet().
setOriginalStart()
void de.dlr.ivf.tapas.scheme.TPS_Episode.setOriginalStart (int originalStart)
Method to set the original start in minutes after midnight
Parameters
originalStart
Definition at line 267 of file TPS_Episode.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readSchemeSet().
setShorterDuration()
void de.dlr.ivf.tapas.scheme.TPS_Episode.setShorterDuration (double shorterDuration)
Definition at line 296 of file TPS_Episode.java.
setStartEarlier()
void de.dlr.ivf.tapas.scheme.TPS_Episode.setStartEarlier (double startEarlier)
Definition at line 309 of file TPS_Episode.java.
setStartLater()
void de.dlr.ivf.tapas.scheme.TPS_Episode.setStartLater (double startLater)
Definition at line 322 of file TPS_Episode.java.
toString() [1/2]
String de.dlr.ivf.tapas.scheme.TPS_Episode.toString ()
Definition at line 364 of file TPS_Episode.java.
Referenced by de.dlr.ivf.tapas.scheme.TPS_Scheme.addEpisode(), de.dlr.ivf.tapas.scheme.TPS_HomePart.toString(), and de.dlr.ivf.tapas.scheme.TPS_TourPart.toString().
toString() [2/2]
String de.dlr.ivf.tapas.scheme.TPS_Episode.toString (String prefix)
This method should print the object naturally with the given prefix.
Parameters
prefix
Returns
prefix + toString();
Implements de.dlr.ivf.tapas.util.ExtendedWritable.
Reimplemented in de.dlr.ivf.tapas.scheme.TPS_Stay.
Definition at line 373 of file TPS_Episode.java.
References de.dlr.ivf.tapas.constants.TPS_ActivityConstant.TPS_ActivityCodeType.ZBE.
Member Data Documentation
actCode
TPS_ActivityConstant de.dlr.ivf.tapas.scheme.TPS_Episode.actCode private
activity code of the episode
Definition at line 33 of file TPS_Episode.java.
alphaEarlier
double de.dlr.ivf.tapas.scheme.TPS_Episode.alphaEarlier private
shift parameter for balancing episode starts: earlier
Definition at line 35 of file TPS_Episode.java.
alphaLater
double de.dlr.ivf.tapas.scheme.TPS_Episode.alphaLater private
shift parameter for balancing episode starts: later
Definition at line 37 of file TPS_Episode.java.
betaLonger
double de.dlr.ivf.tapas.scheme.TPS_Episode.betaLonger private
stretch parameter for balancing episode durations: longer
Definition at line 39 of file TPS_Episode.java.
betaShorter
double de.dlr.ivf.tapas.scheme.TPS_Episode.betaShorter private
stretch parameter for balancing episode durations: shorter
Definition at line 41 of file TPS_Episode.java.
id
final int de.dlr.ivf.tapas.scheme.TPS_Episode.id private
id of the episode
Definition at line 31 of file TPS_Episode.java.
isHomePart
boolean de.dlr.ivf.tapas.scheme.TPS_Episode.isHomePart
Variable which determines, if this part is a HomePart.
Definition at line 27 of file TPS_Episode.java.
Referenced by de.dlr.ivf.tapas.scheme.TPS_Scheme.addEpisode(), de.dlr.ivf.tapas.scheme.TPS_Episode.clone(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readSchemeSet(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.storeLocationOccupanyInDB().
longerDuration
double de.dlr.ivf.tapas.scheme.TPS_Episode.longerDuration private
allowed longer duration of the episode in seconds
Definition at line 43 of file TPS_Episode.java.
originalDuration
int de.dlr.ivf.tapas.scheme.TPS_Episode.originalDuration private
original reported duration of the episode in seconds
Definition at line 45 of file TPS_Episode.java.
originalStart
int de.dlr.ivf.tapas.scheme.TPS_Episode.originalStart private
original reported start time of the episode in minutes
Definition at line 47 of file TPS_Episode.java.
parameterClass
final TPS_ParameterClass de.dlr.ivf.tapas.scheme.TPS_Episode.parameterClass private
Definition at line 56 of file TPS_Episode.java.
schemePart
TPS_SchemePart de.dlr.ivf.tapas.scheme.TPS_Episode.schemePart private
Each episode is part of a scheme part, this member is the link to the corresponding scheme part.
Definition at line 49 of file TPS_Episode.java.
shorterDuration
double de.dlr.ivf.tapas.scheme.TPS_Episode.shorterDuration private
allowed shorter duration of the episode in seconds
Definition at line 51 of file TPS_Episode.java.
startEarlier
double de.dlr.ivf.tapas.scheme.TPS_Episode.startEarlier private
allowed earlier start of the episode in seconds
Definition at line 53 of file TPS_Episode.java.
startLater
double de.dlr.ivf.tapas.scheme.TPS_Episode.startLater private
allowed later start of the episode in seconds
Definition at line 55 of file TPS_Episode.java.
tourNumber
int de.dlr.ivf.tapas.scheme.TPS_Episode.tourNumber
tour number
Definition at line 29 of file TPS_Episode.java.
Referenced by de.dlr.ivf.tapas.scheme.TPS_Scheme.addEpisode(), de.dlr.ivf.tapas.scheme.TPS_Episode.clone(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readSchemeSet().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/scheme/TPS_Episode.java