TAPAS: de.dlr.ivf.tapas.runtime.client.util.table.TextPopupEditor.TextAreaDialog Class Reference
de.dlr.ivf.tapas.runtime.client.util.table.TextPopupEditor.TextAreaDialog Class Reference
Public Member Functions
TextAreaDialog ()
String getText ()
void hide (boolean save)
void show (String oldText, Point position)
Private Attributes
final JTextArea textArea
String oldText
Static Private Attributes
static final long serialVersionUID = 159198378419035738L
static final String LEAVE_SAVE = "leave_save"
static final String LEAVE_DISCARD = "leave_discard"
static final String ENTER = "enter"
Detailed Description
Definition at line 63 of file TextPopupEditor.java.
Constructor & Destructor Documentation
TextAreaDialog()
de.dlr.ivf.tapas.runtime.client.util.table.TextPopupEditor.TextAreaDialog.TextAreaDialog ()
Definition at line 75 of file TextPopupEditor.java.
References de.dlr.ivf.tapas.runtime.client.util.table.TextPopupEditor.actionPerformed(), de.dlr.ivf.tapas.runtime.client.util.table.TextPopupEditor.TextAreaDialog.ENTER, de.dlr.ivf.tapas.runtime.client.util.table.TextPopupEditor.TextAreaDialog.hide(), de.dlr.ivf.tapas.runtime.client.util.table.TextPopupEditor.TextAreaDialog.LEAVE_DISCARD, de.dlr.ivf.tapas.runtime.client.util.table.TextPopupEditor.TextAreaDialog.LEAVE_SAVE, de.dlr.ivf.tapas.runtime.client.util.table.TextPopupEditor.TextAreaDialog.serialVersionUID, and de.dlr.ivf.tapas.runtime.client.util.table.TextPopupEditor.TextAreaDialog.textArea.
Member Function Documentation
getText()
String de.dlr.ivf.tapas.runtime.client.util.table.TextPopupEditor.TextAreaDialog.getText ()
Definition at line 144 of file TextPopupEditor.java.
References de.dlr.ivf.tapas.runtime.client.util.table.TextPopupEditor.TextAreaDialog.textArea.
Referenced by de.dlr.ivf.tapas.runtime.client.util.table.TextPopupEditor.getCellEditorValue().
hide()
void de.dlr.ivf.tapas.runtime.client.util.table.TextPopupEditor.TextAreaDialog.hide (boolean save)
Definition at line 148 of file TextPopupEditor.java.
References de.dlr.ivf.tapas.runtime.client.util.table.TextPopupEditor.TextAreaDialog.oldText, and de.dlr.ivf.tapas.runtime.client.util.table.TextPopupEditor.TextAreaDialog.textArea.
Referenced by de.dlr.ivf.tapas.runtime.client.util.table.TextPopupEditor.TextAreaDialog.TextAreaDialog().
show()
void de.dlr.ivf.tapas.runtime.client.util.table.TextPopupEditor.TextAreaDialog.show (String oldText, Point position)
Definition at line 160 of file TextPopupEditor.java.
References de.dlr.ivf.tapas.runtime.client.util.table.TextPopupEditor.TextAreaDialog.oldText, de.dlr.ivf.tapas.runtime.client.util.table.TextPopupEditor.table, and de.dlr.ivf.tapas.runtime.client.util.table.TextPopupEditor.TextAreaDialog.textArea.
Referenced by de.dlr.ivf.tapas.runtime.client.util.table.TextPopupEditor.actionPerformed().
Member Data Documentation
ENTER
final String de.dlr.ivf.tapas.runtime.client.util.table.TextPopupEditor.TextAreaDialog.ENTER = "enter" static private
Definition at line 70 of file TextPopupEditor.java.
Referenced by de.dlr.ivf.tapas.runtime.client.util.table.TextPopupEditor.TextAreaDialog.TextAreaDialog().
LEAVE_DISCARD
final String de.dlr.ivf.tapas.runtime.client.util.table.TextPopupEditor.TextAreaDialog.LEAVE_DISCARD = "leave_discard" static private
Definition at line 69 of file TextPopupEditor.java.
Referenced by de.dlr.ivf.tapas.runtime.client.util.table.TextPopupEditor.TextAreaDialog.TextAreaDialog().
LEAVE_SAVE
final String de.dlr.ivf.tapas.runtime.client.util.table.TextPopupEditor.TextAreaDialog.LEAVE_SAVE = "leave_save" static private
Definition at line 68 of file TextPopupEditor.java.
Referenced by de.dlr.ivf.tapas.runtime.client.util.table.TextPopupEditor.TextAreaDialog.TextAreaDialog().
oldText
String de.dlr.ivf.tapas.runtime.client.util.table.TextPopupEditor.TextAreaDialog.oldText private
Definition at line 73 of file TextPopupEditor.java.
Referenced by de.dlr.ivf.tapas.runtime.client.util.table.TextPopupEditor.TextAreaDialog.hide(), and de.dlr.ivf.tapas.runtime.client.util.table.TextPopupEditor.TextAreaDialog.show().
serialVersionUID
final long de.dlr.ivf.tapas.runtime.client.util.table.TextPopupEditor.TextAreaDialog.serialVersionUID = 159198378419035738L static private
Definition at line 67 of file TextPopupEditor.java.
Referenced by de.dlr.ivf.tapas.runtime.client.util.table.TextPopupEditor.TextAreaDialog.TextAreaDialog().
textArea
final JTextArea de.dlr.ivf.tapas.runtime.client.util.table.TextPopupEditor.TextAreaDialog.textArea private
Definition at line 72 of file TextPopupEditor.java.
Referenced by de.dlr.ivf.tapas.runtime.client.util.table.TextPopupEditor.TextAreaDialog.getText(), de.dlr.ivf.tapas.runtime.client.util.table.TextPopupEditor.TextAreaDialog.hide(), de.dlr.ivf.tapas.runtime.client.util.table.TextPopupEditor.TextAreaDialog.show(), and de.dlr.ivf.tapas.runtime.client.util.table.TextPopupEditor.TextAreaDialog.TextAreaDialog().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/runtime/client/util/table/TextPopupEditor.java