TAPAS: de.dlr.ivf.tapas.modechoice.TPS_Node Class Reference
de.dlr.ivf.tapas.modechoice.TPS_Node Class Reference
Public Member Functions
TPS_Node (int id, TPS_Attribute splitVariable, Collection< Integer > attributeValues, TPS_DiscreteDistribution< TPS_Mode > distribution, TPS_Node parent)
void addChild (TPS_Node pChild)
int compareTo (TPS_Node o)
boolean find (int val)
TPS_Node getChild (int childId)
List< TPS_Node > getChildren ()
TPS_DiscreteDistribution< TPS_Mode > getCopyOfValueDistribution ()
int getId ()
List< Integer > getMyAttValues ()
TPS_Node getParent ()
TPS_Attribute getSplitVariable ()
boolean isLeaf ()
void setDistribution (double[] distribution)
String toString ()
String toString (String prefix)
String toString (String prefix, boolean recursive)
Protected Attributes
TPS_DiscreteDistribution< TPS_Mode > distribution
Private Attributes
TPS_Node parent = null
final List< TPS_Node > children = new Vector<>()
final int id
List< Integer > myAttValues = new Vector<>()
final TPS_Attribute splitVariable
Detailed Description
This class is a node in the TPS_ModeChoiceTree. It can either be a real node or leaf. Each real node contains a split variable which describes how the children are separated from each other.
Author
mark_ma
Definition at line 30 of file TPS_Node.java.
Constructor & Destructor Documentation
TPS_Node()
de.dlr.ivf.tapas.modechoice.TPS_Node.TPS_Node (int id, TPS_Attribute splitVariable, Collection< Integer > attributeValues, TPS_DiscreteDistribution< TPS_Mode > distribution, TPS_Node parent)
Constructor initializes all members with the given values.
Parameters
id node id
splitVariable the current split variable
attributeValues the attribute values of this node
distribution the mode distribution
Definition at line 66 of file TPS_Node.java.
Member Function Documentation
addChild()
void de.dlr.ivf.tapas.modechoice.TPS_Node.addChild (TPS_Node pChild)
Adds a child.
Parameters
pChild
Definition at line 80 of file TPS_Node.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readExpertKnowledgeTree(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readModeChoiceTree().
compareTo()
int de.dlr.ivf.tapas.modechoice.TPS_Node.compareTo (TPS_Node o)
compares the hashCode of this attribute values with the attribute values of the given node
Returns
returns zero if the attribute values have the same hashCode
Definition at line 89 of file TPS_Node.java.
References de.dlr.ivf.tapas.modechoice.TPS_Node.myAttValues.
find()
boolean de.dlr.ivf.tapas.modechoice.TPS_Node.find (int val)
Method to check if the attribute values contain a given value
Parameters
val value to look for
Returns
true if the value is contained; false else
Definition at line 99 of file TPS_Node.java.
Referenced by de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree.find(), and de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree.getNode().
getChild()
TPS_Node de.dlr.ivf.tapas.modechoice.TPS_Node.getChild (int childId)
This method recursively searches the node with the given childId in the branch of this node.
Parameters
childId
Returns
child node if found, null otherwise
Definition at line 116 of file TPS_Node.java.
References de.dlr.ivf.tapas.modechoice.TPS_Node.getChild().
Referenced by de.dlr.ivf.tapas.modechoice.TPS_Node.getChild(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readExpertKnowledgeTree(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readModeChoiceTree().
getChildren()
List<TPS_Node> de.dlr.ivf.tapas.modechoice.TPS_Node.getChildren ()
Returns the child nodes of the node
Returns
child nodes
Definition at line 137 of file TPS_Node.java.
Referenced by de.dlr.ivf.tapas.modechoice.TPS_ModeChoiceTree.descend(), and de.dlr.ivf.tapas.modechoice.TPS_ModeChoiceTree.find().
getCopyOfValueDistribution()
TPS_DiscreteDistribution<TPS_Mode> de.dlr.ivf.tapas.modechoice.TPS_Node.getCopyOfValueDistribution ()
Returns the mode distribution of the node
Returns
mode distribution of this node
Definition at line 146 of file TPS_Node.java.
References de.dlr.ivf.tapas.mode.TPS_Mode.getConstants(), de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.getValues(), and de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.setValues().
Referenced by de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixed.getDistributionSet(), and de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixedBS.getDistributionSet().
getId()
int de.dlr.ivf.tapas.modechoice.TPS_Node.getId ()
Returns the id of the node
Returns
id
Definition at line 157 of file TPS_Node.java.
Referenced by de.dlr.ivf.tapas.modechoice.TPS_ModeChoiceTree.find().
getMyAttValues()
List<Integer> de.dlr.ivf.tapas.modechoice.TPS_Node.getMyAttValues ()
returns the attribute values
Returns
Definition at line 166 of file TPS_Node.java.
getParent()
TPS_Node de.dlr.ivf.tapas.modechoice.TPS_Node.getParent ()
Returns
the parent
Definition at line 173 of file TPS_Node.java.
Referenced by de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixed.getDistributionSet(), and de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixedBS.getDistributionSet().
getSplitVariable()
TPS_Attribute de.dlr.ivf.tapas.modechoice.TPS_Node.getSplitVariable ()
Returns the split variable of the node
Returns
the split variable
Definition at line 182 of file TPS_Node.java.
Referenced by de.dlr.ivf.tapas.modechoice.TPS_ModeChoiceTree.descend().
isLeaf()
boolean de.dlr.ivf.tapas.modechoice.TPS_Node.isLeaf ()
States if the node is a leave node
Returns
true if node is a leaf, false otherwise
Definition at line 191 of file TPS_Node.java.
Referenced by de.dlr.ivf.tapas.modechoice.TPS_ModeChoiceTree.descend().
setDistribution()
void de.dlr.ivf.tapas.modechoice.TPS_Node.setDistribution (double[] distribution)
Sets the distribution given
Parameters
distribution
Definition at line 200 of file TPS_Node.java.
toString() [1/3]
String de.dlr.ivf.tapas.modechoice.TPS_Node.toString ()
Definition at line 211 of file TPS_Node.java.
Referenced by de.dlr.ivf.tapas.modechoice.TPS_ModeChoiceTree.toString().
toString() [2/3]
String de.dlr.ivf.tapas.modechoice.TPS_Node.toString (String prefix)
This method should print the object naturally with the given prefix.
Parameters
prefix
Returns
prefix + toString();
Implements de.dlr.ivf.tapas.util.ExtendedWritable.
Definition at line 220 of file TPS_Node.java.
toString() [3/3]
String de.dlr.ivf.tapas.modechoice.TPS_Node.toString (String prefix, boolean recursive)
extended toString-method for output
Parameters
prefix
recursive
Returns
Definition at line 231 of file TPS_Node.java.
Member Data Documentation
children
final List<TPS_Node> de.dlr.ivf.tapas.modechoice.TPS_Node.children = new Vector<>() private
direct child nodes
Definition at line 44 of file TPS_Node.java.
distribution
TPS_DiscreteDistribution<TPS_Mode> de.dlr.ivf.tapas.modechoice.TPS_Node.distribution protected
mode distribution
Definition at line 35 of file TPS_Node.java.
id
final int de.dlr.ivf.tapas.modechoice.TPS_Node.id private
node id
Definition at line 48 of file TPS_Node.java.
myAttValues
List<Integer> de.dlr.ivf.tapas.modechoice.TPS_Node.myAttValues = new Vector<>() private
Collection with all values for this node, eg. Distances or age classes
Definition at line 52 of file TPS_Node.java.
Referenced by de.dlr.ivf.tapas.modechoice.TPS_Node.compareTo().
parent
TPS_Node de.dlr.ivf.tapas.modechoice.TPS_Node.parent = null private
the parent node
Definition at line 40 of file TPS_Node.java.
Referenced by de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeNode.TPS_ExpertKnowledgeNode().
splitVariable
final TPS_Attribute de.dlr.ivf.tapas.modechoice.TPS_Node.splitVariable private
Node's split variable
Definition at line 56 of file TPS_Node.java.
Referenced by de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeNode.TPS_ExpertKnowledgeNode().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/modechoice/TPS_Node.java