TAPAS: de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon Class Reference
de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon Class Reference
Classes
class RunWhenShuttingDownSumo
Public Member Functions
SumoDaemon (File tapasNetworkDirectory)
void run ()
Static Public Member Functions
static void main (String[] args) throws InterruptedException
Private Member Functions
void changeSimulationStatus (boolean start)
boolean checkAndReestablishCon () throws SQLException
List< String > createNewMatrixMap (String oldName, String pVal)
String getOutputPath ()
MatrixMap loadSumoValues (String matrixMap, double weight)
void readParameter ()
int readSumoIteration (String sim_key)
void resetSimulation (String sim_key)
void saveMatrices (MatrixMap map, List< String > newNames)
void searchSimsToProcess ()
String updateStringIter (String val)
Private Attributes
final HashMap< String, Integer > simKeysTriggerIteration = new HashMap<>()
TPS_DB_Connector manager = null
final File tapasNetworkDirectory
final TPS_ParameterClass parameterClass
String actualKey = ""
int actualIter = 0
Static Private Attributes
static final TPS_ArgumentType<?>[] PARAMETERS
Detailed Description
Definition at line 33 of file SumoDaemon.java.
Constructor & Destructor Documentation
SumoDaemon()
de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.SumoDaemon (File tapasNetworkDirectory)
Definition at line 61 of file SumoDaemon.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.FILE_WORKING_DIRECTORY, de.dlr.ivf.tapas.runtime.util.DaemonControlProperties.get(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.loadRuntimeParameters(), de.dlr.ivf.tapas.runtime.util.DaemonControlProperties.DaemonControlPropKey.LOGIN_CONFIG, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.setString(), and de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.SIM_DIR.
Member Function Documentation
changeSimulationStatus()
void de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.changeSimulationStatus (boolean start) private
This method starts a new iteration for the set simulation key
Definition at line 98 of file SumoDaemon.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute().
checkAndReestablishCon()
boolean de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.checkAndReestablishCon () throws SQLException private
Definition at line 113 of file SumoDaemon.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection().
createNewMatrixMap()
List<String> de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.createNewMatrixMap (String oldName, String pVal) private
Definition at line 122 of file SumoDaemon.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_MATRIXMAPS, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), and de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString().
getOutputPath()
String de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.getOutputPath () private
Definition at line 234 of file SumoDaemon.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_TRIPS, de.dlr.ivf.tapas.util.parameters.ParamString.FILE_WORKING_DIRECTORY, and de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString().
loadSumoValues()
MatrixMap de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.loadSumoValues (String matrixMap, double weight) private
Definition at line 241 of file SumoDaemon.java.
References de.dlr.ivf.tapas.util.MatrixMap.clone(), de.dlr.ivf.tapas.util.parameters.ParamString.DB_SCHEMA_TEMP, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_TAZ, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), de.dlr.ivf.tapas.util.MatrixMap.getMatrix(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.util.Matrix.getValue(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.readMatrixMap(), and de.dlr.ivf.tapas.util.Matrix.setValue().
main()
static void de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.main (String[] args) throws InterruptedException static
Parameters
args
Exceptions
InterruptedException
Definition at line 84 of file SumoDaemon.java.
References de.dlr.ivf.tapas.util.TPS_Argument.checkArguments().
readParameter()
void de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.readParameter () private
Definition at line 291 of file SumoDaemon.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.CURRENCY, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_SIMULATION_PARAMETERS, de.dlr.ivf.tapas.util.parameters.CURRENCY.EUR, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), de.dlr.ivf.tapas.util.parameters.ParamString.FILE_WORKING_DIRECTORY, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.readParametersFromDBMaintainLoginInfo(), de.dlr.ivf.tapas.util.parameters.ParamString.RUN_IDENTIFIER, and de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.setString().
readSumoIteration()
int de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.readSumoIteration (String sim_key) private
Definition at line 312 of file SumoDaemon.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.readSingleParameter().
resetSimulation()
void de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.resetSimulation (String sim_key) private
Definition at line 335 of file SumoDaemon.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeUpdate(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.readSingleParameter(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.updateSingleParameter().
run()
void de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.run ()
Definition at line 391 of file SumoDaemon.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_TT_MIT, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.updateSingleParameter().
saveMatrices()
void de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.saveMatrices (MatrixMap map, List< String > newNames) private
Definition at line 428 of file SumoDaemon.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_MATRICES, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.util.MatrixMap.matrices, de.dlr.ivf.tapas.util.MatrixMap.MatrixTuple.matrix, de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.matrixToSQLArray(), and name.
searchSimsToProcess()
void de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.searchSimsToProcess () private
Definition at line 441 of file SumoDaemon.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery().
updateStringIter()
String de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.updateStringIter (String val) private
This method adopts the string-value to point to the actual iteration
Parameters
val the old value
Returns
the new string for the db
Definition at line 489 of file SumoDaemon.java.
Member Data Documentation
actualIter
int de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.actualIter = 0 private
Definition at line 59 of file SumoDaemon.java.
actualKey
String de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.actualKey = "" private
Definition at line 58 of file SumoDaemon.java.
manager
TPS_DB_Connector de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.manager = null private
The reference to the connection manager, needed to reestablish the connection, if necessary
Definition at line 49 of file SumoDaemon.java.
parameterClass
final TPS_ParameterClass de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.parameterClass private
TPS_ParameterClass parameter container
Definition at line 57 of file SumoDaemon.java.
PARAMETERS
final TPS_ArgumentType<?> [] de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.PARAMETERS static private
Initial value:
= {new TPS_ArgumentType<>("tapas network directory path",
            File.class)}
Parameter array with all parameters for this main method.
PARAMETERS[0] = tapas network directory path
Definition at line 41 of file SumoDaemon.java.
simKeysTriggerIteration
final HashMap<String, Integer> de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.simKeysTriggerIteration = new HashMap<>() private
Definition at line 45 of file SumoDaemon.java.
tapasNetworkDirectory
final File de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.tapasNetworkDirectory private
Path of the TAPAS network directory
Definition at line 53 of file SumoDaemon.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/runtime/sumoDaemon/SumoDaemon.java