TAPAS: de.dlr.ivf.tapas.util.parameters.ParamValueClass Class Reference
de.dlr.ivf.tapas.util.parameters.ParamValueClass Class Reference
Public Member Functions
void clear (ParamValue param)
double getDoubleValue (ParamValue param)
float getFloatValue (ParamValue param)
int getIntValue (ParamValue param)
long getLongValue (ParamValue param)
Number getPreset (ParamValue param)
ParamType getType (ParamValue param)
Number getValue (ParamValue param) throws RuntimeException
boolean isDefined (ParamValue param)
void setValue (ParamValue param, double value)
void setValue (ParamValue param, float value)
void setValue (ParamValue param, Number value)
void setValue (ParamValue param, int value)
void setValue (ParamValue param, long value)
Private Attributes
final EnumMap< ParamValue, MutablePair< ParamType, Number > > paramValues
Detailed Description
Definition at line 15 of file ParamValueClass.java.
Member Function Documentation
clear()
void de.dlr.ivf.tapas.util.parameters.ParamValueClass.clear (ParamValue param)
clears the attached value to the default value
Parameters
param value parameter enum
Definition at line 167 of file ParamValueClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamValueClass.getValue(), and de.dlr.ivf.tapas.util.parameters.ParamValueClass.setValue().
getDoubleValue()
double de.dlr.ivf.tapas.util.parameters.ParamValueClass.getDoubleValue (ParamValue param)
Parameters
param parameter enum
Returns
value as double
Exceptions
RuntimeException if the constant was not defined
Definition at line 176 of file ParamValueClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamValueClass.isDefined().
Referenced by de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getDoubleValue(), de.dlr.ivf.tapas.TPS_Main.updateCosts(), and de.dlr.ivf.tapas.iteration.TPS_VisumConverter.writeODMatrices().
getFloatValue()
float de.dlr.ivf.tapas.util.parameters.ParamValueClass.getFloatValue (ParamValue param)
Parameters
param parameter enum
Returns
value as float
Exceptions
RuntimeException if the constant was not defined
Definition at line 186 of file ParamValueClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamValueClass.isDefined().
getIntValue()
int de.dlr.ivf.tapas.util.parameters.ParamValueClass.getIntValue (ParamValue param)
Parameters
param parameter enum
Returns
value as int, values after decimal point are skipped
Exceptions
RuntimeException if the constant was not defined
Definition at line 196 of file ParamValueClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamValueClass.isDefined().
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.checkProperties(), and de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getIntValue().
getLongValue()
long de.dlr.ivf.tapas.util.parameters.ParamValueClass.getLongValue (ParamValue param)
Parameters
param parameter enum
Returns
value as long, values after decimal point are skipped
Exceptions
RuntimeException if the constant was not defined
Definition at line 206 of file ParamValueClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamValueClass.isDefined().
Referenced by de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getLongValue().
getPreset()
Number de.dlr.ivf.tapas.util.parameters.ParamValueClass.getPreset (ParamValue param)
TODO ugly hack maybe improve
Parameters
param number parameter enum
Returns
the default number value of the enum
Definition at line 217 of file ParamValueClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamValueClass.getValue().
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.getDefaultParams().
getType()
ParamType de.dlr.ivf.tapas.util.parameters.ParamValueClass.getType (ParamValue param)
Parameters
param parameter enum
Returns
parameter type
Definition at line 229 of file ParamValueClass.java.
Referenced by de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getType().
getValue()
Number de.dlr.ivf.tapas.util.parameters.ParamValueClass.getValue (ParamValue param) throws RuntimeException
Parameters
param parameter enum
Returns
value as the general Number type
Exceptions
RuntimeException if the constant was not defined
Definition at line 238 of file ParamValueClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamValueClass.isDefined().
Referenced by de.dlr.ivf.tapas.util.parameters.ParamValueClass.clear(), and de.dlr.ivf.tapas.util.parameters.ParamValueClass.getPreset().
isDefined()
boolean de.dlr.ivf.tapas.util.parameters.ParamValueClass.isDefined (ParamValue param)
Parameters
param value/Number parameter enum
Returns
true if defined, false otherwise
Definition at line 247 of file ParamValueClass.java.
Referenced by de.dlr.ivf.tapas.util.parameters.ParamValueClass.getDoubleValue(), de.dlr.ivf.tapas.util.parameters.ParamValueClass.getFloatValue(), de.dlr.ivf.tapas.util.parameters.ParamValueClass.getIntValue(), de.dlr.ivf.tapas.util.parameters.ParamValueClass.getLongValue(), de.dlr.ivf.tapas.util.parameters.ParamValueClass.getValue(), and de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isDefined().
setValue() [1/5]
void de.dlr.ivf.tapas.util.parameters.ParamValueClass.setValue (ParamValue param, double value)
Sets the value
Parameters
param value/Number parameter enum
value as a double type
Definition at line 257 of file ParamValueClass.java.
Referenced by de.dlr.ivf.tapas.util.parameters.ParamValueClass.clear(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.consumeParameter(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.setValue(), and de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.updateParameter().
setValue() [2/5]
void de.dlr.ivf.tapas.util.parameters.ParamValueClass.setValue (ParamValue param, float value)
Sets the value
Parameters
param value/Number parameter enum
value as a float
Definition at line 267 of file ParamValueClass.java.
setValue() [3/5]
void de.dlr.ivf.tapas.util.parameters.ParamValueClass.setValue (ParamValue param, int value)
Sets the value
Parameters
param value/Number parameter enum
value as an int
Definition at line 287 of file ParamValueClass.java.
setValue() [4/5]
void de.dlr.ivf.tapas.util.parameters.ParamValueClass.setValue (ParamValue param, long value)
Sets the value
Parameters
param value/Number parameter enum
value as a long
Definition at line 297 of file ParamValueClass.java.
setValue() [5/5]
void de.dlr.ivf.tapas.util.parameters.ParamValueClass.setValue (ParamValue param, Number value)
Sets the value
Parameters
param value/Number parameter enum
value as a Number type
Definition at line 277 of file ParamValueClass.java.
Member Data Documentation
paramValues
final EnumMap<ParamValue, MutablePair<ParamType, Number> > de.dlr.ivf.tapas.util.parameters.ParamValueClass.paramValues private
Definition at line 16 of file ParamValueClass.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/util/parameters/ParamValueClass.java