TAPAS: de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ Class Reference
de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ Class Reference
Public Member Functions
GroupToTAZ (TPS_ParameterClass parameterClass)
GroupToTAZ (TPS_DB_Connector con)
String getDbName ()
void setDbName (String dbName)
List< Integer > getMappingValues ()
String getRegion ()
void setRegion (String region)
String getShapeSQLQuery (int map_id)
int[] getTAZes (int map_id)
boolean importData (String name, String region, String csvFile)
boolean initRegion (String region)
boolean loadMapping (String name)
Private Member Functions
boolean flushTAZImportData (String name, String region, int map_id, List< Integer > tazes)
void initDB ()
Private Attributes
final List< Integer > taz = new ArrayList<>()
String region
String dbName = "_taz_mapping_values"
final HashMap< Integer, int[]> mapping = new HashMap<>()
Detailed Description
Definition at line 26 of file GroupToTAZ.java.
Constructor & Destructor Documentation
GroupToTAZ() [1/2]
de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ.GroupToTAZ (TPS_ParameterClass parameterClass)
Stand alone initializator, assumes that global TPS_Parameters contains the login information for the db
Definition at line 37 of file GroupToTAZ.java.
References de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ.initDB().
GroupToTAZ() [2/2]
de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ.GroupToTAZ (TPS_DB_Connector con)
Constructor with a given db-connector to use
Parameters
con The Connector to use
Definition at line 53 of file GroupToTAZ.java.
References de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ.initDB().
Member Function Documentation
flushTAZImportData()
boolean de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ.flushTAZImportData (String name, String region, int map_id, List< Integer > tazes) private
Definition at line 58 of file GroupToTAZ.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeUpdate(), name, and de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ.region.
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ.importData().
getDbName()
String de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ.getDbName ()
Returns
the dbName
Definition at line 74 of file GroupToTAZ.java.
References de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ.dbName.
getMappingValues()
List<Integer> de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ.getMappingValues ()
Returns a sorted list of the map-values which are actually present.
Returns
Definition at line 90 of file GroupToTAZ.java.
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.initRegionsFromTazGrouper().
getRegion()
String de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ.getRegion ()
Returns
the region
Definition at line 100 of file GroupToTAZ.java.
References de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ.region.
getShapeSQLQuery()
String de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ.getShapeSQLQuery (int map_id)
Method to return a sql-query which contains the shape of the given mapping group
Parameters
map_id the id for tzhis group
Returns
a sql-string or null if group is empty
Definition at line 117 of file GroupToTAZ.java.
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.initRegionsFromTazGrouper().
getTAZes()
int [] de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ.getTAZes (int map_id)
Method to return an array of tazes for the given map_id.
Parameters
map_id The map id
Returns
The sorted array of tazes or an zero-element array if map_id is not found.
Definition at line 140 of file GroupToTAZ.java.
importData()
boolean de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ.importData (String name, String region, String csvFile)
Definition at line 145 of file GroupToTAZ.java.
References de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ.flushTAZImportData(), and de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ.region.
initDB()
void de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ.initDB () private
Definition at line 198 of file GroupToTAZ.java.
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ.GroupToTAZ().
initRegion()
boolean de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ.initRegion (String region)
Method to init the taz info: load all taz ids for this region
Returns
Definition at line 207 of file GroupToTAZ.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ.region, and de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ.taz.
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.initRegionsFromTazGrouper().
loadMapping()
boolean de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ.loadMapping (String name)
Method to load the mapping infos. Loads the mapping values, checks them and stores them internaly
Returns
true if everything is ok and values are found.
Definition at line 231 of file GroupToTAZ.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.extractIntArray(), name, and de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ.taz.
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.initRegionsFromTazGrouper().
setDbName()
void de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ.setDbName (String dbName)
Parameters
dbName the dbName to set
Definition at line 81 of file GroupToTAZ.java.
References de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ.dbName.
setRegion()
void de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ.setRegion (String region)
Parameters
region the region to set
Definition at line 107 of file GroupToTAZ.java.
References de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ.region.
Member Data Documentation
dbName
String de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ.dbName = "_taz_mapping_values" private
Definition at line 31 of file GroupToTAZ.java.
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ.getDbName(), and de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ.setDbName().
mapping
final HashMap<Integer, int[]> de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ.mapping = new HashMap<>() private
Definition at line 32 of file GroupToTAZ.java.
region
String de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ.region private
Definition at line 30 of file GroupToTAZ.java.
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ.flushTAZImportData(), de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ.getRegion(), de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ.importData(), de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ.initRegion(), and de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ.setRegion().
taz
final List<Integer> de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ.taz = new ArrayList<>() private
Definition at line 29 of file GroupToTAZ.java.
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ.initRegion(), and de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ.loadMapping().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/OpportunityDistribution/GroupToTAZ.java