TAPAS: de.dlr.ivf.tapas.runtime.server.SimulationData.ProgressCalculator Class Reference
de.dlr.ivf.tapas.runtime.server.SimulationData.ProgressCalculator Class Reference
Public Member Functions
ProgressCalculator (SimulationData sim)
long getEstimatedTime ()
void update ()
Private Member Functions
void stateUpdate ()
Private Attributes
long estimatedTime
long processedHouseholds
long startTime
long lastTimeUpdate
final SimulationData simData
boolean lastStateStarted
final double[] slidingAverage
int indexSlidingAverage = 0
Detailed Description
Definition at line 436 of file SimulationData.java.
Constructor & Destructor Documentation
ProgressCalculator()
de.dlr.ivf.tapas.runtime.server.SimulationData.ProgressCalculator.ProgressCalculator (SimulationData sim)
Definition at line 447 of file SimulationData.java.
References de.dlr.ivf.tapas.runtime.server.SimulationData.isStarted(), de.dlr.ivf.tapas.runtime.server.SimulationData.ProgressCalculator.slidingAverage, and de.dlr.ivf.tapas.runtime.server.SimulationData.ProgressCalculator.stateUpdate().
Member Function Documentation
getEstimatedTime()
long de.dlr.ivf.tapas.runtime.server.SimulationData.ProgressCalculator.getEstimatedTime ()
Definition at line 455 of file SimulationData.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationData.getEstimatedTime().
stateUpdate()
void de.dlr.ivf.tapas.runtime.server.SimulationData.ProgressCalculator.stateUpdate () private
Definition at line 461 of file SimulationData.java.
References de.dlr.ivf.tapas.runtime.server.SimulationData.sim_progress, and de.dlr.ivf.tapas.runtime.server.SimulationData.ProgressCalculator.startTime.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationData.ProgressCalculator.ProgressCalculator(), and de.dlr.ivf.tapas.runtime.server.SimulationData.ProgressCalculator.update().
update()
void de.dlr.ivf.tapas.runtime.server.SimulationData.ProgressCalculator.update ()
Definition at line 474 of file SimulationData.java.
References de.dlr.ivf.tapas.runtime.server.SimulationData.ProgressCalculator.indexSlidingAverage, de.dlr.ivf.tapas.runtime.server.SimulationData.isStarted(), de.dlr.ivf.tapas.runtime.server.SimulationData.ProgressCalculator.lastTimeUpdate, de.dlr.ivf.tapas.runtime.server.SimulationData.ProgressCalculator.processedHouseholds, de.dlr.ivf.tapas.runtime.server.SimulationData.sim_progress, de.dlr.ivf.tapas.runtime.server.SimulationData.sim_total, and de.dlr.ivf.tapas.runtime.server.SimulationData.ProgressCalculator.stateUpdate().
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationData.update().
Member Data Documentation
estimatedTime
long de.dlr.ivf.tapas.runtime.server.SimulationData.ProgressCalculator.estimatedTime private
Definition at line 438 of file SimulationData.java.
indexSlidingAverage
int de.dlr.ivf.tapas.runtime.server.SimulationData.ProgressCalculator.indexSlidingAverage = 0 private
Definition at line 445 of file SimulationData.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationData.ProgressCalculator.update().
lastStateStarted
boolean de.dlr.ivf.tapas.runtime.server.SimulationData.ProgressCalculator.lastStateStarted private
Definition at line 443 of file SimulationData.java.
lastTimeUpdate
long de.dlr.ivf.tapas.runtime.server.SimulationData.ProgressCalculator.lastTimeUpdate private
Definition at line 441 of file SimulationData.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationData.ProgressCalculator.update().
processedHouseholds
long de.dlr.ivf.tapas.runtime.server.SimulationData.ProgressCalculator.processedHouseholds private
Definition at line 439 of file SimulationData.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationData.ProgressCalculator.update().
simData
final SimulationData de.dlr.ivf.tapas.runtime.server.SimulationData.ProgressCalculator.simData private
Definition at line 442 of file SimulationData.java.
slidingAverage
final double [] de.dlr.ivf.tapas.runtime.server.SimulationData.ProgressCalculator.slidingAverage private
Definition at line 444 of file SimulationData.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationData.ProgressCalculator.ProgressCalculator().
startTime
long de.dlr.ivf.tapas.runtime.server.SimulationData.ProgressCalculator.startTime private
Definition at line 440 of file SimulationData.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationData.ProgressCalculator.stateUpdate().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/runtime/server/SimulationData.java