TAPAS: de.dlr.ivf.tapas.tools.fileModifier.persistence.TPS_ParameterCSVDAO Class Reference
de.dlr.ivf.tapas.tools.fileModifier.persistence.TPS_ParameterCSVDAO Class Reference
Public Member Functions
void readParameter ()
void writeParameter (TPS_ParameterClass parameterClass)
Public Member Functions inherited from de.dlr.ivf.tapas.tools.fileModifier.persistence.AbstractTPS_ParameterDAO
AbstractTPS_ParameterDAO ()
void addAdditionalParameter (String name, String value, String comment)
File getFile ()
void setFile (File file)
void writeParameter ()
Additional Inherited Members
Public Attributes inherited from de.dlr.ivf.tapas.tools.fileModifier.persistence.ITPS_ParameterDAO
String[] header = new String[]{"name", "value", "comment"}
Detailed Description
Definition at line 18 of file TPS_ParameterCSVDAO.java.
Member Function Documentation
readParameter()
void de.dlr.ivf.tapas.tools.fileModifier.persistence.TPS_ParameterCSVDAO.readParameter ()
Reimplemented from de.dlr.ivf.tapas.tools.fileModifier.persistence.AbstractTPS_ParameterDAO.
Definition at line 20 of file TPS_ParameterCSVDAO.java.
writeParameter()
void de.dlr.ivf.tapas.tools.fileModifier.persistence.TPS_ParameterCSVDAO.writeParameter (TPS_ParameterClass parameterClass)
Definition at line 24 of file TPS_ParameterCSVDAO.java.
References de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getDoubleValue(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.tools.fileModifier.persistence.ITPS_ParameterDAO.header, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isDefined(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isTrue(), and name.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.init().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/fileModifier/persistence/TPS_ParameterCSVDAO.java