TAPAS: de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData Class Reference
de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData Class Reference
Public Member Functions
CruisingSpeedValData ()
String getMatricesTable ()
void setMatricesTable (String matricesTable)
String getPath ()
void setPath (String path)
String getRecordName ()
void setRecordName (String recordName)
String[] getReferenceDist ()
void setReferenceDist (String[] referenceDist)
String[] getReferenceTT ()
void setReferenceTT (String[] referenceTT)
String getTazTable ()
void setTazTable (String tazTable)
String getTerrain ()
void setTerrain (String terrain)
boolean isIndirectWayFactor ()
void setIndirectWayFactor (boolean indirectWayFactor)
Private Attributes
String recordName = null
String matricesTable = null
String terrain = null
String tazTable = null
String path = null
boolean indirectWayFactor
String[] referenceDist = null
String[] referenceTT = null
Detailed Description
Definition at line 11 of file CruisingSpeedValData.java.
Constructor & Destructor Documentation
CruisingSpeedValData()
de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.CruisingSpeedValData ()
Definition at line 21 of file CruisingSpeedValData.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.indirectWayFactor, de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.setReferenceDist(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.setReferenceTT().
Member Function Documentation
getMatricesTable()
String de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.getMatricesTable ()
Definition at line 27 of file CruisingSpeedValData.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.matricesTable.
getPath()
String de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.getPath ()
Definition at line 35 of file CruisingSpeedValData.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.path.
getRecordName()
String de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.getRecordName ()
Definition at line 43 of file CruisingSpeedValData.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.recordName.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.init().
getReferenceDist()
String [] de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.getReferenceDist ()
Definition at line 51 of file CruisingSpeedValData.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.referenceDist.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.readProperties(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.start().
getReferenceTT()
String [] de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.getReferenceTT ()
Definition at line 59 of file CruisingSpeedValData.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.referenceTT.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.readProperties(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.start().
getTazTable()
String de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.getTazTable ()
Definition at line 67 of file CruisingSpeedValData.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.tazTable.
getTerrain()
String de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.getTerrain ()
Definition at line 75 of file CruisingSpeedValData.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.terrain.
isIndirectWayFactor()
boolean de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.isIndirectWayFactor ()
Definition at line 83 of file CruisingSpeedValData.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.indirectWayFactor.
setIndirectWayFactor()
void de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.setIndirectWayFactor (boolean indirectWayFactor)
Definition at line 87 of file CruisingSpeedValData.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.indirectWayFactor.
setMatricesTable()
void de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.setMatricesTable (String matricesTable)
Definition at line 31 of file CruisingSpeedValData.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.matricesTable.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.readProperties().
setPath()
void de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.setPath (String path)
Definition at line 39 of file CruisingSpeedValData.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.path.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.readProperties().
setRecordName()
void de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.setRecordName (String recordName)
Definition at line 47 of file CruisingSpeedValData.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.recordName.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.readProperties().
setReferenceDist()
void de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.setReferenceDist (String[] referenceDist)
Definition at line 55 of file CruisingSpeedValData.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.referenceDist.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.CruisingSpeedValData().
setReferenceTT()
void de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.setReferenceTT (String[] referenceTT)
Definition at line 63 of file CruisingSpeedValData.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.referenceTT.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.CruisingSpeedValData().
setTazTable()
void de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.setTazTable (String tazTable)
Definition at line 71 of file CruisingSpeedValData.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.tazTable.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.readProperties().
setTerrain()
void de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.setTerrain (String terrain)
Definition at line 79 of file CruisingSpeedValData.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.terrain.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.readProperties().
Member Data Documentation
indirectWayFactor
boolean de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.indirectWayFactor private
Definition at line 17 of file CruisingSpeedValData.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.CruisingSpeedValData(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.isIndirectWayFactor(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.setIndirectWayFactor().
matricesTable
String de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.matricesTable = null private
Definition at line 13 of file CruisingSpeedValData.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.getMatricesTable(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.setMatricesTable().
path
String de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.path = null private
Definition at line 16 of file CruisingSpeedValData.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.getPath(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.setPath().
recordName
String de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.recordName = null private
Definition at line 12 of file CruisingSpeedValData.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.getRecordName(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.setRecordName().
referenceDist
String [] de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.referenceDist = null private
Definition at line 18 of file CruisingSpeedValData.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.getReferenceDist(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.setReferenceDist().
referenceTT
String [] de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.referenceTT = null private
Definition at line 19 of file CruisingSpeedValData.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.getReferenceTT(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.setReferenceTT().
tazTable
String de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.tazTable = null private
Definition at line 15 of file CruisingSpeedValData.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.getTazTable(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.setTazTable().
terrain
String de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.terrain = null private
Definition at line 14 of file CruisingSpeedValData.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.getTerrain(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.setTerrain().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/matrixMap/CruisingSpeedValData.java