TAPAS: de.dlr.ivf.tapas.plan.acceptance.TPS_PlanEVA1Acceptance Class Reference
de.dlr.ivf.tapas.plan.acceptance.TPS_PlanEVA1Acceptance Class Reference
Public Member Functions
boolean isPlanAccepted (TPS_Plan plan)
Private Member Functions
double calculateAcceptanceProbBudgetConstraints (TPS_Plan plan)
double calculateAcceptanceProbTimeConstraints (TPS_Plan plan)
boolean isPlanAcceptedByAdditionalConstraints (TPS_Plan plan)
boolean isPlanAcceptedByOverallTravelTime (TPS_Plan plan)
Detailed Description
This class is an implementation of the TPS_PlanAcceptance interface and uses the EVA(1) function of Lohse
Author
mark_ma
Definition at line 28 of file TPS_PlanEVA1Acceptance.java.
Member Function Documentation
calculateAcceptanceProbBudgetConstraints()
double de.dlr.ivf.tapas.plan.acceptance.TPS_PlanEVA1Acceptance.calculateAcceptanceProbBudgetConstraints (TPS_Plan plan) private
Calculates the acceptance probability of the plan constructed resulting from the financial expenditures associated with the plan execution while accounting for the mobility budget available
Parameters
plan plan which is used to determine acceptance
Returns
acceptance probability of the plan between 0.0 and 1.0
Definition at line 37 of file TPS_PlanEVA1Acceptance.java.
References de.dlr.ivf.tapas.util.TPS_GX.calculateEVA1Acceptance(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.DEBUG, de.dlr.ivf.tapas.util.parameters.ParamValue.FINANCE_BUDGET_E, de.dlr.ivf.tapas.util.parameters.ParamValue.FINANCE_BUDGET_F, de.dlr.ivf.tapas.util.parameters.ParamValue.FINANCE_BUDGET_WP, de.dlr.ivf.tapas.person.TPS_Person.getBudget(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getDoubleValue(), de.dlr.ivf.tapas.plan.TPS_Plan.getParameters(), de.dlr.ivf.tapas.plan.TPS_Plan.getPerson(), de.dlr.ivf.tapas.plan.TPS_Plan.getTravelCosts(), de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), de.dlr.ivf.tapas.log.TPS_Logger.log(), and de.dlr.ivf.tapas.plan.TPS_Plan.setBudgetAcceptanceProbability().
calculateAcceptanceProbTimeConstraints()
double de.dlr.ivf.tapas.plan.acceptance.TPS_PlanEVA1Acceptance.calculateAcceptanceProbTimeConstraints (TPS_Plan plan) private
Calculates the acceptance probability of the plan constructed resulting from the time expenditures associated with the plan execution while accounting for the available time budget and the flexibility / the time constraints associated with the person type. Function copes both with negative and positive deviance from the reference value.
Parameters
plan plan which is used to determine acceptance
Returns
acceptance probability; between 0.0 and 1.0
Definition at line 93 of file TPS_PlanEVA1Acceptance.java.
References de.dlr.ivf.tapas.util.TPS_GX.calculateEVA1Acceptance(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.DEBUG, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getDoubleValue(), de.dlr.ivf.tapas.plan.TPS_Plan.getParameters(), de.dlr.ivf.tapas.plan.TPS_Plan.getScheme(), de.dlr.ivf.tapas.plan.TPS_Plan.getTravelDuration(), de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.plan.TPS_Plan.setTimeAcceptanceProbability(), de.dlr.ivf.tapas.util.parameters.ParamValue.TIME_BUDGET_E, and de.dlr.ivf.tapas.util.parameters.ParamValue.TIME_BUDGET_F.
isPlanAccepted()
boolean de.dlr.ivf.tapas.plan.acceptance.TPS_PlanEVA1Acceptance.isPlanAccepted (TPS_Plan plan)
This method determines whether this plan is accepted or not. Possible values are e.g. the overall travel time of the plan or the financial costs.
Parameters
plan plan which is used to determine acceptance
Returns
true if the plan is accepted, false otherwise
Implements de.dlr.ivf.tapas.plan.acceptance.TPS_PlanAcceptance.
Definition at line 134 of file TPS_PlanEVA1Acceptance.java.
References de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_CHECK_BUDGET_CONSTRAINTS, de.dlr.ivf.tapas.plan.TPS_Plan.getParameters(), and de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isTrue().
isPlanAcceptedByAdditionalConstraints()
boolean de.dlr.ivf.tapas.plan.acceptance.TPS_PlanEVA1Acceptance.isPlanAcceptedByAdditionalConstraints (TPS_Plan plan) private
This method checks all additional constraints (here: financial costs and travel time acceptance using the average travel time of the whole scheme class of the plan's scheme)
Parameters
plan plan which is used to determine acceptance
Returns
true if all additional constraints are accepted, false otherwise
Definition at line 150 of file TPS_PlanEVA1Acceptance.java.
References de.dlr.ivf.tapas.util.Randomizer.random().
isPlanAcceptedByOverallTravelTime()
boolean de.dlr.ivf.tapas.plan.acceptance.TPS_PlanEVA1Acceptance.isPlanAcceptedByOverallTravelTime (TPS_Plan plan) private
Determines whether the travel times resulting from the chosen modes and locations for the plan exceed too much the travel times initially scheduled for the scheme. The acceptance limit is defined in the configuration.
Parameters
plan the constructed day plan to be checked for acceptance
Returns
true, if the plan with its travel times is not too far off the designated travel times; false if the travel times exceed the maximum difference defined in the configuration
Definition at line 171 of file TPS_PlanEVA1Acceptance.java.
References de.dlr.ivf.tapas.util.TPS_GX.calculateEVA1Acceptance(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.DEBUG, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.FATAL, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getDoubleValue(), de.dlr.ivf.tapas.plan.TPS_Plan.getParameters(), de.dlr.ivf.tapas.plan.TPS_Plan.getScheme(), de.dlr.ivf.tapas.plan.TPS_Plan.getTravelDuration(), de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.util.parameters.ParamValue.MAX_TIME_DIFFERENCE, de.dlr.ivf.tapas.util.parameters.ParamValue.OVERALL_TIME_E, de.dlr.ivf.tapas.util.parameters.ParamValue.OVERALL_TIME_F, de.dlr.ivf.tapas.util.Randomizer.random(), de.dlr.ivf.tapas.plan.TPS_Plan.setAcceptanceProbability(), and de.dlr.ivf.tapas.plan.TPS_Plan.setPlanFeasible().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/plan/acceptance/TPS_PlanEVA1Acceptance.java