TAPAS: de.dlr.ivf.tapas.tools.TPS_PTScoreCalculator Class Reference
de.dlr.ivf.tapas.tools.TPS_PTScoreCalculator Class Reference
Classes
class PTStation
Public Member Functions
TPS_PTScoreCalculator (TPS_DB_Connector connection)
void calcScoresBlock (String region, String key, double radius)
void calcScoresTAZ (String multilineTable, String ptStopTable, String tazTable, String tazScoresTable, String key, double radius)
void readDatabase (String region)
void readStationsBVG (String fileName)
void readStationsSBahn (String fileName)
void writeDB (String ptStopsName, String key)
Static Public Member Functions
static void main (String[] args) throws IOException, ClassNotFoundException
Detailed Description
Class to calculate the PT score for blocks and TAZs
Sample usage: java PTScoreCalculator berlin "T:\Aufbereitung\1 Berlin\Raumsystem\Öv-Haltestellen\U-Bus-Tram-Fähr-Bahnhöfe.txt" "T:\Aufbereitung\1 Berlin\Raumsystem\Öv-Haltestellen\S-Bahnhöfe-2.txt" pt-2008
Author
hein_mh
Definition at line 35 of file TPS_PTScoreCalculator.java.
Constructor & Destructor Documentation
TPS_PTScoreCalculator()
de.dlr.ivf.tapas.tools.TPS_PTScoreCalculator.TPS_PTScoreCalculator (TPS_DB_Connector connection)
the one and only standard-constructor
Parameters
connection reference to the db-connection-manager
Definition at line 50 of file TPS_PTScoreCalculator.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_PTScoreCalculator.main().
Member Function Documentation
calcScoresBlock()
void de.dlr.ivf.tapas.tools.TPS_PTScoreCalculator.calcScoresBlock (String region, String key, double radius)
Definition at line 79 of file TPS_PTScoreCalculator.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery().
calcScoresTAZ()
void de.dlr.ivf.tapas.tools.TPS_PTScoreCalculator.calcScoresTAZ (String multilineTable, String ptStopTable, String tazTable, String tazScoresTable, String key, double radius)
Definition at line 235 of file TPS_PTScoreCalculator.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery().
Referenced by de.dlr.ivf.tapas.tools.TPS_PTScoreCalculator.main().
main()
static void de.dlr.ivf.tapas.tools.TPS_PTScoreCalculator.main (String[] args) throws IOException, ClassNotFoundException static
Parameters
args
Exceptions
IOException
ClassNotFoundException
Definition at line 59 of file TPS_PTScoreCalculator.java.
References de.dlr.ivf.tapas.tools.TPS_PTScoreCalculator.calcScoresTAZ(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.loadRuntimeParameters(), de.dlr.ivf.tapas.tools.TPS_PTScoreCalculator.readDatabase(), de.dlr.ivf.tapas.tools.TPS_PTScoreCalculator.readStationsBVG(), de.dlr.ivf.tapas.tools.TPS_PTScoreCalculator.readStationsSBahn(), and de.dlr.ivf.tapas.tools.TPS_PTScoreCalculator.TPS_PTScoreCalculator().
readDatabase()
void de.dlr.ivf.tapas.tools.TPS_PTScoreCalculator.readDatabase (String region)
Definition at line 392 of file TPS_PTScoreCalculator.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), and name.
Referenced by de.dlr.ivf.tapas.tools.TPS_PTScoreCalculator.main().
readStationsBVG()
void de.dlr.ivf.tapas.tools.TPS_PTScoreCalculator.readStationsBVG (String fileName)
Definition at line 415 of file TPS_PTScoreCalculator.java.
References name.
Referenced by de.dlr.ivf.tapas.tools.TPS_PTScoreCalculator.main().
readStationsSBahn()
void de.dlr.ivf.tapas.tools.TPS_PTScoreCalculator.readStationsSBahn (String fileName)
Definition at line 461 of file TPS_PTScoreCalculator.java.
References name.
Referenced by de.dlr.ivf.tapas.tools.TPS_PTScoreCalculator.main().
writeDB()
void de.dlr.ivf.tapas.tools.TPS_PTScoreCalculator.writeDB (String ptStopsName, String key)
Definition at line 519 of file TPS_PTScoreCalculator.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/TPS_PTScoreCalculator.java