TAPAS: de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController Class Reference
de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController Class Reference
Public Member Functions
SimParamComparatorController (String simkey1, String simkey2, TPS_DB_Connector conn)
void initialize (URL location, ResourceBundle resources)
Private Member Functions
void generateComparisonList ()
Private Attributes
final String simkey1
final TPS_DB_Connector conn
TableView< SimParamComparatorObject > tvSimComparator
TableColumn< SimParamComparatorObject, String > tcParameter
AnchorPane root
ComboBox< ParamFilterPredicate > cbFilter
AnchorPane topBox
final StringProperty para_header
final StringProperty sim1_header
final StringProperty sim2_header
final boolean is_correct_input
ListProperty< SimParamComparatorObject > tablecontent
FilteredList< SimParamComparatorObject > lst
Detailed Description
Definition at line 40 of file SimParamComparatorController.java.
Constructor & Destructor Documentation
SimParamComparatorController()
de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.SimParamComparatorController (String simkey1, String simkey2, TPS_DB_Connector conn)
Definition at line 62 of file SimParamComparatorController.java.
References de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.conn, de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.is_correct_input, and de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.simkey1.
Member Function Documentation
generateComparisonList()
void de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.generateComparisonList () private
Definition at line 72 of file SimParamComparatorController.java.
References de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.cbFilter, de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.conn, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.is_correct_input, de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.lst, de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.simkey1, de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.tablecontent, and de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.tvSimComparator.
Referenced by de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.initialize().
initialize()
void de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.initialize (URL location, ResourceBundle resources)
Definition at line 129 of file SimParamComparatorController.java.
References de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.cbFilter, de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.generateComparisonList(), de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorObject.getIsDefaultFirstSim(), de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorObject.getIsDefaultSecondSim(), de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.getLocale(), de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorObject.isDefault(), de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorObject.isEqual(), de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorObject.isNotEqual(), de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorObject.isNull(), de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.root, de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.sim1_header, de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.sim2_header, de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.tcParameter, de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.topBox, and de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.tvSimComparator.
Member Data Documentation
cbFilter
ComboBox<ParamFilterPredicate> de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.cbFilter private
Definition at line 51 of file SimParamComparatorController.java.
Referenced by de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.generateComparisonList(), and de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.initialize().
conn
final TPS_DB_Connector de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.conn private
Definition at line 43 of file SimParamComparatorController.java.
Referenced by de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.generateComparisonList(), and de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.SimParamComparatorController().
is_correct_input
final boolean de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.is_correct_input private
Definition at line 57 of file SimParamComparatorController.java.
Referenced by de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.generateComparisonList(), and de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.SimParamComparatorController().
lst
FilteredList<SimParamComparatorObject> de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.lst private
Definition at line 59 of file SimParamComparatorController.java.
Referenced by de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.generateComparisonList().
para_header
final StringProperty de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.para_header private
Definition at line 54 of file SimParamComparatorController.java.
root
AnchorPane de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.root private
Definition at line 49 of file SimParamComparatorController.java.
Referenced by de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.initialize().
sim1_header
final StringProperty de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.sim1_header private
Definition at line 55 of file SimParamComparatorController.java.
Referenced by de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.initialize().
sim2_header
final StringProperty de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.sim2_header private
Definition at line 56 of file SimParamComparatorController.java.
Referenced by de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.initialize().
simkey1
final String de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.simkey1 private
Definition at line 42 of file SimParamComparatorController.java.
Referenced by de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.generateComparisonList(), and de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.SimParamComparatorController().
tablecontent
ListProperty<SimParamComparatorObject> de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.tablecontent private
Definition at line 58 of file SimParamComparatorController.java.
Referenced by de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.generateComparisonList().
tcParameter
TableColumn<SimParamComparatorObject, String> de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.tcParameter private
Definition at line 47 of file SimParamComparatorController.java.
Referenced by de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.initialize().
topBox
AnchorPane de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.topBox private
Definition at line 53 of file SimParamComparatorController.java.
Referenced by de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.initialize().
tvSimComparator
TableView<SimParamComparatorObject> de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.tvSimComparator private
Definition at line 45 of file SimParamComparatorController.java.
Referenced by de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.generateComparisonList(), and de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.initialize().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/runtime/client/ParameterComparator/SimParamComparatorController.java