TAPAS: de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixed Class Reference
de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixed Class Reference
Public Member Functions
TPS_DiscreteDistribution< TPS_Mode > getDistributionSet (TPS_ModeSet modeSet, TPS_Plan plan, double distanceNet, TPS_ModeChoiceContext mcc)
Public Member Functions inherited from de.dlr.ivf.tapas.modechoice.TPS_UtilityMNLFullComplex
double getCostOfMode (TPS_Mode mode, TPS_Plan plan, double travelTime, TPS_ModeChoiceContext mcc, SimulationType simType)
Public Member Functions inherited from de.dlr.ivf.tapas.modechoice.TPS_UtilityMNL
double calculateDelta (TPS_Mode mode, TPS_Plan plan, double distanceNet, TPS_ModeChoiceContext mcc)
void setParameterSet (TPS_Mode mode, double[] parameters)
Additional Inherited Members
Public Attributes inherited from de.dlr.ivf.tapas.modechoice.TPS_UtilityFunction
double walkDistanceBarrier = 3000
double walkDistanceShareAfterBarrier = 0.02
double walkDistanceBarrierStrong = 5000
double walkDistanceShareAfterBarrierStrong = 0.00
double minModeProbability = 0
Protected Attributes inherited from de.dlr.ivf.tapas.modechoice.TPS_UtilityMNL
HashMap< TPS_Mode, double[]> parameterMap = new HashMap<>()
Detailed Description
This class calculates the mode share based on the chaid model, but calculates the delta with the MNL-Values
Author
hein_mh
Definition at line 26 of file TPS_UtilityChaidMNLMixed.java.
Member Function Documentation
getDistributionSet()
TPS_DiscreteDistribution<TPS_Mode> de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixed.getDistributionSet (TPS_ModeSet modeSet, TPS_Plan plan, double distanceNet, TPS_ModeChoiceContext mcc)
This method calculates the mode share based on the chaid model, but calculates the delta with the MNL-Values
Reimplemented from de.dlr.ivf.tapas.modechoice.TPS_UtilityMNL.
Definition at line 31 of file TPS_UtilityChaidMNLMixed.java.
References de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree.applyExpertKnowledge(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.HierarchyLogLevel.EPISODE, de.dlr.ivf.tapas.mode.TPS_Mode.get(), de.dlr.ivf.tapas.modechoice.TPS_Node.getCopyOfValueDistribution(), de.dlr.ivf.tapas.modechoice.TPS_ModeChoiceTree.getDistributionSet(), de.dlr.ivf.tapas.mode.TPS_ModeSet.getModeChoiceTree(), de.dlr.ivf.tapas.modechoice.TPS_Node.getParent(), de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.MIT_PASS, de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.normalize(), de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.setValueByKey(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.SEVERE, and de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.WARN.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/modechoice/TPS_UtilityChaidMNLMixed.java