TAPAS: de.dlr.ivf.tapas.constants.TPS_ActivityConstant Class Reference
de.dlr.ivf.tapas.constants.TPS_ActivityConstant Class Reference
Classes
enum TPS_ActivityCodeType
enum TPS_ActivityConstantAttribute
Public Member Functions
TPS_ActivityConstant (int id, String[] attributes, boolean isTrip, boolean isFix, String attr)
void addActivityConstantToMap ()
int getCode (TPS_ActivityCodeType type)
int getId ()
boolean hasAttribute (TPS_ActivityConstantAttribute... attributes)
boolean isFix ()
boolean isTrip ()
Static Public Member Functions
static void clearActivityConstantMap ()
static TPS_ActivityConstant getActivityCodeByTypeAndCode (TPS_ActivityCodeType type, int code)
Static Public Attributes
static TPS_ActivityConstant DEFAULT_ACTIVITY
static TPS_ActivityConstant DUMMY
Private Attributes
TPS_ActivityConstantAttribute attribute
final boolean isFix
final boolean isTrip
final int id
final EnumMap< TPS_ActivityCodeType, TPS_InternalConstant< TPS_ActivityCodeType > > map
Static Private Attributes
static final HashMap< Integer, TPS_ActivityConstant > ACTIVITY_CONSTANTS_MAP = new HashMap<>()
Detailed Description
This class represents the activity constants.
Definition at line 18 of file TPS_ActivityConstant.java.
Constructor & Destructor Documentation
TPS_ActivityConstant()
de.dlr.ivf.tapas.constants.TPS_ActivityConstant.TPS_ActivityConstant (int id, String[] attributes, boolean isTrip, boolean isFix, String attr)
Basic constructor for a TPS_ActivityConstant
Parameters
id corresponding id from the db
attributes attributes have to have a length of 3*n where each 3-segment is of the form (name, code, type) like ("SCHOOL", "410", "MCT")
isTrip True if the activity constant is a trip or a stay
isFix True if the location to this activity is fixed, i.e. is set once, e.g. SCHOOL, WORK etc.
attr special attribute, seeTPS_ActivityConstantAttribute
Definition at line 68 of file TPS_ActivityConstant.java.
References de.dlr.ivf.tapas.constants.TPS_ActivityConstant.TPS_ActivityConstantAttribute.DEFAULT, de.dlr.ivf.tapas.constants.TPS_ActivityConstant.DEFAULT_ACTIVITY, de.dlr.ivf.tapas.constants.TPS_ActivityConstant.getId(), de.dlr.ivf.tapas.constants.TPS_ActivityConstant.hasAttribute(), de.dlr.ivf.tapas.constants.TPS_ActivityConstant.id, de.dlr.ivf.tapas.constants.TPS_ActivityConstant.isFix, de.dlr.ivf.tapas.constants.TPS_ActivityConstant.isTrip, and type.
Member Function Documentation
addActivityConstantToMap()
void de.dlr.ivf.tapas.constants.TPS_ActivityConstant.addActivityConstantToMap ()
Add to static collection of all activity code constants. The objects are accessed by their ids from the db.
Definition at line 125 of file TPS_ActivityConstant.java.
References de.dlr.ivf.tapas.constants.TPS_ActivityConstant.ACTIVITY_CONSTANTS_MAP.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readActivityConstantCodes().
clearActivityConstantMap()
static void de.dlr.ivf.tapas.constants.TPS_ActivityConstant.clearActivityConstantMap () static
Empties the global static activity constant map
Definition at line 103 of file TPS_ActivityConstant.java.
References de.dlr.ivf.tapas.constants.TPS_ActivityConstant.ACTIVITY_CONSTANTS_MAP.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.clearConstants().
getActivityCodeByTypeAndCode()
static TPS_ActivityConstant de.dlr.ivf.tapas.constants.TPS_ActivityConstant.getActivityCodeByTypeAndCode (TPS_ActivityCodeType type, int code) static
Parameters
type like MCT or TAPAS, see TPS_ActivityCodeType
code activityCode code from the db
Returns
activity code object for a given TPS_ActivityCodeType and code (int)
Definition at line 112 of file TPS_ActivityConstant.java.
References de.dlr.ivf.tapas.constants.TPS_ActivityConstant.ACTIVITY_CONSTANTS_MAP, code, and type.
Referenced by de.dlr.ivf.tapas.scheme.TPS_Scheme.addEpisode(), de.dlr.ivf.tapas.loc.TPS_CFN.addToCFN4Map(), de.dlr.ivf.tapas.loc.TPS_CFN.getCFN4Value(), de.dlr.ivf.tapas.loc.TPS_CFN.getParamValue(), de.dlr.ivf.tapas.plan.TPS_Plan.hackStudents(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readActivity2LocationCodes(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readSchemeSet().
getCode()
int de.dlr.ivf.tapas.constants.TPS_ActivityConstant.getCode (TPS_ActivityCodeType type)
Convenience method to obtain the activity code for a given TPS_ActivityCodeType
Parameters
type like MCT or TAPAS, see TPS_ActivityCodeType
Returns
the corresponding code as int
Definition at line 135 of file TPS_ActivityConstant.java.
References type.
Referenced by de.dlr.ivf.tapas.scheme.TPS_TourPart.addStay(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.batchStoreTrips(), de.dlr.ivf.tapas.plan.TPS_Plan.createOutput(), de.dlr.ivf.tapas.loc.TPS_CFN.getCFN4Value(), de.dlr.ivf.tapas.loc.TPS_MultipleTAZRepresentant.getLocationRepresentatives(), de.dlr.ivf.tapas.mode.TPS_ModeSet.getModeDistribution(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.getModeLogSum(), de.dlr.ivf.tapas.loc.TPS_CFN.getParamValue(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readSchemeSet(), de.dlr.ivf.tapas.plan.TPS_LocatedStay.selectLocation(), de.dlr.ivf.tapas.loc.TPS_Region.selectLocation(), de.dlr.ivf.tapas.loc.TPS_SelectLocationWeightBased.selectLocationFromChoiceSet(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.selectLocationFromChoiceSet(), de.dlr.ivf.tapas.scheme.TPS_Stay.setActCode(), and de.dlr.ivf.tapas.plan.TPS_Plan.writeOutputStream().
getId()
int de.dlr.ivf.tapas.constants.TPS_ActivityConstant.getId ()
Returns
id of the activity constant
Definition at line 142 of file TPS_ActivityConstant.java.
References de.dlr.ivf.tapas.constants.TPS_ActivityConstant.id.
Referenced by de.dlr.ivf.tapas.loc.TPS_Region.selectLocation(), and de.dlr.ivf.tapas.constants.TPS_ActivityConstant.TPS_ActivityConstant().
hasAttribute()
boolean de.dlr.ivf.tapas.constants.TPS_ActivityConstant.hasAttribute (TPS_ActivityConstantAttribute... attributes)
This method compares the stored special attribute with the given attributes. If any of the given attributes is equal to the member attribute true is returned, false otherwise.
Parameters
attributes array of attributes to compare the member attribute with
Returns
true if the constant contains on of the given attributes
Definition at line 153 of file TPS_ActivityConstant.java.
References de.dlr.ivf.tapas.constants.TPS_ActivityConstant.attribute.
Referenced by de.dlr.ivf.tapas.mode.TPS_MassTransportMode.getTravelTime(), de.dlr.ivf.tapas.plan.TPS_LocatedStay.selectLocation(), and de.dlr.ivf.tapas.constants.TPS_ActivityConstant.TPS_ActivityConstant().
isFix()
boolean de.dlr.ivf.tapas.constants.TPS_ActivityConstant.isFix ()
Returns
true if the constant is fix, false otherwise
Definition at line 165 of file TPS_ActivityConstant.java.
References de.dlr.ivf.tapas.constants.TPS_ActivityConstant.isFix.
isTrip()
boolean de.dlr.ivf.tapas.constants.TPS_ActivityConstant.isTrip ()
Returns
true if constant represents a trip, false otherwise
Definition at line 172 of file TPS_ActivityConstant.java.
References de.dlr.ivf.tapas.constants.TPS_ActivityConstant.isTrip.
Member Data Documentation
ACTIVITY_CONSTANTS_MAP
final HashMap<Integer, TPS_ActivityConstant> de.dlr.ivf.tapas.constants.TPS_ActivityConstant.ACTIVITY_CONSTANTS_MAP = new HashMap<>() static private
maps ids from the db to TPS_ActivityConstant objects constructed from corresponding db data
Definition at line 34 of file TPS_ActivityConstant.java.
Referenced by de.dlr.ivf.tapas.constants.TPS_ActivityConstant.addActivityConstantToMap(), de.dlr.ivf.tapas.constants.TPS_ActivityConstant.clearActivityConstantMap(), and de.dlr.ivf.tapas.constants.TPS_ActivityConstant.getActivityCodeByTypeAndCode().
attribute
TPS_ActivityConstantAttribute de.dlr.ivf.tapas.constants.TPS_ActivityConstant.attribute private
Special attribute of the constant
Definition at line 38 of file TPS_ActivityConstant.java.
Referenced by de.dlr.ivf.tapas.constants.TPS_ActivityConstant.hasAttribute().
DEFAULT_ACTIVITY
TPS_ActivityConstant de.dlr.ivf.tapas.constants.TPS_ActivityConstant.DEFAULT_ACTIVITY static
Constant for the default activity
Definition at line 23 of file TPS_ActivityConstant.java.
Referenced by de.dlr.ivf.tapas.constants.TPS_ActivityConstant.TPS_ActivityConstant().
DUMMY
TPS_ActivityConstant de.dlr.ivf.tapas.constants.TPS_ActivityConstant.DUMMY static
Initial value:
= new TPS_ActivityConstant(-1,
            new String[]{"null", "-999", "ZBE", "null", "-999", "VOT", "null", "-999", "TAPAS", "null", "-999", "MCT", "null", "-999", "PRIORITY"},
            false, false, null)
dummy activity constant This constant is used for calculating the travel times to the representatives of the traffic analysis zones
Definition at line 28 of file TPS_ActivityConstant.java.
Referenced by de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree.applyExpertKnowledge(), de.dlr.ivf.tapas.modechoice.TPS_UtilityMNL.calculateDelta(), de.dlr.ivf.tapas.modechoice.TPS_UtilityMNL.getDistributionSet(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.getModeLogSum(), and de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes().
id
final int de.dlr.ivf.tapas.constants.TPS_ActivityConstant.id private
id of the activity constant (in the db)
Definition at line 52 of file TPS_ActivityConstant.java.
Referenced by de.dlr.ivf.tapas.constants.TPS_ActivityConstant.getId(), and de.dlr.ivf.tapas.constants.TPS_ActivityConstant.TPS_ActivityConstant().
isFix
final boolean de.dlr.ivf.tapas.constants.TPS_ActivityConstant.isFix private
This flag determines whether the location which is chosen to this kind of activity is fix. When it is true, e.g. for work, then the location can only be chosen once, otherwise the location to this activity is chosen every time.
Definition at line 43 of file TPS_ActivityConstant.java.
Referenced by de.dlr.ivf.tapas.constants.TPS_ActivityConstant.isFix(), de.dlr.ivf.tapas.loc.TPS_Region.selectLocation(), de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes(), and de.dlr.ivf.tapas.constants.TPS_ActivityConstant.TPS_ActivityConstant().
isTrip
final boolean de.dlr.ivf.tapas.constants.TPS_ActivityConstant.isTrip private
This flag determines whether the activity constant is a trip or a stay.
Definition at line 47 of file TPS_ActivityConstant.java.
Referenced by de.dlr.ivf.tapas.constants.TPS_ActivityConstant.isTrip(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readSchemeSet(), and de.dlr.ivf.tapas.constants.TPS_ActivityConstant.TPS_ActivityConstant().
map
final EnumMap<TPS_ActivityCodeType, TPS_InternalConstant<TPS_ActivityCodeType> > de.dlr.ivf.tapas.constants.TPS_ActivityConstant.map private
mapping enum TPS_ActivityCodeType to internal constant, i.e. its three properties (name, code, type)
Definition at line 56 of file TPS_ActivityConstant.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/constants/TPS_ActivityConstant.java