TAPAS: de.dlr.ivf.tapas.analyzer.core.Core Class Reference
de.dlr.ivf.tapas.analyzer.core.Core Class Reference
Public Member Functions
Core (String name, TPS_ParameterClass parameterClass)
void cancel ()
void run ()
void setCoreInput (CoreInputInterface input) throws IOException, ClassNotFoundException, SQLException
Static Public Member Functions
static String getRuntime ()
Private Member Functions
void setStartTime (long st)
Private Attributes
final Collection< CoreProcessInterface > modules = new HashSet<>()
boolean isCancelled
String outputPath = ""
TapasTripReader tripReader
final JTextPane cons = new JTextPane()
StyledDocument console = cons.getStyledDocument()
final TPS_ParameterClass parameterClass
Static Private Attributes
static long systemTime
Detailed Description
The main thread responsible for the processing of selected methods
Author
Marco
Definition at line 28 of file Core.java.
Constructor & Destructor Documentation
Core()
de.dlr.ivf.tapas.analyzer.core.Core.Core (String name, TPS_ParameterClass parameterClass)
Definition at line 43 of file Core.java.
References name, and de.dlr.ivf.tapas.analyzer.core.Core.parameterClass.
Member Function Documentation
cancel()
void de.dlr.ivf.tapas.analyzer.core.Core.cancel ()
Cancel all modules
Definition at line 61 of file Core.java.
References de.dlr.ivf.tapas.analyzer.core.Core.modules.
getRuntime()
static String de.dlr.ivf.tapas.analyzer.core.Core.getRuntime () static
return runtime in milliseconds
Returns
Definition at line 54 of file Core.java.
References de.dlr.ivf.tapas.analyzer.core.Core.systemTime.
Referenced by de.dlr.ivf.tapas.analyzer.core.Core.run().
run()
void de.dlr.ivf.tapas.analyzer.core.Core.run ()
Definition at line 70 of file Core.java.
References de.dlr.ivf.tapas.analyzer.core.Core.console, de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripReader.getIterator(), de.dlr.ivf.tapas.analyzer.core.Core.getRuntime(), de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripReader.getSource(), de.dlr.ivf.tapas.analyzer.core.Core.isCancelled, de.dlr.ivf.tapas.analyzer.core.Core.modules, de.dlr.ivf.tapas.analyzer.core.Core.outputPath, de.dlr.ivf.tapas.analyzer.core.Core.setStartTime(), and de.dlr.ivf.tapas.analyzer.core.Core.tripReader.
setCoreInput()
void de.dlr.ivf.tapas.analyzer.core.Core.setCoreInput (CoreInputInterface input) throws IOException, ClassNotFoundException, SQLException
übergibt die benötigten Inputdaten an Core. Die Methode holt sich alles was es brauch aus dem CoreInputInterface.
Parameters
input
Exceptions
IOException
SQLException
ClassNotFoundException
Definition at line 143 of file Core.java.
References de.dlr.ivf.tapas.analyzer.core.Core.console, de.dlr.ivf.tapas.analyzer.core.Core.outputPath, and de.dlr.ivf.tapas.analyzer.core.Core.tripReader.
Referenced by de.dlr.ivf.tapas.analyzer.gui.Control.createAndShowGUI().
setStartTime()
void de.dlr.ivf.tapas.analyzer.core.Core.setStartTime (long st) private
Definition at line 156 of file Core.java.
References de.dlr.ivf.tapas.analyzer.core.Core.systemTime.
Referenced by de.dlr.ivf.tapas.analyzer.core.Core.run().
Member Data Documentation
cons
final JTextPane de.dlr.ivf.tapas.analyzer.core.Core.cons = new JTextPane() private
Definition at line 39 of file Core.java.
console
StyledDocument de.dlr.ivf.tapas.analyzer.core.Core.console = cons.getStyledDocument() private
Definition at line 40 of file Core.java.
Referenced by de.dlr.ivf.tapas.analyzer.core.Core.run(), and de.dlr.ivf.tapas.analyzer.core.Core.setCoreInput().
isCancelled
boolean de.dlr.ivf.tapas.analyzer.core.Core.isCancelled private
Definition at line 34 of file Core.java.
Referenced by de.dlr.ivf.tapas.analyzer.core.Core.run().
modules
final Collection<CoreProcessInterface> de.dlr.ivf.tapas.analyzer.core.Core.modules = new HashSet<>() private
Definition at line 32 of file Core.java.
Referenced by de.dlr.ivf.tapas.analyzer.core.Core.cancel(), and de.dlr.ivf.tapas.analyzer.core.Core.run().
outputPath
String de.dlr.ivf.tapas.analyzer.core.Core.outputPath = "" private
Definition at line 36 of file Core.java.
Referenced by de.dlr.ivf.tapas.analyzer.core.Core.run(), and de.dlr.ivf.tapas.analyzer.core.Core.setCoreInput().
parameterClass
final TPS_ParameterClass de.dlr.ivf.tapas.analyzer.core.Core.parameterClass private
Definition at line 41 of file Core.java.
Referenced by de.dlr.ivf.tapas.analyzer.core.Core.Core().
systemTime
long de.dlr.ivf.tapas.analyzer.core.Core.systemTime static private
Definition at line 30 of file Core.java.
Referenced by de.dlr.ivf.tapas.analyzer.core.Core.getRuntime(), and de.dlr.ivf.tapas.analyzer.core.Core.setStartTime().
tripReader
TapasTripReader de.dlr.ivf.tapas.analyzer.core.Core.tripReader private
Definition at line 37 of file Core.java.
Referenced by de.dlr.ivf.tapas.analyzer.core.Core.run(), and de.dlr.ivf.tapas.analyzer.core.Core.setCoreInput().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/core/Core.java