TAPAS: de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor Class Reference
de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor Class Reference
Classes
class Location
Public Member Functions
void addLocationToAddressProcessing (Location entry)
void addLocationToRelocate (Location entry)
List< Location > getLocationsForAddressProcessing ()
List< Location > getLocationsForRelocation ()
boolean hasDuplicate (Location loc, int startSearchAt)
void loadHeaders (String headerString)
String locationToString (Location loc)
Static Public Member Functions
static void main (String[] args)
Private Attributes
final HashMap< Integer, String > headerMap = new HashMap<>()
int posOfIdColumn = -1
Detailed Description
Definition at line 21 of file LocationProcessor.java.
Member Function Documentation
addLocationToAddressProcessing()
void de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.addLocationToAddressProcessing (Location entry)
This method ads a location if it is corect initialized to the address filter list
Parameters
entry the location, which holds the data
Definition at line 227 of file LocationProcessor.java.
References de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.isCorrectInitialized().
Referenced by de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.main().
addLocationToRelocate()
void de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.addLocationToRelocate (Location entry)
This method ads a location if it is corect initialized to the relocation list
Parameters
entry the location, which holds the data
Definition at line 239 of file LocationProcessor.java.
References de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.isCorrectInitialized().
Referenced by de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.main().
getLocationsForAddressProcessing()
List<Location> de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.getLocationsForAddressProcessing ()
Returns the list of locations, where the housenumbers need to be processed
Returns
Definition at line 251 of file LocationProcessor.java.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.main().
getLocationsForRelocation()
List<Location> de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.getLocationsForRelocation ()
Returns the list of locations, where the location should be relocated
Returns
Definition at line 260 of file LocationProcessor.java.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.hasDuplicate(), and de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.main().
hasDuplicate()
boolean de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.hasDuplicate (Location loc, int startSearchAt)
Definition at line 265 of file LocationProcessor.java.
References de.dlr.ivf.tapas.tools.locationallocation.Constants.ENABLE_CHANGES_OF_MARCO, de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.getLocationsForRelocation(), and de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.isDuplicateImport().
Referenced by de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.main().
loadHeaders()
void de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.loadHeaders (String headerString)
Method to initialize the header tokens.
Parameters
headerString the header string of the csv-file
Definition at line 294 of file LocationProcessor.java.
References de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.posOfIdColumn.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.main().
locationToString()
String de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.locationToString (Location loc)
Definition at line 307 of file LocationProcessor.java.
References de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.getValue().
main()
static void de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.main (String[] args) static
Parameters
args 0: filename for input, 1: filename for output, 2: mode (process name, generate address), 3: db-config
Definition at line 35 of file LocationProcessor.java.
References de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.addLocationToAddressProcessing(), de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.addLocationToRelocate(), de.dlr.ivf.tapas.tools.locationallocation.Constants.ENABLE_CHANGES_OF_MARCO, de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.getID(), de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.getLocationsForAddressProcessing(), de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.getLocationsForRelocation(), de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.getStatus(), de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.getStreet(), de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.getStreetNumber(), de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.getValue(), de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.getZipCode(), de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.hasDuplicate(), de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.isCorrectInitialized(), de.dlr.ivf.tapas.tools.locationallocation.Locator.isInRegion(), de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.loadHeaders(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.loadRuntimeParameters(), de.dlr.ivf.tapas.tools.locationallocation.Locator.localizeLocation(), de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.locationToString(), de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.processStreet(), de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.replaceStreetTag(), de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.setCity(), de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.STATUS_NOT_DISTINCT_IN_DATABASE, and de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.updateValue().
Member Data Documentation
headerMap
final HashMap<Integer, String> de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.headerMap = new HashMap<>() private
local variable to store the header information
Definition at line 28 of file LocationProcessor.java.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.addValue(), de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.getValue(), de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.Location(), de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.locationToString(), de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.updateOrAddValue(), and de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.updateValue().
posOfIdColumn
int de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.posOfIdColumn = -1 private
Definition at line 29 of file LocationProcessor.java.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.getID(), de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.loadHeaders(), de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.Location(), and de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.setID().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/locationallocation/LocationProcessor.java