TAPAS: de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher Class Reference
de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher Class Reference
Public Member Functions
DBTripFetcher (BlockingQueue< TapasTrip > q, String simulation, String hhkey, String schema, String region, TPS_DB_Connector connection, boolean verbose) throws SQLException, IOException, ClassNotFoundException
String getSource ()
void run ()
Private Member Functions
boolean cleanDB ()
void close ()
boolean createTripTable () throws BadLocationException, SQLException
TapasTrip getTripFromResult (ResultSet rs)
Private Attributes
final String simulation
final String hhkey
final String schema
final String region
final boolean verbose
final TPS_DB_Connector dbCon
final PreparedStatement fetchNext
Statement fillTableStatement
int fetchStart = 0
final BlockingQueue< TapasTrip > queue
boolean isFinished = false
Detailed Description
This class is the actual connection to the database that uses a separate thread.
Author
boec_pa
Definition at line 248 of file DBTripReader.java.
Constructor & Destructor Documentation
DBTripFetcher()
de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.DBTripFetcher (BlockingQueue< TapasTrip > q, String simulation, String hhkey, String schema, String region, TPS_DB_Connector connection, boolean verbose) throws SQLException, IOException, ClassNotFoundException
Definition at line 267 of file DBTripReader.java.
References de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.dbCon, de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.fetchNext, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getParameters(), de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.hhkey, de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.initStart(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readSettlementSystemCodes(), de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.region, de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.schema, de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.simulation, de.dlr.ivf.tapas.util.FuncUtils.toRawSimKey, and de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.verbose.
Member Function Documentation
cleanDB()
boolean de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.cleanDB () private
Definition at line 302 of file DBTripReader.java.
References de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection(), de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.simulation, and de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.verbose.
Referenced by de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.createTripTable().
close()
void de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.close () private
Definition at line 331 of file DBTripReader.java.
References de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.dbCon, de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.fillTableStatement, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection(), and de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.simulation.
Referenced by de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.TripIterator.close(), and de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.run().
createTripTable()
boolean de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.createTripTable () throws BadLocationException, SQLException private
Definition at line 347 of file DBTripReader.java.
References de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.cleanDB(), de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.console, de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.dbCon, de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.fillTableStatement, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection(), de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.hhkey, de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.region, de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.schema, de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.simulation, de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.totaltripcount, and de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.verbose.
Referenced by de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.run().
getSource()
String de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.getSource ()
Definition at line 498 of file DBTripReader.java.
References de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.simulation.
Referenced by de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.TripIterator.getSource().
getTripFromResult()
TapasTrip de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.getTripFromResult (ResultSet rs) private
Definition at line 502 of file DBTripReader.java.
References de.dlr.ivf.tapas.constants.TPS_SettlementSystem.getCode(), de.dlr.ivf.tapas.constants.TPS_SettlementSystem.getSettlementSystem(), de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.settlementType, and de.dlr.ivf.tapas.constants.TPS_SettlementSystem.TPS_SettlementSystemType.TAPAS.
Referenced by de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.run().
run()
void de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.run ()
Definition at line 556 of file DBTripReader.java.
References de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.close(), de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.createTripTable(), de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.FETCH_SIZE, de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.fetchNext, de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.fetchStart, de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.getTripFromResult(), de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.isCancelled, de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.isFinished, de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.pcs, de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.POISON_INSTANCE, and de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.queue.
Member Data Documentation
dbCon
final TPS_DB_Connector de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.dbCon private
Definition at line 256 of file DBTripReader.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.cleanDB(), de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.close(), de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.createTripTable(), and de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.DBTripFetcher().
fetchNext
final PreparedStatement de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.fetchNext private
Definition at line 258 of file DBTripReader.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.DBTripFetcher(), and de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.run().
fetchStart
int de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.fetchStart = 0 private
Definition at line 261 of file DBTripReader.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.run().
fillTableStatement
Statement de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.fillTableStatement private
Definition at line 259 of file DBTripReader.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.close(), and de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.createTripTable().
hhkey
final String de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.hhkey private
Definition at line 251 of file DBTripReader.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.createTripTable(), and de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.DBTripFetcher().
isFinished
boolean de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.isFinished = false private
Definition at line 265 of file DBTripReader.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.run().
queue
final BlockingQueue<TapasTrip> de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.queue private
Definition at line 263 of file DBTripReader.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.run().
region
final String de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.region private
Definition at line 253 of file DBTripReader.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.createTripTable(), and de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.DBTripFetcher().
schema
final String de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.schema private
Definition at line 252 of file DBTripReader.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.createTripTable(), and de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.DBTripFetcher().
simulation
final String de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.simulation private
Definition at line 250 of file DBTripReader.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.cleanDB(), de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.close(), de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.createTripTable(), de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.DBTripFetcher(), and de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.getSource().
verbose
final boolean de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.verbose private
Definition at line 254 of file DBTripReader.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.cleanDB(), de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.createTripTable(), and de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.DBTripFetcher().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/tum/databaseConnector/DBTripReader.java