TAPAS: de.dlr.ivf.tapas.log.TPS_Logger Class Reference
de.dlr.ivf.tapas.log.TPS_Logger Class Reference
Classes
class LogItem
Static Public Member Functions
static void closeLoggers ()
static boolean isLogging (Class<?> callerClass, HierarchyLogLevel hLog, SeverenceLogLevel sLog)
static boolean isLogging (Class<?> callerClass, SeverenceLogLevel sLog)
static boolean isLogging (HierarchyLogLevel hLog, SeverenceLogLevel sLog)
static boolean isLogging (SeverenceLogLevel sLog)
static void log (Class<?> callerClass, HierarchyLogLevel hLog, SeverenceLogLevel sLog, String text)
static void log (Class<?> callerClass, HierarchyLogLevel hLog, SeverenceLogLevel sLog, String text, Throwable throwable)
static void log (Class<?> callerClass, SeverenceLogLevel sLog, String text)
static void log (Class<?> callerClass, SeverenceLogLevel sLog, String text, Throwable throwable)
static void log (HierarchyLogLevel hLog, SeverenceLogLevel sLog, String text)
static void log (HierarchyLogLevel hLog, SeverenceLogLevel sLog, String text, Throwable throwable)
static void log (SeverenceLogLevel sLog, String text)
static void log (SeverenceLogLevel sLog, Exception e)
static void log (SeverenceLogLevel sLog, String text, Throwable throwable)
static void setLoggingClass (String loggingClass, TPS_ParameterClass parameterClass)
static boolean shallBeLogged (SeverenceLogLevel sLog)
Returns whether the given severence level messages shall be logged.
static boolean shallBeLogged (HierarchyLogLevel hLog)
Returns whether the given hierarchy level messages shall be logged.
Static Private Member Functions
static Class<?> getCallerClass ()
static HierarchyLogLevel getHierarchyLogLevel (Class<?> callerClass)
Static Private Attributes
static List< LogItem > LOG_ITEMS = new LinkedList<>()
static HierarchyLogLevel HIERARCHY_LOG_LEVEL_MASK
static SeverenceLogLevel SEVERENCE_LOG_LEVEL_MASK
static TPS_LoggingInterface LOGGING
Detailed Description
Basic class for the TAPAS loging functionality.
Author
hein_mh
Definition at line 24 of file TPS_Logger.java.
Member Function Documentation
closeLoggers()
static void de.dlr.ivf.tapas.log.TPS_Logger.closeLoggers () static
Definition at line 34 of file TPS_Logger.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.closeLogger(), and de.dlr.ivf.tapas.log.TPS_Logger.LOGGING.
Referenced by de.dlr.ivf.tapas.TPS_Main.run().
getCallerClass()
static Class<?> de.dlr.ivf.tapas.log.TPS_Logger.getCallerClass () static private
Method to return the calling class for this function.
Returns
The calling class.
Definition at line 43 of file TPS_Logger.java.
Referenced by de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), and de.dlr.ivf.tapas.log.TPS_Logger.log().
getHierarchyLogLevel()
static HierarchyLogLevel de.dlr.ivf.tapas.log.TPS_Logger.getHierarchyLogLevel (Class<?> callerClass) static private
Method to get the default HierarchyLogLevel for the provided class. This is set by the "LogHierarchy(hierarchyLogLevel = HierarchyLogLevel.EPISODE)" tag on top of the classes. If the tag is missing HierarchyLogLevel.ALL is returned to avoid a NullPointerException during logging.
Parameters
callerClass The calling class
Returns
The specified HierarchyLogLevel
Definition at line 67 of file TPS_Logger.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.HierarchyLogLevel.ALL, and de.dlr.ivf.tapas.log.LogHierarchy.hierarchyLogLevel().
Referenced by de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), and de.dlr.ivf.tapas.log.TPS_Logger.log().
isLogging() [1/4]
static boolean de.dlr.ivf.tapas.log.TPS_Logger.isLogging (Class<?> callerClass, HierarchyLogLevel hLog, SeverenceLogLevel sLog) static
Method to check if logging is enabled for the given parameters.
Parameters
callerClass The calling Class
hLog The HierarchyLogLevel
sLog The SeverenceLogLevel
Returns
true if logging is enabled for the given combination
Definition at line 84 of file TPS_Logger.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.isLogging(), de.dlr.ivf.tapas.log.TPS_Logger.LOGGING, and de.dlr.ivf.tapas.log.TPS_Logger.shallBeLogged().
Referenced by de.dlr.ivf.tapas.util.Timeline.add(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.addPersonToHousehold(), de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree.applyExpertKnowledge(), de.dlr.ivf.tapas.plan.acceptance.TPS_PlanEVA1Acceptance.calculateAcceptanceProbBudgetConstraints(), de.dlr.ivf.tapas.plan.acceptance.TPS_PlanEVA1Acceptance.calculateAcceptanceProbTimeConstraints(), de.dlr.ivf.tapas.loc.TPS_Region.calculateVOTadds(), de.dlr.ivf.tapas.person.TPS_Worker.call(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.checkParameters(), de.dlr.ivf.tapas.persistence.io.TPS_FileConsumer.consumeFile(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.consumeParameter(), de.dlr.ivf.tapas.person.TPS_Worker.createPersonPlans(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.createTemporaryAndOutputTables(), de.dlr.ivf.tapas.util.TPS_TripDeleter.deleteHouseholdsFromTriptable(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.fetchNextSetOfHouseholds(), de.dlr.ivf.tapas.scheme.TPS_SchemeSet.findScheme(), de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixed.getDistributionSet(), de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixedBS.getDistributionSet(), de.dlr.ivf.tapas.modechoice.TPS_UtilityMNL.getDistributionSet(), de.dlr.ivf.tapas.loc.TPS_FocusPointModel.getFocusPoint(), de.dlr.ivf.tapas.loc.TPS_MultipleTAZRepresentant.getLocationRepresentatives(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.getNextHousehold(), de.dlr.ivf.tapas.mode.TPS_MassTransportMode.getScore(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.init(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.insertTrips(), de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), de.dlr.ivf.tapas.plan.acceptance.TPS_PlanEVA1Acceptance.isPlanAcceptedByOverallTravelTime(), de.dlr.ivf.tapas.runtime.util.WindowsProcessHandler.killProcess(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.load(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.loadHouseholds(), de.dlr.ivf.tapas.iteration.TPS_VisumConverter.mergeMatrices(), de.dlr.ivf.tapas.iteration.TPS_VisumConverter.mergeMatrixPair(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.mergeMatrixPair(), de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.normalize(), de.dlr.ivf.tapas.person.TPS_Worker.processHousehold(), de.dlr.ivf.tapas.util.TPS_TripDeleter.putHHID(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.readCSVFile(), de.dlr.ivf.tapas.iteration.TPS_VisumConverter.readCSVFile(), de.dlr.ivf.tapas.tools.TPS_VisumOD2DB.readCSVFile(), de.dlr.ivf.scripts.SumoTripVisualization.readFile(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.readIDMap(), de.dlr.ivf.tapas.iteration.TPS_VisumConverter.readIDMap(), de.dlr.ivf.tapas.tools.TPS_VisumOD2DB.readIDMap(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readRegion(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.readRuntimeParametersFromDB(), de.dlr.ivf.tapas.iteration.TPS_IterationManagement.resetPlansForRecalculation(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.resetUnfinishedHouseholds(), de.dlr.ivf.tapas.TPS_Main.run(), de.dlr.ivf.tapas.plan.TPS_LocatedStay.selectLocation(), de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes(), de.dlr.ivf.tapas.mode.TPS_ModeSet.selectMode0(), de.dlr.ivf.tapas.iteration.TPS_AcceptanceIterationManager.selectPlansForRecalculation(), de.dlr.ivf.tapas.iteration.TPS_BasicIterationManager.selectPlansForRecalculation(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.storeFinishedHouseholdIDsToDB(), de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.storeInDB(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.storeInDB(), de.dlr.ivf.tapas.iteration.TPS_VisumConverter.storeIntraInfos(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.storeLocationOccupanyInDB(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.updateOccupancyTable(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.updateParameter(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.vacuumTempTables(), de.dlr.ivf.tapas.runtime.sumoDaemon.SumoMatrixImporter.writeMatrix(), and de.dlr.ivf.tapas.iteration.TPS_VisumConverter.writeODMatrices().
isLogging() [2/4]
static boolean de.dlr.ivf.tapas.log.TPS_Logger.isLogging (Class<?> callerClass, SeverenceLogLevel sLog) static
Definition at line 93 of file TPS_Logger.java.
References de.dlr.ivf.tapas.log.TPS_Logger.getHierarchyLogLevel(), de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), and de.dlr.ivf.tapas.log.TPS_Logger.shallBeLogged().
isLogging() [3/4]
static boolean de.dlr.ivf.tapas.log.TPS_Logger.isLogging (HierarchyLogLevel hLog, SeverenceLogLevel sLog) static
Method to check if logging is enabled for the calling class with the given parameters.
Parameters
hLog The HierarchyLogLevel
sLog The SeverenceLogLevel
Returns
true if logging is enabled for the given combination
Definition at line 107 of file TPS_Logger.java.
References de.dlr.ivf.tapas.log.TPS_Logger.getCallerClass(), de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), and de.dlr.ivf.tapas.log.TPS_Logger.shallBeLogged().
isLogging() [4/4]
static boolean de.dlr.ivf.tapas.log.TPS_Logger.isLogging (SeverenceLogLevel sLog) static
Method to check if logging is enabled for the calling class at the default HierarchyLogLevel with the given SeverenceLogLevel.
Parameters
sLog The SeverenceLogLevel
Returns
true if logging is enabled for the given combination
Definition at line 120 of file TPS_Logger.java.
References de.dlr.ivf.tapas.log.TPS_Logger.getCallerClass(), de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), and de.dlr.ivf.tapas.log.TPS_Logger.shallBeLogged().
log() [1/9]
static void de.dlr.ivf.tapas.log.TPS_Logger.log (Class<?> callerClass, HierarchyLogLevel hLog, SeverenceLogLevel sLog, String text) static
Definition at line 128 of file TPS_Logger.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.log(), de.dlr.ivf.tapas.log.TPS_Logger.LOG_ITEMS, de.dlr.ivf.tapas.log.TPS_Logger.LOGGING, and de.dlr.ivf.tapas.log.TPS_Logger.shallBeLogged().
Referenced by de.dlr.ivf.tapas.util.Timeline.add(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.addPersonToHousehold(), de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree.applyExpertKnowledge(), de.dlr.ivf.tapas.plan.TPS_Plan.balanceStarts(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.batchStoreTrips(), de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.binarySearch(), de.dlr.ivf.tapas.iteration.TPS_VisumConverter.calcMinMaxValue(), de.dlr.ivf.tapas.plan.acceptance.TPS_PlanEVA1Acceptance.calculateAcceptanceProbBudgetConstraints(), de.dlr.ivf.tapas.plan.acceptance.TPS_PlanEVA1Acceptance.calculateAcceptanceProbTimeConstraints(), de.dlr.ivf.tapas.iteration.TPS_IterationManagement.calculatePlanDerivation(), de.dlr.ivf.tapas.loc.TPS_Region.calculateVOTadds(), de.dlr.ivf.tapas.person.TPS_Worker.call(), de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.catMatchingCSVImport(), de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.change(), de.dlr.ivf.tapas.iteration.TPS_VisumConverter.checkIntraInfos(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.checkMatrixName(), de.dlr.ivf.tapas.iteration.TPS_VisumConverter.checkMatrixName(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.checkParameters(), de.dlr.ivf.tapas.runtime.util.ClientControlProperties.ClientControlProperties(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.closeConnections(), de.dlr.ivf.tapas.persistence.io.TPS_FileConsumer.consumeFile(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.consumeParameter(), de.dlr.ivf.tapas.person.TPS_Worker.createPersonPlans(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.createTemporaryAndOutputTables(), de.dlr.ivf.tapas.runtime.util.DaemonControlProperties.DaemonControlProperties(), de.dlr.ivf.tapas.util.TPS_TripDeleter.deleteHouseholdsFromTriptable(), de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.draw(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeUpdate(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.fetchNextSetOfHouseholds(), de.dlr.ivf.tapas.runtime.util.WindowsProcessHandler.findProcess(), de.dlr.ivf.tapas.scheme.TPS_SchemeSet.findScheme(), de.dlr.ivf.tapas.TPS_Main.finish(), de.dlr.ivf.tapas.loc.TPS_CFN.getCFN4Value(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection(), de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixed.getDistributionSet(), de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixedBS.getDistributionSet(), de.dlr.ivf.tapas.modechoice.TPS_UtilityMNL.getDistributionSet(), de.dlr.ivf.tapas.loc.TPS_FocusPointModel.getFocusPoint(), de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.getKey(), de.dlr.ivf.tapas.loc.TPS_MultipleTAZRepresentant.getLocationRepresentatives(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.getNextHousehold(), de.dlr.ivf.tapas.mode.TPS_MassTransportMode.getScore(), de.dlr.ivf.tapas.mode.TPS_IndividualTransportMode.getTravelTime(), de.dlr.ivf.tapas.mode.TPS_MassTransportMode.getTravelTime(), de.dlr.ivf.tapas.runtime.util.CPUUsage.getWMIC(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.init(), de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.init(), de.dlr.ivf.tapas.loc.TPS_Region.initLocationChoiceSet(), de.dlr.ivf.tapas.loc.TPS_Region.initLocationSelectModel(), de.dlr.ivf.tapas.mode.TPS_Mode.initUtilityFunction(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.insertTrips(), de.dlr.ivf.tapas.plan.acceptance.TPS_PlanEVA1Acceptance.isPlanAcceptedByOverallTravelTime(), de.dlr.ivf.tapas.runtime.util.WindowsProcessHandler.killProcess(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.load(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.loadHouseholds(), de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.util.MatrixMap.logStatistics(), de.dlr.ivf.tapas.util.MatrixMap.MatrixMap(), de.dlr.ivf.tapas.iteration.TPS_VisumConverter.mergeMatrices(), de.dlr.ivf.tapas.iteration.TPS_VisumConverter.mergeMatrixPair(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.mergeMatrixPair(), de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.normalize(), de.dlr.ivf.tapas.person.TPS_Worker.processHousehold(), de.dlr.ivf.tapas.util.TPS_TripDeleter.putHHID(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readActivity2LocationCodes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readActivityConstantCodes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readAgeClassCodes(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.readAllParis(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readCarCodes(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.readCSVFile(), de.dlr.ivf.tapas.iteration.TPS_VisumConverter.readCSVFile(), de.dlr.ivf.tapas.tools.TPS_VisumOD2DB.readCSVFile(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readDistanceCodes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readDrivingLicenseCodes(), de.dlr.ivf.scripts.SumoTripVisualization.readFile(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.readIDMap(), de.dlr.ivf.tapas.iteration.TPS_VisumConverter.readIDMap(), de.dlr.ivf.tapas.tools.TPS_VisumOD2DB.readIDMap(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readIncomeCodes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readLocationConstantCodes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readMatrices(), de.dlr.ivf.tapas.iteration.TPS_VisumConverter.readMatrix(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.readMatrix(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readMatrix(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.readMatrixFromDB(), de.dlr.ivf.tapas.iteration.TPS_VisumConverter.readMatrixFromDB(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.readMatrixMap(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.readMatrixMap(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readModes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.readParameter(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readPersonGroupCodes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readRegion(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.readRuntimeParametersFromDB(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readSettlementSystemCodes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readSexCodes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readVariableMap(), de.dlr.ivf.tapas.iteration.TPS_IterationManagement.resetPlansForRecalculation(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.resetUnfinishedHouseholds(), de.dlr.ivf.tapas.runtime.util.ProcessHandler.run(), de.dlr.ivf.tapas.runtime.util.ProcessHandler.ProcesshandlerThread.run(), de.dlr.ivf.tapas.TPS_Main.run(), de.dlr.ivf.tapas.plan.TPS_LocatedStay.selectLocation(), de.dlr.ivf.tapas.loc.TPS_Region.selectLocation(), de.dlr.ivf.tapas.loc.TPS_SelectLocationWeightBased.selectLocationFromChoiceSet(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.selectLocationFromChoiceSet(), de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes(), de.dlr.ivf.tapas.mode.TPS_ModeSet.selectMode(), de.dlr.ivf.tapas.mode.TPS_ModeSet.selectMode0(), de.dlr.ivf.tapas.iteration.TPS_AcceptanceIterationManager.selectPlansForRecalculation(), de.dlr.ivf.tapas.iteration.TPS_BasicIterationManager.selectPlansForRecalculation(), de.dlr.ivf.tapas.log.TPS_Logger.setLoggingClass(), de.dlr.ivf.tapas.util.parameters.ParamMatrixClass.setMatrix(), de.dlr.ivf.tapas.util.parameters.ParamMatrixMapClass.setMatrixMap(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.setValue(), de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.setValues(), de.dlr.ivf.tapas.persistence.io.TPS_FileConsumer.start(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.storeFinishedHouseholdIDsToDB(), de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.storeInDB(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.storeInDB(), de.dlr.ivf.tapas.iteration.TPS_VisumConverter.storeIntraInfos(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.storeLocationOccupanyInDB(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.storeMatrixMap(), de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.sum(), de.dlr.ivf.tapas.TPS_Main.TPS_Main(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.TPS_SumoConverter(), de.dlr.ivf.tapas.iteration.TPS_VisumConverter.TPS_VisumConverter(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.updateOccupancyTable(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.updateParameter(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.vacuumTempTables(), de.dlr.ivf.tapas.runtime.sumoDaemon.SumoMatrixImporter.writeMatrix(), de.dlr.ivf.tapas.iteration.TPS_VisumConverter.writeODMatrices(), and de.dlr.ivf.tapas.iteration.TPS_SumoConverter.writeTripFile().
log() [2/9]
static void de.dlr.ivf.tapas.log.TPS_Logger.log (Class<?> callerClass, HierarchyLogLevel hLog, SeverenceLogLevel sLog, String text, Throwable throwable) static
Definition at line 138 of file TPS_Logger.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.includes(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.log(), de.dlr.ivf.tapas.log.TPS_Logger.LOG_ITEMS, de.dlr.ivf.tapas.log.TPS_Logger.LOGGING, de.dlr.ivf.tapas.log.TPS_Logger.SEVERENCE_LOG_LEVEL_MASK, and de.dlr.ivf.tapas.log.TPS_Logger.shallBeLogged().
log() [3/9]
static void de.dlr.ivf.tapas.log.TPS_Logger.log (Class<?> callerClass, SeverenceLogLevel sLog, String text) static
Method to log an info.
Parameters
callerClass The calling class
sLog The SeverenceLogLevel
text The text to log
Definition at line 161 of file TPS_Logger.java.
References de.dlr.ivf.tapas.log.TPS_Logger.getHierarchyLogLevel(), de.dlr.ivf.tapas.log.TPS_Logger.log(), and de.dlr.ivf.tapas.log.TPS_Logger.shallBeLogged().
log() [4/9]
static void de.dlr.ivf.tapas.log.TPS_Logger.log (Class<?> callerClass, SeverenceLogLevel sLog, String text, Throwable throwable) static
Method to log an info and parse an Exception.
Parameters
callerClass The calling class
sLog The SeverenceLogLevel
text The text to log
throwable The exception to log
Definition at line 176 of file TPS_Logger.java.
References de.dlr.ivf.tapas.log.TPS_Logger.getHierarchyLogLevel(), de.dlr.ivf.tapas.log.TPS_Logger.log(), and de.dlr.ivf.tapas.log.TPS_Logger.shallBeLogged().
log() [5/9]
static void de.dlr.ivf.tapas.log.TPS_Logger.log (HierarchyLogLevel hLog, SeverenceLogLevel sLog, String text) static
Method to log an info.
Parameters
hLog The HierarchyLogLevel
sLog The SeverenceLogLevel
text The text to log
Definition at line 190 of file TPS_Logger.java.
References de.dlr.ivf.tapas.log.TPS_Logger.getCallerClass(), de.dlr.ivf.tapas.log.TPS_Logger.log(), and de.dlr.ivf.tapas.log.TPS_Logger.shallBeLogged().
log() [6/9]
static void de.dlr.ivf.tapas.log.TPS_Logger.log (HierarchyLogLevel hLog, SeverenceLogLevel sLog, String text, Throwable throwable) static
Method to log an info and parse an Exception.
Parameters
hLog The HierarchyLogLevel
sLog The SeverenceLogLevel
text The text to log
throwable The exception to log
Definition at line 205 of file TPS_Logger.java.
References de.dlr.ivf.tapas.log.TPS_Logger.getCallerClass(), de.dlr.ivf.tapas.log.TPS_Logger.log(), and de.dlr.ivf.tapas.log.TPS_Logger.shallBeLogged().
log() [7/9]
static void de.dlr.ivf.tapas.log.TPS_Logger.log (SeverenceLogLevel sLog, Exception e) static
Method to log an info and parse an Exception.
Parameters
sLog The SeverenceLogLevel
e The exception to log
Definition at line 234 of file TPS_Logger.java.
References de.dlr.ivf.tapas.log.TPS_Logger.getCallerClass(), de.dlr.ivf.tapas.log.TPS_Logger.log(), and de.dlr.ivf.tapas.log.TPS_Logger.shallBeLogged().
log() [8/9]
static void de.dlr.ivf.tapas.log.TPS_Logger.log (SeverenceLogLevel sLog, String text) static
Method to log an info.
Parameters
sLog The SeverenceLogLevel
text The text to log
Definition at line 221 of file TPS_Logger.java.
References de.dlr.ivf.tapas.log.TPS_Logger.getCallerClass(), de.dlr.ivf.tapas.log.TPS_Logger.log(), and de.dlr.ivf.tapas.log.TPS_Logger.shallBeLogged().
log() [9/9]
static void de.dlr.ivf.tapas.log.TPS_Logger.log (SeverenceLogLevel sLog, String text, Throwable throwable) static
Method to log an info and parse an Exception.
Parameters
sLog The SeverenceLogLevel
text The text to log
throwable The exception to log
Definition at line 249 of file TPS_Logger.java.
References de.dlr.ivf.tapas.log.TPS_Logger.getCallerClass(), de.dlr.ivf.tapas.log.TPS_Logger.log(), and de.dlr.ivf.tapas.log.TPS_Logger.shallBeLogged().
setLoggingClass()
static void de.dlr.ivf.tapas.log.TPS_Logger.setLoggingClass (String loggingClass, TPS_ParameterClass parameterClass) static
This method sets a new instance of the logging class.
Parameters
loggingClass The Class, which holds the logging functionality.
parameterClass parameter class reference
Definition at line 262 of file TPS_Logger.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.HierarchyLogLevel.CLIENT, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.log.TPS_Logger.HIERARCHY_LOG_LEVEL_MASK, de.dlr.ivf.tapas.util.parameters.ParamString.HIERARCHY_LOG_LEVEL_MASK, de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.log.TPS_Logger.LOG_ITEMS, de.dlr.ivf.tapas.log.TPS_Logger.LOGGING, de.dlr.ivf.tapas.log.TPS_Logger.SEVERENCE_LOG_LEVEL_MASK, de.dlr.ivf.tapas.util.parameters.ParamString.SEVERENCE_LOG_LEVEL_MASK, and de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.WARN.
Referenced by de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.loadRuntimeParameters(), and de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.readRuntimeParametersFromDB().
shallBeLogged() [1/2]
static boolean de.dlr.ivf.tapas.log.TPS_Logger.shallBeLogged (HierarchyLogLevel hLog) static
Returns whether the given hierarchy level messages shall be logged.
Definition at line 294 of file TPS_Logger.java.
References de.dlr.ivf.tapas.log.TPS_Logger.HIERARCHY_LOG_LEVEL_MASK, and de.dlr.ivf.tapas.log.TPS_LoggingInterface.HierarchyLogLevel.includes().
shallBeLogged() [2/2]
static boolean de.dlr.ivf.tapas.log.TPS_Logger.shallBeLogged (SeverenceLogLevel sLog) static
Returns whether the given severence level messages shall be logged.
Definition at line 287 of file TPS_Logger.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.includes(), and de.dlr.ivf.tapas.log.TPS_Logger.SEVERENCE_LOG_LEVEL_MASK.
Referenced by de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), and de.dlr.ivf.tapas.log.TPS_Logger.log().
Member Data Documentation
HIERARCHY_LOG_LEVEL_MASK
HierarchyLogLevel de.dlr.ivf.tapas.log.TPS_Logger.HIERARCHY_LOG_LEVEL_MASK static private
Definition at line 30 of file TPS_Logger.java.
Referenced by de.dlr.ivf.tapas.log.TPS_Logger.setLoggingClass(), and de.dlr.ivf.tapas.log.TPS_Logger.shallBeLogged().
LOG_ITEMS
List<LogItem> de.dlr.ivf.tapas.log.TPS_Logger.LOG_ITEMS = new LinkedList<>() static private
The list with the items to log
Definition at line 29 of file TPS_Logger.java.
Referenced by de.dlr.ivf.tapas.log.TPS_Logger.log(), and de.dlr.ivf.tapas.log.TPS_Logger.setLoggingClass().
LOGGING
TPS_LoggingInterface de.dlr.ivf.tapas.log.TPS_Logger.LOGGING static private
Definition at line 32 of file TPS_Logger.java.
Referenced by de.dlr.ivf.tapas.log.TPS_Logger.closeLoggers(), de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), de.dlr.ivf.tapas.log.TPS_Logger.log(), and de.dlr.ivf.tapas.log.TPS_Logger.setLoggingClass().
SEVERENCE_LOG_LEVEL_MASK
SeverenceLogLevel de.dlr.ivf.tapas.log.TPS_Logger.SEVERENCE_LOG_LEVEL_MASK static private
Definition at line 31 of file TPS_Logger.java.
Referenced by de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.log.TPS_Logger.setLoggingClass(), and de.dlr.ivf.tapas.log.TPS_Logger.shallBeLogged().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/log/TPS_Logger.java