TAPAS: de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass Class Reference
de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass Class Reference
Public Member Functions
TPS_ParameterClass ()
void checkParameters ()
void clear ()
void deleteInDB (Connection con, String sim_key, Map< String, String > params) throws SQLException
void generateTemporaryParameters ()
double getDoubleValue (ParamValue param)
int getIntValue (ParamValue param)
long getLongValue (ParamValue param)
Matrix getMatrix (ParamMatrix param)
SimulationType getSimulationType ()
String getString (ParamString param)
ParamType getType (ParamString param)
ParamType getType (ParamValue param)
ParamType getType (ParamFlag param)
ParamType getType (ParamMatrix param)
ParamType getType (ParamMatrixMap param)
boolean isDefined (ParamFlag param)
boolean isDefined (ParamString param)
boolean isDefined (ParamValue param)
boolean isDefined (ParamMatrix param)
boolean isDefined (ParamMatrixMap param)
boolean isFalse (ParamFlag param)
boolean isTrue (ParamFlag param)
void loadRuntimeParameters (File runPropertiesFile) throws IOException
void loadSingleParameterFile (File propertiesFile) throws FileNotFoundException, IOException
void print ()
void readRuntimeParametersFromDB (ResultSet rs) throws SQLException
void revertTemporaryParameters ()
void setFlag (ParamFlag param, boolean flag)
void setMatrix (ParamMatrix param, Matrix matrix)
void setMatrix (ParamMatrix param, Matrix matrix, SimulationType simType)
void setString (ParamString param, String str)
boolean setValue (String key, String value)
void setValue (ParamValue param, int val)
void setValue (ParamValue param, double val)
void setValue (ParamValue param, float val)
void setValue (ParamValue param, long val)
void setValue (ParamValue param, Number val)
void updateInDB (Connection con, String sim_key, Map< String, String > params) throws SQLException
void writeToDB (Connection con, String sim_key, Map< String, String > params) throws SQLException
Public Attributes
String BIN_DIR
String INPUT_DIR
String OUTPUT_DIR
String SIM_DIR
String LOG_DIR = "Log/"
ParamFlagClass paramFlagClass
ParamValueClass paramValueClass
ParamMatrixClass paramMatrixClass
ParamMatrixMapClass paramMatrixMapClass
ParamStringClass paramStringClass
Private Member Functions
void checkPath (ParamString param)
void checkSchema (ParamString param)
boolean consumeParameter (File currentPath, String key, String value, EnumSet< ParamFlag > flagSet, EnumSet< ParamString > stringSet, EnumSet< ParamValue > valueSet)
void load (File currentPath, File propertiesFile, EnumSet< ParamFlag > flagSet, EnumSet< ParamString > stringSet, EnumSet< ParamValue > valueSet) throws FileNotFoundException, IOException
String replaceSeparator (String string)
boolean updateParameter (String key, String value, EnumSet< ParamFlag > flagSet, EnumSet< ParamString > stringSet, EnumSet< ParamValue > valueSet)
Private Attributes
final Stack< File > parameterFiles
Detailed Description
This class provides all constants which are available in the application
Definition at line 34 of file TPS_ParameterClass.java.
Constructor & Destructor Documentation
TPS_ParameterClass()
de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.TPS_ParameterClass ()
Constructor of TPS_ParameterClass calls the inner classes ParamFlagClass, ParamValueClass, ParamMatrixClass, ParamMatrixMapClass, ParamStringClass which are container classes for the corresponding parameter enums TPS_Param*
Definition at line 77 of file TPS_ParameterClass.java.
Member Function Documentation
checkParameters()
void de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.checkParameters ()
Method to check uninitialised parameters. Uninitialised parameters are reported via the logging function.
Definition at line 95 of file TPS_ParameterClass.java.
References de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.util.parameters.ParamType.OPTIONAL, and de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.WARN.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.readRuntimeParametersFromDB(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.TPS_SumoConverter(), and de.dlr.ivf.tapas.iteration.TPS_VisumConverter.TPS_VisumConverter().
checkPath()
void de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.checkPath (ParamString param) private
Checks if the path is in the correct format and corrects it if necessary.
Parameters
param the ParamString to check.
Definition at line 132 of file TPS_ParameterClass.java.
checkSchema()
void de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.checkSchema (ParamString param) private
Checks if the given ParamString has the correct db-schema format, which means, it should end with a dot.
Parameters
param The parameter to check
Definition at line 147 of file TPS_ParameterClass.java.
clear()
void de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.clear ()
Clears all attached parameters
Definition at line 158 of file TPS_ParameterClass.java.
consumeParameter()
boolean de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.consumeParameter (File currentPath, String key, String value, EnumSet< ParamFlag > flagSet, EnumSet< ParamString > stringSet, EnumSet< ParamValue > valueSet) private
This method processes exactly one parameter and its given value. It returns true if the parameter is successfully consumed
Parameters
currentPath the path for other files, leave null if the parameters are read from the database
key the parameter name for the value
value the parameter value
flagSet set with all instances of ParamFlag, which are not defined yet
stringSet set with all instances of ParamString, which are not defined yet
valueSet set with all instances of ParamValue, which are not defined yet
Returns
true, if successful
Exceptions
FileNotFoundException This exception is thrown if the fiel is not found
IOException This exception is thrown if there occurs a read error
Definition at line 220 of file TPS_ParameterClass.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.DEBUG, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.util.parameters.ParamString.FILE_PARENT_PROPERTIES, de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.util.parameters.ParamValueClass.setValue(), and de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.WARN.
deleteInDB()
void de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.deleteInDB (Connection con, String sim_key, Map< String, String > params) throws SQLException
Deletes all given parameters in the table "simulation_parameters" for which the simulation-identifier is sim_key.
Definition at line 331 of file TPS_ParameterClass.java.
generateTemporaryParameters()
void de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.generateTemporaryParameters ()
Method to generate some temporary parameters for this run. It generates tablenames and the Filesystem directories for this run.
Definition at line 352 of file TPS_ParameterClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamStringClass.add(), de.dlr.ivf.tapas.util.parameters.ParamString.DB_SCHEMA_CORE, de.dlr.ivf.tapas.util.parameters.ParamString.DB_SCHEMA_TEMP, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_HOUSEHOLD_TMP, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_LOCATION_TMP, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_TRIPS, de.dlr.ivf.tapas.util.parameters.ParamString.PATH_ABS_INPUT, de.dlr.ivf.tapas.util.parameters.ParamString.PATH_ABS_OUTPUT, de.dlr.ivf.tapas.util.parameters.ParamString.PATH_ABS_PROPERTIES, and de.dlr.ivf.tapas.util.parameters.ParamString.RUN_IDENTIFIER.
Referenced by de.dlr.ivf.tapas.tools.TPS_VisumToDB.main().
getDoubleValue()
double de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getDoubleValue (ParamValue param)
Definition at line 397 of file TPS_ParameterClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamValueClass.getDoubleValue().
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.addPersonToHousehold(), de.dlr.ivf.tapas.plan.acceptance.TPS_PlanEVA1Acceptance.calculateAcceptanceProbBudgetConstraints(), de.dlr.ivf.tapas.plan.acceptance.TPS_PlanEVA1Acceptance.calculateAcceptanceProbTimeConstraints(), de.dlr.ivf.tapas.loc.TPS_Location.TPS_LocationData.calculateWeight(), de.dlr.ivf.tapas.tools.fileModifier.persistence.TPS_ParameterXLSDAO.convert(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverter.convert(), de.dlr.ivf.tapas.scheme.TPS_TourPart.TravelDurations.getArrivalDuration(), de.dlr.ivf.tapas.person.TPS_Car.getCostPerKilometer(), de.dlr.ivf.tapas.scheme.TPS_TourPart.TravelDurations.getDepartureDuration(), de.dlr.ivf.tapas.util.TPS_Geometrics.getDistance(), de.dlr.ivf.tapas.loc.TPS_MultipleTAZRepresentant.getLocationRepresentatives(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.getLogSum(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.getTrafficAnalysisZonesAround(), de.dlr.ivf.tapas.mode.TPS_IndividualTransportMode.getTravelTime(), de.dlr.ivf.tapas.mode.TPS_NonMotorisedMode.getTravelTime(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessMode.getTravelTime(), de.dlr.ivf.tapas.loc.TPS_SelectWithSingleAccessMode.getTravelTime(), de.dlr.ivf.tapas.person.TPS_Car.getVariableCostPerKilometer(), de.dlr.ivf.tapas.person.TPS_Car.init(), de.dlr.ivf.tapas.plan.acceptance.TPS_PlanEVA1Acceptance.isPlanAcceptedByOverallTravelTime(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.loadHouseholds(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readRegion(), de.dlr.ivf.tapas.person.TPS_Car.refuelCar(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverter.save(), de.dlr.ivf.tapas.loc.TPS_SelectLocationWeightBased.selectLocationFromChoiceSet(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.selectLocationFromChoiceSet(), de.dlr.ivf.tapas.mode.TPS_ModeSet.selectMode(), de.dlr.ivf.tapas.iteration.TPS_AcceptanceIterationManager.selectPlansForRecalculation(), de.dlr.ivf.tapas.mode.TPS_Mode.setAttribute(), de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.setCostParkingPerHour(), de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.setCostToll(), de.dlr.ivf.tapas.scheme.TPS_TourPart.setInitialTravelDurations(), de.dlr.ivf.tapas.scheme.TPS_Episode.TPS_Episode(), de.dlr.ivf.tapas.scheme.TPS_Trip.TPS_Trip(), de.dlr.ivf.tapas.scheme.TPS_TourPart.updateActualTravelDistances(), de.dlr.ivf.tapas.tools.fileModifier.persistence.TPS_ParameterCSVDAO.writeParameter(), and de.dlr.ivf.tapas.tools.fileModifier.persistence.TPS_ParameterXLSDAO.writeParameter().
getIntValue()
int de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getIntValue (ParamValue param)
Definition at line 401 of file TPS_ParameterClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamValueClass.getIntValue().
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.addPersonToHousehold(), de.dlr.ivf.tapas.scheme.TPS_TourPart.addStay(), de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree.applyExpertKnowledge(), de.dlr.ivf.tapas.plan.TPS_Plan.calcPlanFeasiblity(), de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.fillLoginData(), de.dlr.ivf.tapas.loc.TPS_MultipleTAZRepresentant.getLocationRepresentatives(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.getModeLogSum(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.getTrafficAnalysisZonesAround(), de.dlr.ivf.tapas.mode.TPS_IndividualTransportMode.getTravelTime(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessMode.getTravelTime(), de.dlr.ivf.tapas.loc.TPS_SelectWithSingleAccessMode.getTravelTime(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.loadConfig(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.loadHouseholds(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.openConnection(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readSchemeSet(), de.dlr.ivf.tapas.iteration.TPS_AcceptanceIterationManager.selectPlansForRecalculation(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.vacuumTempTables(), and de.dlr.ivf.tapas.iteration.TPS_SumoConverter.writeTripFile().
getLongValue()
long de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getLongValue (ParamValue param)
Definition at line 405 of file TPS_ParameterClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamValueClass.getLongValue().
getMatrix()
Matrix de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getMatrix (ParamMatrix param)
Definition at line 409 of file TPS_ParameterClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamMatrixClass.getMatrix().
getSimulationType()
SimulationType de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getSimulationType ()
Method to return the set simulation type for this run
Returns
The SimulationType
Definition at line 418 of file TPS_ParameterClass.java.
References de.dlr.ivf.tapas.util.parameters.SimulationType.BASE, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_RUN_SZENARIO, de.dlr.ivf.tapas.util.parameters.ParamFlagClass.isTrue(), and de.dlr.ivf.tapas.util.parameters.SimulationType.SCENARIO.
getString()
String de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString (ParamString param)
Definition at line 422 of file TPS_ParameterClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamStringClass.getString().
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.buildQuery(), de.dlr.ivf.tapas.iteration.TPS_IterationManagement.calculatePlanDerivation(), de.dlr.ivf.tapas.iteration.TPS_VisumConverter.checkIntraInfos(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.checkMatrixName(), de.dlr.ivf.tapas.iteration.TPS_VisumConverter.checkMatrixName(), de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.checkMatrixName(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.checkProperties(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.checkProperty(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.chooseSimulation(), de.dlr.ivf.tapas.tools.fileModifier.persistence.TPS_ParameterXLSDAO.convert(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverter.convert(), de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.createNewMatrixMap(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportController.dbimport(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.define(), de.dlr.ivf.tapas.util.TPS_TripDeleter.deleteHouseholdsFromTriptable(), de.dlr.ivf.tapas.iteration.TPS_VisumConverter.deleteIntraInfos(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.deleteMatrix(), de.dlr.ivf.tapas.iteration.TPS_VisumConverter.deleteMatrix(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.fetchNextSetOfHouseholds(), de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.fillLoginData(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.getKey(), de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.getOutputPath(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.getTrafficAnalysisZonesAround(), de.dlr.ivf.tapas.loc.TPS_Region.initLocationChoiceSet(), de.dlr.ivf.tapas.loc.TPS_Region.initLocationSelectModel(), de.dlr.ivf.tapas.mode.TPS_Mode.initUtilityFunction(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.isSimulationStartedAlready(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.load(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.loadConfig(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.loadConfigFromDatabase(), de.dlr.ivf.tapas.tools.TPS_MainDiagonalLengthEstimator.loadDistMatrix(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.loadHouseholds(), de.dlr.ivf.tapas.tools.TPS_SubnetMatrixIntegrator.loadMatricesAndMappings(), de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.loadSumoValues(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.openConnection(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readActivity2LocationCodes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readActivityConstantCodes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readAgeClassCodes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readCarCodes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readDistanceCodes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readDrivingLicenseCodes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readExpertKnowledgeTree(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.readIDMap(), de.dlr.ivf.tapas.iteration.TPS_VisumConverter.readIDMap(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readIncomeCodes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readLocationConstantCodes(), de.dlr.ivf.tapas.tools.TPS_MainDiagonalLengthEstimator.readLocations(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readMatrices(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readMatrix(), de.dlr.ivf.tapas.iteration.TPS_VisumConverter.readMatrix(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.readMatrix(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.readMatrixFromDB(), de.dlr.ivf.tapas.iteration.TPS_VisumConverter.readMatrixFromDB(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.readMatrixMap(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.readMatrixMap(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readModeChoiceTree(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readModes(), de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.readParameter(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readPersonGroupCodes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readRegion(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.readRuntimeParametersFromDB(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readSchemeSet(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readSettlementSystemCodes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readSexCodes(), de.dlr.ivf.tapas.runtime.sumoDaemon.SumoMatrixImporter.readSumoValues(), de.dlr.ivf.tapas.tools.TPS_MainDiagonalLengthEstimator.readTAZ(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readUtilityFunction(), de.dlr.ivf.tapas.runtime.client.SimulationControl.removeServer(), de.dlr.ivf.tapas.runtime.client.SimulationControl.ServerOnlineTester.SimulationServerOnlineTestThread.resetDatabaseEntryOfSimulationServer(), de.dlr.ivf.tapas.iteration.TPS_IterationManagement.resetPlansForRecalculation(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.returnHousehold(), de.dlr.ivf.tapas.runtime.client.SimulationControl.SimulationServerDataUpdateTask.run(), de.dlr.ivf.tapas.runtime.client.SimulationControl.SimulationDataUpdateTask.run(), de.dlr.ivf.tapas.runtime.server.SimulationDaemon.ShutDownProcedure.run(), de.dlr.ivf.tapas.runtime.server.SimulationDaemon.ServerProcessChecker.run(), de.dlr.ivf.tapas.runtime.server.SimulationServer.run(), de.dlr.ivf.tapas.runtime.server.SimulationServer.SimulationServerUpdateTask.run(), de.dlr.ivf.tapas.runtime.server.SimulationServer.RunWhenShuttingDown.run(), de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.run(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverter.save(), de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.saveMatrices(), de.dlr.ivf.tapas.tools.TPS_SubnetMatrixIntegrator.saveMatrix(), de.dlr.ivf.tapas.iteration.TPS_AcceptanceIterationManager.selectPlansForRecalculation(), de.dlr.ivf.tapas.iteration.TPS_BasicIterationManager.selectPlansForRecalculation(), de.dlr.ivf.tapas.log.TPS_Logger.setLoggingClass(), de.dlr.ivf.tapas.runtime.server.SimulationDaemon.SimulationDaemon(), de.dlr.ivf.tapas.runtime.server.SimulationServer.SimulationServer(), de.dlr.ivf.tapas.runtime.server.SimulationServer.SimulationServerUpdateTask.SimulationServerUpdateTask(), de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.storeInDB(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.storeInDB(), de.dlr.ivf.tapas.iteration.TPS_VisumConverter.storeIntraInfos(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.storeMatrixMap(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.TPS_DB_Connector(), de.dlr.ivf.tapas.TPS_Main.TPS_Main(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.TPS_SumoConverter(), de.dlr.ivf.tapas.iteration.TPS_VisumConverter.TPS_VisumConverter(), de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.updateData(), de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.SimulationTableModel.updateData(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.updateOccupancyTable(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.vacuumTempTables(), de.dlr.ivf.tapas.runtime.sumoDaemon.SumoMatrixImporter.writeMatrix(), de.dlr.ivf.tapas.iteration.TPS_VisumConverter.writeODMatrices(), de.dlr.ivf.tapas.tools.fileModifier.persistence.TPS_ParameterCSVDAO.writeParameter(), de.dlr.ivf.tapas.tools.fileModifier.persistence.TPS_ParameterXLSDAO.writeParameter(), and de.dlr.ivf.tapas.iteration.TPS_SumoConverter.writeTripFile().
getType() [1/5]
ParamType de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getType (ParamFlag param)
Definition at line 439 of file TPS_ParameterClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamFlagClass.getType().
getType() [2/5]
ParamType de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getType (ParamMatrix param)
Definition at line 443 of file TPS_ParameterClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamMatrixClass.getType().
getType() [3/5]
ParamType de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getType (ParamMatrixMap param)
Definition at line 447 of file TPS_ParameterClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamMatrixMapClass.getType().
getType() [4/5]
ParamType de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getType (ParamString param)
Definition at line 431 of file TPS_ParameterClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamStringClass.getType().
Referenced by de.dlr.ivf.tapas.tools.fileModifier.persistence.TPS_ParameterXLSDAO.convert(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverter.convert(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverter.save(), and de.dlr.ivf.tapas.tools.fileModifier.persistence.TPS_ParameterXLSDAO.writeParameter().
getType() [5/5]
ParamType de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getType (ParamValue param)
Definition at line 435 of file TPS_ParameterClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamValueClass.getType().
isDefined() [1/5]
boolean de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isDefined (ParamFlag param)
here follow helper function which are basically calls into the Param{Flag|Matrix|MatrixMap|Value|String}Class
Definition at line 456 of file TPS_ParameterClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamFlagClass.isDefined().
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.calcPlanFeasiblity(), de.dlr.ivf.tapas.tools.fileModifier.persistence.TPS_ParameterXLSDAO.convert(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverter.convert(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.fill(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.load(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.openConnection(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.readClientProperties(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readExpertKnowledgeTree(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readMatrices(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readRegion(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverter.save(), de.dlr.ivf.tapas.loc.TPS_SelectLocationWeightBased.selectLocationFromChoiceSet(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.selectLocationFromChoiceSet(), de.dlr.ivf.tapas.mode.TPS_Mode.setAttribute(), de.dlr.ivf.tapas.TPS_Main.updateCosts(), de.dlr.ivf.tapas.tools.fileModifier.persistence.TPS_ParameterCSVDAO.writeParameter(), and de.dlr.ivf.tapas.tools.fileModifier.persistence.TPS_ParameterXLSDAO.writeParameter().
isDefined() [2/5]
boolean de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isDefined (ParamMatrix param)
Definition at line 468 of file TPS_ParameterClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamMatrixClass.isDefined().
isDefined() [3/5]
boolean de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isDefined (ParamMatrixMap param)
Definition at line 472 of file TPS_ParameterClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamMatrixMapClass.isDefined().
isDefined() [4/5]
boolean de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isDefined (ParamString param)
Definition at line 460 of file TPS_ParameterClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamStringClass.isDefined().
isDefined() [5/5]
boolean de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isDefined (ParamValue param)
Definition at line 464 of file TPS_ParameterClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamValueClass.isDefined().
isFalse()
boolean de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isFalse (ParamFlag param)
Definition at line 476 of file TPS_ParameterClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamFlagClass.isFalse().
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.addPersonToHousehold(), de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree.applyExpertKnowledge(), de.dlr.ivf.tapas.util.TPS_Geometrics.getDistance(), de.dlr.ivf.tapas.modechoice.TPS_UtilityMNL.getDistributionSet(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.getModeLogSum(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.loadHouseholds().
isTrue()
boolean de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isTrue (ParamFlag param)
Definition at line 480 of file TPS_ParameterClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamFlagClass.isTrue().
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.addPersonToHousehold(), de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixedBS.calculateDelta(), de.dlr.ivf.tapas.tools.fileModifier.persistence.TPS_ParameterXLSDAO.convert(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverter.convert(), de.dlr.ivf.tapas.util.TPS_Geometrics.getDistance(), de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixedBS.getDistributionSet(), de.dlr.ivf.tapas.loc.TPS_MultipleTAZRepresentant.getLocationRepresentatives(), de.dlr.ivf.tapas.mode.TPS_ModeSet.getModeDistribution(), de.dlr.ivf.tapas.plan.acceptance.TPS_PlanEVA1Acceptance.isPlanAccepted(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.loadHouseholds(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readMatrices(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readRegion(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverter.save(), de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes(), de.dlr.ivf.tapas.loc.TPS_Location.TPS_LocationData.setOccupancy(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.TPS_DB_IO(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.updateOccupancyTable(), de.dlr.ivf.tapas.tools.fileModifier.persistence.TPS_ParameterCSVDAO.writeParameter(), and de.dlr.ivf.tapas.tools.fileModifier.persistence.TPS_ParameterXLSDAO.writeParameter().
load()
void de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.load (File currentPath, File propertiesFile, EnumSet< ParamFlag > flagSet, EnumSet< ParamString > stringSet, EnumSet< ParamValue > valueSet) throws FileNotFoundException, IOException private
This method opens the file and stores all key value pairs in a property instance. If the file is in csv format the key is in the first column and the value in the second one.
In the second step the value all values are set to enum constants of type ParamString, ParamFlag and ParamValue. If the constant is found and the parameter has a wrong format an error is logged (e.g. you try to define an instance of ParamValue with "true"). If no constant was found to set the value a warning is logged.
Parameters
currentPath current path of the properties file
propertiesFile file name of the current properties file; file can be in java properties or in standard csv format
flagSet set with all instances of ParamFlag, which are not defined yet
stringSet set with all instances of ParamString, which are not defined yet
valueSet set with all instances of ParamValue, which are not defined yet
Exceptions
FileNotFoundException if the file is not found
IOException if there occurs a read error
Definition at line 504 of file TPS_ParameterClass.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.INFO, de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), and de.dlr.ivf.tapas.log.TPS_Logger.log().
loadRuntimeParameters()
void de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.loadRuntimeParameters (File runPropertiesFile) throws IOException
This method reads all properties for the Application and stores them in the constants of type ParamString , ParamFlag and ParamValue. If one constant is not defined in the properties files a warning is logged. If an exception occurs during reading the application stops and logs a fatal message.
Parameters
runPropertiesFile file name of the properties file with the run parameters
Exceptions
IOException if there occurs an error while reading from a file
Definition at line 537 of file TPS_ParameterClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.LOG_CLASS, de.dlr.ivf.tapas.util.parameters.ParamString.PATH_ABS_INPUT, de.dlr.ivf.tapas.util.parameters.ParamString.PATH_ABS_OUTPUT, de.dlr.ivf.tapas.util.parameters.ParamString.PATH_ABS_PROPERTIES, and de.dlr.ivf.tapas.log.TPS_Logger.setLoggingClass().
Referenced by de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader.CalibrationResultsReader(), de.dlr.ivf.tapas.analyzer.tum.results.DatabaseSummaryExport.DatabaseSummaryExport(), de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.DBSimulationChooserPanel(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.define(), de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.fillLoginData(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.GeneralDatabaseSummaryExport(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.load(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.login(), de.dlr.ivf.scripts.SrVCalculator.main(), de.dlr.ivf.scripts.SumoTripVisualization.main(), de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.main(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.main(), de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.main(), de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.main(), de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.main(), de.dlr.ivf.tapas.tools.OpportunityDistribution.OpportunityDistribution.main(), de.dlr.ivf.tapas.tools.riesel.RieselTool.main(), de.dlr.ivf.tapas.tools.riesel.SimpleCollector.main(), de.dlr.ivf.tapas.tools.tazcalculator.TAZCalculator.main(), de.dlr.ivf.tapas.tools.TAZFilter.TAZFilter.main(), de.dlr.ivf.tapas.tools.TPS_PTScoreCalculator.main(), de.dlr.ivf.tapas.tools.TPS_SchemeClassCalculator.main(), de.dlr.ivf.tapas.tools.TPS_VisumToDB.main(), de.dlr.ivf.tapas.util.TPS_TripDeleter.main(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.readClientProperties(), de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.ReferenceDBReader.ReferenceDBReader(), de.dlr.ivf.tapas.runtime.client.SimulationControl.SimulationControl(), de.dlr.ivf.tapas.runtime.server.SimulationDaemon.SimulationDaemon(), de.dlr.ivf.tapas.runtime.server.SimulationServer.SimulationServer(), de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.SumoDaemon(), de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.TPS_BasicConnectionClass(), de.dlr.ivf.tapas.TPS_Main.TPS_Main(), and de.dlr.ivf.tapas.iteration.TPS_SumoConverter.TPS_SumoConverter().
loadSingleParameterFile()
void de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.loadSingleParameterFile (File propertiesFile) throws FileNotFoundException, IOException
Method to load a single parameter file. Parent files and other files are ignored.
Parameters
propertiesFile The one and only file to load
Exceptions
FileNotFoundException
IOException
Definition at line 578 of file TPS_ParameterClass.java.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.load(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.loadConfig(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverter.main(), de.dlr.ivf.tapas.tools.TPS_VisumToDB.main(), and de.dlr.ivf.tapas.runtime.sumoDaemon.SumoMatrixImporter.SumoMatrixImporter().
print()
void de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.print ()
Prints all parameters
Definition at line 596 of file TPS_ParameterClass.java.
readRuntimeParametersFromDB()
void de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.readRuntimeParametersFromDB (ResultSet rs) throws SQLException
This method reads all properties for the Application and stores them in the constants of type ParamString , ParamFlag and ParamValue. If one constant is not defined in the properties files a warning is logged. If an exception occurs during reading the application stops and logs a fatal message.
Parameters
rs the SQL-result set to look for parameters
Exceptions
SQLException This exception is thrown if there occurs an error while reading from a file
Definition at line 626 of file TPS_ParameterClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.FILE_DATABASE_PROPERTIES, de.dlr.ivf.tapas.util.parameters.ParamString.FILE_LOGGING_PROPERTIES, de.dlr.ivf.tapas.util.parameters.ParamString.FILE_PARAMETER_PROPERTIES, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.INFO, de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.util.parameters.ParamString.LOG_CLASS, de.dlr.ivf.tapas.util.parameters.ParamString.PATH_ABS_INPUT, de.dlr.ivf.tapas.util.parameters.ParamString.PATH_ABS_OUTPUT, de.dlr.ivf.tapas.util.parameters.ParamString.PATH_ABS_PROPERTIES, and de.dlr.ivf.tapas.log.TPS_Logger.setLoggingClass().
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.readRuntimeParametersFromDB().
replaceSeparator()
String de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.replaceSeparator (String string) private
This method replaces double slashes and double backslashes with single one in the given string.
Parameters
string The string to chsnge
Returns
The result without double slashes
Definition at line 676 of file TPS_ParameterClass.java.
revertTemporaryParameters()
void de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.revertTemporaryParameters ()
Method to revert the temporary parameters for this run.
Definition at line 687 of file TPS_ParameterClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_SCHEMA_CORE, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_HOUSEHOLD_TMP, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_LOCATION_TMP, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_TRIPS, and de.dlr.ivf.tapas.util.parameters.ParamString.RUN_IDENTIFIER.
setFlag()
void de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.setFlag (ParamFlag param, boolean flag)
Definition at line 718 of file TPS_ParameterClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamFlagClass.setFlag().
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverter.load(), and de.dlr.ivf.tapas.tools.fileModifier.persistence.TPS_ParameterPropertiesDAO.readParameter().
setMatrix() [1/2]
void de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.setMatrix (ParamMatrix param, Matrix matrix)
Definition at line 722 of file TPS_ParameterClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamMatrixClass.setMatrix().
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readMatrices(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readMatrix().
setMatrix() [2/2]
void de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.setMatrix (ParamMatrix param, Matrix matrix, SimulationType simType)
Definition at line 726 of file TPS_ParameterClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamMatrixClass.setMatrix().
setString()
void de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.setString (ParamString param, String str)
Definition at line 730 of file TPS_ParameterClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamStringClass.setString().
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportController.dbimport(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverter.load(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.loadConfigFromDatabase(), de.dlr.ivf.tapas.tools.TPS_SubnetMatrixIntegrator.main(), de.dlr.ivf.tapas.tools.TPS_VisumOD2DB.main(), de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.main(), de.dlr.ivf.tapas.util.TPS_TripDeleter.main(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.readClientProperties(), de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.readParameter(), de.dlr.ivf.tapas.tools.fileModifier.persistence.TPS_ParameterPropertiesDAO.readParameter(), de.dlr.ivf.tapas.runtime.server.SimulationDaemon.SimulationDaemon(), de.dlr.ivf.tapas.runtime.server.SimulationServer.SimulationServer(), de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.SumoDaemon(), de.dlr.ivf.tapas.TPS_Main.TPS_Main(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.TPS_SumoConverter(), and de.dlr.ivf.tapas.iteration.TPS_VisumConverter.TPS_VisumConverter().
setValue() [1/6]
void de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.setValue (ParamValue param, double val)
Definition at line 811 of file TPS_ParameterClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamValueClass.setValue().
setValue() [2/6]
void de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.setValue (ParamValue param, float val)
Definition at line 815 of file TPS_ParameterClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamValueClass.setValue().
setValue() [3/6]
void de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.setValue (ParamValue param, int val)
Definition at line 807 of file TPS_ParameterClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamValueClass.setValue().
setValue() [4/6]
void de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.setValue (ParamValue param, long val)
Definition at line 819 of file TPS_ParameterClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamValueClass.setValue().
setValue() [5/6]
void de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.setValue (ParamValue param, Number val)
Definition at line 823 of file TPS_ParameterClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamValueClass.setValue().
setValue() [6/6]
boolean de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.setValue (String key, String value)
This method sets the value for the given key string with the given value. The value is casted to the correct format, if possible
Parameters
key The name of the parameter
value The value of the parameter
Returns
Definition at line 742 of file TPS_ParameterClass.java.
References de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.util.parameters.ParamValueClass.setValue(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.SEVERE, and de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.WARN.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.init(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverter.load(), de.dlr.ivf.tapas.tools.riesel.RieselTool.main(), de.dlr.ivf.tapas.tools.riesel.SimpleCollector.main(), de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.main(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readMatrices(), and de.dlr.ivf.tapas.tools.fileModifier.persistence.TPS_ParameterPropertiesDAO.readParameter().
updateInDB()
void de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.updateInDB (Connection con, String sim_key, Map< String, String > params) throws SQLException
Updates all given parameters in the table "simulation_parameters" for which the simulation-identifier is sim_key.
Definition at line 873 of file TPS_ParameterClass.java.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.saveConfigInDatabase().
updateParameter()
boolean de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.updateParameter (String key, String value, EnumSet< ParamFlag > flagSet, EnumSet< ParamString > stringSet, EnumSet< ParamValue > valueSet) private
This method processes exactly one parameter and its given value. It returns true if the parameter is successfully consumed
Parameters
key the parameter name for the value
value the parameter value
flagSet set with all instances of ParamFlag, which are not defined yet
stringSet set with all instances of ParamString, which are not defined yet
valueSet set with all instances of ParamValue, which are not defined yet
Returns
true, if sucessfull
Exceptions
FileNotFoundException if the file is not found
IOException if there occurs a read error
Definition at line 894 of file TPS_ParameterClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.FILE_PARENT_PROPERTIES, de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.util.parameters.ParamValueClass.setValue(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.SEVERE, and de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.WARN.
writeToDB()
void de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.writeToDB (Connection con, String sim_key, Map< String, String > params) throws SQLException
Inserts the given params into the table "simulation_parameters". The identifier for the simulation in this table will be the given sim_key.
Definition at line 986 of file TPS_ParameterClass.java.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationControl.addSimulation(), and de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.saveConfigInDatabase().
Member Data Documentation
BIN_DIR
String de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.BIN_DIR
Name of the binary folder
Definition at line 40 of file TPS_ParameterClass.java.
INPUT_DIR
String de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.INPUT_DIR
Name of the Input folder
Definition at line 44 of file TPS_ParameterClass.java.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportController.dbimport().
LOG_DIR
String de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.LOG_DIR = "Log/"
Name of the log folder
Definition at line 56 of file TPS_ParameterClass.java.
OUTPUT_DIR
String de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.OUTPUT_DIR
Name of the output folder
Definition at line 48 of file TPS_ParameterClass.java.
parameterFiles
final Stack<File> de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.parameterFiles private
Stack to store the parents of the parameter files. Needed to descent in the correct order.
Definition at line 67 of file TPS_ParameterClass.java.
paramFlagClass
ParamFlagClass de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.paramFlagClass
Definition at line 58 of file TPS_ParameterClass.java.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.getDefaultParams().
paramMatrixClass
ParamMatrixClass de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.paramMatrixClass
Definition at line 60 of file TPS_ParameterClass.java.
Referenced by de.dlr.ivf.tapas.mode.TPS_IndividualTransportMode.getDistance(), de.dlr.ivf.tapas.mode.TPS_NonMotorisedMode.getDistance(), de.dlr.ivf.tapas.util.TPS_Geometrics.getDistance(), de.dlr.ivf.tapas.mode.TPS_IndividualTransportMode.getTravelTime(), and de.dlr.ivf.tapas.mode.TPS_NonMotorisedMode.getTravelTime().
paramMatrixMapClass
ParamMatrixMapClass de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.paramMatrixMapClass
Definition at line 61 of file TPS_ParameterClass.java.
Referenced by de.dlr.ivf.tapas.mode.TPS_IndividualTransportMode.getTravelTime(), de.dlr.ivf.tapas.mode.TPS_NonMotorisedMode.getTravelTime(), de.dlr.ivf.tapas.iteration.TPS_VisumConverter.readMatrix(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readMatrix(), and de.dlr.ivf.tapas.iteration.TPS_VisumConverter.writeODMatrices().
paramStringClass
ParamStringClass de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.paramStringClass
Definition at line 62 of file TPS_ParameterClass.java.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.getDefaultParams(), and de.dlr.ivf.tapas.tools.TPS_MainDiagonalLengthEstimator.main().
paramValueClass
ParamValueClass de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.paramValueClass
Definition at line 59 of file TPS_ParameterClass.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.checkProperties(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.getDefaultParams(), de.dlr.ivf.tapas.TPS_Main.updateCosts(), and de.dlr.ivf.tapas.iteration.TPS_VisumConverter.writeODMatrices().
SIM_DIR
String de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.SIM_DIR
Name of the binary folder
Definition at line 52 of file TPS_ParameterClass.java.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.readClientProperties(), de.dlr.ivf.tapas.runtime.server.SimulationDaemon.SimulationDaemon(), de.dlr.ivf.tapas.runtime.server.SimulationServer.SimulationServer(), de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.SumoDaemon(), and de.dlr.ivf.tapas.iteration.TPS_SumoConverter.TPS_SumoConverter().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/util/parameters/TPS_ParameterClass.java