TAPAS: de.dlr.ivf.tapas.util.PropertyReader Class Reference
de.dlr.ivf.tapas.util.PropertyReader Class Reference
Static Public Member Functions
static Properties getProperties (String propFileName) throws IOException
static String getProperty (String propFileName, String name) throws IOException
static void setProperty (String propFileName, String name, String value) throws IOException
Static Private Member Functions
static void save (String propFileName) throws IOException
Static Private Attributes
static Properties properties
Detailed Description
Author
Holger Siedel(edited) original code from Marco
Definition at line 19 of file PropertyReader.java.
Member Function Documentation
getProperties()
static Properties de.dlr.ivf.tapas.util.PropertyReader.getProperties (String propFileName) throws IOException static
Definition at line 22 of file PropertyReader.java.
References de.dlr.ivf.tapas.util.PropertyReader.properties.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedGUI.CruisingSpeedGUI(), de.dlr.ivf.tapas.util.PropertyReader.getProperty(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.readProperties(), de.dlr.ivf.tapas.util.PropertyReader.save(), de.dlr.ivf.tapas.util.PropertyReader.setProperty(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedGUI.start().
getProperty()
static String de.dlr.ivf.tapas.util.PropertyReader.getProperty (String propFileName, String name) throws IOException static
Definition at line 48 of file PropertyReader.java.
References de.dlr.ivf.tapas.util.PropertyReader.getProperties(), and name.
save()
static void de.dlr.ivf.tapas.util.PropertyReader.save (String propFileName) throws IOException static private
Definition at line 52 of file PropertyReader.java.
References de.dlr.ivf.tapas.util.PropertyReader.getProperties().
Referenced by de.dlr.ivf.tapas.util.PropertyReader.setProperty().
setProperty()
static void de.dlr.ivf.tapas.util.PropertyReader.setProperty (String propFileName, String name, String value) throws IOException static
Definition at line 66 of file PropertyReader.java.
References de.dlr.ivf.tapas.util.PropertyReader.getProperties(), name, and de.dlr.ivf.tapas.util.PropertyReader.save().
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedGUI.savePropertieFile().
Member Data Documentation
properties
Properties de.dlr.ivf.tapas.util.PropertyReader.properties static private
Definition at line 20 of file PropertyReader.java.
Referenced by de.dlr.ivf.tapas.util.PropertyReader.getProperties().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/util/PropertyReader.java