TAPAS: de.dlr.ivf.tapas.analyzer.gui.FileChooserHistoryManager Class Reference
de.dlr.ivf.tapas.analyzer.gui.FileChooserHistoryManager Class Reference
Static Public Member Functions
static String getLastDirectory (String name)
static void updateLastDirectory (String name, String path)
Static Private Member Functions
static Properties getProperties ()
static void save ()
Static Private Attributes
static Properties properties
Detailed Description
Ein Manager der sich um das Speihern der zuletzt selektierten Dateipfade kümmert. Wird der FileChooser oder FilesChooser verwendet, speichern diese den selektierten Pfad mithilfe dieser Klasse in einer Property-Datei. Beim nächsten Start der Anwendung wird diese Datei dann wieder ausgelesen und dient der Initialisierung der FileChooser bzw. FilesChooser
Author
Marco
Definition at line 22 of file FileChooserHistoryManager.java.
Member Function Documentation
getLastDirectory()
static String de.dlr.ivf.tapas.analyzer.gui.FileChooserHistoryManager.getLastDirectory (String name) static
Definition at line 26 of file FileChooserHistoryManager.java.
References de.dlr.ivf.tapas.analyzer.gui.FileChooserHistoryManager.getProperties(), and name.
Referenced by de.dlr.ivf.tapas.analyzer.gui.FileChooser.chooseFile(), de.dlr.ivf.tapas.analyzer.gui.FilesChooser.chooseFile(), and de.dlr.ivf.tapas.analyzer.gui.Control.Control().
getProperties()
static Properties de.dlr.ivf.tapas.analyzer.gui.FileChooserHistoryManager.getProperties () static private
Definition at line 30 of file FileChooserHistoryManager.java.
References de.dlr.ivf.tapas.analyzer.core.Constants.PATH_PROPERTIES, and de.dlr.ivf.tapas.analyzer.gui.FileChooserHistoryManager.properties.
Referenced by de.dlr.ivf.tapas.analyzer.gui.FileChooserHistoryManager.getLastDirectory(), de.dlr.ivf.tapas.analyzer.gui.FileChooserHistoryManager.save(), and de.dlr.ivf.tapas.analyzer.gui.FileChooserHistoryManager.updateLastDirectory().
save()
static void de.dlr.ivf.tapas.analyzer.gui.FileChooserHistoryManager.save () static private
Definition at line 54 of file FileChooserHistoryManager.java.
References de.dlr.ivf.tapas.analyzer.gui.FileChooserHistoryManager.getProperties(), and de.dlr.ivf.tapas.analyzer.core.Constants.PATH_PROPERTIES.
Referenced by de.dlr.ivf.tapas.analyzer.gui.FileChooserHistoryManager.updateLastDirectory().
updateLastDirectory()
static void de.dlr.ivf.tapas.analyzer.gui.FileChooserHistoryManager.updateLastDirectory (String name, String path) static
Definition at line 73 of file FileChooserHistoryManager.java.
References de.dlr.ivf.tapas.analyzer.gui.FileChooserHistoryManager.getProperties(), name, and de.dlr.ivf.tapas.analyzer.gui.FileChooserHistoryManager.save().
Referenced by de.dlr.ivf.tapas.analyzer.gui.Control.chooseDirectory(), de.dlr.ivf.tapas.analyzer.gui.FileChooser.chooseFile(), de.dlr.ivf.tapas.analyzer.gui.FilesChooser.chooseFile(), and de.dlr.ivf.tapas.analyzer.gui.Control.Control().
Member Data Documentation
properties
Properties de.dlr.ivf.tapas.analyzer.gui.FileChooserHistoryManager.properties static private
Definition at line 24 of file FileChooserHistoryManager.java.
Referenced by de.dlr.ivf.tapas.analyzer.gui.FileChooserHistoryManager.getProperties().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/gui/FileChooserHistoryManager.java