TAPAS: de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location Class Reference
de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location Class Reference
Public Member Functions
Location (String entry)
boolean addValue (int valID, String val)
boolean addValue (String valName, String val)
String getID ()
void setID (String id)
int getSqlQueryIndex ()
void setSqlQueryIndex (int sqlQueryIndex)
int getStatus ()
void setStatus (int status)
String getValue (int valID)
String getValue (String valName)
boolean isCorrectInitialized ()
boolean isDuplicateImport (Location loc)
boolean isUpdatedByDB ()
void setUpdatedByDB (boolean isUpdatedByDB)
String locationToString ()
void updateOrAddValue (String valName, String val)
boolean updateValue (int valID, String val)
boolean updateValue (String valName, String val)
Static Public Attributes
static final int STATUS_NOT_DISTINCT_IN_DATABASE = 1
static final int STATUS_DISTINCT_IN_DATABASE = 0
Private Attributes
boolean correctInitialized = false
int myHash = -1
boolean isUpdatedByDB = false
int sqlQueryIndex = -1
final HashMap< String, String > valueMap = new HashMap<>()
int status = STATUS_DISTINCT_IN_DATABASE
Detailed Description
This class represents one location.
Author
hein_mh
Definition at line 330 of file LocationProcessor.java.
Constructor & Destructor Documentation
Location()
de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.Location (String entry)
Definition at line 350 of file LocationProcessor.java.
References de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.addValue(), de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.correctInitialized, de.dlr.ivf.tapas.tools.locationallocation.Constants.ENABLE_CHANGES_OF_MARCO, de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.headerMap, de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.myHash, and de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.posOfIdColumn.
Member Function Documentation
addValue() [1/2]
boolean de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.addValue (int valID, String val)
Add one value at position valID.
Parameters
valID The column in the csv-file.
val The value to set.
Returns
Returns true if succesfull. False if valID is unknown or valID is already set.
Definition at line 400 of file LocationProcessor.java.
References de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.headerMap.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.Location().
addValue() [2/2]
boolean de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.addValue (String valName, String val)
Add one value for the given name.
Parameters
valName The value key in the csv-file.
val The value to set.
Returns
Returns true if succesfull. False if valName is unknown or valName is already set.
Definition at line 418 of file LocationProcessor.java.
References de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.headerMap.
getID()
String de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.getID ()
Definition at line 427 of file LocationProcessor.java.
References de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.getValue(), and de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.posOfIdColumn.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.main().
getSqlQueryIndex()
int de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.getSqlQueryIndex ()
Returns
the sqlQueryIndex
Definition at line 444 of file LocationProcessor.java.
References de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.sqlQueryIndex.
getStatus()
int de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.getStatus ()
Definition at line 455 of file LocationProcessor.java.
References de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.status.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.Locator.localizeLocation(), and de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.main().
getValue() [1/2]
String de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.getValue (int valID)
This method gets the value for a specified column-index.
Parameters
valID The column index
Returns
Returns the stored value or null if the value is not set or the column is unknown
Definition at line 470 of file LocationProcessor.java.
References de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.headerMap.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.getID(), de.dlr.ivf.tapas.tools.locationallocation.Locator.isInRegion(), de.dlr.ivf.tapas.tools.locationallocation.Locator.localizeLocation(), de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.locationToString(), de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.locationToString(), and de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.main().
getValue() [2/2]
String de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.getValue (String valName)
This method gets the value for a specified value name
Parameters
valName The name of the value
Returns
Returns the stored value or null if the value is not set or the value name is unknown
Definition at line 485 of file LocationProcessor.java.
References de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.headerMap.
isCorrectInitialized()
boolean de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.isCorrectInitialized ()
Returns
the correctInitialized
Definition at line 495 of file LocationProcessor.java.
References de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.correctInitialized.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.addLocationToAddressProcessing(), de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.addLocationToRelocate(), and de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.main().
isDuplicateImport()
boolean de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.isDuplicateImport (Location loc)
Method which returns true if everything is the same except the "id" which indicates a duplicate import
Parameters
loc the test location
Returns
true if they differ only in the location id-field
Definition at line 507 of file LocationProcessor.java.
References de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.myHash.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.hasDuplicate().
isUpdatedByDB()
boolean de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.isUpdatedByDB ()
Definition at line 530 of file LocationProcessor.java.
References de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.isUpdatedByDB.
locationToString()
String de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.locationToString ()
Definition at line 546 of file LocationProcessor.java.
References de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.getValue(), and de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.headerMap.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.main().
setID()
void de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.setID (String id)
Definition at line 435 of file LocationProcessor.java.
References de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.posOfIdColumn, and de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.updateValue().
setSqlQueryIndex()
void de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.setSqlQueryIndex (int sqlQueryIndex)
Parameters
sqlQueryIndex the sqlQueryIndex to set
Definition at line 451 of file LocationProcessor.java.
References de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.sqlQueryIndex.
setStatus()
void de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.setStatus (int status)
Definition at line 459 of file LocationProcessor.java.
References de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.status.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.Locator.localizeLocation().
setUpdatedByDB()
void de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.setUpdatedByDB (boolean isUpdatedByDB)
Parameters
isUpdatedByDB true if the values set are inserted by a row from the database
Definition at line 538 of file LocationProcessor.java.
References de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.isUpdatedByDB.
updateOrAddValue()
void de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.updateOrAddValue (String valName, String val)
Updates one value for the given name. If not existent the value is added
Parameters
valName the value key in the csv-file.
val the value to set.
Definition at line 575 of file LocationProcessor.java.
References de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.headerMap.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.Locator.localizeLocation().
updateValue() [1/2]
boolean de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.updateValue (int valID, String val)
Updates one value at position valID.
Parameters
valID The column in the csv-file.
val The value to set.
Returns
Returns true if succesfull. False if valID is unknown or valID is not set.
Definition at line 591 of file LocationProcessor.java.
References de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.headerMap.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.main(), and de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.setID().
updateValue() [2/2]
boolean de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.updateValue (String valName, String val)
Updates one value for the given name.
Parameters
valName The value key in the csv-file.
val The value to set.
Returns
Returns true if succesfull. False if valName is unknown or valName is not set.
Definition at line 609 of file LocationProcessor.java.
References de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.headerMap.
Member Data Documentation
correctInitialized
boolean de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.correctInitialized = false private
Definition at line 335 of file LocationProcessor.java.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.isCorrectInitialized(), and de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.Location().
isUpdatedByDB
boolean de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.isUpdatedByDB = false private
Definition at line 338 of file LocationProcessor.java.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.isUpdatedByDB(), and de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.setUpdatedByDB().
myHash
int de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.myHash = -1 private
Definition at line 337 of file LocationProcessor.java.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.isDuplicateImport(), and de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.Location().
sqlQueryIndex
int de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.sqlQueryIndex = -1 private
Definition at line 339 of file LocationProcessor.java.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.getSqlQueryIndex(), and de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.setSqlQueryIndex().
status
int de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.status = STATUS_DISTINCT_IN_DATABASE private
Definition at line 344 of file LocationProcessor.java.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.getStatus(), and de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.setStatus().
STATUS_DISTINCT_IN_DATABASE
final int de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.STATUS_DISTINCT_IN_DATABASE = 0 static
Definition at line 333 of file LocationProcessor.java.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.Locator.localizeLocation().
STATUS_NOT_DISTINCT_IN_DATABASE
final int de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.STATUS_NOT_DISTINCT_IN_DATABASE = 1 static
Definition at line 332 of file LocationProcessor.java.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.Locator.localizeLocation(), de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.main(), and de.dlr.ivf.tapas.tools.locationallocation.Locator.updateLocation().
valueMap
final HashMap<String, String> de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.valueMap = new HashMap<>() private
The HashMap for the values
Definition at line 343 of file LocationProcessor.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/locationallocation/LocationProcessor.java