TAPAS: de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate Class Reference
de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate Class Reference
Classes
class ClassStatistics
enum Data
class DataRecord
enum Evaluation
Public Member Functions
CruisingSpeedValidate (CruisingSpeedValData valData, CruisingSpeedCalcData calcData)
void start ()
Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_BasicConnectionClass ()
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass)
TPS_BasicConnectionClass (String loginFile)
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass, String loginFile)
boolean checkMatrixName (String matrixName)
TPS_ParameterClass getParameters ()
String readParameter (String simKey, String paramKey)
void storeInDB (String matrixName, double[][] matrix, int decimalPlaces)
Static Public Member Functions
static void main (String[] args)
Static Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
static double[][] array1Dto2D (Integer[] matrixVal)
static double[][] array1Dto2D (int[] matrixVal)
static File getRuntimeFile (boolean forceNewFile)
static File getRuntimeFile (String propertyFile, boolean forceNewFile)
static File getRuntimeFile ()
static File getRuntimeFile (String propertyFile)
static int[][] intArray1Dto2D (int[] matrixVal)
static String matrixToSQLArray (double[][] array, int decimalPlaces)
static StringWriter matrixToStringWriterSQL (double[][] array, int decimalPlaces)
Private Member Functions
int calulateMinMaxValues (int index)
boolean checkFileName ()
void checkParameter (String text) throws IllegalArgumentException
void fillStatistics (Evaluation type)
void generateDifferencesMatrix ()
void generateFactorMatrix ()
void init ()
void initDistanceClasses ()
boolean readData ()
void readProperties () throws IllegalArgumentException
void validate ()
void writeFactorsToCVS ()
void writeStatisticsToCVS ()
Private Attributes
final CruisingSpeedValData propData
final CruisingSpeedCalcData calcData
final DataRecord[] records
final DataRecord[] differences
final DataRecord[] factors
int sizeOfClassDistance
int length
String directory = null
ClassStatistics[][] statistics = null
File file = null
Properties properties = null
String modus
String terrain
double[] calcFactors = null
Additional Inherited Members
Protected Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
void finalize ()
Protected Attributes inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_DB_Connector dbCon = null
TPS_ParameterClass parameterClass
Detailed Description
Author
Holger
Definition at line 31 of file CruisingSpeedValidate.java.
Constructor & Destructor Documentation
CruisingSpeedValidate()
de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.CruisingSpeedValidate (CruisingSpeedValData valData, CruisingSpeedCalcData calcData)
Definition at line 52 of file CruisingSpeedValidate.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.calcData, de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.differences, de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.factors, and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.records.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.main().
Member Function Documentation
calulateMinMaxValues()
int de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.calulateMinMaxValues (int index) private
The method stores min and max values in the given array and returns the count of classes
Parameters
index index of the matrix 0 - validation data , 1 - reference data, 2 - base data
Returns
count of classes for the given matrix in relation to BINS_WIDTH
Definition at line 93 of file CruisingSpeedValidate.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.records.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.validate().
checkFileName()
boolean de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.checkFileName () private
Definition at line 117 of file CruisingSpeedValidate.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.directory.
checkParameter()
void de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.checkParameter (String text) throws IllegalArgumentException private
Definition at line 126 of file CruisingSpeedValidate.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.directory, de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.modus, de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.records, and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.terrain.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.readProperties().
fillStatistics()
void de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.fillStatistics (Evaluation type) private
Definition at line 199 of file CruisingSpeedValidate.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.differences, de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.length, de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.records, de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.statistics, and type.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.validate().
generateDifferencesMatrix()
void de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.generateDifferencesMatrix () private
Definition at line 228 of file CruisingSpeedValidate.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.differences, de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.length, and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.records.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.validate().
generateFactorMatrix()
void de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.generateFactorMatrix () private
Definition at line 247 of file CruisingSpeedValidate.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.factors, de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.length, and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.records.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.validate().
init()
void de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.init () private
Definition at line 263 of file CruisingSpeedValidate.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.directory, de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.getRecordName(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.modus, de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.propData, de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.properties, de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.records, and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.terrain.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.readProperties().
initDistanceClasses()
void de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.initDistanceClasses () private
Definition at line 282 of file CruisingSpeedValidate.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.sizeOfClassDistance, and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.statistics.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.validate().
main()
static void de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.main (String[] args) static
Definition at line 79 of file CruisingSpeedValidate.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.CruisingSpeedValidate(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.start().
readData()
boolean de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.readData () private
Definition at line 295 of file CruisingSpeedValidate.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.array1Dto2D(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.calcData, de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.calcDistance(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.calcFactors, de.dlr.ivf.tapas.util.TPS_Geometrics.calcTop3(), de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.getFactors(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.modus, de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.records, and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.terrain.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.validate().
readProperties()
void de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.readProperties () throws IllegalArgumentException private
Definition at line 332 of file CruisingSpeedValidate.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.checkParameter(), de.dlr.ivf.tapas.util.PropertyReader.getProperties(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.init(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.properties, de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.propertyFileName, and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.records.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.start().
start()
void de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.start ()
Definition at line 346 of file CruisingSpeedValidate.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.DISTANCE, de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.generateRecordName(), de.dlr.ivf.tapas.tools.matrixMap.Modus.getName(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.getReferenceDist(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValData.getReferenceTT(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.length, de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.readProperties(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.TRAVELTIME, and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.validate().
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.main(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.start().
validate()
void de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.validate () private
Definition at line 392 of file CruisingSpeedValidate.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.calulateMinMaxValues(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.fillStatistics(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.generateDifferencesMatrix(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.generateFactorMatrix(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.initDistanceClasses(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.readData(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.sizeOfClassDistance, de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.writeFactorsToCVS(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.writeStatisticsToCVS().
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.start().
writeFactorsToCVS()
void de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.writeFactorsToCVS () private
Definition at line 428 of file CruisingSpeedValidate.java.
References de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.directory, de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.factors, de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.file, de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.length, and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.records.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.validate().
writeStatisticsToCVS()
void de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.writeStatisticsToCVS () private
Definition at line 491 of file CruisingSpeedValidate.java.
References de.dlr.ivf.tapas.tools.matrixMap.Modus.BIKE, de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.calcFactors, de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.directory, de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.file, de.dlr.ivf.tapas.tools.matrixMap.Modus.MIV, de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.modus, de.dlr.ivf.tapas.tools.matrixMap.Modus.PT, de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.records, de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.statistics, de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.terrain, and de.dlr.ivf.tapas.tools.matrixMap.Modus.WALK.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.validate().
Member Data Documentation
calcData
final CruisingSpeedCalcData de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.calcData private
Definition at line 36 of file CruisingSpeedValidate.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.CruisingSpeedValidate(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.readData().
calcFactors
double [] de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.calcFactors = null private
Definition at line 50 of file CruisingSpeedValidate.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.readData(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.writeStatisticsToCVS().
differences
final DataRecord [] de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.differences private
Definition at line 38 of file CruisingSpeedValidate.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.CruisingSpeedValidate(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.fillStatistics(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.generateDifferencesMatrix().
directory
String de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.directory = null private
Definition at line 42 of file CruisingSpeedValidate.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.checkFileName(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.checkParameter(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.init(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.writeFactorsToCVS(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.writeStatisticsToCVS().
factors
final DataRecord [] de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.factors private
Definition at line 39 of file CruisingSpeedValidate.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.CruisingSpeedValidate(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.generateFactorMatrix(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.writeFactorsToCVS().
file
File de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.file = null private
Definition at line 44 of file CruisingSpeedValidate.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.writeFactorsToCVS(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.writeStatisticsToCVS().
length
int de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.length private
Definition at line 41 of file CruisingSpeedValidate.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.fillStatistics(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.generateDifferencesMatrix(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.generateFactorMatrix(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.start(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.writeFactorsToCVS().
modus
String de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.modus private
Definition at line 46 of file CruisingSpeedValidate.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.checkParameter(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.init(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.readData(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.writeStatisticsToCVS().
propData
final CruisingSpeedValData de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.propData private
Definition at line 35 of file CruisingSpeedValidate.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.init().
properties
Properties de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.properties = null private
Definition at line 45 of file CruisingSpeedValidate.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.init(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.readProperties().
records
final DataRecord [] de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.records private
Definition at line 37 of file CruisingSpeedValidate.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.calulateMinMaxValues(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.checkParameter(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.CruisingSpeedValidate(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.fillStatistics(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.generateDifferencesMatrix(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.generateFactorMatrix(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.init(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.readData(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.readProperties(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.writeFactorsToCVS(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.writeStatisticsToCVS().
sizeOfClassDistance
int de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.sizeOfClassDistance private
Definition at line 40 of file CruisingSpeedValidate.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.initDistanceClasses(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.validate().
statistics
ClassStatistics [][] de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.statistics = null private
Definition at line 43 of file CruisingSpeedValidate.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.fillStatistics(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.initDistanceClasses(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.writeStatisticsToCVS().
terrain
String de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.terrain private
Definition at line 47 of file CruisingSpeedValidate.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.checkParameter(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.init(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.readData(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.writeStatisticsToCVS().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/matrixMap/CruisingSpeedValidate.java