TAPAS: de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel Class Reference
de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel Class Reference
Classes
class AlignmentRenderer
class BorderedRenderer
class ButtonRenderer
class ColorRenderer
class LongTextRenderer
class ProgressRenderer
class SimTableButtonEditor
class SimulationTableModel
class StringArrayRenderer
Public Member Functions
SimulationMonitorPanel (TPS_DB_Connector connection, TPS_ParameterClass parameterClass)
Static Public Member Functions
static void main (String[] args)
Private Member Functions
String[] getColumnNames ()
Object[] getRowFromSimulation (SimulationData simulation)
HashMap< String, Integer > getSimulations ()
void initTable ()
void removeSimulation (String simkey)
String textToHTML (String s)
void updateData ()
Private Attributes
final TPS_DB_Connector connection
final ConfigurableJTable table
final Timer updateTimer
final ClassifiedTableModel tableModel
Static Private Attributes
static final long serialVersionUID = -9157874571784201217L
Detailed Description
Definition at line 36 of file SimulationMonitorPanel.java.
Constructor & Destructor Documentation
SimulationMonitorPanel()
de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.SimulationMonitorPanel (TPS_DB_Connector connection, TPS_ParameterClass parameterClass)
Definition at line 47 of file SimulationMonitorPanel.java.
References de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.connection, de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.getColumnNames(), de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.table, de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.tableModel, de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.updateData(), and de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.updateTimer.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.main().
Member Function Documentation
getColumnNames()
String [] de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.getColumnNames () private
Definition at line 98 of file SimulationMonitorPanel.java.
References de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.getString(), and de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.init().
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.SimulationMonitorPanel().
getRowFromSimulation()
Object [] de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.getRowFromSimulation (SimulationData simulation) private
Definition at line 119 of file SimulationMonitorPanel.java.
References de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState.FINISHED, de.dlr.ivf.tapas.runtime.server.SimulationData.getDescription(), de.dlr.ivf.tapas.runtime.server.SimulationData.getKey(), de.dlr.ivf.tapas.runtime.server.SimulationData.getProgress(), de.dlr.ivf.tapas.runtime.server.SimulationData.getRelativeFileName(), de.dlr.ivf.tapas.runtime.server.SimulationData.getTimestampFinished(), de.dlr.ivf.tapas.runtime.server.SimulationData.getTimestampStarted(), de.dlr.ivf.tapas.runtime.server.SimulationData.getTotal(), de.dlr.ivf.tapas.runtime.server.SimulationData.minimumState(), de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState.STARTED, and de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState.STOPPED.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.updateData().
getSimulations()
HashMap<String, Integer> de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.getSimulations () private
Definition at line 139 of file SimulationMonitorPanel.java.
References de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.table.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.updateData().
initTable()
void de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.initTable () private
Definition at line 148 of file SimulationMonitorPanel.java.
References de.dlr.ivf.tapas.runtime.client.util.table.ConfigurableJTable.initTableColumn(), and de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.table.
main()
static void de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.main (String[] args) static
Parameters
args
Definition at line 73 of file SimulationMonitorPanel.java.
References de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.connection, de.dlr.ivf.tapas.runtime.util.ClientControlProperties.get(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.loadRuntimeParameters(), de.dlr.ivf.tapas.runtime.util.ClientControlProperties.ClientControlPropKey.LOGIN_CONFIG, and de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.SimulationMonitorPanel().
removeSimulation()
void de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.removeSimulation (String simkey) private
Definition at line 193 of file SimulationMonitorPanel.java.
References de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.table.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.updateData().
textToHTML()
String de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.textToHTML (String s) private
convert newlines to html breaks
Definition at line 205 of file SimulationMonitorPanel.java.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.LongTextRenderer.getTableCellRendererComponent().
updateData()
void de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.updateData () private
Definition at line 209 of file SimulationMonitorPanel.java.
References de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.connection, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_SIMULATIONS, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getParameters(), de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.getRowFromSimulation(), de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.getSimulations(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.removeSimulation(), de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.table, and de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.tableModel.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.SimulationMonitorPanel().
Member Data Documentation
connection
final TPS_DB_Connector de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.connection private
Definition at line 42 of file SimulationMonitorPanel.java.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.main(), de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.SimulationMonitorPanel(), de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.updateData(), and de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.SimulationTableModel.updateData().
serialVersionUID
final long de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.serialVersionUID = -9157874571784201217L static private
Definition at line 41 of file SimulationMonitorPanel.java.
table
final ConfigurableJTable de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.table private
Definition at line 43 of file SimulationMonitorPanel.java.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.getSimulations(), de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.AlignmentRenderer.getTableCellRendererComponent(), de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.LongTextRenderer.getTableCellRendererComponent(), de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.BorderedRenderer.getTableCellRendererComponent(), de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.ButtonRenderer.getTableCellRendererComponent(), de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.StringArrayRenderer.getTableCellRendererComponent(), de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.ColorRenderer.getTableCellRendererComponent(), de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.ProgressRenderer.getTableCellRendererComponent(), de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.initTable(), de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.removeSimulation(), de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.SimulationMonitorPanel(), and de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.updateData().
tableModel
final ClassifiedTableModel de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.tableModel private
Definition at line 45 of file SimulationMonitorPanel.java.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.SimulationMonitorPanel(), and de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.updateData().
updateTimer
final Timer de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.updateTimer private
Definition at line 44 of file SimulationMonitorPanel.java.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.SimulationMonitorPanel().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/runtime/client/SimulationMonitorPanel.java