TAPAS: de.dlr.ivf.tapas.runtime.server.SimulationServer.RunWhenShuttingDown Class Reference
de.dlr.ivf.tapas.runtime.server.SimulationServer.RunWhenShuttingDown Class Reference
Public Member Functions
void run ()
Detailed Description
Definition at line 414 of file SimulationServer.java.
Member Function Documentation
run()
void de.dlr.ivf.tapas.runtime.server.SimulationServer.RunWhenShuttingDown.run ()
Definition at line 416 of file SimulationServer.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_PROCESSES, de.dlr.ivf.tapas.runtime.server.SimulationServer.dbConnector, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeUpdate(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection(), de.dlr.ivf.tapas.runtime.server.SimulationServer.getParameters(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.runtime.server.SimulationServer.hostname, de.dlr.ivf.tapas.runtime.server.SimulationServer.keepOn, de.dlr.ivf.tapas.TPS_Main.TPS_State.setRunning(), de.dlr.ivf.tapas.runtime.server.SimulationServer.shutdown, de.dlr.ivf.tapas.runtime.server.SimulationServer.shuttingDown, de.dlr.ivf.tapas.TPS_Main.STATE, de.dlr.ivf.tapas.runtime.server.SimulationServer.sysoutPrefix, de.dlr.ivf.tapas.runtime.server.SimulationServer.timer, and de.dlr.ivf.tapas.TPS_Main.waitForMe.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/runtime/server/SimulationServer.java