TAPAS: de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.SimulationTableModel.SimulationList Class Reference
de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.SimulationTableModel.SimulationList Class Reference
Public Member Functions
Object get (int row, int col)
SimulationData get (String simkey)
HashSet< String > getKeySet ()
boolean remove (String simkey)
Static Private Attributes
static final long serialVersionUID = -2387380790466400080L
Detailed Description
Definition at line 746 of file SimulationMonitorPanel.java.
Member Function Documentation
get() [1/2]
Object de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.SimulationTableModel.SimulationList.get (int row, int col)
Definition at line 752 of file SimulationMonitorPanel.java.
References de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState.FINISHED, de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState.getAction(), de.dlr.ivf.tapas.runtime.server.SimulationData.getDescription(), de.dlr.ivf.tapas.runtime.server.SimulationData.getKey(), de.dlr.ivf.tapas.runtime.server.SimulationData.getProgress(), de.dlr.ivf.tapas.runtime.server.SimulationData.getRelativeFileName(), de.dlr.ivf.tapas.runtime.server.SimulationData.getState(), de.dlr.ivf.tapas.runtime.server.SimulationData.getTimestampFinished(), de.dlr.ivf.tapas.runtime.server.SimulationData.getTimestampStarted(), de.dlr.ivf.tapas.runtime.server.SimulationData.getTotal(), de.dlr.ivf.tapas.runtime.server.SimulationData.minimumState(), de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState.STARTED, and de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState.STOPPED.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.SimulationTableModel.getValueAt(), and de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.SimulationTableModel.updateData().
get() [2/2]
SimulationData de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.SimulationTableModel.SimulationList.get (String simkey)
Definition at line 794 of file SimulationMonitorPanel.java.
References de.dlr.ivf.tapas.runtime.server.SimulationData.getKey().
getKeySet()
HashSet<String> de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.SimulationTableModel.SimulationList.getKeySet ()
Definition at line 803 of file SimulationMonitorPanel.java.
References de.dlr.ivf.tapas.runtime.server.SimulationData.getKey().
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.SimulationTableModel.updateData().
remove()
boolean de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.SimulationTableModel.SimulationList.remove (String simkey)
Definition at line 811 of file SimulationMonitorPanel.java.
References de.dlr.ivf.tapas.runtime.server.SimulationData.getKey().
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.SimulationTableModel.updateData().
Member Data Documentation
serialVersionUID
final long de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.SimulationTableModel.SimulationList.serialVersionUID = -2387380790466400080L static private
Definition at line 750 of file SimulationMonitorPanel.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/runtime/client/SimulationMonitorPanel.java