TAPAS: de.dlr.ivf.tapas.util.parameters.ParamMatrixClass Class Reference
de.dlr.ivf.tapas.util.parameters.ParamMatrixClass Class Reference
Public Member Functions
void clear (ParamMatrix param)
Matrix getMatrix (ParamMatrix param)
Matrix getMatrix (ParamMatrix param, SimulationType type)
ParamType getType (ParamMatrix param)
double getValue (ParamMatrix param, int i, int j)
double getValue (ParamMatrix param, int i, int j, SimulationType type)
boolean isDefined (ParamMatrix param)
void setMatrix (ParamMatrix param, Matrix matrix)
void setMatrix (ParamMatrix param, Matrix matrix, SimulationType type)
String toRawString (ParamMatrix param)
Private Attributes
final EnumMap< ParamMatrix, MutablePair< ParamType, Matrix[]> > paramMatrix
Detailed Description
Definition at line 19 of file ParamMatrixClass.java.
Member Function Documentation
clear()
void de.dlr.ivf.tapas.util.parameters.ParamMatrixClass.clear (ParamMatrix param)
Sets all matrices of a matrix parameter to null.
Parameters
param matrix parameter enum
Definition at line 38 of file ParamMatrixClass.java.
getMatrix() [1/2]
Matrix de.dlr.ivf.tapas.util.parameters.ParamMatrixClass.getMatrix (ParamMatrix param)
If there exist only one matrix, this matrix is returned. If there exists two matrices this matrix is returned which corresponds to the simulation type. The simulation type is retrieved by the method getSimulationType().
Parameters
param matrix parameter enum
Returns
one matrix of the enum constant
Exceptions
RuntimeException This exception is thrown if the constant was not defined
Definition at line 53 of file ParamMatrixClass.java.
References de.dlr.ivf.tapas.util.parameters.SimulationType.SCENARIO.
Referenced by de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getMatrix(), and de.dlr.ivf.tapas.util.parameters.ParamMatrixClass.getValue().
getMatrix() [2/2]
Matrix de.dlr.ivf.tapas.util.parameters.ParamMatrixClass.getMatrix (ParamMatrix param, SimulationType type)
The matrix corresponding to the given simulation type is returned.
Parameters
param matrix parameter enum
type simulation type
Returns
matrix corresponding to the given simulation type
Exceptions
RuntimeException This exception is thrown if the constant was not defined or the constant is not simulation type dependent
Definition at line 72 of file ParamMatrixClass.java.
References type.
getType()
ParamType de.dlr.ivf.tapas.util.parameters.ParamMatrixClass.getType (ParamMatrix param)
Parameters
param parameter matrix enum
Returns
parameter type
Definition at line 86 of file ParamMatrixClass.java.
Referenced by de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getType().
getValue() [1/2]
double de.dlr.ivf.tapas.util.parameters.ParamMatrixClass.getValue (ParamMatrix param, int i, int j)
This method uses the getMatrix() method so it returns the value corresponding to the current simulation type.
Parameters
param matrix parameter enum
i line position
j column position
Returns
value at position (i,j)
Exceptions
RuntimeException if the constant was not defined
Definition at line 100 of file ParamMatrixClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamMatrixClass.getMatrix(), and de.dlr.ivf.tapas.util.Matrix.getValue().
Referenced by de.dlr.ivf.tapas.mode.TPS_IndividualTransportMode.getDistance(), de.dlr.ivf.tapas.mode.TPS_NonMotorisedMode.getDistance(), de.dlr.ivf.tapas.util.TPS_Geometrics.getDistance(), de.dlr.ivf.tapas.mode.TPS_IndividualTransportMode.getTravelTime(), and de.dlr.ivf.tapas.mode.TPS_NonMotorisedMode.getTravelTime().
getValue() [2/2]
double de.dlr.ivf.tapas.util.parameters.ParamMatrixClass.getValue (ParamMatrix param, int i, int j, SimulationType type)
This method uses the getMatrix(SimulationType type) method so it returns the value corresponding to the given simulation type.
Parameters
param matrix parameter enum
i line position
j column position
type type of the simulation
Returns
value at position (i,j)
Exceptions
RuntimeException if the constant was not defined
Definition at line 115 of file ParamMatrixClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamMatrixClass.getMatrix(), de.dlr.ivf.tapas.util.Matrix.getValue(), and type.
isDefined()
boolean de.dlr.ivf.tapas.util.parameters.ParamMatrixClass.isDefined (ParamMatrix param)
Flag if matrix has been instantiated
Parameters
param matrix parameter enum
Returns
true, if matrix is defined, false else
Definition at line 125 of file ParamMatrixClass.java.
Referenced by de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isDefined(), and de.dlr.ivf.tapas.util.parameters.ParamMatrixClass.toRawString().
setMatrix() [1/2]
void de.dlr.ivf.tapas.util.parameters.ParamMatrixClass.setMatrix (ParamMatrix param, Matrix matrix)
This method sets one matrix in the array. This method is for constants which don't depend on the simulation type
Parameters
param matrix parameter enum
matrix new matrix to set
Definition at line 140 of file ParamMatrixClass.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.DEBUG, and de.dlr.ivf.tapas.log.TPS_Logger.log().
Referenced by de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.setMatrix().
setMatrix() [2/2]
void de.dlr.ivf.tapas.util.parameters.ParamMatrixClass.setMatrix (ParamMatrix param, Matrix matrix, SimulationType type)
This method sets one matrix in the array. This method is for constants which do depend on the simulation type
Parameters
param matrix parameter enum
matrix new matrix to set
type type of the simulation
Definition at line 159 of file ParamMatrixClass.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.DEBUG, de.dlr.ivf.tapas.log.TPS_Logger.log(), and type.
toRawString()
String de.dlr.ivf.tapas.util.parameters.ParamMatrixClass.toRawString (ParamMatrix param)
Creates a raw string for all matrices
Parameters
param matrix parameter enum
Returns
a String containing the raw values of all matrices
Definition at line 177 of file ParamMatrixClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamMatrixClass.isDefined(), and de.dlr.ivf.tapas.util.parameters.ParamMatrixClass.paramMatrix.
Member Data Documentation
paramMatrix
final EnumMap<ParamMatrix, MutablePair<ParamType, Matrix[]> > de.dlr.ivf.tapas.util.parameters.ParamMatrixClass.paramMatrix private
Definition at line 20 of file ParamMatrixClass.java.
Referenced by de.dlr.ivf.tapas.util.parameters.ParamMatrixClass.toRawString().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/util/parameters/ParamMatrixClass.java