TAPAS: de.dlr.ivf.tapas.tools.TPS_ParkingSpaceAproximator Class Reference
de.dlr.ivf.tapas.tools.TPS_ParkingSpaceAproximator Class Reference
Public Member Functions
void calcParkingTimes (double minSearch, double maxSearch, double searchSpeedCar, double blockDistance, double walkSpeed, double saturationFactor)
void loadPersonsAndCars (String db, String key)
void loadTazArea (String db)
void storeSQLMatrix (String db, String nameEgress, String nameAccess)
Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_BasicConnectionClass ()
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass)
TPS_BasicConnectionClass (String loginFile)
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass, String loginFile)
boolean checkMatrixName (String matrixName)
TPS_ParameterClass getParameters ()
String readParameter (String simKey, String paramKey)
void storeInDB (String matrixName, double[][] matrix, int decimalPlaces)
Static Public Member Functions
static void main (String[] args)
Static Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
static double[][] array1Dto2D (Integer[] matrixVal)
static double[][] array1Dto2D (int[] matrixVal)
static File getRuntimeFile (boolean forceNewFile)
static File getRuntimeFile (String propertyFile, boolean forceNewFile)
static File getRuntimeFile ()
static File getRuntimeFile (String propertyFile)
static int[][] intArray1Dto2D (int[] matrixVal)
static String matrixToSQLArray (double[][] array, int decimalPlaces)
static StringWriter matrixToStringWriterSQL (double[][] array, int decimalPlaces)
Additional Inherited Members
Protected Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
void finalize ()
Protected Attributes inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_DB_Connector dbCon = null
TPS_ParameterClass parameterClass
Detailed Description
Definition at line 21 of file TPS_ParkingSpaceAproximator.java.
Member Function Documentation
calcParkingTimes()
void de.dlr.ivf.tapas.tools.TPS_ParkingSpaceAproximator.calcParkingTimes (double minSearch, double maxSearch, double searchSpeedCar, double blockDistance, double walkSpeed, double saturationFactor)
Theory behind it:
Searching for a parking lot: The probability to find a parking lot in a area with a fixed availability of parking spaces increases linearly with the street length covered. The availability of parking lots decreases linearly with the density of cars is a specific region. ->Extension: We found this true for the first 90%! So interpolate between 0 and the 80%-Median So we interpolate between a given minimum (e. g. 10 m) and maximum search distance (e.g. 1500m). Additionally a search speed is needed to calculate the search time.
Going back to your original destination If you found a parking lot, you have to walk back to your original destination. But the search-strategy is most probable a spiral around the original destination. We assume grid-blocks (Manhattan style). The search strategy is as follows: First round you drive around the block, called center block (4 Streets) Second round you drive around the cross around the center block (12 streets -draw it!) Third round you drive around the diamond arount the cros (20 streets) Forth round 28 Streets...
When you draw it you see that the length of the search line increases by eight segments every round (plus + street to the next circle, but we ommit that ;))
The length of going back to the origin is the number of rounds but the length of the search distance is the sum of street segments for all rounds
So if you know the block distance, a walking speed and have a search length for finding a lot, you can calculate the walking distance between lot and destination.
Parameters
minSearch the minimum search distance in meters eg 10m
maxSearch the maximum search distance in meters e.g. 1500m
searchSpeedCar the speed during the search in m/s (e.g. 14.4km/h = 4m/s)
blockDistance the average block length in meters (e.g. 1000)
walkSpeed the speed going back in m/s (e.g. 3.6km/h = 1m/s)
saturationFactor is the factor between 0 and 1, how many regions are affected by less than the maximum search radius.
Definition at line 101 of file TPS_ParkingSpaceAproximator.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_ParkingSpaceAproximator.main().
loadPersonsAndCars()
void de.dlr.ivf.tapas.tools.TPS_ParkingSpaceAproximator.loadPersonsAndCars (String db, String key)
Definition at line 157 of file TPS_ParkingSpaceAproximator.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery().
Referenced by de.dlr.ivf.tapas.tools.TPS_ParkingSpaceAproximator.main().
loadTazArea()
void de.dlr.ivf.tapas.tools.TPS_ParkingSpaceAproximator.loadTazArea (String db)
Definition at line 180 of file TPS_ParkingSpaceAproximator.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery().
Referenced by de.dlr.ivf.tapas.tools.TPS_ParkingSpaceAproximator.main().
main()
static void de.dlr.ivf.tapas.tools.TPS_ParkingSpaceAproximator.main (String[] args) static
Definition at line 34 of file TPS_ParkingSpaceAproximator.java.
References de.dlr.ivf.tapas.tools.TPS_ParkingSpaceAproximator.calcParkingTimes(), de.dlr.ivf.tapas.tools.TPS_ParkingSpaceAproximator.loadPersonsAndCars(), de.dlr.ivf.tapas.tools.TPS_ParkingSpaceAproximator.loadTazArea(), and de.dlr.ivf.tapas.tools.TPS_ParkingSpaceAproximator.storeSQLMatrix().
storeSQLMatrix()
void de.dlr.ivf.tapas.tools.TPS_ParkingSpaceAproximator.storeSQLMatrix (String db, String nameEgress, String nameAccess)
Definition at line 202 of file TPS_ParkingSpaceAproximator.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.matrixToSQLArray(), and de.dlr.ivf.tapas.util.Matrix.setValue().
Referenced by de.dlr.ivf.tapas.tools.TPS_ParkingSpaceAproximator.main().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/TPS_ParkingSpaceAproximator.java