TAPAS: de.dlr.ivf.scripts.SumoTripVisualization Class Reference
de.dlr.ivf.scripts.SumoTripVisualization Class Reference
Classes
class Route
Public Member Functions
void readFile (String fileName)
void writeSQLQuery (String filename) throws IOException
Static Public Member Functions
static void main (String[] args) throws IOException
Protected Member Functions
void finalize ()
Private Attributes
final List< Route > myRoutes = new ArrayList<>()
Static Private Attributes
static final String table = "core.berlin_routes"
Detailed Description
Definition at line 24 of file SumoTripVisualization.java.
Member Function Documentation
finalize()
void de.dlr.ivf.scripts.SumoTripVisualization.finalize () protected
Definition at line 39 of file SumoTripVisualization.java.
main()
static void de.dlr.ivf.scripts.SumoTripVisualization.main (String[] args) throws IOException static
Definition at line 28 of file SumoTripVisualization.java.
References de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.loadRuntimeParameters(), de.dlr.ivf.scripts.SumoTripVisualization.readFile(), and de.dlr.ivf.scripts.SumoTripVisualization.writeSQLQuery().
readFile()
void de.dlr.ivf.scripts.SumoTripVisualization.readFile (String fileName)
Definition at line 44 of file SumoTripVisualization.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.INFO, de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), and de.dlr.ivf.tapas.log.TPS_Logger.log().
Referenced by de.dlr.ivf.scripts.SumoTripVisualization.main().
writeSQLQuery()
void de.dlr.ivf.scripts.SumoTripVisualization.writeSQLQuery (String filename) throws IOException
Definition at line 92 of file SumoTripVisualization.java.
References de.dlr.ivf.scripts.SumoTripVisualization.table.
Referenced by de.dlr.ivf.scripts.SumoTripVisualization.main().
Member Data Documentation
myRoutes
final List<Route> de.dlr.ivf.scripts.SumoTripVisualization.myRoutes = new ArrayList<>() private
Definition at line 26 of file SumoTripVisualization.java.
table
final String de.dlr.ivf.scripts.SumoTripVisualization.table = "core.berlin_routes" static private
Definition at line 25 of file SumoTripVisualization.java.
Referenced by de.dlr.ivf.scripts.SumoTripVisualization.writeSQLQuery().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/scripts/SumoTripVisualization.java