TAPAS: de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartFactory Class Reference
de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartFactory Class Reference
Classes
class QualityChartLegendGerator
Static Public Member Functions
static JFreeChart createChart (ArrayList< QualityChartData > data)
static void main (String[] args)
Static Private Attributes
static final String TOOL_TIP_TEMPLATE = "<html><div align=\"center\">%s<br />(%.3f;%.3f)</div></html>"
Detailed Description
Factory to create a JFreeChart for quality assessment of traffic simulations.
This class handles the specifics of the JFreeChart library.
Author
boec_pa
Definition at line 37 of file QualityChartFactory.java.
Member Function Documentation
createChart()
static JFreeChart de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartFactory.createChart (ArrayList< QualityChartData > data) static
Parameters
data
Returns
Definition at line 45 of file QualityChartFactory.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.Quality.BAD, de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.Key.DATA_HIGH, de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.Key.DATA_LOW, de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.Key.DATA_MED, de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.getXValue(), de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.getYValue(), de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.Quality.GOOD, de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.indexOf(), de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.Key.LOWER_CONFIDENCE, de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.Key.LOWER_GEH5, de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.Quality.MEDIUM, de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.Key.OPTIMAL, de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartFactory.TOOL_TIP_TEMPLATE, de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.Key.UPPER_CONFIDENCE, and de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.Key.UPPER_GEH5.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartFactory.main(), and de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDatasetDBFetcher.makeQSChart().
main()
static void de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartFactory.main (String[] args) static
For testing purposes only
Parameters
args
Definition at line 150 of file QualityChartFactory.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartFactory.createChart().
Member Data Documentation
TOOL_TIP_TEMPLATE
final String de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartFactory.TOOL_TIP_TEMPLATE = "<html><div align=\"center\">%s<br />(%.3f;%.3f)</div></html>" static private
Definition at line 39 of file QualityChartFactory.java.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartFactory.createChart().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/runtime/client/Graphics/QualityChart/QualityChartFactory.java