TAPAS: de.dlr.ivf.tapas.tools.OpportunityDistribution.UniqueStreetIdentifier.PlzPair Class Reference
de.dlr.ivf.tapas.tools.OpportunityDistribution.UniqueStreetIdentifier.PlzPair Class Reference
Public Member Functions
PlzPair (String left, String right)
boolean equals (Object o)
String getLeft ()
String getRight ()
int hashCode ()
String toString ()
Private Attributes
final String left
final String right
Detailed Description
Definition at line 206 of file UniqueStreetIdentifier.java.
Constructor & Destructor Documentation
PlzPair()
de.dlr.ivf.tapas.tools.OpportunityDistribution.UniqueStreetIdentifier.PlzPair.PlzPair (String left, String right)
Definition at line 210 of file UniqueStreetIdentifier.java.
References de.dlr.ivf.tapas.tools.OpportunityDistribution.UniqueStreetIdentifier.PlzPair.left, and de.dlr.ivf.tapas.tools.OpportunityDistribution.UniqueStreetIdentifier.PlzPair.right.
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.UniqueStreetIdentifier.PlzPair.equals().
Member Function Documentation
equals()
boolean de.dlr.ivf.tapas.tools.OpportunityDistribution.UniqueStreetIdentifier.PlzPair.equals (Object o)
Definition at line 216 of file UniqueStreetIdentifier.java.
References de.dlr.ivf.tapas.tools.OpportunityDistribution.UniqueStreetIdentifier.PlzPair.equals(), de.dlr.ivf.tapas.tools.OpportunityDistribution.UniqueStreetIdentifier.PlzPair.getLeft(), de.dlr.ivf.tapas.tools.OpportunityDistribution.UniqueStreetIdentifier.PlzPair.getRight(), and de.dlr.ivf.tapas.tools.OpportunityDistribution.UniqueStreetIdentifier.PlzPair.PlzPair().
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.UniqueStreetIdentifier.PlzPair.equals().
getLeft()
String de.dlr.ivf.tapas.tools.OpportunityDistribution.UniqueStreetIdentifier.PlzPair.getLeft ()
Definition at line 223 of file UniqueStreetIdentifier.java.
References de.dlr.ivf.tapas.tools.OpportunityDistribution.UniqueStreetIdentifier.PlzPair.left.
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.UniqueStreetIdentifier.PlzPair.equals().
getRight()
String de.dlr.ivf.tapas.tools.OpportunityDistribution.UniqueStreetIdentifier.PlzPair.getRight ()
Definition at line 227 of file UniqueStreetIdentifier.java.
References de.dlr.ivf.tapas.tools.OpportunityDistribution.UniqueStreetIdentifier.PlzPair.right.
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.UniqueStreetIdentifier.PlzPair.equals().
hashCode()
int de.dlr.ivf.tapas.tools.OpportunityDistribution.UniqueStreetIdentifier.PlzPair.hashCode ()
Definition at line 232 of file UniqueStreetIdentifier.java.
References de.dlr.ivf.tapas.tools.OpportunityDistribution.UniqueStreetIdentifier.PlzPair.left, and de.dlr.ivf.tapas.tools.OpportunityDistribution.UniqueStreetIdentifier.PlzPair.right.
toString()
String de.dlr.ivf.tapas.tools.OpportunityDistribution.UniqueStreetIdentifier.PlzPair.toString ()
Definition at line 237 of file UniqueStreetIdentifier.java.
References de.dlr.ivf.tapas.tools.OpportunityDistribution.UniqueStreetIdentifier.PlzPair.left, and de.dlr.ivf.tapas.tools.OpportunityDistribution.UniqueStreetIdentifier.PlzPair.right.
Member Data Documentation
left
final String de.dlr.ivf.tapas.tools.OpportunityDistribution.UniqueStreetIdentifier.PlzPair.left private
Definition at line 207 of file UniqueStreetIdentifier.java.
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.UniqueStreetIdentifier.PlzPair.getLeft(), de.dlr.ivf.tapas.tools.OpportunityDistribution.UniqueStreetIdentifier.PlzPair.hashCode(), de.dlr.ivf.tapas.tools.OpportunityDistribution.UniqueStreetIdentifier.PlzPair.PlzPair(), and de.dlr.ivf.tapas.tools.OpportunityDistribution.UniqueStreetIdentifier.PlzPair.toString().
right
final String de.dlr.ivf.tapas.tools.OpportunityDistribution.UniqueStreetIdentifier.PlzPair.right private
Definition at line 208 of file UniqueStreetIdentifier.java.
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.UniqueStreetIdentifier.PlzPair.getRight(), de.dlr.ivf.tapas.tools.OpportunityDistribution.UniqueStreetIdentifier.PlzPair.hashCode(), de.dlr.ivf.tapas.tools.OpportunityDistribution.UniqueStreetIdentifier.PlzPair.PlzPair(), and de.dlr.ivf.tapas.tools.OpportunityDistribution.UniqueStreetIdentifier.PlzPair.toString().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/OpportunityDistribution/UniqueStreetIdentifier.java