TAPAS: de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator Class Reference
de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator Class Reference
Static Public Member Functions
static void showDialog (JFrame parent, Statement stat, String dbMatrixMap, String dbMatrix, String entry)
Private Member Functions
void addMatrixToMatrixMap ()
void changeMatrixInMatrixMap ()
void changeTimeInMatrixMap ()
boolean checkAndSaveMatrixMap ()
boolean checkMatrixMap ()
boolean closeAction ()
void deleteMatrixFromMatrixMap ()
JPanel getAvailableMatrixPanel ()
JButton getChangeMatrixButton ()
JButton getChangeTimeButton ()
JPanel getCurrentMatrixMapSetPanel ()
JButton getDeleteButton ()
JPanel getMainPanel1 ()
JSplitPane getMainSplitPane ()
JButton getMatrixAddButton ()
JPanel getMatrixButtonPanel ()
JPanel getMatrixMapButtonPanel ()
JScrollPane getMatrixMapEntriesScrollPane ()
JScrollPane getMatrixScrollPane ()
JButton getSaveButton ()
void initialize ()
boolean isValidTime (double time)
void loadMatrixList ()
void loadMatrixMapEntries ()
void updateMatrixMapDisplay ()
Private Attributes
Statement statement = null
String dbMatrixName = ""
String dbName = ""
String entryName = ""
JPanel mainPanel1 = null
JSplitPane mainSplitPane = null
JPanel availableMatrixPanel = null
JPanel currentMatrixMapSetPanel = null
JScrollPane matrixScrollPane = null
JList< String > availableMatrixList
JList< String > matrixMapList
JScrollPane matrixMapEntriesScrollPane = null
JPanel matrixMapButtonPanel = null
JPanel matrixButtonPanel = null
JButton matrixAddButton = null
JButton changeMatrixButton = null
JButton changeTimeButton = null
JButton deleteButton = null
String[] matrixEntries = null
double[] distribution = null
JButton saveButton = null
Static Private Attributes
static final long serialVersionUID = -6979246790481072698L
Detailed Description
Class for the "edit MatrixMap"-Dialog. This modal dialog is called by the MatrixMapHandler
Author
hein_mh
Definition at line 26 of file MatrixMapManipulator.java.
Member Function Documentation
addMatrixToMatrixMap()
void de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.addMatrixToMatrixMap () private
method to add the selected matrix to the matrixMap
Definition at line 91 of file MatrixMapManipulator.java.
References de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.checkMatrixMap(), de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.distribution, de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.isValidTime(), and de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.updateMatrixMapDisplay().
changeMatrixInMatrixMap()
void de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.changeMatrixInMatrixMap () private
method to change the selected matrix-references in the matrixmap
Definition at line 133 of file MatrixMapManipulator.java.
References de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.updateMatrixMapDisplay().
changeTimeInMatrixMap()
void de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.changeTimeInMatrixMap () private
method to change the time for the selected entries
Definition at line 160 of file MatrixMapManipulator.java.
References de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.checkMatrixMap(), de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.isValidTime(), and de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.updateMatrixMapDisplay().
checkAndSaveMatrixMap()
boolean de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.checkAndSaveMatrixMap () private
method to check, if the entries are valid and save them
Returns
sucessfull check and save
Definition at line 198 of file MatrixMapManipulator.java.
References de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.checkMatrixMap(), de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.distribution, de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.matrixEntries, and de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.statement.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.closeAction().
checkMatrixMap()
boolean de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.checkMatrixMap () private
method to check, if the entries are valid
Returns
sucessfull check
Definition at line 242 of file MatrixMapManipulator.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.addMatrixToMatrixMap(), de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.changeTimeInMatrixMap(), and de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.checkAndSaveMatrixMap().
closeAction()
boolean de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.closeAction () private
method to check if saving is needed and asks to save or not
Returns
success of this operation
Definition at line 272 of file MatrixMapManipulator.java.
References de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.checkAndSaveMatrixMap().
deleteMatrixFromMatrixMap()
void de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.deleteMatrixFromMatrixMap () private
method to delete selected matrix entries from matrixMap
Definition at line 286 of file MatrixMapManipulator.java.
References de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.matrixEntries, and de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.updateMatrixMapDisplay().
getAvailableMatrixPanel()
JPanel de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.getAvailableMatrixPanel () private
This method initializes availableMatrixPanel
Returns
javax.swing.JPanel
Definition at line 329 of file MatrixMapManipulator.java.
References de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.availableMatrixPanel, de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.getMatrixButtonPanel(), de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.getMatrixScrollPane(), and de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.newGridBag().
getChangeMatrixButton()
JButton de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.getChangeMatrixButton () private
This method initializes changeMatrixButton
Returns
javax.swing.JButton
Definition at line 348 of file MatrixMapManipulator.java.
References de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.changeMatrixButton.
getChangeTimeButton()
JButton de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.getChangeTimeButton () private
This method initializes changeTimeButton
Returns
javax.swing.JButton
Definition at line 366 of file MatrixMapManipulator.java.
getCurrentMatrixMapSetPanel()
JPanel de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.getCurrentMatrixMapSetPanel () private
This method initializes currentMatrixMapSetPanel
Returns
javax.swing.JPanel
Definition at line 384 of file MatrixMapManipulator.java.
References de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.newGridBag().
getDeleteButton()
JButton de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.getDeleteButton () private
This method initializes deleteButton
Returns
javax.swing.JButton
Definition at line 402 of file MatrixMapManipulator.java.
getMainPanel1()
JPanel de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.getMainPanel1 () private
This method initializes mainPanel1
Returns
javax.swing.JPanel
Definition at line 420 of file MatrixMapManipulator.java.
References de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.newGridBag().
getMainSplitPane()
JSplitPane de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.getMainSplitPane () private
This method initializes mainSplitPane
Returns
javax.swing.JSplitPane
Definition at line 437 of file MatrixMapManipulator.java.
getMatrixAddButton()
JButton de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.getMatrixAddButton () private
This method initializes matrixAddButton
Returns
javax.swing.JButton
Definition at line 451 of file MatrixMapManipulator.java.
getMatrixButtonPanel()
JPanel de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.getMatrixButtonPanel () private
This method initializes matrixButtonPanel
Returns
javax.swing.JPanel
Definition at line 469 of file MatrixMapManipulator.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.getAvailableMatrixPanel().
getMatrixMapButtonPanel()
JPanel de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.getMatrixMapButtonPanel () private
This method initializes matrixMapButtonPanel
Returns
javax.swing.JPanel
Definition at line 483 of file MatrixMapManipulator.java.
getMatrixMapEntriesScrollPane()
JScrollPane de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.getMatrixMapEntriesScrollPane () private
This method initializes matrixMapEntriesScrollPane
Returns
javax.swing.JScrollPane
Definition at line 499 of file MatrixMapManipulator.java.
getMatrixScrollPane()
JScrollPane de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.getMatrixScrollPane () private
This method initializes matrixScrollPane
Returns
javax.swing.JScrollPane
Definition at line 511 of file MatrixMapManipulator.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.getAvailableMatrixPanel().
getSaveButton()
JButton de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.getSaveButton () private
This method initializes saveButton
Returns
javax.swing.JButton
Definition at line 523 of file MatrixMapManipulator.java.
initialize()
void de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.initialize () private
This method initialises this instance
Definition at line 540 of file MatrixMapManipulator.java.
isValidTime()
boolean de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.isValidTime (double time) private
method to check if this new timeslot is valid
Returns
true if valid
Definition at line 564 of file MatrixMapManipulator.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.addMatrixToMatrixMap(), and de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.changeTimeInMatrixMap().
loadMatrixList()
void de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.loadMatrixList () private
method to fill the matrixlist with the entries from the db
Definition at line 580 of file MatrixMapManipulator.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.showDialog().
loadMatrixMapEntries()
void de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.loadMatrixMapEntries () private
method to fill the matrixlist with the entries from the db
Definition at line 601 of file MatrixMapManipulator.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.showDialog().
showDialog()
static void de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.showDialog (JFrame parent, Statement stat, String dbMatrixMap, String dbMatrix, String entry) static
static method to get a dialog
Parameters
parent parent frame for modal mode
stat the statement for the sql-db
dbMatrixMap the name of the matrixMap-table
dbMatrix the name of the matrix-table
entry the entry to edit in dbMatrixMap
Definition at line 72 of file MatrixMapManipulator.java.
References de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.changeMatrixButton, de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.changeTimeButton, de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.dbMatrixName, de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.dbName, de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.deleteButton, de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.entryName, de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.loadMatrixList(), de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.loadMatrixMapEntries(), de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.matrixAddButton, and de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.statement.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.editMatrixMap().
updateMatrixMapDisplay()
void de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.updateMatrixMapDisplay () private
method to update the matrixmap-related fields
Definition at line 646 of file MatrixMapManipulator.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.addMatrixToMatrixMap(), de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.changeMatrixInMatrixMap(), de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.changeTimeInMatrixMap(), and de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.deleteMatrixFromMatrixMap().
Member Data Documentation
availableMatrixList
JList<String> de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.availableMatrixList private
Definition at line 40 of file MatrixMapManipulator.java.
availableMatrixPanel
JPanel de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.availableMatrixPanel = null private
Definition at line 37 of file MatrixMapManipulator.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.getAvailableMatrixPanel().
changeMatrixButton
JButton de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.changeMatrixButton = null private
Definition at line 46 of file MatrixMapManipulator.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.getChangeMatrixButton(), and de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.showDialog().
changeTimeButton
JButton de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.changeTimeButton = null private
Definition at line 47 of file MatrixMapManipulator.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.showDialog().
currentMatrixMapSetPanel
JPanel de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.currentMatrixMapSetPanel = null private
Definition at line 38 of file MatrixMapManipulator.java.
dbMatrixName
String de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.dbMatrixName = "" private
Definition at line 32 of file MatrixMapManipulator.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.showDialog().
dbName
String de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.dbName = "" private
Definition at line 33 of file MatrixMapManipulator.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.showDialog().
deleteButton
JButton de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.deleteButton = null private
Definition at line 48 of file MatrixMapManipulator.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.showDialog().
distribution
double [] de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.distribution = null private
Definition at line 50 of file MatrixMapManipulator.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.addMatrixToMatrixMap(), and de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.checkAndSaveMatrixMap().
entryName
String de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.entryName = "" private
Definition at line 34 of file MatrixMapManipulator.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.showDialog().
mainPanel1
JPanel de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.mainPanel1 = null private
Definition at line 35 of file MatrixMapManipulator.java.
mainSplitPane
JSplitPane de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.mainSplitPane = null private
Definition at line 36 of file MatrixMapManipulator.java.
matrixAddButton
JButton de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.matrixAddButton = null private
Definition at line 45 of file MatrixMapManipulator.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.showDialog().
matrixButtonPanel
JPanel de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.matrixButtonPanel = null private
Definition at line 44 of file MatrixMapManipulator.java.
matrixEntries
String [] de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.matrixEntries = null private
Definition at line 49 of file MatrixMapManipulator.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.checkAndSaveMatrixMap(), and de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.deleteMatrixFromMatrixMap().
matrixMapButtonPanel
JPanel de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.matrixMapButtonPanel = null private
Definition at line 43 of file MatrixMapManipulator.java.
matrixMapEntriesScrollPane
JScrollPane de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.matrixMapEntriesScrollPane = null private
Definition at line 42 of file MatrixMapManipulator.java.
matrixMapList
JList<String> de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.matrixMapList private
Definition at line 41 of file MatrixMapManipulator.java.
matrixScrollPane
JScrollPane de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.matrixScrollPane = null private
Definition at line 39 of file MatrixMapManipulator.java.
saveButton
JButton de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.saveButton = null private
Definition at line 51 of file MatrixMapManipulator.java.
serialVersionUID
final long de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.serialVersionUID = -6979246790481072698L static private
Automatic serialVErsionID for serialisation
Definition at line 30 of file MatrixMapManipulator.java.
statement
Statement de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.statement = null private
Definition at line 31 of file MatrixMapManipulator.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.checkAndSaveMatrixMap(), and de.dlr.ivf.tapas.tools.matrixMap.MatrixMapManipulator.showDialog().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/matrixMap/MatrixMapManipulator.java