TAPAS: de.dlr.ivf.tapas.constants.TPS_SettlementSystem Class Reference
de.dlr.ivf.tapas.constants.TPS_SettlementSystem Class Reference
Classes
enum TPS_SettlementSystemType
Public Member Functions
TPS_SettlementSystem (int id, String[] attributes)
void addSettlementSystemToMap ()
int getCode (TPS_SettlementSystemType type)
int getId ()
Static Public Member Functions
static void clearSettlementSystemMap ()
static TPS_SettlementSystem getSettlementSystem (TPS_SettlementSystemType type, int code)
Private Attributes
final EnumMap< TPS_SettlementSystemType, TPS_InternalConstant< TPS_SettlementSystemType > > map
final int id
Static Private Attributes
static final HashMap< Integer, TPS_SettlementSystem > SETTLEMENT_SYSTEMS_MAP = new HashMap<>()
Detailed Description
Settlement system constants.
Definition at line 18 of file TPS_SettlementSystem.java.
Constructor & Destructor Documentation
TPS_SettlementSystem()
de.dlr.ivf.tapas.constants.TPS_SettlementSystem.TPS_SettlementSystem (int id, String[] attributes)
Basic constructor for a TPS_SettlementSystem
Parameters
id corresponding id from the db
attributes attributes have to have a length of 3*n where each 3-segment is of the form (name, code, type) like ("R1, K1, Kernstadt > 500000", "1", "FORDCP")
Definition at line 42 of file TPS_SettlementSystem.java.
References de.dlr.ivf.tapas.constants.TPS_SettlementSystem.id, and type.
Member Function Documentation
addSettlementSystemToMap()
void de.dlr.ivf.tapas.constants.TPS_SettlementSystem.addSettlementSystemToMap ()
Add to static collection of all settlement system constants. The objects are accessed by their ids from the db.
Definition at line 90 of file TPS_SettlementSystem.java.
References de.dlr.ivf.tapas.constants.TPS_SettlementSystem.SETTLEMENT_SYSTEMS_MAP.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readSettlementSystemCodes().
clearSettlementSystemMap()
static void de.dlr.ivf.tapas.constants.TPS_SettlementSystem.clearSettlementSystemMap () static
Empties settlement system map
Definition at line 68 of file TPS_SettlementSystem.java.
References de.dlr.ivf.tapas.constants.TPS_SettlementSystem.SETTLEMENT_SYSTEMS_MAP.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.clearConstants().
getCode()
int de.dlr.ivf.tapas.constants.TPS_SettlementSystem.getCode (TPS_SettlementSystemType type)
Convenience method to obtain the settlement system code for a given TPS_SettlementSystemType
Parameters
type like FORDCP or TAPAS, see TPS_SettlementSystemType
Returns
the corresponding code as int
Definition at line 100 of file TPS_SettlementSystem.java.
References type.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.batchStoreTrips(), de.dlr.ivf.tapas.loc.TPS_CFN.getCFN4Value(), de.dlr.ivf.tapas.loc.TPS_CFN.getCFNXValue(), de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixedBS.getDistributionSet(), de.dlr.ivf.tapas.loc.TPS_CFN.getParamValue(), de.dlr.ivf.tapas.mode.TPS_MassTransportMode.getTravelTime(), de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.getTripFromResult(), de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes(), and de.dlr.ivf.tapas.plan.TPS_Plan.TPS_Plan().
getId()
int de.dlr.ivf.tapas.constants.TPS_SettlementSystem.getId ()
Returns
the id corresponding to a settlement system object from the db
Definition at line 107 of file TPS_SettlementSystem.java.
References de.dlr.ivf.tapas.constants.TPS_SettlementSystem.id.
Referenced by de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.toString().
getSettlementSystem()
static TPS_SettlementSystem de.dlr.ivf.tapas.constants.TPS_SettlementSystem.getSettlementSystem (TPS_SettlementSystemType type, int code) static
Parameters
type like FORDCP or TAPAS, see TPS_SettlementSystemType
code settlement system code from the db
Returns
settlement system object for a given TPS_SettlementSystemType and code
Definition at line 77 of file TPS_SettlementSystem.java.
References code, de.dlr.ivf.tapas.constants.TPS_SettlementSystem.SETTLEMENT_SYSTEMS_MAP, and type.
Referenced by de.dlr.ivf.tapas.loc.TPS_CFN.addToCFN4Map(), de.dlr.ivf.tapas.loc.TPS_CFN.addToCFNXMap(), de.dlr.ivf.tapas.loc.TPS_CFN.getCFN4Value(), de.dlr.ivf.tapas.loc.TPS_CFN.getCFNXValue(), de.dlr.ivf.tapas.loc.TPS_CFN.getParamValue(), and de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.getTripFromResult().
Member Data Documentation
id
final int de.dlr.ivf.tapas.constants.TPS_SettlementSystem.id private
settlement system id obtained from the db
Definition at line 33 of file TPS_SettlementSystem.java.
Referenced by de.dlr.ivf.tapas.constants.TPS_SettlementSystem.getId(), and de.dlr.ivf.tapas.constants.TPS_SettlementSystem.TPS_SettlementSystem().
map
final EnumMap<TPS_SettlementSystemType, TPS_InternalConstant<TPS_SettlementSystemType> > de.dlr.ivf.tapas.constants.TPS_SettlementSystem.map private
mapping of the TPS_SettlementSystemType to the internal representation
Definition at line 28 of file TPS_SettlementSystem.java.
SETTLEMENT_SYSTEMS_MAP
final HashMap<Integer, TPS_SettlementSystem> de.dlr.ivf.tapas.constants.TPS_SettlementSystem.SETTLEMENT_SYSTEMS_MAP = new HashMap<>() static private
maps ids from the db to TPS_SettlementSystem objects constructed from corresponding db data
Definition at line 23 of file TPS_SettlementSystem.java.
Referenced by de.dlr.ivf.tapas.constants.TPS_SettlementSystem.addSettlementSystemToMap(), de.dlr.ivf.tapas.constants.TPS_SettlementSystem.clearSettlementSystemMap(), and de.dlr.ivf.tapas.constants.TPS_SettlementSystem.getSettlementSystem().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/constants/TPS_SettlementSystem.java