TAPAS: de.dlr.ivf.tapas.mode.TPS_ModeSet Class Reference
de.dlr.ivf.tapas.mode.TPS_ModeSet Class Reference
Public Member Functions
TPS_ModeSet (TPS_ModeChoiceTree modeChoiceTree, TPS_ExpertKnowledgeTree expertKnowledgeTree, TPS_ParameterClass parameterClass)
TPS_ExpertKnowledgeTree getExpertKnowledgeTree ()
TPS_ModeChoiceTree getModeChoiceTree ()
void setModeChoiceTree (TPS_ModeChoiceTree modeChoiceTree)
TPS_DiscreteDistribution< TPS_Mode > getModeDistribution (TPS_Plan plan, double distanceNet, TPS_ModeChoiceContext mcc)
TPS_ParameterClass getParameters ()
void selectMode (TPS_Plan plan, TPS_Stay prevStay, TPS_LocatedStay locatedStay, TPS_Stay nextStay, TPS_PlanningContext pc)
String toString ()
String toString (String prefix)
Private Member Functions
TPS_ExtMode selectMode0 (TPS_Plan plan, double distanceNet, TPS_ModeChoiceContext mcc)
Private Attributes
TPS_ModeChoiceTree modeChoiceTree
final TPS_ExpertKnowledgeTree expertKnowledgeTree
final TPS_ParameterClass parameterClass
Detailed Description
Class for the organisation of the modes available for choice as well as the choice of a mode considering the existing alternatives
Author
mark_ma
Definition at line 42 of file TPS_ModeSet.java.
Constructor & Destructor Documentation
TPS_ModeSet()
de.dlr.ivf.tapas.mode.TPS_ModeSet.TPS_ModeSet (TPS_ModeChoiceTree modeChoiceTree, TPS_ExpertKnowledgeTree expertKnowledgeTree, TPS_ParameterClass parameterClass)
Standard constructor for a mode set
Parameters
modeChoiceTree The choice tree for pivot point models
expertKnowledgeTree
parameterClass parameter class reference
Definition at line 64 of file TPS_ModeSet.java.
References de.dlr.ivf.tapas.mode.TPS_ModeSet.expertKnowledgeTree, de.dlr.ivf.tapas.mode.TPS_ModeSet.modeChoiceTree, and de.dlr.ivf.tapas.mode.TPS_ModeSet.parameterClass.
Member Function Documentation
getExpertKnowledgeTree()
TPS_ExpertKnowledgeTree de.dlr.ivf.tapas.mode.TPS_ModeSet.getExpertKnowledgeTree ()
returns the initial expert knowledge tree
Returns
mode choice tree
Definition at line 76 of file TPS_ModeSet.java.
References de.dlr.ivf.tapas.mode.TPS_ModeSet.expertKnowledgeTree.
Referenced by de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree.applyExpertKnowledge().
getModeChoiceTree()
TPS_ModeChoiceTree de.dlr.ivf.tapas.mode.TPS_ModeSet.getModeChoiceTree ()
returns the initial mode choice tree
Returns
mode choice tree
Definition at line 85 of file TPS_ModeSet.java.
References de.dlr.ivf.tapas.mode.TPS_ModeSet.modeChoiceTree.
Referenced by de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixed.getDistributionSet(), and de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixedBS.getDistributionSet().
getModeDistribution()
TPS_DiscreteDistribution<TPS_Mode> de.dlr.ivf.tapas.mode.TPS_ModeSet.getModeDistribution (TPS_Plan plan, double distanceNet, TPS_ModeChoiceContext mcc)
Calculates the mode distribution
Parameters
plan day plan
distanceNet distance between the locations
mcc
Returns
mode chosen mode TPS_ModeSet
Definition at line 106 of file TPS_ModeSet.java.
References de.dlr.ivf.tapas.mode.TPS_ModeDistribution.calculateDistribution(), de.dlr.ivf.tapas.util.TPS_AttributeReader.TPS_Attribute.CURRENT_DISTANCE_CLASS_CODE_MCT, de.dlr.ivf.tapas.util.TPS_AttributeReader.TPS_Attribute.CURRENT_EPISODE_ACTIVITY_CODE_MCT, de.dlr.ivf.tapas.util.TPS_AttributeReader.TPS_Attribute.CURRENT_EPISODE_ACTIVITY_CODE_TAPAS, de.dlr.ivf.tapas.util.TPS_AttributeReader.TPS_Attribute.CURRENT_EPISODE_ACTIVITY_CODE_VOT, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_RUN_SZENARIO, de.dlr.ivf.tapas.scheme.TPS_Episode.getActCode(), de.dlr.ivf.tapas.constants.TPS_ActivityConstant.getCode(), de.dlr.ivf.tapas.constants.TPS_Distance.getCode(), de.dlr.ivf.tapas.modechoice.TPS_UtilityFunction.getDistributionSet(), de.dlr.ivf.tapas.mode.TPS_Mode.getUtilityFunction(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isTrue(), de.dlr.ivf.tapas.constants.TPS_ActivityConstant.TPS_ActivityCodeType.MCT, de.dlr.ivf.tapas.constants.TPS_Distance.TPS_DistanceCodeType.MCT, de.dlr.ivf.tapas.plan.TPS_Plan.removeAttribute(), de.dlr.ivf.tapas.plan.TPS_Plan.setAttributeValue(), de.dlr.ivf.tapas.constants.TPS_ActivityConstant.TPS_ActivityCodeType.TAPAS, and de.dlr.ivf.tapas.constants.TPS_ActivityConstant.TPS_ActivityCodeType.VOT.
Referenced by de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessMode.getTravelTime(), de.dlr.ivf.tapas.loc.TPS_SelectWithSingleAccessMode.getTravelTime(), and de.dlr.ivf.tapas.mode.TPS_ModeSet.selectMode0().
getParameters()
TPS_ParameterClass de.dlr.ivf.tapas.mode.TPS_ModeSet.getParameters ()
Returns the parameter class reference
Returns
parameter class reference
Definition at line 141 of file TPS_ModeSet.java.
References de.dlr.ivf.tapas.mode.TPS_ModeSet.parameterClass.
Referenced by de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree.applyExpertKnowledge(), and de.dlr.ivf.tapas.mode.TPS_ModeSet.selectMode0().
selectMode()
void de.dlr.ivf.tapas.mode.TPS_ModeSet.selectMode (TPS_Plan plan, TPS_Stay prevStay, TPS_LocatedStay locatedStay, TPS_Stay nextStay, TPS_PlanningContext pc)
Sets the departure and arrival modes for a stay
Parameters
plan day plan
prevStay
locatedStay the stay the modes should be selected for
nextStay
pc
Definition at line 154 of file TPS_ModeSet.java.
References de.dlr.ivf.tapas.mode.TPS_ModeChoiceContext.carForThisPlan, de.dlr.ivf.tapas.plan.TPS_PlanningContext.carForThisPlan, de.dlr.ivf.tapas.mode.TPS_ModeChoiceContext.duration, de.dlr.ivf.tapas.log.TPS_LoggingInterface.HierarchyLogLevel.EPISODE, de.dlr.ivf.tapas.mode.TPS_ModeChoiceContext.fromStayLocation, de.dlr.ivf.tapas.mode.TPS_Mode.get(), de.dlr.ivf.tapas.scheme.TPS_TourPart.getCar(), de.dlr.ivf.tapas.mode.TPS_Mode.getDistance(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getDoubleValue(), de.dlr.ivf.tapas.plan.TPS_Plan.getLocatedStay(), de.dlr.ivf.tapas.plan.TPS_LocatedStay.getLocation(), de.dlr.ivf.tapas.plan.TPS_LocatedStay.getModeArr(), de.dlr.ivf.tapas.plan.TPS_LocatedStay.getModeDep(), de.dlr.ivf.tapas.scheme.TPS_Episode.getOriginalDuration(), de.dlr.ivf.tapas.scheme.TPS_Episode.getOriginalStart(), de.dlr.ivf.tapas.scheme.TPS_Episode.getSchemePart(), de.dlr.ivf.tapas.plan.TPS_LocatedStay.getStay(), de.dlr.ivf.tapas.mode.TPS_ModeChoiceContext.isBikeAvailable, de.dlr.ivf.tapas.plan.TPS_PlanningContext.isBikeAvailable, de.dlr.ivf.tapas.scheme.TPS_TourPart.isBikeUsed(), de.dlr.ivf.tapas.mode.TPS_ExtMode.isFix(), de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.util.parameters.ParamValue.MIN_DIST, de.dlr.ivf.tapas.util.parameters.SimulationType.SCENARIO, de.dlr.ivf.tapas.mode.TPS_ModeSet.selectMode0(), de.dlr.ivf.tapas.plan.TPS_LocatedStay.setModeArr(), de.dlr.ivf.tapas.plan.TPS_LocatedStay.setModeDep(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.SEVERE, de.dlr.ivf.tapas.mode.TPS_ModeChoiceContext.startTime, and de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.WALK.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes().
selectMode0()
TPS_ExtMode de.dlr.ivf.tapas.mode.TPS_ModeSet.selectMode0 (TPS_Plan plan, double distanceNet, TPS_ModeChoiceContext mcc) private
Method to determine a preliminary mode, just as if this stay would be the first stay to choose a mode
Parameters
plan The plan, which is processed
locatedStay the actual Stay
beelineDistanceLocArr the beeline from the last location (block level)
beelineDistanceLocDep the beeline to the next location (block level)
beelineDistanceTAZArr the beeline from the last location (taz level)
beelineDistanceTAZDep the beeline to the next location (taz level)
car a car which could be used or null
bikeIsAvailable flag for bike availability Selects a mode, default being public transport
plan day plan
distanceNet distance between the locations
mcc
Returns
mode chosen mode TPS_ModeSet
Definition at line 306 of file TPS_ModeSet.java.
References de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.BIKE, de.dlr.ivf.tapas.mode.TPS_ModeChoiceContext.carForThisPlan, de.dlr.ivf.tapas.mode.TPS_ModeChoiceContext.combinedMode, de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.drawKey(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.HierarchyLogLevel.EPISODE, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_USE_EXIT_MAUT, de.dlr.ivf.tapas.mode.TPS_ModeChoiceContext.fromStayLocation, de.dlr.ivf.tapas.mode.TPS_Mode.get(), de.dlr.ivf.tapas.mode.TPS_ModeSet.getModeDistribution(), de.dlr.ivf.tapas.mode.TPS_ModeSet.getParameters(), de.dlr.ivf.tapas.loc.TPS_Location.getTrafficAnalysisZone(), de.dlr.ivf.tapas.person.TPS_Car.hasPaidToll, de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.hasToll(), de.dlr.ivf.tapas.mode.TPS_ModeChoiceContext.isBikeAvailable, de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), de.dlr.ivf.tapas.mode.TPS_Mode.isType(), de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.MIT, de.dlr.ivf.tapas.plan.TPS_Plan.mustPayToll, de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.PT, de.dlr.ivf.tapas.util.parameters.SimulationType.SCENARIO, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.SEVERE, de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.size(), and de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.WALK.
Referenced by de.dlr.ivf.tapas.mode.TPS_ModeSet.selectMode().
setModeChoiceTree()
void de.dlr.ivf.tapas.mode.TPS_ModeSet.setModeChoiceTree (TPS_ModeChoiceTree modeChoiceTree)
Sets the initial mode choice tree.
Parameters
modeChoiceTree
Definition at line 94 of file TPS_ModeSet.java.
References de.dlr.ivf.tapas.mode.TPS_ModeSet.modeChoiceTree.
toString() [1/2]
String de.dlr.ivf.tapas.mode.TPS_ModeSet.toString ()
Definition at line 396 of file TPS_ModeSet.java.
toString() [2/2]
String de.dlr.ivf.tapas.mode.TPS_ModeSet.toString (String prefix)
This method should print the object naturally with the given prefix.
Parameters
prefix
Returns
prefix + toString();
Implements de.dlr.ivf.tapas.util.ExtendedWritable.
Definition at line 405 of file TPS_ModeSet.java.
References de.dlr.ivf.tapas.mode.TPS_Mode.getConstants(), and de.dlr.ivf.tapas.modechoice.TPS_ModeChoiceTree.toString().
Member Data Documentation
expertKnowledgeTree
final TPS_ExpertKnowledgeTree de.dlr.ivf.tapas.mode.TPS_ModeSet.expertKnowledgeTree private
Mode Choice Tree for this mode set
Definition at line 53 of file TPS_ModeSet.java.
Referenced by de.dlr.ivf.tapas.mode.TPS_ModeSet.getExpertKnowledgeTree(), and de.dlr.ivf.tapas.mode.TPS_ModeSet.TPS_ModeSet().
modeChoiceTree
TPS_ModeChoiceTree de.dlr.ivf.tapas.mode.TPS_ModeSet.modeChoiceTree private
Mode Choice Tree for this mode set
Definition at line 48 of file TPS_ModeSet.java.
Referenced by de.dlr.ivf.tapas.mode.TPS_ModeSet.getModeChoiceTree(), de.dlr.ivf.tapas.mode.TPS_ModeSet.setModeChoiceTree(), and de.dlr.ivf.tapas.mode.TPS_ModeSet.TPS_ModeSet().
parameterClass
final TPS_ParameterClass de.dlr.ivf.tapas.mode.TPS_ModeSet.parameterClass private
Definition at line 55 of file TPS_ModeSet.java.
Referenced by de.dlr.ivf.tapas.mode.TPS_ModeSet.getParameters(), and de.dlr.ivf.tapas.mode.TPS_ModeSet.TPS_ModeSet().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/mode/TPS_ModeSet.java