TAPAS: de.dlr.ivf.tapas.scheme.TPS_SchemePart Class Reference
de.dlr.ivf.tapas.scheme.TPS_SchemePart Class Reference abstract
Classes
class StayIterator
Public Member Functions
TPS_SchemePart (int id)
boolean addStay (TPS_Stay stay, TPS_ParameterClass parameterClass)
TPS_Episode getFirstEpisode ()
int getId ()
TPS_Episode getLastEpisode ()
TPS_Episode getNextEpisode (TPS_Episode episode)
TPS_Episode getNextEpisodeFromThisPart (TPS_Episode episode)
TPS_Stay getNextStay (TPS_Episode episode)
double getOriginalSchemePartEnd ()
double getOriginalSchemePartStart ()
TPS_Episode getPreviousEpisode (TPS_Episode episode)
TPS_Episode getPreviousEpisodeFromThisPart (TPS_Episode episode)
TPS_Stay getPreviousStay (TPS_Episode episode)
TPS_Scheme getScheme ()
Iterable< TPS_Stay > getStayIterator ()
boolean isFirst (TPS_Episode episode)
abstract boolean isHomePart ()
boolean isLast (TPS_Episode episode)
abstract boolean isTourPart ()
Iterator< TPS_Episode > iterator ()
int size ()
String toString ()
abstract String toString (String prefix)
Protected Member Functions
boolean addEpisode (TPS_Episode episode)
Protected Attributes
List< TPS_Episode > episodes
double originalSchemePartStart = 24 * 60 * 60
double originalSchemePartEnd = 0.0
Private Attributes
final int id
TPS_Scheme scheme
Detailed Description
This class implements the basic aspects of a scheme part. It provides a list of all episodes in the part.
Author
mark_ma
Definition at line 26 of file TPS_SchemePart.java.
Constructor & Destructor Documentation
TPS_SchemePart()
de.dlr.ivf.tapas.scheme.TPS_SchemePart.TPS_SchemePart (int id)
Sets the id and builds the list for the episodes.
Parameters
id
Definition at line 56 of file TPS_SchemePart.java.
Member Function Documentation
addEpisode()
boolean de.dlr.ivf.tapas.scheme.TPS_SchemePart.addEpisode (TPS_Episode episode) protected
This method adds an episode to the list and sets its reference to a scheme part to this.
Parameters
episode
Returns
true if added, false otherwise
Definition at line 67 of file TPS_SchemePart.java.
References de.dlr.ivf.tapas.scheme.TPS_Episode.getOriginalEnd(), and de.dlr.ivf.tapas.scheme.TPS_Episode.getOriginalStart().
addStay()
boolean de.dlr.ivf.tapas.scheme.TPS_SchemePart.addStay (TPS_Stay stay, TPS_ParameterClass parameterClass)
This method adds a stay to the list and sets its reference to a scheme part to this.
Parameters
stay
parameterClass reference - which is not used in here, only in the subclass
Returns
true if added, false otherwise
Reimplemented in de.dlr.ivf.tapas.scheme.TPS_TourPart.
Definition at line 81 of file TPS_SchemePart.java.
Referenced by de.dlr.ivf.tapas.scheme.TPS_Scheme.addEpisode().
getFirstEpisode()
TPS_Episode de.dlr.ivf.tapas.scheme.TPS_SchemePart.getFirstEpisode ()
Returns the first episode of the scheme part
Returns
first episode
Definition at line 90 of file TPS_SchemePart.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Worker.assignCarToPlan(), de.dlr.ivf.tapas.scheme.TPS_SchemePart.getNextEpisode(), and de.dlr.ivf.tapas.scheme.TPS_SchemePart.getNextStay().
getId()
int de.dlr.ivf.tapas.scheme.TPS_SchemePart.getId ()
Returns the id of the scheme part
Returns
id
Definition at line 99 of file TPS_SchemePart.java.
Referenced by de.dlr.ivf.tapas.scheme.TPS_Scheme.addEpisode(), and de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes().
getLastEpisode()
TPS_Episode de.dlr.ivf.tapas.scheme.TPS_SchemePart.getLastEpisode ()
Returns the last episode of the scheme part
Returns
last episode
Definition at line 108 of file TPS_SchemePart.java.
Referenced by de.dlr.ivf.tapas.scheme.TPS_Scheme.addEpisode(), de.dlr.ivf.tapas.person.TPS_Worker.assignCarToPlan(), de.dlr.ivf.tapas.scheme.TPS_SchemePart.getPreviousEpisode(), and de.dlr.ivf.tapas.scheme.TPS_SchemePart.getPreviousStay().
getNextEpisode()
TPS_Episode de.dlr.ivf.tapas.scheme.TPS_SchemePart.getNextEpisode (TPS_Episode episode)
This method returns the next episode to this episode. If there is no next episode, the first episode of the next scheme part in the scheme is returned. If there is no next episode at all the return value is null;
Parameters
episode
Returns
next episode in this or the next scheme part or null
Definition at line 119 of file TPS_SchemePart.java.
References de.dlr.ivf.tapas.scheme.TPS_SchemePart.getFirstEpisode().
getNextEpisodeFromThisPart()
TPS_Episode de.dlr.ivf.tapas.scheme.TPS_SchemePart.getNextEpisodeFromThisPart (TPS_Episode episode)
This method returns the next episode to this episode. If there is no next episode, the return value is null;
Parameters
episode
Returns
next episode in this part or null
Definition at line 137 of file TPS_SchemePart.java.
getNextStay()
TPS_Stay de.dlr.ivf.tapas.scheme.TPS_SchemePart.getNextStay (TPS_Episode episode)
This method returns the next stay to this episode. If there is no further stay, the first stay of the next scheme part in the scheme is returned.
Parameters
episode
Returns
next stay in this or the next scheme part
Definition at line 152 of file TPS_SchemePart.java.
References de.dlr.ivf.tapas.scheme.TPS_SchemePart.getFirstEpisode(), de.dlr.ivf.tapas.scheme.TPS_SchemePart.getNextStay(), and de.dlr.ivf.tapas.scheme.TPS_Episode.isStay().
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.createOutput(), de.dlr.ivf.tapas.scheme.TPS_SchemePart.getNextStay(), and de.dlr.ivf.tapas.plan.TPS_Plan.writeOutputStream().
getOriginalSchemePartEnd()
double de.dlr.ivf.tapas.scheme.TPS_SchemePart.getOriginalSchemePartEnd ()
Returns
the originalSchemePartEnd
Definition at line 175 of file TPS_SchemePart.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Car.selectCar().
getOriginalSchemePartStart()
double de.dlr.ivf.tapas.scheme.TPS_SchemePart.getOriginalSchemePartStart ()
Returns
the originalSchemePartStart
Definition at line 182 of file TPS_SchemePart.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Car.selectCar().
getPreviousEpisode()
TPS_Episode de.dlr.ivf.tapas.scheme.TPS_SchemePart.getPreviousEpisode (TPS_Episode episode)
This method returns the previous episode to this episode. If there is no previous episode, the last episode of the previous scheme part in the scheme is returned. If there is no previous episode at all the return value is null;
Parameters
episode
Returns
previous episode in this or the previous scheme part or null
Definition at line 193 of file TPS_SchemePart.java.
References de.dlr.ivf.tapas.scheme.TPS_SchemePart.getLastEpisode().
getPreviousEpisodeFromThisPart()
TPS_Episode de.dlr.ivf.tapas.scheme.TPS_SchemePart.getPreviousEpisodeFromThisPart (TPS_Episode episode)
This method returns the previous episode to this episode. If there is no previous episode, the return value is null;
Parameters
episode
Returns
previous episode in this or null
Definition at line 212 of file TPS_SchemePart.java.
getPreviousStay()
TPS_Stay de.dlr.ivf.tapas.scheme.TPS_SchemePart.getPreviousStay (TPS_Episode episode)
This method returns the previous stay to this episode. If there is no previous stay, the last stay of the previous scheme part in the scheme is returned.
Parameters
episode
Returns
previous stay in this or the previous scheme part
Definition at line 227 of file TPS_SchemePart.java.
References de.dlr.ivf.tapas.scheme.TPS_SchemePart.getLastEpisode(), de.dlr.ivf.tapas.scheme.TPS_SchemePart.getPreviousStay(), and de.dlr.ivf.tapas.scheme.TPS_Episode.isStay().
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.createOutput(), de.dlr.ivf.tapas.plan.TPS_Plan.getPreviousLocatedStay(), de.dlr.ivf.tapas.scheme.TPS_SchemePart.getPreviousStay(), and de.dlr.ivf.tapas.plan.TPS_Plan.writeOutputStream().
getScheme()
TPS_Scheme de.dlr.ivf.tapas.scheme.TPS_SchemePart.getScheme ()
Returns a reference to the scheme to scheme part belongs to
Returns
reference to the scheme
Definition at line 252 of file TPS_SchemePart.java.
Referenced by de.dlr.ivf.tapas.scheme.TPS_Scheme.addEpisode(), and de.dlr.ivf.tapas.person.TPS_Worker.processHousehold().
getStayIterator()
Iterable<TPS_Stay> de.dlr.ivf.tapas.scheme.TPS_SchemePart.getStayIterator ()
This method returns an iterator over all stays of this scheme part
Returns
an instance of StayIterator
Definition at line 270 of file TPS_SchemePart.java.
isFirst()
boolean de.dlr.ivf.tapas.scheme.TPS_SchemePart.isFirst (TPS_Episode episode)
Checks whether the given episode is the first episode of the scheme part
Parameters
episode
Returns
true if the given episode is the first one, false otherwise
Definition at line 280 of file TPS_SchemePart.java.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes().
isHomePart()
abstract boolean de.dlr.ivf.tapas.scheme.TPS_SchemePart.isHomePart () abstract
Flag indicating whether this scheme part is a home part, i.e. all stays are at home and the scheme part does not contain a trip.
Returns
true if the scheme part is a home part
Reimplemented in de.dlr.ivf.tapas.scheme.TPS_TourPart, and de.dlr.ivf.tapas.scheme.TPS_HomePart.
Referenced by de.dlr.ivf.tapas.scheme.TPS_Scheme.addEpisode().
isLast()
boolean de.dlr.ivf.tapas.scheme.TPS_SchemePart.isLast (TPS_Episode episode)
Checks whether the episode given is the last episode of the scheme part
Parameters
episode
Returns
true if the given episode is the last one, false otherwise
Definition at line 298 of file TPS_SchemePart.java.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes().
isTourPart()
abstract boolean de.dlr.ivf.tapas.scheme.TPS_SchemePart.isTourPart () abstract
Flag indicating whether the scheme part is a tour part, i.e. the scheme part contains trips, in detail it has to start and end with a trip. Every change of a location in the stays in the scheme part is separated by a further trip.
Returns
true if the scheme part is a tour part, false otherwise
Reimplemented in de.dlr.ivf.tapas.scheme.TPS_TourPart, and de.dlr.ivf.tapas.scheme.TPS_HomePart.
Referenced by de.dlr.ivf.tapas.scheme.TPS_Scheme.addEpisode(), and de.dlr.ivf.tapas.scheme.TPS_Scheme.TourPartIterator.next().
iterator()
Iterator<TPS_Episode> de.dlr.ivf.tapas.scheme.TPS_SchemePart.iterator ()
Definition at line 315 of file TPS_SchemePart.java.
size()
int de.dlr.ivf.tapas.scheme.TPS_SchemePart.size ()
Returns the number of all episodes in the scheme part
Returns
number of all episodes
Definition at line 324 of file TPS_SchemePart.java.
Referenced by de.dlr.ivf.tapas.scheme.TPS_Scheme.size().
toString() [1/2]
String de.dlr.ivf.tapas.scheme.TPS_SchemePart.toString ()
Definition at line 334 of file TPS_SchemePart.java.
Referenced by de.dlr.ivf.tapas.scheme.TPS_Scheme.toString().
toString() [2/2]
abstract String de.dlr.ivf.tapas.scheme.TPS_SchemePart.toString (String prefix) abstract
This method should print the object naturally with the given prefix.
Parameters
prefix
Returns
prefix + toString();
Implements de.dlr.ivf.tapas.util.ExtendedWritable.
Reimplemented in de.dlr.ivf.tapas.scheme.TPS_TourPart, and de.dlr.ivf.tapas.scheme.TPS_HomePart.
Member Data Documentation
episodes
List<TPS_Episode> de.dlr.ivf.tapas.scheme.TPS_SchemePart.episodes protected
Chronological list with all episodes of this scheme part
Definition at line 31 of file TPS_SchemePart.java.
id
final int de.dlr.ivf.tapas.scheme.TPS_SchemePart.id private
scheme part id
Definition at line 45 of file TPS_SchemePart.java.
originalSchemePartEnd
double de.dlr.ivf.tapas.scheme.TPS_SchemePart.originalSchemePartEnd = 0.0 protected
original end of the scheme part
Definition at line 41 of file TPS_SchemePart.java.
originalSchemePartStart
double de.dlr.ivf.tapas.scheme.TPS_SchemePart.originalSchemePartStart = 24 * 60 * 60 protected
original start of the scheme part
Definition at line 36 of file TPS_SchemePart.java.
scheme
TPS_Scheme de.dlr.ivf.tapas.scheme.TPS_SchemePart.scheme private
Reference to the scheme
Definition at line 49 of file TPS_SchemePart.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/scheme/TPS_SchemePart.java