TAPAS: de.dlr.ivf.tapas.tools.locationallocation.Locator Class Reference
de.dlr.ivf.tapas.tools.locationallocation.Locator Class Reference
Public Member Functions
Locator (TPS_DB_Connector con, boolean exactOnly)
boolean isInRegion (Location loc)
boolean localizeLocation (Location loc)
Private Member Functions
String checkPLZ (String input)
String extractHouseNumber (String houseNumber)
String extractHouseNumberAddOn (String houseNumber)
void generateQueriesForAdressToCoordinate (State bundesland, String streetValue, String houseNumber, String plz, String houseNumberAddOn, String additionalConstraints, String additionalColumns, String order, HashMap< Integer, String > queries, int startSqlIndex)
boolean isAddOddChar (char character)
boolean isIntNumeric (char character)
String stringBeautifier (String input)
void updateLocation (ResultSet rs, Location loc) throws SQLException
Private Attributes
final boolean exactOnly
Static Private Attributes
static final double searchRadius = 500
Detailed Description
Definition at line 18 of file Locator.java.
Constructor & Destructor Documentation
Locator()
de.dlr.ivf.tapas.tools.locationallocation.Locator.Locator (TPS_DB_Connector con, boolean exactOnly)
Parameters
con
exactOnly
Definition at line 28 of file Locator.java.
References de.dlr.ivf.tapas.tools.locationallocation.Locator.exactOnly.
Member Function Documentation
checkPLZ()
String de.dlr.ivf.tapas.tools.locationallocation.Locator.checkPLZ (String input) private
Checks for valid PLZ (5 digits) or list of plz (comma-seperated
Parameters
input the inputstring
Returns
the input if valid else null
Definition at line 39 of file Locator.java.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.Locator.localizeLocation().
extractHouseNumber()
String de.dlr.ivf.tapas.tools.locationallocation.Locator.extractHouseNumber (String houseNumber) private
Method to extract the housenumber from the gioven string
Parameters
houseNumber
Returns
the number only without "a" "/1" or whatever
Definition at line 78 of file Locator.java.
References de.dlr.ivf.tapas.tools.locationallocation.Locator.isIntNumeric().
Referenced by de.dlr.ivf.tapas.tools.locationallocation.Locator.localizeLocation().
extractHouseNumberAddOn()
String de.dlr.ivf.tapas.tools.locationallocation.Locator.extractHouseNumberAddOn (String houseNumber) private
Definition at line 91 of file Locator.java.
References de.dlr.ivf.tapas.tools.locationallocation.Locator.isAddOddChar().
Referenced by de.dlr.ivf.tapas.tools.locationallocation.Locator.localizeLocation().
generateQueriesForAdressToCoordinate()
void de.dlr.ivf.tapas.tools.locationallocation.Locator.generateQueriesForAdressToCoordinate (State bundesland, String streetValue, String houseNumber, String plz, String houseNumberAddOn, String additionalConstraints, String additionalColumns, String order, HashMap< Integer, String > queries, int startSqlIndex) private
Definition at line 113 of file Locator.java.
References de.dlr.ivf.tapas.tools.locationallocation.Constants.ENABLE_CHANGES_OF_MARCO, de.dlr.ivf.tapas.tools.locationallocation.State.getGemeindeSchluessel(), and de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.replaceStreetTag().
Referenced by de.dlr.ivf.tapas.tools.locationallocation.Locator.localizeLocation().
isAddOddChar()
boolean de.dlr.ivf.tapas.tools.locationallocation.Locator.isAddOddChar (char character) private
Method to check if a character is an numeric integer
Parameters
character the character to check
Returns
true if character is 0-9 or + or -
Definition at line 446 of file Locator.java.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.Locator.extractHouseNumberAddOn().
isInRegion()
boolean de.dlr.ivf.tapas.tools.locationallocation.Locator.isInRegion (Location loc)
Definition at line 497 of file Locator.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.getValue(), de.dlr.ivf.tapas.tools.locationallocation.Locator.searchRadius, and de.dlr.ivf.tapas.tools.locationallocation.Locator.stringBeautifier().
Referenced by de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.main().
isIntNumeric()
boolean de.dlr.ivf.tapas.tools.locationallocation.Locator.isIntNumeric (char character) private
Method to check if a character is an numeric integer
Parameters
character the character to check
Returns
true if character is 0-9 or + or -
Definition at line 528 of file Locator.java.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.Locator.extractHouseNumber().
localizeLocation()
boolean de.dlr.ivf.tapas.tools.locationallocation.Locator.localizeLocation (Location loc)
Definition at line 553 of file Locator.java.
References de.dlr.ivf.tapas.tools.locationallocation.Locator.checkPLZ(), de.dlr.ivf.tapas.tools.locationallocation.Constants.ENABLE_CHANGES_OF_MARCO, de.dlr.ivf.tapas.tools.locationallocation.Locator.exactOnly, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), de.dlr.ivf.tapas.tools.locationallocation.Locator.extractHouseNumber(), de.dlr.ivf.tapas.tools.locationallocation.Locator.extractHouseNumberAddOn(), de.dlr.ivf.tapas.tools.locationallocation.Locator.generateQueriesForAdressToCoordinate(), de.dlr.ivf.tapas.tools.locationallocation.State.getByName(), de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.getStatus(), de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.getValue(), de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.replaceStreetTag(), de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.setStatus(), de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.STATUS_DISTINCT_IN_DATABASE, de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.STATUS_NOT_DISTINCT_IN_DATABASE, de.dlr.ivf.tapas.tools.locationallocation.Locator.stringBeautifier(), de.dlr.ivf.tapas.tools.locationallocation.Locator.updateLocation(), and de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.updateOrAddValue().
Referenced by de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.main().
stringBeautifier()
String de.dlr.ivf.tapas.tools.locationallocation.Locator.stringBeautifier (String input) private
Definition at line 809 of file Locator.java.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.Locator.isInRegion(), and de.dlr.ivf.tapas.tools.locationallocation.Locator.localizeLocation().
updateLocation()
void de.dlr.ivf.tapas.tools.locationallocation.Locator.updateLocation (ResultSet rs, Location loc) throws SQLException private
Definition at line 820 of file Locator.java.
References de.dlr.ivf.tapas.tools.locationallocation.Constants.ENABLE_CHANGES_OF_MARCO, and de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.Location.STATUS_NOT_DISTINCT_IN_DATABASE.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.Locator.localizeLocation().
Member Data Documentation
exactOnly
final boolean de.dlr.ivf.tapas.tools.locationallocation.Locator.exactOnly private
Definition at line 22 of file Locator.java.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.Locator.localizeLocation(), and de.dlr.ivf.tapas.tools.locationallocation.Locator.Locator().
searchRadius
final double de.dlr.ivf.tapas.tools.locationallocation.Locator.searchRadius = 500 static private
Definition at line 20 of file Locator.java.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.Locator.isInRegion().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/locationallocation/Locator.java