TAPAS: de.dlr.ivf.tapas.runtime.util.ClientControlProperties Class Reference
de.dlr.ivf.tapas.runtime.util.ClientControlProperties Class Reference
Inherits de.dlr.ivf.tapas.runtime.util.ControlProperties.
Classes
enum ClientControlPropKey
Public Member Functions
ClientControlProperties (File file)
String get (ClientControlPropKey key)
void set (ClientControlPropKey key, String value)
Detailed Description
Definition at line 19 of file ClientControlProperties.java.
Constructor & Destructor Documentation
ClientControlProperties()
de.dlr.ivf.tapas.runtime.util.ClientControlProperties.ClientControlProperties (File file)
The constructor builds the properties object and fills it with the key value pairs from the file.
Parameters
file the client.properties file
Definition at line 25 of file ClientControlProperties.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, and de.dlr.ivf.tapas.log.TPS_Logger.log().
Member Function Documentation
get()
String de.dlr.ivf.tapas.runtime.util.ClientControlProperties.get (ClientControlPropKey key)
Parameters
key simulation property key
Returns
value corresponding to the given key
Definition at line 55 of file ClientControlProperties.java.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationControl.chooseRunFile(), de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.getRuntimeFile(), de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.main(), and de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.readClientProperties().
set()
void de.dlr.ivf.tapas.runtime.util.ClientControlProperties.set (ClientControlPropKey key, String value)
Sets a key value pair for this property.
Parameters
key simulation property key
value simulation property value
Definition at line 65 of file ClientControlProperties.java.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationControl.chooseRunFile(), de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.getRuntimeFile(), de.dlr.ivf.tapas.runtime.client.SimulationControl.main(), and de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.readClientProperties().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/runtime/util/ClientControlProperties.java