TAPAS: de.dlr.ivf.tapas.iteration.TPS_VisumConverter Class Reference
de.dlr.ivf.tapas.iteration.TPS_VisumConverter Class Reference
Public Member Functions
TPS_VisumConverter (TPS_ParameterClass parameterClass)
TPS_VisumConverter (TPS_ParameterClass parameterClass, String file, String simKey)
boolean checkIntraInfos (String name)
boolean checkMatrixName (String matrixName)
void deleteIntraInfos (String name)
void deleteMatrix (String matrixName)
void generateIntraCellInfos (double weight)
double[][] getAccessTime ()
void setAccessTime (double[][] accessTime)
double[][] getDistance ()
void setDistance (double[][] distance)
double[][] getEgressTime ()
void setEgressTime (double[][] egressTime)
int getIteration ()
void setIteration (int iteration)
double[][] getTravelTime ()
void setTravelTime (double[][] travelTime)
void mergeMatrices ()
void mergeMatrixPair (double[][] oldVals, double[][] newVals)
void readCSVFile (String fileName) throws IOException
void readIDMap () throws SQLException
double[][] readMatrixFromDB (String matrixName)
void setCompareMatrix (String[] compareMatrix)
void setPT (boolean isPT)
void setWeight (double weight)
boolean storeIntraInfos (String name)
void writeODMatrices (String outputPath) throws SQLException, IOException
Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_BasicConnectionClass ()
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass)
TPS_BasicConnectionClass (String loginFile)
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass, String loginFile)
TPS_ParameterClass getParameters ()
String readParameter (String simKey, String paramKey)
void storeInDB (String matrixName, double[][] matrix, int decimalPlaces)
Public Attributes
TPS_ParameterClass parameterClass
Private Member Functions
void calcMinMaxValue (double[] array)
int checkMultiMin (double val, double[] array)
void insertMinAt (double val, double[] array, int position)
void readMatrix (ParamString matrixName, ParamMatrixMap matrix, SimulationType simType, int sIndex)
void setValue (double[][] array, int x, int y, double val, boolean symmetric)
Private Attributes
double weight = 1
int iteration = 1
String[] compareMatrix = null
boolean isPT = false
double[] intraBeeLineFactor = null
double[] intraSpeed = null
double[][] travelTime = null
double[][] speed = null
double[][] accessTime = null
double[][] egressTime = null
double[][] distance = null
double[][] beeline = null
final HashMap< Integer, Integer > idToIndex = new HashMap<>()
final HashMap< Integer, Integer > indexToId = new HashMap<>()
Additional Inherited Members
Static Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
static double[][] array1Dto2D (Integer[] matrixVal)
static double[][] array1Dto2D (int[] matrixVal)
static File getRuntimeFile (boolean forceNewFile)
static File getRuntimeFile (String propertyFile, boolean forceNewFile)
static File getRuntimeFile ()
static File getRuntimeFile (String propertyFile)
static int[][] intArray1Dto2D (int[] matrixVal)
static String matrixToSQLArray (double[][] array, int decimalPlaces)
static StringWriter matrixToStringWriterSQL (double[][] array, int decimalPlaces)
Protected Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
void finalize ()
Protected Attributes inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_DB_Connector dbCon = null
TPS_ParameterClass parameterClass
Detailed Description
This class provides all the necessary tools to communicate with Visum. This includes converter routines, to load/store form the database to/from Visum Generating additional information.
Author
hein_mh
Definition at line 39 of file TPS_VisumConverter.java.
Constructor & Destructor Documentation
TPS_VisumConverter() [1/2]
de.dlr.ivf.tapas.iteration.TPS_VisumConverter.TPS_VisumConverter (TPS_ParameterClass parameterClass)
standard constructor
Definition at line 103 of file TPS_VisumConverter.java.
TPS_VisumConverter() [2/2]
de.dlr.ivf.tapas.iteration.TPS_VisumConverter.TPS_VisumConverter (TPS_ParameterClass parameterClass, String file, String simKey)
This constructor reads all parameters and tries to initialise all data which is available via the TPS_PersistenceManager . If any Exception is thrown it is logged and the application stops.
Parameters
file filename of the parameter file with all run information. This file leads to all other files with e.g. logging, database, etc. information.
simKey key of the simulation
Definition at line 115 of file TPS_VisumConverter.java.
References de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.checkParameters(), de.dlr.ivf.tapas.util.parameters.ParamString.CURRENCY, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_SIMULATION_PARAMETERS, de.dlr.ivf.tapas.util.parameters.CURRENCY.EUR, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.FATAL, de.dlr.ivf.tapas.util.parameters.ParamString.FILE_WORKING_DIRECTORY, de.dlr.ivf.tapas.TPS_Main.getDefaultSimKey(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.readParametersFromDBMaintainLoginInfo(), de.dlr.ivf.tapas.util.parameters.ParamString.RUN_IDENTIFIER, and de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.setString().
Member Function Documentation
calcMinMaxValue()
void de.dlr.ivf.tapas.iteration.TPS_VisumConverter.calcMinMaxValue (double[] array) private
Internal method to store the min/max-values
Parameters
array
Definition at line 152 of file TPS_VisumConverter.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, and de.dlr.ivf.tapas.log.TPS_Logger.log().
checkIntraInfos()
boolean de.dlr.ivf.tapas.iteration.TPS_VisumConverter.checkIntraInfos (String name)
Method to check if a given intro info name exists
Parameters
name the info name to look for
Returns
true if it exists
Definition at line 167 of file TPS_VisumConverter.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_TAZ_INTRA_MIT_INFOS, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_TAZ_INTRA_PT_INFOS, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.log.TPS_Logger.log(), and name.
Referenced by de.dlr.ivf.tapas.tools.TPS_VisumToDB.main().
checkMatrixName()
boolean de.dlr.ivf.tapas.iteration.TPS_VisumConverter.checkMatrixName (String matrixName)
This method checks if the given matrix already exists
Parameters
matrixName the name of the matrix
Returns
true if
Reimplemented from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.
Definition at line 194 of file TPS_VisumConverter.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_MATRICES, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), and de.dlr.ivf.tapas.log.TPS_Logger.log().
Referenced by de.dlr.ivf.tapas.tools.TPS_VisumToDB.interactiveStoreInDB().
checkMultiMin()
int de.dlr.ivf.tapas.iteration.TPS_VisumConverter.checkMultiMin (double val, double[] array) private
Internal Method to check for multiple mins.
Parameters
val the value to test
array an array, which holds the array.length minimum values
Returns
the position, where the value was inserted or -1 if "val" is bigger than every value in "array"
Definition at line 220 of file TPS_VisumConverter.java.
deleteIntraInfos()
void de.dlr.ivf.tapas.iteration.TPS_VisumConverter.deleteIntraInfos (String name)
This method deletes the intra info cells for the given name.
Parameters
name the name if the intra infos to delete
Definition at line 235 of file TPS_VisumConverter.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_TAZ_INTRA_MIT_INFOS, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_TAZ_INTRA_PT_INFOS, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), and name.
Referenced by de.dlr.ivf.tapas.tools.TPS_VisumToDB.main().
deleteMatrix()
void de.dlr.ivf.tapas.iteration.TPS_VisumConverter.deleteMatrix (String matrixName)
This method deletes the matrix from the db
Parameters
matrixName the matrix to delete
Definition at line 250 of file TPS_VisumConverter.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_MATRICES, and de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString().
Referenced by de.dlr.ivf.tapas.tools.TPS_VisumToDB.interactiveStoreInDB().
generateIntraCellInfos()
void de.dlr.ivf.tapas.iteration.TPS_VisumConverter.generateIntraCellInfos (double weight)
This method generates the intra-infos. Workflow:
Find n closest TVZs
Store traveltime, distance, beeline and speed
Calc top3-average for speed
Calc top3-average for ratio distance/beeline
Calv top3*weight average for traveltime and distance
Store intra-infos in the vector for speed and distance/beeline
Store traveltime and distance in diagonal of the according matrix
Definition at line 267 of file TPS_VisumConverter.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_VisumToDB.main().
getAccessTime()
double [][] de.dlr.ivf.tapas.iteration.TPS_VisumConverter.getAccessTime ()
Returns
the accessTime
Definition at line 343 of file TPS_VisumConverter.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_VisumToDB.main().
getDistance()
double [][] de.dlr.ivf.tapas.iteration.TPS_VisumConverter.getDistance ()
Returns
the distance
Definition at line 357 of file TPS_VisumConverter.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_VisumToDB.main().
getEgressTime()
double [][] de.dlr.ivf.tapas.iteration.TPS_VisumConverter.getEgressTime ()
Returns
the egressTime
Definition at line 371 of file TPS_VisumConverter.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_VisumToDB.main().
getIteration()
int de.dlr.ivf.tapas.iteration.TPS_VisumConverter.getIteration ()
Returns
the iteration
Definition at line 386 of file TPS_VisumConverter.java.
getTravelTime()
double [][] de.dlr.ivf.tapas.iteration.TPS_VisumConverter.getTravelTime ()
Returns
the travelTime
Definition at line 400 of file TPS_VisumConverter.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_VisumToDB.main().
insertMinAt()
void de.dlr.ivf.tapas.iteration.TPS_VisumConverter.insertMinAt (double val, double[] array, int position) private
Internal method to insert a value at a specific position in the array. All succedion values are shifted one to the left. In C I would use the shift command ;)
Parameters
val the new value
array the array to insert into
position the position
Definition at line 418 of file TPS_VisumConverter.java.
mergeMatrices()
void de.dlr.ivf.tapas.iteration.TPS_VisumConverter.mergeMatrices ()
Method to merge the matrices according to the weight
Definition at line 430 of file TPS_VisumConverter.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.INFO, de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), and de.dlr.ivf.tapas.log.TPS_Logger.log().
Referenced by de.dlr.ivf.tapas.tools.TPS_VisumToDB.main().
mergeMatrixPair()
void de.dlr.ivf.tapas.iteration.TPS_VisumConverter.mergeMatrixPair (double oldVals[][], double newVals[][])
This method merges the two matrices. The result is stored in "newVals". Every value of the matrix is updated by: val = (old_val+weight*new_val)/(1+weight)
Parameters
oldVals matrix containing the old values
newVals matrix containing the new values and return object
Definition at line 472 of file TPS_VisumConverter.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.INFO, de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), and de.dlr.ivf.tapas.log.TPS_Logger.log().
readCSVFile()
void de.dlr.ivf.tapas.iteration.TPS_VisumConverter.readCSVFile (String fileName) throws IOException
This Method reads the csv-file and stores the information in the according matrices. The file has the format:
IV: fromID;toID;travelTime;Speed;Distance;Beeline
PT: fromID;toID;accessTime;Beeline;egressTime;Distance;TravelTime
Parameters
fileName The csv-file.
Definition at line 513 of file TPS_VisumConverter.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.INFO, de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), and de.dlr.ivf.tapas.log.TPS_Logger.log().
Referenced by de.dlr.ivf.tapas.tools.TPS_VisumToDB.main().
readIDMap()
void de.dlr.ivf.tapas.iteration.TPS_VisumConverter.readIDMap () throws SQLException
Definition at line 692 of file TPS_VisumConverter.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_TAZ, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.INFO, de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), and de.dlr.ivf.tapas.log.TPS_Logger.log().
Referenced by de.dlr.ivf.tapas.tools.TPS_VisumToDB.main().
readMatrix()
void de.dlr.ivf.tapas.iteration.TPS_VisumConverter.readMatrix (ParamString matrixName, ParamMatrixMap matrix, SimulationType simType, int sIndex) private
Definition at line 719 of file TPS_VisumConverter.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_MATRICES, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_MATRIXMAPS, de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.extractDoubleArray(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.extractIntArray(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.extractStringArray(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.FATAL, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.paramMatrixMapClass, de.dlr.ivf.tapas.util.parameters.ParamMatrixMapClass.setMatrixMap(), and de.dlr.ivf.tapas.util.Matrix.setRawValue().
readMatrixFromDB()
double [][] de.dlr.ivf.tapas.iteration.TPS_VisumConverter.readMatrixFromDB (String matrixName)
This method reads the square matrix from the db and returns a 2D-Array
Parameters
matrixName The matrix name in the db
Returns
the 2D-double array of the square matrix
Definition at line 788 of file TPS_VisumConverter.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_MATRICES, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), and de.dlr.ivf.tapas.log.TPS_Logger.log().
setAccessTime()
void de.dlr.ivf.tapas.iteration.TPS_VisumConverter.setAccessTime (double accessTime[][])
Parameters
accessTime the accessTime to set
Definition at line 350 of file TPS_VisumConverter.java.
setCompareMatrix()
void de.dlr.ivf.tapas.iteration.TPS_VisumConverter.setCompareMatrix (String[] compareMatrix)
Sets the array of matrixnames for comparison. Order for IV: travelTime distance
Order for PT: travelTime distance accessTime egressTime
Parameters
compareMatrix The array of matrix names in the db.
Definition at line 839 of file TPS_VisumConverter.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_VisumToDB.main().
setDistance()
void de.dlr.ivf.tapas.iteration.TPS_VisumConverter.setDistance (double distance[][])
Parameters
distance the distance to set
Definition at line 364 of file TPS_VisumConverter.java.
setEgressTime()
void de.dlr.ivf.tapas.iteration.TPS_VisumConverter.setEgressTime (double egressTime[][])
Parameters
egressTime the egressTime to set
Definition at line 379 of file TPS_VisumConverter.java.
setIteration()
void de.dlr.ivf.tapas.iteration.TPS_VisumConverter.setIteration (int iteration)
Parameters
iteration the iteration to set
Definition at line 393 of file TPS_VisumConverter.java.
setPT()
void de.dlr.ivf.tapas.iteration.TPS_VisumConverter.setPT (boolean isPT)
Setter if the input is pt or iv
Parameters
isPT the flag
Definition at line 848 of file TPS_VisumConverter.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_VisumToDB.main().
setTravelTime()
void de.dlr.ivf.tapas.iteration.TPS_VisumConverter.setTravelTime (double travelTime[][])
Parameters
travelTime the travelTime to set
Definition at line 407 of file TPS_VisumConverter.java.
setValue()
void de.dlr.ivf.tapas.iteration.TPS_VisumConverter.setValue (double array[][], int x, int y, double val, boolean symmetric) private
Internal method to insert data in (symmetric) matrices
Parameters
array Reference to the array to store
x First coordinate
y Second coordinate
val The value to store
symmetric Is the Matrix symmetric? Yes: store array[y][x], too.
Definition at line 861 of file TPS_VisumConverter.java.
setWeight()
void de.dlr.ivf.tapas.iteration.TPS_VisumConverter.setWeight (double weight)
Sets the weight for merging with the old matrix. val = (old_val + weight*new_val)/(1+weight)
Parameters
weight the weight of the new values
Definition at line 872 of file TPS_VisumConverter.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_VisumToDB.main().
storeIntraInfos()
boolean de.dlr.ivf.tapas.iteration.TPS_VisumConverter.storeIntraInfos (String name)
this method stores the intra infos.
Parameters
name name for the entry.
Returns
true if successful
Definition at line 882 of file TPS_VisumConverter.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_TAZ_INTRA_MIT_INFOS, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_TAZ_INTRA_PT_INFOS, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.INFO, de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), de.dlr.ivf.tapas.log.TPS_Logger.log(), and name.
Referenced by de.dlr.ivf.tapas.tools.TPS_VisumToDB.main().
writeODMatrices()
void de.dlr.ivf.tapas.iteration.TPS_VisumConverter.writeODMatrices (String outputPath) throws SQLException, IOException
This method exports the trips to VISUM OD-Matrices
Parameters
outputPath the path to store the OD-matrix. usually Trip-Exports
Definition at line 928 of file TPS_VisumConverter.java.
References de.dlr.ivf.tapas.util.parameters.ParamValue.DB_HH_SAMPLE_SIZE, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_TT_MIT, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_SIMULATIONS, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_TRIPS, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.FATAL, de.dlr.ivf.tapas.util.parameters.ParamValueClass.getDoubleValue(), de.dlr.ivf.tapas.util.parameters.ParamMatrixMapClass.getMatrixMap(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.INFO, de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), de.dlr.ivf.tapas.util.parameters.ParamValue.ITERATION, de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.util.MatrixMap.matrices, de.dlr.ivf.tapas.mode.TPS_Mode.MODE_TYPE_ARRAY, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.paramMatrixMapClass, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.paramValueClass, de.dlr.ivf.tapas.util.parameters.ParamString.RUN_IDENTIFIER, de.dlr.ivf.tapas.util.parameters.SimulationType.SCENARIO, de.dlr.ivf.tapas.util.parameters.ParamMatrixMap.TRAVEL_TIME_MIT, and de.dlr.ivf.tapas.util.MatrixMap.MatrixTuple.value.
Member Data Documentation
accessTime
double [][] de.dlr.ivf.tapas.iteration.TPS_VisumConverter.accessTime = null private
array for the access time in seconds
Definition at line 78 of file TPS_VisumConverter.java.
beeline
double [][] de.dlr.ivf.tapas.iteration.TPS_VisumConverter.beeline = null private
array for the beeline distances in meter
Definition at line 90 of file TPS_VisumConverter.java.
compareMatrix
String [] de.dlr.ivf.tapas.iteration.TPS_VisumConverter.compareMatrix = null private
String array which holds the matrix names for comparison.
Definition at line 54 of file TPS_VisumConverter.java.
distance
double [][] de.dlr.ivf.tapas.iteration.TPS_VisumConverter.distance = null private
array for the net-distances in m
Definition at line 86 of file TPS_VisumConverter.java.
egressTime
double [][] de.dlr.ivf.tapas.iteration.TPS_VisumConverter.egressTime = null private
array for the egress time in seconds
Definition at line 82 of file TPS_VisumConverter.java.
idToIndex
final HashMap<Integer, Integer> de.dlr.ivf.tapas.iteration.TPS_VisumConverter.idToIndex = new HashMap<>() private
hashmap for id conversion
Definition at line 94 of file TPS_VisumConverter.java.
indexToId
final HashMap<Integer, Integer> de.dlr.ivf.tapas.iteration.TPS_VisumConverter.indexToId = new HashMap<>() private
hashmap for id conversion
Definition at line 98 of file TPS_VisumConverter.java.
intraBeeLineFactor
double [] de.dlr.ivf.tapas.iteration.TPS_VisumConverter.intraBeeLineFactor = null private
vector to store the intra taz-beeline factors
Definition at line 62 of file TPS_VisumConverter.java.
intraSpeed
double [] de.dlr.ivf.tapas.iteration.TPS_VisumConverter.intraSpeed = null private
vector to store the intra taz-speeds
Definition at line 66 of file TPS_VisumConverter.java.
isPT
boolean de.dlr.ivf.tapas.iteration.TPS_VisumConverter.isPT = false private
Parameter to determine, if the input is a pt matrix or iv matrix
Definition at line 58 of file TPS_VisumConverter.java.
iteration
int de.dlr.ivf.tapas.iteration.TPS_VisumConverter.iteration = 1 private
Identifier for the iteration cycle
Definition at line 49 of file TPS_VisumConverter.java.
parameterClass
TPS_ParameterClass de.dlr.ivf.tapas.iteration.TPS_VisumConverter.parameterClass
Definition at line 41 of file TPS_VisumConverter.java.
speed
double [][] de.dlr.ivf.tapas.iteration.TPS_VisumConverter.speed = null private
array for the speed in m/s
Definition at line 74 of file TPS_VisumConverter.java.
travelTime
double [][] de.dlr.ivf.tapas.iteration.TPS_VisumConverter.travelTime = null private
array for the traveltime in seconds
Definition at line 70 of file TPS_VisumConverter.java.
weight
double de.dlr.ivf.tapas.iteration.TPS_VisumConverter.weight = 1 private
Parameter for the weight, if two matrices should be merged.
Definition at line 45 of file TPS_VisumConverter.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/iteration/TPS_VisumConverter.java