TAPAS: de.dlr.ivf.tapas.runtime.client.SimulationControl.SimulationDataUpdateTask Class Reference
de.dlr.ivf.tapas.runtime.client.SimulationControl.SimulationDataUpdateTask Class Reference
Public Member Functions
SimulationDataUpdateTask ()
void run ()
Detailed Description
This task updates the SimulationData of all simulations from the database.
Author
mark_ma
Definition at line 824 of file SimulationControl.java.
Constructor & Destructor Documentation
SimulationDataUpdateTask()
de.dlr.ivf.tapas.runtime.client.SimulationControl.SimulationDataUpdateTask.SimulationDataUpdateTask ()
Definition at line 826 of file SimulationControl.java.
References de.dlr.ivf.tapas.runtime.client.SimulationControl.dbConnection, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection().
Member Function Documentation
run()
void de.dlr.ivf.tapas.runtime.client.SimulationControl.SimulationDataUpdateTask.run ()
Definition at line 841 of file SimulationControl.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.checkConnection(), de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_SIMULATIONS, de.dlr.ivf.tapas.runtime.client.SimulationControl.dbConnection, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), de.dlr.ivf.tapas.runtime.server.SimulationData.getKey(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getParameters(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.runtime.client.SimulationControl.gui, de.dlr.ivf.tapas.runtime.client.SimulationMonitor.removeSimulation(), de.dlr.ivf.tapas.runtime.client.SimulationControl.simulationDataMap, de.dlr.ivf.tapas.runtime.client.SimulationControl.skipUpdate, de.dlr.ivf.tapas.runtime.server.SimulationData.update(), and de.dlr.ivf.tapas.runtime.client.SimulationMonitor.updateSimulationData().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/runtime/client/SimulationControl.java