TAPAS: de.dlr.ivf.tapas.installer.Installer Class Reference
de.dlr.ivf.tapas.installer.Installer Class Reference
Static Public Member Functions
static void main (String[] args)
Static Private Member Functions
static void closeConnection ()
static String composeFilesInDir (String dir)
static void connectToDB (String dbname)
static void createDB (String dbname)
static boolean deleteDirectory (File directoryToBeDeleted)
static void dropDBIfFailed ()
static void executeCommand (String command)
static void executeCommands (String[] commands)
static void executeCompleteQuery (String destination)
static void executeDir (String dir)
static void executeFile (String file)
static void executeFile (Path path)
static void exitAndCleanUp (Exception e, boolean cleanUp)
static void help (Options options)
static List< String > parseFunctionFile (String functionString)
static String promptCmdArgument (CommandLine cmd, Options opts, String argumentOpt, boolean passwordPrompt)
static void existsDestinationDirectory (String destination)
static void unzip (String source, String destination)
Static Private Attributes
static Connection DBCONNECTION
static String DBSERVER
static String DBNAME
static String DBUSER
static String DBPASSWORD
static boolean DESTINATION_ALREADY_EXISTS = true
static String source = "sql_dumps.zip"
static String destination = "tmp_sql_dumps"
Detailed Description
Installer scripts for a minimal and exemplary install of a TAPAS database installation
Definition at line 32 of file Installer.java.
Member Function Documentation
closeConnection()
static void de.dlr.ivf.tapas.installer.Installer.closeConnection () static private
Closes the database connection
Definition at line 51 of file Installer.java.
References de.dlr.ivf.tapas.installer.Installer.DBCONNECTION, and de.dlr.ivf.tapas.installer.Installer.exitAndCleanUp().
Referenced by de.dlr.ivf.tapas.installer.Installer.dropDBIfFailed(), and de.dlr.ivf.tapas.installer.Installer.main().
composeFilesInDir()
static String de.dlr.ivf.tapas.installer.Installer.composeFilesInDir (String dir) static private
Takes a directory and concatenates all files in it to one string
Parameters
dir string representing a directory
Returns
string composed of all files in the given directory dir
Definition at line 67 of file Installer.java.
References de.dlr.ivf.tapas.installer.Installer.DBUSER, and de.dlr.ivf.tapas.installer.Installer.exitAndCleanUp().
Referenced by de.dlr.ivf.tapas.installer.Installer.executeCompleteQuery().
connectToDB()
static void de.dlr.ivf.tapas.installer.Installer.connectToDB (String dbname) static private
Connects to a postgres database
Parameters
dbname name of the database one wants connect to
Definition at line 88 of file Installer.java.
References de.dlr.ivf.tapas.installer.Installer.DBCONNECTION, de.dlr.ivf.tapas.installer.Installer.DBPASSWORD, de.dlr.ivf.tapas.installer.Installer.DBSERVER, de.dlr.ivf.tapas.installer.Installer.DBUSER, and de.dlr.ivf.tapas.installer.Installer.exitAndCleanUp().
Referenced by de.dlr.ivf.tapas.installer.Installer.dropDBIfFailed(), and de.dlr.ivf.tapas.installer.Installer.main().
createDB()
static void de.dlr.ivf.tapas.installer.Installer.createDB (String dbname) static private
Creates a new database on the server
Parameters
dbname name of the database to be created
Definition at line 105 of file Installer.java.
References de.dlr.ivf.tapas.installer.Installer.DBCONNECTION, and de.dlr.ivf.tapas.installer.Installer.exitAndCleanUp().
Referenced by de.dlr.ivf.tapas.installer.Installer.main().
deleteDirectory()
static boolean de.dlr.ivf.tapas.installer.Installer.deleteDirectory (File directoryToBeDeleted) static private
Deletes a directory recursively, i.e. at first each file and subfolder in the directory is deleted first This is a necessary condition for the standard file deletion procedure in Java
Parameters
directoryToBeDeleted File pointing to the directory to be deleted
Returns
true if deletion was successful
Definition at line 123 of file Installer.java.
Referenced by de.dlr.ivf.tapas.installer.Installer.exitAndCleanUp(), and de.dlr.ivf.tapas.installer.Installer.main().
dropDBIfFailed()
static void de.dlr.ivf.tapas.installer.Installer.dropDBIfFailed () static private
Drops newly created database DBNAME if it failed during the process
Definition at line 136 of file Installer.java.
References de.dlr.ivf.tapas.installer.Installer.closeConnection(), de.dlr.ivf.tapas.installer.Installer.connectToDB(), de.dlr.ivf.tapas.installer.Installer.DBCONNECTION, de.dlr.ivf.tapas.installer.Installer.DBNAME, and de.dlr.ivf.tapas.installer.Installer.exitAndCleanUp().
Referenced by de.dlr.ivf.tapas.installer.Installer.exitAndCleanUp().
executeCommand()
static void de.dlr.ivf.tapas.installer.Installer.executeCommand (String command) static private
Execute an sql command on a database
Parameters
command sql command to execute
Definition at line 156 of file Installer.java.
References de.dlr.ivf.tapas.installer.Installer.DBCONNECTION, and de.dlr.ivf.tapas.installer.Installer.exitAndCleanUp().
executeCommands()
static void de.dlr.ivf.tapas.installer.Installer.executeCommands (String[] commands) static private
Executes an array of postgres commands as strings
Parameters
commands string array of postgres commands
Definition at line 170 of file Installer.java.
References de.dlr.ivf.tapas.installer.Installer.DBCONNECTION, and de.dlr.ivf.tapas.installer.Installer.exitAndCleanUp().
Referenced by de.dlr.ivf.tapas.installer.Installer.executeCompleteQuery(), and de.dlr.ivf.tapas.installer.Installer.executeFile().
executeCompleteQuery()
static void de.dlr.ivf.tapas.installer.Installer.executeCompleteQuery (String destination) static private
Reads all necessary sql files and executes the command to the database
Parameters
destination directory of sql-datasets
Definition at line 191 of file Installer.java.
References de.dlr.ivf.tapas.installer.Installer.composeFilesInDir(), de.dlr.ivf.tapas.installer.Installer.DBCONNECTION, de.dlr.ivf.tapas.installer.Installer.destination, de.dlr.ivf.tapas.installer.Installer.executeCommands(), de.dlr.ivf.tapas.installer.Installer.executeDir(), de.dlr.ivf.tapas.installer.Installer.executeFile(), and de.dlr.ivf.tapas.installer.Installer.parseFunctionFile().
Referenced by de.dlr.ivf.tapas.installer.Installer.main().
executeDir()
static void de.dlr.ivf.tapas.installer.Installer.executeDir (String dir) static private
Walks over each sql-file in a directory and executes all sql statements
Parameters
dir string representing a directory
Definition at line 237 of file Installer.java.
References de.dlr.ivf.tapas.installer.Installer.executeFile(), and de.dlr.ivf.tapas.installer.Installer.exitAndCleanUp().
Referenced by de.dlr.ivf.tapas.installer.Installer.executeCompleteQuery().
executeFile() [1/2]
static void de.dlr.ivf.tapas.installer.Installer.executeFile (Path path) static private
Reads an sql-file and executes each command. For most files the commands will be executed in batches through the executeCommands method. For big files like core_berlin_matrices.sql each command is executed separately because of memory overhead.
Parameters
path path object pointing to a file
Definition at line 263 of file Installer.java.
References de.dlr.ivf.tapas.installer.Installer.DBUSER, de.dlr.ivf.tapas.installer.Installer.executeCommands(), and de.dlr.ivf.tapas.installer.Installer.exitAndCleanUp().
executeFile() [2/2]
static void de.dlr.ivf.tapas.installer.Installer.executeFile (String file) static private
Reads an sql-file and executes each command. For most files the commands will be executed in batches through the executeCommands method. For big files like core_berlin_matrices.sql each command is executed separately because of memory overhead.
Parameters
file file file name as a string
Definition at line 252 of file Installer.java.
Referenced by de.dlr.ivf.tapas.installer.Installer.executeCompleteQuery(), and de.dlr.ivf.tapas.installer.Installer.executeDir().
existsDestinationDirectory()
static void de.dlr.ivf.tapas.installer.Installer.existsDestinationDirectory (String destination) static private
Checks if the destination directory (where the sql_dumps.zip will extracted to) already exists or not Sets the global DESTINATION_ALREADY_EXISTS variable to true if it exists. Normally we delete the tmp_sql_dumps folder after the Installer run. But we do not want to do this if this folder has been created already (who knows what is in there).
Parameters
destination string oath to destination folder
Definition at line 399 of file Installer.java.
References de.dlr.ivf.tapas.installer.Installer.destination, and de.dlr.ivf.tapas.installer.Installer.DESTINATION_ALREADY_EXISTS.
Referenced by de.dlr.ivf.tapas.installer.Installer.unzip().
exitAndCleanUp()
static void de.dlr.ivf.tapas.installer.Installer.exitAndCleanUp (Exception e, boolean cleanUp) static private
Method to exit the program as cleanly as possible when an exception occurred, i.e. it prints the stack trace and drops the newly created database if necessary additionally it deletes the destination folder (if it did not exist at the beginning)
Parameters
e exception whose stack trace is printed
cleanUp if true it drops the newly created database
Definition at line 281 of file Installer.java.
References de.dlr.ivf.tapas.installer.Installer.deleteDirectory(), de.dlr.ivf.tapas.installer.Installer.destination, de.dlr.ivf.tapas.installer.Installer.DESTINATION_ALREADY_EXISTS, and de.dlr.ivf.tapas.installer.Installer.dropDBIfFailed().
Referenced by de.dlr.ivf.tapas.installer.Installer.closeConnection(), de.dlr.ivf.tapas.installer.Installer.composeFilesInDir(), de.dlr.ivf.tapas.installer.Installer.connectToDB(), de.dlr.ivf.tapas.installer.Installer.createDB(), de.dlr.ivf.tapas.installer.Installer.dropDBIfFailed(), de.dlr.ivf.tapas.installer.Installer.executeCommand(), de.dlr.ivf.tapas.installer.Installer.executeCommands(), de.dlr.ivf.tapas.installer.Installer.executeDir(), de.dlr.ivf.tapas.installer.Installer.executeFile(), and de.dlr.ivf.tapas.installer.Installer.main().
help()
static void de.dlr.ivf.tapas.installer.Installer.help (Options options) static private
Prints the help message and exits the program afterwards.
Parameters
options commandline options
Definition at line 293 of file Installer.java.
Referenced by de.dlr.ivf.tapas.installer.Installer.main().
main()
static void de.dlr.ivf.tapas.installer.Installer.main (String[] args) static
Definition at line 307 of file Installer.java.
References de.dlr.ivf.tapas.installer.Installer.closeConnection(), de.dlr.ivf.tapas.installer.Installer.connectToDB(), de.dlr.ivf.tapas.installer.Installer.createDB(), de.dlr.ivf.tapas.installer.Installer.DBNAME, de.dlr.ivf.tapas.installer.Installer.DBPASSWORD, de.dlr.ivf.tapas.installer.Installer.DBSERVER, de.dlr.ivf.tapas.installer.Installer.DBUSER, de.dlr.ivf.tapas.installer.Installer.deleteDirectory(), de.dlr.ivf.tapas.installer.Installer.destination, de.dlr.ivf.tapas.installer.Installer.DESTINATION_ALREADY_EXISTS, de.dlr.ivf.tapas.installer.Installer.executeCompleteQuery(), de.dlr.ivf.tapas.installer.Installer.exitAndCleanUp(), de.dlr.ivf.tapas.installer.Installer.help(), de.dlr.ivf.tapas.installer.Installer.promptCmdArgument(), de.dlr.ivf.tapas.installer.Installer.source, and de.dlr.ivf.tapas.installer.Installer.unzip().
parseFunctionFile()
static List<String> de.dlr.ivf.tapas.installer.Installer.parseFunctionFile (String functionString) static private
Parses an sql string containing one or more sql function definitions and other sql commands. Uses the property that all our functions start with "CREATE OR REPLACE FUNCTION" and end with "COST 100;" Returns a list of strings, where each string represents a command for a proper execution of sql commands
Parameters
functionString content
Returns
list of sql commands (one function is one command) as strings
Definition at line 353 of file Installer.java.
Referenced by de.dlr.ivf.tapas.installer.Installer.executeCompleteQuery().
promptCmdArgument()
static String de.dlr.ivf.tapas.installer.Installer.promptCmdArgument (CommandLine cmd, Options opts, String argumentOpt, boolean passwordPrompt) static private
Either evaluates the given command line arguments or prompt for missing arguments
Parameters
cmd commandline object with parsed arguments
opts options
argumentOpt specific option to read
passwordPrompt boolean value if the argument is either a password or not
Returns
string containing the argument value
Definition at line 380 of file Installer.java.
Referenced by de.dlr.ivf.tapas.installer.Installer.main().
unzip()
static void de.dlr.ivf.tapas.installer.Installer.unzip (String source, String destination) static private
Extracts zip archive into a destination folder
Parameters
source zip archive
destination directory to which is archive is extracted
Definition at line 425 of file Installer.java.
References de.dlr.ivf.tapas.installer.Installer.destination, de.dlr.ivf.tapas.installer.Installer.existsDestinationDirectory(), and de.dlr.ivf.tapas.installer.Installer.source.
Referenced by de.dlr.ivf.tapas.installer.Installer.main().
Member Data Documentation
DBCONNECTION
Connection de.dlr.ivf.tapas.installer.Installer.DBCONNECTION static private
Definition at line 34 of file Installer.java.
Referenced by de.dlr.ivf.tapas.installer.Installer.closeConnection(), de.dlr.ivf.tapas.installer.Installer.connectToDB(), de.dlr.ivf.tapas.installer.Installer.createDB(), de.dlr.ivf.tapas.installer.Installer.dropDBIfFailed(), de.dlr.ivf.tapas.installer.Installer.executeCommand(), de.dlr.ivf.tapas.installer.Installer.executeCommands(), and de.dlr.ivf.tapas.installer.Installer.executeCompleteQuery().
DBNAME
String de.dlr.ivf.tapas.installer.Installer.DBNAME static private
Definition at line 36 of file Installer.java.
Referenced by de.dlr.ivf.tapas.installer.Installer.dropDBIfFailed(), and de.dlr.ivf.tapas.installer.Installer.main().
DBPASSWORD
String de.dlr.ivf.tapas.installer.Installer.DBPASSWORD static private
Definition at line 38 of file Installer.java.
Referenced by de.dlr.ivf.tapas.installer.Installer.connectToDB(), and de.dlr.ivf.tapas.installer.Installer.main().
DBSERVER
String de.dlr.ivf.tapas.installer.Installer.DBSERVER static private
Definition at line 35 of file Installer.java.
Referenced by de.dlr.ivf.tapas.installer.Installer.connectToDB(), and de.dlr.ivf.tapas.installer.Installer.main().
DBUSER
String de.dlr.ivf.tapas.installer.Installer.DBUSER static private
Definition at line 37 of file Installer.java.
Referenced by de.dlr.ivf.tapas.installer.Installer.composeFilesInDir(), de.dlr.ivf.tapas.installer.Installer.connectToDB(), de.dlr.ivf.tapas.installer.Installer.executeFile(), and de.dlr.ivf.tapas.installer.Installer.main().
destination
String de.dlr.ivf.tapas.installer.Installer.destination = "tmp_sql_dumps" static private
Definition at line 46 of file Installer.java.
Referenced by de.dlr.ivf.tapas.installer.Installer.executeCompleteQuery(), de.dlr.ivf.tapas.installer.Installer.existsDestinationDirectory(), de.dlr.ivf.tapas.installer.Installer.exitAndCleanUp(), de.dlr.ivf.tapas.installer.Installer.main(), and de.dlr.ivf.tapas.installer.Installer.unzip().
DESTINATION_ALREADY_EXISTS
boolean de.dlr.ivf.tapas.installer.Installer.DESTINATION_ALREADY_EXISTS = true static private
Definition at line 41 of file Installer.java.
Referenced by de.dlr.ivf.tapas.installer.Installer.existsDestinationDirectory(), de.dlr.ivf.tapas.installer.Installer.exitAndCleanUp(), and de.dlr.ivf.tapas.installer.Installer.main().
source
String de.dlr.ivf.tapas.installer.Installer.source = "sql_dumps.zip" static private
Definition at line 44 of file Installer.java.
Referenced by de.dlr.ivf.tapas.installer.Installer.main(), and de.dlr.ivf.tapas.installer.Installer.unzip().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/installer/Installer.java