TAPAS: de.dlr.ivf.tapas.tools.TPS_ParkAndRideAnalysator Class Reference
de.dlr.ivf.tapas.tools.TPS_ParkAndRideAnalysator Class Reference
Classes
class PnRSpace
Public Member Functions
void analyzeTrips (String name)
void loadInterchanges (String name, String tableName)
void loadMIVDist (String name, String tableName)
void loadOriginalTimes (String name, String tableName)
void loadPNRTimes (String name, String tableName)
void loadPnRRegion (String table, String name)
void printConnHistoOnScreen ()
void printTimeHistoOnScreen ()
void storeInterchangesInDB (String tableName)
Public Member Functions inherited from de.dlr.ivf.tapas.tools.TPS_ParkAndRideRouter
Matrix createPandRMatrix ()
void loadMatrices (String mivName, String ptName, String walkName, String tableName)
void loadTAZRestriction (String tazInfo, String table)
void routePnR (double transferTime)
void saveInterchangeMatrixInDB (String matrixName, String tableName)
void storeMatrixInDB (Matrix matrix, String matrixName, String tableName)
Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_BasicConnectionClass ()
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass)
TPS_BasicConnectionClass (String loginFile)
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass, String loginFile)
boolean checkMatrixName (String matrixName)
TPS_ParameterClass getParameters ()
String readParameter (String simKey, String paramKey)
void storeInDB (String matrixName, double[][] matrix, int decimalPlaces)
Static Public Member Functions
static void main (String[] args)
Static Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
static double[][] array1Dto2D (Integer[] matrixVal)
static double[][] array1Dto2D (int[] matrixVal)
static File getRuntimeFile (boolean forceNewFile)
static File getRuntimeFile (String propertyFile, boolean forceNewFile)
static File getRuntimeFile ()
static File getRuntimeFile (String propertyFile)
static int[][] intArray1Dto2D (int[] matrixVal)
static String matrixToSQLArray (double[][] array, int decimalPlaces)
static StringWriter matrixToStringWriterSQL (double[][] array, int decimalPlaces)
Additional Inherited Members
Protected Member Functions inherited from de.dlr.ivf.tapas.tools.TPS_ParkAndRideRouter
Matrix readMatrix (String matrixName, String tableName)
Protected Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
void finalize ()
Protected Attributes inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_DB_Connector dbCon = null
TPS_ParameterClass parameterClass
Detailed Description
Definition at line 19 of file TPS_ParkAndRideAnalysator.java.
Member Function Documentation
analyzeTrips()
void de.dlr.ivf.tapas.tools.TPS_ParkAndRideAnalysator.analyzeTrips (String name)
Definition at line 46 of file TPS_ParkAndRideAnalysator.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), de.dlr.ivf.tapas.util.Matrix.getNumberOfColums(), de.dlr.ivf.tapas.util.Matrix.getNumberOfRows(), de.dlr.ivf.tapas.util.Matrix.getValue(), and name.
Referenced by de.dlr.ivf.tapas.tools.TPS_ParkAndRideAnalysator.main().
loadInterchanges()
void de.dlr.ivf.tapas.tools.TPS_ParkAndRideAnalysator.loadInterchanges (String name, String tableName)
Definition at line 122 of file TPS_ParkAndRideAnalysator.java.
References de.dlr.ivf.tapas.tools.TPS_ParkAndRideRouter.readMatrix().
Referenced by de.dlr.ivf.tapas.tools.TPS_ParkAndRideAnalysator.main().
loadMIVDist()
void de.dlr.ivf.tapas.tools.TPS_ParkAndRideAnalysator.loadMIVDist (String name, String tableName)
Definition at line 126 of file TPS_ParkAndRideAnalysator.java.
References de.dlr.ivf.tapas.tools.TPS_ParkAndRideRouter.readMatrix().
Referenced by de.dlr.ivf.tapas.tools.TPS_ParkAndRideAnalysator.main().
loadOriginalTimes()
void de.dlr.ivf.tapas.tools.TPS_ParkAndRideAnalysator.loadOriginalTimes (String name, String tableName)
Definition at line 130 of file TPS_ParkAndRideAnalysator.java.
References de.dlr.ivf.tapas.tools.TPS_ParkAndRideRouter.readMatrix().
Referenced by de.dlr.ivf.tapas.tools.TPS_ParkAndRideAnalysator.main().
loadPnRRegion()
void de.dlr.ivf.tapas.tools.TPS_ParkAndRideAnalysator.loadPnRRegion (String table, String name)
Definition at line 138 of file TPS_ParkAndRideAnalysator.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), and name.
Referenced by de.dlr.ivf.tapas.tools.TPS_ParkAndRideAnalysator.main().
loadPNRTimes()
void de.dlr.ivf.tapas.tools.TPS_ParkAndRideAnalysator.loadPNRTimes (String name, String tableName)
Definition at line 134 of file TPS_ParkAndRideAnalysator.java.
References de.dlr.ivf.tapas.tools.TPS_ParkAndRideRouter.readMatrix().
Referenced by de.dlr.ivf.tapas.tools.TPS_ParkAndRideAnalysator.main().
main()
static void de.dlr.ivf.tapas.tools.TPS_ParkAndRideAnalysator.main (String[] args) static
Reimplemented from de.dlr.ivf.tapas.tools.TPS_ParkAndRideRouter.
Definition at line 34 of file TPS_ParkAndRideAnalysator.java.
References de.dlr.ivf.tapas.tools.TPS_ParkAndRideAnalysator.analyzeTrips(), de.dlr.ivf.tapas.tools.TPS_ParkAndRideAnalysator.loadInterchanges(), de.dlr.ivf.tapas.tools.TPS_ParkAndRideAnalysator.loadMIVDist(), de.dlr.ivf.tapas.tools.TPS_ParkAndRideAnalysator.loadOriginalTimes(), de.dlr.ivf.tapas.tools.TPS_ParkAndRideAnalysator.loadPnRRegion(), de.dlr.ivf.tapas.tools.TPS_ParkAndRideAnalysator.loadPNRTimes(), de.dlr.ivf.tapas.tools.TPS_ParkAndRideAnalysator.printConnHistoOnScreen(), and de.dlr.ivf.tapas.tools.TPS_ParkAndRideAnalysator.storeInterchangesInDB().
printConnHistoOnScreen()
void de.dlr.ivf.tapas.tools.TPS_ParkAndRideAnalysator.printConnHistoOnScreen ()
Definition at line 158 of file TPS_ParkAndRideAnalysator.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_ParkAndRideAnalysator.main().
printTimeHistoOnScreen()
void de.dlr.ivf.tapas.tools.TPS_ParkAndRideAnalysator.printTimeHistoOnScreen ()
Definition at line 167 of file TPS_ParkAndRideAnalysator.java.
storeInterchangesInDB()
void de.dlr.ivf.tapas.tools.TPS_ParkAndRideAnalysator.storeInterchangesInDB (String tableName)
Definition at line 176 of file TPS_ParkAndRideAnalysator.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute().
Referenced by de.dlr.ivf.tapas.tools.TPS_ParkAndRideAnalysator.main().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/TPS_ParkAndRideAnalysator.java