TAPAS: de.dlr.ivf.tapas.mode.TPS_Mode Class Reference
de.dlr.ivf.tapas.mode.TPS_Mode Class Reference abstract
Classes
enum ModeType
enum TPS_ModeCodeType
Public Member Functions
void addModeToMap ()
ModeType getAttribute ()
int getCode (TPS_ModeCodeType type)
double getCost_per_km (SimulationType simType)
abstract double getDistance (Locatable start, Locatable end, SimulationType simType, TPS_Car car)
ModeType getModeType ()
String getName ()
TPS_ParameterClass getParameters ()
void setParameters (TPS_ParameterClass param)
abstract double getTravelTime (Locatable start, Locatable end, int time, SimulationType simType, TPS_ActivityConstant actCodeFrom, TPS_ActivityConstant actCodeTo, TPS_Person person, TPS_Car car)
double getVariableCost_per_km (SimulationType simType)
ParamValue getVelocity ()
boolean isFix ()
boolean isType (ModeType... type)
boolean isType (ModeType type)
boolean isUseBase ()
String toString (String prefix)
Static Public Member Functions
static void clearModeMap ()
static TPS_Mode get (ModeType key)
static Collection< TPS_Mode > getConstants ()
static TPS_UtilityFunction getUtilityFunction (TPS_ParameterClass parameterClass)
static boolean hasConnection (double val)
static void initUtilityFunction (TPS_ParameterClass parameterClass)
static boolean noConnection (double val)
Public Attributes
ParamValue velocity = null
double cost_per_km = 0
double cost_per_km_base = 0
double variable_cost_per_km = 0
double variable_cost_per_km_base = 0
boolean useBase = false
Static Public Attributes
static ModeType[] MODE_TYPE_ARRAY = new ModeType[]{ModeType.WALK, ModeType.BIKE, ModeType.MIT, ModeType.MIT_PASS, ModeType.TAXI, ModeType.PT, ModeType.TRAIN}
static double NO_CONNECTION = -1
static double VISUM_NO_CONNECTION = 99999.0
Protected Member Functions
TPS_Mode (String name, String[] attributes, boolean isFix, TPS_ParameterClass parameterClass)
Private Member Functions
void setAttribute (ModeType attribute)
void setFix (boolean isFix)
Private Attributes
TPS_ParameterClass parameterClass
final EnumMap< TPS_ModeCodeType, TPS_InternalConstant< TPS_ModeCodeType > > map
final String name
boolean isFix
ModeType modeType
Static Private Attributes
static final EnumMap< ModeType, TPS_Mode > MODE_MAP = new EnumMap<>(ModeType.class)
static TPS_UtilityFunction UTILITY_FUNCTION = null
Detailed Description
This class represents the basic features of a mode. It is characterized by a type and a name.
Every mode is a singleton so the type and the name have to be unique. This is realized by the visibility of the constructor. Only classes in this package have access.
see TPS_ModeSet
Furthermore there are two abstract methods to calculate the distance and the travel time between two locations.
Definition at line 42 of file TPS_Mode.java.
Constructor & Destructor Documentation
TPS_Mode()
de.dlr.ivf.tapas.mode.TPS_Mode.TPS_Mode (String name, String[] attributes, boolean isFix, TPS_ParameterClass parameterClass) protected
Basic constructor for a TPS_Mode
Parameters
name of the mode
attributes list of string containing the (name, code, type) triples; length must be divisible by 3
isFix states if the mode is fix, like bike or car
parameterClass reference
Definition at line 86 of file TPS_Mode.java.
References name, and type.
Member Function Documentation
addModeToMap()
void de.dlr.ivf.tapas.mode.TPS_Mode.addModeToMap ()
Adds this TPS_Mode instance to the global static MODE_MAP
Definition at line 194 of file TPS_Mode.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readModes().
clearModeMap()
static void de.dlr.ivf.tapas.mode.TPS_Mode.clearModeMap () static
Empties the global static TPS_Mode map
Definition at line 115 of file TPS_Mode.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.clearConstants().
get()
static TPS_Mode de.dlr.ivf.tapas.mode.TPS_Mode.get (ModeType key) static
This method returns the mode corresponding to the given mode type
Parameters
key key mode type
Returns
mode corresponding to the mode type
Definition at line 125 of file TPS_Mode.java.
References de.dlr.ivf.tapas.mode.TPS_Mode.get().
Referenced by de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree.applyExpertKnowledge(), de.dlr.ivf.tapas.mode.TPS_ModeDistribution.calculateDistribution(), de.dlr.ivf.tapas.mode.TPS_Mode.get(), de.dlr.ivf.tapas.scheme.TPS_TourPart.TravelDurations.getArrivalDuration(), de.dlr.ivf.tapas.scheme.TPS_TourPart.TravelDurations.getDepartureDuration(), de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixed.getDistributionSet(), de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixedBS.getDistributionSet(), de.dlr.ivf.tapas.modechoice.TPS_UtilityMNL.getDistributionSet(), de.dlr.ivf.tapas.loc.TPS_MultipleTAZRepresentant.getLocationRepresentatives(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.getLogSum(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.getModeLogSum(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessMode.getTravelTime(), de.dlr.ivf.tapas.loc.TPS_SelectWithSingleAccessMode.getTravelTime(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readUtilityFunction(), de.dlr.ivf.tapas.plan.TPS_LocatedStay.selectLocation(), de.dlr.ivf.tapas.mode.TPS_ModeSet.selectMode(), de.dlr.ivf.tapas.mode.TPS_ModeSet.selectMode0(), de.dlr.ivf.tapas.scheme.TPS_TourPart.setInitialTravelDurations(), de.dlr.ivf.tapas.scheme.TPS_TourPart.updateActualTravelDistances(), and de.dlr.ivf.tapas.TPS_Main.updateCosts().
getAttribute()
ModeType de.dlr.ivf.tapas.mode.TPS_Mode.getAttribute ()
Returns the type of the mode
Returns
mode type attribute
Definition at line 210 of file TPS_Mode.java.
getCode()
int de.dlr.ivf.tapas.mode.TPS_Mode.getCode (TPS_ModeCodeType type)
Parameters
type TPS_ModeCodeTyp like MCT or VOT
Returns
code of the constant corresponding to the given enum type
Definition at line 274 of file TPS_Mode.java.
References type.
Referenced by de.dlr.ivf.tapas.mode.TPS_ExtMode.getMCTCode(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessMode.getTravelTime(), and de.dlr.ivf.tapas.loc.TPS_SelectWithSingleAccessMode.getTravelTime().
getConstants()
static Collection<TPS_Mode> de.dlr.ivf.tapas.mode.TPS_Mode.getConstants () static
Returns a collection/view of the values of the PERSON_GROUP_MAP, i.e. all stored person group constants Note: changes in the map are reflected in the collection and vice-versa
Returns
a collection/view of the values of the PERSON_GROUP_MAP
Definition at line 135 of file TPS_Mode.java.
Referenced by de.dlr.ivf.tapas.modechoice.TPS_Node.getCopyOfValueDistribution(), de.dlr.ivf.tapas.mode.TPS_ModeDistribution.getDistribution(), de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixedBS.getDistributionSet(), de.dlr.ivf.tapas.loc.TPS_SelectWithSingleAccessMode.getTravelTime(), de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeNode.modifyDistribution(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readExpertKnowledgeTree(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readModeChoiceTree(), and de.dlr.ivf.tapas.mode.TPS_ModeSet.toString().
getCost_per_km()
double de.dlr.ivf.tapas.mode.TPS_Mode.getCost_per_km (SimulationType simType)
This method returns the cost factor for this mode for the specified Scenario case. It must be multiplied with a cost per km value.
Parameters
simType scenario or base
Returns
cost factor per km.
Definition at line 284 of file TPS_Mode.java.
References de.dlr.ivf.tapas.util.parameters.SimulationType.BASE.
getDistance()
abstract double de.dlr.ivf.tapas.mode.TPS_Mode.getDistance (Locatable start, Locatable end, SimulationType simType, TPS_Car car) abstract
This method calculates the real distance between two locations.
Parameters
start location, where this trip starts
end location, where this trip ends
simType Type of simulation (Base/Scenario)
car The car for this trip, if available. Set it to null, if no car is used
Returns
calculated distance in meter
Reimplemented in de.dlr.ivf.tapas.mode.TPS_NonMotorisedMode, de.dlr.ivf.tapas.mode.TPS_MassTransportMode, and de.dlr.ivf.tapas.mode.TPS_IndividualTransportMode.
Referenced by de.dlr.ivf.tapas.util.TPS_Geometrics.getDistance(), de.dlr.ivf.tapas.loc.TPS_MultipleTAZRepresentant.getLocationRepresentatives(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.getLogSum(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessMode.getTravelTime(), de.dlr.ivf.tapas.loc.TPS_SelectWithSingleAccessMode.getTravelTime(), de.dlr.ivf.tapas.plan.TPS_LocatedStay.selectLocation(), and de.dlr.ivf.tapas.mode.TPS_ModeSet.selectMode().
getModeType()
ModeType de.dlr.ivf.tapas.mode.TPS_Mode.getModeType ()
Gets the ModeType for this mode
Returns
The ModeType
Definition at line 320 of file TPS_Mode.java.
getName()
String de.dlr.ivf.tapas.mode.TPS_Mode.getName ()
Definition at line 324 of file TPS_Mode.java.
References name.
Referenced by de.dlr.ivf.tapas.mode.TPS_ExtMode.getName().
getParameters()
TPS_ParameterClass de.dlr.ivf.tapas.mode.TPS_Mode.getParameters ()
This method returns the parameter class reference
Returns
parameter class reference
Definition at line 333 of file TPS_Mode.java.
Referenced by de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree.applyExpertKnowledge(), de.dlr.ivf.tapas.mode.TPS_IndividualTransportMode.getDistance(), de.dlr.ivf.tapas.mode.TPS_NonMotorisedMode.getDistance(), de.dlr.ivf.tapas.util.TPS_Geometrics.getDistance(), de.dlr.ivf.tapas.modechoice.TPS_UtilityMNL.getDistributionSet(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.getModeLogSum(), de.dlr.ivf.tapas.mode.TPS_IndividualTransportMode.getTravelTime(), and de.dlr.ivf.tapas.mode.TPS_NonMotorisedMode.getTravelTime().
getTravelTime()
abstract double de.dlr.ivf.tapas.mode.TPS_Mode.getTravelTime (Locatable start, Locatable end, int time, SimulationType simType, TPS_ActivityConstant actCodeFrom, TPS_ActivityConstant actCodeTo, TPS_Person person, TPS_Car car) abstract
This method calculates the travel time between two locations.
Parameters
start location, where this trip starts
end location, where this trip ends
time departure time of the trip in seconds after midnight
simType simulation type
actCodeFrom activity code of the earlier episode
actCodeTo activity code of the later episode
person reference to the person on this trip
Returns
travel time in seconds
Reimplemented in de.dlr.ivf.tapas.mode.TPS_NonMotorisedMode, de.dlr.ivf.tapas.mode.TPS_MassTransportMode, and de.dlr.ivf.tapas.mode.TPS_IndividualTransportMode.
Referenced by de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree.applyExpertKnowledge(), de.dlr.ivf.tapas.modechoice.TPS_UtilityMNL.calculateDelta(), de.dlr.ivf.tapas.modechoice.TPS_UtilityMNL.getDistributionSet(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.getModeLogSum(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessMode.getTravelTime(), and de.dlr.ivf.tapas.loc.TPS_SelectWithSingleAccessMode.getTravelTime().
getUtilityFunction()
static TPS_UtilityFunction de.dlr.ivf.tapas.mode.TPS_Mode.getUtilityFunction (TPS_ParameterClass parameterClass) static
Method initializes and returns utility function
Parameters
parameterClass reference
Returns
utility function
Definition at line 145 of file TPS_Mode.java.
References de.dlr.ivf.tapas.mode.TPS_Mode.initUtilityFunction(), and de.dlr.ivf.tapas.mode.TPS_Mode.UTILITY_FUNCTION.
Referenced by de.dlr.ivf.tapas.mode.TPS_ModeSet.getModeDistribution(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.getModeLogSum(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readUtilityFunction(), and de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.selectLocationFromChoiceSet().
getVariableCost_per_km()
double de.dlr.ivf.tapas.mode.TPS_Mode.getVariableCost_per_km (SimulationType simType)
This method returns the cost factor for the variable costs for the specified Scenario case. It must be multiplied with a variable cost per km value.
Parameters
simType Scenario or base
Returns
cost factor per km.
Definition at line 367 of file TPS_Mode.java.
References de.dlr.ivf.tapas.util.parameters.SimulationType.BASE.
getVelocity()
ParamValue de.dlr.ivf.tapas.mode.TPS_Mode.getVelocity ()
If there is a specific velocity for this mode known, it can be got with this method.
Returns
specific velocity in m/s
Definition at line 380 of file TPS_Mode.java.
Referenced by de.dlr.ivf.tapas.scheme.TPS_TourPart.TravelDurations.getArrivalDuration(), de.dlr.ivf.tapas.scheme.TPS_TourPart.TravelDurations.getDepartureDuration(), de.dlr.ivf.tapas.mode.TPS_NonMotorisedMode.getTravelTime(), de.dlr.ivf.tapas.scheme.TPS_TourPart.setInitialTravelDurations(), and de.dlr.ivf.tapas.scheme.TPS_TourPart.updateActualTravelDistances().
hasConnection()
static boolean de.dlr.ivf.tapas.mode.TPS_Mode.hasConnection (double val) static
Method to check if the returned value is a connection. Inverse function is noConnection.
Parameters
val the value to check
Returns
true if connection is detected
Definition at line 158 of file TPS_Mode.java.
References de.dlr.ivf.tapas.mode.TPS_Mode.NO_CONNECTION.
Referenced by de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessMode.getTravelTime(), and de.dlr.ivf.tapas.loc.TPS_SelectWithSingleAccessMode.getTravelTime().
initUtilityFunction()
static void de.dlr.ivf.tapas.mode.TPS_Mode.initUtilityFunction (TPS_ParameterClass parameterClass) static
This method initializes the utility function.
Parameters
parameterClass reference the parameter class object
Definition at line 167 of file TPS_Mode.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.HierarchyLogLevel.APPLICATION, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.FATAL, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.mode.TPS_Mode.UTILITY_FUNCTION, and de.dlr.ivf.tapas.util.parameters.ParamString.UTILITY_FUNCTION_CLASS.
Referenced by de.dlr.ivf.tapas.mode.TPS_Mode.getUtilityFunction().
isFix()
boolean de.dlr.ivf.tapas.mode.TPS_Mode.isFix ()
Flag determining whether the mode is fix or can be chosen
Returns
fix flag
Definition at line 391 of file TPS_Mode.java.
isType() [1/2]
boolean de.dlr.ivf.tapas.mode.TPS_Mode.isType (ModeType type)
This method check if the mode contains the given attribute
Parameters
type mode type attribute
Returns
true if the attribute is contained, false otherwise
Definition at line 423 of file TPS_Mode.java.
References type.
isType() [2/2]
boolean de.dlr.ivf.tapas.mode.TPS_Mode.isType (ModeType... type)
This method check if the mode contains one of the given attributes
Parameters
type mode type attributes
Returns
true if the mode contains one attribute, false otherwise
Definition at line 410 of file TPS_Mode.java.
References type.
Referenced by de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree.applyExpertKnowledge(), de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixedBS.calculateDelta(), de.dlr.ivf.tapas.modechoice.TPS_UtilityMNL.getDistributionSet(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.getModeLogSum(), de.dlr.ivf.tapas.mode.TPS_NonMotorisedMode.getTravelTime(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessMode.getTravelTime(), de.dlr.ivf.tapas.loc.TPS_SelectWithSingleAccessMode.getTravelTime(), de.dlr.ivf.tapas.mode.TPS_ExtMode.isBikeUsed(), de.dlr.ivf.tapas.mode.TPS_ExtMode.isCarUsed(), and de.dlr.ivf.tapas.mode.TPS_ModeSet.selectMode0().
isUseBase()
boolean de.dlr.ivf.tapas.mode.TPS_Mode.isUseBase ()
Flag to indicate if time differences to the base scenario are present.
Returns
True if tie travel times of scenario and base differs.
Definition at line 432 of file TPS_Mode.java.
Referenced by de.dlr.ivf.tapas.modechoice.TPS_UtilityMNL.calculateDelta().
noConnection()
static boolean de.dlr.ivf.tapas.mode.TPS_Mode.noConnection (double val) static
Method to check if the returned value is a "no connection". Inverse function is hasConnection.
Parameters
val the value to check
Returns
true if no connection is detected
Definition at line 187 of file TPS_Mode.java.
References de.dlr.ivf.tapas.mode.TPS_Mode.NO_CONNECTION.
Referenced by de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree.applyExpertKnowledge(), de.dlr.ivf.tapas.modechoice.TPS_UtilityMNL.getDistributionSet(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.getModeLogSum(), and de.dlr.ivf.tapas.mode.TPS_MassTransportMode.getTravelTime().
setAttribute()
void de.dlr.ivf.tapas.mode.TPS_Mode.setAttribute (ModeType attribute) private
Sets mode type attribute
Parameters
attribute mode type like BIKE, MIT etc., see ModeType
Definition at line 219 of file TPS_Mode.java.
References de.dlr.ivf.tapas.util.parameters.ParamValue.BIKE_COST_PER_KM, de.dlr.ivf.tapas.util.parameters.ParamValue.BIKE_COST_PER_KM_BASE, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_TT_BIKE_BASE, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_TT_MIT_BASE, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_TT_PT_BASE, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_TT_WALK_BASE, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getDoubleValue(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isDefined(), de.dlr.ivf.tapas.util.parameters.ParamValue.MIT_GASOLINE_COST_PER_KM, de.dlr.ivf.tapas.util.parameters.ParamValue.MIT_GASOLINE_COST_PER_KM_BASE, de.dlr.ivf.tapas.util.parameters.ParamValue.MIT_VARIABLE_COST_PER_KM, de.dlr.ivf.tapas.util.parameters.ParamValue.MIT_VARIABLE_COST_PER_KM_BASE, de.dlr.ivf.tapas.util.parameters.ParamValue.PASS_COST_PER_KM, de.dlr.ivf.tapas.util.parameters.ParamValue.PASS_COST_PER_KM_BASE, de.dlr.ivf.tapas.util.parameters.ParamValue.PT_COST_PER_KM, de.dlr.ivf.tapas.util.parameters.ParamValue.PT_COST_PER_KM_BASE, de.dlr.ivf.tapas.util.parameters.ParamValue.TAXI_COST_PER_KM, de.dlr.ivf.tapas.util.parameters.ParamValue.TAXI_COST_PER_KM_BASE, de.dlr.ivf.tapas.util.parameters.ParamValue.TRAIN_COST_PER_KM, de.dlr.ivf.tapas.util.parameters.ParamValue.TRAIN_COST_PER_KM_BASE, de.dlr.ivf.tapas.util.parameters.ParamValue.VELOCITY_BIKE, de.dlr.ivf.tapas.util.parameters.ParamValue.VELOCITY_CAR, de.dlr.ivf.tapas.util.parameters.ParamValue.VELOCITY_FOOT, de.dlr.ivf.tapas.util.parameters.ParamValue.VELOCITY_TRAIN, de.dlr.ivf.tapas.util.parameters.ParamValue.WALK_COST_PER_KM, and de.dlr.ivf.tapas.util.parameters.ParamValue.WALK_COST_PER_KM_BASE.
setFix()
void de.dlr.ivf.tapas.mode.TPS_Mode.setFix (boolean isFix) private
Sets whether the mode is fix or can be changed.
Parameters
isFix boolean value for isFix
Definition at line 400 of file TPS_Mode.java.
setParameters()
void de.dlr.ivf.tapas.mode.TPS_Mode.setParameters (TPS_ParameterClass param)
This method sets the parameter class reference
Parameters
param parameter class reference
Definition at line 342 of file TPS_Mode.java.
toString()
String de.dlr.ivf.tapas.mode.TPS_Mode.toString (String prefix)
Definition at line 436 of file TPS_Mode.java.
Member Data Documentation
cost_per_km
double de.dlr.ivf.tapas.mode.TPS_Mode.cost_per_km = 0
Definition at line 56 of file TPS_Mode.java.
Referenced by de.dlr.ivf.tapas.TPS_Main.updateCosts().
cost_per_km_base
double de.dlr.ivf.tapas.mode.TPS_Mode.cost_per_km_base = 0
Definition at line 57 of file TPS_Mode.java.
Referenced by de.dlr.ivf.tapas.TPS_Main.updateCosts().
isFix
boolean de.dlr.ivf.tapas.mode.TPS_Mode.isFix private
This flag determines whether the choice for this mode has to be fix or not, i.e. when I decide to drive to work by car then I have to take it back home too (fix = true). If I go to work by taxi then I can take the bus to go home (fix = false).
Definition at line 72 of file TPS_Mode.java.
Referenced by de.dlr.ivf.tapas.mode.TPS_ExtMode.isFix(), de.dlr.ivf.tapas.mode.TPS_IndividualTransportMode.TPS_IndividualTransportMode(), and de.dlr.ivf.tapas.mode.TPS_NonMotorisedMode.TPS_NonMotorisedMode().
map
final EnumMap<TPS_ModeCodeType, TPS_InternalConstant<TPS_ModeCodeType> > de.dlr.ivf.tapas.mode.TPS_Mode.map private
In this map all internal representation of this constant are stored
Definition at line 65 of file TPS_Mode.java.
MODE_MAP
final EnumMap<ModeType, TPS_Mode> de.dlr.ivf.tapas.mode.TPS_Mode.MODE_MAP = new EnumMap<>(ModeType.class) static private
Map stores all modes indexed by their mode type
Definition at line 50 of file TPS_Mode.java.
MODE_TYPE_ARRAY
ModeType [] de.dlr.ivf.tapas.mode.TPS_Mode.MODE_TYPE_ARRAY = new ModeType[]{ModeType.WALK, ModeType.BIKE, ModeType.MIT, ModeType.MIT_PASS, ModeType.TAXI, ModeType.PT, ModeType.TRAIN} static
Definition at line 44 of file TPS_Mode.java.
Referenced by de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree.applyExpertKnowledge(), de.dlr.ivf.tapas.mode.TPS_ModeDistribution.getDistribution(), de.dlr.ivf.tapas.modechoice.TPS_UtilityMNL.getDistributionSet(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.getModeLogSum(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessMode.getTravelTime(), de.dlr.ivf.tapas.loc.TPS_SelectWithSingleAccessMode.getTravelTime(), and de.dlr.ivf.tapas.iteration.TPS_VisumConverter.writeODMatrices().
modeType
ModeType de.dlr.ivf.tapas.mode.TPS_Mode.modeType private
type (Name) of the mode
Definition at line 76 of file TPS_Mode.java.
name
final String de.dlr.ivf.tapas.mode.TPS_Mode.name private
Definition at line 66 of file TPS_Mode.java.
Referenced by de.dlr.ivf.tapas.mode.TPS_IndividualTransportMode.TPS_IndividualTransportMode(), and de.dlr.ivf.tapas.mode.TPS_NonMotorisedMode.TPS_NonMotorisedMode().
NO_CONNECTION
double de.dlr.ivf.tapas.mode.TPS_Mode.NO_CONNECTION = -1 static
Definition at line 45 of file TPS_Mode.java.
Referenced by de.dlr.ivf.scripts.OTP2SQLMatrix.checkDBMatrix(), de.dlr.ivf.tapas.mode.TPS_IndividualTransportMode.getTravelTime(), de.dlr.ivf.tapas.mode.TPS_MassTransportMode.getTravelTime(), de.dlr.ivf.tapas.mode.TPS_Mode.hasConnection(), de.dlr.ivf.tapas.mode.TPS_Mode.noConnection(), and de.dlr.ivf.scripts.OTP2SQLMatrix.readCSVFile().
parameterClass
TPS_ParameterClass de.dlr.ivf.tapas.mode.TPS_Mode.parameterClass private
Definition at line 61 of file TPS_Mode.java.
Referenced by de.dlr.ivf.tapas.mode.TPS_IndividualTransportMode.TPS_IndividualTransportMode(), and de.dlr.ivf.tapas.mode.TPS_NonMotorisedMode.TPS_NonMotorisedMode().
useBase
boolean de.dlr.ivf.tapas.mode.TPS_Mode.useBase = false
Definition at line 60 of file TPS_Mode.java.
Referenced by de.dlr.ivf.tapas.TPS_Main.updateCosts().
UTILITY_FUNCTION
TPS_UtilityFunction de.dlr.ivf.tapas.mode.TPS_Mode.UTILITY_FUNCTION = null static private
Instance to the utility function
Definition at line 54 of file TPS_Mode.java.
Referenced by de.dlr.ivf.tapas.mode.TPS_Mode.getUtilityFunction(), and de.dlr.ivf.tapas.mode.TPS_Mode.initUtilityFunction().
variable_cost_per_km
double de.dlr.ivf.tapas.mode.TPS_Mode.variable_cost_per_km = 0
Definition at line 58 of file TPS_Mode.java.
Referenced by de.dlr.ivf.tapas.TPS_Main.updateCosts().
variable_cost_per_km_base
double de.dlr.ivf.tapas.mode.TPS_Mode.variable_cost_per_km_base = 0
Definition at line 59 of file TPS_Mode.java.
Referenced by de.dlr.ivf.tapas.TPS_Main.updateCosts().
velocity
ParamValue de.dlr.ivf.tapas.mode.TPS_Mode.velocity = null
Definition at line 55 of file TPS_Mode.java.
Referenced by de.dlr.ivf.tapas.TPS_Main.updateCosts().
VISUM_NO_CONNECTION
double de.dlr.ivf.tapas.mode.TPS_Mode.VISUM_NO_CONNECTION = 99999.0 static
Definition at line 46 of file TPS_Mode.java.
Referenced by de.dlr.ivf.scripts.OTP2SQLMatrix.checkDBMatrix(), and de.dlr.ivf.scripts.OTP2SQLMatrix.fixMissing().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/mode/TPS_Mode.java