TAPAS: de.dlr.ivf.tapas.runtime.server.SimulationServer Class Reference
de.dlr.ivf.tapas.runtime.server.SimulationServer Class Reference
Classes
class RunWhenShuttingDown
class SimulationServerUpdateTask
Public Member Functions
TPS_ParameterClass getParameters ()
void run ()
Static Public Member Functions
static void main (String[] args) throws Exception
Private Member Functions
SimulationServer (InetAddress simulationServerIPAddress, File tapasNetworkDirectory) throws SQLException, IOException, ClassNotFoundException
boolean checkAndReestablishCon (Object caller) throws SQLException
void killProcess (String pid) throws IOException
Private Attributes
final TPS_DB_Connector dbConnector
final InetAddress simulationServerIPAddress
final File runtimeFile
final Timer timer
volatile boolean keepOn = true
Static Private Attributes
static final String sysoutPrefix = "-- Server -- "
static final TPS_ArgumentType<?>[] PARAMETERS
static String hostname
static String hashcode
static volatile boolean shuttingDown = false
static volatile boolean shutdown = false
Detailed Description
The main method of this class is used to setup a TAPAS remote server. Each machine which is registered in the database in the public.sim_servers table and where the server is running there can be remote simulations for tapas started.
Author
mark_ma
Definition at line 46 of file SimulationServer.java.
Constructor & Destructor Documentation
SimulationServer()
de.dlr.ivf.tapas.runtime.server.SimulationServer.SimulationServer (InetAddress simulationServerIPAddress, File tapasNetworkDirectory) throws SQLException, IOException, ClassNotFoundException private
The constructor setup the remote server, binds the remote object and starts the update task
Parameters
simulationServerIPAddress IP address of the current network adapter
tapasNetworkDirectory tapas network directory path
Exceptions
SQLException This exception is thrown if a connection to the database could not be established.
ClassNotFoundException This exception is thrown if the driver for the database was not found.
Definition at line 104 of file SimulationServer.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_PROCESSES, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_SERVERS, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), de.dlr.ivf.tapas.util.parameters.ParamString.FILE_WORKING_DIRECTORY, de.dlr.ivf.tapas.util.Checksum.generateFileChecksum(), de.dlr.ivf.tapas.runtime.util.DaemonControlProperties.get(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.runtime.server.SimulationServer.hashcode, de.dlr.ivf.tapas.runtime.server.SimulationServer.hostname, de.dlr.ivf.tapas.runtime.server.SimulationServer.killProcess(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.loadRuntimeParameters(), de.dlr.ivf.tapas.runtime.util.DaemonControlProperties.DaemonControlPropKey.LOGIN_CONFIG, de.dlr.ivf.tapas.runtime.util.DaemonControlProperties.set(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.setString(), de.dlr.ivf.tapas.util.Checksum.HashType.SHA512, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.SIM_DIR, de.dlr.ivf.tapas.runtime.server.SimulationServer.simulationServerIPAddress, and de.dlr.ivf.tapas.runtime.server.SimulationServer.sysoutPrefix.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationServer.main().
Member Function Documentation
checkAndReestablishCon()
boolean de.dlr.ivf.tapas.runtime.server.SimulationServer.checkAndReestablishCon (Object caller) throws SQLException private
Definition at line 199 of file SimulationServer.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection().
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationServer.SimulationServerUpdateTask.SimulationServerUpdateTask().
getParameters()
TPS_ParameterClass de.dlr.ivf.tapas.runtime.server.SimulationServer.getParameters ()
Definition at line 208 of file SimulationServer.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getParameters().
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationServer.run(), de.dlr.ivf.tapas.runtime.server.SimulationServer.SimulationServerUpdateTask.run(), de.dlr.ivf.tapas.runtime.server.SimulationServer.RunWhenShuttingDown.run(), and de.dlr.ivf.tapas.runtime.server.SimulationServer.SimulationServerUpdateTask.SimulationServerUpdateTask().
killProcess()
void de.dlr.ivf.tapas.runtime.server.SimulationServer.killProcess (String pid) throws IOException private
Forcibly kills a process by its PID
Parameters
pid the process identification
Exceptions
IOException if an I/O error occurs
Definition at line 218 of file SimulationServer.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationServer.SimulationServer().
main()
static void de.dlr.ivf.tapas.runtime.server.SimulationServer.main (String[] args) throws Exception static
This main method checks all parameters and then setup a remote server for TAPAS simulations
Parameters
args args[0]: tapas network directory path
Exceptions
Exception this exception is thrown when the server couldn't be setup
Definition at line 180 of file SimulationServer.java.
References de.dlr.ivf.tapas.util.TPS_Argument.checkArguments(), de.dlr.ivf.tapas.runtime.util.IPInfo.getEthernetInetAddress(), de.dlr.ivf.tapas.runtime.util.IPInfo.getHostname(), de.dlr.ivf.tapas.runtime.server.SimulationServer.hostname, de.dlr.ivf.tapas.runtime.server.SimulationServer.PARAMETERS, de.dlr.ivf.tapas.runtime.server.SimulationServer.SimulationServer(), and de.dlr.ivf.tapas.runtime.server.SimulationServer.sysoutPrefix.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationDaemon.main(), and de.dlr.ivf.tapas.runtime.server.SimulationServer.run().
run()
void de.dlr.ivf.tapas.runtime.server.SimulationServer.run ()
Definition at line 230 of file SimulationServer.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_SIMULATIONS, de.dlr.ivf.tapas.runtime.server.SimulationServer.dbConnector, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), de.dlr.ivf.tapas.runtime.util.IPInfo.getEthernetInetAddress(), de.dlr.ivf.tapas.runtime.server.SimulationServer.getParameters(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.runtime.server.SimulationServer.hostname, de.dlr.ivf.tapas.runtime.server.SimulationServer.keepOn, de.dlr.ivf.tapas.runtime.server.SimulationServer.main(), de.dlr.ivf.tapas.runtime.server.SimulationServer.runtimeFile, de.dlr.ivf.tapas.TPS_Main.TPS_State.setFinished(), de.dlr.ivf.tapas.runtime.server.SimulationServer.shuttingDown, de.dlr.ivf.tapas.TPS_Main.STATE, and de.dlr.ivf.tapas.runtime.server.SimulationServer.sysoutPrefix.
Member Data Documentation
dbConnector
final TPS_DB_Connector de.dlr.ivf.tapas.runtime.server.SimulationServer.dbConnector private
The reference to the connection manager, needed to reestablish the connection, if necessary
Definition at line 81 of file SimulationServer.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationServer.run(), de.dlr.ivf.tapas.runtime.server.SimulationServer.SimulationServerUpdateTask.run(), de.dlr.ivf.tapas.runtime.server.SimulationServer.RunWhenShuttingDown.run(), and de.dlr.ivf.tapas.runtime.server.SimulationServer.SimulationServerUpdateTask.SimulationServerUpdateTask().
hashcode
String de.dlr.ivf.tapas.runtime.server.SimulationServer.hashcode static private
contains the generated sha512 hash of the servers jar file
Definition at line 67 of file SimulationServer.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationServer.SimulationServer().
hostname
String de.dlr.ivf.tapas.runtime.server.SimulationServer.hostname static private
the hostname extracted by IPInfo#getHostname()
Definition at line 62 of file SimulationServer.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationServer.main(), de.dlr.ivf.tapas.runtime.server.SimulationServer.run(), de.dlr.ivf.tapas.runtime.server.SimulationServer.SimulationServerUpdateTask.run(), de.dlr.ivf.tapas.runtime.server.SimulationServer.RunWhenShuttingDown.run(), de.dlr.ivf.tapas.runtime.server.SimulationServer.SimulationServer(), and de.dlr.ivf.tapas.runtime.server.SimulationServer.SimulationServerUpdateTask.SimulationServerUpdateTask().
keepOn
volatile boolean de.dlr.ivf.tapas.runtime.server.SimulationServer.keepOn = true private
Definition at line 94 of file SimulationServer.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationServer.run(), and de.dlr.ivf.tapas.runtime.server.SimulationServer.RunWhenShuttingDown.run().
PARAMETERS
final TPS_ArgumentType<?> [] de.dlr.ivf.tapas.runtime.server.SimulationServer.PARAMETERS static private
Initial value:
= {new TPS_ArgumentType<>("tapas network directory path",
            File.class)}
Parameter array with all parameters for this main method.
PARAMETERS[0] = tapas network directory path
Definition at line 56 of file SimulationServer.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationServer.main().
runtimeFile
final File de.dlr.ivf.tapas.runtime.server.SimulationServer.runtimeFile private
runtime file including the user credentials
Definition at line 89 of file SimulationServer.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationServer.run().
shutdown
volatile boolean de.dlr.ivf.tapas.runtime.server.SimulationServer.shutdown = false static private
Prevent RunWhenShuttingDown#run() from being executed twice when shutting down a server from the GUI. {@link #killServer()} invokes the RunWhenShuttingDown#run() procedure, which, when it returns, lets the main(String[]) finish. As RunWhenShuttingDown also being a ShutDownHook it will be invoked when main(String[]) finishes.
Definition at line 77 of file SimulationServer.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationServer.SimulationServerUpdateTask.run(), and de.dlr.ivf.tapas.runtime.server.SimulationServer.RunWhenShuttingDown.run().
shuttingDown
volatile boolean de.dlr.ivf.tapas.runtime.server.SimulationServer.shuttingDown = false static private
this will block the main method to finish before the shutdown procedure is fully executed
Definition at line 71 of file SimulationServer.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationServer.run(), de.dlr.ivf.tapas.runtime.server.SimulationServer.SimulationServerUpdateTask.run(), and de.dlr.ivf.tapas.runtime.server.SimulationServer.RunWhenShuttingDown.run().
simulationServerIPAddress
final InetAddress de.dlr.ivf.tapas.runtime.server.SimulationServer.simulationServerIPAddress private
IP Address of this SimulationServer
Definition at line 85 of file SimulationServer.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationServer.SimulationServer(), and de.dlr.ivf.tapas.runtime.server.SimulationServer.SimulationServerUpdateTask.SimulationServerUpdateTask().
sysoutPrefix
final String de.dlr.ivf.tapas.runtime.server.SimulationServer.sysoutPrefix = "-- Server -- " static private
Identifying String for the command line output
Definition at line 51 of file SimulationServer.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationServer.main(), de.dlr.ivf.tapas.runtime.server.SimulationServer.run(), de.dlr.ivf.tapas.runtime.server.SimulationServer.RunWhenShuttingDown.run(), and de.dlr.ivf.tapas.runtime.server.SimulationServer.SimulationServer().
timer
final Timer de.dlr.ivf.tapas.runtime.server.SimulationServer.timer private
Timer for the SimulationServerUpdateTask task
Definition at line 93 of file SimulationServer.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationServer.RunWhenShuttingDown.run().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/runtime/server/SimulationServer.java