TAPAS: de.dlr.ivf.tapas.tools.riesel.AddressPojo Class Reference
de.dlr.ivf.tapas.tools.riesel.AddressPojo Class Reference
Public Member Functions
AddressPojo (long key, int inhabitants)
int getInhabitants ()
void setInhabitants (int inhabitants)
long getKey ()
void setKey (int key)
void incInhabitants ()
Static Public Attributes
static AddressPojo POISON_ELEMENT = new AddressPojo(-1, -1)
Private Attributes
long key
int inhabitants
Detailed Description
Definition at line 11 of file AddressPojo.java.
Constructor & Destructor Documentation
AddressPojo()
de.dlr.ivf.tapas.tools.riesel.AddressPojo.AddressPojo (long key, int inhabitants)
Definition at line 18 of file AddressPojo.java.
References de.dlr.ivf.tapas.tools.riesel.AddressPojo.inhabitants, and de.dlr.ivf.tapas.tools.riesel.AddressPojo.key.
Member Function Documentation
getInhabitants()
int de.dlr.ivf.tapas.tools.riesel.AddressPojo.getInhabitants ()
Definition at line 24 of file AddressPojo.java.
References de.dlr.ivf.tapas.tools.riesel.AddressPojo.inhabitants.
Referenced by de.dlr.ivf.tapas.tools.riesel.UpdateAddressesWorker.addToBatch(), and de.dlr.ivf.tapas.tools.riesel.SimpleCollectorWriter.run().
getKey()
long de.dlr.ivf.tapas.tools.riesel.AddressPojo.getKey ()
Definition at line 32 of file AddressPojo.java.
References de.dlr.ivf.tapas.tools.riesel.AddressPojo.key.
Referenced by de.dlr.ivf.tapas.tools.riesel.UpdateAddressesWorker.addToBatch(), and de.dlr.ivf.tapas.tools.riesel.SimpleCollectorWriter.run().
incInhabitants()
void de.dlr.ivf.tapas.tools.riesel.AddressPojo.incInhabitants ()
Definition at line 40 of file AddressPojo.java.
setInhabitants()
void de.dlr.ivf.tapas.tools.riesel.AddressPojo.setInhabitants (int inhabitants)
Definition at line 28 of file AddressPojo.java.
References de.dlr.ivf.tapas.tools.riesel.AddressPojo.inhabitants.
setKey()
void de.dlr.ivf.tapas.tools.riesel.AddressPojo.setKey (int key)
Definition at line 36 of file AddressPojo.java.
References de.dlr.ivf.tapas.tools.riesel.AddressPojo.key.
Member Data Documentation
inhabitants
int de.dlr.ivf.tapas.tools.riesel.AddressPojo.inhabitants private
Definition at line 16 of file AddressPojo.java.
Referenced by de.dlr.ivf.tapas.tools.riesel.AddressPojo.AddressPojo(), de.dlr.ivf.tapas.tools.riesel.AddressPojo.getInhabitants(), and de.dlr.ivf.tapas.tools.riesel.AddressPojo.setInhabitants().
key
long de.dlr.ivf.tapas.tools.riesel.AddressPojo.key private
Definition at line 15 of file AddressPojo.java.
Referenced by de.dlr.ivf.tapas.tools.riesel.AddressPojo.AddressPojo(), de.dlr.ivf.tapas.tools.riesel.AddressPojo.getKey(), and de.dlr.ivf.tapas.tools.riesel.AddressPojo.setKey().
POISON_ELEMENT
AddressPojo de.dlr.ivf.tapas.tools.riesel.AddressPojo.POISON_ELEMENT = new AddressPojo(-1, -1) static
Definition at line 13 of file AddressPojo.java.
Referenced by de.dlr.ivf.tapas.tools.riesel.SimpleCollector.run(), de.dlr.ivf.tapas.tools.riesel.SimpleCollectorWriter.run(), de.dlr.ivf.tapas.tools.riesel.UpdateAddressesWorker.run(), and de.dlr.ivf.tapas.tools.riesel.RieselTool.updateAll().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/riesel/AddressPojo.java