TAPAS: de.dlr.ivf.tapas.tools.riesel.SimpleCollector Class Reference
de.dlr.ivf.tapas.tools.riesel.SimpleCollector Class Reference
Classes
class EWZPojo
Public Member Functions
SimpleCollector (TPS_DB_Connector dbCon, String outputFilePath) throws IOException
void run ()
Static Public Member Functions
static void main (String[] args) throws IOException, ClassNotFoundException
Private Member Functions
List< AddressPojo > distributeInhabitants (ArrayList< Integer > addresses, long inh)
ArrayList< Integer > getAddresses (EWZPojo ewz) throws SQLException
List< EWZPojo > getGeometries () throws SQLException
Private Attributes
final TPS_DB_Connector dbCon
final ArrayBlockingQueue< AddressPojo > queue
final SimpleCollectorWriter writer
Static Private Attributes
static final int QUEUE_SIZE = 10000
Detailed Description
This class distributes a given number of inhabitants on addresses found within the geometries.
It distributes them equally among all addresses found.
Hence it is only useful for relatively small geometries with little diversity.
Author
boec_pa
Definition at line 29 of file SimpleCollector.java.
Constructor & Destructor Documentation
SimpleCollector()
de.dlr.ivf.tapas.tools.riesel.SimpleCollector.SimpleCollector (TPS_DB_Connector dbCon, String outputFilePath) throws IOException
Definition at line 39 of file SimpleCollector.java.
References de.dlr.ivf.tapas.tools.riesel.SimpleCollector.dbCon, de.dlr.ivf.tapas.tools.riesel.SimpleCollector.queue, de.dlr.ivf.tapas.tools.riesel.SimpleCollector.QUEUE_SIZE, and de.dlr.ivf.tapas.tools.riesel.SimpleCollector.writer.
Referenced by de.dlr.ivf.tapas.tools.riesel.SimpleCollector.main().
Member Function Documentation
distributeInhabitants()
List<AddressPojo> de.dlr.ivf.tapas.tools.riesel.SimpleCollector.distributeInhabitants (ArrayList< Integer > addresses, long inh) private
Definition at line 63 of file SimpleCollector.java.
Referenced by de.dlr.ivf.tapas.tools.riesel.SimpleCollector.run().
getAddresses()
ArrayList<Integer> de.dlr.ivf.tapas.tools.riesel.SimpleCollector.getAddresses (EWZPojo ewz) throws SQLException private
Definition at line 78 of file SimpleCollector.java.
References de.dlr.ivf.tapas.tools.riesel.SimpleCollector.dbCon, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery().
Referenced by de.dlr.ivf.tapas.tools.riesel.SimpleCollector.run().
getGeometries()
List<EWZPojo> de.dlr.ivf.tapas.tools.riesel.SimpleCollector.getGeometries () throws SQLException private
Definition at line 95 of file SimpleCollector.java.
References de.dlr.ivf.tapas.tools.riesel.SimpleCollector.dbCon, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery().
Referenced by de.dlr.ivf.tapas.tools.riesel.SimpleCollector.run().
main()
static void de.dlr.ivf.tapas.tools.riesel.SimpleCollector.main (String[] args) throws IOException, ClassNotFoundException static
Start here.
Definition at line 50 of file SimpleCollector.java.
References de.dlr.ivf.tapas.tools.riesel.SimpleCollector.dbCon, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.loadRuntimeParameters(), de.dlr.ivf.tapas.tools.riesel.SimpleCollector.run(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.setValue(), and de.dlr.ivf.tapas.tools.riesel.SimpleCollector.SimpleCollector().
run()
void de.dlr.ivf.tapas.tools.riesel.SimpleCollector.run ()
Definition at line 112 of file SimpleCollector.java.
References de.dlr.ivf.tapas.tools.riesel.SimpleCollector.distributeInhabitants(), de.dlr.ivf.tapas.tools.riesel.SimpleCollector.getAddresses(), de.dlr.ivf.tapas.tools.riesel.SimpleCollector.getGeometries(), de.dlr.ivf.tapas.tools.riesel.AddressPojo.POISON_ELEMENT, and de.dlr.ivf.tapas.tools.riesel.SimpleCollector.queue.
Referenced by de.dlr.ivf.tapas.tools.riesel.SimpleCollector.main().
Member Data Documentation
dbCon
final TPS_DB_Connector de.dlr.ivf.tapas.tools.riesel.SimpleCollector.dbCon private
Definition at line 33 of file SimpleCollector.java.
Referenced by de.dlr.ivf.tapas.tools.riesel.SimpleCollector.getAddresses(), de.dlr.ivf.tapas.tools.riesel.SimpleCollector.getGeometries(), de.dlr.ivf.tapas.tools.riesel.SimpleCollector.main(), and de.dlr.ivf.tapas.tools.riesel.SimpleCollector.SimpleCollector().
queue
final ArrayBlockingQueue<AddressPojo> de.dlr.ivf.tapas.tools.riesel.SimpleCollector.queue private
Definition at line 35 of file SimpleCollector.java.
Referenced by de.dlr.ivf.tapas.tools.riesel.SimpleCollector.run(), and de.dlr.ivf.tapas.tools.riesel.SimpleCollector.SimpleCollector().
QUEUE_SIZE
final int de.dlr.ivf.tapas.tools.riesel.SimpleCollector.QUEUE_SIZE = 10000 static private
Definition at line 31 of file SimpleCollector.java.
Referenced by de.dlr.ivf.tapas.tools.riesel.SimpleCollector.SimpleCollector().
writer
final SimpleCollectorWriter de.dlr.ivf.tapas.tools.riesel.SimpleCollector.writer private
Definition at line 37 of file SimpleCollector.java.
Referenced by de.dlr.ivf.tapas.tools.riesel.SimpleCollector.SimpleCollector().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/riesel/SimpleCollector.java