TAPAS: de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2 Class Reference
de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2 Class Reference
Classes
class Act2Loc
class Block
class BlockPTStop
class CFN4
class CFN4Index
class HouseHold
class Location
class ModeChoice
class Person
class Score
class TAZ
class TAZFee
class TAZIntraMITInfo
class TAZIntraPTInfo
Public Member Functions
boolean createRegion (String name)
boolean importAct2Loc (File file, String region)
boolean importBlock (File file, String region, boolean adoptIDs)
boolean importBlockNextPTStop (File file, String region, String name)
boolean importCFN4 (File file, String region)
boolean importCFN4Ind (File file, String region)
boolean importHH (File file, String region, String name, boolean adoptIDs)
boolean importIntraMIT (File file, String region, String name, boolean adoptIDs)
boolean importIntraPT (File file, String region, String name, boolean adoptIDs)
boolean importLocations (File file, String region, boolean adoptIDs)
boolean importMatrix (File file, String region, String name)
boolean importModeChoice (File file, String name)
boolean importPersons (File file, String region, String name)
boolean importScores (File file, String region, String type, String name, boolean adoptIDs)
boolean importTAZ (File file, String region, boolean useID)
boolean importTazFee (File file, String region, String name, boolean useID, boolean updateBBR)
boolean login (File loginInfo)
Protected Member Functions
void finalize ()
Detailed Description
Definition at line 22 of file DBImportV2.java.
Member Function Documentation
createRegion()
boolean de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.createRegion (String name)
Definition at line 26 of file DBImportV2.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection(), and name.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2GUI.createAndShowGui().
finalize()
void de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.finalize () protected
Definition at line 47 of file DBImportV2.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.closeConnections().
importAct2Loc()
boolean de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.importAct2Loc (File file, String region)
Definition at line 51 of file DBImportV2.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection().
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2GUI.createAndShowGui().
importBlock()
boolean de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.importBlock (File file, String region, boolean adoptIDs)
Definition at line 111 of file DBImportV2.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection().
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2GUI.createAndShowGui().
importBlockNextPTStop()
boolean de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.importBlockNextPTStop (File file, String region, String name)
Definition at line 174 of file DBImportV2.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection(), and name.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2GUI.createAndShowGui().
importCFN4()
boolean de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.importCFN4 (File file, String region)
Definition at line 221 of file DBImportV2.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection().
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2GUI.createAndShowGui().
importCFN4Ind()
boolean de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.importCFN4Ind (File file, String region)
Definition at line 281 of file DBImportV2.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection().
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2GUI.createAndShowGui().
importHH()
boolean de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.importHH (File file, String region, String name, boolean adoptIDs)
Definition at line 337 of file DBImportV2.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection(), and name.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2GUI.createAndShowGui().
importIntraMIT()
boolean de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.importIntraMIT (File file, String region, String name, boolean adoptIDs)
Definition at line 417 of file DBImportV2.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection(), and name.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2GUI.createAndShowGui().
importIntraPT()
boolean de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.importIntraPT (File file, String region, String name, boolean adoptIDs)
Definition at line 486 of file DBImportV2.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection(), and name.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2GUI.createAndShowGui().
importLocations()
boolean de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.importLocations (File file, String region, boolean adoptIDs)
Definition at line 553 of file DBImportV2.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection().
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2GUI.createAndShowGui().
importMatrix()
boolean de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.importMatrix (File file, String region, String name)
Definition at line 629 of file DBImportV2.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection(), and name.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2GUI.createAndShowGui().
importModeChoice()
boolean de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.importModeChoice (File file, String name)
Definition at line 682 of file DBImportV2.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ModeChoiceTreeConverter.map, and name.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2GUI.createAndShowGui().
importPersons()
boolean de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.importPersons (File file, String region, String name)
Definition at line 749 of file DBImportV2.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection(), and name.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2GUI.createAndShowGui().
importScores()
boolean de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.importScores (File file, String region, String type, String name, boolean adoptIDs)
Definition at line 863 of file DBImportV2.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection(), name, and type.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2GUI.createAndShowGui().
importTAZ()
boolean de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.importTAZ (File file, String region, boolean useID)
Definition at line 925 of file DBImportV2.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection().
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2GUI.createAndShowGui().
importTazFee()
boolean de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.importTazFee (File file, String region, String name, boolean useID, boolean updateBBR)
Definition at line 985 of file DBImportV2.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection(), and name.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2GUI.createAndShowGui().
login()
boolean de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.login (File loginInfo)
Definition at line 1083 of file DBImportV2.java.
References de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.loadRuntimeParameters().
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2GUI.createAndShowGui().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/persitence/db/dbImport/DBImportV2.java