TAPAS: de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportController Class Reference
de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportController Class Reference
Classes
enum DBImportMethod
Public Member Functions
DBImportController (DBImportGUI control)
void dbimport (final JTable fileTable)
Static Private Member Functions
static List< ParamString > getList (ParamString... fileKeyArray)
Private Attributes
final DBImportGUI control
Detailed Description
Definition at line 26 of file DBImportController.java.
Constructor & Destructor Documentation
DBImportController()
de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportController.DBImportController (DBImportGUI control)
Definition at line 191 of file DBImportController.java.
References de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportController.control.
Member Function Documentation
dbimport()
void de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportController.dbimport (final JTable fileTable)
Definition at line 199 of file DBImportController.java.
References de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.activateStart(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.closeConnection(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportController.control, de.dlr.ivf.tapas.util.parameters.ParamString.DB_SCHEMA_CORE, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.handleException(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.INPUT_DIR, name, de.dlr.ivf.tapas.util.parameters.ParamString.PATH_ABS_DB, de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.print(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.repaint(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.resetCursor(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.setCursor(), and de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.setString().
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportGUI.createAndShowGui().
getList()
static List<ParamString> de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportController.getList (ParamString... fileKeyArray) static private
Definition at line 195 of file DBImportController.java.
Member Data Documentation
control
final DBImportGUI de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportController.control private
Definition at line 189 of file DBImportController.java.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportController.dbimport(), and de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportController.DBImportController().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/persitence/db/dbImport/DBImportController.java