TAPAS: de.dlr.ivf.tapas.mode.TPS_MassTransportMode Class Reference
de.dlr.ivf.tapas.mode.TPS_MassTransportMode Class Reference
Public Member Functions
TPS_MassTransportMode (String name, String[] attributes, boolean isFix, TPS_ParameterClass parameterClass)
double getDistance (Locatable start, Locatable end, SimulationType simType, TPS_Car car)
double getInterchanges (Locatable start, Locatable end, int time, SimulationType simType)
double getTravelTime (Locatable start, Locatable end, int time, SimulationType simType, TPS_ActivityConstant actCodeFrom, TPS_ActivityConstant actCodeTo, TPS_Person person, TPS_Car car)
Public Member Functions inherited from de.dlr.ivf.tapas.mode.TPS_Mode
void addModeToMap ()
ModeType getAttribute ()
int getCode (TPS_ModeCodeType type)
double getCost_per_km (SimulationType simType)
ModeType getModeType ()
String getName ()
TPS_ParameterClass getParameters ()
void setParameters (TPS_ParameterClass param)
double getVariableCost_per_km (SimulationType simType)
ParamValue getVelocity ()
boolean isFix ()
boolean isType (ModeType... type)
boolean isType (ModeType type)
boolean isUseBase ()
String toString (String prefix)
Private Member Functions
int getScore (TPS_Block block)
int getScore (TPS_TrafficAnalysisZone taz)
Additional Inherited Members
Static Public Member Functions inherited from de.dlr.ivf.tapas.mode.TPS_Mode
static void clearModeMap ()
static TPS_Mode get (ModeType key)
static Collection< TPS_Mode > getConstants ()
static TPS_UtilityFunction getUtilityFunction (TPS_ParameterClass parameterClass)
static boolean hasConnection (double val)
static void initUtilityFunction (TPS_ParameterClass parameterClass)
static boolean noConnection (double val)
Public Attributes inherited from de.dlr.ivf.tapas.mode.TPS_Mode
ParamValue velocity = null
double cost_per_km = 0
double cost_per_km_base = 0
double variable_cost_per_km = 0
double variable_cost_per_km_base = 0
boolean useBase = false
Static Public Attributes inherited from de.dlr.ivf.tapas.mode.TPS_Mode
static ModeType[] MODE_TYPE_ARRAY = new ModeType[]{ModeType.WALK, ModeType.BIKE, ModeType.MIT, ModeType.MIT_PASS, ModeType.TAXI, ModeType.PT, ModeType.TRAIN}
static double NO_CONNECTION = -1
static double VISUM_NO_CONNECTION = 99999.0
Protected Member Functions inherited from de.dlr.ivf.tapas.mode.TPS_Mode
TPS_Mode (String name, String[] attributes, boolean isFix, TPS_ParameterClass parameterClass)
Detailed Description
This class represents modes 'pubtrans' and 'train'
Author
mark_ma
Definition at line 34 of file TPS_MassTransportMode.java.
Constructor & Destructor Documentation
TPS_MassTransportMode()
de.dlr.ivf.tapas.mode.TPS_MassTransportMode.TPS_MassTransportMode (String name, String[] attributes, boolean isFix, TPS_ParameterClass parameterClass)
Calls super constructor with name
Parameters
name
parameterClass parameter class reference
Definition at line 42 of file TPS_MassTransportMode.java.
References name.
Member Function Documentation
getDistance()
double de.dlr.ivf.tapas.mode.TPS_MassTransportMode.getDistance (Locatable start, Locatable end, SimulationType simType, TPS_Car car)
This method calculates the real distance between two locations.
Parameters
start location, where this trip starts
end location, where this trip ends
simType Type of simulation (Base/Scenario)
car The car for this trip, if available. Set it to null, if no car is used
Returns
calculated distance in meter
Reimplemented from de.dlr.ivf.tapas.mode.TPS_Mode.
Definition at line 53 of file TPS_MassTransportMode.java.
References de.dlr.ivf.tapas.util.parameters.ParamMatrix.DISTANCES_PT, de.dlr.ivf.tapas.util.TPS_Geometrics.getDistance(), de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.getTAZId(), de.dlr.ivf.tapas.loc.Locatable.getTrafficAnalysisZone(), and de.dlr.ivf.tapas.util.parameters.ParamValue.MIN_DIST.
getInterchanges()
double de.dlr.ivf.tapas.mode.TPS_MassTransportMode.getInterchanges (Locatable start, Locatable end, int time, SimulationType simType)
Method to return the average numbers of interchanges between two locations. The number is a double, because multiple pt-routes might have different numbers of interchanges.
Parameters
start The starting location
end The destination location
time The starting time for this trip
simType Scenario or base
Returns
the average number of interchanges of these two locations
Definition at line 75 of file TPS_MassTransportMode.java.
References de.dlr.ivf.tapas.loc.Locatable.getTAZId(), de.dlr.ivf.tapas.util.parameters.ParamMatrixMap.INTERCHANGES_PT, and de.dlr.ivf.tapas.util.parameters.ParamMatrixMap.TRAVEL_TIME_PT.
getScore() [1/2]
int de.dlr.ivf.tapas.mode.TPS_MassTransportMode.getScore (TPS_Block block) private
Returns the pt quality score of the block; if no score is known, the score of the traffic zone is used
Parameters
block the block the score is to be looked up for
Returns
the score
Definition at line 92 of file TPS_MassTransportMode.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.DEBUG, de.dlr.ivf.tapas.util.parameters.ParamValue.DEFAULT_BLOCK_SCORE, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_USE_BLOCK_LEVEL, de.dlr.ivf.tapas.loc.TPS_Block.getScoreCat(), de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), and de.dlr.ivf.tapas.log.TPS_Logger.log().
getScore() [2/2]
int de.dlr.ivf.tapas.mode.TPS_MassTransportMode.getScore (TPS_TrafficAnalysisZone taz) private
Returns the pt quality score of the traffic analysis zone
Parameters
taz the traffic analysis zone
Returns
the score
Definition at line 113 of file TPS_MassTransportMode.java.
References de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.getScoreCat().
getTravelTime()
double de.dlr.ivf.tapas.mode.TPS_MassTransportMode.getTravelTime (Locatable start, Locatable end, int time, SimulationType simType, TPS_ActivityConstant actCodeFrom, TPS_ActivityConstant actCodeTo, TPS_Person person, TPS_Car car)
This method calculates the travel time between two locations.
Parameters
start location, where this trip starts
end location, where this trip ends
time departure time of the trip in seconds after midnight
simType simulation type
actCodeFrom activity code of the earlier episode
actCodeTo activity code of the later episode
person reference to the person on this trip
Returns
travel time in seconds
Reimplemented from de.dlr.ivf.tapas.mode.TPS_Mode.
Definition at line 123 of file TPS_MassTransportMode.java.
References de.dlr.ivf.tapas.util.parameters.ParamMatrixMap.ARRIVAL_PT, de.dlr.ivf.tapas.util.parameters.ParamValue.AVERAGE_DISTANCE_PT_STOP, de.dlr.ivf.tapas.util.parameters.ParamMatrixMap.AVERAGE_SPEED_SCHOOLBUS, de.dlr.ivf.tapas.util.parameters.SimulationType.BASE, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_ACCESS_PT, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_ACCESS_PT_BASE, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_EGRESS_PT, de.dlr.ivf.tapas.util.parameters.ParamString.DB_NAME_MATRIX_EGRESS_PT_BASE, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.DEBUG, de.dlr.ivf.tapas.util.parameters.ParamValue.DEFAULT_SCHOOL_BUS_ACCESS, de.dlr.ivf.tapas.util.parameters.ParamValue.DEFAULT_SCHOOL_BUS_EGRESS, de.dlr.ivf.tapas.util.parameters.ParamValue.DEFAULT_SCHOOL_BUS_WAIT, de.dlr.ivf.tapas.util.parameters.ParamMatrix.DISTANCES_BL, de.dlr.ivf.tapas.util.parameters.ParamMatrixMap.EGRESS_PT, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_INTRA_INFOS_MATRIX, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_USE_BLOCK_LEVEL, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_USE_SCHOOLBUS, de.dlr.ivf.tapas.constants.TPS_SettlementSystem.TPS_SettlementSystemType.FORDCP, de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.getAverageSpeedPT(), de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.getBbrType(), de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.getBeelineFactorMIT(), de.dlr.ivf.tapas.loc.Locatable.getBlock(), de.dlr.ivf.tapas.constants.TPS_SettlementSystem.getCode(), de.dlr.ivf.tapas.util.TPS_Geometrics.getDistance(), de.dlr.ivf.tapas.loc.TPS_Block.getNearestPubTransStop(), de.dlr.ivf.tapas.person.TPS_Person.getPersGroup(), de.dlr.ivf.tapas.constants.TPS_PersonGroup.getPersType(), de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.getSimulationTypeValues(), de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.getTAZId(), de.dlr.ivf.tapas.loc.Locatable.getTrafficAnalysisZone(), de.dlr.ivf.tapas.constants.TPS_ActivityConstant.hasAttribute(), de.dlr.ivf.tapas.loc.Locatable.hasBlock(), de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.isIntraPTTrafficAllowed(), de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.util.parameters.ParamValue.MIN_DIST, de.dlr.ivf.tapas.mode.TPS_Mode.NO_CONNECTION, de.dlr.ivf.tapas.mode.TPS_Mode.noConnection(), de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.PT, de.dlr.ivf.tapas.util.parameters.ParamValue.PT_ACCESS_FACTOR, de.dlr.ivf.tapas.util.parameters.ParamValue.PT_EGRESS_FACTOR, de.dlr.ivf.tapas.util.parameters.ParamValue.PT_TT_FACTOR, de.dlr.ivf.tapas.constants.TPS_PersonGroup.TPS_PersonType.PUPIL, de.dlr.ivf.tapas.util.parameters.SimulationType.SCENARIO, de.dlr.ivf.tapas.constants.TPS_ActivityConstant.TPS_ActivityConstantAttribute.SCHOOL, de.dlr.ivf.tapas.util.parameters.ParamMatrixMap.TRAVEL_TIME_PT, and de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.WALK.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/mode/TPS_MassTransportMode.java