TAPAS: de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector Class Reference
de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector Class Reference
Classes
enum DBUser
Public Member Functions
TPS_DB_Connector (String username, String password, TPS_ParameterClass parameterClass) throws UnknownHostException, ClassNotFoundException
TPS_DB_Connector (TPS_ParameterClass parameterClass) throws UnknownHostException, ClassNotFoundException
boolean checkConnection (Object caller)
void closeConnection (Object key) throws SQLException
void closeConnections ()
void commit (Connection c) throws SQLException
void execute (String query, Object caller)
ResultSet executeQuery (String query, Object caller)
int executeUpdate (String query, Object caller)
Connection getConnection (Object key) throws SQLException
TPS_ParameterClass getParameters ()
MatrixMap readMatrixMap (String matrixName, int sIndex, Object caller)
Matrix readMatrix (String matrixName, int sIndex, Object caller)
String readParameter (String simKey, String paramKey, Object caller)
void readRuntimeParametersFromDB (String simKey)
String readSingleParameter (String sim_key, String param_key)
int updateSingleParameter (String sim_key, String param_key, String paramValue)
Public Attributes
TPS_ParameterClass parameterClass
Private Member Functions
boolean isSqlConnectionError (SQLException e)
Connection openConnection () throws SQLException
Static Private Member Functions
static void checkProperties (TPS_ParameterClass parameterClass) throws ClassNotFoundException, UnknownHostException
static void checkProperty (ParamString key, TPS_ParameterClass parameterClass)
Private Attributes
String myUserName
String myUserPwd
final Map< Object, Connection > connections
Detailed Description
This class provides in general two services. After you built one instance you have one new client connected to the database. Then you can retrieve a connection corresponding to a special key value. This connection is always open. The second service is to close a connection.
Author
mark_ma
Definition at line 37 of file TPS_DB_Connector.java.
Constructor & Destructor Documentation
TPS_DB_Connector() [1/2]
de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.TPS_DB_Connector (String username, String password, TPS_ParameterClass parameterClass) throws UnknownHostException, ClassNotFoundException
The constructor has three parts. Fist of all the database properties are read from a file. Then these properties are checked if they have correct values. The connections are opened in the TPS_DB_Connector::getConnection(Object) routine.
Parameters
password
username
Exceptions
ClassNotFoundException This exception is thrown if the driver in ParamString.DB_DRIVER was not found
UnknownHostException This exception is thrown if the host in ParamString.DB_HOST was not found
Definition at line 61 of file TPS_DB_Connector.java.
TPS_DB_Connector() [2/2]
de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.TPS_DB_Connector (TPS_ParameterClass parameterClass) throws UnknownHostException, ClassNotFoundException
Definition at line 69 of file TPS_DB_Connector.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_PASSWORD, de.dlr.ivf.tapas.util.parameters.ParamString.DB_USER, and de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString().
Member Function Documentation
checkConnection()
boolean de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.checkConnection (Object caller)
This method checks if the connection is still alive.
Parameters
caller Caller object, which should be checked for connectivity.
Returns
Definition at line 128 of file TPS_DB_Connector.java.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationControl.SimulationServerDataUpdateTask.run(), and de.dlr.ivf.tapas.runtime.client.SimulationControl.SimulationDataUpdateTask.run().
checkProperties()
static void de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.checkProperties (TPS_ParameterClass parameterClass) throws ClassNotFoundException, UnknownHostException static private
This method checks all properties. It calls checkProperty(String key) for every key except the password key. Furthermore some property values are checked in detail, e.g. if the driver for the database exists, if the host exists or if the port has a correct integer value etc.
Exceptions
ClassNotFoundException This exception is thrown if the driver in ParamString.DB_DRIVER was not found
UnknownHostException This exception is thrown if the host in ParamString.DB_HOST was not found
IllegalArgumentException This exception is thrown if the port is outside the value range of [1,65534]
Definition at line 87 of file TPS_DB_Connector.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_DBNAME, de.dlr.ivf.tapas.util.parameters.ParamString.DB_DRIVER, de.dlr.ivf.tapas.util.parameters.ParamString.DB_HOST, de.dlr.ivf.tapas.util.parameters.ParamValue.DB_PORT, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TYPE, de.dlr.ivf.tapas.util.parameters.ParamValueClass.getIntValue(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), and de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.paramValueClass.
checkProperty()
static void de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.checkProperty (ParamString key, TPS_ParameterClass parameterClass) static private
This method checks, if the property value corresponding to the given key exists and has a correct value (i.e. a length greater than 0)
Parameters
key property key
Exceptions
NullPointerException This exception is thrown, when the property value is null or has a length of 0
Definition at line 115 of file TPS_DB_Connector.java.
References de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString().
closeConnection()
void de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.closeConnection (Object key) throws SQLException
Closes the database connection specified via the key
Parameters
key object key of the connection
Exceptions
SQLException Exception is thrown in case of an error trying to close the db connection
Definition at line 169 of file TPS_DB_Connector.java.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationControl.close(), de.dlr.ivf.scripts.SrVCalculator.closeConnection(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportController.dbimport(), and de.dlr.ivf.tapas.TPS_Main.TPS_Main().
closeConnections()
void de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.closeConnections ()
If a connection to a database exists this method tries to close it.
Definition at line 180 of file TPS_DB_Connector.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, and de.dlr.ivf.tapas.log.TPS_Logger.log().
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.close(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2GUI.createAndShowGui(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.finalize(), and de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.finalize().
commit()
void de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.commit (Connection c) throws SQLException
This method commits the db-changes if autocommit is disabled.
Parameters
c the connection to commit
Exceptions
SQLException any exception, e.g connection loss
Definition at line 196 of file TPS_DB_Connector.java.
execute()
void de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute (String query, Object caller)
This method does a sql-execute for the given string with the given calling class. Each calling class gets its own connection
Parameters
query The sql-query
caller the caller Object. If this Object made a call before, Its connection is reused. Otherwise a new connection is created.
Definition at line 206 of file TPS_DB_Connector.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, and de.dlr.ivf.tapas.log.TPS_Logger.log().
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationControl.addSimulation(), de.dlr.ivf.tapas.tools.TPS_PTScoreCalculator.calcScoresBlock(), de.dlr.ivf.tapas.tools.TPS_PTScoreCalculator.calcScoresTAZ(), de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.catMatchingCSVImport(), de.dlr.ivf.tapas.runtime.client.SimulationControl.changeSimulationDataState(), de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.changeSimulationStatus(), de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer.cleanUpDB(), de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer2017.cleanUpDB(), de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer_Zeitreihendatensatz.cleanUpDB(), de.dlr.ivf.tapas.tools.TPS_MainDiagonalLengthEstimator.createIntraTAZTable(), de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.createNewMatrixMap(), de.dlr.ivf.tapas.tools.TPS_CapacityAdjuster.createNewMinimalLocationTable(), de.dlr.ivf.scripts.GridResultsPreparator.createRamonaTripTable(), de.dlr.ivf.scripts.RamonaResultPreparator.createRamonaTripTable(), de.dlr.ivf.tapas.tools.TPS_FillLocationRepresentatives.createRepresentativesTable(), de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.createTable(), de.dlr.ivf.scripts.DiscoImporter.createTables(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportController.dbimport(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.deleteMatrix(), de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.emptyLocations(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.execute(), de.dlr.ivf.scripts.DiscoImporter.fillCars(), de.dlr.ivf.tapas.tools.TPS_MainDiagonalLengthEstimator.fillIntraTAZTable(), de.dlr.ivf.tapas.tools.TPS_CapacityScale.fillNewLocations(), de.dlr.ivf.scripts.DiscoImporter.findCarIDs(), de.dlr.ivf.tapas.tools.OpportunityDistribution.ImportDistributions.GeringfuegigBeschaeftigte.GeringfuegigBeschaeftigte(), de.dlr.ivf.tapas.tools.OpportunityDistribution.RefactorDistricts.main(), de.dlr.ivf.scripts.CarFleetAdjuster.makeModifiedFleet(), de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer.printDiariesSQLInserts(), de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer2017.printDiariesSQLInserts(), de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer_Zeitreihendatensatz.printDiariesSQLInserts(), de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer.printDistributionVectorSQLInserts(), de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer2017.printDistributionVectorSQLInserts(), de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer_Zeitreihendatensatz.printDistributionVectorSQLInserts(), de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer.printSchemeClassSQLInserts(), de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer2017.printSchemeClassSQLInserts(), de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer_Zeitreihendatensatz.printSchemeClassSQLInserts(), de.dlr.ivf.tapas.runtime.client.SimulationControl.removeServer(), de.dlr.ivf.tapas.runtime.client.SimulationControl.removeSimulation(), de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.resetSimulation(), de.dlr.ivf.tapas.runtime.server.SimulationServer.run(), de.dlr.ivf.tapas.runtime.server.SimulationServer.SimulationServerUpdateTask.run(), de.dlr.ivf.tapas.tools.TPS_PTBikeInterchangeMatrix.saveInterchangeMatrixInDB(), de.dlr.ivf.tapas.tools.TPS_PTCarInterchangeMatrix.saveInterchangeMatrixInDB(), de.dlr.ivf.tapas.tools.TPS_ParkAndRideRouter.saveInterchangeMatrixInDB(), de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.saveMatrices(), de.dlr.ivf.tapas.tools.TPS_SubnetMatrixIntegrator.saveMatrix(), de.dlr.ivf.scripts.InterCellTrafficImporter.saveMatrix(), de.dlr.ivf.tapas.tools.TPS_FeederCellManipulator.saveMatrixInDB(), de.dlr.ivf.tapas.tools.TPS_FillLocationRepresentatives.saveToDB(), de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.saveToDB(), de.dlr.ivf.tapas.runtime.server.SimulationServer.SimulationServer(), de.dlr.ivf.tapas.runtime.server.SimulationServer.SimulationServerUpdateTask.SimulationServerUpdateTask(), de.dlr.ivf.tapas.tools.OpportunityDistribution.ImportDistributions.SozialVersichterte.SozialVersichterte(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.storeFinishedHouseholdIDsToDB(), de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.storeInDB(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.storeInDB(), de.dlr.ivf.tapas.tools.TPS_ParkAndRideAnalysator.storeInterchangesInDB(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.storeLocationOccupanyInDB(), de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.storeLocations(), de.dlr.ivf.tapas.tools.TPS_ParkAndRideRouter.storeMatrixInDB(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.storeMatrixMap(), de.dlr.ivf.tapas.tools.TPS_ParkingSpaceAproximator.storeSQLMatrix(), de.dlr.ivf.tapas.tools.tazcalculator.TAZCalculator.updateTAZ(), de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.updateWeights(), de.dlr.ivf.tapas.tools.TPS_PTScoreCalculator.writeDB(), de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.writeEComTripsToDB(), de.dlr.ivf.tapas.tools.TPS_HouseholdToLocationCreator.writeLocations(), de.dlr.ivf.tapas.runtime.sumoDaemon.SumoMatrixImporter.writeMatrix(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.writeMatrix().
executeQuery()
ResultSet de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery (String query, Object caller)
Parameters
query
caller
Returns
Definition at line 249 of file TPS_DB_Connector.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, and de.dlr.ivf.tapas.log.TPS_Logger.log().
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.adaptCapacities(), de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.addHouseHoldsForVisit(), de.dlr.ivf.scripts.LocationGroupAnalyzer.analyzeTrips(), de.dlr.ivf.tapas.tools.TPS_ParkAndRideAnalysator.analyzeTrips(), de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.appendBZRInfo(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.calcDistance(), de.dlr.ivf.tapas.tools.TPS_PTScoreCalculator.calcScoresBlock(), de.dlr.ivf.tapas.tools.TPS_PTScoreCalculator.calcScoresTAZ(), de.dlr.ivf.tapas.tools.TPS_CapacityAdjuster.calculateGenerationRates(), de.dlr.ivf.scripts.OTP2SQLMatrix.checkDBMatrix(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.checkMatrixName(), de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.checkMatrixName(), de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.collectEComTrips(), de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.createNewMatrixMap(), de.dlr.ivf.tapas.tools.TPS_CapacityAdjuster.createNewMinimalLocationTable(), de.dlr.ivf.tapas.analyzer.tum.results.DatabaseSummaryExport.DatabaseSummaryExport(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.executeQuery(), de.dlr.ivf.scripts.DiscoImporter.fillCars(), de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.fillLocationList(), de.dlr.ivf.tapas.tools.TPS_CapacityAdjuster.fillOverloadFactors(), de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.findBlockAndAdressForDLMObject(), de.dlr.ivf.scripts.DiscoImporter.findCarIDs(), de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.generateCodeMap(), de.dlr.ivf.tapas.runtime.client.ParameterComparator.SimParamComparatorController.generateComparisonList(), de.dlr.ivf.tapas.tools.riesel.SimpleCollector.getAddresses(), de.dlr.ivf.tapas.tools.riesel.RieselTool.getAllInhabitants(), de.dlr.ivf.tapas.tools.riesel.RieselTool.getBuildingsForArea(), de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.getDatabaseContent(), de.dlr.ivf.tapas.tools.riesel.SimpleCollector.getGeometries(), de.dlr.ivf.tapas.tools.TPS_CapacityScale.getLocationInfo(), de.dlr.ivf.tapas.tools.TPS_LocationGroupCreator.groupLocations(), de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.GroupToDistribute(), de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.HouseholdDistribution(), de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ.initRegion(), de.dlr.ivf.tapas.tools.locationallocation.Locator.isInRegion(), de.dlr.ivf.tapas.tools.TPS_CarRedistributor.loadCarMap(), de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.loadCordonDistricts(), de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.loadCordonDistrictsKoFIF(), de.dlr.ivf.tapas.tools.TPS_CapacityAdjuster.loadDBEntries(), de.dlr.ivf.tapas.tools.TPS_MainDiagonalLengthEstimator.loadDistMatrix(), de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.loadExternalPositions(), de.dlr.ivf.tapas.tools.TPS_CarRedistributor.loadHouseHolds(), de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.loadHouseholds(), de.dlr.ivf.tapas.tools.TPS_HouseholdToLocationCreator.loadHouseholdsPerBlock(), de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.loadLocations(), de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ.loadMapping(), de.dlr.ivf.tapas.tools.TPS_SubnetMatrixIntegrator.loadMatricesAndMappings(), de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.loadMatrix(), de.dlr.ivf.tapas.tools.TPS_MatrixComparison.loadMatrix(), de.dlr.ivf.tapas.tools.TPS_SpeedAndDistanceValidator.loadMatrix(), de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.loadNexigaLocations(), de.dlr.ivf.tapas.tools.TPS_CapacityScale.loadPersons(), de.dlr.ivf.tapas.tools.TPS_ParkingSpaceAproximator.loadPersonsAndCars(), de.dlr.ivf.tapas.tools.TPS_ParkAndRideAnalysator.loadPnRRegion(), de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.loadPTStops(), de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.loadSumoValues(), de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.loadTAPASDeutschlandmodellMapping(), de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.loadTAZ(), de.dlr.ivf.tapas.tools.TPS_SpeedAndDistanceValidator.loadTAZ(), de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.loadTAZ(), de.dlr.ivf.tapas.tools.TPS_CapacityScale.loadTaz2DistrictMapping(), de.dlr.ivf.tapas.tools.TPS_ParkingSpaceAproximator.loadTazArea(), de.dlr.ivf.tapas.tools.TPS_CarRedistributor.loadTazMap(), de.dlr.ivf.tapas.tools.TPS_ParkAndRideRouter.loadTAZRestriction(), de.dlr.ivf.scripts.SrVCalculator.loadTAZToArea(), de.dlr.ivf.scripts.SrVCalculator.loadTAZToMapping(), de.dlr.ivf.scripts.VP2030Comparator.loadTrafficVolumes(), de.dlr.ivf.tapas.tools.TPS_MatrixComparison.loadTrips(), de.dlr.ivf.scripts.VP2030Comparator.loadVP2TAZValues(), de.dlr.ivf.tapas.tools.locationallocation.Locator.localizeLocation(), de.dlr.ivf.tapas.tools.OpportunityDistribution.UniqueStreetIdentifier.main(), de.dlr.ivf.scripts.CarFleetAdjuster.makeModifiedFleet(), de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.pKeyList(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.prepareNextSimulationIteration(), de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.processOpportunities(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.readAllParis(), de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.readBosserhofMapingValues(), de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.readBosserhofValues(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.readData(), de.dlr.ivf.tapas.tools.TPS_PTScoreCalculator.readDatabase(), de.dlr.ivf.scripts.GridResultsPreparator.readGeolocations(), de.dlr.ivf.scripts.RamonaResultPreparator.readGeolocations(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.readIDMap(), de.dlr.ivf.tapas.tools.TPS_VisumOD2DB.readIDMap(), de.dlr.ivf.tapas.tools.TPS_MainDiagonalLengthEstimator.readLocations(), de.dlr.ivf.scripts.LocationGroupAnalyzer.readLocations(), de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.readLocationsTable(), de.dlr.ivf.tapas.tools.TPS_FeederCellManipulator.readMatrix(), de.dlr.ivf.tapas.tools.TPS_ParkAndRideRouter.readMatrix(), de.dlr.ivf.tapas.tools.TPS_PTBikeInterchangeMatrix.readMatrix(), de.dlr.ivf.tapas.tools.TPS_PTCarInterchangeMatrix.readMatrix(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.readMatrixFromDB(), de.dlr.ivf.scripts.SrVCalculator.readMatrixFromDB(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.readMatrixMap(), de.dlr.ivf.tapas.tools.TPS_HouseholdToLocationCreator.readMaxLocID(), de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer.readMIDDiary(), de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer2017.readMIDDiary(), de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer_Zeitreihendatensatz.readMIDDiary(), de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.readParameter(), de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.readParameter(), de.dlr.ivf.scripts.FleetAnalyzer.readParameters(), de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.readPersonsTable(), de.dlr.ivf.tapas.tools.TPS_FillLocationRepresentatives.readRepresentatives(), de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.readSumoIteration(), de.dlr.ivf.tapas.runtime.sumoDaemon.SumoMatrixImporter.readSumoValues(), de.dlr.ivf.tapas.tools.TPS_MainDiagonalLengthEstimator.readTAZ(), de.dlr.ivf.tapas.tools.TPS_FillLocationRepresentatives.readTazes(), de.dlr.ivf.scripts.FleetAnalyzer.readTrips(), de.dlr.ivf.scripts.BikeModeCheck.readTrips(), de.dlr.ivf.scripts.SrVCalculator.readTrips(), de.dlr.ivf.tapas.tools.TPS_CarRedistributor.recodeAllCars(), de.dlr.ivf.tapas.runtime.client.SimulationControl.SimulationServerDataUpdateTask.run(), de.dlr.ivf.tapas.runtime.client.SimulationControl.SimulationDataUpdateTask.run(), de.dlr.ivf.tapas.runtime.client.SimulationControl.TimeUpdateTask.run(), de.dlr.ivf.tapas.runtime.client.SimulationMonitor.ExportThread.run(), de.dlr.ivf.tapas.runtime.server.SimulationDaemon.ServerProcessChecker.run(), de.dlr.ivf.tapas.runtime.server.SimulationServer.run(), de.dlr.ivf.tapas.runtime.server.SimulationServer.SimulationServerUpdateTask.run(), de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.saveToDB(), de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.searchSimsToProcess(), de.dlr.ivf.tapas.runtime.server.SimulationServer.SimulationServer(), de.dlr.ivf.tapas.runtime.server.SimulationServer.SimulationServerUpdateTask.SimulationServerUpdateTask(), de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.storeCodeMap(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.storeMatrixMap(), de.dlr.ivf.tapas.tools.riesel.RieselTool.testPerformance(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.TPS_SumoConverter(), de.dlr.ivf.tapas.tools.TPS_CarRedistributor.transformAllCars(), de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.updateData(), de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.SimulationTableModel.updateData(), de.dlr.ivf.tapas.tools.tazcalculator.TAZCalculator.updateTAZ(), and de.dlr.ivf.tapas.iteration.TPS_SumoConverter.writeTripFile().
executeUpdate()
int de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeUpdate (String query, Object caller)
This method does a sql-executeUpdate for the given string with the given calling class and returns the number of updated rows. Each calling class gets its own connection.
Parameters
query The sql-query
caller the caller Object. If this Object made a call before, Its connection is reused. Otherwise a new connection is created.
Returns
the number of updated rows
Definition at line 298 of file TPS_DB_Connector.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, and de.dlr.ivf.tapas.log.TPS_Logger.log().
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ.flushTAZImportData(), de.dlr.ivf.tapas.runtime.client.SimulationControl.ServerOnlineTester.SimulationServerOnlineTestThread.resetDatabaseEntryOfSimulationServer(), de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.resetSimulation(), de.dlr.ivf.tapas.runtime.server.SimulationDaemon.ShutDownProcedure.run(), de.dlr.ivf.tapas.runtime.server.SimulationServer.RunWhenShuttingDown.run(), de.dlr.ivf.tapas.runtime.client.SimulationControl.shutServerDown(), de.dlr.ivf.tapas.runtime.server.SimulationDaemon.SimulationDaemon(), de.dlr.ivf.tapas.runtime.client.SimulationControl.startServer(), de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.storeLocations(), de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.updateLocationCapacity(), de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.updateLocCodesInBosserhofMapingValues(), de.dlr.ivf.tapas.tools.TPS_CapacityAdjuster.updateNewDemand(), and de.dlr.ivf.tapas.runtime.client.SimulationMonitor.updateSimulationDescription().
getConnection()
Connection de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection (Object key) throws SQLException
Returns the connection specified via its object key; if the key does not reference an existing connection, a new connection with the provided object key is opened
Parameters
key the object key of the connection
Returns
the connection referenced by the key
Exceptions
SQLException This exception is thrown in case of non-existence or non-accessibility to the server or refusing the connection by the server (e.g. this IP has no permission to connect to the database)
Definition at line 350 of file TPS_DB_Connector.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, and de.dlr.ivf.tapas.log.TPS_Logger.log().
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationControl.addSimulation(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.batchStoreTrips(), de.dlr.ivf.tapas.iteration.TPS_IterationManagement.calculatePlanDerivation(), de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.checkAndReestablishCon(), de.dlr.ivf.tapas.runtime.server.SimulationServer.checkAndReestablishCon(), de.dlr.ivf.tapas.runtime.client.SimulationControl.checkConnection(), de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.cleanDB(), de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.cleanDB(), de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.close(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.createRegion(), de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.createTripTable(), de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.DBTripFetcher(), de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.doInBackground(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.fetchNextSetOfHouseholds(), de.dlr.ivf.scripts.DiscoImporter.fillTables(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.GeneralDatabaseSummaryExport(), de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader.getAbsoluteSplit(), de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader.getCntTrips(), de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader.getModalSplit(), de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.ReferenceDBReader.getMoDcValues(), de.dlr.ivf.tapas.tools.tazcalculator.TAZCalculator.getNewTAZ(), de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.getOldTables(), de.dlr.ivf.tapas.tools.TPS_LocationGroupCreator.groupLocations(), de.dlr.ivf.tapas.tools.OpportunityDistribution.HouseholdDistribution.HouseholdDistribution(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.importAct2Loc(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.importBlock(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.importBlockNextPTStop(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.importCFN4(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.importCFN4Ind(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.importHH(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.importIntraMIT(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.importIntraPT(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.importLocations(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.importMatrix(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.importModeChoice(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.importPersons(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.importScores(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.importTAZ(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.importTazFee(), de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.insertPersonsIntoTable(), de.dlr.ivf.scripts.GridResultsPreparator.insertTrips(), de.dlr.ivf.scripts.RamonaResultPreparator.insertTrips(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.loadConfigFromDatabase(), de.dlr.ivf.tapas.tools.OpportunityDistribution.UniqueStreetIdentifier.main(), de.dlr.ivf.tapas.util.TPS_TripDeleter.main(), de.dlr.ivf.scripts.CarFleetAdjuster.makeModifiedFleet(), de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer.printDiariesSQLInserts(), de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer2017.printDiariesSQLInserts(), de.dlr.ivf.tapas.tools.TPS_MiD_Diary_Analyzer_Zeitreihendatensatz.printDiariesSQLInserts(), de.dlr.ivf.scripts.GridResultsPreparator.readGeolocations(), de.dlr.ivf.scripts.RamonaResultPreparator.readGeolocations(), de.dlr.ivf.scripts.GridResultsPreparator.readTrips(), de.dlr.ivf.scripts.RamonaResultPreparator.readTrips(), de.dlr.ivf.tapas.iteration.TPS_IterationManagement.resetPlansForRecalculation(), de.dlr.ivf.tapas.runtime.server.SimulationServer.RunWhenShuttingDown.run(), de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.saveConfigInDatabase(), de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.saveToDB(), de.dlr.ivf.tapas.runtime.client.SimulationControl.SimulationDataUpdateTask.SimulationDataUpdateTask(), de.dlr.ivf.tapas.runtime.client.SimulationControl.SimulationServerDataUpdateTask.SimulationServerDataUpdateTask(), de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.storeCodeMap(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.storeFinishedHouseholdIDsToDB(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.storeLocationOccupanyInDB(), de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.storeLocations(), de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.updateEComTripsInDB(), de.dlr.ivf.tapas.tools.TPS_CarRedistributor.updateHouseHolds(), de.dlr.ivf.tapas.tools.tazcalculator.TAZCalculator.updateTAZID(), de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.updateWeights(), de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.writeEComTripsToDB(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.writeSummary(), and de.dlr.ivf.tapas.analyzer.tum.results.DatabaseSummaryExport.writeSummary().
getParameters()
TPS_ParameterClass de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getParameters ()
returns the parameters class reference
Returns
Definition at line 383 of file TPS_DB_Connector.java.
Referenced by de.dlr.ivf.tapas.iteration.TPS_SumoConverter.checkMatrixName(), de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.DBTripFetcher(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.deleteMatrix(), de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.doInBackground(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.getParameters(), de.dlr.ivf.tapas.runtime.client.SimulationControl.getParameters(), de.dlr.ivf.tapas.runtime.server.SimulationServer.getParameters(), de.dlr.ivf.tapas.tools.TPS_VisumOeVToDB.main(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.readIDMap(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.readMatrixFromDB(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.readMatrixMap(), de.dlr.ivf.tapas.runtime.client.SimulationControl.ServerOnlineTester.SimulationServerOnlineTestThread.resetDatabaseEntryOfSimulationServer(), de.dlr.ivf.tapas.runtime.client.SimulationControl.SimulationServerDataUpdateTask.run(), de.dlr.ivf.tapas.runtime.client.SimulationControl.SimulationDataUpdateTask.run(), de.dlr.ivf.tapas.runtime.server.SimulationDaemon.ShutDownProcedure.run(), de.dlr.ivf.tapas.runtime.server.SimulationDaemon.ServerProcessChecker.run(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.storeInDB(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.storeMatrixMap(), de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.updateData(), and de.dlr.ivf.tapas.iteration.TPS_SumoConverter.writeTripFile().
isSqlConnectionError()
boolean de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.isSqlConnectionError (SQLException e) private
Definition at line 387 of file TPS_DB_Connector.java.
openConnection()
Connection de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.openConnection () throws SQLException private
This method opens a connection to a database if there doesn't already exist one. All parameters for the connection are determined by the properties file. If there is no password set, the user gets a dialog where is asked for the password.
Exceptions
SQLException This exception is thrown in case of non-existence or non-accessibility to the server or refuting the connection by the server (e.g. this IP has no permission to connect to the database)
Definition at line 409 of file TPS_DB_Connector.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_DBNAME, de.dlr.ivf.tapas.util.parameters.ParamString.DB_HOST, de.dlr.ivf.tapas.util.parameters.ParamString.DB_PASSWORD, de.dlr.ivf.tapas.util.parameters.ParamValue.DB_PORT, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TYPE, de.dlr.ivf.tapas.util.parameters.ParamString.DB_USER, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getIntValue(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), and de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isDefined().
readMatrix()
Matrix de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.readMatrix (String matrixName, int sIndex, Object caller)
Method to load a single matrix from the DB. The parameter ParamString.DB_TABLE_MATRICES must be defined.
Parameters
matrixName The name of the matrix
sIndex the indexoffset of the matrix
caller the calling object to reuse DB-connections
Returns
the matrix or null, if nothing is found in the DB
Definition at line 510 of file TPS_DB_Connector.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_MATRICES, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.extractIntArray(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.INFO, de.dlr.ivf.tapas.log.TPS_Logger.log(), and de.dlr.ivf.tapas.util.Matrix.setRawValue().
Referenced by de.dlr.ivf.tapas.tools.TPS_SubnetMatrixIntegrator.loadMatricesAndMappings().
readMatrixMap()
MatrixMap de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.readMatrixMap (String matrixName, int sIndex, Object caller)
Method to read a single specified matrix map
Parameters
matrixName the name in the db
sIndex the matrixmap to store in
caller the caller for the connection to save connections
Returns
the loaded MatrixMap
Definition at line 454 of file TPS_DB_Connector.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_MATRIXMAPS, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.extractDoubleArray(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.extractStringArray(), de.dlr.ivf.tapas.util.Matrix.getAverageValue(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.INFO, and de.dlr.ivf.tapas.log.TPS_Logger.log().
Referenced by de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.loadSumoValues(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readMatrix().
readParameter()
String de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.readParameter (String simKey, String paramKey, Object caller)
Method to return a parameter value for a given simulation key and parameter key. Returns null, if simulation or parameter key is not present
Parameters
simKey The simulation to look for
paramKey The parameter to look for
caller The caller for connection hygiene
Returns
A String containing the parameter value
Definition at line 547 of file TPS_DB_Connector.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, and de.dlr.ivf.tapas.log.TPS_Logger.log().
Referenced by de.dlr.ivf.tapas.iteration.TPS_SumoConverter.prepareNextSimulationIteration().
readRuntimeParametersFromDB()
void de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.readRuntimeParametersFromDB (String simKey)
Method to read simulation parameters from the DB for a given key.
Parameters
simKey
Returns
Definition at line 571 of file TPS_DB_Connector.java.
References de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.checkParameters(), de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_SIMULATION_PARAMETERS, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), and de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.readRuntimeParametersFromDB().
Referenced by de.dlr.ivf.tapas.TPS_Main.TPS_Main().
readSingleParameter()
String de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.readSingleParameter (String sim_key, String param_key)
Method to read a single simulation parameter from the DB.
Parameters
sim_key the simulation-key
param_key the parameter key
Returns
a string containing the vale or null if no matching key is found.
Definition at line 594 of file TPS_DB_Connector.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readSettlementSystemCodes(), de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.readSumoIteration(), de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.resetSimulation(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.vacuumTempTables().
updateSingleParameter()
int de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.updateSingleParameter (String sim_key, String param_key, String paramValue)
Method to update a single simulation parameter for a given simulation in the DB. Be careful, if you have the rights to do so!
Parameters
sim_key The simmulation
param_key The parameter
paramValue The new value
Returns
1 for success, 0 for no update
Definition at line 621 of file TPS_DB_Connector.java.
Referenced by de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.resetSimulation(), de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.run(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.vacuumTempTables().
Member Data Documentation
connections
final Map<Object, Connection> de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.connections private
The connection to the database. The connection to the database is established in the constructor and closed when the application exits, via a shutdown hook.
Definition at line 47 of file TPS_DB_Connector.java.
myUserName
String de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.myUserName private
Definition at line 40 of file TPS_DB_Connector.java.
myUserPwd
String de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.myUserPwd private
Definition at line 41 of file TPS_DB_Connector.java.
parameterClass
TPS_ParameterClass de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.parameterClass
Definition at line 39 of file TPS_DB_Connector.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/persistence/db/TPS_DB_Connector.java