TAPAS: de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyExcelWriter Class Reference
de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyExcelWriter Class Reference
Public Member Functions
LegacyExcelWriter (String filename, RegionAnalyzer regionAnalyzer) throws IOException
void writeStatistics ()
Private Member Functions
void addCNF4Config (int x, int y, WritableSheet writableSheet) throws WriteException
void addDistanceClasses (int x, int y, WritableSheet sheet) throws WriteException
void initFurtherValuesSheet (WritableSheet writableSheet) throws WriteException
void initModalsplitSheet (WritableSheet writableSheet) throws WriteException
void initPersongroupSheet (WritableSheet writableSheet) throws WriteException
void initWegelaengenSheet (WritableSheet writableSheet) throws WriteException
double saveDiv (double n, double d)
void writeFurtherValuesData (RegionCode region, WritableSheet furtherValuesSheet) throws WriteException
void writeModalsplitData (RegionCode region, WritableSheet modalsplitSheet) throws WriteException
void writePersongroupData (RegionCode region, WritableSheet persongroupSheet) throws WriteException
void writeWegelaengenData (RegionCode region, WritableSheet wegelaengenSheet) throws WriteException
Private Attributes
final RegionAnalyzer regionAnalyzer
final WritableWorkbook workbook
final int xOffset = 0
final int yOffset = 0
Detailed Description
Definition at line 21 of file LegacyExcelWriter.java.
Constructor & Destructor Documentation
LegacyExcelWriter()
de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyExcelWriter.LegacyExcelWriter (String filename, RegionAnalyzer regionAnalyzer) throws IOException
Parameters
filename
regionAnalyzer
Exceptions
IOException if the Excel workbook could not be initialized. Handle retry!
Definition at line 34 of file LegacyExcelWriter.java.
Member Function Documentation
addCNF4Config()
void de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyExcelWriter.addCNF4Config (int x, int y, WritableSheet writableSheet) throws WriteException private
Definition at line 41 of file LegacyExcelWriter.java.
addDistanceClasses()
void de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyExcelWriter.addDistanceClasses (int x, int y, WritableSheet sheet) throws WriteException private
Definition at line 54 of file LegacyExcelWriter.java.
initFurtherValuesSheet()
void de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyExcelWriter.initFurtherValuesSheet (WritableSheet writableSheet) throws WriteException private
Definition at line 65 of file LegacyExcelWriter.java.
initModalsplitSheet()
void de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyExcelWriter.initModalsplitSheet (WritableSheet writableSheet) throws WriteException private
Definition at line 105 of file LegacyExcelWriter.java.
References de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getDistanceCategoryDescription().
initPersongroupSheet()
void de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyExcelWriter.initPersongroupSheet (WritableSheet writableSheet) throws WriteException private
Definition at line 142 of file LegacyExcelWriter.java.
initWegelaengenSheet()
void de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyExcelWriter.initWegelaengenSheet (WritableSheet writableSheet) throws WriteException private
Definition at line 156 of file LegacyExcelWriter.java.
saveDiv()
double de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyExcelWriter.saveDiv (double n, double d) private
Definition at line 194 of file LegacyExcelWriter.java.
writeFurtherValuesData()
void de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyExcelWriter.writeFurtherValuesData (RegionCode region, WritableSheet furtherValuesSheet) throws WriteException private
Definition at line 198 of file LegacyExcelWriter.java.
References de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategory.CAT_1, de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.DistanceCategory, de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getAvgDistByTrip(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getCntPersons(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getCntTrips(), de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.RegionCode, de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.TripIntention.TRIP_31, and de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.TripIntention.
writeModalsplitData()
void de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyExcelWriter.writeModalsplitData (RegionCode region, WritableSheet modalsplitSheet) throws WriteException private
Definition at line 269 of file LegacyExcelWriter.java.
References de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategory.CAT_1, de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.DistanceCategory, de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getCntTrips(), de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.Mode, de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.RegionCode, de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.TripIntention.TRIP_31, and de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.TripIntention.
writePersongroupData()
void de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyExcelWriter.writePersongroupData (RegionCode region, WritableSheet persongroupSheet) throws WriteException private
Definition at line 339 of file LegacyExcelWriter.java.
References de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getCntPersons(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getCntTrips(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getDist(), de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.PersonGroup, de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.PersonGroup.PG_1, and de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.RegionCode.
writeStatistics()
void de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyExcelWriter.writeStatistics ()
Definition at line 364 of file LegacyExcelWriter.java.
References de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getCntTrips(), and de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.RegionCode.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.finish().
writeWegelaengenData()
void de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyExcelWriter.writeWegelaengenData (RegionCode region, WritableSheet wegelaengenSheet) throws WriteException private
Definition at line 395 of file LegacyExcelWriter.java.
References de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategory.CAT_1, de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.DistanceCategory, de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getAvgDistByTrip(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getCntPersons(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getCntTrips(), de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.RegionCode, de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.TripIntention.TRIP_31, and de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.TripIntention.
Member Data Documentation
regionAnalyzer
final RegionAnalyzer de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyExcelWriter.regionAnalyzer private
Definition at line 23 of file LegacyExcelWriter.java.
workbook
final WritableWorkbook de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyExcelWriter.workbook private
Definition at line 24 of file LegacyExcelWriter.java.
xOffset
final int de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyExcelWriter.xOffset = 0 private
Definition at line 26 of file LegacyExcelWriter.java.
yOffset
final int de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyExcelWriter.yOffset = 0 private
Definition at line 27 of file LegacyExcelWriter.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/tum/regionanalyzer/LegacyExcelWriter.java