TAPAS: de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.Quality Enum Reference
de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.Quality Enum Reference
Public Member Functions
Quality (Color color)
Color getColor ()
Static Public Member Functions
static Quality getById (int id)
Public Attributes
NOT_SET =(Color.GRAY)
BAD =(Color.RED)
MEDIUM =(Color.ORANGE)
GOOD =(Color.GREEN)
Private Attributes
final Color color
Detailed Description
Definition at line 13 of file Quality.java.
Constructor & Destructor Documentation
Quality()
de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.Quality.Quality (Color color)
Definition at line 21 of file Quality.java.
Member Function Documentation
getById()
static Quality de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.Quality.getById (int id) static
Definition at line 25 of file Quality.java.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.ReferenceDBReader.getMoDcValues().
getColor()
Color de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.Quality.getColor ()
Definition at line 29 of file Quality.java.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.ModalSplitRenderer.getItemPaint().
Member Data Documentation
BAD
de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.Quality.BAD =(Color.RED)
Definition at line 15 of file Quality.java.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartFactory.createChart(), de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.Key.getQuality(), and de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartData.QualityChartData().
color
final Color de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.Quality.color private
Definition at line 19 of file Quality.java.
GOOD
de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.Quality.GOOD =(Color.GREEN)
Definition at line 17 of file Quality.java.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartFactory.createChart(), de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.Key.getQuality(), and de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartData.QualityChartData().
MEDIUM
de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.Quality.MEDIUM =(Color.ORANGE)
Definition at line 16 of file Quality.java.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartFactory.createChart(), de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDataset.Key.getQuality(), and de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartData.QualityChartData().
NOT_SET
de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.Quality.NOT_SET =(Color.GRAY)
Definition at line 14 of file Quality.java.
The documentation for this enum was generated from the following file:
src/main/java/de/dlr/ivf/tapas/runtime/client/Graphics/QualityChart/Quality.java