TAPAS: de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.TripIntention Enum Reference
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.TripIntention Enum Reference
Public Member Functions
TripIntention (int id, String caption, Set< Activity > actingCodes)
Set< Activity > getActingCodes ()
String getCaption ()
int getId ()
String getName ()
String toString ()
Static Public Member Functions
static TripIntention getByActivity (Activity act)
static TripIntention getById (int id) throws IllegalArgumentException
static int maxNameWidth ()
Public Attributes
TRIP_31 =(0, "Schule", generateSet(Activity.ACT_410, Activity.ACT_413, Activity.ACT_499))
TRIP_38 =(1, "Studium", generateSet(Activity.ACT_411, Activity.ACT_412, Activity.ACT_414))
TRIP_32 =(2, "Arbeit", generateSet(Activity.ACT_62, Activity.ACT_211, Activity.ACT_212, Activity.ACT_213))
TRIP_33
TRIP_34
TRIP_35
TRIP_36 =(6, "Sonstige", generateSet(Activity.ACT_799))
TRIP_37 =(7, "BackHome", generateSet())
TRIP_MISC =(8, "Nicht zugeordnet", generateSet())
Static Private Member Functions
static Set< Activity > generateSet (Activity... activities)
Private Attributes
final int id
final String caption
final Set< Activity > actingCodes
Detailed Description
Definition at line 201 of file TuMEnums.java.
Constructor & Destructor Documentation
TripIntention()
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.TripIntention.TripIntention (int id, String caption, Set< Activity > actingCodes)
Definition at line 226 of file TuMEnums.java.
Member Function Documentation
generateSet()
static Set<Activity> de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.TripIntention.generateSet (Activity... activities) static private
Definition at line 233 of file TuMEnums.java.
getActingCodes()
Set<Activity> de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.TripIntention.getActingCodes ()
Definition at line 283 of file TuMEnums.java.
getByActivity()
static TripIntention de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.TripIntention.getByActivity (Activity act) static
Parameters
act
Returns
den Wegezweck der diese Activity enthält, null wenn die activity null ist oder die Activity keinem Wegezweck zugeordnet ist
Definition at line 243 of file TuMEnums.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.TripIntentionAnalyzer.assignTrip().
getById()
static TripIntention de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.TripIntention.getById (int id) throws IllegalArgumentException static
Parameters
id
Returns
den Wegezweck der dieser ID zugeordnet ist
Exceptions
IllegalArgumentException geworfen wenn die ID keinem Wegezweck zugeordnet werden konnte
Definition at line 260 of file TuMEnums.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.getElementById().
getCaption()
String de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.TripIntention.getCaption ()
Definition at line 287 of file TuMEnums.java.
getId()
int de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.TripIntention.getId ()
Definition at line 291 of file TuMEnums.java.
getName()
String de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.TripIntention.getName ()
Definition at line 295 of file TuMEnums.java.
maxNameWidth()
static int de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.TripIntention.maxNameWidth () static
Returns the maximal number of characters the names can have.
Returns
Definition at line 275 of file TuMEnums.java.
toString()
String de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.TripIntention.toString ()
Definition at line 300 of file TuMEnums.java.
Member Data Documentation
actingCodes
final Set<Activity> de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.TripIntention.actingCodes private
Definition at line 224 of file TuMEnums.java.
caption
final String de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.TripIntention.caption private
Definition at line 223 of file TuMEnums.java.
id
final int de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.TripIntention.id private
Definition at line 222 of file TuMEnums.java.
TRIP_31
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.TripIntention.TRIP_31 =(0, "Schule", generateSet(Activity.ACT_410, Activity.ACT_413, Activity.ACT_499))
Definition at line 204 of file TuMEnums.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.fillBatch(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyTextWriter.processTUM(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.AnalyzerTest.testEnums(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyExcelWriter.writeFurtherValuesData(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyExcelWriter.writeModalsplitData(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyExcelWriter.writeWegelaengenData().
TRIP_32
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.TripIntention.TRIP_32 =(2, "Arbeit", generateSet(Activity.ACT_62, Activity.ACT_211, Activity.ACT_212, Activity.ACT_213))
Definition at line 206 of file TuMEnums.java.
TRIP_33
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.TripIntention.TRIP_33
Initial value:
=(3, "Private Erledigungen",
                generateSet(Activity.ACT_10, Activity.ACT_12, Activity.ACT_32, Activity.ACT_522, Activity.ACT_611,
                        Activity.ACT_631))
Definition at line 209 of file TuMEnums.java.
TRIP_34
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.TripIntention.TRIP_34
Initial value:
=(4, "Einkauf",
                generateSet(Activity.ACT_50, Activity.ACT_51, Activity.ACT_52, Activity.ACT_53, Activity.ACT_54,
                        Activity.ACT_55))
Definition at line 212 of file TuMEnums.java.
TRIP_35
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.TripIntention.TRIP_35
Initial value:
=(5, "Freizeit",
                generateSet(Activity.ACT_231, Activity.ACT_300, Activity.ACT_511, Activity.ACT_512, Activity.ACT_531,
                        Activity.ACT_533, Activity.ACT_640, Activity.ACT_700, Activity.ACT_711, Activity.ACT_720,
                        Activity.ACT_721, Activity.ACT_722, Activity.ACT_723, Activity.ACT_724, Activity.ACT_740,
                        Activity.ACT_800, Activity.ACT_880, Activity.ACT_881))
Definition at line 217 of file TuMEnums.java.
TRIP_36
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.TripIntention.TRIP_36 =(6, "Sonstige", generateSet(Activity.ACT_799))
Definition at line 218 of file TuMEnums.java.
TRIP_37
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.TripIntention.TRIP_37 =(7, "BackHome", generateSet())
Definition at line 219 of file TuMEnums.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.TripIntentionAnalyzer.assignTrip().
TRIP_38
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.TripIntention.TRIP_38 =(1, "Studium", generateSet(Activity.ACT_411, Activity.ACT_412, Activity.ACT_414))
Definition at line 205 of file TuMEnums.java.
TRIP_MISC
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.TripIntention.TRIP_MISC =(8, "Nicht zugeordnet", generateSet())
Definition at line 220 of file TuMEnums.java.
The documentation for this enum was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/tum/constants/TuMEnums.java