TAPAS: de.dlr.ivf.tapas.tools.matrixMap.Terrain Enum Reference
de.dlr.ivf.tapas.tools.matrixMap.Terrain Enum Reference
Public Member Functions
Terrain (double correctionTerrain)
double getValue ()
Public Attributes
PLAIN =(0.1)
DOWNS =(0.1)
MOUNTAINOUS =(0.1)
CITY =(0.15)
STOPS =(0.2)
Private Attributes
final double correctionTerrain
Detailed Description
Author
Holger Siedel
Definition at line 14 of file Terrain.java.
Constructor & Destructor Documentation
Terrain()
de.dlr.ivf.tapas.tools.matrixMap.Terrain.Terrain (double correctionTerrain)
Definition at line 19 of file Terrain.java.
Member Function Documentation
getValue()
double de.dlr.ivf.tapas.tools.matrixMap.Terrain.getValue ()
Definition at line 23 of file Terrain.java.
Member Data Documentation
CITY
de.dlr.ivf.tapas.tools.matrixMap.Terrain.CITY =(0.15)
Definition at line 15 of file Terrain.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.init().
correctionTerrain
final double de.dlr.ivf.tapas.tools.matrixMap.Terrain.correctionTerrain private
Definition at line 17 of file Terrain.java.
DOWNS
de.dlr.ivf.tapas.tools.matrixMap.Terrain.DOWNS =(0.1)
Definition at line 15 of file Terrain.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.init().
MOUNTAINOUS
de.dlr.ivf.tapas.tools.matrixMap.Terrain.MOUNTAINOUS =(0.1)
Definition at line 15 of file Terrain.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.init().
PLAIN
de.dlr.ivf.tapas.tools.matrixMap.Terrain.PLAIN =(0.1)
Definition at line 15 of file Terrain.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.init().
STOPS
de.dlr.ivf.tapas.tools.matrixMap.Terrain.STOPS =(0.2)
Definition at line 15 of file Terrain.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.init().
The documentation for this enum was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/matrixMap/Terrain.java