TAPAS: de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories Enum Reference
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories Enum Reference
Public Member Functions
Categories (Class<?> theClass, String calibrationColumn)
String getCalibrationColumn ()
Enum getElementById (int id)
Class<?> getEnumeration ()
Static Public Member Functions
[static initializer]
static Categories getByClass (Class<?> theClass)
static AnalyzerBase getNewAnalyzer (Class<?> theClass)
static boolean isValid (Enum cat)
Public Attributes
RegionCode =(de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.RegionCode.class, null)
PersonGroup =(de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.PersonGroup.class, "person_group")
DistanceCategory
DistanceCategoryDefault
DistanceCategoryEquiFive
DistanceCategoryEquiTen
TripIntention =(de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.TripIntention.class, "trip_intention")
Mode =(de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Mode.class, "trip_mode")
Job =(de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.class, null)
TravelTime =(de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.TravelTime.class, null)
Private Attributes
final Class<?> theClass
final String calibrationColumn
Static Private Attributes
static final HashSet< Class<?> > CATEGORIES
Detailed Description
Definition at line 20 of file TuMEnums.java.
Constructor & Destructor Documentation
Categories()
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.Categories (Class<?> theClass, String calibrationColumn)
Definition at line 48 of file TuMEnums.java.
Member Function Documentation
[static initializer]()
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.[static initializer] static
getByClass()
static Categories de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.getByClass (Class<?> theClass) static
Definition at line 53 of file TuMEnums.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.constants.CategoryCombination.contains(), and de.dlr.ivf.tapas.analyzer.tum.constants.CategoryCombination.getCategory().
getCalibrationColumn()
String de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.getCalibrationColumn ()
Returns
the column name used to identify this element in the calibration_results table.
Definition at line 99 of file TuMEnums.java.
getElementById()
Enum de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.getElementById (int id)
Returns an the enumeration element of the calling class with the given id.
Parameters
id
Returns
Definition at line 111 of file TuMEnums.java.
References de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.RegionCode.getById(), de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.TripIntention.getById(), de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategory.getById(), de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategoryDefault.getById(), de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.PersonGroup.getById(), de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Mode.getById(), and de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.getById().
getEnumeration()
Class<?> de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.getEnumeration ()
Returns
the enumeration class of this element.
Definition at line 135 of file TuMEnums.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.Analyzer.getSplit(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralExcelExport.writeTab().
getNewAnalyzer()
static AnalyzerBase de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.getNewAnalyzer (Class<?> theClass) static
Parameters
theClass
Returns
a new AnalyzerBase for the given class.
Definition at line 66 of file TuMEnums.java.
isValid()
static boolean de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.isValid (Enum cat) static
Definition at line 88 of file TuMEnums.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.constants.CategoryCombination.CategoryCombination(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.AnalyzerTest.testCategoryCombination().
Member Data Documentation
calibrationColumn
final String de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.calibrationColumn private
Definition at line 46 of file TuMEnums.java.
CATEGORIES
final HashSet<Class<?> > de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.CATEGORIES static private
Definition at line 36 of file TuMEnums.java.
DistanceCategory
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.DistanceCategory
Initial value:
=(de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategory.class,
                "distance_category")
Definition at line 24 of file TuMEnums.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.createAllCombinations(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getDistanceCategories(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getDistanceCategoryDescription(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyTextWriter.processTUM(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.RegionAnalyzer(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.AnalyzerTest.testCategoryCombination(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyExcelWriter.writeFurtherValuesData(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyExcelWriter.writeModalsplitData(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyExcelWriter.writeWegelaengenData().
DistanceCategoryDefault
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.DistanceCategoryDefault
Initial value:
=(de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategoryDefault.class,
                "distance_category")
Definition at line 26 of file TuMEnums.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.addDefaultAnalyzers(), de.dlr.ivf.tapas.tools.TUM.StandardTUM.buildAnalyzerList(), de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.createToolTips(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.fillBatch(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.GeneralDatabaseSummaryExport(), de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDBFetcher.getModalSplitData(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.main(), and de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDatasetDBFetcher.makeQSChart().
DistanceCategoryEquiFive
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.DistanceCategoryEquiFive
Initial value:
=(de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategoryEquiFive.class,
                null)
Definition at line 28 of file TuMEnums.java.
DistanceCategoryEquiTen
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.DistanceCategoryEquiTen
Initial value:
=(de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategoryEquiTen.class,
                null)
Definition at line 30 of file TuMEnums.java.
Job
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.Job =(de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.class, null)
Definition at line 33 of file TuMEnums.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.createAllCombinations(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyTextWriter.processTUM(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.RegionAnalyzer().
Mode
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.Mode =(de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Mode.class, "trip_mode")
Definition at line 32 of file TuMEnums.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.addDefaultAnalyzers(), de.dlr.ivf.tapas.tools.TUM.StandardTUM.buildAnalyzerList(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.createAllCombinations(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.fillBatch(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.GeneralDatabaseSummaryExport(), de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDBFetcher.getModalSplitData(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.main(), de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDatasetDBFetcher.makeQSChart(), de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitData.ModalSplitData(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyTextWriter.processTUM(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.RegionAnalyzer(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.AnalyzerTest.testCategoryCombination(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.AnalyzerTest.testEnumSets(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyExcelWriter.writeModalsplitData().
PersonGroup
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.PersonGroup =(de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.PersonGroup.class, "person_group")
Definition at line 22 of file TuMEnums.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.addDefaultAnalyzers(), de.dlr.ivf.tapas.tools.TUM.StandardTUM.buildAnalyzerList(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.createAllCombinations(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.fillBatch(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.GeneralDatabaseSummaryExport(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.main(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyTextWriter.processTUM(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.RegionAnalyzer(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.AnalyzerTest.testCategoryCombination(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.updateGlobalStatistics(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyExcelWriter.writePersongroupData().
RegionCode
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.RegionCode =(de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.RegionCode.class, null)
Definition at line 21 of file TuMEnums.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.addDefaultAnalyzers(), de.dlr.ivf.tapas.tools.TUM.StandardTUM.buildAnalyzerList(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.createAllCombinations(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.main(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyTextWriter.processTUM(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.RegionAnalyzer(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.AnalyzerTest.testEnumSets(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.updateGlobalStatistics(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyExcelWriter.writeFurtherValuesData(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyExcelWriter.writeModalsplitData(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyExcelWriter.writePersongroupData(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyExcelWriter.writeStatistics(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyExcelWriter.writeWegelaengenData().
theClass
final Class<?> de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.theClass private
Definition at line 45 of file TuMEnums.java.
TravelTime
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.TravelTime =(de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.TravelTime.class, null)
Definition at line 34 of file TuMEnums.java.
TripIntention
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.TripIntention =(de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.TripIntention.class, "trip_intention")
Definition at line 31 of file TuMEnums.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.addDefaultAnalyzers(), de.dlr.ivf.tapas.tools.TUM.StandardTUM.buildAnalyzerList(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.createAllCombinations(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.fillBatch(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.GeneralDatabaseSummaryExport(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.main(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyTextWriter.processTUM(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.RegionAnalyzer(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.AnalyzerTest.testCategoryCombination(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyExcelWriter.writeFurtherValuesData(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyExcelWriter.writeModalsplitData(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyExcelWriter.writeWegelaengenData().
The documentation for this enum was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/tum/constants/TuMEnums.java