TAPAS: de.dlr.ivf.tapas.util.parameters.ParamType Enum Reference
de.dlr.ivf.tapas.util.parameters.ParamType Enum Reference
Public Member Functions
ParamType (int index)
int getIndex ()
Public Attributes
DB =(2)
DEFAULT =(3)
EXEC =(-1)
FILE =(1)
LOG =(4)
RUN =(0)
OPTIONAL =(5)
TMP =(-2)
Private Attributes
final int index
Detailed Description
This enum provides all parameter types
Definition at line 14 of file ParamType.java.
Constructor & Destructor Documentation
ParamType()
de.dlr.ivf.tapas.util.parameters.ParamType.ParamType (int index)
Definition at line 58 of file ParamType.java.
Member Function Documentation
getIndex()
int de.dlr.ivf.tapas.util.parameters.ParamType.getIndex ()
Gets the type index of this parameter
Returns
the index
Definition at line 67 of file ParamType.java.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.persistence.TPS_ParameterXLSDAO.convert(), and de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverter.convert().
Member Data Documentation
DB
de.dlr.ivf.tapas.util.parameters.ParamType.DB =(2)
Type for parameters which contain a table name in the database
Definition at line 18 of file ParamType.java.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverter.save(), and de.dlr.ivf.tapas.tools.fileModifier.persistence.TPS_ParameterXLSDAO.writeParameter().
DEFAULT
de.dlr.ivf.tapas.util.parameters.ParamType.DEFAULT =(3)
Type for parameters which are run-independent
Definition at line 23 of file ParamType.java.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverter.save(), and de.dlr.ivf.tapas.tools.fileModifier.persistence.TPS_ParameterXLSDAO.writeParameter().
EXEC
de.dlr.ivf.tapas.util.parameters.ParamType.EXEC =(-1)
Type for parameters which have to be set as a virtual machine argument
Definition at line 29 of file ParamType.java.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.insert().
FILE
de.dlr.ivf.tapas.util.parameters.ParamType.FILE =(1)
Type for parameters which contains a name of an input file
Definition at line 34 of file ParamType.java.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverter.save(), and de.dlr.ivf.tapas.tools.fileModifier.persistence.TPS_ParameterXLSDAO.writeParameter().
index
final int de.dlr.ivf.tapas.util.parameters.ParamType.index private
Definition at line 56 of file ParamType.java.
LOG
de.dlr.ivf.tapas.util.parameters.ParamType.LOG =(4)
Type for logging parameters
Definition at line 39 of file ParamType.java.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverter.save(), and de.dlr.ivf.tapas.tools.fileModifier.persistence.TPS_ParameterXLSDAO.writeParameter().
OPTIONAL
de.dlr.ivf.tapas.util.parameters.ParamType.OPTIONAL =(5)
Type for parameters which are optional
Definition at line 49 of file ParamType.java.
Referenced by de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.checkParameters().
RUN
de.dlr.ivf.tapas.util.parameters.ParamType.RUN =(0)
Type for parameters which have to be set for every single run
Definition at line 44 of file ParamType.java.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverter.save(), and de.dlr.ivf.tapas.tools.fileModifier.persistence.TPS_ParameterXLSDAO.writeParameter().
TMP
de.dlr.ivf.tapas.util.parameters.ParamType.TMP =(-2)
Temporary Keys
Definition at line 54 of file ParamType.java.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.insert().
The documentation for this enum was generated from the following file:
src/main/java/de/dlr/ivf/tapas/util/parameters/ParamType.java