TAPAS: de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.RegionCode Enum Reference
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.RegionCode Enum Reference
Public Member Functions
RegionCode (int id, String desc)
int getId ()
String getName ()
String toString ()
Static Public Member Functions
static RegionCode getById (int id)
static int maxNameWidth ()
Public Attributes
REGION_0 =(0, "Gesamt")
REGION_1 =(1, "Agglomeration")
REGION_2 =(2, "städtisch")
REGION_3 =(3, "wenig verstädtert")
REGION_4 =(4, "ländlich")
REGION_5 =(5, "sehr ländlich")
Private Attributes
final int id
final String desc
Detailed Description
Definition at line 141 of file TuMEnums.java.
Constructor & Destructor Documentation
RegionCode()
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.RegionCode.RegionCode (int id, String desc)
Definition at line 152 of file TuMEnums.java.
Member Function Documentation
getById()
static RegionCode de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.RegionCode.getById (int id) static
Parameters
id
Returns
Exceptions
IllegalArgumentException if the id cannot be assigned.
Definition at line 162 of file TuMEnums.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.RegionCodeAnalyzer.assignTrip(), and de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.getElementById().
getId()
int de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.RegionCode.getId ()
Definition at line 186 of file TuMEnums.java.
getName()
String de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.RegionCode.getName ()
Definition at line 190 of file TuMEnums.java.
maxNameWidth()
static int de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.RegionCode.maxNameWidth () static
Returns the maximal number of characters the names can have.
Returns
Definition at line 178 of file TuMEnums.java.
toString()
String de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.RegionCode.toString ()
Definition at line 195 of file TuMEnums.java.
Member Data Documentation
desc
final String de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.RegionCode.desc private
Definition at line 150 of file TuMEnums.java.
id
final int de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.RegionCode.id private
Definition at line 149 of file TuMEnums.java.
REGION_0
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.RegionCode.REGION_0 =(0, "Gesamt")
Definition at line 142 of file TuMEnums.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.RegionCodeIgnored.assignTrip(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getCntPersons(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getCntTrips(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getMaxDuration(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getMaxTripLength(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getMinDuration(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getMinTripLength(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getTotalDuration(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.getTotalTripLength(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyTextWriter.processTUM(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.RegionAnalyzer(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.AnalyzerTest.testEnums(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.updateGlobalStatistics().
REGION_1
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.RegionCode.REGION_1 =(1, "Agglomeration")
Definition at line 143 of file TuMEnums.java.
REGION_2
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.RegionCode.REGION_2 =(2, "städtisch")
Definition at line 144 of file TuMEnums.java.
REGION_3
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.RegionCode.REGION_3 =(3, "wenig verstädtert")
Definition at line 145 of file TuMEnums.java.
REGION_4
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.RegionCode.REGION_4 =(4, "ländlich")
Definition at line 146 of file TuMEnums.java.
REGION_5
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.RegionCode.REGION_5 =(5, "sehr ländlich")
Definition at line 147 of file TuMEnums.java.
The documentation for this enum was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/tum/constants/TuMEnums.java