TAPAS: de.dlr.ivf.tapas.analyzer.inputfileconverter.TripIntention Enum Reference
de.dlr.ivf.tapas.analyzer.inputfileconverter.TripIntention Enum Reference
Public Member Functions
TripIntention (int id, String caption, Set< Activity > actingCodes)
Set< Activity > getActingCodes ()
String getCaption ()
int getId ()
String getName ()
Static Public Member Functions
static TripIntention getByActivity (Activity act)
static TripIntention getById (int id) throws IllegalArgumentException
Public Attributes
TRIP_31 =(0, "Schule", generateSet(Activity.ACT_410, Activity.ACT_413, Activity.ACT_499))
TRIP_38 =(1, "Studium", generateSet(Activity.ACT_411,Activity.ACT_412,Activity.ACT_414))
TRIP_32 =(2, "Arbeit", generateSet(Activity.ACT_62, Activity.ACT_211, Activity.ACT_212, Activity.ACT_213))
TRIP_33
TRIP_34 =(4, "Einkauf", generateSet(Activity.ACT_50,Activity.ACT_51,Activity.ACT_52,Activity.ACT_53,Activity.ACT_54))
TRIP_35
TRIP_36 =(6, "Sonstige", generateSet(Activity.ACT_799))
TRIP_37 =(7, "BackHome", generateSet())
TRIP_MISC =(8, "Nicht zugeordnet", generateSet())
Static Private Member Functions
static Set< Activity > generateSet (Activity... activities)
Private Attributes
final int id
final String caption
final Set< Activity > actingCodes
Detailed Description
Definition at line 15 of file TripIntention.java.
Constructor & Destructor Documentation
TripIntention()
de.dlr.ivf.tapas.analyzer.inputfileconverter.TripIntention.TripIntention (int id, String caption, Set< Activity > actingCodes)
Definition at line 36 of file TripIntention.java.
Member Function Documentation
generateSet()
static Set<Activity> de.dlr.ivf.tapas.analyzer.inputfileconverter.TripIntention.generateSet (Activity... activities) static private
Definition at line 43 of file TripIntention.java.
getActingCodes()
Set<Activity> de.dlr.ivf.tapas.analyzer.inputfileconverter.TripIntention.getActingCodes ()
Definition at line 79 of file TripIntention.java.
getByActivity()
static TripIntention de.dlr.ivf.tapas.analyzer.inputfileconverter.TripIntention.getByActivity (Activity act) static
Parameters
act
Returns
den Wegezweck der diese Activity enthält, null wenn die activity null ist oder die Activity keinem Wegezweck zugeordnet ist
Definition at line 52 of file TripIntention.java.
getById()
static TripIntention de.dlr.ivf.tapas.analyzer.inputfileconverter.TripIntention.getById (int id) throws IllegalArgumentException static
Parameters
id
Returns
den Wegezweck der dieser ID zugeordnet ist
Exceptions
IllegalArgumentException geworfen wenn die ID keinem Wegezweck zugeordnet werden konnte
Definition at line 69 of file TripIntention.java.
getCaption()
String de.dlr.ivf.tapas.analyzer.inputfileconverter.TripIntention.getCaption ()
Definition at line 83 of file TripIntention.java.
getId()
int de.dlr.ivf.tapas.analyzer.inputfileconverter.TripIntention.getId ()
Definition at line 87 of file TripIntention.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getAvgTripDurationForTripIntention(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getAvgTripLengthForTripIntention(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getCountOfTripsForTripIntention(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getCountOfTripsForTripIntentionAndPersonGroupTapas(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getCountOfTripsForTripIntentionAndPersonGroupViseva(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getCountTripsByTripIntention(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getModalSplitForDistanceCategoryAndTripIntention(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getModalSplitForDistanceCategoryTripIntentionAbs(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getModalSplitForTripIntentionAbs(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getModalSplitForTripIntentionAndPersonGroupTapasAbs(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getModalSplitForTripIntentionAndPersonGroupVisevaAbs(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getNrOfTripsForPersonGroupTapasAndTripIntention(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getNrOfTripsForPersonGroupVisevaAndTripIntention(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getNrTripsForTripIntention(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getPercentageOfTriplengthAllocationForDistanceCategoryAndTripIntention(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getPercentageOfTriplengthAllocationForDistanceCategoryAndTripIntentionAndPersonGroupTAPAS(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getPercentageOfTriplengthAllocationForDistanceCategoryAndTripIntentionAndPersonGroupViseva(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getPercentageOfTripLengthAllocationForTripIntentionAndPersonGroupsTapas(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getPercentageOfTripLengthAllocationForTripIntentionAndPersonGroupsViseva(), and de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getPercentageOfTripLengthAllocationForTripIntentions().
getName()
String de.dlr.ivf.tapas.analyzer.inputfileconverter.TripIntention.getName ()
Definition at line 91 of file TripIntention.java.
Member Data Documentation
actingCodes
final Set<Activity> de.dlr.ivf.tapas.analyzer.inputfileconverter.TripIntention.actingCodes private
Definition at line 34 of file TripIntention.java.
caption
final String de.dlr.ivf.tapas.analyzer.inputfileconverter.TripIntention.caption private
Definition at line 33 of file TripIntention.java.
id
final int de.dlr.ivf.tapas.analyzer.inputfileconverter.TripIntention.id private
Definition at line 32 of file TripIntention.java.
TRIP_31
de.dlr.ivf.tapas.analyzer.inputfileconverter.TripIntention.TRIP_31 =(0, "Schule", generateSet(Activity.ACT_410, Activity.ACT_413, Activity.ACT_499))
Definition at line 17 of file TripIntention.java.
TRIP_32
de.dlr.ivf.tapas.analyzer.inputfileconverter.TripIntention.TRIP_32 =(2, "Arbeit", generateSet(Activity.ACT_62, Activity.ACT_211, Activity.ACT_212, Activity.ACT_213))
Definition at line 19 of file TripIntention.java.
TRIP_33
de.dlr.ivf.tapas.analyzer.inputfileconverter.TripIntention.TRIP_33
Initial value:
=(3, "Private Erledigungen",
            generateSet(Activity.ACT_10, Activity.ACT_12, Activity.ACT_32, Activity.ACT_522, Activity.ACT_611,
                    Activity.ACT_631))
Definition at line 22 of file TripIntention.java.
TRIP_34
de.dlr.ivf.tapas.analyzer.inputfileconverter.TripIntention.TRIP_34 =(4, "Einkauf", generateSet(Activity.ACT_50,Activity.ACT_51,Activity.ACT_52,Activity.ACT_53,Activity.ACT_54))
Definition at line 23 of file TripIntention.java.
TRIP_35
de.dlr.ivf.tapas.analyzer.inputfileconverter.TripIntention.TRIP_35
Initial value:
=(5, "Freizeit",
            generateSet(Activity.ACT_231, Activity.ACT_299, Activity.ACT_300, Activity.ACT_511, Activity.ACT_512, Activity.ACT_531,
                    Activity.ACT_533, Activity.ACT_640, Activity.ACT_700, Activity.ACT_711, Activity.ACT_720,
                    Activity.ACT_721, Activity.ACT_722, Activity.ACT_723, Activity.ACT_724, Activity.ACT_740, Activity.ACT_800))
Definition at line 27 of file TripIntention.java.
TRIP_36
de.dlr.ivf.tapas.analyzer.inputfileconverter.TripIntention.TRIP_36 =(6, "Sonstige", generateSet(Activity.ACT_799))
Definition at line 28 of file TripIntention.java.
TRIP_37
de.dlr.ivf.tapas.analyzer.inputfileconverter.TripIntention.TRIP_37 =(7, "BackHome", generateSet())
Definition at line 29 of file TripIntention.java.
TRIP_38
de.dlr.ivf.tapas.analyzer.inputfileconverter.TripIntention.TRIP_38 =(1, "Studium", generateSet(Activity.ACT_411,Activity.ACT_412,Activity.ACT_414))
Definition at line 18 of file TripIntention.java.
TRIP_MISC
de.dlr.ivf.tapas.analyzer.inputfileconverter.TripIntention.TRIP_MISC =(8, "Nicht zugeordnet", generateSet())
Definition at line 30 of file TripIntention.java.
The documentation for this enum was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/inputfileconverter/TripIntention.java