TAPAS: de.dlr.ivf.tapas.log.TPS_LoggingInterface.HierarchyLogLevel Enum Reference
de.dlr.ivf.tapas.log.TPS_LoggingInterface.HierarchyLogLevel Enum Reference
Public Member Functions
HierarchyLogLevel (int index)
int getIndex ()
boolean includes (HierarchyLogLevel hLog)
Public Attributes
OFF =(0)
APPLICATION =(1)
CLIENT =(2)
THREAD =(3)
HOUSEHOLD =(4)
PERSON =(5)
PLAN =(6)
EPISODE =(7)
ALL =(8)
Private Attributes
final int index
final int value
final int mask
Detailed Description
The HierarchyLogLevel: specifies the Hierarchy within the application
Author
hein_mh
Definition at line 56 of file TPS_LoggingInterface.java.
Constructor & Destructor Documentation
HierarchyLogLevel()
de.dlr.ivf.tapas.log.TPS_LoggingInterface.HierarchyLogLevel.HierarchyLogLevel (int index)
Constructor, which initialises the internal variables for the given index.
Parameters
index
Definition at line 70 of file TPS_LoggingInterface.java.
Member Function Documentation
getIndex()
int de.dlr.ivf.tapas.log.TPS_LoggingInterface.HierarchyLogLevel.getIndex ()
Getter for the index of this instance. The higher the more important.
Returns
Definition at line 81 of file TPS_LoggingInterface.java.
includes()
boolean de.dlr.ivf.tapas.log.TPS_LoggingInterface.HierarchyLogLevel.includes (HierarchyLogLevel hLog)
This method returns true if the instance is included in the logging
Parameters
hLog
Returns
Definition at line 91 of file TPS_LoggingInterface.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.HierarchyLogLevel.value.
Referenced by de.dlr.ivf.tapas.log.TPS_Logger.shallBeLogged().
Member Data Documentation
ALL
de.dlr.ivf.tapas.log.TPS_LoggingInterface.HierarchyLogLevel.ALL =(8)
Definition at line 57 of file TPS_LoggingInterface.java.
Referenced by de.dlr.ivf.tapas.log.TPS_Logger.getHierarchyLogLevel().
APPLICATION
de.dlr.ivf.tapas.log.TPS_LoggingInterface.HierarchyLogLevel.APPLICATION =(1)
Definition at line 57 of file TPS_LoggingInterface.java.
Referenced by de.dlr.ivf.tapas.loc.TPS_Region.initLocationChoiceSet(), de.dlr.ivf.tapas.loc.TPS_Region.initLocationSelectModel(), and de.dlr.ivf.tapas.mode.TPS_Mode.initUtilityFunction().
CLIENT
de.dlr.ivf.tapas.log.TPS_LoggingInterface.HierarchyLogLevel.CLIENT =(2)
Definition at line 57 of file TPS_LoggingInterface.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Worker.call(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.createTemporaryAndOutputTables(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.init(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readMatrix(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readRegion(), and de.dlr.ivf.tapas.log.TPS_Logger.setLoggingClass().
EPISODE
de.dlr.ivf.tapas.log.TPS_LoggingInterface.HierarchyLogLevel.EPISODE =(7)
Definition at line 57 of file TPS_LoggingInterface.java.
Referenced by de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree.applyExpertKnowledge(), de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixed.getDistributionSet(), de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixedBS.getDistributionSet(), de.dlr.ivf.tapas.modechoice.TPS_UtilityMNL.getDistributionSet(), de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes(), de.dlr.ivf.tapas.mode.TPS_ModeSet.selectMode(), and de.dlr.ivf.tapas.mode.TPS_ModeSet.selectMode0().
HOUSEHOLD
de.dlr.ivf.tapas.log.TPS_LoggingInterface.HierarchyLogLevel.HOUSEHOLD =(4)
Definition at line 57 of file TPS_LoggingInterface.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Worker.call().
index
final int de.dlr.ivf.tapas.log.TPS_LoggingInterface.HierarchyLogLevel.index private
Definition at line 59 of file TPS_LoggingInterface.java.
mask
final int de.dlr.ivf.tapas.log.TPS_LoggingInterface.HierarchyLogLevel.mask private
Definition at line 63 of file TPS_LoggingInterface.java.
OFF
de.dlr.ivf.tapas.log.TPS_LoggingInterface.HierarchyLogLevel.OFF =(0)
Definition at line 57 of file TPS_LoggingInterface.java.
PERSON
de.dlr.ivf.tapas.log.TPS_LoggingInterface.HierarchyLogLevel.PERSON =(5)
Definition at line 57 of file TPS_LoggingInterface.java.
Referenced by de.dlr.ivf.tapas.scheme.TPS_SchemeSet.findScheme(), and de.dlr.ivf.tapas.person.TPS_Worker.processHousehold().
PLAN
de.dlr.ivf.tapas.log.TPS_LoggingInterface.HierarchyLogLevel.PLAN =(6)
Definition at line 57 of file TPS_LoggingInterface.java.
THREAD
de.dlr.ivf.tapas.log.TPS_LoggingInterface.HierarchyLogLevel.THREAD =(3)
Definition at line 57 of file TPS_LoggingInterface.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.addPersonToHousehold(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.fetchNextSetOfHouseholds(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.insertTrips(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.loadHouseholds(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.updateOccupancyTable(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.vacuumTempTables().
value
final int de.dlr.ivf.tapas.log.TPS_LoggingInterface.HierarchyLogLevel.value private
Definition at line 61 of file TPS_LoggingInterface.java.
Referenced by de.dlr.ivf.tapas.log.TPS_LoggingInterface.HierarchyLogLevel.includes().
The documentation for this enum was generated from the following file:
src/main/java/de/dlr/ivf/tapas/log/TPS_LoggingInterface.java