TAPAS: de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategoryDefault Enum Reference
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategoryDefault Enum Reference
Public Member Functions
DistanceCategoryDefault (int id, double maxDistance, String description)
String getDescription ()
int getId ()
String toString ()
Static Public Member Functions
static String createDistanceCategoriesID (List< DistanceCategoryDefault > categories)
static String createDistanceCategoriesName (List< DistanceCategoryDefault > categories)
static DistanceCategoryDefault getByDistance (double dist)
static DistanceCategoryDefault getById (int id) throws IllegalArgumentException
static int maxNameWidth ()
Public Attributes
CAT_1 =(0, 1000, "< 1 km")
CAT_2 =(1, 3000, "1-3 km")
CAT_3 =(2, 5000, "3-5 km")
CAT_4 =(3, 7000, "5-7 km")
CAT_5 =(4, 10000, "7-10 km")
CAT_6 =(5, 25000, "10-25 km")
CAT_7 =(6, 100000, "25-100 km")
CAT_8 =(7, Double.MAX_VALUE, ">=100 km")
Protected Member Functions
double getMaxDistance ()
Private Attributes
final int id
final double maxDistance
final String description
Detailed Description
Definition at line 356 of file TuMEnums.java.
Constructor & Destructor Documentation
DistanceCategoryDefault()
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategoryDefault.DistanceCategoryDefault (int id, double maxDistance, String description)
Parameters
id die ID der Kategorie
maxDistance die maximale Distanz (ausschließlich, der angegebene Wert ist nicht mehr gültig)
Definition at line 375 of file TuMEnums.java.
Member Function Documentation
createDistanceCategoriesID()
static String de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategoryDefault.createDistanceCategoriesID (List< DistanceCategoryDefault > categories) static
Erzeugt aus den DistanceCategory einen einheitlichen Namen. z.B. Wird aus DistanceCategory#CAT_2 und DistanceCategory#CAT_3 = 1-5 km
Returns
Definition at line 389 of file TuMEnums.java.
References categories.
createDistanceCategoriesName()
static String de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategoryDefault.createDistanceCategoriesName (List< DistanceCategoryDefault > categories) static
Erzeugt aus den DistanceCategory einen einheitlichen Namen. z.B. Wird aus DistanceCategory#CAT_2 und DistanceCategory#CAT_3 = 1-5 km
Parameters
categories Elemente müssen aufsteigend sortiert sein
Returns
Definition at line 405 of file TuMEnums.java.
References categories.
getByDistance()
static DistanceCategoryDefault de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategoryDefault.getByDistance (double dist) static
Parameters
dist
Returns
die DistanceCategory dessen obere Distanzgrenze am nächsten an der angebenen größe ist und gleichzeitig größer als die angebene ist. Sollte keine DistanceCategory eine größere Distance haben wird immer die größte zurückgegeben.
Definition at line 431 of file TuMEnums.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DefaultDistanceCategoryAnalyzer.assignTrip().
getById()
static DistanceCategoryDefault de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategoryDefault.getById (int id) throws IllegalArgumentException static
Parameters
id
Returns
die DistanceCategory die die angegebene ID besitzt
Exceptions
IllegalArgumentException wenn die ID keiner Kategorie zugeordnet werden kann
Definition at line 445 of file TuMEnums.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.getElementById(), and de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.ReferenceDBReader.getMoDcValues().
getDescription()
String de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategoryDefault.getDescription ()
Definition at line 466 of file TuMEnums.java.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.createToolTips(), and de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.ReferenceDBReader.getMoDcValues().
getId()
int de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategoryDefault.getId ()
Definition at line 470 of file TuMEnums.java.
getMaxDistance()
double de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategoryDefault.getMaxDistance () protected
Definition at line 474 of file TuMEnums.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategory.createFilteredDistances().
maxNameWidth()
static int de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategoryDefault.maxNameWidth () static
Returns the maximal number of characters the names can have.
Returns
Definition at line 459 of file TuMEnums.java.
toString()
String de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategoryDefault.toString ()
Definition at line 479 of file TuMEnums.java.
Member Data Documentation
CAT_1
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategoryDefault.CAT_1 =(0, 1000, "< 1 km")
Definition at line 357 of file TuMEnums.java.
CAT_2
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategoryDefault.CAT_2 =(1, 3000, "1-3 km")
Definition at line 358 of file TuMEnums.java.
CAT_3
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategoryDefault.CAT_3 =(2, 5000, "3-5 km")
Definition at line 359 of file TuMEnums.java.
CAT_4
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategoryDefault.CAT_4 =(3, 7000, "5-7 km")
Definition at line 360 of file TuMEnums.java.
CAT_5
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategoryDefault.CAT_5 =(4, 10000, "7-10 km")
Definition at line 361 of file TuMEnums.java.
CAT_6
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategoryDefault.CAT_6 =(5, 25000, "10-25 km")
Definition at line 362 of file TuMEnums.java.
CAT_7
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategoryDefault.CAT_7 =(6, 100000, "25-100 km")
Definition at line 363 of file TuMEnums.java.
CAT_8
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategoryDefault.CAT_8 =(7, Double.MAX_VALUE, ">=100 km")
Definition at line 364 of file TuMEnums.java.
description
final String de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategoryDefault.description private
Definition at line 368 of file TuMEnums.java.
id
final int de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategoryDefault.id private
Definition at line 366 of file TuMEnums.java.
maxDistance
final double de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategoryDefault.maxDistance private
Definition at line 367 of file TuMEnums.java.
The documentation for this enum was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/tum/constants/TuMEnums.java