TAPAS: de.dlr.ivf.tapas.util.parameters.CURRENCY Enum Reference
de.dlr.ivf.tapas.util.parameters.CURRENCY Enum Reference
Public Member Functions
CURRENCY (double factor)
double convert (double value, CURRENCY currentCurrency)
Public Attributes
DM =(1)
EUR =(1.95583)
Private Attributes
final double factor
Detailed Description
These enum constants provide factors to convert values between different currencies.
Author
mark_ma
Definition at line 17 of file CURRENCY.java.
Constructor & Destructor Documentation
CURRENCY()
de.dlr.ivf.tapas.util.parameters.CURRENCY.CURRENCY (double factor)
Constructor sets the factor
Parameters
factor
Definition at line 37 of file CURRENCY.java.
Member Function Documentation
convert()
double de.dlr.ivf.tapas.util.parameters.CURRENCY.convert (double value, CURRENCY currentCurrency)
This method converts the given value in the given currency into the currency of this constant
Parameters
value value to convert
currentCurrency the current currency the value is expressed in
Returns
converted value into the currency of this constant
Definition at line 49 of file CURRENCY.java.
References de.dlr.ivf.tapas.util.parameters.CURRENCY.factor.
Referenced by de.dlr.ivf.tapas.plan.TPS_PlannedTrip.getCosts().
Member Data Documentation
DM
de.dlr.ivf.tapas.util.parameters.CURRENCY.DM =(1)
German currency until 2002: German Mark (Deutsche Mark)
Definition at line 21 of file CURRENCY.java.
EUR
de.dlr.ivf.tapas.util.parameters.CURRENCY.EUR =(1.95583)
European currency: EURO
Definition at line 25 of file CURRENCY.java.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.getTravelCosts(), de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.readParameter(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.TPS_SumoConverter(), and de.dlr.ivf.tapas.iteration.TPS_VisumConverter.TPS_VisumConverter().
factor
final double de.dlr.ivf.tapas.util.parameters.CURRENCY.factor private
Factor to convert between currencies
Definition at line 30 of file CURRENCY.java.
Referenced by de.dlr.ivf.tapas.util.parameters.CURRENCY.convert().
The documentation for this enum was generated from the following file:
src/main/java/de/dlr/ivf/tapas/util/parameters/CURRENCY.java