TAPAS: de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel Enum Reference
de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel Enum Reference
Public Member Functions
SeverenceLogLevel (int index, ParamString key)
int getIndex ()
String getKey (TPS_ParameterClass parameterClass)
boolean includes (SeverenceLogLevel sll)
Public Attributes
OFF =(0, ParamString.LOG_LEVEL_OFF)
FATAL =(1, ParamString.LOG_LEVEL_FATAL)
ERROR
SEVERE =(3, ParamString.LOG_LEVEL_SEVERE)
WARN
INFO =(5, ParamString.LOG_LEVEL_INFO)
DEBUG
FINE =(7, ParamString.LOG_LEVEL_FINE)
FINER
FINEST =(9, ParamString.LOG_LEVEL_FINEST)
ALL
Private Attributes
final int index
final ParamString key
Detailed Description
The SeverenceLogLevel: specifies the Hierarchy within the severence
Definition at line 100 of file TPS_LoggingInterface.java.
Constructor & Destructor Documentation
SeverenceLogLevel()
de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.SeverenceLogLevel (int index, ParamString key)
Parameters
index index of this level
key corresponding key of this level
Definition at line 118 of file TPS_LoggingInterface.java.
Member Function Documentation
getIndex()
int de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.getIndex ()
Returns
index
Definition at line 126 of file TPS_LoggingInterface.java.
getKey()
String de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.getKey (TPS_ParameterClass parameterClass)
Parameters
parameterClass parameter class reference
Returns
corresponding ParamString to this log level
Definition at line 134 of file TPS_LoggingInterface.java.
References de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString().
includes()
boolean de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.includes (SeverenceLogLevel sll)
Parameters
sll SeverenceLogLevel to test
Returns
true if this level includes the given level
Definition at line 142 of file TPS_LoggingInterface.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.index.
Referenced by de.dlr.ivf.tapas.log.TPS_Logger.log(), and de.dlr.ivf.tapas.log.TPS_Logger.shallBeLogged().
Member Data Documentation
ALL
de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ALL
Initial value:
=(10,
                ParamString.LOG_LEVEL_ALL)
Definition at line 106 of file TPS_LoggingInterface.java.
DEBUG
de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.DEBUG
Initial value:
=(6,
                ParamString.LOG_LEVEL_DEBUG)
Definition at line 104 of file TPS_LoggingInterface.java.
Referenced by de.dlr.ivf.tapas.plan.acceptance.TPS_PlanEVA1Acceptance.calculateAcceptanceProbBudgetConstraints(), de.dlr.ivf.tapas.plan.acceptance.TPS_PlanEVA1Acceptance.calculateAcceptanceProbTimeConstraints(), de.dlr.ivf.tapas.person.TPS_Worker.call(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.consumeParameter(), de.dlr.ivf.tapas.person.TPS_Worker.createPersonPlans(), de.dlr.ivf.tapas.scheme.TPS_SchemeSet.findScheme(), de.dlr.ivf.tapas.loc.TPS_FocusPointModel.getFocusPoint(), de.dlr.ivf.tapas.loc.TPS_MultipleTAZRepresentant.getLocationRepresentatives(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.getNextHousehold(), de.dlr.ivf.tapas.mode.TPS_MassTransportMode.getScore(), de.dlr.ivf.tapas.mode.TPS_MassTransportMode.getTravelTime(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.insertTrips(), de.dlr.ivf.tapas.plan.acceptance.TPS_PlanEVA1Acceptance.isPlanAcceptedByOverallTravelTime(), de.dlr.ivf.tapas.person.TPS_Worker.processHousehold(), de.dlr.ivf.tapas.plan.TPS_LocatedStay.selectLocation(), de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes(), de.dlr.ivf.tapas.util.parameters.ParamMatrixClass.setMatrix(), de.dlr.ivf.tapas.util.parameters.ParamMatrixMapClass.setMatrixMap(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.updateOccupancyTable(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.vacuumTempTables().
ERROR
de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR
Initial value:
=(2,
                ParamString.LOG_LEVEL_ERROR)
Definition at line 102 of file TPS_LoggingInterface.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.batchStoreTrips(), de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.binarySearch(), de.dlr.ivf.tapas.iteration.TPS_VisumConverter.calcMinMaxValue(), de.dlr.ivf.tapas.iteration.TPS_IterationManagement.calculatePlanDerivation(), de.dlr.ivf.tapas.person.TPS_Worker.call(), de.dlr.ivf.tapas.tools.TPS_CapacityCalculator.catMatchingCSVImport(), de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.change(), de.dlr.ivf.tapas.iteration.TPS_VisumConverter.checkIntraInfos(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.checkMatrixName(), de.dlr.ivf.tapas.iteration.TPS_VisumConverter.checkMatrixName(), de.dlr.ivf.tapas.runtime.util.ClientControlProperties.ClientControlProperties(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.closeConnections(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.consumeParameter(), de.dlr.ivf.tapas.runtime.util.DaemonControlProperties.DaemonControlProperties(), de.dlr.ivf.tapas.util.TPS_TripDeleter.deleteHouseholdsFromTriptable(), de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.draw(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeUpdate(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.fetchNextSetOfHouseholds(), de.dlr.ivf.tapas.runtime.util.WindowsProcessHandler.findProcess(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection(), de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.getKey(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.getNextHousehold(), de.dlr.ivf.tapas.runtime.util.CPUUsage.getWMIC(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.init(), de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.init(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.insertTrips(), de.dlr.ivf.tapas.runtime.util.WindowsProcessHandler.killProcess(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.loadHouseholds(), de.dlr.ivf.tapas.util.MatrixMap.MatrixMap(), de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.normalize(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readActivity2LocationCodes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readActivityConstantCodes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readAgeClassCodes(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.readAllParis(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readCarCodes(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.readCSVFile(), de.dlr.ivf.tapas.iteration.TPS_VisumConverter.readCSVFile(), de.dlr.ivf.tapas.tools.TPS_VisumOD2DB.readCSVFile(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readDistanceCodes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readDrivingLicenseCodes(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.readIDMap(), de.dlr.ivf.tapas.iteration.TPS_VisumConverter.readIDMap(), de.dlr.ivf.tapas.tools.TPS_VisumOD2DB.readIDMap(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readIncomeCodes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readLocationConstantCodes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.readMatrix(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.readMatrixFromDB(), de.dlr.ivf.tapas.iteration.TPS_VisumConverter.readMatrixFromDB(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.readMatrixMap(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readModes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.readParameter(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readPersonGroupCodes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readSettlementSystemCodes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readSexCodes(), de.dlr.ivf.tapas.iteration.TPS_IterationManagement.resetPlansForRecalculation(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.resetUnfinishedHouseholds(), de.dlr.ivf.tapas.runtime.util.ProcessHandler.run(), de.dlr.ivf.tapas.runtime.util.ProcessHandler.ProcesshandlerThread.run(), de.dlr.ivf.tapas.plan.TPS_LocatedStay.selectLocation(), de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes(), de.dlr.ivf.tapas.iteration.TPS_AcceptanceIterationManager.selectPlansForRecalculation(), de.dlr.ivf.tapas.iteration.TPS_BasicIterationManager.selectPlansForRecalculation(), de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.setValues(), de.dlr.ivf.tapas.persistence.io.TPS_FileConsumer.start(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.storeFinishedHouseholdIDsToDB(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.storeLocationOccupanyInDB(), de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.sum(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.updateOccupancyTable(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.vacuumTempTables().
FATAL
de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.FATAL =(1, ParamString.LOG_LEVEL_FATAL)
Definition at line 101 of file TPS_LoggingInterface.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.batchStoreTrips(), de.dlr.ivf.tapas.TPS_Main.finish(), de.dlr.ivf.tapas.mode.TPS_IndividualTransportMode.getTravelTime(), de.dlr.ivf.tapas.loc.TPS_Region.initLocationChoiceSet(), de.dlr.ivf.tapas.loc.TPS_Region.initLocationSelectModel(), de.dlr.ivf.tapas.mode.TPS_Mode.initUtilityFunction(), de.dlr.ivf.tapas.plan.acceptance.TPS_PlanEVA1Acceptance.isPlanAcceptedByOverallTravelTime(), de.dlr.ivf.tapas.iteration.TPS_VisumConverter.readMatrix(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.readMatrixMap(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readVariableMap(), de.dlr.ivf.tapas.TPS_Main.run(), de.dlr.ivf.tapas.loc.TPS_SelectLocationWeightBased.selectLocationFromChoiceSet(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.selectLocationFromChoiceSet(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.storeMatrixMap(), de.dlr.ivf.tapas.TPS_Main.TPS_Main(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.TPS_SumoConverter(), de.dlr.ivf.tapas.iteration.TPS_VisumConverter.TPS_VisumConverter(), de.dlr.ivf.tapas.iteration.TPS_VisumConverter.writeODMatrices(), and de.dlr.ivf.tapas.iteration.TPS_SumoConverter.writeTripFile().
FINE
de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.FINE =(7, ParamString.LOG_LEVEL_FINE)
Definition at line 104 of file TPS_LoggingInterface.java.
Referenced by de.dlr.ivf.tapas.loc.TPS_Region.calculateVOTadds(), de.dlr.ivf.tapas.persistence.io.TPS_FileConsumer.consumeFile(), and de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes().
FINER
de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.FINER
Initial value:
=(8,
                ParamString.LOG_LEVEL_FINER)
Definition at line 105 of file TPS_LoggingInterface.java.
FINEST
de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.FINEST =(9, ParamString.LOG_LEVEL_FINEST)
Definition at line 105 of file TPS_LoggingInterface.java.
index
final int de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.index private
Definition at line 107 of file TPS_LoggingInterface.java.
Referenced by de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.includes().
INFO
de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.INFO =(5, ParamString.LOG_LEVEL_INFO)
Definition at line 103 of file TPS_LoggingInterface.java.
Referenced by de.dlr.ivf.tapas.persistence.io.TPS_FileConsumer.consumeFile(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.createTemporaryAndOutputTables(), de.dlr.ivf.tapas.util.TPS_TripDeleter.deleteHouseholdsFromTriptable(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.fetchNextSetOfHouseholds(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.init(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.insertTrips(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.load(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.loadHouseholds(), de.dlr.ivf.tapas.util.MatrixMap.logStatistics(), de.dlr.ivf.tapas.iteration.TPS_VisumConverter.mergeMatrices(), de.dlr.ivf.tapas.iteration.TPS_VisumConverter.mergeMatrixPair(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.mergeMatrixPair(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.readCSVFile(), de.dlr.ivf.tapas.iteration.TPS_VisumConverter.readCSVFile(), de.dlr.ivf.tapas.tools.TPS_VisumOD2DB.readCSVFile(), de.dlr.ivf.scripts.SumoTripVisualization.readFile(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.readIDMap(), de.dlr.ivf.tapas.iteration.TPS_VisumConverter.readIDMap(), de.dlr.ivf.tapas.tools.TPS_VisumOD2DB.readIDMap(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readMatrices(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.readMatrix(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readMatrix(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.readMatrixMap(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readRegion(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.readRuntimeParametersFromDB(), de.dlr.ivf.tapas.iteration.TPS_IterationManagement.resetPlansForRecalculation(), de.dlr.ivf.tapas.TPS_Main.run(), de.dlr.ivf.tapas.iteration.TPS_AcceptanceIterationManager.selectPlansForRecalculation(), de.dlr.ivf.tapas.iteration.TPS_BasicIterationManager.selectPlansForRecalculation(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.storeFinishedHouseholdIDsToDB(), de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.storeInDB(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.storeInDB(), de.dlr.ivf.tapas.iteration.TPS_VisumConverter.storeIntraInfos(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.storeLocationOccupanyInDB(), de.dlr.ivf.tapas.TPS_Main.TPS_Main(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.updateOccupancyTable(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.vacuumTempTables(), de.dlr.ivf.tapas.runtime.sumoDaemon.SumoMatrixImporter.writeMatrix(), and de.dlr.ivf.tapas.iteration.TPS_VisumConverter.writeODMatrices().
key
final ParamString de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.key private
The corresponding ParamString to this log level
Definition at line 112 of file TPS_LoggingInterface.java.
OFF
de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.OFF =(0, ParamString.LOG_LEVEL_OFF)
Definition at line 101 of file TPS_LoggingInterface.java.
SEVERE
de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.SEVERE =(3, ParamString.LOG_LEVEL_SEVERE)
Definition at line 102 of file TPS_LoggingInterface.java.
Referenced by de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree.applyExpertKnowledge(), de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixed.getDistributionSet(), de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixedBS.getDistributionSet(), de.dlr.ivf.tapas.modechoice.TPS_UtilityMNL.getDistributionSet(), de.dlr.ivf.tapas.loc.TPS_Region.selectLocation(), de.dlr.ivf.tapas.mode.TPS_ModeSet.selectMode(), de.dlr.ivf.tapas.mode.TPS_ModeSet.selectMode0(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.setValue(), and de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.updateParameter().
WARN
de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.WARN
Initial value:
=(4,
                ParamString.LOG_LEVEL_WARN)
Definition at line 103 of file TPS_LoggingInterface.java.
Referenced by de.dlr.ivf.tapas.util.Timeline.add(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.addPersonToHousehold(), de.dlr.ivf.tapas.plan.TPS_Plan.balanceStarts(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.checkParameters(), de.dlr.ivf.tapas.persistence.io.TPS_FileConsumer.consumeFile(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.consumeParameter(), de.dlr.ivf.tapas.util.TPS_TripDeleter.deleteHouseholdsFromTriptable(), de.dlr.ivf.tapas.loc.TPS_CFN.getCFN4Value(), de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixed.getDistributionSet(), de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixedBS.getDistributionSet(), de.dlr.ivf.tapas.runtime.util.WindowsProcessHandler.killProcess(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.loadHouseholds(), de.dlr.ivf.tapas.util.TPS_TripDeleter.putHHID(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readCarCodes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readDrivingLicenseCodes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readMatrix(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readSexCodes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.resetUnfinishedHouseholds(), de.dlr.ivf.tapas.loc.TPS_SelectLocationWeightBased.selectLocationFromChoiceSet(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.selectLocationFromChoiceSet(), de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes(), de.dlr.ivf.tapas.iteration.TPS_AcceptanceIterationManager.selectPlansForRecalculation(), de.dlr.ivf.tapas.log.TPS_Logger.setLoggingClass(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.setValue(), de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.storeInDB(), de.dlr.ivf.tapas.iteration.TPS_SumoConverter.storeInDB(), and de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.updateParameter().
The documentation for this enum was generated from the following file:
src/main/java/de/dlr/ivf/tapas/log/TPS_LoggingInterface.java