TAPAS: de.dlr.ivf.tapas.analyzer.inputfileconverter.PersonGroup Enum Reference
de.dlr.ivf.tapas.analyzer.inputfileconverter.PersonGroup Enum Reference
Public Member Functions
PersonGroup (int id, Set< Job > jobSet)
int getId ()
Set< Job > getJobSet ()
String getName ()
Static Public Member Functions
static PersonGroup getById (int id) throws IllegalArgumentException
static PersonGroup getByJob (Job job)
Public Attributes
PG_1 =(0, generateSet(Job.JOB_5, Job.JOB_11, Job.JOB_19))
PG_2 =(1, generateSet(Job.JOB_12, Job.JOB_20))
PG_3 =(2, generateSet(Job.JOB_3, Job.JOB_9, Job.JOB_17))
PG_4 =(3, generateSet(Job.JOB_10, Job.JOB_18))
PG_5 =(4, generateSet(Job.JOB_8, Job.JOB_15, Job.JOB_23))
PG_6 =(5, generateSet(Job.JOB_16, Job.JOB_24))
PG_7 =(6, generateSet(Job.JOB_6, Job.JOB_13, Job.JOB_21))
PG_8 =(7, generateSet(Job.JOB_14, Job.JOB_22))
PG_9 =(8, generateSet(Job.JOB_25, Job.JOB_27, Job.JOB_29, Job.JOB_31))
PG_10 =(9, generateSet(Job.JOB_26, Job.JOB_28, Job.JOB_30, Job.JOB_32))
PG_11 =(10, generateSet(Job.JOB_1, Job.JOB_2))
PG_12 =(11, generateSet())
PG_13 =(12, generateSet(Job.JOB_4, Job.JOB_7))
Static Private Member Functions
static Set< Job > generateSet (Job... jobs)
Private Attributes
final int id
final Set< Job > jobSet
Detailed Description
Definition at line 15 of file PersonGroup.java.
Constructor & Destructor Documentation
PersonGroup()
de.dlr.ivf.tapas.analyzer.inputfileconverter.PersonGroup.PersonGroup (int id, Set< Job > jobSet)
Definition at line 33 of file PersonGroup.java.
Member Function Documentation
generateSet()
static Set<Job> de.dlr.ivf.tapas.analyzer.inputfileconverter.PersonGroup.generateSet (Job... jobs) static private
Definition at line 38 of file PersonGroup.java.
getById()
static PersonGroup de.dlr.ivf.tapas.analyzer.inputfileconverter.PersonGroup.getById (int id) throws IllegalArgumentException static
Parameters
id
Returns
den Wegezweck der dieser ID zugeordnet ist
Exceptions
IllegalArgumentException geworfen wenn die ID keinem Wegezweck zugeordnet werden konnte
Definition at line 48 of file PersonGroup.java.
getByJob()
static PersonGroup de.dlr.ivf.tapas.analyzer.inputfileconverter.PersonGroup.getByJob (Job job) static
Definition at line 58 of file PersonGroup.java.
getId()
int de.dlr.ivf.tapas.analyzer.inputfileconverter.PersonGroup.getId ()
Definition at line 69 of file PersonGroup.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getAvgNrOfTripsForPersonGroup(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getAvgTripDurationForPersonGroup(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getAvgTripLengthForPersonGroup(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getCountOfTripsForTripIntentionAndPersonGroupViseva(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getCountTripsPGViseva(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getModalSplitForTripIntentionAndPersonGroupVisevaAbs(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getNrOfTripsForPersonGroupViseva(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getNrOfTripsForPersonGroupVisevaAndTripIntention(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getPercentageOfTripAllocationForPersonGroupViseva(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getPercentageOfTriplengthAllocationForDistanceCategoryAndTripIntentionAndPersonGroupViseva(), and de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getPercentageOfTripLengthAllocationForTripIntentionAndPersonGroupsViseva().
getJobSet()
Set<Job> de.dlr.ivf.tapas.analyzer.inputfileconverter.PersonGroup.getJobSet ()
Definition at line 73 of file PersonGroup.java.
getName()
String de.dlr.ivf.tapas.analyzer.inputfileconverter.PersonGroup.getName ()
Definition at line 77 of file PersonGroup.java.
Member Data Documentation
id
final int de.dlr.ivf.tapas.analyzer.inputfileconverter.PersonGroup.id private
Definition at line 30 of file PersonGroup.java.
jobSet
final Set<Job> de.dlr.ivf.tapas.analyzer.inputfileconverter.PersonGroup.jobSet private
Definition at line 31 of file PersonGroup.java.
PG_1
de.dlr.ivf.tapas.analyzer.inputfileconverter.PersonGroup.PG_1 =(0, generateSet(Job.JOB_5, Job.JOB_11, Job.JOB_19))
Definition at line 16 of file PersonGroup.java.
PG_10
de.dlr.ivf.tapas.analyzer.inputfileconverter.PersonGroup.PG_10 =(9, generateSet(Job.JOB_26, Job.JOB_28, Job.JOB_30, Job.JOB_32))
Definition at line 25 of file PersonGroup.java.
PG_11
de.dlr.ivf.tapas.analyzer.inputfileconverter.PersonGroup.PG_11 =(10, generateSet(Job.JOB_1, Job.JOB_2))
Definition at line 26 of file PersonGroup.java.
PG_12
de.dlr.ivf.tapas.analyzer.inputfileconverter.PersonGroup.PG_12 =(11, generateSet())
Definition at line 27 of file PersonGroup.java.
PG_13
de.dlr.ivf.tapas.analyzer.inputfileconverter.PersonGroup.PG_13 =(12, generateSet(Job.JOB_4, Job.JOB_7))
Definition at line 28 of file PersonGroup.java.
PG_2
de.dlr.ivf.tapas.analyzer.inputfileconverter.PersonGroup.PG_2 =(1, generateSet(Job.JOB_12, Job.JOB_20))
Definition at line 17 of file PersonGroup.java.
PG_3
de.dlr.ivf.tapas.analyzer.inputfileconverter.PersonGroup.PG_3 =(2, generateSet(Job.JOB_3, Job.JOB_9, Job.JOB_17))
Definition at line 18 of file PersonGroup.java.
PG_4
de.dlr.ivf.tapas.analyzer.inputfileconverter.PersonGroup.PG_4 =(3, generateSet(Job.JOB_10, Job.JOB_18))
Definition at line 19 of file PersonGroup.java.
PG_5
de.dlr.ivf.tapas.analyzer.inputfileconverter.PersonGroup.PG_5 =(4, generateSet(Job.JOB_8, Job.JOB_15, Job.JOB_23))
Definition at line 20 of file PersonGroup.java.
PG_6
de.dlr.ivf.tapas.analyzer.inputfileconverter.PersonGroup.PG_6 =(5, generateSet(Job.JOB_16, Job.JOB_24))
Definition at line 21 of file PersonGroup.java.
PG_7
de.dlr.ivf.tapas.analyzer.inputfileconverter.PersonGroup.PG_7 =(6, generateSet(Job.JOB_6, Job.JOB_13, Job.JOB_21))
Definition at line 22 of file PersonGroup.java.
PG_8
de.dlr.ivf.tapas.analyzer.inputfileconverter.PersonGroup.PG_8 =(7, generateSet(Job.JOB_14, Job.JOB_22))
Definition at line 23 of file PersonGroup.java.
PG_9
de.dlr.ivf.tapas.analyzer.inputfileconverter.PersonGroup.PG_9 =(8, generateSet(Job.JOB_25, Job.JOB_27, Job.JOB_29, Job.JOB_31))
Definition at line 24 of file PersonGroup.java.
The documentation for this enum was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/inputfileconverter/PersonGroup.java