TAPAS: de.dlr.ivf.tapas.constants.TPS_DrivingLicenseInformation Enum Reference
de.dlr.ivf.tapas.constants.TPS_DrivingLicenseInformation Enum Reference
Public Member Functions
TPS_DrivingLicenseInformation (int code)
int getCode ()
void setCode (int code)
boolean hasDrivingLicenseInformation ()
Static Public Member Functions
static TPS_DrivingLicenseInformation getEnum (int code)
Public Attributes
UNKNOWN =(-1)
CAR =(1)
NO_DRIVING_LICENSE =(2)
Private Attributes
int code
Detailed Description
This class represents the information about driving licenses of a person. One person can have more than one driving license information. But there are restrictions about their combination.
There exist three types of information: a) no driving license (not combinable) b) no driving license information available (not combinable) c) driving license (e.g. motorbike, car, truck) (combinable)
Definition at line 20 of file TPS_DrivingLicenseInformation.java.
Constructor & Destructor Documentation
TPS_DrivingLicenseInformation()
de.dlr.ivf.tapas.constants.TPS_DrivingLicenseInformation.TPS_DrivingLicenseInformation (int code)
Parameters
code of the driving license information from the database
Definition at line 33 of file TPS_DrivingLicenseInformation.java.
References code.
Member Function Documentation
getCode()
int de.dlr.ivf.tapas.constants.TPS_DrivingLicenseInformation.getCode ()
Returns
code of TPS_DrivingLicenseInformation
Definition at line 51 of file TPS_DrivingLicenseInformation.java.
References code.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.TPS_Plan().
getEnum()
static TPS_DrivingLicenseInformation de.dlr.ivf.tapas.constants.TPS_DrivingLicenseInformation.getEnum (int code) static
Parameters
code corresponding to an TPS_DrivingLicenseInformation enum
Returns
driving license information
Definition at line 41 of file TPS_DrivingLicenseInformation.java.
References code, and de.dlr.ivf.tapas.constants.TPS_DrivingLicenseInformation.UNKNOWN.
hasDrivingLicenseInformation()
boolean de.dlr.ivf.tapas.constants.TPS_DrivingLicenseInformation.hasDrivingLicenseInformation ()
Returns
true if there is information about the driving license, i.e. in either case of CAR or NO_DRIVING_LICENSE
Definition at line 65 of file TPS_DrivingLicenseInformation.java.
setCode()
void de.dlr.ivf.tapas.constants.TPS_DrivingLicenseInformation.setCode (int code)
Parameters
code code to set
Definition at line 58 of file TPS_DrivingLicenseInformation.java.
References code.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readDrivingLicenseCodes().
Member Data Documentation
CAR
de.dlr.ivf.tapas.constants.TPS_DrivingLicenseInformation.CAR =(1)
Definition at line 22 of file TPS_DrivingLicenseInformation.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.addPersonToHousehold(), de.dlr.ivf.tapas.person.TPS_Person.hasDrivingLicense(), and de.dlr.ivf.tapas.plan.TPS_Plan.TPS_Plan().
code
int de.dlr.ivf.tapas.constants.TPS_DrivingLicenseInformation.code private
code of the driving license information from the database
Definition at line 28 of file TPS_DrivingLicenseInformation.java.
NO_DRIVING_LICENSE
de.dlr.ivf.tapas.constants.TPS_DrivingLicenseInformation.NO_DRIVING_LICENSE =(2)
Definition at line 23 of file TPS_DrivingLicenseInformation.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.addPersonToHousehold(), and de.dlr.ivf.tapas.plan.TPS_Plan.TPS_Plan().
UNKNOWN
de.dlr.ivf.tapas.constants.TPS_DrivingLicenseInformation.UNKNOWN =(-1)
Definition at line 21 of file TPS_DrivingLicenseInformation.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.addPersonToHousehold(), de.dlr.ivf.tapas.constants.TPS_DrivingLicenseInformation.getEnum(), and de.dlr.ivf.tapas.person.TPS_Person.TPS_Person().
The documentation for this enum was generated from the following file:
src/main/java/de/dlr/ivf/tapas/constants/TPS_DrivingLicenseInformation.java