TAPAS: de.dlr.ivf.tapas.util.parameters.SimulationType Enum Reference
de.dlr.ivf.tapas.util.parameters.SimulationType Enum Reference
Public Member Functions
SimulationType (int index)
int getIndex ()
Public Attributes
BASE =(0)
SCENARIO =(1)
Private Attributes
final int index
Detailed Description
The two types of simulations: basis and scenario case
Author
mark_ma
Definition at line 17 of file SimulationType.java.
Constructor & Destructor Documentation
SimulationType()
de.dlr.ivf.tapas.util.parameters.SimulationType.SimulationType (int index)
Constructor sets the index.
Parameters
index
Definition at line 30 of file SimulationType.java.
Member Function Documentation
getIndex()
int de.dlr.ivf.tapas.util.parameters.SimulationType.getIndex ()
Returns
index value
Definition at line 37 of file SimulationType.java.
Member Data Documentation
BASE
de.dlr.ivf.tapas.util.parameters.SimulationType.BASE =(0)
Definition at line 18 of file SimulationType.java.
Referenced by de.dlr.ivf.tapas.modechoice.TPS_UtilityMNL.calculateDelta(), de.dlr.ivf.tapas.mode.TPS_Mode.getCost_per_km(), de.dlr.ivf.tapas.person.TPS_Car.getKBAFuelCostPerKilometerFactor(), de.dlr.ivf.tapas.util.parameters.ParamMatrixMapClass.getMatrixFromMap(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getSimulationType(), de.dlr.ivf.tapas.mode.TPS_IndividualTransportMode.getTravelTime(), de.dlr.ivf.tapas.mode.TPS_MassTransportMode.getTravelTime(), de.dlr.ivf.tapas.mode.TPS_NonMotorisedMode.getTravelTime(), de.dlr.ivf.tapas.mode.TPS_Mode.getVariableCost_per_km(), de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.initFeesTolls(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readMatrices(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readRegion(), de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.toString(), and de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.TPS_TrafficAnalysisZone().
index
final int de.dlr.ivf.tapas.util.parameters.SimulationType.index private
index of the simulation type. This index can be used to access values in an array of size two.
Definition at line 23 of file SimulationType.java.
SCENARIO
de.dlr.ivf.tapas.util.parameters.SimulationType.SCENARIO =(1)
Definition at line 18 of file SimulationType.java.
Referenced by de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree.applyExpertKnowledge(), de.dlr.ivf.tapas.modechoice.TPS_UtilityMNL.calculateDelta(), de.dlr.ivf.tapas.plan.TPS_Plan.createOutput(), de.dlr.ivf.tapas.person.TPS_Car.FuelType.getCostPerKilometer(), de.dlr.ivf.tapas.modechoice.TPS_UtilityMNL.getDistributionSet(), de.dlr.ivf.tapas.loc.TPS_MultipleTAZRepresentant.getLocationRepresentatives(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.getLogSum(), de.dlr.ivf.tapas.util.parameters.ParamMatrixClass.getMatrix(), de.dlr.ivf.tapas.util.parameters.ParamMatrixMapClass.getMatrixFromMap(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.getModeLogSum(), de.dlr.ivf.tapas.person.TPS_Car.FuelType.getRange(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getSimulationType(), de.dlr.ivf.tapas.mode.TPS_IndividualTransportMode.getTravelTime(), de.dlr.ivf.tapas.mode.TPS_MassTransportMode.getTravelTime(), de.dlr.ivf.tapas.mode.TPS_NonMotorisedMode.getTravelTime(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessMode.getTravelTime(), de.dlr.ivf.tapas.loc.TPS_SelectWithSingleAccessMode.getTravelTime(), de.dlr.ivf.tapas.person.TPS_Car.FuelType.getVariableCostsPerKilometer(), de.dlr.ivf.tapas.person.TPS_Car.init(), de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.initFeesTolls(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readMatrices(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readRegion(), de.dlr.ivf.tapas.person.TPS_Car.refuelCar(), de.dlr.ivf.tapas.plan.TPS_LocatedStay.selectLocation(), de.dlr.ivf.tapas.mode.TPS_ModeSet.selectMode(), de.dlr.ivf.tapas.mode.TPS_ModeSet.selectMode0(), de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.setCostParkingPerHour(), de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.setCostToll(), de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.toString(), de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.TPS_TrafficAnalysisZone(), de.dlr.ivf.tapas.iteration.TPS_VisumConverter.writeODMatrices(), and de.dlr.ivf.tapas.plan.TPS_Plan.writeOutputStream().
The documentation for this enum was generated from the following file:
src/main/java/de/dlr/ivf/tapas/util/parameters/SimulationType.java