TAPAS: de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingPreferenceSupply Enum Reference
de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingPreferenceSupply Enum Reference
Public Member Functions
ShoppingPreferenceSupply (int code)
Public Attributes
Oeko =(1)
Angebot =(2)
Erlebnis =(3)
Preis =(4)
Sonstige =(0)
int code
Static Public Attributes
static ShoppingPreferenceSupply[] valueArray = ShoppingPreferenceSupply.values()
Detailed Description
Definition at line 320 of file TPS_PreferenceParameters.java.
Constructor & Destructor Documentation
ShoppingPreferenceSupply()
de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingPreferenceSupply.ShoppingPreferenceSupply (int code)
Definition at line 334 of file TPS_PreferenceParameters.java.
References code.
Member Data Documentation
Angebot
de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingPreferenceSupply.Angebot =(2)
Definition at line 324 of file TPS_PreferenceParameters.java.
Referenced by de.dlr.ivf.tapas.person.TPS_PreferenceParameters.readParams().
code
int de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingPreferenceSupply.code
Definition at line 332 of file TPS_PreferenceParameters.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.batchStoreTrips().
Erlebnis
de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingPreferenceSupply.Erlebnis =(3)
Definition at line 324 of file TPS_PreferenceParameters.java.
Referenced by de.dlr.ivf.tapas.person.TPS_PreferenceParameters.readParams().
Oeko
de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingPreferenceSupply.Oeko =(1)
I want well defined values for the coding.
Definition at line 324 of file TPS_PreferenceParameters.java.
Referenced by de.dlr.ivf.tapas.person.TPS_PreferenceParameters.readParams().
Preis
de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingPreferenceSupply.Preis =(4)
Definition at line 324 of file TPS_PreferenceParameters.java.
Referenced by de.dlr.ivf.tapas.person.TPS_PreferenceParameters.readParams().
Sonstige
de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingPreferenceSupply.Sonstige =(0)
Definition at line 324 of file TPS_PreferenceParameters.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Person.estimateAccessibilityPreference(), de.dlr.ivf.tapas.person.TPS_PreferenceParameters.readParams(), de.dlr.ivf.tapas.person.TPS_Person.selectPreferenceSupply(), and de.dlr.ivf.tapas.person.TPS_Preference.TPS_Preference().
valueArray
ShoppingPreferenceSupply [] de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingPreferenceSupply.valueArray = ShoppingPreferenceSupply.values() static
this is an static array of the members of this enum. The values()-function allocates EVERY TIME a new array, which makes your memory explode and slows down the code! see: https://stackoverflow.com/questions/2446135/is-there-a-performance-hit-when-using-enum-values-vs-string-arrays
Definition at line 330 of file TPS_PreferenceParameters.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Person.selectPreferenceSupply(), de.dlr.ivf.tapas.person.TPS_Preference.TPS_Preference(), and de.dlr.ivf.tapas.person.TPS_PreferenceParameters.TPS_PreferenceParameters().
The documentation for this enum was generated from the following file:
src/main/java/de/dlr/ivf/tapas/person/TPS_PreferenceParameters.java