TAPAS: de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingClass Enum Reference
de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingClass Enum Reference
Public Member Functions
ShoppingClass (int code)
Public Attributes
NUG =(0)
TEX =(1)
UEL =(2)
int code
Static Public Attributes
static ShoppingClass[] valueArray = ShoppingClass.values()
Detailed Description
Definition at line 303 of file TPS_PreferenceParameters.java.
Constructor & Destructor Documentation
ShoppingClass()
de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingClass.ShoppingClass (int code)
Definition at line 315 of file TPS_PreferenceParameters.java.
References code.
Member Data Documentation
code
int de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingClass.code
Definition at line 313 of file TPS_PreferenceParameters.java.
NUG
de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingClass.NUG =(0)
I want well defined values for the coding.
Definition at line 307 of file TPS_PreferenceParameters.java.
Referenced by de.dlr.ivf.tapas.scheme.TPS_Stay.getTypeOfShoppingGoods(), and de.dlr.ivf.tapas.person.TPS_PreferenceParameters.readParams().
TEX
de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingClass.TEX =(1)
Definition at line 307 of file TPS_PreferenceParameters.java.
Referenced by de.dlr.ivf.tapas.scheme.TPS_Stay.getTypeOfShoppingGoods(), and de.dlr.ivf.tapas.person.TPS_PreferenceParameters.readParams().
UEL
de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingClass.UEL =(2)
Definition at line 307 of file TPS_PreferenceParameters.java.
Referenced by de.dlr.ivf.tapas.scheme.TPS_Stay.getTypeOfShoppingGoods(), de.dlr.ivf.tapas.person.TPS_PreferenceParameters.readParams(), and de.dlr.ivf.tapas.person.TPS_Person.selectPreferenceAccessibility().
valueArray
ShoppingClass [] de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingClass.valueArray = ShoppingClass.values() static
this is an static array of the members of this enum. The values()-function allocates EVERY TIME a new array, which makes your memory explode and slows down the code! see: https://stackoverflow.com/questions/2446135/is-there-a-performance-hit-when-using-enum-values-vs-string-arrays
Definition at line 312 of file TPS_PreferenceParameters.java.
Referenced by de.dlr.ivf.tapas.person.TPS_PreferenceParameters.TPS_PreferenceParameters().
The documentation for this enum was generated from the following file:
src/main/java/de/dlr/ivf/tapas/person/TPS_PreferenceParameters.java