TAPAS: de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingPreferenceAccessibility Enum Reference
de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingPreferenceAccessibility Enum Reference
Public Member Functions
ShoppingPreferenceAccessibility (int code)
Public Attributes
Sonstige =(0)
Erreichbarkeit =(1)
Naehe =(2)
Kopplung =(3)
int code
Static Public Attributes
static ShoppingPreferenceAccessibility[] valueArray = ShoppingPreferenceAccessibility.values()
Detailed Description
Definition at line 340 of file TPS_PreferenceParameters.java.
Constructor & Destructor Documentation
ShoppingPreferenceAccessibility()
de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingPreferenceAccessibility.ShoppingPreferenceAccessibility (int code)
Definition at line 354 of file TPS_PreferenceParameters.java.
References code.
Member Data Documentation
code
int de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingPreferenceAccessibility.code
Definition at line 352 of file TPS_PreferenceParameters.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.batchStoreTrips().
Erreichbarkeit
de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingPreferenceAccessibility.Erreichbarkeit =(1)
Definition at line 344 of file TPS_PreferenceParameters.java.
Referenced by de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessMode.getTravelTime(), and de.dlr.ivf.tapas.person.TPS_PreferenceParameters.readParams().
Kopplung
de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingPreferenceAccessibility.Kopplung =(3)
Definition at line 344 of file TPS_PreferenceParameters.java.
Referenced by de.dlr.ivf.tapas.person.TPS_PreferenceParameters.readParams().
Naehe
de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingPreferenceAccessibility.Naehe =(2)
Definition at line 344 of file TPS_PreferenceParameters.java.
Referenced by de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessMode.getTravelTime(), and de.dlr.ivf.tapas.person.TPS_PreferenceParameters.readParams().
Sonstige
de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingPreferenceAccessibility.Sonstige =(0)
I want well defined values for the coding.
Definition at line 344 of file TPS_PreferenceParameters.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Person.estimateAccessibilityPreference(), de.dlr.ivf.tapas.person.TPS_PreferenceParameters.readParams(), de.dlr.ivf.tapas.person.TPS_Person.selectPreferenceAccessibility(), and de.dlr.ivf.tapas.person.TPS_Preference.TPS_Preference().
valueArray
ShoppingPreferenceAccessibility [] de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingPreferenceAccessibility.valueArray = ShoppingPreferenceAccessibility.values() static
this is an static array of the members of this enum. The values()-function allocates EVERY TIME a new array, which makes your memory explode and slows down the code! see: https://stackoverflow.com/questions/2446135/is-there-a-performance-hit-when-using-enum-values-vs-string-arrays
Definition at line 350 of file TPS_PreferenceParameters.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Person.selectPreferenceAccessibility(), de.dlr.ivf.tapas.person.TPS_Preference.TPS_Preference(), and de.dlr.ivf.tapas.person.TPS_PreferenceParameters.TPS_PreferenceParameters().
The documentation for this enum was generated from the following file:
src/main/java/de/dlr/ivf/tapas/person/TPS_PreferenceParameters.java