TAPAS: de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.PTLineType Enum Reference
de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.PTLineType Enum Reference
Public Member Functions
PTLineType (int code)
Public Attributes
Train =(0)
S =(1)
U =(2)
Tram =(3)
BRT =(4)
Bus =(5)
LowPriBus =(6)
Unknown =(7)
int code
Detailed Description
Definition at line 385 of file TPS_PTStopWeightCalculator.java.
Constructor & Destructor Documentation
PTLineType()
de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.PTLineType.PTLineType (int code)
Definition at line 389 of file TPS_PTStopWeightCalculator.java.
References code.
Member Data Documentation
BRT
de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.PTLineType.BRT =(4)
Definition at line 386 of file TPS_PTStopWeightCalculator.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.main(), and de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.printPTStatisticsPerTAZ().
Bus
de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.PTLineType.Bus =(5)
Definition at line 386 of file TPS_PTStopWeightCalculator.java.
code
int de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.PTLineType.code
Definition at line 387 of file TPS_PTStopWeightCalculator.java.
LowPriBus
de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.PTLineType.LowPriBus =(6)
Definition at line 386 of file TPS_PTStopWeightCalculator.java.
S
de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.PTLineType.S =(1)
Definition at line 386 of file TPS_PTStopWeightCalculator.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.printPTStatisticsPerTAZ().
Train
de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.PTLineType.Train =(0)
Definition at line 386 of file TPS_PTStopWeightCalculator.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.printPTStatisticsPerTAZ().
Tram
de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.PTLineType.Tram =(3)
Definition at line 386 of file TPS_PTStopWeightCalculator.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.printPTStatisticsPerTAZ().
U
de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.PTLineType.U =(2)
Definition at line 386 of file TPS_PTStopWeightCalculator.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.printPTStatisticsPerTAZ().
Unknown
de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.PTLineType.Unknown =(7)
Definition at line 386 of file TPS_PTStopWeightCalculator.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.main().
The documentation for this enum was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/TPS_PTStopWeightCalculator.java