TAPAS: de.dlr.ivf.tapas.constants.TPS_CarCode Enum Reference
de.dlr.ivf.tapas.constants.TPS_CarCode Enum Reference
Public Member Functions
TPS_CarCode (int code)
boolean fits (int amountOfCars)
Static Public Member Functions
static TPS_CarCode getEnum (int code)
Public Attributes
NO =(2)
NON_RELEVANT =(0)
YES =(1)
int code
Detailed Description
Constant for the person groups which are subdivided by the ownership of cars.
Definition at line 14 of file TPS_CarCode.java.
Constructor & Destructor Documentation
TPS_CarCode()
de.dlr.ivf.tapas.constants.TPS_CarCode.TPS_CarCode (int code)
Parameters
code of the car
Definition at line 29 of file TPS_CarCode.java.
References code.
Member Function Documentation
fits()
boolean de.dlr.ivf.tapas.constants.TPS_CarCode.fits (int amountOfCars)
This method checks whether the given amount of cars fits to the constant. If the constant is NON_RELEVANT then true is returned. In the cases NO and YES the amount has to be zero or greater than 0 to return true. False is otherwise returned.
Parameters
amountOfCars number of cars
Returns
true if the given amount of cars fits with this constant, false otherwise
Definition at line 48 of file TPS_CarCode.java.
Referenced by de.dlr.ivf.tapas.constants.TPS_PersonGroup.fits().
getEnum()
static TPS_CarCode de.dlr.ivf.tapas.constants.TPS_CarCode.getEnum (int code) static
Definition at line 33 of file TPS_CarCode.java.
References code, and de.dlr.ivf.tapas.constants.TPS_CarCode.NON_RELEVANT.
Referenced by de.dlr.ivf.tapas.constants.TPS_PersonGroup.TPS_PersonGroup().
Member Data Documentation
code
int de.dlr.ivf.tapas.constants.TPS_CarCode.code
car enumeration constant code
Definition at line 24 of file TPS_CarCode.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readCarCodes().
NO
de.dlr.ivf.tapas.constants.TPS_CarCode.NO =(2)
Enumeration of the car constants
Definition at line 19 of file TPS_CarCode.java.
NON_RELEVANT
de.dlr.ivf.tapas.constants.TPS_CarCode.NON_RELEVANT =(0)
Definition at line 19 of file TPS_CarCode.java.
Referenced by de.dlr.ivf.tapas.constants.TPS_CarCode.getEnum().
YES
de.dlr.ivf.tapas.constants.TPS_CarCode.YES =(1)
Definition at line 19 of file TPS_CarCode.java.
The documentation for this enum was generated from the following file:
src/main/java/de/dlr/ivf/tapas/constants/TPS_CarCode.java