TAPAS: de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.PersonGroup Enum Reference
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.PersonGroup Enum Reference
Public Member Functions
PersonGroup (int id, String desc, Set< Job > jobSet)
int getId ()
Set< Job > getJobSet ()
String getName ()
String toString ()
Static Public Member Functions
static PersonGroup getById (int id) throws IllegalArgumentException
static PersonGroup getByJob (Job job)
static int maxNameWidth ()
Public Attributes
PG_1 =(0, "Vollzeit/Teilzeit Frau mit Pkw", generateSet(Job.JOB_5, Job.JOB_11, Job.JOB_19, Job.JOB_36, Job.JOB_44, Job.JOB_52, Job.JOB_60))
PG_2 =(1, "Vollzeit/Teilzeit Frau ohne Pkw", generateSet(Job.JOB_12, Job.JOB_20, Job.JOB_37, Job.JOB_45, Job.JOB_53, Job.JOB_61))
PG_3 =(2, "Vollzeit/Teilzeit Mann mit Pkw", generateSet(Job.JOB_3, Job.JOB_9, Job.JOB_17, Job.JOB_34, Job.JOB_42, Job.JOB_50, Job.JOB_58))
PG_4 =(3, "Vollzeit/Teilzeit Mann ohne Pkw", generateSet(Job.JOB_10, Job.JOB_18, Job.JOB_35, Job.JOB_43, Job.JOB_51, Job.JOB_59))
PG_5 =(4, "nicht erwerbstätig Frau mit Pkw", generateSet(Job.JOB_8, Job.JOB_15, Job.JOB_23, Job.JOB_40, Job.JOB_48, Job.JOB_56, Job.JOB_64))
PG_6 =(5, "nicht erwerbstätig Frau ohne Pkw", generateSet(Job.JOB_16, Job.JOB_24, Job.JOB_41, Job.JOB_49, Job.JOB_57, Job.JOB_65))
PG_7 =(6, "nicht erwerbstätig Mann mit Pkw", generateSet(Job.JOB_6, Job.JOB_13, Job.JOB_21, Job.JOB_38, Job.JOB_46, Job.JOB_54, Job.JOB_62))
PG_8 =(7, "nicht erwerbstätig Mann ohne Pkw", generateSet(Job.JOB_14, Job.JOB_22, Job.JOB_39, Job.JOB_47, Job.JOB_55, Job.JOB_63))
PG_9 =(8, "Rentner mit Pkw", generateSet(Job.JOB_25, Job.JOB_27, Job.JOB_29, Job.JOB_31))
PG_10 =(9, "Rentner ohne Pkw", generateSet(Job.JOB_26, Job.JOB_28, Job.JOB_30, Job.JOB_32))
PG_11 =(10, "Schüler/Student/Azubi", generateSet(Job.JOB_1, Job.JOB_2, Job.JOB_33))
PG_12 =(11, "Kinder", generateSet())
PG_13
Static Private Member Functions
static Set< Job > generateSet (Job... jobs)
Private Attributes
final int id
final String desc
final Set< Job > jobSet
Detailed Description
Definition at line 717 of file TuMEnums.java.
Constructor & Destructor Documentation
PersonGroup()
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.PersonGroup.PersonGroup (int id, String desc, Set< Job > jobSet)
Definition at line 739 of file TuMEnums.java.
Member Function Documentation
generateSet()
static Set<Job> de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.PersonGroup.generateSet (Job... jobs) static private
Definition at line 745 of file TuMEnums.java.
getById()
static PersonGroup de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.PersonGroup.getById (int id) throws IllegalArgumentException static
Parameters
id
Returns
den Wegezweck der dieser ID zugeordnet ist
Exceptions
IllegalArgumentException geworfen wenn die ID keinem Wegezweck zugeordnet werden konnte
Definition at line 755 of file TuMEnums.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.getElementById().
getByJob()
static PersonGroup de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.PersonGroup.getByJob (Job job) static
Definition at line 765 of file TuMEnums.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.PersonGroupAnalyzer.assignTrip().
getId()
int de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.PersonGroup.getId ()
Definition at line 787 of file TuMEnums.java.
getJobSet()
Set<Job> de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.PersonGroup.getJobSet ()
Definition at line 791 of file TuMEnums.java.
getName()
String de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.PersonGroup.getName ()
Definition at line 795 of file TuMEnums.java.
maxNameWidth()
static int de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.PersonGroup.maxNameWidth () static
Returns the maximal number of characters the names can have.
Returns
Definition at line 779 of file TuMEnums.java.
toString()
String de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.PersonGroup.toString ()
Definition at line 800 of file TuMEnums.java.
Member Data Documentation
desc
final String de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.PersonGroup.desc private
Definition at line 736 of file TuMEnums.java.
id
final int de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.PersonGroup.id private
Definition at line 735 of file TuMEnums.java.
jobSet
final Set<Job> de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.PersonGroup.jobSet private
Definition at line 737 of file TuMEnums.java.
PG_1
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.PersonGroup.PG_1 =(0, "Vollzeit/Teilzeit Frau mit Pkw", generateSet(Job.JOB_5, Job.JOB_11, Job.JOB_19, Job.JOB_36, Job.JOB_44, Job.JOB_52, Job.JOB_60))
Definition at line 718 of file TuMEnums.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.fillBatch(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyTextWriter.processTUM(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyExcelWriter.writePersongroupData().
PG_10
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.PersonGroup.PG_10 =(9, "Rentner ohne Pkw", generateSet(Job.JOB_26, Job.JOB_28, Job.JOB_30, Job.JOB_32))
Definition at line 729 of file TuMEnums.java.
PG_11
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.PersonGroup.PG_11 =(10, "Schüler/Student/Azubi", generateSet(Job.JOB_1, Job.JOB_2, Job.JOB_33))
Definition at line 730 of file TuMEnums.java.
PG_12
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.PersonGroup.PG_12 =(11, "Kinder", generateSet())
Definition at line 731 of file TuMEnums.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.LegacyTextWriter.processTUM().
PG_13
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.PersonGroup.PG_13
Initial value:
=(12, "4 und 7: junge Erwachsene bis 24 Jahre mit und ohne PKW, erwerbstätig und nichterwerbstätig",
                generateSet(Job.JOB_4, Job.JOB_7))
Definition at line 733 of file TuMEnums.java.
PG_2
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.PersonGroup.PG_2 =(1, "Vollzeit/Teilzeit Frau ohne Pkw", generateSet(Job.JOB_12, Job.JOB_20, Job.JOB_37, Job.JOB_45, Job.JOB_53, Job.JOB_61))
Definition at line 719 of file TuMEnums.java.
PG_3
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.PersonGroup.PG_3 =(2, "Vollzeit/Teilzeit Mann mit Pkw", generateSet(Job.JOB_3, Job.JOB_9, Job.JOB_17, Job.JOB_34, Job.JOB_42, Job.JOB_50, Job.JOB_58))
Definition at line 721 of file TuMEnums.java.
PG_4
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.PersonGroup.PG_4 =(3, "Vollzeit/Teilzeit Mann ohne Pkw", generateSet(Job.JOB_10, Job.JOB_18, Job.JOB_35, Job.JOB_43, Job.JOB_51, Job.JOB_59))
Definition at line 722 of file TuMEnums.java.
PG_5
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.PersonGroup.PG_5 =(4, "nicht erwerbstätig Frau mit Pkw", generateSet(Job.JOB_8, Job.JOB_15, Job.JOB_23, Job.JOB_40, Job.JOB_48, Job.JOB_56, Job.JOB_64))
Definition at line 724 of file TuMEnums.java.
PG_6
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.PersonGroup.PG_6 =(5, "nicht erwerbstätig Frau ohne Pkw", generateSet(Job.JOB_16, Job.JOB_24, Job.JOB_41, Job.JOB_49, Job.JOB_57, Job.JOB_65))
Definition at line 725 of file TuMEnums.java.
PG_7
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.PersonGroup.PG_7 =(6, "nicht erwerbstätig Mann mit Pkw", generateSet(Job.JOB_6, Job.JOB_13, Job.JOB_21, Job.JOB_38, Job.JOB_46, Job.JOB_54, Job.JOB_62))
Definition at line 726 of file TuMEnums.java.
PG_8
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.PersonGroup.PG_8 =(7, "nicht erwerbstätig Mann ohne Pkw", generateSet(Job.JOB_14, Job.JOB_22, Job.JOB_39, Job.JOB_47, Job.JOB_55, Job.JOB_63))
Definition at line 727 of file TuMEnums.java.
PG_9
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.PersonGroup.PG_9 =(8, "Rentner mit Pkw", generateSet(Job.JOB_25, Job.JOB_27, Job.JOB_29, Job.JOB_31))
Definition at line 728 of file TuMEnums.java.
The documentation for this enum was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/tum/constants/TuMEnums.java