TAPAS: de.dlr.ivf.tapas.analyzer.inputfileconverter.Mode Enum Reference
de.dlr.ivf.tapas.analyzer.inputfileconverter.Mode Enum Reference
Public Member Functions
Mode (int id, String description)
String getDescription ()
int getId ()
String toString ()
Static Public Member Functions
static Mode getById (int id) throws IllegalArgumentException
Public Attributes
WALK =(0, "Fuß")
BIKE =(1, "Rad")
MIV =(2, "Pkw")
MIV_PASS =(3, "PkwMf")
TAXI =(4, "Taxi")
PT =(5, "ÖV")
TRAIN =(6, "Zug")
Private Attributes
final int id
final String description
Detailed Description
Definition at line 11 of file Mode.java.
Constructor & Destructor Documentation
Mode()
de.dlr.ivf.tapas.analyzer.inputfileconverter.Mode.Mode (int id, String description)
Definition at line 19 of file Mode.java.
Member Function Documentation
getById()
static Mode de.dlr.ivf.tapas.analyzer.inputfileconverter.Mode.getById (int id) throws IllegalArgumentException static
Parameters
id
Returns
den Mode der dieser ID zugeordnet ist
Exceptions
IllegalArgumentException geworfen wenn die ID keinem Wegezweck zugeordnet werden konnte
Definition at line 30 of file Mode.java.
getDescription()
String de.dlr.ivf.tapas.analyzer.inputfileconverter.Mode.getDescription ()
Definition at line 40 of file Mode.java.
getId()
int de.dlr.ivf.tapas.analyzer.inputfileconverter.Mode.getId ()
Definition at line 44 of file Mode.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getModalSplitAbs(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getModalSplitForDistanceCategoryAbs(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getModalSplitForDistanceCategoryTripIntentionAbs(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getModalSplitForTripIntentionAbs(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getModalSplitForTripIntentionAndPersonGroupTapasAbs(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getModalSplitForTripIntentionAndPersonGroupVisevaAbs(), and de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getPercentageOfTriplengthAllocationForDistanceCategoryAndMode().
toString()
String de.dlr.ivf.tapas.analyzer.inputfileconverter.Mode.toString ()
Definition at line 48 of file Mode.java.
Member Data Documentation
BIKE
de.dlr.ivf.tapas.analyzer.inputfileconverter.Mode.BIKE =(1, "Rad")
Definition at line 12 of file Mode.java.
description
final String de.dlr.ivf.tapas.analyzer.inputfileconverter.Mode.description private
Definition at line 17 of file Mode.java.
id
final int de.dlr.ivf.tapas.analyzer.inputfileconverter.Mode.id private
Definition at line 16 of file Mode.java.
MIV
de.dlr.ivf.tapas.analyzer.inputfileconverter.Mode.MIV =(2, "Pkw")
Definition at line 12 of file Mode.java.
MIV_PASS
de.dlr.ivf.tapas.analyzer.inputfileconverter.Mode.MIV_PASS =(3, "PkwMf")
Definition at line 12 of file Mode.java.
PT
de.dlr.ivf.tapas.analyzer.inputfileconverter.Mode.PT =(5, "ÖV")
Definition at line 12 of file Mode.java.
TAXI
de.dlr.ivf.tapas.analyzer.inputfileconverter.Mode.TAXI =(4, "Taxi")
Definition at line 12 of file Mode.java.
TRAIN
de.dlr.ivf.tapas.analyzer.inputfileconverter.Mode.TRAIN =(6, "Zug")
Definition at line 12 of file Mode.java.
WALK
de.dlr.ivf.tapas.analyzer.inputfileconverter.Mode.WALK =(0, "Fuß")
Definition at line 12 of file Mode.java.
The documentation for this enum was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/inputfileconverter/Mode.java