TAPAS: de.dlr.ivf.tapas.constants.TPS_Sex Enum Reference
de.dlr.ivf.tapas.constants.TPS_Sex Enum Reference
Public Member Functions
TPS_Sex (int code)
int getCode ()
Static Public Member Functions
static TPS_Sex getEnum (int code)
Public Attributes
NON_RELEVANT =(0)
MALE =(1)
FEMALE =(2)
UNKNOWN =(3)
int code
Detailed Description
Sex constant.
Definition at line 14 of file TPS_Sex.java.
Constructor & Destructor Documentation
TPS_Sex()
de.dlr.ivf.tapas.constants.TPS_Sex.TPS_Sex (int code)
Definition at line 27 of file TPS_Sex.java.
References code.
Member Function Documentation
getCode()
int de.dlr.ivf.tapas.constants.TPS_Sex.getCode ()
Definition at line 38 of file TPS_Sex.java.
References code.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.TPS_Plan().
getEnum()
static TPS_Sex de.dlr.ivf.tapas.constants.TPS_Sex.getEnum (int code) static
Definition at line 31 of file TPS_Sex.java.
References code, and de.dlr.ivf.tapas.constants.TPS_Sex.UNKNOWN.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.addPersonToHousehold(), and de.dlr.ivf.tapas.constants.TPS_PersonGroup.TPS_PersonGroup().
Member Data Documentation
code
int de.dlr.ivf.tapas.constants.TPS_Sex.code
Definition at line 25 of file TPS_Sex.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readSexCodes().
FEMALE
de.dlr.ivf.tapas.constants.TPS_Sex.FEMALE =(2)
Definition at line 22 of file TPS_Sex.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Preference.calcUtility().
MALE
de.dlr.ivf.tapas.constants.TPS_Sex.MALE =(1)
Definition at line 21 of file TPS_Sex.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Household.getNumMalePersons(), and de.dlr.ivf.tapas.person.TPS_Person.primaryDriver().
NON_RELEVANT
de.dlr.ivf.tapas.constants.TPS_Sex.NON_RELEVANT =(0)
All possible values for the sex.
Definition at line 20 of file TPS_Sex.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Household.getNumMalePersons().
UNKNOWN
de.dlr.ivf.tapas.constants.TPS_Sex.UNKNOWN =(3)
Definition at line 23 of file TPS_Sex.java.
Referenced by de.dlr.ivf.tapas.constants.TPS_Sex.getEnum().
The documentation for this enum was generated from the following file:
src/main/java/de/dlr/ivf/tapas/constants/TPS_Sex.java