TAPAS: de.dlr.ivf.tapas.analyzer.inputfileconverter.Job Enum Reference
de.dlr.ivf.tapas.analyzer.inputfileconverter.Job Enum Reference
Public Member Functions
Job (int id)
int getId ()
Static Public Member Functions
static Job getById (int job)
Public Attributes
JOB_1 =(1)
JOB_2 =(2)
JOB_3 =(3)
JOB_4 =(4)
JOB_5 =(5)
JOB_6 =(6)
JOB_7 =(7)
JOB_8 =(8)
JOB_9 =(9)
JOB_10 =(10)
JOB_11
JOB_12 =(12)
JOB_13 =(13)
JOB_14 =(14)
JOB_15 =(15)
JOB_16 =(16)
JOB_17 =(17)
JOB_18 =(18)
JOB_19 =(19)
JOB_20
JOB_21 =(21)
JOB_22 =(22)
JOB_23 =(23)
JOB_24 =(24)
JOB_25 =(25)
JOB_26 =(26)
JOB_27 =(27)
JOB_28 =(28)
JOB_29
JOB_30 =(30)
JOB_31 =(31)
JOB_32 =(32)
Private Attributes
final int id
Detailed Description
Definition at line 11 of file Job.java.
Constructor & Destructor Documentation
Job()
de.dlr.ivf.tapas.analyzer.inputfileconverter.Job.Job (int id)
Definition at line 19 of file Job.java.
Member Function Documentation
getById()
static Job de.dlr.ivf.tapas.analyzer.inputfileconverter.Job.getById (int job) static
Definition at line 23 of file Job.java.
getId()
int de.dlr.ivf.tapas.analyzer.inputfileconverter.Job.getId ()
Definition at line 32 of file Job.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getCountOfTripsForTripIntentionAndPersonGroupTapas(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getModalSplitForTripIntentionAndPersonGroupTapasAbs(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getNrOfTripsForPersonGroupTapas(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getNrOfTripsForPersonGroupTapasAndTripIntention(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getPercentageOfTripAllocationForPersonGroupTapas(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getPercentageOfTriplengthAllocationForDistanceCategoryAndTripIntentionAndPersonGroupTAPAS(), and de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getPercentageOfTripLengthAllocationForTripIntentionAndPersonGroupsTapas().
Member Data Documentation
id
final int de.dlr.ivf.tapas.analyzer.inputfileconverter.Job.id private
Definition at line 17 of file Job.java.
JOB_1
de.dlr.ivf.tapas.analyzer.inputfileconverter.Job.JOB_1 =(1)
Definition at line 12 of file Job.java.
JOB_10
de.dlr.ivf.tapas.analyzer.inputfileconverter.Job.JOB_10 =(10)
Definition at line 12 of file Job.java.
JOB_11
de.dlr.ivf.tapas.analyzer.inputfileconverter.Job.JOB_11
Initial value:
=(
            11)
Definition at line 13 of file Job.java.
JOB_12
de.dlr.ivf.tapas.analyzer.inputfileconverter.Job.JOB_12 =(12)
Definition at line 13 of file Job.java.
JOB_13
de.dlr.ivf.tapas.analyzer.inputfileconverter.Job.JOB_13 =(13)
Definition at line 13 of file Job.java.
JOB_14
de.dlr.ivf.tapas.analyzer.inputfileconverter.Job.JOB_14 =(14)
Definition at line 13 of file Job.java.
JOB_15
de.dlr.ivf.tapas.analyzer.inputfileconverter.Job.JOB_15 =(15)
Definition at line 13 of file Job.java.
JOB_16
de.dlr.ivf.tapas.analyzer.inputfileconverter.Job.JOB_16 =(16)
Definition at line 13 of file Job.java.
JOB_17
de.dlr.ivf.tapas.analyzer.inputfileconverter.Job.JOB_17 =(17)
Definition at line 13 of file Job.java.
JOB_18
de.dlr.ivf.tapas.analyzer.inputfileconverter.Job.JOB_18 =(18)
Definition at line 13 of file Job.java.
JOB_19
de.dlr.ivf.tapas.analyzer.inputfileconverter.Job.JOB_19 =(19)
Definition at line 13 of file Job.java.
JOB_2
de.dlr.ivf.tapas.analyzer.inputfileconverter.Job.JOB_2 =(2)
Definition at line 12 of file Job.java.
JOB_20
de.dlr.ivf.tapas.analyzer.inputfileconverter.Job.JOB_20
Initial value:
=(
            20)
Definition at line 14 of file Job.java.
JOB_21
de.dlr.ivf.tapas.analyzer.inputfileconverter.Job.JOB_21 =(21)
Definition at line 14 of file Job.java.
JOB_22
de.dlr.ivf.tapas.analyzer.inputfileconverter.Job.JOB_22 =(22)
Definition at line 14 of file Job.java.
JOB_23
de.dlr.ivf.tapas.analyzer.inputfileconverter.Job.JOB_23 =(23)
Definition at line 14 of file Job.java.
JOB_24
de.dlr.ivf.tapas.analyzer.inputfileconverter.Job.JOB_24 =(24)
Definition at line 14 of file Job.java.
JOB_25
de.dlr.ivf.tapas.analyzer.inputfileconverter.Job.JOB_25 =(25)
Definition at line 14 of file Job.java.
JOB_26
de.dlr.ivf.tapas.analyzer.inputfileconverter.Job.JOB_26 =(26)
Definition at line 14 of file Job.java.
JOB_27
de.dlr.ivf.tapas.analyzer.inputfileconverter.Job.JOB_27 =(27)
Definition at line 14 of file Job.java.
JOB_28
de.dlr.ivf.tapas.analyzer.inputfileconverter.Job.JOB_28 =(28)
Definition at line 14 of file Job.java.
JOB_29
de.dlr.ivf.tapas.analyzer.inputfileconverter.Job.JOB_29
Initial value:
=(
            29)
Definition at line 15 of file Job.java.
JOB_3
de.dlr.ivf.tapas.analyzer.inputfileconverter.Job.JOB_3 =(3)
Definition at line 12 of file Job.java.
JOB_30
de.dlr.ivf.tapas.analyzer.inputfileconverter.Job.JOB_30 =(30)
Definition at line 15 of file Job.java.
JOB_31
de.dlr.ivf.tapas.analyzer.inputfileconverter.Job.JOB_31 =(31)
Definition at line 15 of file Job.java.
JOB_32
de.dlr.ivf.tapas.analyzer.inputfileconverter.Job.JOB_32 =(32)
Definition at line 15 of file Job.java.
JOB_4
de.dlr.ivf.tapas.analyzer.inputfileconverter.Job.JOB_4 =(4)
Definition at line 12 of file Job.java.
JOB_5
de.dlr.ivf.tapas.analyzer.inputfileconverter.Job.JOB_5 =(5)
Definition at line 12 of file Job.java.
JOB_6
de.dlr.ivf.tapas.analyzer.inputfileconverter.Job.JOB_6 =(6)
Definition at line 12 of file Job.java.
JOB_7
de.dlr.ivf.tapas.analyzer.inputfileconverter.Job.JOB_7 =(7)
Definition at line 12 of file Job.java.
JOB_8
de.dlr.ivf.tapas.analyzer.inputfileconverter.Job.JOB_8 =(8)
Definition at line 12 of file Job.java.
JOB_9
de.dlr.ivf.tapas.analyzer.inputfileconverter.Job.JOB_9 =(9)
Definition at line 12 of file Job.java.
The documentation for this enum was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/inputfileconverter/Job.java