TAPAS: de.dlr.ivf.tapas.log.TPS_LoggingInterface Interface Reference
de.dlr.ivf.tapas.log.TPS_LoggingInterface Interface Reference
Inherited by de.dlr.ivf.tapas.log.TPS_Log4jLogger.
Classes
enum HierarchyLogLevel
enum SeverenceLogLevel
Public Member Functions
boolean closeLogger ()
boolean isLogging (Class<?> callerClass, SeverenceLogLevel sLog)
void log (Class<?> callerClass, SeverenceLogLevel sLog, String text, Throwable throwable)
void log (Class<?> callerClass, SeverenceLogLevel sLog, String text)
Detailed Description
Interface for the logging function. This interface also holds the enums for the HierarchyLogLevel and SeverenceLogLevel.
Author
hein_mh
Definition at line 19 of file TPS_LoggingInterface.java.
Member Function Documentation
closeLogger()
boolean de.dlr.ivf.tapas.log.TPS_LoggingInterface.closeLogger ()
Referenced by de.dlr.ivf.tapas.log.TPS_Logger.closeLoggers().
isLogging()
boolean de.dlr.ivf.tapas.log.TPS_LoggingInterface.isLogging (Class<?> callerClass, SeverenceLogLevel sLog)
Method to check if logging is enabled for the given parameters at the default HierarchyLogLevel.
Parameters
callerClass The calling Class
sLog The SeverenceLogLevel
Returns
true if logging is enabled for the given combination
Referenced by de.dlr.ivf.tapas.log.TPS_Logger.isLogging().
log() [1/2]
void de.dlr.ivf.tapas.log.TPS_LoggingInterface.log (Class<?> callerClass, SeverenceLogLevel sLog, String text)
Method to log an info.
Parameters
callerClass The calling class
sLog The SeverenceLogLevel
text The text to log
log() [2/2]
void de.dlr.ivf.tapas.log.TPS_LoggingInterface.log (Class<?> callerClass, SeverenceLogLevel sLog, String text, Throwable throwable)
Method to log an info and parse an Exception.
Parameters
callerClass The calling class
sLog The SeverenceLogLevel
text The text to log
throwable The exception to log
Referenced by de.dlr.ivf.tapas.log.TPS_Logger.log().
The documentation for this interface was generated from the following file:
src/main/java/de/dlr/ivf/tapas/log/TPS_LoggingInterface.java