TAPAS: de.dlr.ivf.tapas.persistence.TPS_PersistenceManager Interface Reference
de.dlr.ivf.tapas.persistence.TPS_PersistenceManager Interface Reference
Public Member Functions
void close ()
boolean finish ()
TPS_ModeSet getModeSet ()
TPS_Household getNextHousehold ()
TPS_ParameterClass getParameters ()
TPS_Region getRegion ()
TPS_SchemeSet getSchemesSet ()
boolean incrementOccupancy ()
void init ()
void resetUnfinishedHouseholds ()
void returnHousehold (TPS_Household hh)
void writePlan (TPS_Plan plan)
Detailed Description
This interface separates the software from the data structure. Behind this interface there can be implementations which base on e.g. files or a database. The interface provides all methods which are used from the application.
Author
mark_ma
Definition at line 24 of file TPS_PersistenceManager.java.
Member Function Documentation
close()
void de.dlr.ivf.tapas.persistence.TPS_PersistenceManager.close ()
Closes all open files, database connections, etc.
Implemented in de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.
Referenced by de.dlr.ivf.tapas.TPS_Main.main().
finish()
boolean de.dlr.ivf.tapas.persistence.TPS_PersistenceManager.finish ()
commit all pending data
Implemented in de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.
getModeSet()
TPS_ModeSet de.dlr.ivf.tapas.persistence.TPS_PersistenceManager.getModeSet ()
Returns a singleton instance of TPS_ModeSet.
Returns
singleton of TPS_ModeSet
Implemented in de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes().
getNextHousehold()
TPS_Household de.dlr.ivf.tapas.persistence.TPS_PersistenceManager.getNextHousehold ()
Returns
next household to process
Implemented in de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.
Referenced by de.dlr.ivf.tapas.person.TPS_Worker.call().
getParameters()
TPS_ParameterClass de.dlr.ivf.tapas.persistence.TPS_PersistenceManager.getParameters ()
This method returns the parameterClass reference
Implemented in de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.calcPlanFeasiblity(), de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixedBS.calculateDelta(), de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixedBS.getDistributionSet(), de.dlr.ivf.tapas.loc.TPS_MultipleTAZRepresentant.getLocationRepresentatives(), de.dlr.ivf.tapas.person.TPS_Worker.getParameters(), de.dlr.ivf.tapas.plan.TPS_Plan.getParameters(), de.dlr.ivf.tapas.loc.TPS_Region.initLocationChoiceSet(), de.dlr.ivf.tapas.loc.TPS_Region.initLocationSelectModel(), de.dlr.ivf.tapas.loc.TPS_Region.selectLocation(), de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes(), and de.dlr.ivf.tapas.scheme.TPS_TourPart.updateActualTravelDistances().
getRegion()
TPS_Region de.dlr.ivf.tapas.persistence.TPS_PersistenceManager.getRegion ()
Returns a singleton instance of TPS_Region.
Returns
singleton of TPS_Region
Implemented in de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.
Referenced by de.dlr.ivf.tapas.plan.TPS_LocatedStay.selectLocation().
getSchemesSet()
TPS_SchemeSet de.dlr.ivf.tapas.persistence.TPS_PersistenceManager.getSchemesSet ()
Returns a singleton instance of TPS_SchemeSet.
Returns
singleton of TPS_SchemeSet
Implemented in de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.
Referenced by de.dlr.ivf.tapas.person.TPS_Worker.createPersonPlans().
incrementOccupancy()
boolean de.dlr.ivf.tapas.persistence.TPS_PersistenceManager.incrementOccupancy ()
This method increments the occupancy and recalculates the weight of the location, the location set and the traffic analysis zone.
Implemented in de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.
init()
void de.dlr.ivf.tapas.persistence.TPS_PersistenceManager.init ()
This method initialises the the persistence manager, i.e. for the database that a connection is established and the main values are read or for files that the main path of the input files is set, etc.
Implemented in de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.
Referenced by de.dlr.ivf.tapas.TPS_Main.run().
resetUnfinishedHouseholds()
void de.dlr.ivf.tapas.persistence.TPS_PersistenceManager.resetUnfinishedHouseholds ()
This method checks if unfinished households are present in the database
Implemented in de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.
returnHousehold()
void de.dlr.ivf.tapas.persistence.TPS_PersistenceManager.returnHousehold (TPS_Household hh)
This method returns the completely processed household back to the persistence manager. This method is used for pooling the household and person objects. If you don't give the instances back you have to built always new instances instead of using the old ones by initialising them only.
Parameters
hh completely processed household
Implemented in de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.
Referenced by de.dlr.ivf.tapas.person.TPS_Worker.call().
writePlan()
void de.dlr.ivf.tapas.persistence.TPS_PersistenceManager.writePlan (TPS_Plan plan)
This method stores the current plan on a device. This device can be e.g. a database or a file.
Parameters
plan plan to write
Exceptions
Exception An exception is thrown if the plan wasn't write back to the storage medium
Implemented in de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.
Referenced by de.dlr.ivf.tapas.person.TPS_Worker.processHousehold().
The documentation for this interface was generated from the following file:
src/main/java/de/dlr/ivf/tapas/persistence/TPS_PersistenceManager.java