TAPAS: de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager Class Reference
de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager Class Reference
Classes
enum Behaviour
class LocWithOccupancy
Public Member Functions
TPS_DB_IOManager (TPS_ParameterClass parameterClass) throws IOException, ClassNotFoundException
void close ()
void createTemporaryAndOutputTables ()
void dropTemporaryTables ()
void execute (String query)
ResultSet executeQuery (String query)
boolean finish ()
void functionExecute (String function, Object... parameters)
ResultSet functionExecuteQuery (String function, Object... parameters)
TPS_DB_Connector getDbConnector ()
TPS_ModeSet getModeSet ()
TPS_Household getNextHousehold ()
TPS_ParameterClass getParameters ()
TPS_Region getRegion ()
TPS_SchemeSet getSchemesSet ()
boolean incrementOccupancy ()
void init ()
void insertTrips ()
void resetUnfinishedHouseholds ()
void returnHousehold (TPS_Household hh)
void writePlan (TPS_Plan plan)
Static Public Member Functions
static String buildQuery (TPS_ParameterClass parameterClass, String function, Object... parameters)
Static Public Attributes
static Behaviour BEHAVIOUR = Behaviour.FAT
The current behaviour of the simulation server.
Private Member Functions
void batchStoreTrips ()
void insertPlansIntoDB () throws NumberFormatException
void storeFinishedHouseholdIDsToDB ()
void storeLocationOccupanyInDB ()
Private Attributes
final TPS_DB_Connector dbConnector
The instance of a connector to the db, each thread may have its own connection.
final TPS_DB_IO dbIO
The instance of an Database IO module.
final Queue< Integer > insertedHouseHolds = new LinkedList<>()
final Queue< TPS_Plan > plansToStore = new LinkedList<>()
TPS_ModeSet modeSet
TPS_Region region
The region for this run, eg. Berlin, Hamburg etc.
TPS_SchemeSet schemeSet
Detailed Description
Class for IO management regarding Database IO like connection check, statement execution, temporary table creation, higher-level functions
Definition at line 42 of file TPS_DB_IOManager.java.
Constructor & Destructor Documentation
TPS_DB_IOManager()
de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.TPS_DB_IOManager (TPS_ParameterClass parameterClass) throws IOException, ClassNotFoundException
Constructor class: creates a new db connection, file handler, statement map and the general pattern of the trip-statement
Exceptions
ClassNotFoundException
IOException
Definition at line 62 of file TPS_DB_IOManager.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_PASSWORD, and de.dlr.ivf.tapas.util.parameters.ParamString.DB_USER.
Member Function Documentation
batchStoreTrips()
void de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.batchStoreTrips () private
Definition at line 99 of file TPS_DB_IOManager.java.
References de.dlr.ivf.tapas.plan.TPS_Plan.balanceStarts(), de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingPreferenceSupply.code, de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingPreferenceAccessibility.code, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_TRIPS, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.FATAL, de.dlr.ivf.tapas.constants.TPS_SettlementSystem.TPS_SettlementSystemType.FORDCP, de.dlr.ivf.tapas.plan.TPS_Plan.getAcceptanceProbability(), de.dlr.ivf.tapas.scheme.TPS_Episode.getActCode(), de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.getBbrType(), de.dlr.ivf.tapas.loc.TPS_Location.getBlock(), de.dlr.ivf.tapas.plan.TPS_Plan.getBudgetAcceptanceProbability(), de.dlr.ivf.tapas.constants.TPS_PersonGroup.getCode(), de.dlr.ivf.tapas.constants.TPS_ActivityConstant.getCode(), de.dlr.ivf.tapas.constants.TPS_SettlementSystem.getCode(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection(), de.dlr.ivf.tapas.loc.TPS_Location.getCoordinate(), de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.getDistance(), de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.getDistanceBeeline(), de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.getDuration(), de.dlr.ivf.tapas.person.TPS_Person.getHousehold(), de.dlr.ivf.tapas.loc.TPS_Block.getId(), de.dlr.ivf.tapas.loc.TPS_Location.getId(), de.dlr.ivf.tapas.person.TPS_Household.getId(), de.dlr.ivf.tapas.person.TPS_Person.getId(), de.dlr.ivf.tapas.scheme.TPS_Scheme.getId(), de.dlr.ivf.tapas.plan.TPS_Plan.getLocatedStay(), de.dlr.ivf.tapas.person.TPS_Household.getLocation(), de.dlr.ivf.tapas.plan.TPS_LocatedStay.getLocation(), de.dlr.ivf.tapas.mode.TPS_ExtMode.getMCTCode(), de.dlr.ivf.tapas.plan.TPS_PlannedTrip.getMode(), de.dlr.ivf.tapas.plan.TPS_Plan.getPerson(), de.dlr.ivf.tapas.person.TPS_Person.getPersonGroup(), de.dlr.ivf.tapas.plan.TPS_Plan.getPlannedTrip(), de.dlr.ivf.tapas.plan.TPS_Plan.getScheme(), de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.getStart(), de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.getTAZId(), de.dlr.ivf.tapas.plan.TPS_Plan.getTimeAcceptanceProbability(), de.dlr.ivf.tapas.scheme.TPS_Scheme.getTourPartIterator(), de.dlr.ivf.tapas.loc.TPS_Location.getTrafficAnalysisZone(), de.dlr.ivf.tapas.loc.TPS_Coordinate.getValue(), de.dlr.ivf.tapas.loc.TPS_Location.hasBlock(), de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.hasToll(), de.dlr.ivf.tapas.scheme.TPS_Stay.isAtHome(), de.dlr.ivf.tapas.scheme.TPS_Stay.locationChoiceMotive, de.dlr.ivf.tapas.scheme.TPS_Stay.locationChoiceMotiveSupply, de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.plan.TPS_Plan.reset(), and de.dlr.ivf.tapas.constants.TPS_ActivityConstant.TPS_ActivityCodeType.ZBE.
buildQuery()
static String de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.buildQuery (TPS_ParameterClass parameterClass, String function, Object... parameters) static
Method to build a sql-function from the given parameters
Parameters
parameterClass parameter class reference
function The name of the sql-function to call
parameters A set of parameters for the sql-function
Returns
A String which holds the complete SQL-Query.
Definition at line 76 of file TPS_DB_IOManager.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_SCHEMA_CORE, and de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString().
Referenced by de.dlr.ivf.tapas.util.TPS_TripDeleter.deleteHouseholdsFromTriptable().
close()
void de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.close ()
Closes all open files, database connections, etc.
Implements de.dlr.ivf.tapas.persistence.TPS_PersistenceManager.
Definition at line 257 of file TPS_DB_IOManager.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.closeConnections().
createTemporaryAndOutputTables()
void de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.createTemporaryAndOutputTables ()
Definition at line 261 of file TPS_DB_IOManager.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.HierarchyLogLevel.CLIENT, de.dlr.ivf.tapas.util.parameters.ParamValue.DB_HH_SAMPLE_SIZE, de.dlr.ivf.tapas.util.parameters.ParamString.DB_HOUSEHOLD_AND_PERSON_KEY, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_HOUSEHOLD, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_HOUSEHOLD_TMP, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_LOCATION, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_LOCATION_TMP, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_PERSON, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_TRIPS, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.INFO, de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), de.dlr.ivf.tapas.log.TPS_Logger.log(), and de.dlr.ivf.tapas.util.parameters.ParamValue.RANDOM_SEED_NUMBER.
Referenced by de.dlr.ivf.tapas.TPS_Main.init().
dropTemporaryTables()
void de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.dropTemporaryTables ()
Definition at line 292 of file TPS_DB_IOManager.java.
References de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_DELETE_TEMPORARY_TABLES.
Referenced by de.dlr.ivf.tapas.TPS_Main.finish().
execute()
void de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.execute (String query)
Method to execute a SQL-Query without any results
Parameters
query The query to execute
Exceptions
SQLException
Definition at line 304 of file TPS_DB_IOManager.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute().
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.vacuumTempTables().
executeQuery()
ResultSet de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.executeQuery (String query)
Method to execute a SQL-Query witch provides an result set
Parameters
query The sql-query
Returns
A SQL ResultSet containing the result
Definition at line 314 of file TPS_DB_IOManager.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery().
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.fetchNextSetOfHouseholds(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.getTrafficAnalysisZonesAround(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.loadHouseholds(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readActivity2LocationCodes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readActivityConstantCodes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readAgeClassCodes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readCarCodes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readDistanceCodes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readDrivingLicenseCodes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readExpertKnowledgeTree(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readIncomeCodes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readLocationConstantCodes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readMatrix(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readModeChoiceTree(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readModes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readPersonGroupCodes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readRegion(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readSchemeSet(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readSettlementSystemCodes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readSexCodes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readUtilityFunction(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.updateOccupancyTable(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.vacuumTempTables().
finish()
boolean de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.finish ()
Commit pending data and finish all db connections.
Implements de.dlr.ivf.tapas.persistence.TPS_PersistenceManager.
Definition at line 321 of file TPS_DB_IOManager.java.
functionExecute()
void de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.functionExecute (String function, Object... parameters)
Method to execute a function. Calls buildQuery and execute
Parameters
function The name of the function
parameters The parameters for the function
Definition at line 334 of file TPS_DB_IOManager.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.returnHousehold(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.vacuumTempTables().
functionExecuteQuery()
ResultSet de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.functionExecuteQuery (String function, Object... parameters)
Method to execute a function. Calls buildQuery and executeQuery
Parameters
function The name of the function
parameters The parameters for the function
Returns
A SQL ResultSet containing the result
Definition at line 345 of file TPS_DB_IOManager.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readMatrices().
getDbConnector()
TPS_DB_Connector de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.getDbConnector ()
Returns
the dbConnector
Definition at line 352 of file TPS_DB_IOManager.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.fetchNextSetOfHouseholds(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readMatrix(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readSettlementSystemCodes(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.vacuumTempTables().
getModeSet()
TPS_ModeSet de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.getModeSet ()
Returns a singleton instance of TPS_ModeSet.
Returns
singleton of TPS_ModeSet
Implements de.dlr.ivf.tapas.persistence.TPS_PersistenceManager.
Definition at line 361 of file TPS_DB_IOManager.java.
Referenced by de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessMode.getTravelTime(), and de.dlr.ivf.tapas.loc.TPS_SelectWithSingleAccessMode.getTravelTime().
getNextHousehold()
TPS_Household de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.getNextHousehold ()
Returns
next household to process
Implements de.dlr.ivf.tapas.persistence.TPS_PersistenceManager.
Definition at line 370 of file TPS_DB_IOManager.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.DEBUG, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), and de.dlr.ivf.tapas.log.TPS_Logger.log().
getParameters()
TPS_ParameterClass de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.getParameters ()
This method returns the parameterClass reference
Implements de.dlr.ivf.tapas.persistence.TPS_PersistenceManager.
Definition at line 385 of file TPS_DB_IOManager.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getParameters().
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.addPersonToHousehold(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.fetchNextSetOfHouseholds(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.getTrafficAnalysisZonesAround(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.loadHouseholds(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readActivity2LocationCodes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readActivityConstantCodes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readAgeClassCodes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readCarCodes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readDistanceCodes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readDrivingLicenseCodes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readExpertKnowledgeTree(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readIncomeCodes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readLocationConstantCodes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readMatrices(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readMatrix(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readModeChoiceTree(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readModes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readPersonGroupCodes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readRegion(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readSchemeSet(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readSettlementSystemCodes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readSexCodes(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readUtilityFunction(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.returnHousehold(), de.dlr.ivf.tapas.loc.TPS_SelectLocationWeightBased.selectLocationFromChoiceSet(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.selectLocationFromChoiceSet(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.TPS_DB_IO(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.updateOccupancyTable(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.vacuumTempTables().
getRegion()
TPS_Region de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.getRegion ()
Returns a singleton instance of TPS_Region.
Returns
singleton of TPS_Region
Implements de.dlr.ivf.tapas.persistence.TPS_PersistenceManager.
Definition at line 394 of file TPS_DB_IOManager.java.
getSchemesSet()
TPS_SchemeSet de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.getSchemesSet ()
Returns a singleton instance of TPS_SchemeSet.
Returns
singleton of TPS_SchemeSet
Implements de.dlr.ivf.tapas.persistence.TPS_PersistenceManager.
Definition at line 404 of file TPS_DB_IOManager.java.
incrementOccupancy()
boolean de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.incrementOccupancy ()
This method increments the occupancy and recalculates the weight of the location, the location set and the traffic analysis zone.
Implements de.dlr.ivf.tapas.persistence.TPS_PersistenceManager.
Definition at line 414 of file TPS_DB_IOManager.java.
init()
void de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.init ()
This method initialises the the persistence manager, i.e. for the database that a connection is established and the main values are read or for files that the main path of the input files is set, etc.
Implements de.dlr.ivf.tapas.persistence.TPS_PersistenceManager.
Definition at line 425 of file TPS_DB_IOManager.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.clearConstants(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.HierarchyLogLevel.CLIENT, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.INFO, de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.initStart(), de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readMatrices(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readModeChoiceTree(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readRegion(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readSchemeSet(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readUtilityFunction().
insertPlansIntoDB()
void de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.insertPlansIntoDB () throws NumberFormatException private
Definition at line 486 of file TPS_DB_IOManager.java.
insertTrips()
void de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.insertTrips ()
Method to insert all pending Trips.
Definition at line 498 of file TPS_DB_IOManager.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.DEBUG, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.INFO, de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), de.dlr.ivf.tapas.log.TPS_Logger.log(), and de.dlr.ivf.tapas.log.TPS_LoggingInterface.HierarchyLogLevel.THREAD.
resetUnfinishedHouseholds()
void de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.resetUnfinishedHouseholds ()
This method checks if unfinished households are present in the database
Implements de.dlr.ivf.tapas.persistence.TPS_PersistenceManager.
Definition at line 517 of file TPS_DB_IOManager.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.runtime.util.IPInfo.getEthernetInetAddress(), de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.util.parameters.ParamString.RUN_IDENTIFIER, and de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.WARN.
returnHousehold()
void de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.returnHousehold (TPS_Household hh)
This method returns the completely processed household back to the persistence manager. This method is used for pooling the household and person objects. If you don't give the instances back you have to built always new instances instead of using the old ones by initialising them only.
Parameters
hh completely processed household
Implements de.dlr.ivf.tapas.persistence.TPS_PersistenceManager.
Definition at line 546 of file TPS_DB_IOManager.java.
References de.dlr.ivf.tapas.person.TPS_Household.getId().
storeFinishedHouseholdIDsToDB()
void de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.storeFinishedHouseholdIDsToDB () private
Definition at line 552 of file TPS_DB_IOManager.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_HOUSEHOLD_TMP, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.INFO, de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), and de.dlr.ivf.tapas.log.TPS_Logger.log().
storeLocationOccupanyInDB()
void de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.storeLocationOccupanyInDB () private
Definition at line 638 of file TPS_DB_IOManager.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_LOCATION_TMP, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.INFO, de.dlr.ivf.tapas.scheme.TPS_Episode.isHomePart, de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), and de.dlr.ivf.tapas.log.TPS_Logger.log().
writePlan()
void de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.writePlan (TPS_Plan plan)
This method stores the current plan on a device. This device can be e.g. a database or a file.
Parameters
plan plan to write
Exceptions
Exception An exception is thrown if the plan wasn't write back to the storage medium
Implements de.dlr.ivf.tapas.persistence.TPS_PersistenceManager.
Definition at line 735 of file TPS_DB_IOManager.java.
Member Data Documentation
BEHAVIOUR
Behaviour de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.BEHAVIOUR = Behaviour.FAT static
The current behaviour of the simulation server.
Definition at line 44 of file TPS_DB_IOManager.java.
Referenced by de.dlr.ivf.tapas.util.TPS_TripDeleter.deleteHouseholdsFromTriptable(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.getTrafficAnalysisZonesAround(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.returnHousehold().
dbConnector
final TPS_DB_Connector de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.dbConnector private
The instance of a connector to the db, each thread may have its own connection.
Definition at line 46 of file TPS_DB_IOManager.java.
dbIO
final TPS_DB_IO de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.dbIO private
The instance of an Database IO module.
Definition at line 48 of file TPS_DB_IOManager.java.
insertedHouseHolds
final Queue<Integer> de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.insertedHouseHolds = new LinkedList<>() private
Definition at line 49 of file TPS_DB_IOManager.java.
modeSet
TPS_ModeSet de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.modeSet private
Definition at line 51 of file TPS_DB_IOManager.java.
plansToStore
final Queue<TPS_Plan> de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.plansToStore = new LinkedList<>() private
Definition at line 50 of file TPS_DB_IOManager.java.
region
TPS_Region de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.region private
The region for this run, eg. Berlin, Hamburg etc.
Definition at line 53 of file TPS_DB_IOManager.java.
schemeSet
TPS_SchemeSet de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.schemeSet private
Definition at line 54 of file TPS_DB_IOManager.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/persistence/db/TPS_DB_IOManager.java