TAPAS: de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute Class Reference
de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute Class Reference
Classes
class BlockInDB
class ConversionUnitToCapacity
class LocationInDB
class VolumeDistribution
Public Member Functions
GroupToDistribute (TPS_DB_Connector dbCon, String region)
void adaptCapacities ()
void exportOpportunityOutputToCSV (String fileName)
void exportUpdatedCapacitiesToCSV (String fileName)
void initRegionsFromTazGrouper (String name)
void processOpportunities (String opportunityDistribution)
void setSqlRegionsDirectly (HashMap< Integer, String > sqlQueryForRegions)
Static Public Member Functions
static String generateConversionUnitToCapacityKey (String type, String unit)
Private Member Functions
int areaToOpportunity (int code, double area, boolean workPlace)
int capacityToOpportunity (LocationInDB loc, boolean workPlace)
void fillLocationList (int map_id, int volume, int[] locationCodes)
BlockInDB findBlockAndAdressForDLMObject (int id)
int pickOpportunitiesFromList (int volume, String idPrefix)
Private Attributes
HashMap< Integer, String > sqlQueryForRegions = new HashMap<>()
Static Private Attributes
static final String opportunityDistributionTableSuffix = "_opportunity_distribution"
static final String dlm_table = "core.gis_dlm_fot"
static final String preFixLocation = "location_"
static final String preFixDLM = "dlm_"
Detailed Description
Definition at line 24 of file GroupToDistribute.java.
Constructor & Destructor Documentation
GroupToDistribute()
de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.GroupToDistribute (TPS_DB_Connector dbCon, String region)
Definition at line 42 of file GroupToDistribute.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery().
Member Function Documentation
adaptCapacities()
void de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.adaptCapacities ()
Definition at line 99 of file GroupToDistribute.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), and de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.generateConversionUnitToCapacityKey().
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.OpportunityDistribution.main().
areaToOpportunity()
int de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.areaToOpportunity (int code, double area, boolean workPlace) private
Definition at line 127 of file GroupToDistribute.java.
References code.
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.fillLocationList().
capacityToOpportunity()
int de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.capacityToOpportunity (LocationInDB loc, boolean workPlace) private
Definition at line 150 of file GroupToDistribute.java.
References de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.generateConversionUnitToCapacityKey().
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.fillLocationList().
exportOpportunityOutputToCSV()
void de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.exportOpportunityOutputToCSV (String fileName)
Definition at line 161 of file GroupToDistribute.java.
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.OpportunityDistribution.main().
exportUpdatedCapacitiesToCSV()
void de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.exportUpdatedCapacitiesToCSV (String fileName)
Definition at line 182 of file GroupToDistribute.java.
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.OpportunityDistribution.main().
fillLocationList()
void de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.fillLocationList (int map_id, int volume, int[] locationCodes) private
Definition at line 197 of file GroupToDistribute.java.
References de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.areaToOpportunity(), de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.capacityToOpportunity(), code, de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.dlm_table, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.findBlockAndAdressForDLMObject(), de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.pickOpportunitiesFromList(), de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.preFixDLM, and de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.preFixLocation.
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.processOpportunities().
findBlockAndAdressForDLMObject()
BlockInDB de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.findBlockAndAdressForDLMObject (int id) private
Definition at line 299 of file GroupToDistribute.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery().
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.fillLocationList().
generateConversionUnitToCapacityKey()
static String de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.generateConversionUnitToCapacityKey (String type, String unit) static
Definition at line 94 of file GroupToDistribute.java.
References type.
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.adaptCapacities(), and de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.capacityToOpportunity().
initRegionsFromTazGrouper()
void de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.initRegionsFromTazGrouper (String name)
This method initates a adapter to load a specific TAZ mapping for the given region and fills the internal sql-queries
Parameters
name the name of the mapping
Definition at line 363 of file GroupToDistribute.java.
References de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ.getMappingValues(), de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ.getShapeSQLQuery(), de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ.initRegion(), de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToTAZ.loadMapping(), and name.
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.OpportunityDistribution.main().
pickOpportunitiesFromList()
int de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.pickOpportunitiesFromList (int volume, String idPrefix) private
Definition at line 374 of file GroupToDistribute.java.
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.fillLocationList().
processOpportunities()
void de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.processOpportunities (String opportunityDistribution)
Definition at line 402 of file GroupToDistribute.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.extractIntArray(), de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.fillLocationList(), and de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.opportunityDistributionTableSuffix.
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.OpportunityDistribution.main().
setSqlRegionsDirectly()
void de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.setSqlRegionsDirectly (HashMap< Integer, String > sqlQueryForRegions)
This method initiates a adapter to load a specific TAZ mapping for the given region and fills the internal sql-queries
Parameters
sqlQueryForRegions
Definition at line 440 of file GroupToDistribute.java.
References de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.sqlQueryForRegions.
Member Data Documentation
dlm_table
final String de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.dlm_table = "core.gis_dlm_fot" static private
Definition at line 27 of file GroupToDistribute.java.
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.fillLocationList().
opportunityDistributionTableSuffix
final String de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.opportunityDistributionTableSuffix = "_opportunity_distribution" static private
Definition at line 26 of file GroupToDistribute.java.
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.processOpportunities().
preFixDLM
final String de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.preFixDLM = "dlm_" static private
Definition at line 29 of file GroupToDistribute.java.
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.fillLocationList().
preFixLocation
final String de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.preFixLocation = "location_" static private
Definition at line 28 of file GroupToDistribute.java.
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.fillLocationList().
sqlQueryForRegions
HashMap<Integer, String> de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.sqlQueryForRegions = new HashMap<>() private
Definition at line 40 of file GroupToDistribute.java.
Referenced by de.dlr.ivf.tapas.tools.OpportunityDistribution.GroupToDistribute.setSqlRegionsDirectly().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/OpportunityDistribution/GroupToDistribute.java