TAPAS: de.dlr.ivf.tapas.util.parameters.ParamMatrixMapClass Class Reference
de.dlr.ivf.tapas.util.parameters.ParamMatrixMapClass Class Reference
Public Member Functions
void clear (ParamMatrixMap param)
MatrixMap getMatrixMap (ParamMatrixMap param, SimulationType type)
ParamType getType (ParamMatrixMap param)
double getValue (ParamMatrixMap param, int i, int j, int time)
double getValue (ParamMatrixMap param, int i, int j, SimulationType type, int time)
boolean isDefined (ParamMatrixMap param)
void setMatrix (ParamMatrixMap param, Matrix matrix)
void setMatrix (ParamMatrixMap param, Matrix matrix, SimulationType type)
void setMatrixMap (ParamMatrixMap param, MatrixMap matrixMap)
void setMatrixMap (ParamMatrixMap param, MatrixMap matrixMap, SimulationType type)
void setMatrixMap (ParamMatrixMap param, double[] distribution, Matrix[] matrices)
void setMatrixMap (ParamMatrixMap param, double[] distribution, Matrix[] matrices, SimulationType type)
String toRawString (ParamMatrixMap param)
Private Member Functions
Matrix getMatrixFromMap (ParamMatrixMap param, int time)
Matrix getMatrixFromMap (ParamMatrixMap param, SimulationType type, int time)
Private Attributes
final EnumMap< ParamMatrixMap, MutablePair< ParamType, MatrixMap[]> > paramMatrixMaps
Detailed Description
Definition at line 20 of file ParamMatrixMapClass.java.
Member Function Documentation
clear()
void de.dlr.ivf.tapas.util.parameters.ParamMatrixMapClass.clear (ParamMatrixMap param)
This method clears all matrix maps.
Parameters
param matrix map parameter enum
Definition at line 61 of file ParamMatrixMapClass.java.
getMatrixFromMap() [1/2]
Matrix de.dlr.ivf.tapas.util.parameters.ParamMatrixMapClass.getMatrixFromMap (ParamMatrixMap param, int time) private
If there exist only one matrixMap, the matrix for the given time of this map is returned. If there exists two matrixMaps the matrix for the given time is returned which matrixMap corresponds to the scenario type.
Parameters
param matrix map parameter enum
time the time slot for the requested matrix
Returns
one matrix of the enum constant
Exceptions
RuntimeException if the constant was not defined
Definition at line 76 of file ParamMatrixMapClass.java.
References de.dlr.ivf.tapas.util.parameters.SimulationType.BASE, de.dlr.ivf.tapas.util.parameters.SimulationType.SCENARIO, and type.
Referenced by de.dlr.ivf.tapas.util.parameters.ParamMatrixMapClass.getValue().
getMatrixFromMap() [2/2]
Matrix de.dlr.ivf.tapas.util.parameters.ParamMatrixMapClass.getMatrixFromMap (ParamMatrixMap param, SimulationType type, int time) private
The matrix for the given time of the matrixMap corresponding to the given simulation type is returned.
Parameters
param matrix map parameter enum
time the time slot for the requested matrix
type simulation type
Returns
matrix corresponding to the given simulation type
Exceptions
RuntimeException if the constant was not defined or the constant is not simulation type dependent
Definition at line 96 of file ParamMatrixMapClass.java.
References type.
getMatrixMap()
MatrixMap de.dlr.ivf.tapas.util.parameters.ParamMatrixMapClass.getMatrixMap (ParamMatrixMap param, SimulationType type)
This method gets the whole MatrixMap for the given SimulationType
Parameters
param matrix map parameter enum
type SimulationType for this request
Returns
the MatrixMap for the given SimulationType
Definition at line 113 of file ParamMatrixMapClass.java.
References type.
Referenced by de.dlr.ivf.tapas.iteration.TPS_VisumConverter.writeODMatrices().
getType()
ParamType de.dlr.ivf.tapas.util.parameters.ParamMatrixMapClass.getType (ParamMatrixMap param)
Parameters
param matrix map parameter enum
Returns
parameter type
Definition at line 127 of file ParamMatrixMapClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamMatrixMapClass.paramMatrixMaps.
Referenced by de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getType().
getValue() [1/2]
double de.dlr.ivf.tapas.util.parameters.ParamMatrixMapClass.getValue (ParamMatrixMap param, int i, int j, int time)
This method uses the getMatrixFromMap(time) method so it returns the value corresponding to the current simulation type and to the given time.
Parameters
param matrix map parameter enum
i line position
j column position
time the time slot for the requested matrix
Returns
value at position (i,j)
Exceptions
RuntimeException if the constant was not defined
Definition at line 143 of file ParamMatrixMapClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamMatrixMapClass.getMatrixFromMap(), and de.dlr.ivf.tapas.util.Matrix.getValue().
Referenced by de.dlr.ivf.tapas.mode.TPS_IndividualTransportMode.getTravelTime(), and de.dlr.ivf.tapas.mode.TPS_NonMotorisedMode.getTravelTime().
getValue() [2/2]
double de.dlr.ivf.tapas.util.parameters.ParamMatrixMapClass.getValue (ParamMatrixMap param, int i, int j, SimulationType type, int time)
This method uses the getMatrix(SimulationType type, double time) method so it returns the value corresponding to the given simulation type.
Parameters
param matrix map parameter enum
i line position
j column position
type simulation type
time the time slot for the requested matrix
Returns
value at position (i,j)
Exceptions
RuntimeException if the constant was not defined
Definition at line 160 of file ParamMatrixMapClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamMatrixMapClass.getMatrixFromMap(), de.dlr.ivf.tapas.util.Matrix.getValue(), and type.
isDefined()
boolean de.dlr.ivf.tapas.util.parameters.ParamMatrixMapClass.isDefined (ParamMatrixMap param)
Flag if matrix has been instantiated
Parameters
param matrix map parameter enum
Returns
true, if matrix is defined, false else
Definition at line 170 of file ParamMatrixMapClass.java.
Referenced by de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isDefined(), and de.dlr.ivf.tapas.util.parameters.ParamMatrixMapClass.toRawString().
setMatrix() [1/2]
void de.dlr.ivf.tapas.util.parameters.ParamMatrixMapClass.setMatrix (ParamMatrixMap param, Matrix matrix)
This method sets one matrixMap in the array, which contains only one matrix. This method is for constants which don't depend on the simulation type
Parameters
param matrix map parameter enum
matrix new matrix to set
Exceptions
RuntimeException if matrix map is simulation dependent and no simulation type is set
Definition at line 188 of file ParamMatrixMapClass.java.
setMatrix() [2/2]
void de.dlr.ivf.tapas.util.parameters.ParamMatrixMapClass.setMatrix (ParamMatrixMap param, Matrix matrix, SimulationType type)
This method sets one matrix in the array, which contains only one matrix. This method is for constants which do depend on the simulation type
Parameters
param matrix map parameter enum
matrix new matrix to set
type simulation type
Exceptions
RuntimeException if the parameter is independent from the simulation type
Definition at line 209 of file ParamMatrixMapClass.java.
References type.
setMatrixMap() [1/4]
void de.dlr.ivf.tapas.util.parameters.ParamMatrixMapClass.setMatrixMap (ParamMatrixMap param, double[] distribution, Matrix[] matrices)
This method sets one matrixMap in the array, which contains a set of matrices with a given time distribution. This method is for constants which don't depend on the simulation type
Parameters
param matrix map parameter enum
distribution the time distribution for the given matrixset
matrices new matrixset to set
Exceptions
RuntimeException if matrix map is simulation dependent and no simulation type is set or distribution and matrices length does not match
Definition at line 276 of file ParamMatrixMapClass.java.
setMatrixMap() [2/4]
void de.dlr.ivf.tapas.util.parameters.ParamMatrixMapClass.setMatrixMap (ParamMatrixMap param, double[] distribution, Matrix[] matrices, SimulationType type)
This method sets one matrix in the array, which contains only one matrix. This method is for constants which do depend on the simulation type
Parameters
param matrix map parameter enum
distribution the time distribution for the given matrixset
matrices new matrixset to set
type simulation type
Exceptions
RuntimeException if matrix map is simulation independent or distribution and matrices length does not match
Definition at line 299 of file ParamMatrixMapClass.java.
References type.
setMatrixMap() [3/4]
void de.dlr.ivf.tapas.util.parameters.ParamMatrixMapClass.setMatrixMap (ParamMatrixMap param, MatrixMap matrixMap)
This method sets one matrixMap in the array. This method is for constants which don't depend on the simulation type
Parameters
param matrix map parameter enum
matrixMap new matrixMap to set
Exceptions
RuntimeException if matrix map is simulation dependent and no simulation type is set
Definition at line 228 of file ParamMatrixMapClass.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.DEBUG, and de.dlr.ivf.tapas.log.TPS_Logger.log().
Referenced by de.dlr.ivf.tapas.iteration.TPS_VisumConverter.readMatrix(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readMatrix().
setMatrixMap() [4/4]
void de.dlr.ivf.tapas.util.parameters.ParamMatrixMapClass.setMatrixMap (ParamMatrixMap param, MatrixMap matrixMap, SimulationType type)
This method sets one matrixMap in the array. This method is for constants which do depend on the simulation type
Parameters
param matrix map parameter enum
matrixMap new matrixMap to set
type simulation type
Exceptions
RuntimeException if the parameter is independent from the simulation type
Definition at line 250 of file ParamMatrixMapClass.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.DEBUG, de.dlr.ivf.tapas.log.TPS_Logger.log(), and type.
toRawString()
String de.dlr.ivf.tapas.util.parameters.ParamMatrixMapClass.toRawString (ParamMatrixMap param)
Method to return the RAW values of all matrix maps
Parameters
param matrix map parameter enum
Returns
A String containing the RAW Values of the matrix map array.
Definition at line 316 of file ParamMatrixMapClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamMatrixMapClass.isDefined(), and de.dlr.ivf.tapas.util.parameters.ParamMatrixMapClass.paramMatrixMaps.
Member Data Documentation
paramMatrixMaps
final EnumMap<ParamMatrixMap, MutablePair<ParamType, MatrixMap[]> > de.dlr.ivf.tapas.util.parameters.ParamMatrixMapClass.paramMatrixMaps private
Definition at line 21 of file ParamMatrixMapClass.java.
Referenced by de.dlr.ivf.tapas.util.parameters.ParamMatrixMapClass.getType(), and de.dlr.ivf.tapas.util.parameters.ParamMatrixMapClass.toRawString().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/util/parameters/ParamMatrixMapClass.java