TAPAS: de.dlr.ivf.tapas.runtime.server.SimulationDaemon.ServerProcessChecker Class Reference
de.dlr.ivf.tapas.runtime.server.SimulationDaemon.ServerProcessChecker Class Reference
Public Member Functions
void run ()
Detailed Description
Definition at line 172 of file SimulationDaemon.java.
Member Function Documentation
run()
void de.dlr.ivf.tapas.runtime.server.SimulationDaemon.ServerProcessChecker.run ()
Definition at line 175 of file SimulationDaemon.java.
References de.dlr.ivf.tapas.runtime.server.SimulationDaemon.con, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_SERVERS, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getParameters(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.runtime.server.SimulationDaemon.hostname, and de.dlr.ivf.tapas.runtime.server.SimulationDaemon.startServer().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/runtime/server/SimulationDaemon.java