TAPAS: de.dlr.ivf.tapas.loc.TPS_SelectWithSingleAccessMode Class Reference
de.dlr.ivf.tapas.loc.TPS_SelectWithSingleAccessMode Class Reference
Classes
class InterveningOpportunitiesWeightedResult
Public Member Functions
WeightedResult createLocationOption (Result result, double travelTime, double parameter)
double getTravelTime (TPS_Plan plan, TPS_PlanningContext pc, TPS_ModeChoiceContext prevMCC, TPS_ModeChoiceContext nextMCC, TPS_TrafficAnalysisZone taz, TPS_ParameterClass parameterClass)
Public Member Functions inherited from de.dlr.ivf.tapas.loc.TPS_SelectLocationWeightBased
TPS_Location selectLocationFromChoiceSet (TPS_RegionResultSet choiceSet, TPS_Plan plan, TPS_PlanningContext pc, TPS_LocatedStay locatedStay)
Public Member Functions inherited from de.dlr.ivf.tapas.loc.TPS_LocationSelectModel
void setClassReferences (TPS_Region region, TPS_DB_IOManager pm)
Detailed Description
Definition at line 24 of file TPS_SelectWithSingleAccessMode.java.
Member Function Documentation
createLocationOption()
WeightedResult de.dlr.ivf.tapas.loc.TPS_SelectWithSingleAccessMode.createLocationOption (Result result, double travelTime, double parameter)
Reimplemented from de.dlr.ivf.tapas.loc.TPS_SelectLocationWeightBased.
Definition at line 26 of file TPS_SelectWithSingleAccessMode.java.
getTravelTime()
double de.dlr.ivf.tapas.loc.TPS_SelectWithSingleAccessMode.getTravelTime (TPS_Plan plan, TPS_PlanningContext pc, TPS_ModeChoiceContext prevMCC, TPS_ModeChoiceContext nextMCC, TPS_TrafficAnalysisZone taz, TPS_ParameterClass parameterClass)
Method to calculate the expected tavel time to the locRepresentant.
Parameters
plan
pc
prevMCC
nextMCC
taz
Returns
Reimplemented from de.dlr.ivf.tapas.loc.TPS_SelectLocationWeightBased.
Definition at line 40 of file TPS_SelectWithSingleAccessMode.java.
References de.dlr.ivf.tapas.plan.TPS_PlanningContext.carForThisPlan, de.dlr.ivf.tapas.util.TPS_AttributeReader.TPS_Attribute.CURRENT_MODE_CODE_VOT, de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.drawKey(), de.dlr.ivf.tapas.mode.TPS_ModeChoiceContext.fromStay, de.dlr.ivf.tapas.mode.TPS_ModeChoiceContext.fromStayLocation, de.dlr.ivf.tapas.mode.TPS_Mode.get(), de.dlr.ivf.tapas.scheme.TPS_Episode.getActCode(), de.dlr.ivf.tapas.mode.TPS_Mode.getCode(), de.dlr.ivf.tapas.mode.TPS_Mode.getConstants(), de.dlr.ivf.tapas.mode.TPS_Mode.getDistance(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getDoubleValue(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getIntValue(), de.dlr.ivf.tapas.mode.TPS_ModeSet.getModeDistribution(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.getModeSet(), de.dlr.ivf.tapas.scheme.TPS_Episode.getOriginalEnd(), de.dlr.ivf.tapas.plan.TPS_Plan.getPerson(), de.dlr.ivf.tapas.mode.TPS_Mode.getTravelTime(), de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.getValueByKey(), de.dlr.ivf.tapas.mode.TPS_Mode.hasConnection(), de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.isRestricted, de.dlr.ivf.tapas.person.TPS_Car.isRestricted(), de.dlr.ivf.tapas.mode.TPS_Mode.isType(), de.dlr.ivf.tapas.util.parameters.ParamValue.MAX_WALK_DIST, de.dlr.ivf.tapas.util.parameters.ParamValue.MIN_DIST, de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.MIT, de.dlr.ivf.tapas.mode.TPS_Mode.MODE_TYPE_ARRAY, de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.normalize(), de.dlr.ivf.tapas.util.parameters.SimulationType.SCENARIO, de.dlr.ivf.tapas.plan.TPS_Plan.setAttributeValue(), de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.setValueByKey(), de.dlr.ivf.tapas.mode.TPS_Mode.TPS_ModeCodeType.VOT, and de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.WALK.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/loc/TPS_SelectWithSingleAccessMode.java