TAPAS: de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel Class Reference
de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel Class Reference
Classes
class StringListModel
class ToggleSelectionModel
Public Member Functions
DBSimulationChooserPanel (String title, String initSimulation, StyledDocument console)
DBSimulationChooserPanel (StyledDocument console)
void cleanDB ()
DBTripReader createDBTripReader ()
String getTitle ()
void setTitle (String title)
boolean isReady ()
Private Member Functions
void createContents (String title)
boolean getDatabaseContent ()
List< String > getOldTables ()
void updateLabel ()
Private Attributes
final String NO_PICK = " "
final StyledDocument console
final String schema = "core"
JList< String > lstSimulations
JLabel lblPicked
JComboBox< TPS_SettlementSystemType > cbConvert
JComboBox< String > cbFilter
final List< String[]> simdata = new ArrayList<>()
final List< String > simulations = new ArrayList<>()
final List< String > filters = new ArrayList<>()
StringListModel simulationDataModel
TPS_DB_Connector dbCon = null
TitledBorder border
Static Private Attributes
static final long serialVersionUID = 380071457799580782L
Detailed Description
Eine UI-Komponente die das Auswählen von Simulationstabellen in der DB ermöglicht.
Author
boec_pa
Definition at line 42 of file DBSimulationChooserPanel.java.
Constructor & Destructor Documentation
DBSimulationChooserPanel() [1/2]
de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.DBSimulationChooserPanel (String title, String initSimulation, StyledDocument console)
Create the panel.
Definition at line 70 of file DBSimulationChooserPanel.java.
References de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.cleanDB(), de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.console, de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.createContents(), de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.dbCon, de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.getRuntimeFile(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.loadRuntimeParameters(), and de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.lstSimulations.
DBSimulationChooserPanel() [2/2]
de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.DBSimulationChooserPanel (StyledDocument console)
Create the panel.
Definition at line 96 of file DBSimulationChooserPanel.java.
References de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.console.
Member Function Documentation
cleanDB()
void de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.cleanDB ()
Definition at line 100 of file DBSimulationChooserPanel.java.
References de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection(), and de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.getOldTables().
Referenced by de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.DBSimulationChooserPanel().
createContents()
void de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.createContents (String title) private
Definition at line 124 of file DBSimulationChooserPanel.java.
References de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.border, de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.cbConvert, de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.cbFilter, de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.StringListModel.changed(), de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.getDatabaseContent(), de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.lblPicked, de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.lstSimulations, de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.simulationDataModel, and de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.updateLabel().
Referenced by de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.DBSimulationChooserPanel().
createDBTripReader()
DBTripReader de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.createDBTripReader ()
Returns
null if anything went wrong.
Definition at line 237 of file DBSimulationChooserPanel.java.
References de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.cbConvert, de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.cbFilter, de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.console, de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.dbCon, de.dlr.ivf.tapas.tools.TAZFilter.TAZFilter.getTAZValues(), de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.lstSimulations, de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.NO_PICK, de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.schema, and de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.simdata.
Referenced by de.dlr.ivf.tapas.analyzer.gui.TripChooserPanel.getTripReader().
getDatabaseContent()
boolean de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.getDatabaseContent () private
Definition at line 265 of file DBSimulationChooserPanel.java.
References de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.cbFilter, de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.filters, de.dlr.ivf.tapas.tools.TAZFilter.TAZFilter.getMappingNames(), de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.lstSimulations, de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.NO_PICK, de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.simdata, de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.simulationDataModel, de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.simulations, and de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.updateLabel().
Referenced by de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.createContents().
getOldTables()
List<String> de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.getOldTables () private
Definition at line 322 of file DBSimulationChooserPanel.java.
References de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.dbCon, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection().
Referenced by de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.cleanDB().
getTitle()
String de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.getTitle ()
Definition at line 349 of file DBSimulationChooserPanel.java.
References de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.border.
isReady()
boolean de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.isReady ()
Definition at line 357 of file DBSimulationChooserPanel.java.
References de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.lstSimulations.
Referenced by de.dlr.ivf.tapas.analyzer.gui.TripChooserPanel.getTripReader(), and de.dlr.ivf.tapas.analyzer.gui.TripChooserPanel.isReady().
setTitle()
void de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.setTitle (String title)
Definition at line 353 of file DBSimulationChooserPanel.java.
References de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.border.
updateLabel()
void de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.updateLabel () private
Definition at line 361 of file DBSimulationChooserPanel.java.
References de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.lblPicked, and de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.lstSimulations.
Referenced by de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.createContents(), and de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.getDatabaseContent().
Member Data Documentation
border
TitledBorder de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.border private
Definition at line 65 of file DBSimulationChooserPanel.java.
Referenced by de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.createContents(), de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.getTitle(), and de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.setTitle().
cbConvert
JComboBox<TPS_SettlementSystemType> de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.cbConvert private
Definition at line 55 of file DBSimulationChooserPanel.java.
Referenced by de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.createContents(), and de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.createDBTripReader().
cbFilter
JComboBox<String> de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.cbFilter private
Definition at line 56 of file DBSimulationChooserPanel.java.
Referenced by de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.createContents(), de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.createDBTripReader(), and de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.getDatabaseContent().
console
final StyledDocument de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.console private
Definition at line 51 of file DBSimulationChooserPanel.java.
Referenced by de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.createDBTripReader(), and de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.DBSimulationChooserPanel().
dbCon
TPS_DB_Connector de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.dbCon = null private
Definition at line 63 of file DBSimulationChooserPanel.java.
Referenced by de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.cleanDB(), de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.createDBTripReader(), de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.DBSimulationChooserPanel(), de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.getDatabaseContent(), and de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.getOldTables().
filters
final List<String> de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.filters = new ArrayList<>() private
Definition at line 59 of file DBSimulationChooserPanel.java.
Referenced by de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.getDatabaseContent().
lblPicked
JLabel de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.lblPicked private
Definition at line 54 of file DBSimulationChooserPanel.java.
Referenced by de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.createContents(), and de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.updateLabel().
lstSimulations
JList<String> de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.lstSimulations private
Definition at line 53 of file DBSimulationChooserPanel.java.
Referenced by de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.createContents(), de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.createDBTripReader(), de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.DBSimulationChooserPanel(), de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.getDatabaseContent(), de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.isReady(), and de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.updateLabel().
NO_PICK
final String de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.NO_PICK = " " private
Definition at line 49 of file DBSimulationChooserPanel.java.
Referenced by de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.createDBTripReader(), and de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.getDatabaseContent().
schema
final String de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.schema = "core" private
Definition at line 52 of file DBSimulationChooserPanel.java.
Referenced by de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.createDBTripReader().
serialVersionUID
final long de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.serialVersionUID = 380071457799580782L static private
Definition at line 47 of file DBSimulationChooserPanel.java.
simdata
final List<String[]> de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.simdata = new ArrayList<>() private
Definition at line 57 of file DBSimulationChooserPanel.java.
Referenced by de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.createDBTripReader(), and de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.getDatabaseContent().
simulationDataModel
StringListModel de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.simulationDataModel private
Definition at line 61 of file DBSimulationChooserPanel.java.
Referenced by de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.createContents(), and de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.getDatabaseContent().
simulations
final List<String> de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.simulations = new ArrayList<>() private
Definition at line 58 of file DBSimulationChooserPanel.java.
Referenced by de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.getDatabaseContent().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/gui/DBSimulationChooserPanel.java