TAPAS: de.dlr.ivf.tapas.util.TPS_FastMath Class Reference
de.dlr.ivf.tapas.util.TPS_FastMath Class Reference
Some fast math functions - mainly approximations based on "Numerical Recipes".
Static Public Member Functions
static double acos (double x)
acos function from Numerical Recipes
static double exp (double x)
An exp() approximation.
Detailed Description
Some fast math functions - mainly approximations based on "Numerical Recipes".
Author
dkrajzew
Note
Please note that the values are checked to be in valid ranges.
Definition at line 16 of file TPS_FastMath.java.
Member Function Documentation
acos()
static double de.dlr.ivf.tapas.util.TPS_FastMath.acos (double x) static
acos function from Numerical Recipes
Parameters
x
Returns
acos of x
See also
http://http.developer.nvidia.com/Cg/acos.html
http://stackoverflow.com/questions/3380628/fast-arc-cos-algorithm
Definition at line 29 of file TPS_FastMath.java.
Referenced by de.dlr.ivf.tapas.util.TPS_Geometrics.getDistance().
exp()
static double de.dlr.ivf.tapas.util.TPS_FastMath.exp (double x) static
An exp() approximation.
Parameters
x
Returns
exp of x
See also
Definition at line 52 of file TPS_FastMath.java.
Referenced by de.dlr.ivf.tapas.mode.TPS_ModeDistribution.calculateDistribution(), de.dlr.ivf.tapas.util.TPS_GX.calculateEVA1Acceptance(), de.dlr.ivf.tapas.loc.TPS_Location.TPS_LocationData.calculateWeight(), de.dlr.ivf.tapas.modechoice.TPS_UtilityMNL.getDistributionSet(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.getModeLogSum(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.selectLocationFromChoiceSet(), de.dlr.ivf.tapas.person.TPS_Person.selectPreferenceAccessibility(), and de.dlr.ivf.tapas.person.TPS_Person.selectPreferenceSupply().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/util/TPS_FastMath.java