TAPAS: de.dlr.ivf.tapas.tools.TPS_CarRedistributor Class Reference
de.dlr.ivf.tapas.tools.TPS_CarRedistributor Class Reference
Classes
class CarProbabaility
class HouseHoldWithCars
Public Member Functions
void loadCarMap (String table, String key)
void loadHouseHolds (String table, String key)
void loadTazMap (String table, String name)
void printStatistics ()
void recodeAllCars (String table, String key)
void redistributeCars ()
void transformAllCars (String table, String key, List< CarProbabaility > probs)
void transformCars ()
void updateHouseHolds (String table, String key)
Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_BasicConnectionClass ()
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass)
TPS_BasicConnectionClass (String loginFile)
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass, String loginFile)
boolean checkMatrixName (String matrixName)
TPS_ParameterClass getParameters ()
String readParameter (String simKey, String paramKey)
void storeInDB (String matrixName, double[][] matrix, int decimalPlaces)
Static Public Member Functions
static void main (String[] args)
Static Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
static double[][] array1Dto2D (Integer[] matrixVal)
static double[][] array1Dto2D (int[] matrixVal)
static File getRuntimeFile (boolean forceNewFile)
static File getRuntimeFile (String propertyFile, boolean forceNewFile)
static File getRuntimeFile ()
static File getRuntimeFile (String propertyFile)
static int[][] intArray1Dto2D (int[] matrixVal)
static String matrixToSQLArray (double[][] array, int decimalPlaces)
static StringWriter matrixToStringWriterSQL (double[][] array, int decimalPlaces)
Additional Inherited Members
Protected Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
void finalize ()
Protected Attributes inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_DB_Connector dbCon = null
TPS_ParameterClass parameterClass
Detailed Description
In several scenarios households within a restricted access area poses a restricted car. This is highly unlikely! This class scans for such households and exchanges the cars randomly with unrestricted cars from the outside. Of course this is not a good model, but what can I do?
Author
hein_mh
Definition at line 28 of file TPS_CarRedistributor.java.
Member Function Documentation
loadCarMap()
void de.dlr.ivf.tapas.tools.TPS_CarRedistributor.loadCarMap (String table, String key)
Definition at line 92 of file TPS_CarRedistributor.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery().
Referenced by de.dlr.ivf.tapas.tools.TPS_CarRedistributor.main().
loadHouseHolds()
void de.dlr.ivf.tapas.tools.TPS_CarRedistributor.loadHouseHolds (String table, String key)
Definition at line 108 of file TPS_CarRedistributor.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.extractIntArray().
Referenced by de.dlr.ivf.tapas.tools.TPS_CarRedistributor.main().
loadTazMap()
void de.dlr.ivf.tapas.tools.TPS_CarRedistributor.loadTazMap (String table, String name)
Definition at line 159 of file TPS_CarRedistributor.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), and name.
Referenced by de.dlr.ivf.tapas.tools.TPS_CarRedistributor.main().
main()
static void de.dlr.ivf.tapas.tools.TPS_CarRedistributor.main (String[] args) static
Definition at line 37 of file TPS_CarRedistributor.java.
References de.dlr.ivf.tapas.tools.TPS_CarRedistributor.loadCarMap(), de.dlr.ivf.tapas.tools.TPS_CarRedistributor.loadHouseHolds(), de.dlr.ivf.tapas.tools.TPS_CarRedistributor.loadTazMap(), de.dlr.ivf.tapas.tools.TPS_CarRedistributor.printStatistics(), de.dlr.ivf.tapas.tools.TPS_CarRedistributor.recodeAllCars(), and de.dlr.ivf.tapas.tools.TPS_CarRedistributor.updateHouseHolds().
printStatistics()
void de.dlr.ivf.tapas.tools.TPS_CarRedistributor.printStatistics ()
Definition at line 174 of file TPS_CarRedistributor.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_CarRedistributor.main().
recodeAllCars()
void de.dlr.ivf.tapas.tools.TPS_CarRedistributor.recodeAllCars (String table, String key)
Definition at line 180 of file TPS_CarRedistributor.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.extractIntArray().
Referenced by de.dlr.ivf.tapas.tools.TPS_CarRedistributor.main().
redistributeCars()
void de.dlr.ivf.tapas.tools.TPS_CarRedistributor.redistributeCars ()
Definition at line 216 of file TPS_CarRedistributor.java.
transformAllCars()
void de.dlr.ivf.tapas.tools.TPS_CarRedistributor.transformAllCars (String table, String key, List< CarProbabaility > probs)
Definition at line 258 of file TPS_CarRedistributor.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.extractIntArray().
transformCars()
void de.dlr.ivf.tapas.tools.TPS_CarRedistributor.transformCars ()
Definition at line 302 of file TPS_CarRedistributor.java.
updateHouseHolds()
void de.dlr.ivf.tapas.tools.TPS_CarRedistributor.updateHouseHolds (String table, String key)
Definition at line 350 of file TPS_CarRedistributor.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection().
Referenced by de.dlr.ivf.tapas.tools.TPS_CarRedistributor.main().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/TPS_CarRedistributor.java