TAPAS: de.dlr.ivf.tapas.analyzer.tum.RegionPOJO Class Reference
de.dlr.ivf.tapas.analyzer.tum.RegionPOJO Class Reference
Classes
class ModalSplitForDistanceCategory
class ModalSplitForDistanceCategoryAndTripIntention
enum RegionCode
Public Member Functions
RegionPOJO (RegionCode regionCode)
int compareTo (RegionPOJO compareObject)
double getAvgNrOfTripsForPersonGroup (PersonGroup pg)
double getAvgNrOfTripsPerPerson ()
long getAvgTripDurationForPersonGroup (PersonGroup pg)
long getAvgTripDurationForTripIntention (TripIntention ti)
double getAvgTripLengthForPersonGroup (PersonGroup pg)
double getAvgTripLengthForTripIntention (TripIntention ti)
long getCountOfTripsForTripIntention (TripIntention ti)
long getCountOfTripsForTripIntentionAndPersonGroupTapas (TripIntention ti, Job pg)
long getCountOfTripsForTripIntentionAndPersonGroupViseva (TripIntention ti, PersonGroup pg)
long getCountTripsByTripIntention (TripIntention ti)
long getCountTripsPGViseva (PersonGroup pg)
double getDistMax ()
void setDistMax (double distMax)
double getDistMin ()
void setDistMin (double distMin)
double getDurMax ()
void setDurMax (double durMax)
double getDurMin ()
void setDurMin (double durMin)
long getMedDur ()
void setMedDur (long medDur)
double getMedLength ()
void setMedLength (double medLength)
double getModalSplit (Mode mode)
double getModalSplitAbs (Mode mode)
Map< Mode, ModalSplitForDistanceCategory > getModalSplitForDistanceCategory (boolean[] modalSplitForDistanceCatFilter)
Map< Mode, ModalSplitForDistanceCategoryAndTripIntention > getModalSplitForDistanceCategoryAndTripIntention (boolean[] modalSplitForDistanceCatAndTripIntentionFilterDistCat, boolean[] modalSplitForDistanceCatAndTripIntentionFilterTripInt)
double getModalSplitForTripIntention (Mode m, TripIntention ti)
long getModalSplitForTripIntentionAbs (Mode m, TripIntention ti)
double getModalSplitForTripIntentionAndPersonGroupTapas (Mode m, TripIntention ti, Job pg)
long getModalSplitForTripIntentionAndPersonGroupTapasAbs (Mode m, TripIntention ti, Job pg)
double getModalSplitForTripIntentionAndPersonGroupViseva (Mode m, TripIntention ti, PersonGroup pg)
long getModalSplitForTripIntentionAndPersonGroupVisevaAbs (Mode m, TripIntention ti, PersonGroup pg)
long getNbPers ()
void setNbPers (long nbPers)
long getNbTrips ()
void setNbTrips (long nbTrips)
long getNrOfPersonsForPersonGroup (PersonGroup pg)
long getNrOfTripsForPersonGroupTapas (Job pg)
long getNrOfTripsForPersonGroupTapasAndTripIntention (Job pg, TripIntention ti)
long getNrOfTripsForPersonGroupViseva (PersonGroup pg)
long getNrOfTripsForPersonGroupVisevaAndTripIntention (PersonGroup pg, TripIntention ti)
long getNrTripsForTripIntention (TripIntention ti)
double getPercentageOfTripAllocationForPersonGroupTapas (Job pg)
double getPercentageOfTripAllocationForPersonGroupViseva (PersonGroup pg)
double getPercentageOfTripAllocationForTripIntention (TripIntention ti)
double getPercentageOfTripLengthAllocationForTripIntentionAndPersonGroupsTapas (TripIntention ti, Job pg)
double getPercentageOfTripLengthAllocationForTripIntentionAndPersonGroupsViseva (TripIntention ti, PersonGroup pg)
double getPercentageOfTripLengthAllocationForTripIntentions (TripIntention ti)
double getPercentageOfTriplengthAllocationForDistanceCategory (DistanceCategory cat)
double getPercentageOfTriplengthAllocationForDistanceCategoryAndMode (Mode m, DistanceCategory cat)
double getPercentageOfTriplengthAllocationForDistanceCategoryAndTripIntention (TripIntention ti, DistanceCategory cat)
double getPercentageOfTriplengthAllocationForDistanceCategoryAndTripIntentionAndPersonGroupTAPAS (TripIntention ti, DistanceCategory cat, Job pg)
double getPercentageOfTriplengthAllocationForDistanceCategoryAndTripIntentionAndPersonGroupViseva (TripIntention ti, DistanceCategory cat, PersonGroup pg)
RegionCode getRegionCode ()
void setAggCounter (long[] aggCounter)
void setCntDistTrips (long[] cntDistTrips)
void setCntDurTrips (long[] cntDurTrips)
void setCntDurTripsPGTapas (long[] cntDurTripsPGTapas)
void setCntDurTripsPGViseva (long[] cntDurTripsPG)
void setCntModeTapas (long[][][] cntModeTapas)
void setCntModeViseva (long[][][] cntMode)
void setCntTripIntentionPersonGroupTapas (long[][] cntTripIntentionPersonGroup)
void setCntTripIntentionPersonGroupViseva (long[][] cntTripIntentionPersonGroup)
void setCntTrips (long[] cntTrips)
void setCntTripsPGTapas (long[] cntTripsPGTapas)
void setCntTripsPGViseva (long[] cntTripsPG)
void setDistCatTapas (long[][][] distCatTapas)
void setDistCatViseva (long[][][] distCat)
void setDistModeTapas (long[][][] distModeTapas)
void setDistTripsPGTapas (long[] cntDistTripsPGTapas)
void setDistTripsPGViseva (long[] cntDistTripsPG)
void setPersBuffs (Map< PersonGroup, Long > persBuffs)
Private Member Functions
long calcArraySum (long[] arr)
double getModalSplitForDistanceCategory (Mode mode, DistanceCategory cat)
long getModalSplitForDistanceCategoryAbs (Mode mode, DistanceCategory cat)
double getModalSplitForDistanceCategoryAndTripIntention (Mode mode, DistanceCategory cat, TripIntention ti)
long getModalSplitForDistanceCategoryTripIntentionAbs (Mode mode, DistanceCategory cat, TripIntention ti)
double saveDiv (long a, long b)
double saveDiv (double a, long b)
Private Attributes
final RegionCode regionCode
double medLength
long medDur
long nbTrips
long nbPers
long[] cntTripsPGViseva
long[] cntDistTripsPGViseva
long[] cntDurTripsPGViseva
long[] cntTrips
long[] cntDistTrips
long[] cntDurTrips
long[][][] distCatViseva
long[] aggCounter
Map< PersonGroup, Long > persBuffs
double distMin
double distMax
double durMin
double durMax
long[][][] cntModeViseva
long[][] cntTripIntentionPersonGroupViseva
long[][] cntTripIntentionPersonGroupTapas
long[] cntTripsPGTapas
long[] cntDistTripsPGTapas
long[] cntDurTripsPGTapas
long[][][] distCatTapas
long[][][] cntModeTapas
long[][][] distModeTapas
Detailed Description
Definition at line 21 of file RegionPOJO.java.
Constructor & Destructor Documentation
RegionPOJO()
de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.RegionPOJO (RegionCode regionCode)
Definition at line 49 of file RegionPOJO.java.
Member Function Documentation
calcArraySum()
long de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.calcArraySum (long[] arr) private
Definition at line 53 of file RegionPOJO.java.
compareTo()
int de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.compareTo (RegionPOJO compareObject)
Definition at line 61 of file RegionPOJO.java.
References de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.RegionCode.getId(), and de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getRegionCode().
getAvgNrOfTripsForPersonGroup()
double de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getAvgNrOfTripsForPersonGroup (PersonGroup pg)
Definition at line 65 of file RegionPOJO.java.
References de.dlr.ivf.tapas.analyzer.inputfileconverter.PersonGroup.getId().
getAvgNrOfTripsPerPerson()
double de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getAvgNrOfTripsPerPerson ()
Definition at line 70 of file RegionPOJO.java.
getAvgTripDurationForPersonGroup()
long de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getAvgTripDurationForPersonGroup (PersonGroup pg)
Definition at line 75 of file RegionPOJO.java.
References de.dlr.ivf.tapas.analyzer.inputfileconverter.PersonGroup.getId().
getAvgTripDurationForTripIntention()
long de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getAvgTripDurationForTripIntention (TripIntention ti)
Definition at line 81 of file RegionPOJO.java.
References de.dlr.ivf.tapas.analyzer.inputfileconverter.TripIntention.getId().
getAvgTripLengthForPersonGroup()
double de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getAvgTripLengthForPersonGroup (PersonGroup pg)
Definition at line 85 of file RegionPOJO.java.
References de.dlr.ivf.tapas.analyzer.inputfileconverter.PersonGroup.getId().
getAvgTripLengthForTripIntention()
double de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getAvgTripLengthForTripIntention (TripIntention ti)
Definition at line 91 of file RegionPOJO.java.
References de.dlr.ivf.tapas.analyzer.inputfileconverter.TripIntention.getId().
getCountOfTripsForTripIntention()
long de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getCountOfTripsForTripIntention (TripIntention ti)
Definition at line 95 of file RegionPOJO.java.
References de.dlr.ivf.tapas.analyzer.inputfileconverter.TripIntention.getId().
getCountOfTripsForTripIntentionAndPersonGroupTapas()
long de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getCountOfTripsForTripIntentionAndPersonGroupTapas (TripIntention ti, Job pg)
Definition at line 104 of file RegionPOJO.java.
References de.dlr.ivf.tapas.analyzer.inputfileconverter.Job.getId(), and de.dlr.ivf.tapas.analyzer.inputfileconverter.TripIntention.getId().
getCountOfTripsForTripIntentionAndPersonGroupViseva()
long de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getCountOfTripsForTripIntentionAndPersonGroupViseva (TripIntention ti, PersonGroup pg)
Definition at line 112 of file RegionPOJO.java.
References de.dlr.ivf.tapas.analyzer.inputfileconverter.PersonGroup.getId(), and de.dlr.ivf.tapas.analyzer.inputfileconverter.TripIntention.getId().
getCountTripsByTripIntention()
long de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getCountTripsByTripIntention (TripIntention ti)
Definition at line 120 of file RegionPOJO.java.
References de.dlr.ivf.tapas.analyzer.inputfileconverter.TripIntention.getId().
getCountTripsPGViseva()
long de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getCountTripsPGViseva (PersonGroup pg)
Definition at line 124 of file RegionPOJO.java.
References de.dlr.ivf.tapas.analyzer.inputfileconverter.PersonGroup.getId().
getDistMax()
double de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getDistMax ()
Definition at line 128 of file RegionPOJO.java.
getDistMin()
double de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getDistMin ()
Definition at line 136 of file RegionPOJO.java.
getDurMax()
double de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getDurMax ()
Definition at line 144 of file RegionPOJO.java.
getDurMin()
double de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getDurMin ()
Definition at line 152 of file RegionPOJO.java.
getMedDur()
long de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getMedDur ()
Definition at line 160 of file RegionPOJO.java.
getMedLength()
double de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getMedLength ()
Definition at line 168 of file RegionPOJO.java.
getModalSplit()
double de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getModalSplit (Mode mode)
Definition at line 176 of file RegionPOJO.java.
getModalSplitAbs()
double de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getModalSplitAbs (Mode mode)
Definition at line 181 of file RegionPOJO.java.
References de.dlr.ivf.tapas.analyzer.inputfileconverter.Mode.getId().
getModalSplitForDistanceCategory() [1/2]
Map<Mode, ModalSplitForDistanceCategory> de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getModalSplitForDistanceCategory (boolean[] modalSplitForDistanceCatFilter)
Berechnet die Modalsplits fr die DistanceCategory die in dem bergebenen Array true sind. Felder die hintereinander false sind werden mit dem nchsten true-Feld zusammengefasst. D.h. ist das erste und 4. Feld selektiert, gibt es eine Kategorie 1 und eine Kategorie 2-4.
Parameters
modalSplitForDistanceCatFilter
Returns
Definition at line 196 of file RegionPOJO.java.
References de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.ModalSplitForDistanceCategory.ModalSplitForDistanceCategoryElement.getDistanceCategories(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.ModalSplitForDistanceCategory.getElements(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.ModalSplitForDistanceCategory.ModalSplitForDistanceCategoryElement.modalSplit, de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.ModalSplitForDistanceCategory.ModalSplitForDistanceCategoryElement.modalSplitAbs, and de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.ModalSplitForDistanceCategory.mode.
getModalSplitForDistanceCategory() [2/2]
double de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getModalSplitForDistanceCategory (Mode mode, DistanceCategory cat) private
Definition at line 243 of file RegionPOJO.java.
References de.dlr.ivf.tapas.analyzer.inputfileconverter.DistanceCategory.getId().
getModalSplitForDistanceCategoryAbs()
long de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getModalSplitForDistanceCategoryAbs (Mode mode, DistanceCategory cat) private
Definition at line 255 of file RegionPOJO.java.
References de.dlr.ivf.tapas.analyzer.inputfileconverter.DistanceCategory.getId(), and de.dlr.ivf.tapas.analyzer.inputfileconverter.Mode.getId().
getModalSplitForDistanceCategoryAndTripIntention() [1/2]
Map<Mode, ModalSplitForDistanceCategoryAndTripIntention> de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getModalSplitForDistanceCategoryAndTripIntention (boolean[] modalSplitForDistanceCatAndTripIntentionFilterDistCat, boolean[] modalSplitForDistanceCatAndTripIntentionFilterTripInt)
Berechnet die Modalsplits fr die DistanceCategory und die TripIntention bei dem in dem jeweiligen bergebenen Array der Wert true ist. Alle DistanceCategory und TripIntention die im Array false sind werden zur Kategorie "other" zusammengefasst
Parameters
modalSplitForDistanceCatAndTripIntentionFilterDistCat
modalSplitForDistanceCatAndTripIntentionFilterTripInt
Returns
Definition at line 271 of file RegionPOJO.java.
References de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.ModalSplitForDistanceCategoryAndTripIntention.ModalSplitForDistanceCategoryAndTripIntentionElement.containsModalSplitTripIntentionSeparatedAbs(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.ModalSplitForDistanceCategoryAndTripIntention.ModalSplitForDistanceCategoryAndTripIntentionElement.getDistanceCategories(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.ModalSplitForDistanceCategoryAndTripIntention.getElements(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.ModalSplitForDistanceCategoryAndTripIntention.ModalSplitForDistanceCategoryAndTripIntentionElement.getModalSplitTripIntentionSeparatedAbs(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.ModalSplitForDistanceCategoryAndTripIntention.ModalSplitForDistanceCategoryAndTripIntentionElement.modalSplitOther, de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.ModalSplitForDistanceCategoryAndTripIntention.ModalSplitForDistanceCategoryAndTripIntentionElement.modalSplitOtherAbs, de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.ModalSplitForDistanceCategoryAndTripIntention.mode, de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.ModalSplitForDistanceCategoryAndTripIntention.ModalSplitForDistanceCategoryAndTripIntentionElement.putModalSplitTripIntentionSeparated(), and de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.ModalSplitForDistanceCategoryAndTripIntention.ModalSplitForDistanceCategoryAndTripIntentionElement.putModalSplitTripIntentionSeparatedAbs().
getModalSplitForDistanceCategoryAndTripIntention() [2/2]
double de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getModalSplitForDistanceCategoryAndTripIntention (Mode mode, DistanceCategory cat, TripIntention ti) private
Definition at line 419 of file RegionPOJO.java.
References de.dlr.ivf.tapas.analyzer.inputfileconverter.DistanceCategory.getId(), and de.dlr.ivf.tapas.analyzer.inputfileconverter.TripIntention.getId().
getModalSplitForDistanceCategoryTripIntentionAbs()
long de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getModalSplitForDistanceCategoryTripIntentionAbs (Mode mode, DistanceCategory cat, TripIntention ti) private
Definition at line 429 of file RegionPOJO.java.
References de.dlr.ivf.tapas.analyzer.inputfileconverter.DistanceCategory.getId(), de.dlr.ivf.tapas.analyzer.inputfileconverter.Mode.getId(), and de.dlr.ivf.tapas.analyzer.inputfileconverter.TripIntention.getId().
getModalSplitForTripIntention()
double de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getModalSplitForTripIntention (Mode m, TripIntention ti)
Definition at line 433 of file RegionPOJO.java.
getModalSplitForTripIntentionAbs()
long de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getModalSplitForTripIntentionAbs (Mode m, TripIntention ti)
Definition at line 437 of file RegionPOJO.java.
References de.dlr.ivf.tapas.analyzer.inputfileconverter.Mode.getId(), and de.dlr.ivf.tapas.analyzer.inputfileconverter.TripIntention.getId().
getModalSplitForTripIntentionAndPersonGroupTapas()
double de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getModalSplitForTripIntentionAndPersonGroupTapas (Mode m, TripIntention ti, Job pg)
Definition at line 441 of file RegionPOJO.java.
getModalSplitForTripIntentionAndPersonGroupTapasAbs()
long de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getModalSplitForTripIntentionAndPersonGroupTapasAbs (Mode m, TripIntention ti, Job pg)
Definition at line 448 of file RegionPOJO.java.
References de.dlr.ivf.tapas.analyzer.inputfileconverter.Job.getId(), de.dlr.ivf.tapas.analyzer.inputfileconverter.Mode.getId(), and de.dlr.ivf.tapas.analyzer.inputfileconverter.TripIntention.getId().
getModalSplitForTripIntentionAndPersonGroupViseva()
double de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getModalSplitForTripIntentionAndPersonGroupViseva (Mode m, TripIntention ti, PersonGroup pg)
Definition at line 452 of file RegionPOJO.java.
getModalSplitForTripIntentionAndPersonGroupVisevaAbs()
long de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getModalSplitForTripIntentionAndPersonGroupVisevaAbs (Mode m, TripIntention ti, PersonGroup pg)
Definition at line 458 of file RegionPOJO.java.
References de.dlr.ivf.tapas.analyzer.inputfileconverter.Mode.getId(), de.dlr.ivf.tapas.analyzer.inputfileconverter.PersonGroup.getId(), and de.dlr.ivf.tapas.analyzer.inputfileconverter.TripIntention.getId().
getNbPers()
long de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getNbPers ()
Definition at line 462 of file RegionPOJO.java.
getNbTrips()
long de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getNbTrips ()
Definition at line 470 of file RegionPOJO.java.
getNrOfPersonsForPersonGroup()
long de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getNrOfPersonsForPersonGroup (PersonGroup pg)
Definition at line 478 of file RegionPOJO.java.
getNrOfTripsForPersonGroupTapas()
long de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getNrOfTripsForPersonGroupTapas (Job pg)
Definition at line 486 of file RegionPOJO.java.
References de.dlr.ivf.tapas.analyzer.inputfileconverter.Job.getId().
getNrOfTripsForPersonGroupTapasAndTripIntention()
long de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getNrOfTripsForPersonGroupTapasAndTripIntention (Job pg, TripIntention ti)
Definition at line 490 of file RegionPOJO.java.
References de.dlr.ivf.tapas.analyzer.inputfileconverter.Job.getId(), and de.dlr.ivf.tapas.analyzer.inputfileconverter.TripIntention.getId().
getNrOfTripsForPersonGroupViseva()
long de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getNrOfTripsForPersonGroupViseva (PersonGroup pg)
Definition at line 494 of file RegionPOJO.java.
References de.dlr.ivf.tapas.analyzer.inputfileconverter.PersonGroup.getId().
getNrOfTripsForPersonGroupVisevaAndTripIntention()
long de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getNrOfTripsForPersonGroupVisevaAndTripIntention (PersonGroup pg, TripIntention ti)
Definition at line 498 of file RegionPOJO.java.
References de.dlr.ivf.tapas.analyzer.inputfileconverter.PersonGroup.getId(), and de.dlr.ivf.tapas.analyzer.inputfileconverter.TripIntention.getId().
getNrTripsForTripIntention()
long de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getNrTripsForTripIntention (TripIntention ti)
Definition at line 502 of file RegionPOJO.java.
References de.dlr.ivf.tapas.analyzer.inputfileconverter.TripIntention.getId().
getPercentageOfTripAllocationForPersonGroupTapas()
double de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getPercentageOfTripAllocationForPersonGroupTapas (Job pg)
Definition at line 506 of file RegionPOJO.java.
References de.dlr.ivf.tapas.analyzer.inputfileconverter.Job.getId().
getPercentageOfTripAllocationForPersonGroupViseva()
double de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getPercentageOfTripAllocationForPersonGroupViseva (PersonGroup pg)
Definition at line 513 of file RegionPOJO.java.
References de.dlr.ivf.tapas.analyzer.inputfileconverter.PersonGroup.getId().
getPercentageOfTripAllocationForTripIntention()
double de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getPercentageOfTripAllocationForTripIntention (TripIntention ti)
Definition at line 518 of file RegionPOJO.java.
getPercentageOfTriplengthAllocationForDistanceCategory()
double de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getPercentageOfTriplengthAllocationForDistanceCategory (DistanceCategory cat)
Definition at line 544 of file RegionPOJO.java.
References de.dlr.ivf.tapas.analyzer.inputfileconverter.DistanceCategory.getId().
getPercentageOfTriplengthAllocationForDistanceCategoryAndMode()
double de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getPercentageOfTriplengthAllocationForDistanceCategoryAndMode (Mode m, DistanceCategory cat)
Definition at line 549 of file RegionPOJO.java.
References de.dlr.ivf.tapas.analyzer.inputfileconverter.DistanceCategory.getId(), and de.dlr.ivf.tapas.analyzer.inputfileconverter.Mode.getId().
getPercentageOfTriplengthAllocationForDistanceCategoryAndTripIntention()
double de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getPercentageOfTriplengthAllocationForDistanceCategoryAndTripIntention (TripIntention ti, DistanceCategory cat)
Definition at line 567 of file RegionPOJO.java.
References de.dlr.ivf.tapas.analyzer.inputfileconverter.DistanceCategory.getId(), and de.dlr.ivf.tapas.analyzer.inputfileconverter.TripIntention.getId().
getPercentageOfTriplengthAllocationForDistanceCategoryAndTripIntentionAndPersonGroupTAPAS()
double de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getPercentageOfTriplengthAllocationForDistanceCategoryAndTripIntentionAndPersonGroupTAPAS (TripIntention ti, DistanceCategory cat, Job pg)
Definition at line 578 of file RegionPOJO.java.
References de.dlr.ivf.tapas.analyzer.inputfileconverter.DistanceCategory.getId(), de.dlr.ivf.tapas.analyzer.inputfileconverter.Job.getId(), and de.dlr.ivf.tapas.analyzer.inputfileconverter.TripIntention.getId().
getPercentageOfTriplengthAllocationForDistanceCategoryAndTripIntentionAndPersonGroupViseva()
double de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getPercentageOfTriplengthAllocationForDistanceCategoryAndTripIntentionAndPersonGroupViseva (TripIntention ti, DistanceCategory cat, PersonGroup pg)
Definition at line 582 of file RegionPOJO.java.
References de.dlr.ivf.tapas.analyzer.inputfileconverter.DistanceCategory.getId(), de.dlr.ivf.tapas.analyzer.inputfileconverter.PersonGroup.getId(), and de.dlr.ivf.tapas.analyzer.inputfileconverter.TripIntention.getId().
getPercentageOfTripLengthAllocationForTripIntentionAndPersonGroupsTapas()
double de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getPercentageOfTripLengthAllocationForTripIntentionAndPersonGroupsTapas (TripIntention ti, Job pg)
Definition at line 523 of file RegionPOJO.java.
References de.dlr.ivf.tapas.analyzer.inputfileconverter.Job.getId(), and de.dlr.ivf.tapas.analyzer.inputfileconverter.TripIntention.getId().
getPercentageOfTripLengthAllocationForTripIntentionAndPersonGroupsViseva()
double de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getPercentageOfTripLengthAllocationForTripIntentionAndPersonGroupsViseva (TripIntention ti, PersonGroup pg)
Definition at line 528 of file RegionPOJO.java.
References de.dlr.ivf.tapas.analyzer.inputfileconverter.PersonGroup.getId(), and de.dlr.ivf.tapas.analyzer.inputfileconverter.TripIntention.getId().
getPercentageOfTripLengthAllocationForTripIntentions()
double de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getPercentageOfTripLengthAllocationForTripIntentions (TripIntention ti)
Definition at line 533 of file RegionPOJO.java.
References de.dlr.ivf.tapas.analyzer.inputfileconverter.TripIntention.getId().
getRegionCode()
RegionCode de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getRegionCode ()
Definition at line 588 of file RegionPOJO.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.compareTo().
saveDiv() [1/2]
double de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.saveDiv (double a, long b) private
Definition at line 598 of file RegionPOJO.java.
saveDiv() [2/2]
double de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.saveDiv (long a, long b) private
Definition at line 592 of file RegionPOJO.java.
setAggCounter()
void de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.setAggCounter (long[] aggCounter)
Definition at line 604 of file RegionPOJO.java.
setCntDistTrips()
void de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.setCntDistTrips (long[] cntDistTrips)
Definition at line 608 of file RegionPOJO.java.
setCntDurTrips()
void de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.setCntDurTrips (long[] cntDurTrips)
Definition at line 612 of file RegionPOJO.java.
setCntDurTripsPGTapas()
void de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.setCntDurTripsPGTapas (long[] cntDurTripsPGTapas)
Definition at line 616 of file RegionPOJO.java.
setCntDurTripsPGViseva()
void de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.setCntDurTripsPGViseva (long[] cntDurTripsPG)
Definition at line 620 of file RegionPOJO.java.
setCntModeTapas()
void de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.setCntModeTapas (long cntModeTapas[][][])
Definition at line 624 of file RegionPOJO.java.
setCntModeViseva()
void de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.setCntModeViseva (long cntMode[][][])
Definition at line 628 of file RegionPOJO.java.
setCntTripIntentionPersonGroupTapas()
void de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.setCntTripIntentionPersonGroupTapas (long cntTripIntentionPersonGroup[][])
Definition at line 632 of file RegionPOJO.java.
setCntTripIntentionPersonGroupViseva()
void de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.setCntTripIntentionPersonGroupViseva (long cntTripIntentionPersonGroup[][])
Definition at line 636 of file RegionPOJO.java.
setCntTrips()
void de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.setCntTrips (long[] cntTrips)
Definition at line 640 of file RegionPOJO.java.
setCntTripsPGTapas()
void de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.setCntTripsPGTapas (long[] cntTripsPGTapas)
Definition at line 644 of file RegionPOJO.java.
setCntTripsPGViseva()
void de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.setCntTripsPGViseva (long[] cntTripsPG)
Definition at line 648 of file RegionPOJO.java.
setDistCatTapas()
void de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.setDistCatTapas (long distCatTapas[][][])
Definition at line 652 of file RegionPOJO.java.
setDistCatViseva()
void de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.setDistCatViseva (long distCat[][][])
Definition at line 656 of file RegionPOJO.java.
setDistMax()
void de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.setDistMax (double distMax)
Definition at line 132 of file RegionPOJO.java.
setDistMin()
void de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.setDistMin (double distMin)
Definition at line 140 of file RegionPOJO.java.
setDistModeTapas()
void de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.setDistModeTapas (long distModeTapas[][][])
Definition at line 660 of file RegionPOJO.java.
setDistTripsPGTapas()
void de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.setDistTripsPGTapas (long[] cntDistTripsPGTapas)
Definition at line 664 of file RegionPOJO.java.
setDistTripsPGViseva()
void de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.setDistTripsPGViseva (long[] cntDistTripsPG)
Definition at line 668 of file RegionPOJO.java.
setDurMax()
void de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.setDurMax (double durMax)
Definition at line 148 of file RegionPOJO.java.
setDurMin()
void de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.setDurMin (double durMin)
Definition at line 156 of file RegionPOJO.java.
setMedDur()
void de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.setMedDur (long medDur)
Definition at line 164 of file RegionPOJO.java.
setMedLength()
void de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.setMedLength (double medLength)
Definition at line 172 of file RegionPOJO.java.
setNbPers()
void de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.setNbPers (long nbPers)
Definition at line 466 of file RegionPOJO.java.
setNbTrips()
void de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.setNbTrips (long nbTrips)
Definition at line 474 of file RegionPOJO.java.
setPersBuffs()
void de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.setPersBuffs (Map< PersonGroup, Long > persBuffs)
Definition at line 672 of file RegionPOJO.java.
Member Data Documentation
aggCounter
long [] de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.aggCounter private
Definition at line 34 of file RegionPOJO.java.
cntDistTrips
long [] de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.cntDistTrips private
Definition at line 31 of file RegionPOJO.java.
cntDistTripsPGTapas
long [] de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.cntDistTripsPGTapas private
Definition at line 44 of file RegionPOJO.java.
cntDistTripsPGViseva
long [] de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.cntDistTripsPGViseva private
Definition at line 28 of file RegionPOJO.java.
cntDurTrips
long [] de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.cntDurTrips private
Definition at line 32 of file RegionPOJO.java.
cntDurTripsPGTapas
long [] de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.cntDurTripsPGTapas private
Definition at line 45 of file RegionPOJO.java.
cntDurTripsPGViseva
long [] de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.cntDurTripsPGViseva private
Definition at line 29 of file RegionPOJO.java.
cntModeTapas
long [][][] de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.cntModeTapas private
Definition at line 47 of file RegionPOJO.java.
cntModeViseva
long [][][] de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.cntModeViseva private
Definition at line 40 of file RegionPOJO.java.
cntTripIntentionPersonGroupTapas
long [][] de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.cntTripIntentionPersonGroupTapas private
Definition at line 42 of file RegionPOJO.java.
cntTripIntentionPersonGroupViseva
long [][] de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.cntTripIntentionPersonGroupViseva private
Definition at line 41 of file RegionPOJO.java.
cntTrips
long [] de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.cntTrips private
Definition at line 30 of file RegionPOJO.java.
cntTripsPGTapas
long [] de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.cntTripsPGTapas private
Definition at line 43 of file RegionPOJO.java.
cntTripsPGViseva
long [] de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.cntTripsPGViseva private
Definition at line 27 of file RegionPOJO.java.
distCatTapas
long [][][] de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.distCatTapas private
Definition at line 46 of file RegionPOJO.java.
distCatViseva
long [][][] de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.distCatViseva private
Definition at line 33 of file RegionPOJO.java.
distMax
double de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.distMax private
Definition at line 37 of file RegionPOJO.java.
distMin
double de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.distMin private
Definition at line 36 of file RegionPOJO.java.
distModeTapas
long [][][] de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.distModeTapas private
Definition at line 48 of file RegionPOJO.java.
durMax
double de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.durMax private
Definition at line 39 of file RegionPOJO.java.
durMin
double de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.durMin private
Definition at line 38 of file RegionPOJO.java.
medDur
long de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.medDur private
Definition at line 24 of file RegionPOJO.java.
medLength
double de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.medLength private
Definition at line 23 of file RegionPOJO.java.
nbPers
long de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.nbPers private
Definition at line 26 of file RegionPOJO.java.
nbTrips
long de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.nbTrips private
Definition at line 25 of file RegionPOJO.java.
persBuffs
Map<PersonGroup, Long> de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.persBuffs private
Definition at line 35 of file RegionPOJO.java.
regionCode
final RegionCode de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.regionCode private
Definition at line 22 of file RegionPOJO.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/tum/RegionPOJO.java