TAPAS: de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key > Class Template Reference
de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key > Class Template Reference
Public Member Functions
TPS_DiscreteDistribution (Collection< Key > singletons)
TPS_DiscreteDistribution (ArrayList< Key > singletons, double[] values)
TPS_DiscreteDistribution (Map< Key, ? extends Number > map)
TPS_DiscreteDistribution (ArrayList< Key > singletons, List<? extends Number > values)
int draw ()
int draw (double randomValue)
int draw (Random random)
Key drawKey ()
Key drawKey (double randomValue)
Key drawKey (Random random)
boolean equals (TPS_DiscreteDistribution< Key > obj)
Key getKey (int position)
ArrayList< Key > getSingletons ()
void setSingletons (Collection< Key > singletons)
double getValueByKey (Key key)
double getValueByPosition (int index)
double[] getValues ()
void setValues (double value)
void setValues (double[] values)
int hashCode ()
boolean isNormalized ()
boolean normalize ()
boolean normalize (boolean normalizeValues)
void setSize (int size)
void setValueByKey (Key key, double value)
void setValueByPosition (int index, double value)
int size ()
double sum ()
String toString ()
Protected Attributes
double[] values
boolean isNormalized
double[] cumulativeValues
Private Member Functions
TPS_DiscreteDistribution (int size)
int binarySearch (double randomValue)
int indexOf (Key key)
Private Attributes
ArrayList< Key > singletons
Detailed Description
This class represents a discrete probability distribution. Every probability value is referenced by a position/index and a key (or singleton value). The values do not necessarily have to sum up to 1. They will be normalized intrinsically. The values have to be non-negative.
Parameters
<Key> key type for the index
Definition at line 24 of file TPS_DiscreteDistribution.java.
Constructor & Destructor Documentation
TPS_DiscreteDistribution() [1/5]
de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.TPS_DiscreteDistribution (int size) private
Definition at line 45 of file TPS_DiscreteDistribution.java.
References de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.setSize().
TPS_DiscreteDistribution() [2/5]
de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.TPS_DiscreteDistribution (Collection< Key > singletons)
This constructor initializes the indices with the given collection and creates a uniform distribution on its values
Parameters
singletons indices
Definition at line 56 of file TPS_DiscreteDistribution.java.
References de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.setSingletons(), de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.setValues(), and de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.singletons.
TPS_DiscreteDistribution() [3/5]
de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.TPS_DiscreteDistribution (ArrayList< Key > singletons, double[] values)
Initializes a distribution over singletons with the values as probabilities
Parameters
singletons object of the distribution, pay attention! if you change the singletons from the calling object they will be changed here too
values probability values as a double array
Definition at line 69 of file TPS_DiscreteDistribution.java.
References de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.setSingletons(), de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.setValues(), and de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.values.
TPS_DiscreteDistribution() [4/5]
de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.TPS_DiscreteDistribution (Map< Key, ? extends Number > map)
Initializes a distribution over singletons with the values as probabilities
Parameters
map mapping of singleton values to probability values
Definition at line 80 of file TPS_DiscreteDistribution.java.
TPS_DiscreteDistribution() [5/5]
de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.TPS_DiscreteDistribution (ArrayList< Key > singletons, List<? extends Number > values)
Initializes a distribution over singletons with the values as probabilities
Parameters
singletons object of the distribution
values probability values as List of Number extending obejcts (like Integer or Double)
Definition at line 90 of file TPS_DiscreteDistribution.java.
References de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.singletons, and de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.values.
Member Function Documentation
binarySearch()
int de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.binarySearch (double randomValue) private
Looks for the smallest index in the cumulativeValues such that cumulativeValues[index] >= randomValue and values[index]>0
Parameters
randomValue random value
Returns
index s.t. cumulativeValues[index] >= randomValue and values[index]>0
Definition at line 101 of file TPS_DiscreteDistribution.java.
References de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.cumulativeValues, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.size(), and de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.values.
Referenced by de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.draw().
draw() [1/3]
int de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.draw ()
This method draws a random value out of the distribution.
Returns
index of the drawn value
Definition at line 138 of file TPS_DiscreteDistribution.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.assignSecondarySchoolLocation(), de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.assignTertiaryEduLocation(), de.dlr.ivf.tapas.tools.TPS_PrimaryActivityAssignment.assignWorkplaceLocation(), de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.draw(), and de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.drawKey().
draw() [2/3]
int de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.draw (double randomValue)
This method takes the index of the best fitting value to the given value. The distribution needs not to be normalized.
Parameters
randomValue value between 0 and 1
Returns
index of the drawn value
Definition at line 149 of file TPS_DiscreteDistribution.java.
References de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.binarySearch(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.isNormalized, de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.normalize(), and de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.size().
draw() [3/3]
int de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.draw (Random random)
This method draws a random value out of the distribution by using a random number generator.
Parameters
random Random number generator
Returns
index of the drawn value
Definition at line 173 of file TPS_DiscreteDistribution.java.
References de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.draw().
drawKey() [1/3]
Key de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.drawKey ()
This method draws a random key out of the distribution.
Returns
a random Key from the singletons by the probabilities from the distribution's values
Definition at line 185 of file TPS_DiscreteDistribution.java.
References de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.draw().
Referenced by de.dlr.ivf.tapas.scheme.TPS_SchemeClass.draw(), de.dlr.ivf.tapas.loc.TPS_SelectWithSingleAccessMode.getTravelTime(), de.dlr.ivf.tapas.mode.TPS_ModeSet.selectMode0(), and de.dlr.ivf.tapas.scheme.TPS_SchemeSet.selectScheme().
drawKey() [2/3]
Key de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.drawKey (double randomValue)
This method draws a random key out of the distribution.
Parameters
randomValue between 0 and 1
Returns
a random Key from the singletons by the probabilities from the distribution's values
Definition at line 195 of file TPS_DiscreteDistribution.java.
References de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.draw().
drawKey() [3/3]
Key de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.drawKey (Random random)
This method draws a random key out of the distribution.
Parameters
random Random number generator
Returns
a random Key from the singletons by the probabilities from the distribution's values
Definition at line 205 of file TPS_DiscreteDistribution.java.
References de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.draw().
equals()
boolean de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.equals (TPS_DiscreteDistribution< Key > obj)
Compares the array values given with the own array values
Parameters
obj distribution to compare with
Returns
true if the arrays have the same values, false otherwise
Definition at line 216 of file TPS_DiscreteDistribution.java.
References de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.values.
getKey()
Key de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.getKey (int position)
Returns the index of the distribution corresponding to the position given
Parameters
position position of the value in the distribution
Returns
Index at the position i
Definition at line 226 of file TPS_DiscreteDistribution.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, and de.dlr.ivf.tapas.log.TPS_Logger.log().
getSingletons()
ArrayList<Key> de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.getSingletons ()
Returns an array containing all indices
Returns
all singleton keys
Definition at line 239 of file TPS_DiscreteDistribution.java.
References de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.singletons.
Referenced by de.dlr.ivf.tapas.mode.TPS_ModeDistribution.getDistribution().
getValueByKey()
double de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.getValueByKey (Key key)
Returns the distribution value for the given key
Parameters
key singleton value
Returns
value corresponding to the given key
Definition at line 258 of file TPS_DiscreteDistribution.java.
References de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.getValueByPosition(), and de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.indexOf().
Referenced by de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree.applyExpertKnowledge(), de.dlr.ivf.tapas.mode.TPS_ModeDistribution.calculateDistribution(), de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixedBS.getDistributionSet(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessMode.getTravelTime(), de.dlr.ivf.tapas.loc.TPS_SelectWithSingleAccessMode.getTravelTime(), de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeNode.modifyDistribution(), and de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.toString().
getValueByPosition()
double de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.getValueByPosition (int index)
Returns the distribution value for the given position index
Parameters
index position
Returns
value corresponding to the given index
Definition at line 268 of file TPS_DiscreteDistribution.java.
Referenced by de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree.applyExpertKnowledge(), and de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.getValueByKey().
getValues()
double [] de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.getValues ()
returns the probability values array
Returns
probability array
Definition at line 277 of file TPS_DiscreteDistribution.java.
References de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.values.
Referenced by de.dlr.ivf.tapas.mode.TPS_ModeDistribution.calculateDistribution(), de.dlr.ivf.tapas.modechoice.TPS_Node.getCopyOfValueDistribution(), de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixedBS.getDistributionSet(), and de.dlr.ivf.tapas.modechoice.TPS_UtilityMNL.getDistributionSet().
hashCode()
int de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.hashCode ()
Definition at line 315 of file TPS_DiscreteDistribution.java.
indexOf()
int de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.indexOf (Key key) private
This method returns the index of the given key in the array distribution
Parameters
key key
Returns
value between 0 and length-1 -> index of the value in the distribution corresponding to the given key
-1 -> if the key doesn't exist
Definition at line 326 of file TPS_DiscreteDistribution.java.
Referenced by de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.getValueByKey(), and de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.setValueByKey().
isNormalized()
boolean de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.isNormalized ()
This method normalizes the distribution, i.e. that the sum of all values is 1. and computes the cumulative sum of the probability values also cumulativeValues[this.size()-1] will equal 1
Returns
true if the distribution is normalized, false otherwise
Definition at line 342 of file TPS_DiscreteDistribution.java.
References de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.isNormalized.
normalize() [1/2]
boolean de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.normalize ()
Definition at line 346 of file TPS_DiscreteDistribution.java.
Referenced by de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree.applyExpertKnowledge(), de.dlr.ivf.tapas.mode.TPS_ModeDistribution.calculateDistribution(), de.dlr.ivf.tapas.scheme.TPS_SchemeClass.draw(), de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.draw(), de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixed.getDistributionSet(), de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixedBS.getDistributionSet(), and de.dlr.ivf.tapas.loc.TPS_SelectWithSingleAccessMode.getTravelTime().
normalize() [2/2]
boolean de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.normalize (boolean normalizeValues)
This method normalizes the distribution and computes the cumulative sum, i.e. cumulativeValues[this.size()-1] will equal 1
Parameters
normalizeValues if true it normalizes the values array too, otherwise the probability values will be left untouched
Returns
true if normalizing was successful, false otherwise
Definition at line 358 of file TPS_DiscreteDistribution.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.size(), and de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.sum().
setSingletons()
void de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.setSingletons (Collection< Key > singletons)
Sets the keys list to the given list
Parameters
singletons keys
Definition at line 248 of file TPS_DiscreteDistribution.java.
References de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.singletons.
Referenced by de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.TPS_DiscreteDistribution().
setSize()
void de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.setSize (int size)
Initializes the arrays
Parameters
size array size
Definition at line 380 of file TPS_DiscreteDistribution.java.
References de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.size().
Referenced by de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.TPS_DiscreteDistribution().
setValueByKey()
void de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.setValueByKey (Key key, double value)
Returns the distribution value for the given key
Parameters
key key
value probability value
Definition at line 391 of file TPS_DiscreteDistribution.java.
References de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.indexOf(), and de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.setValueByPosition().
Referenced by de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree.applyExpertKnowledge(), de.dlr.ivf.tapas.mode.TPS_ModeDistribution.calculateDistribution(), de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixed.getDistributionSet(), de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixedBS.getDistributionSet(), de.dlr.ivf.tapas.modechoice.TPS_UtilityMNL.getDistributionSet(), de.dlr.ivf.tapas.loc.TPS_SelectWithSingleAccessMode.getTravelTime(), and de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeNode.modifyDistribution().
setValueByPosition()
void de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.setValueByPosition (int index, double value)
Definition at line 395 of file TPS_DiscreteDistribution.java.
Referenced by de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree.applyExpertKnowledge(), de.dlr.ivf.tapas.mode.TPS_ModeDistribution.getDistribution(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readExpertKnowledgeTree(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readModeChoiceTree(), and de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.setValueByKey().
setValues() [1/2]
void de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.setValues (double value)
Sets the probabilities to the given value
Parameters
value single probability value which is then the same for all probabilities
Definition at line 286 of file TPS_DiscreteDistribution.java.
Referenced by de.dlr.ivf.tapas.mode.TPS_ModeDistribution.calculateDistribution(), de.dlr.ivf.tapas.modechoice.TPS_Node.getCopyOfValueDistribution(), de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixedBS.getDistributionSet(), and de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.TPS_DiscreteDistribution().
setValues() [2/2]
void de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.setValues (double[] values)
Sets the probabilities to the given values
Parameters
values probability values
Definition at line 296 of file TPS_DiscreteDistribution.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.size(), and de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.values.
size()
int de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.size ()
Definition at line 405 of file TPS_DiscreteDistribution.java.
Referenced by de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree.applyExpertKnowledge(), de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.binarySearch(), de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.draw(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.getModeLogSum(), de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.normalize(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readExpertKnowledgeTree(), de.dlr.ivf.tapas.mode.TPS_ModeSet.selectMode0(), de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.setSize(), and de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.setValues().
sum()
double de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.sum ()
Returns the sum of all values; if normalized this is 1
Returns
sum of all values
Definition at line 414 of file TPS_DiscreteDistribution.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.log.TPS_Logger.log(), and de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.toString().
Referenced by de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.normalize().
toString()
String de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.toString ()
Definition at line 430 of file TPS_DiscreteDistribution.java.
References de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.getValueByKey().
Referenced by de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.sum().
Member Data Documentation
cumulativeValues
double [] de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.cumulativeValues protected
Definition at line 35 of file TPS_DiscreteDistribution.java.
Referenced by de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.binarySearch().
isNormalized
boolean de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.isNormalized protected
This flag indicates if the distribution is normalized
Definition at line 34 of file TPS_DiscreteDistribution.java.
Referenced by de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.draw(), and de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.isNormalized().
singletons
ArrayList<Key> de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.singletons private
array list of the keys of the distribution order should be corresponding to the probability values Important! This is only a reference of given list parameter If you change the list or its values from the parameters they will be changed in here too
Definition at line 43 of file TPS_DiscreteDistribution.java.
Referenced by de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.getSingletons(), de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.setSingletons(), and de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.TPS_DiscreteDistribution().
values
double [] de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.values protected
value array
Definition at line 29 of file TPS_DiscreteDistribution.java.
Referenced by de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.binarySearch(), de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.equals(), de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.getValues(), de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.setValues(), and de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.TPS_DiscreteDistribution().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/distribution/TPS_DiscreteDistribution.java