TAPAS: de.dlr.ivf.tapas.tools.TPS_ParkAndRideRouter Class Reference
de.dlr.ivf.tapas.tools.TPS_ParkAndRideRouter Class Reference
Classes
class IntermodalNode
class IntermodalRoute
Public Member Functions
Matrix createPandRMatrix ()
void loadMatrices (String mivName, String ptName, String walkName, String tableName)
void loadTAZRestriction (String tazInfo, String table)
void routePnR (double transferTime)
void saveInterchangeMatrixInDB (String matrixName, String tableName)
void storeMatrixInDB (Matrix matrix, String matrixName, String tableName)
Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_BasicConnectionClass ()
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass)
TPS_BasicConnectionClass (String loginFile)
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass, String loginFile)
boolean checkMatrixName (String matrixName)
TPS_ParameterClass getParameters ()
String readParameter (String simKey, String paramKey)
void storeInDB (String matrixName, double[][] matrix, int decimalPlaces)
Static Public Member Functions
static void main (String[] args)
Static Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
static double[][] array1Dto2D (Integer[] matrixVal)
static double[][] array1Dto2D (int[] matrixVal)
static File getRuntimeFile (boolean forceNewFile)
static File getRuntimeFile (String propertyFile, boolean forceNewFile)
static File getRuntimeFile ()
static File getRuntimeFile (String propertyFile)
static int[][] intArray1Dto2D (int[] matrixVal)
static String matrixToSQLArray (double[][] array, int decimalPlaces)
static StringWriter matrixToStringWriterSQL (double[][] array, int decimalPlaces)
Protected Member Functions
Matrix readMatrix (String matrixName, String tableName)
Protected Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
void finalize ()
Additional Inherited Members
Protected Attributes inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_DB_Connector dbCon = null
TPS_ParameterClass parameterClass
Detailed Description
Definition at line 25 of file TPS_ParkAndRideRouter.java.
Member Function Documentation
createPandRMatrix()
Matrix de.dlr.ivf.tapas.tools.TPS_ParkAndRideRouter.createPandRMatrix ()
Definition at line 43 of file TPS_ParkAndRideRouter.java.
References de.dlr.ivf.tapas.util.Matrix.getValue(), and de.dlr.ivf.tapas.util.Matrix.setValue().
Referenced by de.dlr.ivf.tapas.tools.TPS_ParkAndRideRouter.main().
loadMatrices()
void de.dlr.ivf.tapas.tools.TPS_ParkAndRideRouter.loadMatrices (String mivName, String ptName, String walkName, String tableName)
Definition at line 92 of file TPS_ParkAndRideRouter.java.
References de.dlr.ivf.tapas.tools.TPS_ParkAndRideRouter.readMatrix().
Referenced by de.dlr.ivf.tapas.tools.TPS_ParkAndRideRouter.main().
loadTAZRestriction()
void de.dlr.ivf.tapas.tools.TPS_ParkAndRideRouter.loadTAZRestriction (String tazInfo, String table)
Definition at line 98 of file TPS_ParkAndRideRouter.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), and de.dlr.ivf.tapas.util.Matrix.getNumberOfColums().
Referenced by de.dlr.ivf.tapas.tools.TPS_ParkAndRideRouter.main().
main()
static void de.dlr.ivf.tapas.tools.TPS_ParkAndRideRouter.main (String[] args) static
Reimplemented in de.dlr.ivf.tapas.tools.TPS_ParkAndRideAnalysator.
Definition at line 32 of file TPS_ParkAndRideRouter.java.
References de.dlr.ivf.tapas.tools.TPS_ParkAndRideRouter.createPandRMatrix(), de.dlr.ivf.tapas.tools.TPS_ParkAndRideRouter.loadMatrices(), de.dlr.ivf.tapas.tools.TPS_ParkAndRideRouter.loadTAZRestriction(), de.dlr.ivf.tapas.tools.TPS_ParkAndRideRouter.routePnR(), de.dlr.ivf.tapas.tools.TPS_ParkAndRideRouter.saveInterchangeMatrixInDB(), and de.dlr.ivf.tapas.tools.TPS_ParkAndRideRouter.storeMatrixInDB().
readMatrix()
Matrix de.dlr.ivf.tapas.tools.TPS_ParkAndRideRouter.readMatrix (String matrixName, String tableName) protected
Bad copy&paste from TPS_DB_IO, but I do not want to set up a PM-Manager
Parameters
matrixName
tableName
Definition at line 125 of file TPS_ParkAndRideRouter.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.extractIntArray(), and de.dlr.ivf.tapas.util.Matrix.setRawValue().
Referenced by de.dlr.ivf.tapas.tools.TPS_ParkAndRideAnalysator.loadInterchanges(), de.dlr.ivf.tapas.tools.TPS_ParkAndRideRouter.loadMatrices(), de.dlr.ivf.tapas.tools.TPS_ParkAndRideAnalysator.loadMIVDist(), de.dlr.ivf.tapas.tools.TPS_ParkAndRideAnalysator.loadOriginalTimes(), and de.dlr.ivf.tapas.tools.TPS_ParkAndRideAnalysator.loadPNRTimes().
routePnR()
void de.dlr.ivf.tapas.tools.TPS_ParkAndRideRouter.routePnR (double transferTime)
Definition at line 147 of file TPS_ParkAndRideRouter.java.
References de.dlr.ivf.tapas.util.Matrix.getNumberOfColums(), de.dlr.ivf.tapas.util.Matrix.getValue(), de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.MIT, and de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.PT.
Referenced by de.dlr.ivf.tapas.tools.TPS_ParkAndRideRouter.main().
saveInterchangeMatrixInDB()
void de.dlr.ivf.tapas.tools.TPS_ParkAndRideRouter.saveInterchangeMatrixInDB (String matrixName, String tableName)
Definition at line 227 of file TPS_ParkAndRideRouter.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute().
Referenced by de.dlr.ivf.tapas.tools.TPS_ParkAndRideRouter.main().
storeMatrixInDB()
void de.dlr.ivf.tapas.tools.TPS_ParkAndRideRouter.storeMatrixInDB (Matrix matrix, String matrixName, String tableName)
Definition at line 250 of file TPS_ParkAndRideRouter.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute(), de.dlr.ivf.tapas.util.Matrix.getNumberOfColums(), de.dlr.ivf.tapas.util.Matrix.getNumberOfRows(), and de.dlr.ivf.tapas.util.Matrix.getValue().
Referenced by de.dlr.ivf.tapas.tools.TPS_ParkAndRideRouter.main().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/TPS_ParkAndRideRouter.java