TAPAS: de.dlr.ivf.tapas.analyzer.tum.constants.CategoryCombination Class Reference
de.dlr.ivf.tapas.analyzer.tum.constants.CategoryCombination Class Reference
Public Member Functions
CategoryCombination (Enum... categories)
boolean contains (Categories category)
boolean equals (Object obj)
Enum[] getCategories ()
Enum getCategory (Categories category)
int hashCode ()
String toString ()
Static Public Member Functions
static ArrayList< CategoryCombination > listAllCombinations (Categories... categories)
Detailed Description
Immutable object used as key for different splits.
Author
boec_pa
Definition at line 22 of file CategoryCombination.java.
Constructor & Destructor Documentation
CategoryCombination()
de.dlr.ivf.tapas.analyzer.tum.constants.CategoryCombination.CategoryCombination (Enum... categories)
Parameters
categories combination of different enum entries. The order is important for the toString method only. Example: [Mode.BIKE, RegionCode.REGION_0]
Definition at line 32 of file CategoryCombination.java.
References categories, and de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.isValid().
Member Function Documentation
contains()
boolean de.dlr.ivf.tapas.analyzer.tum.constants.CategoryCombination.contains (Categories category)
Definition at line 90 of file CategoryCombination.java.
References categories, and de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.getByClass().
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitData.ModalSplitData().
equals()
boolean de.dlr.ivf.tapas.analyzer.tum.constants.CategoryCombination.equals (Object obj)
Definition at line 98 of file CategoryCombination.java.
getCategories()
Enum [] de.dlr.ivf.tapas.analyzer.tum.constants.CategoryCombination.getCategories ()
Definition at line 107 of file CategoryCombination.java.
References categories.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitData.getMode(), and de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitData.ModalSplitData().
getCategory()
Enum de.dlr.ivf.tapas.analyzer.tum.constants.CategoryCombination.getCategory (Categories category)
Returns the Enum element of the given category.
Parameters
category
Returns
null if the category is not found.
Definition at line 117 of file CategoryCombination.java.
References categories, and de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.getByClass().
hashCode()
int de.dlr.ivf.tapas.analyzer.tum.constants.CategoryCombination.hashCode ()
Definition at line 125 of file CategoryCombination.java.
listAllCombinations()
static ArrayList<CategoryCombination> de.dlr.ivf.tapas.analyzer.tum.constants.CategoryCombination.listAllCombinations (Categories... categories) static
Returns a list of all possible combinations of the given categories.
Parameters
categories
Definition at line 51 of file CategoryCombination.java.
References categories.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.fillBatch(), de.dlr.ivf.tapas.analyzer.tum.results.DatabaseSummaryExport.fillBatch(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.Analyzer.getSplit(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.AnalyzerTest.testCategoryCombination(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralExcelExport.writeAnalysis(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralExcelExport.writeFile(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralExcelExport.writeTab().
toString()
String de.dlr.ivf.tapas.analyzer.tum.constants.CategoryCombination.toString ()
Definition at line 130 of file CategoryCombination.java.
References categories.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitData.getLabel(), and de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.ReferenceDBReader.getMoDcValues().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/tum/constants/CategoryCombination.java