TAPAS: de.dlr.ivf.tapas.scheme.TPS_Stay Class Reference
de.dlr.ivf.tapas.scheme.TPS_Stay Class Reference
Public Member Functions
TPS_Stay (int id, TPS_ActivityConstant actCode, int start, int duration, double startEarlier, double startLater, double durationMinus, double durationPlus, TPS_ParameterClass parameterClass)
int compareTo (TPS_Stay stay)
int getPriority ()
ShoppingClass getTypeOfShoppingGoods ()
boolean hasDetailedShoppingInformation ()
boolean isAtHome ()
boolean isShopping ()
boolean isStay ()
void setActCode (TPS_ActivityConstant actCode)
String toString (String prefix)
Public Member Functions inherited from de.dlr.ivf.tapas.scheme.TPS_Episode
TPS_Episode (int id, TPS_ActivityConstant actCode, int start, int duration, double startEarlier, double startLater, double shorterDuration, double longerDuration, TPS_ParameterClass parameterClass)
TPS_Episode clone ()
TPS_ActivityConstant getActCode ()
double getAlphaEarlier ()
void setAlphaEarlier (double alphaEarlier)
double getAlphaLater ()
void setAlphaLater (double alphaLater)
double getBetaLonger ()
void setBetaLonger (double betaLonger)
double getBetaShorter ()
void setBetaShorter (double betaShorter)
int getId ()
double getLongerDuration ()
void setLongerDuration (double longerDuration)
int getOriginalDuration ()
void setOriginalDuration (int originalDuration)
double getOriginalEnd ()
int getOriginalStart ()
void setOriginalStart (int originalStart)
TPS_SchemePart getSchemePart ()
double getShorterDuration ()
void setShorterDuration (double shorterDuration)
double getStartEarlier ()
void setStartEarlier (double startEarlier)
double getStartLater ()
void setStartLater (double startLater)
int hashCode ()
boolean isLonger (TPS_Episode episode)
boolean isTrip ()
String toString ()
Public Attributes
ShoppingPreferenceAccessibility locationChoiceMotive = ShoppingPreferenceAccessibility.Sonstige
ShoppingPreferenceSupply locationChoiceMotiveSupply = ShoppingPreferenceSupply.Sonstige
Public Attributes inherited from de.dlr.ivf.tapas.scheme.TPS_Episode
boolean isHomePart
Variable which determines, if this part is a HomePart.
int tourNumber
tour number
Private Attributes
int priority
Detailed Description
A Stay indicates an episode at one specific place. A stay can be part of a home part or a tour part.
Definition at line 24 of file TPS_Stay.java.
Constructor & Destructor Documentation
TPS_Stay()
de.dlr.ivf.tapas.scheme.TPS_Stay.TPS_Stay (int id, TPS_ActivityConstant actCode, int start, int duration, double startEarlier, double startLater, double durationMinus, double durationPlus, TPS_ParameterClass parameterClass)
Calls the super constructor with all parameters
Parameters
id ID of the stay
actCode activity code of the stay
start original start time of the stay in seconds
duration original duration of the stay in seconds
startEarlier
startLater
durationMinus
durationPlus
parameterClass parameter class reference
Definition at line 48 of file TPS_Stay.java.
Member Function Documentation
compareTo()
int de.dlr.ivf.tapas.scheme.TPS_Stay.compareTo (TPS_Stay stay)
Definition at line 58 of file TPS_Stay.java.
References de.dlr.ivf.tapas.scheme.TPS_Episode.getOriginalDuration(), de.dlr.ivf.tapas.scheme.TPS_Episode.getOriginalStart(), and de.dlr.ivf.tapas.scheme.TPS_Stay.getPriority().
getPriority()
int de.dlr.ivf.tapas.scheme.TPS_Stay.getPriority ()
Returns the priority of the stay
Returns
priority
Definition at line 77 of file TPS_Stay.java.
Referenced by de.dlr.ivf.tapas.scheme.TPS_Stay.compareTo(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readSchemeSet().
getTypeOfShoppingGoods()
ShoppingClass de.dlr.ivf.tapas.scheme.TPS_Stay.getTypeOfShoppingGoods ()
Determines the type of shopping for a shopping stay from a fixed coding. 51 is short term shopping 54 is mid term shopping 53 is long term shopping the coding is due to historic reasons and makes no sense, except the leading 5
Returns
The shopping class or null if no class available
Definition at line 90 of file TPS_Stay.java.
References de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingClass.NUG, de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingClass.TEX, de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingClass.UEL, and de.dlr.ivf.tapas.constants.TPS_ActivityConstant.TPS_ActivityCodeType.ZBE.
Referenced by de.dlr.ivf.tapas.person.TPS_Person.estimateAccessibilityPreference().
hasDetailedShoppingInformation()
boolean de.dlr.ivf.tapas.scheme.TPS_Stay.hasDetailedShoppingInformation ()
This function checks if the activity has some detailed shopping information available. (short, mid, long term shopping)
Returns
Returns ture if the activity is shopping and detailed information is available. False otherwise
Definition at line 115 of file TPS_Stay.java.
isAtHome()
boolean de.dlr.ivf.tapas.scheme.TPS_Stay.isAtHome ()
Flag indicating whether the stay is part of a home based episode, i.e. the stay is located at home -> housework, telework, watching tv, etc.
Returns
true if the stay is part of a home part, false otherwise
Definition at line 125 of file TPS_Stay.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.batchStoreTrips(), de.dlr.ivf.tapas.plan.TPS_Plan.createOutput(), de.dlr.ivf.tapas.loc.TPS_FocusPointModel.getFocusPoint(), de.dlr.ivf.tapas.plan.TPS_Plan.reset(), de.dlr.ivf.tapas.plan.TPS_LocatedStay.selectLocation(), de.dlr.ivf.tapas.plan.TPS_Plan.TPS_Plan(), and de.dlr.ivf.tapas.plan.TPS_Plan.writeOutputStream().
isShopping()
boolean de.dlr.ivf.tapas.scheme.TPS_Stay.isShopping ()
Definition at line 129 of file TPS_Stay.java.
isStay()
boolean de.dlr.ivf.tapas.scheme.TPS_Stay.isStay ()
Returns
true if this is a TPS_Stay
Reimplemented from de.dlr.ivf.tapas.scheme.TPS_Episode.
Definition at line 139 of file TPS_Stay.java.
setActCode()
void de.dlr.ivf.tapas.scheme.TPS_Stay.setActCode (TPS_ActivityConstant actCode)
Setter for the activity code
Parameters
actCode The activity code
Reimplemented from de.dlr.ivf.tapas.scheme.TPS_Episode.
Definition at line 149 of file TPS_Stay.java.
References de.dlr.ivf.tapas.constants.TPS_ActivityConstant.getCode(), de.dlr.ivf.tapas.constants.TPS_ActivityConstant.TPS_ActivityCodeType.PRIORITY, and de.dlr.ivf.tapas.constants.TPS_ActivityConstant.TPS_ActivityCodeType.ZBE.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readSchemeSet().
toString()
String de.dlr.ivf.tapas.scheme.TPS_Stay.toString (String prefix)
This method should print the object naturally with the given prefix.
Parameters
prefix
Returns
prefix + toString();
Reimplemented from de.dlr.ivf.tapas.scheme.TPS_Episode.
Definition at line 163 of file TPS_Stay.java.
Member Data Documentation
locationChoiceMotive
ShoppingPreferenceAccessibility de.dlr.ivf.tapas.scheme.TPS_Stay.locationChoiceMotive = ShoppingPreferenceAccessibility.Sonstige
Definition at line 25 of file TPS_Stay.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.batchStoreTrips(), and de.dlr.ivf.tapas.person.TPS_Person.estimateAccessibilityPreference().
locationChoiceMotiveSupply
ShoppingPreferenceSupply de.dlr.ivf.tapas.scheme.TPS_Stay.locationChoiceMotiveSupply = ShoppingPreferenceSupply.Sonstige
Definition at line 26 of file TPS_Stay.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.batchStoreTrips(), and de.dlr.ivf.tapas.person.TPS_Person.estimateAccessibilityPreference().
priority
int de.dlr.ivf.tapas.scheme.TPS_Stay.priority private
priority in tour - stays at home have always priority 0; stays in trips have priorities from 0 to infinity (Highest: 0, Lowest: Infinity)
Definition at line 33 of file TPS_Stay.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/scheme/TPS_Stay.java