TAPAS: de.dlr.ivf.tapas.plan.TPS_Plan Class Reference
de.dlr.ivf.tapas.plan.TPS_Plan Class Reference
Public Member Functions
TPS_Plan (TPS_Person person, TPS_PlanEnvironment pe, TPS_Scheme schemeIn, TPS_PersistenceManager pm)
TPS_Plan (TPS_Plan src)
boolean allowsCar (TPS_Car car)
int balanceStarts ()
void calcPlanFeasiblity ()
int compareTo (TPS_Plan o)
List< List< String > > createOutput ()
boolean entersRestrictedAreas ()
double getAcceptanceProbability ()
void setAcceptanceProbability (double acceptanceProbability)
TPS_AdaptedEpisode getAdaptedEpisode (TPS_Episode key)
int getAttributeValue (TPS_Attribute att)
Map< TPS_Attribute, Integer > getAttributes ()
double getBudgetAcceptanceProbability ()
void setBudgetAcceptanceProbability (double budgetAcceptanceProbability)
double getCombinedAcceptanceProbability ()
TPS_AdaptedEpisode getCurrentAdaptedEpisode ()
void setCurrentAdaptedEpisode (TPS_AdaptedEpisode currentAdaptedEpisode)
TPS_LocatedStay getHierarchizedPreviousStay (TPS_AdaptedEpisode adaptedEpisode)
TPS_LocatedStay getLocatedStay (TPS_Stay key)
Collection< TPS_LocatedStay > getLocatedStays ()
TPS_PersistenceManager getPM ()
TPS_ParameterClass getParameters ()
TPS_Person getPerson ()
TPS_PlanEnvironment getPlanEnvironment ()
TPS_PlannedTrip getPlannedTrip (TPS_Trip key)
Collection< TPS_PlannedTrip > getPlannedTrips ()
TPS_LocatedStay getPreviousLocatedStay (TPS_AdaptedEpisode adaptedEpisode)
TPS_Scheme getScheme ()
int getSumOfTimeAdaptation ()
double getTimeAcceptanceProbability ()
void setTimeAcceptanceProbability (double timeAcceptanceProbability)
int getTimeAdaptation ()
double getTravelCosts ()
double getTravelDuration ()
void hackStudents ()
boolean isLocated (TPS_Stay stay)
boolean isPlanAccepted ()
boolean isPlanFeasible ()
void setPlanFeasible (boolean feasible)
void removeAttribute (TPS_Attribute att)
void reset ()
void selectLocationsAndModesAndTravelTimes (TPS_PlanningContext pc)
void setAttributeValue (TPS_Attribute att, int val)
void setTravelTimes ()
String toString ()
String toString (String prefix)
boolean usesCar ()
void writeOutputStream (Writer out) throws IOException
Public Attributes
TPS_PlanEnvironment pe
The environment for this plan.
List< TPS_Car > usedCars = new LinkedList<>()
boolean usesBike = false
boolean mustPayToll = false
Private Attributes
TPS_PersistenceManager PM = null
The reference to the persistence manager.
double budgetAcceptanceProbability
TPS_AdaptedEpisode currentAdaptedEpisode
Adapted Episode, which is currently under work.
final Map< TPS_Stay, TPS_LocatedStay > locatedStays
Map of located stays for stays during this plan.
final Map< TPS_Trip, TPS_PlannedTrip > plannedTrips
A map of planned trips so far.
final TPS_Scheme scheme
the actual selected scheme
boolean feasible = false
the feasibility flag
int adapt = 0
variable for time adaptation analysis
int adaptAbsSum = 0
variable for time adaptation differenceanalysis
Detailed Description
Class for a TAPAS plan. Contains trips, budgets, and many more stuff for plan related work
Definition at line 45 of file TPS_Plan.java.
Constructor & Destructor Documentation
TPS_Plan() [1/2]
de.dlr.ivf.tapas.plan.TPS_Plan.TPS_Plan (TPS_Person person, TPS_PlanEnvironment pe, TPS_Scheme schemeIn, TPS_PersistenceManager pm)
Constructor for this class
Parameters
person the person the scheme was selected for
pe
schemeIn the scheme selected for the person
pm reference to the persistence manager for db-access
Definition at line 81 of file TPS_Plan.java.
References de.dlr.ivf.tapas.constants.TPS_DrivingLicenseInformation.CAR, de.dlr.ivf.tapas.scheme.TPS_Scheme.clone(), code, de.dlr.ivf.tapas.util.TPS_AttributeReader.TPS_Attribute.CURRENT_TAZ_SETTLEMENT_CODE_TAPAS, de.dlr.ivf.tapas.person.TPS_Person.getAge(), de.dlr.ivf.tapas.person.TPS_Person.getAgeClass(), de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.getBbrType(), de.dlr.ivf.tapas.constants.TPS_DrivingLicenseInformation.getCode(), de.dlr.ivf.tapas.constants.TPS_PersonGroup.getCode(), de.dlr.ivf.tapas.constants.TPS_Sex.getCode(), de.dlr.ivf.tapas.constants.TPS_Income.getCode(), de.dlr.ivf.tapas.constants.TPS_AgeClass.getCode(), de.dlr.ivf.tapas.constants.TPS_SettlementSystem.getCode(), de.dlr.ivf.tapas.person.TPS_Person.getDrivingLicenseInformation(), de.dlr.ivf.tapas.person.TPS_Person.getHousehold(), de.dlr.ivf.tapas.person.TPS_Household.getIncome(), de.dlr.ivf.tapas.person.TPS_Household.getLocation(), de.dlr.ivf.tapas.person.TPS_Household.getNumberOfCars(), de.dlr.ivf.tapas.scheme.TPS_Episode.getOriginalStart(), de.dlr.ivf.tapas.person.TPS_Person.getPersonGroup(), de.dlr.ivf.tapas.person.TPS_Person.getSex(), de.dlr.ivf.tapas.loc.TPS_Location.getTrafficAnalysisZone(), de.dlr.ivf.tapas.person.TPS_Person.hasBike, de.dlr.ivf.tapas.person.TPS_Person.hasDrivingLicenseInformation(), de.dlr.ivf.tapas.util.TPS_AttributeReader.TPS_Attribute.HOUSEHOLD_CARS, de.dlr.ivf.tapas.util.TPS_AttributeReader.TPS_Attribute.HOUSEHOLD_INCOME_CLASS_CODE, de.dlr.ivf.tapas.scheme.TPS_Stay.isAtHome(), de.dlr.ivf.tapas.constants.TPS_DrivingLicenseInformation.NO_DRIVING_LICENSE, de.dlr.ivf.tapas.util.TPS_AttributeReader.TPS_Attribute.PERSON_AGE, de.dlr.ivf.tapas.util.TPS_AttributeReader.TPS_Attribute.PERSON_AGE_CLASS_CODE_PERSON_GROUP, de.dlr.ivf.tapas.util.TPS_AttributeReader.TPS_Attribute.PERSON_AGE_CLASS_CODE_STBA, de.dlr.ivf.tapas.util.TPS_AttributeReader.TPS_Attribute.PERSON_DRIVING_LICENSE_CODE, de.dlr.ivf.tapas.util.TPS_AttributeReader.TPS_Attribute.PERSON_HAS_BIKE, de.dlr.ivf.tapas.util.TPS_AttributeReader.TPS_Attribute.PERSON_SEX_CLASS_CODE, de.dlr.ivf.tapas.plan.TPS_LocatedStay.setLocation(), de.dlr.ivf.tapas.constants.TPS_AgeClass.TPS_AgeCodeType.STBA, and de.dlr.ivf.tapas.constants.TPS_SettlementSystem.TPS_SettlementSystemType.TAPAS.
TPS_Plan() [2/2]
de.dlr.ivf.tapas.plan.TPS_Plan.TPS_Plan (TPS_Plan src)
Definition at line 141 of file TPS_Plan.java.
References de.dlr.ivf.tapas.scheme.TPS_Scheme.getEpisodeIterator(), de.dlr.ivf.tapas.scheme.TPS_Episode.getOriginalStart(), de.dlr.ivf.tapas.plan.TPS_Plan.isLocated(), de.dlr.ivf.tapas.plan.TPS_Plan.locatedStays, de.dlr.ivf.tapas.plan.TPS_Plan.pe, de.dlr.ivf.tapas.plan.TPS_Plan.PM, de.dlr.ivf.tapas.plan.TPS_Plan.scheme, de.dlr.ivf.tapas.plan.TPS_LocatedStay.setLocation(), and de.dlr.ivf.tapas.plan.TPS_Plan.usedCars.
Member Function Documentation
allowsCar()
boolean de.dlr.ivf.tapas.plan.TPS_Plan.allowsCar (TPS_Car car)
Returns whether the given car may be used for this plan
Parameters
car The car to use
Returns
Whether the given car may be used
Definition at line 176 of file TPS_Plan.java.
References de.dlr.ivf.tapas.person.TPS_Car.getRangeLeft().
balanceStarts()
int de.dlr.ivf.tapas.plan.TPS_Plan.balanceStarts ()
Function tries to modify the scheme in such way, that the travel times and duration of the stays do not vary too much from the initial times reported. This is done by varying the timing (duration / start / end) of the episodes within the varianze reported for similar schemes
Returns
0 > error (no adoption), !0 > OK
Definition at line 196 of file TPS_Plan.java.
References de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.getDuration(), de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.getEnd(), de.dlr.ivf.tapas.scheme.TPS_TourPart.getPriorisedStayIterable(), de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.getStart(), de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.setStart(), and de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.WARN.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.batchStoreTrips(), and de.dlr.ivf.tapas.person.TPS_Worker.createPersonPlans().
calcPlanFeasiblity()
void de.dlr.ivf.tapas.plan.TPS_Plan.calcPlanFeasiblity ()
This method returns if the selected plan is feasible. If any start of a stay/trip is after the end of the previous trip/stay it returns false. If everythig is ok or there are no stays or trips it returns true.
Returns
result if this plan is feasible
Definition at line 281 of file TPS_Plan.java.
References de.dlr.ivf.tapas.util.Timeline.add(), de.dlr.ivf.tapas.person.TPS_Household.Sorting.COST_OPTIMUM, de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.getDistance(), de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.getDuration(), de.dlr.ivf.tapas.scheme.TPS_Scheme.getEpisodeIterator(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getIntValue(), de.dlr.ivf.tapas.scheme.TPS_Episode.getOriginalStart(), de.dlr.ivf.tapas.persistence.TPS_PersistenceManager.getParameters(), de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.getStart(), de.dlr.ivf.tapas.util.parameters.ParamString.HOUSEHOLD_MEMBERSORTING, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isDefined(), de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.isPlannedTrip(), de.dlr.ivf.tapas.util.parameters.ParamValue.SEC_TIME_SLOT, and de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.setDuration().
Referenced by de.dlr.ivf.tapas.person.TPS_Worker.createPersonPlans().
compareTo()
int de.dlr.ivf.tapas.plan.TPS_Plan.compareTo (TPS_Plan o)
compare Plans according to their acceptance probability
Definition at line 352 of file TPS_Plan.java.
References de.dlr.ivf.tapas.plan.TPS_Plan.getAcceptanceProbability().
createOutput()
List<List<String> > de.dlr.ivf.tapas.plan.TPS_Plan.createOutput ()
Method to create the output for log-file
Returns
Definition at line 361 of file TPS_Plan.java.
References de.dlr.ivf.tapas.constants.TPS_SettlementSystem.TPS_SettlementSystemType.FORDCP, de.dlr.ivf.tapas.scheme.TPS_Episode.getActCode(), de.dlr.ivf.tapas.person.TPS_Person.getAgeClass(), de.dlr.ivf.tapas.constants.TPS_PersonGroup.getCode(), de.dlr.ivf.tapas.constants.TPS_Income.getCode(), de.dlr.ivf.tapas.constants.TPS_ActivityConstant.getCode(), de.dlr.ivf.tapas.constants.TPS_AgeClass.getCode(), de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.getDistance(), de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.getDistanceBeeline(), de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.getDistanceEmptyNet(), de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.getDuration(), de.dlr.ivf.tapas.person.TPS_Person.getHousehold(), de.dlr.ivf.tapas.person.TPS_Person.getId(), de.dlr.ivf.tapas.scheme.TPS_Scheme.getId(), de.dlr.ivf.tapas.person.TPS_Household.getIncome(), de.dlr.ivf.tapas.mode.TPS_ExtMode.getMCTCode(), de.dlr.ivf.tapas.plan.TPS_PlannedTrip.getMode(), de.dlr.ivf.tapas.scheme.TPS_SchemePart.getNextStay(), de.dlr.ivf.tapas.person.TPS_Household.getNumberOfMembers(), de.dlr.ivf.tapas.plan.TPS_PlanEnvironment.getPerson(), de.dlr.ivf.tapas.person.TPS_Person.getPersonGroup(), de.dlr.ivf.tapas.scheme.TPS_SchemePart.getPreviousStay(), de.dlr.ivf.tapas.scheme.TPS_Episode.getSchemePart(), de.dlr.ivf.tapas.person.TPS_Person.getSex(), de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.getStart(), de.dlr.ivf.tapas.scheme.TPS_Scheme.getTourPartIterator(), de.dlr.ivf.tapas.plan.TPS_PlannedTrip.getTrip(), de.dlr.ivf.tapas.scheme.TPS_Stay.isAtHome(), de.dlr.ivf.tapas.person.TPS_Person.isStudent(), de.dlr.ivf.tapas.util.parameters.SimulationType.SCENARIO, de.dlr.ivf.tapas.constants.TPS_AgeClass.TPS_AgeCodeType.STBA, and de.dlr.ivf.tapas.constants.TPS_ActivityConstant.TPS_ActivityCodeType.ZBE.
entersRestrictedAreas()
boolean de.dlr.ivf.tapas.plan.TPS_Plan.entersRestrictedAreas ()
Method to look if a trip of this plan enters a restricted area
Returns
true if it enters a restricted area
Definition at line 504 of file TPS_Plan.java.
getAcceptanceProbability()
double de.dlr.ivf.tapas.plan.TPS_Plan.getAcceptanceProbability ()
Gets the general acceptance probability based on the deviation of the travel time compared to the original travel time.
Returns
A value between 0 and 1 describing the acceptance
Definition at line 518 of file TPS_Plan.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.batchStoreTrips(), de.dlr.ivf.tapas.plan.TPS_Plan.compareTo(), and de.dlr.ivf.tapas.person.TPS_Worker.processHousehold().
getAdaptedEpisode()
TPS_AdaptedEpisode de.dlr.ivf.tapas.plan.TPS_Plan.getAdaptedEpisode (TPS_Episode key)
gets the adapted episode for the given key
Parameters
key key for the episode to look for
Returns
null if key is not in the planed trips or located stays
Definition at line 537 of file TPS_Plan.java.
References de.dlr.ivf.tapas.scheme.TPS_Episode.isStay().
Referenced by de.dlr.ivf.tapas.person.TPS_Worker.assignCarToPlan(), and de.dlr.ivf.tapas.scheme.TPS_TourPart.updateActualTravelDurations().
getAttributes()
Map<TPS_Attribute, Integer> de.dlr.ivf.tapas.plan.TPS_Plan.getAttributes ()
Getter for the attribute map
Returns
Definition at line 564 of file TPS_Plan.java.
Referenced by de.dlr.ivf.tapas.loc.TPS_Region.calculateVOTadds().
getAttributeValue()
int de.dlr.ivf.tapas.plan.TPS_Plan.getAttributeValue (TPS_Attribute att)
Getter for a specific attribute value. Throws a runtime exception, if the value is not set!
Parameters
att The attribute to look for
Returns
the value or RuntimeException
Definition at line 551 of file TPS_Plan.java.
Referenced by de.dlr.ivf.tapas.modechoice.TPS_ModeChoiceTree.descend().
getBudgetAcceptanceProbability()
double de.dlr.ivf.tapas.plan.TPS_Plan.getBudgetAcceptanceProbability ()
Gets the budget acceptance probability based on the deviation of the travel costs compared to the available budget.
Returns
A value between 0 and 1 describing the acceptance
Definition at line 573 of file TPS_Plan.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.batchStoreTrips().
getCombinedAcceptanceProbability()
double de.dlr.ivf.tapas.plan.TPS_Plan.getCombinedAcceptanceProbability ()
Gets the acceptance probability based on the deviation of the travel costs compared to the available budget and the time deviation compared to the time deviation in the scheme class of the plan.
Returns
A value between 0 and 1 describing the acceptance
Definition at line 591 of file TPS_Plan.java.
getCurrentAdaptedEpisode()
TPS_AdaptedEpisode de.dlr.ivf.tapas.plan.TPS_Plan.getCurrentAdaptedEpisode ()
gets the current episode, which is adapted
Returns
Definition at line 600 of file TPS_Plan.java.
getHierarchizedPreviousStay()
TPS_LocatedStay de.dlr.ivf.tapas.plan.TPS_Plan.getHierarchizedPreviousStay (TPS_AdaptedEpisode adaptedEpisode)
Gets the previous Stay with respect tho the Hierarchy of the actual schemepart
Parameters
adaptedEpisode
Returns
Definition at line 619 of file TPS_Plan.java.
References de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.getEpisode(), de.dlr.ivf.tapas.scheme.TPS_TourPart.TPS_StayHierarchy.getPrevStay(), de.dlr.ivf.tapas.scheme.TPS_Episode.getSchemePart(), and de.dlr.ivf.tapas.scheme.TPS_TourPart.getStayHierarchy().
getLocatedStay()
TPS_LocatedStay de.dlr.ivf.tapas.plan.TPS_Plan.getLocatedStay (TPS_Stay key)
gets the located stay for the given key
Parameters
key
Returns
null if key is not found in locatedStays or the stay otherwise
Definition at line 630 of file TPS_Plan.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.batchStoreTrips(), de.dlr.ivf.tapas.loc.TPS_FocusPointModel.getFocusPoint(), de.dlr.ivf.tapas.loc.TPS_MultipleTAZRepresentant.getLocationRepresentatives(), de.dlr.ivf.tapas.plan.TPS_LocatedStay.selectLocation(), de.dlr.ivf.tapas.loc.TPS_SelectLocationWeightBased.selectLocationFromChoiceSet(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.selectLocationFromChoiceSet(), and de.dlr.ivf.tapas.mode.TPS_ModeSet.selectMode().
getLocatedStays()
Collection<TPS_LocatedStay> de.dlr.ivf.tapas.plan.TPS_Plan.getLocatedStays ()
Getter for a Collection of the located stays for this plan.
Returns
The Collection of TPS_LocatedStay
Definition at line 639 of file TPS_Plan.java.
getParameters()
TPS_ParameterClass de.dlr.ivf.tapas.plan.TPS_Plan.getParameters ()
Return the parameter class reference (through the persistence manager)
Returns
parameter class reference
Definition at line 657 of file TPS_Plan.java.
References de.dlr.ivf.tapas.persistence.TPS_PersistenceManager.getParameters().
Referenced by de.dlr.ivf.tapas.plan.acceptance.TPS_PlanEVA1Acceptance.calculateAcceptanceProbBudgetConstraints(), de.dlr.ivf.tapas.plan.acceptance.TPS_PlanEVA1Acceptance.calculateAcceptanceProbTimeConstraints(), de.dlr.ivf.tapas.plan.acceptance.TPS_PlanEVA1Acceptance.isPlanAccepted(), and de.dlr.ivf.tapas.plan.acceptance.TPS_PlanEVA1Acceptance.isPlanAcceptedByOverallTravelTime().
getPerson()
TPS_Person de.dlr.ivf.tapas.plan.TPS_Plan.getPerson ()
gets the person for this plan from the plan environment
Returns
Definition at line 666 of file TPS_Plan.java.
References de.dlr.ivf.tapas.plan.TPS_PlanEnvironment.getPerson().
Referenced by de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree.applyExpertKnowledge(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.batchStoreTrips(), de.dlr.ivf.tapas.plan.acceptance.TPS_PlanEVA1Acceptance.calculateAcceptanceProbBudgetConstraints(), de.dlr.ivf.tapas.modechoice.TPS_UtilityMNL.calculateDelta(), de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixedBS.getDistributionSet(), de.dlr.ivf.tapas.modechoice.TPS_UtilityMNL.getDistributionSet(), de.dlr.ivf.tapas.loc.TPS_FocusPointModel.getFocusPoint(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.getModeLogSum(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessMode.getTravelTime(), de.dlr.ivf.tapas.loc.TPS_SelectWithSingleAccessMode.getTravelTime(), de.dlr.ivf.tapas.person.TPS_Car.selectCar(), de.dlr.ivf.tapas.plan.TPS_LocatedStay.selectLocation(), de.dlr.ivf.tapas.loc.TPS_Region.selectLocation(), de.dlr.ivf.tapas.loc.TPS_SelectLocationWeightBased.selectLocationFromChoiceSet(), and de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.selectLocationFromChoiceSet().
getPlanEnvironment()
TPS_PlanEnvironment de.dlr.ivf.tapas.plan.TPS_Plan.getPlanEnvironment ()
gets the local plan environment
Returns
Definition at line 675 of file TPS_Plan.java.
getPlannedTrip()
TPS_PlannedTrip de.dlr.ivf.tapas.plan.TPS_Plan.getPlannedTrip (TPS_Trip key)
gets the planed trip for the given key
Parameters
key key for the trip to look for
Returns
null if key is not in the planed trips or the trip elsewise
Definition at line 685 of file TPS_Plan.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.batchStoreTrips(), and de.dlr.ivf.tapas.scheme.TPS_TourPart.updateActualTravelDistances().
getPlannedTrips()
Collection<TPS_PlannedTrip> de.dlr.ivf.tapas.plan.TPS_Plan.getPlannedTrips ()
Getter for a Collection of the planned trips for this plan.
Returns
The Collection of TPS_PlannedTrip
Definition at line 694 of file TPS_Plan.java.
getPM()
TPS_PersistenceManager de.dlr.ivf.tapas.plan.TPS_Plan.getPM ()
Return the persistence manager
Returns
The persistence manager
Definition at line 648 of file TPS_Plan.java.
Referenced by de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixedBS.calculateDelta(), de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixedBS.getDistributionSet(), de.dlr.ivf.tapas.loc.TPS_MultipleTAZRepresentant.getLocationRepresentatives(), de.dlr.ivf.tapas.plan.TPS_LocatedStay.TPS_LocatedStay(), and de.dlr.ivf.tapas.scheme.TPS_TourPart.updateActualTravelDistances().
getPreviousLocatedStay()
TPS_LocatedStay de.dlr.ivf.tapas.plan.TPS_Plan.getPreviousLocatedStay (TPS_AdaptedEpisode adaptedEpisode)
gets the previous stay for the actual adapted Episode
Parameters
adaptedEpisode
Returns
Definition at line 704 of file TPS_Plan.java.
References de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.getEpisode(), de.dlr.ivf.tapas.scheme.TPS_SchemePart.getPreviousStay(), and de.dlr.ivf.tapas.scheme.TPS_Episode.getSchemePart().
getScheme()
TPS_Scheme de.dlr.ivf.tapas.plan.TPS_Plan.getScheme ()
gets the actual scheme for this plan
Returns
Definition at line 714 of file TPS_Plan.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Worker.assignCarToPlan(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.batchStoreTrips(), de.dlr.ivf.tapas.plan.acceptance.TPS_PlanEVA1Acceptance.calculateAcceptanceProbTimeConstraints(), and de.dlr.ivf.tapas.plan.acceptance.TPS_PlanEVA1Acceptance.isPlanAcceptedByOverallTravelTime().
getSumOfTimeAdaptation()
int de.dlr.ivf.tapas.plan.TPS_Plan.getSumOfTimeAdaptation ()
This method returns the absolute sum of time adaptations to make this plan feasible
Returns
the time adaptation in seconds
Definition at line 723 of file TPS_Plan.java.
getTimeAcceptanceProbability()
double de.dlr.ivf.tapas.plan.TPS_Plan.getTimeAcceptanceProbability ()
Gets the budget acceptance probability based on the deviation of the travel time deviation compared to the time deviation in the scheme class of the plan.
Returns
A value between 0 and 1 describing the acceptance
Definition at line 732 of file TPS_Plan.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.batchStoreTrips().
getTimeAdaptation()
int de.dlr.ivf.tapas.plan.TPS_Plan.getTimeAdaptation ()
This method returns the time adaptation to make this plan feasible
Returns
the time adaptation in seconds
Definition at line 750 of file TPS_Plan.java.
getTravelCosts()
double de.dlr.ivf.tapas.plan.TPS_Plan.getTravelCosts ()
Calculates the financial expenditures for the modal use in the scheme in Euro
Returns
sum of the travel costs
Definition at line 759 of file TPS_Plan.java.
References de.dlr.ivf.tapas.util.parameters.CURRENCY.EUR.
Referenced by de.dlr.ivf.tapas.plan.acceptance.TPS_PlanEVA1Acceptance.calculateAcceptanceProbBudgetConstraints().
getTravelDuration()
double de.dlr.ivf.tapas.plan.TPS_Plan.getTravelDuration ()
Calculates the aggregate travel time of the scheme resulting from the chosen modes and locations.
Returns
sum of travel time of the scheme
Definition at line 772 of file TPS_Plan.java.
Referenced by de.dlr.ivf.tapas.plan.acceptance.TPS_PlanEVA1Acceptance.calculateAcceptanceProbTimeConstraints(), and de.dlr.ivf.tapas.plan.acceptance.TPS_PlanEVA1Acceptance.isPlanAcceptedByOverallTravelTime().
hackStudents()
void de.dlr.ivf.tapas.plan.TPS_Plan.hackStudents ()
Change all 410 codes for students to 411
Definition at line 783 of file TPS_Plan.java.
References de.dlr.ivf.tapas.constants.TPS_ActivityConstant.getActivityCodeByTypeAndCode(), de.dlr.ivf.tapas.constants.TPS_ActivityConstant.TPS_ActivityConstantAttribute.SCHOOL, and de.dlr.ivf.tapas.constants.TPS_ActivityConstant.TPS_ActivityCodeType.ZBE.
isLocated()
boolean de.dlr.ivf.tapas.plan.TPS_Plan.isLocated (TPS_Stay stay)
Determines whether a stay has been located
Parameters
stay stay to check
Returns
true if a location has been chosen; false else
Definition at line 799 of file TPS_Plan.java.
Referenced by de.dlr.ivf.tapas.plan.TPS_LocatedStay.selectLocation(), and de.dlr.ivf.tapas.plan.TPS_Plan.TPS_Plan().
isPlanAccepted()
boolean de.dlr.ivf.tapas.plan.TPS_Plan.isPlanAccepted ()
Determines whether the travel times resulting from the chosen modes and locations for the plan exceed too much the travel times initially scheduled for the scheme. The acceptance limit is defined in the configuration.
Returns
true, if the plan with its travel times is not too far off the designated travel times; false if the travel times exceed the maximum difference defined in the configuration
Definition at line 810 of file TPS_Plan.java.
References de.dlr.ivf.tapas.plan.TPS_PlanEnvironment.isPlanAccepted().
Referenced by de.dlr.ivf.tapas.plan.TPS_PlanEnvironment.addPlan(), and de.dlr.ivf.tapas.person.TPS_Worker.createPersonPlans().
isPlanFeasible()
boolean de.dlr.ivf.tapas.plan.TPS_Plan.isPlanFeasible ()
This method returns if the selected plan is feasible. If any start of a stay/trip is after the end of the previous trip/stay it returns false. If everythig is ok or there are no stays or trips it returns true.
Returns
result if this plan is feasible
Definition at line 821 of file TPS_Plan.java.
removeAttribute()
void de.dlr.ivf.tapas.plan.TPS_Plan.removeAttribute (TPS_Attribute att)
Removes a given Attribute. If it does not exist nothing happens.
Parameters
att The Attribute to remove
Definition at line 839 of file TPS_Plan.java.
Referenced by de.dlr.ivf.tapas.mode.TPS_ModeSet.getModeDistribution().
reset()
void de.dlr.ivf.tapas.plan.TPS_Plan.reset ()
Resets a scheme to its initial state; e.g. clears modes and locations selected
Definition at line 846 of file TPS_Plan.java.
References de.dlr.ivf.tapas.scheme.TPS_Scheme.getEpisodeIterator(), de.dlr.ivf.tapas.scheme.TPS_Episode.getOriginalDuration(), de.dlr.ivf.tapas.scheme.TPS_Scheme.getTourPartIterator(), de.dlr.ivf.tapas.plan.TPS_LocatedStay.init(), de.dlr.ivf.tapas.scheme.TPS_Stay.isAtHome(), and de.dlr.ivf.tapas.plan.TPS_LocatedStay.setLocation().
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.batchStoreTrips().
selectLocationsAndModesAndTravelTimes()
void de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes (TPS_PlanningContext pc)
Initiates the determination of locations and modes for stays and trips of the scheme
Definition at line 875 of file TPS_Plan.java.
References de.dlr.ivf.tapas.plan.TPS_PlanningContext.carForThisPlan, de.dlr.ivf.tapas.util.TPS_AttributeReader.TPS_Attribute.CURRENT_EPISODE_ACTIVITY_CODE_TAPAS, de.dlr.ivf.tapas.util.TPS_AttributeReader.TPS_Attribute.CURRENT_TAZ_SETTLEMENT_CODE_TAPAS, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.DEBUG, de.dlr.ivf.tapas.constants.TPS_ActivityConstant.DUMMY, de.dlr.ivf.tapas.log.TPS_LoggingInterface.HierarchyLogLevel.EPISODE, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.person.TPS_Person.estimateAccessibilityPreference(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.FINE, de.dlr.ivf.tapas.plan.TPS_PlanningContext.fixLocationAtBase, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_USE_FIXED_LOCS_ON_BASE, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_USE_SHOPPING_MOTIVES, de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.getBbrType(), de.dlr.ivf.tapas.loc.TPS_Location.getBlock(), de.dlr.ivf.tapas.scheme.TPS_TourPart.getCar(), de.dlr.ivf.tapas.constants.TPS_SettlementSystem.getCode(), de.dlr.ivf.tapas.plan.TPS_LocatedStay.getEpisode(), de.dlr.ivf.tapas.loc.TPS_Block.getId(), de.dlr.ivf.tapas.loc.TPS_Location.getId(), de.dlr.ivf.tapas.scheme.TPS_Episode.getId(), de.dlr.ivf.tapas.scheme.TPS_SchemePart.getId(), de.dlr.ivf.tapas.plan.TPS_LocatedStay.getLocation(), de.dlr.ivf.tapas.plan.TPS_LocatedStay.getModeArr(), de.dlr.ivf.tapas.plan.TPS_LocatedStay.getModeDep(), de.dlr.ivf.tapas.persistence.TPS_PersistenceManager.getModeSet(), de.dlr.ivf.tapas.mode.TPS_ExtMode.getName(), de.dlr.ivf.tapas.scheme.TPS_TourPart.TPS_StayHierarchy.getNextStay(), de.dlr.ivf.tapas.scheme.TPS_TourPart.getNextTrip(), de.dlr.ivf.tapas.plan.TPS_PlanEnvironment.getNumberOfRejectedPlans(), de.dlr.ivf.tapas.persistence.TPS_PersistenceManager.getParameters(), de.dlr.ivf.tapas.plan.TPS_PlanEnvironment.getPerson(), de.dlr.ivf.tapas.scheme.TPS_TourPart.getPreviousTrip(), de.dlr.ivf.tapas.scheme.TPS_TourPart.TPS_StayHierarchy.getPrevStay(), de.dlr.ivf.tapas.scheme.TPS_TourPart.getPriorisedStayIterable(), de.dlr.ivf.tapas.scheme.TPS_TourPart.getStayHierarchy(), de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.getTAZId(), de.dlr.ivf.tapas.loc.TPS_Location.getTrafficAnalysisZone(), de.dlr.ivf.tapas.scheme.TPS_TourPart.getUsedMode(), de.dlr.ivf.tapas.loc.TPS_Location.hasBlock(), de.dlr.ivf.tapas.util.TPS_AttributeReader.TPS_Attribute.HOUSEHOLD_CARS, de.dlr.ivf.tapas.plan.TPS_PlanningContext.influenceBikeUsageInPlan, de.dlr.ivf.tapas.plan.TPS_PlanningContext.influenceCarUsageInPlan, de.dlr.ivf.tapas.plan.TPS_PlanningContext.isBikeAvailable, de.dlr.ivf.tapas.mode.TPS_ExtMode.isBikeUsed(), de.dlr.ivf.tapas.scheme.TPS_TourPart.isBikeUsed(), de.dlr.ivf.tapas.mode.TPS_ExtMode.isCarUsed(), de.dlr.ivf.tapas.scheme.TPS_TourPart.isCarUsed(), de.dlr.ivf.tapas.scheme.TPS_SchemePart.isFirst(), de.dlr.ivf.tapas.constants.TPS_ActivityConstant.isFix, de.dlr.ivf.tapas.scheme.TPS_TourPart.isFixedModeUsed(), de.dlr.ivf.tapas.scheme.TPS_SchemePart.isLast(), de.dlr.ivf.tapas.plan.TPS_LocatedStay.isLocated(), de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.isRestricted, de.dlr.ivf.tapas.person.TPS_Car.isRestricted(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isTrue(), de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.plan.TPS_PlanningContext.pe, de.dlr.ivf.tapas.util.TPS_AttributeReader.TPS_Attribute.PERSON_HAS_BIKE, de.dlr.ivf.tapas.plan.TPS_PlanningContext.previousTrip, de.dlr.ivf.tapas.person.TPS_Car.selectCar(), de.dlr.ivf.tapas.plan.TPS_LocatedStay.selectLocation(), de.dlr.ivf.tapas.mode.TPS_ModeSet.selectMode(), de.dlr.ivf.tapas.plan.TPS_LocatedStay.setLocation(), de.dlr.ivf.tapas.plan.TPS_LocatedStay.setModeArr(), de.dlr.ivf.tapas.plan.TPS_LocatedStay.setModeDep(), de.dlr.ivf.tapas.scheme.TPS_TourPart.setUsedMode(), de.dlr.ivf.tapas.mode.TPS_ExtMode.simpleWalk, de.dlr.ivf.tapas.constants.TPS_ActivityConstant.TPS_ActivityCodeType.TAPAS, de.dlr.ivf.tapas.constants.TPS_SettlementSystem.TPS_SettlementSystemType.TAPAS, de.dlr.ivf.tapas.scheme.TPS_TourPart.updateActualTravelDurations(), and de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.WARN.
Referenced by de.dlr.ivf.tapas.person.TPS_Worker.createPersonPlans().
setAcceptanceProbability()
void de.dlr.ivf.tapas.plan.TPS_Plan.setAcceptanceProbability (double acceptanceProbability)
Sets the general acceptance probability based on the deviation of the travel time compared to the original travel time.
Parameters
acceptanceProbability A value between 0 and 1 describing the acceptance
Definition at line 527 of file TPS_Plan.java.
Referenced by de.dlr.ivf.tapas.plan.acceptance.TPS_PlanEVA1Acceptance.isPlanAcceptedByOverallTravelTime().
setAttributeValue()
void de.dlr.ivf.tapas.plan.TPS_Plan.setAttributeValue (TPS_Attribute att, int val)
Setter for a specific attribute of this plan
Parameters
att the Attribute from TPS_Attribute
val the value
Definition at line 1140 of file TPS_Plan.java.
Referenced by de.dlr.ivf.tapas.mode.TPS_ModeSet.getModeDistribution(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.getModeLogSum(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessMode.getTravelTime(), de.dlr.ivf.tapas.loc.TPS_SelectWithSingleAccessMode.getTravelTime(), and de.dlr.ivf.tapas.plan.TPS_LocatedStay.selectLocation().
setBudgetAcceptanceProbability()
void de.dlr.ivf.tapas.plan.TPS_Plan.setBudgetAcceptanceProbability (double budgetAcceptanceProbability)
Sets the budget acceptance probability based on the deviation of the travel costs compared to the available budget.
Parameters
budgetAcceptanceProbability A value between 0 and 1 describing the acceptance
Definition at line 582 of file TPS_Plan.java.
Referenced by de.dlr.ivf.tapas.plan.acceptance.TPS_PlanEVA1Acceptance.calculateAcceptanceProbBudgetConstraints().
setCurrentAdaptedEpisode()
void de.dlr.ivf.tapas.plan.TPS_Plan.setCurrentAdaptedEpisode (TPS_AdaptedEpisode currentAdaptedEpisode)
sets the currently adapted episode
Parameters
currentAdaptedEpisode
Definition at line 609 of file TPS_Plan.java.
setPlanFeasible()
void de.dlr.ivf.tapas.plan.TPS_Plan.setPlanFeasible (boolean feasible)
sets the feasibility of this plan by expert analysis
Parameters
feasible the feasibility for this plan
Definition at line 830 of file TPS_Plan.java.
Referenced by de.dlr.ivf.tapas.plan.acceptance.TPS_PlanEVA1Acceptance.isPlanAcceptedByOverallTravelTime().
setTimeAcceptanceProbability()
void de.dlr.ivf.tapas.plan.TPS_Plan.setTimeAcceptanceProbability (double timeAcceptanceProbability)
Sets the budget acceptance probability based on the deviation of the travel time deviation compared to the time deviation in the scheme class of the plan.
Parameters
timeAcceptanceProbability A value between 0 and 1 describing the acceptance
Definition at line 741 of file TPS_Plan.java.
Referenced by de.dlr.ivf.tapas.plan.acceptance.TPS_PlanEVA1Acceptance.calculateAcceptanceProbTimeConstraints().
setTravelTimes()
void de.dlr.ivf.tapas.plan.TPS_Plan.setTravelTimes ()
Calls for each trip of the plan the routine setTravelTime von TPS_PlannedTrip.
Definition at line 1147 of file TPS_Plan.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Worker.createPersonPlans().
toString() [1/2]
String de.dlr.ivf.tapas.plan.TPS_Plan.toString ()
overrides toString to use local toString function
Definition at line 1204 of file TPS_Plan.java.
toString() [2/2]
String de.dlr.ivf.tapas.plan.TPS_Plan.toString (String prefix)
puts a prefix to the toString functionality of this specially formated output. PREFIX is currently disabled!
Implements de.dlr.ivf.tapas.util.ExtendedWritable.
Definition at line 1212 of file TPS_Plan.java.
References de.dlr.ivf.tapas.scheme.TPS_Scheme.getEpisodeIterator(), and de.dlr.ivf.tapas.scheme.TPS_Scheme.toString().
usesCar()
boolean de.dlr.ivf.tapas.plan.TPS_Plan.usesCar ()
Returns whether a car is used within this plan
Returns
Whether a car is used
Definition at line 1234 of file TPS_Plan.java.
Referenced by de.dlr.ivf.tapas.plan.TPS_PlanningContext.needsOtherModeAlternatives(), and de.dlr.ivf.tapas.person.TPS_Worker.processHousehold().
writeOutputStream()
void de.dlr.ivf.tapas.plan.TPS_Plan.writeOutputStream (Writer out) throws IOException
Method to write this trip to an output-stream
Parameters
out
Exceptions
IOException
Definition at line 1244 of file TPS_Plan.java.
References de.dlr.ivf.tapas.constants.TPS_SettlementSystem.TPS_SettlementSystemType.FORDCP, de.dlr.ivf.tapas.scheme.TPS_Episode.getActCode(), de.dlr.ivf.tapas.person.TPS_Person.getAgeClass(), de.dlr.ivf.tapas.constants.TPS_PersonGroup.getCode(), de.dlr.ivf.tapas.constants.TPS_Income.getCode(), de.dlr.ivf.tapas.constants.TPS_ActivityConstant.getCode(), de.dlr.ivf.tapas.constants.TPS_AgeClass.getCode(), de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.getDistance(), de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.getDistanceBeeline(), de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.getDistanceEmptyNet(), de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.getDuration(), de.dlr.ivf.tapas.person.TPS_Person.getHousehold(), de.dlr.ivf.tapas.person.TPS_Person.getId(), de.dlr.ivf.tapas.scheme.TPS_Scheme.getId(), de.dlr.ivf.tapas.person.TPS_Household.getIncome(), de.dlr.ivf.tapas.mode.TPS_ExtMode.getMCTCode(), de.dlr.ivf.tapas.plan.TPS_PlannedTrip.getMode(), de.dlr.ivf.tapas.scheme.TPS_SchemePart.getNextStay(), de.dlr.ivf.tapas.person.TPS_Household.getNumberOfMembers(), de.dlr.ivf.tapas.plan.TPS_PlanEnvironment.getPerson(), de.dlr.ivf.tapas.person.TPS_Person.getPersonGroup(), de.dlr.ivf.tapas.scheme.TPS_SchemePart.getPreviousStay(), de.dlr.ivf.tapas.scheme.TPS_Episode.getSchemePart(), de.dlr.ivf.tapas.person.TPS_Person.getSex(), de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.getStart(), de.dlr.ivf.tapas.scheme.TPS_Scheme.getTourPartIterator(), de.dlr.ivf.tapas.plan.TPS_PlannedTrip.getTrip(), de.dlr.ivf.tapas.scheme.TPS_Stay.isAtHome(), de.dlr.ivf.tapas.person.TPS_Person.isStudent(), de.dlr.ivf.tapas.util.parameters.SimulationType.SCENARIO, de.dlr.ivf.tapas.constants.TPS_AgeClass.TPS_AgeCodeType.STBA, and de.dlr.ivf.tapas.constants.TPS_ActivityConstant.TPS_ActivityCodeType.ZBE.
Member Data Documentation
adapt
int de.dlr.ivf.tapas.plan.TPS_Plan.adapt = 0 private
variable for time adaptation analysis
Definition at line 69 of file TPS_Plan.java.
adaptAbsSum
int de.dlr.ivf.tapas.plan.TPS_Plan.adaptAbsSum = 0 private
variable for time adaptation differenceanalysis
Definition at line 71 of file TPS_Plan.java.
budgetAcceptanceProbability
double de.dlr.ivf.tapas.plan.TPS_Plan.budgetAcceptanceProbability private
Definition at line 57 of file TPS_Plan.java.
currentAdaptedEpisode
TPS_AdaptedEpisode de.dlr.ivf.tapas.plan.TPS_Plan.currentAdaptedEpisode private
Adapted Episode, which is currently under work.
Definition at line 59 of file TPS_Plan.java.
feasible
boolean de.dlr.ivf.tapas.plan.TPS_Plan.feasible = false private
the feasibility flag
Definition at line 67 of file TPS_Plan.java.
locatedStays
final Map<TPS_Stay, TPS_LocatedStay> de.dlr.ivf.tapas.plan.TPS_Plan.locatedStays private
Map of located stays for stays during this plan.
Definition at line 61 of file TPS_Plan.java.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.TPS_Plan().
mustPayToll
boolean de.dlr.ivf.tapas.plan.TPS_Plan.mustPayToll = false
Definition at line 50 of file TPS_Plan.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Worker.assignCarToPlan(), and de.dlr.ivf.tapas.mode.TPS_ModeSet.selectMode0().
pe
TPS_PlanEnvironment de.dlr.ivf.tapas.plan.TPS_Plan.pe
The environment for this plan.
Definition at line 47 of file TPS_Plan.java.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.TPS_Plan().
plannedTrips
final Map<TPS_Trip, TPS_PlannedTrip> de.dlr.ivf.tapas.plan.TPS_Plan.plannedTrips private
A map of planned trips so far.
Definition at line 63 of file TPS_Plan.java.
PM
TPS_PersistenceManager de.dlr.ivf.tapas.plan.TPS_Plan.PM = null private
The reference to the persistence manager.
Definition at line 55 of file TPS_Plan.java.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.TPS_Plan().
scheme
final TPS_Scheme de.dlr.ivf.tapas.plan.TPS_Plan.scheme private
the actual selected scheme
Definition at line 65 of file TPS_Plan.java.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.TPS_Plan().
usedCars
List<TPS_Car> de.dlr.ivf.tapas.plan.TPS_Plan.usedCars = new LinkedList<>()
Definition at line 48 of file TPS_Plan.java.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.TPS_Plan().
usesBike
boolean de.dlr.ivf.tapas.plan.TPS_Plan.usesBike = false
Definition at line 49 of file TPS_Plan.java.
Referenced by de.dlr.ivf.tapas.plan.TPS_PlanningContext.needsOtherModeAlternatives(), and de.dlr.ivf.tapas.person.TPS_Worker.processHousehold().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/plan/TPS_Plan.java