TAPAS: de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor Class Reference
de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor Class Reference
Classes
class StreetTagEntry
Public Member Functions
StreetnameProcessor ()
StreetTagEntry containsTag (String input)
String getCity ()
void setCity (String city)
String getStreet ()
void setStreet (String street)
String getStreetNumber ()
void setStreetNumber (String streetNumber)
String getZipCode ()
void setZipCode (String zipCode)
boolean processStreet (String input)
String replaceStreetTag (String input)
Private Member Functions
String capStupidAmendments (String number)
boolean checkCharacterAfterTag (String input, String tag)
String replaceStreetTag (String input, StreetTagEntry tag)
Private Attributes
final List< StreetTagEntry > streetTagList = new ArrayList<>()
String street = null
String streetNumber = null
String zipCode = null
String city = null
String inputString = null
Detailed Description
Definition at line 15 of file StreetnameProcessor.java.
Constructor & Destructor Documentation
StreetnameProcessor()
de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.StreetnameProcessor ()
Default constructor. fills the street tag list.
Definition at line 44 of file StreetnameProcessor.java.
Member Function Documentation
capStupidAmendments()
String de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.capStupidAmendments (String number) private
Definition at line 114 of file StreetnameProcessor.java.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.processStreet().
checkCharacterAfterTag()
boolean de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.checkCharacterAfterTag (String input, String tag) private
Definition at line 149 of file StreetnameProcessor.java.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.containsTag().
containsTag()
StreetTagEntry de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.containsTag (String input)
This method checks if the input string contains a street tag. Search starts from the right!
Parameters
input The String to test
Returns
The found street tag or null if no tag is found.
Definition at line 168 of file StreetnameProcessor.java.
References de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.checkCharacterAfterTag().
Referenced by de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.processStreet(), and de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.replaceStreetTag().
getCity()
String de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.getCity ()
Definition at line 186 of file StreetnameProcessor.java.
References de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.city.
getStreet()
String de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.getStreet ()
Definition at line 194 of file StreetnameProcessor.java.
References de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.street.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.main().
getStreetNumber()
String de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.getStreetNumber ()
Definition at line 202 of file StreetnameProcessor.java.
References de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.streetNumber.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.main().
getZipCode()
String de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.getZipCode ()
Definition at line 210 of file StreetnameProcessor.java.
References de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.zipCode.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.main().
processStreet()
boolean de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.processStreet (String input)
Definition at line 218 of file StreetnameProcessor.java.
References de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.capStupidAmendments(), de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.containsTag(), de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.inputString, de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.replaceStreetTag(), de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.setStreet(), and de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.streetNumber.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.main().
replaceStreetTag() [1/2]
String de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.replaceStreetTag (String input)
Definition at line 340 of file StreetnameProcessor.java.
References de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.containsTag().
Referenced by de.dlr.ivf.tapas.tools.locationallocation.Locator.generateQueriesForAdressToCoordinate(), de.dlr.ivf.tapas.tools.locationallocation.Locator.localizeLocation(), de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.main(), and de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.processStreet().
replaceStreetTag() [2/2]
String de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.replaceStreetTag (String input, StreetTagEntry tag) private
Definition at line 345 of file StreetnameProcessor.java.
References de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.inputString.
setCity()
void de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.setCity (String city)
Definition at line 190 of file StreetnameProcessor.java.
References de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.city.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.LocationProcessor.main().
setStreet()
void de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.setStreet (String street)
Definition at line 198 of file StreetnameProcessor.java.
References de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.street.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.processStreet().
setStreetNumber()
void de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.setStreetNumber (String streetNumber)
Definition at line 206 of file StreetnameProcessor.java.
References de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.streetNumber.
setZipCode()
void de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.setZipCode (String zipCode)
Definition at line 214 of file StreetnameProcessor.java.
References de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.zipCode.
Member Data Documentation
city
String de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.city = null private
The city. Input and output.
Definition at line 36 of file StreetnameProcessor.java.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.getCity(), and de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.setCity().
inputString
String de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.inputString = null private
The input string. Input.
Definition at line 40 of file StreetnameProcessor.java.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.processStreet(), and de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.replaceStreetTag().
street
String de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.street = null private
The street name. Input and output.
Definition at line 24 of file StreetnameProcessor.java.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.getStreet(), and de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.setStreet().
streetNumber
String de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.streetNumber = null private
The street number. Input and output.
Definition at line 28 of file StreetnameProcessor.java.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.getStreetNumber(), de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.processStreet(), and de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.setStreetNumber().
streetTagList
final List<StreetTagEntry> de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.streetTagList = new ArrayList<>() private
The List for the street tags
Definition at line 20 of file StreetnameProcessor.java.
zipCode
String de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.zipCode = null private
The zip code. Input and output.
Definition at line 32 of file StreetnameProcessor.java.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.getZipCode(), and de.dlr.ivf.tapas.tools.locationallocation.StreetnameProcessor.setZipCode().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/locationallocation/StreetnameProcessor.java