TAPAS: de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer Class Reference
de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer Class Reference
Public Member Functions
StandaloneRegionAnalyzer (String simulation, Set< Integer > acceptedTAZs, TPS_DB_Connector connection)
StandaloneRegionAnalyzer (String[] simulation, Set< Integer > acceptedTAZs, TPS_DB_Connector connection)
String getSimulation ()
String getSource ()
Static Public Member Functions
static void main (String[] args) throws IOException, ClassNotFoundException, InterruptedException, ExecutionException
Static Public Attributes
static final int SUCCESS = 0
static final int FAILED = 1
Protected Member Functions
Integer doInBackground () throws SQLException, ClassNotFoundException, IOException, BadLocationException
void done ()
Private Attributes
DBTripReader tripReader
String source
final LinkedList< String > simulations = new LinkedList<>()
String simulation
final TPS_DB_Connector connection
Detailed Description
This RegionAnalyzer starts a standard analysis of the given simkey as a background task.
You may override the StandaloneRegionAnalyzer#done() method to have a callback.
Author
boec_pa
Definition at line 37 of file StandaloneRegionAnalyzer.java.
Constructor & Destructor Documentation
StandaloneRegionAnalyzer() [1/2]
de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.StandaloneRegionAnalyzer (String simulation, Set< Integer > acceptedTAZs, TPS_DB_Connector connection)
Parameters
simulation the simulation to be analyzed.
acceptedTAZs may be null. All trips not starting or ending in these TAZs will be ignored.
connection the database connection to be used.
Exceptions
ClassNotFoundException
IOException when some parameter loading does not work.
SQLException when some database connection does not work.
Definition at line 57 of file StandaloneRegionAnalyzer.java.
References de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.connection, de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.simulation, and de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.source.
Referenced by de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.main().
StandaloneRegionAnalyzer() [2/2]
de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.StandaloneRegionAnalyzer (String[] simulation, Set< Integer > acceptedTAZs, TPS_DB_Connector connection)
Definition at line 63 of file StandaloneRegionAnalyzer.java.
References de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.connection, and de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.simulation.
Member Function Documentation
doInBackground()
Integer de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.doInBackground () throws SQLException, ClassNotFoundException, IOException, BadLocationException protected
Definition at line 98 of file StandaloneRegionAnalyzer.java.
References de.dlr.ivf.tapas.analyzer.gui.AbstractCoreProcess.cancelFinish(), de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.close(), de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.connection, de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.FAILED, de.dlr.ivf.tapas.constants.TPS_SettlementSystem.TPS_SettlementSystemType.FORDCP, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection(), de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.getIterator(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getParameters(), de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.getProgress(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.init(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.RegionAnalyzer.prepare(), de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.simulation, de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.simulations, de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.SUCCESS, de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.tripReader, and de.dlr.ivf.tapas.analyzer.tum.results.DatabaseSummaryExport.writeSummary().
done()
void de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.done () protected
Definition at line 187 of file StandaloneRegionAnalyzer.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.main().
getSimulation()
String de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.getSimulation ()
Definition at line 194 of file StandaloneRegionAnalyzer.java.
References de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.simulation.
getSource()
String de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.getSource ()
Definition at line 199 of file StandaloneRegionAnalyzer.java.
References de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.source.
main()
static void de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.main (String[] args) throws IOException, ClassNotFoundException, InterruptedException, ExecutionException static
For testing purposes only!
Exceptions
IOException
SQLException
ClassNotFoundException
ExecutionException
InterruptedException
Definition at line 77 of file StandaloneRegionAnalyzer.java.
References de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.done(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.loadRuntimeParameters(), and de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.StandaloneRegionAnalyzer().
Member Data Documentation
connection
final TPS_DB_Connector de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.connection private
Definition at line 46 of file StandaloneRegionAnalyzer.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.doInBackground(), and de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.StandaloneRegionAnalyzer().
FAILED
final int de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.FAILED = 1 static
Definition at line 40 of file StandaloneRegionAnalyzer.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.doInBackground().
simulation
String de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.simulation private
Definition at line 45 of file StandaloneRegionAnalyzer.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.doInBackground(), de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.getSimulation(), and de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.StandaloneRegionAnalyzer().
simulations
final LinkedList<String> de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.simulations = new LinkedList<>() private
Definition at line 44 of file StandaloneRegionAnalyzer.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.doInBackground().
source
String de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.source private
Definition at line 43 of file StandaloneRegionAnalyzer.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.getSource(), and de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.StandaloneRegionAnalyzer().
SUCCESS
final int de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.SUCCESS = 0 static
Definition at line 39 of file StandaloneRegionAnalyzer.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.doInBackground().
tripReader
DBTripReader de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.tripReader private
Definition at line 42 of file StandaloneRegionAnalyzer.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.doInBackground().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/tum/results/StandaloneRegionAnalyzer.java