TAPAS: de.dlr.ivf.scripts.DiscoImporter Class Reference
de.dlr.ivf.scripts.DiscoImporter Class Reference
Public Member Functions
void createTables (String basename)
void fillCars (String basename)
void fillTables (String basename, String fileName)
void findCarIDs (String basename)
Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_BasicConnectionClass ()
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass)
TPS_BasicConnectionClass (String loginFile)
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass, String loginFile)
boolean checkMatrixName (String matrixName)
TPS_ParameterClass getParameters ()
String readParameter (String simKey, String paramKey)
void storeInDB (String matrixName, double[][] matrix, int decimalPlaces)
Static Public Member Functions
static void main (String[] args)
Static Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
static double[][] array1Dto2D (Integer[] matrixVal)
static double[][] array1Dto2D (int[] matrixVal)
static File getRuntimeFile (boolean forceNewFile)
static File getRuntimeFile (String propertyFile, boolean forceNewFile)
static File getRuntimeFile ()
static File getRuntimeFile (String propertyFile)
static int[][] intArray1Dto2D (int[] matrixVal)
static String matrixToSQLArray (double[][] array, int decimalPlaces)
static StringWriter matrixToStringWriterSQL (double[][] array, int decimalPlaces)
Additional Inherited Members
Protected Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
void finalize ()
Protected Attributes inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_DB_Connector dbCon = null
TPS_ParameterClass parameterClass
Detailed Description
Class which realizes the DB-Import for a DISCO-Sample from STATA.
This class handles the table creation, DB import and car clustering
Author
hein_mh
Definition at line 27 of file DiscoImporter.java.
Member Function Documentation
createTables()
void de.dlr.ivf.scripts.DiscoImporter.createTables (String basename)
Method to create the tables for the given basename. Existing tables will be deleted!
Parameters
basename
Definition at line 57 of file DiscoImporter.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute().
Referenced by de.dlr.ivf.scripts.DiscoImporter.main().
fillCars()
void de.dlr.ivf.scripts.DiscoImporter.fillCars (String basename)
This method finds all distinct car groups and stores them in the car-table
Parameters
basename the table name
Definition at line 102 of file DiscoImporter.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery().
Referenced by de.dlr.ivf.scripts.DiscoImporter.main().
fillTables()
void de.dlr.ivf.scripts.DiscoImporter.fillTables (String basename, String fileName)
Method to import the data from the given file to the household table
Parameters
basename the tablename to store the data to
fileName the file to read the data from
Definition at line 169 of file DiscoImporter.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection().
Referenced by de.dlr.ivf.scripts.DiscoImporter.main().
findCarIDs()
void de.dlr.ivf.scripts.DiscoImporter.findCarIDs (String basename)
This Method finds the corresponding car-IDs for car1 and car2 in the household table
Parameters
basename the basename of the two tables
Definition at line 296 of file DiscoImporter.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery().
Referenced by de.dlr.ivf.scripts.DiscoImporter.main().
main()
static void de.dlr.ivf.scripts.DiscoImporter.main (String[] args) static
Parameters
args
Definition at line 37 of file DiscoImporter.java.
References de.dlr.ivf.scripts.DiscoImporter.createTables(), de.dlr.ivf.scripts.DiscoImporter.fillCars(), de.dlr.ivf.scripts.DiscoImporter.fillTables(), de.dlr.ivf.scripts.DiscoImporter.findCarIDs(), and name.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/scripts/DiscoImporter.java