TAPAS: de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart Class Reference
de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart Class Reference
Classes
class ModalShapeLegendSource
class ModalSplitRenderer
class ModalSplitToolTipGenerator
class QualityLegendSource
Public Member Functions
ModalSplitChart (ArrayList< ModalSplitData > data, String title)
ModalSplitChart (String reference, String model) throws ClassNotFoundException, IOException
void clearSelection ()
String exportSelected ()
void triggerSelect (int item)
Private Member Functions
void createShapeMap ()
void createToolTips (ArrayList< ModalSplitData > data)
Private Attributes
EnumMap< Mode, Shape > shapeMap
final HashSet< Integer > selected = new HashSet<>()
ArrayList< String > toolTips
ArrayList< String > toolTipsExport
Static Private Attributes
static final long serialVersionUID = 168088681357544692L
Detailed Description
This is a JFreeChart to compare the generated modal split with a reference.
Author
boec_pa
Definition at line 41 of file ModalSplitChart.java.
Constructor & Destructor Documentation
ModalSplitChart() [1/2]
de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.ModalSplitChart (ArrayList< ModalSplitData > data, String title)
Parameters
data the datapoints containing reference and model.
title the title of the chart.
Definition at line 53 of file ModalSplitChart.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.createShapeMap(), de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.createToolTips(), de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.getString(), and de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.init().
ModalSplitChart() [2/2]
de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.ModalSplitChart (String reference, String model) throws ClassNotFoundException, IOException
Builds a chart from the database.
Parameters
reference the key to reference (like mid2008) in reference
model the key of the model run in the calibration_results table.
Exceptions
ClassNotFoundException
IOException when database connections go wrong.
Definition at line 93 of file ModalSplitChart.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDBFetcher.getModalSplitData().
Member Function Documentation
clearSelection()
void de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.clearSelection ()
Deselects all items.
Definition at line 101 of file ModalSplitChart.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.selected.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartFrame.actionPerformed().
createShapeMap()
void de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.createShapeMap () private
Definition at line 105 of file ModalSplitChart.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.shapeMap.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.ModalSplitChart().
createToolTips()
void de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.createToolTips (ArrayList< ModalSplitData > data) private
Definition at line 114 of file ModalSplitChart.java.
References de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.DistanceCategoryDefault, de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategoryDefault.getDescription(), de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Mode.getDescription(), de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.getString(), de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.toolTips, and de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.toolTipsExport.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.ModalSplitChart().
exportSelected()
String de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.exportSelected ()
Exports the tooltips of all selected items
Definition at line 183 of file ModalSplitChart.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.selected, and de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.toolTipsExport.
triggerSelect()
void de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.triggerSelect (int item)
Adds or removes the given item to/from the selection.
Parameters
item
Definition at line 198 of file ModalSplitChart.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.selected.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartFrame.ModalSplitMouseListener.chartMouseClicked().
Member Data Documentation
selected
final HashSet<Integer> de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.selected = new HashSet<>() private
Definition at line 45 of file ModalSplitChart.java.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.clearSelection(), de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.exportSelected(), de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.ModalSplitRenderer.getItemOutlinePaint(), and de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.triggerSelect().
serialVersionUID
final long de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.serialVersionUID = 168088681357544692L static private
Definition at line 43 of file ModalSplitChart.java.
shapeMap
EnumMap<Mode, Shape> de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.shapeMap private
Definition at line 44 of file ModalSplitChart.java.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.createShapeMap(), de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.ModalSplitRenderer.getItemShape(), and de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.ModalShapeLegendSource.ModalShapeLegendSource().
toolTips
ArrayList<String> de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.toolTips private
Definition at line 46 of file ModalSplitChart.java.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.createToolTips(), and de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.ModalSplitToolTipGenerator.generateToolTip().
toolTipsExport
ArrayList<String> de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.toolTipsExport private
Definition at line 47 of file ModalSplitChart.java.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.createToolTips(), and de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.exportSelected().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/runtime/client/Graphics/ModalSplitChart/ModalSplitChart.java