TAPAS: de.dlr.ivf.tapas.util.TPS_Geometrics Class Reference
de.dlr.ivf.tapas.util.TPS_Geometrics Class Reference
Static Public Member Functions
static void calcTop3 (double[][] matrix)
static void calcTopX (double[][] matrix, int numOfElem, double weight)
static void convertToCartesian (TPS_Coordinate g, double[] p)
static double getDistance (Locatable l0, Locatable l1, double min_dist)
static double getDistance (Locatable startLoc, Locatable endLoc, TPS_Mode mode, SimulationType simType)
static double getDistance (TPS_Coordinate c0, TPS_Coordinate c1, double min_dist)
static double getDistance (double lat1, double lon1, double lat2, double lon2)
static double getDistance (TPS_Coordinate g0, TPS_Coordinate g1, TPS_Coordinate point, double min_distance)
static boolean isBetweenLine (TPS_Coordinate g0, double distToStart, TPS_Coordinate g1, double distToEnd, TPS_Coordinate point, double min_dist)
static boolean isSameLocation (TPS_Coordinate g0, TPS_Coordinate g1)
static boolean isWithin (TPS_Coordinate c0, TPS_Coordinate c1, double minDistance, double maxDistance)
Static Private Member Functions
static void writeKMLDebug (TPS_Coordinate c0, TPS_Coordinate c1, TPS_Coordinate c2, TPS_Coordinate c3)
Static Private Attributes
static final double earthRadius = 6371000.785
Detailed Description
Class for geometric operations. EG distance on earth surface etc.
Author
hein_mh
Definition at line 31 of file TPS_Geometrics.java.
Member Function Documentation
calcTop3()
static void de.dlr.ivf.tapas.util.TPS_Geometrics.calcTop3 (double matrix[][]) static
Function to calculate the TOP3-Strategy for diagonal elements. Elements=3 Damping factor: 0.8
Parameters
matrix
Definition at line 43 of file TPS_Geometrics.java.
References de.dlr.ivf.tapas.util.TPS_Geometrics.calcTopX().
Referenced by de.dlr.ivf.scripts.OTP2SQLMatrix.calcTop3(), de.dlr.ivf.scripts.SrVCalculator.initAreasWithDefaultTimes(), de.dlr.ivf.tapas.tools.tazcalculator.TAZSRVAggregator.main(), de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.manipulateTop3(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.readData(), de.dlr.ivf.tapas.runtime.sumoDaemon.SumoMatrixImporter.readSumoValues(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.start().
calcTopX()
static void de.dlr.ivf.tapas.util.TPS_Geometrics.calcTopX (double matrix[][], int numOfElem, double weight) static
Function to calculate a generic TOPx-Strategy for diagonal elements with a given weight.
Parameters
matrix the Input matrix. Must be square and larger than numOfElem+1
numOfElem Number of elems for average traveltime calculation
weight the damping weight for the average.
Definition at line 54 of file TPS_Geometrics.java.
Referenced by de.dlr.ivf.tapas.util.TPS_Geometrics.calcTop3().
convertToCartesian()
static void de.dlr.ivf.tapas.util.TPS_Geometrics.convertToCartesian (TPS_Coordinate g, double[] p) static
Definition at line 73 of file TPS_Geometrics.java.
References de.dlr.ivf.tapas.util.TPS_Geometrics.earthRadius, and de.dlr.ivf.tapas.loc.TPS_Coordinate.getValue().
Referenced by de.dlr.ivf.tapas.util.TPS_Geometrics.getDistance(), and de.dlr.ivf.tapas.util.TPS_Geometrics.isBetweenLine().
getDistance() [1/5]
static double de.dlr.ivf.tapas.util.TPS_Geometrics.getDistance (double lat1, double lon1, double lat2, double lon2) static
This method calculates the distance in meters between both coordinates using a sphere.
Returns
distance of the two coordinates depending an a sphere
Definition at line 162 of file TPS_Geometrics.java.
References de.dlr.ivf.tapas.util.TPS_FastMath.acos(), and de.dlr.ivf.tapas.util.TPS_Geometrics.earthRadius.
getDistance() [2/5]
static double de.dlr.ivf.tapas.util.TPS_Geometrics.getDistance (Locatable l0, Locatable l1, double min_dist) static
Definition at line 91 of file TPS_Geometrics.java.
References de.dlr.ivf.tapas.loc.Locatable.getCoordinate(), and de.dlr.ivf.tapas.util.TPS_Geometrics.getDistance().
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.calcDistance(), de.dlr.ivf.tapas.tools.TPS_PTStopWeightCalculator.calcWeights(), de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.getCorrectedMatrixVal(), de.dlr.ivf.tapas.util.TPS_Geometrics.getDistance(), de.dlr.ivf.tapas.mode.TPS_IndividualTransportMode.getDistance(), de.dlr.ivf.tapas.mode.TPS_MassTransportMode.getDistance(), de.dlr.ivf.tapas.mode.TPS_NonMotorisedMode.getDistance(), de.dlr.ivf.scripts.SrVCalculator.TAZ.getDistance(), de.dlr.ivf.tapas.mode.TPS_IndividualTransportMode.getTravelTime(), de.dlr.ivf.tapas.mode.TPS_MassTransportMode.getTravelTime(), de.dlr.ivf.tapas.mode.TPS_NonMotorisedMode.getTravelTime(), de.dlr.ivf.tapas.util.TPS_Geometrics.isBetweenLine(), de.dlr.ivf.tapas.util.TPS_Geometrics.isWithin(), de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.loadTAZ(), de.dlr.ivf.tapas.tools.TPS_SpeedAndDistanceValidator.loadTAZInfos(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readMatrices(), de.dlr.ivf.tapas.tools.TPS_ExternalTrafficDistribution.saveToDB(), and de.dlr.ivf.tapas.tools.TPS_ECommerceEstimator.updateEComTripsInDB().
getDistance() [3/5]
static double de.dlr.ivf.tapas.util.TPS_Geometrics.getDistance (Locatable startLoc, Locatable endLoc, TPS_Mode mode, SimulationType simType) static
Parameters
startLoc Starting location
endLoc Destination location
Returns
distance in meters
Definition at line 103 of file TPS_Geometrics.java.
References de.dlr.ivf.tapas.util.parameters.ParamMatrix.DISTANCES_BL, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_INTRA_INFOS_MATRIX, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_USE_BLOCK_LEVEL, de.dlr.ivf.tapas.loc.Locatable.getCoordinate(), de.dlr.ivf.tapas.util.TPS_Geometrics.getDistance(), de.dlr.ivf.tapas.mode.TPS_Mode.getDistance(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getDoubleValue(), de.dlr.ivf.tapas.mode.TPS_Mode.getParameters(), de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.getTAZId(), de.dlr.ivf.tapas.loc.Locatable.getTrafficAnalysisZone(), de.dlr.ivf.tapas.util.parameters.ParamMatrixClass.getValue(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isFalse(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isTrue(), de.dlr.ivf.tapas.util.parameters.ParamValue.MIN_DIST, and de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.paramMatrixClass.
getDistance() [4/5]
static double de.dlr.ivf.tapas.util.TPS_Geometrics.getDistance (TPS_Coordinate c0, TPS_Coordinate c1, double min_dist) static
This method calculates the distance in meters between both coordinates using a sphere.
Parameters
c0
c1
min_dist
Returns
distance of the two coordinates depending an a sphere
Definition at line 146 of file TPS_Geometrics.java.
References de.dlr.ivf.tapas.loc.TPS_Coordinate.getEuclidianDistance().
getDistance() [5/5]
static double de.dlr.ivf.tapas.util.TPS_Geometrics.getDistance (TPS_Coordinate g0, TPS_Coordinate g1, TPS_Coordinate point, double min_distance) static
This method calculates the distance in meters between a line form g0 to g1 and a point p
Parameters
g0 start point of the line
g1 end point of the line
point point to measure the distance
min_distance minimum distance
Returns
minimum distance : zero if point is part of the line g0-g1, the length of the line through the point perpendicular to g0-g1 otherwise.
Definition at line 185 of file TPS_Geometrics.java.
References de.dlr.ivf.tapas.util.TPS_Geometrics.convertToCartesian(), de.dlr.ivf.tapas.util.TPS_Geometrics.getDistance(), and de.dlr.ivf.tapas.util.TPS_Geometrics.isSameLocation().
isBetweenLine()
static boolean de.dlr.ivf.tapas.util.TPS_Geometrics.isBetweenLine (TPS_Coordinate g0, double distToStart, TPS_Coordinate g1, double distToEnd, TPS_Coordinate point, double min_dist) static
This method calculates the distance in meters between a line form g0 to g1 and a point point
Parameters
g0 start point of the line
distToStart radius around the start
g1 end point of the line
distToEnd radius around the end
point point, which distance should be measured
min_dist minimum distance
Returns
distance in meters
Definition at line 246 of file TPS_Geometrics.java.
References de.dlr.ivf.tapas.util.TPS_Geometrics.convertToCartesian(), de.dlr.ivf.tapas.util.TPS_Geometrics.getDistance(), de.dlr.ivf.tapas.util.TPS_Geometrics.isSameLocation(), and de.dlr.ivf.tapas.util.TPS_Geometrics.isWithin().
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.getTrafficAnalysisZonesAround().
isSameLocation()
static boolean de.dlr.ivf.tapas.util.TPS_Geometrics.isSameLocation (TPS_Coordinate g0, TPS_Coordinate g1) static
Method to check if two given locations are neglegtable close to eachother.
Parameters
g0 the 1st location
g1 the 2nd location
Returns
true if the location are VERY close to eachother
Definition at line 311 of file TPS_Geometrics.java.
References de.dlr.ivf.tapas.loc.TPS_Coordinate.getValue().
Referenced by de.dlr.ivf.tapas.util.TPS_Geometrics.getDistance(), and de.dlr.ivf.tapas.util.TPS_Geometrics.isBetweenLine().
isWithin()
static boolean de.dlr.ivf.tapas.util.TPS_Geometrics.isWithin (TPS_Coordinate c0, TPS_Coordinate c1, double minDistance, double maxDistance) static
This method calculates if the distance between both coordinates is lower than the given maximum.
Parameters
c0
c1
minDistance the minimum distance
maxDistance the maximum distance
Returns
true if the distance is lower or equal maxDistance
Definition at line 328 of file TPS_Geometrics.java.
References de.dlr.ivf.tapas.util.TPS_Geometrics.getDistance().
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.getTrafficAnalysisZonesAround(), and de.dlr.ivf.tapas.util.TPS_Geometrics.isBetweenLine().
writeKMLDebug()
static void de.dlr.ivf.tapas.util.TPS_Geometrics.writeKMLDebug (TPS_Coordinate c0, TPS_Coordinate c1, TPS_Coordinate c2, TPS_Coordinate c3) static private
Definition at line 335 of file TPS_Geometrics.java.
Member Data Documentation
earthRadius
final double de.dlr.ivf.tapas.util.TPS_Geometrics.earthRadius = 6371000.785 static private
Mittlerer Erdradius in Metern
Definition at line 36 of file TPS_Geometrics.java.
Referenced by de.dlr.ivf.tapas.util.TPS_Geometrics.convertToCartesian(), and de.dlr.ivf.tapas.util.TPS_Geometrics.getDistance().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/util/TPS_Geometrics.java