TAPAS: de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartFrame Class Reference
de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartFrame Class Reference
Classes
class ModalSplitMouseListener
Public Member Functions
ModalSplitChartFrame (String reference, String model, String title) throws ClassNotFoundException, IOException
void actionPerformed (ActionEvent e)
Static Public Member Functions
static void main (String[] args) throws ClassNotFoundException, IOException
Private Member Functions
ModalSplitChart getChart ()
Static Private Attributes
static final long serialVersionUID = 685327265946837604L
Detailed Description
This frame encapsulates a ModalSplitChart and adds specific behavior like popup menus and mouse events.
Author
boec_pa
Definition at line 31 of file ModalSplitChartFrame.java.
Constructor & Destructor Documentation
ModalSplitChartFrame()
de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartFrame.ModalSplitChartFrame (String reference, String model, String title) throws ClassNotFoundException, IOException
Definition at line 38 of file ModalSplitChartFrame.java.
References de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.getString(), and de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.init().
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartFrame.main().
Member Function Documentation
actionPerformed()
void de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartFrame.actionPerformed (ActionEvent e)
Definition at line 71 of file ModalSplitChartFrame.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.clearSelection(), and de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartFrame.getChart().
getChart()
ModalSplitChart de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartFrame.getChart () private
Convenience shortcut
Definition at line 89 of file ModalSplitChartFrame.java.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartFrame.actionPerformed(), and de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartFrame.ModalSplitMouseListener.chartMouseClicked().
main()
static void de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartFrame.main (String[] args) throws ClassNotFoundException, IOException static
Testing only
Definition at line 61 of file ModalSplitChartFrame.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartFrame.ModalSplitChartFrame().
Member Data Documentation
serialVersionUID
final long de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartFrame.serialVersionUID = 685327265946837604L static private
Definition at line 33 of file ModalSplitChartFrame.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/runtime/client/Graphics/ModalSplitChart/ModalSplitChartFrame.java