TAPAS: de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitData Class Reference
de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitData Class Reference
Public Member Functions
ModalSplitData (CategoryCombination cc, Quality q, double model, double reference)
CategoryCombination getCategories ()
String getLabel ()
Mode getMode ()
double getModel ()
Quality getQuality ()
double getReference ()
String toString ()
Private Attributes
final CategoryCombination categoryCombination
final Quality quality
final double model
final double reference
Detailed Description
Definition at line 16 of file ModalSplitData.java.
Constructor & Destructor Documentation
ModalSplitData()
de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitData.ModalSplitData (CategoryCombination cc, Quality q, double model, double reference)
Definition at line 23 of file ModalSplitData.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitData.categoryCombination, de.dlr.ivf.tapas.analyzer.tum.constants.CategoryCombination.contains(), de.dlr.ivf.tapas.analyzer.tum.constants.CategoryCombination.getCategories(), de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.Mode, de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitData.model, de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitData.quality, and de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitData.reference.
Member Function Documentation
getCategories()
CategoryCombination de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitData.getCategories ()
Definition at line 36 of file ModalSplitData.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitData.categoryCombination.
getLabel()
String de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitData.getLabel ()
Definition at line 40 of file ModalSplitData.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitData.categoryCombination, and de.dlr.ivf.tapas.analyzer.tum.constants.CategoryCombination.toString().
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitData.toString().
getMode()
Mode de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitData.getMode ()
Returns
the Mode of this data point.
Definition at line 48 of file ModalSplitData.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitData.categoryCombination, and de.dlr.ivf.tapas.analyzer.tum.constants.CategoryCombination.getCategories().
getModel()
double de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitData.getModel ()
Definition at line 55 of file ModalSplitData.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitData.model.
getQuality()
Quality de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitData.getQuality ()
Definition at line 59 of file ModalSplitData.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitData.quality.
getReference()
double de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitData.getReference ()
Definition at line 63 of file ModalSplitData.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitData.reference.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDataset.ModalSplitChartDataset().
toString()
String de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitData.toString ()
Definition at line 68 of file ModalSplitData.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitData.getLabel(), de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitData.model, and de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitData.reference.
Member Data Documentation
categoryCombination
final CategoryCombination de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitData.categoryCombination private
Definition at line 18 of file ModalSplitData.java.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitData.getCategories(), de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitData.getLabel(), de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitData.getMode(), and de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitData.ModalSplitData().
model
final double de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitData.model private
Definition at line 20 of file ModalSplitData.java.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitData.getModel(), de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitData.ModalSplitData(), and de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitData.toString().
quality
final Quality de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitData.quality private
Definition at line 19 of file ModalSplitData.java.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitData.getQuality(), and de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitData.ModalSplitData().
reference
final double de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitData.reference private
Definition at line 21 of file ModalSplitData.java.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitData.getReference(), de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitData.ModalSplitData(), and de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitData.toString().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/runtime/client/Graphics/ModalSplitChart/ModalSplitData.java