TAPAS: de.dlr.ivf.tapas.analyzer.core.ModuleData Class Reference
de.dlr.ivf.tapas.analyzer.core.ModuleData Class Reference abstract
Public Member Functions
ModuleData (String id, String version)
boolean equals (Object obj)
String getId ()
String getVersion ()
boolean isLast ()
void setLast (boolean last)
Static Public Attributes
static final ModuleData NO_RESULT
Private Attributes
final String id
final String version
boolean last = true
Detailed Description
Container für die Daten, die zwischen den Modulen hin und her geschickt werden.
Author
Martin
Version
$Revision$
Definition at line 16 of file ModuleData.java.
Constructor & Destructor Documentation
ModuleData()
de.dlr.ivf.tapas.analyzer.core.ModuleData.ModuleData (String id, String version)
Erstellt eine Instanz von ModuleData mit einer id und einer version um die Kompatibilität der Daten zu garantieren.
Parameters
id - der Moduldaten
version - der Moduldaten
Definition at line 32 of file ModuleData.java.
References de.dlr.ivf.tapas.analyzer.core.ModuleData.id, and de.dlr.ivf.tapas.analyzer.core.ModuleData.version.
Referenced by de.dlr.ivf.tapas.analyzer.core.ModuleData.equals().
Member Function Documentation
equals()
boolean de.dlr.ivf.tapas.analyzer.core.ModuleData.equals (Object obj)
Definition at line 38 of file ModuleData.java.
References de.dlr.ivf.tapas.analyzer.core.ModuleData.getId(), de.dlr.ivf.tapas.analyzer.core.ModuleData.getVersion(), and de.dlr.ivf.tapas.analyzer.core.ModuleData.ModuleData().
getId()
String de.dlr.ivf.tapas.analyzer.core.ModuleData.getId ()
Returns
ID der Moduldaten
Definition at line 49 of file ModuleData.java.
References de.dlr.ivf.tapas.analyzer.core.ModuleData.id.
Referenced by de.dlr.ivf.tapas.analyzer.core.ModuleData.equals().
getVersion()
String de.dlr.ivf.tapas.analyzer.core.ModuleData.getVersion ()
Returns
Version der Moduldaten
Definition at line 56 of file ModuleData.java.
References de.dlr.ivf.tapas.analyzer.core.ModuleData.version.
Referenced by de.dlr.ivf.tapas.analyzer.core.ModuleData.equals().
isLast()
boolean de.dlr.ivf.tapas.analyzer.core.ModuleData.isLast ()
Definition at line 60 of file ModuleData.java.
References de.dlr.ivf.tapas.analyzer.core.ModuleData.last.
setLast()
void de.dlr.ivf.tapas.analyzer.core.ModuleData.setLast (boolean last)
Definition at line 64 of file ModuleData.java.
References de.dlr.ivf.tapas.analyzer.core.ModuleData.last.
Member Data Documentation
id
final String de.dlr.ivf.tapas.analyzer.core.ModuleData.id private
Definition at line 21 of file ModuleData.java.
Referenced by de.dlr.ivf.tapas.analyzer.core.ModuleData.getId(), and de.dlr.ivf.tapas.analyzer.core.ModuleData.ModuleData().
last
boolean de.dlr.ivf.tapas.analyzer.core.ModuleData.last = true private
Definition at line 23 of file ModuleData.java.
Referenced by de.dlr.ivf.tapas.analyzer.core.ModuleData.isLast(), and de.dlr.ivf.tapas.analyzer.core.ModuleData.setLast().
NO_RESULT
final ModuleData de.dlr.ivf.tapas.analyzer.core.ModuleData.NO_RESULT static
Initial value:
= new ModuleData("no.result", "0.0.0") {
    }
Definition at line 18 of file ModuleData.java.
version
final String de.dlr.ivf.tapas.analyzer.core.ModuleData.version private
Definition at line 22 of file ModuleData.java.
Referenced by de.dlr.ivf.tapas.analyzer.core.ModuleData.getVersion(), and de.dlr.ivf.tapas.analyzer.core.ModuleData.ModuleData().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/core/ModuleData.java