TAPAS: de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.KeyPairListModel Class Reference
de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.KeyPairListModel Class Reference
Public Member Functions
KeyPairListModel ()
synchronized void addElement (String dbKey, String csvKey)
synchronized boolean contains (String dbKey, String csvKey)
synchronized String getElementAt (int index)
synchronized HashMap< String, String > getMapping ()
synchronized int getSize ()
synchronized void remove (int[] indices)
synchronized String remove (int index)
Private Attributes
final ArrayList< String > dbKeys = new ArrayList<>()
final ArrayList< String > csvKeys = new ArrayList<>()
Static Private Attributes
static final long serialVersionUID = 4039203363152111876L
static final String SEPERATOR = " -- "
Detailed Description
This class handles the key pairs shown in the bottom JList. The pairs are hold as two independent Lists and only put together on request. All access methods are synchronized to ensure thread safety.
Author
boec_pa
Definition at line 202 of file HeaderMatcher.java.
Constructor & Destructor Documentation
KeyPairListModel()
de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.KeyPairListModel.KeyPairListModel ()
Definition at line 213 of file HeaderMatcher.java.
Member Function Documentation
addElement()
synchronized void de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.KeyPairListModel.addElement (String dbKey, String csvKey)
Definition at line 233 of file HeaderMatcher.java.
References de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.KeyPairListModel.csvKeys, and de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.KeyPairListModel.dbKeys.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.initGUI().
contains()
synchronized boolean de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.KeyPairListModel.contains (String dbKey, String csvKey)
Returns
true if at least one of the given keys is already in the pairing.
Definition at line 243 of file HeaderMatcher.java.
References de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.KeyPairListModel.csvKeys, and de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.KeyPairListModel.dbKeys.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.initGUI().
getElementAt()
synchronized String de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.KeyPairListModel.getElementAt (int index)
Definition at line 248 of file HeaderMatcher.java.
References de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.KeyPairListModel.csvKeys, de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.KeyPairListModel.dbKeys, and de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.KeyPairListModel.SEPERATOR.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.KeyPairListModel.remove().
getMapping()
synchronized HashMap<String, String> de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.KeyPairListModel.getMapping ()
Definition at line 252 of file HeaderMatcher.java.
References de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.KeyPairListModel.csvKeys, and de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.KeyPairListModel.dbKeys.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.getMapping().
getSize()
synchronized int de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.KeyPairListModel.getSize ()
Definition at line 261 of file HeaderMatcher.java.
References de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.KeyPairListModel.dbKeys.
remove() [1/2]
synchronized String de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.KeyPairListModel.remove (int index)
Definition at line 272 of file HeaderMatcher.java.
References de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.KeyPairListModel.csvKeys, de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.KeyPairListModel.dbKeys, and de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.KeyPairListModel.getElementAt().
remove() [2/2]
synchronized void de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.KeyPairListModel.remove (int[] indices)
Definition at line 265 of file HeaderMatcher.java.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.initGUI().
Member Data Documentation
csvKeys
final ArrayList<String> de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.KeyPairListModel.csvKeys = new ArrayList<>() private
Definition at line 211 of file HeaderMatcher.java.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.KeyPairListModel.addElement(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.KeyPairListModel.contains(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.KeyPairListModel.getElementAt(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.KeyPairListModel.getMapping(), and de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.KeyPairListModel.remove().
dbKeys
final ArrayList<String> de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.KeyPairListModel.dbKeys = new ArrayList<>() private
Definition at line 210 of file HeaderMatcher.java.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.KeyPairListModel.addElement(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.KeyPairListModel.contains(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.KeyPairListModel.getElementAt(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.KeyPairListModel.getMapping(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.KeyPairListModel.getSize(), and de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.KeyPairListModel.remove().
SEPERATOR
final String de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.KeyPairListModel.SEPERATOR = " -- " static private
Definition at line 208 of file HeaderMatcher.java.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.KeyPairListModel.getElementAt().
serialVersionUID
final long de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.KeyPairListModel.serialVersionUID = 4039203363152111876L static private
Definition at line 206 of file HeaderMatcher.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/persitence/db/dbImport/HeaderMatcher.java