TAPAS: de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBCorrector Class Reference
de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBCorrector Class Reference
Classes
class Person
Static Public Member Functions
static void main (String[] args)
Private Member Functions
void closeConnection ()
boolean correctIDinTable (Person p, String table, int newID)
void correctIDs (String table)
void openConnection (String ip, int port, String DBName, String user, String passwd)
Private Attributes
Connection connection = null
Statement statement = null
Detailed Description
Class to correct double person ids, which where found. Not needed anymore, unless we import faulty data again
Author
hein_mh
Definition at line 22 of file DBCorrector.java.
Member Function Documentation
closeConnection()
void de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBCorrector.closeConnection () private
Definition at line 42 of file DBCorrector.java.
References de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBCorrector.connection, and de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBCorrector.statement.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBCorrector.main().
correctIDinTable()
boolean de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBCorrector.correctIDinTable (Person p, String table, int newID) private
Definition at line 57 of file DBCorrector.java.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBCorrector.correctIDs().
correctIDs()
void de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBCorrector.correctIDs (String table) private
Definition at line 72 of file DBCorrector.java.
References de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBCorrector.correctIDinTable().
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBCorrector.main().
main()
static void de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBCorrector.main (String[] args) static
main method
Parameters
args no args
Definition at line 32 of file DBCorrector.java.
References de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBCorrector.closeConnection(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBCorrector.correctIDs(), and de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBCorrector.openConnection().
openConnection()
void de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBCorrector.openConnection (String ip, int port, String DBName, String user, String passwd) private
method to open the db connection and to create the sqlStatement
Definition at line 141 of file DBCorrector.java.
References de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBCorrector.connection, and de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBCorrector.statement.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBCorrector.main().
Member Data Documentation
connection
Connection de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBCorrector.connection = null private
Definition at line 24 of file DBCorrector.java.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBCorrector.closeConnection(), and de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBCorrector.openConnection().
statement
Statement de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBCorrector.statement = null private
Definition at line 25 of file DBCorrector.java.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBCorrector.closeConnection(), and de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBCorrector.openConnection().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/persitence/db/dbImport/DBCorrector.java