TAPAS: de.dlr.ivf.tapas.runtime.util.IPInfo Class Reference
de.dlr.ivf.tapas.runtime.util.IPInfo Class Reference
Static Public Member Functions
static InetAddress getEthernetInetAddress () throws IOException
static String getHostname () throws IOException
static InetAddress getInetAddress (String namePrefix) throws IOException
static InetAddress getLocalhost () throws IOException
Detailed Description
This class provides methods to determine the IP addresses of the computer's network adapters
Author
mark_ma
Definition at line 23 of file IPInfo.java.
Member Function Documentation
getEthernetInetAddress()
static InetAddress de.dlr.ivf.tapas.runtime.util.IPInfo.getEthernetInetAddress () throws IOException static
Returns
IP address of ethernet network adapter
Exceptions
IOException thrown if a error occurs
Definition at line 29 of file IPInfo.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationServer.main(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.resetUnfinishedHouseholds(), de.dlr.ivf.tapas.runtime.server.SimulationServer.run(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.TPS_DB_IO().
getHostname()
static String de.dlr.ivf.tapas.runtime.util.IPInfo.getHostname () throws IOException static
retrieves the HOSTNAME where the JVM is currently running using the 'hostname' runtime command
Returns
HOSTNAME
Exceptions
IOException
Definition at line 41 of file IPInfo.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationServer.main(), and de.dlr.ivf.tapas.runtime.server.SimulationDaemon.SimulationDaemon().
getInetAddress()
static InetAddress de.dlr.ivf.tapas.runtime.util.IPInfo.getInetAddress (String namePrefix) throws IOException static
Parameters
namePrefix prefix of the network adapter name e.g. "lo" for localhost
Returns
IP address of the network adapter with the given name prefix
Exceptions
IOException thrown if a error occurs
Definition at line 61 of file IPInfo.java.
Referenced by de.dlr.ivf.tapas.runtime.util.IPInfo.getLocalhost().
getLocalhost()
static InetAddress de.dlr.ivf.tapas.runtime.util.IPInfo.getLocalhost () throws IOException static
Returns
IP address of the localhost
Exceptions
IOException thrown if a error occurs
Definition at line 87 of file IPInfo.java.
References de.dlr.ivf.tapas.runtime.util.IPInfo.getInetAddress().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/runtime/util/IPInfo.java