TAPAS: de.dlr.ivf.tapas.TPS_Main.TPS_State Class Reference
de.dlr.ivf.tapas.TPS_Main.TPS_State Class Reference
Public Member Functions
TPS_State ()
boolean isFinished ()
boolean isRunning ()
void setRunning (boolean running)
void setFinished ()
void waitFor (long timeout)
Private Attributes
boolean finished
boolean running
Detailed Description
This class represents the current state of the simulation.
Author
mark_ma
Definition at line 345 of file TPS_Main.java.
Constructor & Destructor Documentation
TPS_State()
de.dlr.ivf.tapas.TPS_Main.TPS_State.TPS_State ()
Initialises the flags.
Definition at line 359 of file TPS_Main.java.
Member Function Documentation
isFinished()
boolean de.dlr.ivf.tapas.TPS_Main.TPS_State.isFinished ()
Returns
finished flag
Definition at line 367 of file TPS_Main.java.
isRunning()
boolean de.dlr.ivf.tapas.TPS_Main.TPS_State.isRunning ()
Returns
running flag
Definition at line 374 of file TPS_Main.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Worker.call().
setFinished()
void de.dlr.ivf.tapas.TPS_Main.TPS_State.setFinished ()
Sets the finished flag on true and wakes up all waiting threads.
Definition at line 391 of file TPS_Main.java.
Referenced by de.dlr.ivf.tapas.runtime.TPS_Launch.main(), de.dlr.ivf.tapas.TPS_Main.main(), and de.dlr.ivf.tapas.runtime.server.SimulationServer.run().
setRunning()
void de.dlr.ivf.tapas.TPS_Main.TPS_State.setRunning (boolean running)
Parameters
running new running flag value
Definition at line 381 of file TPS_Main.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationServer.RunWhenShuttingDown.run().
waitFor()
void de.dlr.ivf.tapas.TPS_Main.TPS_State.waitFor (long timeout)
Waits for the end of this simulation.
Parameters
timeout timeout in milliseconds to wait. The value 0 indicates an endless waiting.
Definition at line 404 of file TPS_Main.java.
Member Data Documentation
finished
boolean de.dlr.ivf.tapas.TPS_Main.TPS_State.finished private
Flag if the simulation has finished
Definition at line 349 of file TPS_Main.java.
running
boolean de.dlr.ivf.tapas.TPS_Main.TPS_State.running private
Flag if the simulation is running
Definition at line 354 of file TPS_Main.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/TPS_Main.java