TAPAS: de.dlr.ivf.tapas.tools.riesel.UpdateAddressesWorker Class Reference
de.dlr.ivf.tapas.tools.riesel.UpdateAddressesWorker Class Reference
Public Member Functions
UpdateAddressesWorker (BlockingQueue< AddressPojo > queue, TPS_DB_Connector dbCon) throws SQLException
void commitBatch ()
void run ()
Private Member Functions
void addToBatch (AddressPojo address)
Private Attributes
final BlockingQueue< AddressPojo > queue
final int BATCH_MAX_SIZE = 10000
final PreparedStatement updateBatch
final Connection connection
int BATCH_SIZE = 0
Detailed Description
This class updates the number of inhabitants of the given list of addresses. The input of the data is handled by the BlockingQueue given and construction time.
The update is done in batches of size UpdateAddressesWorker#BATCH_MAX_SIZE. The last batch can be emptied by notifying this object via TPS_Main.TPS_State#setFinished().
Definition at line 31 of file UpdateAddressesWorker.java.
Constructor & Destructor Documentation
UpdateAddressesWorker()
de.dlr.ivf.tapas.tools.riesel.UpdateAddressesWorker.UpdateAddressesWorker (BlockingQueue< AddressPojo > queue, TPS_DB_Connector dbCon) throws SQLException
Definition at line 39 of file UpdateAddressesWorker.java.
References de.dlr.ivf.tapas.tools.riesel.UpdateAddressesWorker.connection, de.dlr.ivf.tapas.tools.riesel.UpdateAddressesWorker.queue, and de.dlr.ivf.tapas.tools.riesel.UpdateAddressesWorker.updateBatch.
Member Function Documentation
addToBatch()
void de.dlr.ivf.tapas.tools.riesel.UpdateAddressesWorker.addToBatch (AddressPojo address) private
Definition at line 48 of file UpdateAddressesWorker.java.
References de.dlr.ivf.tapas.tools.riesel.UpdateAddressesWorker.BATCH_MAX_SIZE, de.dlr.ivf.tapas.tools.riesel.UpdateAddressesWorker.BATCH_SIZE, de.dlr.ivf.tapas.tools.riesel.UpdateAddressesWorker.commitBatch(), de.dlr.ivf.tapas.tools.riesel.AddressPojo.getInhabitants(), de.dlr.ivf.tapas.tools.riesel.AddressPojo.getKey(), and de.dlr.ivf.tapas.tools.riesel.UpdateAddressesWorker.updateBatch.
Referenced by de.dlr.ivf.tapas.tools.riesel.UpdateAddressesWorker.run().
commitBatch()
void de.dlr.ivf.tapas.tools.riesel.UpdateAddressesWorker.commitBatch ()
Definition at line 66 of file UpdateAddressesWorker.java.
References de.dlr.ivf.tapas.tools.riesel.UpdateAddressesWorker.connection, de.dlr.ivf.tapas.tools.riesel.UpdateAddressesWorker.queue, and de.dlr.ivf.tapas.tools.riesel.UpdateAddressesWorker.updateBatch.
Referenced by de.dlr.ivf.tapas.tools.riesel.UpdateAddressesWorker.addToBatch(), and de.dlr.ivf.tapas.tools.riesel.UpdateAddressesWorker.run().
run()
void de.dlr.ivf.tapas.tools.riesel.UpdateAddressesWorker.run ()
Definition at line 84 of file UpdateAddressesWorker.java.
References de.dlr.ivf.tapas.tools.riesel.UpdateAddressesWorker.addToBatch(), de.dlr.ivf.tapas.tools.riesel.UpdateAddressesWorker.commitBatch(), de.dlr.ivf.tapas.tools.riesel.AddressPojo.POISON_ELEMENT, and de.dlr.ivf.tapas.tools.riesel.UpdateAddressesWorker.queue.
Member Data Documentation
BATCH_MAX_SIZE
final int de.dlr.ivf.tapas.tools.riesel.UpdateAddressesWorker.BATCH_MAX_SIZE = 10000 private
Definition at line 34 of file UpdateAddressesWorker.java.
Referenced by de.dlr.ivf.tapas.tools.riesel.UpdateAddressesWorker.addToBatch().
BATCH_SIZE
int de.dlr.ivf.tapas.tools.riesel.UpdateAddressesWorker.BATCH_SIZE = 0 private
Definition at line 37 of file UpdateAddressesWorker.java.
Referenced by de.dlr.ivf.tapas.tools.riesel.UpdateAddressesWorker.addToBatch().
connection
final Connection de.dlr.ivf.tapas.tools.riesel.UpdateAddressesWorker.connection private
Definition at line 36 of file UpdateAddressesWorker.java.
Referenced by de.dlr.ivf.tapas.tools.riesel.UpdateAddressesWorker.commitBatch(), and de.dlr.ivf.tapas.tools.riesel.UpdateAddressesWorker.UpdateAddressesWorker().
queue
final BlockingQueue<AddressPojo> de.dlr.ivf.tapas.tools.riesel.UpdateAddressesWorker.queue private
Definition at line 33 of file UpdateAddressesWorker.java.
Referenced by de.dlr.ivf.tapas.tools.riesel.UpdateAddressesWorker.commitBatch(), de.dlr.ivf.tapas.tools.riesel.UpdateAddressesWorker.run(), and de.dlr.ivf.tapas.tools.riesel.UpdateAddressesWorker.UpdateAddressesWorker().
updateBatch
final PreparedStatement de.dlr.ivf.tapas.tools.riesel.UpdateAddressesWorker.updateBatch private
Definition at line 35 of file UpdateAddressesWorker.java.
Referenced by de.dlr.ivf.tapas.tools.riesel.UpdateAddressesWorker.addToBatch(), de.dlr.ivf.tapas.tools.riesel.UpdateAddressesWorker.commitBatch(), and de.dlr.ivf.tapas.tools.riesel.UpdateAddressesWorker.UpdateAddressesWorker().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/riesel/UpdateAddressesWorker.java