TAPAS: de.dlr.ivf.tapas.runtime.server.SimulationData Class Reference
de.dlr.ivf.tapas.runtime.server.SimulationData Class Reference
Classes
class ProgressCalculator
enum TPS_SimulationState
Public Member Functions
SimulationData (ResultSet rs) throws SQLException
SimulationData (String sim_key, String fileName)
String getAbsoluteFileName (File path)
String getDescription ()
String getElapsedTime (Timestamp current)
String getEstimatedTime (Timestamp current)
String getKey ()
long getProgress ()
String getRelativeFileName ()
TPS_SimulationState getState ()
String getTimestampFinished ()
String getTimestampStarted ()
long getTotal ()
boolean higherState (TPS_SimulationState state)
boolean isFinished ()
boolean isReady ()
boolean isStarted ()
boolean minimumState (TPS_SimulationState state)
String toString ()
void update (ResultSet rs) throws SQLException
Private Member Functions
SimulationData (String sim_key, String fileName, String description, long sim_progress, long sim_total, boolean sim_ready, boolean sim_started, boolean sim_finished)
String format (long duration)
Private Attributes
final String fileName
final String description
boolean sim_finished
final String sim_key
long sim_progress
boolean sim_ready
boolean sim_started
long sim_total
Timestamp timestamp_finished
Timestamp timestamp_started
final ProgressCalculator progressCalc
Static Private Attributes
static final DecimalFormat DF = new DecimalFormat("00")
static final SimpleDateFormat SDF = new SimpleDateFormat("dd.MM.yyyy kk:mm:ss")
Detailed Description
In instances of this class all simulation data can be stored. These are the same as in the database. There exist an unique identifier, the run properties file, three falgs to determine the simulation state, two timestamps for start and end of the simulation and two values for the completed and total amount of households to simulate.
Behaviour of flags and state:
The states have a logical order: INSERTED -> READY -> STARTED -> FINISHED. Only when a simulation is interrupted it gets the STOPPED state which is equal to the INSERTED state. With this logical order you can detect whether a simulation is at least e.g started or ready. The state is detected by the flags. They are not reset when the state rises, i.e. when the state is READY the ready flag is true. Then the next state is STARTED and the started and the ready flags are true. This behaviour leads to the following table:
State Flags ready / started / finished progress
INSERTED false / false / false 0
STOPPED false / false / false 0 < progress < total
READY true / false / false 0
STARTED true / true / false 0 < progress < total
FINISHED true / true / true total
Author
mark_ma
Definition at line 62 of file SimulationData.java.
Constructor & Destructor Documentation
SimulationData() [1/3]
de.dlr.ivf.tapas.runtime.server.SimulationData.SimulationData (ResultSet rs) throws SQLException
This constructor should be used when the simulation is build because of a database query. All members are set from the ResultSet of a database select statement.
Parameters
rs ResultSet of a database select statement
Exceptions
SQLException This exception is thrown if anything with the ResultSet is wrong, e.g. closed or too few values
Definition at line 125 of file SimulationData.java.
References de.dlr.ivf.tapas.runtime.server.SimulationData.update().
SimulationData() [2/3]
de.dlr.ivf.tapas.runtime.server.SimulationData.SimulationData (String sim_key, String fileName)
This constructor is used when a simulation is build from a remote application. All values are initialised with default values. After the simulation is inserted in the database you have to update the local simulation.
Parameters
sim_key The key value for this simulation
fileName The filename of the config file
Definition at line 139 of file SimulationData.java.
References de.dlr.ivf.tapas.runtime.server.SimulationData.fileName, and de.dlr.ivf.tapas.runtime.server.SimulationData.sim_key.
SimulationData() [3/3]
de.dlr.ivf.tapas.runtime.server.SimulationData.SimulationData (String sim_key, String fileName, String description, long sim_progress, long sim_total, boolean sim_ready, boolean sim_started, boolean sim_finished) private
Internal constructor to set all member values.
Parameters
sim_key unique identifier
fileName run properties file
sim_progress amount of simulated households
sim_total total amount of households
sim_ready ready flag
sim_started started flag
sim_finished finished flag
Definition at line 154 of file SimulationData.java.
References de.dlr.ivf.tapas.runtime.server.SimulationData.description, de.dlr.ivf.tapas.runtime.server.SimulationData.fileName, de.dlr.ivf.tapas.runtime.server.SimulationData.progressCalc, de.dlr.ivf.tapas.runtime.server.SimulationData.sim_finished, de.dlr.ivf.tapas.runtime.server.SimulationData.sim_key, de.dlr.ivf.tapas.runtime.server.SimulationData.sim_progress, de.dlr.ivf.tapas.runtime.server.SimulationData.sim_ready, de.dlr.ivf.tapas.runtime.server.SimulationData.sim_started, and de.dlr.ivf.tapas.runtime.server.SimulationData.sim_total.
Member Function Documentation
format()
String de.dlr.ivf.tapas.runtime.server.SimulationData.format (long duration) private
This method formats the given duration in milliseconds into the format *hh:mm:ss.
Parameters
duration duration in milliseconds
Returns
formatted string
Definition at line 172 of file SimulationData.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationData.getElapsedTime(), and de.dlr.ivf.tapas.runtime.server.SimulationData.getEstimatedTime().
getAbsoluteFileName()
String de.dlr.ivf.tapas.runtime.server.SimulationData.getAbsoluteFileName (File path)
Parameters
path absolute path where the run properties file can be found.
Returns
absolute path of the properties file
Definition at line 203 of file SimulationData.java.
References de.dlr.ivf.tapas.runtime.server.SimulationData.fileName.
getDescription()
String de.dlr.ivf.tapas.runtime.server.SimulationData.getDescription ()
Returns
the description
Definition at line 210 of file SimulationData.java.
References de.dlr.ivf.tapas.runtime.server.SimulationData.description.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitor.addSimulation(), de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.SimulationTableModel.SimulationList.get(), and de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.getRowFromSimulation().
getElapsedTime()
String de.dlr.ivf.tapas.runtime.server.SimulationData.getElapsedTime (Timestamp current)
This method return the elapsed time of the simulation if it is already started and not stopped or finished.
Parameters
current current database timestamp
Returns
elapsed time of the simulation
Definition at line 220 of file SimulationData.java.
References de.dlr.ivf.tapas.runtime.server.SimulationData.format(), de.dlr.ivf.tapas.runtime.server.SimulationData.isFinished(), de.dlr.ivf.tapas.runtime.server.SimulationData.isStarted(), de.dlr.ivf.tapas.runtime.server.SimulationData.minimumState(), de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState.STARTED, de.dlr.ivf.tapas.runtime.server.SimulationData.timestamp_finished, and de.dlr.ivf.tapas.runtime.server.SimulationData.timestamp_started.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitor.updateSimulationData().
getEstimatedTime()
String de.dlr.ivf.tapas.runtime.server.SimulationData.getEstimatedTime (Timestamp current)
This method return the estimated time of the simulation if it is already started and not stopped or finished by:
duration = [(sim_total - sim_progress)/sim_progress] * (current - timestamp_started)
Parameters
current current database timestamp
Returns
elapsed time of the simulation
Definition at line 241 of file SimulationData.java.
References de.dlr.ivf.tapas.runtime.server.SimulationData.format(), de.dlr.ivf.tapas.runtime.server.SimulationData.ProgressCalculator.getEstimatedTime(), de.dlr.ivf.tapas.runtime.server.SimulationData.isFinished(), de.dlr.ivf.tapas.runtime.server.SimulationData.isStarted(), and de.dlr.ivf.tapas.runtime.server.SimulationData.progressCalc.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitor.updateSimulationData().
getKey()
String de.dlr.ivf.tapas.runtime.server.SimulationData.getKey ()
Returns
unique identifer
Definition at line 251 of file SimulationData.java.
References de.dlr.ivf.tapas.runtime.server.SimulationData.sim_key.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitor.addSimulation(), de.dlr.ivf.tapas.runtime.client.SimulationMonitor.containsSimulation(), de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.SimulationTableModel.SimulationList.get(), de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.SimulationTableModel.SimulationList.getKeySet(), de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.getRowFromSimulation(), de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.SimulationTableModel.SimulationList.remove(), de.dlr.ivf.tapas.runtime.client.SimulationControl.SimulationDataUpdateTask.run(), and de.dlr.ivf.tapas.runtime.server.SimulationData.toString().
getProgress()
long de.dlr.ivf.tapas.runtime.server.SimulationData.getProgress ()
Returns
amount of simulated households
Definition at line 258 of file SimulationData.java.
References de.dlr.ivf.tapas.runtime.server.SimulationData.sim_progress.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitor.addSimulation(), de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.SimulationTableModel.SimulationList.get(), de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.getRowFromSimulation(), de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState.getState(), and de.dlr.ivf.tapas.runtime.client.SimulationMonitor.updateSimulationData().
getRelativeFileName()
String de.dlr.ivf.tapas.runtime.server.SimulationData.getRelativeFileName ()
Returns
relative path to the run properties file
Definition at line 265 of file SimulationData.java.
References de.dlr.ivf.tapas.runtime.server.SimulationData.fileName.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitor.addSimulation(), de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.SimulationTableModel.SimulationList.get(), and de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.getRowFromSimulation().
getState()
TPS_SimulationState de.dlr.ivf.tapas.runtime.server.SimulationData.getState ()
Returns
current state of the simulation
Definition at line 272 of file SimulationData.java.
References de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState.getState().
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.SimulationTableModel.SimulationList.get(), de.dlr.ivf.tapas.runtime.server.SimulationData.higherState(), de.dlr.ivf.tapas.runtime.server.SimulationData.isFinished(), de.dlr.ivf.tapas.runtime.server.SimulationData.isReady(), de.dlr.ivf.tapas.runtime.server.SimulationData.isStarted(), de.dlr.ivf.tapas.runtime.server.SimulationData.minimumState(), de.dlr.ivf.tapas.runtime.server.SimulationData.toString(), and de.dlr.ivf.tapas.runtime.client.SimulationMonitor.updateSimulationData().
getTimestampFinished()
String de.dlr.ivf.tapas.runtime.server.SimulationData.getTimestampFinished ()
Returns
formatted finished timestamp
Definition at line 279 of file SimulationData.java.
References de.dlr.ivf.tapas.runtime.server.SimulationData.SDF, and de.dlr.ivf.tapas.runtime.server.SimulationData.timestamp_finished.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitor.addSimulation(), de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.SimulationTableModel.SimulationList.get(), de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.getRowFromSimulation(), and de.dlr.ivf.tapas.runtime.client.SimulationMonitor.updateSimulationData().
getTimestampStarted()
String de.dlr.ivf.tapas.runtime.server.SimulationData.getTimestampStarted ()
Returns
formatted start timestamp
Definition at line 287 of file SimulationData.java.
References de.dlr.ivf.tapas.runtime.server.SimulationData.SDF, and de.dlr.ivf.tapas.runtime.server.SimulationData.timestamp_started.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitor.addSimulation(), de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.SimulationTableModel.SimulationList.get(), de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.getRowFromSimulation(), and de.dlr.ivf.tapas.runtime.client.SimulationMonitor.updateSimulationData().
getTotal()
long de.dlr.ivf.tapas.runtime.server.SimulationData.getTotal ()
Returns
total amount of households to simulate
Definition at line 295 of file SimulationData.java.
References de.dlr.ivf.tapas.runtime.server.SimulationData.sim_total.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitor.addSimulation(), de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.SimulationTableModel.SimulationList.get(), de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.getRowFromSimulation(), de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState.getState(), and de.dlr.ivf.tapas.runtime.client.SimulationMonitor.updateSimulationData().
higherState()
boolean de.dlr.ivf.tapas.runtime.server.SimulationData.higherState (TPS_SimulationState state)
Parameters
state state to compare the current state to
Returns
true if the state of this simulation is higher than the given state
Definition at line 303 of file SimulationData.java.
References de.dlr.ivf.tapas.runtime.server.SimulationData.getState(), and de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState.value.
isFinished()
boolean de.dlr.ivf.tapas.runtime.server.SimulationData.isFinished ()
Returns
true if state is FINISHED
Definition at line 310 of file SimulationData.java.
References de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState.FINISHED, and de.dlr.ivf.tapas.runtime.server.SimulationData.getState().
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationData.getElapsedTime(), and de.dlr.ivf.tapas.runtime.server.SimulationData.getEstimatedTime().
isReady()
boolean de.dlr.ivf.tapas.runtime.server.SimulationData.isReady ()
Returns
true if state is READY
Definition at line 317 of file SimulationData.java.
References de.dlr.ivf.tapas.runtime.server.SimulationData.getState(), and de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState.STOPPED.
isStarted()
boolean de.dlr.ivf.tapas.runtime.server.SimulationData.isStarted ()
Returns
true if state is STARTED
Definition at line 324 of file SimulationData.java.
References de.dlr.ivf.tapas.runtime.server.SimulationData.getState(), and de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState.STARTED.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationData.getElapsedTime(), de.dlr.ivf.tapas.runtime.server.SimulationData.getEstimatedTime(), de.dlr.ivf.tapas.runtime.server.SimulationData.ProgressCalculator.ProgressCalculator(), and de.dlr.ivf.tapas.runtime.server.SimulationData.ProgressCalculator.update().
minimumState()
boolean de.dlr.ivf.tapas.runtime.server.SimulationData.minimumState (TPS_SimulationState state)
Parameters
state state to compare the current state to
Returns
true if the state of this simulation is at least the given state
Definition at line 332 of file SimulationData.java.
References de.dlr.ivf.tapas.runtime.server.SimulationData.getState(), and de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState.value.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitor.addSimulation(), de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.SimulationTableModel.SimulationList.get(), de.dlr.ivf.tapas.runtime.server.SimulationData.getElapsedTime(), de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.getRowFromSimulation(), and de.dlr.ivf.tapas.runtime.client.SimulationMonitor.updateSimulationData().
toString()
String de.dlr.ivf.tapas.runtime.server.SimulationData.toString ()
Definition at line 342 of file SimulationData.java.
References de.dlr.ivf.tapas.runtime.server.SimulationData.getKey(), de.dlr.ivf.tapas.runtime.server.SimulationData.getState(), de.dlr.ivf.tapas.runtime.server.SimulationData.sim_finished, de.dlr.ivf.tapas.runtime.server.SimulationData.sim_ready, and de.dlr.ivf.tapas.runtime.server.SimulationData.sim_started.
update()
void de.dlr.ivf.tapas.runtime.server.SimulationData.update (ResultSet rs) throws SQLException
This method updates all members from the given ResultSet of a database select statement.
Parameters
rs ResultSet from a database select
Exceptions
SQLException This exception is thrown if anything with the ResultSet is wrong, e.g. closed or too few values
Definition at line 353 of file SimulationData.java.
References de.dlr.ivf.tapas.runtime.server.SimulationData.progressCalc, de.dlr.ivf.tapas.runtime.server.SimulationData.sim_finished, de.dlr.ivf.tapas.runtime.server.SimulationData.sim_progress, de.dlr.ivf.tapas.runtime.server.SimulationData.sim_ready, de.dlr.ivf.tapas.runtime.server.SimulationData.sim_started, de.dlr.ivf.tapas.runtime.server.SimulationData.sim_total, de.dlr.ivf.tapas.runtime.server.SimulationData.timestamp_finished, de.dlr.ivf.tapas.runtime.server.SimulationData.timestamp_started, and de.dlr.ivf.tapas.runtime.server.SimulationData.ProgressCalculator.update().
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationControl.SimulationDataUpdateTask.run(), de.dlr.ivf.tapas.runtime.server.SimulationData.SimulationData(), and de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.SimulationTableModel.updateData().
Member Data Documentation
description
final String de.dlr.ivf.tapas.runtime.server.SimulationData.description private
a description field
Definition at line 80 of file SimulationData.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationData.getDescription(), and de.dlr.ivf.tapas.runtime.server.SimulationData.SimulationData().
DF
final DecimalFormat de.dlr.ivf.tapas.runtime.server.SimulationData.DF = new DecimalFormat("00") static private
This format is used to print the minutes and seconds of a time always with two digits, e.g. 12:05.
Definition at line 68 of file SimulationData.java.
fileName
final String de.dlr.ivf.tapas.runtime.server.SimulationData.fileName private
Relative filename of the run properties file
Definition at line 76 of file SimulationData.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationData.getAbsoluteFileName(), de.dlr.ivf.tapas.runtime.server.SimulationData.getRelativeFileName(), and de.dlr.ivf.tapas.runtime.server.SimulationData.SimulationData().
progressCalc
final ProgressCalculator de.dlr.ivf.tapas.runtime.server.SimulationData.progressCalc private
a link to ther insance which calculates the progress
Definition at line 116 of file SimulationData.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationData.getEstimatedTime(), de.dlr.ivf.tapas.runtime.server.SimulationData.SimulationData(), and de.dlr.ivf.tapas.runtime.server.SimulationData.update().
SDF
final SimpleDateFormat de.dlr.ivf.tapas.runtime.server.SimulationData.SDF = new SimpleDateFormat("dd.MM.yyyy kk:mm:ss") static private
This format is used to print dates in the format dd.MM.yyyy kk:mm:ss, e.g. 12.05.2011 12:01:12.
Definition at line 72 of file SimulationData.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationData.getTimestampFinished(), and de.dlr.ivf.tapas.runtime.server.SimulationData.getTimestampStarted().
sim_finished
boolean de.dlr.ivf.tapas.runtime.server.SimulationData.sim_finished private
Flag if the simulation is finished
Definition at line 84 of file SimulationData.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState.getState(), de.dlr.ivf.tapas.runtime.server.SimulationData.SimulationData(), de.dlr.ivf.tapas.runtime.server.SimulationData.toString(), and de.dlr.ivf.tapas.runtime.server.SimulationData.update().
sim_key
final String de.dlr.ivf.tapas.runtime.server.SimulationData.sim_key private
Unique simulation identifier
Definition at line 88 of file SimulationData.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationData.getKey(), and de.dlr.ivf.tapas.runtime.server.SimulationData.SimulationData().
sim_progress
long de.dlr.ivf.tapas.runtime.server.SimulationData.sim_progress private
Amount of completely simulated households
Definition at line 92 of file SimulationData.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationData.getProgress(), de.dlr.ivf.tapas.runtime.server.SimulationData.SimulationData(), de.dlr.ivf.tapas.runtime.server.SimulationData.ProgressCalculator.stateUpdate(), de.dlr.ivf.tapas.runtime.server.SimulationData.ProgressCalculator.update(), and de.dlr.ivf.tapas.runtime.server.SimulationData.update().
sim_ready
boolean de.dlr.ivf.tapas.runtime.server.SimulationData.sim_ready private
Flag if the simulation is ready. This flag is not reset when the simulation is started or finished.
Definition at line 96 of file SimulationData.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState.getState(), de.dlr.ivf.tapas.runtime.server.SimulationData.SimulationData(), de.dlr.ivf.tapas.runtime.server.SimulationData.toString(), and de.dlr.ivf.tapas.runtime.server.SimulationData.update().
sim_started
boolean de.dlr.ivf.tapas.runtime.server.SimulationData.sim_started private
Flag if simulation is started. This flag is not reset when simulation is finished.
Definition at line 100 of file SimulationData.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState.getState(), de.dlr.ivf.tapas.runtime.server.SimulationData.SimulationData(), de.dlr.ivf.tapas.runtime.server.SimulationData.toString(), and de.dlr.ivf.tapas.runtime.server.SimulationData.update().
sim_total
long de.dlr.ivf.tapas.runtime.server.SimulationData.sim_total private
Total amount of households to simulate.
Definition at line 104 of file SimulationData.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationData.getTotal(), de.dlr.ivf.tapas.runtime.server.SimulationData.SimulationData(), de.dlr.ivf.tapas.runtime.server.SimulationData.ProgressCalculator.update(), and de.dlr.ivf.tapas.runtime.server.SimulationData.update().
timestamp_finished
Timestamp de.dlr.ivf.tapas.runtime.server.SimulationData.timestamp_finished private
Timestamp when simulation finished
Definition at line 108 of file SimulationData.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationData.getElapsedTime(), de.dlr.ivf.tapas.runtime.server.SimulationData.getTimestampFinished(), and de.dlr.ivf.tapas.runtime.server.SimulationData.update().
timestamp_started
Timestamp de.dlr.ivf.tapas.runtime.server.SimulationData.timestamp_started private
Timestamp when simulation starts
Definition at line 112 of file SimulationData.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationData.getElapsedTime(), de.dlr.ivf.tapas.runtime.server.SimulationData.getTimestampStarted(), and de.dlr.ivf.tapas.runtime.server.SimulationData.update().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/runtime/server/SimulationData.java