TAPAS: de.dlr.ivf.tapas.constants.TPS_LocationConstant Class Reference
de.dlr.ivf.tapas.constants.TPS_LocationConstant Class Reference
Classes
enum TPS_LocationCodeType
Public Member Functions
TPS_LocationConstant (int id, String[] attributes)
void addLocationCodeToMap ()
int getCode (TPS_LocationCodeType type)
int getId ()
Static Public Member Functions
static void clearLocationConstantMap ()
static TPS_LocationConstant getLocationCodeByTypeAndCode (TPS_LocationCodeType type, int code)
Static Public Attributes
static TPS_LocationConstant HOME
Private Attributes
final EnumMap< TPS_LocationCodeType, TPS_InternalConstant< TPS_LocationCodeType > > map
final int id
Static Private Attributes
static final HashMap< Integer, TPS_LocationConstant > LOCATION_CONSTANT_MAP = new HashMap<>()
Detailed Description
This class represents the constants for the location codes.
Definition at line 17 of file TPS_LocationConstant.java.
Constructor & Destructor Documentation
TPS_LocationConstant()
de.dlr.ivf.tapas.constants.TPS_LocationConstant.TPS_LocationConstant (int id, String[] attributes)
Basic constructor for a TPS_LocationConstant
Parameters
id corresponding id from the db
attributes attributes have to have a length of 3*n where each 3-segment is of the form (name, code, type) like ("Einkauf-Lebensmittel-SB", "1003003003", "TAPAS") and
Definition at line 46 of file TPS_LocationConstant.java.
References de.dlr.ivf.tapas.constants.TPS_LocationConstant.getId(), de.dlr.ivf.tapas.constants.TPS_LocationConstant.id, and type.
Member Function Documentation
addLocationCodeToMap()
void de.dlr.ivf.tapas.constants.TPS_LocationConstant.addLocationCodeToMap ()
Add to static collection of all location constants. The objects are accessed by their ids from the db.
Definition at line 94 of file TPS_LocationConstant.java.
References de.dlr.ivf.tapas.constants.TPS_LocationConstant.LOCATION_CONSTANT_MAP.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readLocationConstantCodes().
clearLocationConstantMap()
static void de.dlr.ivf.tapas.constants.TPS_LocationConstant.clearLocationConstantMap () static
Empties the location constant map
Definition at line 72 of file TPS_LocationConstant.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.clearConstants().
getCode()
int de.dlr.ivf.tapas.constants.TPS_LocationConstant.getCode (TPS_LocationCodeType type)
Parameters
type location code enum type (e.g. TAPAS or GENERAL)
Returns
code corresponding to the location code enum type
Definition at line 102 of file TPS_LocationConstant.java.
References de.dlr.ivf.tapas.constants.TPS_LocationConstant.map, and type.
getId()
int de.dlr.ivf.tapas.constants.TPS_LocationConstant.getId ()
Returns
id of the location constant
Definition at line 109 of file TPS_LocationConstant.java.
References de.dlr.ivf.tapas.constants.TPS_LocationConstant.id.
Referenced by de.dlr.ivf.tapas.constants.TPS_LocationConstant.TPS_LocationConstant().
getLocationCodeByTypeAndCode()
static TPS_LocationConstant de.dlr.ivf.tapas.constants.TPS_LocationConstant.getLocationCodeByTypeAndCode (TPS_LocationCodeType type, int code) static
Parameters
type like GENERAL or TAPAS, see TPS_LocationCodeType
code location constant code from the db
Returns
location constant object for a given TPS_LocationCodeType and code (int)
Definition at line 81 of file TPS_LocationConstant.java.
References code, de.dlr.ivf.tapas.constants.TPS_LocationConstant.LOCATION_CONSTANT_MAP, and type.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readActivity2LocationCodes(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readRegion().
Member Data Documentation
HOME
TPS_LocationConstant de.dlr.ivf.tapas.constants.TPS_LocationConstant.HOME static
Initial value:
= new TPS_LocationConstant(-1,
            new String[]{"null", "-1", TPS_LocationCodeType.GENERAL.name(), "null", "-1", TPS_LocationCodeType.TAPAS.name()})
This constant represents the location code for the home of a person/household
Definition at line 22 of file TPS_LocationConstant.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.loadHouseholds(), and de.dlr.ivf.tapas.loc.TPS_Location.TPS_Location().
id
final int de.dlr.ivf.tapas.constants.TPS_LocationConstant.id private
id from the db
Definition at line 37 of file TPS_LocationConstant.java.
Referenced by de.dlr.ivf.tapas.constants.TPS_LocationConstant.getId(), and de.dlr.ivf.tapas.constants.TPS_LocationConstant.TPS_LocationConstant().
LOCATION_CONSTANT_MAP
final HashMap<Integer, TPS_LocationConstant> de.dlr.ivf.tapas.constants.TPS_LocationConstant.LOCATION_CONSTANT_MAP = new HashMap<>() static private
maps ids from the db to TPS_LocationConstant objects constructed from corresponding db data
Definition at line 27 of file TPS_LocationConstant.java.
Referenced by de.dlr.ivf.tapas.constants.TPS_LocationConstant.addLocationCodeToMap(), and de.dlr.ivf.tapas.constants.TPS_LocationConstant.getLocationCodeByTypeAndCode().
map
final EnumMap<TPS_LocationCodeType, TPS_InternalConstant<TPS_LocationCodeType> > de.dlr.ivf.tapas.constants.TPS_LocationConstant.map private
maps a location code type (like TAPAS o GENERAL) to an internal constant and its fields (name, code and the same location code)
Definition at line 32 of file TPS_LocationConstant.java.
Referenced by de.dlr.ivf.tapas.constants.TPS_LocationConstant.getCode().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/constants/TPS_LocationConstant.java