TAPAS: de.dlr.ivf.tapas.tools.riesel.RieselTool Class Reference
de.dlr.ivf.tapas.tools.riesel.RieselTool Class Reference
Classes
class Distributor
class EWZPojo
enum LAND_USE
Public Member Functions
RieselTool (TPS_DB_Connector dbCon) throws SQLException
List< EWZPojo > getAllInhabitants () throws SQLException
EnumMap< LAND_USE, ArrayList< Long > > getBuildingsForArea (String rs_key) throws SQLException
int testPerformance () throws SQLException
void updateAddresses (EnumMap< LAND_USE, ArrayList< Long >> addresses, int ewz)
void updateAll ()
Static Public Member Functions
static void main (String[] args) throws SQLException
Private Attributes
final TPS_DB_Connector dbCon
final BlockingQueue< AddressPojo > queue = new LinkedBlockingQueue<>()
final UpdateAddressesWorker updateWorker
Detailed Description
This tool distributes households given on some geometries on the addresses within these geometries. It uses land use information (given on different geometries) for this distribution.
Author
boec_pa
Definition at line 31 of file RieselTool.java.
Constructor & Destructor Documentation
RieselTool()
de.dlr.ivf.tapas.tools.riesel.RieselTool.RieselTool (TPS_DB_Connector dbCon) throws SQLException
Parameters
dbCon
Exceptions
SQLException if the database connection cannot be established.
Definition at line 42 of file RieselTool.java.
References de.dlr.ivf.tapas.tools.riesel.RieselTool.dbCon, de.dlr.ivf.tapas.tools.riesel.RieselTool.queue, and de.dlr.ivf.tapas.tools.riesel.RieselTool.updateWorker.
Referenced by de.dlr.ivf.tapas.tools.riesel.RieselTool.main().
Member Function Documentation
getAllInhabitants()
List<EWZPojo> de.dlr.ivf.tapas.tools.riesel.RieselTool.getAllInhabitants () throws SQLException
Lists the ids of all areas where the number of inhabitants is known and the according number.
Returns
Exceptions
SQLException if the query fails which might happen if the database connection fails.
Definition at line 79 of file RieselTool.java.
References de.dlr.ivf.tapas.tools.riesel.RieselTool.dbCon, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery().
Referenced by de.dlr.ivf.tapas.tools.riesel.RieselTool.updateAll().
getBuildingsForArea()
EnumMap<LAND_USE, ArrayList<Long> > de.dlr.ivf.tapas.tools.riesel.RieselTool.getBuildingsForArea (String rs_key) throws SQLException
This method retrieves the ids of all buildings in the area identified with rs_key.
Note that this method might take a long time and might return a large data set.
Returns
null if no buildings are found.
Exceptions
SQLException if the query is not successful. This might happen if the database connection is not active.
Definition at line 109 of file RieselTool.java.
References de.dlr.ivf.tapas.tools.riesel.RieselTool.dbCon, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery().
Referenced by de.dlr.ivf.tapas.tools.riesel.RieselTool.updateAll().
main()
static void de.dlr.ivf.tapas.tools.riesel.RieselTool.main (String[] args) throws SQLException static
Parameters
args
Exceptions
SQLException
Definition at line 54 of file RieselTool.java.
References de.dlr.ivf.tapas.tools.riesel.RieselTool.dbCon, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.loadRuntimeParameters(), de.dlr.ivf.tapas.tools.riesel.RieselTool.RieselTool(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.setValue(), and de.dlr.ivf.tapas.tools.riesel.RieselTool.updateAll().
testPerformance()
int de.dlr.ivf.tapas.tools.riesel.RieselTool.testPerformance () throws SQLException
Retrieves all buildings for Berlin (around 2Mio adresses). This is for testing purposes only.
Exceptions
SQLException
Definition at line 142 of file RieselTool.java.
References de.dlr.ivf.tapas.tools.riesel.RieselTool.dbCon, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery().
updateAddresses()
void de.dlr.ivf.tapas.tools.riesel.RieselTool.updateAddresses (EnumMap< LAND_USE, ArrayList< Long >> addresses, int ewz)
Updates the given addresses with a number of inhabitants according to a distribution.
Parameters
addresses database ids of the buildings that are to be updated ordered by their LAND_USE.
ewz Number of inhabitants to be distributed among the buildings.
Definition at line 165 of file RieselTool.java.
References de.dlr.ivf.tapas.tools.riesel.RieselTool.Distributor.getRandomBuilding(), and de.dlr.ivf.tapas.tools.riesel.RieselTool.queue.
Referenced by de.dlr.ivf.tapas.tools.riesel.RieselTool.updateAll().
updateAll()
void de.dlr.ivf.tapas.tools.riesel.RieselTool.updateAll ()
This is the main access method of the class. It will retrieve all areas where the number of inhabitants is known, intersect it with the land use polygons and put them into RieselTool#queue. The actual update process is done by the UpdateAddressesWorker.
Definition at line 192 of file RieselTool.java.
References de.dlr.ivf.tapas.tools.riesel.RieselTool.getAllInhabitants(), de.dlr.ivf.tapas.tools.riesel.RieselTool.getBuildingsForArea(), de.dlr.ivf.tapas.tools.riesel.AddressPojo.POISON_ELEMENT, de.dlr.ivf.tapas.tools.riesel.RieselTool.queue, and de.dlr.ivf.tapas.tools.riesel.RieselTool.updateAddresses().
Referenced by de.dlr.ivf.tapas.tools.riesel.RieselTool.main().
Member Data Documentation
dbCon
final TPS_DB_Connector de.dlr.ivf.tapas.tools.riesel.RieselTool.dbCon private
Definition at line 34 of file RieselTool.java.
Referenced by de.dlr.ivf.tapas.tools.riesel.RieselTool.getAllInhabitants(), de.dlr.ivf.tapas.tools.riesel.RieselTool.getBuildingsForArea(), de.dlr.ivf.tapas.tools.riesel.RieselTool.main(), de.dlr.ivf.tapas.tools.riesel.RieselTool.RieselTool(), and de.dlr.ivf.tapas.tools.riesel.RieselTool.testPerformance().
queue
final BlockingQueue<AddressPojo> de.dlr.ivf.tapas.tools.riesel.RieselTool.queue = new LinkedBlockingQueue<>() private
Definition at line 35 of file RieselTool.java.
Referenced by de.dlr.ivf.tapas.tools.riesel.RieselTool.RieselTool(), de.dlr.ivf.tapas.tools.riesel.RieselTool.updateAddresses(), and de.dlr.ivf.tapas.tools.riesel.RieselTool.updateAll().
updateWorker
final UpdateAddressesWorker de.dlr.ivf.tapas.tools.riesel.RieselTool.updateWorker private
Definition at line 36 of file RieselTool.java.
Referenced by de.dlr.ivf.tapas.tools.riesel.RieselTool.RieselTool().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/riesel/RieselTool.java