TAPAS: de.dlr.ivf.tapas.util.MatrixMap Class Reference
de.dlr.ivf.tapas.util.MatrixMap Class Reference
Classes
class MatrixTuple
Public Member Functions
MatrixMap (double[] distribution, Matrix[] matrices)
MatrixMap clone ()
Matrix getMatrix (int time)
void logStatistics ()
String toString (MatrixPrint print)
String toString ()
Static Public Member Functions
static void main (String[] args)
Public Attributes
MatrixTuple[] matrices = new MatrixTuple[0]
Detailed Description
Class for a set of matrices, which correspond to a given distribution
Author
hein_mh
Definition at line 22 of file MatrixMap.java.
Constructor & Destructor Documentation
MatrixMap()
de.dlr.ivf.tapas.util.MatrixMap.MatrixMap (double[] distribution, Matrix[] matrices)
Definition at line 27 of file MatrixMap.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.log.TPS_Logger.log(), and de.dlr.ivf.tapas.util.MatrixMap.matrices.
Referenced by de.dlr.ivf.tapas.util.MatrixMap.clone(), and de.dlr.ivf.tapas.util.MatrixMap.main().
Member Function Documentation
clone()
MatrixMap de.dlr.ivf.tapas.util.MatrixMap.clone ()
Definition at line 71 of file MatrixMap.java.
References de.dlr.ivf.tapas.util.Matrix.clone(), and de.dlr.ivf.tapas.util.MatrixMap.MatrixMap().
Referenced by de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.loadSumoValues().
getMatrix()
Matrix de.dlr.ivf.tapas.util.MatrixMap.getMatrix (int time)
Method to select the appropriate matrix for the given time slot
Parameters
time inputtime in minutes since midnight.
Returns
matrix for the given time
Definition at line 90 of file MatrixMap.java.
References de.dlr.ivf.tapas.util.MatrixMap.MatrixTuple.matrix.
Referenced by de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.loadSumoValues(), and de.dlr.ivf.tapas.util.MatrixMap.main().
logStatistics()
void de.dlr.ivf.tapas.util.MatrixMap.logStatistics ()
Definition at line 104 of file MatrixMap.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.INFO, and de.dlr.ivf.tapas.log.TPS_Logger.log().
main()
static void de.dlr.ivf.tapas.util.MatrixMap.main (String[] args) static
Definition at line 42 of file MatrixMap.java.
References de.dlr.ivf.tapas.util.MatrixMap.getMatrix(), de.dlr.ivf.tapas.util.Matrix.MatrixPrint.LINE, de.dlr.ivf.tapas.util.MatrixMap.matrices, de.dlr.ivf.tapas.util.MatrixMap.MatrixMap(), de.dlr.ivf.tapas.util.Matrix.toString(), and de.dlr.ivf.tapas.util.MatrixMap.toString().
toString() [1/2]
String de.dlr.ivf.tapas.util.MatrixMap.toString ()
Definition at line 132 of file MatrixMap.java.
References de.dlr.ivf.tapas.util.Matrix.MatrixPrint.LINE.
toString() [2/2]
String de.dlr.ivf.tapas.util.MatrixMap.toString (MatrixPrint print)
Returns a matrixmap as string representation; format of the string depends on the type of printing specified: either as single line or as matrix
Parameters
print type of printing
Returns
printed matrix
Definition at line 118 of file MatrixMap.java.
Referenced by de.dlr.ivf.tapas.util.MatrixMap.main().
Member Data Documentation
matrices
MatrixTuple [] de.dlr.ivf.tapas.util.MatrixMap.matrices = new MatrixTuple[0]
Definition at line 25 of file MatrixMap.java.
Referenced by de.dlr.ivf.tapas.util.MatrixMap.main(), de.dlr.ivf.tapas.util.MatrixMap.MatrixMap(), de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.saveMatrices(), and de.dlr.ivf.tapas.iteration.TPS_VisumConverter.writeODMatrices().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/util/MatrixMap.java