TAPAS: de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues Class Reference
de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues Class Reference
Public Member Functions
ScenarioTypeValues ()
double getAverageSpeedMIT ()
void setAverageSpeedMIT (double averageSpeed)
double getAverageSpeedPT ()
void setAverageSpeedPT (double averageSpeed)
double getBeelineFactorMIT ()
void setBeelineFactorMIT (double beelineFactor)
double getFeeParking ()
void setFeeParking (double feeParking)
double getFeeToll ()
void setFeeToll (double feeToll)
int getPtZone ()
void setPtZone (int ptZone)
int getTypeParking ()
void setTypeParking (int typeParking)
int getTypeToll ()
void setTypeToll (int typeToll)
boolean hasParkingFee ()
boolean hasToll ()
boolean isCarsharingServiceArea ()
void setCarsharingServiceArea (boolean isCarsharingServiceArea)
boolean isIntraMITTrafficAllowed ()
void setIntraMITTrafficAllowed (boolean intraMITTrafficAllowed)
boolean isIntraPTTrafficAllowed ()
void setIntraPTTrafficAllowed (boolean intraPTTrafficAllowed)
void setHasParkingFee (boolean hasParkingFee)
void setHasToll (boolean hasToll)
String toString ()
Private Attributes
double averageSpeedMIT
Average speed inside the traffic analysis zone for motorised individual transport mode.
double averageSpeedPT = 1.0
The travel time inside the traffic analysis zone for public transport mode.
double beelineFactorMIT
The beeline factor for transforming beeline distances in net distances within this traffic analysis zone and only for car.
double feeParking
The costs for parking per hour in Euro.
double feeToll
The costs for toll per entrance.
boolean hasParkingFee
The flag if parking fee is applicable.
boolean hasToll
The flag whether a toll shall be applied.
int typeParking
The type of the parking fee.
int typeToll
The type of the toll.
int ptZone = 1
The zone id for a public transport tariff system.
boolean intraMITTrafficAllowed = true
Whether intra MIT traffic is allowed.
boolean intraPTTrafficAllowed = true
Whether intra PT traffic is allowed.
boolean isCarsharingServiceArea = false
Detailed Description
Stores all values which are used in the different simulation type: parking (fee, has, type) and toll (fee, has, type)
Author
mark_ma
Definition at line 603 of file TPS_TrafficAnalysisZone.java.
Constructor & Destructor Documentation
ScenarioTypeValues()
de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.ScenarioTypeValues ()
BUGFIX: Mantis Entry 4318 Default constructor, which fills the local variables with reasonable values. If this TAZ is initialized, but not filled with values, divisions by zero may happen, e.g. averageTravelingSpeed is used
Definition at line 648 of file TPS_TrafficAnalysisZone.java.
Member Function Documentation
getAverageSpeedMIT()
double de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.getAverageSpeedMIT ()
Returns the average speed within the traffic analysis zone in m/s for the motorised individual transport mode
Returns
speed in m/s for MIT
Definition at line 670 of file TPS_TrafficAnalysisZone.java.
Referenced by de.dlr.ivf.tapas.mode.TPS_IndividualTransportMode.getTravelTime().
getAverageSpeedPT()
double de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.getAverageSpeedPT ()
Returns the average speed within the traffic analysis zone in m/s for the public transport mode
Returns
speed in m/s for PT
Definition at line 689 of file TPS_TrafficAnalysisZone.java.
Referenced by de.dlr.ivf.tapas.mode.TPS_MassTransportMode.getTravelTime().
getBeelineFactorMIT()
double de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.getBeelineFactorMIT ()
Returns the beeline factor valid for trips within this traffic analysis zone and for the car modes; used for converting beeline distances into net distances
Returns
beeline factor
Definition at line 709 of file TPS_TrafficAnalysisZone.java.
Referenced by de.dlr.ivf.tapas.mode.TPS_IndividualTransportMode.getDistance(), de.dlr.ivf.tapas.mode.TPS_IndividualTransportMode.getTravelTime(), and de.dlr.ivf.tapas.mode.TPS_MassTransportMode.getTravelTime().
getFeeParking()
double de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.getFeeParking ()
Returns the parking fee per hour in €
Returns
parking fee
Definition at line 728 of file TPS_TrafficAnalysisZone.java.
getFeeToll()
double de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.getFeeToll ()
Returns the toll fee per entrance in €
Returns
toll fee
Definition at line 746 of file TPS_TrafficAnalysisZone.java.
getPtZone()
int de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.getPtZone ()
This Method returns the fare zone for the given TAZ- cell
Returns
The id of the PT fare zone this TAZ is assigned to
Definition at line 764 of file TPS_TrafficAnalysisZone.java.
getTypeParking()
int de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.getTypeParking ()
Returns the parking type / category
Returns
the category of parking fee
Definition at line 782 of file TPS_TrafficAnalysisZone.java.
getTypeToll()
int de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.getTypeToll ()
Returns the category / type of the toll
Returns
toll type
Definition at line 800 of file TPS_TrafficAnalysisZone.java.
hasParkingFee()
boolean de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.hasParkingFee ()
Flag if a parking fee is charged in the traffic analysis zone
Returns
true if parking fee is applicable, false else
Definition at line 818 of file TPS_TrafficAnalysisZone.java.
hasToll()
boolean de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.hasToll ()
Flag if a toll fee is charged in the traffic analysis zone
Returns
true if toll fee is applicable, false else
Definition at line 827 of file TPS_TrafficAnalysisZone.java.
isCarsharingServiceArea()
boolean de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.isCarsharingServiceArea ()
Returns
the isCarsharingServiceArea
Definition at line 834 of file TPS_TrafficAnalysisZone.java.
isIntraMITTrafficAllowed()
boolean de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.isIntraMITTrafficAllowed ()
This method returns true if intra cell traffic is allowed for MIT
Returns
Whether intra MIT traffic is allowed
Definition at line 850 of file TPS_TrafficAnalysisZone.java.
Referenced by de.dlr.ivf.tapas.mode.TPS_IndividualTransportMode.getTravelTime().
isIntraPTTrafficAllowed()
boolean de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.isIntraPTTrafficAllowed ()
This method returns true if intra cell traffic is allowed for PT
Returns
Whether intra PT traffic is allowed
Definition at line 868 of file TPS_TrafficAnalysisZone.java.
Referenced by de.dlr.ivf.tapas.mode.TPS_MassTransportMode.getTravelTime().
setAverageSpeedMIT()
void de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.setAverageSpeedMIT (double averageSpeed)
Sets the average MIT speed in m/s
Parameters
averageSpeed The average MIT speed in m/s
Definition at line 679 of file TPS_TrafficAnalysisZone.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readTAZInfos().
setAverageSpeedPT()
void de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.setAverageSpeedPT (double averageSpeed)
Sets the travel PT speed within the traffic analysis zone in m/s
Parameters
averageSpeed The average PT speed in m/s
Definition at line 698 of file TPS_TrafficAnalysisZone.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readTAZInfos().
setBeelineFactorMIT()
void de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.setBeelineFactorMIT (double beelineFactor)
Sets the beeline factor for converting beeline distances into net distances for car trips within this traffic analysis zone
Parameters
beelineFactor The new beeline factor
Definition at line 719 of file TPS_TrafficAnalysisZone.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readTAZInfos().
setCarsharingServiceArea()
void de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.setCarsharingServiceArea (boolean isCarsharingServiceArea)
Parameters
isCarsharingServiceArea the isCarsharingServiceArea to set
Definition at line 841 of file TPS_TrafficAnalysisZone.java.
setFeeParking()
void de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.setFeeParking (double feeParking)
Sets the parking fee in Euro per hour
Parameters
feeParking The parking fee for this TAZ
Definition at line 737 of file TPS_TrafficAnalysisZone.java.
setFeeToll()
void de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.setFeeToll (double feeToll)
Sets the toll fee per entrance
Parameters
feeToll The toll for this TAZ
Definition at line 755 of file TPS_TrafficAnalysisZone.java.
setHasParkingFee()
void de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.setHasParkingFee (boolean hasParkingFee)
Sets the flag indicating, if a parking fee is charged in the TAZ
Parameters
hasParkingFee Whether a parking fee is charged in this TAZ
Definition at line 886 of file TPS_TrafficAnalysisZone.java.
setHasToll()
void de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.setHasToll (boolean hasToll)
Sets the flag indicating, if a toll fee is charged in the TAZ
Parameters
hasToll Whether a toll is charged in this TAZ
Definition at line 895 of file TPS_TrafficAnalysisZone.java.
setIntraMITTrafficAllowed()
void de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.setIntraMITTrafficAllowed (boolean intraMITTrafficAllowed)
This method sets the intra cell traffic for MIT
Parameters
intraMITTrafficAllowed true if traffic within this cell is allowed
Definition at line 859 of file TPS_TrafficAnalysisZone.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readTAZInfos().
setIntraPTTrafficAllowed()
void de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.setIntraPTTrafficAllowed (boolean intraPTTrafficAllowed)
This method sets the intra cell traffic for PT
Parameters
intraPTTrafficAllowed true if traffic within this cell is allowed
Definition at line 877 of file TPS_TrafficAnalysisZone.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readTAZInfos().
setPtZone()
void de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.setPtZone (int ptZone)
This method sets the PT zone for the PT fare
Parameters
ptZone The id of the PT fare zone
Definition at line 773 of file TPS_TrafficAnalysisZone.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readTAZInfos().
setTypeParking()
void de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.setTypeParking (int typeParking)
Sets the type of parking fee applicable for the TAZ
Parameters
typeParking The parking fee type to set
Definition at line 791 of file TPS_TrafficAnalysisZone.java.
setTypeToll()
void de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.setTypeToll (int typeToll)
Sets the type of toll fee applicable for the tvz
Parameters
typeToll The toll type to set
Definition at line 809 of file TPS_TrafficAnalysisZone.java.
toString()
String de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.toString ()
Returns this object's string representation
See also
java.lang.Object::toString()
Definition at line 905 of file TPS_TrafficAnalysisZone.java.
Member Data Documentation
averageSpeedMIT
double de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.averageSpeedMIT private
Average speed inside the traffic analysis zone for motorised individual transport mode.
Definition at line 605 of file TPS_TrafficAnalysisZone.java.
averageSpeedPT
double de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.averageSpeedPT = 1.0 private
The travel time inside the traffic analysis zone for public transport mode.
Definition at line 608 of file TPS_TrafficAnalysisZone.java.
beelineFactorMIT
double de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.beelineFactorMIT private
The beeline factor for transforming beeline distances in net distances within this traffic analysis zone and only for car.
Definition at line 611 of file TPS_TrafficAnalysisZone.java.
feeParking
double de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.feeParking private
The costs for parking per hour in Euro.
Definition at line 614 of file TPS_TrafficAnalysisZone.java.
Referenced by de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.setCostParkingPerHour().
feeToll
double de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.feeToll private
The costs for toll per entrance.
Definition at line 617 of file TPS_TrafficAnalysisZone.java.
Referenced by de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.setCostToll().
hasParkingFee
boolean de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.hasParkingFee private
The flag if parking fee is applicable.
Definition at line 620 of file TPS_TrafficAnalysisZone.java.
Referenced by de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.setCostParkingPerHour().
hasToll
boolean de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.hasToll private
The flag whether a toll shall be applied.
Definition at line 623 of file TPS_TrafficAnalysisZone.java.
Referenced by de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.setCostToll().
intraMITTrafficAllowed
boolean de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.intraMITTrafficAllowed = true private
Whether intra MIT traffic is allowed.
Definition at line 635 of file TPS_TrafficAnalysisZone.java.
intraPTTrafficAllowed
boolean de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.intraPTTrafficAllowed = true private
Whether intra PT traffic is allowed.
Definition at line 638 of file TPS_TrafficAnalysisZone.java.
isCarsharingServiceArea
boolean de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.isCarsharingServiceArea = false private
Definition at line 640 of file TPS_TrafficAnalysisZone.java.
ptZone
int de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.ptZone = 1 private
The zone id for a public transport tariff system.
Definition at line 632 of file TPS_TrafficAnalysisZone.java.
typeParking
int de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.typeParking private
The type of the parking fee.
Definition at line 626 of file TPS_TrafficAnalysisZone.java.
Referenced by de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.setCostParkingPerHour().
typeToll
int de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.typeToll private
The type of the toll.
Definition at line 629 of file TPS_TrafficAnalysisZone.java.
Referenced by de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.setCostToll().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/loc/TPS_TrafficAnalysisZone.java