TAPAS: de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral Class Reference
de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral Class Reference
Classes
class AnalyzerTransferable
class AnalyzerTreeTransferHandler
class BaseListTransferHandler
class NodeListTransferHandler
Public Member Functions
void expandAll (JTree tree, boolean expand)
JComponent getComponent ()
int getIndex ()
CoreProcessInterface getProcessImpl ()
boolean isActive ()
void loadTree ()
void saveTree ()
Static Public Member Functions
static void main (String[] args)
Private Member Functions
void addDefaultAnalyzers ()
JPanel createGUI ()
void deleteSelectedTreeNode ()
void expandAll (JTree tree, TreePath parent, boolean expand)
AnalyzerBase getAnalyzer (Categories c)
JPanel getControlListPanel ()
JPanel getControlTreePanel ()
String getLevelAddition (DefaultMutableTreeNode node)
void initActiveList ()
void initBaseList ()
void initTree ()
void loadSelectedNodeInfo ()
JButton makeConstantWidthButton (String text, Action a)
void updateNode (boolean add)
Private Attributes
boolean TUMactivated = true
GeneralAnalyzer analyzer = null
JTree tree
JList< AnalyzerBase > baseAnalyzerList
JPanel pMain
JTextField edtName
JLabel lblType
JList< AnalyzerBase > activeAnalyzerList
JCheckBox ckbxActive
JCheckBox ckbxDatabaseSummary
DefaultMutableTreeNode root
DefaultTreeModel treeModel
Static Private Attributes
static final String[] treeLevel = {"ROOT", "FILE", "TAB", "SPLIT"}
static final int BUTTON_WIDTH = 80
Detailed Description
Definition at line 39 of file TUMControlGeneral.java.
Member Function Documentation
addDefaultAnalyzers()
void de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.addDefaultAnalyzers () private
Definition at line 94 of file TUMControlGeneral.java.
References de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.DistanceCategoryDefault, de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.Mode, de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.PersonGroup, de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.RegionCode, and de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.TripIntention.
createGUI()
JPanel de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.createGUI () private
Builds the layout and initiates all global fields.
Returns
Definition at line 139 of file TUMControlGeneral.java.
deleteSelectedTreeNode()
void de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.deleteSelectedTreeNode () private
Definition at line 188 of file TUMControlGeneral.java.
expandAll() [1/2]
void de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.expandAll (JTree tree, boolean expand)
Definition at line 198 of file TUMControlGeneral.java.
expandAll() [2/2]
void de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.expandAll (JTree tree, TreePath parent, boolean expand) private
Definition at line 204 of file TUMControlGeneral.java.
getAnalyzer()
AnalyzerBase de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.getAnalyzer (Categories c) private
Definition at line 222 of file TUMControlGeneral.java.
getComponent()
JComponent de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.getComponent ()
The ui-component for all settings needed for this module.
Returns
Implements de.dlr.ivf.tapas.analyzer.gui.ControlInputInterface.
Definition at line 235 of file TUMControlGeneral.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.main().
getControlListPanel()
JPanel de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.getControlListPanel () private
Definition at line 259 of file TUMControlGeneral.java.
getControlTreePanel()
JPanel de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.getControlTreePanel () private
Definition at line 307 of file TUMControlGeneral.java.
getIndex()
int de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.getIndex ()
the priority gives the ui an advice how the subcomponents should be sorted. a lower priority means that a component is further above
Returns
Implements de.dlr.ivf.tapas.analyzer.gui.ControlInputInterface.
Definition at line 342 of file TUMControlGeneral.java.
getLevelAddition()
String de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.getLevelAddition (DefaultMutableTreeNode node) private
Definition at line 346 of file TUMControlGeneral.java.
getProcessImpl()
CoreProcessInterface de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.getProcessImpl ()
the logic-component
Returns
Implements de.dlr.ivf.tapas.analyzer.gui.ControlInputInterface.
Definition at line 361 of file TUMControlGeneral.java.
initActiveList()
void de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.initActiveList () private
Definition at line 369 of file TUMControlGeneral.java.
initBaseList()
void de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.initBaseList () private
Definition at line 396 of file TUMControlGeneral.java.
initTree()
void de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.initTree () private
Definition at line 419 of file TUMControlGeneral.java.
isActive()
boolean de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.isActive ()
Returns
true when the process is running
Implements de.dlr.ivf.tapas.analyzer.gui.ControlInputInterface.
Definition at line 501 of file TUMControlGeneral.java.
loadSelectedNodeInfo()
void de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.loadSelectedNodeInfo () private
Definition at line 505 of file TUMControlGeneral.java.
References de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.AnalyzerCollection.getAnalyzers(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.AnalyzerCollection.getName().
loadTree()
void de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.loadTree ()
Definition at line 528 of file TUMControlGeneral.java.
References de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.readTree().
main()
static void de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.main (String[] args) static
for testing purposes only
Definition at line 59 of file TUMControlGeneral.java.
References de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.getComponent().
makeConstantWidthButton()
JButton de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.makeConstantWidthButton (String text, Action a) private
Definition at line 555 of file TUMControlGeneral.java.
saveTree()
void de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.saveTree ()
Definition at line 563 of file TUMControlGeneral.java.
References de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzerTreeExporter.writeTree().
updateNode()
void de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.updateNode (boolean add) private
Definition at line 581 of file TUMControlGeneral.java.
References name.
Member Data Documentation
activeAnalyzerList
JList<AnalyzerBase> de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.activeAnalyzerList private
Definition at line 50 of file TUMControlGeneral.java.
analyzer
GeneralAnalyzer de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.analyzer = null private
Definition at line 44 of file TUMControlGeneral.java.
baseAnalyzerList
JList<AnalyzerBase> de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.baseAnalyzerList private
Definition at line 46 of file TUMControlGeneral.java.
BUTTON_WIDTH
final int de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.BUTTON_WIDTH = 80 static private
Definition at line 42 of file TUMControlGeneral.java.
ckbxActive
JCheckBox de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.ckbxActive private
Definition at line 51 of file TUMControlGeneral.java.
ckbxDatabaseSummary
JCheckBox de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.ckbxDatabaseSummary private
Definition at line 52 of file TUMControlGeneral.java.
edtName
JTextField de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.edtName private
Definition at line 48 of file TUMControlGeneral.java.
lblType
JLabel de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.lblType private
Definition at line 49 of file TUMControlGeneral.java.
pMain
JPanel de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.pMain private
Definition at line 47 of file TUMControlGeneral.java.
root
DefaultMutableTreeNode de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.root private
Definition at line 53 of file TUMControlGeneral.java.
tree
JTree de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.tree private
Definition at line 45 of file TUMControlGeneral.java.
treeLevel
final String [] de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.treeLevel = {"ROOT", "FILE", "TAB", "SPLIT"} static private
Definition at line 41 of file TUMControlGeneral.java.
treeModel
DefaultTreeModel de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.treeModel private
Definition at line 54 of file TUMControlGeneral.java.
TUMactivated
boolean de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.TUMactivated = true private
Definition at line 43 of file TUMControlGeneral.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/tum/regionanalyzer/general/TUMControlGeneral.java