TAPAS: de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig Class Reference
de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig Class Reference
Classes
class PTStop
class Trip
Public Member Functions
void loadHeaders (String headerString)
void processPTStop (String entry)
void processTrip (String entry)
Static Public Member Functions
static void main (String[] args)
Private Member Functions
String formatCSVLine (String entry)
Private Attributes
final int NUM_TRIP_COLUMNS = 22
final String DELIMITER = ";"
final HashMap< Integer, String > headerMap = new HashMap<>()
final HashMap< String, Trip > valueMap = new HashMap<>()
final HashMap< String, PTStop > stopMap = new HashMap<>()
final List< String > unknownPTStops = new ArrayList<>()
final List< String > knownPTStops = new ArrayList<>()
int validTips = 0
int totalTips = 0
Detailed Description
Definition at line 15 of file PTTripProcessorBraunschweig.java.
Member Function Documentation
formatCSVLine()
String de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.formatCSVLine (String entry) private
Definition at line 134 of file PTTripProcessorBraunschweig.java.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.loadHeaders(), de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.processPTStop(), and de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.processTrip().
loadHeaders()
void de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.loadHeaders (String headerString)
Method to initialize the header tokens.
Parameters
headerString the header string of the csv-file
Definition at line 153 of file PTTripProcessorBraunschweig.java.
References de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.formatCSVLine().
Referenced by de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.main().
main()
static void de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.main (String[] args) static
Parameters
args
Definition at line 30 of file PTTripProcessorBraunschweig.java.
References de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.Trip.getHeader(), de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.knownPTStops, de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.loadHeaders(), de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.processPTStop(), de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.processTrip(), de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.stopMap, de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.Trip.toCSVString(), de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.totalTips, de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.unknownPTStops, de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.validTips, and de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.valueMap.
processPTStop()
void de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.processPTStop (String entry)
Definition at line 167 of file PTTripProcessorBraunschweig.java.
References de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.formatCSVLine(), de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.headerMap, and name.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.main().
processTrip()
void de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.processTrip (String entry)
Definition at line 236 of file PTTripProcessorBraunschweig.java.
References de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.formatCSVLine(), de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.Trip.incNum(), and de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.NUM_TRIP_COLUMNS.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.main().
Member Data Documentation
DELIMITER
final String de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.DELIMITER = ";" private
Definition at line 18 of file PTTripProcessorBraunschweig.java.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.Trip.getHeader(), and de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.Trip.toCSVString().
headerMap
final HashMap<Integer, String> de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.headerMap = new HashMap<>() private
Definition at line 19 of file PTTripProcessorBraunschweig.java.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.processPTStop().
knownPTStops
final List<String> de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.knownPTStops = new ArrayList<>() private
Definition at line 23 of file PTTripProcessorBraunschweig.java.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.main().
NUM_TRIP_COLUMNS
final int de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.NUM_TRIP_COLUMNS = 22 private
Definition at line 17 of file PTTripProcessorBraunschweig.java.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.processTrip().
stopMap
final HashMap<String, PTStop> de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.stopMap = new HashMap<>() private
Definition at line 21 of file PTTripProcessorBraunschweig.java.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.main(), and de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.Trip.toCSVString().
totalTips
int de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.totalTips = 0 private
Definition at line 25 of file PTTripProcessorBraunschweig.java.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.main().
unknownPTStops
final List<String> de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.unknownPTStops = new ArrayList<>() private
Definition at line 22 of file PTTripProcessorBraunschweig.java.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.main().
validTips
int de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.validTips = 0 private
Definition at line 24 of file PTTripProcessorBraunschweig.java.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.main().
valueMap
final HashMap<String, Trip> de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.valueMap = new HashMap<>() private
Definition at line 20 of file PTTripProcessorBraunschweig.java.
Referenced by de.dlr.ivf.tapas.tools.locationallocation.PTTripProcessorBraunschweig.main().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/locationallocation/PTTripProcessorBraunschweig.java