TAPAS: de.dlr.ivf.tapas.tools.fileModifier.persistence.AbstractTPS_ParameterDAO Class Reference
de.dlr.ivf.tapas.tools.fileModifier.persistence.AbstractTPS_ParameterDAO Class Reference abstract
Public Member Functions
AbstractTPS_ParameterDAO ()
void addAdditionalParameter (String name, String value, String comment)
File getFile ()
void setFile (File file)
void readParameter ()
void writeParameter ()
Additional Inherited Members
Public Attributes inherited from de.dlr.ivf.tapas.tools.fileModifier.persistence.ITPS_ParameterDAO
String[] header = new String[]{"name", "value", "comment"}
Detailed Description
Definition at line 21 of file AbstractTPS_ParameterDAO.java.
Constructor & Destructor Documentation
AbstractTPS_ParameterDAO()
de.dlr.ivf.tapas.tools.fileModifier.persistence.AbstractTPS_ParameterDAO.AbstractTPS_ParameterDAO ()
Definition at line 35 of file AbstractTPS_ParameterDAO.java.
References de.dlr.ivf.tapas.util.parameters.ParamValue.AVERAGE_DISTANCE_PT_STOP, de.dlr.ivf.tapas.util.parameters.ParamString.DB_DBNAME, de.dlr.ivf.tapas.util.parameters.ParamValue.DEFAULT_VOT, de.dlr.ivf.tapas.util.parameters.ParamValue.FINANCE_BUDGET_E, de.dlr.ivf.tapas.util.parameters.ParamValue.FINANCE_BUDGET_F, de.dlr.ivf.tapas.util.parameters.ParamValue.FINANCE_BUDGET_WP, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_CHECK_BUDGET_CONSTRAINTS, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_INFLUENCE_RANDOM_NUMBER, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_INTRA_INFOS_MATRIX, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_LOCATION_POCKET_COSTS, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_REJUVENATE_RETIREE, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_RUN_SZENARIO, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_SCHEMES_MANIPULATE_BY_WORK_AT_HOME, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_SCHEMES_MANIPULATE_BY_WORKINGCHAINS, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_SCHEMES_MANIPULATE_SELECTION_PROBS, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_SELECT_LOCATIONS_DIFF_PERSON_GROUP, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_USE_BLOCK_LEVEL, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_USE_DRIVING_LICENCE, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_USE_EXIT_MAUT, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_USE_FIXED_LOCS_ON_BASE, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_USE_SCHOOLBUS, de.dlr.ivf.tapas.util.parameters.ParamValue.GAMMA_LOCATION_WEIGHT, de.dlr.ivf.tapas.util.parameters.ParamValue.LOC_CHOICE_MOD_CFN4, de.dlr.ivf.tapas.util.parameters.ParamValue.MAX_TIME_DIFFERENCE, de.dlr.ivf.tapas.util.parameters.ParamValue.MAX_TRIES_PERSON, de.dlr.ivf.tapas.util.parameters.ParamValue.MIT_FUEL_COST_PER_KM_COMMUTE, de.dlr.ivf.tapas.util.parameters.ParamValue.MIT_FUEL_COST_PER_KM_COMMUTE_BASE, de.dlr.ivf.tapas.util.parameters.ParamValue.MIT_GASOLINE_COST_PER_KM, de.dlr.ivf.tapas.util.parameters.ParamValue.MIT_GASOLINE_COST_PER_KM_BASE, de.dlr.ivf.tapas.util.parameters.ParamValue.MIT_VARIABLE_COST_PER_KM, de.dlr.ivf.tapas.util.parameters.ParamValue.MIT_VARIABLE_COST_PER_KM_BASE, de.dlr.ivf.tapas.util.parameters.ParamValue.PARKING_FEE_CAT_1, de.dlr.ivf.tapas.util.parameters.ParamValue.PARKING_FEE_CAT_1_BASE, de.dlr.ivf.tapas.util.parameters.ParamValue.PARKING_FEE_CAT_2, de.dlr.ivf.tapas.util.parameters.ParamValue.PARKING_FEE_CAT_2_BASE, de.dlr.ivf.tapas.util.parameters.ParamValue.PARKING_FEE_CAT_3, de.dlr.ivf.tapas.util.parameters.ParamValue.PARKING_FEE_CAT_3_BASE, de.dlr.ivf.tapas.util.parameters.ParamString.PATH_ABS_INPUT, de.dlr.ivf.tapas.util.parameters.ParamString.PATH_ABS_OUTPUT, de.dlr.ivf.tapas.util.parameters.ParamValue.PT_COST_PER_KM, de.dlr.ivf.tapas.util.parameters.ParamValue.PT_COST_PER_KM_BASE, de.dlr.ivf.tapas.util.parameters.ParamValue.RANDOM_SEED_NUMBER, de.dlr.ivf.tapas.util.parameters.ParamValue.REJUVENATE_BY_NB_YEARS, de.dlr.ivf.tapas.util.parameters.ParamValue.TAXI_COST_PER_KM, de.dlr.ivf.tapas.util.parameters.ParamValue.TAXI_COST_PER_KM_BASE, de.dlr.ivf.tapas.util.parameters.ParamValue.TIME_BUDGET_E, de.dlr.ivf.tapas.util.parameters.ParamValue.TIME_BUDGET_F, de.dlr.ivf.tapas.util.parameters.ParamValue.TIME_BUDGET_WP, de.dlr.ivf.tapas.util.parameters.ParamValue.TOLL_CAT_1, de.dlr.ivf.tapas.util.parameters.ParamValue.TOLL_CAT_1_BASE, de.dlr.ivf.tapas.util.parameters.ParamValue.TOLL_CAT_2, de.dlr.ivf.tapas.util.parameters.ParamValue.TOLL_CAT_2_BASE, de.dlr.ivf.tapas.util.parameters.ParamValue.TOLL_CAT_3, de.dlr.ivf.tapas.util.parameters.ParamValue.TOLL_CAT_3_BASE, de.dlr.ivf.tapas.util.parameters.ParamValue.TRAIN_COST_PER_KM, de.dlr.ivf.tapas.util.parameters.ParamValue.TRAIN_COST_PER_KM_BASE, de.dlr.ivf.tapas.util.parameters.ParamString.UTILITY_FUNCTION_CLASS, de.dlr.ivf.tapas.util.parameters.ParamValue.VELOCITY_BIKE, de.dlr.ivf.tapas.util.parameters.ParamValue.VELOCITY_FOOT, de.dlr.ivf.tapas.util.parameters.ParamValue.WEIGHT_WORKING_AT_HOME, and de.dlr.ivf.tapas.util.parameters.ParamValue.WEIGHT_WORKING_CHAINS.
Member Function Documentation
addAdditionalParameter()
void de.dlr.ivf.tapas.tools.fileModifier.persistence.AbstractTPS_ParameterDAO.addAdditionalParameter (String name, String value, String comment)
Implements de.dlr.ivf.tapas.tools.fileModifier.persistence.ITPS_ParameterDAO.
Definition at line 107 of file AbstractTPS_ParameterDAO.java.
References name.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.init().
getFile()
File de.dlr.ivf.tapas.tools.fileModifier.persistence.AbstractTPS_ParameterDAO.getFile ()
Definition at line 113 of file AbstractTPS_ParameterDAO.java.
readParameter()
void de.dlr.ivf.tapas.tools.fileModifier.persistence.AbstractTPS_ParameterDAO.readParameter ()
Implements de.dlr.ivf.tapas.tools.fileModifier.persistence.ITPS_ParameterDAO.
Reimplemented in de.dlr.ivf.tapas.tools.fileModifier.persistence.TPS_ParameterCSVDAO.
Definition at line 121 of file AbstractTPS_ParameterDAO.java.
setFile()
void de.dlr.ivf.tapas.tools.fileModifier.persistence.AbstractTPS_ParameterDAO.setFile (File file)
Definition at line 117 of file AbstractTPS_ParameterDAO.java.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.init(), and de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.load().
writeParameter()
void de.dlr.ivf.tapas.tools.fileModifier.persistence.AbstractTPS_ParameterDAO.writeParameter ()
Implements de.dlr.ivf.tapas.tools.fileModifier.persistence.ITPS_ParameterDAO.
Definition at line 125 of file AbstractTPS_ParameterDAO.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/fileModifier/persistence/AbstractTPS_ParameterDAO.java