TAPAS: de.dlr.ivf.tapas.iteration.TPS_SumoConverter Class Reference
de.dlr.ivf.tapas.iteration.TPS_SumoConverter Class Reference
Public Member Functions
TPS_SumoConverter (TPS_DB_Connector con)
TPS_SumoConverter (File file, String simKey)
TPS_SumoConverter (String filename, String sim_key)
boolean checkMatrixName (String matrixName)
void deleteMatrix (String matrixName)
int[][][] getCounter ()
void setCounter (int[][][] counter)
double[][] getDistance ()
void setDistance (double[][] distance)
double[] getDistribution ()
void setDistribution (double[] distribution)
int getIteration ()
void setIteration (int iteration)
Matrix[] getMatrixArray ()
void setMatrixArray (Matrix[] matrixArray)
void mergeMatrices ()
void mergeMatrixPair (Matrix oldVals, int index)
void prepareNextSimulationIteration (String key)
void readAllParis (String tablename)
void readCSVFile (String fileName) throws IOException
void readIDMap () throws SQLException
double[][] readMatrixFromDB (String matrixName)
MatrixMap readMatrixMap (ParamString matrixName, List< String > matrixNames)
void setPT (boolean isPT)
void setWeight (double weight)
void storeInDB (String matrixName, Matrix mat, int decimalPlaces)
void storeMatrixMap (ParamString matrixMapName, List< String > matrixNames)
void writeTripFile (String outputPath) throws SQLException
Static Public Member Functions
static void readParametersFromDBMaintainLoginInfo (ResultSet rs, TPS_ParameterClass parameterClass) throws SQLException
Private Member Functions
int getTimeSliceIndex (int startTimeMin)
Private Attributes
final TPS_DB_Connector dbManager
double[][] distance = null
double[] distribution = null
Matrix[] matrixArray = null
int[][][] counter = null
final HashMap< Integer, Integer > idToIndex = new HashMap<>()
final HashMap< Integer, Integer > indexToId = new HashMap<>()
Detailed Description
This class provides all the necessary tools to communicate with Sumo. This includes converter routines, to load/store form the database to/from Sumo Generating additional information.
Author
hein_mh
Definition at line 43 of file TPS_SumoConverter.java.
Constructor & Destructor Documentation
TPS_SumoConverter() [1/3]
de.dlr.ivf.tapas.iteration.TPS_SumoConverter.TPS_SumoConverter (TPS_DB_Connector con)
Constructor, if this is called externally with already loaded parameters.
Parameters
con reference to the TPS_DB_Connector to use
Definition at line 92 of file TPS_SumoConverter.java.
TPS_SumoConverter() [2/3]
de.dlr.ivf.tapas.iteration.TPS_SumoConverter.TPS_SumoConverter (File file, String simKey)
This constructor reads all parameters and tries to initialise all data which is available via the TPS_PersistenceManager . If any Exception is thrown it is logged and the application stops.
Parameters
file filename of the parameter file with all run information. This file leads to all other files with e.g. logging, database, etc. information.
simKey key of the simulation
Definition at line 104 of file TPS_SumoConverter.java.
References de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.checkParameters(), de.dlr.ivf.tapas.util.parameters.ParamString.CURRENCY, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_SIMULATION_PARAMETERS, de.dlr.ivf.tapas.util.parameters.CURRENCY.EUR, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.FATAL, de.dlr.ivf.tapas.util.parameters.ParamString.FILE_WORKING_DIRECTORY, de.dlr.ivf.tapas.TPS_Main.getDefaultSimKey(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.loadRuntimeParameters(), de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.util.parameters.ParamString.RUN_IDENTIFIER, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.setString(), and de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.SIM_DIR.
TPS_SumoConverter() [3/3]
de.dlr.ivf.tapas.iteration.TPS_SumoConverter.TPS_SumoConverter (String filename, String sim_key)
The constructor builds a File from the given filename and calls TPS_SumoConverter(File, String).
Parameters
filename filename of the run properties file
sim_key key of the simulation
Definition at line 145 of file TPS_SumoConverter.java.
Member Function Documentation
checkMatrixName()
boolean de.dlr.ivf.tapas.iteration.TPS_SumoConverter.checkMatrixName (String matrixName)
This method checks if the given matrix already exists
Parameters
matrixName the name of the matrix
Returns
true if
Definition at line 183 of file TPS_SumoConverter.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_SCHEMA_CORE, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_MATRICES, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getParameters(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), and de.dlr.ivf.tapas.log.TPS_Logger.log().
Referenced by de.dlr.ivf.tapas.runtime.sumoDaemon.SumoMatrixImporter.writeMatrix().
deleteMatrix()
void de.dlr.ivf.tapas.iteration.TPS_SumoConverter.deleteMatrix (String matrixName)
This method deletes the matrix from the db
Parameters
matrixName the matrix to delete
Definition at line 207 of file TPS_SumoConverter.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_MATRICES, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getParameters(), and de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString().
getCounter()
int [][][] de.dlr.ivf.tapas.iteration.TPS_SumoConverter.getCounter ()
Returns
the counter
Definition at line 217 of file TPS_SumoConverter.java.
getDistance()
double [][] de.dlr.ivf.tapas.iteration.TPS_SumoConverter.getDistance ()
Returns
the distance
Definition at line 231 of file TPS_SumoConverter.java.
getDistribution()
double [] de.dlr.ivf.tapas.iteration.TPS_SumoConverter.getDistribution ()
Returns
the distribution
Definition at line 245 of file TPS_SumoConverter.java.
getIteration()
int de.dlr.ivf.tapas.iteration.TPS_SumoConverter.getIteration ()
Returns
the iteration
Definition at line 259 of file TPS_SumoConverter.java.
getMatrixArray()
Matrix [] de.dlr.ivf.tapas.iteration.TPS_SumoConverter.getMatrixArray ()
Returns
the matrixArray
Definition at line 273 of file TPS_SumoConverter.java.
getTimeSliceIndex()
int de.dlr.ivf.tapas.iteration.TPS_SumoConverter.getTimeSliceIndex (int startTimeMin) private
this method returns the Index of the time slices according to the distribution
Parameters
startTimeMin the start time in minutes after midnight
Returns
the index of the time slice or -1 if nothing is found
Definition at line 290 of file TPS_SumoConverter.java.
mergeMatrices()
void de.dlr.ivf.tapas.iteration.TPS_SumoConverter.mergeMatrices ()
Method to merge the matrices according to the weight
Definition at line 308 of file TPS_SumoConverter.java.
mergeMatrixPair()
void de.dlr.ivf.tapas.iteration.TPS_SumoConverter.mergeMatrixPair (Matrix oldVals, int index)
This method merges the two matrices. The result is stored in "newVals". Every value of the matrix is updated by: val = (old_val+weight*new_val)/(1+weight)
Parameters
oldVals matrix containing the old values
index index of the internal matrix containing the new values and return object
Definition at line 318 of file TPS_SumoConverter.java.
References de.dlr.ivf.tapas.util.Matrix.getNumberOfColums(), de.dlr.ivf.tapas.util.Matrix.getValue(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.INFO, de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), de.dlr.ivf.tapas.log.TPS_Logger.log(), and de.dlr.ivf.tapas.util.Matrix.setValue().
prepareNextSimulationIteration()
void de.dlr.ivf.tapas.iteration.TPS_SumoConverter.prepareNextSimulationIteration (String key)
Definition at line 345 of file TPS_SumoConverter.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.readParameter().
readAllParis()
void de.dlr.ivf.tapas.iteration.TPS_SumoConverter.readAllParis (String tablename)
Definition at line 374 of file TPS_SumoConverter.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), de.dlr.ivf.tapas.log.TPS_Logger.log(), and de.dlr.ivf.tapas.util.Matrix.setValue().
readCSVFile()
void de.dlr.ivf.tapas.iteration.TPS_SumoConverter.readCSVFile (String fileName) throws IOException
This Method reads the csv-file and stores the information in the according matrices. The file has the format:
IV: fromID;toID;travelTime;Speed;Distance;Beeline
PT: fromID;toID;accessTime;Beeline;egressTime;Distance;TravelTime
Parameters
fileName The csv-file.
Definition at line 409 of file TPS_SumoConverter.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.util.Matrix.getValue(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.INFO, de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), de.dlr.ivf.tapas.log.TPS_Logger.log(), and de.dlr.ivf.tapas.util.Matrix.setValue().
readIDMap()
void de.dlr.ivf.tapas.iteration.TPS_SumoConverter.readIDMap () throws SQLException
Definition at line 499 of file TPS_SumoConverter.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_TAZ, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getParameters(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.INFO, de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), and de.dlr.ivf.tapas.log.TPS_Logger.log().
readMatrixFromDB()
double [][] de.dlr.ivf.tapas.iteration.TPS_SumoConverter.readMatrixFromDB (String matrixName)
This method reads the square matrix from the db and returns a 2D-Array
Parameters
matrixName The matrix name in the db
Returns
the 2D-double array of the square matrix
Definition at line 534 of file TPS_SumoConverter.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_MATRICES, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getParameters(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), and de.dlr.ivf.tapas.log.TPS_Logger.log().
readMatrixMap()
MatrixMap de.dlr.ivf.tapas.iteration.TPS_SumoConverter.readMatrixMap (ParamString matrixName, List< String > matrixNames)
Definition at line 571 of file TPS_SumoConverter.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_MATRICES, de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_MATRIXMAPS, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.extractDoubleArray(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.extractIntArray(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.extractStringArray(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.FATAL, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getParameters(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.log.TPS_Logger.log(), and de.dlr.ivf.tapas.util.Matrix.setRawValue().
readParametersFromDBMaintainLoginInfo()
static void de.dlr.ivf.tapas.iteration.TPS_SumoConverter.readParametersFromDBMaintainLoginInfo (ResultSet rs, TPS_ParameterClass parameterClass) throws SQLException static
This method is used to read all parameters but should keep the login information because we need elevated rights to write to db later!
Parameters
rs the ResultSet which contains the simulation parameters
parameterClass parameter container to access the enum values
Exceptions
SQLException The exception could be thrown while reading form the DB
Definition at line 156 of file TPS_SumoConverter.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_PASSWORD, and de.dlr.ivf.tapas.util.parameters.ParamString.DB_USER.
Referenced by de.dlr.ivf.tapas.runtime.sumoDaemon.SumoDaemon.readParameter(), and de.dlr.ivf.tapas.iteration.TPS_VisumConverter.TPS_VisumConverter().
setCounter()
void de.dlr.ivf.tapas.iteration.TPS_SumoConverter.setCounter (int counter[][][])
Parameters
counter the counter to set
Definition at line 224 of file TPS_SumoConverter.java.
setDistance()
void de.dlr.ivf.tapas.iteration.TPS_SumoConverter.setDistance (double distance[][])
Parameters
distance the distance to set
Definition at line 238 of file TPS_SumoConverter.java.
setDistribution()
void de.dlr.ivf.tapas.iteration.TPS_SumoConverter.setDistribution (double[] distribution)
Parameters
distribution the distribution to set
Definition at line 252 of file TPS_SumoConverter.java.
setIteration()
void de.dlr.ivf.tapas.iteration.TPS_SumoConverter.setIteration (int iteration)
Parameters
iteration the iteration to set
Definition at line 266 of file TPS_SumoConverter.java.
setMatrixArray()
void de.dlr.ivf.tapas.iteration.TPS_SumoConverter.setMatrixArray (Matrix[] matrixArray)
Parameters
matrixArray the matrixArray to set
Definition at line 280 of file TPS_SumoConverter.java.
setPT()
void de.dlr.ivf.tapas.iteration.TPS_SumoConverter.setPT (boolean isPT)
Setter if the input is pt or iv
Parameters
isPT the flag
Definition at line 637 of file TPS_SumoConverter.java.
setWeight()
void de.dlr.ivf.tapas.iteration.TPS_SumoConverter.setWeight (double weight)
Sets the weight for merging with the old matrix. val = (old_val + weight*new_val)/(1+weight)
Parameters
weight the weight of the new values
Definition at line 647 of file TPS_SumoConverter.java.
storeInDB()
void de.dlr.ivf.tapas.iteration.TPS_SumoConverter.storeInDB (String matrixName, Matrix mat, int decimalPlaces)
This method stores the given matrix with the given key in the db
Parameters
matrixName the key for this matrix
mat the Matrix to store
decimalPlaces the number of decimal placed, curently only 0 is supported!
Definition at line 658 of file TPS_SumoConverter.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_MATRICES, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getParameters(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.INFO, de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.matrixToSQLArray(), and de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.WARN.
storeMatrixMap()
void de.dlr.ivf.tapas.iteration.TPS_SumoConverter.storeMatrixMap (ParamString matrixMapName, List< String > matrixNames)
Method to store the matrixMap of this set of matrices inthe db
Parameters
matrixMapName
matrixNames
Returns
Definition at line 705 of file TPS_SumoConverter.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_MATRIXMAPS, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.FATAL, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getParameters(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), and de.dlr.ivf.tapas.log.TPS_Logger.log().
writeTripFile()
void de.dlr.ivf.tapas.iteration.TPS_SumoConverter.writeTripFile (String outputPath) throws SQLException
This method exports the trips to Sumo TripFile
Parameters
outputPath the path to store the OD-matrix. usually Trip-Exports
Definition at line 734 of file TPS_SumoConverter.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_REGION, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.FATAL, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getIntValue(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getParameters(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.util.parameters.ParamValue.ITERATION, de.dlr.ivf.tapas.log.TPS_Logger.log(), and de.dlr.ivf.tapas.util.parameters.ParamString.RUN_IDENTIFIER.
Member Data Documentation
counter
int [][][] de.dlr.ivf.tapas.iteration.TPS_SumoConverter.counter = null private
matrix array for the counters
Definition at line 76 of file TPS_SumoConverter.java.
dbManager
final TPS_DB_Connector de.dlr.ivf.tapas.iteration.TPS_SumoConverter.dbManager private
extracted reference to the dbManager
Definition at line 60 of file TPS_SumoConverter.java.
distance
double [][] de.dlr.ivf.tapas.iteration.TPS_SumoConverter.distance = null private
array for the net-distances in m
Definition at line 64 of file TPS_SumoConverter.java.
distribution
double [] de.dlr.ivf.tapas.iteration.TPS_SumoConverter.distribution = null private
time distribution for the matrices
Definition at line 68 of file TPS_SumoConverter.java.
idToIndex
final HashMap<Integer, Integer> de.dlr.ivf.tapas.iteration.TPS_SumoConverter.idToIndex = new HashMap<>() private
hashmap for id conversion
Definition at line 80 of file TPS_SumoConverter.java.
indexToId
final HashMap<Integer, Integer> de.dlr.ivf.tapas.iteration.TPS_SumoConverter.indexToId = new HashMap<>() private
hashmap for id conversion
Definition at line 84 of file TPS_SumoConverter.java.
matrixArray
Matrix [] de.dlr.ivf.tapas.iteration.TPS_SumoConverter.matrixArray = null private
matrix array for the travel times
Definition at line 72 of file TPS_SumoConverter.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/iteration/TPS_SumoConverter.java