TAPAS: de.dlr.ivf.tapas.tools.TPS_CapacityAdjuster Class Reference
de.dlr.ivf.tapas.tools.TPS_CapacityAdjuster Class Reference
Classes
class ValueDistribution
Public Member Functions
void calcLocDemand ()
void calculateGenerationRates ()
void fillOverloadFactors ()
void createNewMinimalLocationTable ()
void loadDBEntries ()
void printNewDemand ()
void updateNewDemand ()
Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_BasicConnectionClass ()
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass)
TPS_BasicConnectionClass (String loginFile)
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass, String loginFile)
boolean checkMatrixName (String matrixName)
TPS_ParameterClass getParameters ()
String readParameter (String simKey, String paramKey)
void storeInDB (String matrixName, double[][] matrix, int decimalPlaces)
Static Public Member Functions
static void main (String[] args)
Static Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
static double[][] array1Dto2D (Integer[] matrixVal)
static double[][] array1Dto2D (int[] matrixVal)
static File getRuntimeFile (boolean forceNewFile)
static File getRuntimeFile (String propertyFile, boolean forceNewFile)
static File getRuntimeFile ()
static File getRuntimeFile (String propertyFile)
static int[][] intArray1Dto2D (int[] matrixVal)
static String matrixToSQLArray (double[][] array, int decimalPlaces)
static StringWriter matrixToStringWriterSQL (double[][] array, int decimalPlaces)
Additional Inherited Members
Protected Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
void finalize ()
Protected Attributes inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_DB_Connector dbCon = null
TPS_ParameterClass parameterClass
Detailed Description
Definition at line 21 of file TPS_CapacityAdjuster.java.
Member Function Documentation
calcLocDemand()
void de.dlr.ivf.tapas.tools.TPS_CapacityAdjuster.calcLocDemand ()
Definition at line 49 of file TPS_CapacityAdjuster.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_CapacityAdjuster.main().
calculateGenerationRates()
void de.dlr.ivf.tapas.tools.TPS_CapacityAdjuster.calculateGenerationRates ()
Definition at line 105 of file TPS_CapacityAdjuster.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery().
Referenced by de.dlr.ivf.tapas.tools.TPS_CapacityAdjuster.loadDBEntries().
createNewMinimalLocationTable()
void de.dlr.ivf.tapas.tools.TPS_CapacityAdjuster.createNewMinimalLocationTable ()
Definition at line 272 of file TPS_CapacityAdjuster.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.execute(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery().
fillOverloadFactors()
void de.dlr.ivf.tapas.tools.TPS_CapacityAdjuster.fillOverloadFactors ()
Definition at line 157 of file TPS_CapacityAdjuster.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery().
Referenced by de.dlr.ivf.tapas.tools.TPS_CapacityAdjuster.loadDBEntries().
loadDBEntries()
void de.dlr.ivf.tapas.tools.TPS_CapacityAdjuster.loadDBEntries ()
Definition at line 333 of file TPS_CapacityAdjuster.java.
References de.dlr.ivf.tapas.tools.TPS_CapacityAdjuster.calculateGenerationRates(), de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), and de.dlr.ivf.tapas.tools.TPS_CapacityAdjuster.fillOverloadFactors().
Referenced by de.dlr.ivf.tapas.tools.TPS_CapacityAdjuster.main().
main()
static void de.dlr.ivf.tapas.tools.TPS_CapacityAdjuster.main (String[] args) static
Definition at line 36 of file TPS_CapacityAdjuster.java.
References de.dlr.ivf.tapas.tools.TPS_CapacityAdjuster.calcLocDemand(), de.dlr.ivf.tapas.tools.TPS_CapacityAdjuster.loadDBEntries(), de.dlr.ivf.tapas.tools.TPS_CapacityAdjuster.printNewDemand(), and de.dlr.ivf.tapas.tools.TPS_CapacityAdjuster.updateNewDemand().
printNewDemand()
void de.dlr.ivf.tapas.tools.TPS_CapacityAdjuster.printNewDemand ()
Definition at line 407 of file TPS_CapacityAdjuster.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_CapacityAdjuster.main().
updateNewDemand()
void de.dlr.ivf.tapas.tools.TPS_CapacityAdjuster.updateNewDemand ()
Definition at line 424 of file TPS_CapacityAdjuster.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeUpdate().
Referenced by de.dlr.ivf.tapas.tools.TPS_CapacityAdjuster.main().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/TPS_CapacityAdjuster.java