TAPAS: de.dlr.ivf.tapas.runtime.client.SimulationControl.ServerOnlineTester.SimulationServerOnlineTestThread Class Reference
de.dlr.ivf.tapas.runtime.client.SimulationControl.ServerOnlineTester.SimulationServerOnlineTestThread Class Reference
Public Member Functions
SimulationServerOnlineTestThread (InetAddress simulationServerIPAddress)
void run ()
Private Member Functions
boolean resetDatabaseEntryOfSimulationServer ()
Private Attributes
final InetAddress simulationServerIPAddress
Detailed Description
This Thread tests if a SimulationServer is online. If the server is available the thread does nothing. If the server is not online the Thread resets the entry in the database to the corresponding simulation process.
Author
mark_ma
Definition at line 652 of file SimulationControl.java.
Constructor & Destructor Documentation
SimulationServerOnlineTestThread()
de.dlr.ivf.tapas.runtime.client.SimulationControl.ServerOnlineTester.SimulationServerOnlineTestThread.SimulationServerOnlineTestThread (InetAddress simulationServerIPAddress)
Constructs the thread an sets the SimulationServer IP Address
Parameters
simulationServerIPAddress IP Address of the SimulationServer to test
Definition at line 664 of file SimulationControl.java.
Member Function Documentation
resetDatabaseEntryOfSimulationServer()
boolean de.dlr.ivf.tapas.runtime.client.SimulationControl.ServerOnlineTester.SimulationServerOnlineTestThread.resetDatabaseEntryOfSimulationServer () private
Returns
true if the server was successfully reseted, false otherwise
Definition at line 672 of file SimulationControl.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.DB_TABLE_SERVERS, de.dlr.ivf.tapas.runtime.client.SimulationControl.dbConnection, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeUpdate(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getParameters(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), and de.dlr.ivf.tapas.runtime.client.SimulationControl.ServerOnlineTester.simulationServerIPAddressCollection.
run()
void de.dlr.ivf.tapas.runtime.client.SimulationControl.ServerOnlineTester.SimulationServerOnlineTestThread.run ()
Definition at line 697 of file SimulationControl.java.
Member Data Documentation
simulationServerIPAddress
final InetAddress de.dlr.ivf.tapas.runtime.client.SimulationControl.ServerOnlineTester.SimulationServerOnlineTestThread.simulationServerIPAddress private
IP Address of the SimulationServer to test
Definition at line 657 of file SimulationControl.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/runtime/client/SimulationControl.java