TAPAS: de.dlr.ivf.tapas.util.parameters.ParamFlagClass Class Reference
de.dlr.ivf.tapas.util.parameters.ParamFlagClass Class Reference
Public Member Functions
void clear (ParamFlag param)
boolean getFlag (ParamFlag param) throws RuntimeException
Boolean getPreset (ParamFlag param)
ParamType getType (ParamFlag param)
boolean isDefined (ParamFlag param)
boolean isFalse (ParamFlag param)
boolean isTrue (ParamFlag param)
void setFlag (ParamFlag param, boolean flag)
Private Attributes
final EnumMap< ParamFlag, MutablePair< ParamType, Boolean > > paramFlags
Detailed Description
Definition at line 15 of file ParamFlagClass.java.
Member Function Documentation
clear()
void de.dlr.ivf.tapas.util.parameters.ParamFlagClass.clear (ParamFlag param)
clears the flag value to the default flag
Definition at line 60 of file ParamFlagClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamFlagClass.getFlag(), and de.dlr.ivf.tapas.util.parameters.ParamFlagClass.setFlag().
getFlag()
boolean de.dlr.ivf.tapas.util.parameters.ParamFlagClass.getFlag (ParamFlag param) throws RuntimeException
Gets the flag of the param parameter
Parameters
param enum parameter of ParamFlag
Returns
bool value of param
Definition at line 70 of file ParamFlagClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamFlagClass.isDefined().
Referenced by de.dlr.ivf.tapas.util.parameters.ParamFlagClass.clear(), and de.dlr.ivf.tapas.util.parameters.ParamFlagClass.getPreset().
getPreset()
Boolean de.dlr.ivf.tapas.util.parameters.ParamFlagClass.getPreset (ParamFlag param)
TODO ugly hack maybe improve
Parameters
param flag parameter enum
Returns
the default boolean value of the enum
Definition at line 81 of file ParamFlagClass.java.
References de.dlr.ivf.tapas.util.parameters.ParamFlagClass.getFlag().
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverterGUI.getDefaultParams().
getType()
ParamType de.dlr.ivf.tapas.util.parameters.ParamFlagClass.getType (ParamFlag param)
Returns
parameter type
Definition at line 92 of file ParamFlagClass.java.
Referenced by de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getType().
isDefined()
boolean de.dlr.ivf.tapas.util.parameters.ParamFlagClass.isDefined (ParamFlag param)
checks if the parameter is not null
Parameters
param parameter to be checked
Returns
true if defined, false otherwise
Definition at line 102 of file ParamFlagClass.java.
Referenced by de.dlr.ivf.tapas.util.parameters.ParamFlagClass.getFlag(), and de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isDefined().
isFalse()
boolean de.dlr.ivf.tapas.util.parameters.ParamFlagClass.isFalse (ParamFlag param)
States if the parameter is defined and false.
Parameters
param Parameter enum ParamFlag
Returns
true if flag is false
Exceptions
RuntimeException This exception is thrown if the constant was not defined
Definition at line 114 of file ParamFlagClass.java.
Referenced by de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isFalse().
isTrue()
boolean de.dlr.ivf.tapas.util.parameters.ParamFlagClass.isTrue (ParamFlag param)
States if the parameter is defined and true.
Parameters
param Parameter enum ParamFlag
Returns
true if flag is true
Exceptions
RuntimeException This exception is thrown if the constant was not defined
Definition at line 128 of file ParamFlagClass.java.
Referenced by de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getSimulationType(), and de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isTrue().
setFlag()
void de.dlr.ivf.tapas.util.parameters.ParamFlagClass.setFlag (ParamFlag param, boolean flag)
Sets the flag of this parameter
Parameters
param enum parameter to be set
flag flag value
Definition at line 140 of file ParamFlagClass.java.
Referenced by de.dlr.ivf.tapas.util.parameters.ParamFlagClass.clear(), and de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.setFlag().
Member Data Documentation
paramFlags
final EnumMap<ParamFlag, MutablePair<ParamType, Boolean> > de.dlr.ivf.tapas.util.parameters.ParamFlagClass.paramFlags private
Definition at line 16 of file ParamFlagClass.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/util/parameters/ParamFlagClass.java