TAPAS: de.dlr.ivf.tapas.constants.TPS_AgeClass Class Reference
de.dlr.ivf.tapas.constants.TPS_AgeClass Class Reference
Classes
enum TPS_AgeCodeType
Public Member Functions
int getMax ()
int getMin ()
TPS_AgeClass (int id, String[] attributes, int min, int max)
void addAgeClassToMap ()
boolean fits (int age)
int getCode (TPS_AgeCodeType type)
Static Public Member Functions
static void clearAgeClassMap ()
static TPS_AgeClass getAgeClass (int age)
static ArrayList< TPS_AgeClass > getConstants (TPS_AgeCodeType type, int code)
Private Attributes
final int max
final int min
final int id
final EnumMap< TPS_AgeCodeType, TPS_InternalConstant< TPS_AgeCodeType > > map
Static Private Attributes
static TPS_AgeClass NON_RELEVANT = null
static final HashMap< Integer, TPS_AgeClass > AGE_CLASS_MAP = new HashMap<>()
Detailed Description
This class represents the age classes constants. There exist two layers of distributions. The first layer should include a continuous amount of intervals e.g. [10,15][16,18] and so on. The second layer consists of one constant, the NON-RELEVANT constant. It includes all ages from 0 to infinite. When there exists no appropriate age class in the first layer, this constant is used as the default age class.
Definition at line 21 of file TPS_AgeClass.java.
Constructor & Destructor Documentation
TPS_AgeClass()
de.dlr.ivf.tapas.constants.TPS_AgeClass.TPS_AgeClass (int id, String[] attributes, int min, int max)
Basic constructor for a TPS_AgeClass
Parameters
id corresponding id from the db
attributes attributes have to have a length of 3*n where each 3-segment is of the form (name, code, type) like ("under 40", "8", "STBA")
Definition at line 64 of file TPS_AgeClass.java.
References de.dlr.ivf.tapas.constants.TPS_AgeClass.id, de.dlr.ivf.tapas.constants.TPS_AgeClass.max, de.dlr.ivf.tapas.constants.TPS_AgeClass.min, de.dlr.ivf.tapas.constants.TPS_AgeClass.NON_RELEVANT, and type.
Member Function Documentation
addAgeClassToMap()
void de.dlr.ivf.tapas.constants.TPS_AgeClass.addAgeClassToMap ()
Adds age class object to static collection of all age classes constants. The objects are accessed by their ids from the db.
Definition at line 129 of file TPS_AgeClass.java.
References de.dlr.ivf.tapas.constants.TPS_AgeClass.AGE_CLASS_MAP.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readAgeClassCodes().
clearAgeClassMap()
static void de.dlr.ivf.tapas.constants.TPS_AgeClass.clearAgeClassMap () static
Empties the global static age class map
Definition at line 94 of file TPS_AgeClass.java.
References de.dlr.ivf.tapas.constants.TPS_AgeClass.AGE_CLASS_MAP.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.clearConstants().
fits()
boolean de.dlr.ivf.tapas.constants.TPS_AgeClass.fits (int age)
Parameters
age should be a non-negative integer
Returns
true if the given age is inside the interval [minimum, maximum], false otherwise
Definition at line 137 of file TPS_AgeClass.java.
References de.dlr.ivf.tapas.constants.TPS_AgeClass.max.
getAgeClass()
static TPS_AgeClass de.dlr.ivf.tapas.constants.TPS_AgeClass.getAgeClass (int age) static
This method searches the corresponding age class to the given age., When there exists no appropriate age class the default age class NON_RELEVANT is returned.
Parameters
age should be a non-negative integer
Returns
corresponding age class
Definition at line 105 of file TPS_AgeClass.java.
References de.dlr.ivf.tapas.constants.TPS_AgeClass.AGE_CLASS_MAP, and de.dlr.ivf.tapas.constants.TPS_AgeClass.NON_RELEVANT.
Referenced by de.dlr.ivf.tapas.person.TPS_Person.setAgeAdaption(), and de.dlr.ivf.tapas.person.TPS_Person.TPS_Person().
getCode()
int de.dlr.ivf.tapas.constants.TPS_AgeClass.getCode (TPS_AgeCodeType type)
Convenience method to obtain the age class code for a given TPS_AgeCodeType
Parameters
type like STBA or PersGroup, see TPS_AgeCodeType
Returns
the corresponding code as int
Definition at line 147 of file TPS_AgeClass.java.
References type.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.createOutput(), de.dlr.ivf.tapas.plan.TPS_Plan.TPS_Plan(), and de.dlr.ivf.tapas.plan.TPS_Plan.writeOutputStream().
getConstants()
static ArrayList<TPS_AgeClass> de.dlr.ivf.tapas.constants.TPS_AgeClass.getConstants (TPS_AgeCodeType type, int code) static
Parameters
type age code type
code code of the internal constant
Returns
constants corresponding to the internal representation of this code
Definition at line 117 of file TPS_AgeClass.java.
References de.dlr.ivf.tapas.constants.TPS_AgeClass.AGE_CLASS_MAP, code, and type.
Referenced by de.dlr.ivf.tapas.constants.TPS_PersonGroup.TPS_PersonGroup().
getMax()
int de.dlr.ivf.tapas.constants.TPS_AgeClass.getMax ()
Definition at line 36 of file TPS_AgeClass.java.
References de.dlr.ivf.tapas.constants.TPS_AgeClass.max.
getMin()
int de.dlr.ivf.tapas.constants.TPS_AgeClass.getMin ()
Definition at line 40 of file TPS_AgeClass.java.
References de.dlr.ivf.tapas.constants.TPS_AgeClass.min.
Member Data Documentation
AGE_CLASS_MAP
final HashMap<Integer, TPS_AgeClass> de.dlr.ivf.tapas.constants.TPS_AgeClass.AGE_CLASS_MAP = new HashMap<>() static private
maps ids from the db to TPS_AgeClass objects constructed from corresponding db data
Definition at line 30 of file TPS_AgeClass.java.
Referenced by de.dlr.ivf.tapas.constants.TPS_AgeClass.addAgeClassToMap(), de.dlr.ivf.tapas.constants.TPS_AgeClass.clearAgeClassMap(), de.dlr.ivf.tapas.constants.TPS_AgeClass.getAgeClass(), and de.dlr.ivf.tapas.constants.TPS_AgeClass.getConstants().
id
final int de.dlr.ivf.tapas.constants.TPS_AgeClass.id private
id obtained from the db
Definition at line 51 of file TPS_AgeClass.java.
Referenced by de.dlr.ivf.tapas.constants.TPS_AgeClass.TPS_AgeClass().
map
final EnumMap<TPS_AgeCodeType, TPS_InternalConstant<TPS_AgeCodeType> > de.dlr.ivf.tapas.constants.TPS_AgeClass.map private
mapping of the TPS_AgeCodeType to the internal representation
Definition at line 55 of file TPS_AgeClass.java.
max
final int de.dlr.ivf.tapas.constants.TPS_AgeClass.max private
Included maximum vale
Definition at line 34 of file TPS_AgeClass.java.
Referenced by de.dlr.ivf.tapas.constants.TPS_AgeClass.fits(), de.dlr.ivf.tapas.constants.TPS_AgeClass.getMax(), and de.dlr.ivf.tapas.constants.TPS_AgeClass.TPS_AgeClass().
min
final int de.dlr.ivf.tapas.constants.TPS_AgeClass.min private
Included minimum value
Definition at line 47 of file TPS_AgeClass.java.
Referenced by de.dlr.ivf.tapas.constants.TPS_AgeClass.getMin(), and de.dlr.ivf.tapas.constants.TPS_AgeClass.TPS_AgeClass().
NON_RELEVANT
TPS_AgeClass de.dlr.ivf.tapas.constants.TPS_AgeClass.NON_RELEVANT = null static private
Static constant which represents all ages [0, infinite[
Definition at line 26 of file TPS_AgeClass.java.
Referenced by de.dlr.ivf.tapas.constants.TPS_AgeClass.getAgeClass(), and de.dlr.ivf.tapas.constants.TPS_AgeClass.TPS_AgeClass().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/constants/TPS_AgeClass.java