TAPAS: de.dlr.ivf.tapas.runtime.util.WindowsProcessHandler Class Reference
de.dlr.ivf.tapas.runtime.util.WindowsProcessHandler Class Reference
Static Public Member Functions
static boolean findProcess (int pid, String name)
static int killProcess (int pid)
Detailed Description
This class provides basic methods to find and kill processes on a Windows Operating System.
Author
mark_ma
Definition at line 25 of file WindowsProcessHandler.java.
Member Function Documentation
findProcess()
static boolean de.dlr.ivf.tapas.runtime.util.WindowsProcessHandler.findProcess (int pid, String name) static
This method finds the system process by process id and name.
Parameters
pid process id
name process name
Returns
true if process was found, false otherwise
Definition at line 34 of file WindowsProcessHandler.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.log.TPS_Logger.log(), and name.
killProcess()
static int de.dlr.ivf.tapas.runtime.util.WindowsProcessHandler.killProcess (int pid) static
This method kills the process corresponding to the given pid
Parameters
pid process id
Returns
true if process was killed, false otherwise
Definition at line 99 of file WindowsProcessHandler.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), de.dlr.ivf.tapas.log.TPS_Logger.log(), and de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.WARN.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/runtime/util/WindowsProcessHandler.java