TAPAS: de.dlr.ivf.tapas.mode.TPS_ExtMode Class Reference
de.dlr.ivf.tapas.mode.TPS_ExtMode Class Reference
Public Member Functions
TPS_ExtMode (TPS_Mode primary, TPS_Mode secondary)
int getMCTCode ()
String getName ()
boolean isBikeUsed ()
boolean isCarUsed ()
boolean isFix ()
Public Attributes
TPS_Mode primary
TPS_Mode secondary
Static Public Attributes
final static TPS_ExtMode simpleWalk = new TPS_ExtMode(TPS_Mode.get(ModeType.WALK), null)
final static TPS_ExtMode simplePT = new TPS_ExtMode(TPS_Mode.get(ModeType.PT), null)
final static TPS_ExtMode simpleMIT = new TPS_ExtMode(TPS_Mode.get(ModeType.MIT), null)
Detailed Description
Definition at line 14 of file TPS_ExtMode.java.
Constructor & Destructor Documentation
TPS_ExtMode()
de.dlr.ivf.tapas.mode.TPS_ExtMode.TPS_ExtMode (TPS_Mode primary, TPS_Mode secondary)
Definition at line 22 of file TPS_ExtMode.java.
References de.dlr.ivf.tapas.mode.TPS_ExtMode.primary, and de.dlr.ivf.tapas.mode.TPS_ExtMode.secondary.
Member Function Documentation
getMCTCode()
int de.dlr.ivf.tapas.mode.TPS_ExtMode.getMCTCode ()
Definition at line 28 of file TPS_ExtMode.java.
References de.dlr.ivf.tapas.mode.TPS_Mode.getCode(), de.dlr.ivf.tapas.mode.TPS_Mode.TPS_ModeCodeType.MCT, de.dlr.ivf.tapas.mode.TPS_ExtMode.primary, and de.dlr.ivf.tapas.mode.TPS_ExtMode.secondary.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.batchStoreTrips(), de.dlr.ivf.tapas.plan.TPS_Plan.createOutput(), and de.dlr.ivf.tapas.plan.TPS_Plan.writeOutputStream().
getName()
String de.dlr.ivf.tapas.mode.TPS_ExtMode.getName ()
Definition at line 33 of file TPS_ExtMode.java.
References de.dlr.ivf.tapas.mode.TPS_Mode.getName(), name, de.dlr.ivf.tapas.mode.TPS_ExtMode.primary, and de.dlr.ivf.tapas.mode.TPS_ExtMode.secondary.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes(), and de.dlr.ivf.tapas.plan.TPS_PlannedTrip.toString().
isBikeUsed()
boolean de.dlr.ivf.tapas.mode.TPS_ExtMode.isBikeUsed ()
Definition at line 41 of file TPS_ExtMode.java.
References de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.BIKE, de.dlr.ivf.tapas.mode.TPS_Mode.isType(), de.dlr.ivf.tapas.mode.TPS_ExtMode.primary, and de.dlr.ivf.tapas.mode.TPS_ExtMode.secondary.
Referenced by de.dlr.ivf.tapas.scheme.TPS_TourPart.isBikeUsed(), and de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes().
isCarUsed()
boolean de.dlr.ivf.tapas.mode.TPS_ExtMode.isCarUsed ()
Definition at line 49 of file TPS_ExtMode.java.
References de.dlr.ivf.tapas.mode.TPS_Mode.isType(), de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.MIT, de.dlr.ivf.tapas.mode.TPS_ExtMode.primary, and de.dlr.ivf.tapas.mode.TPS_ExtMode.secondary.
Referenced by de.dlr.ivf.tapas.scheme.TPS_TourPart.isCarUsed(), de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes(), and de.dlr.ivf.tapas.scheme.TPS_TourPart.setUsedMode().
isFix()
boolean de.dlr.ivf.tapas.mode.TPS_ExtMode.isFix ()
Definition at line 56 of file TPS_ExtMode.java.
References de.dlr.ivf.tapas.mode.TPS_Mode.isFix, de.dlr.ivf.tapas.mode.TPS_ExtMode.primary, and de.dlr.ivf.tapas.mode.TPS_ExtMode.secondary.
Referenced by de.dlr.ivf.tapas.scheme.TPS_TourPart.isFixedModeUsed(), and de.dlr.ivf.tapas.mode.TPS_ModeSet.selectMode().
Member Data Documentation
primary
TPS_Mode de.dlr.ivf.tapas.mode.TPS_ExtMode.primary
Definition at line 18 of file TPS_ExtMode.java.
Referenced by de.dlr.ivf.tapas.mode.TPS_ExtMode.getMCTCode(), de.dlr.ivf.tapas.mode.TPS_ExtMode.getName(), de.dlr.ivf.tapas.mode.TPS_ExtMode.isBikeUsed(), de.dlr.ivf.tapas.mode.TPS_ExtMode.isCarUsed(), de.dlr.ivf.tapas.mode.TPS_ExtMode.isFix(), and de.dlr.ivf.tapas.mode.TPS_ExtMode.TPS_ExtMode().
secondary
TPS_Mode de.dlr.ivf.tapas.mode.TPS_ExtMode.secondary
Definition at line 19 of file TPS_ExtMode.java.
Referenced by de.dlr.ivf.tapas.mode.TPS_ExtMode.getMCTCode(), de.dlr.ivf.tapas.mode.TPS_ExtMode.getName(), de.dlr.ivf.tapas.mode.TPS_ExtMode.isBikeUsed(), de.dlr.ivf.tapas.mode.TPS_ExtMode.isCarUsed(), de.dlr.ivf.tapas.mode.TPS_ExtMode.isFix(), and de.dlr.ivf.tapas.mode.TPS_ExtMode.TPS_ExtMode().
simpleMIT
final static TPS_ExtMode de.dlr.ivf.tapas.mode.TPS_ExtMode.simpleMIT = new TPS_ExtMode(TPS_Mode.get(ModeType.MIT), null) static
Definition at line 17 of file TPS_ExtMode.java.
Referenced by de.dlr.ivf.tapas.scheme.TPS_TourPart.setCar().
simplePT
final static TPS_ExtMode de.dlr.ivf.tapas.mode.TPS_ExtMode.simplePT = new TPS_ExtMode(TPS_Mode.get(ModeType.PT), null) static
Definition at line 16 of file TPS_ExtMode.java.
simpleWalk
final static TPS_ExtMode de.dlr.ivf.tapas.mode.TPS_ExtMode.simpleWalk = new TPS_ExtMode(TPS_Mode.get(ModeType.WALK), null) static
Definition at line 15 of file TPS_ExtMode.java.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/mode/TPS_ExtMode.java