TAPAS: de.dlr.ivf.tapas.loc.TPS_Coordinate Class Reference
de.dlr.ivf.tapas.loc.TPS_Coordinate Class Reference
Public Member Functions
TPS_Coordinate (double x, double y)
TPS_Coordinate copy ()
double getEuclidianDistance (TPS_Coordinate b)
double getValue (int index)
double[] getValues ()
void setValues (double[] values)
void setValue (int index, double value)
void setValues (double value1, double value2)
Private Member Functions
void updateEuclidianCoordinates ()
Detailed Description
This class implements a Coordinate by extending an array value distribution.
Author
mark_ma
Definition at line 20 of file TPS_Coordinate.java.
Constructor & Destructor Documentation
TPS_Coordinate()
de.dlr.ivf.tapas.loc.TPS_Coordinate.TPS_Coordinate (double x, double y)
Calls super constructor with size and sets both values for the x and y coordinate
Parameters
x x-coordinate value
y y-coordinate value
Definition at line 32 of file TPS_Coordinate.java.
Member Function Documentation
copy()
TPS_Coordinate de.dlr.ivf.tapas.loc.TPS_Coordinate.copy ()
Returns a copy of the coordinate
Returns
copy the coordinate
Definition at line 43 of file TPS_Coordinate.java.
getEuclidianDistance()
double de.dlr.ivf.tapas.loc.TPS_Coordinate.getEuclidianDistance (TPS_Coordinate b)
Definition at line 47 of file TPS_Coordinate.java.
Referenced by de.dlr.ivf.tapas.util.TPS_Geometrics.getDistance().
getValue()
double de.dlr.ivf.tapas.loc.TPS_Coordinate.getValue (int index)
Getter for the coordinates.
Parameters
index the index 0= x 1= y
Returns
the x or y value
Definition at line 61 of file TPS_Coordinate.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.batchStoreTrips(), de.dlr.ivf.tapas.util.TPS_Geometrics.convertToCartesian(), de.dlr.ivf.tapas.util.TPS_Geometrics.isSameLocation(), and de.dlr.ivf.tapas.loc.TPS_Block.setCenter().
getValues()
double [] de.dlr.ivf.tapas.loc.TPS_Coordinate.getValues ()
Getter for the coordinate-array
Returns
the 2 element array of the coordinate
Definition at line 70 of file TPS_Coordinate.java.
setValue()
void de.dlr.ivf.tapas.loc.TPS_Coordinate.setValue (int index, double value)
Setter for a specific coordinate. index 0= x = lon index 1= y = lat
Parameters
index
value
Definition at line 93 of file TPS_Coordinate.java.
setValues() [1/2]
void de.dlr.ivf.tapas.loc.TPS_Coordinate.setValues (double value1, double value2)
Setter for both coordinates
Parameters
value1 x value
value2 y value
Definition at line 104 of file TPS_Coordinate.java.
setValues() [2/2]
void de.dlr.ivf.tapas.loc.TPS_Coordinate.setValues (double[] values)
Setter for both variables a a 2-elem-array
Parameters
values
Definition at line 79 of file TPS_Coordinate.java.
Referenced by de.dlr.ivf.tapas.loc.TPS_Block.setCenter(), de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.setCenter(), and de.dlr.ivf.tapas.loc.TPS_Location.TPS_Location().
updateEuclidianCoordinates()
void de.dlr.ivf.tapas.loc.TPS_Coordinate.updateEuclidianCoordinates () private
Definition at line 110 of file TPS_Coordinate.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/loc/TPS_Coordinate.java