TAPAS: de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone Class Reference
de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone Class Reference
Classes
class ScenarioTypeValues
class TPS_TAZData
class TypedWeightedLocationDistribution
Public Member Functions
TPS_TrafficAnalysisZone (int id)
void addLocation (TPS_Location loc)
boolean allowsActivity (TPS_ActivityConstant actCode)
int compareTo (TPS_TrafficAnalysisZone o)
boolean containsBlock (int blockId)
double getActivityWeightSum (TPS_ActivityConstant actCode)
TPS_SettlementSystem getBbrType ()
void setBbrType (TPS_SettlementSystem bbrType)
TPS_Block getBlock (int blockId)
TPS_Block getBlock ()
TPS_Coordinate getCenter ()
TPS_Coordinate getCoordinate ()
TPS_TAZData getData ()
int getExternalId ()
void setExternalId (int externalId)
double getParkingFee (SimulationType scenario)
TPS_Region getRegion ()
void setRegion (TPS_Region region)
double getScore ()
void setScore (double score)
int getScoreCat ()
void setScoreCat (int scoreCat)
ScenarioTypeValues getSimulationTypeValues (SimulationType type)
int getTAZId ()
double getTollFee (SimulationType scenario)
TPS_TrafficAnalysisZone getTrafficAnalysisZone ()
boolean hasBlock ()
boolean hasData ()
boolean hasParkingFee (SimulationType scenario)
boolean hasToll (SimulationType scenario)
void initFeesTolls (boolean hasBasisToll, int basisTollType, boolean hasBasisParkingFee, int basisParkingType, boolean hasScenToll, int scenTollType, boolean hasScenParkingFee, int scenParkingType, boolean isCarSharingBase, boolean isCarSharingScen, TPS_ParameterClass parameterClass)
boolean isCarSharingService (SimulationType scenario)
boolean isPNR ()
void setPNR (boolean isPNR)
boolean isRestricted ()
void setRestricted (boolean isRestricted)
ArrayList< TPS_Location > selectActivityLocations (TPS_ActivityConstant actCode, int number)
void setCenter (double x, double y)
String toString ()
void updateActivityOccupancy (TPS_ActivityConstant actCode, double oldWeight, double weight)
Public Attributes
HashMap< TPS_ActivityConstant, TypedWeightedLocationDistribution > locationsByActivity = new HashMap<>()
Static Public Attributes
static ArrayListValuedHashMap< TPS_ActivityConstant, TPS_LocationConstant > ACTIVITY2LOCATIONS_MAP = new ArrayListValuedHashMap<>()
Mapping between corresponding codes.
static ArrayListValuedHashMap< TPS_LocationConstant, TPS_ActivityConstant > LOCATION2ACTIVITIES_MAP = new ArrayListValuedHashMap<>()
Private Member Functions
void setCostParkingPerHour (SimulationType type, TPS_ParameterClass parameterClass)
void setCostToll (SimulationType type, TPS_ParameterClass parameterClass)
Private Attributes
TPS_SettlementSystem bbrType
community type, used during choice of locations
final SortedMap< Integer, TPS_Block > blocks
Collection with all blocks of this traffic analysis zone.
TPS_Coordinate center
Coordinate of the center point of this traffic analysis zone.
final int id
id of the traffic analysis zone
TPS_Region region
Reference to the region.
double score = 3
score value for the quality of pt access and service in the traffic analysis zone
int scoreCat = 3
Category of the score for the quality of pt in the traffic analysis zone.
int externalId = -1
reference to external id code
final Map< SimulationType, ScenarioTypeValues > simulationTypeValues
Map which stores the values for the corresponding SimulationType.
TPS_TAZData data
Local variable for the TAZData (locations etc.)
boolean isRestricted = false
boolean isPNR = false
Detailed Description
Definition at line 25 of file TPS_TrafficAnalysisZone.java.
Constructor & Destructor Documentation
TPS_TrafficAnalysisZone()
de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.TPS_TrafficAnalysisZone (int id)
Constructor
Parameters
id The id of this TAZ
Definition at line 64 of file TPS_TrafficAnalysisZone.java.
References de.dlr.ivf.tapas.util.parameters.SimulationType.BASE, and de.dlr.ivf.tapas.util.parameters.SimulationType.SCENARIO.
Member Function Documentation
addLocation()
void de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.addLocation (TPS_Location loc)
This method adds the given location
Parameters
loc The location to add
Definition at line 77 of file TPS_TrafficAnalysisZone.java.
References de.dlr.ivf.tapas.loc.TPS_Location.getLocType(), and de.dlr.ivf.tapas.loc.TPS_Location.hasData().
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readRegion().
allowsActivity()
boolean de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.allowsActivity (TPS_ActivityConstant actCode)
Returns whether this activity can be performed within this TAZ (whether at least one location that supports this activity is included in this TAZ)
Parameters
actCode The code of the activity it is asked for
Returns
Whether at least one location allows the activity to be performed
Definition at line 109 of file TPS_TrafficAnalysisZone.java.
Referenced by de.dlr.ivf.tapas.loc.TPS_MultipleTAZRepresentant.generateLocationRepr(), and de.dlr.ivf.tapas.loc.TPS_Location.updateOccupancy().
compareTo()
int de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.compareTo (TPS_TrafficAnalysisZone o)
Definition at line 114 of file TPS_TrafficAnalysisZone.java.
References de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.id.
containsBlock()
boolean de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.containsBlock (int blockId)
Returns whether the named block is contained
Parameters
blockId The id of the block
Returns
true if the block is contained, false otherwise
Definition at line 124 of file TPS_TrafficAnalysisZone.java.
Referenced by de.dlr.ivf.tapas.loc.TPS_Region.getBlock().
getActivityWeightSum()
double de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.getActivityWeightSum (TPS_ActivityConstant actCode)
Returns the weight sum of locations that support the given activity
Parameters
actCode The code of the activity
Returns
The sum of weights of the locations that support this activity
Definition at line 134 of file TPS_TrafficAnalysisZone.java.
getBbrType()
TPS_SettlementSystem de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.getBbrType ()
Returns the community / region type of the traffic analysis zone according to BBR
Returns
The BBR (community) type
Definition at line 146 of file TPS_TrafficAnalysisZone.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.batchStoreTrips(), de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixedBS.getDistributionSet(), de.dlr.ivf.tapas.mode.TPS_MassTransportMode.getTravelTime(), de.dlr.ivf.tapas.loc.TPS_SelectLocationWeightBased.selectLocationFromChoiceSet(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.selectLocationFromChoiceSet(), de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes(), and de.dlr.ivf.tapas.plan.TPS_Plan.TPS_Plan().
getBlock() [1/2]
TPS_Block de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.getBlock ()
TODO check
Returns
null
Implements de.dlr.ivf.tapas.loc.Locatable.
Definition at line 182 of file TPS_TrafficAnalysisZone.java.
getBlock() [2/2]
TPS_Block de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.getBlock (int blockId)
Returns the block corresponding to the given blockId. If the block doesn't exist it is created.
Parameters
blockId The id of the block to return
Returns
block with this blockId
Definition at line 166 of file TPS_TrafficAnalysisZone.java.
References de.dlr.ivf.tapas.loc.TPS_Block.setTrafficAnalysisZone().
Referenced by de.dlr.ivf.tapas.loc.TPS_Region.getBlock(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readRegion().
getCenter()
TPS_Coordinate de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.getCenter ()
Returns the coordinate of the center of this TAZ
Returns
The center coordinate
Definition at line 191 of file TPS_TrafficAnalysisZone.java.
getCoordinate()
TPS_Coordinate de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.getCoordinate ()
Returns the coordinate of the center of this TAZ
Returns
The center coordinate
Implements de.dlr.ivf.tapas.loc.Locatable.
Definition at line 200 of file TPS_TrafficAnalysisZone.java.
getData()
TPS_TAZData de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.getData ()
Returns the data attached to this zone.
Returns
This TAZ's data
Definition at line 209 of file TPS_TrafficAnalysisZone.java.
getExternalId()
int de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.getExternalId ()
Returns the external id of this TAZ.
Returns
the external id or -1, if no external id is known
Definition at line 218 of file TPS_TrafficAnalysisZone.java.
getParkingFee()
double de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.getParkingFee (SimulationType scenario)
Returns the parking fee for an hour for the traffic analysis zone in the scenario or base situation as specified
Parameters
scenario
Returns
Parking fee
Definition at line 238 of file TPS_TrafficAnalysisZone.java.
getRegion()
TPS_Region de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.getRegion ()
Returns the region the traffic analysis zone lies within
Returns
reference to the region
Definition at line 247 of file TPS_TrafficAnalysisZone.java.
getScore()
double de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.getScore ()
Returns the score indicating the PT quality in the traffic analysis zone
Returns
score
Definition at line 265 of file TPS_TrafficAnalysisZone.java.
getScoreCat()
int de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.getScoreCat ()
Returns the category of the score indicating the pt quality in the traffic analysis zone
Returns
score category
Definition at line 284 of file TPS_TrafficAnalysisZone.java.
Referenced by de.dlr.ivf.tapas.mode.TPS_MassTransportMode.getScore().
getSimulationTypeValues()
ScenarioTypeValues de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.getSimulationTypeValues (SimulationType type)
Returns the scenario specific values for the scenario given
Parameters
type scenario the values should be given for
Returns
set of scenario values
Definition at line 303 of file TPS_TrafficAnalysisZone.java.
References type.
Referenced by de.dlr.ivf.tapas.mode.TPS_IndividualTransportMode.getDistance(), de.dlr.ivf.tapas.mode.TPS_IndividualTransportMode.getTravelTime(), de.dlr.ivf.tapas.mode.TPS_MassTransportMode.getTravelTime(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readTAZInfos().
getTAZId()
int de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.getTAZId ()
Returns the ID of this TAZ
Returns
This TAZ's ID
Implements de.dlr.ivf.tapas.loc.Locatable.
Definition at line 313 of file TPS_TrafficAnalysisZone.java.
Referenced by de.dlr.ivf.tapas.loc.TPS_Region.addTrafficAnalysisZone(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.batchStoreTrips(), de.dlr.ivf.tapas.mode.TPS_IndividualTransportMode.getDistance(), de.dlr.ivf.tapas.mode.TPS_MassTransportMode.getDistance(), de.dlr.ivf.tapas.mode.TPS_NonMotorisedMode.getDistance(), de.dlr.ivf.tapas.util.TPS_Geometrics.getDistance(), de.dlr.ivf.tapas.mode.TPS_MassTransportMode.getTravelTime(), de.dlr.ivf.tapas.mode.TPS_NonMotorisedMode.getTravelTime(), and de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes().
getTollFee()
double de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.getTollFee (SimulationType scenario)
Returns the toll fee in EURO per entrance for the traffic analysis zone in the specified scenario
Parameters
scenario scenario to get the fee for
Returns
toll fee in EURO
Definition at line 324 of file TPS_TrafficAnalysisZone.java.
getTrafficAnalysisZone()
TPS_TrafficAnalysisZone de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.getTrafficAnalysisZone ()
Returns this TAZ
Returns
This TAZ
Implements de.dlr.ivf.tapas.loc.Locatable.
Definition at line 334 of file TPS_TrafficAnalysisZone.java.
hasBlock()
boolean de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.hasBlock ()
TODO check
Returns
false
Implements de.dlr.ivf.tapas.loc.Locatable.
Definition at line 344 of file TPS_TrafficAnalysisZone.java.
hasData()
boolean de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.hasData ()
Returns whether this TAZ has data
Returns
Whether this TAZ has data
Definition at line 353 of file TPS_TrafficAnalysisZone.java.
hasParkingFee()
boolean de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.hasParkingFee (SimulationType scenario)
Returns if a parking fee has to be payed in the scenario specified
Parameters
scenario scenario the fee should be determined for
Returns
true if parking fee is applicable, false else
Definition at line 363 of file TPS_TrafficAnalysisZone.java.
hasToll()
boolean de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.hasToll (SimulationType scenario)
Returns if a toll fee has to be payed in the scenario specified
Parameters
scenario The scenario the fee should be determined for
Returns
true if toll fee is applicable, false else
Definition at line 382 of file TPS_TrafficAnalysisZone.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.batchStoreTrips(), and de.dlr.ivf.tapas.mode.TPS_ModeSet.selectMode0().
initFeesTolls()
void de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.initFeesTolls (boolean hasBasisToll, int basisTollType, boolean hasBasisParkingFee, int basisParkingType, boolean hasScenToll, int scenTollType, boolean hasScenParkingFee, int scenParkingType, boolean isCarSharingBase, boolean isCarSharingScen, TPS_ParameterClass parameterClass)
Constructor of the traffic analysis zone with information concerning the costs associated with a visit (toll, parking fee, bbr region type)
Parameters
hasBasisToll flag if the traffic analysis zone has a toll fee in the base scenario
basisTollType type of toll fee in the base scenario
hasBasisParkingFee flag if the traffic analysis zone has a parking fee in the base scenario
basisParkingType type of parking fee in the base scenario
hasScenToll flag if the traffic analysis zone has a toll fee in the scenario
scenTollType type of toll fee in the scenario
hasScenParkingFee flag if the traffic analysis zone has a parking fee in the scenario
scenParkingType type of parking fee in the scenario
parameterClass parameter class reference
Definition at line 400 of file TPS_TrafficAnalysisZone.java.
References de.dlr.ivf.tapas.util.parameters.SimulationType.BASE, and de.dlr.ivf.tapas.util.parameters.SimulationType.SCENARIO.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readRegion().
isCarSharingService()
boolean de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.isCarSharingService (SimulationType scenario)
Returns the parking fee for an hour for the traffic analysis zone in the scenario or base situation as specified
Parameters
scenario
Returns
Parking fee
Definition at line 439 of file TPS_TrafficAnalysisZone.java.
isPNR()
boolean de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.isPNR ()
Definition at line 443 of file TPS_TrafficAnalysisZone.java.
isRestricted()
boolean de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.isRestricted ()
Definition at line 451 of file TPS_TrafficAnalysisZone.java.
selectActivityLocations()
ArrayList<TPS_Location> de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.selectActivityLocations (TPS_ActivityConstant actCode, int number)
Chooses the given number of locations that support te given activity
Parameters
actCode The code of the activity
number The number of locations to select
Returns
The list of the selected locations
Definition at line 466 of file TPS_TrafficAnalysisZone.java.
Referenced by de.dlr.ivf.tapas.loc.TPS_MultipleTAZRepresentant.generateLocationRepr().
setBbrType()
void de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.setBbrType (TPS_SettlementSystem bbrType)
Sets community / region type according to the BBR
Parameters
bbrType
Definition at line 155 of file TPS_TrafficAnalysisZone.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readRegion().
setCenter()
void de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.setCenter (double x, double y)
This method sets the center coordinate to the given value TODO: check whether this could be done within the constructor
Parameters
x
y
Definition at line 480 of file TPS_TrafficAnalysisZone.java.
References de.dlr.ivf.tapas.loc.TPS_Coordinate.setValues().
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readRegion().
setCostParkingPerHour()
void de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.setCostParkingPerHour (SimulationType type, TPS_ParameterClass parameterClass) private
Calculates the hourly fee in Euro for parking in the TAZ according to the scenario and the parking type in the TAZ
Parameters
type type indicating if the fees should be calculated for the scenario or the base situation
Definition at line 494 of file TPS_TrafficAnalysisZone.java.
References de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.feeParking, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getDoubleValue(), de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.hasParkingFee, de.dlr.ivf.tapas.util.parameters.ParamValue.PARKING_FEE_CAT_1, de.dlr.ivf.tapas.util.parameters.ParamValue.PARKING_FEE_CAT_1_BASE, de.dlr.ivf.tapas.util.parameters.ParamValue.PARKING_FEE_CAT_2, de.dlr.ivf.tapas.util.parameters.ParamValue.PARKING_FEE_CAT_2_BASE, de.dlr.ivf.tapas.util.parameters.ParamValue.PARKING_FEE_CAT_3, de.dlr.ivf.tapas.util.parameters.ParamValue.PARKING_FEE_CAT_3_BASE, de.dlr.ivf.tapas.util.parameters.SimulationType.SCENARIO, type, and de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.typeParking.
setCostToll()
void de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.setCostToll (SimulationType type, TPS_ParameterClass parameterClass) private
Calculates the hourly fee in for entering in the tvz according to the scenario and the toll type in the traffic analysis zone; toll is assumed to be cordon and undifferentiated by car type and person type
Parameters
type type indicating if the fees should be calculated for the scenario or the base situation
parameterClass parameter class reference
Definition at line 525 of file TPS_TrafficAnalysisZone.java.
References de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.feeToll, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getDoubleValue(), de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.hasToll, de.dlr.ivf.tapas.util.parameters.SimulationType.SCENARIO, de.dlr.ivf.tapas.util.parameters.ParamValue.TOLL_CAT_1, de.dlr.ivf.tapas.util.parameters.ParamValue.TOLL_CAT_1_BASE, de.dlr.ivf.tapas.util.parameters.ParamValue.TOLL_CAT_2, de.dlr.ivf.tapas.util.parameters.ParamValue.TOLL_CAT_2_BASE, de.dlr.ivf.tapas.util.parameters.ParamValue.TOLL_CAT_3, de.dlr.ivf.tapas.util.parameters.ParamValue.TOLL_CAT_3_BASE, type, and de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ScenarioTypeValues.typeToll.
setExternalId()
void de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.setExternalId (int externalId)
Sets the external id number of this TAZ.
Parameters
externalId The external id number. Set to -1, if unknown.
Definition at line 227 of file TPS_TrafficAnalysisZone.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readRegion().
setPNR()
void de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.setPNR (boolean isPNR)
Definition at line 447 of file TPS_TrafficAnalysisZone.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readRegion().
setRegion()
void de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.setRegion (TPS_Region region)
Sets the reference of the region
Parameters
region The region this TAZ belongs to
Definition at line 256 of file TPS_TrafficAnalysisZone.java.
Referenced by de.dlr.ivf.tapas.loc.TPS_Region.addTrafficAnalysisZone().
setRestricted()
void de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.setRestricted (boolean isRestricted)
Definition at line 455 of file TPS_TrafficAnalysisZone.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readRegion().
setScore()
void de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.setScore (double score)
Sets the score for the pt quality and access in the traffic analysis zone
Parameters
score The (PT) score of this TAZ
Definition at line 274 of file TPS_TrafficAnalysisZone.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readRegion().
setScoreCat()
void de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.setScoreCat (int scoreCat)
Sets the category of the score for the pt quality and access in the traffic analysis zone
Parameters
scoreCat The score category of this TAZ
Definition at line 293 of file TPS_TrafficAnalysisZone.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readRegion().
toString()
String de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.toString ()
Returns this object's string representation
See also
java.lang.Object::toString()
Definition at line 553 of file TPS_TrafficAnalysisZone.java.
References de.dlr.ivf.tapas.util.parameters.SimulationType.BASE, de.dlr.ivf.tapas.constants.TPS_SettlementSystem.getId(), and de.dlr.ivf.tapas.util.parameters.SimulationType.SCENARIO.
updateActivityOccupancy()
void de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.updateActivityOccupancy (TPS_ActivityConstant actCode, double oldWeight, double weight)
Updates the weights (occupancies) of the activity within this TAZ
Parameters
actCode The code of the activity
oldWeight The earlier weight of the location that is responsible for this update
weight The new weight of the location that is responsible for this update
Definition at line 566 of file TPS_TrafficAnalysisZone.java.
Referenced by de.dlr.ivf.tapas.loc.TPS_Location.updateOccupancy().
Member Data Documentation
ACTIVITY2LOCATIONS_MAP
ArrayListValuedHashMap<TPS_ActivityConstant, TPS_LocationConstant> de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.ACTIVITY2LOCATIONS_MAP = new ArrayListValuedHashMap<>() static
Mapping between corresponding codes.
Definition at line 28 of file TPS_TrafficAnalysisZone.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.clearConstants(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readActivity2LocationCodes(), and de.dlr.ivf.tapas.loc.TPS_Region.selectLocation().
bbrType
TPS_SettlementSystem de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.bbrType private
community type, used during choice of locations
Definition at line 37 of file TPS_TrafficAnalysisZone.java.
blocks
final SortedMap<Integer, TPS_Block> de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.blocks private
Collection with all blocks of this traffic analysis zone.
Definition at line 39 of file TPS_TrafficAnalysisZone.java.
center
TPS_Coordinate de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.center private
Coordinate of the center point of this traffic analysis zone.
Definition at line 41 of file TPS_TrafficAnalysisZone.java.
data
TPS_TAZData de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.data private
Local variable for the TAZData (locations etc.)
Definition at line 55 of file TPS_TrafficAnalysisZone.java.
externalId
int de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.externalId = -1 private
reference to external id code
Definition at line 51 of file TPS_TrafficAnalysisZone.java.
id
final int de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.id private
id of the traffic analysis zone
Definition at line 43 of file TPS_TrafficAnalysisZone.java.
Referenced by de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.compareTo().
isPNR
boolean de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.isPNR = false private
Definition at line 57 of file TPS_TrafficAnalysisZone.java.
isRestricted
boolean de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.isRestricted = false private
Definition at line 56 of file TPS_TrafficAnalysisZone.java.
Referenced by de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.getModeLogSum(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessMode.getTravelTime(), de.dlr.ivf.tapas.loc.TPS_SelectWithSingleAccessMode.getTravelTime(), and de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes().
LOCATION2ACTIVITIES_MAP
ArrayListValuedHashMap<TPS_LocationConstant, TPS_ActivityConstant> de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.LOCATION2ACTIVITIES_MAP = new ArrayListValuedHashMap<>() static
Definition at line 31 of file TPS_TrafficAnalysisZone.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.clearConstants(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readActivity2LocationCodes(), and de.dlr.ivf.tapas.loc.TPS_Location.TPS_Location().
locationsByActivity
HashMap<TPS_ActivityConstant, TypedWeightedLocationDistribution> de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.locationsByActivity = new HashMap<>()
Definition at line 35 of file TPS_TrafficAnalysisZone.java.
Referenced by de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.TPS_TAZData.generateLocationRepr().
region
TPS_Region de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.region private
Reference to the region.
Definition at line 45 of file TPS_TrafficAnalysisZone.java.
score
double de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.score = 3 private
score value for the quality of pt access and service in the traffic analysis zone
Definition at line 47 of file TPS_TrafficAnalysisZone.java.
scoreCat
int de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.scoreCat = 3 private
Category of the score for the quality of pt in the traffic analysis zone.
Definition at line 49 of file TPS_TrafficAnalysisZone.java.
simulationTypeValues
final Map<SimulationType, ScenarioTypeValues> de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.simulationTypeValues private
Map which stores the values for the corresponding SimulationType.
Definition at line 53 of file TPS_TrafficAnalysisZone.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/loc/TPS_TrafficAnalysisZone.java