TAPAS: de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.AnalyzerTransferable Class Reference
de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.AnalyzerTransferable Class Reference
Public Member Functions
AnalyzerTransferable (AnalyzerBase analyzer)
AnalyzerBase getTransferData (DataFlavor flavor)
DataFlavor[] getTransferDataFlavors ()
boolean isDataFlavorSupported (DataFlavor flavor)
Static Public Attributes
static final DataFlavor ANALYZER_DATA_FLAVOR = new DataFlavor(AnalyzerBase.class, "Analyzer")
Private Attributes
final AnalyzerBase analyzer
Detailed Description
Definition at line 618 of file TUMControlGeneral.java.
Constructor & Destructor Documentation
AnalyzerTransferable()
de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.AnalyzerTransferable.AnalyzerTransferable (AnalyzerBase analyzer)
Definition at line 623 of file TUMControlGeneral.java.
Member Function Documentation
getTransferData()
AnalyzerBase de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.AnalyzerTransferable.getTransferData (DataFlavor flavor)
Definition at line 628 of file TUMControlGeneral.java.
getTransferDataFlavors()
DataFlavor [] de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.AnalyzerTransferable.getTransferDataFlavors ()
Definition at line 633 of file TUMControlGeneral.java.
isDataFlavorSupported()
boolean de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.AnalyzerTransferable.isDataFlavorSupported (DataFlavor flavor)
Definition at line 638 of file TUMControlGeneral.java.
Member Data Documentation
analyzer
final AnalyzerBase de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.AnalyzerTransferable.analyzer private
Definition at line 621 of file TUMControlGeneral.java.
ANALYZER_DATA_FLAVOR
final DataFlavor de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.AnalyzerTransferable.ANALYZER_DATA_FLAVOR = new DataFlavor(AnalyzerBase.class, "Analyzer") static
Definition at line 619 of file TUMControlGeneral.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.AnalyzerTreeTransferHandler.canImport(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.NodeListTransferHandler.canImport(), de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.AnalyzerTreeTransferHandler.importData(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.TUMControlGeneral.NodeListTransferHandler.importData().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/tum/regionanalyzer/general/TUMControlGeneral.java