TAPAS: de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverter Class Reference
de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverter Class Reference
Public Member Functions
TPS_ParameterFileConverter ()
void load (File file, TPS_ParameterClass parameterClass)
void save (File file, TPS_ParameterClass parameterClass, String... parameters)
void scan (File oldPath, File newPath, TPS_ParameterClass parameterClass)
Static Public Member Functions
static void main (String[] args)
Private Member Functions
void convert (File oldFile, File newPath, TPS_ParameterClass parameterClass)
Static Private Member Functions
static JFileChooser createDialog (File path, String title, int type, boolean multisel)
static JFileChooser createDialog (File path, String title, int type, boolean multisel, boolean save, javax.swing.filechooser.FileFilter... fileFilter)
Private Attributes
final Map< String, Enum<?> > map
Detailed Description
This method was designed to convert old Text-Tapas configs to the new config format. Since a lot of new parameters are introduces this method is obsolete.
Definition at line 28 of file TPS_ParameterFileConverter.java.
Constructor & Destructor Documentation
TPS_ParameterFileConverter()
de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverter.TPS_ParameterFileConverter ()
Default constructor, which initializes the string/enum-map
Definition at line 41 of file TPS_ParameterFileConverter.java.
References de.dlr.ivf.tapas.util.parameters.ParamValue.AVERAGE_DISTANCE_PT_STOP, de.dlr.ivf.tapas.util.parameters.ParamString.DB_DBNAME, de.dlr.ivf.tapas.util.parameters.ParamValue.DEFAULT_VOT, de.dlr.ivf.tapas.util.parameters.ParamValue.FINANCE_BUDGET_E, de.dlr.ivf.tapas.util.parameters.ParamValue.FINANCE_BUDGET_F, de.dlr.ivf.tapas.util.parameters.ParamValue.FINANCE_BUDGET_WP, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_CHECK_BUDGET_CONSTRAINTS, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_INFLUENCE_RANDOM_NUMBER, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_INTRA_INFOS_MATRIX, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_LOCATION_POCKET_COSTS, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_REJUVENATE_RETIREE, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_RUN_SZENARIO, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_SCHEMES_MANIPULATE_BY_WORK_AT_HOME, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_SCHEMES_MANIPULATE_BY_WORKINGCHAINS, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_SCHEMES_MANIPULATE_SELECTION_PROBS, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_SELECT_LOCATIONS_DIFF_PERSON_GROUP, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_USE_BLOCK_LEVEL, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_USE_DRIVING_LICENCE, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_USE_EXIT_MAUT, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_USE_FIXED_LOCS_ON_BASE, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_USE_SCHOOLBUS, de.dlr.ivf.tapas.util.parameters.ParamValue.GAMMA_LOCATION_WEIGHT, de.dlr.ivf.tapas.util.parameters.ParamValue.LOC_CHOICE_MOD_CFN4, de.dlr.ivf.tapas.util.parameters.ParamValue.MAX_TIME_DIFFERENCE, de.dlr.ivf.tapas.util.parameters.ParamValue.MAX_TRIES_PERSON, de.dlr.ivf.tapas.util.parameters.ParamValue.MIT_FUEL_COST_PER_KM_COMMUTE, de.dlr.ivf.tapas.util.parameters.ParamValue.MIT_FUEL_COST_PER_KM_COMMUTE_BASE, de.dlr.ivf.tapas.util.parameters.ParamValue.MIT_GASOLINE_COST_PER_KM, de.dlr.ivf.tapas.util.parameters.ParamValue.MIT_GASOLINE_COST_PER_KM_BASE, de.dlr.ivf.tapas.util.parameters.ParamValue.MIT_VARIABLE_COST_PER_KM, de.dlr.ivf.tapas.util.parameters.ParamValue.MIT_VARIABLE_COST_PER_KM_BASE, de.dlr.ivf.tapas.util.parameters.ParamValue.PARKING_FEE_CAT_1, de.dlr.ivf.tapas.util.parameters.ParamValue.PARKING_FEE_CAT_1_BASE, de.dlr.ivf.tapas.util.parameters.ParamValue.PARKING_FEE_CAT_2, de.dlr.ivf.tapas.util.parameters.ParamValue.PARKING_FEE_CAT_2_BASE, de.dlr.ivf.tapas.util.parameters.ParamValue.PARKING_FEE_CAT_3, de.dlr.ivf.tapas.util.parameters.ParamValue.PARKING_FEE_CAT_3_BASE, de.dlr.ivf.tapas.util.parameters.ParamString.PATH_ABS_INPUT, de.dlr.ivf.tapas.util.parameters.ParamString.PATH_ABS_OUTPUT, de.dlr.ivf.tapas.util.parameters.ParamValue.PT_COST_PER_KM, de.dlr.ivf.tapas.util.parameters.ParamValue.PT_COST_PER_KM_BASE, de.dlr.ivf.tapas.util.parameters.ParamValue.RANDOM_SEED_NUMBER, de.dlr.ivf.tapas.util.parameters.ParamValue.REJUVENATE_BY_NB_YEARS, de.dlr.ivf.tapas.util.parameters.ParamValue.TAXI_COST_PER_KM, de.dlr.ivf.tapas.util.parameters.ParamValue.TAXI_COST_PER_KM_BASE, de.dlr.ivf.tapas.util.parameters.ParamValue.TIME_BUDGET_E, de.dlr.ivf.tapas.util.parameters.ParamValue.TIME_BUDGET_F, de.dlr.ivf.tapas.util.parameters.ParamValue.TIME_BUDGET_WP, de.dlr.ivf.tapas.util.parameters.ParamValue.TOLL_CAT_1, de.dlr.ivf.tapas.util.parameters.ParamValue.TOLL_CAT_1_BASE, de.dlr.ivf.tapas.util.parameters.ParamValue.TOLL_CAT_2, de.dlr.ivf.tapas.util.parameters.ParamValue.TOLL_CAT_2_BASE, de.dlr.ivf.tapas.util.parameters.ParamValue.TOLL_CAT_3, de.dlr.ivf.tapas.util.parameters.ParamValue.TOLL_CAT_3_BASE, de.dlr.ivf.tapas.util.parameters.ParamValue.TRAIN_COST_PER_KM, de.dlr.ivf.tapas.util.parameters.ParamValue.TRAIN_COST_PER_KM_BASE, de.dlr.ivf.tapas.util.parameters.ParamString.UTILITY_FUNCTION_CLASS, de.dlr.ivf.tapas.util.parameters.ParamValue.VELOCITY_BIKE, de.dlr.ivf.tapas.util.parameters.ParamValue.VELOCITY_FOOT, de.dlr.ivf.tapas.util.parameters.ParamValue.WEIGHT_WORKING_AT_HOME, and de.dlr.ivf.tapas.util.parameters.ParamValue.WEIGHT_WORKING_CHAINS.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverter.main().
Member Function Documentation
convert()
void de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverter.convert (File oldFile, File newPath, TPS_ParameterClass parameterClass) private
File converter (obsolete?!)
Parameters
oldFile
newPath
Definition at line 236 of file TPS_ParameterFileConverter.java.
References de.dlr.ivf.tapas.util.parameters.ParamString.CLASS_DATA_SCOURCE_ORIGIN, de.dlr.ivf.tapas.util.parameters.ParamString.FILE_DATABASE_PROPERTIES, de.dlr.ivf.tapas.util.parameters.ParamString.FILE_LOGGING_PROPERTIES, de.dlr.ivf.tapas.util.parameters.ParamString.FILE_PARAMETER_PROPERTIES, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getDoubleValue(), de.dlr.ivf.tapas.util.parameters.ParamType.getIndex(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getType(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isDefined(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isTrue(), and name.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverter.main(), and de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverter.scan().
createDialog() [1/2]
static JFileChooser de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverter.createDialog (File path, String title, int type, boolean multisel) static private
Definition at line 161 of file TPS_ParameterFileConverter.java.
References type.
createDialog() [2/2]
static JFileChooser de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverter.createDialog (File path, String title, int type, boolean multisel, boolean save, javax.swing.filechooser.FileFilter... fileFilter) static private
Definition at line 172 of file TPS_ParameterFileConverter.java.
References de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverter.save(), and type.
load()
void de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverter.load (File file, TPS_ParameterClass parameterClass)
Definition at line 391 of file TPS_ParameterFileConverter.java.
References de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.setFlag(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.setString(), and de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.setValue().
main()
static void de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverter.main (String[] args) static
Main routine for this converter
Parameters
args
Definition at line 195 of file TPS_ParameterFileConverter.java.
References de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverter.convert(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.loadSingleParameterFile(), and de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverter.TPS_ParameterFileConverter().
save()
void de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverter.save (File file, TPS_ParameterClass parameterClass, String... parameters)
Definition at line 433 of file TPS_ParameterFileConverter.java.
References de.dlr.ivf.tapas.util.parameters.ParamType.DB, de.dlr.ivf.tapas.util.parameters.ParamType.DEFAULT, de.dlr.ivf.tapas.util.parameters.ParamType.FILE, de.dlr.ivf.tapas.util.parameters.ParamString.FILE_DATABASE_PROPERTIES, de.dlr.ivf.tapas.util.parameters.ParamString.FILE_LOGGING_PROPERTIES, de.dlr.ivf.tapas.util.parameters.ParamString.FILE_PARAMETER_PROPERTIES, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getDoubleValue(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getString(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getType(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isDefined(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isTrue(), de.dlr.ivf.tapas.util.parameters.ParamType.LOG, name, and de.dlr.ivf.tapas.util.parameters.ParamType.RUN.
Referenced by de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverter.createDialog().
scan()
void de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverter.scan (File oldPath, File newPath, TPS_ParameterClass parameterClass)
Scan for txt files in a directory or checks if given file is a txt file
Parameters
oldPath
newPath
Definition at line 564 of file TPS_ParameterFileConverter.java.
References de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverter.convert().
Member Data Documentation
map
final Map<String, Enum<?> > de.dlr.ivf.tapas.tools.fileModifier.TPS_ParameterFileConverter.map private
Mapping for String to enums
Definition at line 33 of file TPS_ParameterFileConverter.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/fileModifier/TPS_ParameterFileConverter.java