TAPAS: de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDatasetDBFetcher Class Reference
de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDatasetDBFetcher Class Reference
Static Public Member Functions
static void main (String[] args) throws ClassNotFoundException, IOException
static JFreeChart makeQSChart (String refKey, String modelKey) throws ClassNotFoundException, IOException
Static Private Member Functions
static ArrayList< QualityChartData > mergeData (HashMap< CategoryCombination, QualityChartData > reference, HashMap< CategoryCombination, Double > model, double cntModel, double cntReference)
Detailed Description
This class handles the input from the database (the tables calibration_results and reference) to produce a JFreeChart with the QualityChartFactory.
Author
boec_pa
Definition at line 31 of file QualityChartDatasetDBFetcher.java.
Member Function Documentation
main()
static void de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDatasetDBFetcher.main (String[] args) throws ClassNotFoundException, IOException static
For testing purposes only
Exceptions
IOException
ClassNotFoundException
Definition at line 38 of file QualityChartDatasetDBFetcher.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDatasetDBFetcher.makeQSChart().
makeQSChart()
static JFreeChart de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDatasetDBFetcher.makeQSChart (String refKey, String modelKey) throws ClassNotFoundException, IOException static
Parameters
refKey the key in the reference table (like mid2008)
modelKey the key of the model run in the calibration_results table.
Exceptions
ClassNotFoundException
IOException
Definition at line 58 of file QualityChartDatasetDBFetcher.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartFactory.createChart(), de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.DistanceCategoryDefault, de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader.getAbsoluteSplit(), de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.ReferenceDBReader.getCntTrips(), de.dlr.ivf.tapas.analyzer.tum.results.CalibrationResultsReader.getCntTrips(), de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.ReferenceDBReader.getMoDcValues(), de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDatasetDBFetcher.mergeData(), and de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.Mode.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDatasetDBFetcher.main().
mergeData()
static ArrayList<QualityChartData> de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDatasetDBFetcher.mergeData (HashMap< CategoryCombination, QualityChartData > reference, HashMap< CategoryCombination, Double > model, double cntModel, double cntReference) static private
Takes reference and model and merge them into a list of data points for the QualityChartFactory. Also scales the model to fit the reference.
Parameters
reference
model
cntModel number of trips in the model
cntReference number of trips in the reference
Returns
Definition at line 90 of file QualityChartDatasetDBFetcher.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartData.getLabel(), de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartData.getQuality(), and de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartData.getReference().
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDatasetDBFetcher.makeQSChart().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/runtime/client/Graphics/QualityChart/QualityChartDatasetDBFetcher.java