TAPAS: de.dlr.ivf.tapas.constants.TPS_Distance Class Reference
de.dlr.ivf.tapas.constants.TPS_Distance Class Reference
Classes
enum TPS_DistanceCodeType
Public Member Functions
TPS_Distance (int id, String[] attributes, int max)
void addDistanceToMap ()
int getCode (TPS_DistanceCodeType type)
Static Public Member Functions
static void clearDistanceMap ()
static int getCode (TPS_DistanceCodeType type, double distance)
Private Attributes
final int max
final int id
final EnumMap< TPS_DistanceCodeType, TPS_InternalConstant< TPS_DistanceCodeType > > map
Static Private Attributes
static final HashMap< Integer, TPS_Distance > DISTANCE_MAP = new HashMap<>()
static final TreeMap< Integer, Integer > MAX_VALUES = new TreeMap<>()
Detailed Description
This class represents the constants for the distances. They are all stored in one distribution to retrieve the best fitting distance constant to each distant value.
Definition at line 19 of file TPS_Distance.java.
Constructor & Destructor Documentation
TPS_Distance()
de.dlr.ivf.tapas.constants.TPS_Distance.TPS_Distance (int id, String[] attributes, int max)
Basic constructor for a TPS_Distance object
Parameters
id corresponding to the db entry
attributes list of triples like (name, code, type)
max maximum value of the distance constant category
Definition at line 54 of file TPS_Distance.java.
References de.dlr.ivf.tapas.constants.TPS_Distance.id, de.dlr.ivf.tapas.constants.TPS_Distance.max, and type.
Member Function Documentation
addDistanceToMap()
void de.dlr.ivf.tapas.constants.TPS_Distance.addDistanceToMap ()
Add distance instance to the global static distance map Additionally add (max_val, id)-key-value-pair to the MAX_VALUES map for better searchability of the DISTANCE_MAP
Definition at line 103 of file TPS_Distance.java.
References de.dlr.ivf.tapas.constants.TPS_Distance.DISTANCE_MAP.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readDistanceCodes().
clearDistanceMap()
static void de.dlr.ivf.tapas.constants.TPS_Distance.clearDistanceMap () static
Empties the global static distance map and the max values map
Definition at line 81 of file TPS_Distance.java.
References de.dlr.ivf.tapas.constants.TPS_Distance.DISTANCE_MAP, and de.dlr.ivf.tapas.constants.TPS_Distance.MAX_VALUES.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.clearConstants().
getCode() [1/2]
int de.dlr.ivf.tapas.constants.TPS_Distance.getCode (TPS_DistanceCodeType type)
Returns the distance code for this object for a given distance code type
Parameters
type distance code type like MCT or VOT
Returns
returns the distance code
Definition at line 114 of file TPS_Distance.java.
References type.
getCode() [2/2]
static int de.dlr.ivf.tapas.constants.TPS_Distance.getCode (TPS_DistanceCodeType type, double distance) static
This method searches the distance value which is the next greater (or equal) than the given value. To this constant the code is returned.
Parameters
type distance type (enum)
distance determines the corresponding distance category, e.g. distance=2.3km corresponds to category 'under 5km'
Returns
code corresponding to the given enumeration type and the distance
Definition at line 95 of file TPS_Distance.java.
References de.dlr.ivf.tapas.constants.TPS_Distance.DISTANCE_MAP, de.dlr.ivf.tapas.constants.TPS_Distance.MAX_VALUES, and type.
Referenced by de.dlr.ivf.tapas.mode.TPS_ModeSet.getModeDistribution(), and de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.getModeLogSum().
Member Data Documentation
DISTANCE_MAP
final HashMap<Integer, TPS_Distance> de.dlr.ivf.tapas.constants.TPS_Distance.DISTANCE_MAP = new HashMap<>() static private
DISTANCE_MAP maps ids to TPS_Distance objects containing (name, code, type)
Definition at line 24 of file TPS_Distance.java.
Referenced by de.dlr.ivf.tapas.constants.TPS_Distance.addDistanceToMap(), de.dlr.ivf.tapas.constants.TPS_Distance.clearDistanceMap(), and de.dlr.ivf.tapas.constants.TPS_Distance.getCode().
id
final int de.dlr.ivf.tapas.constants.TPS_Distance.id private
id corresponding to the db entry
Definition at line 38 of file TPS_Distance.java.
Referenced by de.dlr.ivf.tapas.constants.TPS_Distance.TPS_Distance().
map
final EnumMap<TPS_DistanceCodeType, TPS_InternalConstant<TPS_DistanceCodeType> > de.dlr.ivf.tapas.constants.TPS_Distance.map private
mapping of distance code types to (name, code, type) triples Example: VOT -> (under 10k, 2, VOT) MCT -> (under 7k, 7000, MCT)
Definition at line 45 of file TPS_Distance.java.
max
final int de.dlr.ivf.tapas.constants.TPS_Distance.max private
maximum value of a distance category
Definition at line 34 of file TPS_Distance.java.
Referenced by de.dlr.ivf.tapas.constants.TPS_Distance.TPS_Distance().
MAX_VALUES
final TreeMap<Integer, Integer> de.dlr.ivf.tapas.constants.TPS_Distance.MAX_VALUES = new TreeMap<>() static private
MAX_VALUES maps max values of distance to ids (=keys in DISTANCE_MAP)
Definition at line 28 of file TPS_Distance.java.
Referenced by de.dlr.ivf.tapas.constants.TPS_Distance.clearDistanceMap(), and de.dlr.ivf.tapas.constants.TPS_Distance.getCode().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/constants/TPS_Distance.java