TAPAS: de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.StringListModel Class Reference
de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.StringListModel Class Reference
Public Member Functions
StringListModel (List< String > list)
void addListDataListener (ListDataListener l)
void changed ()
String getElementAt (int index)
int getSize ()
void removeListDataListener (ListDataListener l)
Private Attributes
final List< ListDataListener > listeners = new ArrayList<>()
final List< String > list
Detailed Description
Definition at line 372 of file DBSimulationChooserPanel.java.
Constructor & Destructor Documentation
StringListModel()
de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.StringListModel.StringListModel (List< String > list)
Definition at line 377 of file DBSimulationChooserPanel.java.
References de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.StringListModel.list.
Member Function Documentation
addListDataListener()
void de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.StringListModel.addListDataListener (ListDataListener l)
Definition at line 382 of file DBSimulationChooserPanel.java.
References de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.StringListModel.listeners.
changed()
void de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.StringListModel.changed ()
Definition at line 386 of file DBSimulationChooserPanel.java.
References de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.StringListModel.list, and de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.StringListModel.listeners.
Referenced by de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.createContents().
getElementAt()
String de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.StringListModel.getElementAt (int index)
Definition at line 391 of file DBSimulationChooserPanel.java.
References de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.StringListModel.list.
getSize()
int de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.StringListModel.getSize ()
Definition at line 395 of file DBSimulationChooserPanel.java.
References de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.StringListModel.list.
removeListDataListener()
void de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.StringListModel.removeListDataListener (ListDataListener l)
Definition at line 399 of file DBSimulationChooserPanel.java.
References de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.StringListModel.listeners.
Member Data Documentation
list
final List<String> de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.StringListModel.list private
Definition at line 375 of file DBSimulationChooserPanel.java.
Referenced by de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.StringListModel.changed(), de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.StringListModel.getElementAt(), de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.StringListModel.getSize(), and de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.StringListModel.StringListModel().
listeners
final List<ListDataListener> de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.StringListModel.listeners = new ArrayList<>() private
Definition at line 374 of file DBSimulationChooserPanel.java.
Referenced by de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.StringListModel.addListDataListener(), de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.StringListModel.changed(), and de.dlr.ivf.tapas.analyzer.gui.DBSimulationChooserPanel.StringListModel.removeListDataListener().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/gui/DBSimulationChooserPanel.java