TAPAS: de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader Class Reference
de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader Class Reference
Classes
class DBTripFetcher
class TripIterator
Public Member Functions
DBTripReader (String simulation, String hhkey, String schema, String region, TPS_SettlementSystemType settlementType, Set< Integer > tazFilter, TPS_DB_Connector connection, StyledDocument console) throws SQLException, ClassNotFoundException, IOException
DBTripReader (String simulation, StyledDocument console, TPS_SettlementSystemType settlementType, Set< Integer > tazFilter, TPS_DB_Connector connection) throws SQLException, ClassNotFoundException, IOException
void addPropertyChangeListener (PropertyChangeListener listener)
void cancel ()
void close ()
Iterator< TapasTrip > getIterator ()
int getProgress ()
String getSource ()
long getTotal ()
boolean isCancelled ()
void removePropertyChangeListener (PropertyChangeListener listener)
Static Public Member Functions
static void main (String[] args) throws SQLException, ClassNotFoundException, IOException
Public Attributes
String region = ""
String description = ""
Protected Attributes
long cntTrips = 0
Private Member Functions
void init (String simulation, String hhkey, String schema, String region, TPS_SettlementSystemType settlementType, Set< Integer > tazFilter, TPS_DB_Connector connection, StyledDocument console) throws SQLException, ClassNotFoundException, IOException
Private Attributes
final int QUEUE_SIZE = 100000
final int FETCH_SIZE = 10000
StyledDocument console
long totalEstimate
long totaltripcount
boolean isCancelled = false
final PropertyChangeSupport pcs = new PropertyChangeSupport(this)
TPS_SettlementSystemType settlementType
TripIterator tripIterator
Static Private Attributes
static final TapasTrip POISON_INSTANCE = new TapasTrip()
Detailed Description
This class provides a way to export TapasTrips directly from the database without using a file export first.
It implements the Iterable for easy use. The main method provides a minimal example of usage.
As this class creates temporary tables and sequences on the database, it is recommended to use the close() method.
Author
boec_pa
Definition at line 43 of file DBTripReader.java.
Constructor & Destructor Documentation
DBTripReader() [1/2]
de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripReader (String simulation, String hhkey, String schema, String region, TPS_SettlementSystemType settlementType, Set< Integer > tazFilter, TPS_DB_Connector connection, StyledDocument console) throws SQLException, ClassNotFoundException, IOException
Parameters
settlementType may be null
tazFilter may be null. The taz ids to accept.
Exceptions
SQLException if SQL commands could not be executed properly. Check connection!
ClassNotFoundException
IOException if the connection file could not be found or read.
Definition at line 79 of file DBTripReader.java.
References de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.console, de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.init(), de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.region, and de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.settlementType.
Referenced by de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.main().
DBTripReader() [2/2]
de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripReader (String simulation, StyledDocument console, TPS_SettlementSystemType settlementType, Set< Integer > tazFilter, TPS_DB_Connector connection) throws SQLException, ClassNotFoundException, IOException
Definition at line 83 of file DBTripReader.java.
References de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.console, de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.init(), and de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.settlementType.
Member Function Documentation
addPropertyChangeListener()
void de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.addPropertyChangeListener (PropertyChangeListener listener)
Definition at line 144 of file DBTripReader.java.
Referenced by de.dlr.ivf.tapas.tools.TUM.IntegratedTUM.doInBackground().
cancel()
void de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.cancel ()
Definition at line 149 of file DBTripReader.java.
References de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.close().
Referenced by de.dlr.ivf.tapas.tools.TUM.IntegratedTUM.done().
close()
void de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.close ()
Implements de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripReader.
Definition at line 155 of file DBTripReader.java.
References de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.TripIterator.close(), and de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.tripIterator.
Referenced by de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.cancel(), de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.doInBackground(), de.dlr.ivf.tapas.tools.TUM.IntegratedTUM.doInBackground(), de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.main(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.main().
getIterator()
Iterator<TapasTrip> de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.getIterator ()
Implements de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripReader.
Definition at line 160 of file DBTripReader.java.
References de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.tripIterator.
Referenced by de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.doInBackground(), de.dlr.ivf.tapas.tools.TUM.IntegratedTUM.doInBackground(), de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.main(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.main().
getProgress()
int de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.getProgress ()
Returns an estimated progress between 0 and 100 . 0 means, the trip table is still build. 100 does not guaranty that the process is finished.
Implements de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripReader.
Definition at line 168 of file DBTripReader.java.
References de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.cntTrips, and de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.totalEstimate.
Referenced by de.dlr.ivf.tapas.analyzer.tum.results.StandaloneRegionAnalyzer.doInBackground().
getSource()
String de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.getSource ()
Returns
a human readable description of the source of the trips.
Implements de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripReader.
Definition at line 191 of file DBTripReader.java.
References de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.TripIterator.getSource(), and de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.tripIterator.
getTotal()
long de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.getTotal ()
Returns
(estimated) number of elements to be read.
Implements de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripReader.
Definition at line 195 of file DBTripReader.java.
References de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.totaltripcount.
Referenced by de.dlr.ivf.tapas.tools.TUM.IntegratedTUM.doInBackground().
init()
void de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.init (String simulation, String hhkey, String schema, String region, TPS_SettlementSystemType settlementType, Set< Integer > tazFilter, TPS_DB_Connector connection, StyledDocument console) throws SQLException, ClassNotFoundException, IOException private
Definition at line 200 of file DBTripReader.java.
References de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.console, de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.region, de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.settlementType, de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.totalEstimate, and de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.tripIterator.
Referenced by de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripReader().
isCancelled()
boolean de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.isCancelled ()
Definition at line 230 of file DBTripReader.java.
References de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.isCancelled.
main()
static void de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.main (String[] args) throws SQLException, ClassNotFoundException, IOException static
Definition at line 111 of file DBTripReader.java.
References de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.close(), de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripReader(), de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.getIterator(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.loadRuntimeParameters(), and de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.region.
removePropertyChangeListener()
void de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.removePropertyChangeListener (PropertyChangeListener listener)
Definition at line 236 of file DBTripReader.java.
Member Data Documentation
cntTrips
long de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.cntTrips = 0 protected
Definition at line 60 of file DBTripReader.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.getProgress(), de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.TripIterator.hasNext(), and de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.TripIterator.next().
console
StyledDocument de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.console private
Every output goes here
Definition at line 64 of file DBTripReader.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.createTripTable(), de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripReader(), and de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.init().
description
String de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.description = ""
Definition at line 59 of file DBTripReader.java.
Referenced by de.dlr.ivf.tapas.tools.TUM.IntegratedTUM.doInBackground().
FETCH_SIZE
final int de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.FETCH_SIZE = 10000 private
The number of rows fetched from the database at once. A large number reduces overhead of Java-DB communication.
Definition at line 57 of file DBTripReader.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.run().
isCancelled
boolean de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.isCancelled = false private
Definition at line 67 of file DBTripReader.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.isCancelled(), and de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.run().
pcs
final PropertyChangeSupport de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.pcs = new PropertyChangeSupport(this) private
Definition at line 68 of file DBTripReader.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.run().
POISON_INSTANCE
final TapasTrip de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.POISON_INSTANCE = new TapasTrip() static private
Needed to mark the end of the queue.
Definition at line 48 of file DBTripReader.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.TripIterator.hasNext(), and de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.run().
QUEUE_SIZE
final int de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.QUEUE_SIZE = 100000 private
This is the maximal number of TapasTrips that are prefetched from the database. Memory size is the only restriction here.
Definition at line 53 of file DBTripReader.java.
region
String de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.region = ""
Definition at line 58 of file DBTripReader.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripReader(), de.dlr.ivf.tapas.tools.TUM.IntegratedTUM.doInBackground(), de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.init(), de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.main(), and de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.TripIterator.TripIterator().
settlementType
TPS_SettlementSystemType de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.settlementType private
Definition at line 69 of file DBTripReader.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripReader(), de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.getTripFromResult(), and de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.init().
totalEstimate
long de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.totalEstimate private
Definition at line 65 of file DBTripReader.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.getProgress(), and de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.init().
totaltripcount
long de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.totaltripcount private
Definition at line 66 of file DBTripReader.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.DBTripFetcher.createTripTable(), and de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.getTotal().
tripIterator
TripIterator de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.tripIterator private
Definition at line 70 of file DBTripReader.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.close(), de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.getIterator(), de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.getSource(), and de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader.init().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/tum/databaseConnector/DBTripReader.java