TAPAS: de.dlr.ivf.tapas.person.TPS_Worker Class Reference
de.dlr.ivf.tapas.person.TPS_Worker Class Reference
Public Member Functions
TPS_Worker (TPS_PersistenceManager pm)
Exception call ()
TPS_ParameterClass getParameters ()
Static Public Member Functions
static List< Integer[]> getAllLists (List< Integer > elements, int lengthOfVector)
Private Member Functions
void assignCarToPlan (TPS_Plan plan)
void createPersonPlans (TPS_PlanEnvironment pe, TPS_Car carDummy)
void processHousehold (TPS_Household hh)
Private Attributes
TPS_PersistenceManager PM = null
Detailed Description
A TPS_Worker proceeds all available households and searches plans for all household members. after a plan is found the location occupancies are updated and the trips are stored.
It is possible to create more workers. Then they are synchronised over all available households so no household is proceeded twice.
Author
mark_ma
Definition at line 43 of file TPS_Worker.java.
Constructor & Destructor Documentation
TPS_Worker()
de.dlr.ivf.tapas.person.TPS_Worker.TPS_Worker (TPS_PersistenceManager pm)
Standard constructor.
Parameters
pm a reference to the persistence manager to be able to read some data
Definition at line 59 of file TPS_Worker.java.
References de.dlr.ivf.tapas.person.TPS_PreferenceParameters.readParams().
Member Function Documentation
assignCarToPlan()
void de.dlr.ivf.tapas.person.TPS_Worker.assignCarToPlan (TPS_Plan plan) private
Function to assign a car to a given plan. The car can not be used during this period of time by someone else.
Parameters
plan
Definition at line 113 of file TPS_Worker.java.
References de.dlr.ivf.tapas.plan.TPS_Plan.getAdaptedEpisode(), de.dlr.ivf.tapas.scheme.TPS_TourPart.getCar(), de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.getEnd(), de.dlr.ivf.tapas.scheme.TPS_SchemePart.getFirstEpisode(), de.dlr.ivf.tapas.scheme.TPS_SchemePart.getLastEpisode(), de.dlr.ivf.tapas.plan.TPS_Plan.getScheme(), de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.getStart(), de.dlr.ivf.tapas.scheme.TPS_TourPart.getTourpartDistance(), de.dlr.ivf.tapas.person.TPS_Car.hasPaidToll, de.dlr.ivf.tapas.plan.TPS_Plan.mustPayToll, and de.dlr.ivf.tapas.person.TPS_Car.pickCar().
call()
Exception de.dlr.ivf.tapas.person.TPS_Worker.call ()
Definition at line 134 of file TPS_Worker.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.HierarchyLogLevel.CLIENT, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.DEBUG, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.persistence.TPS_PersistenceManager.getNextHousehold(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.HierarchyLogLevel.HOUSEHOLD, de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), de.dlr.ivf.tapas.TPS_Main.TPS_State.isRunning(), de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.persistence.TPS_PersistenceManager.returnHousehold(), de.dlr.ivf.tapas.TPS_Main.STATE, and de.dlr.ivf.tapas.person.TPS_Household.toString().
createPersonPlans()
void de.dlr.ivf.tapas.person.TPS_Worker.createPersonPlans (TPS_PlanEnvironment pe, TPS_Car carDummy) private
This method tries to find a suitable plan for the given person. First of all a scheme is selected. Then the locations and travel times are selected. When the plan is complete then it is rated and when the rate is good enough it is accepted. When it is not accepted new locations are searched for the same scheme. After a specific number of unsuitable tries for this scheme the scheme is discharged and newly selected. If there is no suitable plan after a specific number of tries found a warning is logged and the method stops.
All plans during the execution are stored in the TPS_PlanEnvironment. This environment is then returned.
Returns
all produced plans stored in the TPS_PlanEnvironment
Definition at line 164 of file TPS_Worker.java.
References de.dlr.ivf.tapas.plan.TPS_PlanEnvironment.addPlan(), de.dlr.ivf.tapas.person.TPS_Household.Sorting.AGE, de.dlr.ivf.tapas.plan.TPS_Plan.balanceStarts(), de.dlr.ivf.tapas.plan.TPS_Plan.calcPlanFeasiblity(), de.dlr.ivf.tapas.person.TPS_Household.Sorting.COST_OPTIMUM, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.DEBUG, de.dlr.ivf.tapas.plan.TPS_PlanEnvironment.dismissScheme(), de.dlr.ivf.tapas.scheme.TPS_SchemeSet.findScheme(), de.dlr.ivf.tapas.plan.TPS_PlanEnvironment.getNumberOfFeasiblePlans(), de.dlr.ivf.tapas.plan.TPS_PlanEnvironment.getNumberOfRejectedPlans(), de.dlr.ivf.tapas.plan.TPS_PlanEnvironment.getPerson(), de.dlr.ivf.tapas.persistence.TPS_PersistenceManager.getSchemesSet(), de.dlr.ivf.tapas.person.TPS_Person.hasBike, de.dlr.ivf.tapas.util.parameters.ParamString.HOUSEHOLD_MEMBERSORTING, de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), de.dlr.ivf.tapas.plan.TPS_Plan.isPlanAccepted(), de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.util.parameters.ParamValue.MAX_TRIES_SCHEME, de.dlr.ivf.tapas.plan.TPS_PlanningContext.needsOtherModeAlternatives(), de.dlr.ivf.tapas.plan.TPS_Plan.selectLocationsAndModesAndTravelTimes(), and de.dlr.ivf.tapas.plan.TPS_Plan.setTravelTimes().
getAllLists()
static List<Integer[]> de.dlr.ivf.tapas.person.TPS_Worker.getAllLists (List< Integer > elements, int lengthOfVector) static
This method generates all permutations of a list of given elements with a fixed length e.g. getAllLists({0;1},2} returns {[00];[01];[10];[11]}
Parameters
elements the elements to permute
lengthOfVector the length of the output lists
Returns
a long list (elements^lengthOfList) containing all permutations
Definition at line 75 of file TPS_Worker.java.
getParameters()
TPS_ParameterClass de.dlr.ivf.tapas.person.TPS_Worker.getParameters ()
Definition at line 237 of file TPS_Worker.java.
References de.dlr.ivf.tapas.persistence.TPS_PersistenceManager.getParameters().
processHousehold()
void de.dlr.ivf.tapas.person.TPS_Worker.processHousehold (TPS_Household hh) private
Builds plans for all members of the given household
Parameters
hh The household to process
Definition at line 246 of file TPS_Worker.java.
References de.dlr.ivf.tapas.person.TPS_Household.Sorting.AGE, de.dlr.ivf.tapas.person.TPS_Household.Sorting.COST_OPTIMUM, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.DEBUG, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_REJUVENATE_RETIREE, de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_USE_SHOPPING_MOTIVES, de.dlr.ivf.tapas.plan.TPS_Plan.getAcceptanceProbability(), de.dlr.ivf.tapas.person.TPS_Household.getAllCars(), de.dlr.ivf.tapas.plan.TPS_PlanEnvironment.getBestPlan(), de.dlr.ivf.tapas.person.TPS_Household.getCar(), de.dlr.ivf.tapas.person.TPS_Household.getMembers(), de.dlr.ivf.tapas.person.TPS_Household.getNumberOfCars(), de.dlr.ivf.tapas.person.TPS_Household.getNumberOfMembers(), de.dlr.ivf.tapas.plan.TPS_PlanEnvironment.getPlans(), de.dlr.ivf.tapas.scheme.TPS_SchemePart.getScheme(), de.dlr.ivf.tapas.scheme.TPS_Scheme.getSchemeParts(), de.dlr.ivf.tapas.util.parameters.ParamString.HOUSEHOLD_MEMBERSORTING, de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.HierarchyLogLevel.PERSON, de.dlr.ivf.tapas.util.parameters.ParamValue.REJUVENATE_AGE, de.dlr.ivf.tapas.util.parameters.ParamValue.REJUVENATE_BY_NB_YEARS, de.dlr.ivf.tapas.plan.TPS_Plan.usesBike, de.dlr.ivf.tapas.plan.TPS_Plan.usesCar(), and de.dlr.ivf.tapas.persistence.TPS_PersistenceManager.writePlan().
Member Data Documentation
PM
TPS_PersistenceManager de.dlr.ivf.tapas.person.TPS_Worker.PM = null private
Definition at line 52 of file TPS_Worker.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/person/TPS_Worker.java