TAPAS: de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher Class Reference
de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher Class Reference
Classes
class KeyPairListModel
Public Member Functions
HeaderMatcher (List< String > dbHeaders, List< String > csvHeaders)
HashMap< String, String > getMapping ()
Static Public Member Functions
static void main (String[] args)
Private Member Functions
void initGUI (List< String > dbHeaders, List< String > csvHeaders)
Private Attributes
KeyPairListModel lstPairsModel
JList< String > lstDB
JList< String > lstCSV
JList< String > lstPairs
JLabel lblStatus
JButton btnAdd
Static Private Attributes
static final long serialVersionUID = 8144993710660146669L
static final int CONTROL_WIDTH = 100
Detailed Description
This is a panel to match csvHeaders to dbHeaders. It needs two lists of headers and returns a mapping between the do usable with DbCsvMap.
Author
boec_pa
See also
JPanel
Definition at line 29 of file HeaderMatcher.java.
Constructor & Destructor Documentation
HeaderMatcher()
de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.HeaderMatcher (List< String > dbHeaders, List< String > csvHeaders)
Definition at line 42 of file HeaderMatcher.java.
References de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.initGUI().
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.main().
Member Function Documentation
getMapping()
HashMap<String, String> de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.getMapping ()
Definition at line 72 of file HeaderMatcher.java.
References de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.KeyPairListModel.getMapping(), and de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.lstPairsModel.
initGUI()
void de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.initGUI (List< String > dbHeaders, List< String > csvHeaders) private
Definition at line 76 of file HeaderMatcher.java.
References de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.KeyPairListModel.addElement(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.btnAdd, de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.KeyPairListModel.contains(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.CONTROL_WIDTH, de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.lblStatus, de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.lstCSV, de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.lstDB, de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.lstPairs, de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.lstPairsModel, and de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.KeyPairListModel.remove().
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.HeaderMatcher().
main()
static void de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.main (String[] args) static
Testing purposes only
Definition at line 50 of file HeaderMatcher.java.
References de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.HeaderMatcher().
Member Data Documentation
btnAdd
JButton de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.btnAdd private
Definition at line 41 of file HeaderMatcher.java.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.initGUI().
CONTROL_WIDTH
final int de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.CONTROL_WIDTH = 100 static private
Definition at line 35 of file HeaderMatcher.java.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.initGUI().
lblStatus
JLabel de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.lblStatus private
Definition at line 40 of file HeaderMatcher.java.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.initGUI().
lstCSV
JList<String> de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.lstCSV private
Definition at line 38 of file HeaderMatcher.java.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.initGUI().
lstDB
JList<String> de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.lstDB private
Definition at line 37 of file HeaderMatcher.java.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.initGUI().
lstPairs
JList<String> de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.lstPairs private
Definition at line 39 of file HeaderMatcher.java.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.initGUI().
lstPairsModel
KeyPairListModel de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.lstPairsModel private
Definition at line 36 of file HeaderMatcher.java.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.getMapping(), and de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.initGUI().
serialVersionUID
final long de.dlr.ivf.tapas.tools.persitence.db.dbImport.HeaderMatcher.serialVersionUID = 8144993710660146669L static private
Definition at line 34 of file HeaderMatcher.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/persitence/db/dbImport/HeaderMatcher.java