TAPAS: de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzer Class Reference
de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzer Class Reference
Public Member Functions
GeneralAnalyzer (DefaultMutableTreeNode root, boolean writeToDB)
GeneralAnalyzer (DefaultMutableTreeNode root, boolean writeToDB, String region)
void addPropertyChangeListener (PropertyChangeListener listener)
boolean finish () throws BadLocationException
boolean finish (File exportfile) throws BadLocationException
HashMap< DefaultMutableTreeNode, Analyzer > getAnalyzers ()
String getDescription ()
void setDescription (String description)
long getNumberTrips ()
String getRegion ()
DefaultMutableTreeNode getRoot ()
String getSource ()
boolean init (String outputPath, StyledDocument console, boolean clearSources) throws BadLocationException
boolean init (boolean clearSources)
boolean prepare (String source, TapasTrip trip, TPS_ParameterClass parameterClass)
void removePropertyChangeListener (PropertyChangeListener listener)
Public Member Functions inherited from de.dlr.ivf.tapas.analyzer.gui.AbstractCoreProcess
AbstractCoreProcess ()
final boolean cancelFinish ()
void doCancel ()
boolean isCancelled ()
final void run ()
Private Member Functions
HashMap< DefaultMutableTreeNode, Analyzer > buildAnalyzerList ()
Private Attributes
StyledDocument console
String outputPath
final HashSet< String > sources = new HashSet<>()
final HashMap< DefaultMutableTreeNode, Analyzer > analyzers
final DefaultMutableTreeNode root
final boolean writeToDB
final String region
String description
long totalTrips = 0
final PropertyChangeSupport pcs = new PropertyChangeSupport(this)
Static Private Attributes
static final String sourceSeperator = ";"
Additional Inherited Members
Protected Attributes inherited from de.dlr.ivf.tapas.analyzer.gui.AbstractCoreProcess
boolean isProcessing
Detailed Description
This is the general logic module for the TUM export of the TAPAS Analyzer. It takes a tree of AnalyzerCollections and fills it accordingly. The main loop of adding TapasTrips is done outside this class. The method GeneralAnalyzer#prepare(String, TapasTrip, TPS_ParameterClass) is expected to be called very often.
The logic of this module is mostly handled by the Analyzers hold (and implicitly defined with the tree passed to the constructor) and the exporters. This class provides an entry point to the TAPAS analyzer structure.
As per the definition of the extended AbstractCoreProcess the method GeneralAnalyzer#finish() will trigger the default export methods. An excel export via GeneralExcelExport will be attempted. If the boolean writeToDB is set on construction, a GeneralDatabaseSummaryExport will be started as well.
Author
boec_pa
Definition at line 56 of file GeneralAnalyzer.java.
Constructor & Destructor Documentation
GeneralAnalyzer() [1/2]
de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzer.GeneralAnalyzer (DefaultMutableTreeNode root, boolean writeToDB)
Definition at line 70 of file GeneralAnalyzer.java.
GeneralAnalyzer() [2/2]
de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzer.GeneralAnalyzer (DefaultMutableTreeNode root, boolean writeToDB, String region)
Parameters
root must be the root of a tree of AnalyzerCollections as provided by TUMControlGeneral.
writeToDB if true, it will trigger a GeneralDatabaseSummaryExport on finish.
region only used for the GeneralExcelExport as a flag in the header. Defaults to "".
Definition at line 83 of file GeneralAnalyzer.java.
Member Function Documentation
addPropertyChangeListener()
void de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzer.addPropertyChangeListener (PropertyChangeListener listener)
Definition at line 90 of file GeneralAnalyzer.java.
buildAnalyzerList()
HashMap<DefaultMutableTreeNode, Analyzer> de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzer.buildAnalyzerList () private
Definition at line 95 of file GeneralAnalyzer.java.
finish() [1/2]
boolean de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzer.finish () throws BadLocationException
Muss aufgerufen werden, wenn der Prozess beendet wird
Returns
Implements de.dlr.ivf.tapas.analyzer.core.CoreProcessInterface.
Definition at line 125 of file GeneralAnalyzer.java.
References de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralExcelExport.writeAnalysis(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralDatabaseSummaryExport.writeSummary().
Referenced by de.dlr.ivf.tapas.tools.TUM.IntegratedTUM.doInBackground().
finish() [2/2]
boolean de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzer.finish (File exportfile) throws BadLocationException
Reimplemented from de.dlr.ivf.tapas.analyzer.gui.AbstractCoreProcess.
Definition at line 184 of file GeneralAnalyzer.java.
References de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralExcelExport.writeAnalysis().
getAnalyzers()
HashMap<DefaultMutableTreeNode, Analyzer> de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzer.getAnalyzers ()
Definition at line 212 of file GeneralAnalyzer.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralExcelExport.writeTab().
getDescription()
String de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzer.getDescription ()
Returns
the description
Definition at line 219 of file GeneralAnalyzer.java.
getNumberTrips()
long de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzer.getNumberTrips ()
Returns
the total number of added trips.
Definition at line 233 of file GeneralAnalyzer.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralExcelExport.GeneralExcelExport(), and de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralExcelExport.writeTabHeader().
getRegion()
String de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzer.getRegion ()
Returns
the region of the analysis given at construction time. May be empty (but not null).
Definition at line 241 of file GeneralAnalyzer.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralExcelExport.writeTabHeader().
getRoot()
DefaultMutableTreeNode de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzer.getRoot ()
Definition at line 245 of file GeneralAnalyzer.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralExcelExport.writeAnalysis().
getSource()
String de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzer.getSource ()
Returns
the accumulated sources of all added trips.
Definition at line 252 of file GeneralAnalyzer.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralExcelExport.writeTabHeader().
init() [1/2]
boolean de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzer.init (boolean clearSources)
Used by the de.dlr.ivf.tapas.tools.TUM.IntegratedTUM
Parameters
clearSources
Returns
Reimplemented from de.dlr.ivf.tapas.analyzer.gui.AbstractCoreProcess.
Definition at line 277 of file GeneralAnalyzer.java.
init() [2/2]
boolean de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzer.init (String outputPath, StyledDocument console, boolean clearSources) throws BadLocationException
Muss einmalig vor dem Start aufgerufen werden.
Parameters
outputPath Pfad wo die Ergebnisse hingeschrieben werden sollen
console Konsole für Info-Mitteilungen.
clearSources Flag ob vorherige Resultate gelöscht werden sollen.
Returns
Implements de.dlr.ivf.tapas.analyzer.core.CoreProcessInterface.
Definition at line 261 of file GeneralAnalyzer.java.
Referenced by de.dlr.ivf.tapas.tools.TUM.IntegratedTUM.doInBackground().
prepare()
boolean de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzer.prepare (String filePath, TapasTrip trip, TPS_ParameterClass parameterClass)
Muss vor dem Start des Prozesses für jeden zu behandelnden Trip aufgerufen werden.
Parameters
filePath Der Pfad zum Trip
trip der Trip
Returns
Implements de.dlr.ivf.tapas.analyzer.core.CoreProcessInterface.
Definition at line 284 of file GeneralAnalyzer.java.
Referenced by de.dlr.ivf.tapas.tools.TUM.IntegratedTUM.doInBackground().
removePropertyChangeListener()
void de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzer.removePropertyChangeListener (PropertyChangeListener listener)
Definition at line 304 of file GeneralAnalyzer.java.
setDescription()
void de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzer.setDescription (String description)
Parameters
description the description to set
Definition at line 226 of file GeneralAnalyzer.java.
Referenced by de.dlr.ivf.tapas.tools.TUM.IntegratedTUM.doInBackground().
Member Data Documentation
analyzers
final HashMap<DefaultMutableTreeNode, Analyzer> de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzer.analyzers private
Definition at line 62 of file GeneralAnalyzer.java.
console
StyledDocument de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzer.console private
Definition at line 59 of file GeneralAnalyzer.java.
description
String de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzer.description private
Definition at line 66 of file GeneralAnalyzer.java.
outputPath
String de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzer.outputPath private
Definition at line 60 of file GeneralAnalyzer.java.
pcs
final PropertyChangeSupport de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzer.pcs = new PropertyChangeSupport(this) private
Definition at line 68 of file GeneralAnalyzer.java.
region
final String de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzer.region private
Definition at line 65 of file GeneralAnalyzer.java.
root
final DefaultMutableTreeNode de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzer.root private
Definition at line 63 of file GeneralAnalyzer.java.
sources
final HashSet<String> de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzer.sources = new HashSet<>() private
Definition at line 61 of file GeneralAnalyzer.java.
sourceSeperator
final String de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzer.sourceSeperator = ";" static private
Definition at line 58 of file GeneralAnalyzer.java.
totalTrips
long de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzer.totalTrips = 0 private
Definition at line 67 of file GeneralAnalyzer.java.
writeToDB
final boolean de.dlr.ivf.tapas.analyzer.tum.regionanalyzer.general.GeneralAnalyzer.writeToDB private
Definition at line 64 of file GeneralAnalyzer.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/tum/regionanalyzer/general/GeneralAnalyzer.java