TAPAS: de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2GUI Class Reference
de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2GUI Class Reference
Static Public Member Functions
static void main (String[] args) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException
Private Member Functions
void activateElements (boolean val)
String chooseFile (String title, JFrame f, boolean multi)
void createAndShowGui ()
Private Attributes
JFrame frame
final DBImportV2 control = new DBImportV2()
Detailed Description
Definition at line 19 of file DBImportV2GUI.java.
Member Function Documentation
activateElements()
void de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2GUI.activateElements (boolean val) private
Definition at line 80 of file DBImportV2GUI.java.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2GUI.createAndShowGui().
chooseFile()
String de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2GUI.chooseFile (String title, JFrame f, boolean multi) private
Definition at line 86 of file DBImportV2GUI.java.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2GUI.createAndShowGui().
createAndShowGui()
void de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2GUI.createAndShowGui () private
Definition at line 120 of file DBImportV2GUI.java.
References de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2GUI.activateElements(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2GUI.chooseFile(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.closeConnections(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2GUI.control, de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.createRegion(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2GUI.frame, de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.importAct2Loc(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.importBlock(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.importBlockNextPTStop(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.importCFN4(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.importCFN4Ind(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.importHH(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.importIntraMIT(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.importIntraPT(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.importLocations(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.importMatrix(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.importModeChoice(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.importPersons(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.importScores(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.importTAZ(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.importTazFee(), de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2.login(), and name.
main()
static void de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2GUI.main (String[] args) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException static
Parameters
args
Exceptions
UnsupportedLookAndFeelException
IllegalAccessException
InstantiationException
ClassNotFoundException
Definition at line 69 of file DBImportV2GUI.java.
References de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2GUI.control.
Member Data Documentation
control
final DBImportV2 de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2GUI.control = new DBImportV2() private
Definition at line 60 of file DBImportV2GUI.java.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2GUI.createAndShowGui(), and de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2GUI.main().
frame
JFrame de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2GUI.frame private
Definition at line 59 of file DBImportV2GUI.java.
Referenced by de.dlr.ivf.tapas.tools.persitence.db.dbImport.DBImportV2GUI.createAndShowGui().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/persitence/db/dbImport/DBImportV2GUI.java