TAPAS: de.dlr.ivf.tapas.plan.TPS_PlannedTrip Class Reference
de.dlr.ivf.tapas.plan.TPS_PlannedTrip Class Reference
Public Member Functions
TPS_PlannedTrip (TPS_Plan plan, TPS_Trip trip, TPS_ParameterClass parameterClass)
double getCosts (CURRENCY currency)
TPS_Episode getEpisode ()
TPS_ExtMode getMode ()
void setMode (TPS_ExtMode mode)
TPS_Trip getTrip ()
boolean isLocatedStay ()
String toString ()
String toString (String prefix)
Public Member Functions inherited from de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode
TPS_AdaptedEpisode (TPS_Plan plan, TPS_Episode episode)
double getDistance ()
void setDistance (double distance)
double getDistanceBeeline ()
void setDistanceBeeline (double distanceBeeline)
double getDistanceEmptyNet ()
void setDistanceEmptyNet (double distanceEmptyNet)
int getDuration ()
void setDuration (int duration)
int getEnd ()
int getStart ()
void setStart (int start)
boolean isPlannedTrip ()
Private Attributes
double costs
TPS_ExtMode mode
final TPS_Trip trip
Additional Inherited Members
Protected Member Functions inherited from de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode
void init (TPS_Episode episode)
Protected Attributes inherited from de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode
TPS_Plan plan
Detailed Description
Author
cyga_ri
Definition at line 33 of file TPS_PlannedTrip.java.
Constructor & Destructor Documentation
TPS_PlannedTrip()
de.dlr.ivf.tapas.plan.TPS_PlannedTrip.TPS_PlannedTrip (TPS_Plan plan, TPS_Trip trip, TPS_ParameterClass parameterClass)
This constructor calls the super constructor with the trip and sets the internal reference of the trip.
Parameters
plan Reference to the whole plan
trip Reference to the original trip
Definition at line 48 of file TPS_PlannedTrip.java.
Member Function Documentation
getCosts()
double de.dlr.ivf.tapas.plan.TPS_PlannedTrip.getCosts (CURRENCY currency)
Returns the variable costs of the trip in the given currency
Parameters
currency currency to return in the costs
Returns
cost of the trip
Definition at line 59 of file TPS_PlannedTrip.java.
References de.dlr.ivf.tapas.util.parameters.CURRENCY.convert(), and de.dlr.ivf.tapas.util.parameters.ParamString.CURRENCY.
getEpisode()
TPS_Episode de.dlr.ivf.tapas.plan.TPS_PlannedTrip.getEpisode ()
Returns
episode
Reimplemented from de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.
Definition at line 69 of file TPS_PlannedTrip.java.
getMode()
TPS_ExtMode de.dlr.ivf.tapas.plan.TPS_PlannedTrip.getMode ()
Returns the mode selected for the trip
Returns
the mode
Definition at line 78 of file TPS_PlannedTrip.java.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.batchStoreTrips(), de.dlr.ivf.tapas.plan.TPS_Plan.createOutput(), de.dlr.ivf.tapas.scheme.TPS_TourPart.updateActualTravelDistances(), and de.dlr.ivf.tapas.plan.TPS_Plan.writeOutputStream().
getTrip()
TPS_Trip de.dlr.ivf.tapas.plan.TPS_PlannedTrip.getTrip ()
Returns
reference to the corresponding trip
Definition at line 94 of file TPS_PlannedTrip.java.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.createOutput(), and de.dlr.ivf.tapas.plan.TPS_Plan.writeOutputStream().
isLocatedStay()
boolean de.dlr.ivf.tapas.plan.TPS_PlannedTrip.isLocatedStay ()
Returns
true if it is a located stay false otherwise
Reimplemented from de.dlr.ivf.tapas.plan.TPS_AdaptedEpisode.
Definition at line 104 of file TPS_PlannedTrip.java.
setMode()
void de.dlr.ivf.tapas.plan.TPS_PlannedTrip.setMode (TPS_ExtMode mode)
Sets the selected mode for the trip
Parameters
mode
Definition at line 87 of file TPS_PlannedTrip.java.
toString() [1/2]
String de.dlr.ivf.tapas.plan.TPS_PlannedTrip.toString ()
Definition at line 353 of file TPS_PlannedTrip.java.
toString() [2/2]
String de.dlr.ivf.tapas.plan.TPS_PlannedTrip.toString (String prefix)
This method should print the object naturally with the given prefix.
Parameters
prefix
Returns
prefix + toString();
Implements de.dlr.ivf.tapas.util.ExtendedWritable.
Definition at line 362 of file TPS_PlannedTrip.java.
References de.dlr.ivf.tapas.mode.TPS_ExtMode.getName().
Member Data Documentation
costs
double de.dlr.ivf.tapas.plan.TPS_PlannedTrip.costs private
Definition at line 35 of file TPS_PlannedTrip.java.
mode
TPS_ExtMode de.dlr.ivf.tapas.plan.TPS_PlannedTrip.mode private
Definition at line 37 of file TPS_PlannedTrip.java.
trip
final TPS_Trip de.dlr.ivf.tapas.plan.TPS_PlannedTrip.trip private
Definition at line 39 of file TPS_PlannedTrip.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/plan/TPS_PlannedTrip.java