TAPAS: de.dlr.ivf.tapas.util.Timeline Class Reference
de.dlr.ivf.tapas.util.Timeline Class Reference
Classes
class Entry
Public Member Functions
Timeline ()
boolean add (int start, int end)
boolean clash (int start, int end)
boolean contains (int start, int end)
boolean remove (int start, int end)
String toString ()
Static Public Member Functions
static void main (String[] args)
Private Member Functions
Entry[] getSurroundingEntries (int start, int end)
Private Attributes
final Entry entrance
final Entry[] entries
final Entry exit
Detailed Description
This class represents a time line. It is possible to add entries from a start to an end point. These entries build up a linked list in both directions. The time line holds the entries consistent, i.e. there can be no entries added which overlaps already added entries.
Author
mark_ma
Definition at line 24 of file Timeline.java.
Constructor & Destructor Documentation
Timeline()
de.dlr.ivf.tapas.util.Timeline.Timeline ()
The Constructor initialises the member values
Definition at line 42 of file Timeline.java.
References de.dlr.ivf.tapas.util.Timeline.Entry.next, and de.dlr.ivf.tapas.util.Timeline.Entry.previous.
Member Function Documentation
add()
boolean de.dlr.ivf.tapas.util.Timeline.add (int start, int end)
This method tries to add an entry to the time line in a consistent way
Parameters
start
end
Returns
true if an entry was added, false otherwise
Exceptions
IllegalArgumentException when start >= end
Definition at line 102 of file Timeline.java.
References de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.util.Timeline.Entry.next, de.dlr.ivf.tapas.util.Timeline.Entry.previous, and de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.WARN.
Referenced by de.dlr.ivf.tapas.plan.TPS_Plan.calcPlanFeasiblity(), de.dlr.ivf.tapas.util.Timeline.main(), and de.dlr.ivf.tapas.person.TPS_Car.pickCar().
clash()
boolean de.dlr.ivf.tapas.util.Timeline.clash (int start, int end)
This method checks if the given interval overlaps an existing entries
Parameters
start
end
Returns
true if the intervals overlaps
Definition at line 129 of file Timeline.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Car.isAvailable(), and de.dlr.ivf.tapas.util.Timeline.main().
contains()
boolean de.dlr.ivf.tapas.util.Timeline.contains (int start, int end)
This method checks if the Timeline contains an entry with exactly the given start and stop times
Parameters
start
end
Returns
true if an entry exists
Definition at line 141 of file Timeline.java.
References de.dlr.ivf.tapas.util.Timeline.Entry.next.
Referenced by de.dlr.ivf.tapas.util.Timeline.main().
getSurroundingEntries()
Entry [] de.dlr.ivf.tapas.util.Timeline.getSurroundingEntries (int start, int end) private
This method returns the surrounding entries to the given interval. When the interval don't overlaps another one, then the next and the previous interval is returned.
Parameters
start
end
Returns
next and previous entry to the given interval
Definition at line 162 of file Timeline.java.
References de.dlr.ivf.tapas.util.Timeline.Entry.end, de.dlr.ivf.tapas.util.Timeline.Entry.next, de.dlr.ivf.tapas.util.Timeline.Entry.previous, and de.dlr.ivf.tapas.util.Timeline.Entry.start.
main()
static void de.dlr.ivf.tapas.util.Timeline.main (String[] args) static
Small test for the time line
Parameters
args
Definition at line 55 of file Timeline.java.
References de.dlr.ivf.tapas.util.Timeline.add(), de.dlr.ivf.tapas.util.Timeline.clash(), de.dlr.ivf.tapas.util.Timeline.contains(), and de.dlr.ivf.tapas.util.Timeline.remove().
remove()
boolean de.dlr.ivf.tapas.util.Timeline.remove (int start, int end)
This method removes the entry with exactly the given start and stop times from this timeline
Parameters
start
end
Returns
true if entry was removed
Definition at line 186 of file Timeline.java.
References de.dlr.ivf.tapas.util.Timeline.Entry.next, and de.dlr.ivf.tapas.util.Timeline.Entry.previous.
Referenced by de.dlr.ivf.tapas.util.Timeline.main(), and de.dlr.ivf.tapas.person.TPS_Car.unPickCar().
toString()
String de.dlr.ivf.tapas.util.Timeline.toString ()
Definition at line 207 of file Timeline.java.
References de.dlr.ivf.tapas.util.Timeline.Entry.next.
Member Data Documentation
entrance
final Entry de.dlr.ivf.tapas.util.Timeline.entrance private
The entrance entry
Definition at line 29 of file Timeline.java.
entries
final Entry [] de.dlr.ivf.tapas.util.Timeline.entries private
Internal storage for a pair of references
Definition at line 33 of file Timeline.java.
exit
final Entry de.dlr.ivf.tapas.util.Timeline.exit private
The exit entry
Definition at line 37 of file Timeline.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/util/Timeline.java