TAPAS: de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.ModalSplitForDistanceCategoryAndTripIntention.ModalSplitForDistanceCategoryAndTripIntentionElement Class Reference
de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.ModalSplitForDistanceCategoryAndTripIntention.ModalSplitForDistanceCategoryAndTripIntentionElement Class Reference
Public Member Functions
boolean containsModalSplitTripIntentionSeparated (TripIntention tripIntention)
boolean containsModalSplitTripIntentionSeparatedAbs (TripIntention tripIntention)
List< DistanceCategory > getDistanceCategories ()
double getModalSplitOther ()
long getModalSplitOtherAbs ()
double getModalSplitTripIntentionSeparated (TripIntention tripIntention)
long getModalSplitTripIntentionSeparatedAbs (TripIntention tripIntention)
void putModalSplitTripIntentionSeparated (TripIntention tripIntention, double modalSplit)
void putModalSplitTripIntentionSeparatedAbs (TripIntention tripIntention, long modalSplitAbs)
Private Attributes
List< DistanceCategory > distanceCategories
final Map< TripIntention, Double > modalSplitTripIntentionSeparated = new HashMap<>()
final Map< TripIntention, Long > modalSplitTripIntentionSeparatedAbs = new HashMap<>()
double modalSplitOther
long modalSplitOtherAbs
Detailed Description
Ein Element des Modalsplits. Abhängig davon welche Distanzkategorien selektiert wurden, enthält dieses Element die Distanzkategorien die zusammengefasst wurden. Jedes Element wird des weiteren nach TripIntention getrennt
Author
Marco
Definition at line 765 of file RegionPOJO.java.
Member Function Documentation
containsModalSplitTripIntentionSeparated()
boolean de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.ModalSplitForDistanceCategoryAndTripIntention.ModalSplitForDistanceCategoryAndTripIntentionElement.containsModalSplitTripIntentionSeparated (TripIntention tripIntention)
Definition at line 772 of file RegionPOJO.java.
Referenced by de.dlr.ivf.tapas.analyzer.core.TapasChartFactory.createModalSplitTripIntentionDistanceCategorySeparated().
containsModalSplitTripIntentionSeparatedAbs()
boolean de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.ModalSplitForDistanceCategoryAndTripIntention.ModalSplitForDistanceCategoryAndTripIntentionElement.containsModalSplitTripIntentionSeparatedAbs (TripIntention tripIntention)
Definition at line 776 of file RegionPOJO.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getModalSplitForDistanceCategoryAndTripIntention().
getDistanceCategories()
List<DistanceCategory> de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.ModalSplitForDistanceCategoryAndTripIntention.ModalSplitForDistanceCategoryAndTripIntentionElement.getDistanceCategories ()
Definition at line 780 of file RegionPOJO.java.
Referenced by de.dlr.ivf.tapas.analyzer.core.TapasChartFactory.createModalSplitTripIntentionDistanceCategorySeparated(), and de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getModalSplitForDistanceCategoryAndTripIntention().
getModalSplitOther()
double de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.ModalSplitForDistanceCategoryAndTripIntention.ModalSplitForDistanceCategoryAndTripIntentionElement.getModalSplitOther ()
Definition at line 785 of file RegionPOJO.java.
Referenced by de.dlr.ivf.tapas.analyzer.core.TapasChartFactory.createModalSplitTripIntentionDistanceCategorySeparated().
getModalSplitOtherAbs()
long de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.ModalSplitForDistanceCategoryAndTripIntention.ModalSplitForDistanceCategoryAndTripIntentionElement.getModalSplitOtherAbs ()
Definition at line 789 of file RegionPOJO.java.
getModalSplitTripIntentionSeparated()
double de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.ModalSplitForDistanceCategoryAndTripIntention.ModalSplitForDistanceCategoryAndTripIntentionElement.getModalSplitTripIntentionSeparated (TripIntention tripIntention)
Definition at line 793 of file RegionPOJO.java.
Referenced by de.dlr.ivf.tapas.analyzer.core.TapasChartFactory.createModalSplitTripIntentionDistanceCategorySeparated().
getModalSplitTripIntentionSeparatedAbs()
long de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.ModalSplitForDistanceCategoryAndTripIntention.ModalSplitForDistanceCategoryAndTripIntentionElement.getModalSplitTripIntentionSeparatedAbs (TripIntention tripIntention)
Definition at line 798 of file RegionPOJO.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getModalSplitForDistanceCategoryAndTripIntention().
putModalSplitTripIntentionSeparated()
void de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.ModalSplitForDistanceCategoryAndTripIntention.ModalSplitForDistanceCategoryAndTripIntentionElement.putModalSplitTripIntentionSeparated (TripIntention tripIntention, double modalSplit)
Definition at line 803 of file RegionPOJO.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getModalSplitForDistanceCategoryAndTripIntention().
putModalSplitTripIntentionSeparatedAbs()
void de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.ModalSplitForDistanceCategoryAndTripIntention.ModalSplitForDistanceCategoryAndTripIntentionElement.putModalSplitTripIntentionSeparatedAbs (TripIntention tripIntention, long modalSplitAbs)
Definition at line 807 of file RegionPOJO.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getModalSplitForDistanceCategoryAndTripIntention().
Member Data Documentation
distanceCategories
List<DistanceCategory> de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.ModalSplitForDistanceCategoryAndTripIntention.ModalSplitForDistanceCategoryAndTripIntentionElement.distanceCategories private
Definition at line 766 of file RegionPOJO.java.
modalSplitOther
double de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.ModalSplitForDistanceCategoryAndTripIntention.ModalSplitForDistanceCategoryAndTripIntentionElement.modalSplitOther private
Definition at line 769 of file RegionPOJO.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getModalSplitForDistanceCategoryAndTripIntention().
modalSplitOtherAbs
long de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.ModalSplitForDistanceCategoryAndTripIntention.ModalSplitForDistanceCategoryAndTripIntentionElement.modalSplitOtherAbs private
Definition at line 770 of file RegionPOJO.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getModalSplitForDistanceCategoryAndTripIntention().
modalSplitTripIntentionSeparated
final Map<TripIntention, Double> de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.ModalSplitForDistanceCategoryAndTripIntention.ModalSplitForDistanceCategoryAndTripIntentionElement.modalSplitTripIntentionSeparated = new HashMap<>() private
Definition at line 767 of file RegionPOJO.java.
modalSplitTripIntentionSeparatedAbs
final Map<TripIntention, Long> de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.ModalSplitForDistanceCategoryAndTripIntention.ModalSplitForDistanceCategoryAndTripIntentionElement.modalSplitTripIntentionSeparatedAbs = new HashMap<>() private
Definition at line 768 of file RegionPOJO.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/tum/RegionPOJO.java