TAPAS: de.dlr.ivf.tapas.analyzer.core.TapasChartFactory Class Reference
de.dlr.ivf.tapas.analyzer.core.TapasChartFactory Class Reference
Static Public Member Functions
static Map< RegionCode, JFreeChart > createModalSplit (StatisticPOJO statistics, boolean asPie, ChartTheme theme)
static MultiKeyMap createModalSplitDistanceCategorySeparated (StatisticPOJO statistics, boolean[] modalSplitForDistanceCatFilter, boolean asPie, ChartTheme theme)
static MultiKeyMap createModalSplitTripIntentionDistanceCategorySeparated (StatisticPOJO statistics, boolean[] modalSplitForDistanceCatAndTripIntentionFilterTripInt, boolean[] modalSplitForDistanceCatAndTripIntentionFilterDistCat, boolean asPie, ChartTheme theme)
static MultiKeyMap createModalSplitTripIntentionSeparated (StatisticPOJO statistics, boolean asPie, ChartTheme theme)
static MultiKeyMap createModalSplitTripIntentionTapasPersonGroupSeparated (StatisticPOJO statistics, boolean asPie, ChartTheme theme)
static MultiKeyMap createModalSplitTripIntentionVisevaPersonGroupSeparated (StatisticPOJO statistics, boolean asPie, ChartTheme theme)
static Map< RegionCode, JFreeChart > createTripLength (StatisticPOJO statistics, boolean asPie, ChartTheme theme)
static MultiKeyMap createTripLengthModeSeparated (StatisticPOJO statistics, boolean asPie, ChartTheme theme)
static MultiKeyMap createTripLengthTripIntentionSeparated (StatisticPOJO statistics, boolean asPie, ChartTheme theme)
Static Private Member Functions
static int countFalses (boolean[] modalSplitForDistanceCatFilter)
static JFreeChart createChartBar (String caption, DefaultCategoryDataset dataset, String horizontalCaption, String verticalCaption, ChartTheme theme)
static JFreeChart createChartPie (String caption, DefaultPieDataset dataset, ChartTheme theme)
static JFreeChart createModalSplitChartBar (String caption, DefaultCategoryDataset dataset, ChartTheme theme)
Static Private Attributes
static final String OTHER = "other"
Detailed Description
Factory Class for creating the Graphics JFreeCharts from given StatisticPOJO's
Definition at line 41 of file TapasChartFactory.java.
Member Function Documentation
countFalses()
static int de.dlr.ivf.tapas.analyzer.core.TapasChartFactory.countFalses (boolean[] modalSplitForDistanceCatFilter) static private
Definition at line 48 of file TapasChartFactory.java.
createChartBar()
static JFreeChart de.dlr.ivf.tapas.analyzer.core.TapasChartFactory.createChartBar (String caption, DefaultCategoryDataset dataset, String horizontalCaption, String verticalCaption, ChartTheme theme) static private
creates a bar-chart for the given DefaultCategoryDataset.
Parameters
caption the chart title (
null
permitted)
dataset the dataset for the chart (
null
permitted).
theme chart theme
Returns
the created bar chart object
Definition at line 63 of file TapasChartFactory.java.
createChartPie()
static JFreeChart de.dlr.ivf.tapas.analyzer.core.TapasChartFactory.createChartPie (String caption, DefaultPieDataset dataset, ChartTheme theme) static private
creates a pie-chart for the given DefaultPieDataset
Parameters
caption the chart title (
null
permitted)
dataset the dataset for the chart (
null
permitted).
theme chart theme
Returns
the created pie chart object
Definition at line 79 of file TapasChartFactory.java.
createModalSplit()
static Map<RegionCode, JFreeChart> de.dlr.ivf.tapas.analyzer.core.TapasChartFactory.createModalSplit (StatisticPOJO statistics, boolean asPie, ChartTheme theme) static
creates the modal split separated by region as pie or bar
Parameters
statistics StatisticPOJO to obtain a list of RegionPOJOs
asPie if true creates a DefaultPieDataset, otherwise DefaultCategoryDataset
Returns
a Map with a regionCode as Key and a JFreeChart as Value
Definition at line 98 of file TapasChartFactory.java.
References de.dlr.ivf.tapas.analyzer.tum.StatisticPOJO.getAnalyses().
createModalSplitChartBar()
static JFreeChart de.dlr.ivf.tapas.analyzer.core.TapasChartFactory.createModalSplitChartBar (String caption, DefaultCategoryDataset dataset, ChartTheme theme) static private
Definition at line 132 of file TapasChartFactory.java.
createModalSplitDistanceCategorySeparated()
static MultiKeyMap de.dlr.ivf.tapas.analyzer.core.TapasChartFactory.createModalSplitDistanceCategorySeparated (StatisticPOJO statistics, boolean[] modalSplitForDistanceCatFilter, boolean asPie, ChartTheme theme) static
Creates the graphics and returns them in a multi key map the keys are RegionCode and a list of DistanceCategory
Parameters
statistics StatisticPOJO to obtain a list of RegionPOJOs
modalSplitForDistanceCatFilter
asPie if true creates a DefaultPieDataset, otherwise DefaultCategoryDataset
theme chart theme
Returns
Definition at line 147 of file TapasChartFactory.java.
References categories, de.dlr.ivf.tapas.analyzer.inputfileconverter.DistanceCategory.createDistanceCategoriesName(), de.dlr.ivf.tapas.analyzer.tum.StatisticPOJO.getAnalyses(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.ModalSplitForDistanceCategory.ModalSplitForDistanceCategoryElement.getDistanceCategories(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.ModalSplitForDistanceCategory.getElements(), and de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.ModalSplitForDistanceCategory.ModalSplitForDistanceCategoryElement.getModalSplit().
createModalSplitTripIntentionDistanceCategorySeparated()
static MultiKeyMap de.dlr.ivf.tapas.analyzer.core.TapasChartFactory.createModalSplitTripIntentionDistanceCategorySeparated (StatisticPOJO statistics, boolean[] modalSplitForDistanceCatAndTripIntentionFilterTripInt, boolean[] modalSplitForDistanceCatAndTripIntentionFilterDistCat, boolean asPie, ChartTheme theme) static
Parameters
statistics StatisticPOJO to obtain a list of RegionPOJOs
modalSplitForDistanceCatAndTripIntentionFilterTripInt
modalSplitForDistanceCatAndTripIntentionFilterDistCat
asPie if true creates a DefaultPieDataset, otherwise DefaultCategoryDataset
theme chart theme
Returns
Map mit RegionCode, DistanceCategory, TripIntention als Key. Zusätzlich noch Other statt TripIntention
Definition at line 204 of file TapasChartFactory.java.
References categories, de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.ModalSplitForDistanceCategoryAndTripIntention.ModalSplitForDistanceCategoryAndTripIntentionElement.containsModalSplitTripIntentionSeparated(), de.dlr.ivf.tapas.analyzer.inputfileconverter.DistanceCategory.createDistanceCategoriesName(), de.dlr.ivf.tapas.analyzer.tum.StatisticPOJO.getAnalyses(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.ModalSplitForDistanceCategoryAndTripIntention.ModalSplitForDistanceCategoryAndTripIntentionElement.getDistanceCategories(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.ModalSplitForDistanceCategoryAndTripIntention.getElements(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.ModalSplitForDistanceCategoryAndTripIntention.ModalSplitForDistanceCategoryAndTripIntentionElement.getModalSplitOther(), and de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.ModalSplitForDistanceCategoryAndTripIntention.ModalSplitForDistanceCategoryAndTripIntentionElement.getModalSplitTripIntentionSeparated().
createModalSplitTripIntentionSeparated()
static MultiKeyMap de.dlr.ivf.tapas.analyzer.core.TapasChartFactory.createModalSplitTripIntentionSeparated (StatisticPOJO statistics, boolean asPie, ChartTheme theme) static
creates the modal split separated by region and TripIntention as a pie or bar
Parameters
statistics StatisticPOJO to obtain a list of RegionPOJOs
asPie if true creates a DefaultPieDataset, otherwise DefaultCategoryDataset
Returns
a MultiKeyMap with regionCode and TripIntention as key and JFreeChart as value
Definition at line 304 of file TapasChartFactory.java.
References de.dlr.ivf.tapas.analyzer.tum.StatisticPOJO.getAnalyses().
createModalSplitTripIntentionTapasPersonGroupSeparated()
static MultiKeyMap de.dlr.ivf.tapas.analyzer.core.TapasChartFactory.createModalSplitTripIntentionTapasPersonGroupSeparated (StatisticPOJO statistics, boolean asPie, ChartTheme theme) static
creates the modal split separated by region, TripIntention and Job as a pie or bar
Parameters
statistics StatisticPOJO to obtain a list of RegionPOJOs
asPie if true creates a DefaultPieDataset, otherwise DefaultCategoryDataset
Returns
a MultiKeyMap with regionCode and TripIntention and Job as key and JFreeChart as value
Definition at line 349 of file TapasChartFactory.java.
References de.dlr.ivf.tapas.analyzer.tum.StatisticPOJO.getAnalyses().
createModalSplitTripIntentionVisevaPersonGroupSeparated()
static MultiKeyMap de.dlr.ivf.tapas.analyzer.core.TapasChartFactory.createModalSplitTripIntentionVisevaPersonGroupSeparated (StatisticPOJO statistics, boolean asPie, ChartTheme theme) static
creates the modal split separated by region and PersonGroup as pie or bar
Parameters
statistics StatisticPOJO to obtain a list of RegionPOJOs
asPie if true creates a DefaultPieDataset, otherwise DefaultCategoryDataset
Returns
a MultiKeyMap with regionCode and TripIntention and PersonGroup as key and JFreeChart as value
Definition at line 396 of file TapasChartFactory.java.
References de.dlr.ivf.tapas.analyzer.tum.StatisticPOJO.getAnalyses().
createTripLength()
static Map<RegionCode, JFreeChart> de.dlr.ivf.tapas.analyzer.core.TapasChartFactory.createTripLength (StatisticPOJO statistics, boolean asPie, ChartTheme theme) static
Parameters
statistics StatisticPOJO to obtain a list of RegionPOJOs
asPie if true creates a DefaultPieDataset, otherwise DefaultCategoryDataset
theme chart theme
Returns
Definition at line 443 of file TapasChartFactory.java.
References de.dlr.ivf.tapas.analyzer.tum.StatisticPOJO.getAnalyses().
createTripLengthModeSeparated()
static MultiKeyMap de.dlr.ivf.tapas.analyzer.core.TapasChartFactory.createTripLengthModeSeparated (StatisticPOJO statistics, boolean asPie, ChartTheme theme) static
Parameters
statistics StatisticPOJO to obtain a list of RegionPOJOs
asPie if true creates a DefaultPieDataset, otherwise DefaultCategoryDataset
theme chart theme
Returns
Definition at line 488 of file TapasChartFactory.java.
References de.dlr.ivf.tapas.analyzer.tum.StatisticPOJO.getAnalyses().
createTripLengthTripIntentionSeparated()
static MultiKeyMap de.dlr.ivf.tapas.analyzer.core.TapasChartFactory.createTripLengthTripIntentionSeparated (StatisticPOJO statistics, boolean asPie, ChartTheme theme) static
Parameters
statistics StatisticPOJO to obtain a list of RegionPOJOs
asPie if true creates a DefaultPieDataset, otherwise DefaultCategoryDataset
theme chart theme
Returns
Definition at line 537 of file TapasChartFactory.java.
References de.dlr.ivf.tapas.analyzer.tum.StatisticPOJO.getAnalyses().
Member Data Documentation
OTHER
final String de.dlr.ivf.tapas.analyzer.core.TapasChartFactory.OTHER = "other" static private
is partly used as an additional key
Definition at line 46 of file TapasChartFactory.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/core/TapasChartFactory.java