TAPAS: de.dlr.ivf.tapas.tools.TPS_ModeShareEstimator Class Reference
de.dlr.ivf.tapas.tools.TPS_ModeShareEstimator Class Reference
Classes
class CustomRenderer
class PieRenderer
class SliderListener
enum ValueType
Public Member Functions
TPS_ModeShareEstimator (String title)
JPanel createDemoPanel ()
void setDefaultSliderValues ()
void updateValue ()
Static Public Member Functions
static void main (String[] args)
static GridBagConstraints newGridBag (int gridX, int padX, int gridY, int padY)
Private Member Functions
void createChart ()
void createDataset ()
Static Private Attributes
static final long serialVersionUID = 3502972524853251146L
Detailed Description
Definition at line 38 of file TPS_ModeShareEstimator.java.
Constructor & Destructor Documentation
TPS_ModeShareEstimator()
de.dlr.ivf.tapas.tools.TPS_ModeShareEstimator.TPS_ModeShareEstimator (String title)
Definition at line 92 of file TPS_ModeShareEstimator.java.
References de.dlr.ivf.tapas.tools.TPS_ModeShareEstimator.createDemoPanel().
Referenced by de.dlr.ivf.tapas.tools.TPS_ModeShareEstimator.main().
Member Function Documentation
createChart()
void de.dlr.ivf.tapas.tools.TPS_ModeShareEstimator.createChart () private
Definition at line 114 of file TPS_ModeShareEstimator.java.
References de.dlr.ivf.tapas.tools.TPS_ModeShareEstimator.PieRenderer.setColor().
Referenced by de.dlr.ivf.tapas.tools.TPS_ModeShareEstimator.createDemoPanel().
createDataset()
void de.dlr.ivf.tapas.tools.TPS_ModeShareEstimator.createDataset () private
Definition at line 170 of file TPS_ModeShareEstimator.java.
References de.dlr.ivf.tapas.tools.TPS_ModeShareEstimator.updateValue().
Referenced by de.dlr.ivf.tapas.tools.TPS_ModeShareEstimator.createDemoPanel().
createDemoPanel()
JPanel de.dlr.ivf.tapas.tools.TPS_ModeShareEstimator.createDemoPanel ()
Definition at line 222 of file TPS_ModeShareEstimator.java.
References de.dlr.ivf.tapas.tools.TPS_ModeShareEstimator.createChart(), de.dlr.ivf.tapas.tools.TPS_ModeShareEstimator.createDataset(), de.dlr.ivf.tapas.tools.TPS_ModeShareEstimator.newGridBag(), and de.dlr.ivf.tapas.tools.TPS_ModeShareEstimator.setDefaultSliderValues().
Referenced by de.dlr.ivf.tapas.tools.TPS_ModeShareEstimator.TPS_ModeShareEstimator().
main()
static void de.dlr.ivf.tapas.tools.TPS_ModeShareEstimator.main (String[] args) static
Definition at line 99 of file TPS_ModeShareEstimator.java.
References de.dlr.ivf.tapas.tools.TPS_ModeShareEstimator.TPS_ModeShareEstimator().
newGridBag()
static GridBagConstraints de.dlr.ivf.tapas.tools.TPS_ModeShareEstimator.newGridBag (int gridX, int padX, int gridY, int padY) static
Definition at line 105 of file TPS_ModeShareEstimator.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_ModeShareEstimator.createDemoPanel().
setDefaultSliderValues()
void de.dlr.ivf.tapas.tools.TPS_ModeShareEstimator.setDefaultSliderValues ()
Definition at line 478 of file TPS_ModeShareEstimator.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_ModeShareEstimator.createDemoPanel().
updateValue()
void de.dlr.ivf.tapas.tools.TPS_ModeShareEstimator.updateValue ()
Definition at line 494 of file TPS_ModeShareEstimator.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_ModeShareEstimator.createDataset().
Member Data Documentation
serialVersionUID
final long de.dlr.ivf.tapas.tools.TPS_ModeShareEstimator.serialVersionUID = 3502972524853251146L static private
Definition at line 43 of file TPS_ModeShareEstimator.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/TPS_ModeShareEstimator.java