TAPAS: de.dlr.ivf.tapas.runtime.client.SimulationMonitor Class Reference
de.dlr.ivf.tapas.runtime.client.SimulationMonitor Class Reference
Classes
class AlignmentRenderer
class BorderedRenderer
class ButtonRenderer
class ColorRenderer
class ExportThread
class HashRenderer
class ProgressRenderer
class ServerColorRenderer
enum SIM_INDEX
class SimTableButtonEditor
class StringArrayRenderer
Public Member Functions
SimulationMonitor (SimulationControl control)
void addServerData (SimulationServerData serverData)
void addSimulation (SimulationData simulation)
void enableComponents (Container container, boolean enable)
TPS_DB_Connector getConnection ()
StyledDocument getConsole ()
File[] getExportFiles ()
String[] getSimKeys ()
void removeServerData (SimulationServerData serverData) throws SQLException
void removeSimulation (SimulationData simulation)
void setBackGroundColorForWorking (String simKey, Component component, boolean selected)
void tableChanged (TableModelEvent e)
void updateServerControl (Map< String, SimulationServerData > serverDataMap)
void updateServerData (SimulationServerData serverData)
void updateSimulationData (SimulationData simulation)
Protected Member Functions
void deleteSelected (Object[][] rows)
void exportSelected (Object[][] rows)
void pauseSelected (Object[][] rows)
void startSelected (Object[][] rows)
Private Member Functions
void addWorkingKey (String... keys)
int containsServerData (SimulationServerData serverData)
int containsSimulation (SimulationData simulation)
Object[][] getSelectedRows ()
String[] getSelectedSimkeys ()
void handleSimulationButtons (int cntsim)
void initDocStyles (StyledDocument console)
void initTables ()
void insertAction ()
void removeWorkingKey (String... keys)
void resetProgressBars ()
void startAnalyzer (int selectedRow)
JFileChooser tumFileChooser (int simcount)
void updateSimulationDescription (String description, String simkey)
void updateTable ()
Private Attributes
final JTextPane cons = new JTextPane()
final StyledDocument console = cons.getStyledDocument()
final JTextField runFilenameField
final ServerColorRenderer blinkCellRenderer
final JPanel tuminfo = new JPanel(new BorderLayout())
File[] exportfiles
IntegratedTUM itum = null
final JPanel serverPanelRight
final SimulationControl control
final JFrame frame
final ConfigurableJTable serverTable
ConfigurableJTable simTable
final Set< String > workingSimKeys = Collections.synchronizedSet(new HashSet<>())
Static Private Attributes
static final int SERVER_INDEX_CORES = 5
static final int SERVER_INDEX_CPU = 4
static final int SERVER_INDEX_IP = 1
static final int SERVER_INDEX_NAME = 0
static final int SERVER_INDEX_ONLINE = 3
static final int SERVER_INDEX_TIMESTAMP = 6
static final int SERVER_INDEX_HASH = 2
static final int SERVER_INDEX_SHUTDOWN = 7
static final int SERVER_INDICES = 8
Detailed Description
GUI of the simulation client.
Author
mark_ma
Definition at line 76 of file SimulationMonitor.java.
Constructor & Destructor Documentation
SimulationMonitor()
de.dlr.ivf.tapas.runtime.client.SimulationMonitor.SimulationMonitor (SimulationControl control)
The constructor builds up the whole GUI
Parameters
control Reference to the control instance of this client
serial UID
Definition at line 158 of file SimulationMonitor.java.
References de.dlr.ivf.tapas.runtime.client.SimulationMonitor.blinkCellRenderer, de.dlr.ivf.tapas.runtime.client.SimulationMonitor.control, de.dlr.ivf.tapas.tools.fileModifier.ExpertKnowledgeHandler.createAndShowGUI(), de.dlr.ivf.tapas.tools.matrixMap.MatrixMapHandler.createAndShowGUI(), de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState.FINISHED, de.dlr.ivf.tapas.runtime.client.SimulationControl.getBuilddate(), de.dlr.ivf.tapas.runtime.client.SimulationControl.getBuildnumber(), de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.getString(), de.dlr.ivf.tapas.runtime.client.SimulationControl.getVersion(), de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.init(), de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState.INSERTED, de.dlr.ivf.tapas.runtime.util.MouseListenerFactory.onClick(), de.dlr.ivf.tapas.runtime.client.SimulationMonitor.SERVER_INDEX_ONLINE, de.dlr.ivf.tapas.runtime.client.SimulationMonitor.SERVER_INDEX_SHUTDOWN, de.dlr.ivf.tapas.runtime.client.SimulationMonitor.serverTable, de.dlr.ivf.tapas.runtime.client.SimulationMonitor.simTable, de.dlr.ivf.tapas.runtime.client.SimulationMonitor.startAnalyzer(), de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState.STARTED, de.dlr.ivf.tapas.runtime.util.ServerControlState.STOP, and de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState.STOPPED.
Member Function Documentation
addServerData()
void de.dlr.ivf.tapas.runtime.client.SimulationMonitor.addServerData (SimulationServerData serverData)
Adds server data to the simulation server table
Parameters
serverData simulation server data to add
Definition at line 780 of file SimulationMonitor.java.
References de.dlr.ivf.tapas.runtime.server.SimulationServerData.getCores(), de.dlr.ivf.tapas.runtime.server.SimulationServerData.getCpu(), de.dlr.ivf.tapas.runtime.server.SimulationServerData.getFormattedTimestamp(), de.dlr.ivf.tapas.runtime.server.SimulationServerData.getHashStatus(), de.dlr.ivf.tapas.runtime.server.SimulationServerData.getIp(), de.dlr.ivf.tapas.runtime.server.SimulationServerData.getName(), de.dlr.ivf.tapas.runtime.server.SimulationServerData.getServerState(), and de.dlr.ivf.tapas.runtime.server.SimulationServerData.isOnline().
addSimulation()
void de.dlr.ivf.tapas.runtime.client.SimulationMonitor.addSimulation (SimulationData simulation)
Adds simulation of the simulation table
Parameters
simulation simulation to add
Definition at line 804 of file SimulationMonitor.java.
References de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState.FINISHED, de.dlr.ivf.tapas.runtime.server.SimulationData.getDescription(), de.dlr.ivf.tapas.runtime.server.SimulationData.getKey(), de.dlr.ivf.tapas.runtime.server.SimulationData.getProgress(), de.dlr.ivf.tapas.runtime.server.SimulationData.getRelativeFileName(), de.dlr.ivf.tapas.runtime.server.SimulationData.getTimestampFinished(), de.dlr.ivf.tapas.runtime.server.SimulationData.getTimestampStarted(), de.dlr.ivf.tapas.runtime.server.SimulationData.getTotal(), de.dlr.ivf.tapas.runtime.server.SimulationData.minimumState(), de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState.STARTED, and de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState.STOPPED.
addWorkingKey()
void de.dlr.ivf.tapas.runtime.client.SimulationMonitor.addWorkingKey (String... keys) private
Definition at line 826 of file SimulationMonitor.java.
containsServerData()
int de.dlr.ivf.tapas.runtime.client.SimulationMonitor.containsServerData (SimulationServerData serverData) private
Parameters
serverData simulation server data to search
Returns
row number of the corresponding entry in the simulation server table, /1 if not found
Definition at line 839 of file SimulationMonitor.java.
References de.dlr.ivf.tapas.runtime.server.SimulationServerData.getIp().
containsSimulation()
int de.dlr.ivf.tapas.runtime.client.SimulationMonitor.containsSimulation (SimulationData simulation) private
Parameters
simulation simulation data to search
Returns
row number of the corresponding entry in the simulation table, -1 if not found
Definition at line 855 of file SimulationMonitor.java.
References de.dlr.ivf.tapas.runtime.server.SimulationData.getKey().
deleteSelected()
void de.dlr.ivf.tapas.runtime.client.SimulationMonitor.deleteSelected (Object rows[][]) protected
Definition at line 866 of file SimulationMonitor.java.
References de.dlr.ivf.tapas.runtime.client.SimulationControl.removeSimulation().
enableComponents()
void de.dlr.ivf.tapas.runtime.client.SimulationMonitor.enableComponents (Container container, boolean enable)
This method either enables or disables all Components inside a specific Container
Parameters
container a Container where all its components should be either enabled or disabled
enable flag specifying whether all components should be enabled (TRUE) or disabled (FALSE)
Definition at line 898 of file SimulationMonitor.java.
exportSelected()
void de.dlr.ivf.tapas.runtime.client.SimulationMonitor.exportSelected (Object rows[][]) protected
Definition at line 908 of file SimulationMonitor.java.
References de.dlr.ivf.tapas.runtime.client.SimulationControl.getConnection().
getConnection()
TPS_DB_Connector de.dlr.ivf.tapas.runtime.client.SimulationMonitor.getConnection ()
Implements de.dlr.ivf.tapas.tools.TUM.ITumInterface.
Definition at line 970 of file SimulationMonitor.java.
References de.dlr.ivf.tapas.runtime.client.SimulationControl.getConnection().
getConsole()
StyledDocument de.dlr.ivf.tapas.runtime.client.SimulationMonitor.getConsole ()
Implements de.dlr.ivf.tapas.tools.TUM.ITumInterface.
Definition at line 976 of file SimulationMonitor.java.
getExportFiles()
File [] de.dlr.ivf.tapas.runtime.client.SimulationMonitor.getExportFiles ()
Implementation of the ITumInterface
Implements de.dlr.ivf.tapas.tools.TUM.ITumInterface.
Definition at line 985 of file SimulationMonitor.java.
getSelectedRows()
Object [][] de.dlr.ivf.tapas.runtime.client.SimulationMonitor.getSelectedRows () private
Definition at line 990 of file SimulationMonitor.java.
getSelectedSimkeys()
String [] de.dlr.ivf.tapas.runtime.client.SimulationMonitor.getSelectedSimkeys () private
Definition at line 1008 of file SimulationMonitor.java.
getSimKeys()
String [] de.dlr.ivf.tapas.runtime.client.SimulationMonitor.getSimKeys ()
Implements de.dlr.ivf.tapas.tools.TUM.ITumInterface.
Definition at line 1018 of file SimulationMonitor.java.
handleSimulationButtons()
void de.dlr.ivf.tapas.runtime.client.SimulationMonitor.handleSimulationButtons (int cntsim) private
Handles the enable status for all buttons below the simulations panel for mouse events occurring in that panel While the IntegratedTUM is also being considered the bTUM button gets handled separately
Parameters
cntsim number of selected simulations in the simulation panel
Definition at line 1029 of file SimulationMonitor.java.
initDocStyles()
void de.dlr.ivf.tapas.runtime.client.SimulationMonitor.initDocStyles (StyledDocument console) private
sets up styles used in the console
Definition at line 1064 of file SimulationMonitor.java.
initTables()
void de.dlr.ivf.tapas.runtime.client.SimulationMonitor.initTables () private
Sets all strings and widths of the tables
Definition at line 1106 of file SimulationMonitor.java.
References de.dlr.ivf.tapas.runtime.util.MultilanguageSupport.getString(), and de.dlr.ivf.tapas.runtime.client.util.table.ConfigurableJTable.initTableColumn().
insertAction()
void de.dlr.ivf.tapas.runtime.client.SimulationMonitor.insertAction () private
This method leads the control to insert a new simulation into the database
Definition at line 1200 of file SimulationMonitor.java.
References de.dlr.ivf.tapas.runtime.client.SimulationControl.addSimulation(), and de.dlr.ivf.tapas.runtime.client.SimulationMonitor.control.
pauseSelected()
void de.dlr.ivf.tapas.runtime.client.SimulationMonitor.pauseSelected (Object rows[][]) protected
Definition at line 1224 of file SimulationMonitor.java.
References de.dlr.ivf.tapas.runtime.client.SimulationControl.changeSimulationDataState().
removeServerData()
void de.dlr.ivf.tapas.runtime.client.SimulationMonitor.removeServerData (SimulationServerData serverData) throws SQLException
Removes server data from the simulation server table
Parameters
serverData simulation server data to remove
Exceptions
SQLException
Definition at line 1257 of file SimulationMonitor.java.
References de.dlr.ivf.tapas.runtime.client.SimulationControl.removeServer().
removeSimulation()
void de.dlr.ivf.tapas.runtime.client.SimulationMonitor.removeSimulation (SimulationData simulation)
Removes simulation of the simulation table
Parameters
simulation simulation to remove
Definition at line 1273 of file SimulationMonitor.java.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationControl.SimulationDataUpdateTask.run().
removeWorkingKey()
void de.dlr.ivf.tapas.runtime.client.SimulationMonitor.removeWorkingKey (String... keys) private
Definition at line 1283 of file SimulationMonitor.java.
resetProgressBars()
void de.dlr.ivf.tapas.runtime.client.SimulationMonitor.resetProgressBars () private
Definition at line 1290 of file SimulationMonitor.java.
setBackGroundColorForWorking()
void de.dlr.ivf.tapas.runtime.client.SimulationMonitor.setBackGroundColorForWorking (String simKey, Component component, boolean selected)
Definition at line 1302 of file SimulationMonitor.java.
startAnalyzer()
void de.dlr.ivf.tapas.runtime.client.SimulationMonitor.startAnalyzer (int selectedRow) private
Definition at line 1308 of file SimulationMonitor.java.
References de.dlr.ivf.tapas.runtime.client.SimulationControl.getParameters().
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitor.SimulationMonitor().
startSelected()
void de.dlr.ivf.tapas.runtime.client.SimulationMonitor.startSelected (Object rows[][]) protected
Definition at line 1315 of file SimulationMonitor.java.
References de.dlr.ivf.tapas.runtime.client.SimulationControl.changeSimulationDataState().
tableChanged()
void de.dlr.ivf.tapas.runtime.client.SimulationMonitor.tableChanged (TableModelEvent e)
performs update if server data changed
Definition at line 1346 of file SimulationMonitor.java.
tumFileChooser()
JFileChooser de.dlr.ivf.tapas.runtime.client.SimulationMonitor.tumFileChooser (int simcount) private
Parameters
simcount number of simulations selected in the simulation panel
Returns
a customized JFileChooser for the IntegratedTUM export
return computed file objects that get passed to IntegratedTUM through ITumInterface
Returns
Definition at line 1373 of file SimulationMonitor.java.
updateServerControl()
void de.dlr.ivf.tapas.runtime.client.SimulationMonitor.updateServerControl (Map< String, SimulationServerData > serverDataMap)
This method updates the server control panel on the right side next to the servers table. It handles the presentation of additional server information and the enable status of the control buttons
Parameters
serverDataMap a map containing hostname as key and SimulationServerData as value
Definition at line 1496 of file SimulationMonitor.java.
References de.dlr.ivf.tapas.runtime.server.SimulationServerData.getServerProcessInfo(), de.dlr.ivf.tapas.runtime.server.SimulationServerData.ServerInfo.IDENTIFIER, de.dlr.ivf.tapas.runtime.server.SimulationServerData.isOnline(), de.dlr.ivf.tapas.runtime.server.SimulationServerData.isRemotelyControllable(), de.dlr.ivf.tapas.runtime.server.SimulationServerData.ServerInfo.PID, de.dlr.ivf.tapas.runtime.server.SimulationServerData.ServerInfo.RUNSINCE, de.dlr.ivf.tapas.runtime.server.SimulationServerData.ServerInfo.SHUTDOWN, and de.dlr.ivf.tapas.runtime.server.SimulationServerData.ServerInfo.WORKON.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationControl.ServerControlUpdateTask.run(), and de.dlr.ivf.tapas.runtime.client.SimulationControl.shutServerDown().
updateServerData()
void de.dlr.ivf.tapas.runtime.client.SimulationMonitor.updateServerData (SimulationServerData serverData)
Updates server data of the simulation server table
Parameters
serverData simulation server data to update
Definition at line 1535 of file SimulationMonitor.java.
References de.dlr.ivf.tapas.runtime.server.SimulationServerData.getCores(), de.dlr.ivf.tapas.runtime.server.SimulationServerData.getCpu(), de.dlr.ivf.tapas.runtime.server.SimulationServerData.getFormattedTimestamp(), de.dlr.ivf.tapas.runtime.server.SimulationServerData.getHashStatus(), de.dlr.ivf.tapas.runtime.server.SimulationServerData.getIp(), de.dlr.ivf.tapas.runtime.server.SimulationServerData.getName(), de.dlr.ivf.tapas.runtime.server.SimulationServerData.getServerState(), and de.dlr.ivf.tapas.runtime.server.SimulationServerData.isOnline().
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationControl.SimulationServerDataUpdateTask.run().
updateSimulationData()
void de.dlr.ivf.tapas.runtime.client.SimulationMonitor.updateSimulationData (SimulationData simulation)
Updates simulation of the simulation table
Parameters
simulation simulation to update
Definition at line 1560 of file SimulationMonitor.java.
References de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState.FINISHED, de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState.getAction(), de.dlr.ivf.tapas.runtime.client.SimulationControl.getCurrentDatabaseTimestamp(), de.dlr.ivf.tapas.runtime.server.SimulationData.getElapsedTime(), de.dlr.ivf.tapas.runtime.server.SimulationData.getEstimatedTime(), de.dlr.ivf.tapas.runtime.server.SimulationData.getProgress(), de.dlr.ivf.tapas.runtime.server.SimulationData.getState(), de.dlr.ivf.tapas.runtime.server.SimulationData.getTimestampFinished(), de.dlr.ivf.tapas.runtime.server.SimulationData.getTimestampStarted(), de.dlr.ivf.tapas.runtime.server.SimulationData.getTotal(), de.dlr.ivf.tapas.runtime.server.SimulationData.minimumState(), de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState.STARTED, and de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState.STOPPED.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationControl.SimulationDataUpdateTask.run().
updateSimulationDescription()
void de.dlr.ivf.tapas.runtime.client.SimulationMonitor.updateSimulationDescription (String description, String simkey) private
Updates the description text of the given simulation in the database.
Parameters
description
simkey
Definition at line 1590 of file SimulationMonitor.java.
References de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeUpdate(), and de.dlr.ivf.tapas.runtime.client.SimulationControl.getConnection().
updateTable()
void de.dlr.ivf.tapas.runtime.client.SimulationMonitor.updateTable () private
Definition at line 1597 of file SimulationMonitor.java.
Member Data Documentation
blinkCellRenderer
final ServerColorRenderer de.dlr.ivf.tapas.runtime.client.SimulationMonitor.blinkCellRenderer private
Definition at line 121 of file SimulationMonitor.java.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitor.SimulationMonitor().
cons
final JTextPane de.dlr.ivf.tapas.runtime.client.SimulationMonitor.cons = new JTextPane() private
Definition at line 115 of file SimulationMonitor.java.
console
final StyledDocument de.dlr.ivf.tapas.runtime.client.SimulationMonitor.console = cons.getStyledDocument() private
Definition at line 116 of file SimulationMonitor.java.
control
final SimulationControl de.dlr.ivf.tapas.runtime.client.SimulationMonitor.control private
Reference to the control instance of this client
Definition at line 138 of file SimulationMonitor.java.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitor.insertAction(), de.dlr.ivf.tapas.runtime.client.SimulationMonitor.ExportThread.run(), de.dlr.ivf.tapas.runtime.client.SimulationMonitor.SimTableButtonEditor.SimTableButtonEditor(), and de.dlr.ivf.tapas.runtime.client.SimulationMonitor.SimulationMonitor().
exportfiles
File [] de.dlr.ivf.tapas.runtime.client.SimulationMonitor.exportfiles private
Definition at line 129 of file SimulationMonitor.java.
frame
final JFrame de.dlr.ivf.tapas.runtime.client.SimulationMonitor.frame private
The GUI frame
Definition at line 142 of file SimulationMonitor.java.
itum
IntegratedTUM de.dlr.ivf.tapas.runtime.client.SimulationMonitor.itum = null private
Definition at line 130 of file SimulationMonitor.java.
runFilenameField
final JTextField de.dlr.ivf.tapas.runtime.client.SimulationMonitor.runFilenameField private
Field with the current run properties filename
Definition at line 120 of file SimulationMonitor.java.
SERVER_INDEX_CORES
final int de.dlr.ivf.tapas.runtime.client.SimulationMonitor.SERVER_INDEX_CORES = 5 static private
Definition at line 78 of file SimulationMonitor.java.
SERVER_INDEX_CPU
final int de.dlr.ivf.tapas.runtime.client.SimulationMonitor.SERVER_INDEX_CPU = 4 static private
Definition at line 79 of file SimulationMonitor.java.
SERVER_INDEX_HASH
final int de.dlr.ivf.tapas.runtime.client.SimulationMonitor.SERVER_INDEX_HASH = 2 static private
Definition at line 84 of file SimulationMonitor.java.
SERVER_INDEX_IP
final int de.dlr.ivf.tapas.runtime.client.SimulationMonitor.SERVER_INDEX_IP = 1 static private
Definition at line 80 of file SimulationMonitor.java.
SERVER_INDEX_NAME
final int de.dlr.ivf.tapas.runtime.client.SimulationMonitor.SERVER_INDEX_NAME = 0 static private
Definition at line 81 of file SimulationMonitor.java.
SERVER_INDEX_ONLINE
final int de.dlr.ivf.tapas.runtime.client.SimulationMonitor.SERVER_INDEX_ONLINE = 3 static private
Definition at line 82 of file SimulationMonitor.java.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitor.SimulationMonitor().
SERVER_INDEX_SHUTDOWN
final int de.dlr.ivf.tapas.runtime.client.SimulationMonitor.SERVER_INDEX_SHUTDOWN = 7 static private
This column will be invisible
Definition at line 88 of file SimulationMonitor.java.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitor.SimulationMonitor().
SERVER_INDEX_TIMESTAMP
final int de.dlr.ivf.tapas.runtime.client.SimulationMonitor.SERVER_INDEX_TIMESTAMP = 6 static private
Definition at line 83 of file SimulationMonitor.java.
SERVER_INDICES
final int de.dlr.ivf.tapas.runtime.client.SimulationMonitor.SERVER_INDICES = 8 static private
Definition at line 89 of file SimulationMonitor.java.
serverPanelRight
final JPanel de.dlr.ivf.tapas.runtime.client.SimulationMonitor.serverPanelRight private
right side next to the servers table
Definition at line 134 of file SimulationMonitor.java.
serverTable
final ConfigurableJTable de.dlr.ivf.tapas.runtime.client.SimulationMonitor.serverTable private
Table with all server information
Definition at line 146 of file SimulationMonitor.java.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitor.SimulationMonitor().
simTable
ConfigurableJTable de.dlr.ivf.tapas.runtime.client.SimulationMonitor.simTable private
Table with all simulation information
Definition at line 150 of file SimulationMonitor.java.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitor.SimulationMonitor().
tuminfo
final JPanel de.dlr.ivf.tapas.runtime.client.SimulationMonitor.tuminfo = new JPanel(new BorderLayout()) private
Definition at line 128 of file SimulationMonitor.java.
workingSimKeys
final Set<String> de.dlr.ivf.tapas.runtime.client.SimulationMonitor.workingSimKeys = Collections.synchronizedSet(new HashSet<>()) private
Definition at line 151 of file SimulationMonitor.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/runtime/client/SimulationMonitor.java