TAPAS: de.dlr.ivf.tapas.tools.TPS_MatrixComparison Class Reference
de.dlr.ivf.tapas.tools.TPS_MatrixComparison Class Reference
Public Member Functions
void analyze (int radix)
void analyzeThis (String table, String matrix1, String matrix2, String path, int binSize)
void analyzeThisTripWeighted (String table, String trips, String matrix1, String matrix2, int[] modes, String path, int binSize)
int[][] loadMatrix (String table, String name)
void loadMatrixces (String table, String matrix1, String matrix2)
void loadTrips (String trips, int[] modes)
void writeDiffData (String filename)
Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_BasicConnectionClass ()
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass)
TPS_BasicConnectionClass (String loginFile)
TPS_BasicConnectionClass (TPS_ParameterClass parameterClass, String loginFile)
boolean checkMatrixName (String matrixName)
TPS_ParameterClass getParameters ()
String readParameter (String simKey, String paramKey)
void storeInDB (String matrixName, double[][] matrix, int decimalPlaces)
Static Public Member Functions
static void main (String[] args)
Static Public Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
static double[][] array1Dto2D (Integer[] matrixVal)
static double[][] array1Dto2D (int[] matrixVal)
static File getRuntimeFile (boolean forceNewFile)
static File getRuntimeFile (String propertyFile, boolean forceNewFile)
static File getRuntimeFile ()
static File getRuntimeFile (String propertyFile)
static int[][] intArray1Dto2D (int[] matrixVal)
static String matrixToSQLArray (double[][] array, int decimalPlaces)
static StringWriter matrixToStringWriterSQL (double[][] array, int decimalPlaces)
Additional Inherited Members
Protected Member Functions inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
void finalize ()
Protected Attributes inherited from de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass
TPS_DB_Connector dbCon = null
TPS_ParameterClass parameterClass
Detailed Description
Definition at line 23 of file TPS_MatrixComparison.java.
Member Function Documentation
analyze()
void de.dlr.ivf.tapas.tools.TPS_MatrixComparison.analyze (int radix)
Definition at line 59 of file TPS_MatrixComparison.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_MatrixComparison.analyzeThis(), and de.dlr.ivf.tapas.tools.TPS_MatrixComparison.analyzeThisTripWeighted().
analyzeThis()
void de.dlr.ivf.tapas.tools.TPS_MatrixComparison.analyzeThis (String table, String matrix1, String matrix2, String path, int binSize)
Definition at line 123 of file TPS_MatrixComparison.java.
References de.dlr.ivf.tapas.tools.TPS_MatrixComparison.analyze(), de.dlr.ivf.tapas.tools.TPS_MatrixComparison.loadMatrixces(), and de.dlr.ivf.tapas.tools.TPS_MatrixComparison.writeDiffData().
Referenced by de.dlr.ivf.tapas.tools.TPS_MatrixComparison.main().
analyzeThisTripWeighted()
void de.dlr.ivf.tapas.tools.TPS_MatrixComparison.analyzeThisTripWeighted (String table, String trips, String matrix1, String matrix2, int[] modes, String path, int binSize)
Definition at line 132 of file TPS_MatrixComparison.java.
References de.dlr.ivf.tapas.tools.TPS_MatrixComparison.analyze(), de.dlr.ivf.tapas.tools.TPS_MatrixComparison.loadMatrixces(), de.dlr.ivf.tapas.tools.TPS_MatrixComparison.loadTrips(), and de.dlr.ivf.tapas.tools.TPS_MatrixComparison.writeDiffData().
loadMatrix()
int [][] de.dlr.ivf.tapas.tools.TPS_MatrixComparison.loadMatrix (String table, String name)
Definition at line 140 of file TPS_MatrixComparison.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.extractIntArray(), de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.intArray1Dto2D(), and name.
Referenced by de.dlr.ivf.tapas.tools.TPS_MatrixComparison.loadMatrixces().
loadMatrixces()
void de.dlr.ivf.tapas.tools.TPS_MatrixComparison.loadMatrixces (String table, String matrix1, String matrix2)
Definition at line 162 of file TPS_MatrixComparison.java.
References de.dlr.ivf.tapas.tools.TPS_MatrixComparison.loadMatrix().
Referenced by de.dlr.ivf.tapas.tools.TPS_MatrixComparison.analyzeThis(), and de.dlr.ivf.tapas.tools.TPS_MatrixComparison.analyzeThisTripWeighted().
loadTrips()
void de.dlr.ivf.tapas.tools.TPS_MatrixComparison.loadTrips (String trips, int[] modes)
Definition at line 167 of file TPS_MatrixComparison.java.
References de.dlr.ivf.tapas.tools.persitence.db.TPS_BasicConnectionClass.dbCon, and de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.executeQuery().
Referenced by de.dlr.ivf.tapas.tools.TPS_MatrixComparison.analyzeThisTripWeighted().
main()
static void de.dlr.ivf.tapas.tools.TPS_MatrixComparison.main (String[] args) static
Definition at line 30 of file TPS_MatrixComparison.java.
References de.dlr.ivf.tapas.tools.TPS_MatrixComparison.analyzeThis().
writeDiffData()
void de.dlr.ivf.tapas.tools.TPS_MatrixComparison.writeDiffData (String filename)
Definition at line 208 of file TPS_MatrixComparison.java.
Referenced by de.dlr.ivf.tapas.tools.TPS_MatrixComparison.analyzeThis(), and de.dlr.ivf.tapas.tools.TPS_MatrixComparison.analyzeThisTripWeighted().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/TPS_MatrixComparison.java