TAPAS: de.dlr.ivf.tapas.person.TPS_PreferenceParameters Class Reference
de.dlr.ivf.tapas.person.TPS_PreferenceParameters Class Reference
Classes
class ChoiceParams
enum ShoppingClass
enum ShoppingPreferenceAccessibility
enum ShoppingPreferenceSupply
Public Member Functions
TPS_PreferenceParameters ()
void readParams ()
Public Attributes
Map< ShoppingClass, Map< ShoppingPreferenceSupply, ChoiceParams > > paramsSupply = new HashMap<>()
Map< ShoppingClass, Map< ShoppingPreferenceAccessibility, ChoiceParams > > paramsAccess = new HashMap<>()
Detailed Description
Class to store all PreferenceParameters for the special choices
Author
hein_mh
Definition at line 19 of file TPS_PreferenceParameters.java.
Constructor & Destructor Documentation
TPS_PreferenceParameters()
de.dlr.ivf.tapas.person.TPS_PreferenceParameters.TPS_PreferenceParameters ()
The constructor allocates all maps and fills it with default values.
Definition at line 26 of file TPS_PreferenceParameters.java.
References de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingClass.valueArray, de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingPreferenceSupply.valueArray, and de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingPreferenceAccessibility.valueArray.
Member Function Documentation
readParams()
void de.dlr.ivf.tapas.person.TPS_PreferenceParameters.readParams ()
Method to read all the choice Parameters. TODO: from DB
Definition at line 48 of file TPS_PreferenceParameters.java.
References de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingPreferenceSupply.Angebot, de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingPreferenceSupply.Erlebnis, de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingPreferenceAccessibility.Erreichbarkeit, de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingPreferenceAccessibility.Kopplung, de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingPreferenceAccessibility.Naehe, de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingClass.NUG, de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingPreferenceSupply.Oeko, de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingPreferenceSupply.Preis, de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingPreferenceSupply.Sonstige, de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingPreferenceAccessibility.Sonstige, de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingClass.TEX, and de.dlr.ivf.tapas.person.TPS_PreferenceParameters.ShoppingClass.UEL.
Referenced by de.dlr.ivf.tapas.person.TPS_Worker.TPS_Worker().
Member Data Documentation
paramsAccess
Map<ShoppingClass, Map<ShoppingPreferenceAccessibility, ChoiceParams> > de.dlr.ivf.tapas.person.TPS_PreferenceParameters.paramsAccess = new HashMap<>()
Definition at line 21 of file TPS_PreferenceParameters.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Preference.computePreferences().
paramsSupply
Map<ShoppingClass, Map<ShoppingPreferenceSupply, ChoiceParams> > de.dlr.ivf.tapas.person.TPS_PreferenceParameters.paramsSupply = new HashMap<>()
Definition at line 20 of file TPS_PreferenceParameters.java.
Referenced by de.dlr.ivf.tapas.person.TPS_Preference.computePreferences().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/person/TPS_PreferenceParameters.java