TAPAS: de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.ReferenceDBReader Class Reference
de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.ReferenceDBReader Class Reference
Public Member Functions
ReferenceDBReader (String referenceKey) throws IOException, ClassNotFoundException
double getCntTrips ()
HashMap< CategoryCombination, QualityChartData > getMoDcValues ()
Static Public Member Functions
static void main (String[] args) throws ClassNotFoundException, IOException
Private Attributes
final TPS_DB_Connector dbCon
final String referenceKey
Static Private Attributes
static final String loginInfo = "T:\\Simulationen\\runtime_perseus.csv"
static final double BERLIN_TRIPS = 3416255 * 3.4
Detailed Description
This class provides an interface to the public table reference.
Author
boec_pa
Definition at line 28 of file ReferenceDBReader.java.
Constructor & Destructor Documentation
ReferenceDBReader()
de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.ReferenceDBReader.ReferenceDBReader (String referenceKey) throws IOException, ClassNotFoundException
Connects to the database.
Parameters
referenceKey the key to the reference (like mid2008).
Exceptions
IOException
ClassNotFoundException
Definition at line 46 of file ReferenceDBReader.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.ReferenceDBReader.dbCon, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.loadRuntimeParameters(), de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.ReferenceDBReader.loginInfo, and de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.ReferenceDBReader.referenceKey.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.ReferenceDBReader.main().
Member Function Documentation
getCntTrips()
double de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.ReferenceDBReader.getCntTrips ()
Definition at line 68 of file ReferenceDBReader.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.ReferenceDBReader.BERLIN_TRIPS.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDBFetcher.getModalSplitData(), and de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDatasetDBFetcher.makeQSChart().
getMoDcValues()
HashMap<CategoryCombination, QualityChartData> de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.ReferenceDBReader.getMoDcValues ()
Assembles absolute numbers in the categories of Mode/DistanceCategory of the given reference.
Returns
null if a problem with the database occurs.
Definition at line 78 of file ReferenceDBReader.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.ReferenceDBReader.BERLIN_TRIPS, de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.ReferenceDBReader.dbCon, de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategoryDefault.getById(), de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Mode.getById(), de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.Quality.getById(), de.dlr.ivf.tapas.persistence.db.TPS_DB_Connector.getConnection(), de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.DistanceCategoryDefault.getDescription(), de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartData.getQuality(), de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartData.getReference(), de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.ReferenceDBReader.referenceKey, and de.dlr.ivf.tapas.analyzer.tum.constants.CategoryCombination.toString().
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChartDBFetcher.getModalSplitData(), de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.ReferenceDBReader.main(), and de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.QualityChartDatasetDBFetcher.makeQSChart().
main()
static void de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.ReferenceDBReader.main (String[] args) throws ClassNotFoundException, IOException static
For testing purposes only.
Definition at line 62 of file ReferenceDBReader.java.
References de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.ReferenceDBReader.getMoDcValues(), and de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.ReferenceDBReader.ReferenceDBReader().
Member Data Documentation
BERLIN_TRIPS
final double de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.ReferenceDBReader.BERLIN_TRIPS = 3416255 * 3.4 static private
number of persons in B times avg mobility rate
Definition at line 34 of file ReferenceDBReader.java.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.ReferenceDBReader.getCntTrips(), and de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.ReferenceDBReader.getMoDcValues().
dbCon
final TPS_DB_Connector de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.ReferenceDBReader.dbCon private
Definition at line 36 of file ReferenceDBReader.java.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.ReferenceDBReader.getMoDcValues(), and de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.ReferenceDBReader.ReferenceDBReader().
loginInfo
final String de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.ReferenceDBReader.loginInfo = "T:\\Simulationen\\runtime_perseus.csv" static private
Definition at line 30 of file ReferenceDBReader.java.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.ReferenceDBReader.ReferenceDBReader().
referenceKey
final String de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.ReferenceDBReader.referenceKey private
Definition at line 37 of file ReferenceDBReader.java.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.ReferenceDBReader.getMoDcValues(), and de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.ReferenceDBReader.ReferenceDBReader().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/runtime/client/Graphics/QualityChart/ReferenceDBReader.java