TAPAS: de.dlr.ivf.tapas.loc.TPS_SelectLocationWeightBased Class Reference
de.dlr.ivf.tapas.loc.TPS_SelectLocationWeightBased Class Reference abstract
Classes
class GravityWeightedResults
class WeightedResult
Public Member Functions
abstract WeightedResult createLocationOption (Result result, double travelTime, double parameter)
abstract double getTravelTime (TPS_Plan plan, TPS_PlanningContext pc, TPS_ModeChoiceContext prevMCC, TPS_ModeChoiceContext nextMCC, TPS_TrafficAnalysisZone taz, TPS_ParameterClass parameterClass)
TPS_Location selectLocationFromChoiceSet (TPS_RegionResultSet choiceSet, TPS_Plan plan, TPS_PlanningContext pc, TPS_LocatedStay locatedStay)
Public Member Functions inherited from de.dlr.ivf.tapas.loc.TPS_LocationSelectModel
void setClassReferences (TPS_Region region, TPS_DB_IOManager pm)
Detailed Description
Definition at line 31 of file TPS_SelectLocationWeightBased.java.
Member Function Documentation
createLocationOption()
abstract WeightedResult de.dlr.ivf.tapas.loc.TPS_SelectLocationWeightBased.createLocationOption (Result result, double travelTime, double parameter) abstract
Reimplemented in de.dlr.ivf.tapas.loc.TPS_SelectWithSingleAccessMode, de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum, de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeGravity, de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessMode, and de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeGravityPow2.
Referenced by de.dlr.ivf.tapas.loc.TPS_SelectLocationWeightBased.selectLocationFromChoiceSet().
getTravelTime()
abstract double de.dlr.ivf.tapas.loc.TPS_SelectLocationWeightBased.getTravelTime (TPS_Plan plan, TPS_PlanningContext pc, TPS_ModeChoiceContext prevMCC, TPS_ModeChoiceContext nextMCC, TPS_TrafficAnalysisZone taz, TPS_ParameterClass parameterClass) abstract
Method to calculate the expected travel time to the locRepresentant.
Parameters
plan
pc
prevMCC
nextMCC
taz
Returns
Reimplemented in de.dlr.ivf.tapas.loc.TPS_SelectWithSingleAccessMode, and de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessMode.
Referenced by de.dlr.ivf.tapas.loc.TPS_SelectLocationWeightBased.selectLocationFromChoiceSet().
selectLocationFromChoiceSet()
TPS_Location de.dlr.ivf.tapas.loc.TPS_SelectLocationWeightBased.selectLocationFromChoiceSet (TPS_RegionResultSet choiceSet, TPS_Plan plan, TPS_PlanningContext pc, TPS_LocatedStay locatedStay)
The interface method to select a location from the given choice set
Parameters
choiceSet the choice set to scan
Returns
the picked location.
Reimplemented from de.dlr.ivf.tapas.loc.TPS_LocationSelectModel.
Reimplemented in de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.
Definition at line 47 of file TPS_SelectLocationWeightBased.java.
References de.dlr.ivf.tapas.mode.TPS_ModeChoiceContext.carForThisPlan, de.dlr.ivf.tapas.plan.TPS_PlanningContext.carForThisPlan, de.dlr.ivf.tapas.loc.TPS_SelectLocationWeightBased.createLocationOption(), de.dlr.ivf.tapas.mode.TPS_ModeChoiceContext.duration, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.FATAL, de.dlr.ivf.tapas.mode.TPS_ModeChoiceContext.fromStay, de.dlr.ivf.tapas.mode.TPS_ModeChoiceContext.fromStayLocation, de.dlr.ivf.tapas.util.parameters.ParamValue.GAMMA_LOCATION_WEIGHT, de.dlr.ivf.tapas.scheme.TPS_Episode.getActCode(), de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.getBbrType(), de.dlr.ivf.tapas.loc.TPS_Region.getCfn(), de.dlr.ivf.tapas.loc.TPS_CFN.getCFN4Value(), de.dlr.ivf.tapas.loc.TPS_CFN.getCFNXValue(), de.dlr.ivf.tapas.constants.TPS_ActivityConstant.getCode(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getDoubleValue(), de.dlr.ivf.tapas.person.TPS_Person.getHousehold(), de.dlr.ivf.tapas.plan.TPS_Plan.getLocatedStay(), de.dlr.ivf.tapas.person.TPS_Household.getLocation(), de.dlr.ivf.tapas.plan.TPS_LocatedStay.getLocation(), de.dlr.ivf.tapas.scheme.TPS_TourPart.TPS_StayHierarchy.getNextStay(), de.dlr.ivf.tapas.scheme.TPS_Episode.getOriginalDuration(), de.dlr.ivf.tapas.scheme.TPS_Episode.getOriginalStart(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.getParameters(), de.dlr.ivf.tapas.loc.TPS_CFN.getParamValue(), de.dlr.ivf.tapas.plan.TPS_Plan.getPerson(), de.dlr.ivf.tapas.loc.TPS_Region.getPotential(), de.dlr.ivf.tapas.scheme.TPS_TourPart.TPS_StayHierarchy.getPrevStay(), de.dlr.ivf.tapas.persistence.TPS_RegionResultSet.getResultIterable(), de.dlr.ivf.tapas.scheme.TPS_Episode.getSchemePart(), de.dlr.ivf.tapas.plan.TPS_LocatedStay.getStay(), de.dlr.ivf.tapas.scheme.TPS_TourPart.getStayHierarchy(), de.dlr.ivf.tapas.loc.TPS_Location.getTrafficAnalysisZone(), de.dlr.ivf.tapas.loc.TPS_SelectLocationWeightBased.getTravelTime(), de.dlr.ivf.tapas.mode.TPS_ModeChoiceContext.isBikeAvailable, de.dlr.ivf.tapas.plan.TPS_PlanningContext.isBikeAvailable, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isDefined(), de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.util.Randomizer.random(), de.dlr.ivf.tapas.mode.TPS_ModeChoiceContext.startTime, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.WARN, and de.dlr.ivf.tapas.constants.TPS_ActivityConstant.TPS_ActivityCodeType.ZBE.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/loc/TPS_SelectLocationWeightBased.java