TAPAS: de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum Class Reference
de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum Class Reference
Classes
class LogSumWeightedResult
Public Member Functions
WeightedResult createLocationOption (Result result, double travelTime, double parameter)
Double getLogSum (TPS_Plan plan, TPS_PlanningContext pc, TPS_ModeChoiceContext prevMCC, TPS_ModeChoiceContext nextMCC, TPS_TrafficAnalysisZone taz, TPS_ParameterClass parameterClass, double mu)
double getModeLogSum (TPS_Plan plan, TPS_PlanningContext pc, TPS_TrafficAnalysisZone taz, double distanceNet, double distanceNetInclReturn, TPS_ModeChoiceContext mcc, TPS_ParameterClass parameterClass, double mu)
TPS_Location selectLocationFromChoiceSet (TPS_RegionResultSet choiceSet, TPS_Plan plan, TPS_PlanningContext pc, TPS_LocatedStay locatedStay)
Public Member Functions inherited from de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessMode
double getTravelTime (TPS_Plan plan, TPS_PlanningContext pc, TPS_ModeChoiceContext prevMCC, TPS_ModeChoiceContext nextMCC, TPS_TrafficAnalysisZone taz, TPS_ParameterClass parameterClass)
Public Member Functions inherited from de.dlr.ivf.tapas.loc.TPS_LocationSelectModel
void setClassReferences (TPS_Region region, TPS_DB_IOManager pm)
Detailed Description
Definition at line 43 of file TPS_SelectWithMultipleAccessModeLogSum.java.
Member Function Documentation
createLocationOption()
WeightedResult de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.createLocationOption (Result result, double travelTime, double parameter)
Reimplemented from de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessMode.
Definition at line 46 of file TPS_SelectWithMultipleAccessModeLogSum.java.
Referenced by de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.selectLocationFromChoiceSet().
getLogSum()
Double de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.getLogSum (TPS_Plan plan, TPS_PlanningContext pc, TPS_ModeChoiceContext prevMCC, TPS_ModeChoiceContext nextMCC, TPS_TrafficAnalysisZone taz, TPS_ParameterClass parameterClass, double mu)
Method to calculate the expected log sum to the locRepresentant.
Parameters
plan
pc
prevMCC
nextMCC
taz
Returns
Definition at line 60 of file TPS_SelectWithMultipleAccessModeLogSum.java.
References de.dlr.ivf.tapas.mode.TPS_ModeChoiceContext.fromStayLocation, de.dlr.ivf.tapas.mode.TPS_Mode.get(), de.dlr.ivf.tapas.mode.TPS_Mode.getDistance(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getDoubleValue(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.getModeLogSum(), de.dlr.ivf.tapas.util.parameters.ParamValue.MIN_DIST, de.dlr.ivf.tapas.util.parameters.SimulationType.SCENARIO, and de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.WALK.
Referenced by de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.selectLocationFromChoiceSet().
getModeLogSum()
double de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.getModeLogSum (TPS_Plan plan, TPS_PlanningContext pc, TPS_TrafficAnalysisZone taz, double distanceNet, double distanceNetInclReturn, TPS_ModeChoiceContext mcc, TPS_ParameterClass parameterClass, double mu)
Definition at line 91 of file TPS_SelectWithMultipleAccessModeLogSum.java.
References de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.BIKE, de.dlr.ivf.tapas.mode.TPS_ModeChoiceContext.carForThisPlan, de.dlr.ivf.tapas.plan.TPS_PlanningContext.carForThisPlan, de.dlr.ivf.tapas.util.TPS_AttributeReader.TPS_Attribute.CURRENT_DISTANCE_CLASS_CODE_MCT, de.dlr.ivf.tapas.util.TPS_AttributeReader.TPS_Attribute.CURRENT_EPISODE_ACTIVITY_CODE_MCT, de.dlr.ivf.tapas.util.TPS_AttributeReader.TPS_Attribute.CURRENT_EPISODE_ACTIVITY_CODE_TAPAS, de.dlr.ivf.tapas.util.TPS_AttributeReader.TPS_Attribute.CURRENT_EPISODE_ACTIVITY_CODE_VOT, de.dlr.ivf.tapas.constants.TPS_ActivityConstant.DUMMY, de.dlr.ivf.tapas.util.TPS_FastMath.exp(), de.dlr.ivf.tapas.util.parameters.ParamFlag.FLAG_USE_TAXI, de.dlr.ivf.tapas.mode.TPS_ModeChoiceContext.fromStayLocation, de.dlr.ivf.tapas.mode.TPS_Mode.get(), de.dlr.ivf.tapas.scheme.TPS_Episode.getActCode(), de.dlr.ivf.tapas.constants.TPS_ActivityConstant.getCode(), de.dlr.ivf.tapas.constants.TPS_Distance.getCode(), de.dlr.ivf.tapas.mode.TPS_ModeDistribution.getDistribution(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getIntValue(), de.dlr.ivf.tapas.mode.TPS_Mode.getParameters(), de.dlr.ivf.tapas.plan.TPS_Plan.getPerson(), de.dlr.ivf.tapas.mode.TPS_Mode.getTravelTime(), de.dlr.ivf.tapas.mode.TPS_Mode.getUtilityFunction(), de.dlr.ivf.tapas.mode.TPS_ModeChoiceContext.isBikeAvailable, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isFalse(), de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.isRestricted, de.dlr.ivf.tapas.person.TPS_Car.isRestricted(), de.dlr.ivf.tapas.mode.TPS_Mode.isType(), de.dlr.ivf.tapas.util.parameters.ParamValue.MAX_WALK_DIST, de.dlr.ivf.tapas.constants.TPS_ActivityConstant.TPS_ActivityCodeType.MCT, de.dlr.ivf.tapas.constants.TPS_Distance.TPS_DistanceCodeType.MCT, de.dlr.ivf.tapas.modechoice.TPS_UtilityFunction.minModeProbability, de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.MIT, de.dlr.ivf.tapas.mode.TPS_Mode.MODE_TYPE_ARRAY, de.dlr.ivf.tapas.mode.TPS_Mode.noConnection(), de.dlr.ivf.tapas.util.parameters.SimulationType.SCENARIO, de.dlr.ivf.tapas.plan.TPS_Plan.setAttributeValue(), de.dlr.ivf.tapas.distribution.TPS_DiscreteDistribution< Key >.size(), de.dlr.ivf.tapas.mode.TPS_ModeChoiceContext.startTime, de.dlr.ivf.tapas.constants.TPS_ActivityConstant.TPS_ActivityCodeType.TAPAS, de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.TAXI, and de.dlr.ivf.tapas.constants.TPS_ActivityConstant.TPS_ActivityCodeType.VOT.
Referenced by de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.getLogSum().
selectLocationFromChoiceSet()
TPS_Location de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.selectLocationFromChoiceSet (TPS_RegionResultSet choiceSet, TPS_Plan plan, TPS_PlanningContext pc, TPS_LocatedStay locatedStay)
The interface method to select a location from the given choice set
Parameters
choiceSet the choice set to scan
Returns
the picked location.
Reimplemented from de.dlr.ivf.tapas.loc.TPS_SelectLocationWeightBased.
Definition at line 162 of file TPS_SelectWithMultipleAccessModeLogSum.java.
References de.dlr.ivf.tapas.mode.TPS_ModeChoiceContext.carForThisPlan, de.dlr.ivf.tapas.plan.TPS_PlanningContext.carForThisPlan, de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.createLocationOption(), de.dlr.ivf.tapas.mode.TPS_ModeChoiceContext.duration, de.dlr.ivf.tapas.util.TPS_FastMath.exp(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.FATAL, de.dlr.ivf.tapas.mode.TPS_ModeChoiceContext.fromStay, de.dlr.ivf.tapas.mode.TPS_ModeChoiceContext.fromStayLocation, de.dlr.ivf.tapas.util.parameters.ParamValue.GAMMA_LOCATION_WEIGHT, de.dlr.ivf.tapas.scheme.TPS_Episode.getActCode(), de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone.getBbrType(), de.dlr.ivf.tapas.loc.TPS_Region.getCfn(), de.dlr.ivf.tapas.loc.TPS_CFN.getCFN4Value(), de.dlr.ivf.tapas.loc.TPS_CFN.getCFNXValue(), de.dlr.ivf.tapas.constants.TPS_ActivityConstant.getCode(), de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.getDoubleValue(), de.dlr.ivf.tapas.person.TPS_Person.getHousehold(), de.dlr.ivf.tapas.plan.TPS_Plan.getLocatedStay(), de.dlr.ivf.tapas.person.TPS_Household.getLocation(), de.dlr.ivf.tapas.plan.TPS_LocatedStay.getLocation(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.getLogSum(), de.dlr.ivf.tapas.scheme.TPS_TourPart.TPS_StayHierarchy.getNextStay(), de.dlr.ivf.tapas.scheme.TPS_Episode.getOriginalDuration(), de.dlr.ivf.tapas.scheme.TPS_Episode.getOriginalStart(), de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.getParameters(), de.dlr.ivf.tapas.loc.TPS_CFN.getParamValue(), de.dlr.ivf.tapas.plan.TPS_Plan.getPerson(), de.dlr.ivf.tapas.loc.TPS_Region.getPotential(), de.dlr.ivf.tapas.scheme.TPS_TourPart.TPS_StayHierarchy.getPrevStay(), de.dlr.ivf.tapas.persistence.TPS_RegionResultSet.getResultIterable(), de.dlr.ivf.tapas.scheme.TPS_Episode.getSchemePart(), de.dlr.ivf.tapas.plan.TPS_LocatedStay.getStay(), de.dlr.ivf.tapas.scheme.TPS_TourPart.getStayHierarchy(), de.dlr.ivf.tapas.loc.TPS_Location.getTrafficAnalysisZone(), de.dlr.ivf.tapas.mode.TPS_Mode.getUtilityFunction(), de.dlr.ivf.tapas.mode.TPS_ModeChoiceContext.isBikeAvailable, de.dlr.ivf.tapas.plan.TPS_PlanningContext.isBikeAvailable, de.dlr.ivf.tapas.util.parameters.TPS_ParameterClass.isDefined(), de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.util.parameters.ParamValue.LOGSUM_CALIB_EDUCATION, de.dlr.ivf.tapas.util.parameters.ParamValue.LOGSUM_CALIB_ERRANT, de.dlr.ivf.tapas.util.parameters.ParamValue.LOGSUM_CALIB_FREETIME, de.dlr.ivf.tapas.util.parameters.ParamValue.LOGSUM_CALIB_FREETIME_HOME, de.dlr.ivf.tapas.util.parameters.ParamValue.LOGSUM_CALIB_MISC, de.dlr.ivf.tapas.util.parameters.ParamValue.LOGSUM_CALIB_SHOP, de.dlr.ivf.tapas.util.parameters.ParamValue.LOGSUM_CALIB_STUDENT, de.dlr.ivf.tapas.util.parameters.ParamValue.LOGSUM_CALIB_WORK, de.dlr.ivf.tapas.util.parameters.ParamValue.LOGSUM_INTERACT_MU, de.dlr.ivf.tapas.util.parameters.ParamValue.LOGSUM_WEIGHT_MU, de.dlr.ivf.tapas.util.Randomizer.random(), de.dlr.ivf.tapas.mode.TPS_ModeChoiceContext.startTime, de.dlr.ivf.tapas.constants.TPS_ActivityConstant.TPS_ActivityCodeType.TAPAS, de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.WARN, and de.dlr.ivf.tapas.constants.TPS_ActivityConstant.TPS_ActivityCodeType.ZBE.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/loc/TPS_SelectWithMultipleAccessModeLogSum.java