TAPAS: de.dlr.ivf.tapas.util.TPS_VariableMap Class Reference
de.dlr.ivf.tapas.util.TPS_VariableMap Class Reference
Public Member Functions
TPS_VariableMap ()
TPS_VariableMap (Collection< TPS_Attribute > attributes)
TPS_VariableMap (Collection< TPS_Attribute > attributeList, double defaultValue)
void addValue (List< Integer > codes, double value)
Map< TPS_Attribute, Integer > getAttributeMap ()
String getLastRequest ()
double getValue (Map< TPS_Attribute, Integer > map)
void init (Collection< TPS_Attribute > attributeList)
void init (Collection< TPS_Attribute > attributeList, double defaultValue)
String toString ()
Private Member Functions
String toString (Map< Integer, Double > valueMap, String prefix)
String toString (Map< Integer, Map< Integer, ?>> mappedMap, String prefix, int depth)
Private Attributes
final Map< Thread, Map< TPS_Attribute, Integer > > attributeMap
final List< TPS_Attribute > attributes
final Map< Thread, String > lastRequest
double value
Map< Integer, ?> vMap
Detailed Description
This map is a dynamic nested map for attributed values, i.t. you can define a file with a tree structure. At each leaf there has to be a double value. The values for the branches have to be readable by the TPS_AttributeReader.
Definition at line 19 of file TPS_VariableMap.java.
Constructor & Destructor Documentation
TPS_VariableMap() [1/3]
de.dlr.ivf.tapas.util.TPS_VariableMap.TPS_VariableMap ()
Definition at line 39 of file TPS_VariableMap.java.
TPS_VariableMap() [2/3]
de.dlr.ivf.tapas.util.TPS_VariableMap.TPS_VariableMap (Collection< TPS_Attribute > attributes)
Default constructor initialises the attributes list and the source map
Parameters
attributes
Definition at line 50 of file TPS_VariableMap.java.
References de.dlr.ivf.tapas.util.TPS_VariableMap.attributes.
TPS_VariableMap() [3/3]
de.dlr.ivf.tapas.util.TPS_VariableMap.TPS_VariableMap (Collection< TPS_Attribute > attributeList, double defaultValue)
Calls default constructor and sets the default value
Parameters
attributeList
defaultValue
Definition at line 60 of file TPS_VariableMap.java.
References de.dlr.ivf.tapas.util.TPS_VariableMap.init().
Member Function Documentation
addValue()
void de.dlr.ivf.tapas.util.TPS_VariableMap.addValue (List< Integer > codes, double value)
Adds a new leaf to the tree
Parameters
codes list of codes corresponding to the attributes list
value the leaf value
Definition at line 72 of file TPS_VariableMap.java.
References code, and de.dlr.ivf.tapas.util.TPS_VariableMap.value.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readVariableMap().
getAttributeMap()
Map<TPS_Attribute, Integer> de.dlr.ivf.tapas.util.TPS_VariableMap.getAttributeMap ()
Definition at line 105 of file TPS_VariableMap.java.
getLastRequest()
String de.dlr.ivf.tapas.util.TPS_VariableMap.getLastRequest ()
This method returns the last request which was consumed by the variable map
Returns
last request
Definition at line 121 of file TPS_VariableMap.java.
References de.dlr.ivf.tapas.util.TPS_VariableMap.lastRequest.
getValue()
double de.dlr.ivf.tapas.util.TPS_VariableMap.getValue (Map< TPS_Attribute, Integer > map)
This method walks through the tree by reading the attributes out of the plan down to a leaf and return the value. If the leaf does not exist a default value is returned
Parameters
map the map of attributes
Returns
leaf value
Definition at line 183 of file TPS_VariableMap.java.
References de.dlr.ivf.tapas.util.TPS_VariableMap.value.
init() [1/2]
void de.dlr.ivf.tapas.util.TPS_VariableMap.init (Collection< TPS_Attribute > attributeList)
This method initialises the attribute list with the default value of -1.
Parameters
attributeList list of attributes
Definition at line 231 of file TPS_VariableMap.java.
Referenced by de.dlr.ivf.tapas.util.TPS_VariableMap.TPS_VariableMap().
init() [2/2]
void de.dlr.ivf.tapas.util.TPS_VariableMap.init (Collection< TPS_Attribute > attributeList, double defaultValue)
This method initialises the attribute list with the given default value.
Parameters
attributeList list of attributes
defaultValue default value for all attributes
Definition at line 241 of file TPS_VariableMap.java.
toString() [1/3]
String de.dlr.ivf.tapas.util.TPS_VariableMap.toString ()
Definition at line 260 of file TPS_VariableMap.java.
Referenced by de.dlr.ivf.tapas.util.TPS_VariableMap.toString().
toString() [2/3]
String de.dlr.ivf.tapas.util.TPS_VariableMap.toString (Map< Integer, Double > valueMap, String prefix) private
This method prints this map into a String
Parameters
valueMap value map at a leaf
prefix line prefix
Returns
printed value map
Definition at line 282 of file TPS_VariableMap.java.
toString() [3/3]
String de.dlr.ivf.tapas.util.TPS_VariableMap.toString (Map< Integer, Map< Integer, ?>> mappedMap, String prefix, int depth) private
This method prints this map into a String.
Parameters
mappedMap current branch
prefix line prefix
depth current depth in tree
Returns
printed mapped map
Definition at line 299 of file TPS_VariableMap.java.
References de.dlr.ivf.tapas.util.TPS_VariableMap.toString().
Member Data Documentation
attributeMap
final Map<Thread, Map<TPS_Attribute, Integer> > de.dlr.ivf.tapas.util.TPS_VariableMap.attributeMap private
Definition at line 21 of file TPS_VariableMap.java.
attributes
final List<TPS_Attribute> de.dlr.ivf.tapas.util.TPS_VariableMap.attributes private
List of attributes which describe each layer of the tree
Definition at line 25 of file TPS_VariableMap.java.
Referenced by de.dlr.ivf.tapas.util.TPS_VariableMap.TPS_VariableMap().
lastRequest
final Map<Thread, String> de.dlr.ivf.tapas.util.TPS_VariableMap.lastRequest private
Debug string which stores the last request
Definition at line 29 of file TPS_VariableMap.java.
Referenced by de.dlr.ivf.tapas.util.TPS_VariableMap.getLastRequest().
value
double de.dlr.ivf.tapas.util.TPS_VariableMap.value private
This value is returned when no appropriate leaf is found
Definition at line 33 of file TPS_VariableMap.java.
Referenced by de.dlr.ivf.tapas.util.TPS_VariableMap.addValue(), and de.dlr.ivf.tapas.util.TPS_VariableMap.getValue().
vMap
Map<Integer, ?> de.dlr.ivf.tapas.util.TPS_VariableMap.vMap private
Source map of the tree
Definition at line 37 of file TPS_VariableMap.java.
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/util/TPS_VariableMap.java