TAPAS: de.dlr.ivf.tapas.analyzer.inputfileconverter.TPS_FileReader Class Reference
de.dlr.ivf.tapas.analyzer.inputfileconverter.TPS_FileReader Class Reference
Public Member Functions
TPS_FileReader (String fileName, boolean hasHeader) throws FileNotFoundException, IOException
String getFileName ()
String[] getHeaders () throws IOException
String[] getRecord () throws IOException
Private Attributes
final String fileName
final CsvReader reader
Detailed Description
This class provides basic methods to open and read from a comma separated value file via a CsvReader. You can receive the headers and each record, i.e. a line in the file. A method to check the header is also provided
important The method for checking the headers is not implemented, therefore it is depreciated. If you implement it, remove this comment and the deprecation statement.
Author
mark_ma
Definition at line 24 of file TPS_FileReader.java.
Constructor & Destructor Documentation
TPS_FileReader()
de.dlr.ivf.tapas.analyzer.inputfileconverter.TPS_FileReader.TPS_FileReader (String fileName, boolean hasHeader) throws FileNotFoundException, IOException
This constructor builds a CsvReader from the given file.
Parameters
fileName The filename of the file
Exceptions
FileNotFoundException This exception is thrown if the file doesn't exist
IOException This exception is thrown if there is no permission to open the file or read from it
Definition at line 43 of file TPS_FileReader.java.
References de.dlr.ivf.tapas.analyzer.inputfileconverter.TPS_FileReader.fileName, and de.dlr.ivf.tapas.analyzer.inputfileconverter.TPS_FileReader.getFileName().
Member Function Documentation
getFileName()
String de.dlr.ivf.tapas.analyzer.inputfileconverter.TPS_FileReader.getFileName ()
Returns the name of the file
Returns
filename
Definition at line 58 of file TPS_FileReader.java.
References de.dlr.ivf.tapas.analyzer.inputfileconverter.TPS_FileReader.fileName.
Referenced by de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripConverter.convertNextTrip(), de.dlr.ivf.tapas.analyzer.inputfileconverter.PersonFileConverter.convertPersonFileElements(), and de.dlr.ivf.tapas.analyzer.inputfileconverter.TPS_FileReader.TPS_FileReader().
getHeaders()
String [] de.dlr.ivf.tapas.analyzer.inputfileconverter.TPS_FileReader.getHeaders () throws IOException
This method should be called only once, because it reads one record of the file. Usually this method can be called after opening the file.
Returns
header of the file
Exceptions
IOException this exception is thrown when the file is already closed
Definition at line 68 of file TPS_FileReader.java.
References de.dlr.ivf.tapas.analyzer.inputfileconverter.TPS_FileReader.reader.
Referenced by de.dlr.ivf.tapas.analyzer.inputfileconverter.PersonFileConverter.PersonFileConverter(), and de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripConverter.TapasTripConverter().
getRecord()
String [] de.dlr.ivf.tapas.analyzer.inputfileconverter.TPS_FileReader.getRecord () throws IOException
Returns the next line of the file, separated in a String array
Returns
the next line of the file
Exceptions
IOException this exception is thrown if anything in the reading process of the record produces an exception
Definition at line 78 of file TPS_FileReader.java.
References de.dlr.ivf.tapas.analyzer.inputfileconverter.TPS_FileReader.reader.
Referenced by de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripConverter.convertNextTrip(), and de.dlr.ivf.tapas.analyzer.inputfileconverter.PersonFileConverter.convertPersonFileElements().
Member Data Documentation
fileName
final String de.dlr.ivf.tapas.analyzer.inputfileconverter.TPS_FileReader.fileName private
The filename of the file
Definition at line 29 of file TPS_FileReader.java.
Referenced by de.dlr.ivf.tapas.analyzer.inputfileconverter.TPS_FileReader.getFileName(), and de.dlr.ivf.tapas.analyzer.inputfileconverter.TPS_FileReader.TPS_FileReader().
reader
final CsvReader de.dlr.ivf.tapas.analyzer.inputfileconverter.TPS_FileReader.reader private
The Reader of the file
Definition at line 34 of file TPS_FileReader.java.
Referenced by de.dlr.ivf.tapas.analyzer.inputfileconverter.TPS_FileReader.getHeaders(), and de.dlr.ivf.tapas.analyzer.inputfileconverter.TPS_FileReader.getRecord().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/inputfileconverter/TPS_FileReader.java