TAPAS: de.dlr.ivf.tapas.constants.TPS_PersonGroup Class Reference
de.dlr.ivf.tapas.constants.TPS_PersonGroup Class Reference
Public Member Functions
TPS_PersonGroup (int code, String description, int ageClass, int minAge, int maxAge, int cars, int sex, String personType, String hasChild)
int getMinAge ()
void setMinAge (int minAge)
int getMaxAge ()
void setMaxAge (int maxAge)
void addPersonGroupToMap ()
int compareTo (TPS_PersonGroup persGroup)
boolean fits (TPS_Person person)
String getDescription ()
int getCode ()
TPS_PersonType getPersonType ()
void setDescription (String description)
TPS_Sex getSex ()
boolean isChild ()
boolean isPupil ()
boolean isStudent ()
String toString ()
String toString (boolean extended)
Static Public Member Functions
static void clearPersonGroupMap ()
static Collection< TPS_PersonGroup > getConstants ()
static TPS_PersonGroup getPersonGroupByCode (int code)
static TPS_PersonGroup getPersonGroupOfPerson (TPS_Person person)
Static Public Attributes
static boolean USE_GROUP_COLUMN_FOR_PERSON_GROUPS
Private Member Functions
List< TPS_AgeClass > getAgeClasses ()
void setAgeClasses (List< TPS_AgeClass > ageClasses)
TPS_CarCode getCarCode ()
void setCarCode (TPS_CarCode carCode)
void setPersonType (TPS_PersonType persType)
void setHasChildCode (TPS_HasChildCode hasChildCode)
TPS_HasChildCode getHasChildCode ()
void setSex (TPS_Sex sex)
Private Attributes
List< TPS_AgeClass > ageClasses
int minAge
int maxAge
TPS_CarCode carCode
TPS_HasChildCode hasChildCode
TPS_PersonType personType
TPS_Sex sex
int code
String description
Static Private Attributes
static final HashMap< Integer, TPS_PersonGroup > PERSON_GROUP_MAP = new HashMap<>()
Detailed Description
This class represents the person groups of TAPAS. Each person group contains of one sex, one car constant and some age classes. The age classes have a finer granularity than the person groups, so a person group have to store more than one age class. There also exist a fits*(method to check whether a person fits to the person group constant.
Definition at line 25 of file TPS_PersonGroup.java.
Constructor & Destructor Documentation
TPS_PersonGroup()
de.dlr.ivf.tapas.constants.TPS_PersonGroup.TPS_PersonGroup (int code, String description, int ageClass, int minAge, int maxAge, int cars, int sex, String personType, String hasChild)
Definition at line 57 of file TPS_PersonGroup.java.
References de.dlr.ivf.tapas.constants.TPS_PersonGroup.code, de.dlr.ivf.tapas.constants.TPS_PersonGroup.description, de.dlr.ivf.tapas.constants.TPS_AgeClass.getConstants(), de.dlr.ivf.tapas.constants.TPS_CarCode.getEnum(), de.dlr.ivf.tapas.constants.TPS_Sex.getEnum(), de.dlr.ivf.tapas.constants.TPS_AgeClass.TPS_AgeCodeType.PersGroup, de.dlr.ivf.tapas.constants.TPS_PersonGroup.personType, de.dlr.ivf.tapas.constants.TPS_PersonGroup.setAgeClasses(), de.dlr.ivf.tapas.constants.TPS_PersonGroup.setCarCode(), de.dlr.ivf.tapas.constants.TPS_PersonGroup.setHasChildCode(), de.dlr.ivf.tapas.constants.TPS_PersonGroup.setMaxAge(), de.dlr.ivf.tapas.constants.TPS_PersonGroup.setMinAge(), de.dlr.ivf.tapas.constants.TPS_PersonGroup.setPersonType(), de.dlr.ivf.tapas.constants.TPS_PersonGroup.setSex(), and de.dlr.ivf.tapas.constants.TPS_PersonGroup.sex.
Member Function Documentation
addPersonGroupToMap()
void de.dlr.ivf.tapas.constants.TPS_PersonGroup.addPersonGroupToMap ()
Add to static collection of all person groups constants. The objects are accessed by their ids from the db.
Definition at line 139 of file TPS_PersonGroup.java.
References de.dlr.ivf.tapas.constants.TPS_PersonGroup.code, and de.dlr.ivf.tapas.constants.TPS_PersonGroup.PERSON_GROUP_MAP.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readPersonGroupCodes().
clearPersonGroupMap()
static void de.dlr.ivf.tapas.constants.TPS_PersonGroup.clearPersonGroupMap () static
Empties the global static person group map
Definition at line 90 of file TPS_PersonGroup.java.
References de.dlr.ivf.tapas.constants.TPS_PersonGroup.PERSON_GROUP_MAP.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.clearConstants().
compareTo()
int de.dlr.ivf.tapas.constants.TPS_PersonGroup.compareTo (TPS_PersonGroup persGroup)
Definition at line 143 of file TPS_PersonGroup.java.
References de.dlr.ivf.tapas.constants.TPS_PersonGroup.getCode().
fits()
boolean de.dlr.ivf.tapas.constants.TPS_PersonGroup.fits (TPS_Person person)
This method checks the following attributes:
a) TPS_AgeClass: Checks if the person's age class is included in the person group
b) TPS_Sex: checks the sex of person and group
c) TPS_CarCode: checks whether the amount of cars in the person's household corresponds with the constant in car d) TPS_HasChildCode checks whether the number of children in the person's household corresponds to the HasChildCode constant in the person group constant.
Parameters
person which is checked against the person group
Returns
true if the person attributes fit with the person group constant
Definition at line 158 of file TPS_PersonGroup.java.
References de.dlr.ivf.tapas.constants.TPS_CarCode.fits(), de.dlr.ivf.tapas.constants.TPS_HasChildCode.fits(), de.dlr.ivf.tapas.constants.TPS_Sex.fits(), de.dlr.ivf.tapas.person.TPS_Person.getAge(), de.dlr.ivf.tapas.constants.TPS_PersonGroup.getCarCode(), de.dlr.ivf.tapas.constants.TPS_PersonGroup.getHasChildCode(), de.dlr.ivf.tapas.person.TPS_Person.getHousehold(), de.dlr.ivf.tapas.constants.TPS_PersonGroup.getMaxAge(), de.dlr.ivf.tapas.constants.TPS_PersonGroup.getMinAge(), de.dlr.ivf.tapas.person.TPS_Household.getNumberOfCars(), de.dlr.ivf.tapas.person.TPS_Household.getNumChildren(), de.dlr.ivf.tapas.constants.TPS_PersonGroup.getPersonType(), de.dlr.ivf.tapas.constants.TPS_PersonType.getPersonTypeByStatus(), de.dlr.ivf.tapas.constants.TPS_PersonGroup.getSex(), de.dlr.ivf.tapas.person.TPS_Person.getSex(), and de.dlr.ivf.tapas.person.TPS_Person.getStatus().
getAgeClasses()
List<TPS_AgeClass> de.dlr.ivf.tapas.constants.TPS_PersonGroup.getAgeClasses () private
Returns the age categories; see TPS_AgeClass
Returns
return all age classes
Definition at line 172 of file TPS_PersonGroup.java.
References de.dlr.ivf.tapas.constants.TPS_PersonGroup.ageClasses.
getCarCode()
TPS_CarCode de.dlr.ivf.tapas.constants.TPS_PersonGroup.getCarCode () private
Returns the categories for car availability in the household; see TPS_CarCode
Returns
cars
Definition at line 194 of file TPS_PersonGroup.java.
References de.dlr.ivf.tapas.constants.TPS_PersonGroup.carCode.
Referenced by de.dlr.ivf.tapas.constants.TPS_PersonGroup.fits().
getCode()
int de.dlr.ivf.tapas.constants.TPS_PersonGroup.getCode ()
Definition at line 208 of file TPS_PersonGroup.java.
References de.dlr.ivf.tapas.constants.TPS_PersonGroup.code.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IOManager.batchStoreTrips(), de.dlr.ivf.tapas.constants.TPS_PersonGroup.compareTo(), de.dlr.ivf.tapas.plan.TPS_Plan.createOutput(), de.dlr.ivf.tapas.constants.TPS_PersonGroup.toString(), de.dlr.ivf.tapas.plan.TPS_Plan.TPS_Plan(), and de.dlr.ivf.tapas.plan.TPS_Plan.writeOutputStream().
getConstants()
static Collection<TPS_PersonGroup> de.dlr.ivf.tapas.constants.TPS_PersonGroup.getConstants () static
Returns a collection/view of the values of the PERSON_GROUP_MAP, i.e. all stored person group constants Note: changes in the map are reflected in the collection and vice-versa
Returns
a collection/view of the values of the PERSON_GROUP_MAP
Definition at line 100 of file TPS_PersonGroup.java.
References de.dlr.ivf.tapas.constants.TPS_PersonGroup.PERSON_GROUP_MAP.
getDescription()
String de.dlr.ivf.tapas.constants.TPS_PersonGroup.getDescription ()
Definition at line 176 of file TPS_PersonGroup.java.
References de.dlr.ivf.tapas.constants.TPS_PersonGroup.description.
getHasChildCode()
TPS_HasChildCode de.dlr.ivf.tapas.constants.TPS_PersonGroup.getHasChildCode () private
Definition at line 239 of file TPS_PersonGroup.java.
References de.dlr.ivf.tapas.constants.TPS_PersonGroup.hasChildCode.
Referenced by de.dlr.ivf.tapas.constants.TPS_PersonGroup.fits().
getMaxAge()
int de.dlr.ivf.tapas.constants.TPS_PersonGroup.getMaxAge ()
Definition at line 79 of file TPS_PersonGroup.java.
References de.dlr.ivf.tapas.constants.TPS_PersonGroup.maxAge.
Referenced by de.dlr.ivf.tapas.constants.TPS_PersonGroup.fits().
getMinAge()
int de.dlr.ivf.tapas.constants.TPS_PersonGroup.getMinAge ()
Definition at line 71 of file TPS_PersonGroup.java.
References de.dlr.ivf.tapas.constants.TPS_PersonGroup.minAge.
Referenced by de.dlr.ivf.tapas.constants.TPS_PersonGroup.fits().
getPersonGroupByCode()
static TPS_PersonGroup de.dlr.ivf.tapas.constants.TPS_PersonGroup.getPersonGroupByCode (int code) static
Parameters
code person group code from the db
Returns
person group object for a given TPS_PersonGroupType and code (int)
Definition at line 108 of file TPS_PersonGroup.java.
References de.dlr.ivf.tapas.constants.TPS_PersonGroup.code, and de.dlr.ivf.tapas.constants.TPS_PersonGroup.PERSON_GROUP_MAP.
Referenced by de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readSchemeSet().
getPersonGroupOfPerson()
static TPS_PersonGroup de.dlr.ivf.tapas.constants.TPS_PersonGroup.getPersonGroupOfPerson (TPS_Person person) static
Parameters
person of who the group is determined
Returns
person group object for a given person
Definition at line 116 of file TPS_PersonGroup.java.
References de.dlr.ivf.tapas.log.TPS_LoggingInterface.SeverenceLogLevel.ERROR, de.dlr.ivf.tapas.person.TPS_Person.getGroup(), de.dlr.ivf.tapas.log.TPS_Logger.isLogging(), de.dlr.ivf.tapas.log.TPS_Logger.log(), de.dlr.ivf.tapas.log.TPS_LoggingInterface.HierarchyLogLevel.PERSON, de.dlr.ivf.tapas.constants.TPS_PersonGroup.PERSON_GROUP_MAP, de.dlr.ivf.tapas.person.TPS_Person.toString(), and de.dlr.ivf.tapas.constants.TPS_PersonGroup.USE_GROUP_COLUMN_FOR_PERSON_GROUPS.
Referenced by de.dlr.ivf.tapas.person.TPS_Person.getPersonGroup().
getPersonType()
TPS_PersonType de.dlr.ivf.tapas.constants.TPS_PersonGroup.getPersonType ()
Returns the type of the person; see TPS_PersonType
Returns
person type
Definition at line 217 of file TPS_PersonGroup.java.
References de.dlr.ivf.tapas.constants.TPS_PersonGroup.personType.
Referenced by de.dlr.ivf.tapas.constants.TPS_PersonGroup.fits(), de.dlr.ivf.tapas.mode.TPS_MassTransportMode.getTravelTime(), de.dlr.ivf.tapas.constants.TPS_PersonGroup.isChild(), de.dlr.ivf.tapas.constants.TPS_PersonGroup.isPupil(), and de.dlr.ivf.tapas.constants.TPS_PersonGroup.isStudent().
getSex()
TPS_Sex de.dlr.ivf.tapas.constants.TPS_PersonGroup.getSex ()
Returns the sex of the person; see TPS_Sex
Returns
sex
Definition at line 248 of file TPS_PersonGroup.java.
References de.dlr.ivf.tapas.constants.TPS_PersonGroup.sex.
Referenced by de.dlr.ivf.tapas.constants.TPS_PersonGroup.fits().
isChild()
boolean de.dlr.ivf.tapas.constants.TPS_PersonGroup.isChild ()
States if the person is a child, that means the person is before school-age!
Returns
true if the constant represents a child, false otherwise
Definition at line 266 of file TPS_PersonGroup.java.
References de.dlr.ivf.tapas.constants.TPS_PersonType.CHILD, and de.dlr.ivf.tapas.constants.TPS_PersonGroup.getPersonType().
isPupil()
boolean de.dlr.ivf.tapas.constants.TPS_PersonGroup.isPupil ()
States if the person is a pupil, that means the person goes to school
Returns
true if the constant represents a pupil, false otherwise
Definition at line 275 of file TPS_PersonGroup.java.
References de.dlr.ivf.tapas.constants.TPS_PersonGroup.getPersonType(), and de.dlr.ivf.tapas.constants.TPS_PersonType.PUPIL.
isStudent()
boolean de.dlr.ivf.tapas.constants.TPS_PersonGroup.isStudent ()
States if the person is a student (university)
Returns
true if the constant represents a student, false otherwise
Definition at line 284 of file TPS_PersonGroup.java.
References de.dlr.ivf.tapas.constants.TPS_PersonGroup.getPersonType(), and de.dlr.ivf.tapas.constants.TPS_PersonType.STUDENT.
setAgeClasses()
void de.dlr.ivf.tapas.constants.TPS_PersonGroup.setAgeClasses (List< TPS_AgeClass > ageClasses) private
Sets age classes.
Parameters
ageClasses list of of age classes objects
Definition at line 185 of file TPS_PersonGroup.java.
References de.dlr.ivf.tapas.constants.TPS_PersonGroup.ageClasses.
Referenced by de.dlr.ivf.tapas.constants.TPS_PersonGroup.TPS_PersonGroup().
setCarCode()
void de.dlr.ivf.tapas.constants.TPS_PersonGroup.setCarCode (TPS_CarCode carCode) private
Sets CarCode.
Parameters
carCode set carCode
Definition at line 203 of file TPS_PersonGroup.java.
References de.dlr.ivf.tapas.constants.TPS_PersonGroup.carCode.
Referenced by de.dlr.ivf.tapas.constants.TPS_PersonGroup.TPS_PersonGroup().
setDescription()
void de.dlr.ivf.tapas.constants.TPS_PersonGroup.setDescription (String description)
Definition at line 221 of file TPS_PersonGroup.java.
References de.dlr.ivf.tapas.constants.TPS_PersonGroup.description.
setHasChildCode()
void de.dlr.ivf.tapas.constants.TPS_PersonGroup.setHasChildCode (TPS_HasChildCode hasChildCode) private
Definition at line 235 of file TPS_PersonGroup.java.
References de.dlr.ivf.tapas.constants.TPS_PersonGroup.hasChildCode.
Referenced by de.dlr.ivf.tapas.constants.TPS_PersonGroup.TPS_PersonGroup().
setMaxAge()
void de.dlr.ivf.tapas.constants.TPS_PersonGroup.setMaxAge (int maxAge)
Definition at line 83 of file TPS_PersonGroup.java.
References de.dlr.ivf.tapas.constants.TPS_PersonGroup.maxAge.
Referenced by de.dlr.ivf.tapas.constants.TPS_PersonGroup.TPS_PersonGroup().
setMinAge()
void de.dlr.ivf.tapas.constants.TPS_PersonGroup.setMinAge (int minAge)
Definition at line 75 of file TPS_PersonGroup.java.
References de.dlr.ivf.tapas.constants.TPS_PersonGroup.minAge.
Referenced by de.dlr.ivf.tapas.constants.TPS_PersonGroup.TPS_PersonGroup().
setPersonType()
void de.dlr.ivf.tapas.constants.TPS_PersonGroup.setPersonType (TPS_PersonType persType) private
Sets person type.
Parameters
persType new person type for the person type field
Definition at line 230 of file TPS_PersonGroup.java.
Referenced by de.dlr.ivf.tapas.constants.TPS_PersonGroup.TPS_PersonGroup().
setSex()
void de.dlr.ivf.tapas.constants.TPS_PersonGroup.setSex (TPS_Sex sex) private
Sets sex.
Parameters
sex new sex code
Definition at line 257 of file TPS_PersonGroup.java.
References de.dlr.ivf.tapas.constants.TPS_PersonGroup.sex.
Referenced by de.dlr.ivf.tapas.constants.TPS_PersonGroup.TPS_PersonGroup().
toString() [1/2]
String de.dlr.ivf.tapas.constants.TPS_PersonGroup.toString ()
Definition at line 288 of file TPS_PersonGroup.java.
References de.dlr.ivf.tapas.constants.TPS_PersonGroup.getCode().
Referenced by de.dlr.ivf.tapas.constants.TPS_PersonGroup.toString().
toString() [2/2]
String de.dlr.ivf.tapas.constants.TPS_PersonGroup.toString (boolean extended)
Definition at line 292 of file TPS_PersonGroup.java.
References de.dlr.ivf.tapas.constants.TPS_PersonGroup.toString().
Member Data Documentation
ageClasses
List<TPS_AgeClass> de.dlr.ivf.tapas.constants.TPS_PersonGroup.ageClasses private
List of all age classes the person group constant contains
Definition at line 35 of file TPS_PersonGroup.java.
Referenced by de.dlr.ivf.tapas.constants.TPS_PersonGroup.getAgeClasses(), and de.dlr.ivf.tapas.constants.TPS_PersonGroup.setAgeClasses().
carCode
TPS_CarCode de.dlr.ivf.tapas.constants.TPS_PersonGroup.carCode private
number of cars in the household
Definition at line 41 of file TPS_PersonGroup.java.
Referenced by de.dlr.ivf.tapas.constants.TPS_PersonGroup.getCarCode(), and de.dlr.ivf.tapas.constants.TPS_PersonGroup.setCarCode().
code
int de.dlr.ivf.tapas.constants.TPS_PersonGroup.code private
code obtained from the db
Definition at line 54 of file TPS_PersonGroup.java.
Referenced by de.dlr.ivf.tapas.constants.TPS_PersonGroup.addPersonGroupToMap(), de.dlr.ivf.tapas.constants.TPS_PersonGroup.getCode(), de.dlr.ivf.tapas.constants.TPS_PersonGroup.getPersonGroupByCode(), and de.dlr.ivf.tapas.constants.TPS_PersonGroup.TPS_PersonGroup().
description
String de.dlr.ivf.tapas.constants.TPS_PersonGroup.description private
Definition at line 55 of file TPS_PersonGroup.java.
Referenced by de.dlr.ivf.tapas.constants.TPS_PersonGroup.getDescription(), de.dlr.ivf.tapas.constants.TPS_PersonGroup.setDescription(), and de.dlr.ivf.tapas.constants.TPS_PersonGroup.TPS_PersonGroup().
hasChildCode
TPS_HasChildCode de.dlr.ivf.tapas.constants.TPS_PersonGroup.hasChildCode private
states if there are children in the household
Definition at line 45 of file TPS_PersonGroup.java.
Referenced by de.dlr.ivf.tapas.constants.TPS_PersonGroup.getHasChildCode(), and de.dlr.ivf.tapas.constants.TPS_PersonGroup.setHasChildCode().
maxAge
int de.dlr.ivf.tapas.constants.TPS_PersonGroup.maxAge private
Definition at line 37 of file TPS_PersonGroup.java.
Referenced by de.dlr.ivf.tapas.constants.TPS_PersonGroup.getMaxAge(), and de.dlr.ivf.tapas.constants.TPS_PersonGroup.setMaxAge().
minAge
int de.dlr.ivf.tapas.constants.TPS_PersonGroup.minAge private
Definition at line 36 of file TPS_PersonGroup.java.
Referenced by de.dlr.ivf.tapas.constants.TPS_PersonGroup.getMinAge(), and de.dlr.ivf.tapas.constants.TPS_PersonGroup.setMinAge().
PERSON_GROUP_MAP
final HashMap<Integer, TPS_PersonGroup> de.dlr.ivf.tapas.constants.TPS_PersonGroup.PERSON_GROUP_MAP = new HashMap<>() static private
Definition at line 27 of file TPS_PersonGroup.java.
Referenced by de.dlr.ivf.tapas.constants.TPS_PersonGroup.addPersonGroupToMap(), de.dlr.ivf.tapas.constants.TPS_PersonGroup.clearPersonGroupMap(), de.dlr.ivf.tapas.constants.TPS_PersonGroup.getConstants(), de.dlr.ivf.tapas.constants.TPS_PersonGroup.getPersonGroupByCode(), and de.dlr.ivf.tapas.constants.TPS_PersonGroup.getPersonGroupOfPerson().
personType
TPS_PersonType de.dlr.ivf.tapas.constants.TPS_PersonGroup.personType private
Definition at line 46 of file TPS_PersonGroup.java.
Referenced by de.dlr.ivf.tapas.constants.TPS_PersonGroup.getPersonType(), and de.dlr.ivf.tapas.constants.TPS_PersonGroup.TPS_PersonGroup().
sex
TPS_Sex de.dlr.ivf.tapas.constants.TPS_PersonGroup.sex private
Sex constant; 1= male, 2 = female, 0 = not relevant
Definition at line 50 of file TPS_PersonGroup.java.
Referenced by de.dlr.ivf.tapas.constants.TPS_PersonGroup.getSex(), de.dlr.ivf.tapas.constants.TPS_PersonGroup.setSex(), and de.dlr.ivf.tapas.constants.TPS_PersonGroup.TPS_PersonGroup().
USE_GROUP_COLUMN_FOR_PERSON_GROUPS
boolean de.dlr.ivf.tapas.constants.TPS_PersonGroup.USE_GROUP_COLUMN_FOR_PERSON_GROUPS static
is set once while reading the person groups in TPS_DB_IO.readPersonGroupCodes()
Definition at line 31 of file TPS_PersonGroup.java.
Referenced by de.dlr.ivf.tapas.constants.TPS_PersonGroup.getPersonGroupOfPerson(), and de.dlr.ivf.tapas.persistence.db.TPS_DB_IO.readPersonGroupCodes().
The documentation for this class was generated from the following file:
src/main/java/de/dlr/ivf/tapas/constants/TPS_PersonGroup.java