TAPAS: de.dlr.ivf.tapas.mode.TPS_Mode.ModeType Enum Reference
de.dlr.ivf.tapas.mode.TPS_Mode.ModeType Enum Reference
Public Member Functions
ModeType (ParamValue beelineFactor)
ParamValue getBeelineFactor ()
Public Attributes
WALK =(ParamValue.BEELINE_FACTOR_FOOT)
BIKE =(ParamValue.BEELINE_FACTOR_BIKE)
MIT
MIT_PASS =(ParamValue.BEELINE_FACTOR_MIT)
TAXI
PT =(ParamValue.BEELINE_FACTOR_PT)
TRAIN =(ParamValue.BEELINE_FACTOR_PT)
Private Attributes
final ParamValue beelineFactor
Detailed Description
This enum represents all known mode types of TAPAS
Definition at line 472 of file TPS_Mode.java.
Constructor & Destructor Documentation
ModeType()
de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.ModeType (ParamValue beelineFactor)
Definition at line 480 of file TPS_Mode.java.
Member Function Documentation
getBeelineFactor()
ParamValue de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.getBeelineFactor ()
Definition at line 484 of file TPS_Mode.java.
Member Data Documentation
beelineFactor
final ParamValue de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.beelineFactor private
Definition at line 478 of file TPS_Mode.java.
BIKE
de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.BIKE =(ParamValue.BEELINE_FACTOR_BIKE)
Definition at line 474 of file TPS_Mode.java.
Referenced by de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree.applyExpertKnowledge(), de.dlr.ivf.tapas.mode.TPS_ModeDistribution.calculateDistribution(), de.dlr.ivf.tapas.mode.TPS_NonMotorisedMode.getDistance(), de.dlr.ivf.tapas.modechoice.TPS_UtilityMNL.getDistributionSet(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.getModeLogSum(), de.dlr.ivf.tapas.mode.TPS_NonMotorisedMode.getTravelTime(), de.dlr.ivf.tapas.mode.TPS_ExtMode.isBikeUsed(), de.dlr.ivf.tapas.mode.TPS_ModeSet.selectMode0(), and de.dlr.ivf.tapas.TPS_Main.updateCosts().
MIT
de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.MIT
Initial value:
=(
                ParamValue.BEELINE_FACTOR_MIT)
Definition at line 475 of file TPS_Mode.java.
Referenced by de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree.applyExpertKnowledge(), de.dlr.ivf.tapas.mode.TPS_ModeDistribution.calculateDistribution(), de.dlr.ivf.tapas.modechoice.TPS_UtilityMNL.getDistributionSet(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.getModeLogSum(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessMode.getTravelTime(), de.dlr.ivf.tapas.loc.TPS_SelectWithSingleAccessMode.getTravelTime(), de.dlr.ivf.tapas.mode.TPS_ExtMode.isCarUsed(), de.dlr.ivf.tapas.tools.TPS_ParkAndRideRouter.routePnR(), de.dlr.ivf.tapas.plan.TPS_LocatedStay.selectLocation(), de.dlr.ivf.tapas.mode.TPS_ModeSet.selectMode0(), and de.dlr.ivf.tapas.TPS_Main.updateCosts().
MIT_PASS
de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.MIT_PASS =(ParamValue.BEELINE_FACTOR_MIT)
Definition at line 475 of file TPS_Mode.java.
Referenced by de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixed.getDistributionSet(), de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixedBS.getDistributionSet(), de.dlr.ivf.tapas.modechoice.TPS_UtilityMNL.getDistributionSet(), and de.dlr.ivf.tapas.TPS_Main.updateCosts().
PT
de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.PT =(ParamValue.BEELINE_FACTOR_PT)
Definition at line 476 of file TPS_Mode.java.
Referenced by de.dlr.ivf.tapas.mode.TPS_MassTransportMode.getTravelTime(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessMode.getTravelTime(), de.dlr.ivf.tapas.tools.TPS_ParkAndRideRouter.routePnR(), de.dlr.ivf.tapas.mode.TPS_ModeSet.selectMode0(), and de.dlr.ivf.tapas.TPS_Main.updateCosts().
TAXI
de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.TAXI
Initial value:
=(
                ParamValue.BEELINE_FACTOR_MIT)
Definition at line 476 of file TPS_Mode.java.
Referenced by de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree.applyExpertKnowledge(), de.dlr.ivf.tapas.modechoice.TPS_UtilityMNL.getDistributionSet(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.getModeLogSum(), and de.dlr.ivf.tapas.TPS_Main.updateCosts().
TRAIN
de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.TRAIN =(ParamValue.BEELINE_FACTOR_PT)
Definition at line 476 of file TPS_Mode.java.
Referenced by de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixedBS.calculateDelta(), de.dlr.ivf.tapas.modechoice.TPS_UtilityChaidMNLMixedBS.getDistributionSet(), and de.dlr.ivf.tapas.TPS_Main.updateCosts().
WALK
de.dlr.ivf.tapas.mode.TPS_Mode.ModeType.WALK =(ParamValue.BEELINE_FACTOR_FOOT)
Definition at line 474 of file TPS_Mode.java.
Referenced by de.dlr.ivf.tapas.modechoice.TPS_ExpertKnowledgeTree.applyExpertKnowledge(), de.dlr.ivf.tapas.scheme.TPS_TourPart.TravelDurations.getArrivalDuration(), de.dlr.ivf.tapas.scheme.TPS_TourPart.TravelDurations.getDepartureDuration(), de.dlr.ivf.tapas.mode.TPS_NonMotorisedMode.getDistance(), de.dlr.ivf.tapas.loc.TPS_MultipleTAZRepresentant.getLocationRepresentatives(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessModeLogSum.getLogSum(), de.dlr.ivf.tapas.mode.TPS_IndividualTransportMode.getTravelTime(), de.dlr.ivf.tapas.mode.TPS_MassTransportMode.getTravelTime(), de.dlr.ivf.tapas.mode.TPS_NonMotorisedMode.getTravelTime(), de.dlr.ivf.tapas.loc.TPS_SelectWithMultipleAccessMode.getTravelTime(), de.dlr.ivf.tapas.loc.TPS_SelectWithSingleAccessMode.getTravelTime(), de.dlr.ivf.tapas.mode.TPS_ModeSet.selectMode(), de.dlr.ivf.tapas.mode.TPS_ModeSet.selectMode0(), de.dlr.ivf.tapas.scheme.TPS_TourPart.setInitialTravelDurations(), de.dlr.ivf.tapas.scheme.TPS_TourPart.updateActualTravelDistances(), and de.dlr.ivf.tapas.TPS_Main.updateCosts().
The documentation for this enum was generated from the following file:
src/main/java/de/dlr/ivf/tapas/mode/TPS_Mode.java