TAPAS: de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job Enum Reference
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job Enum Reference
Public Member Functions
Job (int id)
int getId ()
Static Public Member Functions
static Job getById (int job)
static int maxNameWidth ()
Public Attributes
JOB_1 =(1)
JOB_2 =(2)
JOB_3 =(3)
JOB_4 =(4)
JOB_5 =(5)
JOB_6 =(6)
JOB_7 =(7)
JOB_8 =(8)
JOB_9 =(9)
JOB_10 =(10)
JOB_11
JOB_12 =(12)
JOB_13 =(13)
JOB_14 =(14)
JOB_15 =(15)
JOB_16 =(16)
JOB_17 =(17)
JOB_18 =(18)
JOB_19
JOB_20 =(20)
JOB_21 =(21)
JOB_22 =(22)
JOB_23 =(23)
JOB_24 =(24)
JOB_25 =(25)
JOB_26 =(26)
JOB_27
JOB_28 =(28)
JOB_29 =(29)
JOB_30 =(30)
JOB_31 =(31)
JOB_32 =(32)
JOB_33 =(33)
JOB_34 =(34)
JOB_35
JOB_36 =(36)
JOB_37 =(37)
JOB_38 =(38)
JOB_39 =(39)
JOB_40 =(40)
JOB_41 =(41)
JOB_42 =(42)
JOB_43
JOB_44 =(44)
JOB_45 =(45)
JOB_46 =(46)
JOB_47 =(47)
JOB_48 =(48)
JOB_49 =(49)
JOB_50 =(50)
JOB_51
JOB_52 =(52)
JOB_53 =(53)
JOB_54 =(54)
JOB_55 =(55)
JOB_56 =(56)
JOB_57 =(57)
JOB_58 =(58)
JOB_59
JOB_60 =(60)
JOB_61 =(61)
JOB_62 =(62)
JOB_63 =(63)
JOB_64 =(64)
JOB_65 =(65)
Private Attributes
final int id
Detailed Description
Definition at line 859 of file TuMEnums.java.
Constructor & Destructor Documentation
Job()
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.Job (int id)
Definition at line 871 of file TuMEnums.java.
Member Function Documentation
getById()
static Job de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.getById (int job) static
Definition at line 875 of file TuMEnums.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.PersonGroupAnalyzer.assignTrip(), de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.TapasPersonGroupAnalyzer.assignTrip(), and de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.getElementById().
getId()
int de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.getId ()
Definition at line 897 of file TuMEnums.java.
maxNameWidth()
static int de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.maxNameWidth () static
Returns the maximal number of characters the names can have.
Returns
Definition at line 889 of file TuMEnums.java.
Member Data Documentation
id
final int de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.id private
Definition at line 869 of file TuMEnums.java.
JOB_1
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_1 =(1)
Definition at line 860 of file TuMEnums.java.
JOB_10
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_10 =(10)
Definition at line 860 of file TuMEnums.java.
JOB_11
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_11
Initial value:
=(
                11)
Definition at line 861 of file TuMEnums.java.
JOB_12
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_12 =(12)
Definition at line 861 of file TuMEnums.java.
JOB_13
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_13 =(13)
Definition at line 861 of file TuMEnums.java.
JOB_14
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_14 =(14)
Definition at line 861 of file TuMEnums.java.
JOB_15
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_15 =(15)
Definition at line 861 of file TuMEnums.java.
JOB_16
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_16 =(16)
Definition at line 861 of file TuMEnums.java.
JOB_17
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_17 =(17)
Definition at line 861 of file TuMEnums.java.
JOB_18
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_18 =(18)
Definition at line 861 of file TuMEnums.java.
JOB_19
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_19
Initial value:
=(
                19)
Definition at line 862 of file TuMEnums.java.
JOB_2
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_2 =(2)
Definition at line 860 of file TuMEnums.java.
JOB_20
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_20 =(20)
Definition at line 862 of file TuMEnums.java.
JOB_21
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_21 =(21)
Definition at line 862 of file TuMEnums.java.
JOB_22
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_22 =(22)
Definition at line 862 of file TuMEnums.java.
JOB_23
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_23 =(23)
Definition at line 862 of file TuMEnums.java.
JOB_24
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_24 =(24)
Definition at line 862 of file TuMEnums.java.
JOB_25
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_25 =(25)
Definition at line 862 of file TuMEnums.java.
JOB_26
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_26 =(26)
Definition at line 862 of file TuMEnums.java.
JOB_27
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_27
Initial value:
=(
                27)
Definition at line 863 of file TuMEnums.java.
JOB_28
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_28 =(28)
Definition at line 863 of file TuMEnums.java.
JOB_29
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_29 =(29)
Definition at line 863 of file TuMEnums.java.
JOB_3
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_3 =(3)
Definition at line 860 of file TuMEnums.java.
JOB_30
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_30 =(30)
Definition at line 863 of file TuMEnums.java.
JOB_31
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_31 =(31)
Definition at line 863 of file TuMEnums.java.
JOB_32
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_32 =(32)
Definition at line 863 of file TuMEnums.java.
JOB_33
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_33 =(33)
Definition at line 863 of file TuMEnums.java.
JOB_34
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_34 =(34)
Definition at line 863 of file TuMEnums.java.
JOB_35
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_35
Initial value:
=(
                35)
Definition at line 864 of file TuMEnums.java.
JOB_36
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_36 =(36)
Definition at line 864 of file TuMEnums.java.
JOB_37
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_37 =(37)
Definition at line 864 of file TuMEnums.java.
JOB_38
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_38 =(38)
Definition at line 864 of file TuMEnums.java.
JOB_39
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_39 =(39)
Definition at line 864 of file TuMEnums.java.
JOB_4
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_4 =(4)
Definition at line 860 of file TuMEnums.java.
JOB_40
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_40 =(40)
Definition at line 864 of file TuMEnums.java.
JOB_41
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_41 =(41)
Definition at line 864 of file TuMEnums.java.
JOB_42
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_42 =(42)
Definition at line 864 of file TuMEnums.java.
JOB_43
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_43
Initial value:
=(
                43)
Definition at line 865 of file TuMEnums.java.
JOB_44
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_44 =(44)
Definition at line 865 of file TuMEnums.java.
JOB_45
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_45 =(45)
Definition at line 865 of file TuMEnums.java.
JOB_46
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_46 =(46)
Definition at line 865 of file TuMEnums.java.
JOB_47
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_47 =(47)
Definition at line 865 of file TuMEnums.java.
JOB_48
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_48 =(48)
Definition at line 865 of file TuMEnums.java.
JOB_49
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_49 =(49)
Definition at line 865 of file TuMEnums.java.
JOB_5
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_5 =(5)
Definition at line 860 of file TuMEnums.java.
JOB_50
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_50 =(50)
Definition at line 865 of file TuMEnums.java.
JOB_51
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_51
Initial value:
=(
                51)
Definition at line 866 of file TuMEnums.java.
JOB_52
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_52 =(52)
Definition at line 866 of file TuMEnums.java.
JOB_53
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_53 =(53)
Definition at line 866 of file TuMEnums.java.
JOB_54
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_54 =(54)
Definition at line 866 of file TuMEnums.java.
JOB_55
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_55 =(55)
Definition at line 866 of file TuMEnums.java.
JOB_56
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_56 =(56)
Definition at line 866 of file TuMEnums.java.
JOB_57
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_57 =(57)
Definition at line 866 of file TuMEnums.java.
JOB_58
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_58 =(58)
Definition at line 866 of file TuMEnums.java.
JOB_59
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_59
Initial value:
=(
                59)
Definition at line 867 of file TuMEnums.java.
JOB_6
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_6 =(6)
Definition at line 860 of file TuMEnums.java.
JOB_60
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_60 =(60)
Definition at line 867 of file TuMEnums.java.
JOB_61
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_61 =(61)
Definition at line 867 of file TuMEnums.java.
JOB_62
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_62 =(62)
Definition at line 867 of file TuMEnums.java.
JOB_63
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_63 =(63)
Definition at line 867 of file TuMEnums.java.
JOB_64
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_64 =(64)
Definition at line 867 of file TuMEnums.java.
JOB_65
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_65 =(65)
Definition at line 867 of file TuMEnums.java.
JOB_7
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_7 =(7)
Definition at line 860 of file TuMEnums.java.
JOB_8
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_8 =(8)
Definition at line 860 of file TuMEnums.java.
JOB_9
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Job.JOB_9 =(9)
Definition at line 860 of file TuMEnums.java.
The documentation for this enum was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/tum/constants/TuMEnums.java