TAPAS: de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Mode Enum Reference
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Mode Enum Reference
Public Member Functions
Mode (int id, String description)
String getDescription ()
int getId ()
String toString ()
Static Public Member Functions
static Mode getById (int id) throws IllegalArgumentException
static int maxNameWidth ()
Public Attributes
WALK =(0, "Fuß")
BIKE =(1, "Rad")
MIV =(2, "Pkw")
MIV_PASS =(3, "PkwMf")
TAXI =(4, "Taxi")
PT =(5, "ÖV")
TRAIN
Private Attributes
final int id
final String description
Detailed Description
Definition at line 805 of file TuMEnums.java.
Constructor & Destructor Documentation
Mode()
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Mode.Mode (int id, String description)
Definition at line 812 of file TuMEnums.java.
Member Function Documentation
getById()
static Mode de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Mode.getById (int id) throws IllegalArgumentException static
Parameters
id
Returns
den Mode der dieser ID zugeordnet ist
Exceptions
IllegalArgumentException geworfen wenn die ID keinem Wegezweck zugeordnet werden konnte
Definition at line 823 of file TuMEnums.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.ModeAnalyzer.assignTrip(), de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Categories.getElementById(), and de.dlr.ivf.tapas.runtime.client.Graphics.QualityChart.ReferenceDBReader.getMoDcValues().
getDescription()
String de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Mode.getDescription ()
Definition at line 846 of file TuMEnums.java.
Referenced by de.dlr.ivf.tapas.runtime.client.Graphics.ModalSplitChart.ModalSplitChart.createToolTips().
getId()
int de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Mode.getId ()
Definition at line 850 of file TuMEnums.java.
maxNameWidth()
static int de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Mode.maxNameWidth () static
Returns the maximal number of characters the names can have.
Returns
Definition at line 838 of file TuMEnums.java.
toString()
String de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Mode.toString ()
Definition at line 854 of file TuMEnums.java.
Member Data Documentation
BIKE
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Mode.BIKE =(1, "Rad")
Definition at line 806 of file TuMEnums.java.
description
final String de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Mode.description private
Definition at line 810 of file TuMEnums.java.
id
final int de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Mode.id private
Definition at line 809 of file TuMEnums.java.
MIV
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Mode.MIV =(2, "Pkw")
Definition at line 806 of file TuMEnums.java.
MIV_PASS
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Mode.MIV_PASS =(3, "PkwMf")
Definition at line 806 of file TuMEnums.java.
PT
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Mode.PT =(5, "ÖV")
Definition at line 806 of file TuMEnums.java.
TAXI
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Mode.TAXI =(4, "Taxi")
Definition at line 806 of file TuMEnums.java.
TRAIN
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Mode.TRAIN
Initial value:
=(6,
                "Zug")
Definition at line 807 of file TuMEnums.java.
WALK
de.dlr.ivf.tapas.analyzer.tum.constants.TuMEnums.Mode.WALK =(0, "Fuß")
Definition at line 806 of file TuMEnums.java.
The documentation for this enum was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/tum/constants/TuMEnums.java