TAPAS: de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState Enum Reference
de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState Enum Reference
Public Member Functions
TPS_SimulationState (int value)
String getAction ()
void setAction (String string)
Static Public Member Functions
static TPS_SimulationState getState (SimulationData simulation)
Public Attributes
FINISHED =(3)
INSERTED =(0)
STOPPED =(1)
STARTED =(2)
Private Attributes
String action
final int value
Detailed Description
Possible states of a simulation. Each state holds an action string and a hierarchy value. The action string tells which is the next possible action with a simulation in this state, e.g. READY -> "Start". The hierarchy value is used for detecting the progress of the simulation.
Author
mark_ma
Definition at line 370 of file SimulationData.java.
Constructor & Destructor Documentation
TPS_SimulationState()
de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState.TPS_SimulationState (int value)
Constructor initialises members.
Parameters
value hierarchy value
Definition at line 402 of file SimulationData.java.
Member Function Documentation
getAction()
String de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState.getAction ()
Returns
action string
Definition at line 427 of file SimulationData.java.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.SimulationTableModel.SimulationList.get(), and de.dlr.ivf.tapas.runtime.client.SimulationMonitor.updateSimulationData().
getState()
static TPS_SimulationState de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState.getState (SimulationData simulation) static
Parameters
simulation simulation to get the state of
Returns
state of the current simulation
Definition at line 412 of file SimulationData.java.
References de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState.FINISHED, de.dlr.ivf.tapas.runtime.server.SimulationData.getProgress(), de.dlr.ivf.tapas.runtime.server.SimulationData.getTotal(), de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState.INSERTED, de.dlr.ivf.tapas.runtime.server.SimulationData.sim_finished, de.dlr.ivf.tapas.runtime.server.SimulationData.sim_ready, de.dlr.ivf.tapas.runtime.server.SimulationData.sim_started, de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState.STARTED, and de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState.STOPPED.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationControl.changeSimulationDataState(), and de.dlr.ivf.tapas.runtime.server.SimulationData.getState().
setAction()
void de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState.setAction (String string)
Definition at line 431 of file SimulationData.java.
Member Data Documentation
action
String de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState.action private
Possible action the this state. This action string can be shown in a GUI.
Definition at line 391 of file SimulationData.java.
FINISHED
de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState.FINISHED =(3)
The simulation is stopped and all households are simulated
Definition at line 374 of file SimulationData.java.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitor.addSimulation(), de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.SimulationTableModel.SimulationList.get(), de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.getRowFromSimulation(), de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState.getState(), de.dlr.ivf.tapas.runtime.server.SimulationData.isFinished(), de.dlr.ivf.tapas.runtime.client.SimulationMonitor.SimulationMonitor(), and de.dlr.ivf.tapas.runtime.client.SimulationMonitor.updateSimulationData().
INSERTED
de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState.INSERTED =(0)
The simulation is added to the database but is not ready to start
Definition at line 378 of file SimulationData.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState.getState(), and de.dlr.ivf.tapas.runtime.client.SimulationMonitor.SimulationMonitor().
STARTED
de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState.STARTED =(2)
The simulation is started and not finished
Definition at line 386 of file SimulationData.java.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitor.addSimulation(), de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.SimulationTableModel.SimulationList.get(), de.dlr.ivf.tapas.runtime.server.SimulationData.getElapsedTime(), de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.getRowFromSimulation(), de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState.getState(), de.dlr.ivf.tapas.runtime.server.SimulationData.isStarted(), de.dlr.ivf.tapas.runtime.client.SimulationMonitor.SimulationMonitor(), and de.dlr.ivf.tapas.runtime.client.SimulationMonitor.updateSimulationData().
STOPPED
de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState.STOPPED =(1)
The simulation is ready to start
Definition at line 382 of file SimulationData.java.
Referenced by de.dlr.ivf.tapas.runtime.client.SimulationMonitor.addSimulation(), de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.SimulationTableModel.SimulationList.get(), de.dlr.ivf.tapas.runtime.client.SimulationMonitorPanel.getRowFromSimulation(), de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState.getState(), de.dlr.ivf.tapas.runtime.server.SimulationData.isReady(), de.dlr.ivf.tapas.runtime.client.SimulationMonitor.SimulationMonitor(), and de.dlr.ivf.tapas.runtime.client.SimulationMonitor.updateSimulationData().
value
final int de.dlr.ivf.tapas.runtime.server.SimulationData.TPS_SimulationState.value private
Hierarchy value of the state
Definition at line 395 of file SimulationData.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationData.higherState(), and de.dlr.ivf.tapas.runtime.server.SimulationData.minimumState().
The documentation for this enum was generated from the following file:
src/main/java/de/dlr/ivf/tapas/runtime/server/SimulationData.java