TAPAS: de.dlr.ivf.tapas.runtime.server.SimulationServerData.HashStatus Enum Reference
de.dlr.ivf.tapas.runtime.server.SimulationServerData.HashStatus Enum Reference
Public Member Functions
HashStatus (int status)
int getValue ()
Public Attributes
UNKNOWN =(-2)
INVALID =(-1)
NON_DOMINANT =(0)
DOMINANT =(1)
DEBUG =(2)
Private Attributes
final int status
Detailed Description
Definition at line 275 of file SimulationServerData.java.
Constructor & Destructor Documentation
HashStatus()
de.dlr.ivf.tapas.runtime.server.SimulationServerData.HashStatus.HashStatus (int status)
Definition at line 281 of file SimulationServerData.java.
Member Function Documentation
getValue()
int de.dlr.ivf.tapas.runtime.server.SimulationServerData.HashStatus.getValue ()
Definition at line 285 of file SimulationServerData.java.
Member Data Documentation
DEBUG
de.dlr.ivf.tapas.runtime.server.SimulationServerData.HashStatus.DEBUG =(2)
Definition at line 277 of file SimulationServerData.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationServerData.setServerProcessInfo().
DOMINANT
de.dlr.ivf.tapas.runtime.server.SimulationServerData.HashStatus.DOMINANT =(1)
Definition at line 277 of file SimulationServerData.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationServerData.setServerProcessInfo().
INVALID
de.dlr.ivf.tapas.runtime.server.SimulationServerData.HashStatus.INVALID =(-1)
Definition at line 277 of file SimulationServerData.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationServerData.setServerProcessInfo().
NON_DOMINANT
de.dlr.ivf.tapas.runtime.server.SimulationServerData.HashStatus.NON_DOMINANT =(0)
Definition at line 277 of file SimulationServerData.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationServerData.setServerProcessInfo().
status
final int de.dlr.ivf.tapas.runtime.server.SimulationServerData.HashStatus.status private
Definition at line 279 of file SimulationServerData.java.
UNKNOWN
de.dlr.ivf.tapas.runtime.server.SimulationServerData.HashStatus.UNKNOWN =(-2)
Definition at line 277 of file SimulationServerData.java.
Referenced by de.dlr.ivf.tapas.runtime.server.SimulationServerData.setServerProcessInfo(), de.dlr.ivf.tapas.runtime.server.SimulationServerData.SimulationServerData(), and de.dlr.ivf.tapas.runtime.server.SimulationServerData.update().
The documentation for this enum was generated from the following file:
src/main/java/de/dlr/ivf/tapas/runtime/server/SimulationServerData.java