TAPAS: de.dlr.ivf.tapas.analyzer.inputfileconverter.DistanceCategory Enum Reference
de.dlr.ivf.tapas.analyzer.inputfileconverter.DistanceCategory Enum Reference
Public Member Functions
DistanceCategory (int id, double maxDistance, String description)
String getDescription ()
int getId ()
Static Public Member Functions
static String createDistanceCategoriesID (List< DistanceCategory > categories)
static String createDistanceCategoriesName (List< DistanceCategory > categories)
static DistanceCategory getByDistance (double dist)
static DistanceCategory getById (int id) throws IllegalArgumentException
Public Attributes
CAT_1 =(0, 1000, "< 1 km")
CAT_2 =(1, 3000, "1-3 km")
CAT_3 =(2, 5000, "3-5 km")
CAT_4 =(3, 7000, "5-7 km")
CAT_5
CAT_6 =(5, 25000, "10-25 km")
CAT_7 =(6, 100000, "25-100 km")
CAT_8
Protected Member Functions
double getMaxDistance ()
Private Attributes
final int id
final double maxDistance
final String description
Detailed Description
Definition at line 13 of file DistanceCategory.java.
Constructor & Destructor Documentation
DistanceCategory()
de.dlr.ivf.tapas.analyzer.inputfileconverter.DistanceCategory.DistanceCategory (int id, double maxDistance, String description)
Parameters
id die ID der Kategorie
maxDistance die maximale Distanz (ausschließlich, der angegebene Wert ist nicht mehr gültig)
Definition at line 26 of file DistanceCategory.java.
Member Function Documentation
createDistanceCategoriesID()
static String de.dlr.ivf.tapas.analyzer.inputfileconverter.DistanceCategory.createDistanceCategoriesID (List< DistanceCategory > categories) static
Erzeugt aus den DistanceCategory einen einheitlichen Namen. z.B. Wird aus DistanceCategory#CAT_2 und DistanceCategory#CAT_3 = 1-5 km
Parameters
categories
Returns
Definition at line 40 of file DistanceCategory.java.
References categories.
createDistanceCategoriesName()
static String de.dlr.ivf.tapas.analyzer.inputfileconverter.DistanceCategory.createDistanceCategoriesName (List< DistanceCategory > categories) static
Erzeugt aus den DistanceCategory einen einheitlichen Namen. z.B. Wird aus DistanceCategory#CAT_2 und DistanceCategory#CAT_3 = 1-5 km
Parameters
categories Elemente müssen aufsteigend sortiert sein
Returns
Definition at line 54 of file DistanceCategory.java.
References de.dlr.ivf.tapas.analyzer.inputfileconverter.DistanceCategory.CAT_1, de.dlr.ivf.tapas.analyzer.inputfileconverter.DistanceCategory.CAT_8, and categories.
Referenced by de.dlr.ivf.tapas.analyzer.core.TapasChartFactory.createModalSplitDistanceCategorySeparated(), and de.dlr.ivf.tapas.analyzer.core.TapasChartFactory.createModalSplitTripIntentionDistanceCategorySeparated().
getByDistance()
static DistanceCategory de.dlr.ivf.tapas.analyzer.inputfileconverter.DistanceCategory.getByDistance (double dist) static
Parameters
dist
Returns
die DistanceCategory dessen obere Distanzgrenze am nächsten an der angebenen größe ist und gleichzeitig größer als die angebene ist. Sollte keine DistanceCategory eine größere Distance haben wird immer die größte zurückgegeben.
Definition at line 76 of file DistanceCategory.java.
getById()
static DistanceCategory de.dlr.ivf.tapas.analyzer.inputfileconverter.DistanceCategory.getById (int id) throws IllegalArgumentException static
Parameters
id
Returns
die DistanceCategory die die angegebene ID besitzt
Exceptions
IllegalArgumentException wenn die ID keiner Kategorie zugeordnet werden kann
Definition at line 90 of file DistanceCategory.java.
getDescription()
String de.dlr.ivf.tapas.analyzer.inputfileconverter.DistanceCategory.getDescription ()
Definition at line 99 of file DistanceCategory.java.
getId()
int de.dlr.ivf.tapas.analyzer.inputfileconverter.DistanceCategory.getId ()
Definition at line 103 of file DistanceCategory.java.
Referenced by de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getModalSplitForDistanceCategory(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getModalSplitForDistanceCategoryAbs(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getModalSplitForDistanceCategoryAndTripIntention(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getModalSplitForDistanceCategoryTripIntentionAbs(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getPercentageOfTriplengthAllocationForDistanceCategory(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getPercentageOfTriplengthAllocationForDistanceCategoryAndMode(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getPercentageOfTriplengthAllocationForDistanceCategoryAndTripIntention(), de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getPercentageOfTriplengthAllocationForDistanceCategoryAndTripIntentionAndPersonGroupTAPAS(), and de.dlr.ivf.tapas.analyzer.tum.RegionPOJO.getPercentageOfTriplengthAllocationForDistanceCategoryAndTripIntentionAndPersonGroupViseva().
getMaxDistance()
double de.dlr.ivf.tapas.analyzer.inputfileconverter.DistanceCategory.getMaxDistance () protected
Definition at line 107 of file DistanceCategory.java.
Member Data Documentation
CAT_1
de.dlr.ivf.tapas.analyzer.inputfileconverter.DistanceCategory.CAT_1 =(0, 1000, "< 1 km")
Definition at line 14 of file DistanceCategory.java.
Referenced by de.dlr.ivf.tapas.analyzer.inputfileconverter.DistanceCategory.createDistanceCategoriesName().
CAT_2
de.dlr.ivf.tapas.analyzer.inputfileconverter.DistanceCategory.CAT_2 =(1, 3000, "1-3 km")
Definition at line 14 of file DistanceCategory.java.
CAT_3
de.dlr.ivf.tapas.analyzer.inputfileconverter.DistanceCategory.CAT_3 =(2, 5000, "3-5 km")
Definition at line 14 of file DistanceCategory.java.
CAT_4
de.dlr.ivf.tapas.analyzer.inputfileconverter.DistanceCategory.CAT_4 =(3, 7000, "5-7 km")
Definition at line 14 of file DistanceCategory.java.
CAT_5
de.dlr.ivf.tapas.analyzer.inputfileconverter.DistanceCategory.CAT_5
Initial value:
=(4,
            10000, "7-10 km")
Definition at line 15 of file DistanceCategory.java.
CAT_6
de.dlr.ivf.tapas.analyzer.inputfileconverter.DistanceCategory.CAT_6 =(5, 25000, "10-25 km")
Definition at line 15 of file DistanceCategory.java.
CAT_7
de.dlr.ivf.tapas.analyzer.inputfileconverter.DistanceCategory.CAT_7 =(6, 100000, "25-100 km")
Definition at line 15 of file DistanceCategory.java.
CAT_8
de.dlr.ivf.tapas.analyzer.inputfileconverter.DistanceCategory.CAT_8
Initial value:
=(7, Double.MAX_VALUE,
            ">=100 km")
Definition at line 16 of file DistanceCategory.java.
Referenced by de.dlr.ivf.tapas.analyzer.inputfileconverter.DistanceCategory.createDistanceCategoriesName().
description
final String de.dlr.ivf.tapas.analyzer.inputfileconverter.DistanceCategory.description private
Definition at line 20 of file DistanceCategory.java.
id
final int de.dlr.ivf.tapas.analyzer.inputfileconverter.DistanceCategory.id private
Definition at line 18 of file DistanceCategory.java.
maxDistance
final double de.dlr.ivf.tapas.analyzer.inputfileconverter.DistanceCategory.maxDistance private
Definition at line 19 of file DistanceCategory.java.
The documentation for this enum was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/inputfileconverter/DistanceCategory.java