TAPAS: de.dlr.ivf.tapas.tools.matrixMap.Modus Enum Reference
de.dlr.ivf.tapas.tools.matrixMap.Modus Enum Reference
Public Member Functions
Modus (double correctionFactor, int value, String name)
double getCorrectionFactor ()
String getName ()
int getValue ()
Public Attributes
WALK =(0.15, 0, "WALK")
BIKE =(0.145, 1, "BIKE")
PT =(0.670, 2, "PT")
MIV =(0.480, 3, "MIV")
Private Attributes
final double correctionFactor
final int value
final String name
Detailed Description
Author
Holger Siedel
Definition at line 14 of file Modus.java.
Constructor & Destructor Documentation
Modus()
de.dlr.ivf.tapas.tools.matrixMap.Modus.Modus (double correctionFactor, int value, String name)
Definition at line 23 of file Modus.java.
References name.
Member Function Documentation
getCorrectionFactor()
double de.dlr.ivf.tapas.tools.matrixMap.Modus.getCorrectionFactor ()
Definition at line 29 of file Modus.java.
getName()
String de.dlr.ivf.tapas.tools.matrixMap.Modus.getName ()
Definition at line 33 of file Modus.java.
References name.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.start(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.start().
getValue()
int de.dlr.ivf.tapas.tools.matrixMap.Modus.getValue ()
Definition at line 37 of file Modus.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.getTravelTime().
Member Data Documentation
BIKE
de.dlr.ivf.tapas.tools.matrixMap.Modus.BIKE =(0.145, 1, "BIKE")
Definition at line 17 of file Modus.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedGUI.cbBikeDistItemStateChanged(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedGUI.cbBikeTTItemStateChanged(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.init(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.readProperties(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.writeStatisticsToCVS().
correctionFactor
final double de.dlr.ivf.tapas.tools.matrixMap.Modus.correctionFactor private
Definition at line 19 of file Modus.java.
MIV
de.dlr.ivf.tapas.tools.matrixMap.Modus.MIV =(0.480, 3, "MIV")
Definition at line 17 of file Modus.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedGUI.cbMIVDistItemStateChanged(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedGUI.cbMIVTTItemStateChanged(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.init(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.readProperties(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.writeStatisticsToCVS().
name
final String de.dlr.ivf.tapas.tools.matrixMap.Modus.name private
Definition at line 21 of file Modus.java.
PT
de.dlr.ivf.tapas.tools.matrixMap.Modus.PT =(0.670, 2, "PT")
Definition at line 17 of file Modus.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedGUI.cbPTDistItemStateChanged(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedGUI.cbPTTTItemStateChanged(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.init(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.readProperties(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.writeStatisticsToCVS().
value
final int de.dlr.ivf.tapas.tools.matrixMap.Modus.value private
Definition at line 20 of file Modus.java.
WALK
de.dlr.ivf.tapas.tools.matrixMap.Modus.WALK =(0.15, 0, "WALK")
Definition at line 17 of file Modus.java.
Referenced by de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedGUI.cbWalkDistItemStateChanged(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedGUI.cbWalkTTItemStateChanged(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedCalculate.init(), de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeed.readProperties(), and de.dlr.ivf.tapas.tools.matrixMap.CruisingSpeedValidate.writeStatisticsToCVS().
The documentation for this enum was generated from the following file:
src/main/java/de/dlr/ivf/tapas/tools/matrixMap/Modus.java