TAPAS: de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripReader Interface Reference
de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripReader Interface Reference
Public Member Functions
void close ()
Iterator< TapasTrip > getIterator ()
int getProgress ()
String getSource ()
long getTotal ()
Detailed Description
Definition at line 13 of file TapasTripReader.java.
Member Function Documentation
close()
void de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripReader.close ()
Implemented in de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader, and de.dlr.ivf.tapas.analyzer.inputfileconverter.FileTripReader.
Referenced by de.dlr.ivf.tapas.analyzer.gui.Control.createAndShowGUI().
getIterator()
Iterator<TapasTrip> de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripReader.getIterator ()
Implemented in de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader, and de.dlr.ivf.tapas.analyzer.inputfileconverter.FileTripReader.
Referenced by de.dlr.ivf.tapas.analyzer.core.Core.run().
getProgress()
int de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripReader.getProgress ()
Returns an estimated progress between 0 and 100
Implemented in de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader, and de.dlr.ivf.tapas.analyzer.inputfileconverter.FileTripReader.
Referenced by de.dlr.ivf.tapas.analyzer.gui.Control.actionPerformed().
getSource()
String de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripReader.getSource ()
Returns
a human readable description of the source of the trips.
Implemented in de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader, and de.dlr.ivf.tapas.analyzer.inputfileconverter.FileTripReader.
Referenced by de.dlr.ivf.tapas.analyzer.core.Core.run().
getTotal()
long de.dlr.ivf.tapas.analyzer.inputfileconverter.TapasTripReader.getTotal ()
Returns
(estimated) number of elements to be read.
Implemented in de.dlr.ivf.tapas.analyzer.tum.databaseConnector.DBTripReader, and de.dlr.ivf.tapas.analyzer.inputfileconverter.FileTripReader.
The documentation for this interface was generated from the following file:
src/main/java/de/dlr/ivf/tapas/analyzer/inputfileconverter/TapasTripReader.java