TAPAS: de.dlr.ivf.tapas.loc.Locatable Interface Reference
de.dlr.ivf.tapas.loc.Locatable Interface Reference
Public Member Functions
TPS_Block getBlock ()
TPS_Coordinate getCoordinate ()
int getTAZId ()
TPS_TrafficAnalysisZone getTrafficAnalysisZone ()
boolean hasBlock ()
Detailed Description
Generic interface for all entities which are located in an coordinate system. These entities are numbered by an identifier and have a single coordinate to determine their location.
Author
mark_ma
Definition at line 21 of file Locatable.java.
Member Function Documentation
getBlock()
TPS_Block de.dlr.ivf.tapas.loc.Locatable.getBlock ()
Implemented in de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone, and de.dlr.ivf.tapas.loc.TPS_Location.
Referenced by de.dlr.ivf.tapas.mode.TPS_MassTransportMode.getTravelTime().
getCoordinate()
TPS_Coordinate de.dlr.ivf.tapas.loc.Locatable.getCoordinate ()
Returns
coordinate
Implemented in de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone, and de.dlr.ivf.tapas.loc.TPS_Location.
Referenced by de.dlr.ivf.tapas.util.TPS_Geometrics.getDistance().
getTAZId()
int de.dlr.ivf.tapas.loc.Locatable.getTAZId ()
Returns
identifier of according
Implemented in de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone, and de.dlr.ivf.tapas.loc.TPS_Location.
Referenced by de.dlr.ivf.tapas.mode.TPS_MassTransportMode.getInterchanges(), and de.dlr.ivf.tapas.mode.TPS_IndividualTransportMode.getTravelTime().
getTrafficAnalysisZone()
TPS_TrafficAnalysisZone de.dlr.ivf.tapas.loc.Locatable.getTrafficAnalysisZone ()
Implemented in de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone, and de.dlr.ivf.tapas.loc.TPS_Location.
Referenced by de.dlr.ivf.tapas.mode.TPS_IndividualTransportMode.getDistance(), de.dlr.ivf.tapas.mode.TPS_MassTransportMode.getDistance(), de.dlr.ivf.tapas.mode.TPS_NonMotorisedMode.getDistance(), de.dlr.ivf.tapas.util.TPS_Geometrics.getDistance(), de.dlr.ivf.tapas.mode.TPS_IndividualTransportMode.getTravelTime(), de.dlr.ivf.tapas.mode.TPS_MassTransportMode.getTravelTime(), and de.dlr.ivf.tapas.mode.TPS_NonMotorisedMode.getTravelTime().
hasBlock()
boolean de.dlr.ivf.tapas.loc.Locatable.hasBlock ()
Implemented in de.dlr.ivf.tapas.loc.TPS_TrafficAnalysisZone, and de.dlr.ivf.tapas.loc.TPS_Location.
Referenced by de.dlr.ivf.tapas.mode.TPS_MassTransportMode.getTravelTime().
The documentation for this interface was generated from the following file:
src/main/java/de/dlr/ivf/tapas/loc/Locatable.java